import { Spot } from "@/types/spot";

export const chubuSpots: Spot[] = [
  // ── 新潟 ──────────────────────────────────────
  {
    id: "yahiko-shrine", title: "弥彦神社", location: "西蒲原郡弥彦村",
    prefecture: "新潟県", prefectureId: "niigata", area: "弥彦", areaId: "yahiko-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "越後一宮の格。杉並木の参道が、神域へ誘う。",
    longDescription: "弥彦神社は越後の国一宮として、古代から人々の信仰を集めてきた。大鳥居をくぐると、樹齢数百年の杉並木が続く参道が始まる。境内は本殿を中心に広大な敷地を持ち、背後には弥彦山がそびえる。山頂へのロープウェイからは越後平野と日本海を一望できる。11月の菊まつりは県内屈指の規模で、境内が色とりどりの菊に埋め尽くされる。元旦の初詣は県内最多の参拝者が訪れる。",
    tags: ["神社", "一宮", "紅葉", "初詣", "歴史"],
    stayDuration: 90, bestTime: "朝 8:00〜10:00", crowdLevel: "medium",
    budget: "無料", access: "JR弥彦線 弥彦駅から徒歩10分", rainyDay: false,
    highlights: ["杉並木参道", "弥彦山ロープウェイ", "菊まつり"],
    features: [
      { label: "杉並木参道", text: "大鳥居から本殿まで続く杉並木。朝の空気が清澄で気持ちいい。" },
      { label: "弥彦山頂展望台", text: "ロープウェイで山頂へ。越後平野と日本海の絶景が広がる。" },
      { label: "彌彦公園の紅葉", text: "11月の紅葉は境内と合わせて歩くと、色彩の密度が高い。" },
    ],
    nearby: ["kiyotsu-gorge"],
  },
  {
    id: "kiyotsu-gorge", title: "清津峡", location: "十日町市",
    prefecture: "新潟県", prefectureId: "niigata", area: "十日町", areaId: "tokamachi-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "岩の間に光が差し込む。日本三大峡谷の、現代アートな終着点。",
    longDescription: "清津峡は日本三大峡谷のひとつ。トンネルを歩いて進むと、三か所のパノラマステーションから峡谷を見渡せる。最奥部のトンネル終端は、水盤を設けたインスタレーション「Tunnel of Light」として大地の芸術祭以来世界的に知られる。水面に映る峡谷と空のリフレクションは、人間が作った風景でありながら自然を超えた美しさがある。秋の紅葉と水鏡の組み合わせが最高潮を迎える。",
    tags: ["峡谷", "アート", "紅葉", "写真映え", "大地の芸術祭"],
    stayDuration: 90, bestTime: "午前中（光の角度が最良）", crowdLevel: "medium",
    budget: "¥800", access: "越後湯沢駅からバスで30分、徒歩10分", rainyDay: false,
    highlights: ["Tunnel of Light", "パノラマステーション", "柱状節理の岸壁"],
    features: [
      { label: "水盤のリフレクション", text: "終端の水鏡に映る峡谷。この一枚のために来る人が多い。" },
      { label: "柱状節理", text: "六角形の岩が積み重なる自然造形。地球の力を感じる。" },
    ],
    nearby: ["yahiko-shrine", "nagaoka-fireworks"],
  },
  {
    id: "nagaoka-fireworks", title: "長岡花火", location: "長岡市",
    prefecture: "新潟県", prefectureId: "niigata", area: "長岡", areaId: "nagaoka-area",
    category: "experience",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "日本三大花火の頂点。鎮魂と復興の花火は、他の花火と意味が違う。",
    longDescription: "長岡まつり大花火大会は毎年8月2・3日に信濃川河川敷で開催される。戦災・水害からの復興を祈念して始まった花火は、単なる祭りを超えた鎮魂の意味を持つ。三尺玉の爆発音は腹の底まで響き、正三尺玉は打ち上げ花火の中で最大規模を誇る。「フェニックス」と呼ばれる超大型ナイアガラは、2kmに渡る信濃川の空を火の鳥が飛翔する。開催前日からの混雑を計算に入れた宿泊計画が必須。",
    tags: ["花火", "夏祭り", "長岡", "鎮魂", "体験"],
    stayDuration: 240, bestTime: "8月2〜3日（本番）", crowdLevel: "high",
    budget: "¥4,000〜（有料観覧席）", access: "JR長岡駅から徒歩20分", rainyDay: false,
    highlights: ["三尺玉", "フェニックス花火", "正三尺玉"],
    features: [
      { label: "フェニックス花火", text: "信濃川全体を使う超大型演出。音と光で肌が震える。" },
      { label: "三尺玉", text: "直径540mに広がる打ち上げ花火。腹に響く爆発音が名物。" },
    ],
    nearby: ["kiyotsu-gorge"],
  },

  // ── 富山 ──────────────────────────────────────
  {
    id: "kurobe-dam", title: "黒部ダム", location: "中新川郡立山町",
    prefecture: "富山県", prefectureId: "toyama", area: "立山黒部", areaId: "tateyama-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "220mの堤高。放水の轟音が、山肌をつたう。",
    longDescription: "黒部ダムは立山黒部アルペンルートの核心地点。電源開発のために建設された高さ186mのアーチ式ドーム越流型ダムは、建設工事の過酷さで知られる。毎秒10〜15トンの水が放流される観光放水（6〜10月）は圧巻。ダム堤上から見る黒部湖の水色は、周囲の峰々と対照的に鮮やかに輝く。観光放水期間中は虹が出現することも多い。立山室堂や雪の大谷と組み合わせた1泊2日ルートが王道。",
    tags: ["ダム", "絶景", "立山", "アルペンルート", "夏"],
    stayDuration: 120, bestTime: "6〜10月（観光放水期間）", crowdLevel: "medium",
    budget: "¥2,000〜（ルート交通費別）", access: "信濃大町駅から関電トンネルバスで40分", rainyDay: false,
    highlights: ["観光放水", "黒部湖遊覧船", "展望台からの眺め"],
    features: [
      { label: "観光放水", text: "毎秒10トンの放水。霧状のしぶきが虹を作ることがある。" },
      { label: "黒部湖の碧", text: "標高1470mに広がる人造湖。空と山の色を水面が映す。" },
    ],
    nearby: ["amaharashi-coast"],
  },
  {
    id: "amaharashi-coast", title: "雨晴海岸", location: "高岡市",
    prefecture: "富山県", prefectureId: "toyama", area: "高岡", areaId: "takaoka-area",
    category: "beach",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "富山湾越しに立山連峰が浮かぶ。日本で最も贅沢な海の風景。",
    longDescription: "雨晴海岸は富山湾越しに3000m級の立山連峰を望む日本有数の絶景海岸。晴天の日、海面の向こうに雪を纏った北アルプスがそびえる景色は「富山が世界に誇る風景」と呼ばれる。義経が源氏追討の際に雨宿りした「義経岩」が名前の由来。日の出の時間帯、空がオレンジに染まる中に山の白が浮かぶ瞬間は唯一無二。道の駅雨晴では浜揚げ直送の新鮮な魚介が食べられる。",
    tags: ["海岸", "絶景", "立山連峰", "日の出", "写真映え"],
    stayDuration: 60, bestTime: "早朝（日の出前後）・冬の晴天日", crowdLevel: "low",
    budget: "無料", access: "あいの風とやま鉄道 雨晴駅から徒歩5分", rainyDay: false,
    highlights: ["立山連峰の眺望", "義経岩", "道の駅雨晴"],
    features: [
      { label: "立山連峰の眺望", text: "海と雪山の組み合わせ。冬から春が最も鮮明に見える。" },
      { label: "日の出の時間", text: "海面を染める朝日と山の白。三脚を立てて待つ価値がある。" },
    ],
    nearby: ["gokayama-gassho"],
  },
  {
    id: "gokayama-gassho", title: "五箇山合掌造り", location: "南砺市",
    prefecture: "富山県", prefectureId: "toyama", area: "五箇山", areaId: "gokayama-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "白川郷より静か。雪に埋まった合掌造りは、世界遺産の孤高がある。",
    longDescription: "五箇山の合掌造り集落（相倉・菅沼）はユネスコ世界遺産。白川郷よりも観光客が少なく、静かに集落を歩ける。冬の積雪期は合掌屋根が白く染まり、厳しい山村の原風景が現れる。囲炉裏を囲む古民家の宿に泊まると、夜の集落は街灯もなく星空だけが広がる。塩硝（火薬の原料）製造で外界と隔絶されながら独自文化を育てた歴史が、この集落の重みになっている。",
    tags: ["世界遺産", "合掌造り", "冬景色", "古民家", "秘境"],
    stayDuration: 120, bestTime: "冬（雪景色）・早朝", crowdLevel: "low",
    budget: "無料（集落見学）", access: "高岡駅から城端バスで約1時間", rainyDay: false,
    highlights: ["相倉集落", "菅沼集落", "冬のライトアップ"],
    features: [
      { label: "相倉集落", text: "23棟の合掌造りが現存。宿泊可能な民家もあり、夜の静けさが本物。" },
      { label: "冬のライトアップ", text: "雪原に浮かぶ合掌屋根。夜の寒さと引き換えに非日常がある。" },
    ],
    nearby: ["shirakawa-go"],
  },

  // ── 石川 ──────────────────────────────────────
  {
    id: "kenroku-en", title: "兼六園", location: "金沢市",
    prefecture: "石川県", prefectureId: "ishikawa", area: "金沢", areaId: "kanazawa-area",
    category: "park",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "日本三名園の筆頭。雪吊りの冬が、兼六園の本当の季節。",
    longDescription: "兼六園は水戸偕楽園・岡山後楽園と並ぶ日本三名園のひとつ。「兼六」の名は「宏大・幽邃・人力・蒼古・水泉・眺望」の六勝を兼ね備えることに由来する。冬の雪吊りは11月初旬から始まり、松の枝を縄で吊る独特の景観を作り出す。ことじ灯籠と霞が池を入れた構図は日本庭園の象徴的写真として世界的に知られる。早朝7時の開園直後（無料）に入ると、ほぼ独占状態で歩ける。",
    tags: ["庭園", "名園", "金沢", "雪吊り", "早朝"],
    stayDuration: 90, bestTime: "早朝（7時〜8時）・冬の雪吊り期", crowdLevel: "medium",
    budget: "¥320（早朝無料時間あり）", access: "JR金沢駅からバスで20分", rainyDay: false,
    highlights: ["ことじ灯籠", "雪吊り", "霞が池"],
    features: [
      { label: "ことじ灯籠", text: "霞が池畔の二本脚の灯籠。兼六園を代表する構図。" },
      { label: "雪吊り", text: "11月から始まる縄掛け作業。冬の金沢の象徴的な光景。" },
      { label: "早朝無料開放", text: "3月〜10月の早朝7時から8時は無料。静かに歩ける至福の時間。" },
    ],
    nearby: ["higashi-chaya", "omicho-market"],
  },
  {
    id: "higashi-chaya", title: "ひがし茶屋街", location: "金沢市",
    prefecture: "石川県", prefectureId: "ishikawa", area: "金沢", areaId: "kanazawa-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "格子戸の向こうに三味線の音。加賀百万石の花街が、今も息づく。",
    longDescription: "ひがし茶屋街は江戸時代に加賀藩が公認した茶屋（置屋）街。石畳と紅殻格子の町家が続く通りは、国の重要伝統的建造物群保存地区に指定されている。今も現役のお茶屋が数軒残り、一見さんでも昼間の観覧が可能な施設もある。箔一・中島めんや・箸专などの老舗が並ぶ通りを歩くと、金沢の工芸文化が凝縮される。夕暮れ後は人が引き、格子窓に明かりが入る静かな風景が現れる。",
    tags: ["茶屋街", "金沢", "伝統", "街歩き", "工芸"],
    stayDuration: 60, bestTime: "夕方（格子に灯りが入る時間）", crowdLevel: "medium",
    budget: "無料（見学）", access: "JR金沢駅からバスで15分", rainyDay: false,
    highlights: ["紅殻格子の町家", "箔一 本店", "お茶屋見学"],
    features: [
      { label: "紅殻格子", text: "赤い塗料を塗った格子窓。茶屋街の美意識を象徴する建築要素。" },
      { label: "金箔工芸", text: "箔一では金箔アイスや金箔押し体験が楽しめる。" },
    ],
    nearby: ["kenroku-en", "omicho-market"],
  },
  {
    id: "omicho-market", title: "近江町市場", location: "金沢市",
    prefecture: "石川県", prefectureId: "ishikawa", area: "金沢", areaId: "kanazawa-area",
    category: "market",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "金沢市民の台所。ノドグロとカニが、威勢よく並ぶ朝の市場。",
    longDescription: "近江町市場は280年以上の歴史を持つ金沢市民の食文化の中心地。約180の店舗が軒を連ね、日本海の新鮮な魚介類をはじめ地野菜・金沢の食品が集まる。冬はずわい蟹、夏はのど黒と、季節ごとの旬がそのまま並ぶ。市場内の食堂で食べる海鮮丼は、石川県で最もコストパフォーマンスが高い食事のひとつ。朝8時台に入ると、地元の料理人が仕入れる様子を間近で見られる。",
    tags: ["市場", "海鮮", "金沢", "グルメ", "朝"],
    stayDuration: 60, bestTime: "朝 8:00〜10:00", crowdLevel: "medium",
    budget: "¥1,500〜（海鮮丼）", access: "JR金沢駅から徒歩15分", rainyDay: true,
    highlights: ["のど黒", "ずわい蟹", "海鮮丼"],
    features: [
      { label: "海鮮丼", text: "市場内の食堂はどこも新鮮。のど黒丼は金沢に来たら必食。" },
      { label: "朝の仕入れ", text: "8時台は料理人が仕入れる時間。本物の市場の活気がある。" },
    ],
    nearby: ["kenroku-en", "higashi-chaya"],
  },
  {
    id: "shiroyone-senmaida", title: "白米千枚田", location: "輪島市",
    prefecture: "石川県", prefectureId: "ishikawa", area: "輪島", areaId: "wajima-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "海に向かって段々と落ちる棚田。日本海に沈む夕日が、田んぼを金色に染める。",
    longDescription: "白米千枚田は世界農業遺産にも認定された能登半島の棚田景観。海岸に沿って急斜面を下る約1004枚の棚田は、最小の田が0.2平方メートルしかない極小棚田を含む。田植え期（5月）の水鏡と夕日の組み合わせ、黄金色の稲穂が揺れる秋（9月）、冬のあぜ道に灯されるLEDイルミネーション「あぜのきらめき」と、四季それぞれに絶景がある。国道249号線沿いの展望台から一望できるが、畦道を歩いて田の中に入るのが正解。",
    tags: ["棚田", "絶景", "世界農業遺産", "夕日", "能登"],
    stayDuration: 60, bestTime: "夕方（日没前後）・5月田植え期", crowdLevel: "low",
    budget: "無料", access: "金沢駅から車で約2時間", rainyDay: false,
    highlights: ["日没の棚田", "あぜのきらめき（冬）", "田植え期の水鏡"],
    features: [
      { label: "夕日の棚田", text: "日本海に沈む夕日が海と田を同時に染める。構図が完璧。" },
      { label: "あぜのきらめき", text: "冬の夜、約21,000個のLEDが棚田を光で埋める。" },
    ],
    nearby: ["higashi-chaya"],
  },

  // ── 福井 ──────────────────────────────────────
  {
    id: "eiheiji-temple", title: "永平寺", location: "吉田郡永平寺町",
    prefecture: "福井県", prefectureId: "fukui", area: "永平寺", areaId: "eiheiji-area",
    category: "temple",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "禅の空気が満ちた森の中の大伽藍。修行僧の走る足音が聞こえる。",
    longDescription: "永平寺は道元禅師が1244年に開いた曹洞宗の大本山。樹齢数百年の杉木立に包まれた境内には70以上の伽藍が連なり、今も200名以上の修行僧が厳しい禅修行を行う。参拝者は修行の場である七堂伽藍を見学できる。廊下を走る修行僧、早朝の読経、精進料理の香りが境内に満ちる。朝6時に行われる早暁（朝のお勤め）に参加すると、日常から切り離された静寂に包まれる。",
    tags: ["禅寺", "修行", "大本山", "森", "精進料理"],
    stayDuration: 120, bestTime: "早朝（朝のお勤め時間）", crowdLevel: "medium",
    budget: "¥500", access: "JR福井駅からバスで1時間", rainyDay: true,
    highlights: ["七堂伽藍", "早暁のお勤め", "大杉の参道"],
    features: [
      { label: "七堂伽藍", text: "修行僧が使う本物の修行空間。走る僧侶とすれ違う臨場感がある。" },
      { label: "大杉の参道", text: "樹齢数百年の杉が立ち並ぶ参道。夏でも薄暗く涼しい。" },
    ],
    nearby: ["tojinbo"],
  },
  {
    id: "tojinbo", title: "東尋坊", location: "坂井市",
    prefecture: "福井県", prefectureId: "fukui", area: "坂井", areaId: "sakai-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "日本海の荒波が削った柱状節理。波の音が、崖の上まで届く。",
    longDescription: "東尋坊は日本海に面した高さ25mの断崖絶壁。マグマが冷えて収縮した柱状節理（輝石安山岩）が約1kmにわたって続き、世界に3か所しかないとされる大規模なものとして知られる。強風の日、崖下に打ち寄せる波の轟音は150m離れた遊歩道にまで響く。遊覧船で崖の下から見上げると、地上からは想像できない迫力の断崖が現れる。夕日が沈む時間帯、崖の赤みと空のグラデーションが重なる瞬間が最も美しい。",
    tags: ["断崖", "絶景", "日本海", "柱状節理", "夕日"],
    stayDuration: 90, bestTime: "夕方（日没前後）・荒天日", crowdLevel: "medium",
    budget: "無料（遊覧船¥1,500）", access: "JR芦原温泉駅からバスで40分", rainyDay: false,
    highlights: ["柱状節理の断崖", "遊覧船", "夕日"],
    features: [
      { label: "遊覧船", text: "崖の下から見上げる東尋坊。上からより下から見た方が迫力がある。" },
      { label: "夕日の時間", text: "崖の赤みが増す夕方が最も東尋坊らしい瞬間。" },
    ],
    nearby: ["eiheiji-temple", "fukui-dinosaur"],
  },
  {
    id: "fukui-dinosaur", title: "恐竜博物館", location: "勝山市",
    prefecture: "福井県", prefectureId: "fukui", area: "勝山", areaId: "katsuyama-area",
    category: "experience",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "世界三大恐竜博物館のひとつ。日本最多の恐竜化石がここにある。",
    longDescription: "福井県立恐竜博物館は世界三大恐竜博物館のひとつに数えられ、国内で発見された恐竜化石の多くが福井産。フクイラプトル・フクイサウルス・フクイティタンなど福井固有種の全身骨格標本が展示される。銀色のドーム型の建物は野山に突如出現するSFめいた外観で、館内の吹き抜け空間に並ぶ実物大骨格は子どもも大人も圧倒する。発掘現場に近い勝山市には野外恐竜博物館もあり、本物の地層を観察しながら化石発掘体験ができる。",
    tags: ["博物館", "恐竜", "化石", "体験", "家族"],
    stayDuration: 180, bestTime: "平日（混雑を避けられる）", crowdLevel: "medium",
    budget: "¥730", access: "えちぜん鉄道 勝山駅からバスで15分", rainyDay: true,
    highlights: ["全身骨格標本", "化石発掘体験", "野外恐竜博物館"],
    features: [
      { label: "全身骨格標本", text: "43体の恐竜骨格が並ぶ空間。スケールが頭で理解できない。" },
      { label: "化石発掘体験", text: "野外博物館では本物の地層から化石を掘る体験が可能。" },
    ],
    nearby: ["eiheiji-temple"],
  },

  // ── 山梨 ──────────────────────────────────────
  {
    id: "fuji-goko", title: "富士五湖", location: "南都留郡富士河口湖町ほか",
    prefecture: "山梨県", prefectureId: "yamanashi", area: "富士五湖", areaId: "fujigoko-area",
    category: "park",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "水面に映る逆さ富士。本栖湖の朝靄が、千円札と同じ景色を見せる。",
    longDescription: "富士五湖は富士山の北麓に広がる河口湖・山中湖・西湖・精進湖・本栖湖の総称。それぞれ異なる表情を持つ。本栖湖は千円札のモデルになった「逆さ富士」の撮影地として有名で、無風の早朝に湖面が鏡になる。山中湖は富士山の眺望が最も開けており、白鳥が浮かぶ景観が美しい。河口湖は観光施設が充実し、ロープウェイ・カチカチ山からの展望が人気。4月末から5月にかけて新緑が映える時期が最高潮。",
    tags: ["富士山", "湖", "逆さ富士", "写真映え", "絶景"],
    stayDuration: 180, bestTime: "早朝（逆さ富士）・4〜5月（新緑）", crowdLevel: "medium",
    budget: "無料（施設入場別）", access: "新宿から富士急ハイランドまで特急2時間", rainyDay: false,
    highlights: ["本栖湖の逆さ富士", "カチカチ山ロープウェイ", "山中湖の白鳥"],
    features: [
      { label: "逆さ富士（本栖湖）", text: "無風の早朝だけ出現する鏡像。千円札と同じアングルを探す。" },
      { label: "カチカチ山ロープウェイ", text: "河口湖畔から富士山と湖を一望。天気が良ければ南アルプスまで。" },
    ],
    nearby: ["shosenkyo"],
  },
  {
    id: "shosenkyo", title: "昇仙峡", location: "甲府市",
    prefecture: "山梨県", prefectureId: "yamanashi", area: "甲府", areaId: "kofu-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "花崗岩の奇峰が連なる、日本一の渓谷美。秋の紅葉は別世界になる。",
    longDescription: "昇仙峡は国の特別名勝に指定された甲府市北部の峡谷。荒川が花崗岩を浸食して作った奇岩・奇石が約5kmにわたって続く。仙娥滝（30m）は日本の滝百選のひとつ。覚円峰と呼ばれる約180mの柱状岩壁は昇仙峡のシンボル。11月の紅葉期は岸壁・渓流・紅葉が重なり、絵画のような風景になる。渓谷沿いの遊歩道は往復1時間半で歩けるが、ロープウェイで上部エリアに出ると水晶・宝石の店が立ち並ぶ。",
    tags: ["渓谷", "紅葉", "奇岩", "国特別名勝", "滝"],
    stayDuration: 120, bestTime: "11月（紅葉最盛期）", crowdLevel: "medium",
    budget: "無料（ロープウェイ¥1,000）", access: "JR甲府駅からバスで30分", rainyDay: false,
    highlights: ["仙娥滝", "覚円峰", "秋の紅葉"],
    features: [
      { label: "覚円峰", text: "天を突く180mの岩柱。川沿いから見上げると首が痛くなる高さ。" },
      { label: "仙娥滝", text: "30mを一気に落ちる滝。近づくと飛沫が夏でも涼しい。" },
    ],
    nearby: ["hottarakashi-onsen"],
  },
  {
    id: "hottarakashi-onsen", title: "ほったらかし温泉", location: "山梨市",
    prefecture: "山梨県", prefectureId: "yamanashi", area: "山梨市", areaId: "yamanashi-city-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "日の出前から入れる露天風呂。富士山と甲府盆地を見下ろして湯に浸かる。",
    longDescription: "ほったらかし温泉は山梨市の山腹に建つ露天風呂施設。「あっちの湯」「こっちの湯」の2つの露天風呂があり、日の出1時間前から営業するのが最大の特徴。暗闇の中で湯に入り、甲府盆地の夜景を眺めながら空が白み始め、富士山のシルエットが浮かんで日が昇る。この一連の体験が「ほったらかし温泉」を唯一無二にする。入浴料は900円。隣接する果樹園で朝5時から食べられる桃やぶどうのソフトクリームが名物。",
    tags: ["温泉", "日の出", "露天風呂", "富士山", "早朝"],
    stayDuration: 120, bestTime: "日の出前（5:00〜）", crowdLevel: "medium",
    budget: "¥900", access: "JR山梨市駅からタクシー15分", rainyDay: true,
    highlights: ["日の出の露天風呂", "富士山の眺望", "甲府盆地の夜景"],
    features: [
      { label: "日の出の露天風呂", text: "暗闇から夜明けへ移行する30分間。湯の中から見るから特別。" },
      { label: "早朝のソフトクリーム", text: "朝5時から隣の売店が開く。桃ソフトを温泉上がりに食べる。" },
    ],
    nearby: ["shosenkyo"],
  },

  // ── 長野 ──────────────────────────────────────
  {
    id: "matsumoto-castle", title: "松本城", location: "松本市",
    prefecture: "長野県", prefectureId: "nagano", area: "松本", areaId: "matsumoto-area",
    category: "castle",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "国宝天守5城のひとつ。黒漆喰の外壁に、北アルプスの白が映える。",
    longDescription: "松本城は現存する12天守のひとつであり、国宝に指定された5つの天守の中でも最古に属する。黒漆喰塗の外壁（黒城）と内堀の水面に映る逆さ天守が、北アルプスを背景に圧倒的な美しさを誇る。天守内部には急勾配の階段が6階まで続き、最上階から見る北アルプスの連嶺は松本城を訪ねる最大の理由のひとつ。4月の桜、冬の雪と天守の組み合わせも日本の城風景の中で特別の美しさがある。",
    tags: ["城", "国宝", "北アルプス", "桜", "歴史"],
    stayDuration: 90, bestTime: "早朝（開門直後）・4月（桜）", crowdLevel: "medium",
    budget: "¥700", access: "JR松本駅から徒歩15分", rainyDay: false,
    highlights: ["国宝天守", "お堀の逆さ天守", "北アルプスの眺め"],
    features: [
      { label: "黒い天守", text: "白城が多い中で黒漆喰は珍しい。水面に映るとより際立つ。" },
      { label: "天守最上階", text: "急勾配の階段を登った先の北アルプス展望。登る価値がある。" },
    ],
    nearby: ["kamikochi"],
  },
  {
    id: "kamikochi", title: "上高地", location: "松本市（梓川上流）",
    prefecture: "長野県", prefectureId: "nagano", area: "上高地", areaId: "kamikochi-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "穂高連峰の麓、梓川の清流。日本で最も美しい山岳リゾートがここにある。",
    longDescription: "上高地は標高1500mの山岳景勝地。マイカー乗り入れ禁止のため、シャトルバスかタクシーでしかアクセスできない。梓川の澄んだ流れと穂高連峰の威容が同時に目に入る河童橋付近の景観は、国内登山道でも最も写真に撮られる場所のひとつ。5月の残雪期、7〜8月の緑と清流、10月の紅葉と燃えるような黄葉とそれぞれに絶景がある。大正池から河童橋まで3kmの遊歩道を歩くだけで、山に登らずとも本物の自然に触れられる。",
    tags: ["山岳", "清流", "北アルプス", "紅葉", "絶景"],
    stayDuration: 240, bestTime: "5月（残雪）・10月（紅葉）", crowdLevel: "medium",
    budget: "無料（交通費別）", access: "松本駅からバスで1時間半", rainyDay: false,
    highlights: ["河童橋", "大正池", "穂高連峰の眺め"],
    features: [
      { label: "大正池〜河童橋遊歩道", text: "3kmを1時間で歩ける自然探勝路。野生のサルやニホンジカが出る。" },
      { label: "河童橋", text: "梓川と穂高を結ぶ上高地の象徴的風景ポイント。" },
    ],
    nearby: ["matsumoto-castle", "zenkoji"],
  },
  {
    id: "zenkoji", title: "善光寺", location: "長野市",
    prefecture: "長野県", prefectureId: "nagano", area: "長野", areaId: "nagano-city-area",
    category: "temple",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "宗派を超えて全ての人を迎える寺。お朝事の鐘が、長野の朝を始める。",
    longDescription: "善光寺は「一生に一度は善光寺詣り」と言われる無宗派の単立寺院。本堂内陣の地下には「お戒壇めぐり」があり、真っ暗な回廊を手探りで進んで錠前に触れると極楽往生が約束されるとされる。毎朝6時（夏は5時半）から行われる朝のお勤め「お朝事」では住職たちの読経が本堂に響き、参道沿いの民宿に一泊してこれに参加する旅が信仰の旅の基本形。7年に一度の御開帳は全国から数百万人が訪れる最大規模の行事。",
    tags: ["寺院", "無宗派", "朝のお勤め", "長野", "信仰"],
    stayDuration: 90, bestTime: "早朝（お朝事の時間）", crowdLevel: "medium",
    budget: "無料（内陣・戒壇入場¥500）", access: "JR長野駅から徒歩25分またはバス10分", rainyDay: true,
    highlights: ["お戒壇めぐり", "お朝事", "仲見世参道"],
    features: [
      { label: "お戒壇めぐり", text: "本当に何も見えない暗闇。錠前を探す10分間が非日常体験。" },
      { label: "お朝事", text: "朝6時の読経参列。参道から本堂まで歩く朝の空気が清澄。" },
    ],
    nearby: ["karuizawa"],
  },
  {
    id: "karuizawa", title: "軽井沢", location: "北佐久郡軽井沢町",
    prefecture: "長野県", prefectureId: "nagano", area: "軽井沢", areaId: "karuizawa-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "避暑地の品格が今も生きている。白樺と教会と、ショップが共存する場所。",
    longDescription: "軽井沢は明治期に外国人宣教師が訪れて以来、日本屈指の避暑地として発展してきた。旧軽井沢銀座は観光客で賑わうが、南軽井沢の白樺林を歩くと別世界の静けさがある。聖パウロカトリック教会は軽井沢の象徴的建築で、石造りのたたずまいが白樺に包まれる。秋の紅葉期（10月中旬）は白樺が黄色く染まり、軽井沢で最も美しい季節。新幹線で東京から70分というアクセスが、週末の小旅行先として唯一無二の地位を与えている。",
    tags: ["避暑地", "軽井沢", "白樺", "教会", "リゾート"],
    stayDuration: 180, bestTime: "10月（紅葉）・7〜8月（避暑）", crowdLevel: "medium",
    budget: "無料（ショッピング別）", access: "JR北陸新幹線 軽井沢駅から徒歩・自転車", rainyDay: false,
    highlights: ["旧軽井沢銀座", "聖パウロカトリック教会", "白樺林"],
    features: [
      { label: "旧軽井沢銀座", text: "土産物屋・カフェ・食堂が集まる通り。混雑するが外せない。" },
      { label: "雲場池", text: "秋の紅葉が水面に映る軽井沢随一の絶景ポイント。朝が空いている。" },
    ],
    nearby: ["zenkoji"],
  },

  // ── 岐阜 ──────────────────────────────────────
  {
    id: "shirakawa-go", title: "白川郷", location: "大野郡白川村",
    prefecture: "岐阜県", prefectureId: "gifu", area: "白川郷", areaId: "shirakawa-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "ユネスコ世界遺産の合掌造り集落。冬の雪原に立つ茅葺きは、別の時代の話。",
    longDescription: "白川郷は岐阜県北西部に位置するユネスコ世界遺産の合掌造り集落。荻町集落には114棟の合掌造り家屋が今も現役で使われ、多くが民宿や食堂として機能する。集落を見下ろす展望台（城山）からの俯瞰が有名で、特に冬の雪景色は何度見ても非現実的な美しさ。冬のライトアップ（1〜2月の土日）は世界中から観光客が集まるが、平日は静かに集落を歩ける。五箇山と合わせて1泊2日のルートが推奨される。",
    tags: ["世界遺産", "合掌造り", "冬景色", "岐阜", "古民家"],
    stayDuration: 150, bestTime: "冬（雪景色・ライトアップ）・早朝", crowdLevel: "high",
    budget: "無料（集落内見学）", access: "名古屋駅から高速バスで2時間半", rainyDay: false,
    highlights: ["荻町城山展望台", "冬のライトアップ", "合掌造り宿泊"],
    features: [
      { label: "城山展望台", text: "集落全体を俯瞰できる。冬の白と茅葺きの対比が最高の構図。" },
      { label: "合掌造りへの宿泊", text: "囲炉裏端での夕食と早朝の霧。これを体験した人だけが知る価値。" },
    ],
    nearby: ["takayama-old-town", "gokayama-gassho"],
  },
  {
    id: "takayama-old-town", title: "高山古い町並", location: "高山市",
    prefecture: "岐阜県", prefectureId: "gifu", area: "高山", areaId: "takayama-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "飛騨の小京都。江戸時代の商家がそのまま通りになっている。",
    longDescription: "高山の古い町並（三町伝統的建造物群保存地区）は江戸〜明治時代の商家町が保存された地区。一之町・二之町・三之町の通りを歩くと、黒い格子窓の商家が連なり、現代の建物がほとんど目に入らない。酒蔵の杉玉が軒先に下がり、飛騨牛・朴葉味噌・みたらし団子の香りが路地を満たす。早朝は観光客がなく、地元の人だけが歩く本来の町の顔がある。春と秋の高山祭は国の重要無形民俗文化財で、日本三大祭りのひとつ。",
    tags: ["古い町並", "高山", "飛騨", "酒蔵", "グルメ"],
    stayDuration: 120, bestTime: "早朝（朝市から始める）", crowdLevel: "medium",
    budget: "無料（見学）", access: "JR高山駅から徒歩10分", rainyDay: false,
    highlights: ["三町の格子窓", "朝市（陣屋前・宮川沿い）", "高山祭"],
    features: [
      { label: "陣屋前朝市", text: "毎朝7時から開く朝市。漬物・野菜・民芸品が並ぶ。" },
      { label: "飛騨牛の立ち食い", text: "串焼きを食べ歩きながら町並みを歩く。これが正しい高山の楽しみ方。" },
    ],
    nearby: ["shirakawa-go", "gero-onsen"],
  },
  {
    id: "gero-onsen", title: "下呂温泉", location: "下呂市",
    prefecture: "岐阜県", prefectureId: "gifu", area: "下呂", areaId: "gero-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "日本三名泉のひとつ。飛騨川沿いに広がる温泉街が、夜に輝く。",
    longDescription: "下呂温泉は草津・有馬と並ぶ日本三名泉。アルカリ性単純泉の泉質は肌がぬるっとする美人湯として有名。飛騨川の両岸に温泉旅館が並ぶ温泉街は、夜になると橋が朱色にライトアップされ鮮やかな景観を作る。河川敷には無料で入れる「噴泉池」があり、水着着用で昼間に入れる。温泉まんじゅうの老舗が何軒もあり、各店で食べ比べるのが下呂の楽しみ方のひとつ。日帰り入浴可能な旅館が多いので、名古屋からの日帰りコースにも組みやすい。",
    tags: ["温泉", "三名泉", "旅館", "飛騨川", "美人湯"],
    stayDuration: 180, bestTime: "夕方〜夜（温泉街のライトアップ）", crowdLevel: "medium",
    budget: "¥700〜（日帰り入浴）", access: "JR高山線 下呂駅から徒歩10分", rainyDay: true,
    highlights: ["噴泉池（無料露天）", "飛騨川沿いの温泉街", "温泉まんじゅう"],
    features: [
      { label: "噴泉池", text: "河川敷にある無料の露天風呂。観光客も入れる珍しい施設。" },
      { label: "夜の温泉街", text: "橋のライトアップと川の反射。温泉上がりに歩くのが最高。" },
    ],
    nearby: ["takayama-old-town"],
  },

  // ── 静岡 ──────────────────────────────────────
  {
    id: "miho-no-matsubara", title: "三保の松原", location: "静岡市清水区",
    prefecture: "静岡県", prefectureId: "shizuoka", area: "静岡", areaId: "shizuoka-area",
    category: "beach",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "富士山・松林・駿河湾が一枚の絵に収まる。世界遺産の松林で天女を想う。",
    longDescription: "三保の松原は富士山世界文化遺産の構成資産のひとつ。約7kmにわたって続く松林（約5万4千本）と富士山・駿河湾が重なる景観は、江戸時代から「日本三景に加えるべき」と言われてきた絶景。天女が羽衣を掛けたとされる「羽衣の松」は境内にあり、樹齢650年以上の老松。朝の透明な空気の中、松林越しに富士山が見える瞬間がここを訪れる最大の理由。駿河湾の向こうに沈む夕日も美しい。",
    tags: ["富士山", "世界遺産", "松林", "駿河湾", "絶景"],
    stayDuration: 90, bestTime: "早朝（晴れた日の富士山）", crowdLevel: "low",
    budget: "無料", access: "JR清水駅からバスで25分", rainyDay: false,
    highlights: ["羽衣の松", "富士山の眺望", "砂浜散策"],
    features: [
      { label: "羽衣の松", text: "天女伝説の松。樹齢650年以上、三代目が現在の御神木。" },
      { label: "富士山の眺め", text: "松の間から望む富士。距離があるからこそ全体像が美しい。" },
    ],
    nearby: ["izu-hanto"],
  },
  {
    id: "izu-hanto", title: "伊豆半島", location: "静岡県伊豆半島全域",
    prefecture: "静岡県", prefectureId: "shizuoka", area: "伊豆", areaId: "izu-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "温泉・海・火山地形が凝縮。東京から最も近い、本物のリゾート半島。",
    longDescription: "伊豆半島はユネスコ世界ジオパークに認定された火山活動が生んだ地形の宝庫。温泉が随所に湧き出し、修善寺・熱川・伊東・下田など多様な温泉地が連なる。西伊豆の堂ヶ島では海蝕洞窟の遊覧船が人気で、干潮時には海底が透けて見える天窓洞がある。東伊豆の城ヶ崎海岸はマグマが固まった柱状節理の断崖が続く。南端の石廊崎からは太平洋が広がり、季節外れの静けさが本物の旅の気分にしてくれる。",
    tags: ["半島", "温泉", "ジオパーク", "海", "リゾート"],
    stayDuration: 480, bestTime: "春（菜の花）・秋（空いている）", crowdLevel: "medium",
    budget: "¥1,000〜（日帰り入浴込み）", access: "東京から踊り子号・新幹線＋伊豆急で2時間", rainyDay: false,
    highlights: ["堂ヶ島の天窓洞", "城ヶ崎海岸の断崖", "修善寺温泉"],
    features: [
      { label: "堂ヶ島の天窓洞", text: "海蝕洞窟に空いた穴から光が入る。遊覧船で下から見上げると神秘的。" },
      { label: "城ヶ崎海岸", text: "マグマが作った断崖の上を歩く吊り橋コース。海の青と断崖の黒が鮮烈。" },
    ],
    nearby: ["atami-onsen"],
  },
  {
    id: "atami-onsen", title: "熱海温泉", location: "熱海市",
    prefecture: "静岡県", prefectureId: "shizuoka", area: "熱海", areaId: "atami-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "再生した昭和の温泉リゾート。若い旅行者が戻ってきた熱海が、今熱い。",
    longDescription: "熱海温泉はかつて「日本一の温泉観光地」として栄えた後、一時期衰退したが2010年代以降に劇的な再生を遂げた。若いクリエイターが古いビルをリノベーションし、カフェ・ギャラリー・ゲストハウスに生まれ変わらせた。熱海銀座は個性的なショップが並び、週末は若い旅行者で賑わう。有名な熱海プリン・熱海バーガーなどのご当地グルメも充実。相模湾を見下ろす高台の温泉宿から見る朝日が、熱海で最も豊かな瞬間。",
    tags: ["温泉", "リゾート", "再生", "海景色", "昭和レトロ"],
    stayDuration: 180, bestTime: "平日（週末は混む）", crowdLevel: "high",
    budget: "¥1,500〜（日帰り入浴）", access: "東京から新幹線こだまで40分", rainyDay: true,
    highlights: ["熱海銀座", "起雲閣", "相模湾の眺望"],
    features: [
      { label: "熱海銀座", text: "昭和の商店街がリノベーションで復活。お洒落な店と古い店が混在。" },
      { label: "起雲閣", text: "大正時代の別荘建築。太宰治・山本有三が滞在した歴史的施設。" },
    ],
    nearby: ["hamanako"],
  },
  {
    id: "hamanako", title: "浜名湖", location: "浜松市・湖西市",
    prefecture: "静岡県", prefectureId: "shizuoka", area: "浜松", areaId: "hamamatsu-area",
    category: "park",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "うなぎと新茶と舘山寺温泉。遠州灘に繋がる汽水湖の、静かな旅。",
    longDescription: "浜名湖は遠州灘と繋がる汽水湖で、日本有数のうなぎの産地。湖周遊のサイクリングロードは全長約68kmで、のんびり走ると1〜2日かかる。舘山寺温泉は湖畔に旅館が並ぶ温泉地で、湖の夕日を眺めながら入る露天風呂が楽しみ。浜松名物・鰻はここでしか食べられない直焼き（関西風）と蒸し焼き（関東風）の中間スタイル。浜名湖ガーデンパークや浜名湖フルーツパークも点在し、家族連れにも対応した広域リゾートになっている。",
    tags: ["湖", "うなぎ", "温泉", "サイクリング", "浜松"],
    stayDuration: 240, bestTime: "春（新茶シーズン）・秋", crowdLevel: "low",
    budget: "¥3,000〜（うなぎ定食込み）", access: "JR東海道本線 弁天島駅・浜松駅", rainyDay: false,
    highlights: ["浜名湖うなぎ", "舘山寺温泉", "湖畔サイクリング"],
    features: [
      { label: "浜名湖うなぎ", text: "養鰻場から直送の蒲焼き。浜松の食文化の核心。" },
      { label: "舘山寺温泉", text: "湖越しに夕日が落ちる露天風呂。静岡の温泉の中で特別な眺め。" },
    ],
    nearby: ["atami-onsen"],
  },

  // ── 愛知 ──────────────────────────────────────
  {
    id: "nagoya-castle", title: "名古屋城", location: "名古屋市中区",
    prefecture: "愛知県", prefectureId: "aichi", area: "名古屋", areaId: "nagoya-area",
    category: "castle",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "金のシャチホコが名古屋の空に輝く。本丸御殿の障壁画が、豪壮な城絵を見せる。",
    longDescription: "名古屋城は徳川家康が九男・義直のために築いた城。天守に輝く金のシャチホコは名古屋の象徴として全国的に知られる。平成30年に完全復元された本丸御殿は、将軍が宿泊するために作られた豪華な書院造建築で、内部の障壁画（金碧画）は桃山時代の美術を今に伝える。春の桜シーズンは天守と桜のコントラストが美しく、一日中歩ける規模の城郭。隣接する二之丸庭園でのんびり過ごす時間も楽しい。",
    tags: ["城", "名古屋", "金シャチ", "本丸御殿", "桜"],
    stayDuration: 120, bestTime: "4月（桜）・早朝", crowdLevel: "medium",
    budget: "¥500", access: "名古屋市営地下鉄 名城公園駅から徒歩5分", rainyDay: false,
    highlights: ["金のシャチホコ", "本丸御殿の障壁画", "桜の名所"],
    features: [
      { label: "本丸御殿", text: "金箔を多用した障壁画。江戸時代の「見せる権力」が詰まった空間。" },
      { label: "金のシャチホコ", text: "東・西2体で約44kg分の金を使用。天守最上部で輝く名古屋のシンボル。" },
    ],
    nearby: ["atsuta-jingu", "inuyama-castle"],
  },
  {
    id: "atsuta-jingu", title: "熱田神宮", location: "名古屋市熱田区",
    prefecture: "愛知県", prefectureId: "aichi", area: "名古屋", areaId: "nagoya-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "三種の神器・草薙剣が眠る森。杉木立の中に静寂がある。",
    longDescription: "熱田神宮は三種の神器のひとつ「草薙の剣」を御神体として祀る神社。年間700万人以上が参拝する愛知県最大の神社で、古来から「熱田さん」として名古屋市民に親しまれてきた。境内は広大な杉木立に覆われ、都市の中にありながら深い森の静けさが広がる。名物「宮きしめん」は境内内の神宮きしめん亭で食べられ、参拝前後の一杯が習慣になっている人も多い。元旦には200万人を超える参拝者が集まる。",
    tags: ["神社", "三種の神器", "名古屋", "森", "宮きしめん"],
    stayDuration: 60, bestTime: "早朝（開門時間）", crowdLevel: "medium",
    budget: "無料", access: "名鉄名古屋本線 神宮前駅から徒歩3分", rainyDay: false,
    highlights: ["草薙の剣（御神体）", "境内の杉木立", "宮きしめん"],
    features: [
      { label: "杉木立の参道", text: "樹齢数百年の杉が参道を覆う。都市の中の森として一種の癒しがある。" },
      { label: "宮きしめん", text: "境内で食べるきしめん。薄い麺に透き通った出汁が名古屋の食文化。" },
    ],
    nearby: ["nagoya-castle", "inuyama-castle"],
  },
  {
    id: "inuyama-castle", title: "犬山城", location: "犬山市",
    prefecture: "愛知県", prefectureId: "aichi", area: "犬山", areaId: "inuyama-area",
    category: "castle",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "国宝天守の中で最古。木曽川の断崖に建つ城は、下から見上げるのが正解。",
    longDescription: "犬山城は天文6年（1537年）に建てられたとされる現存最古の国宝天守。木曽川に臨む断崖絶壁の上に建ち、川面から見上げると要塞としての機能と美しさが同時に伝わる。天守最上階（高さ約22m）からは木曽川と対岸の岐阜が見渡せる。城下町の本町通りにはカステラ・みたらし団子・どて丼の店が並び、食べ歩きしながら歩ける。木曽川では鵜飼（5〜10月）も見られ、松明の炎と鵜の動きが幻想的。",
    tags: ["城", "国宝", "最古", "犬山", "城下町"],
    stayDuration: 120, bestTime: "早朝・桜の季節", crowdLevel: "medium",
    budget: "¥550", access: "名鉄犬山線 犬山遊園駅から徒歩15分", rainyDay: false,
    highlights: ["最古の国宝天守", "城下町食べ歩き", "木曽川の鵜飼"],
    features: [
      { label: "天守最上階", text: "木曽川と濃尾平野を見渡す絶景。戦国時代の視点で山河が見える。" },
      { label: "鵜飼（夏〜秋）", text: "木曽川の伝統漁法。松明の炎が川面を照らす夜の光景が幻想的。" },
    ],
    nearby: ["atsuta-jingu", "nagoya-castle"],
  },
];
