import { Spot } from "@/types/spot";

export const chugokuShikokuSpots: Spot[] = [
  // ── 鳥取 ──────────────────────────────────────
  {
    id: "tottori-sand-dunes",
    title: "鳥取砂丘",
    titleEn: "Tottori Sand Dunes",
    location: "鳥取市福部町",
    prefecture: "鳥取県",
    prefectureId: "tottori",
    area: "鳥取",
    areaId: "tottori-city",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=80",
      "https://images.unsplash.com/photo-1682685797406-97f364419b4a?w=1200&q=80",
    ],
    description: "日本最大の砂丘。風が描く砂紋は、毎日違う顔を見せる。",
    longDescription: "日本海に面する鳥取砂丘は、東西16km・南北2.4kmにわたる日本最大の砂丘地帯。起伏が激しく、最大落差は90mにもなる。朝一番に訪れると、前夜の風が描いた砂紋がまだ残っており、足跡のない砂の表面が幻想的だ。ラクダに乗る体験も人気だが、砂丘の馬の背を越えた先に広がる日本海の景色こそが、来た甲斐を感じる瞬間。砂丘センターで靴の砂を落としてから帰るのが鉄則。",
    tags: ["砂丘", "自然", "写真映え", "絶景", "鳥取"],
    stayDuration: 90,
    bestTime: "早朝・夕方",
    crowdLevel: "medium",
    budget: "無料",
    access: "鳥取駅からバス約30分",
    rainyDay: false,
    highlights: ["砂紋", "馬の背からの日本海", "ラクダ体験"],
    features: [
      { label: "砂紋", text: "風によって描かれる自然のアート。朝一番が最も美しい。" },
      { label: "馬の背", text: "砂丘最大の丘。登り切ると日本海が眼前に広がる。" },
      { label: "砂の美術館", text: "砂丘の隣にある世界最大の砂の彫刻美術館。雨の日にも対応。" },
    ],
    nearby: ["mizuki-road", "daisen"],
    mapUrl: "https://maps.google.com/?q=鳥取砂丘",
    officialUrl: "https://www.tottori-guide.jp/",
    seasonality: ["春", "夏", "秋", "冬"],
    openHours: "見学自由",
  },
  {
    id: "mizuki-road",
    title: "水木しげるロード",
    titleEn: "Mizuki Shigeru Road",
    location: "境港市本町",
    prefecture: "鳥取県",
    prefectureId: "tottori",
    area: "境港",
    areaId: "sakaiminato",
    category: "street",
    images: [
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
      "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=80",
    ],
    description: "妖怪の街、境港。ゲゲゲの鬼太郎が全長800mの商店街に潜んでいる。",
    longDescription: "鬼太郎の生みの親、水木しげるの故郷・境港。駅前から続く全長800mの商店街には177体の妖怪ブロンズ像が立ち並ぶ。ネコ娘のケーキ、目玉おやじのまんじゅうなど妖怪モチーフの土産が充実。水木しげる記念館では原画や妖怪の世界観を堪能できる。子連れはもちろん、昭和マンガに思い入れのある大人が最も熱くなる場所。夜の商店街は妖怪感がより増す。",
    tags: ["アニメ", "街歩き", "キャラクター", "食べ歩き", "家族"],
    stayDuration: 120,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "¥500〜",
    access: "JR境港駅から徒歩すぐ",
    rainyDay: true,
    highlights: ["177体のブロンズ像", "水木しげる記念館", "妖怪グルメ"],
    features: [
      { label: "ブロンズ像めぐり", text: "全177体を探す「妖怪スタンプラリー」が楽しめる。" },
      { label: "水木しげる記念館", text: "原画・資料が充実。水木ワールドの核心。" },
    ],
    nearby: ["tottori-sand-dunes", "daisen"],
    mapUrl: "https://maps.google.com/?q=水木しげるロード",
    officialUrl: "https://www.sakaiminato.net/mizuki/",
    openHours: "自由散策（記念館9:00〜18:00）",
    closedDays: "記念館は年中無休",
  },
  {
    id: "daisen",
    title: "大山",
    titleEn: "Mt. Daisen",
    location: "西伯郡大山町",
    prefecture: "鳥取県",
    prefectureId: "tottori",
    area: "大山",
    areaId: "daisen-area",
    category: "mountain",
    images: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
    ],
    description: "中国地方最高峰。伯耆富士と呼ばれる美しい山容が、麓から心を奪う。",
    longDescription: "標高1,729mの大山は、中国地方最高峰にして「伯耆富士」の別名を持つ。夏山登山道を使えば体力があれば日帰りも可能。山頂稜線は独特のナイフリッジで、晴れた日は日本海まで見渡せる。秋の大山寺周辺のブナ林の紅葉は特に有名で、鮮烈な黄金色が山麓を染める。大山牧場では大山放牧牛乳を使ったアイスが絶品。冬はスキーリゾートとしても機能する。",
    tags: ["登山", "自然", "絶景", "紅葉", "スキー"],
    stayDuration: 360,
    bestTime: "6月〜10月",
    crowdLevel: "medium",
    budget: "無料〜",
    access: "米子駅からバス約50分「大山寺」下車",
    rainyDay: false,
    highlights: ["山頂からの日本海", "ブナ林の紅葉", "大山寺"],
    features: [
      { label: "夏山登山道", text: "整備されており初心者でも登れる。山頂まで約2.5時間。" },
      { label: "秋の紅葉", text: "10月中旬のブナ林が最高。大山寺周辺の色づきは見事。" },
      { label: "大山牧場", text: "放牧牛乳のソフトクリームは濃くて甘い。下山後の楽しみ。" },
    ],
    nearby: ["tottori-sand-dunes", "matsue-castle"],
    mapUrl: "https://maps.google.com/?q=大山鳥取",
    officialUrl: "https://www.daisen.jp/",
    seasonality: ["春", "夏", "秋", "冬"],
    openHours: "登山道：終日（悪天候時入山禁止）",
  },

  // ── 島根 ──────────────────────────────────────
  {
    id: "izumo-taisha",
    title: "出雲大社",
    titleEn: "Izumo Taisha",
    location: "出雲市大社町",
    prefecture: "島根県",
    prefectureId: "shimane",
    area: "出雲",
    areaId: "izumo-area",
    category: "shrine",
    images: [
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
      "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    ],
    description: "縁結びの神様、大国主命が鎮座する。正月・縁結びシーズンは日本中から人が集まる。",
    longDescription: "出雲大社は全国8百万の神々が年に一度集まる「神在月」の舞台であり、縁結びの神として全国から参拝者が絶えない。本殿は高さ24mの大社造で日本最古の建築様式。拝殿の大しめ縄は長さ約13mで重さ5トン。一般的な神社は二礼二拍手一礼だが、出雲大社は二礼四拍手一礼が正式。この「違い」を知って参拝すると、より深く神社に向き合える。旧暦10月（神在月）は出雲にすべての神が集まる特別な時期。",
    tags: ["神社", "縁結び", "パワースポット", "定番", "歴史"],
    stayDuration: 90,
    bestTime: "早朝・夕方",
    crowdLevel: "high",
    budget: "無料",
    access: "一畑電車 出雲大社前駅から徒歩5分",
    rainyDay: false,
    highlights: ["本殿（国宝）", "大しめ縄", "神在月の神迎神事"],
    features: [
      { label: "拝殿の大しめ縄", text: "重さ5トン、長さ13m。圧倒的な存在感。" },
      { label: "参拝は二礼四拍手", text: "一般神社と異なる作法。知っているだけで格が上がる。" },
      { label: "神在月", text: "旧暦10月は全国の神が集う。出雲だけが「神有月」。" },
    ],
    nearby: ["matsue-castle", "iwami-ginzan"],
    mapUrl: "https://maps.google.com/?q=出雲大社",
    officialUrl: "https://www.izumooyashiro.or.jp/",
    seasonality: ["春", "秋", "冬"],
    openHours: "6:00〜20:00（宝物殿等は別途）",
    closedDays: "無休",
  },
  {
    id: "matsue-castle",
    title: "松江城",
    titleEn: "Matsue Castle",
    location: "松江市殿町",
    prefecture: "島根県",
    prefectureId: "shimane",
    area: "松江",
    areaId: "matsue-area",
    category: "castle",
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    ],
    description: "現存12天守のひとつ、国宝松江城。宍道湖を望む黒い天守は威圧感が違う。",
    longDescription: "松江城は1611年に完成した現存12天守のひとつで、2015年に国宝に指定された。黒い板張りの外壁が印象的で、現存天守の中でも保存状態が良い。天守最上階からは宍道湖を含む松江市街が一望できる。城周辺のお堀を巡る堀川遊覧船は観光のハイライト。船頭さんのユーモアある解説が楽しく、橋をくぐる際に屋根が下がる仕掛けも体験できる。小泉八雲（ラフカディオ・ハーン）がこよなく愛した「水の都」松江の象徴。",
    tags: ["城", "歴史", "国宝", "絶景"],
    stayDuration: 90,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "¥680",
    access: "JR松江駅からバス約10分「国宝松江城（大手前）」下車",
    rainyDay: true,
    highlights: ["国宝天守", "宍道湖の眺望", "堀川遊覧船"],
    features: [
      { label: "国宝天守", text: "現存12天守かつ国宝指定。内部の構造がよく保存されている。" },
      { label: "堀川遊覧船", text: "お堀を約50分で巡る。低い橋をくぐる場面が圧巻。" },
      { label: "夕景", text: "宍道湖に沈む夕日との組み合わせが絶景。" },
    ],
    nearby: ["izumo-taisha", "iwami-ginzan"],
    mapUrl: "https://maps.google.com/?q=松江城",
    officialUrl: "https://www.matsue-tourism.com/",
    openHours: "8:30〜18:30（季節により変動）",
    closedDays: "無休",
  },
  {
    id: "iwami-ginzan",
    title: "石見銀山",
    titleEn: "Iwami Ginzan Silver Mine",
    location: "大田市大森町",
    prefecture: "島根県",
    prefectureId: "shimane",
    area: "大田",
    areaId: "oda-area",
    category: "museum",
    images: [
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
    ],
    description: "世界遺産の銀山遺跡。江戸時代、世界の銀の三分の一はここから産出された。",
    longDescription: "2007年に世界文化遺産に登録された石見銀山。最盛期の17世紀前半には世界の銀産出量の約3分の1を占めたとされ、日本の近世経済を支えた。龍源寺間歩（まぶ）は実際に入れる坑道で、当時の採掘の様子がリアルに伝わる。銀山街道沿いには江戸時代の町並みが残る大森地区が続き、カフェや土産物屋が軒を連ねる。自転車を借りてゆっくり回るのが正解。世界遺産ながら、渋滞も行列もなく、ゆったり歩ける稀少な場所。",
    tags: ["世界遺産", "歴史", "自然", "のんびり"],
    stayDuration: 180,
    bestTime: "午前中",
    crowdLevel: "low",
    budget: "¥410（龍源寺間歩）",
    access: "JR大田市駅からバス約40分",
    rainyDay: true,
    highlights: ["龍源寺間歩", "大森の町並み", "自転車散策"],
    features: [
      { label: "龍源寺間歩", text: "実際に入れる坑道。ひんやりとした空気と暗がりに緊張感。" },
      { label: "大森の町並み", text: "江戸から明治の建物が混在する保存地区。歩いて楽しい。" },
      { label: "レンタサイクル", text: "広大なエリアを自転車で回る。体力に自信がなければ電動自転車を。" },
    ],
    nearby: ["matsue-castle", "izumo-taisha"],
    mapUrl: "https://maps.google.com/?q=石見銀山",
    officialUrl: "https://ginzan.city.ohda.lg.jp/",
    openHours: "龍源寺間歩 9:00〜17:00",
    closedDays: "無休",
    seasonality: ["春", "夏", "秋"],
  },

  // ── 岡山 ──────────────────────────────────────
  {
    id: "kurashiki-bikan",
    title: "倉敷美観地区",
    titleEn: "Kurashiki Bikan Historical Quarter",
    location: "倉敷市本町",
    prefecture: "岡山県",
    prefectureId: "okayama",
    area: "倉敷",
    areaId: "kurashiki-area",
    category: "street",
    images: [
      "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200&q=80",
      "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    ],
    description: "白壁と柳と運河。倉敷川に映る江戸の残像を、川舟に揺られながら眺める。",
    longDescription: "江戸時代の幕府直轄地として栄えた倉敷に残る美観地区。白壁のなまこ壁と柳の木が続く倉敷川畔は、観光地として整備されながらも江戸〜明治の建築物が現存している。大原美術館はモネ・マネ・エル・グレコを所蔵する地方美術館のレベルを遥かに超えた名門。川舟流しに乗ると、地上とは違う角度で美観地区を眺められる。夕方は混雑が落ち着き、柳のシルエットと白壁のコントラストが美しい。",
    tags: ["街歩き", "歴史", "美術館", "カップル"],
    stayDuration: 180,
    bestTime: "夕方",
    crowdLevel: "high",
    budget: "無料〜",
    access: "JR倉敷駅から徒歩15分",
    rainyDay: true,
    highlights: ["倉敷川畔の白壁", "大原美術館", "川舟流し"],
    features: [
      { label: "大原美術館", text: "西洋・日本の名画が揃う。倉敷に来てここを外すのはもったいない。" },
      { label: "川舟流し", text: "船頭さんが漕ぐ和舟に乗り、白壁の景色を水面から楽しむ。" },
      { label: "アイビースクエア", text: "紡績工場をリノベしたホテル・商業施設。煉瓦と蔦が美しい。" },
    ],
    nearby: ["korakuen", "okayama-castle"],
    mapUrl: "https://maps.google.com/?q=倉敷美観地区",
    officialUrl: "https://www.kurashiki-tabi.jp/",
    openHours: "散策自由（各施設は別途）",
    seasonality: ["春", "夏", "秋", "冬"],
  },
  {
    id: "korakuen",
    title: "後楽園",
    titleEn: "Korakuen Garden",
    location: "岡山市北区",
    prefecture: "岡山県",
    prefectureId: "okayama",
    area: "岡山",
    areaId: "okayama-city",
    category: "garden",
    images: [
      "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    ],
    description: "日本三名園のひとつ。岡山城を背景に、広大な芝生と池が広がる。",
    longDescription: "水戸偕楽園、金沢兼六園と並ぶ日本三名園のひとつ。1700年に岡山藩主・池田綱政が14年かけて造営した回遊式庭園。広大な芝生・延養亭・流店など見どころが多い。背後に岡山城が見える構図は、日本庭園と天守の組み合わせとして理想的。梅・桜・紅葉・雪と四季折々の表情があり、特に秋の紅葉期のライトアップは幻想的。鶴が放し飼いにされており、悠々と歩く姿が庭の格を高めている。",
    tags: ["庭園", "歴史", "日本三名園", "紅葉", "散歩"],
    stayDuration: 90,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "¥410",
    access: "JR岡山駅から路面電車・バス約15分",
    rainyDay: false,
    highlights: ["広大な芝生", "岡山城との組み合わせ", "鶴の放し飼い"],
    features: [
      { label: "延養亭", text: "藩主の居間として使われた建物。庭との調和が完璧。" },
      { label: "鶴", text: "庭内に放し飼い。近くで見られることも。" },
      { label: "秋のライトアップ", text: "紅葉期の夜間開園は特別な雰囲気に包まれる。" },
    ],
    nearby: ["okayama-castle", "kurashiki-bikan"],
    mapUrl: "https://maps.google.com/?q=後楽園岡山",
    officialUrl: "https://www.okayama-korakuen.jp/",
    openHours: "7:30〜18:00（季節変動あり）",
    closedDays: "無休",
  },
  {
    id: "okayama-castle",
    title: "岡山城",
    titleEn: "Okayama Castle",
    location: "岡山市北区丸の内",
    prefecture: "岡山県",
    prefectureId: "okayama",
    area: "岡山",
    areaId: "okayama-city",
    category: "castle",
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
      "https://images.unsplash.com/photo-1533050487297-09b450131914?w=1200&q=80",
    ],
    description: "黒塗りの外壁が特徴の「烏城（うじょう）」。後楽園と合わせて岡山観光の両輪。",
    longDescription: "金色の鯱と黒い下見板張りの外壁から「烏城（うじょう）」の異名を持つ岡山城。戦国時代に宇喜多秀家が築き、1966年に再建された天守は内部を博物館として整備。最上階からは後楽園を見下ろせる絶好のビューポイントがある。後楽園との間を流れる旭川越しに眺める岡山城のシルエットは、岡山を代表する景観。城内では岡山ゆかりの歴史をわかりやすく展示している。後楽園入園後に橋を渡って城へ向かうのが観光の王道ルート。",
    tags: ["城", "歴史", "絶景"],
    stayDuration: 60,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "¥320",
    access: "JR岡山駅から路面電車・バス約15分",
    rainyDay: true,
    highlights: ["黒い外壁の天守", "最上階からの後楽園", "旭川越しの眺望"],
    features: [
      { label: "天守最上階", text: "後楽園と市街を見渡せる。後楽園入園者は特に感慨深い。" },
      { label: "烏城の異名", text: "黒い外観が特徴的。白い姫路城と対比すると面白い。" },
    ],
    nearby: ["korakuen", "kurashiki-bikan"],
    mapUrl: "https://maps.google.com/?q=岡山城",
    officialUrl: "https://okayama-kanko.net/ujo/",
    openHours: "9:00〜17:30",
    closedDays: "12/29〜31",
  },
  {
    id: "seto-ohashi",
    title: "瀬戸大橋",
    titleEn: "Seto Ohashi Bridge",
    location: "倉敷市児島",
    prefecture: "岡山県",
    prefectureId: "okayama",
    area: "倉敷",
    areaId: "kurashiki-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
      "https://images.unsplash.com/photo-1516534775068-ba3e7458af70?w=1200&q=80",
    ],
    description: "本州と四国を結ぶ鉄道・道路の併用橋。瀬戸内の多島美と橋のシルエットが重なる。",
    longDescription: "1988年に開通した瀬戸大橋は、岡山県倉敷市児島と香川県坂出市を結ぶ全長約13kmの橋梁群。鉄道と道路が重なる2層構造は世界最大級。鷲羽山展望台からの眺望は特に名高く、橋と瀬戸内の島々が重なる景観は日本を代表する絶景のひとつ。夜はライトアップされ、昼間とは全く違う幻想的な姿を見せる。カップルや写真好きには夕景〜夜景の時間帯が狙い目。橋のたもとにある児島はデニムの産地としても有名。",
    tags: ["絶景", "橋", "夜景", "カップル"],
    stayDuration: 60,
    bestTime: "夕方〜夜",
    crowdLevel: "medium",
    budget: "無料（通行料別）",
    access: "JR児島駅からバスで鷲羽山展望台へ",
    rainyDay: false,
    highlights: ["鷲羽山展望台", "夕景・夜景", "瀬戸内の多島美"],
    features: [
      { label: "鷲羽山展望台", text: "橋全体を見渡せる最高のビューポイント。夕日が橋を照らす時間帯を狙う。" },
      { label: "夜景", text: "ライトアップされた橋が水面に映る。岡山夜景のハイライト。" },
    ],
    nearby: ["kurashiki-bikan", "korakuen"],
    mapUrl: "https://maps.google.com/?q=鷲羽山展望台",
    seasonality: ["春", "夏", "秋", "冬"],
    openHours: "見学自由",
  },

  // ── 広島 ──────────────────────────────────────
  {
    id: "atomic-bomb-dome",
    title: "原爆ドーム",
    titleEn: "Atomic Bomb Dome",
    location: "広島市中区大手町",
    prefecture: "広島県",
    prefectureId: "hiroshima",
    area: "広島",
    areaId: "hiroshima-city",
    category: "museum",
    images: [
      "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
      "https://images.unsplash.com/photo-1444731961956-751ed90465a5?w=1200&q=80",
    ],
    description: "1945年8月6日、午前8時15分。廃墟は今も、その朝のまま立っている。",
    longDescription: "1996年にユネスコ世界遺産に登録された原爆ドームは、1945年の原子爆弾投下時に奇跡的に外壁の一部が残った旧広島県産業奨励館の遺構。すぐそばを流れる元安川越しに見るドームの姿は、いつ見ても言葉を失わせる。平和記念公園内の広島平和記念資料館は必ず訪れるべき場所。展示は重いが、見なければわからないことがある。原爆の子の像の前には世界から届いた千羽鶴が絶えない。広島に来た意味を問い続ける旅になる。",
    tags: ["世界遺産", "歴史", "平和", "必訪"],
    stayDuration: 120,
    bestTime: "午前中",
    crowdLevel: "high",
    budget: "無料（資料館¥200）",
    access: "広島電鉄「原爆ドーム前」電停すぐ",
    rainyDay: true,
    highlights: ["原爆ドームの遺構", "平和記念資料館", "原爆の子の像"],
    features: [
      { label: "元安川越しの眺望", text: "川面に映る原爆ドームは静寂の中に重みがある。" },
      { label: "平和記念資料館", text: "広島の経験を伝える資料館。展示が問いかけてくる感覚がある。" },
      { label: "灯籠流し", text: "8月6日の夜、川に灯籠が流れる光景は忘れられない。" },
    ],
    nearby: ["itsukushima-shrine", "onomichi"],
    mapUrl: "https://maps.google.com/?q=原爆ドーム",
    officialUrl: "https://hpmmuseum.jp/",
    openHours: "見学自由（資料館 8:30〜18:00）",
    closedDays: "資料館：12/30〜12/31",
    seasonality: ["春", "夏", "秋", "冬"],
  },
  {
    id: "itsukushima-shrine",
    title: "厳島神社",
    titleEn: "Itsukushima Shrine",
    location: "廿日市市宮島町",
    prefecture: "広島県",
    prefectureId: "hiroshima",
    area: "宮島",
    areaId: "miyajima-area",
    category: "shrine",
    images: [
      "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    ],
    description: "海に浮かぶ大鳥居。満潮時に水面に立つ鳥居は、日本三景のひとつ。",
    longDescription: "宮島に建つ厳島神社は1996年世界遺産に登録された。朱色の大鳥居は満潮時に海に浮かんで見える。干潮時は鳥居まで歩いて近づくことができ、触れることも可能。社殿は海上に建てられた独特の建築で、高潮時は社殿の下まで海水が来る。神の島として崇められてきた宮島には鹿が生息し、紅葉谷公園の紅葉は島全体を赤く染める。もみじ饅頭の食べ比べと、焼きがきは宮島グルメのマスト。最終フェリーに注意。",
    tags: ["世界遺産", "神社", "絶景", "写真映え", "定番"],
    stayDuration: 180,
    bestTime: "満潮前後",
    crowdLevel: "high",
    budget: "¥300",
    access: "JR宮島口駅からフェリー約10分",
    rainyDay: false,
    highlights: ["海に浮かぶ大鳥居", "満潮・干潮の変化", "紅葉谷公園"],
    features: [
      { label: "満潮の大鳥居", text: "水面に浮かぶ鳥居は、満潮2時間前後がベスト。潮位を確認して行くこと。" },
      { label: "干潮時の参拝", text: "社殿の下まで歩ける。鳥居まで歩いて触ると感慨深い。" },
      { label: "もみじ饅頭", text: "揚げもみじ饅頭（天ぷら版）は宮島独自。試食を重ねて好みを探す。" },
    ],
    nearby: ["atomic-bomb-dome", "onomichi"],
    mapUrl: "https://maps.google.com/?q=厳島神社",
    officialUrl: "https://www.itsukushimajinja.jp/",
    openHours: "6:30〜18:00（季節変動あり）",
    closedDays: "無休",
    seasonality: ["春", "秋"],
  },
  {
    id: "onomichi",
    title: "尾道",
    titleEn: "Onomichi",
    location: "尾道市",
    prefecture: "広島県",
    prefectureId: "hiroshima",
    area: "尾道",
    areaId: "onomichi-area",
    category: "street",
    images: [
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
      "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    ],
    description: "坂と猫と文学の街。林芙美子や小津安二郎が愛した路地裏を、今も歩ける。",
    longDescription: "尾道は映画と文学の街として知られる。急勾配の山と海に挟まれた地形が生み出した複雑な路地が、独特の雰囲気を持つ。林芙美子の小説の舞台、小津安二郎の映画のロケ地を歩くのが尾道の楽しみ方。千光寺公園展望台からは瀬戸内海と向島を望む絶景が広がる。ロープウェイで上るのが楽だが、猫の小道を歩いて登るのが尾道流。猫に遭遇しながら、古寺のある急坂を歩く時間は旅の中で特別な記憶になる。",
    tags: ["街歩き", "猫", "文学", "絶景", "瀬戸内"],
    stayDuration: 180,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "無料〜",
    access: "JR尾道駅から徒歩圏内",
    rainyDay: false,
    highlights: ["千光寺公園展望台", "猫の小道", "古寺めぐり"],
    features: [
      { label: "猫の小道", text: "坂道の途中に猫が多数生息。写真を撮りながら登るのが正解。" },
      { label: "千光寺公園", text: "尾道の眺望の核心。天気のいい日に必ず上がること。" },
      { label: "文学のこみち", text: "尾道ゆかりの文人の文学碑が並ぶ。文学好きには聖地。" },
    ],
    nearby: ["shimanami-kaido", "atomic-bomb-dome"],
    mapUrl: "https://maps.google.com/?q=尾道",
    officialUrl: "https://www.ononavi.jp/",
    openHours: "散策自由",
    seasonality: ["春", "秋"],
  },
  {
    id: "shimanami-kaido",
    title: "しまなみ海道",
    titleEn: "Shimanami Kaido",
    location: "広島県尾道市〜愛媛県今治市",
    prefecture: "広島県",
    prefectureId: "hiroshima",
    area: "尾道〜今治",
    areaId: "shimanami-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
      "https://images.unsplash.com/photo-1516534775068-ba3e7458af70?w=1200&q=80",
    ],
    description: "瀬戸内を渡る70kmの自転車道。世界のサイクリストが目指す海の絶景ルート。",
    longDescription: "本州（尾道）と四国（今治）を結ぶ全長約70kmのしまなみ海道は、世界最高峰のサイクリングロードのひとつとして知られる。6つの橋と7つの島を繋ぐ専用自転車道が整備されており、レンタサイクルで島から島へ渡れる。サンライズ糸山（今治）や尾道の各レンタサイクルターミナルで乗り捨て可能。多々羅大橋の上から見る多島美は絶品。全部走らなくても、大三島だけ渡るプチしまなみも大人気。大山祇神社は全国武将が奉納した武具が揃う必見スポット。",
    tags: ["サイクリング", "絶景", "瀬戸内", "アクティビティ"],
    stayDuration: 360,
    bestTime: "4月〜11月",
    crowdLevel: "medium",
    budget: "¥1,000〜（レンタサイクル）",
    access: "JR尾道駅またはJR今治駅から",
    rainyDay: false,
    highlights: ["多々羅大橋", "大山祇神社", "各島の地産品"],
    features: [
      { label: "多々羅大橋", text: "斜張橋の美しいシルエット。橋の上からの多島美が最高。" },
      { label: "大山祇神社", text: "大三島にある全国の武将が刀剣を奉納した古社。国宝多数。" },
      { label: "レンタサイクル", text: "島間の乗り捨てOK。体力に合わせて区間を選んで走れる。" },
    ],
    nearby: ["onomichi", "shimanami-imabari"],
    mapUrl: "https://maps.google.com/?q=しまなみ海道",
    officialUrl: "https://shimanami-cycle.or.jp/",
    seasonality: ["春", "夏", "秋"],
    openHours: "自由",
  },

  // ── 山口 ──────────────────────────────────────
  {
    id: "tsunoshima-bridge",
    title: "角島大橋",
    titleEn: "Tsunoshima Bridge",
    location: "下関市豊北町",
    prefecture: "山口県",
    prefectureId: "yamaguchi",
    area: "下関",
    areaId: "shimonoseki-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
      "https://images.unsplash.com/photo-1516534775068-ba3e7458af70?w=1200&q=80",
    ],
    description: "コマーシャルで一躍有名になった角島大橋。エメラルドグリーンの海上を渡る橋。",
    longDescription: "山口県下関市の北西端、日本海に浮かぶ角島へ渡る全長1,780mの橋。橋の両側に広がるエメラルドグリーンの海は、沖縄と見まがうほどの透明度を誇る。無料で渡れることも人気の理由。展望台（夢崎波の公園）から橋と海を俯瞰するのが定番の撮影ポイント。角島に渡ってさらに先にある角島灯台は明治時代の石造りで、灯台百選のひとつ。夏の青い海・青い空とのコントラストは圧巻。",
    tags: ["絶景", "橋", "海", "写真映え", "ドライブ"],
    stayDuration: 90,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "無料",
    access: "JR特牛駅からタクシー約15分",
    rainyDay: false,
    highlights: ["橋俯瞰の展望台", "エメラルドグリーンの海", "角島灯台"],
    features: [
      { label: "夢崎波の公園", text: "角島大橋を見下ろす最高のビューポイント。橋+海の構図が完璧。" },
      { label: "角島灯台", text: "明治9年建造の石造り灯台。角島の先端に立つ。" },
    ],
    nearby: ["akiyoshi-cave", "kintaikyo"],
    mapUrl: "https://maps.google.com/?q=角島大橋",
    seasonality: ["春", "夏", "秋"],
    openHours: "通行自由（24時間）",
  },
  {
    id: "akiyoshi-cave",
    title: "秋芳洞",
    titleEn: "Akiyoshido Cave",
    location: "美祢市秋芳町",
    prefecture: "山口県",
    prefectureId: "yamaguchi",
    area: "美祢",
    areaId: "mine-area",
    category: "other",
    images: [
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
    ],
    description: "東洋最大級の鍾乳洞。地底に広がる異世界は、夏の涼スポットとしても名高い。",
    longDescription: "秋吉台国定公園内にある秋芳洞は、総延長11.2km（一般公開約1km）の国内最大級の鍾乳洞。年間を通して洞内温度が17℃に保たれており、夏は涼しく冬は暖かい。百枚皿・千畳敷・黄金柱など見どころが多く、ライトアップされた石灰石の造形美は圧巻。地上には秋吉台のカルスト台地が広がり、草原に無数の岩塊が点在する独特の景観は「日本のカルスト」と称される。洞窟内は濡れた石畳があるのでスニーカーが必須。",
    tags: ["鍾乳洞", "自然", "涼スポット", "観光"],
    stayDuration: 90,
    bestTime: "夏（涼しい）",
    crowdLevel: "medium",
    budget: "¥1,300",
    access: "JR新山口駅からバス約1時間",
    rainyDay: true,
    highlights: ["千畳敷", "百枚皿", "秋吉台カルスト台地"],
    features: [
      { label: "千畳敷", text: "最大の広間。天井まで30mある圧倒的な空間。" },
      { label: "百枚皿", text: "棚田状に並んだ石灰石の棚。自然が作り出した幾何学模様。" },
      { label: "秋吉台", text: "洞の上に広がるカルスト台地。春は野焼き後の緑が美しい。" },
    ],
    nearby: ["tsunoshima-bridge", "kintaikyo"],
    mapUrl: "https://maps.google.com/?q=秋芳洞",
    officialUrl: "https://www.akiyoshido.jp/",
    openHours: "8:30〜17:30",
    closedDays: "無休",
  },
  {
    id: "kintaikyo",
    title: "錦帯橋",
    titleEn: "Kintaikyo Bridge",
    location: "岩国市横山",
    prefecture: "山口県",
    prefectureId: "yamaguchi",
    area: "岩国",
    areaId: "iwakuni-area",
    category: "other",
    images: [
      "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200&q=80",
      "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    ],
    description: "5連アーチの木造橋。錦川を渡るその曲線は、日本三名橋のひとつに数えられる。",
    longDescription: "1673年に創建された錦帯橋は、全長193.3mの5連木造アーチ橋。日本三名橋のひとつに数えられ、春は桜・夏は鵜飼・秋は紅葉・冬は雪景色と四季を通じて異なる表情を見せる。橋の強度を上げるためにくぎを一本も使わず、木と鉄の組み合わせで設計された匠の技が見もの。川沿いにある吉香公園では城山（横山城）へのロープウェイが出ており、山頂からは錦帯橋と岩国市街が一望できる。岩国の白蛇館も見どころのひとつ。",
    tags: ["橋", "歴史", "桜", "絶景"],
    stayDuration: 90,
    bestTime: "4月（桜）・秋",
    crowdLevel: "medium",
    budget: "¥310",
    access: "JR岩国駅からバス約20分",
    rainyDay: false,
    highlights: ["5連アーチ", "春の桜並木", "城山からの眺望"],
    features: [
      { label: "春の桜", text: "橋周辺の約3,000本の桜が咲く。錦帯橋と桜の組み合わせは絵になる。" },
      { label: "ロープウェイ", text: "城山（横山城）へのロープウェイ。橋を上から見下ろせる。" },
    ],
    nearby: ["tsunoshima-bridge", "akiyoshi-cave"],
    mapUrl: "https://maps.google.com/?q=錦帯橋",
    officialUrl: "https://kintaikyo.iwakuni-city.net/",
    openHours: "通行自由（8:00〜17:00に通行料徴収）",
    closedDays: "無休",
    seasonality: ["春", "夏", "秋", "冬"],
  },

  // ── 徳島 ──────────────────────────────────────
  {
    id: "iya-valley",
    title: "祖谷渓",
    titleEn: "Iya Valley",
    location: "三好市西祖谷山村",
    prefecture: "徳島県",
    prefectureId: "tokushima",
    area: "三好",
    areaId: "miyoshi-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
    ],
    description: "平家の落人が隠れ住んだ深山幽谷。霧に包まれた山の中に、かずら橋が架かる。",
    longDescription: "四国の山奥、標高1,000m前後の急峻な山々に囲まれた秘境・祖谷渓。平家の落人伝説が残り、かつては「秘境三大渓谷」のひとつに数えられた。シラクチカズラで編まれたかずら橋は全長45m、揺れる橋の隙間から下を覗くと足がすくむ。秋の紅葉期に霧が出る朝は、日本の原風景そのものの景観が広がる。近年は隈研吾設計の「祖谷のかずら橋」周辺リニューアルで訪問しやすくなった。温泉もあり、日帰り入浴が可能。",
    tags: ["秘境", "自然", "紅葉", "スリル"],
    stayDuration: 120,
    bestTime: "秋の紅葉期",
    crowdLevel: "low",
    budget: "¥550（かずら橋）",
    access: "JR大歩危駅からバス約30分",
    rainyDay: false,
    highlights: ["かずら橋", "祖谷渓の断崖", "霧の朝"],
    features: [
      { label: "かずら橋", text: "シラクチカズラで編まれた橋。揺れながら渡る緊張感が本物。" },
      { label: "秋の霧", text: "朝霧に包まれた渓谷の景色は、写真では伝わらない。早起きして訪れる価値がある。" },
    ],
    nearby: ["naruto-whirlpools", "oboke-koboke"],
    mapUrl: "https://maps.google.com/?q=祖谷渓",
    officialUrl: "https://www.miyoshi-tourism.jp/",
    openHours: "かずら橋 7:00〜18:00（季節変動あり）",
    closedDays: "無休",
    seasonality: ["春", "秋"],
  },
  {
    id: "naruto-whirlpools",
    title: "鳴門の渦潮",
    titleEn: "Naruto Whirlpools",
    location: "鳴門市鳴門町",
    prefecture: "徳島県",
    prefectureId: "tokushima",
    area: "鳴門",
    areaId: "naruto-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
      "https://images.unsplash.com/photo-1516534775068-ba3e7458af70?w=1200&q=80",
    ],
    description: "潮流が作り出す世界最大級の渦潮。大潮の日、鳴門海峡は轟音とともに海が渦を巻く。",
    longDescription: "淡路島と四国の間、鳴門海峡では太平洋と瀬戸内海の潮流がぶつかり合い、最大直径30mに達する世界最大規模の渦潮が発生する。大鳴門橋の橋桁内の遊歩道「渦の道」からはガラスの床越しに渦潮を見下ろせる。観潮船に乗ると渦のすぐそばまで近づくことができ、潮の流れる音が体に響く迫力は本物。渦潮の大きさは大潮・中潮・小潮で大きく変わるため、潮見表を確認してから行くことが必須。",
    tags: ["自然", "絶景", "海", "迫力"],
    stayDuration: 90,
    bestTime: "大潮の干満前後",
    crowdLevel: "medium",
    budget: "¥510（渦の道）",
    access: "JR鳴門駅からバス約30分",
    rainyDay: true,
    highlights: ["渦の道（橋上展望）", "観潮船", "大鳴門橋"],
    features: [
      { label: "渦の道", text: "橋桁内の遊歩道。ガラス越しに真下の渦潮を見られる。" },
      { label: "観潮船", text: "渦のすぐそばを航行する。迫力と潮の匂いが生々しい。" },
    ],
    nearby: ["iya-valley", "oboke-koboke"],
    mapUrl: "https://maps.google.com/?q=鳴門渦潮",
    officialUrl: "https://www.uzushio.com/",
    openHours: "渦の道 9:00〜18:00（季節変動あり）",
    closedDays: "荒天時",
  },
  {
    id: "oboke-koboke",
    title: "大歩危小歩危",
    titleEn: "Oboke Koboke Gorge",
    location: "三好市山城町",
    prefecture: "徳島県",
    prefectureId: "tokushima",
    area: "三好",
    areaId: "miyoshi-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
    ],
    description: "吉野川が2億年の時をかけて削った峡谷。ラフティングで水面から渓谷美を体感する。",
    longDescription: "吉野川が結晶片岩を削ってできた大歩危・小歩危峡谷は、四国随一の渓谷美として知られる。「大股で歩いても危険」「小股で歩いても危険」という地名の由来通り、急峻な断崖が続く。遊覧船で川面から見上げる岩肌は圧倒的。ラフティングは日本有数の激流として知られ、国内外から愛好者が集まる。春は桜、秋は紅葉が渓谷美を彩る。祖谷渓への入口でもあり、ラフティングと祖谷渓を合わせて1泊2日で楽しむのが定番。",
    tags: ["渓谷", "ラフティング", "自然", "秘境"],
    stayDuration: 180,
    bestTime: "4月〜11月",
    crowdLevel: "low",
    budget: "¥1,200〜（遊覧船）",
    access: "JR大歩危駅下車すぐ",
    rainyDay: false,
    highlights: ["遊覧船", "ラフティング", "秋の紅葉"],
    features: [
      { label: "遊覧船", text: "約30分のクルーズ。川面から見上げる岩壁は迫力満点。" },
      { label: "ラフティング", text: "国内屈指の激流。水温は冷たいが夏でも爽快。" },
    ],
    nearby: ["iya-valley", "naruto-whirlpools"],
    mapUrl: "https://maps.google.com/?q=大歩危",
    officialUrl: "https://www.miyoshi-tourism.jp/",
    openHours: "遊覧船 9:00〜17:00",
    closedDays: "荒天時",
    seasonality: ["春", "夏", "秋"],
  },

  // ── 香川 ──────────────────────────────────────
  {
    id: "kotohira-gu",
    title: "金刀比羅宮",
    titleEn: "Kotohira-gu Shrine",
    location: "仲多度郡琴平町",
    prefecture: "香川県",
    prefectureId: "kagawa",
    area: "琴平",
    areaId: "kotohira-area",
    category: "shrine",
    images: [
      "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    ],
    description: "「こんぴらさん」。本宮まで785段、奥社まで1,368段の石段が待ち受ける。",
    longDescription: "「こんぴらさん」として親しまれる金刀比羅宮は、海の神様として全国の船乗りや漁師から崇められてきた。表参道から本宮まで785段の石段は、杖を借りながら登るのが一般的。途中の旭社は国の重要文化財で、装飾の細かさに足が止まる。本宮からの琴平平野の眺めは達成感とセットで格別。奥社まで行く人は少ないが、583段を更に登り切ったあとの静寂は本殿とは違う神聖さがある。名物の灸まんや参道の醤油豆も忘れずに。",
    tags: ["神社", "石段", "パワースポット", "達成感"],
    stayDuration: 180,
    bestTime: "午前中",
    crowdLevel: "high",
    budget: "無料",
    access: "JR琴平駅から徒歩約15分（参道まで）",
    rainyDay: false,
    highlights: ["785段の石段", "本宮からの眺望", "奥社"],
    features: [
      { label: "石段", text: "本宮まで785段。途中の旭社で一息つきつつ、登り続ける価値がある。" },
      { label: "本宮からの眺め", text: "達成感とともに眺める讃岐平野は格別。" },
      { label: "奥社", text: "さらに583段上の最高地点。訪れる人は少なく、静寂がある。" },
    ],
    nearby: ["ritsurin-garden", "shodoshima"],
    mapUrl: "https://maps.google.com/?q=金刀比羅宮",
    officialUrl: "https://www.konpira.or.jp/",
    openHours: "6:00〜18:00",
    closedDays: "無休",
    seasonality: ["春", "秋"],
  },
  {
    id: "ritsurin-garden",
    title: "栗林公園",
    titleEn: "Ritsurin Garden",
    location: "高松市栗林町",
    prefecture: "香川県",
    prefectureId: "kagawa",
    area: "高松",
    areaId: "takamatsu-area",
    category: "garden",
    images: [
      "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
      "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    ],
    description: "ミシュラン三ツ星の庭園。讃岐松を背景に築かれた大名庭園の傑作。",
    longDescription: "高松藩主が100年以上かけて完成させた大名庭園・栗林公園は、ミシュラン・グリーンガイドで三ツ星を獲得した庭園。国の特別名勝にも指定されている。背後の紫雲山を借景にした6つの池と13の築山が絶妙に配置され、回遊すると常に違う景色が現れる。朝の開園直後は光が柔らかく、池に映る松の影が美しい。讃岐民芸館も園内にあり、郷土工芸品を鑑賞できる。高松空港から近く、四国上陸の最初の目的地にも最適。",
    tags: ["庭園", "国特別名勝", "ミシュラン", "散歩"],
    stayDuration: 120,
    bestTime: "早朝",
    crowdLevel: "medium",
    budget: "¥410",
    access: "JR栗林公園北口駅から徒歩3分",
    rainyDay: false,
    highlights: ["南湖・北湖", "偃月橋", "借景の紫雲山"],
    features: [
      { label: "偃月橋", text: "反り橋越しに庭園を眺める定番アングル。朝の光が最も美しい。" },
      { label: "借景", text: "背後の紫雲山が庭園の奥行きを無限に広げる。日本庭園の真骨頂。" },
    ],
    nearby: ["kotohira-gu", "shodoshima"],
    mapUrl: "https://maps.google.com/?q=栗林公園",
    officialUrl: "https://ritsuringarden.jp/",
    openHours: "日の出〜日没（季節変動）",
    closedDays: "無休",
    seasonality: ["春", "秋"],
  },
  {
    id: "shodoshima",
    title: "小豆島",
    titleEn: "Shodoshima Island",
    location: "小豆郡小豆島町・土庄町",
    prefecture: "香川県",
    prefectureId: "kagawa",
    area: "小豆島",
    areaId: "shodoshima-area",
    category: "other",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
      "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    ],
    description: "オリーブ・そうめん・醤油の島。日本のエーゲ海と呼ばれる美しい海岸線がある。",
    longDescription: "日本のオリーブ栽培発祥の地・小豆島は、温暖な気候と穏やかな瀬戸内海に囲まれた島。オリーブ公園のギリシャ風車はSNSで人気を博しており、オリーブのほうきを持って写真を撮るのが定番。日本三大渓谷美の寒霞渓からは紅葉期に絶景が広がる。手延べそうめんの工場見学と醤油の手作り体験が体験型観光として充実。映画「二十四の瞳」の舞台としても有名で、岬の分教場は昭和の小学校がそのまま残る。",
    tags: ["島旅", "グルメ", "オリーブ", "自然"],
    stayDuration: 360,
    bestTime: "10月〜11月（紅葉）",
    crowdLevel: "medium",
    budget: "¥2,000〜",
    access: "高松港からフェリー約1時間",
    rainyDay: true,
    highlights: ["オリーブ公園", "寒霞渓", "エンジェルロード"],
    features: [
      { label: "オリーブ公園", text: "ギリシャ風車とオリーブ畑。SNS映えを狙うなら朝が正解。" },
      { label: "寒霞渓", text: "日本三大渓谷美。ロープウェイで紅葉を俯瞰する。" },
      { label: "エンジェルロード", text: "干潮時に道が現れる砂の道。手を繋いで渡ると願いが叶うとか。" },
    ],
    nearby: ["naoshima", "ritsurin-garden"],
    mapUrl: "https://maps.google.com/?q=小豆島",
    officialUrl: "https://www.shodoshima.or.jp/",
    seasonality: ["春", "夏", "秋"],
    openHours: "島内自由",
  },
  {
    id: "naoshima",
    title: "直島",
    titleEn: "Naoshima Island",
    location: "香川郡直島町",
    prefecture: "香川県",
    prefectureId: "kagawa",
    area: "直島",
    areaId: "naoshima-area",
    category: "museum",
    images: [
      "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200&q=80",
      "https://images.unsplash.com/photo-1533050487297-09b450131914?w=1200&q=80",
    ],
    description: "現代アートが島全体に溶け込む、瀬戸内海の美術島。草間彌生の黄色いカボチャが迎える。",
    longDescription: "ベネッセホールディングスと建築家・安藤忠雄が中心となって整備した現代アートの島。地中美術館はクロード・モネ・ジェームズ・タレルらの作品を自然光の中で展示する。家プロジェクトは島の古民家の中にアート作品が組み込まれており、島全体がギャラリー。草間彌生の「赤かぼちゃ」「黄かぼちゃ」は直島のシンボル。世界のアートファンが訪れる日本有数のアート聖地で、週末は早めに動かないとチケットが売り切れる。",
    tags: ["現代アート", "島旅", "建築", "文化"],
    stayDuration: 360,
    bestTime: "平日",
    crowdLevel: "high",
    budget: "¥2,100〜（地中美術館）",
    access: "高松港からフェリー約1時間",
    rainyDay: true,
    highlights: ["地中美術館", "家プロジェクト", "草間彌生の黄かぼちゃ"],
    features: [
      { label: "地中美術館", text: "安藤忠雄設計の地下美術館。モネの大睡蓮が自然光の中に置かれる。" },
      { label: "家プロジェクト", text: "古民家の中のアート。島を歩きながら点在する7棟を巡る。" },
      { label: "黄かぼちゃ", text: "波止場近くの桟橋に置かれた草間彌生の作品。フォトスポットの定番。" },
    ],
    nearby: ["shodoshima", "ritsurin-garden"],
    mapUrl: "https://maps.google.com/?q=直島香川",
    officialUrl: "https://benesse-artsite.jp/",
    openHours: "地中美術館 10:00〜18:00（月曜休）",
    closedDays: "月曜日（祝日の場合翌日）",
    seasonality: ["春", "夏", "秋"],
  },

  // ── 愛媛 ──────────────────────────────────────
  {
    id: "dogo-onsen",
    title: "道後温泉",
    titleEn: "Dogo Onsen",
    location: "松山市道後湯之町",
    prefecture: "愛媛県",
    prefectureId: "ehime",
    area: "松山",
    areaId: "matsuyama-area",
    category: "onsen",
    images: [
      "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=80",
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    ],
    description: "日本最古の温泉地。夏目漱石の小説「坊っちゃん」の舞台が今もそのまま残る。",
    longDescription: "3,000年の歴史を誇る日本最古の温泉地・道後温泉。本館「道後温泉本館」は明治27年築の木造3階建てで、宮崎駿の「千と千尋の神隠し」のモデルのひとつとも言われる。現在は改修工事中ながら一部営業中。本館外観のライトアップは夜の必見スポット。夏目漱石が逗留した温泉旅館があることから、「坊っちゃん」の世界観が町全体に浸透している。道後商店街のみかんジュース・蛇口からみかんジュースも話題。",
    tags: ["温泉", "歴史", "文学", "日本三古湯"],
    stayDuration: 120,
    bestTime: "夜",
    crowdLevel: "high",
    budget: "¥460〜",
    access: "JR松山駅から市電約20分「道後温泉」下車",
    rainyDay: true,
    highlights: ["道後温泉本館", "夜のライトアップ", "坊っちゃん列車"],
    features: [
      { label: "本館の夜景", text: "ライトアップされた本館の外観が最も映える時間は日没直後。" },
      { label: "坊っちゃん列車", text: "蒸気機関車を模した市電。松山駅〜道後温泉を結ぶ。" },
      { label: "みかんジュース", text: "商店街の蛇口からみかんジュースが出る。フォトジェニック。" },
    ],
    nearby: ["matsuyama-castle", "shimanami-imabari"],
    mapUrl: "https://maps.google.com/?q=道後温泉",
    officialUrl: "https://dogo.jp/",
    openHours: "6:00〜23:00（施設による）",
    closedDays: "無休",
    seasonality: ["春", "夏", "秋", "冬"],
  },
  {
    id: "matsuyama-castle",
    title: "松山城",
    titleEn: "Matsuyama Castle",
    location: "松山市丸之内",
    prefecture: "愛媛県",
    prefectureId: "ehime",
    area: "松山",
    areaId: "matsuyama-area",
    category: "castle",
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    ],
    description: "現存12天守のひとつ、標高132mの山頂に構える連立式天守。市内随一の眺望を誇る。",
    longDescription: "松山城は標高132mの城山（かつやま）山頂に建つ現存12天守のひとつ。連立式天守群は国の重要文化財。ロープウェイかリフトで山頂まで上がると、松山市街・松山平野・瀬戸内海が一望できる。春は天守と桜の組み合わせが美しく、桜まつり期間中は夜間のライトアップも行われる。城内の展示では松山城の歴史に加え、愛媛の侍文化も紹介される。道後温泉と合わせて、松山の観光の二本柱。",
    tags: ["城", "現存天守", "桜", "絶景"],
    stayDuration: 90,
    bestTime: "4月（桜）",
    crowdLevel: "medium",
    budget: "¥520",
    access: "JR松山駅から市電・徒歩、またはロープウェイ利用",
    rainyDay: true,
    highlights: ["現存天守", "瀬戸内海の眺望", "春の桜"],
    features: [
      { label: "連立式天守", text: "天守・小天守・二重櫓が繋がる構造。内部の複雑さが面白い。" },
      { label: "春の桜", text: "約200本の桜。天守と桜の組み合わせは日本一美しい城景のひとつ。" },
    ],
    nearby: ["dogo-onsen", "shimanami-imabari"],
    mapUrl: "https://maps.google.com/?q=松山城",
    officialUrl: "https://www.matsuyamajo.jp/",
    openHours: "9:00〜17:00（季節変動あり）",
    closedDays: "12/26",
    seasonality: ["春", "夏", "秋", "冬"],
  },
  {
    id: "shimanami-imabari",
    title: "しまなみ海道（今治側）",
    titleEn: "Shimanami Kaido (Imabari Side)",
    location: "今治市",
    prefecture: "愛媛県",
    prefectureId: "ehime",
    area: "今治",
    areaId: "imabari-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
    ],
    description: "今治側から入るしまなみ海道。来島海峡大橋の夕景と、今治タオルの産地を組み合わせる。",
    longDescription: "愛媛・今治はしまなみ海道の四国側の玄関口。来島海峡大橋は世界初の三連吊り橋で、全長4,105m。橋の下を流れる来島海峡の急流は、かつて海上交通の難所として知られた場所。サンライズ糸山展望台から見る橋と海峡の眺めは四国屈指の絶景。今治はタオルの生産地としても日本最大で、今治タオルのファクトリー見学や直売店巡りが楽しめる。しまなみ海道を全線走るスタート・ゴール地点として、今治城も合わせて回るのが定番。",
    tags: ["橋", "絶景", "サイクリング", "産業観光"],
    stayDuration: 180,
    bestTime: "夕方",
    crowdLevel: "medium",
    budget: "無料〜",
    access: "JR今治駅から市内バス",
    rainyDay: false,
    highlights: ["来島海峡大橋", "サンライズ糸山展望台", "今治タオル"],
    features: [
      { label: "来島海峡大橋", text: "世界初の三連吊り橋。自転車で渡ると高さと海流の迫力が伝わる。" },
      { label: "サンライズ糸山", text: "展望台からの夕日と橋のシルエットは西日本屈指の夕景。" },
    ],
    nearby: ["dogo-onsen", "shimanami-kaido"],
    mapUrl: "https://maps.google.com/?q=来島海峡大橋今治",
    officialUrl: "https://www.city.imabari.ehime.jp/",
    openHours: "見学自由",
    seasonality: ["春", "夏", "秋"],
  },

  // ── 高知 ──────────────────────────────────────
  {
    id: "katsurahama",
    title: "桂浜",
    titleEn: "Katsurahama Beach",
    location: "高知市浦戸",
    prefecture: "高知県",
    prefectureId: "kochi",
    area: "高知",
    areaId: "kochi-city",
    category: "beach",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
      "https://images.unsplash.com/photo-1516534775068-ba3e7458af70?w=1200&q=80",
    ],
    description: "坂本龍馬が太平洋を夢見た浜。月の名所として古来から知られる弧を描く砂浜。",
    longDescription: "土佐湾に面する桂浜は、弧を描く砂浜と背後の松林が美しい景勝地。坂本龍馬の銅像が太平洋を見つめる姿は高知の象徴的な光景。月の名所として百人一首にも詠まれ、仲秋の名月の時期には観月会が開かれる。岩場に立つ恋人の聖地・龍王岬は、波しぶきが上がる豪快な景観。坂本龍馬記念館がすぐ近くにあり、幕末の志士の実像を展示で知ることができる。浜では遊泳できないが、波打ち際を散歩するだけで太平洋の雄大さが体に入ってくる。",
    tags: ["海", "歴史", "坂本龍馬", "絶景"],
    stayDuration: 90,
    bestTime: "夕方（月見）",
    crowdLevel: "medium",
    budget: "無料",
    access: "高知駅からバス約40分",
    rainyDay: false,
    highlights: ["坂本龍馬像", "龍王岬", "月の名所"],
    features: [
      { label: "坂本龍馬像", text: "高さ5.3mの銅像が太平洋を見つめる。隣に同じポーズで並ぶ台が人気。" },
      { label: "龍王岬", text: "波が打ち付ける岩場。太平洋の荒々しさを直接感じられる場所。" },
    ],
    nearby: ["shimanto-river", "muroto-cape"],
    mapUrl: "https://maps.google.com/?q=桂浜高知",
    officialUrl: "https://visitkochi.com/",
    openHours: "散策自由",
    seasonality: ["春", "夏", "秋"],
  },
  {
    id: "shimanto-river",
    title: "四万十川",
    titleEn: "Shimanto River",
    location: "四万十市〜高岡郡",
    prefecture: "高知県",
    prefectureId: "kochi",
    area: "四万十",
    areaId: "shimanto-area",
    category: "other",
    images: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
    ],
    description: "日本最後の清流。欄干のない「沈下橋」が川面に低く浮かび、川と共存する暮らしが残る。",
    longDescription: "全長196kmの四万十川は「日本最後の清流」として知られ、大規模なダムがない清流域が今も守られている。川に低く架けられた「沈下橋」は、洪水時に沈むことで流失を防ぐ知恵の産物。欄干がなく川面すれすれを渡る沈下橋は、高知の原風景そのもの。カヌーツーリングやアユ漁の見学ができ、夏の水遊びも最高。沿岸の道の駅では四万十のアユの塩焼きや天然うなぎが味わえる。東京の喧騒とまったく逆の時間が流れる場所。",
    tags: ["清流", "自然", "カヌー", "沈下橋"],
    stayDuration: 360,
    bestTime: "6月〜9月",
    crowdLevel: "low",
    budget: "¥2,000〜（カヌー）",
    access: "JR土佐くろしお鉄道中村駅下車",
    rainyDay: false,
    highlights: ["沈下橋", "カヌー体験", "アユ料理"],
    features: [
      { label: "沈下橋", text: "欄干なし・川面スレスレ。地元の人が日常的に渡る橋。" },
      { label: "カヌーツーリング", text: "半日〜1日で川を下るプログラムが豊富。初心者向けあり。" },
    ],
    nearby: ["katsurahama", "muroto-cape"],
    mapUrl: "https://maps.google.com/?q=四万十川",
    officialUrl: "https://shimanto.city/",
    openHours: "自由",
    seasonality: ["春", "夏", "秋"],
  },
  {
    id: "muroto-cape",
    title: "室戸岬",
    titleEn: "Muroto Cape",
    location: "室戸市室戸岬町",
    prefecture: "高知県",
    prefectureId: "kochi",
    area: "室戸",
    areaId: "muroto-area",
    category: "viewpoint",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
      "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    ],
    description: "空海が悟りを開いた岬。太平洋の荒波が打ち付ける海岸線は、雄大を超えて神聖だ。",
    longDescription: "弘法大師・空海が若き日に修行し、悟りを開いたとされる室戸岬。最御崎寺（ほつみさきじ）は四国八十八箇所の第24番札所。岬の先端には灯台が立ち、太平洋の荒波が打ち付ける岩場は他に類を見ない迫力がある。室戸ジオパークはユネスコ世界ジオパークに認定されており、海岸に露出した地層は大陸移動の証を見せてくれる。地球の歴史と弘法大師の伝説が重なる場所。高知市から約2時間の距離にあるが、来る価値が確かにある端っこ。",
    tags: ["絶景", "パワースポット", "ジオパーク", "四国遍路"],
    stayDuration: 90,
    bestTime: "早朝",
    crowdLevel: "low",
    budget: "無料",
    access: "高知駅から路線バス約2時間半",
    rainyDay: false,
    highlights: ["灯台と太平洋", "最御崎寺", "室戸ジオパーク"],
    features: [
      { label: "室戸岬灯台", text: "岬の先端に立つ灯台。夜明けの太平洋を見るために早起きする価値がある。" },
      { label: "ジオパーク", text: "海岸の地層が地球の歴史を語る。ガイドツアーで理解が深まる。" },
    ],
    nearby: ["katsurahama", "shimanto-river"],
    mapUrl: "https://maps.google.com/?q=室戸岬",
    officialUrl: "https://muroto-geo.jp/",
    openHours: "見学自由",
    seasonality: ["春", "夏", "秋", "冬"],
  },
];
