import { Spot } from "@/types/spot";

export const hokkaidoTohokuSpots: Spot[] = [
  // ── 北海道 ──────────────────────────────────────
  {
    id: "otaru-canal",
    title: "小樽運河",
    location: "小樽市色内",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "小樽",
    areaId: "otaru",
    category: "street",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Otaru_Canal_Hokkaido_Japan01bs5.jpg/1280px-Otaru_Canal_Hokkaido_Japan01bs5.jpg"],
    description: "石造り倉庫と瓦斯燈が水面に映える、北海道ロマンの原点。",
    longDescription: "明治末期に開削された全長1140mの運河は、北海道の海運史そのものだ。夜間のガス燈点灯は17時から翌朝5時まで続き、石畳の遊歩道を歩く人影がオレンジ色に滲む。南倉庫群を改装した飲食店が並ぶエリアでは、小樽産の鮭やウニを使った海鮮丼が1,200円前後から食べられる。冬の雪景色は観光写真では追いつかないほど美しく、地吹雪越しに見る運河は一枚の水墨画だ。堺町本通りのルタオ本店でダブルフロマージュを買い、運河沿いのベンチで食べる、というのが現地民の正解ルートである。",
    tags: ["運河", "夜景", "レトロ", "グルメ", "写真映え"],
    stayDuration: 90,
    bestTime: "夕方〜夜 17:00〜20:00",
    crowdLevel: "medium",
    budget: "無料（飲食別）",
    access: "JR小樽駅から徒歩10分",
    rainyDay: true,
    highlights: ["石造り倉庫群", "ガス燈点灯の夜景", "堺町本通りのスイーツ"],
    features: [
      { label: "ガス燈の夜景", text: "63基のガス燈が水面を照らす。撮影はf2.8以下推奨、ISO800で十分。" },
      { label: "倉庫街のグルメ", text: "北一ホールや小樽ビールは倉庫改装店舗の代表格。夕食の候補筆頭。" },
      { label: "堺町本通り", text: "ルタオ、北菓楼、六花亭が並ぶ。お土産はここで一括購入が効率的。" },
    ],
    nearby: ["hakodate-yama", "sapporo-tokeidai"],
    relatedArticles: [],
  },
  {
    id: "hakodate-yama",
    title: "函館山",
    location: "函館市函館山",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "函館",
    areaId: "hakodate",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Hakodate_night_view01s3.jpg/1280px-Hakodate_night_view01s3.jpg"],
    description: "世界三大夜景のひとつ。くびれた半島に広がる光の海。",
    longDescription: "334mの山頂から見下ろす函館の夜景は、津軽海峡と函館湾に挟まれた細いくびれが特徴的で、ナポリ、香港と並ぶ世界三大夜景に数えられる。日没20分後が最も美しく、空と街の明かりの比率が絶妙になる時間帯だ。ロープウェイは片道1,500円、山頂は気温が3〜5度低いので防寒必須。麓の元町エリアには明治期の洋館が点在し、旧函館区公会堂（入場300円）の青とクリーム色の外壁は函館を象徴する風景だ。翌朝は朝市で海鮮丼を食べる流れが鉄板コースである。",
    tags: ["夜景", "展望", "ロープウェイ", "世界三大", "カップル"],
    stayDuration: 60,
    bestTime: "日没直後 19:00〜21:00",
    crowdLevel: "high",
    budget: "¥1,500（ロープウェイ）",
    access: "函館駅からバスで約30分、函館山ロープウェイ山麓駅下車",
    rainyDay: false,
    highlights: ["山頂からの夜景", "元町の洋館群", "朝市の海鮮"],
    features: [
      { label: "夜景のタイミング", text: "日没後20分が空と街の境界が溶ける黄金時間。混雑前に場所取りを。" },
      { label: "元町散歩", text: "旧函館区公会堂と八幡坂を組み合わせると撮影スポットが密集する。" },
    ],
    nearby: ["otaru-canal", "niseko"],
    relatedArticles: [],
  },
  {
    id: "furano-lavender",
    title: "富良野ラベンダー畑",
    location: "富良野市中御料",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "富良野・美瑛",
    areaId: "furano-biei",
    category: "park",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Furano_lavender01s3.jpg/1280px-Furano_lavender01s3.jpg"],
    description: "7月、紫の波が丘を覆う。日本でここだけの景色。",
    longDescription: "ファーム富田のラベンダーは7月中旬〜下旬が見頃で、早咲き・遅咲き含めると6月下旬から8月上旬まで楽しめる。倖の畑から見下ろすと、紫・白・ピンクのラベンダーが縞状に広がり、奥に十勝岳連峰が連なる構図は額縁絵画そのものだ。入場無料という太っ腹な施設で、ラベンダーソフト（400円）は香りが口に残る。6月には「ラベンダーイースト」でも鑑賞できる。早朝6時の光の柔らかさと朝露を帯びた花は、正午の観光客ラッシュとは別世界の静けさを持っている。",
    tags: ["ラベンダー", "夏", "フラワー", "北海道らしい", "写真映え"],
    stayDuration: 120,
    bestTime: "7月中旬〜下旬、早朝6:00〜8:00",
    crowdLevel: "high",
    budget: "無料",
    access: "JR富良野線 中富良野駅から徒歩20分、またはレンタカー",
    rainyDay: false,
    highlights: ["倖の畑の全景", "ラベンダーソフトクリーム", "十勝岳連峰との共演"],
    features: [
      { label: "ファーム富田", text: "入場無料のラベンダー農場。7月は敷地全体が紫に染まる。" },
      { label: "早朝訪問", text: "6時台は観光バスが来ない。光が柔らかく、写真の質が劇的に変わる。" },
      { label: "香りグッズ", text: "ファーム富田のラベンダー精油は品質が高く、土産として最高。" },
    ],
    nearby: ["biei-blue-pond", "asahiyama-zoo"],
    relatedArticles: [],
  },
  {
    id: "biei-blue-pond",
    title: "美瑛青い池",
    location: "上川郡美瑛町白金",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "富良野・美瑛",
    areaId: "furano-biei",
    category: "park",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Biei_Blue_Pond_2019.jpg/1280px-Biei_Blue_Pond_2019.jpg"],
    description: "コバルトブルーの水面が立ち枯れた白樺を映す、偶然が生んだ絶景。",
    longDescription: "十勝岳噴火の泥流対策として作られた堰堤に水が溜まったのが「青い池」の始まりで、水中のコロイド状の水酸化アルミニウムが青色散乱を起こす。Appleのデスクトップ壁紙に採用されて世界的に知られた。5月から10月は水色が最も濃く、冬季は結氷してライトアップが行われる（18:00〜21:30）。駐車場は500円。立ち枯れた白樺の木と青い水の組み合わせは季節を問わず絵になる。白金温泉（5km）と組み合わせると、日帰り旅が一泊分の充実度になる。",
    tags: ["絶景", "写真映え", "池", "神秘的", "SNS映え"],
    stayDuration: 60,
    bestTime: "5月〜10月 午前中",
    crowdLevel: "high",
    budget: "無料（駐車場¥500）",
    access: "JR旭川駅からバス「白金線」で白金青い池入口下車（約90分）",
    rainyDay: false,
    highlights: ["コバルトブルーの水面", "立ち枯れ白樺", "冬季ライトアップ"],
    features: [
      { label: "青さの仕組み", text: "水酸化アルミニウムのコロイドが青色光を散乱させる。濁りではなく化学現象。" },
      { label: "冬季ライトアップ", text: "12月〜3月の夜間は幻想的な青い水面が闇に浮かぶ。三脚必携。" },
    ],
    nearby: ["furano-lavender", "asahiyama-zoo"],
    relatedArticles: [],
  },
  {
    id: "asahiyama-zoo",
    title: "旭山動物園",
    location: "旭川市東旭川町倉沼",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "旭川",
    areaId: "asahikawa",
    category: "other",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Asahikawa07s3200.jpg/1280px-Asahikawa07s3200.jpg"],
    description: "行動展示で有名。ペンギンが空を泳ぎ、ホッキョクグマが海を渡る動物園。",
    longDescription: "全国最北の動物園でありながら、行動展示の革命的アイデアで年間300万人を動員した。ペンギンが頭上を飛ぶ「ペンギンとびさんぽ」（冬季11月〜3月）は1日3回、雪道を行進するペンギンを間近で見られる。ホッキョクグマ館の水中トンネルは熊が泳ぐ姿を真下から観察できる唯一の施設。日本国内でアムールトラの繁殖に成功している。入園料820円は破格のコストパフォーマンス。朝10時開園直後が動物の活動時間で、閉園の17時まで1日では足りないほど見どころが多い。",
    tags: ["動物園", "家族", "ペンギン", "冬季", "行動展示"],
    stayDuration: 240,
    bestTime: "開園直後 10:00〜12:00",
    crowdLevel: "medium",
    budget: "¥820",
    access: "JR旭川駅からバス「旭山動物園行き」で終点下車（約40分）",
    rainyDay: true,
    highlights: ["ペンギンとびさんぽ（冬季）", "ホッキョクグマ館水中トンネル", "アムールトラ"],
    features: [
      { label: "ペンギンとびさんぽ", text: "冬季限定。ペンギンが雪道を行進する姿は日本一かわいい光景。" },
      { label: "行動展示", text: "動物の自然な行動が見られる展示方式。国内動物園のモデルケース。" },
    ],
    nearby: ["biei-blue-pond", "furano-lavender"],
    relatedArticles: [],
  },
  {
    id: "sapporo-tokeidai",
    title: "札幌時計台",
    location: "札幌市中央区北1条西2丁目",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "札幌",
    areaId: "sapporo",
    category: "museum",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Sapporo-clocktower01.JPG/1280px-Sapporo-clocktower01.JPG"],
    description: "日本三大がっかり名所の一角。でも中の歴史展示は意外とおもしろい。",
    longDescription: "1878年建設の旧札幌農学校演武場は、現存する時計塔として日本最古級。「がっかりスポット」として名高いのは、周囲の高層ビルに囲まれて時計台が小さく見えるためだが、写真アングルを工夫すればビル群を排除した絵が撮れる。内部の歴史展示（200円）は北海道開拓とクラーク博士の思想を深く掘り下げており、1時間で見られる良質なコンテンツだ。正時に鳴る時計の音は意外に大きく、周辺のビジネスマンも振り向く。大通公園まで徒歩5分圏内に位置し、午前の散歩コースとして最適。",
    tags: ["歴史", "北海道開拓", "定番", "街歩き"],
    stayDuration: 45,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "¥200",
    access: "地下鉄大通駅から徒歩5分",
    rainyDay: true,
    highlights: ["時計塔の鐘の音", "歴史展示", "外観撮影スポット"],
    features: [
      { label: "撮影のコツ", text: "正面左斜め45度、ビルを排除できる角度がある。三脚不要、スマホで十分。" },
      { label: "内部展示", text: "クラーク博士とホーレス・ケプロンの開拓思想が丁寧に解説されている。" },
    ],
    nearby: ["odori-park", "otaru-canal"],
    relatedArticles: [],
  },
  {
    id: "odori-park",
    title: "大通公園",
    location: "札幌市中央区大通西1〜12丁目",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "札幌",
    areaId: "sapporo",
    category: "park",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Odori_Park_Sapporo.jpg/1280px-Odori_Park_Sapporo.jpg"],
    description: "東西1.5km、街の真ん中にある緑の軸。雪まつりの会場でもある。",
    longDescription: "幅65m、延長1.5kmの細長い公園は、テレビ塔から西の12丁目まで続く。2月の「さっぽろ雪まつり」はここが主会場となり、6〜8mの大雪像が並ぶ期間中は200万人以上が訪れる。夏の「ビアガーデン」は7月中旬から8月下旬まで続き、各丁目ごとに異なるビールブランドがテントを出す。秋のライラック祭りと紅葉、冬の雪まつりとホワイトイルミネーションと、年間を通じてイベントが絶えない。テレビ塔展望台（720円）から見下ろすと公園の全体像が把握できる。",
    tags: ["公園", "雪まつり", "ビアガーデン", "季節イベント", "札幌"],
    stayDuration: 60,
    bestTime: "2月（雪まつり）または7〜8月（ビアガーデン）",
    crowdLevel: "high",
    budget: "無料",
    access: "地下鉄大通駅すぐ",
    rainyDay: false,
    highlights: ["さっぽろ雪まつり会場", "夏のビアガーデン", "テレビ塔からの眺め"],
    features: [
      { label: "雪まつり", text: "2月上旬開催。大雪像は設計から制作まで数ヶ月かかる芸術作品。" },
      { label: "ビアガーデン", text: "サッポロ・アサヒ・キリン・サントリーが丁目ごとに展開。1杯600円から。" },
    ],
    nearby: ["sapporo-tokeidai", "otaru-canal"],
    relatedArticles: [],
  },
  {
    id: "noboribetsu-onsen",
    title: "登別温泉",
    location: "登別市登別温泉町",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "登別",
    areaId: "noboribetsu",
    category: "onsen",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Noboribetsu_jigokudani01s3.jpg/1280px-Noboribetsu_jigokudani01s3.jpg"],
    description: "9種の泉質が湧出する「地獄谷」は、北海道最大の温泉地の名刺代わり。",
    longDescription: "「地獄谷」は活火山地帯の直径450m・深さ7mの爆裂火口跡で、毎分3,000リットルの温泉が噴出し続ける。硫黄泉・食塩泉・重炭酸土類泉など9種の泉質が異なる宿で楽しめるのは国内でも稀だ。第一滝本館は総湯量が毎分6,000リットルに達する巨大浴場を持つ。地獄谷の遊歩道は30分で一周でき、硫黄の匂いと白煙が立ち込める中を歩く体験は温泉地としての圧倒的な存在感を示す。夜の「鬼花火」（20:00〜、宿泊者無料）は鬼の像が横転して湯煙が上がる演出が面白い。",
    tags: ["温泉", "地獄谷", "硫黄泉", "宿泊", "北海道"],
    stayDuration: 180,
    bestTime: "年間を通じて",
    crowdLevel: "medium",
    budget: "¥800〜（日帰り入浴）",
    access: "JR登別駅からバスで約15分",
    rainyDay: true,
    highlights: ["地獄谷遊歩道", "9種の泉質", "夜の鬼花火"],
    features: [
      { label: "地獄谷", text: "硫黄臭と白煙の中を歩く30分コース。温泉地の迫力が全身で分かる。" },
      { label: "9種の泉質", text: "宿ごとに引き込む源泉が異なる。はしご湯を楽しむ方法もある。" },
    ],
    nearby: ["toya-lake", "niseko"],
    relatedArticles: [],
  },
  {
    id: "toya-lake",
    title: "洞爺湖",
    location: "虻田郡洞爺湖町",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "洞爺湖",
    areaId: "toya",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Lake_Toya_from_Silo_Observatory%2C_Hokkaido%2C_Japan.jpg/1280px-Lake_Toya_from_Silo_Observatory%2C_Hokkaido%2C_Japan.jpg"],
    description: "カルデラ湖と有珠山が向き合う、北海道の地球を感じる場所。",
    longDescription: "直径約11kmの円形カルデラ湖の中央に4つの島（中島）が浮かぶ構図は、上空から見ると完璧な幾何学模様だ。2008年のG8洞爺湖サミットが開催されたことでも知られる。湖畔の「有珠山ロープウェイ」（往復1,800円）で上がると洞爺湖・昭和新山・噴火湾が一望できる。4月下旬から10月末まで毎夜21時に行われる「洞爺湖ロングラン花火」は20分程度の打ち上げで、湖畔に無料で観覧できる。西山火口散策路では2000年噴火の爪痕を間近に見られる（無料、1.5km）。",
    tags: ["カルデラ湖", "火山", "花火", "サミット", "絶景"],
    stayDuration: 120,
    bestTime: "5月〜10月（花火シーズン）",
    crowdLevel: "medium",
    budget: "無料（ロープウェイ¥1,800）",
    access: "JR洞爺駅からバスで約15分",
    rainyDay: false,
    highlights: ["有珠山ロープウェイからの展望", "夜の湖畔花火", "西山火口散策路"],
    features: [
      { label: "ロングラン花火", text: "4月下旬〜10月末の毎夜21時から約20分。湖面反射の花火が美しい。" },
      { label: "西山火口", text: "2000年噴火で隆起した道路や家屋が残る。地球の力を体感できる。" },
    ],
    nearby: ["noboribetsu-onsen", "niseko"],
    relatedArticles: [],
  },
  {
    id: "niseko",
    title: "ニセコ",
    location: "虻田郡ニセコ町",
    prefecture: "北海道",
    prefectureId: "hokkaido",
    area: "ニセコ",
    areaId: "niseko",
    category: "mountain",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/NisekoAnnapuriFromHirafu.jpg/1280px-NisekoAnnapuriFromHirafu.jpg"],
    description: "世界トップクラスのパウダースノーが、国際的スキーリゾートを生んだ。",
    longDescription: "羊蹄山（別名：蝦夷富士）を背景に広がるニセコエリアは、年間降雪量15mを超えるジャパンパウダーの聖地として世界中のスキーヤーを引き寄せる。アンヌプリ・ヒラフ・東山・花園の4スキー場が共通リフト券で滑れる。夏はラフティングやマウンテンバイク、秋は十勝岳の紅葉登山が人気。外国人観光客が多く、英語表記が充実している。ヒラフ地区にはオーストラリア人経営のバーやレストランが多く、深夜まで賑わう国際色豊かな雰囲気が他の北海道とは別世界だ。",
    tags: ["スキー", "パウダースノー", "リゾート", "インバウンド", "アクティブ"],
    stayDuration: 480,
    bestTime: "12月〜3月（スキー）",
    crowdLevel: "high",
    budget: "¥7,000〜（リフト1日券）",
    access: "JRニセコ駅からバス、または新千歳空港から車で約2時間",
    rainyDay: false,
    highlights: ["パウダースノーのスキー", "羊蹄山の眺め", "ヒラフ地区の夜の賑わい"],
    features: [
      { label: "ジャパンパウダー", text: "年間降雪量15m超。湿気の少ないさらさらの雪は世界最高品質と評される。" },
      { label: "4スキー場共通券", text: "ニセコユナイテッド共通券で広大なコースを縦横無尽に滑れる。" },
    ],
    nearby: ["toya-lake", "noboribetsu-onsen"],
    relatedArticles: [],
  },

  // ── 青森県 ──────────────────────────────────────
  {
    id: "hirosaki-castle",
    title: "弘前城",
    location: "弘前市下白銀町",
    prefecture: "青森県",
    prefectureId: "aomori",
    area: "弘前",
    areaId: "hirosaki",
    category: "castle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Hirosaki_Castle_in_spring.jpg/1280px-Hirosaki_Castle_in_spring.jpg"],
    description: "日本最北の現存天守と2,600本の桜。春の弘前は日本一の桜城下町。",
    longDescription: "1611年築城の現存天守は国の重要文化財で、東北最古の城郭建築のひとつだ。弘前公園内の桜は約2,600本、ソメイヨシノを中心に濃いピンクのしだれ桜が外堀を覆う光景は「日本一の桜」と称される。4月下旬〜5月上旬の「弘前さくらまつり」期間中は約200万人が訪れ、花びらが堀を覆う「花いかだ」は世界的に知名度が上がっている。弘前りんご（約55品種）は地元農家の直売で1箱2,000円〜。城外の「かくのだて」と並ぶ武家屋敷文化も残り、弘前市立観光館で津軽の文化が学べる。",
    tags: ["桜", "城", "春", "弘前さくらまつり", "りんご"],
    stayDuration: 120,
    bestTime: "4月下旬〜5月上旬（桜）",
    crowdLevel: "high",
    budget: "¥320（天守）",
    access: "JR弘前駅からバスで約15分",
    rainyDay: false,
    highlights: ["桜と現存天守の共演", "花いかだ（外堀）", "弘前りんごの直売"],
    features: [
      { label: "現存天守", text: "1611年築。石垣修理のため曳家で移動中（2025年現在）。この期間しか見られない内部構造が公開される。" },
      { label: "花いかだ", text: "散った桜の花びらが外堀を覆う現象。5月上旬の数日間だけ現れる。" },
    ],
    nearby: ["oirase-gorge", "towada-lake"],
    relatedArticles: [],
  },
  {
    id: "oirase-gorge",
    title: "奥入瀬渓流",
    location: "十和田市奥瀬",
    prefecture: "青森県",
    prefectureId: "aomori",
    area: "奥入瀬・十和田",
    areaId: "oirase-towada",
    category: "mountain",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Oirase_Gorge_in_autumn.jpg/1280px-Oirase_Gorge_in_autumn.jpg"],
    description: "十和田湖から流れ出す唯一の川が14kmの渓流美をつくる。",
    longDescription: "十和田湖から子ノ口まで14kmにわたる奥入瀬渓流は、急流・瀑布・深淵が連続する国特別名勝だ。銚子大滝は幅20m・高さ7mで渓流最大の滝、「阿修羅の流れ」は白泡が岩を洗う撮影定番地点として知られる。10月中旬〜下旬の紅葉期は緑・黄・赤のグラデーションが渓流沿いに並ぶ。遊歩道は整備されており、子ノ口から焼山まで約4時間の全歩行も可能だが、起点と終点のバス移動を組み合わせるのが一般的。苔むした岩は常に湿気があり、晴れよりも雨上がりの方が色彩が鮮やかになる。",
    tags: ["渓流", "紅葉", "自然", "トレッキング", "国特別名勝"],
    stayDuration: 240,
    bestTime: "10月中旬〜下旬（紅葉）または新緑の5月",
    crowdLevel: "medium",
    budget: "無料",
    access: "JR八戸駅からバスで約2時間（奥入瀬渓流入口）",
    rainyDay: false,
    highlights: ["阿修羅の流れ", "銚子大滝", "秋の紅葉"],
    features: [
      { label: "阿修羅の流れ", text: "白泡が岩を流れ落ちる最も写真映えするポイント。午前の逆光を避けて東向きに。" },
      { label: "苔ロード", text: "苔に覆われた岩が渓流沿いに続く。雨上がりが最も鮮やかな緑になる。" },
    ],
    nearby: ["towada-lake", "hirosaki-castle"],
    relatedArticles: [],
  },
  {
    id: "shirakami-sanchi",
    title: "白神山地",
    location: "中津軽郡西目屋村・秋田県境",
    prefecture: "青森県",
    prefectureId: "aomori",
    area: "白神山地",
    areaId: "shirakami",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "世界遺産のブナ原生林と透明な十二湖。人が踏み込めない原始の森がある。",
    longDescription: "約13万haのブナ天然林が手付かずで残る世界遺産核心地域への入山は許可制だが、緩衝地帯の十二湖エリアは自由に歩ける。十二湖の「青池」はコバルトブルーの透明度が5m以上あり、晴天時の午前中が最も青が鮮明に出る。ブナ林の樹齢は300年超のものも多く、一本のブナが10tもの水を蓄える「緑のダム」機能は津軽平野の農業を支えてきた。秋のブナ紅葉（10月中旬）は黄金色に染まる森が圧巻。アクセスはJR五能線の「十二湖駅」が最寄りで、世界遺産バスツアーも運行されている。",
    tags: ["世界遺産", "ブナ林", "青池", "自然", "トレッキング"],
    stayDuration: 180,
    bestTime: "5月（新緑）または10月中旬（紅葉）",
    crowdLevel: "low",
    budget: "無料",
    access: "JR五能線 十二湖駅から徒歩30分（または観光バス）",
    rainyDay: false,
    highlights: ["十二湖の青池", "ブナ原生林", "リョウブ沢の滝"],
    features: [
      { label: "青池", text: "水深は浅いが透明度が異常に高い。晴れた午前中だけ水面が鮮青になる。" },
      { label: "ブナ原生林", text: "樹齢300年超のブナが林立する。核心地域は許可なく入れない。" },
    ],
    nearby: ["hirosaki-castle", "towada-lake"],
    relatedArticles: [],
  },
  {
    id: "towada-lake",
    title: "十和田湖",
    location: "十和田市・青森・秋田県境",
    prefecture: "青森県",
    prefectureId: "aomori",
    area: "奥入瀬・十和田",
    areaId: "oirase-towada",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Lake_Towada_in_Aomori%2C_Japan.jpg/1280px-Lake_Towada_in_Aomori%2C_Japan.jpg"],
    description: "二重式カルデラ湖の深い紺碧と、奥入瀬渓流の水源。",
    longDescription: "二重カルデラ構造を持つ十和田湖は最深部327mで、東北最大の二重式カルデラ湖だ。透明度11mの深い紺碧は秋晴れに最も映え、湖畔の遊覧船（1,400円、50分）からは外輪山の全体像が見える。湖中に立つ高村光太郎晩年の傑作「乙女の像」は十和田市現代美術館と合わせて訪問する価値がある。冬季は積雪1m超になるが、スノーシューで湖畔を歩く体験が近年人気だ。子ノ口から奥入瀬渓流を遡行して十和田湖に至る2泊3日コースは東北屈指の自然体験ルートだ。",
    tags: ["カルデラ湖", "透明度", "遊覧船", "乙女の像", "東北"],
    stayDuration: 120,
    bestTime: "10月（紅葉）または7月〜8月",
    crowdLevel: "medium",
    budget: "無料（遊覧船¥1,400）",
    access: "JR八戸駅からバスで約2時間30分",
    rainyDay: false,
    highlights: ["乙女の像", "遊覧船からの外輪山", "奥入瀬渓流への起点"],
    features: [
      { label: "乙女の像", text: "高村光太郎が79歳で完成させた最後の大作。湖中の岩に立つ。" },
      { label: "遊覧船", text: "湖面から外輪山を仰ぐ視点は陸からでは得られない。秋の紅葉期が特に美しい。" },
    ],
    nearby: ["oirase-gorge", "hirosaki-castle"],
    relatedArticles: [],
  },

  // ── 岩手県 ──────────────────────────────────────
  {
    id: "chusonji",
    title: "中尊寺",
    location: "西磐井郡平泉町平泉衣関",
    prefecture: "岩手県",
    prefectureId: "iwate",
    area: "平泉",
    areaId: "hiraizumi",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Konjikido.jpg/1280px-Konjikido.jpg"],
    description: "奥州藤原氏が築いた黄金の金色堂。850年の時を経ても輝きを失わない。",
    longDescription: "1124年建立の金色堂は、建物全体を純金箔で覆った平安末期の傑作で、松尾芭蕉も「五月雨の降り残してや光堂」と詠んだ。現在は覆堂の中に保護されており、ガラス越しに見るが、その金色の輝きは圧倒的だ。金色堂だけでなく、弁慶の立ち往生伝説が残る弁慶堂、藤原三代の遺体が安置された経蔵なども見どころが多い。境内は月見坂の杉並木から始まり、20分ほど歩いて奥まで進む。拝観料800円で金色堂・経蔵・讃衡蔵の三点セットが見られる。世界文化遺産「平泉の文化的景観」の中核スポット。",
    tags: ["世界遺産", "金色堂", "平安", "仏教", "東北"],
    stayDuration: 90,
    bestTime: "午前中（混雑前）",
    crowdLevel: "medium",
    budget: "¥800",
    access: "JR東北本線 平泉駅から徒歩20分、またはバスで5分",
    rainyDay: true,
    highlights: ["金色堂", "月見坂の杉並木", "讃衡蔵"],
    features: [
      { label: "金色堂", text: "純金箔張りの建築。覆堂のガラス越しでも、その輝きに息をのむ。" },
      { label: "讃衡蔵", text: "藤原三代の遺体と平安仏像を収める宝物館。仏像の保存状態が驚異的。" },
    ],
    nearby: ["hiraizumi", "ryusendo"],
    relatedArticles: [],
  },
  {
    id: "hiraizumi",
    title: "平泉・毛越寺",
    location: "西磐井郡平泉町平泉大沢",
    prefecture: "岩手県",
    prefectureId: "iwate",
    area: "平泉",
    areaId: "hiraizumi",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Motsuji_Temple_Hiraizumi_01.jpg/1280px-Motsuji_Temple_Hiraizumi_01.jpg"],
    description: "浄土の世界を再現した大庭園が、今もほぼ当時の姿で残る奇跡。",
    longDescription: "毛越寺の大泉が池を中心とした浄土庭園は、平安時代の「作庭記」に基づいて造営され、当時の伽藍配置が地上に残る点で国内でも珍しい。5月下旬の「あやめまつり」では300種3万株のアヤメが咲き誇る。池を時計回りに歩く遊歩道は約500m、池に浮かぶ中島の松が絵画的な構図をつくる。正月の「毛越寺の常行三昧」や1月20日の「二十日夜祭」は平安の雅楽を継承する儀式で、日本の無形民俗文化財だ。拝観料700円、中尊寺と合わせて半日かけるのが平泉観光の正しい時間配分。",
    tags: ["世界遺産", "浄土庭園", "平安", "紅葉", "あやめ"],
    stayDuration: 60,
    bestTime: "5月（あやめ）または10月（紅葉）",
    crowdLevel: "medium",
    budget: "¥700",
    access: "JR東北本線 平泉駅から徒歩10分",
    rainyDay: false,
    highlights: ["大泉が池の浄土庭園", "あやめまつり（5月）", "平安伝統行事"],
    features: [
      { label: "浄土庭園", text: "池・中島・遣水・州浜が平安の作庭技法そのまま。1,000年前の設計が生きている。" },
      { label: "あやめまつり", text: "5月下旬〜6月、3万株のアヤメが池を囲む。紫の水面反射が美しい。" },
    ],
    nearby: ["chusonji", "ryusendo"],
    relatedArticles: [],
  },
  {
    id: "ryusendo",
    title: "龍泉洞",
    location: "下閉伊郡岩泉町岩泉",
    prefecture: "岩手県",
    prefectureId: "iwate",
    area: "岩泉",
    areaId: "iwaizumi",
    category: "other",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Ryusendo_cave_2.jpg/1280px-Ryusendo_cave_2.jpg"],
    description: "地底湖の透明度98m。日本三大鍾乳洞のひとつが持つ神秘の青。",
    longDescription: "龍泉洞の第3地底湖は透明度98mが確認されており、日本で最も透明な地底湖として知られる。総延長5,000mのうち約700mが公開されており、鍾乳石・石筍が形成する空間はライトアップされて幻想的だ。洞内の気温は8〜10℃で夏は天然クーラー、冬は暖かく感じる。観覧料1,100円。洞窟内の池はUV照射により濃いターコイズブルーに見え、写真映えスポットとして定番だ。龍泉新洞科学館（300円）では発掘された化石動物の展示があり、合わせて90分が理想の訪問時間。",
    tags: ["鍾乳洞", "地底湖", "神秘", "洞窟", "日本三大"],
    stayDuration: 90,
    bestTime: "年間を通じて",
    crowdLevel: "medium",
    budget: "¥1,100",
    access: "JR盛岡駅からバスで約2時間30分（岩泉線廃止のため路線バス利用）",
    rainyDay: true,
    highlights: ["第3地底湖の透明度98m", "鍾乳石のライトアップ", "龍泉新洞科学館"],
    features: [
      { label: "地底湖の青", text: "UV照射でターコイズブルーに輝く。洞内が8℃なので夏でも防寒着必要。" },
      { label: "龍泉新洞", text: "隣接する科学館では3万年前の化石熊などを展示。子供に特におすすめ。" },
    ],
    nearby: ["chusonji", "hiraizumi"],
    relatedArticles: [],
  },

  // ── 宮城県 ──────────────────────────────────────
  {
    id: "matsushima",
    title: "松島",
    location: "宮城郡松島町",
    prefecture: "宮城県",
    prefectureId: "miyagi",
    area: "松島",
    areaId: "matsushima",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Matsushima_Miyagi_pref_Japan.JPG/1280px-Matsushima_Miyagi_pref_Japan.JPG"],
    description: "松尾芭蕉も詠んだ日本三景。260余りの松島が浮かぶ絶景の湾。",
    longDescription: "「松島やああ松島や松島や」──実はこの句は芭蕉作ではないという説が有力だが、それほど松島は詩人を沈黙させる絶景だ。260余りの島々に松が茂り、観光遊覧船（大人1,500円、50分）から見ると島の形がそれぞれ異なる。瑞巌寺（拝観700円）は伊達政宗が改築した桃山建築の傑作で、洞窟礼拝所群も独特だ。5島めぐり遊覧は桂島・野々島など有人島への連絡船（往復¥620）でリアルな漁村を体験できる。かき小屋は9月〜5月営業で、地場産の大粒牡蠣が網焼き食べ放題で約3,000円というコスパは圧倒的。",
    tags: ["日本三景", "松島", "遊覧船", "牡蠣", "芭蕉"],
    stayDuration: 180,
    bestTime: "10月〜11月（紅葉と牡蠣シーズン）",
    crowdLevel: "high",
    budget: "¥1,500（遊覧船）",
    access: "JR仙石線 松島海岸駅から徒歩5分",
    rainyDay: false,
    highlights: ["遊覧船からの松島群", "瑞巌寺", "かき小屋の網焼き"],
    features: [
      { label: "遊覧船コース", text: "仁王丸コース（50分）が標準。島の形が多様で飽きない。" },
      { label: "かき小屋", text: "9月〜5月、地場産牡蠣を網焼きで食べ放題。浜値で食べる贅沢。" },
    ],
    nearby: ["zuiganji", "sendai-castle"],
    relatedArticles: [],
  },
  {
    id: "zuiganji",
    title: "瑞巌寺",
    location: "宮城郡松島町松島町内",
    prefecture: "宮城県",
    prefectureId: "miyagi",
    area: "松島",
    areaId: "matsushima",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Zuiganji_temple_Matsushima_Japan02s3.jpg/1280px-Zuiganji_temple_Matsushima_Japan02s3.jpg"],
    description: "伊達政宗が造営した東北随一の桃山建築。杉並木の先に金箔が待つ。",
    longDescription: "1609年に伊達政宗が5年を費やして改築した瑞巌寺は、桃山様式の本堂が国宝に指定されている。参道の両側に並ぶ杉の古木は樹齢400年超で、その荘厳な雰囲気の中を歩くだけで価値がある。洞窟礼拝所「座禅窟」群は12世紀に僧侶が掘った修行場で、内部の彫刻と石仏が独特の空気感を醸し出す。宝物館「青龍殿」では政宗が愛用した具足や、妻子の肖像画が公開されている。松島の観光船桟橋から徒歩3分の好立地で、松島観光の定番ルートに組み込みやすい。",
    tags: ["国宝", "伊達政宗", "桃山建築", "洞窟", "歴史"],
    stayDuration: 60,
    bestTime: "午前中",
    crowdLevel: "medium",
    budget: "¥700",
    access: "JR仙石線 松島海岸駅から徒歩5分",
    rainyDay: true,
    highlights: ["国宝本堂", "洞窟礼拝所群", "杉の参道"],
    features: [
      { label: "洞窟礼拝所", text: "12世紀に掘られた修行洞窟。仏像彫刻が岩壁に刻まれ、薄暗い内部は独特の霊気がある。" },
      { label: "青龍殿", text: "政宗の具足・書状・妻子の肖像など第一級の史料が収蔵されている。" },
    ],
    nearby: ["matsushima", "sendai-castle"],
    relatedArticles: [],
  },
  {
    id: "sendai-castle",
    title: "仙台城跡（青葉城）",
    location: "仙台市青葉区天守台",
    prefecture: "宮城県",
    prefectureId: "miyagi",
    area: "仙台",
    areaId: "sendai",
    category: "castle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Sendai_Castle_Ruins.jpg/1280px-Sendai_Castle_Ruins.jpg"],
    description: "伊達政宗騎馬像が青葉山から仙台を見下ろす。東北最大の城郭跡。",
    longDescription: "1601年に伊達政宗が築いた青葉城は、天守が存在しなかったことが近世城郭として珍しく、本丸の高石垣と大手門脇櫓が当時の面影を残す。青葉山公園内の本丸跡には政宗公騎馬像が仙台市街を向いて鎮座し、眼下に広瀬川と市街地が広がる絶景スポットだ。仙台城見聞館ではVR映像で城郭全体の当時の姿を体験できる（500円）。桜の名所でもあり、4月中旬には本丸跡の桜並木が満開になる。西公苑から本丸まで徒歩15分の登り道は、途中に武家屋敷跡が点在する歴史散歩コースとして最適。",
    tags: ["城跡", "伊達政宗", "展望", "歴史", "桜"],
    stayDuration: 90,
    bestTime: "4月（桜）または秋の晴天時",
    crowdLevel: "medium",
    budget: "無料（VR館¥500）",
    access: "仙台駅からバス「るーぷる仙台」で約20分",
    rainyDay: false,
    highlights: ["伊達政宗騎馬像", "本丸からの仙台市街の眺め", "高石垣"],
    features: [
      { label: "騎馬像と眺望", text: "仙台市を見下ろす政宗像の後ろには広瀬川が見える。夕暮れ時の逆光が美しい。" },
      { label: "仙台城見聞館", text: "VRで400年前の城郭を体験。高石垣の修復記録も展示されている。" },
    ],
    nearby: ["matsushima", "akiu-onsen"],
    relatedArticles: [],
  },
  {
    id: "akiu-onsen",
    title: "秋保温泉",
    location: "仙台市太白区秋保町",
    prefecture: "宮城県",
    prefectureId: "miyagi",
    area: "仙台近郊",
    areaId: "sendai-suburbs",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80"],
    description: "仙台から30分の奥座敷。磊々峡の渓谷美と歴史ある湯を持つ名湯地。",
    longDescription: "奈良時代から記録に残る古湯で、仙台藩主伊達家の御殿湯として歴史を重ねた。仙台市中心部から車で30分の近さが最大の特徴で、日帰り温泉施設「長寿の湯」（700円）を含む複数の宿が日帰り入浴に対応している。名取川沿いの「磊々峡（らいらいきょう）」は奇岩が連なる渓谷で、200mの遊歩道を30分で歩ける。秋保大滝（落差55m、幅6m）は「日本の滝百選」に選ばれており、滝見橋から見下ろす構図は迫力満点だ。仙台牛を使った温泉旅館の夕食は、仙台遠征の締めくくりとして申し分ない。",
    tags: ["温泉", "日帰り", "渓谷", "仙台近郊", "老舗旅館"],
    stayDuration: 180,
    bestTime: "秋（紅葉）または冬（雪見温泉）",
    crowdLevel: "medium",
    budget: "¥700〜（日帰り入浴）",
    access: "仙台駅から車で約30分、またはバスで約50分",
    rainyDay: true,
    highlights: ["磊々峡の渓谷散歩", "秋保大滝", "老舗旅館の仙台牛料理"],
    features: [
      { label: "磊々峡", text: "奇岩が連続する200mの渓谷遊歩道。秋は紅葉が覆い被さる。" },
      { label: "秋保大滝", text: "「日本の滝百選」。滝見橋から全景が見える。落差55mの迫力。" },
    ],
    nearby: ["sendai-castle", "matsushima"],
    relatedArticles: [],
  },

  // ── 秋田県 ──────────────────────────────────────
  {
    id: "kakunodate-bukeyashiki",
    title: "角館武家屋敷",
    location: "仙北市角館町",
    prefecture: "秋田県",
    prefectureId: "akita",
    area: "角館",
    areaId: "kakunodate",
    category: "street",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Kakunodate_samurai_district_1.jpg/1280px-Kakunodate_samurai_district_1.jpg"],
    description: "枝垂れ桜と黒板塀が続く「みちのくの小京都」。",
    longDescription: "仙北藩の武家町として整備された角館は、黒塗りの板塀と重厚な主屋が約400m続く「武家屋敷通り」が見どころだ。4月下旬〜5月上旬にはシダレザクラ約400本が武家屋敷の庭に満開になり、桜のトンネルになる。重要伝統的建造物群保存地区に指定された通りを歩くと、江戸時代の城下町がほぼ完全な形で保存されているのがわかる。青柳家（入場800円）・石黒家（入場500円）は内部公開されており、武家の生活道具や甲冑が展示されている。「稲庭うどん発祥」の佐藤養助総本店（角館店）で昼食を取るのが定番コースだ。",
    tags: ["武家屋敷", "桜", "江戸", "みちのくの小京都", "歴史"],
    stayDuration: 120,
    bestTime: "4月下旬〜5月上旬（桜）",
    crowdLevel: "high",
    budget: "無料（屋敷内部¥500〜¥800）",
    access: "JR田沢湖線 角館駅から徒歩15分",
    rainyDay: false,
    highlights: ["武家屋敷通りの枝垂れ桜", "青柳家・石黒家の内部", "稲庭うどん"],
    features: [
      { label: "枝垂れ桜", text: "4月下旬〜5月上旬、シダレザクラが武家屋敷の黒塀に映える。早朝が最も美しい。" },
      { label: "内部公開屋敷", text: "青柳家では武家の生活用品が見事に保存されている。甲冑は必見。" },
    ],
    nearby: ["tazawa-lake", "nyuto-onsen"],
    relatedArticles: [],
  },
  {
    id: "tazawa-lake",
    title: "田沢湖",
    location: "仙北市西木町",
    prefecture: "秋田県",
    prefectureId: "akita",
    area: "田沢湖",
    areaId: "tazawa",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Lake_Tazawa_Akita_Japan.jpg/1280px-Lake_Tazawa_Akita_Japan.JPG"],
    description: "日本一深い湖（423.4m）の鮮やかなコバルトブルーが、見る者を釘付けにする。",
    longDescription: "水深423.4mは日本一で、年間を通じて凍結しない不凍湖だ。その深さが独特のコバルトブルーを生み、湖岸から見ると吸い込まれるような青さがある。「たつこ像」（金色の乙女像）が湖畔に立ち、永遠の美を求めた悲恋伝説が語り継がれている。湖を一周する道路は約20kmで、レンタサイクル（2時間¥600）で走ると2時間30分。御座の石神社や潟尻から見る夕日は特に美しい。近くの乳頭温泉郷（車で30分）と組み合わせると一日が充実する。",
    tags: ["湖", "日本一深い", "コバルトブルー", "たつこ像", "サイクリング"],
    stayDuration: 120,
    bestTime: "5月〜10月（晴天時が最もコバルトブルーが鮮明）",
    crowdLevel: "medium",
    budget: "無料",
    access: "JR田沢湖線 田沢湖駅からバスで約15分",
    rainyDay: false,
    highlights: ["たつこ像とコバルトブルーの湖面", "湖岸サイクリング", "夕日の湖面"],
    features: [
      { label: "コバルトブルーの水", text: "深さ423mが生む透明感。晴れた正午が最も青く見える。" },
      { label: "レンタサイクル", text: "20km一周はE-bikeで2時間。湖岸の変化する景色が楽しい。" },
    ],
    nearby: ["kakunodate-bukeyashiki", "nyuto-onsen"],
    relatedArticles: [],
  },
  {
    id: "nyuto-onsen",
    title: "乳頭温泉郷",
    location: "仙北市田沢湖生保内",
    prefecture: "秋田県",
    prefectureId: "akita",
    area: "田沢湖・乳頭",
    areaId: "tazawa-nyuto",
    category: "onsen",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Tsurunoyu_onsen_%28007%29.jpg/1280px-Tsurunoyu_onsen_%28007%29.jpg"],
    description: "秘湯・鶴の湯の白濁露天風呂。茅葺き屋根が雪に沈む絶景温泉。",
    longDescription: "乳頭温泉郷は秋田駒ヶ岳の麓に点在する7つの温泉宿（鶴の湯・妙の湯・蟹場・大釜・孫六・黒湯・滝の湯）の総称で、それぞれが異なる泉質と佇まいを持つ。「鶴の湯」は江戸期の本陣が現存し、白濁の硫黄泉が茅葺き屋根の露天風呂に注ぐ姿は「日本の秘湯」を象徴する風景だ。7湯共通入浴手形（2,500円）で各宿を巡る「湯めぐり」は1泊2日が最低ライン。冬季は豪雪のため送迎バスが頼りで、雪に埋もれた鶴の湯の露天風呂は日本の温泉文化の極致といえる。",
    tags: ["秘湯", "白濁温泉", "茅葺き", "湯めぐり", "秋田"],
    stayDuration: 240,
    bestTime: "12月〜3月（雪見温泉）",
    crowdLevel: "low",
    budget: "¥700〜（日帰り入浴）",
    access: "JR田沢湖線 田沢湖駅からバスで約50分（鶴の湯は要予約送迎）",
    rainyDay: true,
    highlights: ["鶴の湯の白濁露天風呂", "湯めぐり手形7湯制覇", "雪中の露天風呂"],
    features: [
      { label: "鶴の湯", text: "江戸期本陣建築と白濁硫黄泉。日帰り入浴は¥600、宿泊は3ヶ月前から争奪戦。" },
      { label: "湯めぐり手形", text: "2,500円で7湯全部入れる。有効期間3日間で、宿泊するなら元が取れる。" },
    ],
    nearby: ["tazawa-lake", "kakunodate-bukeyashiki"],
    relatedArticles: [],
  },

  // ── 山形県 ──────────────────────────────────────
  {
    id: "zao-onsen",
    title: "蔵王温泉",
    location: "山形市蔵王温泉",
    prefecture: "山形県",
    prefectureId: "yamagata",
    area: "蔵王",
    areaId: "zao",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80"],
    description: "pH1.2の強酸性硫黄泉と、冬は樹氷スキーが共存する東北最大の温泉スキーリゾート。",
    longDescription: "1,900年の歴史を持つ蔵王温泉は、pH1.2という日本有数の強酸性硫黄泉で、殺菌力が高く皮膚病への効果が知られる。3ヶ所の共同浴場（上湯・下湯・川原湯）は350〜450円で入浴でき、地元民が日常的に使う素朴さがある。冬季は「ザオースキーリゾート」として蔵王ロープウェイ（往復2,800円）で地蔵山頂に上がると、1月〜2月に見られる「樹氷」（スノーモンスター）が圧巻だ。温泉街の「蔵王チーズ」ソフトクリーム（400円）は地場産乳製品の濃厚さが際立つ。",
    tags: ["強酸性温泉", "樹氷", "スキー", "硫黄泉", "山形"],
    stayDuration: 180,
    bestTime: "1月〜2月（樹氷）または年間を通じて（温泉）",
    crowdLevel: "medium",
    budget: "¥350〜（共同浴場）",
    access: "JR山形駅からバスで約40分",
    rainyDay: true,
    highlights: ["共同浴場の強酸性硫黄泉", "樹氷（スノーモンスター）", "蔵王チーズ"],
    features: [
      { label: "pH1.2の強酸性泉", text: "金属がすぐ腐食するほどの酸性。皮膚への刺激が強いが、肌がすべすべになる。" },
      { label: "樹氷", text: "1〜2月限定。アオモリトドマツがアイスモンスターになる姿はロープウェイから見下ろす。" },
    ],
    nearby: ["ginzan-onsen", "yamadera"],
    relatedArticles: [],
  },
  {
    id: "ginzan-onsen",
    title: "銀山温泉",
    location: "尾花沢市大字銀山新畑",
    prefecture: "山形県",
    prefectureId: "yamagata",
    area: "銀山温泉",
    areaId: "ginzan",
    category: "onsen",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Ginzan_Onsen_in_winter.jpg/1280px-Ginzan_Onsen_in_winter.jpg"],
    description: "大正ロマンの木造旅館が銀山川沿いに並ぶ。雪の夜、ガス燈が灯る絶景。",
    longDescription: "銀山川の両岸に大正末期〜昭和初期の洋風意匠を取り入れた木造多層旅館が建ち並ぶ銀山温泉は、東北で最も絵になる温泉地だ。名称は江戸初期に繁栄した延沢銀山に由来する。旅館の客室数は少なく、人気宿（藤屋・能登屋）の予約は3〜6ヶ月前に満室になる。日帰り入浴は「しろがね湯」（500円）のみ。冬の夜景は降雪と瓦斯燈が相まって、映画のセットのような光景を生み出す。白銀の雪景色の中で浴衣姿で歩く体験は、日本の冬の温泉旅行の最高峰といえる。",
    tags: ["大正ロマン", "木造旅館", "雪景色", "秘湯", "東北"],
    stayDuration: 120,
    bestTime: "12月〜3月（雪景色）",
    crowdLevel: "medium",
    budget: "¥500（しろがね湯）",
    access: "JR大石田駅からバスで約40分",
    rainyDay: true,
    highlights: ["雪夜のガス燈と木造旅館", "しろがね湯", "銀山川沿いの散策"],
    features: [
      { label: "夜の雪景色", text: "ガス燈と旅館の灯りが雪に反射する。撮影はISO1600・f2.8前後が適正。" },
      { label: "宿泊予約", text: "藤屋・能登屋は半年前から争奪戦。キャンセル狙いか平日狙いが現実的。" },
    ],
    nearby: ["zao-onsen", "yamadera"],
    relatedArticles: [],
  },
  {
    id: "yamadera",
    title: "山寺（立石寺）",
    location: "山形市山寺",
    prefecture: "山形県",
    prefectureId: "yamagata",
    area: "山寺",
    areaId: "yamadera",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/RisshakujiFullBridge.jpg/1280px-RisshakujiFullBridge.jpg"],
    description: "「閑さや岩にしみ入る蟬の声」──芭蕉が詠んだ岩山の上の古刹。",
    longDescription: "860年慈覚大師円仁が開山した立石寺は、凝灰岩の断崖に貼り付くように伽藍が建つ。奥の院まで1,015段の石段が続き、登り切るまで約40分。途中の弥陀洞（岩に浮かぶ仏の形）や五大堂からの眺望（山形盆地が一望）が節々の疲れを忘れさせる。7月になると松尾芭蕉が訪れた1689年と同じようにセミが鳴く。拝観料300円は日本の寺院でも最もコストパフォーマンスが高い部類。石段は滑りやすいので運動靴推奨。冬季は積雪で幻想的だが、一部石段が凍結する。",
    tags: ["芭蕉", "石段", "岩寺", "眺望", "修行場"],
    stayDuration: 90,
    bestTime: "5月〜11月（雪のない時期）",
    crowdLevel: "medium",
    budget: "¥300",
    access: "JR仙山線 山寺駅から徒歩5分（山頂まで徒歩40分）",
    rainyDay: false,
    highlights: ["1,015段の石段", "五大堂からの眺め", "弥陀洞の岩仏"],
    features: [
      { label: "五大堂の眺望", text: "断崖の先端に建つ舞台から山形盆地が見える。石段の疲れが吹き飛ぶ。" },
      { label: "芭蕉の句碑", text: "石段途中にある句碑の前で一服するのが雅な旅人の証明。" },
    ],
    nearby: ["ginzan-onsen", "dewa-sanzan"],
    relatedArticles: [],
  },
  {
    id: "dewa-sanzan",
    title: "出羽三山",
    location: "鶴岡市羽黒町・西川町",
    prefecture: "山形県",
    prefectureId: "yamagata",
    area: "庄内・月山",
    areaId: "shonai-gassan",
    category: "shrine",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Gassan_shrine.jpg/1280px-Gassan_shrine.jpg"],
    description: "羽黒山・月山・湯殿山の三山を巡る修験道。日本人の死生観が凝縮した霊地。",
    longDescription: "羽黒山・月山・湯殿山の三山は「現在・過去・未来」を象徴し、三山を巡ることで生まれ変われるとされる修験の地だ。羽黒山の2,446段の石段（杉並木国宝）は夏・秋の定番コースで、山頂の三神合祭殿（国宝）は三山の神が一堂に会す。月山（標高1,984m）への登山は7〜9月が適期で頂上の月山神社本宮は7月1日に開山する。湯殿山は撮影・口外厳禁の秘儀の場で、裸足で霊水の中を歩く体験が待っている。出羽三山神社の五重塔（国宝）は羽黒山中腹にあり、1372年建立の杉木立の中の佇まいが圧倒的。",
    tags: ["修験道", "霊山", "神社", "三山巡り", "パワースポット"],
    stayDuration: 360,
    bestTime: "7月〜9月（月山登山）",
    crowdLevel: "medium",
    budget: "¥500〜（各所拝観料）",
    access: "JR鶴岡駅からバスで約50分（羽黒山）",
    rainyDay: false,
    highlights: ["羽黒山2,446段の石段", "国宝・五重塔", "月山登山"],
    features: [
      { label: "国宝五重塔", text: "1372年建立。杉木立の中に静かに立つ姿は東北の神域を象徴する。" },
      { label: "湯殿山の秘儀", text: "撮影禁止・口外厳禁。裸足で霊水の中を歩く体験は言葉にできない。" },
    ],
    nearby: ["yamadera", "ginzan-onsen"],
    relatedArticles: [],
  },

  // ── 福島県 ──────────────────────────────────────
  {
    id: "aizuwakamatsu-castle",
    title: "会津若松城（鶴ヶ城）",
    location: "会津若松市追手町",
    prefecture: "福島県",
    prefectureId: "fukushima",
    area: "会津若松",
    areaId: "aizu",
    category: "castle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Tsurugajo_castle_in_Aizuwakamatsu.jpg/1280px-Tsurugajo_castle_in_Aizuwakamatsu.jpg"],
    description: "赤瓦の天守が桜に映える。戊辰戦争で落ちなかった幕末最後の城。",
    longDescription: "1384年創建の鶴ヶ城は、戊辰戦争で新政府軍の砲撃に1ヶ月耐え続けた歴史を持つ。現在の天守は1965年の再建だが、赤瓦に葺き替えられた外観が独特で、4月下旬の桜約1,000本との組み合わせは会津の春を象徴する風景だ。天守内の展示（520円）では会津藩の歴史と白虎隊の悲劇が詳細に語られる。隣接する茶室「麟閣」は千利休の子・少庵が建てたとされる重要文化財。会津本郷焼の窯元や三之丸の「七日町通り」の大正ロマン建築と組み合わせて半日のコースが組める。",
    tags: ["城", "桜", "幕末", "戊辰戦争", "白虎隊"],
    stayDuration: 90,
    bestTime: "4月下旬〜5月上旬（桜）",
    crowdLevel: "medium",
    budget: "¥520",
    access: "JR会津若松駅からバスで約10分",
    rainyDay: true,
    highlights: ["赤瓦天守と桜", "白虎隊の展示", "茶室「麟閣」"],
    features: [
      { label: "赤瓦天守", text: "1965年再建だが赤い瓦が独特。4月下旬の桜と組み合わせた写真が有名。" },
      { label: "白虎隊", text: "天守展示は白虎隊の最期を丁寧に解説。飯盛山と合わせて訪問を推奨。" },
    ],
    nearby: ["ouchi-juku", "goshikinuma"],
    relatedArticles: [],
  },
  {
    id: "ouchi-juku",
    title: "大内宿",
    location: "南会津郡下郷町大字大内",
    prefecture: "福島県",
    prefectureId: "fukushima",
    area: "南会津",
    areaId: "minami-aizu",
    category: "street",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Ouchijuku_in_snow.jpg/1280px-Ouchijuku_in_snow.jpg"],
    description: "茅葺き民家が街道の両側に並ぶ江戸の宿場町が現役で生きている。",
    longDescription: "重要伝統的建造物群保存地区に指定された大内宿は、江戸時代に会津西街道の宿場として栄えた集落が現在も実生活の場として使われている。約500mの街道に茅葺き屋根の民家約40軒が並び、土産店・食事処として営業する。名物の「ねぎそば」は箸の代わりにネギ1本を使って食べるスタイルで、1,200円前後。冬の雪景色は特に美しく、白い雪布団をかぶった茅葺き屋根の風景は日本の冬の原風景そのものだ。2月の「大内宿雪まつり」では雪灯籠が灯り、夜の撮影スポットとして人気がある。",
    tags: ["宿場町", "茅葺き", "江戸", "ねぎそば", "重要伝統建造物"],
    stayDuration: 90,
    bestTime: "2月（雪まつり）または11月（紅葉）",
    crowdLevel: "medium",
    budget: "無料（飲食別）",
    access: "JR会津若松駅からバスで約50分",
    rainyDay: false,
    highlights: ["茅葺き街道の雪景色", "ねぎそば", "大内宿雪まつり"],
    features: [
      { label: "ねぎそば", text: "ネギ1本を箸代わりに使う奇抜な食べ方。会津地ネギの辛みが蕎麦に移る。" },
      { label: "雪まつり", text: "2月に開催。雪灯籠が茅葺き街道を幻想的に照らす夜は格別。" },
    ],
    nearby: ["aizuwakamatsu-castle", "goshikinuma"],
    relatedArticles: [],
  },
  {
    id: "goshikinuma",
    title: "五色沼",
    location: "耶麻郡北塩原村大字桧原",
    prefecture: "福島県",
    prefectureId: "fukushima",
    area: "裏磐梯",
    areaId: "ura-bandai",
    category: "park",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Goshiki-numa_%28Kitashiobara%29.jpg/1280px-Goshiki-numa_%28Kitashiobara%29.jpg"],
    description: "磐梯山噴火が生んだ色彩豊かな沼群。同じ湖水なのに色が異なる自然の謎。",
    longDescription: "1888年の磐梯山噴火で生まれた五色沼は、毘沙門沼・赤沼・みどろ沼・竜沼・弁天沼・瑠璃沼・青沼と色や透明度の異なる湖沼群の総称だ。同じ火山性水でもミネラル成分が微妙に異なるため、エメラルドグリーン・コバルトブルー・深紅など各沼が全く異なる色を見せる。五色沼自然探勝路（約3.6km、1時間）は起伏が少なく、子供連れでも歩きやすい。毘沙門沼からの磐梯山の逆さ映りは朝の無風時間帯が最も綺麗。秋の紅葉期（10月中旬）は赤と青のコントラストが異次元の美しさになる。",
    tags: ["火山湖", "五色", "裏磐梯", "ハイキング", "紅葉"],
    stayDuration: 120,
    bestTime: "10月中旬（紅葉）または5月（新緑）",
    crowdLevel: "medium",
    budget: "無料",
    access: "JR磐越西線 猪苗代駅からバスで約30分",
    rainyDay: false,
    highlights: ["毘沙門沼の逆さ磐梯山", "自然探勝路3.6km", "秋の紅葉×青い湖面"],
    features: [
      { label: "毘沙門沼", text: "沼群最大。磐梯山が水面に逆さに映る。無風の朝7時台が狙い目。" },
      { label: "色の多様性", text: "沼ごとにミネラル成分が異なり全く別の色になる。科学的謎が今も続く。" },
    ],
    nearby: ["ouchi-juku", "aizuwakamatsu-castle"],
    relatedArticles: [],
  },
];
