import { Spot } from "@/types/spot";

export const kantoSpots: Spot[] = [
  // ── 東京 ──────────────────────────────────────
  {
    id: "senso-ji", title: "浅草寺", location: "台東区浅草",
    prefecture: "東京都", prefectureId: "tokyo", area: "浅草", areaId: "asakusa-area",
    category: "temple",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "雷門の提灯をくぐると、江戸の空気が残っている。",
    longDescription: "浅草寺は東京で最も古い寺院であり、観光地としても最前線にある。朝6時の開門直後に来ると、仲見世の屋台がまだ準備中で人影がない。本堂の香炉から上がる煙を身体に浴びる作法は、健康祈願の意味があると地元のおばあさんが教えてくれた。仲見世の人形焼きは、揚げたてを食べると全然違う。雷門の提灯の裏に竜の彫刻があることを、ほとんどの観光客は見ていない。浅草寺を制覇するなら、二天門から入るのが空いていて正解。",
    tags: ["寺院", "定番", "浅草", "歴史", "食べ歩き"],
    stayDuration: 90, bestTime: "早朝 6:00〜8:00", crowdLevel: "high",
    budget: "無料", access: "東京メトロ銀座線 浅草駅から徒歩5分", rainyDay: true,
    highlights: ["雷門", "仲見世通り", "本堂・宝蔵門"],
    features: [
      { label: "雷門", text: "赤い提灯の裏に刻まれた竜の彫刻は見落とされがち。表だけで帰るな。" },
      { label: "仲見世通り", text: "250mの参道。人形焼き、雷おこし、揚げまんじゅう。朝が揚げたて。" },
      { label: "本堂", text: "観音様に参拝後、おみくじを引く。凶が出ても木に結んで帰ること。" },
    ],
    nearby: ["ueno-park", "akihabara"], relatedArticles: [],
  },
  {
    id: "meiji-jingu", title: "明治神宮", location: "渋谷区代々木神園町",
    prefecture: "東京都", prefectureId: "tokyo", area: "原宿", areaId: "harajuku-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "70万平方メートルの森。都心にこれだけの静寂がある。",
    longDescription: "明治神宮は「神社」というより「都会の森」として体験するべき場所だ。原宿駅から歩いて5分で、完全に都市の音が消える。参道の砂利を踏む音だけが聞こえる時間は、ビジネス街と同じ東京とは思えない。初詣は日本で最多の300万人以上が訪れる。正月三が日を避けるなら1月4日以降がいい。奉納された酒樽とワイン樽が両側に並ぶ参道は、明治天皇が洋文化を取り入れた象徴だと後から知った。",
    tags: ["神社", "森", "早朝", "初詣", "パワースポット"],
    stayDuration: 60, bestTime: "早朝 7:00前", crowdLevel: "medium",
    budget: "無料", access: "JR山手線 原宿駅から徒歩1分", rainyDay: false,
    highlights: ["大鳥居", "参道の森", "本殿"],
    features: [
      { label: "参道の森", text: "365種10万本の樹木。自然林に見えるが、全て植えられたもの。" },
      { label: "奉納の酒樽とワイン樽", text: "参道両側に並ぶ。明治の文明開化精神がここに凝縮されている。" },
    ],
    nearby: ["shibuya-scramble", "shinjuku-gyoen"], relatedArticles: [],
  },
  {
    id: "tokyo-tower", title: "東京タワー", location: "港区芝公園",
    prefecture: "東京都", prefectureId: "tokyo", area: "港区", areaId: "minato-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "333mの赤と白。見上げても、見下ろしても東京が見える。",
    longDescription: "東京タワーは1958年完成。高さこそスカイツリーに譲ったが、夜のライトアップは今も東京で最も美しい人工光景のひとつだ。メインデッキ（150m）からは六本木の街と東京湾が同時に見える。晴れた日の富士山は予想より大きく見える。タワーの真下から見上げると、鉄骨の迫力が一番わかる。増上寺と東京タワーが同じフレームに収まる写真は、増上寺の正門前から撮れる。",
    tags: ["展望台", "夜景", "定番", "富士山", "写真映え"],
    stayDuration: 60, bestTime: "夕方〜夜", crowdLevel: "medium",
    budget: "¥1,200（メインデッキ）", access: "都営三田線 御成門駅から徒歩5分", rainyDay: true,
    highlights: ["メインデッキ（150m）", "トップデッキ（250m）", "増上寺との構図"],
    features: [
      { label: "メインデッキ", text: "150mから東京湾と六本木ヒルズが一望できる。富士山は西側。" },
      { label: "増上寺との構図", text: "増上寺の正門を前景に東京タワーを撮る。最も東京らしい1枚。" },
    ],
    nearby: ["roppongi-hills", "shibuya-scramble"], relatedArticles: [],
  },
  {
    id: "shibuya-scramble", title: "渋谷スクランブル交差点", location: "渋谷区道玄坂",
    prefecture: "東京都", prefectureId: "tokyo", area: "渋谷", areaId: "shibuya-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "青信号になった瞬間、全方向から人が交差する。",
    longDescription: "渋谷スクランブル交差点は、1回の青信号で最大3,000人が行き交う世界最多の横断歩道として知られる。この迫力を体験したいなら、渡る側ではなくスターバックス2階から見る側に回るべきだ。金曜夜の19時から21時が最も密度が高い。交差点に面したQFRONTのビル壁面の大型ビジョンが、夜の光の洪水を作り出している。渋谷ストリームから渋谷川沿いを歩くと、再開発で生まれた新しい渋谷の顔が見えてくる。",
    tags: ["街歩き", "定番", "夜", "写真映え", "観光"],
    stayDuration: 30, bestTime: "夜 19:00〜21:00（金曜が最多）", crowdLevel: "high",
    budget: "無料", access: "JR山手線 渋谷駅から徒歩すぐ", rainyDay: true,
    highlights: ["スクランブル交差点", "上から見る構図", "夜のビジョン"],
    features: [
      { label: "2階からの俯瞰", text: "スターバックス渋谷スクランブル店2階から全体を見下ろせる。" },
      { label: "金曜夜の混雑", text: "1回の青信号で3,000人。この密度は世界のどの都市にもない。" },
    ],
    nearby: ["meiji-jingu", "roppongi-hills"], relatedArticles: [],
  },
  {
    id: "tsukiji-outer-market", title: "築地場外市場", location: "中央区築地",
    prefecture: "東京都", prefectureId: "tokyo", area: "築地", areaId: "tsukiji-area",
    category: "market",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "マグロの赤身と卵焼きを食べながら歩く、東京の朝。",
    longDescription: "築地場外市場は豊洲への移転後も健在で、約400店が現役営業している。朝5時から開いている鮮魚店があり、プロの料理人が仕入れに来る時間帯がいちばん活気がある。場外で食べるなら大和寿司か鮨大を候補にしつつ、行列が40分を超えるなら吉野家1号店（場外の元祖）という選択もある。玉子焼き専門店「松露」の焼き立ては甘さが違う。月曜と水曜は定休店が多いので注意。",
    tags: ["市場", "グルメ", "朝活", "海鮮", "食べ歩き"],
    stayDuration: 90, bestTime: "朝 6:00〜10:00", crowdLevel: "high",
    budget: "¥2,000〜", access: "東京メトロ日比谷線 築地駅から徒歩1分", rainyDay: true,
    highlights: ["鮮魚店", "海鮮丼", "玉子焼き"],
    features: [
      { label: "朝の仕入れ時間", text: "5時〜7時はプロと観光客が混在。この時間帯が場外の本番。" },
      { label: "松露の玉子焼き", text: "出汁がきいた焼き立て玉子焼きは、ここでしか食べられない味。" },
    ],
    nearby: ["senso-ji", "ueno-park"], relatedArticles: [],
  },
  {
    id: "ueno-park", title: "上野公園", location: "台東区上野",
    prefecture: "東京都", prefectureId: "tokyo", area: "上野", areaId: "ueno-area",
    category: "park",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "美術館と動物園と桜が、1キロ四方に詰まっている。",
    longDescription: "上野公園は東京最大の文化集積地だ。東京国立博物館、東京都美術館、国立科学博物館、上野動物園が徒歩圏内に並ぶ。桜シーズン（3月下旬〜4月上旬）は約800本の桜が一斉に咲き、昼夜問わず花見客が押し寄せる。不忍池のハスは7月から8月にかけて満開を迎え、早朝の蓮の花は別格の美しさがある。不忍弁天堂の横から見る上野の杜は、都心と思えない。",
    tags: ["公園", "桜", "美術館", "家族", "四季"],
    stayDuration: 180, bestTime: "桜シーズン / 早朝", crowdLevel: "high",
    budget: "無料（施設別）", access: "JR上野駅 公園口から徒歩すぐ", rainyDay: true,
    highlights: ["桜並木", "不忍池", "東京国立博物館"],
    features: [
      { label: "桜並木", text: "800本の桜。花見の名所として国内トップクラスの規模。" },
      { label: "不忍池の蓮", text: "7〜8月の早朝、水面を埋め尽くす蓮の花。これを知る観光客は少ない。" },
      { label: "東京国立博物館", text: "所蔵品12万点。常設展だけで半日使える。企画展は別料金。" },
    ],
    nearby: ["senso-ji", "akihabara"], relatedArticles: [],
  },
  {
    id: "shinjuku-gyoen", title: "新宿御苑", location: "新宿区内藤町",
    prefecture: "東京都", prefectureId: "tokyo", area: "新宿", areaId: "shinjuku-area",
    category: "garden",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "新宿の喧騒を忘れる、58ヘクタールの静寂。",
    longDescription: "新宿御苑はフランス式整形庭園・英国風景式庭園・日本庭園が混在する世界的にも珍しい構成を持つ。桜の本数は1,100本以上で、上野より空いていて落ち着いて見られる。11月下旬〜12月上旬の菊花壇展は無料で観覧できる。温室には世界の熱帯植物が集められており、雨の日は温室だけでも価値がある。新宿駅から徒歩10分という立地なのに、中に入ると完全に別の空間。",
    tags: ["庭園", "桜", "自然", "散歩", "カップル"],
    stayDuration: 120, bestTime: "桜シーズン / 11〜12月（菊）", crowdLevel: "medium",
    budget: "¥500", access: "東京メトロ丸ノ内線 新宿御苑前駅から徒歩5分", rainyDay: true,
    highlights: ["フランス式庭園", "桜1,100本", "温室"],
    features: [
      { label: "3種の庭園", text: "フランス式・英国式・日本式が1つの園内に。設計の時代差が面白い。" },
      { label: "温室", text: "雨でも楽しめる。熱帯植物の密度は東京で随一。" },
    ],
    nearby: ["meiji-jingu", "shibuya-scramble"], relatedArticles: [],
  },
  {
    id: "roppongi-hills", title: "六本木ヒルズ", location: "港区六本木",
    prefecture: "東京都", prefectureId: "tokyo", area: "六本木", areaId: "roppongi-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "森美術館と東京シティビューと六本木。夜景と現代アートが共存する。",
    longDescription: "六本木ヒルズは2003年開業の複合施設で、森美術館を頂点に持つ。52階の東京シティビューは360度展望で、東京タワーとスカイツリーを同時に見られる数少ない場所のひとつだ。森美術館は企画展のレベルが高く、世界水準の現代アートが東京で見られる。毛利庭園の池に映る森タワーは、昼夜どちらも美しい写真が撮れる。ヒルズ内の六本木ヒルズクラブの外見だけでも、東京のラグジュアリーの密度がわかる。",
    tags: ["展望", "アート", "夜景", "ラグジュアリー", "買い物"],
    stayDuration: 120, bestTime: "夕方〜夜", crowdLevel: "medium",
    budget: "¥2,000（展望台）", access: "東京メトロ日比谷線 六本木駅から徒歩5分", rainyDay: true,
    highlights: ["東京シティビュー（52F）", "森美術館", "毛利庭園"],
    features: [
      { label: "東京シティビュー", text: "東京タワーとスカイツリーを同フレームで撮れる高さ。夜景は格別。" },
      { label: "森美術館", text: "世界水準の現代アート。展示替えのたびに内容が変わる。" },
    ],
    nearby: ["tokyo-tower", "shibuya-scramble"], relatedArticles: [],
  },
  {
    id: "akihabara", title: "秋葉原", location: "千代田区外神田",
    prefecture: "東京都", prefectureId: "tokyo", area: "秋葉原", areaId: "akihabara-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "電気街からサブカルの聖地へ。世界で最も密度の高いオタクの街。",
    longDescription: "秋葉原はかつて電気部品の問屋街だったが、1990年代以降にアニメ・ゲーム・フィギュアの街に変貌した。中央通りを歩くだけで、ゲームセンター、同人誌専門店、メイドカフェ、中古ゲームショップが交互に現れる。ヨドバシカメラAKIBAは世界最大級の家電量販店で、免税カウンターには常に外国人旅行者の列がある。ラジオ会館の各フロアで、フィギュアやトレカの専門店を見るだけで半日かかる。深夜でも人通りが絶えない。",
    tags: ["サブカル", "電気街", "アニメ", "買い物", "夜"],
    stayDuration: 120, bestTime: "午後〜夜", crowdLevel: "high",
    budget: "¥2,000〜（予算次第）", access: "JR秋葉原駅から徒歩すぐ", rainyDay: true,
    highlights: ["中央通り", "ラジオ会館", "メイドカフェ"],
    features: [
      { label: "ラジオ会館", text: "8フロアにフィギュア・トレカ・コスプレ専門店。1フロアで時間が消える。" },
      { label: "メイドカフェ", text: "日本特有の体験として外国人旅行者に人気。AKIBAカルチャーの象徴。" },
    ],
    nearby: ["ueno-park", "senso-ji"], relatedArticles: [],
  },
  {
    id: "imperial-palace", title: "皇居", location: "千代田区千代田",
    prefecture: "東京都", prefectureId: "tokyo", area: "皇居", areaId: "imperial-palace-area",
    category: "park",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "江戸城の石垣と松の緑。東京の中心にある、立ち入れない場所。",
    longDescription: "皇居は普段は外周のみ開放されているが、東御苑は火・木・金・土・日（無料）に入れる。外周2.14kmのランニングコースは世界中のランナーに知られており、早朝の皇居外周ランは東京の日課風景のひとつだ。二重橋は天皇誕生日や元日に正門前まで入れる。東御苑の本丸跡は広大な芝生が広がり、江戸城の天守台の石積みが今も残っている。桜田門の内側から皇居を見ると、江戸から続く権力の重みを感じる。",
    tags: ["歴史", "ランニング", "散歩", "無料", "定番"],
    stayDuration: 90, bestTime: "早朝（ランニング）/ 春（桜）", crowdLevel: "low",
    budget: "無料（東御苑）", access: "東京メトロ 二重橋前駅から徒歩5分", rainyDay: false,
    highlights: ["二重橋", "東御苑", "皇居外周ランニングコース"],
    features: [
      { label: "東御苑", text: "江戸城本丸跡に広がる芝生と天守台の石積み。無料で入れる。" },
      { label: "外周ランニング", text: "2.14kmのコース。週末の早朝は何百人もランナーが走る。" },
    ],
    nearby: ["senso-ji", "tokyo-tower"], relatedArticles: [],
  },

  // ── 神奈川 ──────────────────────────────────────
  {
    id: "kamakura-daibutsu", title: "鎌倉大仏", location: "鎌倉市長谷",
    prefecture: "神奈川県", prefectureId: "kanagawa", area: "鎌倉", areaId: "kamakura-area",
    category: "temple",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "高さ13mの露座の大仏。空だけを背負って、800年間ここにいる。",
    longDescription: "高徳院の鎌倉大仏は、1252年から造立が始まった国宝の青銅仏だ。露座（屋根なし）になったのは15世紀の台風と津波で大仏殿が流されたから。その後、大仏自身が「外の方が気持ちいい」と言ったという伝承がある。大仏の胎内に入れる（¥20）。内部の鉄骨構造が見えて、建造の工夫がわかる。早朝7時台の大仏は逆光になって、シルエットが締まる。紫陽花の時期（6月）は長谷寺と合わせて回るのが最善の動線。",
    tags: ["大仏", "鎌倉", "歴史", "国宝", "写真映え"],
    stayDuration: 60, bestTime: "早朝 7:00〜8:30", crowdLevel: "high",
    budget: "¥300", access: "江ノ電 長谷駅から徒歩7分", rainyDay: false,
    highlights: ["青銅大仏（国宝）", "胎内参拝", "周辺の紫陽花"],
    features: [
      { label: "胎内参拝", text: "¥20で内部に入れる。鋳造の跡と内壁の薄さに驚く。" },
      { label: "逆光の朝", text: "東側から朝日が当たる早朝は、輪郭が際立つ最良の撮影タイム。" },
    ],
    nearby: ["enoshima", "tsurugaoka-hachimangu"], relatedArticles: [],
  },
  {
    id: "enoshima", title: "江ノ島", location: "藤沢市江の島",
    prefecture: "神奈川県", prefectureId: "kanagawa", area: "湘南", areaId: "shonan-area",
    category: "other",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "橋を渡った先に、神社と洞窟と海鮮が待っている。",
    longDescription: "江ノ島は藤沢市から全長600mの弁天橋で繋がった陸繋島だ。島の入口から江島神社、江の島シーキャンドル（展望台）、岩屋洞窟まで徒歩45分の縦断ルートが王道。江の島丼（しらす丼）は島内数店で食べられるが、新鮮さは店によって差がある。シーキャンドルの展望台からは富士山と相模湾の両方が見える。夕日のタイミングが合うと、富士山のシルエットに太陽が沈む景色が見られる。",
    tags: ["島", "海鮮", "夕日", "神社", "湘南"],
    stayDuration: 180, bestTime: "夕方（富士山の夕日）/ 平日", crowdLevel: "high",
    budget: "¥1,000〜", access: "小田急江ノ島線 片瀬江ノ島駅から徒歩5分", rainyDay: false,
    highlights: ["江島神社", "シーキャンドル展望台", "岩屋洞窟"],
    features: [
      { label: "シーキャンドル", text: "高さ59.8mの展望台。富士山と伊豆大島が晴れれば同時に見える。" },
      { label: "しらす丼", text: "生しらすは4〜12月限定。釜揚げとのハーフ&ハーフが正解。" },
    ],
    nearby: ["kamakura-daibutsu", "tsurugaoka-hachimangu"], relatedArticles: [],
  },
  {
    id: "hakone-onsen", title: "箱根温泉", location: "足柄下郡箱根町",
    prefecture: "神奈川県", prefectureId: "kanagawa", area: "箱根", areaId: "hakone-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "富士山を見ながら入る露天風呂。東京から90分の別世界。",
    longDescription: "箱根は17の温泉地に分かれており、それぞれ泉質が異なる。仙石原のすすき野（10月下旬）は黄金色の絶景が広がる。芦ノ湖から富士山を見るベストポジションは成川美術館前の湖畔。箱根フリーパスは新宿からのロマンスカー往復＋箱根内の交通機関が乗り放題で、コスパが高い。大涌谷の黒たまごを食べると7年長生きする、という伝説があるが食べてみる価値はある。",
    tags: ["温泉", "富士山", "自然", "宿泊", "カップル"],
    stayDuration: 480, bestTime: "平日・紅葉シーズン（11月）", crowdLevel: "high",
    budget: "¥15,000〜（1泊）", access: "新宿からロマンスカーで約80分", rainyDay: true,
    highlights: ["富士山展望", "仙石原すすき野", "大涌谷"],
    features: [
      { label: "17の温泉地", text: "仙石原・強羅・宮ノ下など個性が違う。日帰り湯で梯子するのも正解。" },
      { label: "大涌谷", text: "硫黄の噴煙が上がる活火山地帯。黒たまご1個¥50。雄大な景色付き。" },
    ],
    nearby: ["enoshima"], relatedArticles: [],
  },
  {
    id: "yokohama-chinatown", title: "横浜中華街", location: "横浜市中区山下町",
    prefecture: "神奈川県", prefectureId: "kanagawa", area: "横浜", areaId: "yokohama-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "日本最大の中華街。600店舗が詰め込まれた食と色の迷宮。",
    longDescription: "横浜中華街は東アジア最大規模の中華街で、約600店が東西500m・南北200mのエリアに集中する。牌楼（中華門）が10基あり、方角ごとに異なる神を祀っている。横浜大世界の飲茶は行列必至だが、個人経営の小さな飲茶店に入る方が体験の密度が高い。肉まんは食べ歩き定番だが、北京ダックの専門店は昼前に売り切れることがある。春節（旧正月）前後の1週間は龍の舞と爆竹で街全体が沸く。",
    tags: ["グルメ", "中華", "食べ歩き", "横浜", "定番"],
    stayDuration: 120, bestTime: "昼（飲茶）/ 春節", crowdLevel: "high",
    budget: "¥2,000〜", access: "みなとみらい線 元町・中華街駅から徒歩1分", rainyDay: true,
    highlights: ["10基の牌楼", "横浜大世界", "食べ歩き"],
    features: [
      { label: "10基の牌楼", text: "方角ごとに色と守護神が違う。全部写真に収めると中華街制覇。" },
      { label: "北京ダック専門店", text: "昼前に売り切れる人気店がある。早めの入店が正解。" },
    ],
    nearby: ["yokohama-minatomirai", "tsurugaoka-hachimangu"], relatedArticles: [],
  },
  {
    id: "yokohama-minatomirai", title: "横浜みなとみらい", location: "横浜市西区みなとみらい",
    prefecture: "神奈川県", prefectureId: "kanagawa", area: "横浜", areaId: "yokohama-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "ランドマークタワーと観覧車。横浜の夜景はベイエリアにある。",
    longDescription: "みなとみらいは1980年代から開発が進む横浜の臨海副都心だ。ランドマークタワーの69階スカイガーデンは高さ273mで、晴れた日には富士山・房総半島・秩父まで見渡せる。コスモクロック21（観覧車）は夜のライトアップが横浜港と合わさって美しい。赤レンガ倉庫は週末にマルシェやイベントが開かれており、常に何かが行われている。大桟橋からは客船の入港が間近で見られる。",
    tags: ["夜景", "横浜", "観覧車", "ベイエリア", "カップル"],
    stayDuration: 120, bestTime: "夕方〜夜", crowdLevel: "medium",
    budget: "¥1,000（展望台）", access: "みなとみらい線 みなとみらい駅から徒歩3分", rainyDay: false,
    highlights: ["ランドマークタワー展望台", "赤レンガ倉庫", "大桟橋"],
    features: [
      { label: "スカイガーデン（69F）", text: "273mから横浜全体が見える。富士山は西側に浮かぶ。" },
      { label: "赤レンガ倉庫", text: "明治期の倉庫を改装。週末は必ず何かのマルシェがある。" },
    ],
    nearby: ["yokohama-chinatown"], relatedArticles: [],
  },
  {
    id: "tsurugaoka-hachimangu", title: "鶴岡八幡宮", location: "鎌倉市雪ノ下",
    prefecture: "神奈川県", prefectureId: "kanagawa", area: "鎌倉", areaId: "kamakura-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "段葛の桜並木を抜けると、石段の上に鶴岡八幡宮が現れる。",
    longDescription: "鶴岡八幡宮は1063年創建。鎌倉時代の武家政権の精神的中心だった。源氏池と平家池が境内にあり、政権の対立が地形に残っている。段葛（若宮大路の中央参道）は4月の桜並木が美しい。境内の舞殿は曽我物語の舞台。大石段を上がると、相模湾方向に視界が開ける。秋の例大祭（9月）は流鏑馬が行われ、馬が参道を疾走する姿は圧巻だ。",
    tags: ["神社", "鎌倉", "桜", "歴史", "パワースポット"],
    stayDuration: 60, bestTime: "早朝 / 桜シーズン（4月）", crowdLevel: "medium",
    budget: "無料", access: "JR横須賀線 鎌倉駅から徒歩10分", rainyDay: false,
    highlights: ["段葛の桜", "大石段", "源氏池・平家池"],
    features: [
      { label: "段葛", text: "若宮大路の中央参道。4月は桜トンネルになる。早朝に歩くべき。" },
      { label: "流鏑馬", text: "9月の例大祭で境内を馬が疾走。チケット不要で見られる神事。" },
    ],
    nearby: ["kamakura-daibutsu", "enoshima"], relatedArticles: [],
  },

  // ── 千葉 ──────────────────────────────────────
  {
    id: "naritasan-shinshoji", title: "成田山新勝寺", location: "成田市成田",
    prefecture: "千葉県", prefectureId: "chiba", area: "成田", areaId: "narita-area",
    category: "temple",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "全国第2位の初詣参拝者数。参道の鰻と石段の先の本堂。",
    longDescription: "成田山新勝寺は年間1,000万人以上の参拝者を集める真言宗の大本山だ。成田空港から電車で20分という立地もあり、外国人旅行者にも知られている。仁王門から大本堂まで続く石段は急で、登りきると参拝者の息が整う。成田山公園は境内に隣接する庭園で、紅葉シーズンが特に美しい。参道の鰻屋は170軒以上あり、江戸時代から続く老舗もある。川豊本店の鰻は行列で有名だが、11時の開店直後なら30分以内で入れる。",
    tags: ["寺院", "初詣", "鰻", "成田", "パワースポット"],
    stayDuration: 120, bestTime: "正月・早朝", crowdLevel: "high",
    budget: "無料（拝観）", access: "JR成田線 成田駅から徒歩10分", rainyDay: true,
    highlights: ["大本堂", "仁王門", "成田山公園"],
    features: [
      { label: "成田山公園", text: "境内に隣接する庭園。紅葉は11月中旬〜下旬が見頃。" },
      { label: "参道の鰻", text: "170軒の鰻屋が並ぶ参道。老舗の炭火焼きは香りから違う。" },
    ],
    nearby: ["nokogiriyama"], relatedArticles: [],
  },
  {
    id: "nokogiriyama", title: "鋸山", location: "富津市金谷",
    prefecture: "千葉県", prefectureId: "chiba", area: "南房総", areaId: "minamiboso-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "鋸の歯のような岩肌と、崖の上に突き出た「地獄のぞき」。",
    longDescription: "鋸山は標高329mの低山だが、日本寺の境内を兼ねており境内面積は100万平方mという規模だ。「地獄のぞき」は岩盤の先端が突き出した展望台で、下を覗くと足がすくむ。世界最大の石仏「百尺観音」は高さ31mで圧倒的な存在感。山頂展望台からは東京湾越しに富士山が見える。ロープウェイか徒歩のどちらでも登れるが、帰路は別ルートにして日本寺の石仏群を全部見ながら下山する動線が正解。",
    tags: ["山", "絶景", "寺院", "千葉", "ハイキング"],
    stayDuration: 180, bestTime: "晴天の午前中", crowdLevel: "medium",
    budget: "¥700（ロープウェイ）", access: "JR内房線 浜金谷駅から徒歩5分（ロープウェイ下駅）", rainyDay: false,
    highlights: ["地獄のぞき", "百尺観音", "山頂展望台"],
    features: [
      { label: "地獄のぞき", text: "岩が突き出した展望台。真下に断崖。これが鋸山に来る理由の全て。" },
      { label: "百尺観音", text: "高さ31mの石仏。採石の跡に彫られており、背景の岩肌が迫力を倍増させる。" },
    ],
    nearby: ["naritasan-shinshoji", "yoro-keikoku"], relatedArticles: [],
  },
  {
    id: "yoro-keikoku", title: "養老渓谷", location: "夷隅郡大多喜町",
    prefecture: "千葉県", prefectureId: "chiba", area: "房総", areaId: "boso-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "千葉県最後の紅葉スポット。11月下旬でもまだ色が残る。",
    longDescription: "養老渓谷は千葉県最大の渓谷で、関東の紅葉スポットとして最も「遅い」場所のひとつだ。例年の見頃は11月下旬から12月上旬で、都心の紅葉が終わってから楽しめる。粟又の滝は高さ20m・幅30mで千葉県最大の滝。渓谷沿いのハイキングコースは全長2.5kmで2時間以内に歩ける。温泉が至る所に湧いており、渓谷ハイキングの後に日帰り入浴できる宿が多い。",
    tags: ["紅葉", "渓谷", "温泉", "ハイキング", "秋"],
    stayDuration: 180, bestTime: "紅葉シーズン（11月下旬〜12月上旬）", crowdLevel: "medium",
    budget: "無料", access: "小湊鐡道 養老渓谷駅から徒歩20分", rainyDay: false,
    highlights: ["粟又の滝", "渓谷沿いハイキングコース", "温泉"],
    features: [
      { label: "粟又の滝", text: "千葉最大の滝。幅30mの岩盤を水が薄く広がって流れる独特の形状。" },
      { label: "遅い紅葉", text: "12月でも色が残る関東屈指の紅葉の遅場。都心の紅葉が終わってから行け。" },
    ],
    nearby: ["nokogiriyama", "choshi-inubosaki"], relatedArticles: [],
  },
  {
    id: "choshi-inubosaki", title: "銚子犬吠埼", location: "銚子市犬吠埼",
    prefecture: "千葉県", prefectureId: "chiba", area: "銚子", areaId: "choshi-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "本州最東端の岬。元旦に日本で最も早く日の出を見られる場所のひとつ。",
    longDescription: "犬吠埼は太平洋に突き出た岬で、本州の最東端に位置する。明治6年建設の犬吠埼灯台は白い外壁が青空に映える。灯台に登ると太平洋の水平線が360度広がる。元旦の初日の出は毎年5万人が訪れ、県内最大の初日の出スポットだ。銚子電鉄の終点「犬吠駅」では濡れ煎餅が名物で、廃線の危機を救ったB級グルメとして全国的に知られている。",
    tags: ["岬", "日の出", "灯台", "太平洋", "銚子"],
    stayDuration: 90, bestTime: "元旦（初日の出）/ 早朝", crowdLevel: "medium",
    budget: "¥300（灯台入場）", access: "銚子電鉄 犬吠駅から徒歩5分", rainyDay: false,
    highlights: ["犬吠埼灯台", "太平洋展望", "初日の出"],
    features: [
      { label: "灯台登頂", text: "99段の螺旋階段を上がると太平洋の水平線。登るだけの価値がある。" },
      { label: "銚子電鉄の濡れ煎餅", text: "廃線危機を救った名物。現地で焼き立てを食べるのが正しい食べ方。" },
    ],
    nearby: ["naritasan-shinshoji", "yoro-keikoku"], relatedArticles: [],
  },

  // ── 埼玉 ──────────────────────────────────────
  {
    id: "kawagoe", title: "川越", location: "川越市",
    prefecture: "埼玉県", prefectureId: "saitama", area: "川越", areaId: "kawagoe-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "蔵造りの商家が連なる「小江戸」。東京から30分でタイムスリップ。",
    longDescription: "川越は江戸時代の商家が今も現役で使われており「小江戸」と呼ばれる。蔵造りの街並みが連続する一番街は江戸の面影をそのまま保存している。時の鐘は1日4回（6時・12時・15時・18時）鳴り響く。菓子屋横丁は100年以上続く駄菓子屋が並ぶ小路で、芋けんぴ・麦こうじ・金平糖が軒を連ねる。サツマイモを使った料理は「川越いも」として各店が競い、芋ソフトクリームは定番の食べ歩きだ。",
    tags: ["街歩き", "小江戸", "蔵造り", "食べ歩き", "歴史"],
    stayDuration: 180, bestTime: "平日午前中", crowdLevel: "medium",
    budget: "¥1,500〜", access: "西武新宿線 本川越駅から徒歩15分", rainyDay: false,
    highlights: ["蔵造りの街並み（一番街）", "時の鐘", "菓子屋横丁"],
    features: [
      { label: "一番街", text: "江戸期の蔵造り商家が今も現役。雨の日は蔵の黒塗りが締まる。" },
      { label: "菓子屋横丁", text: "1本の路地に昭和の駄菓子屋が密集。子どもより大人が興奮する。" },
    ],
    nearby: ["chichibu", "nagatoro"], relatedArticles: [],
  },
  {
    id: "chichibu", title: "秩父", location: "秩父市",
    prefecture: "埼玉県", prefectureId: "saitama", area: "秩父", areaId: "chichibu-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "芝桜と三十四か所霊場。東京から近い本物の山岳信仰の地。",
    longDescription: "秩父は武甲山を背景にした山岳信仰の地で、秩父三十四か所霊場は1100年の歴史を持つ。4月下旬〜5月上旬の羊山公園「芝桜の丘」は40万株の芝桜が斜面を埋め尽くす。秩父夜祭（12月3日）は日本三大曳山祭のひとつで、花火と屋台の山車が夜の秩父を埋め尽くす。ポテトを使った「わらじかつ丼」は秩父B級グルメの代表で、1枚のカツが器からはみ出す大きさが迫力。",
    tags: ["自然", "芝桜", "温泉", "埼玉", "霊場"],
    stayDuration: 240, bestTime: "芝桜（4〜5月）/ 秩父夜祭（12月3日）", crowdLevel: "medium",
    budget: "¥1,000〜", access: "西武秩父線 西武秩父駅から徒歩圏内", rainyDay: false,
    highlights: ["羊山公園の芝桜", "秩父三十四か所", "秩父夜祭"],
    features: [
      { label: "芝桜の丘", text: "40万株。ピンク・白・赤の3色が斜面に広がる。GW前後が見頃。" },
      { label: "わらじかつ丼", text: "器からはみ出る大きさのかつが2枚。たれが甘辛で秩父の味。" },
    ],
    nearby: ["nagatoro", "kawagoe"], relatedArticles: [],
  },
  {
    id: "nagatoro", title: "長瀞", location: "秩父郡長瀞町",
    prefecture: "埼玉県", prefectureId: "saitama", area: "秩父", areaId: "chichibu-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "岩畳の上から眺める荒川。ライン下りで川面を流れる体験。",
    longDescription: "長瀞は荒川が結晶片岩の岩盤を削った奇景で、国の名勝・天然記念物に指定されている。岩畳は長さ500m・幅30mの平らな岩盤が川沿いに広がる。ライン下りは3コースあり、急流を含む「上長瀞〜長瀞」コース（約20分）が迫力がある。桜の時期（4月上旬）は岩畳の上から川と桜が同時に見えて、最も人出が多い。夏の川遊びと秋の紅葉も見応えがある。宝登山神社の蝋梅（1〜2月）は関東屈指の蝋梅の名所。",
    tags: ["渓谷", "ライン下り", "自然", "桜", "秩父"],
    stayDuration: 180, bestTime: "桜（4月）/ 紅葉（11月）", crowdLevel: "medium",
    budget: "¥1,500（ライン下り）", access: "秩父鉄道 長瀞駅から徒歩5分", rainyDay: false,
    highlights: ["岩畳", "ライン下り", "宝登山神社"],
    features: [
      { label: "岩畳", text: "川沿いに続く自然の石畳。地質学的にも珍しい結晶片岩の露頭。" },
      { label: "ライン下り", text: "急流と静水が交互に来る約20分。ガイドの解説も面白い。" },
    ],
    nearby: ["chichibu", "kawagoe"], relatedArticles: [],
  },

  // ── 栃木 ──────────────────────────────────────
  {
    id: "nikko-toshogu", title: "日光東照宮", location: "日光市山内",
    prefecture: "栃木県", prefectureId: "tochigi", area: "日光", areaId: "nikko-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "金箔と極彩色の彫刻。徳川家康を神に祀った、絢爛豪華の頂点。",
    longDescription: "日光東照宮は1617年に造営され、1636年に大規模改築された世界遺産の神社だ。「見ざる・言わざる・聞かざる」の三猿は神厩舎（馬小屋）に彫られており、人生の教訓8面の一部に過ぎない。眠り猫は彫刻師・左甚五郎の作とされ、右上の廊下の天井に止まっている。奥宮まで207段の石段を登ると、家康の墓所がある。建物全体の金箔の量は400万枚以上。陽明門を見ていると一日が暮れる、という意味で「日暮の門」とも呼ばれる。",
    tags: ["神社", "世界遺産", "歴史", "彫刻", "定番"],
    stayDuration: 180, bestTime: "平日 / 紅葉（10月下旬〜11月上旬）", crowdLevel: "high",
    budget: "¥1,300", access: "東武日光線 東武日光駅からバス7分", rainyDay: true,
    highlights: ["陽明門", "三猿", "眠り猫・奥宮"],
    features: [
      { label: "陽明門", text: "508体の彫刻が埋め尽くす。江戸の職人技の総決算。見れば見るほど深い。" },
      { label: "三猿", text: "神厩舎の8枚のパネルは人の一生を描いている。三猿は2枚目。全部見よ。" },
    ],
    nearby: ["kegon-falls", "kinugawa-onsen"], relatedArticles: [],
  },
  {
    id: "kegon-falls", title: "華厳の滝", location: "日光市中宮祠",
    prefecture: "栃木県", prefectureId: "tochigi", area: "日光", areaId: "nikko-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "落差97m。中禅寺湖の水が一気に落ちる。",
    longDescription: "華厳の滝は中禅寺湖の水を落差97mで落とす、日本三大瀑布のひとつだ。展望台は無料でアクセスできる地上から見る場所と、有料エレベーターで降りる地下観瀑台（¥570）の2か所ある。地下観瀑台は滝と同じ高さまで降りて見上げる構造で、水しぶきが顔にかかる距離感。秋の紅葉シーズンは、滝を囲む木々が赤と黄色に染まって圧倒的な景色になる。近くの竜頭の滝と湯滝を合わせた「奥日光三名瀑」ルートが定番。",
    tags: ["滝", "自然", "日光", "紅葉", "絶景"],
    stayDuration: 90, bestTime: "紅葉シーズン（10月下旬）", crowdLevel: "high",
    budget: "¥570（地下観瀑台）", access: "東武日光線 東武日光駅からバス45分", rainyDay: false,
    highlights: ["地下観瀑台", "秋の紅葉", "中禅寺湖"],
    features: [
      { label: "地下観瀑台", text: "エレベーターで100m降りて滝と同高さへ。水しぶきが服に届く近さ。" },
      { label: "紅葉との競演", text: "10月下旬、滝と周囲の紅葉が最高に重なる。この時期だけの特権。" },
    ],
    nearby: ["nikko-toshogu", "kinugawa-onsen"], relatedArticles: [],
  },
  {
    id: "kinugawa-onsen", title: "鬼怒川温泉", location: "日光市鬼怒川温泉",
    prefecture: "栃木県", prefectureId: "tochigi", area: "日光", areaId: "nikko-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "渓谷を見下ろす露天風呂。東京から2時間で来れる温泉峡谷。",
    longDescription: "鬼怒川温泉は江戸時代に発見された温泉地で、鬼怒川渓谷沿いに旅館が並ぶ。泉質はアルカリ単純泉で、肌がすべすべになる。渓谷を見下ろす露天風呂を持つ旅館が多く、川音を聴きながら入浴できる。鬼怒川ライン下りは4km・約30分のコースで、春から秋まで運行している。廃墟化した大型旅館が一部残っており、観光客にはカオスな写真スポットとして知られている。日光東照宮からの日帰り温泉として組み合わせる旅程が最も効率がいい。",
    tags: ["温泉", "渓谷", "栃木", "宿泊", "ライン下り"],
    stayDuration: 360, bestTime: "秋（紅葉×温泉）/ 平日", crowdLevel: "medium",
    budget: "¥12,000〜（1泊）", access: "東武鬼怒川線 鬼怒川温泉駅から徒歩5分〜", rainyDay: true,
    highlights: ["渓谷露天風呂", "鬼怒川ライン下り", "紅葉×温泉"],
    features: [
      { label: "渓谷露天風呂", text: "川を見下ろす高さにある露天風呂。秋の紅葉シーズンが圧巻。" },
      { label: "ライン下り", text: "急流区間あり。春の雪解け時期は水量が多く迫力が増す。" },
    ],
    nearby: ["nikko-toshogu", "kegon-falls"], relatedArticles: [],
  },
  {
    id: "ashikaga-flower-park", title: "足利フラワーパーク", location: "足利市迫間町",
    prefecture: "栃木県", prefectureId: "tochigi", area: "足利", areaId: "ashikaga-area",
    category: "park",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "樹齢150年の大藤が、紫の滝のように垂れ下がる。",
    longDescription: "足利フラワーパークの大藤は1房の花が「花の滝」のように長く垂れ、見頃の4月下旬〜5月上旬には藤色の天蓋がパーク全体を覆う。CNNが「世界の夢の旅行先10か所」に選んだことで国際的にも知られるようになった。大藤4本と白藤のトンネルが目玉だが、夜間ライトアップは昼間とは全く別の妖艶さがある。チケットは入場制限があり繁忙期は事前購入が必須。冬のイルミネーション（11〜2月）も圧巻。",
    tags: ["藤", "花", "夜景", "イルミネーション", "写真映え"],
    stayDuration: 120, bestTime: "4月下旬〜5月上旬（藤）/ 夜間（ライトアップ）", crowdLevel: "high",
    budget: "¥300〜1,700（季節変動）", access: "JR両毛線 富田駅から徒歩10分", rainyDay: false,
    highlights: ["大藤4本", "白藤のトンネル", "夜間ライトアップ"],
    features: [
      { label: "大藤", text: "樹齢150年の藤。1本の木が1,000平方mを覆う。スケールが異次元。" },
      { label: "夜間ライトアップ", text: "昼間の藤とは別物の妖艶な光景。見頃期は日没後1時間が最高。" },
    ],
    nearby: ["nikko-toshogu"], relatedArticles: [],
  },

  // ── 群馬 ──────────────────────────────────────
  {
    id: "kusatsu-onsen", title: "草津温泉", location: "吾妻郡草津町",
    prefecture: "群馬県", prefectureId: "gunma", area: "草津", areaId: "kusatsu-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "日本一の自然湧出量。湯畑の湯気が温泉街を包む。",
    longDescription: "草津温泉は1分間に3万2千リットルという日本一の自然湧出量を誇る。pH2.1の強酸性泉は殺菌力が高く「草津の湯は万病に効く」という言葉が残る。湯畑は温泉の源泉が流れる広場で、夜のライトアップは幻想的だ。湯もみは高温の草津の湯を冷ます伝統的な方法で、時間湯（共同浴場）文化と合わせて草津固有の入浴文化を形成している。外湯（共同浴場）は19か所あり、地蔵の湯・白旗の湯は地元民も使う。",
    tags: ["温泉", "定番", "群馬", "湯畑", "宿泊"],
    stayDuration: 480, bestTime: "夜（湯畑ライトアップ）/ 冬", crowdLevel: "high",
    budget: "¥15,000〜（1泊）", access: "上野駅から特急草津・四万号で約2時間", rainyDay: true,
    highlights: ["湯畑", "外湯めぐり", "湯もみ体験"],
    features: [
      { label: "湯畑", text: "草津の中心。毎分3万2千リットルが湧出し続ける源泉地帯。" },
      { label: "外湯19か所", text: "無料の共同浴場が複数ある。地蔵の湯は地元民率が高い本物。" },
    ],
    nearby: ["ikaho-onsen", "oze"], relatedArticles: [],
  },
  {
    id: "ikaho-onsen", title: "伊香保温泉", location: "渋川市伊香保",
    prefecture: "群馬県", prefectureId: "gunma", area: "伊香保", areaId: "ikaho-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "石段街の365段を上ると温泉街が現れる。黄金の湯と白銀の湯、2種の源泉。",
    longDescription: "伊香保温泉は温泉が湧く丘陵地に365段の石段を中心軸として温泉街が形成された、日本で最も個性的な温泉地形のひとつだ。石段の両側に旅館・みやげ店・射的場が並び、大正ロマンの雰囲気が残る。「黄金の湯」はメタケイ酸に富む茶褐色の湯で、「白銀の湯」は無色透明。両方入り比べるのが伊香保の正しい楽しみ方。石段を登り切った先の河鹿橋は、紅葉シーズンに赤いアーチが美しい。",
    tags: ["温泉", "石段街", "大正ロマン", "群馬", "レトロ"],
    stayDuration: 360, bestTime: "紅葉シーズン（11月）/ 平日", crowdLevel: "medium",
    budget: "¥10,000〜（1泊）", access: "JR上越線 渋川駅からバス25分", rainyDay: true,
    highlights: ["365段の石段", "黄金の湯・白銀の湯", "河鹿橋の紅葉"],
    features: [
      { label: "石段街", text: "365段を上がりながら、両側の温泉宿と土産物屋を眺める。射的場もある。" },
      { label: "2種の源泉", text: "茶褐色の黄金の湯と無色の白銀の湯。泉質も効能も違う2つを制覇。" },
    ],
    nearby: ["kusatsu-onsen", "tomioka-silk-mill"], relatedArticles: [],
  },
  {
    id: "oze", title: "尾瀬", location: "片品村",
    prefecture: "群馬県", prefectureId: "gunma", area: "尾瀬", areaId: "oze-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "ミズバショウと木道。標高1,400mの湿原は、本物の別世界。",
    longDescription: "尾瀬は本州最大の高層湿原で、国立公園に指定されている。6月のミズバショウと7月下旬〜8月のニッコウキスゲが2大ハイライトだ。全長60kmの木道は整備されており、ハイキング初心者でも歩ける。鳩待峠からの入山が一般的で、山の鼻ビジターセンターまで約1時間。尾瀬ヶ原は見渡す限りの湿原で、晴れた日は燧ヶ岳と至仏山の両方が水面に映る。テント泊は尾瀬ヶ原・尾瀬沼に指定地があり、夜の星空は格別。",
    tags: ["自然", "湿原", "ハイキング", "ミズバショウ", "群馬"],
    stayDuration: 480, bestTime: "ミズバショウ（6月）/ ニッコウキスゲ（7月下旬）", crowdLevel: "medium",
    budget: "¥500〜（入山料）", access: "関越道 沼田ICから鳩待峠駐車場、またはシャトルバス", rainyDay: false,
    highlights: ["尾瀬ヶ原の木道", "ミズバショウ", "燧ヶ岳・至仏山"],
    features: [
      { label: "尾瀬ヶ原の木道", text: "60kmの木道が湿原を縦断。木道を踏み外すと湿原が傷む。厳守。" },
      { label: "ミズバショウ群落", text: "6月初旬、至る所に白い仏炎苞が広がる。風がない朝は水面に映る。" },
    ],
    nearby: ["kusatsu-onsen", "ikaho-onsen"], relatedArticles: [],
  },
  {
    id: "tomioka-silk-mill", title: "富岡製糸場", location: "富岡市富岡",
    prefecture: "群馬県", prefectureId: "gunma", area: "富岡", areaId: "tomioka-area",
    category: "museum",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "明治5年建設の木骨レンガ造。日本の産業革命が始まった場所。",
    longDescription: "富岡製糸場は1872年（明治5年）に設立された官営の近代的製糸工場で、2014年に世界遺産に登録された。フランス人技師ブリュナーが設計した木骨レンガ造りの建物は、150年経った今も現役の「文化財建造物」として見学できる。東繭倉庫・西繭倉庫・繰糸場・ブリュナー館の4棟が主要見学対象。ガイドツアー（有料）は内部の機械や日本人工女の働き方を詳しく解説してくれる。",
    tags: ["世界遺産", "明治", "産業遺産", "群馬", "歴史"],
    stayDuration: 90, bestTime: "平日 / 午前中", crowdLevel: "medium",
    budget: "¥1,000", access: "上信電鉄 上州富岡駅から徒歩10分", rainyDay: true,
    highlights: ["東繭倉庫・西繭倉庫", "繰糸場", "ブリュナー館"],
    features: [
      { label: "木骨レンガ造り", text: "フランス様式の建築。明治初期の洋式建設技術の実物が現役で立っている。" },
      { label: "ガイドツアー", text: "¥200追加で60分のガイドが付く。当時の工女の生活まで説明してくれる。" },
    ],
    nearby: ["ikaho-onsen", "kusatsu-onsen"], relatedArticles: [],
  },

  // ── 茨城 ──────────────────────────────────────
  {
    id: "kairakuen", title: "偕楽園", location: "水戸市常磐町",
    prefecture: "茨城県", prefectureId: "ibaraki", area: "水戸", areaId: "mito-area",
    category: "garden",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "梅3,000本が一斉に咲く。日本三名園のひとつが、春に最強になる。",
    longDescription: "偕楽園は水戸藩主・徳川斉昭が1842年に造園した。金沢の兼六園・岡山の後楽園と並ぶ「日本三名園」のひとつだ。3月上旬〜中旬の梅まつり期間中は100種3,000本の梅が一斉に咲き、甘い香りが園内を包む。好文亭は斉昭自身が設計した木造建築で、梅林を見下ろす位置にある。千波湖との距離が近く、梅と湖と水戸の街を一度に見渡せる場所がある。入園は夏季以外は無料。",
    tags: ["庭園", "梅", "春", "日本三名園", "茨城"],
    stayDuration: 120, bestTime: "梅まつり（3月上旬〜中旬）", crowdLevel: "high",
    budget: "無料（梅まつり期間は¥300）", access: "JR常磐線 偕楽園駅（臨時）から徒歩すぐ", rainyDay: false,
    highlights: ["梅林3,000本", "好文亭", "千波湖との眺望"],
    features: [
      { label: "好文亭", text: "藩主設計の木造建築。梅林を見下ろす2階から千波湖が見える。" },
      { label: "梅まつり", text: "100種3,000本。香りで場所を選べるほど種類が多い。" },
    ],
    nearby: ["tsukuba-mountain", "fukuroda-falls"], relatedArticles: [],
  },
  {
    id: "tsukuba-mountain", title: "筑波山", location: "つくば市筑波",
    prefecture: "茨城県", prefectureId: "ibaraki", area: "筑波", areaId: "tsukuba-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80"],
    description: "男体山と女体山の双峰。関東平野を一望できる、日本百名山の最東端。",
    longDescription: "筑波山は標高877mと低山だが、関東平野の中に孤立して立つため眺望が圧倒的だ。女体山山頂（877m）からは晴れた日に東京スカイツリーまで見える。ケーブルカーとロープウェイで山頂まで行けるが、白雲橋コース（登り90分）を歩くと途中に「奇岩」と呼ばれる巨石スポットが連続する。ガマ洞窟のガマ石は必見。春の「山笑う」新緑と、秋の紅葉が特に美しい。",
    tags: ["山", "絶景", "ハイキング", "茨城", "関東平野"],
    stayDuration: 240, bestTime: "春（4〜5月）/ 秋（11月）/ 早朝", crowdLevel: "medium",
    budget: "¥1,200（ケーブルカー往復）", access: "つくばエクスプレス つくば駅からバス40分", rainyDay: false,
    highlights: ["女体山山頂（877m）", "奇岩群（白雲橋コース）", "関東平野の眺望"],
    features: [
      { label: "女体山山頂", text: "877m。晴れれば東京スカイツリーが小さく見える。ここまで来い。" },
      { label: "奇岩群", text: "弁慶七戻り・母の胎内くぐり・ガマ石。巨石の連続が面白い。" },
    ],
    nearby: ["kairakuen", "fukuroda-falls"], relatedArticles: [],
  },
  {
    id: "fukuroda-falls", title: "袋田の滝", location: "久慈郡大子町袋田",
    prefecture: "茨城県", prefectureId: "ibaraki", area: "奥久慈", areaId: "okukuji-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80"],
    description: "4段に分かれて落ちる滝。冬は凍結し、氷瀑になる。",
    longDescription: "袋田の滝は高さ120m・幅73mで日本三名瀑のひとつに数えられる。4段に分かれて落ちることから「四度の滝」とも呼ばれる。滝壺に近い第1観瀑台と、吊り橋を渡って正面から見る第2観瀑台の2か所から見学できる。1月〜2月の厳冬期は完全に凍結する「氷瀑」が見られることがあり、寒い年ほど凍結率が高い。奥久慈温泉郷が近く、滝見学と温泉をセットにした日帰り旅程が人気。",
    tags: ["滝", "氷瀑", "自然", "茨城", "日本三名瀑"],
    stayDuration: 90, bestTime: "紅葉（11月）/ 氷瀑（1〜2月）", crowdLevel: "medium",
    budget: "¥300（観瀑台トンネル）", access: "JR水郡線 袋田駅から徒歩20分", rainyDay: false,
    highlights: ["4段の滝（高さ120m）", "冬の氷瀑", "第2観瀑台（吊り橋）"],
    features: [
      { label: "氷瀑", text: "寒い冬は完全凍結する。白と透明が混じった氷の壁は自然の彫刻。" },
      { label: "第2観瀑台", text: "吊り橋を渡った先。正面から滝全体が見える唯一の場所。" },
    ],
    nearby: ["kairakuen", "tsukuba-mountain"], relatedArticles: [],
  },
  {
    id: "oarai-isosaki-shrine", title: "大洗磯前神社", location: "東茨城郡大洗町",
    prefecture: "茨城県", prefectureId: "ibaraki", area: "大洗", areaId: "oarai-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80"],
    description: "太平洋に突き出た岩礁に立つ鳥居。日の出の時、海から神が来る。",
    longDescription: "大洗磯前神社の「神磯の鳥居」は岩礁の上に立ち、荒波に打たれながら太平洋に面する。日の出の時間に来ると、鳥居の間から太陽が昇る瞬間を拝める。元旦は全国から初日の出撮影の写真家が集まる名所。神社本殿は丘上にあり、石段を登ると大洗の海岸線が一望できる。大洗は海鮮も名物で、磯前神社から徒歩圏内のアクアワールド茨城県大洗水族館はサメの展示種類日本一で家族連れにも人気。",
    tags: ["神社", "日の出", "海", "鳥居", "写真映え"],
    stayDuration: 90, bestTime: "日の出の時間 / 元旦", crowdLevel: "medium",
    budget: "無料", access: "鹿島臨海鉄道 大洗駅から徒歩15分", rainyDay: false,
    highlights: ["神磯の鳥居", "日の出", "本殿からの眺望"],
    features: [
      { label: "神磯の鳥居", text: "岩礁に立つ鳥居。波が高い日は水しぶきがかかる位置にある。" },
      { label: "日の出の瞬間", text: "鳥居の間から太陽が昇るタイミングは年に数回。それ以外も美しい。" },
    ],
    nearby: ["kairakuen", "tsukuba-mountain"], relatedArticles: [],
  },
];
