import { Spot } from "@/types/spot";

export const kinkiSpots: Spot[] = [
  {
    id: "fushimi-inari", title: "伏見稲荷大社", location: "京都市伏見区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "shrine",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg/1280px-Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg"],
    description: "千本鳥居の朱が、視界を埋め尽くす。",
    longDescription: "観光客が殺到する午前10時を避けて、早朝6時に来い。誰もいない千本鳥居を独り占めできる。奥社から先の四ツ辻までは約40分の山道。ここまで来る人は少ない。振り返ると京都の街が一望できる。頂上まで行く必要はない。四ツ辻のベンチに座って、汗が引くのを待つ。それだけで十分に「来た」と思える場所。",
    tags: ["神社", "早朝", "写真映え", "一人旅", "定番"],
    stayDuration: 90, bestTime: "早朝 6:00〜7:30", crowdLevel: "high",
    budget: "無料", access: "JR奈良線 稲荷駅から徒歩すぐ", rainyDay: false,
    highlights: ["千本鳥居", "四ツ辻の展望", "奥社奉拝所"],
    features: [
      { label: "千本鳥居", text: "朱の鳥居が延々と続くトンネル。写真を撮るなら早朝一択。" },
      { label: "四ツ辻", text: "稲荷山の中腹。京都市街を見下ろすビューポイント。" },
      { label: "参道の茶屋", text: "登山途中にある茶屋でいなり寿司を食べる。これが正解。" },
    ],
    nearby: ["kiyomizu", "gion"], relatedArticles: ["kyoto-family-fushimi"],
  },
  {
    id: "kiyomizu", title: "清水寺", location: "京都市東山区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Kiyomizu-dera_in_Kyoto-r.jpg/1280px-Kiyomizu-dera_in_Kyoto-r.jpg"],
    description: "崖の上に浮かぶ舞台。京都で一番、空に近い場所。",
    longDescription: "清水の舞台から飛び降りる、という言葉がある。実際に立つとわかる。この高さは冗談じゃない。紅葉シーズンの夜間拝観は、舞台の下から見上げるのがいい。ライトアップされた本堂が闇に浮かぶ。音羽の滝は3つの筋があって、それぞれ学業・恋愛・長寿。全部飲むのは欲張りらしい。",
    tags: ["寺院", "紅葉", "夜景", "定番", "写真映え"],
    stayDuration: 60, bestTime: "朝 6:00（開門直後）", crowdLevel: "high",
    budget: "¥400", access: "京阪 清水五条駅から徒歩25分", rainyDay: false,
    highlights: ["清水の舞台", "音羽の滝", "三年坂・二年坂"],
    features: [
      { label: "舞台からの眺望", text: "13mの高さから京都盆地を一望。秋は紅葉の海になる。" },
      { label: "三年坂の石畳", text: "清水寺への参道。転ぶと三年で死ぬという迷信がある。" },
    ],
    nearby: ["fushimi-inari", "gion"], relatedArticles: ["kyoto-kiyomizu-deep-dive"],
  },
  {
    id: "gion", title: "祇園・花見小路", location: "京都市東山区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "street",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Wooden_and_bamboo_facades_of_dwellings_with_sudare_in_a_cobbled_street_of_Gion%2C_perspective_effect_with_vanishing_point.jpg/1280px-Wooden_and_bamboo_facades_of_dwellings_with_sudare_in_a_cobbled_street_of_Gion%2C_perspective_effect_with_vanishing_point.jpg"],
    description: "石畳と格子戸。夕暮れの一瞬だけ、舞妓に会える。",
    longDescription: "花見小路は昼と夜で全く違う場所になる。昼は観光客が多いが、日が暮れると急に静かになる。18時過ぎに歩くと、お座敷に向かう舞妓さんとすれ違うことがある。写真を撮るのは禁止。見るだけ。白川沿いの柳が風に揺れる景色は、京都で最も美しい一瞬のひとつ。",
    tags: ["街歩き", "夕暮れ", "伝統", "カップル"],
    stayDuration: 60, bestTime: "夕方 17:00〜19:00", crowdLevel: "medium",
    budget: "無料", access: "京阪 祇園四条駅から徒歩5分", rainyDay: false,
    highlights: ["花見小路", "白川沿い", "建仁寺"],
    features: [
      { label: "夕暮れの花見小路", text: "観光客が引いた後、格子戸に灯りが入る。この時間が本番。" },
      { label: "白川沿いの散歩", text: "柳と石橋。祇園の喧騒から一本入るだけで静けさがある。" },
    ],
    nearby: ["kiyomizu", "fushimi-inari"], relatedArticles: ["kyoto-higashiyama-night-walk"],
  },
  {
    id: "arashiyama", title: "嵐山・竹林の小径", location: "京都市右京区",
    prefecture: "京都府", prefectureId: "kyoto", area: "嵐山", areaId: "arashiyama-area",
    category: "park",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Bamboo_forest_01.jpg/1280px-Bamboo_forest_01.jpg"],
    description: "竹の音だけが聞こえる。嵐山の奥に、別世界がある。",
    longDescription: "竹林の小径は朝7時前なら人がいない。天龍寺の裏手から入って、風が竹を揺らす音だけを聴く。嵯峨野トロッコ列車は片道だけ乗るのが正解。行きはトロッコ、帰りは保津川下り。渡月橋は夕方が美しい。山の稜線が夕日で赤く染まる。",
    tags: ["自然", "早朝", "写真映え", "カップル"],
    stayDuration: 120, bestTime: "早朝 7:00前", crowdLevel: "high",
    budget: "無料", access: "JR嵯峨嵐山駅から徒歩10分", rainyDay: false,
    highlights: ["竹林の小径", "渡月橋", "天龍寺"],
    features: [
      { label: "竹林", text: "見上げると空が竹で区切られている。風の音が唯一のBGM。" },
      { label: "渡月橋の夕景", text: "嵐山のシルエットが夕日に染まる。橋の上で立ち止まるべき瞬間。" },
    ],
    nearby: ["gion", "kiyomizu"],
  },
  {
    id: "nara-park", title: "奈良公園", location: "奈良市",
    prefecture: "奈良県", prefectureId: "nara", area: "奈良", areaId: "nara-city",
    category: "park",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Sika_Deer_in_Nara%2C_Japan%2C_20240819_1546_4782.jpg/1280px-Sika_Deer_in_Nara%2C_Japan%2C_20240819_1546_4782.jpg"],
    description: "鹿と大仏と芝生。1300年前から変わらない、のんびりした時間。",
    longDescription: "奈良公園の鹿は「野生動物」であって、ペットではない。鹿せんべいを持っていると囲まれるが、それも含めて体験。東大寺の大仏殿に入ると、想像の3倍デカい。柱の穴くぐりは子供向けに見えるが、大人がやると盛り上がる。春日大社の参道は木漏れ日が美しい。午後の遅い時間に歩くのがいい。",
    tags: ["自然", "歴史", "家族", "のんびり"],
    stayDuration: 180, bestTime: "午前中", crowdLevel: "medium",
    budget: "無料", access: "近鉄奈良駅から徒歩5分", rainyDay: false,
    highlights: ["鹿", "東大寺大仏殿", "春日大社", "若草山"],
    features: [
      { label: "鹿とのふれあい", text: "鹿せんべいは150円。お辞儀する鹿がいる。しない鹿もいる。" },
      { label: "東大寺", text: "世界最大級の木造建築。中に入ると音が消える感覚がある。" },
      { label: "春日大社の参道", text: "石灯籠が並ぶ参道。午後の木漏れ日が一番きれい。" },
    ],
    nearby: ["yoshino"],
  },
  {
    id: "dotonbori", title: "道頓堀", location: "大阪市中央区",
    prefecture: "大阪府", prefectureId: "osaka", area: "大阪", areaId: "minami",
    category: "street",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Dotonbori_Osaka_Japan01-r.jpg/1280px-Dotonbori_Osaka_Japan01-r.jpg"],
    description: "ネオンと串カツと人混み。大阪の胃袋は、ここにある。",
    longDescription: "道頓堀は「観光地」として消費するより「食べ歩き」として体験するのが正解。たこ焼きはわなか、串カツはだるま、お好み焼きは美津の。この3つを回るだけで満足度が高い。グリコの看板の前で写真を撮るのは全員やるけど、橋の上からの夜景の方が絵になる。法善寺横丁は道頓堀から一歩入るだけで、全く違う空気になる。",
    tags: ["グルメ", "夜", "にぎやか", "食べ歩き", "定番"],
    stayDuration: 120, bestTime: "夜 18:00以降", crowdLevel: "high",
    budget: "¥2,000〜", access: "地下鉄 なんば駅から徒歩5分", rainyDay: true,
    highlights: ["グリコ看板", "法善寺横丁", "たこ焼き巡り"],
    features: [
      { label: "食べ歩き", text: "たこ焼き→串カツ→お好み焼き。この順番で回ると胃がもつ。" },
      { label: "法善寺横丁", text: "道頓堀の喧騒から一歩入った石畳の路地。水かけ不動が鎮座する。" },
    ],
    nearby: ["shinsekai"], relatedArticles: ["osaka-dotonbori-night-walk"],
  },
  {
    id: "shinsekai", title: "新世界", location: "大阪市浪速区",
    prefecture: "大阪府", prefectureId: "osaka", area: "大阪", areaId: "shinsekai-area",
    category: "street",
    images: ["https://upload.wikimedia.org/wikipedia/commons/0/0b/Original_Tsutenkaku_and_Shinsekai_2.jpg"],
    description: "通天閣の足元で、串カツを揚げる音が響く。",
    longDescription: "新世界は「レトロ」とか「ディープ」とか言われるけど、地元の人は普通にここで酒を飲んでいる。ジャンジャン横丁の串カツ屋は朝から開いている店がある。通天閣に登るかどうかは自由。登らなくても、下から見上げるだけで十分に「新世界に来た」感がある。",
    tags: ["グルメ", "レトロ", "一人旅", "ディープ"],
    stayDuration: 90, bestTime: "昼〜夕方", crowdLevel: "medium",
    budget: "¥1,500〜", access: "地下鉄 動物園前駅から徒歩3分", rainyDay: true,
    highlights: ["通天閣", "ジャンジャン横丁", "串カツ"],
    features: [
      { label: "ジャンジャン横丁", text: "串カツ屋が密集するアーケード。ソースの二度漬けは禁止。" },
      { label: "通天閣", text: "展望台よりも、足元の商店街の方が面白い。" },
    ],
    nearby: ["dotonbori"], relatedArticles: ["osaka-shinsekai-retro-walk"],
  },
  {
    id: "kinosaki", title: "城崎温泉", location: "豊岡市城崎町",
    prefecture: "兵庫県", prefectureId: "hyogo", area: "城崎", areaId: "kinosaki-area",
    category: "onsen",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Kinosaki_onsen_station.jpg/1280px-Kinosaki_onsen_station.jpg"],
    description: "浴衣で歩く、7つの湯。温泉街の「正解」がここにある。",
    longDescription: "城崎温泉は「外湯めぐり」が本体。宿の内湯に入るより、浴衣とゲタで7つの外湯をハシゴするのがここの流儀。泉質が全部違うから、お気に入りを見つけるのが楽しい。柳並木の夜景は風情がある。冬のカニは松葉ガニ。カニ刺し、焼きガニ、カニすき、カニ雑炊のフルコースは一生に一度は食べるべき。",
    tags: ["温泉", "浴衣", "カップル", "冬", "グルメ"],
    stayDuration: 360, bestTime: "夕方〜夜", crowdLevel: "medium",
    budget: "¥15,000〜（1泊）", access: "大阪から特急こうのとりで約2時間40分", rainyDay: true,
    highlights: ["外湯めぐり", "柳並木", "冬の松葉ガニ"],
    features: [
      { label: "外湯7湯", text: "1日券でハシゴ放題。御所の湯が一番人気。" },
      { label: "柳並木の夕景", text: "大谿川沿いの柳が風に揺れる。温泉街で最も美しい瞬間。" },
      { label: "松葉ガニ", text: "11月〜3月限定。この時期に来る理由がこれ。" },
    ],
    nearby: [], relatedArticles: ["hyogo-kinosaki-onsen-walk"],
  },
  {
    id: "yoshino", title: "吉野山", location: "吉野郡吉野町",
    prefecture: "奈良県", prefectureId: "nara", area: "吉野", areaId: "yoshino-area",
    category: "mountain",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Yoshino-yama_2008_banner.jpg/1280px-Yoshino-yama_2008_banner.jpg"],
    description: "3万本の桜が、山を下から上へ染めていく。",
    longDescription: "吉野の桜は「一目千本」と言われる。下千本→中千本→上千本→奥千本と、標高に沿って順に咲くから、時期をずらせば1ヶ月近く桜を楽しめる。金峯山寺の蔵王堂は桜の時期だけ特別拝観がある。秘仏の蔵王権現は青い肌をしていて、想像と全く違う。",
    tags: ["桜", "自然", "寺院", "春"],
    stayDuration: 240, bestTime: "4月上旬〜中旬", crowdLevel: "high",
    budget: "無料", access: "近鉄 吉野駅からロープウェイ", rainyDay: false,
    highlights: ["一目千本", "金峯山寺", "奥千本"],
    features: [
      { label: "一目千本", text: "中千本から見下ろす桜の海。写真では伝わらないスケール。" },
      { label: "金峯山寺", text: "蔵王権現の秘仏は春と秋だけ。青い肌の巨大仏に圧倒される。" },
    ],
    nearby: ["nara-park"],
  },
  {
    id: "nanki-shirahama", title: "南紀白浜", location: "西牟婁郡白浜町",
    prefecture: "和歌山県", prefectureId: "wakayama", area: "白浜", areaId: "shirahama-area",
    category: "beach",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/131221_Shirarahama_Beach_Shirahama_Wakayama_pref_Japan07s3bs.jpg/1280px-131221_Shirarahama_Beach_Shirahama_Wakayama_pref_Japan07s3bs.jpg"],
    description: "白い砂浜と青い海。関西から一番近い「南国」。",
    longDescription: "白良浜の砂は元々白い石英砂。海の透明度は沖縄に匹敵する。円月島は夕日が岩の穴を通り抜ける瞬間を狙う。三段壁の洞窟は波が荒い日の方が迫力がある。とれとれ市場で海鮮丼を食べて、崎の湯で太平洋を見ながら入浴する。これが白浜の黄金ルート。",
    tags: ["ビーチ", "温泉", "家族", "夏"],
    stayDuration: 360, bestTime: "夏（7〜8月）", crowdLevel: "high",
    budget: "¥10,000〜", access: "大阪から特急くろしおで約2時間半", rainyDay: false,
    highlights: ["白良浜", "円月島", "三段壁", "崎の湯"],
    features: [
      { label: "白良浜", text: "真っ白な砂浜。海の色が本当にエメラルドグリーン。" },
      { label: "崎の湯", text: "太平洋に面した露天風呂。波しぶきが飛んでくる距離感。" },
      { label: "円月島の夕日", text: "岩の穴を夕日が通り抜ける瞬間。年に2回、完全に通過する。" },
    ],
    nearby: ["kumano-kodo"],
  },
  {
    id: "himeji", title: "姫路城", location: "姫路市",
    prefecture: "兵庫県", prefectureId: "hyogo", area: "姫路", areaId: "himeji-area",
    category: "castle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Himeji_Castle_The_Keep_Towers.jpg/1280px-Himeji_Castle_The_Keep_Towers.jpg"],
    description: "白すぎて、空に溶ける。日本で最も美しい城。",
    longDescription: "姫路城は「白鷺城」の名の通り、白い。改修後は特に白い。快晴の日に行くと、白い城と青い空の境界が曖昧になる。天守閣まで登ると、急な階段に足がすくむ。でも最上階から見る姫路の街は、登った甲斐がある。西の丸から見る天守閣の構図が一番美しい。桜の時期は三の丸広場が花見客で埋まる。",
    tags: ["城", "歴史", "写真映え", "一人旅"],
    stayDuration: 120, bestTime: "午前中", crowdLevel: "medium",
    budget: "¥1,000", access: "JR姫路駅から徒歩15分", rainyDay: false,
    highlights: ["天守閣", "西の丸", "好古園"],
    features: [
      { label: "天守閣", text: "6階建て。最上階まで登ると姫路市街が一望できる。" },
      { label: "西の丸からの構図", text: "天守閣を最も美しく撮れるポイント。午前の光が正解。" },
    ],
    nearby: [],
  },
  {
    id: "kumano-kodo", title: "熊野古道", location: "田辺市・新宮市",
    prefecture: "和歌山県", prefectureId: "wakayama", area: "熊野", areaId: "kumano-area",
    category: "mountain",
    images: ["https://upload.wikimedia.org/wikipedia/commons/e/e3/Kumano_Kodo_2.jpg"],
    description: "石畳を踏む足音だけが響く。1000年前の道を歩く。",
    longDescription: "熊野古道は世界遺産の巡礼路。中辺路の滝尻王子から熊野本宮大社までが最もポピュラーなルート。全部歩くと2〜3日かかるが、発心門王子から本宮大社までなら約3時間で歩ける。石畳の道を歩いていると、木漏れ日と苔と湿った空気が混ざった匂いがする。大斎原の大鳥居は日本一の大きさ。田んぼの中にぽつんと立っている姿が、かえって神秘的。",
    tags: ["トレッキング", "歴史", "スピリチュアル", "一人旅"],
    stayDuration: 300, bestTime: "春・秋", crowdLevel: "low",
    budget: "無料", access: "紀伊田辺駅からバス", rainyDay: false,
    highlights: ["中辺路", "熊野本宮大社", "大斎原", "那智の滝"],
    features: [
      { label: "中辺路の石畳", text: "苔むした石段を踏む感触。1000年分の祈りが積もっている。" },
      { label: "大斎原", text: "日本一の大鳥居。田んぼの中に突然現れる巨大な朱の門。" },
    ],
    nearby: ["nanki-shirahama"],
  },
  {
    id: "kinkakuji", title: "金閣寺", location: "京都市北区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Kinkakuji_%28Golden_Pavilion%29%2C_Kyoto%2C_Japan.jpg/1280px-Kinkakuji_%28Golden_Pavilion%29%2C_Kyoto%2C_Japan.jpg"],
    description: "金箔に包まれた三層の塔が、鏡湖池に逆さに映る。",
    longDescription: "金閣寺の正式名称は鹿苑寺。「金閣」と呼ばれる舎利殿は3層構造で、上2層が金箔張り。鏡湖池の水面に映る逆さ金閣は、晴れた朝に最も美しく見える。人が少ない開門直後の8時台を狙うべきだ。境内は一方通行のルートになっていて、人の流れに乗って歩けば30分もあれば回れる。庭園の奥の茶屋で抹茶と干菓子を食べるのが正しい締め方。",
    tags: ["寺院", "写真映え", "世界遺産", "定番", "朝"],
    stayDuration: 60, bestTime: "早朝 8:00〜9:00", crowdLevel: "high",
    budget: "¥500", access: "市バス 金閣寺道バス停から徒歩3分", rainyDay: false,
    highlights: ["鏡湖池の逆さ金閣", "金箔張りの舎利殿", "陸舟の松"],
    features: [
      { label: "鏡湖池", text: "池の水面に映り込む金閣。風がない朝は完全なシンメトリーになる。" },
      { label: "舎利殿の金箔", text: "2・3層は純金箔張り。曇りの日より晴れの日の方が輝きが増す。" },
      { label: "陸舟の松", text: "船の形に仕立てられた天然記念物の松。足利義満が愛でた樹形。" },
    ],
    nearby: ["arashiyama", "nijo-castle"], relatedArticles: ["kyoto-photo-spot-golden-hour", "kyoto-solo-day-walk"],
  },
  {
    id: "nijo-castle", title: "二条城", location: "京都市中京区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "castle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Nijo_Castle%2C_Kyoto%2C_Japan._%2810795618264%29.jpg/1280px-Nijo_Castle%2C_Kyoto%2C_Japan._%2810795618264%29.jpg"],
    description: "徳川将軍が京都に構えた城。廊下を歩くたびにキュッと鳴る。",
    longDescription: "二条城の二の丸御殿は、床下に「うぐいす張り」の廊下がある。釘が摩擦して音を立てる構造で、忍び込んだ者を察知するための仕掛けだ。廊下を歩くたびにキュッキュッと鳴る感触が面白い。大政奉還が行われた場所でもある。二の丸庭園は小堀遠州作と伝わる名園で、桜の時期はライトアップもある。世界遺産の割には入場料が安く、コストパフォーマンスが高い。",
    tags: ["城", "歴史", "世界遺産", "桜"],
    stayDuration: 90, bestTime: "午前中", crowdLevel: "medium",
    budget: "¥1,300", access: "地下鉄東西線 二条城前駅から徒歩すぐ", rainyDay: true,
    highlights: ["うぐいす張りの廊下", "二の丸御殿", "二の丸庭園"],
    features: [
      { label: "うぐいす張り", text: "歩くたびに鳴る廊下。防犯機能だが、体験するとつい何度も踏みたくなる。" },
      { label: "二の丸御殿", text: "国宝。大政奉還が行われた歴史的空間。内部の障壁画が圧倒的。" },
    ],
    nearby: ["kinkakuji", "gion"], relatedArticles: ["kyoto-solo-day-walk", "kyoto-rainy-day-plan"],
  },
  {
    id: "uji-byodoin", title: "平等院鳳凰堂", location: "宇治市",
    prefecture: "京都府", prefectureId: "kyoto", area: "宇治", areaId: "uji",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Byodoin_Phoenix_Hall_Uji_10-1R.jpg/1280px-Byodoin_Phoenix_Hall_Uji_10-1R.jpg"],
    description: "10円硬貨に刻まれた建物が、池の向こうに実在している。",
    longDescription: "平等院鳳凰堂は1053年建立。極楽浄土を地上に再現しようとした藤原頼通の意図が、1000年後もそのまま残っている。阿字池に映る鳳凰堂の姿は、10円玉と全く同じ構図だ。内部のミュージアム鳳翔館には国宝の梵鐘と雲中供養菩薩像が収蔵されている。宇治は抹茶の産地でもあり、参道の抹茶ソフトクリームは外せない。京都市内より観光客が少なく、落ち着いて見られる。",
    tags: ["寺院", "世界遺産", "歴史", "抹茶"],
    stayDuration: 90, bestTime: "午前中", crowdLevel: "medium",
    budget: "¥700", access: "京阪 宇治駅から徒歩10分 / JR宇治駅から徒歩10分", rainyDay: false,
    highlights: ["鳳凰堂", "阿字池の逆さ映り", "鳳翔館の国宝"],
    features: [
      { label: "阿字池", text: "水面に映る鳳凰堂が10円玉そのまま。晴れた朝が一番きれい。" },
      { label: "ミュージアム鳳翔館", text: "雲中供養菩薩像52体が壁に並ぶ光景。見応えがある。" },
      { label: "宇治の抹茶", text: "参道の茶店で飲む抹茶は産地直送の本物。抹茶ソフトも必食。" },
    ],
    nearby: ["fushimi-inari", "kiyomizu"], relatedArticles: ["kyoto-solo-day-walk", "kyoto-budget-temple-pass"],
  },
  {
    id: "osaka-castle", title: "大阪城", location: "大阪市中央区",
    prefecture: "大阪府", prefectureId: "osaka", area: "大阪", areaId: "kita",
    category: "castle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Osaka_Castle%2C_Keep_tower%2C_South_view_20190415_1.jpg/1280px-Osaka_Castle%2C_Keep_tower%2C_South_view_20190415_1.jpg"],
    description: "豊臣秀吉の夢の跡が、大阪の街の真ん中に屹立している。",
    longDescription: "大阪城は豊臣秀吉が築いた城だが、今の天守閣は昭和初期に復元されたもの。外観は立派だが内部はエレベーター付きの博物館だ。それでも最上階からの眺望は本物で、大阪平野が一望できる。桜の時期は西の丸庭園が花見客で埋まる。城の正面から見る構図より、内堀越しに見る角度の方が写真映えする。極楽橋から撮る金の虎が映える構図を見つけた人は、大阪城を制した。",
    tags: ["城", "歴史", "桜", "写真映え"],
    stayDuration: 90, bestTime: "午前中", crowdLevel: "high",
    budget: "¥600", access: "地下鉄谷町線 天満橋駅から徒歩15分 / JR大阪城公園駅から徒歩15分", rainyDay: false,
    highlights: ["天守閣からの眺望", "内堀と石垣", "西の丸庭園"],
    features: [
      { label: "天守閣8階", text: "大阪平野を360度見渡せる展望台。夕方はビル群のシルエットが美しい。" },
      { label: "石垣", text: "巨大な切り石を積み上げた野面積み。豊臣時代の石垣が今も一部残る。" },
    ],
    nearby: ["dotonbori", "kuromon-market"], relatedArticles: ["osaka-spring-sakura-spots", "osaka-photo-spots-guide"],
  },
  {
    id: "kuromon-market", title: "黒門市場", location: "大阪市中央区",
    prefecture: "大阪府", prefectureId: "osaka", area: "大阪", areaId: "minami",
    category: "market",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Seafood_in_Kuromon_Market%2C_Osaka_on_June_7th%2C_2017.jpg/1280px-Seafood_in_Kuromon_Market%2C_Osaka_on_June_7th%2C_2017.jpg"],
    description: "大阪の台所と呼ばれてきた市場で、朝から海鮮を食べる。",
    longDescription: "黒門市場は明治時代から続く生鮮市場。「大阪の台所」と呼ばれてきたが、今は食べ歩きの場として機能している。マグロ、カニ、ウニ、牡蠣——その場でさばいてくれる海鮮を立ったまま食べる。値段は観光地価格だが、鮮度は本物だ。早朝から開いている店と昼前に閉まる店が混在しているので、10時台に来るのがベスト。アーケードがあるので雨の日でも快適に歩ける。",
    tags: ["グルメ", "市場", "海鮮", "食べ歩き"],
    stayDuration: 60, bestTime: "午前 10:00〜11:00", crowdLevel: "high",
    budget: "¥2,000〜", access: "地下鉄堺筋線 日本橋駅から徒歩3分", rainyDay: true,
    highlights: ["海鮮食べ歩き", "マグロ串", "生牡蠣"],
    features: [
      { label: "海鮮立ち食い", text: "その場でさばいたマグロやカニを串に刺して食べる。市場ならではの体験。" },
      { label: "アーケード商店街", text: "全天候型のアーケードで約170店舗。雨でも関係なく歩ける。" },
    ],
    nearby: ["dotonbori", "shinsekai"], relatedArticles: ["osaka-morning-market", "osaka-street-food-tour"],
  },
  {
    id: "sumiyoshi-taisha", title: "住吉大社", location: "大阪市住吉区",
    prefecture: "大阪府", prefectureId: "osaka", area: "大阪", areaId: "minami",
    category: "shrine",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Sumiyoshi-taisha_%28Osaka_Sumiyoshi-ku%29_Shrine_hdsr_S5_c21.jpg/1280px-Sumiyoshi-taisha_%28Osaka_Sumiyoshi-ku%29_Shrine_hdsr_S5_c21.jpg"],
    description: "全国2300社の総本社。そり橋を渡ると、別世界が始まる。",
    longDescription: "住吉大社は全国に約2300ある住吉神社の総本社で、創建は211年と伝わる。反橋（太鼓橋）は傾斜が急で、渡るには少し気合いがいる。橋を渡るだけで罪穢れが祓われるとされている。4つの本殿が縦に並ぶ「住吉造」は日本最古の神社建築様式のひとつ。初詣の参拝者数は全国でも上位に入り、三が日で230万人が訪れる。観光客が少ない平日午前中は、境内が静かで本来の空気を感じられる。",
    tags: ["神社", "歴史", "パワースポット", "初詣"],
    stayDuration: 60, bestTime: "平日午前中", crowdLevel: "medium",
    budget: "無料", access: "南海本線 住吉大社駅から徒歩すぐ / 阪堺電車 住吉鳥居前駅から徒歩すぐ", rainyDay: false,
    highlights: ["反橋（太鼓橋）", "4つの本殿", "住吉造の建築"],
    features: [
      { label: "反橋", text: "急傾斜の朱塗りの太鼓橋。渡ること自体がお祓いになるとされる。" },
      { label: "住吉造", text: "4棟の本殿が縦に並ぶ日本最古の建築様式のひとつ。現存する数少ない遺構。" },
    ],
    nearby: ["dotonbori", "shinsekai"], relatedArticles: ["osaka-solo-backpacker", "osaka-photo-spots-guide"],
  },
  {
    id: "todaiji", title: "東大寺", location: "奈良市",
    prefecture: "奈良県", prefectureId: "nara", area: "奈良", areaId: "nara-city",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/The_Great_Buddha_Hall_of_T%C5%8Ddai-ji%2C_Nara%2C_November_2016.jpg/1280px-The_Great_Buddha_Hall_of_T%C5%8Ddai-ji%2C_Nara%2C_November_2016.jpg"],
    description: "世界最大級の木造建築の中に、想像の3倍でかい大仏がいる。",
    longDescription: "東大寺の大仏殿は現存する世界最大の木造建築。中に入ると、高さ15mの廬舎那仏が鎮座している。想像より圧倒的に大きい。柱の穴くぐりは大仏の鼻の穴と同じ大きさとされ、通り抜けると無病息災のご利益があると言われる。大人がやっても意外と通れる。二月堂はお水取りで有名で、高台から奈良の街が見渡せる。早朝に来ると鹿が境内を自由に歩き回っている光景が見られる。",
    tags: ["寺院", "世界遺産", "歴史", "大仏", "定番"],
    stayDuration: 90, bestTime: "開門直後 7:30〜9:00", crowdLevel: "high",
    budget: "¥600", access: "近鉄奈良駅から徒歩20分 / 市内バス 大仏殿春日大社前停から徒歩5分", rainyDay: false,
    highlights: ["大仏殿", "廬舎那仏", "柱の穴くぐり", "二月堂"],
    features: [
      { label: "廬舎那仏", text: "高さ15m、重さ500トン。見上げると首が痛くなるスケール。" },
      { label: "柱の穴くぐり", text: "大仏の鼻の穴と同じ大きさの穴。通り抜けると御利益ありとされる。" },
      { label: "二月堂", text: "高台にある堂。奈良盆地が一望でき、お水取りの舞台としても有名。" },
    ],
    nearby: ["nara-park", "kasuga-taisha"], relatedArticles: ["nara-todaiji-deep-dive", "nara-deer-park-morning"],
  },
  {
    id: "kasuga-taisha", title: "春日大社", location: "奈良市",
    prefecture: "奈良県", prefectureId: "nara", area: "奈良", areaId: "nara-city",
    category: "shrine",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Kasuga_Taisha_Shrine_%40_Nara.jpg/1280px-Kasuga_Taisha_Shrine_%40_Nara.jpg"],
    description: "3000基の燈籠が灯る夜。奈良を守り続けた神の社。",
    longDescription: "春日大社は768年創建。全国に約1000社ある春日神社の総本社だ。境内には石燈籠と釣燈籠を合わせて約3000基ある。2月と8月の万燈籠の夜は全燈籠に火が入り、別世界になる。参道の春日原始林は世界遺産の森で、木漏れ日と苔の匂いが混ざった空気が独特。鹿は春日大社の神使とされていて、もともとは神鹿を奈良の地に連れてきたのが始まりという。",
    tags: ["神社", "世界遺産", "歴史", "燈籠", "パワースポット"],
    stayDuration: 60, bestTime: "午後の木漏れ日の時間帯", crowdLevel: "medium",
    budget: "無料（本殿は¥500）", access: "近鉄奈良駅から徒歩25分 / 市内バス 春日大社本殿停からすぐ", rainyDay: false,
    highlights: ["3000基の燈籠", "万燈籠の夜", "春日原始林の参道"],
    features: [
      { label: "燈籠の参道", text: "石燈籠が並ぶ原始林の参道。午後の木漏れ日が石に落ちる瞬間が美しい。" },
      { label: "万燈籠", text: "2月と8月の年2回、3000基全部に火が灯る。この夜だけのために来る価値がある。" },
    ],
    nearby: ["nara-park", "todaiji"], relatedArticles: ["nara-kasuga-taisha-visit", "nara-ancient-history-tour"],
  },
  {
    id: "horyuji", title: "法隆寺", location: "生駒郡斑鳩町",
    prefecture: "奈良県", prefectureId: "nara", area: "奈良", areaId: "nara-city",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Ikaruga.-_Le_temple_Horyuji_Sannai.jpg/1280px-Ikaruga.-_Le_temple_Horyuji_Sannai.jpg"],
    description: "1400年前の木造建築が、今も使われている。それだけで十分に奇跡だ。",
    longDescription: "法隆寺の西院伽藍は世界最古の木造建築群。607年に聖徳太子が建立したとされる五重塔と金堂は、今も現役の寺院として機能している。1993年に日本初のユネスコ世界文化遺産に登録された。夢殿は八角形の特異な形で、中には秘仏の救世観音菩薩が安置されている。拝観者が少なく、奈良市内より静かに見学できる。電車で30分の距離感が、逆に「わざわざ来た」感を強める。",
    tags: ["寺院", "世界遺産", "歴史", "聖徳太子"],
    stayDuration: 90, bestTime: "午前中", crowdLevel: "low",
    budget: "¥1,500", access: "JR大和路線 法隆寺駅から徒歩20分 / バスで法隆寺門前停", rainyDay: false,
    highlights: ["五重塔", "金堂（世界最古の木造建築）", "夢殿"],
    features: [
      { label: "五重塔", text: "607年建立。世界最古の木造建築のひとつ。雨にも地震にも1400年耐えてきた。" },
      { label: "夢殿", text: "八角形の堂。春と秋だけ秘仏の救世観音が公開される。" },
    ],
    nearby: ["nara-park", "todaiji"], relatedArticles: ["nara-horyuji-ancient-walk", "nara-ancient-history-tour"],
  },
  {
    id: "kobe-harborland", title: "神戸ハーバーランド", location: "神戸市中央区",
    prefecture: "兵庫県", prefectureId: "hyogo", area: "神戸", areaId: "kobe",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Kobe_Port_Tower_and_Harborland_at_night_20190202-2.jpg/1280px-Kobe_Port_Tower_and_Harborland_at_night_20190202-2.jpg"],
    description: "ポートタワーが水面に映る夜。神戸の夜景はここから始まる。",
    longDescription: "神戸ハーバーランドは、廃線跡地を再開発した港湾エリア。煉瓦倉庫群とガラス張りのショッピング施設が混在し、神戸らしい「古さと新しさが混ざった」景観をつくっている。夜になると、対岸のメリケンパークから見るポートタワーの赤いライトアップが水面に伸びる。その反射が神戸の夜景を完成させる。昼は商業施設でランチ、夕方から海沿いを歩いて夜景を待つのがハーバーランドの正しい使い方だ。umieモザイクの観覧車に乗ると、六甲山と大阪湾が同時に見渡せる。",
    tags: ["夜景", "ショッピング", "カップル", "港町", "写真映え"],
    stayDuration: 120, bestTime: "夕方〜夜 17:00以降", crowdLevel: "medium",
    budget: "無料（施設利用は別途）", access: "JR神戸駅から徒歩10分 / 地下鉄海岸線 ハーバーランド駅から徒歩すぐ", rainyDay: true,
    highlights: ["ポートタワーの夜景", "煉瓦倉庫街", "umieモザイクの観覧車"],
    features: [
      { label: "夜景スポット", text: "メリケンパーク側から見るポートタワーと水面の反射。神戸夜景の代名詞。" },
      { label: "煉瓦倉庫", text: "明治時代の倉庫をリノベーションした商業施設。レンガの質感が良い。" },
      { label: "観覧車", text: "umieモザイクの観覧車から見る六甲山と大阪湾の眺め。カップル向き。" },
    ],
    nearby: ["arima-onsen", "akashi-bridge"],
    relatedArticles: ["hyogo-kobe-night-view", "hyogo-harbor-lunch-walk", "hyogo-kobe-couple-date"],
  },
  {
    id: "arima-onsen", title: "有馬温泉", location: "神戸市北区",
    prefecture: "兵庫県", prefectureId: "hyogo", area: "神戸", areaId: "kobe",
    category: "onsen",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/170811_Rokko-Arima_Ropeway_Kobe_Japan00n.jpg/1280px-170811_Rokko-Arima_Ropeway_Kobe_Japan00n.jpg"],
    description: "金泉と銀泉。日本最古の温泉地が、神戸から30分にある。",
    longDescription: "有馬温泉は日本三名泉のひとつで、奈良時代の文献にも記録される歴史を持つ。特徴は2種類の泉質。鉄分を含む赤褐色の「金泉」と、炭酸・放射能を含む無色の「銀泉」があり、金泉は特に珍しい。公衆浴場「金の湯」と「銀の湯」は日帰り入浴が可能で、金の湯は茶色い湯船に浸かる体験が他では味わえない。温泉街は坂道の路地が多く、炭酸せんべいの店や土産物屋が並ぶ。神戸市街から有馬温泉への直通バスがあり、大阪・京都からも日帰りで行ける距離感が強みだ。",
    tags: ["温泉", "歴史", "日帰り", "カップル", "ひとり旅"],
    stayDuration: 180, bestTime: "平日午前中（混雑回避）", crowdLevel: "medium",
    budget: "¥650〜（金の湯入浴料）", access: "神戸電鉄 有馬温泉駅から徒歩すぐ / 大阪・京都から直通バスあり", rainyDay: true,
    highlights: ["金の湯（金泉）", "銀の湯（銀泉）", "温泉街の坂道"],
    features: [
      { label: "金泉", text: "鉄分で赤く染まった湯。肌に付くとぬるっとした感触。これが有馬の本体。" },
      { label: "銀泉", text: "透明だが炭酸・ラジウムを含む。金泉と交互に入るのが通の楽しみ方。" },
      { label: "炭酸せんべい", text: "有馬名物の薄焼きせんべい。炭酸泉を使った製法は江戸時代から変わらない。" },
    ],
    nearby: ["kobe-harborland", "akashi-bridge"],
    relatedArticles: ["hyogo-arima-onsen-guide", "hyogo-luxury-arima-ryokan", "hyogo-arima-day-trip"],
  },
  {
    id: "akashi-bridge", title: "明石海峡大橋", location: "神戸市垂水区",
    prefecture: "兵庫県", prefectureId: "hyogo", area: "神戸", areaId: "kobe",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Akashi_Bridge.JPG/1280px-Akashi_Bridge.JPG"],
    description: "世界最長の吊り橋が、大阪湾と淡路島を繋いでいる。",
    longDescription: "明石海峡大橋は全長3,911m、中央支間1,991mで世界最長の吊り橋。1998年の開通以来、本州と淡路島を繋ぐ交通の要衝になった。橋のたもとにある「明石海峡公園」から全景を眺めるのがベスト。夕日が橋の背後に沈む時間帯は、シルエットが際立って特に美しい。「舞子海上プロムナード」では海面から47mの高さで橋の下を歩けるガラス床のスペースがある。明石は「明石鯛」と「明石蛸」の産地でもあり、橋の周辺で昼食を済ませてから橋見学というルートが定番だ。",
    tags: ["展望", "橋", "ドライブ", "写真映え", "夕日"],
    stayDuration: 60, bestTime: "夕方（日没前後）", crowdLevel: "low",
    budget: "無料（舞子海上プロムナードは¥250）", access: "JR舞子駅から徒歩すぐ / 山陽電鉄 舞子公園駅から徒歩すぐ", rainyDay: false,
    highlights: ["橋全景の展望", "舞子海上プロムナード", "夕日シルエット"],
    features: [
      { label: "舞子公園からの全景", text: "橋のたもとから見る全景が一番壮観。望遠レンズがあれば淡路島側のアンカレイジまで写せる。" },
      { label: "舞子海上プロムナード", text: "橋の下をガラス床の回廊で歩ける。高さ47mの海の上に立つ感覚。" },
    ],
    nearby: ["kobe-harborland", "arima-onsen"],
    relatedArticles: ["hyogo-akashi-bridge-view", "hyogo-awaji-island-drive", "hyogo-kobe-access-guide"],
  },
  {
    id: "koyasan", title: "高野山", location: "伊都郡高野町",
    prefecture: "和歌山県", prefectureId: "wakayama", area: "高野山", areaId: "kumano-area",
    category: "temple",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Okunoin_Cemetery%2C_Koyasan%2C_Japan.JPG/1280px-Okunoin_Cemetery%2C_Koyasan%2C_Japan.JPG"],
    description: "20万基の墓石が並ぶ森の奥に、空海は今も生きているとされる。",
    longDescription: "高野山は816年に空海（弘法大師）が開いた真言密教の聖地。標高約900mの山上に117の寺院が集まる宗教都市だ。奥之院の参道は杉木立の中に武将や大名の墓碑が並び、織田信長、豊臣秀吉、武田信玄など歴史上の人物が眠る。参道の突き当たりには弘法大師が入定した「御廟」がある。空海はここで今も瞑想を続けていると信じられている。宿坊に泊まって朝の勤行（朝のお勤め）に参加するのが高野山体験の本質。精進料理を食べ、朝の静寂の中で読経を聴く体験は、都市の旅行では得られない時間だ。",
    tags: ["寺院", "世界遺産", "スピリチュアル", "宿坊", "歴史"],
    stayDuration: 480, bestTime: "早朝（勤行参加）", crowdLevel: "low",
    budget: "¥10,000〜（宿坊1泊）", access: "南海高野線 極楽橋駅からロープウェイ15分 / 大阪難波から特急で約1時間20分", rainyDay: true,
    highlights: ["奥之院の参道", "御廟（弘法大師廟）", "宿坊での朝の勤行"],
    features: [
      { label: "奥之院", text: "約2kmの杉並木の参道に20万基以上の墓碑。夜に歩くと別世界になる。" },
      { label: "宿坊", text: "寺院に泊まる体験。朝の勤行、精進料理、写経。日常から完全に切り離される。" },
      { label: "金剛峯寺", text: "高野山の総本山。石庭「蟠龍庭」は日本最大級の石庭。" },
    ],
    nearby: ["nachi-falls", "kumano-kodo"],
    relatedArticles: ["wakayama-koyasan-shukubo-stay", "wakayama-koyasan-couple-retreat", "wakayama-koya-pilgrimage-guide"],
  },
  {
    id: "nachi-falls", title: "那智の滝", location: "東牟婁郡那智勝浦町",
    prefecture: "和歌山県", prefectureId: "wakayama", area: "熊野", areaId: "kumano-area",
    category: "viewpoint",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Nachikatsuura_Nachi_Falls_03.jpg/1280px-Nachikatsuura_Nachi_Falls_03.jpg"],
    description: "落差133m、日本一の直瀑。熊野の神が降りてくる場所。",
    longDescription: "那智の滝は落差133m、流量毎秒1トン。一段の滝として日本最大の落差を誇る。古来から「大滝」として信仰を集め、滝そのものが飛瀧神社の御神体とされている。参拝は本殿ではなく「滝の前」で行う。那智大社の本殿と三重塔を背景に滝が映る構図は、熊野を代表する絶景だ。世界遺産「紀伊山地の霊場と参詣道」の一部で、熊野古道を歩いた先にこの滝がある。雨の後は水量が増して迫力が増す。那智勝浦はマグロの漁港でもあり、港の食堂で食べるマグロ丼は移動の疲れを吹き飛ばす。",
    tags: ["滝", "世界遺産", "パワースポット", "神社", "熊野古道"],
    stayDuration: 120, bestTime: "午前中（光が滝に当たる）", crowdLevel: "medium",
    budget: "無料（飛瀧神社は¥300）", access: "JR紀伊勝浦駅からバスで30分", rainyDay: false,
    highlights: ["落差133mの直瀑", "那智大社と三重塔の構図", "熊野古道との接続"],
    features: [
      { label: "滝の前からの拝観", text: "御神体の滝に直接対面する形で参拝する。飛沫が顔にかかる距離感。" },
      { label: "那智大社三重塔", text: "朱塗りの三重塔と滝が重なる構図は那智の定番。展望台から狙う。" },
    ],
    nearby: ["kumano-kodo", "koyasan"],
    relatedArticles: ["wakayama-nachi-falls-pilgrimage", "wakayama-nachi-fire-festival", "wakayama-kumano-hongu-taisha"],
  },
  {
    id: "adventure-world", title: "アドベンチャーワールド", location: "西牟婁郡白浜町",
    prefecture: "和歌山県", prefectureId: "wakayama", area: "白浜", areaId: "shirahama-area",
    category: "experience",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Panda_Adventure_World_Shirahama.JPG/1280px-Panda_Adventure_World_Shirahama.JPG"],
    description: "日本一パンダが多い場所。白浜でパンダに会いに行く。",
    longDescription: "アドベンチャーワールドは中国の外にある動物園として世界最多のジャイアントパンダを飼育している施設。現在7頭以上のパンダが暮らしており、赤ちゃんパンダが生まれるたびに全国ニュースになる。パンダだけでなく、海に面したマリンワールドでは水族館とイルカショーも楽しめる。サファリパートは乗り物に乗ったまま動物を見るスタイルで、一日では回り切れないほどのボリュームがある。南紀白浜への家族旅行のハイライトとして、子どもから大人まで楽しめる。",
    tags: ["パンダ", "動物園", "家族", "テーマパーク", "子ども"],
    stayDuration: 360, bestTime: "平日開園直後", crowdLevel: "high",
    budget: "¥4,800（大人1日券）", access: "JR白浜駅からバス15分", rainyDay: true,
    highlights: ["ジャイアントパンダ", "サファリパーク", "マリンワールド"],
    features: [
      { label: "パンダ舎", text: "世界最多のジャイアントパンダを飼育。赤ちゃんパンダがいる時期は特に混雑する。" },
      { label: "サファリ", text: "乗り物に乗ったままライオンやキリンと間近で対面できる。子供の目が変わる瞬間。" },
      { label: "イルカショー", text: "海をバックにしたショーは他の水族館と景色が違う。野外席が気持ちいい。" },
    ],
    nearby: ["nanki-shirahama"],
    relatedArticles: ["wakayama-adventure-world-pandas", "wakayama-family-beach-vacation", "wakayama-shirahama-beach-summer"],
  },
  {
    id: "hikone-castle", title: "彦根城", location: "彦根市",
    prefecture: "滋賀県", prefectureId: "shiga", area: "彦根", areaId: "otsu",
    category: "castle",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Hikone_castle5537.JPG/1280px-Hikone_castle5537.JPG"],
    description: "現存12天守のひとつ。江戸時代の姿が琵琶湖畔に残っている。",
    longDescription: "彦根城は1622年築城の現存12天守のひとつで、国宝に指定されている。姫路城と並ぶ格式を持ちながら観光客が少なく、落ち着いて見学できる。天守閣は急勾配の石段と階段が続き、最上階から琵琶湖と近江の山並みが一望できる。桜の季節は三の丸から見る天守閣が特に美しく、内堀の周囲は花見の名所になる。ゆるキャラ「ひこにゃん」は彦根城のPRキャラクターで、毎日3回城内に登場する。国宝の玄宮園は大名庭園として完成度が高く、天守閣と池を同じ構図に収める写真が撮れる。",
    tags: ["城", "国宝", "琵琶湖", "桜", "歴史"],
    stayDuration: 120, bestTime: "午前中（光が天守に当たる）", crowdLevel: "medium",
    budget: "¥800", access: "JR琵琶湖線 彦根駅から徒歩15分", rainyDay: false,
    highlights: ["国宝天守閣", "琵琶湖の眺望", "玄宮園"],
    features: [
      { label: "天守閣", text: "400年前の木造建築がそのまま残る国宝。最上階から琵琶湖が見える。" },
      { label: "玄宮園", text: "大名庭園。池越しに天守閣を映す構図が絵になる。紅葉も見応えがある。" },
      { label: "ひこにゃん", text: "白猫の武将姿のキャラクター。1日3回の登場は彦根城の名物。" },
    ],
    nearby: ["shirahige-shrine"],
    relatedArticles: ["shiga-hikone-castle-deep-dive", "shiga-sakura-spots-spring", "shiga-omi-merchant-culture"],
  },
  {
    id: "shirahige-shrine", title: "白鬚神社", location: "高島市",
    prefecture: "滋賀県", prefectureId: "shiga", area: "高島", areaId: "otsu",
    category: "shrine",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Shirahige_Shrine_20200919_03.jpg/1280px-Shirahige_Shrine_20200919_03.jpg"],
    description: "琵琶湖の水面に立つ鳥居。「近江の厳島」と呼ばれる湖上の神社。",
    longDescription: "白鬚神社は垂仁天皇の時代（約2000年前）に創建されたとされる全国白鬚神社の総本社。境内の湖中鳥居は琵琶湖の水面に立っており、その姿が広島の厳島神社に見立てて「近江の厳島」と呼ばれる。早朝の湖面が静かな時間帯、朝靄の中に鳥居が浮かぶ景色は幻想的で、写真家や旅行者が遠方から訪れる。秋分・春分の時期は鳥居の真ん中から日が昇る「日の出の鳥居」が撮影できる特別な時期で、SNSで話題になる。国道沿いの鳥居へのアクセスは道路を横断するため要注意。",
    tags: ["神社", "鳥居", "琵琶湖", "絶景", "写真映え", "パワースポット"],
    stayDuration: 60, bestTime: "早朝（日の出前後）", crowdLevel: "low",
    budget: "無料", access: "JR湖西線 近江高島駅から徒歩20分 / タクシー5分", rainyDay: false,
    highlights: ["湖中鳥居", "朝霧の水面", "春秋分の日の出鳥居"],
    features: [
      { label: "湖中鳥居", text: "琵琶湖の中に立つ朱の鳥居。水位によって見え方が変わる。" },
      { label: "日の出の鳥居", text: "春分・秋分の前後、鳥居の真ん中から太陽が昇る。この構図を撮りに早朝から人が集まる。" },
    ],
    nearby: ["hikone-castle"],
    relatedArticles: ["shiga-shirahige-shrine-floating-torii", "shiga-takashima-satoyama-walk", "shiga-biwako-cycling-full-course"],
  },
  {
    id: "ise-jingu", title: "伊勢神宮", location: "伊勢市",
    prefecture: "三重県", prefectureId: "mie", area: "伊勢", areaId: "ise",
    category: "shrine",
    images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Ise_Grand_Shrine%2C_Mie_Prefecture%3B_November_2016_%2801%29.jpg/1280px-Ise_Grand_Shrine%2C_Mie_Prefecture%3B_November_2016_%2801%29.jpg"],
    description: "日本の神社の頂点。一生に一度はお伊勢参り、という言葉の重さ。",
    longDescription: "伊勢神宮は天照大御神を祀る内宮（皇大神宮）と豊受大御神を祀る外宮（豊受大神宮）を中心に125社からなる神社の総称。正式参拝は外宮から内宮の順に行う。内宮の宇治橋を渡った瞬間から空気が変わると感じる人が多い。本殿は式年遷宮で20年ごとに建て替えられ、2033年が次の遷宮。参道の砂利を踏む音、木漏れ日の中を歩く五十鈴川沿いの参道——ここに来るためだけに長距離を移動してきた全員が、来てよかったと思う場所だ。おかげ横丁で伊勢うどん、赤福を食べて帰るのが正式ルート。",
    tags: ["神社", "パワースポット", "歴史", "日本文化", "定番"],
    stayDuration: 180, bestTime: "早朝（開門直後）", crowdLevel: "high",
    budget: "無料", access: "近鉄山田線 伊勢市駅から徒歩10分（外宮）/ バスで内宮", rainyDay: false,
    highlights: ["内宮・正宮", "宇治橋", "おかげ横丁"],
    features: [
      { label: "内宮の正宮", text: "日本最高位の神社。写真撮影は外玉垣南御門まで。それより先は目に焼き付ける。" },
      { label: "五十鈴川の御手洗場", text: "清流で手を清める。川の石の踏み心地と水の冷たさが境内の始まりを告げる。" },
      { label: "おかげ横丁", text: "赤福本店と伊勢うどん。参拝後に腹を満たす。江戸時代の街並み再現。" },
    ],
    nearby: ["nabana-no-sato"],
    relatedArticles: ["mie-ise-jingu-complete-guide", "mie-solo-pilgrimage-ise", "mie-ise-morning-visit-strategy"],
  },
  {
    id: "nabana-no-sato", title: "なばなの里", location: "桑名市",
    prefecture: "三重県", prefectureId: "mie", area: "桑名", areaId: "ise",
    category: "garden",
    images: ["https://upload.wikimedia.org/wikipedia/commons/7/7c/Illumination_of_Nabana_no_sato_2010.JPG"],
    description: "日本最大級のイルミネーション。光のトンネルが冬の夜に現れる。",
    longDescription: "なばなの里は長島温泉リゾートの一部にある植物園兼テーマパーク。春から秋は花々が咲き乱れ、特にチューリップと桜の季節は圧巻だが、最大の目玉は冬のイルミネーションだ。300万球を超えるLEDを使ったイルミネーションは毎年テーマが変わり、10月から翌春まで開催される。「光のトンネル」と呼ばれる幅10m・長さ200mのイルミネーション回廊は、歩いているだけで別世界に迷い込んだ感覚になる。名古屋・大阪どちらからも1時間圏内にある立地で、年間180万人以上が訪れる三重最大の観光施設のひとつ。",
    tags: ["イルミネーション", "花", "冬", "夜景", "テーマパーク", "カップル"],
    stayDuration: 180, bestTime: "冬の夜（イルミネーション点灯後）", crowdLevel: "high",
    budget: "¥2,300（入場料）", access: "近鉄長島駅からシャトルバス15分 / 桑名ICから車で5分", rainyDay: true,
    highlights: ["光のトンネル", "冬のイルミネーション", "季節の花畑"],
    features: [
      { label: "光のトンネル", text: "200mのLEDアーチを歩く。毎年デザインが変わるため何度来ても新鮮。" },
      { label: "大噴水ショー", text: "イルミネーションに合わせた噴水と音楽の演出。夜の締めにちょうどいい。" },
      { label: "春の花畑", text: "チューリップ・梅・桜・菜の花。冬以外の季節も花で埋め尽くされる。" },
    ],
    nearby: ["ise-jingu"],
    relatedArticles: ["mie-nabana-no-sato-illumination", "mie-couple-resort-plan", "mie-seasonal-cherry-blossom"],
  },
];
