import { Spot } from "@/types/spot";

export const kinkiSpots: Spot[] = [
  {
    id: "fushimi-inari", title: "伏見稲荷大社", location: "京都市伏見区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80", "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80"],
    description: "千本鳥居の朱が、視界を埋め尽くす。",
    longDescription: "観光客が殺到する午前10時を避けて、早朝6時に来い。誰もいない千本鳥居を独り占めできる。奥社から先の四ツ辻までは約40分の山道。ここまで来る人は少ない。振り返ると京都の街が一望できる。頂上まで行く必要はない。四ツ辻のベンチに座って、汗が引くのを待つ。それだけで十分に「来た」と思える場所。",
    tags: ["神社", "早朝", "写真映え", "一人旅", "定番"],
    stayDuration: 90, bestTime: "早朝 6:00〜7:30", crowdLevel: "high",
    budget: "無料", access: "JR奈良線 稲荷駅から徒歩すぐ", rainyDay: false,
    highlights: ["千本鳥居", "四ツ辻の展望", "奥社奉拝所"],
    features: [
      { label: "千本鳥居", text: "朱の鳥居が延々と続くトンネル。写真を撮るなら早朝一択。" },
      { label: "四ツ辻", text: "稲荷山の中腹。京都市街を見下ろすビューポイント。" },
      { label: "参道の茶屋", text: "登山途中にある茶屋でいなり寿司を食べる。これが正解。" },
    ],
    nearby: ["kiyomizu", "gion"], relatedArticles: ["kyoto-morning-route"],
  },
  {
    id: "kiyomizu", title: "清水寺", location: "京都市東山区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "temple",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "崖の上に浮かぶ舞台。京都で一番、空に近い場所。",
    longDescription: "清水の舞台から飛び降りる、という言葉がある。実際に立つとわかる。この高さは冗談じゃない。紅葉シーズンの夜間拝観は、舞台の下から見上げるのがいい。ライトアップされた本堂が闇に浮かぶ。音羽の滝は3つの筋があって、それぞれ学業・恋愛・長寿。全部飲むのは欲張りらしい。",
    tags: ["寺院", "紅葉", "夜景", "定番", "写真映え"],
    stayDuration: 60, bestTime: "朝 6:00（開門直後）", crowdLevel: "high",
    budget: "¥400", access: "京阪 清水五条駅から徒歩25分", rainyDay: false,
    highlights: ["清水の舞台", "音羽の滝", "三年坂・二年坂"],
    features: [
      { label: "舞台からの眺望", text: "13mの高さから京都盆地を一望。秋は紅葉の海になる。" },
      { label: "三年坂の石畳", text: "清水寺への参道。転ぶと三年で死ぬという迷信がある。" },
    ],
    nearby: ["fushimi-inari", "gion"], relatedArticles: ["kyoto-morning-route"],
  },
  {
    id: "gion", title: "祇園・花見小路", location: "京都市東山区",
    prefecture: "京都府", prefectureId: "kyoto", area: "京都", areaId: "kyoto-city",
    category: "street",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "石畳と格子戸。夕暮れの一瞬だけ、舞妓に会える。",
    longDescription: "花見小路は昼と夜で全く違う場所になる。昼は観光客が多いが、日が暮れると急に静かになる。18時過ぎに歩くと、お座敷に向かう舞妓さんとすれ違うことがある。写真を撮るのは禁止。見るだけ。白川沿いの柳が風に揺れる景色は、京都で最も美しい一瞬のひとつ。",
    tags: ["街歩き", "夕暮れ", "伝統", "カップル"],
    stayDuration: 60, bestTime: "夕方 17:00〜19:00", crowdLevel: "medium",
    budget: "無料", access: "京阪 祇園四条駅から徒歩5分", rainyDay: false,
    highlights: ["花見小路", "白川沿い", "建仁寺"],
    features: [
      { label: "夕暮れの花見小路", text: "観光客が引いた後、格子戸に灯りが入る。この時間が本番。" },
      { label: "白川沿いの散歩", text: "柳と石橋。祇園の喧騒から一本入るだけで静けさがある。" },
    ],
    nearby: ["kiyomizu", "fushimi-inari"], relatedArticles: ["kyoto-morning-route"],
  },
  {
    id: "arashiyama", title: "嵐山・竹林の小径", location: "京都市右京区",
    prefecture: "京都府", prefectureId: "kyoto", area: "嵐山", areaId: "arashiyama-area",
    category: "park",
    images: ["https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80"],
    description: "竹の音だけが聞こえる。嵐山の奥に、別世界がある。",
    longDescription: "竹林の小径は朝7時前なら人がいない。天龍寺の裏手から入って、風が竹を揺らす音だけを聴く。嵯峨野トロッコ列車は片道だけ乗るのが正解。行きはトロッコ、帰りは保津川下り。渡月橋は夕方が美しい。山の稜線が夕日で赤く染まる。",
    tags: ["自然", "早朝", "写真映え", "カップル"],
    stayDuration: 120, bestTime: "早朝 7:00前", crowdLevel: "high",
    budget: "無料", access: "JR嵯峨嵐山駅から徒歩10分", rainyDay: false,
    highlights: ["竹林の小径", "渡月橋", "天龍寺"],
    features: [
      { label: "竹林", text: "見上げると空が竹で区切られている。風の音が唯一のBGM。" },
      { label: "渡月橋の夕景", text: "嵐山のシルエットが夕日に染まる。橋の上で立ち止まるべき瞬間。" },
    ],
    nearby: ["gion", "kiyomizu"],
  },
  {
    id: "nara-park", title: "奈良公園", location: "奈良市",
    prefecture: "奈良県", prefectureId: "nara", area: "奈良", areaId: "nara-city",
    category: "park",
    images: ["https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80"],
    description: "鹿と大仏と芝生。1300年前から変わらない、のんびりした時間。",
    longDescription: "奈良公園の鹿は「野生動物」であって、ペットではない。鹿せんべいを持っていると囲まれるが、それも含めて体験。東大寺の大仏殿に入ると、想像の3倍デカい。柱の穴くぐりは子供向けに見えるが、大人がやると盛り上がる。春日大社の参道は木漏れ日が美しい。午後の遅い時間に歩くのがいい。",
    tags: ["自然", "歴史", "家族", "のんびり"],
    stayDuration: 180, bestTime: "午前中", crowdLevel: "medium",
    budget: "無料", access: "近鉄奈良駅から徒歩5分", rainyDay: false,
    highlights: ["鹿", "東大寺大仏殿", "春日大社", "若草山"],
    features: [
      { label: "鹿とのふれあい", text: "鹿せんべいは150円。お辞儀する鹿がいる。しない鹿もいる。" },
      { label: "東大寺", text: "世界最大級の木造建築。中に入ると音が消える感覚がある。" },
      { label: "春日大社の参道", text: "石灯籠が並ぶ参道。午後の木漏れ日が一番きれい。" },
    ],
    nearby: ["yoshino"],
  },
  {
    id: "dotonbori", title: "道頓堀", location: "大阪市中央区",
    prefecture: "大阪府", prefectureId: "osaka", area: "大阪", areaId: "minami",
    category: "street",
    images: ["https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80"],
    description: "ネオンと串カツと人混み。大阪の胃袋は、ここにある。",
    longDescription: "道頓堀は「観光地」として消費するより「食べ歩き」として体験するのが正解。たこ焼きはわなか、串カツはだるま、お好み焼きは美津の。この3つを回るだけで満足度が高い。グリコの看板の前で写真を撮るのは全員やるけど、橋の上からの夜景の方が絵になる。法善寺横丁は道頓堀から一歩入るだけで、全く違う空気になる。",
    tags: ["グルメ", "夜", "にぎやか", "食べ歩き", "定番"],
    stayDuration: 120, bestTime: "夜 18:00以降", crowdLevel: "high",
    budget: "¥2,000〜", access: "地下鉄 なんば駅から徒歩5分", rainyDay: true,
    highlights: ["グリコ看板", "法善寺横丁", "たこ焼き巡り"],
    features: [
      { label: "食べ歩き", text: "たこ焼き→串カツ→お好み焼き。この順番で回ると胃がもつ。" },
      { label: "法善寺横丁", text: "道頓堀の喧騒から一歩入った石畳の路地。水かけ不動が鎮座する。" },
    ],
    nearby: ["shinsekai"], relatedArticles: ["osaka-kuiadaore"],
  },
  {
    id: "shinsekai", title: "新世界", location: "大阪市浪速区",
    prefecture: "大阪府", prefectureId: "osaka", area: "大阪", areaId: "shinsekai-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1589452271712-64b8a66c3929?w=1200&q=80"],
    description: "通天閣の足元で、串カツを揚げる音が響く。",
    longDescription: "新世界は「レトロ」とか「ディープ」とか言われるけど、地元の人は普通にここで酒を飲んでいる。ジャンジャン横丁の串カツ屋は朝から開いている店がある。通天閣に登るかどうかは自由。登らなくても、下から見上げるだけで十分に「新世界に来た」感がある。",
    tags: ["グルメ", "レトロ", "一人旅", "ディープ"],
    stayDuration: 90, bestTime: "昼〜夕方", crowdLevel: "medium",
    budget: "¥1,500〜", access: "地下鉄 動物園前駅から徒歩3分", rainyDay: true,
    highlights: ["通天閣", "ジャンジャン横丁", "串カツ"],
    features: [
      { label: "ジャンジャン横丁", text: "串カツ屋が密集するアーケード。ソースの二度漬けは禁止。" },
      { label: "通天閣", text: "展望台よりも、足元の商店街の方が面白い。" },
    ],
    nearby: ["dotonbori"], relatedArticles: ["osaka-kuiadaore"],
  },
  {
    id: "kinosaki", title: "城崎温泉", location: "豊岡市城崎町",
    prefecture: "兵庫県", prefectureId: "hyogo", area: "城崎", areaId: "kinosaki-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80"],
    description: "浴衣で歩く、7つの湯。温泉街の「正解」がここにある。",
    longDescription: "城崎温泉は「外湯めぐり」が本体。宿の内湯に入るより、浴衣とゲタで7つの外湯をハシゴするのがここの流儀。泉質が全部違うから、お気に入りを見つけるのが楽しい。柳並木の夜景は風情がある。冬のカニは松葉ガニ。カニ刺し、焼きガニ、カニすき、カニ雑炊のフルコースは一生に一度は食べるべき。",
    tags: ["温泉", "浴衣", "カップル", "冬", "グルメ"],
    stayDuration: 360, bestTime: "夕方〜夜", crowdLevel: "medium",
    budget: "¥15,000〜（1泊）", access: "大阪から特急こうのとりで約2時間40分", rainyDay: true,
    highlights: ["外湯めぐり", "柳並木", "冬の松葉ガニ"],
    features: [
      { label: "外湯7湯", text: "1日券でハシゴ放題。御所の湯が一番人気。" },
      { label: "柳並木の夕景", text: "大谿川沿いの柳が風に揺れる。温泉街で最も美しい瞬間。" },
      { label: "松葉ガニ", text: "11月〜3月限定。この時期に来る理由がこれ。" },
    ],
    nearby: [], relatedArticles: ["kinosaki-complete"],
  },
  {
    id: "yoshino", title: "吉野山", location: "吉野郡吉野町",
    prefecture: "奈良県", prefectureId: "nara", area: "吉野", areaId: "yoshino-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80"],
    description: "3万本の桜が、山を下から上へ染めていく。",
    longDescription: "吉野の桜は「一目千本」と言われる。下千本→中千本→上千本→奥千本と、標高に沿って順に咲くから、時期をずらせば1ヶ月近く桜を楽しめる。金峯山寺の蔵王堂は桜の時期だけ特別拝観がある。秘仏の蔵王権現は青い肌をしていて、想像と全く違う。",
    tags: ["桜", "自然", "寺院", "春"],
    stayDuration: 240, bestTime: "4月上旬〜中旬", crowdLevel: "high",
    budget: "無料", access: "近鉄 吉野駅からロープウェイ", rainyDay: false,
    highlights: ["一目千本", "金峯山寺", "奥千本"],
    features: [
      { label: "一目千本", text: "中千本から見下ろす桜の海。写真では伝わらないスケール。" },
      { label: "金峯山寺", text: "蔵王権現の秘仏は春と秋だけ。青い肌の巨大仏に圧倒される。" },
    ],
    nearby: ["nara-park"],
  },
  {
    id: "nanki-shirahama", title: "南紀白浜", location: "西牟婁郡白浜町",
    prefecture: "和歌山県", prefectureId: "wakayama", area: "白浜", areaId: "shirahama-area",
    category: "beach",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "白い砂浜と青い海。関西から一番近い「南国」。",
    longDescription: "白良浜の砂は元々白い石英砂。海の透明度は沖縄に匹敵する。円月島は夕日が岩の穴を通り抜ける瞬間を狙う。三段壁の洞窟は波が荒い日の方が迫力がある。とれとれ市場で海鮮丼を食べて、崎の湯で太平洋を見ながら入浴する。これが白浜の黄金ルート。",
    tags: ["ビーチ", "温泉", "家族", "夏"],
    stayDuration: 360, bestTime: "夏（7〜8月）", crowdLevel: "high",
    budget: "¥10,000〜", access: "大阪から特急くろしおで約2時間半", rainyDay: false,
    highlights: ["白良浜", "円月島", "三段壁", "崎の湯"],
    features: [
      { label: "白良浜", text: "真っ白な砂浜。海の色が本当にエメラルドグリーン。" },
      { label: "崎の湯", text: "太平洋に面した露天風呂。波しぶきが飛んでくる距離感。" },
      { label: "円月島の夕日", text: "岩の穴を夕日が通り抜ける瞬間。年に2回、完全に通過する。" },
    ],
    nearby: ["kumano-kodo"],
  },
  {
    id: "himeji", title: "姫路城", location: "姫路市",
    prefecture: "兵庫県", prefectureId: "hyogo", area: "姫路", areaId: "himeji-area",
    category: "castle",
    images: ["https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80"],
    description: "白すぎて、空に溶ける。日本で最も美しい城。",
    longDescription: "姫路城は「白鷺城」の名の通り、白い。改修後は特に白い。快晴の日に行くと、白い城と青い空の境界が曖昧になる。天守閣まで登ると、急な階段に足がすくむ。でも最上階から見る姫路の街は、登った甲斐がある。西の丸から見る天守閣の構図が一番美しい。桜の時期は三の丸広場が花見客で埋まる。",
    tags: ["城", "歴史", "写真映え", "一人旅"],
    stayDuration: 120, bestTime: "午前中", crowdLevel: "medium",
    budget: "¥1,000", access: "JR姫路駅から徒歩15分", rainyDay: false,
    highlights: ["天守閣", "西の丸", "好古園"],
    features: [
      { label: "天守閣", text: "6階建て。最上階まで登ると姫路市街が一望できる。" },
      { label: "西の丸からの構図", text: "天守閣を最も美しく撮れるポイント。午前の光が正解。" },
    ],
    nearby: [],
  },
  {
    id: "kumano-kodo", title: "熊野古道", location: "田辺市・新宮市",
    prefecture: "和歌山県", prefectureId: "wakayama", area: "熊野", areaId: "kumano-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80"],
    description: "石畳を踏む足音だけが響く。1000年前の道を歩く。",
    longDescription: "熊野古道は世界遺産の巡礼路。中辺路の滝尻王子から熊野本宮大社までが最もポピュラーなルート。全部歩くと2〜3日かかるが、発心門王子から本宮大社までなら約3時間で歩ける。石畳の道を歩いていると、木漏れ日と苔と湿った空気が混ざった匂いがする。大斎原の大鳥居は日本一の大きさ。田んぼの中にぽつんと立っている姿が、かえって神秘的。",
    tags: ["トレッキング", "歴史", "スピリチュアル", "一人旅"],
    stayDuration: 300, bestTime: "春・秋", crowdLevel: "low",
    budget: "無料", access: "紀伊田辺駅からバス", rainyDay: false,
    highlights: ["中辺路", "熊野本宮大社", "大斎原", "那智の滝"],
    features: [
      { label: "中辺路の石畳", text: "苔むした石段を踏む感触。1000年分の祈りが積もっている。" },
      { label: "大斎原", text: "日本一の大鳥居。田んぼの中に突然現れる巨大な朱の門。" },
    ],
    nearby: ["nanki-shirahama"],
  },
];
