import { Spot } from "@/types/spot";

export const kyushuSpots: Spot[] = [
  // ── 福岡 ──────────────────────────────────────
  {
    id: "dazaifu", title: "太宰府天満宮", location: "太宰府市宰府",
    prefecture: "福岡県", prefectureId: "fukuoka", area: "太宰府", areaId: "dazaifu-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "梅の香が漂う参道の先に、学問の神様が待つ。",
    longDescription: "太宰府天満宮は全国に約12,000社ある天満宮の総本社。菅原道真公を祀り、学問の神様として受験シーズンには全国から参拝者が押し寄せる。参道の梅ヶ枝餅は焼きたてが正解。境内の梅は2月上旬に満開になる。新本殿（仮殿）は藤本壮介設計の現代建築で、杉の木が内部に生えている異空間。宝物殿も見逃せない。早朝の参拝は人が少なく、飛梅伝説の木を独り占めできる。",
    tags: ["神社", "学問", "梅", "定番", "歴史"],
    stayDuration: 90, bestTime: "早朝 8:00前", crowdLevel: "high",
    budget: "無料", access: "西鉄太宰府線 太宰府駅から徒歩5分", rainyDay: false,
    highlights: ["飛梅", "梅ヶ枝餅", "新本殿"],
    features: [
      { label: "飛梅", text: "道真公を追いかけて都から飛んできたという伝説の梅。毎年2月に真っ先に咲く。" },
      { label: "梅ヶ枝餅", text: "参道沿いの茶屋が焼く名物。鉄板から出たばかりの熱さで食べること。" },
      { label: "心字池の橋", text: "三連の橋は過去・現在・未来を表す。渡るときに後ろを振り返ってはいけない。" },
    ],
    nearby: ["nakasu-yatai", "hakata-station"],
    mapUrl: "https://maps.google.com/?q=太宰府天満宮",
    officialUrl: "https://www.dazaifutenmangu.or.jp/",
  },
  {
    id: "nakasu-yatai", title: "中洲屋台", location: "福岡市博多区中洲",
    prefecture: "福岡県", prefectureId: "fukuoka", area: "福岡", areaId: "fukuoka-city",
    category: "restaurant",
    images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80"],
    description: "川沿いに並ぶ屋台の灯り。福岡の夜は、ここから始まる。",
    longDescription: "中洲の屋台は福岡の象徴。那珂川と博多川に挟まれた中洲に、夜になると屋台が一斉に開く。豚骨ラーメン、もつ鍋、焼き鳥、博多の名物が狭いカウンターに並ぶ。隣に座った見知らぬ人と話が弾むのが屋台の醍醐味。天神エリアにも屋台が多い。雨の日は閉まることもあるので確認必須。開店は18時過ぎ、23時ごろには閉まり始める。屋台ごとに個性があるので、はしごするのが正解。",
    tags: ["グルメ", "夜", "ラーメン", "博多", "定番"],
    stayDuration: 120, bestTime: "夜 19:00〜22:00", crowdLevel: "high",
    budget: "¥1,500〜¥3,000", access: "地下鉄中洲川端駅から徒歩5分", rainyDay: false,
    highlights: ["豚骨ラーメン", "もつ鍋", "川沿いの屋台風景"],
    features: [
      { label: "博多ラーメン", text: "細麺に白濁豚骨スープ。替え玉が文化。スープを飲み干すのがマナー。" },
      { label: "屋台はしご", text: "一軒目でラーメン、二軒目でおでん、三軒目で締めのラーメン。これが博多流。" },
    ],
    nearby: ["hakata-station", "dazaifu"],
  },
  {
    id: "hakata-station", title: "博多駅", location: "福岡市博多区博多駅中央街",
    prefecture: "福岡県", prefectureId: "fukuoka", area: "福岡", areaId: "fukuoka-city",
    category: "other",
    images: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80"],
    description: "九州の玄関口は、それ自体が福岡グルメの圧縮版。",
    longDescription: "博多駅は単なる交通拠点ではなく、福岡グルメが凝縮されたフードコートでもある。地下の「博多デイトス」には明太子、ラーメン、もつ鍋の名店が集まり、深夜まで営業している。駅ビル「アミュプラザ」の屋上からは博多の街並みが見渡せる。新幹線のホームから博多ラーメンを食べて次の目的地へ——そんな使い方も博多駅ならではの体験。博多川端商店街も徒歩圏内。",
    tags: ["交通", "グルメ", "お土産", "アクセス"],
    stayDuration: 60, bestTime: "昼食・夕食時", crowdLevel: "high",
    budget: "¥1,000〜", access: "JR博多駅", rainyDay: true,
    highlights: ["博多デイトス", "マイング", "屋上テラス"],
    features: [
      { label: "博多デイトス", text: "地下フードコート。明太子は福さ屋と味明太子を食べ比べること。" },
      { label: "お土産選び", text: "とおりもんとひよ子は定番。あまおう苺スイーツは時期限定で人気。" },
    ],
    nearby: ["nakasu-yatai", "dazaifu"],
  },
  {
    id: "itoshima", title: "糸島", location: "糸島市",
    prefecture: "福岡県", prefectureId: "fukuoka", area: "糸島", areaId: "itoshima-area",
    category: "beach",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "海と山と農村が混在する、福岡の奥座敷。",
    longDescription: "糸島は福岡市街から車で30分とは思えない自然の豊かさ。二見ヶ浦の夫婦岩は夕暮れが最高で、西向きに沈む太陽が岩と鳥居を赤く染める。週末になると福岡市内から若者が集まるが、平日の午前中は海岸に人がいない。カフェやジェラート店が農村の中に点在していて、ドライブしながら寄り道するのが糸島スタイル。牡蠣小屋は11月〜3月限定で浜辺に開く。炭火焼きの新鮮な牡蠣を食べながら海を見る。",
    tags: ["海", "カフェ", "ドライブ", "写真映え", "グルメ"],
    stayDuration: 240, bestTime: "夕暮れ（二見ヶ浦）・冬（牡蠣）", crowdLevel: "low",
    budget: "¥2,000〜", access: "JR筑肥線 筑前前原駅からレンタカー推奨", rainyDay: false,
    highlights: ["二見ヶ浦夫婦岩", "牡蠣小屋", "糸島のカフェ群"],
    features: [
      { label: "二見ヶ浦の夕日", text: "大注連縄を張った夫婦岩と落日。玄界灘に沈む太陽は格別。" },
      { label: "牡蠣小屋", text: "浜辺に設置された仮設小屋で、獲れたての牡蠣を炭火焼きにする。" },
    ],
    nearby: ["hakata-station"],
  },
  {
    id: "mojiko-retro", title: "門司港レトロ", location: "北九州市門司区港町",
    prefecture: "福岡県", prefectureId: "fukuoka", area: "北九州", areaId: "kitakyushu-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "明治・大正の洋館が、海沿いに並ぶ港町。",
    longDescription: "門司港は明治から昭和初期にかけて国際貿易港として栄えた。その遺産である洋館群が今も残り、「門司港レトロ地区」として整備されている。旧門司税関、旧大阪商船、門司港駅（重要文化財）は外観だけでも見応えがある。バナナのたたき売り発祥地の石碑がある。焼きカレーが名物で、10以上の店が競い合っている。夜のライトアップは格別で、建物が浮かび上がる。関門海峡を渡ると山口県・下関が目の前。",
    tags: ["レトロ", "洋館", "グルメ", "歴史", "港"],
    stayDuration: 150, bestTime: "夜（ライトアップ）", crowdLevel: "medium",
    budget: "¥2,000〜", access: "JR鹿児島本線 門司港駅すぐ", rainyDay: true,
    highlights: ["門司港駅", "旧門司税関", "焼きカレー"],
    features: [
      { label: "焼きカレー", text: "グラタン皿で焼いた門司港名物。上に乗る半熟卵を崩してから食べる。" },
      { label: "夜のライトアップ", text: "レンガ造りの建物が橙色の灯りに包まれる。昼と全く別の顔になる。" },
    ],
    nearby: ["hakata-station"],
    mapUrl: "https://maps.google.com/?q=門司港レトロ",
  },

  // ── 佐賀 ──────────────────────────────────────
  {
    id: "yoshinogari", title: "吉野ヶ里遺跡", location: "神埼郡吉野ヶ里町",
    prefecture: "佐賀県", prefectureId: "saga", area: "佐賀", areaId: "saga-area",
    category: "museum",
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80"],
    description: "弥生時代の都市が、そのまま地面の下に眠っていた。",
    longDescription: "吉野ヶ里遺跡は弥生時代の環濠集落跡としては国内最大級。1986年の発見当初から「邪馬台国ではないか」という議論を巻き起こした。国営公園として整備され、復元された竪穴住居や物見櫓を実際に歩いて体感できる。甕棺墓列では当時の埋葬方法が展示されている。敷地が広大なので、自転車レンタルが便利。春は桜、夏はひまわりが遺跡とのコントラストで美しい。",
    tags: ["歴史", "遺跡", "弥生時代", "体験"],
    stayDuration: 180, bestTime: "午前中（暑さを避けて）", crowdLevel: "low",
    budget: "¥460", access: "JR長崎本線 吉野ヶ里公園駅から徒歩15分", rainyDay: false,
    highlights: ["環濠集落跡", "復元竪穴住居", "甕棺墓列"],
    features: [
      { label: "復元建物", text: "弥生時代の集落を実寸大で復元。内部に入ると当時の生活感がリアルに伝わる。" },
      { label: "物見櫓", text: "集落全体を見渡せる高台。水田と遺跡が広がる景色は独特。" },
    ],
    nearby: ["arita-pottery", "ureshino-onsen"],
  },
  {
    id: "arita-pottery", title: "有田焼の里", location: "西松浦郡有田町",
    prefecture: "佐賀県", prefectureId: "saga", area: "有田", areaId: "arita-area",
    category: "shop",
    images: ["https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&q=80"],
    description: "日本磁器の原点が、この小さな町にある。",
    longDescription: "有田は日本で最初に磁器が焼かれた町。江戸時代から300年以上、世界に輸出された有田焼の生産地。陶山神社は鳥居も狛犬も磁器でできているという世界でも珍しい神社。泉山磁石場では磁器の原料となる陶石の採掘跡を見られる。毎年ゴールデンウイークに開催される「有田陶器市」は全国から陶芸ファンが集まる一大イベント。窯元を訪ねて作家と話しながら一品選ぶのが、有田の正しい楽しみ方。",
    tags: ["陶芸", "伝統", "ショッピング", "歴史"],
    stayDuration: 150, bestTime: "10:00〜16:00", crowdLevel: "low",
    budget: "¥3,000〜（購入費用）", access: "JR佐世保線 有田駅から徒歩・レンタサイクル", rainyDay: true,
    highlights: ["陶山神社", "窯元街", "有田陶器市（GW）"],
    features: [
      { label: "陶山神社", text: "磁器製の鳥居と狛犬。有田焼が生活に根ざしてきた証。" },
      { label: "窯元めぐり", text: "予約なしで入れる窯元も多い。作り手から直接買うと愛着が違う。" },
    ],
    nearby: ["yoshinogari", "ureshino-onsen"],
  },
  {
    id: "ureshino-onsen", title: "嬉野温泉", location: "嬉野市嬉野町",
    prefecture: "佐賀県", prefectureId: "saga", area: "嬉野", areaId: "ureshino-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80"],
    description: "日本三大美肌の湯。入れば肌がとろけるように柔らかくなる。",
    longDescription: "嬉野温泉は重曹泉で、日本三大美肌の湯のひとつ。泉質のpH値が高く、肌の角質を溶かす作用があるため「とろとろの湯」とも呼ばれる。嬉野茶の産地でもあり、温泉街の茶店で飲む地元茶は格別。名物の「温泉湯豆腐」はとろとろに溶けた豆腐を食べる佐賀独自の料理。シーボルトもここで療養したという記録が残る。公共の足湯が無料で利用でき、散策の途中で気軽に立ち寄れる。",
    tags: ["温泉", "美肌", "カップル", "宿泊"],
    stayDuration: 300, bestTime: "夕方〜夜（宿泊推奨）", crowdLevel: "medium",
    budget: "¥500〜（日帰り入浴）", access: "JR武雄温泉駅からバス約20分", rainyDay: true,
    highlights: ["美肌の湯", "温泉湯豆腐", "嬉野茶"],
    features: [
      { label: "とろとろの湯", text: "肌にぬるっとした感触がある重曹泉。入浴後は本当に肌がすべすべになる。" },
      { label: "温泉湯豆腐", text: "温泉水で煮ると豆腐がとろとろに溶ける。嬉野でしか食べられない料理。" },
    ],
    nearby: ["arita-pottery", "yoshinogari"],
  },

  // ── 長崎 ──────────────────────────────────────
  {
    id: "glover-garden", title: "グラバー園", location: "長崎市南山手町",
    prefecture: "長崎県", prefectureId: "nagasaki", area: "長崎", areaId: "nagasaki-city",
    category: "museum",
    images: ["https://images.unsplash.com/photo-1516655855035-d5215b0e14f5?w=1200&q=80"],
    description: "丘の上に立つ異人館から、長崎港が一望できる。",
    longDescription: "グラバー園は明治時代の外国人居留地跡。スコットランド出身の商人トーマス・グラバーが建てたグラバー住宅は、現存する日本最古の木造洋風建築のひとつ。敷地内の展望台からは長崎港と稲佐山が望める。大浦天主堂との組み合わせで「明治日本の産業革命遺産」の世界遺産関連施設。プッチーニのオペラ「蝶々夫人」のモデルになったという話もある。動く歩道で登って徒歩で降りると楽。石畳と洋館の組み合わせは長崎でしか見られない。",
    tags: ["歴史", "洋館", "世界遺産", "展望", "長崎"],
    stayDuration: 90, bestTime: "午前中（人が少ない）", crowdLevel: "medium",
    budget: "¥620", access: "路面電車 大浦天主堂駅から徒歩8分", rainyDay: false,
    highlights: ["グラバー住宅", "長崎港の展望", "大浦天主堂"],
    features: [
      { label: "グラバー住宅", text: "幕末から明治に活躍した商人の邸宅。幕府への武器販売も行っていた。" },
      { label: "ハート石探し", text: "園内の石畳に「ハート形」の石が3つ隠れている。見つけると恋愛成就とか。" },
    ],
    nearby: ["gunkan-jima", "heiwa-koen"],
    officialUrl: "https://www.glover-garden.jp/",
  },
  {
    id: "gunkan-jima", title: "軍艦島", location: "長崎市高島町端島",
    prefecture: "長崎県", prefectureId: "nagasaki", area: "長崎", areaId: "nagasaki-harbor",
    category: "other",
    images: ["https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=1200&q=80"],
    description: "廃墟と化した炭鉱の島。人が消えた後、海が静かに飲み込んでいく。",
    longDescription: "端島、通称「軍艦島」は日本初の高層鉄筋コンクリートアパートが建てられた炭鉱島。最盛期には東京の9倍の人口密度を誇り、5,000人が島内で完結した生活を送っていた。1974年の閉山後は無人島となり、廃墟となった建物群が今も残る。2009年に上陸ツアーが解禁され、世界遺産「明治日本の産業革命遺産」の構成資産にもなった。天候によって上陸できないことも多い。波が穏やかな春から秋が上陸チャンスが高い。",
    tags: ["廃墟", "世界遺産", "島", "歴史", "ツアー"],
    stayDuration: 210, bestTime: "天候の良い春〜秋", crowdLevel: "medium",
    budget: "¥4,500〜（ツアー代）", access: "長崎港から船で約40分（要ツアー予約）", rainyDay: false,
    highlights: ["廃墟の建物群", "世界遺産", "長崎港からの船旅"],
    features: [
      { label: "上陸ツアー", text: "2009年に解禁。指定エリアのみ歩ける。廃墟の迫力は現地でしか伝わらない。" },
      { label: "船上からの眺め", text: "上陸できない日でも、周回クルーズで全体像を見られる。" },
    ],
    nearby: ["glover-garden", "heiwa-koen"],
  },
  {
    id: "heiwa-koen", title: "平和公園", location: "長崎市松山町",
    prefecture: "長崎県", prefectureId: "nagasaki", area: "長崎", areaId: "nagasaki-city",
    category: "park",
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80"],
    description: "この場所に立って考える。平和という言葉の重さを。",
    longDescription: "長崎は1945年8月9日に原爆が投下された。爆心地公園と平和公園は隣接し、平和祈念像（北村西望作）が青空に向かって右手を高く上げている。原爆落下中心地の黒い柱の周囲には、世界各国から寄贈された平和のモニュメントが並ぶ。長崎原爆資料館では当時の長崎と被爆の記録を丁寧に展示。黙って見ていると、何かが変わる感覚がある。8月9日の「長崎原爆の日」は式典が行われ、全市が静まり返る。",
    tags: ["平和", "歴史", "原爆", "長崎"],
    stayDuration: 120, bestTime: "午前中（静かな時間帯）", crowdLevel: "medium",
    budget: "無料（資料館¥200）", access: "路面電車 松山町駅から徒歩3分", rainyDay: true,
    highlights: ["平和祈念像", "爆心地公園", "長崎原爆資料館"],
    features: [
      { label: "平和祈念像", text: "右手が原爆を指差し、左手が平和を示す。毎年8月9日にここで式典が行われる。" },
      { label: "長崎原爆資料館", text: "溶けた瓶、焼けた時計、被爆者の証言。静かに向き合うべき場所。" },
    ],
    nearby: ["glover-garden", "gunkan-jima"],
  },
  {
    id: "huis-ten-bosch", title: "ハウステンボス", location: "佐世保市ハウステンボス町",
    prefecture: "長崎県", prefectureId: "nagasaki", area: "佐世保", areaId: "sasebo-area",
    category: "other",
    images: ["https://images.unsplash.com/photo-1515037893149-de7f840978e2?w=1200&q=80"],
    description: "オランダの街並みが九州に再現された、テーマパークを超えた空間。",
    longDescription: "ハウステンボスは152万平方メートルという日本最大のテーマパーク。オランダの街並みを精巧に再現し、本物のレンガ建築が運河の沿いに並ぶ。チューリップ祭（春）とイルミネーション（冬）は年間のハイシーズン。夜のイルミネーションは日本最大規模で、光のアートにSNSで話題になるほど。アトラクションより街並みを歩くことに価値がある。大人でも十分楽しめる洗練された空間設計。",
    tags: ["テーマパーク", "イルミネーション", "カップル", "家族", "春の花"],
    stayDuration: 480, bestTime: "夜（イルミネーション）", crowdLevel: "high",
    budget: "¥6,000〜（入場料）", access: "JR大村線 ハウステンボス駅すぐ", rainyDay: true,
    highlights: ["イルミネーション", "チューリップ祭", "運河の街並み"],
    features: [
      { label: "光の王国", text: "冬のイルミネーションは日本最大規模。1,300万球の光が夜を染める。" },
      { label: "運河クルーズ", text: "ゴンドラに乗って街の内側から景色を楽しむ。昼と夜で全く違う顔。" },
    ],
    nearby: ["glover-garden", "ureshino-onsen"],
    officialUrl: "https://www.huistenbosch.co.jp/",
  },

  // ── 熊本 ──────────────────────────────────────
  {
    id: "kumamoto-castle", title: "熊本城", location: "熊本市中央区本丸",
    prefecture: "熊本県", prefectureId: "kumamoto", area: "熊本", areaId: "kumamoto-city",
    category: "castle",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "震災から立ち上がる黒い天守。復興の象徴がここにある。",
    longDescription: "熊本城は「難攻不落の城」と称されてきた日本三名城のひとつ。2016年の熊本地震で石垣が大きく崩れ、天守も一部損壊したが、長期的な復旧工事が続き2021年に天守閣の内部が公開された。展示は震災の記録も含め、城の歴史と再建の過程を丁寧に紹介。「武者返し」と呼ばれる反り返った石垣は加藤清正の設計の真骨頂。二の丸広場からの天守の眺めは絶景で、桜の時期は人が溢れる。",
    tags: ["城", "歴史", "復興", "熊本", "定番"],
    stayDuration: 120, bestTime: "朝 9:00開城直後", crowdLevel: "medium",
    budget: "¥800", access: "熊本市電 熊本城・市役所前電停から徒歩10分", rainyDay: true,
    highlights: ["天守閣", "武者返しの石垣", "桜の季節"],
    features: [
      { label: "武者返し", text: "下が急勾配で上になるほど反り返る石垣。敵の登攀を防ぐ設計の極致。" },
      { label: "震災復興展示", text: "崩れた石垣の写真と記録。城が市民にとって何を意味するかが伝わる。" },
    ],
    nearby: ["aso-mountain", "suizenji-garden"],
    officialUrl: "https://www.manyou-kumamoto.jp/castle/",
  },
  {
    id: "aso-mountain", title: "阿蘇山", location: "阿蘇市",
    prefecture: "熊本県", prefectureId: "kumamoto", area: "阿蘇", areaId: "aso-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80"],
    description: "世界最大級のカルデラ。草原が地平線まで広がる、スケール違いの景色。",
    longDescription: "阿蘇は世界有数の活火山で、中岳火口は今も噴煙を上げる。世界最大級のカルデラ（東西18km×南北25km）の内側に5万人が住む「人が暮らすカルデラ」は世界でも珍しい。草千里ヶ浜は青々とした草原に馬が放牧され、まるでモンゴルの草原のよう。火山ガスの濃度によって火口展望台への立入が規制されることがある。ミルクロードと呼ばれる尾根道ドライブが絶景。",
    tags: ["山", "火山", "自然", "ドライブ", "絶景"],
    stayDuration: 300, bestTime: "晴れた午前中", crowdLevel: "medium",
    budget: "¥1,000〜（見学料）", access: "JR豊肥本線 阿蘇駅からバスまたはレンタカー", rainyDay: false,
    highlights: ["中岳火口", "草千里ヶ浜", "ミルクロード"],
    features: [
      { label: "中岳火口", text: "エメラルドグリーンの火口湖と立ち昇る噴煙。自然の生々しさを体感する。" },
      { label: "草千里ヶ浜", text: "カルデラ内の草原。馬が放牧され、奥阿蘇の景色が広がる。" },
    ],
    nearby: ["kumamoto-castle", "kurokawa-onsen"],
  },
  {
    id: "kurokawa-onsen", title: "黒川温泉", location: "阿蘇郡南小国町満願寺",
    prefecture: "熊本県", prefectureId: "kumamoto", area: "黒川", areaId: "kurokawa-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80"],
    description: "渓谷に沿って宿が点在する。日本の温泉地の原型がここにある。",
    longDescription: "黒川温泉は田の原川の渓谷沿いに30軒近い旅館が集まる温泉地。派手な大型リゾートではなく、かやぶき屋根や石畳の路地が続くひなびた温泉街の風情が売り。入湯手形（¥1,600）を購入すると3か所の露天風呂を選んで入れるシステムが独特で、浴衣で湯めぐりできる。谷間に霧が立ち込める早朝が最も美しい。秋の紅葉シーズンは特に人気で予約が取りにくい。",
    tags: ["温泉", "湯めぐり", "秋", "カップル", "宿泊"],
    stayDuration: 360, bestTime: "早朝霧の時間帯（宿泊推奨）", crowdLevel: "medium",
    budget: "¥15,000〜（1泊）", access: "熊本駅からバスで約2時間20分", rainyDay: true,
    highlights: ["入湯手形での湯めぐり", "渓谷の露天風呂", "秋の紅葉"],
    features: [
      { label: "入湯手形", text: "3か所選んで入れるチケット。一日で違う泉質を楽しめる仕組み。" },
      { label: "早朝の霧", text: "谷間に霧が漂う黎明の黒川は別世界。宿泊してこそ体験できる。" },
    ],
    nearby: ["aso-mountain", "yufuin"],
  },
  {
    id: "suizenji-garden", title: "水前寺成趣園", location: "熊本市中央区水前寺公園",
    prefecture: "熊本県", prefectureId: "kumamoto", area: "熊本", areaId: "kumamoto-city",
    category: "garden",
    images: ["https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80"],
    description: "阿蘇の伏流水が湧き出る池。東海道五十三次を模した熊本の庭園。",
    longDescription: "水前寺成趣園は細川藩の大名庭園。阿蘇の伏流水が湧き出す池を中心に、富士山を模した丘や東海道五十三次を模した景色が配置された回遊式庭園。池の透明度が高く、鯉が数百匹泳ぐ。加藤清正公を祀る出水神社が隣接し、芸能の神様として知られる。熊本城から路面電車で15分とアクセスが良い。水前寺公園周辺には熊本名物のだご汁（野菜と団子の汁物）が食べられる食堂がある。",
    tags: ["庭園", "歴史", "自然", "熊本"],
    stayDuration: 60, bestTime: "午前中の澄んだ時間帯", crowdLevel: "low",
    budget: "¥400", access: "熊本市電 水前寺公園電停すぐ", rainyDay: false,
    highlights: ["湧水の池", "東海道五十三次模景", "出水神社"],
    features: [
      { label: "湧水の池", text: "阿蘇の地下水が湧き出す透明な池。底まで見える清澄さが熊本の誇り。" },
      { label: "出水神社", text: "能の舞台もある神社。熊本の伝統文化の継承拠点。" },
    ],
    nearby: ["kumamoto-castle", "aso-mountain"],
  },

  // ── 大分 ──────────────────────────────────────
  {
    id: "beppu-onsen", title: "別府温泉", location: "別府市",
    prefecture: "大分県", prefectureId: "oita", area: "別府", areaId: "beppu-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80"],
    description: "湯けむりが街を包む。日本一の温泉都市は、本物の温泉天国。",
    longDescription: "別府は日本最多の温泉湧出量を誇る温泉都市。源泉数も湧出量も日本一。「地獄めぐり」は7か所の個性的な温泉地の見学ツアーで、血の池地獄の赤い湯、海地獄のコバルトブルー、竜巻地獄の間欠泉などそれぞれ個性がある。地元民が使う「共同浴場」は観光客向けより湯質が良く¥100〜¥300で入れる穴場。砂湯（砂で蒸す入浴）は別府ならではの体験。",
    tags: ["温泉", "地獄めぐり", "定番", "大分"],
    stayDuration: 300, bestTime: "地獄めぐり：朝〜昼", crowdLevel: "high",
    budget: "¥2,200（地獄めぐり共通）", access: "JR日豊本線 別府駅から徒歩・バス", rainyDay: true,
    highlights: ["地獄めぐり", "砂湯", "共同浴場"],
    features: [
      { label: "血の池地獄", text: "酸化鉄で真っ赤に染まった温泉。世界最古の天然地獄。" },
      { label: "共同浴場", text: "地元民が日常的に使う銭湯型の温泉。観光地化されていない生の温泉文化。" },
    ],
    nearby: ["yufuin", "kuju-bridge"],
  },
  {
    id: "yufuin", title: "湯布院", location: "由布市湯布院町",
    prefecture: "大分県", prefectureId: "oita", area: "湯布院", areaId: "yufuin-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80"],
    description: "由布岳を背に、静かな温泉街が広がる。朝霧の湯布院がいちばん美しい。",
    longDescription: "湯布院は別府と並ぶ大分の温泉地。由布岳（1583m）を背景に、金鱗湖や湯の坪街道を中心とした温泉街が広がる。金鱗湖は秋から冬の早朝、湖面から霧が立ち上がる幻想的な景色で知られる。湯の坪街道沿いにはアンティーク雑貨、スイーツ、アート系ショップが並ぶ。週末は混雑するが、早朝の金鱗湖周辺は静寂に包まれている。温泉旅館のクオリティが高く、料理と宿を楽しむために来る人が多い。",
    tags: ["温泉", "秋", "霧", "カップル", "宿泊"],
    stayDuration: 360, bestTime: "早朝（金鱗湖の霧）", crowdLevel: "high",
    budget: "¥20,000〜（1泊）", access: "JR久大本線 由布院駅から徒歩15分", rainyDay: false,
    highlights: ["金鱗湖の朝霧", "湯の坪街道", "由布岳"],
    features: [
      { label: "金鱗湖の朝霧", text: "早朝6〜8時、湖面から霧が立ち上がる。写真愛好家が世界中から訪れる。" },
      { label: "湯の坪街道", text: "個性的なショップが並ぶ400mほどの通り。食べ歩きしながら散策。" },
    ],
    nearby: ["beppu-onsen", "kuju-bridge"],
  },
  {
    id: "kuju-bridge", title: "九重夢大吊橋", location: "玖珠郡九重町田野",
    prefecture: "大分県", prefectureId: "oita", area: "九重", areaId: "kuju-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "標高777m、長さ390mの歩行者専用吊橋。足の下に渓谷が広がる。",
    longDescription: "九重夢大吊橋は日本一の高さを誇る歩行者専用の吊橋（高さ173m）。橋の中央から見下ろすと、遥か下に震動の滝と振動の滝が落ちている。紅葉シーズンの橋上は渓谷全体が赤と黄に染まり、日本の紅葉絶景ランキングに常連で登場する。橋の揺れが意外と大きく、怖いくらいの体験。渡り終えるのに約10分。往復で20分。標高が高いので夏でも涼しい。",
    tags: ["絶景", "吊橋", "紅葉", "秋", "スリル"],
    stayDuration: 60, bestTime: "10月下旬〜11月上旬（紅葉）", crowdLevel: "medium",
    budget: "¥500", access: "大分自動車道 九重ICから約15分（車推奨）", rainyDay: false,
    highlights: ["日本一高い歩行者吊橋", "震動の滝", "紅葉"],
    features: [
      { label: "高さ173m", text: "足元を透かして見えるV字谷。橋が揺れるたびに現実感が薄れる。" },
      { label: "紅葉の絶景", text: "10月下旬〜11月、赤・黄・橙が渓谷全体を染める。日本の秋の精華。" },
    ],
    nearby: ["yufuin", "beppu-onsen"],
  },
  {
    id: "usuki-stone-buddha", title: "臼杵石仏", location: "臼杵市深田",
    prefecture: "大分県", prefectureId: "oita", area: "臼杵", areaId: "usuki-area",
    category: "temple",
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80"],
    description: "凝灰岩の崖に刻まれた磨崖仏。千年前の彫刻家の仕事に言葉を失う。",
    longDescription: "臼杵石仏は平安時代後期から鎌倉時代にかけて造られた磨崖仏群。61体が国宝に指定されており、これは国内最多。凝灰岩の崖を直接掘り込んだ仏像は、大きさも表情も多様で、見ていると飽きない。日本の石仏として唯一の国宝となったのは1995年。かつては頭部が落下していた像も修復されている。秋の曼殊沙華と石仏のコントラストは格別。",
    tags: ["国宝", "磨崖仏", "歴史", "仏教"],
    stayDuration: 90, bestTime: "午前中（光の当たり方が良い）", crowdLevel: "low",
    budget: "¥540", access: "JR日豊本線 臼杵駅からバス10分", rainyDay: true,
    highlights: ["国宝磨崖仏61体", "ホキ石仏", "古園石仏"],
    features: [
      { label: "古園石仏", text: "最大の群。大日如来の温和な表情は「東洋のモナリザ」と称される。" },
      { label: "秋の曼殊沙華", text: "9月下旬、石仏の足元に彼岸花が咲く。赤と石の対比が印象的。" },
    ],
    nearby: ["beppu-onsen", "yufuin"],
  },

  // ── 宮崎 ──────────────────────────────────────
  {
    id: "takachiho-gorge", title: "高千穂峡", location: "西臼杵郡高千穂町",
    prefecture: "宮崎県", prefectureId: "miyazaki", area: "高千穂", areaId: "takachiho-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80"],
    description: "柱状節理の断崖から落ちる滝。神話が生まれた理由がここにある。",
    longDescription: "高千穂峡は阿蘇火山の火砕流が五ヶ瀬川を侵食して形成されたV字峡谷。柱状節理（六角形の岩の柱）が壁面に並び、その間から真名井の滝が落ちる景観は国の名勝・天然記念物に指定されている。ボートで峡谷内に入り見上げると、断崖が空を切り取る圧倒的な景色になる。高千穂神社の夜神楽（毎晩公演）は神話の世界を現代に伝える舞台芸術。アマテラスが隠れた天岩戸神社も近くにある。",
    tags: ["絶景", "自然", "神話", "ボート", "宮崎"],
    stayDuration: 150, bestTime: "早朝（霧が出る時間帯）", crowdLevel: "medium",
    budget: "¥800〜（ボート料金）", access: "宮崎空港からバスで約2時間40分", rainyDay: false,
    highlights: ["真名井の滝", "ボート遊覧", "高千穂神社の夜神楽"],
    features: [
      { label: "真名井の滝", text: "17mの高さから滝が落ちる。ボート上から見上げる角度が最高。" },
      { label: "夜神楽", text: "毎晩20:00から高千穂神社で上演。天岩戸開きの神話を舞で再現。" },
    ],
    nearby: ["aoshima", "udo-shrine"],
  },
  {
    id: "aoshima", title: "青島", location: "宮崎市青島",
    prefecture: "宮崎県", prefectureId: "miyazaki", area: "宮崎", areaId: "miyazaki-city",
    category: "beach",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "鬼の洗濯板に囲まれた亜熱帯の島。宮崎の空と海の青さは本物。",
    longDescription: "青島は周囲約1.5kmの小さな島で、橋で本土と繋がる。島全体がビロウ椰子の亜熱帯植物に覆われ、南国感が満点。「鬼の洗濯板」と呼ばれる波状岩（砂岩と泥岩の互層）が島を囲み、干潮時には海底から現れる独特の地形が見られる。青島神社は縁結びの神様として知られ、絵馬がびっしり。宮崎市街から車で20分という近さが嬉しい。夏の海水浴シーズンは混む。",
    tags: ["島", "ビーチ", "縁結び", "自然", "宮崎"],
    stayDuration: 90, bestTime: "干潮時（鬼の洗濯板）", crowdLevel: "medium",
    budget: "無料", access: "JR日南線 青島駅から徒歩5分", rainyDay: false,
    highlights: ["鬼の洗濯板", "亜熱帯植物", "青島神社"],
    features: [
      { label: "鬼の洗濯板", text: "干潮時に現れる波状岩。SFの惑星のような非現実感がある。" },
      { label: "ビロウ椰子林", text: "島全体を覆う国の天然記念物。本州では見られない南国の植生。" },
    ],
    nearby: ["udo-shrine", "takachiho-gorge"],
  },
  {
    id: "udo-shrine", title: "鵜戸神宮", location: "日南市宮浦",
    prefecture: "宮崎県", prefectureId: "miyazaki", area: "日南", areaId: "nichinan-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "断崖の洞窟に朱塗りの本殿が鎮まる。太平洋を前に、神話の気配がある。",
    longDescription: "鵜戸神宮は日向灘の断崖絶壁に建てられた神社。本殿は海に突き出した洞窟の中にあり、社殿まで急な石段を降りていく珍しい「下り宮」。安産・子育ての神様として知られ、縁結びにもご利益がある。運玉と呼ばれる素焼きの小玉を、亀石の升の穴に投げ入れると願いが叶う（男性は左手、女性は右手で投げる）。崖上からの太平洋の眺めは圧巻。",
    tags: ["神社", "洞窟", "縁結び", "神話", "絶景"],
    stayDuration: 90, bestTime: "午前中（光が洞窟に差し込む）", crowdLevel: "low",
    budget: "無料", access: "宮崎市内からバスで約2時間", rainyDay: false,
    highlights: ["洞窟本殿", "運玉投げ", "太平洋の絶景"],
    features: [
      { label: "洞窟本殿", text: "海蝕洞窟の中に鎮座する朱塗りの社殿。自然と人工の対比が神秘的。" },
      { label: "運玉投げ", text: "素焼きの玉を亀石に投げ入れる。入れば願い事が叶うとか。" },
    ],
    nearby: ["aoshima", "takachiho-gorge"],
  },

  // ── 鹿児島 ──────────────────────────────────────
  {
    id: "sakurajima", title: "桜島", location: "鹿児島市桜島",
    prefecture: "鹿児島県", prefectureId: "kagoshima", area: "鹿児島", areaId: "kagoshima-city",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80"],
    description: "今も噴煙を上げる活火山が、市街地のすぐ目の前にある。",
    longDescription: "桜島は鹿児島湾に浮かぶ活火山島で、鹿児島市街からフェリー15分で渡れる。南岳は今も頻繁に噴火し、灰が街に降る日常が鹿児島の風景の一部。溶岩原を歩く散策コース、島一周のサイクリングロード、展望台からの鹿児島市街を望む絶景がある。桜島大根（世界最大級の大根）と桜島小みかん（世界最小クラス）は火山灰土壌が生んだ特産品。フェリーは24時間運航で、終夜の往復が可能。",
    tags: ["火山", "絶景", "自然", "鹿児島", "フェリー"],
    stayDuration: 180, bestTime: "早朝（噴火と朝日）または夕暮れ", crowdLevel: "low",
    budget: "¥160〜（フェリー）", access: "鹿児島港からフェリー15分", rainyDay: false,
    highlights: ["噴火の迫力", "溶岩原散策", "桜島大根"],
    features: [
      { label: "湯之平展望所", text: "一般が入れる最高地点。鹿児島市街を一望する絶景と噴煙のコントラスト。" },
      { label: "足湯", text: "フェリーターミナル近くに無料の足湯。灰まみれの旅の疲れをいやす。" },
    ],
    nearby: ["ibusuki-onsen", "sengan-en"],
  },
  {
    id: "yakushima", title: "屋久島", location: "熊毛郡屋久島町",
    prefecture: "鹿児島県", prefectureId: "kagoshima", area: "屋久島", areaId: "yakushima-area",
    category: "mountain",
    images: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80"],
    description: "樹齢数千年の屋久杉が立つ。時間のスケールが変わる場所。",
    longDescription: "屋久島は「一月に三十五日雨が降る」と言われるほど雨が多く、その雨が数千年の巨木を育てた。縄文杉（推定樹齢2,170〜7,200年）まではトロッコ道と登山道を往復10時間かけて歩く本格的なトレッキング。ガイドなしでは行けない。ウィルソン株（株の内側からハート形の空が見える）も人気スポット。白谷雲水峡はアニメ「もののけ姫」の森のモデルで、苔むした原生林が幻想的。一年中トレッキングできるが、5〜10月がベスト。",
    tags: ["世界遺産", "トレッキング", "縄文杉", "自然", "苔"],
    stayDuration: 480, bestTime: "5月〜10月（晴れ率が高い）", crowdLevel: "medium",
    budget: "¥5,000〜（ガイド込みトレッキング）", access: "鹿児島空港から飛行機約35分または高速船3時間半", rainyDay: false,
    highlights: ["縄文杉", "白谷雲水峡", "ウィルソン株"],
    features: [
      { label: "縄文杉", text: "推定樹齢2,000年超の杉の巨木。樹高25.3m。直前に立つと時間感覚がおかしくなる。" },
      { label: "白谷雲水峡", text: "苔むした岩と杉が続く原生林。雨上がりに霧がかかる様子は「もののけ姫」そのもの。" },
    ],
    nearby: ["sakurajima", "ibusuki-onsen"],
  },
  {
    id: "ibusuki-onsen", title: "指宿温泉", location: "指宿市",
    prefecture: "鹿児島県", prefectureId: "kagoshima", area: "指宿", areaId: "ibusuki-area",
    category: "onsen",
    images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80"],
    description: "砂の下に潜る入浴法。海岸の天然サウナで、ぐっすり眠れる体になる。",
    longDescription: "指宿温泉は薩摩半島の南端、開聞岳の麓に広がる温泉地。名物は「砂むし温泉」。砂浜の地熱で温まった砂の中に浸かる入浴法で、温泉旅館や市の施設「砂むし会館 砂楽」で体験できる。約10分間、砂に埋められた状態で大量に発汗する。抜け出した後の解放感と爽快感がクセになる。池田湖では世界最大級のウナギが生息する。開聞岳（薩摩富士）の美しい姿が湖面に映る。",
    tags: ["温泉", "砂むし", "鹿児島", "体験", "デトックス"],
    stayDuration: 180, bestTime: "早朝（すいてる時間帯）", crowdLevel: "medium",
    budget: "¥1,500〜（砂むし）", access: "JR指宿枕崎線 指宿駅から徒歩20分またはバス", rainyDay: true,
    highlights: ["砂むし温泉", "池田湖", "開聞岳"],
    features: [
      { label: "砂むし温泉", text: "仲居さんに砂をかけてもらい10分間埋まる。出た後のスッキリ感が独特。" },
      { label: "池田湖", text: "九州最大のカルデラ湖。湖畔から見る開聞岳が美しい。イッシーの伝説あり。" },
    ],
    nearby: ["sakurajima", "sengan-en"],
  },
  {
    id: "sengan-en", title: "仙巌園", location: "鹿児島市吉野町",
    prefecture: "鹿児島県", prefectureId: "kagoshima", area: "鹿児島", areaId: "kagoshima-city",
    category: "garden",
    images: ["https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80"],
    description: "桜島を「借景」にした薩摩藩の庭園。スケールが他の庭と違う。",
    longDescription: "仙巌園は島津家の別邸として1658年に造られた大名庭園。錦江湾と桜島を庭の一部として取り込んだ「借景」の手法で、どこを見ても桜島が視界に入る。世界遺産「明治日本の産業革命遺産」の構成資産にもなっており、反射炉跡など近代産業の遺構が残る。隣接する「尚古集成館」は日本最古の機械工場跡の博物館。霧島神宮とセットで薩摩の近代化の歴史を辿るのが正解のルート。",
    tags: ["庭園", "世界遺産", "歴史", "薩摩", "借景"],
    stayDuration: 120, bestTime: "午前中（桜島が澄んで見える）", crowdLevel: "medium",
    budget: "¥1,500", access: "鹿児島市電 鹿児島中央駅からバス30分", rainyDay: false,
    highlights: ["桜島の借景", "反射炉跡", "尚古集成館"],
    features: [
      { label: "借景の桜島", text: "園内のどこにいても桜島が見える。庭全体が自然と一体化した設計。" },
      { label: "薩摩切子体験", text: "薩摩の伝統工芸・薩摩切子のグラスを制作できる体験工房がある。" },
    ],
    nearby: ["sakurajima", "ibusuki-onsen"],
  },

  // ── 沖縄 ──────────────────────────────────────
  {
    id: "shurijo", title: "首里城", location: "那覇市首里金城町",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "那覇", areaId: "naha-area",
    category: "castle",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "琉球王国の宮殿が、那覇の丘の上に再建された。復興中の今が見どころ。",
    longDescription: "首里城は15世紀に建てられた琉球王国の宮殿。沖縄戦で焼失し、1992年に復元されたが2019年に再び焼失。現在は復元工事中で、正殿は工事現場を見学できる仮設施設から見られる。城壁や守礼の門などは健在で、琉球建築の美しさを感じられる。世界遺産「琉球王国のグスク及び関連遺産群」の中心。首里城公園全体を無料散策でき、那覇市街の展望も楽しめる。",
    tags: ["城", "世界遺産", "琉球", "歴史", "復興"],
    stayDuration: 90, bestTime: "早朝（観光客が少ない）", crowdLevel: "high",
    budget: "¥400〜", access: "ゆいレール 首里駅から徒歩15分", rainyDay: true,
    highlights: ["守礼の門", "城壁の眺め", "復元工事の見学"],
    features: [
      { label: "守礼の門", text: "「守礼の邦」と書かれた扁額が掲げられた門。かつて2,000円札の図案になった。" },
      { label: "復元工事", text: "2019年の焼失から続く工事を間近で見学できる。復興の過程を記録する機会。" },
    ],
    nearby: ["kokusai-dori", "kouri-island"],
  },
  {
    id: "churaumi-aquarium", title: "美ら海水族館", location: "国頭郡本部町石川",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "本部", areaId: "motobu-area",
    category: "museum",
    images: ["https://images.unsplash.com/photo-1519430044529-9b6e2e4ef9d5?w=1200&q=80"],
    description: "ジンベエザメが泳ぐ巨大水槽。沖縄の海の全てがここにある。",
    longDescription: "美ら海水族館はオーシャンエキスポ公園内にある国内最大級の水族館。メインの「黒潮の海」水槽は世界最大級の壁面アクリルパネル（幅22.5m×高さ8.2m）を誇り、ジンベエザメとマンタが優雅に泳ぐ。飼育困難とされたジンベエザメを世界で初めて長期飼育に成功した実績を持つ。イルカプログラムは追加料金なしで見られる公演がある。周辺のオーシャンエキスポ公園には熱帯ドリームセンター（植物園）もある。",
    tags: ["水族館", "ジンベエザメ", "家族", "沖縄", "海"],
    stayDuration: 240, bestTime: "開館直後または閉館前1時間（混雑を避ける）", crowdLevel: "high",
    budget: "¥2,180（大人）", access: "那覇空港から車で約2時間（高速利用）", rainyDay: true,
    highlights: ["黒潮の海水槽", "ジンベエザメ", "マンタ"],
    features: [
      { label: "ジンベエザメ", text: "体長8m超の個体が悠然と泳ぐ。水槽の前に立つと吸い込まれる感覚。" },
      { label: "イルカラグーン", text: "ショーではなく自然行動を観察するスタイル。海と繋がった環境が理想的。" },
    ],
    nearby: ["kouri-island", "shurijo"],
    officialUrl: "https://churaumi.okinawa/",
  },
  {
    id: "kokusai-dori", title: "国際通り", location: "那覇市牧志",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "那覇", areaId: "naha-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80"],
    description: "那覇の目抜き通り。泡盛と三線とゴーヤーチャンプルーで沖縄を全部体験できる。",
    longDescription: "国際通りは那覇の中心商店街。1.6km続く通りに土産物店・食堂・居酒屋・ドラッグストアが密集する。朝市の雰囲気は牧志公設市場周辺が本物。市場の2階の食堂では1階で買った食材を調理してもらえる（持ち込み調理可）システムが独特で面白い。日曜日の午前中は「歩行者天国」になり、エイサーのパフォーマンスが無料で見られる。シーサーの土産物の価格は国際通りより市場の奥の方が安い。",
    tags: ["街歩き", "グルメ", "土産", "那覇", "にぎやか"],
    stayDuration: 120, bestTime: "夕方〜夜、または日曜朝（歩行者天国）", crowdLevel: "high",
    budget: "¥2,000〜", access: "ゆいレール 牧志駅から徒歩3分", rainyDay: true,
    highlights: ["牧志公設市場", "歩行者天国（日曜）", "泡盛試飲"],
    features: [
      { label: "牧志公設市場", text: "豚の頭、カラフルな熱帯魚など沖縄の食材が並ぶ市場。2階で調理してくれる。" },
      { label: "泡盛の試飲", text: "酒販店で沖縄全島の泡盛を試飲できる店がある。お気に入りを探す旅。" },
    ],
    nearby: ["shurijo"],
  },
  {
    id: "kouri-island", title: "古宇利島", location: "国頭郡今帰仁村古宇利",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "今帰仁", areaId: "nakijin-area",
    category: "beach",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "エメラルドの海に架かる橋を渡る。沖縄の「恋の島」は写真より美しい。",
    longDescription: "古宇利島は沖縄北部の小島で、古宇利大橋（全長1960m）で本島と繋がっている。橋の上からは左右に美しいエメラルドの海が広がり、沖縄で最も爽快なドライブルートのひとつ。「ハートロック」と呼ばれる岩はカップルの間で縁結びのスポットとして有名。島内のビーチはプライベート感があり、シュノーケリングに最適。沖縄版アダムとイブの伝説が残る「恋の島」でもある。",
    tags: ["ビーチ", "ドライブ", "恋愛", "橋", "エメラルド"],
    stayDuration: 120, bestTime: "午前中（透明度が高い）", crowdLevel: "medium",
    budget: "無料（橋・ビーチ）", access: "那覇空港から車で約1時間30分", rainyDay: false,
    highlights: ["古宇利大橋", "ハートロック", "シュノーケリング"],
    features: [
      { label: "古宇利大橋", text: "約2kmの橋の上で窓を開けると、両側から海の風が吹き込む。" },
      { label: "ハートロック", text: "ビーチから歩いた先にある二つ並んだハート形の岩。朝が人が少ない。" },
    ],
    nearby: ["churaumi-aquarium", "nakijin-castle"],
  },
  {
    id: "taketomi-island", title: "竹富島", location: "八重山郡竹富町竹富",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "石垣・八重山", areaId: "yaeyama-area",
    category: "street",
    images: ["https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80"],
    description: "赤瓦と白砂の路地。時間が止まった琉球の集落が今も生きている。",
    longDescription: "竹富島は石垣島からフェリー10分の距離にある人口約350人の小さな島。赤瓦の屋根と白い砂が敷かれた路地が続く集落景観は、国の重要伝統的建造物群保存地区に指定されている。水牛車に乗りながら集落を案内してもらうのが島の定番。コンドイ浜は白砂と透明な海が広がる天国のようなビーチ。島全体が平坦で自転車移動が快適。夜は星空が美しく、宿泊した方が島の本質が分かる。",
    tags: ["集落", "ビーチ", "水牛車", "世界遺産", "星空"],
    stayDuration: 240, bestTime: "早朝（人が少ない集落散策）", crowdLevel: "medium",
    budget: "¥2,000〜（フェリー＋水牛車）", access: "石垣港からフェリー10分", rainyDay: false,
    highlights: ["赤瓦集落", "コンドイ浜", "水牛車観光"],
    features: [
      { label: "水牛車", text: "ゆっくり揺れながら三線の音と共に集落を回る。急ぐ必要のない時間。" },
      { label: "コンドイ浜", text: "島の西側にある遠浅のビーチ。干潮時は沖まで歩いて行ける。" },
    ],
    nearby: ["churaumi-aquarium", "shurijo"],
  },
  {
    id: "manza-mo", title: "万座毛", location: "国頭郡恩納村真栄田",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "恩納", areaId: "onna-area",
    category: "viewpoint",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "象の形をした岩と青い海。琉球王が「万人が座れる毛」と称えた絶景。",
    longDescription: "万座毛は沖縄本島中部、恩納村の断崖上にある景勝地。名前は琉球王尚敬が「万人が座れる野原」と称えたことに由来する。象の鼻に似た形の岩が断崖の先端に張り出し、その先に広がるエメラルドブルーの海との対比が美しい。2022年に周辺が整備され、観光施設も充実。夕日の時間帯は岩と海が黄金色に染まり、旅の写真の中で最も印象的な一枚が撮れる場所のひとつ。",
    tags: ["絶景", "断崖", "海", "夕日", "沖縄"],
    stayDuration: 60, bestTime: "夕方（夕日と岩のコントラスト）", crowdLevel: "medium",
    budget: "¥100〜", access: "那覇空港から車で約1時間", rainyDay: false,
    highlights: ["象の鼻岩", "エメラルドの海", "夕日"],
    features: [
      { label: "象の鼻岩", text: "断崖の端に突き出た岩。青い海を背景にすると絵になる。" },
      { label: "夕日の時間帯", text: "17時以降に来ると逆光で岩が黒いシルエットになり、神秘的な景色になる。" },
    ],
    nearby: ["churaumi-aquarium", "kouri-island"],
  },
  {
    id: "zamami-island", title: "座間味島", location: "島尻郡座間味村座間味",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "慶良間", areaId: "kerama-area",
    category: "beach",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"],
    description: "ケラマブルーの海は、沖縄本島とは別の色をしている。",
    longDescription: "座間味島は那覇から高速船50分で渡れる慶良間諸島の島。「ケラマブルー」と称される海の透明度は世界屈指で、サンゴ礁の保護が行き届いている。冬（1〜3月）はザトウクジラの繁殖海域で、島からホエールウォッチングができる。シュノーケリングやダイビングの聖地でもある。高台の展望台からは東シナ海と太平洋を同時に見渡せる。アカマ・古座間味・阿真の3ビーチは個性が違い、はしごするのが楽しい。",
    tags: ["ビーチ", "ダイビング", "世界遺産", "クジラ", "離島"],
    stayDuration: 480, bestTime: "1〜3月（クジラ）、4〜10月（ダイビング）", crowdLevel: "low",
    budget: "¥3,000〜（高速船往復）", access: "那覇・泊港から高速船50分", rainyDay: false,
    highlights: ["ケラマブルーの海", "ホエールウォッチング", "サンゴ礁シュノーケリング"],
    features: [
      { label: "ケラマブルー", text: "エメラルドを超えた深いブルー。船の上から底まで見える透明度。" },
      { label: "ホエールウォッチング", text: "1〜3月に座間味沖にザトウクジラが集まる。ブリーチングを見られることも。" },
    ],
    nearby: ["shurijo", "kokusai-dori"],
  },
  {
    id: "sefa-utaki", title: "斎場御嶽", location: "南城市知念久手堅",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "南城", areaId: "nanjo-area",
    category: "shrine",
    images: ["https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80"],
    description: "巨岩の隙間から、久高島が見える。琉球最高の聖地に足を踏み入れる。",
    longDescription: "斎場御嶽（セーファウタキ）は琉球王国最高の聖地。世界遺産「琉球王国のグスク及び関連遺産群」の構成資産のひとつ。三庫理（さんぐーい）と呼ばれる二つの巨岩が寄り合った空間は、自然が作り出した最高の聖域。その隙間から神の島・久高島が見える。現在も祈りの場として地元の人々に使われており、「神聖な場所」という空気が境内全体に漂っている。",
    tags: ["世界遺産", "聖地", "琉球", "パワースポット", "歴史"],
    stayDuration: 90, bestTime: "開園直後（混雑を避ける）", crowdLevel: "medium",
    budget: "¥300", access: "那覇空港から車で約50分", rainyDay: false,
    highlights: ["三庫理の巨岩", "久高島の展望", "神聖な空気"],
    features: [
      { label: "三庫理", text: "二つの巨岩が形成する三角形の空間。ここが斎場御嶽の核心。" },
      { label: "久高島の展望", text: "岩の隙間から見える神の島。琉球神話の始まりの場所とされる。" },
    ],
    nearby: ["shurijo", "kokusai-dori"],
  },
  {
    id: "nakijin-castle", title: "今帰仁城跡", location: "国頭郡今帰仁村今泊",
    prefecture: "沖縄県", prefectureId: "okinawa", area: "今帰仁", areaId: "nakijin-area",
    category: "castle",
    images: ["https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80"],
    description: "首里城よりも古い城壁が、沖縄北部の丘の上に残る。桜の名所でもある。",
    longDescription: "今帰仁城は14世紀の北山王国の居城。世界遺産「琉球王国のグスク及び関連遺産群」の構成資産で、首里城と同時期に世界遺産に登録された。石灰岩の城壁が複雑な曲線を描いて残り、その技術は首里城よりも古い時代のもの。毎年1〜2月には城内の寒緋桜が開花し、「今帰仁グスク桜まつり」が開催される。本土より1〜2ヶ月早く咲く沖縄の桜を、城跡で見る体験は格別。",
    tags: ["世界遺産", "城跡", "桜", "琉球", "歴史"],
    stayDuration: 90, bestTime: "1〜2月（桜の季節）", crowdLevel: "low",
    budget: "¥600", access: "那覇空港から車で約1時間30分", rainyDay: false,
    highlights: ["石灰岩の城壁", "寒緋桜", "海を望む眺望"],
    features: [
      { label: "城壁の曲線美", text: "石灰岩を積み上げた城壁は、自然の地形に沿って曲線を描く。" },
      { label: "寒緋桜", text: "1月下旬〜2月、本土より早く咲く濃いピンクの桜が城跡を染める。" },
    ],
    nearby: ["kouri-island", "churaumi-aquarium"],
  },
];
