import { Article } from "@/types/article";

export const akitaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "akita-kakunodate-bukeyashiki-walk",
    title: "角館武家屋敷通り──みちのくの小京都を枝垂れ桜の季節に歩く",
    description: "武家屋敷の黒板塀と枝垂れ桜が作る春の角館は、東北で最も美しい風景のひとつだ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "akita",
    tags: ["角館", "武家屋敷", "桜", "みちのくの小京都", "春"],
    spotIds: ["kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "黒板塀の武家屋敷通り──400年変わらない景観", level: 2 },
      { type: "text", content: "角館の武家屋敷通りは江戸時代の区画がほぼそのまま残る希少な町並みだ。延長約700mの通りに沿って、黒板塀と切妻屋根の武家屋敷が連続する。国の重要伝統的建造物群保存地区に選定されており、石畳の歩道を歩くだけで江戸時代にタイムスリップする感覚がある。" },
      { type: "spot-card", content: "kakunodate-bukeyashiki" },
      { type: "heading", content: "枝垂れ桜のシーズン──4月下旬の1週間", level: 2 },
      { type: "text", content: "武家屋敷通りに植えられた約160本の枝垂れ桜は、例年4月下旬に満開になる。樹齢300年を超える老木もあり、黒い板塀越しに垂れ下がるピンクの枝は、日本の春の原風景そのものだ。見頃の週末は角館観光協会の開花情報を確認してから訪れること。" },
      { type: "heading", content: "岩橋家・青柳家──内部公開の屋敷を選ぶ", level: 2 },
      { type: "text", content: "武家屋敷のうち内部公開しているのは数軒。青柳家（入場500円）は武器・甲冑・生活道具が展示され、秋田藩の武家文化が凝縮されている。岩橋家の庭園は枝垂れ桜が庭内まで入り込み、内側から見る桜は格別だ。" },
    ],
    relatedArticleSlugs: ["akita-kakunodate-autumn-foliage", "akita-tazawa-lake-trip"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "akita-tazawa-lake-trip",
    title: "田沢湖──日本最深の湖面に映るコバルトブルーと秋田美人伝説",
    description: "深さ423mの田沢湖は、透明度と青みが他の湖とは別格だ。たつこ像が指す先に何があるか。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "akita",
    tags: ["田沢湖", "日本最深", "コバルトブルー", "たつこ像", "湖"],
    spotIds: ["tazawa-lake"],
    sections: [
      { type: "heading", content: "なぜ田沢湖はコバルトブルーなのか", level: 2 },
      { type: "text", content: "田沢湖の深さは日本最深の423mで、水の透明度が他の湖を圧倒する。深い水は赤い光を吸収し、青い光を散乱させる。加えて流入河川の少なさと水の純粋さが、あの独特のコバルトブルーを生み出している。晴天時の午前中が最も青が深く見える時間帯だ。" },
      { type: "spot-card", content: "tazawa-lake" },
      { type: "heading", content: "たつこ像と永遠の美女伝説", level: 2 },
      { type: "text", content: "湖西岸に立つ金色のたつこ像は、美貌を永遠に保ちたいと神に祈った少女・辰子が龍になり田沢湖の主になったという伝説を象徴する。像の美しさと湖の青さが重なる構図は、どの角度から撮っても絵になる。早朝は霧が湖面を這い、たつこ像が霧中に浮かぶ幻想的な写真が撮れる。" },
      { type: "heading", content: "湖畔サイクリング一周40km", level: 2 },
      { type: "text", content: "田沢湖を一周する道路は約20kmで、電動アシスト自転車なら2〜3時間で回れる（レンタサイクル1,000〜1,500円/3時間）。南側の湖岸道路は特にアップダウンが少なく、湖面を眺めながらのサイクリングは爽快だ。乳頭温泉郷まで足を延ばすなら午前中に出発すること。" },
    ],
    relatedArticleSlugs: ["akita-nyuto-onsen-stay", "akita-kakunodate-bukeyashiki-walk"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "akita-nyuto-onsen-stay",
    title: "乳頭温泉郷──秘湯7宿を巡る湯めぐり帖、ブナ林の奥の白濁湯",
    description: "鶴の湯から大釜まで、7つの宿が異なる泉質を持つ。日帰りパスで全部回る方法。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-12",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "akita",
    tags: ["乳頭温泉郷", "秘湯", "白濁湯", "湯めぐり", "ブナ林"],
    spotIds: ["nyuto-onsen"],
    sections: [
      { type: "heading", content: "7宿それぞれの泉質と個性", level: 2 },
      { type: "text", content: "乳頭温泉郷の7宿（鶴の湯・妙乃湯・黒湯・蟹場・大釜・孫六・休暇村）はそれぞれ源泉が異なる。鶴の湯の白濁した硫黄泉、妙乃湯の透明なアルカリ泉、黒湯の茶褐色の強酸性泉──同じ山の中にこれほど多様な湯が湧くのは地質的に稀有な環境だ。" },
      { type: "spot-card", content: "nyuto-onsen" },
      { type: "heading", content: "湯めぐり帖（2,000円）の使い方", level: 2 },
      { type: "text", content: "「乳頭温泉郷湯めぐり帖」は2,000円で7宿すべての日帰り入浴が1回ずつ利用できる冊子だ。有効期間は1年間なので、1日で全部回る必要はない。7宿を2日に分けて巡り、好みの湯に宿泊予約を入れるという使い方が上級者の定番だ。" },
      { type: "heading", content: "鶴の湯の茅葺き旅館──予約は半年前から", level: 2 },
      { type: "text", content: "乳頭温泉郷で最も人気の「鶴の湯温泉」の宿泊は、人気シーズンは半年前でも満室になることがある。電話受付は毎月1日から翌月分の予約が開始される。茅葺き屋根の本陣棟と露天の白濁湯の組み合わせは、日本の秘湯文化の最高到達点のひとつだ。" },
    ],
    relatedArticleSlugs: ["akita-tazawa-lake-trip", "akita-onsen-solo-plan"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "akita-inaniwa-udon-deep-dive",
    title: "稲庭うどん──日本三大うどんの最細麺を秋田で食べる本物の体験",
    description: "300年以上の歴史を持つ稲庭うどんは、手延べの細さと喉越しが他の麺と全く違う。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "akita",
    tags: ["稲庭うどん", "日本三大うどん", "グルメ", "秋田名物", "麺"],
    spotIds: ["kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "稲庭うどんとは何か──扁平で細い奇跡の麺", level: 2 },
      { type: "text", content: "稲庭うどんは江戸時代、秋田県湯沢市稲庭地区で生まれた干し麺だ。手延べを繰り返すことで断面が扁平になり、幅2〜3mm・厚さ1mm前後という他のうどんにない形状を持つ。茹でた後の透き通った白と、啜った時のなめらかな食感が特徴だ。" },
      { type: "heading", content: "本場・稲庭で食べる意味", level: 2 },
      { type: "text", content: "「佐藤養助」「稲庭うどん小忠太」などの老舗は稲庭地区（湯沢市）に本店を構える。冷たいもり（ざる）と温かい汁の両方を一度に食べる「食べ比べセット」が定番注文だ。汁は真昆布の出汁と地元醤油のシンプルな配合で、麺の味を引き立てる。" },
      { type: "heading", content: "角館や秋田市内でも食べられる", level: 2 },
      { type: "text", content: "本場湯沢まで行けない場合は、角館や秋田市内の日本料理店でも稲庭うどんを提供している。ただし乾麺の茹で方と汁の質は店により差が大きい。土産として乾麺を買う場合は冷水でしめてから食べることを守れば、家庭でも80%の再現が可能だ。" },
    ],
    relatedArticleSlugs: ["akita-kiritanpo-guide", "akita-kakunodate-bukeyashiki-walk"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "akita-kiritanpo-guide",
    title: "きりたんぽ鍋──秋田の山の家庭料理を現地で食べる最低限の知識",
    description: "ご飯を串に巻いて焼いたきりたんぽは、秋田の比内地鶏スープで煮ることで完成する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "akita",
    tags: ["きりたんぽ", "秋田名物", "鍋", "比内地鶏", "冬グルメ"],
    spotIds: ["kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "きりたんぽの正しい作り方と食べ方", level: 2 },
      { type: "text", content: "きりたんぽは新米を半潰しにして杉の棒に巻きつけ、囲炉裏または炭火で焼いたものだ。「本場のきりたんぽ鍋」は比内地鶏のガラで取った濃いスープに、たんぽ・比内地鶏・舞茸・ごぼう・せりを入れて煮る。せりの根まで使う食べ方が秋田流だ。" },
      { type: "heading", content: "秋田市内の専門店で食べる", level: 2 },
      { type: "text", content: "秋田市の「秋田比内や」や「川反の酒蔵」周辺の郷土料理店では、10月〜3月にきりたんぽ鍋コースが提供される。1人前2,500〜3,500円が相場で、稲庭うどんとセットのコース（4,000〜5,000円）が観光客に人気だ。夏季はきりたんぽ鍋を出さない店が多い。" },
      { type: "heading", content: "「味噌たんぽ」は通年食べられる", level: 2 },
      { type: "text", content: "鍋ではなく、たんぽに秋田味噌を塗って焼いた「味噌たんぽ」は屋台や道の駅でも食べられ、通年提供される軽食だ。1本150〜200円で、香ばしい焼き目と甘辛い味噌の組み合わせがクセになる。角館の武家屋敷通り沿いの茶屋でも提供される。" },
    ],
    relatedArticleSlugs: ["akita-inaniwa-udon-deep-dive", "akita-namahage-guide"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "akita-namahage-guide",
    title: "なまはげ──男鹿半島のユネスコ無形文化遺産、仮面の神の正体を知る",
    description: "なぜ鬼は子どもを泣かせるのか。なまはげの意味を理解して男鹿に行くと全く違う体験になる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-12-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "akita",
    tags: ["なまはげ", "男鹿半島", "ユネスコ", "民俗", "冬"],
    spotIds: ["kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "なまはげとは何者か──神の使いとしての来訪神", level: 2 },
      { type: "text", content: "なまはげは毎年大晦日の夜、男鹿半島の集落を訪れる来訪神だ。鬼のような面と蓑をまとい「泣く子はいねがぁ」と叫びながら家に入り、怠け者や悪い子を戒める。ユネスコ無形文化遺産「来訪神：仮面・仮装の神々」に2018年登録された。" },
      { type: "heading", content: "なまはげ館──通年で体験できる施設", level: 2 },
      { type: "text", content: "男鹿市の「なまはげ館」では、180体以上のなまはげ面が展示されており、地域ごとのデザインの違いが一目でわかる。隣接する「男鹿真山伝承館」では地元のかつての民家でなまはげ行事を再現した体験公演（1,600円）を見られる。通年開館のため大晦日以外に行く観光客はここで体験できる。" },
      { type: "heading", content: "大晦日のなまはげ本番を見たい人へ", level: 2 },
      { type: "text", content: "本物のなまはげ行事を見るには大晦日に男鹿の民家に泊まる必要がある。観光客向けに宿を通じた見学プログラムを提供する旅館もあるが、枠が限られるため秋から予約を始めること。2月の「なまはげ柴灯まつり」は観光客向けの公開行事として規模が大きく、アクセスしやすい。" },
    ],
    relatedArticleSlugs: ["akita-kiritanpo-guide", "akita-oga-peninsula-trip"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "akita-oga-peninsula-trip",
    title: "男鹿半島一周ドライブ──なまはげの里と日本海の断崖絶壁を一日で",
    description: "男鹿半島は秋田の中でも最も個性的な地形だ。断崖と入り江が交互に現れるドライブコース。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-25",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "akita",
    tags: ["男鹿半島", "ドライブ", "断崖", "日本海", "寒風山"],
    spotIds: ["kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "寒風山の山頂回転展望台──360度の秋田平野", level: 2 },
      { type: "text", content: "男鹿半島の付け根に位置する寒風山（355m）の山頂には回転式展望台がある。日本海・男鹿半島・八郎潟干拓地・秋田市街が全方位に広がり、天気が良ければ鳥海山も見える。展望台の回転速度はゆっくりで、40分かけて一周する。" },
      { type: "heading", content: "ゴジラ岩──日没の逆光シルエット", level: 2 },
      { type: "text", content: "男鹿半島西岸の戸賀湾沿いに立つ「ゴジラ岩」は、夕暮れ時に太陽を口から吐き出すように見える構図で撮影できる。日没30分前から太陽の位置が合い始める。駐車場から徒歩3分で到達できる手軽さで、SNS映えスポットとして全国から写真愛好家が集まる。" },
      { type: "heading", content: "入道崎の白黒灯台と八望台", level: 2 },
      { type: "text", content: "半島最北端の入道崎には白黒横縞模様の灯台（北緯40度線上）と芝生の草原が広がる。灯台に登ると（入場300円）日本海の水平線が圧巻だ。八望台からは戸賀湾の二つの砲弾形カルデラ湖が見下ろせる。半島一周は全行程で約4〜5時間、レンタカーが必須だ。" },
    ],
    relatedArticleSlugs: ["akita-namahage-guide", "akita-kakunodate-bukeyashiki-walk"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "akita-onsen-solo-plan",
    title: "秋田の温泉一人旅──乳頭・玉川・後生掛を3日で巡る泉質制覇ルート",
    description: "日本一の強酸性泉・玉川温泉、泥湯と地熱の後生掛。秋田の温泉は個性が強い。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "akita",
    tags: ["一人旅", "温泉", "玉川温泉", "後生掛温泉", "秘湯"],
    spotIds: ["nyuto-onsen"],
    sections: [
      { type: "heading", content: "玉川温泉──日本一の強酸性泉でリウマチに挑む", level: 2 },
      { type: "text", content: "pH1.05という日本最強の強酸性泉を持つ玉川温泉は、リウマチや皮膚病への効能で知られる。岩盤浴エリア（地熱が湧き出す地面に横たわる）は全国から湯治客が訪れ、長期滞在者も多い。希釈した浴槽で体を慣らしてから原泉に近い浴槽へ移行するのが鉄則だ。" },
      { type: "heading", content: "後生掛温泉──泥風呂と地獄地帯の迫力", level: 2 },
      { type: "text", content: "後生掛温泉は「馬で来て足で帰る」と言われるほどの効能で知られる湯治場だ。泥湯、蒸し風呂、箱蒸し、泡風呂と湯の種類が豊富で、1泊2食付きの湯治プランが充実している。宿舎の外には噴気孔が並ぶ地獄地帯遊歩道があり、温泉の源に立っている実感を味わえる。" },
      { type: "heading", content: "乳頭で締める──静寂のブナ林と白濁湯", level: 2 },
      { type: "text", content: "玉川・後生掛の強い個性の温泉を体験した後、乳頭温泉郷の穏やかな硫黄泉で締めると、温泉の多様性を体で理解できる。田沢湖駅から乳頭温泉行きのバスは1日4本（要事前確認）。ブナ林の中に点在する宿の静けさは、長旅の疲れを完全に溶かしてくれる。" },
    ],
    relatedArticleSlugs: ["akita-nyuto-onsen-stay", "akita-tazawa-lake-trip"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "akita-kakunodate-autumn-foliage",
    title: "角館の紅葉──武家屋敷の紅葉と檜木内川の桜並木が同時に色づく秋",
    description: "桜で有名な角館だが、秋の紅葉も同等に美しい。武家屋敷通りの黒塀×黄葉の組み合わせ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "akita",
    tags: ["角館", "紅葉", "秋", "武家屋敷", "檜木内川"],
    spotIds: ["kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "10月下旬〜11月上旬が紅葉の見頃", level: 2 },
      { type: "text", content: "角館の紅葉は例年10月下旬から始まり、11月上旬が最盛期だ。武家屋敷通りのモミジ・イチョウが黄橙色に染まり、黒板塀との対比が春の桜とは全く異なる絵を作る。気温が下がる朝方は霧が発生することもあり、霧と紅葉の幻想的な風景が撮影できる。" },
      { type: "heading", content: "檜木内川堤の紅葉遊覧船", level: 2 },
      { type: "text", content: "春の桜で有名な檜木内川堤は、秋には並木の葉が黄色と橙に染まる。川沿いを歩く散策コース（約2km）は起伏がなく歩きやすい。10月の紅葉まつり期間中は屋台も出て、きりたんぽ焼きや稲庭うどんを食べながら散策できる。" },
      { type: "heading", content: "田沢湖の紅葉と組み合わせる1泊2日", level: 2 },
      { type: "text", content: "角館から田沢湖は電車で15分と近いため、2地点を1泊2日で巡る旅程が組みやすい。角館に早朝入りして武家屋敷の晩秋の空気を楽しみ、午後に田沢湖へ移動して湖畔に宿泊、翌朝に田沢湖の朝霧を見て乳頭温泉日帰り入浴という行程が充実度の高い定番だ。" },
    ],
    relatedArticleSlugs: ["akita-kakunodate-bukeyashiki-walk", "akita-tazawa-lake-trip"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "akita-couple-trip-plan",
    title: "秋田カップル旅行──角館×乳頭温泉×田沢湖の2泊3日黄金ルート",
    description: "武家屋敷、秘湯、神秘の湖を二人でたどる。秋田観光の最高到達点を2泊3日で体験する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "akita",
    tags: ["カップル", "2泊3日", "角館", "乳頭温泉", "田沢湖"],
    spotIds: ["kakunodate-bukeyashiki", "tazawa-lake", "nyuto-onsen"],
    sections: [
      { type: "heading", content: "1日目：角館でタイムトリップ", level: 2 },
      { type: "text", content: "新幹線でこまちに乗ると東京から角館まで約3時間。午後に到着し、武家屋敷通りをゆっくり散策して角館の小京都を感じる。夕食は地元料理店できりたんぽ鍋と稲庭うどんのコース。角館温泉の宿に1泊。桜シーズンは早めに宿の確保が必須だ。" },
      { type: "heading", content: "2日目：田沢湖サイクリングから乳頭へ", level: 2 },
      { type: "text", content: "午前中に田沢湖を電動自転車で一周（約2時間）。たつこ像を必ず写真に収め、湖畔のカフェでランチ。午後に田沢湖高原を登り、乳頭温泉郷へ（バスで30分）。到着後は湯めぐり帖で日帰り入浴2〜3湯を巡り、泊まる宿の湯に最後に入る。" },
      { type: "heading", content: "3日目：鶴の湯の朝風呂から帰路", level: 2 },
      { type: "text", content: "乳頭温泉最終日は誰もいない早朝5時〜7時の露天風呂が至福の時間だ。チェックアウト後、田沢湖駅から秋田新幹線で帰路につく。駅の売店で稲庭うどんの乾麺とこまちのパッケージ土産を購入して締めくくり。秋田の3大魅力を全部体験できる旅程だ。" },
    ],
    relatedArticleSlugs: ["akita-kakunodate-bukeyashiki-walk", "akita-nyuto-onsen-stay"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "akita-family-trip",
    title: "秋田ファミリー旅行──子どもが喜ぶ体験と安心できる宿の選び方",
    description: "なまはげ体験、田沢湖遊覧、きりたんぽ作り。子ども連れで秋田を楽しむ完全プラン。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-28",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "akita",
    tags: ["ファミリー", "子連れ", "体験", "なまはげ", "秋田"],
    spotIds: ["kakunodate-bukeyashiki", "tazawa-lake"],
    sections: [
      { type: "heading", content: "なまはげ館の子ども向け体験コース", level: 2 },
      { type: "text", content: "男鹿市のなまはげ館では、子ども向けに「なまはげ体験コーナー」がある。なまはげの面をかぶって記念写真を撮れる（無料）ほか、なまはげ太鼓の演奏体験も定期開催される。本物のなまはげが登場する体験公演（1,600円）は幼児には怖すぎることがあるので、4歳以下は様子を見ながら判断を。" },
      { type: "heading", content: "田沢湖の遊覧船──子どもは半額", level: 2 },
      { type: "text", content: "田沢湖の遊覧船は小学生以下が半額（大人800円、子ども400円）。30分のコースで湖上からの眺めを楽しめる。ペダルボートのレンタルも可能で、子どもと一緒に漕ぐ湖上体験は思い出になる。ライフジャケットは無料で借りられる。" },
      { type: "heading", content: "きりたんぽ作り体験で食育", level: 2 },
      { type: "text", content: "角館周辺の体験施設や一部の農家民宿では、きりたんぽ作り体験（2,000〜3,000円/1名）を提供している。ご飯を棒に巻いて囲炉裏で焼く工程は、小学生以上なら楽しめる食育体験だ。自分で作ったたんぽを鍋に入れて食べる達成感は格別だ。" },
    ],
    relatedArticleSlugs: ["akita-namahage-guide", "akita-tazawa-lake-trip"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "akita-luxury-stay",
    title: "秋田の贅沢な一泊──乳頭鶴の湯本陣棟と角館の名旅館を比較する",
    description: "秋田で一番贅沢な宿泊体験とは何か。予算5万円以上で選ぶべき2つの宿の全容。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-09-30",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "akita",
    tags: ["高級旅館", "秋田", "乳頭温泉", "角館", "贅沢"],
    spotIds: ["nyuto-onsen", "kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "鶴の湯温泉・本陣棟──茅葺きで眠る江戸時代", level: 2 },
      { type: "text", content: "乳頭温泉郷「鶴の湯」の本陣棟は、秋田藩の藩主が湯治に使ったとされる茅葺き建築の客室だ。囲炉裏付きの部屋で夕食を食べ、白濁の露天風呂に何度も入る一夜は、日本の山岳温泉文化の頂点を体験することを意味する。一人2〜3万円（2食付き）で、秋の紅葉シーズンはさらに早め予約が必要だ。" },
      { type: "heading", content: "角館の武家屋敷ゲストハウス──歴史建築に泊まる", level: 2 },
      { type: "text", content: "角館市内には江戸・明治期の建築を改修した高級ゲストハウスや旅館が増えている。古民家の梁と板の間、障子の隙間から見える坪庭──この空間で食べる稲庭うどんと山菜料理は、単なるグルメを超えた文化体験になる。" },
      { type: "heading", content: "どちらを選ぶか──目的で変わる答え", level: 2 },
      { type: "text", content: "自然と秘湯を求めるなら鶴の湯、歴史と町並みを重視するなら角館の古民家宿が正解だ。両方を1泊ずつ体験する2泊3日の秋田旅が、最も秋田の奥行きを味わえるプランだ。秋田新幹線を使えば東京から日帰りの距離でありながら、その別世界感は本物だ。" },
    ],
    relatedArticleSlugs: ["akita-nyuto-onsen-stay", "akita-kakunodate-bukeyashiki-walk"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "akita-budget-backpacker",
    title: "秋田をバックパック──1万5千円で乳頭温泉まで到達する節約術",
    description: "高速バス・相乗りタクシー・湯めぐり帖で秋田の秘湯を最安値で制覇する旅の記録。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "akita",
    tags: ["節約", "バックパック", "秋田", "格安旅行", "一人旅"],
    spotIds: ["nyuto-onsen", "tazawa-lake"],
    sections: [
      { type: "heading", content: "東京〜秋田 高速バスで4,000円から", level: 2 },
      { type: "text", content: "東京〜秋田の高速バスは夜行便が4,000〜6,000円（新幹線は15,000〜19,000円）。「秋田道中」「WILLER」などが運行し、早朝に秋田市内に到達できる。秋田駅から田沢湖駅は在来線でも1,500円以内で到達可能だ。" },
      { type: "heading", content: "湯めぐり帖2,000円で7宿制覇", level: 2 },
      { type: "text", content: "乳頭温泉郷の湯めぐり帖（2,000円）は1年間有効なので、日帰り入浴だけで活用しても元が取れる。乳頭温泉郷バス停から各宿まで徒歩または宿の送迎を利用すれば交通費がほぼかからない。田沢湖駅前の宿に泊まれば1泊5,000〜7,000円（素泊まり）で拠点が確保できる。" },
      { type: "heading", content: "角館は自転車レンタルで節約", level: 2 },
      { type: "text", content: "角館駅前のレンタサイクルは1日500〜800円で、武家屋敷通り・桧木内川堤を自力で巡れる。昼食は通り沿いの「角館たかみや」の稲庭うどん（800円）で十分満足できる。宿は角館の素泊まり旅館（4,000〜6,000円）を事前予約すれば、全行程2泊3日で1万5千円前後に収まる。" },
    ],
    relatedArticleSlugs: ["akita-nyuto-onsen-stay", "akita-onsen-solo-plan"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "akita-sake-brewery-tour",
    title: "秋田の地酒を巡る──新政、高清水、雪の茅舎。秋田清酒の秘密と蔵元訪問",
    description: "秋田は日本酒大国だ。全国新酒鑑評会の金賞受賞率が日本一の蔵元が集まる理由を探る。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-03-08",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "akita",
    tags: ["秋田", "日本酒", "地酒", "蔵元", "新政酒造"],
    spotIds: ["kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "秋田の水と米が作る独自の清酒文化", level: 2 },
      { type: "text", content: "秋田の日本酒は仕込み水の柔らかさと秋田酒こまち・秋田酵母の組み合わせが特徴だ。全国新酒鑑評会での金賞受賞数は数年連続で都道府県別全国一位を誇る。口当たりが柔らかく甘みのある「淡麗甘口」が秋田酒の伝統的スタイルだ。" },
      { type: "heading", content: "新政酒造──日本酒の新世界を切り開く実験蔵", level: 2 },
      { type: "text", content: "秋田市の新政酒造は、江戸時代の6号酵母を使った自然派醸造で日本酒ファンから神格化される存在だ。一般見学は行っていないが、蔵前のショールームで商品の試飲・購入ができる（在庫限りあり）。特定の酒造品は飲食店や酒屋でしか入手できず、旅の目的になりうる。" },
      { type: "heading", content: "秋田の地酒を角館の老舗酒屋で選ぶ", level: 2 },
      { type: "text", content: "角館の「北都館」や「角館地酒ラウンジ」では秋田全蔵元の代表銘柄が揃い、スタッフの説明を聞きながら好みの酒を選べる。稲庭うどんや比内地鶏と合わせるなら「雪の茅舎」の純米大吟醸が最もバランスが良い。宅配便での発送サービスも提供している。" },
    ],
    relatedArticleSlugs: ["akita-kakunodate-bukeyashiki-walk", "akita-inaniwa-udon-deep-dive"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "akita-winter-snow-trip",
    title: "秋田の冬旅行──豪雪地帯の雪景色と温泉で「冬こそ秋田」の理由を知る",
    description: "積雪1〜2mの白い世界と白濁の露天風呂。秋田の冬は繊細で過激で最も美しい季節だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "akita",
    tags: ["冬", "雪景色", "温泉", "秋田", "豪雪"],
    spotIds: ["nyuto-onsen", "kakunodate-bukeyashiki"],
    sections: [
      { type: "heading", content: "1〜2月の角館──雪の武家屋敷という非日常", level: 2 },
      { type: "text", content: "冬の角館は積雪が黒板塀の上に重なり、夏・秋とは全く異なる景観を作る。武家屋敷通りの早朝は誰もおらず、雪踏みの音だけが聞こえる。2月には「角館樺細工展示即売会」が開催され、地域伝統工芸の樺細工を見られる貴重な機会になる。" },
      { type: "heading", content: "乳頭温泉の雪中露天──一生の体験", level: 2 },
      { type: "text", content: "1〜3月の乳頭温泉郷では、ブナ林が雪で白く覆われた中に露天風呂が浮かぶ風景が見られる。外気温マイナス10度の中で白濁の湯に浸かる体験は、温泉入浴の最高形態のひとつだ。鶴の湯温泉の混浴露天（タオル入浴可）は雪見風呂として特に人気が高い。" },
      { type: "heading", content: "冬のアクセス注意点──除雪と交通情報", level: 2 },
      { type: "text", content: "冬季は乳頭温泉郷への路線バスが減便になり、悪天候時は運休することもある。田沢湖駅からの相乗りタクシー（4人乗り合い）の活用が現実的だ。レンタカーは4WDスタッドレス必須で、チェーンを持参するとより安心だ。秋田駅〜田沢湖駅間の秋田新幹線は積雪の影響を比較的受けにくい。" },
    ],
    relatedArticleSlugs: ["akita-nyuto-onsen-stay", "akita-namahage-guide"],
  },
];
