import { Article } from "@/types/article";

export const chibaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "chiba-naritasan-model-course",
    title: "成田山新勝寺の歩き方──参道から公園まで半日モデルコース",
    description: "成田空港から20分の大本山を、開門から昼まで効率よく回る全手順。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-01-18",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "chiba",
    tags: ["成田山", "寺院", "参道", "成田", "モデルコース"],
    spotIds: ["naritasan-shinshoji"],
    sections: [
      { type: "heading", content: "9時開門と同時に仁王門をくぐる", level: 2 },
      { type: "text", content: "成田山新勝寺は朝9時が正式な開門時刻だ。仁王門をくぐると正面に三重塔が現れる。石段を上がる前に左手の額堂をチェックしてほしい。奉納された絵馬や力士の手形が壁を埋め尽くし、成田山と相撲の深い関係を物語っている。本堂の不動明王に参拝した後は境内の奥、釈迦堂・光明堂・開山堂と順番に回る。このルートで約1時間。" },
      { type: "heading", content: "成田山公園で紅葉か梅を確認する", level: 2 },
      { type: "text", content: "境内東側の成田山公園は11月中旬〜下旬の紅葉と2月〜3月の梅が見頃だ。3つの池を結ぶ散策路は全長約1.5km。桂木亭という茶屋で一息ついてから参道へ下りるのが正しい動線。公園への入場は無料。" },
      { type: "heading", content: "参道の鰻は川豊本店か駿河屋か", level: 2 },
      { type: "text", content: "参道には170軒以上の鰻屋が並ぶ。川豊本店（表参道）は11時開店直後に並べば30分以内に入れる。うな重は梅¥2,900から。駿河屋は表参道の中ほどにあり、炭火のやや強めの焼きが特徴で¥3,200から。どちらも昼前後は1時間待ちになる。11時前着を死守すること。" },
      { type: "heading", content: "帰りに成田空港の国際線ターミナルを覗く", level: 2 },
      { type: "text", content: "成田駅から空港第2ビル駅まで電車で12分。出発ロビーの吹き抜けを下から眺めるだけで、世界各地へ飛び立つ旅のエネルギーが伝わってくる。展望デッキは無料で飛行機の着陸を間近で見られる。成田山と空港を組み合わせた半日旅程は千葉の最短最強コースだ。" },
    ],
    relatedArticleSlugs: ["chiba-narita-eel-gourmet", "chiba-nokogiriyama-hiking"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "chiba-narita-eel-gourmet",
    title: "成田参道の鰻を全部食べた──老舗7軒の価格・焼き・タレ比較",
    description: "170軒ひしめく成田の鰻文化。地元民が教えてくれた本物の7軒を実食レポート。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "chiba",
    tags: ["鰻", "成田", "グルメ", "老舗", "ランチ"],
    spotIds: ["naritasan-shinshoji"],
    sections: [
      { type: "heading", content: "成田の鰻が旨い理由は水にある", level: 2 },
      { type: "text", content: "成田の鰻文化は江戸時代の参拝客向けに発展した。利根川水系の清水で育てた国産鰻を備長炭で焼くスタイルが基本だ。タレは各店が代々継ぎ足している。川豊本店のタレは創業明治25年から続く甘辛のバランスが絶品で、うな重（並）¥2,900。" },
      { type: "heading", content: "穴場3軒──行列を避けるなら裏参道へ", level: 2 },
      { type: "text", content: "表参道の川豊・駿河屋と並ぶ穴場が、裏参道の菊屋・福助・小川屋だ。菊屋は予約不可だが11時台なら待ち10分以内。蒸しを長めにかける江戸前スタイルで、ふわとろの食感が得られる。うな重（中）¥3,500。" },
      { type: "heading", content: "テイクアウト鰻弁当という選択肢", level: 2 },
      { type: "text", content: "店内で食べる時間がないなら、参道各店のテイクアウト鰻弁当（¥1,800〜¥2,500）が現実的だ。成田山公園のベンチで食べれば境内の緑を眺めながら本格鰻を楽しめる。揚げ物系の屋台と組み合わせて参道グルメを完成させてほしい。" },
    ],
    relatedArticleSlugs: ["chiba-naritasan-model-course", "chiba-choshi-inubosaki-dawn"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "chiba-nokogiriyama-hiking",
    title: "鋸山ハイキング完全ガイド──地獄のぞきと百尺観音を1日で制覇",
    description: "標高329m、されど侮れない鋸山。ロープウェイと徒歩の最適ルートを解説する。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-05-03",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "chiba",
    tags: ["鋸山", "ハイキング", "地獄のぞき", "千葉", "一人旅"],
    spotIds: ["nokogiriyama"],
    sections: [
      { type: "heading", content: "ロープウェイで上り、石段で下りる", level: 2 },
      { type: "text", content: "浜金谷駅から徒歩5分のロープウェイ下駅から山頂まで約4分。往復¥700だが、上りだけ使って下りは徒歩が正解。日本寺の大仏広場・百尺観音・地獄のぞきを全て通過する下山ルートで約2時間。途中の石切場跡は圧巻で、垂直に削られた岩壁が100m以上続く。" },
      { type: "heading", content: "地獄のぞきで足がすくむ体験をする", level: 2 },
      { type: "text", content: "地獄のぞきは岩盤の先端が突き出した展望台で、真下に断崖が広がる。高所恐怖症でなくても足がすくむ感覚がある。撮影は後ろから前の人を入れる構図が迫力が出る。混雑時は10分待ちが発生するが、午前中の早い時間なら待ちゼロ。" },
      { type: "heading", content: "百尺観音と石仏群を見落とすな", level: 2 },
      { type: "text", content: "高さ31mの百尺観音は採石場の跡を利用して彫られた。採石の歴史が背景に残っており、観音像との対比が独特の迫力を生む。周辺には千五百羅漢の石仏群が点在しており、探しながら歩くと飽きない。日本寺拝観料¥700（ロープウェイ料金と別途）。" },
      { type: "heading", content: "帰りは鋸山観光の定番・東京湾フェリー", level: 2 },
      { type: "text", content: "浜金谷港から久里浜港まで東京湾フェリーが運行（約40分、¥900）。対岸の三浦半島に渡って帰路につく往路と異なるルートが旅の締めになる。海上から鋸山の険しいシルエットを見る体験も格別だ。" },
    ],
    relatedArticleSlugs: ["chiba-naritasan-model-course", "chiba-yoro-keikoku-autumn"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "chiba-yoro-keikoku-autumn",
    title: "養老渓谷の紅葉──関東最遅の絶景と粟又の滝を日帰りで楽しむ",
    description: "12月でも紅葉が残る千葉の秘境。渓谷ハイキングと温泉の最強セット。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-11-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "chiba",
    tags: ["紅葉", "養老渓谷", "千葉", "秋", "ハイキング"],
    spotIds: ["yoro-keikoku"],
    sections: [
      { type: "heading", content: "見頃は11月下旬〜12月上旬", level: 2 },
      { type: "text", content: "養老渓谷の紅葉は関東で最も遅い。都心の紅葉が終わる11月下旬からが本番で、例年のピークは12月第1週だ。小湊鐡道養老渓谷駅から粟又の滝まで徒歩20分、ハイキングコース入口まで30分歩くと渓谷美が広がり始める。" },
      { type: "heading", content: "粟又の滝はどこから見るか", level: 2 },
      { type: "text", content: "千葉最大の粟又の滝（高さ20m・幅30m）は、上部の遊歩道からと滝壺近くの2か所から見られる。水が岩盤を薄く広がりながら流れる独特の形状は、上から見るとスケールがわかる。朝9時台は観光客が少なく、滝の音だけが聞こえる時間が作れる。" },
      { type: "heading", content: "渓谷ハイキングコース2.5kmの歩き方", level: 2 },
      { type: "text", content: "弘文洞跡から粟又の滝までの渓谷遊歩道2.5kmは、沢沿いを歩く平坦なルートで約1.5時間。途中の吊り橋から渓谷全体を見下ろすと、紅葉の季節は水面に映る色彩が美しい。スニーカーで問題なく歩けるが、岩が濡れている場合があるので注意。" },
      { type: "heading", content: "ハイキング後は渓谷温泉で仕上げる", level: 2 },
      { type: "text", content: "養老渓谷周辺には日帰り入浴を受け付ける温泉宿が多い。滝見苑（日帰り¥1,500）や渓谷荘（日帰り¥1,200）が渓谷から近く、疲れた足を癒せる。アルカリ性単純泉で肌への刺激が少なく、ハイキング後の温泉として申し分ない。" },
    ],
    relatedArticleSlugs: ["chiba-nokogiriyama-hiking", "chiba-choshi-inubosaki-dawn"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "chiba-choshi-inubosaki-dawn",
    title: "犬吠埼の初日の出──本州最東端で元旦を迎えるための完全準備",
    description: "毎年5万人が集まる元旦の犬吠埼。寒さ対策・アクセス・撮影場所を全部教える。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-12-28",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "chiba",
    tags: ["犬吠埼", "初日の出", "元旦", "銚子", "灯台"],
    spotIds: ["choshi-inubosaki"],
    sections: [
      { type: "heading", content: "元旦の日の出時刻と防寒装備", level: 2 },
      { type: "text", content: "犬吠埼の元旦日の出時刻は例年6時46分前後。気温は1〜3℃で、海風で体感温度はさらに下がる。手袋・ニット帽・ウインドブレーカーは必須で、使い捨てカイロを10枚以上持参することを勧める。日の出の1時間前（5時45分）には現地入りしないと良い場所が埋まる。" },
      { type: "heading", content: "撮影場所は灯台前か岩礁か", level: 2 },
      { type: "text", content: "犬吠埼灯台（明治6年建設）の前からの日の出は、白い灯台と太陽が重なる構図が撮れる。岩礁に降りる場合は波に注意が必要だ。灯台正面のゆるやかな丘が最も安全で見晴らしがいい。元旦は灯台内部への入場（¥300）が混み合うため、日の出後に訪れた方がいい。" },
      { type: "heading", content: "銚子電鉄で来るなら終夜運転を確認", level: 2 },
      { type: "text", content: "銚子電鉄は元旦に終夜運転を行うことがある（年によって異なるため要確認）。犬吠駅から犬吠埼まで徒歩5分。乗車記念に「濡れ煎餅」を犬吠駅で購入できる。¥100〜¥180の醤油味が定番で、廃線の危機を救ったB級グルメの元祖だ。" },
      { type: "heading", content: "銚子の朝食は港直送の海鮮丼で", level: 2 },
      { type: "text", content: "日の出後の空腹を満たすなら銚子漁港そばの食堂が正解。「ウオッセ21」は7時から開いており、金目鯛の煮付け定食¥1,800やまぐろ丼¥1,500が楽しめる。銚子はサバとイワシの漁獲量が全国トップクラスで、朝の海鮮丼の鮮度は別格だ。" },
    ],
    relatedArticleSlugs: ["chiba-naritasan-model-course", "chiba-yoro-keikoku-autumn"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "chiba-choshi-seafood-tour",
    title: "銚子半島グルメ旅──醤油蔵とサバ料理と濡れ煎餅を1日で",
    description: "日本最大の醤油産地・銚子。食のレイヤーが厚い港町を1日で食べ歩く。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-07-12",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "chiba",
    tags: ["銚子", "海鮮", "醤油", "グルメ", "千葉"],
    spotIds: ["choshi-inubosaki"],
    sections: [
      { type: "heading", content: "ヤマサ醤油の工場見学から始める", level: 2 },
      { type: "text", content: "ヤマサ醤油本社工場（銚子市）では平日10時〜15時の間、無料工場見学を実施している（予約推奨）。350年の醤油醸造の歴史を映像と実物で学べる。麹の発酵臭が漂う仕込み蔵の内部は、ここでしか見られない光景だ。見学後に売店で限定の「生揚げ醤油」を購入するのが通のコース。" },
      { type: "heading", content: "港直送のサバとイワシを昼に食べる", level: 2 },
      { type: "text", content: "銚子漁港近くのウオッセ21は食堂とお土産屋が集まる市場だ。サバの刺身定食¥1,600、イワシのつみれ汁¥400が鉄板メニュー。11時開店直後が最も新鮮な魚を食べられるタイミングで、サバは脂のノリが違う。12月〜3月は特にサバの旬で予約なしでは入れない店が出る。" },
      { type: "heading", content: "犬吠埼で濡れ煎餅と夕日", level: 2 },
      { type: "text", content: "午後は銚子電鉄に乗って犬吠駅へ（¥230）。駅売店の焼きたて濡れ煎餅は外パリ中モチモチの食感で、醤油の香りが強い。夕方の犬吠埼から見る太平洋は、正面から沈む夕日ではないが、水平線が赤く染まる光景は一見の価値がある。" },
    ],
    relatedArticleSlugs: ["chiba-choshi-inubosaki-dawn", "chiba-narita-eel-gourmet"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "chiba-disney-area-tips",
    title: "ディズニー周辺に泊まる技術──オフィシャルホテルと穴場ホテルの差",
    description: "夢の国の周辺には知られていない宿泊戦略がある。全部リアルに比較した。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "chiba",
    tags: ["ディズニー", "舞浜", "ホテル", "千葉", "旅のコツ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "オフィシャルホテル3種の差を整理する", level: 2 },
      { type: "text", content: "東京ディズニーランドホテル（最安¥50,000〜）、ディズニーアンバサダーホテル（¥35,000〜）、東京ディズニーシー・ホテルミラコスタ（¥40,000〜）の3つがオフィシャルホテルだ。ミラコスタはホテル内からパークが見える唯一の選択肢で、早朝のパーク入場特典がある。費用対効果最高はアンバサダーで、立地と価格のバランスがいい。" },
      { type: "heading", content: "グッドネイバーホテルという存在", level: 2 },
      { type: "text", content: "舞浜周辺の「グッドネイバーホテル」はディズニー公認パートナーホテルで、シャトルバス無料・早期購入チケット取り扱いなどの特典がある。ヒルトン東京ベイ（¥18,000〜）、シェラトン・グランデ・トーキョーベイ（¥20,000〜）が代表格で、オフィシャルの半額以下から宿泊できる。" },
      { type: "heading", content: "穴場は新浦安・葛西エリア", level: 2 },
      { type: "text", content: "JR京葉線の新浦安駅・葛西臨海公園周辺のビジネスホテルは¥8,000〜¥12,000で舞浜まで電車10分以内だ。朝食込みのビジネスホテルに泊まって差額を食費に回す戦略は、年間何十回もリピートする地元ファンが実践している合理的な選択肢。" },
    ],
    relatedArticleSlugs: ["chiba-disney-area-gourmet", "chiba-naritasan-model-course"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "chiba-disney-area-gourmet",
    title: "舞浜エリアで食べるべきもの──パーク外の隠れた名店を全部教える",
    description: "ディズニーのご飯は高い、という問題を解決する舞浜周辺グルメ完全版。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "chiba",
    tags: ["舞浜", "グルメ", "ディズニー周辺", "節約", "千葉"],
    spotIds: [],
    sections: [
      { type: "heading", content: "イクスピアリのフードコートを活用する", level: 2 },
      { type: "text", content: "舞浜駅直結のイクスピアリには50店以上の飲食店がある。ランチタイムならカジュアルなイタリアン・ラーメン・寿司が¥1,000〜¥1,500で食べられる。パーク内より3割安い水準で、パーク入場前後どちらでも使える。フードコートは11時台に来れば並ばずに入れる。" },
      { type: "heading", content: "新浦安のニッポンバシ商店街が穴場", level: 2 },
      { type: "text", content: "JR新浦安駅から徒歩5分の商店街には地元民向けの定食屋・ラーメン屋・居酒屋が集まる。日替わり定食¥700〜¥900水準で、舞浜の相場の半分以下だ。特に地魚を使った食堂は地元でしか知られていない存在で、旅行者が入ることはほとんどない。" },
      { type: "heading", content: "帰りのディナーは葛西臨海公園で締める", level: 2 },
      { type: "text", content: "ディズニー帰りに葛西臨海公園駅周辺の海鮮居酒屋に立ち寄るルートがある。東京湾に面した立地で東京の夜景を見ながら食べる〆の刺身盛り合わせ（¥1,800〜）は、非日常感のある旅の締めになる。" },
    ],
    relatedArticleSlugs: ["chiba-disney-area-tips", "chiba-choshi-seafood-tour"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "chiba-nokogiriyama-couple",
    title: "鋸山デートコース──「地獄のぞき」から内房の夕日までの完全設計",
    description: "千葉最高の絶景スポットをカップルで1日かけて贅沢に回る全手順。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-06-14",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "chiba",
    tags: ["鋸山", "カップル", "デート", "千葉", "絶景"],
    spotIds: ["nokogiriyama"],
    sections: [
      { type: "heading", content: "午前は鋸山でスリルと絶景を共有する", level: 2 },
      { type: "text", content: "浜金谷駅到着は9時台がベスト。ロープウェイで山頂へ上り、地獄のぞきへ直行する。先端に立つ恐怖感は二人で共有する体験として最高で、後から「あそこで怖かった」という話題が生まれる。百尺観音を経由して日本寺を下山するルートは2時間弱。" },
      { type: "heading", content: "昼は浜金谷港の海鮮で絶対に海を見る", level: 2 },
      { type: "text", content: "下山後の昼食は浜金谷港近くの「ザ・フィッシュ」がおすすめ。海を見ながら金目鯛の煮付け（¥1,600）やアジフライ定食（¥1,200）を食べられる。テラス席は東京湾が一望できて、開放感が段違い。予約なしでも12時前なら待ち時間は短い。" },
      { type: "heading", content: "午後は保田の鋸南町で菜の花か桜を見る", level: 2 },
      { type: "text", content: "鋸山から南へ15分、鋸南町は2〜3月に菜の花畑が広がる。頼朝桜（河津桜系）は2月中旬〜3月上旬が見頃で、全国最速クラスの春を体験できる。菜の花と桜が同時に咲く光景は、他では見られない千葉だけの春だ。" },
    ],
    relatedArticleSlugs: ["chiba-nokogiriyama-hiking", "chiba-yoro-keikoku-autumn"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "chiba-boso-family-tour",
    title: "房総半島ファミリー旅──子どもが喜ぶ体験スポット完全ガイド",
    description: "海と山と動物が揃う房総。子連れ旅行者が選ぶべき5つの体験型スポット。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-07-30",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "chiba",
    tags: ["房総", "家族旅行", "子ども", "千葉", "体験"],
    spotIds: ["nokogiriyama", "yoro-keikoku"],
    sections: [
      { type: "heading", content: "鴨川シーワールドは朝イチが正解", level: 2 },
      { type: "text", content: "鴨川シーワールドはシャチのショーが有名だが、入場は9時開園と同時が鉄則。シャチショーは10時・13時・15時の3回で、最前列から3列目が水しぶきゾーン。子どもにとって最も記憶に残る体験のひとつで、入場料¥3,000（大人）・¥1,500（小学生）。" },
      { type: "heading", content: "マザー牧場で動物とのふれあい体験", level: 2 },
      { type: "text", content: "富津市のマザー牧場は牧羊犬ショー・乳搾り体験・羊の群れの誘導デモンストレーションが全て無料（入場料¥1,500〜）。3月〜5月の菜の花とポピーが咲く斜面は写真映えする背景になる。所要時間は4時間が目安で、ランチは牧場内のバーベキューハウスが盛り上がる。" },
      { type: "heading", content: "養老渓谷の川遊びは夏だけの特権", level: 2 },
      { type: "text", content: "7月〜8月の養老渓谷は川遊びスポットとして機能する。渓谷沿いの浅い川は流れがゆるく、小学生以下でも安心して入れる。川遊びセット（水着・サンダル）を持参して渓谷の中を歩く体験は、都市の子どもが最も感動する体験のひとつだ。" },
    ],
    relatedArticleSlugs: ["chiba-yoro-keikoku-autumn", "chiba-nokogiriyama-hiking"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "chiba-naritasan-luxury-stay",
    title: "成田で贅沢な一夜──空港直結エリアの高級旅館と懐石",
    description: "成田山参拝の後に泊まる贅沢な選択肢。旅館の選び方と懐石料理の楽しみ方。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-10-08",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "chiba",
    tags: ["成田", "高級旅館", "懐石", "贅沢旅", "千葉"],
    spotIds: ["naritasan-shinshoji"],
    sections: [
      { type: "heading", content: "成田山参道の旅館が持つ独特の格式", level: 2 },
      { type: "text", content: "成田山参道周辺には江戸時代から続く旅館が点在する。料亭旅館「横田屋」は明治創業で、成田山の定宿として格式を保っている。1泊2食付き¥35,000〜で、夕食は千葉の地魚を主役にした懐石8品構成。利根川の鰻と九十九里の地はまぐりを使った一皿は、産地の旅館でしか体験できない。" },
      { type: "heading", content: "成田空港近くの国際ホテルを選ぶ理由", level: 2 },
      { type: "text", content: "成田エクセルホテル東急・ヒルトン成田などの国際ブランドホテルは空港直結またはシャトルバスで5分以内だ。¥15,000〜¥25,000水準で、早朝フライト前日の宿泊に最適。成田山観光後の夕食は成田市内の懐石料理屋で食べてから泊まるルートが贅沢旅の完成形。" },
      { type: "heading", content: "翌朝の成田山早朝参拝で旅を締める", level: 2 },
      { type: "text", content: "成田山は6時から開門している。早朝参拝は観光客がいないため、本堂の空気感がまったく異なる。護摩祈祷（毎日9時〜）は一般参拝者も参加できる儀式で、太鼓と読経の音が本堂に響く体験は、他の観光では得られない時間だ。" },
    ],
    relatedArticleSlugs: ["chiba-naritasan-model-course", "chiba-narita-eel-gourmet"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "chiba-solo-boso-route",
    title: "房総一人旅ルート──電車で行ける内房・外房の2泊3日",
    description: "車なしで房総半島を縦断できる。JR・私鉄・フェリーを組み合わせた自由旅程。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "chiba",
    tags: ["一人旅", "房総", "電車旅", "千葉", "2泊3日"],
    spotIds: ["nokogiriyama", "yoro-keikoku", "choshi-inubosaki"],
    sections: [
      { type: "heading", content: "1日目：内房ルート（鋸山〜館山）", level: 2 },
      { type: "text", content: "東京駅9時発の内房線特急「さざなみ」で浜金谷へ（約1時間20分）。鋸山を午前中に制覇して昼食は浜金谷港で。午後に館山へ移動し、館山城と鶴ヶ谷海岸で夕日を見る。宿は館山のゲストハウスで¥4,000〜。" },
      { type: "heading", content: "2日目：外房ルート（勝浦〜銚子）", level: 2 },
      { type: "text", content: "館山から外房線で勝浦へ（約1時間）。勝浦タンタンメン（¥800〜）で昼食。午後は銚子電鉄で犬吠埼へ向かい、灯台と太平洋を堪能する。銚子の海鮮居酒屋で夕食¥2,500前後が最高のコスパ。" },
      { type: "heading", content: "3日目：養老渓谷で〆る", level: 2 },
      { type: "text", content: "銚子から小湊鐡道経由で養老渓谷へ（乗り換え含め約2時間）。渓谷ハイキング2時間、温泉入浴1時間で身体をリセットして帰路へ。「房総横断乗車券」（¥3,000前後）を使えばルート内の電車が乗り放題になりコストを抑えられる。" },
    ],
    relatedArticleSlugs: ["chiba-nokogiriyama-hiking", "chiba-choshi-inubosaki-dawn"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "chiba-kujukuri-beach",
    title: "九十九里浜を走る──60kmの直線海岸と地はまぐりの焼き台",
    description: "日本最長クラスの砂浜と海産物の聖地。サーフィンとハマグリの両立を解説。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "chiba",
    tags: ["九十九里", "海水浴", "はまぐり", "夏", "千葉"],
    spotIds: [],
    sections: [
      { type: "heading", content: "60kmの砂浜でサーフィンを始める", level: 2 },
      { type: "text", content: "九十九里浜は関東最大のサーフスポットで、一宮〜飯岡まで数十か所の海水浴場・サーフポイントが続く。初心者向けサーフィン体験は¥6,000〜でボード・ウェットスーツ込み。7〜8月は講習スクールが各ポイントに常駐しており、当日申し込みで参加できる。" },
      { type: "heading", content: "地はまぐりの焼き台体験は絶対外せない", level: 2 },
      { type: "text", content: "九十九里の海岸沿いには地はまぐりを浜で焼いて食べる「はまぐり焼き」の屋台が並ぶ。大粒の地はまぐり1kg¥1,500〜¥2,000を七輪で焼いて食べるスタイルは、夏の千葉でしかできない体験だ。醤油を少し垂らして口を開けた瞬間が最高のタイミング。" },
      { type: "heading", content: "帰りは東金道路でイチゴ狩りも選択肢", level: 2 },
      { type: "text", content: "九十九里から東金方面に向かうとイチゴ農園が点在する（1月〜5月が旬）。入園料+食べ放題¥1,500〜¥2,000で、夏以外の九十九里旅行の帰りに組み合わせると旅程が濃くなる。JRなら千葉駅から外房線・東金線でアクセスできる。" },
    ],
    relatedArticleSlugs: ["chiba-boso-family-tour", "chiba-choshi-seafood-tour"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "chiba-nokogiriyama-budget",
    title: "鋸山を¥2,000以下で楽しむ──節約派のための完全プラン",
    description: "ロープウェイも鰻も使わない。本当にお金をかけずに鋸山を満喫する方法。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-04-22",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "chiba",
    tags: ["鋸山", "節約", "日帰り", "千葉", "ハイキング"],
    spotIds: ["nokogiriyama"],
    sections: [
      { type: "heading", content: "電車はフリーきっぷで最安化する", level: 2 },
      { type: "text", content: "東京駅からの「内房線休日おでかけパス」（¥2,670）を使えば浜金谷まで往復できる。通常運賃往復¥4,000以上と比較すると1,300円以上安い。土日祝限定で、当日駅の券売機で購入できる。" },
      { type: "heading", content: "ロープウェイを使わず徒歩で登る", level: 2 },
      { type: "text", content: "ロープウェイ往復¥700をカットするために登山口（浜金谷駅から徒歩15分）から歩いて登る。登りは約1時間で、下山は日本寺経由で2時間。日本寺の拝観料¥700は支払うが、それ以外の追加費用はゼロ。地獄のぞきも百尺観音も拝観料に含まれている。" },
      { type: "heading", content: "昼食はコンビニ弁当を山頂展望台で食べる", level: 2 },
      { type: "text", content: "浜金谷駅前のコンビニで弁当を購入してから登山すれば、山頂展望台で東京湾を見ながら昼食が取れる。¥600〜¥800の弁当が、東京湾のパノラマを背景に格上げされる。1日の総コストをフリーきっぷ+拝観料+弁当で¥2,000以下に抑えられる。" },
    ],
    relatedArticleSlugs: ["chiba-nokogiriyama-hiking", "chiba-solo-boso-route"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "chiba-yoro-keikoku-onsen",
    title: "養老渓谷温泉のすべて──泉質・宿・日帰り湯を徹底比較",
    description: "関東でも知る人ぞ知る養老渓谷の温泉。どの湯が本当によいか全部入って確かめた。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-12-05",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "chiba",
    tags: ["養老渓谷", "温泉", "日帰り湯", "千葉", "紅葉"],
    spotIds: ["yoro-keikoku"],
    sections: [
      { type: "heading", content: "養老渓谷温泉は塩分濃度が高い特異な泉質", level: 2 },
      { type: "text", content: "養老渓谷の温泉はナトリウム・炭酸水素塩・塩化物泉に分類される。塩分濃度が高いため保温効果が高く、湯冷めしにくい。黄褐色の湯色は鉄分由来で、白いタオルが色落ちすることがある。11月〜12月の紅葉シーズンは宿の需要が高まり、週末の日帰り受け入れが制限される宿もある。" },
      { type: "heading", content: "日帰り湯のコスパ最強は滝見苑", level: 2 },
      { type: "text", content: "滝見苑の日帰り入浴（¥1,500・10時〜14時）は渓谷を見下ろす露天風呂が売りだ。粟又の滝に最も近い宿で、ハイキング後にそのまま温泉に直行できる動線が完璧。昼食セット（¥1,500追加）で猪鍋定食を頼むと、野生味のある千葉の秋を完全に体験できる。" },
      { type: "heading", content: "宿泊なら渓谷荘が価格と品質の最高点", level: 2 },
      { type: "text", content: "渓谷荘は1泊2食¥16,000〜で、夕食に千葉の地魚と猪汁が出る。全室渓谷向きの和室で、夜に窓を開けると川音だけが聞こえる。露天風呂は24時まで開放されており、深夜の渓谷の星空と湯の組み合わせは千葉でここでしか体験できない静寂だ。" },
    ],
    relatedArticleSlugs: ["chiba-yoro-keikoku-autumn", "chiba-nokogiriyama-hiking"],
  },
];
