import { Article } from "@/types/article";

export const ehimeArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "ehime-dogo-onsen-night",
    title: "道後温泉、夜の過ごし方──千と千尋の元ネタを夜のライトアップで確認する",
    description: "道後温泉本館のライトアップは日没から始まる。昼間とは別の建物が夜の商店街に浮かび上がる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "ehime",
    tags: ["道後温泉", "夜景", "ライトアップ", "松山", "愛媛"],
    spotIds: ["dogo-onsen"],
    sections: [
      { type: "heading", content: "日没直後30分が撮影のゴールデンタイム", level: 2 },
      { type: "text", content: "道後温泉本館のライトアップは日没とともに始まる。空の色が深いブルーに移行する「マジックアワー」の時間帯に本館正面に立つと、橙色の建物と青い空のコントラストが完璧な写真を生む。三脚を持参した写真愛好家が同じタイミングで集まるが、正面の人通りは翌朝まで絶えない。" },
      { type: "spot-card", content: "dogo-onsen" },
      { type: "heading", content: "入浴後に道後商店街でみかんジュースを飲む", level: 2 },
      { type: "text", content: "道後温泉本館（改修中のため飛鳥乃湯泉が主役）での入浴後、道後商店街を歩く。「蛇口からみかんジュース」が出る自販機スポットは今も人気で、愛媛県産100%のみかんジュースが200円で飲める。温泉上がりのほてりにみかんジュースの酸味が合う。夜の商店街は浴衣姿の宿泊客と地元民が混在し、観光地と日常生活の境界が曖昧になる独特の空気がある。" },
      { type: "heading", content: "坊っちゃん列車で温泉へのアプローチを演出する", level: 2 },
      { type: "text", content: "松山市駅から道後温泉まで蒸気機関車を模した「坊っちゃん列車」が走っている（1日数便）。夏目漱石の小説「坊っちゃん」の世界観に乗り込む演出として最高で、車内でもみかんジュースが購入できる。通常の路面電車（市電）は20分間隔で頻発しており、坊っちゃん列車を撮影してから市電で向かうのが賢い使い方だ。" },
    ],
    relatedArticleSlugs: ["ehime-matsuyama-castle-spring", "ehime-model-course-2days"],
  },

  // ── 2 ──────────────────────────────────────
  {
    slug: "ehime-matsuyama-castle-spring",
    title: "松山城の春──200本の桜と現存天守が重なる、日本一美しい城景のひとつ",
    description: "現存12天守の中で桜との組み合わせが最も絵になる松山城。4月上旬の1週間が最高の瞬間だ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "ehime",
    tags: ["松山城", "桜", "春", "現存天守", "愛媛"],
    spotIds: ["matsuyama-castle"],
    sections: [
      { type: "heading", content: "4月上旬の1週間だけ「桜城」になる", level: 2 },
      { type: "text", content: "松山城周辺の約200本の桜は4月上旬に一斉に開花する。ロープウェイ乗り場から城山を見上げると、白い天守と桜のピンクが重なる景観が広がる。桜の時期は夜間ライトアップも行われ、昼とはまったく異なる幻想的な城と桜の世界が現れる。松山市のサイトが公開する「桜開花情報」を事前にチェックして日程を組むことを推奨する。" },
      { type: "spot-card", content: "matsuyama-castle" },
      { type: "heading", content: "天守最上階からの眺望が圧巻", level: 2 },
      { type: "text", content: "松山城天守の最上階からは松山市街・松山平野・瀬戸内海が360度見渡せる。晴れた日は石鎚山（西日本最高峰）の白い山頂まで見える。現存天守の構造として「連立式」は松山城だけで、大天守・小天守・二重櫓が廊下で繋がる複雑な内部は迷宮感があって楽しい。城内の解説展示は愛媛の近世史を30分でコンパクトに知れる内容で充実している。" },
      { type: "heading", content: "リフトで上がってロープウェイで下りる", level: 2 },
      { type: "text", content: "城山への上り方は2つある。リフトは体が外に出るため桜の季節は花の中を通り抜ける感覚で最高。ロープウェイはゴンドラから見下ろす市街の眺めが良い。往復同じ方法より、リフトで上がってロープウェイで下りる（またはその逆）を選ぶと、両方の体験ができる。桜期の混雑時はロープウェイが行列になることが多く、リフトのほうが待ち時間が短い。" },
    ],
    relatedArticleSlugs: ["ehime-dogo-onsen-night", "ehime-model-course-2days"],
  },

  // ── 3 ──────────────────────────────────────
  {
    slug: "ehime-shimanami-cycling-imabari",
    title: "しまなみ海道・今治スタートの全攻略──来島海峡大橋から見る夕日で旅が完結する",
    description: "今治側から入るしまなみ海道は、世界最強の自転車聖地への正規入口だ。最初の橋の夕景で、旅の本気度が変わる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "ehime",
    tags: ["しまなみ海道", "サイクリング", "今治", "来島海峡", "愛媛"],
    spotIds: ["shimanami-imabari"],
    sections: [
      { type: "heading", content: "サンライズ糸山から夕日を見る──計算通りの完璧な景色", level: 2 },
      { type: "text", content: "JR今治駅からバスでサンライズ糸山（今治市サイクリングターミナル）へ。展望台から来島海峡大橋（世界初の三連吊り橋）と西日が重なる時間帯（日没1時間前）が最高の撮影チャンスだ。橋の全体が見え、下の急流と夕焼けの組み合わせは四国の夕景の最高峰のひとつ。この場所で翌日のサイクリングへの期待が最高潮になる。" },
      { type: "spot-card", content: "shimanami-imabari" },
      { type: "heading", content: "今治タオルのファクトリー見学は予約必須", level: 2 },
      { type: "text", content: "今治市は日本最大のタオル産地で、今治ブランドのタオルは品質の証として全国的な知名度を持つ。「今治タオル本店」「タオルの今治本店」では直売と工場見学（要予約）ができる。製造工程を見た後にタオルを触ると、価格の正当性が体感できる。タオルは荷物にならない土産として最適で、種類の豊富さに選ぶのに時間がかかる。" },
      { type: "heading", content: "今治城と焼き鳥で1日を締める", level: 2 },
      { type: "text", content: "今治城は海に面した「海城」で、堀に海水が引き込まれている珍しい構造を持つ。城内から来島海峡大橋が見える展望台は穴場的なビューポイントだ。今治の夜のもう一つの名物は焼き鳥。今治焼き鳥は「鉄板焼き」という独特のスタイルで、鶏肉を串のまま鉄板に押しつけて焼く。皮の脂がじゅっと鉄板に落ちる音が食欲を最大にする。" },
    ],
    relatedArticleSlugs: ["ehime-shimanami-full-ride", "ehime-model-course-2days"],
  },

  // ── 4 ──────────────────────────────────────
  {
    slug: "ehime-shimanami-full-ride",
    title: "しまなみ海道70kmを1日で走る──プロが組んだ体力別3コースと補給地点",
    description: "全長70kmのしまなみ海道を1日で走りきるのは普通の体力で可能か。3コース設計と補給情報を完全公開。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "ehime",
    tags: ["しまなみ海道", "サイクリング", "70km", "ルート", "愛媛"],
    spotIds: ["shimanami-imabari"],
    sections: [
      { type: "heading", content: "コースA：今治→尾道フル70km（6〜8時間）", level: 2 },
      { type: "text", content: "コースAは今治出発の70kmフルライド。獲得標高は約500mで、橋のアプローチ部分が唯一の登坂。サイクリスト向けに整備されたブルーラインに沿って走れば迷わない。今治7時出発・尾道15時着が標準的な所要時間。途中の因島・向島で昼食休憩を入れ、宮島に立ち寄る時間も確保できる。体力に自信がある人の計画向け。" },
      { type: "heading", content: "コースB：大三島だけのプチしまなみ（3〜4時間）", level: 2 },
      { type: "text", content: "今治から3つ目の大三島だけを往復するコースBは、しまなみの核心を30kmで体験できる入門版。大山祇神社（国宝の武具コレクション）と多々羅大橋展望台を組み合わせて、今治に戻る。電動アシスト自転車なら体力に関係なく楽しめる。サンライズ糸山でレンタルして往復する場合は4〜5時間の計画でゆとりがある。" },
      { type: "spot-card", content: "shimanami-imabari" },
      { type: "heading", content: "補給の鉄則：自販機・コンビニ・道の駅の位置を事前把握", level: 2 },
      { type: "text", content: "しまなみ海道の各島には道の駅と自販機が設置されており、補給間隔が開いても約20km以内に必ずある。大三島の「道の駅 多々羅しまなみ公園」は補給と展望を兼ね備えた最重要ポイント。レモン塩ラーメンは大三島の名物で、サイクリストが行列を作る。水分は750ml以上を常時携帯し、夏期は塩飴を合わせて電解質補給を忘れずに。" },
    ],
    relatedArticleSlugs: ["ehime-shimanami-cycling-imabari", "ehime-model-course-2days"],
  },

  // ── 5 ──────────────────────────────────────
  {
    slug: "ehime-mikan-culture",
    title: "愛媛みかんの全貌──品種・産地・時期で変わる味の違いを生産者から学ぶ",
    description: "愛媛みかんは一種類ではない。10月から3月まで品種が切り替わり続ける柑橘王国の深さを解説する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-12-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "ehime",
    tags: ["みかん", "柑橘", "グルメ", "愛媛", "農業体験"],
    spotIds: [],
    sections: [
      { type: "heading", content: "愛媛が全国1位のみかん産地である理由", level: 2 },
      { type: "text", content: "愛媛は温州みかんの全国生産量第1位（和歌山と毎年競っている）の産地。瀬戸内の急傾斜地に段々畑が広がり、日当たりと水はけの良さが高品質な柑橘を生む。しかし愛媛の柑橘は温州みかんだけではない。清見・デコポン・せとか・河内晩柑・紅まどんな・愛媛果試28号など、10月〜翌年5月まで品種がリレーする。" },
      { type: "heading", content: "11〜12月：極早生〜中生みかんの旬", level: 2 },
      { type: "text", content: "11月から12月は一般的な温州みかんの旬。この時期に愛媛の直売所を訪れると、同じ「みかん」が農園ごとに全く違う甘み・酸味・香りを持っていることがわかる。産地直送のみかん（1kg300〜500円）は東京のスーパーで買うそれとは別の食べ物だと感じる。みかん狩り体験は10月下旬〜12月が盛んで、農園の傾斜地を歩きながら採る体験は予約なしでも受け入れる農園が多い。" },
      { type: "heading", content: "1〜3月：高級柑橘「紅まどんな」と「せとか」の季節", level: 2 },
      { type: "text", content: "「紅まどんな」は愛媛オリジナル品種で、とろけるような食感と濃い甘みが特徴。1玉200〜400円の高級柑橘だが、ゼリーのような食感は体験する価値がある。「せとか」は香りが強く、日本で最もジューシーな柑橘のひとつ。2月〜3月が旬の「河内晩柑」は爽やかな酸味で、夏みかんの雰囲気を持ちながらマイルドな味わいだ。" },
    ],
    relatedArticleSlugs: ["ehime-tai-meshi-guide", "ehime-model-course-2days"],
  },

  // ── 6 ──────────────────────────────────────
  {
    slug: "ehime-tai-meshi-guide",
    title: "愛媛の鯛めし──宇和島の「卵かけごはん風」vs 松山の「炊き込み」、どちらが本物か",
    description: "愛媛には二種類の鯛めしがある。卵かけごはんのように生鯛を食べる宇和島流と、丸ごと炊き込む松山流。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "ehime",
    tags: ["鯛めし", "グルメ", "宇和島", "松山", "愛媛"],
    spotIds: [],
    sections: [
      { type: "heading", content: "宇和島流：生の鯛刺しを卵醤油に絡めてご飯にかける", level: 2 },
      { type: "text", content: "宇和島の鯛めしは、薄切りにした生鯛の刺身を、卵・醤油・みりんを混ぜたタレに絡めてご飯の上にのせる料理だ。宇和島が真珠・鯛養殖の産地であり、漁師が船の上で食べた「漁師飯」が起源とされる。生の鯛の甘みと卵のとろみがご飯に混ざる食感は、TKG（卵かけごはん）と刺身丼の交点にある独創的な料理だ。" },
      { type: "heading", content: "松山流：鯛丸ごとをご飯と炊く豪快な炊き込み", level: 2 },
      { type: "text", content: "松山の鯛めしは、頭ごとの鯛を昆布だしと醤油で炊いたご飯に乗せる炊き込みスタイル。鯛の旨みがご飯全体に染み込み、ふっくらした身と香ばしいあごが食べられる。鯛はほぐしてご飯に混ぜながら食べる。松山市内の老舗料亭やみかん鯛を使ったランチコースで提供されることが多い。" },
      { type: "heading", content: "どちらを食べるべきか──旅のスケジュールで決める", level: 2 },
      { type: "text", content: "宇和島流は漁師食・ランチ向け・リーズナブル（1,200〜1,800円）。宇和島市街の食堂で気軽に食べられる。松山流は旅館・料亭の夕食や昼のコースで提供される格式高い料理（2,000〜5,000円）。両方を食べ比べるなら、昼に宇和島スタイルのランチ、夜に松山料亭の夕食という計画が理想的だ。" },
    ],
    relatedArticleSlugs: ["ehime-mikan-culture", "ehime-model-course-2days"],
  },

  // ── 7 ──────────────────────────────────────
  {
    slug: "ehime-imabari-towel-tour",
    title: "今治タオル工場見学──白いタオルの品質を目で見て、手で確かめる産業観光",
    description: "今治タオルは日本一の品質ブランドだ。なぜそう言い切れるのか、製造現場を見れば答えが出る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "ehime",
    tags: ["今治タオル", "工場見学", "今治", "産業観光", "愛媛"],
    spotIds: ["shimanami-imabari"],
    sections: [
      { type: "heading", content: "今治タオルブランド認証の厳しさ", level: 2 },
      { type: "text", content: "今治タオルのブランドマーク取得には独自の基準がある。吸水性試験（水中に落として5秒以内に沈む）・安全基準（禁止成分不使用）・今治産（縫製まで今治市内）の3条件が必要だ。この厳しさが「今治タオル」の価値を支えており、海外の有名ホテルが今治タオルを指定するのはこの品質保証によるものだ。" },
      { type: "heading", content: "工場見学で見るべき3つのポイント", level: 2 },
      { type: "text", content: "今治市内のタオル工場見学では、①整経（縦糸の整列）②製織（横糸を通す工程）③仕上げ（ボリュームを出す乾燥）の3段階が見学の核心だ。自動織機が動く音と速さのギャップ（タオル1枚に7〜8分かかる精密さ）が見学者を驚かせる。ブランケットや浴衣用の厚手タオルの製造ラインを見ると、一枚の重みがまるで変わる。" },
      { type: "spot-card", content: "shimanami-imabari" },
      { type: "heading", content: "アウトレットで割安購入する方法", level: 2 },
      { type: "text", content: "今治タオルのファクトリーアウトレットは市内数カ所にある。検品ではねられたB品（見た目では区別がつかない場合が多い）が定価の30〜50%オフで購入できる。バスタオル1枚2,000〜4,000円、フェイスタオル500〜1,500円が目安。土産として持ち帰れる量に限界があるが、今治タオルは軽く薄いため、思いのほか多く持ち帰れる。" },
    ],
    relatedArticleSlugs: ["ehime-shimanami-cycling-imabari", "ehime-model-course-2days"],
  },

  // ── 8 ──────────────────────────────────────
  {
    slug: "ehime-model-course-2days",
    title: "愛媛2泊3日モデルコース──道後温泉・松山城・しまなみ・みかんを全部回る",
    description: "愛媛の観光資源は松山に集中しているように見えて、実は海道から山奥まで広く分布している。3日間の最適解。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "ehime",
    tags: ["モデルコース", "2泊3日", "愛媛", "松山", "しまなみ"],
    spotIds: ["dogo-onsen", "matsuyama-castle", "shimanami-imabari"],
    sections: [
      { type: "heading", content: "1日目：松山城と道後温泉のW体験", level: 2 },
      { type: "text", content: "松山空港または松山駅着後、ロープウェイで松山城へ（所要90分）。下山後、市電で道後温泉へ移動（20分）。温泉に入り（飛鳥乃湯泉、本館は改修中）、浴衣姿で商店街を歩いて夕食。道後温泉の旅館または松山市内のホテルに宿泊。夜の本館ライトアップを鑑賞してから就寝する。" },
      { type: "spot-card", content: "dogo-onsen" },
      { type: "heading", content: "2日目：今治としまなみ海道へ", level: 2 },
      { type: "text", content: "特急「いしづち」でJR今治駅へ（約35分）。タオル工場見学（予約済み）後、サンライズ糸山でレンタサイクルを借りてプチしまなみ（大三島往復）を体験。夕方のフェリーまたは特急で松山に戻る。夕食は松山市内で鯛めし（松山流）の夕食コースを楽しむ。" },
      { type: "spot-card", content: "shimanami-imabari" },
      { type: "heading", content: "3日目：みかん農園体験と松山観光の深堀り", level: 2 },
      { type: "text", content: "松山市近郊の柑橘農園でみかん（または紅まどんな）の収穫体験（10月〜2月が旬）。試食で食べ比べた後、道後温泉本館外観を再鑑賞してから空港へ。手荷物には今治タオル・宇和島の鯛みりん干し・みかんジュースセットを詰めると、愛媛の全要素が凝縮した土産になる。" },
    ],
    relatedArticleSlugs: ["ehime-dogo-onsen-night", "ehime-shimanami-cycling-imabari"],
  },

  // ── 9 ──────────────────────────────────────
  {
    slug: "ehime-couple-dogo-stay",
    title: "道後温泉カップル滞在記──二人でゆっくり過ごす温泉街の24時間",
    description: "道後温泉は何を急ぐ必要もない。温泉・歩く・食べる・また温泉。この循環が旅の正解だ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-25",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "ehime",
    tags: ["カップル", "道後温泉", "温泉宿", "松山", "愛媛"],
    spotIds: ["dogo-onsen"],
    sections: [
      { type: "heading", content: "午後チェックインで温泉時間を最大化する", level: 2 },
      { type: "text", content: "道後温泉の旅館は15時前後チェックインが多い。松山市内観光を午前中に終え、14時ごろ道後温泉エリアに入ると商店街の人通りがまだ少ない。荷物を預けてから商店街を散策し、温泉街の空気をゆっくり吸う。宿のチェックイン後に大浴場に浸かり、夕食まで浴衣で縁側に座る時間が道後温泉滞在の本質だ。" },
      { type: "spot-card", content: "dogo-onsen" },
      { type: "heading", content: "夕食は愛媛の旬食材を取り入れたコース料理", level: 2 },
      { type: "text", content: "道後温泉の旅館夕食は松山鯛・宇和島産の海鮮・愛媛のみかんを使ったデザートが定番の流れ。季節によってハモ・鯛しゃぶ・松山アゲと呼ばれる厚揚げ豆腐が加わる。食後は宿内の露天風呂に再入浴し、ライトアップされた本館の外観を間近で眺める夜の散歩でしめる。旅館選びのポイントは本館から徒歩3分以内の立地かどうかだ。" },
      { type: "heading", content: "翌朝：早朝の本館前で並ばずに写真を撮る", level: 2 },
      { type: "text", content: "道後温泉本館前は朝6時台は驚くほど人が少ない。日本建築の美しい外観を独占する気分で写真が撮れる最後のチャンスがここにある。朝食後にチェックアウトして、松山城の桜（4月）またはみかん農園（11〜12月）に向かう。温泉の余韻を体に残したまま次の目的地に向かう幸福感が道後温泉滞在の醍醐味だ。" },
    ],
    relatedArticleSlugs: ["ehime-dogo-onsen-night", "ehime-model-course-2days"],
  },

  // ── 10 ──────────────────────────────────────
  {
    slug: "ehime-solo-cycling-shimanami",
    title: "一人でしまなみ海道を走る──途中離脱OKの自由なサイクリングの設計",
    description: "一人旅でしまなみ海道を走る最大の自由は「途中でやめてもいい」こと。その気楽さが島旅の質を上げる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "ehime",
    tags: ["一人旅", "サイクリング", "しまなみ海道", "自由旅", "愛媛"],
    spotIds: ["shimanami-imabari"],
    sections: [
      { type: "heading", content: "途中離脱の選択肢がある安心感", level: 2 },
      { type: "text", content: "しまなみ海道の各島にはバスやフェリーがある程度運航しており、体力が尽きた場合にサイクリングを打ち切って帰ることができる。自転車はターミナル間の乗り捨てが可能（追加料金なし）なため、今治を出発して大三島まで走り、そこから自転車を返してバスで帰るという判断が当日でも取れる。この柔軟性が一人サイクリングを安全にする。" },
      { type: "spot-card", content: "shimanami-imabari" },
      { type: "heading", content: "島の人との偶発的な交流が一人旅の本質", level: 2 },
      { type: "text", content: "しまなみ海道の島々は人口が少なく、観光客と地元民の距離が近い。道の駅で休んでいると話しかけてくれる農家のおじさん、手作りのみかんジュースをご馳走してくれる民宿の奥さん。グループ旅行では入り込めない偶発的な交流が一人旅では日常的に起こる。この種の人との繋がりが、一人旅の記憶を他と代えがたいものにする。" },
      { type: "heading", content: "大山祇神社で旅の意味が変わる", level: 2 },
      { type: "text", content: "大三島にある大山祇神社は全国の武将が戦勝祈願に訪れた古社で、国宝・重要文化財の武具コレクションが圧巻。源義経・北条時政が奉納した鎧・刀剣が保存されている。サイクリングの体の疲れと、1,000年の歴史を持つ神社の静寂が交差する大三島の午後は、一人旅でしか感じられない旅の深さがある。" },
    ],
    relatedArticleSlugs: ["ehime-shimanami-cycling-imabari", "ehime-shimanami-full-ride"],
  },

  // ── 11 ──────────────────────────────────────
  {
    slug: "ehime-budget-matsuyama",
    title: "松山を安く旅する──市電1日券と100円商店街で完成する格安松山",
    description: "松山は市電があれば主要観光地をほぼカバーできる。1日600円の乗り放題で1万円以内の松山旅を設計する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "ehime",
    tags: ["節約旅", "松山", "市電", "格安", "愛媛"],
    spotIds: ["matsuyama-castle", "dogo-onsen"],
    sections: [
      { type: "heading", content: "市電1日乗車券600円で全制覇", level: 2 },
      { type: "text", content: "松山市内の主要観光地を結ぶ路面電車（市電）の1日乗車券は600円（1回180円なので4回乗れば元が取れる）。松山城ロープウェイ前・道後温泉の2カ所が主要目的地で、この往復だけで600円相当になる。さらに大街道商店街・松山市駅周辺を散策するなら、実質無制限に使える1日券の価値が上がる。" },
      { type: "spot-card", content: "matsuyama-castle" },
      { type: "heading", content: "道後温泉の入浴は460円の「霊の湯」で十分", level: 2 },
      { type: "text", content: "道後温泉の入浴には複数の料金コースがある。最安値の「神の湯」は460円（大人）で、一般浴場として十分に良質な湯に入れる。高い料金コース（1,250円〜）は休憩室・お茶・お菓子が付いてくるが、入浴だけが目的なら最安コースで松山の名湯を体験できる。入浴後のみかんジュース（200円）を加えても660円の温泉体験だ。" },
      { type: "heading", content: "大街道商店街の食べ歩きで昼食を安く済ませる", level: 2 },
      { type: "text", content: "大街道のアーケード商店街には地元向けの食堂・惣菜店が多い。鯛飯のランチセット800円、鯛じゃこ天の立ち食い150円、みかんソフトクリーム200円。これらを組み合わせると愛媛グルメを1,200円で体験できる計算になる。商店街の端にある「松山銘菓 一六タルト」の試食は無料で、本場タルトの上品な甘みを手軽に確認できる。" },
    ],
    relatedArticleSlugs: ["ehime-model-course-2days", "ehime-dogo-onsen-night"],
  },

  // ── 12 ──────────────────────────────────────
  {
    slug: "ehime-luxury-dogo-suite",
    title: "道後温泉の贅沢スイート体験──歴史ある旅館で過ごす、人生で一度の夜",
    description: "道後温泉には1泊5〜10万円の高級旅館がある。その価格に見合う体験がそこにあるのかを確かめてきた。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "ehime",
    tags: ["贅沢旅", "道後温泉", "高級旅館", "スイート", "愛媛"],
    spotIds: ["dogo-onsen"],
    sections: [
      { type: "heading", content: "露天風呂付き客室の選び方", level: 2 },
      { type: "text", content: "道後温泉の高級旅館で最も価値が高い客室は「露天風呂付き離れ」。本館から数分の中庭の一角に独立した客室があり、自分だけの檜または陶器浴槽で温泉を楽しめる。温泉街の音がかすかに聞こえる距離感が、旅館に泊まる贅沢の本質だ。1泊2食で8〜15万円の価格帯が相場で、週末より平日が2〜3割安く確保しやすい。" },
      { type: "spot-card", content: "dogo-onsen" },
      { type: "heading", content: "仲居さんのもてなしが「価格の理由」を説明する", level: 2 },
      { type: "text", content: "高級旅館の滞在で感じる価値の多くは、仲居さんの対応に宿っている。チェックイン時の荷物対応から夕食の給仕、翌朝の見送りまで、すべてが自然で温かく、気配りが感じられる。ビジネスホテルとの最大の差はここにある。また温泉への案内・松山の観光アドバイスなど、地元情報の精度が公式ガイドブックを上回ることが多い。" },
      { type: "heading", content: "翌朝は旅館専用の早朝入浴で誰もいない大浴場を独占", level: 2 },
      { type: "text", content: "宿泊者特権として、朝6時開館の大浴場に宿泊者しかいない時間帯がある。白いタイルの大浴場に早朝の光が差し込む朝は、道後温泉の歴史3,000年分の厚みが一人の体に注がれる感覚がある。朝食は8時から。愛媛の鯛・みかん・じゃこ天が並ぶ和朝食の後、ゆっくりと旅館を出る。急ぐ理由のない朝が高級旅館の本質だ。" },
    ],
    relatedArticleSlugs: ["ehime-dogo-onsen-night", "ehime-couple-dogo-stay"],
  },

  // ── 13 ──────────────────────────────────────
  {
    slug: "ehime-family-shimanami",
    title: "子連れしまなみ海道──子どもが喜ぶプチサイクリングと大山祇神社の冒険",
    description: "70km全部走る必要はない。子どもとのしまなみは2〜3時間で十分に充実した体験になる設計がある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "ehime",
    tags: ["子連れ", "しまなみ海道", "サイクリング", "家族旅", "愛媛"],
    spotIds: ["shimanami-imabari"],
    sections: [
      { type: "heading", content: "子ども用自転車とチャイルドシートの手配", level: 2 },
      { type: "text", content: "サンライズ糸山（今治）ではチャイルドシート付き電動自転車・タンデム自転車・子ども用自転車が借りられる。未就学児はチャイルドシートで親の自転車に同乗、小学生低学年は子ども用自転車で自走が現実的な目安だ。電動アシスト付きを選べば坂でも親が体力切れにならない。来島海峡大橋の下を通るルートは平坦で子どもが飽きずに走れる。" },
      { type: "spot-card", content: "shimanami-imabari" },
      { type: "heading", content: "大三島の大山祇神社で宝物館に入る", level: 2 },
      { type: "text", content: "大山祇神社の宝物館は日本の武具の宝庫。源義経が着たとされる鎧が展示されており、歴史が好きな子どもには最高の社会科体験になる。「本物の昔の武士の鎧がある」という事実が子どもの目を輝かせる。神社自体は樹齢2,600年の大楠が存在し、その大きさを子どもと一緒に両手で測ろうとすると笑いが起きる。" },
      { type: "heading", content: "帰りは大三島の海鮮でビタミン補給", level: 2 },
      { type: "text", content: "大三島の「道の駅 多々羅しまなみ公園」には瀬戸内の海鮮が並ぶ売店がある。子どもに人気はタコ唐揚げ（400円〜）と鯛バーガー（600円〜）。親はレモン塩ラーメンか鯛飯。海を眺めながら食べるテラス席が気持ちよく、サイクリングの疲れを忘れる昼食時間になる。帰りは今治駅から特急で松山に戻れる。" },
    ],
    relatedArticleSlugs: ["ehime-shimanami-cycling-imabari", "ehime-model-course-2days"],
  },

  // ── 14 ──────────────────────────────────────
  {
    slug: "ehime-matsuyama-soseki",
    title: "夏目漱石の「坊っちゃん」を歩く──松山が小説の舞台である痕跡を追う",
    description: "「坊っちゃん」は松山の話だ。松山の旅人はすべて、知らないうちに漱石の主人公の足跡を歩いている。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-08-28",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "ehime",
    tags: ["夏目漱石", "坊っちゃん", "文学", "松山", "愛媛"],
    spotIds: ["dogo-onsen", "matsuyama-castle"],
    sections: [
      { type: "heading", content: "漱石が松山に赴任した1895年の地図を持って歩く", level: 2 },
      { type: "text", content: "夏目漱石は1895年、28歳の時に松山中学（現・松山東高校）の英語教師として赴任した。わずか1年の滞在だったが、この体験が「坊っちゃん」（1906年）の素材になった。小説に登場する「道後温泉」「清水小路」「城山」は現代でも地図上に確認できる。松山市内の書店で販売している「坊っちゃん歩き地図」を持参すると、文学散歩の精度が上がる。" },
      { type: "spot-card", content: "dogo-onsen" },
      { type: "heading", content: "道後温泉本館＝小説の「湯治場」", level: 2 },
      { type: "text", content: "小説の主人公が「毎日入浴」する湯治場のモデルが道後温泉本館だ。漱石が実際に入浴した浴槽（神の湯二階席の部屋）は現在も保存されており、漱石の大書額が飾られている。改修工事中だが一部公開されており、「漱石の間」として見学できる。ここに立つと、100年以上前の文豪と同じ建物に立っている実感が来る。" },
      { type: "heading", content: "「坊っちゃん列車」は文学と観光の橋渡し", level: 2 },
      { type: "text", content: "坊っちゃん列車は小説に登場する蒸気機関車をモデルにした市電で、松山市駅〜道後温泉を結ぶ。日本語・英語のアナウンスで「坊っちゃんがここを走った」という案内が流れ、文学に馴染みのない旅行者も物語の世界に引き込まれる仕組みだ。乗車料金は通常市電と同額で、追加費用なしで文学体験ができる。" },
    ],
    relatedArticleSlugs: ["ehime-dogo-onsen-night", "ehime-matsuyama-castle-spring"],
  },

  // ── 15 ──────────────────────────────────────
  {
    slug: "ehime-access-guide",
    title: "愛媛へのアクセス完全版──松山空港・新幹線岡山乗り継ぎ・高速バスを使い分ける",
    description: "愛媛の玄関口は複数ある。目的地・予算・出発地によって最適な交通手段が変わる全比較。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "ehime",
    tags: ["アクセス", "松山空港", "交通", "愛媛", "旅のコツ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "東京からは飛行機一択、松山空港まで85分", level: 2 },
      { type: "text", content: "羽田〜松山空港はANA・JAL合わせて1日7〜8便。飛行時間約85分で、早割購入なら1万円前後から取れる。空港から松山市内はリムジンバスで15分、タクシーで25分。出発地が東京近郊なら飛行機の利便性が圧倒的で、新幹線＋在来線特急（約5時間）とは比較にならない。" },
      { type: "heading", content: "大阪・岡山からは電車で来れる", level: 2 },
      { type: "text", content: "新大阪〜松山は特急しおかぜ（岡山乗り継ぎ）で約3時間30分・約8,000〜12,000円。岡山から特急しおかぜで約2時間30分。大阪からの深夜バス（約5時間30分・3,000〜5,000円）も選択肢になる。しまなみ海道経由のバスは日程次第で今治に先立ち寄りできる利点があり、今治スタートのサイクリング計画と相性が良い。" },
      { type: "heading", content: "愛媛県内の移動はJRと高速バスを組み合わせる", level: 2 },
      { type: "text", content: "松山〜今治は特急で35分・普通で55分。松山〜宇和島は特急で1時間30分。今治〜尾道はしまなみ海道高速バスで1時間10分（自転車積載不可）。レンタカーは松山空港・JR松山駅前で各社揃う。みかん農園や宇和島方面に足を伸ばすなら、レンタカーが圧倒的に自由度が高い。松山市内観光は市電で完結するため、松山滞在中のレンタカーは不要だ。" },
    ],
    relatedArticleSlugs: ["ehime-model-course-2days", "ehime-shimanami-cycling-imabari"],
  },
];
