import { Article } from "@/types/article";

export const fukuokaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "fukuoka-dazaifu-early-morning",
    title: "太宰府天満宮、早朝6時の参拝が正解──観光客ゼロの飛梅と梅ヶ枝餅の朝",
    description: "受験シーズンの太宰府は昼間に行ってはいけない。開門直後の6時台、参道に人がいない時間帯に見る飛梅の美しさを語る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "fukuoka",
    tags: ["太宰府天満宮", "早朝参拝", "梅ヶ枝餅", "学問", "福岡"],
    spotIds: ["dazaifu"],
    sections: [
      { type: "heading", content: "6時開門、最初の10分が黄金時間", level: 2 },
      { type: "text", content: "太宰府天満宮の開門は6時。この時間に参道に立つと、ほぼ誰もいない。石畳に朝の光が差し込み、梅の香が漂う。観光バスが着く9時以降とは別の空間だ。飛梅の前で5分間立ち止まることができる。昼間には不可能なことだ。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "梅ヶ枝餅は焼き上がり7時半の一番餅を狙え", level: 2 },
      { type: "text", content: "参道の茶屋「かさの家」は朝7時半に鉄板に火が入る。最初の一番餅は特に皮がパリっと薄く、白餡の甘さが際立つ。熱々を食べるには早朝参拝が唯一の手段だ。10時以降は行列で30分待ちになる。" },
      { type: "heading", content: "新本殿（仮殿）は朝の光の中が最も美しい", level: 2 },
      { type: "text", content: "藤本壮介設計の新本殿は、内部に杉の木が生える異色の建築。東向きなので朝の光が木々の間から差し込む時間帯が最も幻想的だ。昼間の逆光と比べると、別の建物のように見える。写真愛好家なら早朝が唯一の正解だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-shrine-tour", "fukuoka-day2-dazaifu-itoshima"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "fukuoka-nakasu-yatai-complete",
    title: "中洲屋台完全ガイド──初めての人が失敗しない入り方と注文の作法",
    description: "屋台は怖くない。席の確保から会計まで、中洲屋台の暗黙ルールを全部教える。豚骨ラーメンだけが目的ではないことも。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-01-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "fukuoka",
    tags: ["中洲屋台", "博多ラーメン", "夜ごはん", "博多", "福岡"],
    spotIds: ["nakasu-yatai"],
    sections: [
      { type: "heading", content: "屋台の正しい入り方：立って待つが正解", level: 2 },
      { type: "text", content: "中洲の屋台は満席でも「待ちますか？」と声をかければ入れる。入口付近で立って待つのが流儀で、いきなり座るのはマナー違反だ。回転は早く、ラーメン1杯で15分もあれば空く。店主に目を合わせてうなずけば、席が空いたら呼んでくれる。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "ラーメン以外も頼め：おでんと焼き鳥が隠れた主役", level: 2 },
      { type: "text", content: "中洲の屋台でラーメンしか頼まないのは半分しか楽しんでいない。おでん（特に大根と牛スジ）と焼き鳥は博多の屋台文化の中核だ。はしご前提なら1杯飲んで小皿を2品頼む程度に留める。隣の見知らぬ人との会話が始まれば、それが屋台の完成形だ。" },
      { type: "heading", content: "19時〜21時が最も活気があるゴールデンタイム", level: 2 },
      { type: "text", content: "開店直後の18時台はまだ火が入っていない屋台も多い。21時を過ぎると酔客が増えて雰囲気が変わる。地元のサラリーマンが仕事帰りに立ち寄る19時〜21時が、最も本来の屋台文化を体感できる時間帯だ。週末より平日の方が地元色が強い。" },
    ],
    relatedArticleSlugs: ["fukuoka-hakata-ramen-ranking", "fukuoka-yakitori-guide"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "fukuoka-hakata-ramen-ranking",
    title: "博多ラーメン深掘りガイド──豚骨の「濃さ」で選ぶ5つの名店と替え玉文化",
    description: "博多ラーメンは全部同じに見えて、全然違う。濃さ・麺の硬さ・背脂の量で全く別の飲み物になる豚骨スープの世界に案内する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-02-08",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "fukuoka",
    tags: ["博多ラーメン", "豚骨", "替え玉", "グルメ", "福岡"],
    spotIds: ["nakasu-yatai", "hakata-station"],
    sections: [
      { type: "heading", content: "替え玉は「麺の硬さ」を変えて頼むのが通", level: 2 },
      { type: "text", content: "博多ラーメンの替え玉文化は、単に麺を追加するだけではない。最初の1杯を「普通」で頼み、替え玉は「バリカタ（極硬め）」にすると、2杯分の食感の違いを楽しめる。スープが少し残った状態で替え玉を入れ、かき混ぜながら食べるのが正解。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "「一蘭」より地元民が通う老舗を選べ", level: 2 },
      { type: "text", content: "博多駅周辺の「博多一幸舎」は、泡立てたクリーミーな泡系豚骨スープで知られる。中洲の「元祖長浜屋」は屋台から始まった店で、スープはシンプルで濃い。どちらも行列するが、朝10時の開店直後なら並ばずに食べられる。" },
      { type: "heading", content: "辛子高菜と紅しょうがは入れすぎない", level: 2 },
      { type: "text", content: "テーブルに置かれた辛子高菜と紅しょうがは、あくまで「薬味」だ。豚骨スープは繊細で、入れすぎると風味が塗り潰される。一口食べてからスープの味を確認し、少量ずつ足すのが正しい楽しみ方だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-nakasu-yatai-complete", "fukuoka-mentaiko-guide"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "fukuoka-mentaiko-guide",
    title: "明太子の正解を探す旅──老舗5店食べ比べと、博多駅で買うべき土産の選び方",
    description: "明太子は全部同じだと思っていた。食べ比べてみると、辛さ・塩分・粒の大きさで別の食べ物になる。福岡在住者が教える本当の選び方。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "fukuoka",
    tags: ["明太子", "博多土産", "グルメ", "福岡", "食べ比べ"],
    spotIds: ["hakata-station"],
    sections: [
      { type: "heading", content: "「ふくや」が元祖、「やまや」が量産体制を確立した", level: 2 },
      { type: "text", content: "博多明太子の元祖は中洲「ふくや」だ。昭和24年の創業で、朝鮮半島の塩漬けタラコ「明卵漬け」を日本人向けにアレンジした。現在最も流通しているのは「やまや」で、全国展開の量産品。旅行者が博多駅で買うなら「ふくや」と「かねふく」を食べ比べるセットが正解。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "明太子はご飯で食べるより「たたき」で食べろ", level: 2 },
      { type: "text", content: "最上の食べ方は「明太子のたたき」だ。皮を取り除いて粒だけにし、少量のだし醤油を垂らして白飯に乗せる。居酒屋でこれを頼むと、大根おろしとともに出てくる店もある。ご飯との比率は1:3が黄金比。" },
      { type: "heading", content: "賞味期限に注意：生明太子は2日以内に食べる", level: 2 },
      { type: "text", content: "生明太子は冷蔵で2〜3日、冷凍で1ヶ月が目安。博多土産として持ち帰る際は、新幹線の時間を逆算して購入すること。博多駅改札内「マイング」は当日の朝に店頭に並ぶ新鮮なものが揃う。" },
    ],
    relatedArticleSlugs: ["fukuoka-hakata-ramen-ranking", "fukuoka-motsu-nabe-guide"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "fukuoka-motsu-nabe-guide",
    title: "もつ鍋の食べ方を知っているか──福岡で生まれた鍋料理の流儀と名店選び",
    description: "もつ鍋は博多の発明品だ。ニラとキャベツの山が崩れていく順序と、〆のちゃんぽん麺の入れ方まで、正式な手順を伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "fukuoka",
    tags: ["もつ鍋", "博多グルメ", "鍋料理", "福岡", "居酒屋"],
    spotIds: ["nakasu-yatai"],
    sections: [
      { type: "heading", content: "もつ鍋の正しい順序：崩さずに蓋をして待て", level: 2 },
      { type: "text", content: "もつ鍋は最初から混ぜてはいけない。ニラとキャベツの山、その下に沈むもつ。蓋をして3分待つと、野菜が蒸れてかさが減る。そこで初めて全体をかき混ぜると、もつの脂がスープに溶け出す。醤油ベースと味噌ベースで風味が大きく変わるが、博多の老舗は醤油ダレが多い。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "〆はちゃんぽん麺一択、うどんではない", level: 2 },
      { type: "text", content: "もつ鍋の〆はちゃんぽん麺だ。うどんやご飯もあるが、コシのあるちゃんぽん麺がもつのコクに最も合う。麺を入れた後、再沸騰してから1分弱で食べるのが正解。煮過ぎると麺が溶けてしまう。" },
      { type: "heading", content: "中洲「楽天地」と天神「おおやま」は外せない", level: 2 },
      { type: "text", content: "もつ鍋の老舗は中洲・天神エリアに集中している。「楽天地」は昭和に創業した本家筋で、スープのコクが深い。「おおやま」は全国展開しているが、天神本店のもつは産地直送。1人前2,200円〜が相場で、2〜3名でのシェアが基本。" },
    ],
    relatedArticleSlugs: ["fukuoka-mentaiko-guide", "fukuoka-nakasu-yatai-complete"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "fukuoka-itoshima-day-trip",
    title: "糸島日帰りドライブコース──牡蠣小屋から二見ヶ浦夕日まで完璧なルート",
    description: "糸島は福岡市内から30分なのに、来た人の9割が「思ったより遠かった」と言う。正しいルートと時間配分を地図付きで解説する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-03-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "fukuoka",
    tags: ["糸島", "ドライブ", "牡蠣小屋", "二見ヶ浦", "モデルコース"],
    spotIds: ["itoshima"],
    sections: [
      { type: "heading", content: "11月〜3月限定：牡蠣小屋は予約なしで行く方法", level: 2 },
      { type: "text", content: "糸島の牡蠣小屋は週末の昼間は1時間待ちが当たり前だ。攻略法は平日10時半に現地入りすること。主要な小屋「岐志漁港」「船越漁港」とも11時開始だが、10時半から場所取りができる。1テーブル3kg（約2,000円）から注文。炭火の網を自分で管理する豪快なスタイルが糸島流。" },
      { type: "spot-card", content: "itoshima" },
      { type: "heading", content: "午後はカフェ巡り：農村の中に隠れる5店", level: 2 },
      { type: "text", content: "糸島はカフェの聖地だ。「ITOSHIMA CHEESE FACTORY」の自家製チーズは糸島牛乳から作る。「SOLANIN」は元倉庫を改装した廃墟系カフェで、インスタ映えスポットとして知られる。いずれも車なしでは辿り着けない農村に点在するのが特徴。" },
      { type: "heading", content: "17時：二見ヶ浦で日没を待て", level: 2 },
      { type: "text", content: "糸島の最後は二見ヶ浦の夫婦岩で締める。秋冬は日没が16時半ごろと早い。岩に向かって西向きに立つと、夫婦岩の鳥居と太陽が重なる瞬間がある。5分の勝負なので、15時台に現地入りして場所を確保しておくこと。" },
    ],
    relatedArticleSlugs: ["fukuoka-green-season-guide", "fukuoka-day2-dazaifu-itoshima"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "fukuoka-mojiko-retro-walk",
    title: "門司港レトロ完全散策ガイド──焼きカレーの正解店と夜のライトアップ穴場スポット",
    description: "門司港は昼間に行く観光地だと思ったら間違いだ。夕暮れ後のライトアップで洋館が浮かび上がる2時間が、この街の本番だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "fukuoka",
    tags: ["門司港レトロ", "焼きカレー", "夜景", "北九州", "レトロ建築"],
    spotIds: ["mojiko-retro"],
    sections: [
      { type: "heading", content: "焼きカレーは13店を制覇した人間が選ぶ「3店」", level: 2 },
      { type: "text", content: "門司港の焼きカレーは10店以上が競い合う。王道は「伽哩本舗」で、半熟卵を割ってルーと絡める正統派。穴場は「BEAR FRUITS」のフルーツ焼きカレーで、マンゴーの甘みが豚骨とは別次元の化学反応を起こす。開店前の11時に並ぶ覚悟が必要。" },
      { type: "spot-card", content: "mojiko-retro" },
      { type: "heading", content: "旧門司税関の2階テラスは夕景専用スポット", level: 2 },
      { type: "text", content: "関門海峡に面した旧門司税関の2階テラスは、日没30分前から人が集まり始める。夕陽が関門橋を染める時間帯は息を飲む美しさだ。この角度から撮った写真は、昼間の何百枚よりも価値がある。入場無料、17時まで入れる。" },
      { type: "heading", content: "21時のライトアップが消える前に走れ", level: 2 },
      { type: "text", content: "門司港のライトアップは21時で消える。20時半を過ぎると人が少なくなり、石畳の上でゆっくり歩けるようになる。旧大阪商船前の広場は反射した光がレンガ壁を染め、写真を撮るには20時45分前後が最適だ。三脚があると完璧な一枚が撮れる。" },
    ],
    relatedArticleSlugs: ["fukuoka-northern-kyushu-day-trips", "fukuoka-hakata-station-guide"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "fukuoka-spring-sakura-routes",
    title: "福岡の桜2025──舞鶴公園の夜桜と西公園の穴場、混雑を避ける完全ガイド",
    description: "福岡城跡の桜は3月下旬に満開になる。熊本城より人が少なく、天守台から城下町を見下ろす夜桜は全九州で最高の花見スポットだ。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-03-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "fukuoka",
    tags: ["桜", "花見", "舞鶴公園", "春", "福岡"],
    spotIds: ["hakata-station"],
    sections: [
      { type: "heading", content: "舞鶴公園（福岡城跡）は平日夜が完璧", level: 2 },
      { type: "text", content: "舞鶴公園は福岡城跡を整備した花見の聖地。約1,000本のソメイヨシノが城壁に沿って咲く。ライトアップ期間中の平日20時以降は、花見客が引いて静けさと美しさだけが残る。シートを広げてコンビニ酒で花見をする福岡市民の姿が、城下の春の定番風景だ。" },
      { type: "heading", content: "西公園は地元民専用の穴場、観光客が来ない理由", level: 2 },
      { type: "text", content: "西公園は福岡市西区の小高い丘にある公園で、桜は約1,300本。頂上からは博多湾と能古島が見渡せる。観光バスが来ない理由は単純にアクセスが悪いからで、バスか車が必要だ。だからこそ混雑ゼロで花見ができる。地元の老夫婦が弁当を広げる春の風景が美しい。" },
      { type: "heading", content: "4月第1週は大濠公園の花筏を見よ", level: 2 },
      { type: "text", content: "桜が散り始めると、大濠公園の池面が花筏で覆われる。これは見ごろの1週間後に来た人だけが見られる光景だ。花びらが流れに従って模様を変えていく様子は、散り際の美しさとして花見のピークより印象に残る人が多い。" },
    ],
    relatedArticleSlugs: ["fukuoka-green-season-guide", "fukuoka-itoshima-day-trip"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "fukuoka-summer-marinoa-fireworks",
    title: "福岡の夏祭り2025──山笠の観覧場所と西日本最大級の花火大会を一気に楽しむ方法",
    description: "博多祇園山笠の追い山は7月15日の早朝4時59分に始まる。この時間に中洲川端にいる人間だけが、本物の博多を目撃できる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "fukuoka",
    tags: ["博多祇園山笠", "夏祭り", "花火", "夏", "博多"],
    spotIds: ["nakasu-yatai", "hakata-station"],
    sections: [
      { type: "heading", content: "追い山は4時59分スタート：前夜から場所取りが必要", level: 2 },
      { type: "text", content: "博多祇園山笠のクライマックス「追い山」は7月15日の夜明け前に始まる。1トンを超える飾り山を担いで旧市街を全力疾走する姿は、1,000年以上続く祭りの本気だ。ベストポジションは上川端通り付近の沿道で、前夜から場所取りが行われる。眠れなくてもいい祭りだ。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "花火大会は海の中道と博多港の2択", level: 2 },
      { type: "text", content: "福岡の花火大会は2大会が有名だ。「海の中道海浜公園」の花火は打ち上げ場所が海上なので四方から見える。「博多港花火大会」はビルの屋上や天神の高層ビルからも見えるため、ホテルに泊まりながら観覧という贅沢が成立する。" },
      { type: "heading", content: "〆は屋台の博多ラーメン：夜明けの一杯", level: 2 },
      { type: "text", content: "追い山の終わった朝6時台、中洲の屋台は撤収作業中でも一部は朝ラーメンを提供する。祭りと花火を全力で楽しんだ後、白濁豚骨スープを啜る博多の夜明けは忘れられない体験になる。" },
    ],
    relatedArticleSlugs: ["fukuoka-tenjin-shopping", "fukuoka-rainy-day-guide"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "fukuoka-solo-travel-guide",
    title: "一人旅で福岡を120%楽しむ──カウンター文化の街で孤独を感じない理由",
    description: "福岡は一人旅最強の街だ。屋台・ラーメン屋・もつ鍋屋、全部カウンターが文化の中心にある。一人で来るからこそ地元民と話せる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "fukuoka",
    tags: ["一人旅", "ソロ旅", "博多", "カウンター", "福岡"],
    spotIds: ["nakasu-yatai", "hakata-station"],
    sections: [
      { type: "heading", content: "福岡のカウンター文化：一人こそ最前列に座れる", level: 2 },
      { type: "text", content: "博多の飲食文化の核はカウンターだ。屋台も、老舗ラーメン屋も、もつ鍋の名店も、最高の席はカウンターの1席だ。二人以上ではテーブルに案内されてしまう。一人で来てカウンターに座ると、調理している手元が見える席に通される。これが一人旅最大の特権だ。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "地下鉄1日乗り放題680円で移動コストゼロ", level: 2 },
      { type: "text", content: "福岡市地下鉄の1日乗車券は680円。天神・博多・中洲川端・空港の全主要エリアが移動自由になる。タクシーを使わずに街全体を動き回れる。一人旅で食費以外にかかるコストがほぼゼロになるのが福岡の強みだ。" },
      { type: "heading", content: "キャナルシティの一人映画から始める夜の戦略", level: 2 },
      { type: "text", content: "一人旅の昼間が余った時、キャナルシティ博多の映画館は格好の時間調整スポットだ。19時ごろに映画を終えると、ちょうど屋台が活気づく時間帯に中洲へ動ける。映画後に屋台ラーメン、そして天神のバーで〆る。一人でも完結する博多の夜の方程式だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-nakasu-yatai-complete", "fukuoka-budget-travel-plan"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "fukuoka-couple-romantic-spots",
    title: "福岡カップル旅2泊3日──糸島夕日・中洲屋台・門司港夜景で完成する九州最高のデート",
    description: "福岡はカップル旅に向いているか？答えは最高に向いている。夕日のスポット・二人で食べるもつ鍋・夜景の3つが全部揃う街だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "fukuoka",
    tags: ["カップル旅", "福岡", "デート", "糸島", "夜景"],
    spotIds: ["itoshima", "nakasu-yatai", "mojiko-retro"],
    sections: [
      { type: "heading", content: "1日目：糸島の海と夕日でリセットする", level: 2 },
      { type: "text", content: "福岡に到着したら荷物を博多駅のコインロッカーに預け、すぐに糸島へ向かう。昼のカフェで糸島野菜のプレートランチを食べ、午後は二見ヶ浦の砂浜を歩く。夕日が落ちる17時半まで海岸にいる。この3時間が旅全体のトーンを決める。" },
      { type: "spot-card", content: "itoshima" },
      { type: "heading", content: "2日目夜：中洲屋台で二人のテーブルに相席文化を体験する", level: 2 },
      { type: "text", content: "中洲の屋台は二人でも相席が基本だ。知らない人と肩を並べて同じ鍋をつつく経験が、旅のハイライトになる。カップルは同じ方向を向いてカウンターに座るので、会話が自然に相席客に流れる。この開放感が屋台でしか生まれない空気だ。" },
      { type: "heading", content: "3日目：門司港レトロで昭和の海辺を歩く", level: 2 },
      { type: "text", content: "最終日は北九州市門司区へ足を延ばす。焼きカレーのランチ後、旧門司税関から関門海峡を眺めると対岸の下関が見える。連絡船で渡って「ふく」（ふぐ）を食べて戻るか、橋上の景色を眺めながら帰路につくか。どちらも旅の完璧な幕切れになる。" },
    ],
    relatedArticleSlugs: ["fukuoka-itoshima-day-trip", "fukuoka-mojiko-retro-walk"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "fukuoka-family-kids-trip",
    title: "子連れ福岡3日間モデルコース──マリンワールドから太宰府まで、子どもが飽きない完全プラン",
    description: "福岡は子連れ旅にも最適だ。マリンワールド・太宰府・キャナルシティ・糸島の海と、テーマ別に丸一日遊べるスポットが揃っている。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "fukuoka",
    tags: ["子連れ旅", "家族旅行", "福岡", "マリンワールド", "太宰府"],
    spotIds: ["dazaifu", "itoshima"],
    sections: [
      { type: "heading", content: "1日目：マリンワールド海の中道で海の生き物に圧倒される", level: 2 },
      { type: "text", content: "海の中道海浜公園のマリンワールドは、イルカショーが毎日3回開催される。入場後すぐ正面の大水槽に向かい、10時の開館直後はガラス面の前が空いている。マグロが目の前を横切る瞬間に子どもが立ち尽くす——これが子連れ福岡1日目の正解だ。入場料2,600円。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "2日目：太宰府で梅ヶ枝餅を焼かせてもらう体験", level: 2 },
      { type: "text", content: "太宰府天満宮の一部の茶屋では、子どもが梅ヶ枝餅を自分で焼く体験ができる（要予約）。鉄板の前で真剣な顔をして餅をひっくり返す子どもの姿は、旅の最高の写真になる。焼きたての梅ヶ枝餅を食べる体験は、買って食べるのとは別次元の記憶になる。" },
      { type: "heading", content: "3日目：糸島の海で潮干狩り（春限定）か砂浜遊び", level: 2 },
      { type: "text", content: "3月下旬〜5月、糸島の一部の砂浜では潮干狩りができる。道具レンタルがあり、子どもが夢中で貝を掘る。夏ならシンプルに砂浜で遊ぶだけで半日が溶ける。糸島の海は遠浅で流れが穏やかなので、小さい子どもも安心して遊べる数少ない九州の海だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-dazaifu-early-morning", "fukuoka-itoshima-day-trip"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "fukuoka-budget-travel-plan",
    title: "福岡1日3,000円旅──無料スポットと格安グルメだけで作る最高の一日",
    description: "福岡は安くて旨い街の代名詞だ。交通費・食費・入場料を全部合計しても3,000円で最高の一日が完成する。その具体的なルートを公開する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "fukuoka",
    tags: ["節約旅", "格安", "一人旅", "福岡", "バジェット"],
    spotIds: ["nakasu-yatai", "hakata-station"],
    sections: [
      { type: "heading", content: "朝：博多駅地下の立ち食いうどん300円", level: 2 },
      { type: "text", content: "博多駅地下の「因幡うどん」は朝7時から開く立ち食いうどん店で、ごぼ天うどん310円。出汁の効いた透き通ったスープと柔らかい麺が、福岡の朝食の正解だ。券売機制で回転が早く、7時台でも10分以内に食べ終えられる。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "昼：東長寺の五重塔と承天寺で無料の歴史散策", level: 2 },
      { type: "text", content: "東長寺は空海が開いた日本最古の密教寺院で入場無料。博多千年門から承天寺まで徒歩5分の路地には、博多の歴史が凝縮されている。うどん発祥の地・承天寺の石碑を見るだけで、博多が日本の食文化の起源の一つであることが分かる。" },
      { type: "heading", content: "夜：中洲屋台のラーメン1杯で900円以内", level: 2 },
      { type: "text", content: "中洲屋台のラーメンは700〜900円が相場だ。替え玉150円を追加しても1,000円以内。ビールを飲まなければ屋台でも十分に予算内に収まる。夜は地下鉄で中洲川端駅まで行き（260円）、屋台で1杯食べて帰れば夜の食費は1,200円以内だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-solo-travel-guide", "fukuoka-hakata-ramen-ranking"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "fukuoka-luxury-hotel-dining",
    title: "福岡の贅沢旅──THE BLOSSOM HATAKAと警固神社前の割烹で過ごす大人の2日間",
    description: "福岡はコスパが良い街だが、最上の体験を求めると東京を超えてくる。博多の高級ホテルと本物の九州料理が揃う大人の旅行を設計する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "fukuoka",
    tags: ["高級旅", "贅沢", "ホテル", "料亭", "福岡"],
    spotIds: ["nakasu-yatai", "hakata-station"],
    sections: [
      { type: "heading", content: "JR九州ホテルブラッサム博多：新幹線改札内から入れる唯一のホテル", level: 2 },
      { type: "text", content: "博多駅直結のJR九州ホテルブラッサム博多は、新幹線ホームから直接入れるホテルだ。チェックイン後すぐに博多の夜に出られる立地は、出張客だけでなく旅行者にとっても圧倒的に便利だ。最上階からの夜景と朝の博多の街並みは、旅の始まりに相応しい。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "天神「鮨処あら輝」：予約3ヶ月待ちの正解", level: 2 },
      { type: "text", content: "天神の「鮨処あら輝」はカウンター8席の完全予約制。玄界灘の魚が中心で、大将が握る一貫一貫に九州の海のストーリーがある。おまかせコース25,000円〜。予約は公式サイトのみで、3ヶ月先まで満席が続く。旅行日程が決まったら即日予約を入れるべき店だ。" },
      { type: "heading", content: "翌朝：博多駅デイトスの「博多 海鮮市場」で朝食", level: 2 },
      { type: "text", content: "贅沢な前夜の翌朝は、博多駅地下デイトスの海鮮丼で始める。1,500円台の朝の海鮮丼は、明太子と新鮮な刺身が乗る。東京の同等価格の店とは別次元の鮮度だ。開店の9時に行けば並ばずに座れる。" },
    ],
    relatedArticleSlugs: ["fukuoka-hakata-ramen-ranking", "fukuoka-mentaiko-guide"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "fukuoka-onsen-trip",
    title: "福岡から行く温泉1泊旅──二日市温泉・原鶴温泉・脇田温泉、それぞれの違いを解説",
    description: "福岡市内から1時間以内に、本物の温泉地が3つある。日帰りか1泊かで全く違う体験になる。それぞれの特徴と使い方を比較する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "fukuoka",
    tags: ["温泉", "二日市温泉", "原鶴温泉", "日帰り温泉", "福岡"],
    spotIds: ["dazaifu"],
    sections: [
      { type: "heading", content: "二日市温泉：太宰府の翌日に立ち寄る歴史の湯", level: 2 },
      { type: "text", content: "二日市温泉は西鉄二日市駅から徒歩5分の日帰り温泉施設「博多の湯」が有名だ。公式の温泉利用施設として江戸時代から続く歴史があり、太宰府天満宮観光の帰りに立ち寄る人が多い。泉質はナトリウム塩化物泉で、よく温まる。入浴料は400円と格安。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "原鶴温泉：筑後川沿いの宿で1泊するなら", level: 2 },
      { type: "text", content: "原鶴温泉は筑後川の中洲に旅館が並ぶ温泉地で、福岡市から車で1時間。秋の紅葉シーズンは川沿いの景色が最高になる。「泰泉閣」の露天風呂は川に面しており、轟音を立てて流れる筑後川を見ながら入浴できる。夕食の鮎料理と鶴の子芋も絶品。" },
      { type: "heading", content: "脇田温泉：渓谷の中に静かに存在する穴場", level: 2 },
      { type: "text", content: "脇田温泉は遠賀川の支流・脇田川沿いにある秘湯系の温泉地だ。旅館は数軒のみで、「休暇村 若杉高原おおやま」の隣に位置する穴場。平日は地元の常連客しかいない静けさで、湯質はアルカリ性単純温泉。肌がツルツルになる「美人の湯」として地元民に知られている。" },
    ],
    relatedArticleSlugs: ["fukuoka-dazaifu-early-morning", "fukuoka-northern-kyushu-day-trips"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "fukuoka-hakata-station-guide",
    title: "博多駅を使い倒す完全ガイド──新幹線待ち時間でできる最高の30分・60分・120分プラン",
    description: "博多駅の乗り換え時間が無駄だと思ったら、それは使い方を知らないからだ。地下から屋上まで、時間別に最大化する方法を教える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "fukuoka",
    tags: ["博多駅", "アクセス", "乗り換え", "お土産", "福岡"],
    spotIds: ["hakata-station"],
    sections: [
      { type: "heading", content: "30分：博多デイトス地下でラーメン一杯", level: 2 },
      { type: "text", content: "博多駅地下の「博多デイトス」は時間の短い旅行者の最強の味方だ。改札を出てエスカレーターを下ると、博多ラーメンとうどんの老舗が並ぶ。「一幸舎」のカウンター席は入店から退店まで20分以内で完結する。新幹線の30分前でも確実に食べられる。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "60分：アミュプラザ6階の明太子土産を厳選する", level: 2 },
      { type: "text", content: "アミュプラザ博多6階の「マイング」は博多土産が集約されたゾーン。明太子は「ふくや」「かねふく」「やまや」が横並びで比較できる。各社の試食を全部食べてから選ぶのが正解。とおりもん（和菓子）は10個入りと16個入りの価格比を確認してから買うと節約できる。" },
      { type: "heading", content: "120分：屋上テラスと博多川端商店街を往復", level: 2 },
      { type: "text", content: "アミュプラザの屋上テラスは無料で開放されており、博多の街並みと遠くに霞む海が見える。そこから川端商店街まで徒歩7分。江戸時代から続く商店街で、博多人形や博多織の工芸品を見ながら歩く120分は観光としても十分に充実する。" },
    ],
    relatedArticleSlugs: ["fukuoka-mentaiko-guide", "fukuoka-hakata-ramen-ranking"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "fukuoka-autumn-leaves",
    title: "福岡の紅葉2025──背振山・宝満山・三郡山、11月の山歩きと温泉セットの完全ガイド",
    description: "福岡の紅葉は山にある。観光地の紅葉より、車で1時間の山頂に広がる原生林の紅葉の方が圧倒的に美しい理由を語る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "fukuoka",
    tags: ["紅葉", "秋", "登山", "背振山", "福岡"],
    spotIds: ["dazaifu"],
    sections: [
      { type: "heading", content: "背振山系の紅葉：11月第1週が最高", level: 2 },
      { type: "text", content: "背振山（標高1055m）は福岡と佐賀の県境に位置する。山頂付近の紅葉は10月末〜11月第1週が見頃で、晴れた日には有明海まで見渡せる。登山道は整備されており、初心者でも3時間で山頂に立てる。下山後の二日市温泉の一杯が最高の褒美になる。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "太宰府天満宮の銀杏並木：11月下旬が見頃", level: 2 },
      { type: "text", content: "太宰府天満宮の参道沿いには大きな銀杏の木が並ぶ。11月下旬に一斉に黄葉し、参道が黄金色に染まる。朝霧が出る日の早朝は特別で、黄色の葉と白い霧の対比が幻想的な写真になる。梅ヶ枝餅と一緒に黄葉を見る、秋の太宰府の正解パターンだ。" },
      { type: "heading", content: "三郡山：福岡市民の知る穴場・紅葉の秘境", level: 2 },
      { type: "text", content: "三郡山（標高936m）は篠栗町からアクセスできる穴場の紅葉スポットだ。観光化されていないため、平日に登ると山全体を独り占めできる。山頂の展望台から見える博多湾と紅葉の組み合わせは、インターネットにほとんど写真が出回っていない本物の絶景だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-dazaifu-early-morning", "fukuoka-onsen-trip"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "fukuoka-tenjin-shopping",
    title: "天神ショッピング完全攻略──岩田屋から地下街まで、福岡ファッションの地図を読む",
    description: "天神は九州最大のショッピングエリアだ。東京と同じブランドが揃うだけでなく、九州ローカルのブランドと博多織の専門店が混在する独自の地図がある。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-05-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "fukuoka",
    tags: ["天神", "ショッピング", "博多織", "福岡", "買い物"],
    spotIds: ["hakata-station"],
    sections: [
      { type: "heading", content: "博多織の帯と財布：天神で唯一「本物」が買える店", level: 2 },
      { type: "text", content: "博多織は福岡が誇る伝統工芸で、締め心地の良い帯として全国に知られる。天神「岩田屋本店」の呉服フロアでは、現役の博多織職人が製作した反物を直接見ながら選べる。財布やバッグに加工したものは¥8,000〜から購入可能で、土産として持ち帰る価値がある。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "天神地下街：260mの地下通路で雨の日も完結", level: 2 },
      { type: "text", content: "天神地下街は昭和51年に開業した全長590mの地下商店街。レトロなヨーロッパ風の装飾が特徴で、九州の物産品・スイーツ・ファッションが揃う。雨の日の天神観光はほぼ全て地下で完結できる。地下鉄天神駅と渡辺通駅を地下で繋ぐため、移動も雨に濡れない。" },
      { type: "heading", content: "PARCO・ソラリア・イムズ：三角形の歩き方", level: 2 },
      { type: "text", content: "天神の大型商業施設は三角形に配置されている。PARCOは若者向けセレクトショップ中心、ソラリアプラザは20〜30代向け、天神イムズ（現在リニューアル中）は文化的な空間だった。この三角形を徒歩で動きながら、各施設の食事フロアで食べ歩くのが最も効率的な天神の楽しみ方だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-hakata-station-guide", "fukuoka-mentaiko-guide"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "fukuoka-winter-illumination",
    title: "福岡の冬イルミネーション2025──天神クリスマスと博多阪急のライトアップが九州一の理由",
    description: "12月の福岡は光の街になる。天神・博多駅・中洲の3点が同時にライトアップされる夜の歩き方と、混雑を避ける時間帯を完全解説。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "fukuoka",
    tags: ["イルミネーション", "冬", "クリスマス", "夜景", "福岡"],
    spotIds: ["hakata-station", "nakasu-yatai"],
    sections: [
      { type: "heading", content: "博多駅「光の街・博多」：毎年12月の名物", level: 2 },
      { type: "text", content: "博多駅前広場のイルミネーション「光の街・博多」は毎年11月中旬から始まる。巨大なクリスマスツリーとアミュプラザ外壁のプロジェクションマッピングが組み合わさり、九州最大規模と言われる。平日の点灯直後（17時半〜18時）は人が少なく、写真を撮るなら絶好のタイミングだ。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "天神クリスマスマーケット：ドイツ式の屋台が立ち並ぶ", level: 2 },
      { type: "text", content: "天神中央公園では毎年12月にドイツ式クリスマスマーケットが開催される。グリューワイン（ホットワイン）と本場のソーセージが屋外で食べられる貴重な体験だ。寒い夜でも人で賑わうが、平日の19時台は列が短い。噴水広場周辺のツリーと組み合わせた夜景が美しい。" },
      { type: "heading", content: "中洲の光：屋台とイルミネーションの共演", level: 2 },
      { type: "text", content: "12月の中洲は屋台の灯りとイルミネーションが重なる最も美しい時期だ。那珂川に架かる橋から川面に映る光を見下ろし、屋台のラーメンを一杯食べて温まる。福岡の冬夜の過ごし方として、これ以上の完成形はない。" },
    ],
    relatedArticleSlugs: ["fukuoka-nakasu-yatai-complete", "fukuoka-couple-romantic-spots"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "fukuoka-day2-dazaifu-itoshima",
    title: "福岡2日目の完璧な使い方──午前は太宰府、午後は糸島、夜は中洲で完成する九州一周プランの核心",
    description: "福岡の滞在2日目をどう使うか。太宰府と糸島を同じ日に回ることはできるのか、できるとしたら何時に動けばいいのか。時間と移動の全てを公開する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-04-28",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "fukuoka",
    tags: ["モデルコース", "太宰府", "糸島", "中洲", "2日目"],
    spotIds: ["dazaifu", "itoshima", "nakasu-yatai"],
    sections: [
      { type: "heading", content: "8時：太宰府天満宮で開門直後の参拝", level: 2 },
      { type: "text", content: "2日目の朝は8時に太宰府天満宮へ。早朝の人のいない参道を歩き、梅ヶ枝餅を1個食べる。9時前に退散することで、観光バスの群れを完全に回避できる。所要時間1時間で、次の移動に余裕が生まれる。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "10時：糸島へ移動、牡蠣小屋か農村カフェへ", level: 2 },
      { type: "text", content: "太宰府から糸島への直接移動は電車+バスで約1時間半かかる。レンタカーなら1時間。11〜3月は牡蠣小屋、それ以外はカフェが目標になる。糸島の農村カフェは12時オープンが多いので、到着後すぐに昼食に入れる。" },
      { type: "heading", content: "17時：二見ヶ浦で夕日を見て中洲へ帰還", level: 2 },
      { type: "text", content: "糸島の最終スポットは二見ヶ浦の夕日。日没30分前に到着して、夫婦岩と沈む太陽を見届ける。その後は糸島から西鉄バスで博多に戻り（約50分）、19時台の中洲屋台で1日を締める。この動線が、福岡2日目の最も贅沢な使い方だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-dazaifu-early-morning", "fukuoka-itoshima-day-trip"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "fukuoka-new-year-hatsumode",
    title: "福岡の初詣2026──太宰府天満宮の三が日と、穴場の箱崎宮・住吉神社の完全ガイド",
    description: "太宰府天満宮の三が日は200万人が参拝する。この人混みを避ける方法と、同等の格式を持つ穴場神社を地元民が解説する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-12-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "fukuoka",
    tags: ["初詣", "正月", "太宰府天満宮", "箱崎宮", "福岡"],
    spotIds: ["dazaifu"],
    sections: [
      { type: "heading", content: "太宰府天満宮三が日：最短で参拝する方法", level: 2 },
      { type: "text", content: "三が日の太宰府天満宮は西鉄の臨時列車でも1時間待ちになる。それでも行くなら1月1日の0時から3時が最も回転が早い。初日の出を見てから帰る人が多く、夜明け前の2時台が最も空いている。梅ヶ枝餅は元日から開く茶屋があり、焼きたてが食べられる。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "箱崎宮：全国勝運の総本宮に静かに初詣", level: 2 },
      { type: "text", content: "箱崎宮は「敵国降伏」の額が掲げられた全国勝運の総本宮で、地下鉄箱崎宮前駅すぐ。三が日でも太宰府の100分の1の混雑で参拝できる。勝負事の前に訪れる受験生や就活生に人気で、地元の福岡市民の多くはこちらを選ぶ。" },
      { type: "heading", content: "住吉神社：博多の中心に千年以上続く正月の鎮守", level: 2 },
      { type: "text", content: "博多駅から徒歩5分の住吉神社は、博多の守護神として市民に愛されてきた。境内は広くなく、参拝に10分もかからない。その代わり地元の人たちとの距離が近く、甘酒が無料で振る舞われる正月の雰囲気が温かい。観光客より地元民が多い初詣の正解。" },
    ],
    relatedArticleSlugs: ["fukuoka-dazaifu-early-morning", "fukuoka-spring-sakura-routes"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "fukuoka-hakata-machiya-stay",
    title: "博多の町家に泊まる──川端・祇園エリアの古民家ゲストハウスと地元朝市の組み合わせ",
    description: "博多には江戸時代の商人の家を改装したゲストハウスが点在する。ホテルとは全く異なる滞在感と、朝の博多川端市場の空気を組み合わせた旅の提案。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "fukuoka",
    tags: ["町家", "ゲストハウス", "博多", "古民家", "旅スタイル"],
    spotIds: ["nakasu-yatai", "hakata-station"],
    sections: [
      { type: "heading", content: "川端・祇園エリアの古民家ゲストハウスを選ぶ理由", level: 2 },
      { type: "text", content: "博多川端商店街の裏手に残る古い商家を改装したゲストハウスは、博多の商人文化の痕跡をそのまま感じられる空間だ。梁が見える高い天井と格子窓、中庭の坪庭。1泊4,000〜6,000円で、全国チェーンのホテルでは絶対に体験できない滞在感がある。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "朝7時：川端市場で本物の朝食", level: 2 },
      { type: "text", content: "川端商店街の奥に朝7時から開く市場食堂がある。定食は600円台で、ごま鯖（博多名物の鯖の胡麻和え）が付く。宿から歩いて3分。旅行者は誰も知らないこの食堂で、地元の職人と並んで朝食を食べる時間が、博多に泊まる最大の理由になる。" },
      { type: "heading", content: "シェアキッチンで博多の食材を自炊する体験", level: 2 },
      { type: "text", content: "設備の良いゲストハウスにはシェアキッチンがある。博多中央市場で明太子と鯖を買って、自分でごま鯖を作る体験は、料理好きの旅行者には特別な思い出になる。市場で仕入れた鯖は新鮮で、東京のスーパーとは別物の味がする。" },
    ],
    relatedArticleSlugs: ["fukuoka-solo-travel-guide", "fukuoka-hakata-ramen-ranking"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "fukuoka-tenjin-couple-night",
    title: "天神カップルナイト──Bar Barossa・Nakashin・警固公園の夜を設計する",
    description: "天神の夜は無限に広がる。福岡在住のカップルが実際に使うルートを、Bar選びから公園散歩まで全部公開する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "fukuoka",
    tags: ["カップル", "天神", "バー", "夜デート", "福岡"],
    spotIds: ["nakasu-yatai"],
    sections: [
      { type: "heading", content: "18時：警固神社で縁結びのお守りを買う", level: 2 },
      { type: "text", content: "天神の中心にある警固神社は縁結びの神様として知られる。夕方の参拝は参拝客が少なく、二人でゆっくり手を合わせられる。境内の樹木が天神の喧騒を遮断し、都市の中の静けさを作り出している。縁結びのお守り（1,000円）はカップルで持ち歩く定番。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "20時：中洲の屋台でラーメンを食べてからバーへ", level: 2 },
      { type: "text", content: "中洲屋台で豚骨ラーメンを1杯食べた後、天神に戻って大名エリアのBarへ。大名には個性的な小さいBarが密集しており、カウンター6席のような規模の店で地元産の日本酒や焼酎を飲める。福岡のスナック文化の延長にある大人の夜が展開される。" },
      { type: "heading", content: "22時：警固公園の噴水前でナイトキャップ", level: 2 },
      { type: "text", content: "天神の警固公園は夜でも多くの人が集まる開放的な都市公園だ。コンビニでテイクアウトしたお酒を持ち込んで噴水前のベンチに座る。福岡の夜風は温かく、10月でもコートなしで外にいられる日がある。都市の夜を最も安く楽しむ天神の過ごし方だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-couple-romantic-spots", "fukuoka-nakasu-yatai-complete"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "fukuoka-ramen-pilgrimage",
    title: "博多ラーメン巡礼5店完全ガイド──1日で5杯食べるための作戦と胃袋の守り方",
    description: "博多ラーメンの食べ歩きには技術が要る。一日5杯を完走するためのタイムライン、少量ずつ頼む方法、胃を守るための食べ方を全部教える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "fukuoka",
    tags: ["博多ラーメン", "食べ歩き", "ラーメン巡礼", "グルメ旅", "福岡"],
    spotIds: ["nakasu-yatai", "hakata-station"],
    sections: [
      { type: "heading", content: "1杯目7時：博多駅「一幸舎」の泡系豚骨で開幕", level: 2 },
      { type: "text", content: "博多ラーメン巡礼の初戦は「一幸舎 博多本店」の泡系豚骨で始める。クリーミーな泡立てスープは胃への負担が少なく、1杯目に最適だ。普通盛りではなく「半玉」（麺の量を半分にする）で注文すると残りの4杯に備えられる。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "間食：辛子高菜・キムチで胃をリセット", level: 2 },
      { type: "text", content: "2杯目と3杯目の間に2時間の休憩を入れ、漬物や発酵食品を少量食べると胃酸の働きが正常化する。コンビニのキムチを少量食べるだけでいい。散歩しながら食間を作ることで、5杯まで完走できる胃の余裕が生まれる。" },
      { type: "heading", content: "5杯目21時：長浜屋台「元祖長浜屋」で完全燃焼", level: 2 },
      { type: "text", content: "巡礼の最後は長浜ふ頭の「元祖長浜屋」で締める。細麺に白濁した豚骨スープ、シンプルな構成だが最も博多らしい一杯だ。深夜まで営業しており、最後の替え玉を「粉落とし（ほぼ生麺）」で頼む玄人の贅沢が、1日の締めくくりにふさわしい。" },
    ],
    relatedArticleSlugs: ["fukuoka-hakata-ramen-ranking", "fukuoka-nakasu-yatai-complete"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "fukuoka-green-season-guide",
    title: "福岡の新緑シーズン──5月の糸島と背振山系で出会う、九州の春が爆発する瞬間",
    description: "福岡の5月は新緑が爆発する月だ。桜より短命で、梅雨より先に来る。この2週間に糸島と背振山に行った人だけが見る景色を語る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "fukuoka",
    tags: ["新緑", "5月", "糸島", "ハイキング", "福岡"],
    spotIds: ["itoshima", "dazaifu"],
    sections: [
      { type: "heading", content: "5月第1週：糸島の麦畑と菜の花のコントラスト", level: 2 },
      { type: "text", content: "糸島の農村部では4月末〜5月初旬に麦畑が一面に広がる。緑の麦の穂と青い空のコントラストは、国内の農村風景の中でも別格の美しさだ。農道を走りながら窓を開けると麦の香りが入ってくる。カフェに向かう途中の「寄り道」として発見できる景色だ。" },
      { type: "spot-card", content: "itoshima" },
      { type: "heading", content: "太宰府の飛梅後の梅の実：6月の梅仕事体験", level: 2 },
      { type: "text", content: "太宰府天満宮の境内には梅の木が約6,000本植えられており、6月初旬には梅の実が落ち始める。一部の農家では梅仕事（梅干し・梅酒づくり）の体験プログラムを実施している。飛梅伝説の梅の子孫を実際に手で摘む体験は、参拝とは別次元の太宰府との関わり方だ。" },
      { type: "heading", content: "背振山の新緑トレイル：福岡市から1時間の別世界", level: 2 },
      { type: "text", content: "5月の背振山系は新緑の回廊が続く。杉と雑木林が交互に現れる登山道に、木漏れ日が揺れる。GW期間中でも山の中は静かで、頂上の開けた眺めは特に5月が清々しい。昼前に登頂して山頂でお弁当を食べる日帰りトレッキングが、福岡市民の5月の定番行事になっている。" },
    ],
    relatedArticleSlugs: ["fukuoka-itoshima-day-trip", "fukuoka-spring-sakura-routes"],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "fukuoka-northern-kyushu-day-trips",
    title: "博多発・日帰り旅5選──太宰府・糸島・門司港・唐津・嬉野に新幹線と在来線で行く",
    description: "博多駅は九州の鉄道ハブだ。ここを起点にすれば、佐賀・長崎・熊本まで日帰りで動ける。旅のベースを博多にすると九州全体が射程に入る。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "fukuoka",
    tags: ["日帰り旅", "博多駅", "交通", "九州旅行", "鉄道旅"],
    spotIds: ["hakata-station", "mojiko-retro"],
    sections: [
      { type: "heading", content: "唐津：博多から特急で1時間、玄界灘の城下町へ", level: 2 },
      { type: "text", content: "博多から唐津へは地下鉄・JR直通の特急「から松」で約1時間。唐津城は海に面した曲輪が美しく、玄界灘を望む天守閣からの眺めが格別だ。唐津焼の窯元も城下に点在する。日帰りなら10時着・16時発のスケジュールで十分に回れる。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "嬉野温泉：西九州新幹線で29分、佐賀の美肌の湯へ", level: 2 },
      { type: "text", content: "2022年開業の西九州新幹線「かもめ」で武雄温泉まで行き、在来線で嬉野温泉へ。博多から1時間15分で到達する。重曹泉のとろとろの湯は日帰り入浴¥600〜で体験でき、温泉湯豆腐の昼食と組み合わせると最高の日帰りコースになる。" },
      { type: "heading", content: "門司港：新幹線+JRで50分、大正ロマンの港町", level: 2 },
      { type: "text", content: "博多から小倉経由で門司港まで新幹線+JRで約50分。焼きカレーのランチと夜のライトアップを同じ日に楽しむなら、昼12時発→夜21時帰着のスケジュールが最適だ。関門海峡の渡し船（¥400）で下関まで往復するオプションも時間があれば加えたい。" },
    ],
    relatedArticleSlugs: ["fukuoka-mojiko-retro-walk", "fukuoka-hakata-station-guide"],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "fukuoka-shrine-tour",
    title: "福岡のパワースポット神社巡り──住吉神社・警固神社・竈門神社、それぞれのご利益と最適な参拝時間",
    description: "太宰府だけが福岡の神社ではない。市内に格式の高い神社が点在し、それぞれ異なるご利益を持つ。地元民が毎年参る神社の本当の姿を紹介する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "fukuoka",
    tags: ["神社", "パワースポット", "竈門神社", "縁結び", "福岡"],
    spotIds: ["dazaifu"],
    sections: [
      { type: "heading", content: "竈門神社：太宰府の奥に眠る縁結びの聖地", level: 2 },
      { type: "text", content: "竈門神社は太宰府天満宮から山道を30分歩いた先にある。縁結びのご利益で知られ、アニメ「鬼滅の刃」の影響もあって若者の参拝が急増した。社殿は宝満山の中腹に位置し、山全体が御神体だ。朝9時前の参拝は霧が立ち込めることがあり、神秘的な雰囲気になる。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "住吉神社：博多の守護神は1800年の歴史を持つ", level: 2 },
      { type: "text", content: "博多駅から徒歩5分の住吉神社は、全国に約2,300社ある住吉神社の中でも最古とされる。航海の神として海商人の博多を守ってきた歴史があり、博多祇園山笠の出発地点でもある。境内の力石（相撲の稽古用）や手水舎の龍は見逃せない。" },
      { type: "heading", content: "警固神社：天神の喧騒の中にある静かな森", level: 2 },
      { type: "text", content: "天神のど真ん中に位置する警固神社は、都市の中の緑のオアシスだ。参道の欅の木が夏は木陰を作り、秋は色づく。合格・就職・縁結びと幅広いご利益があり、受験シーズンには絵馬がびっしり掛けられる。昼休みに会社員が訪れる姿が日常の風景になっている。" },
    ],
    relatedArticleSlugs: ["fukuoka-dazaifu-early-morning", "fukuoka-new-year-hatsumode"],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "fukuoka-rainy-day-guide",
    title: "雨の日の福岡完全ガイド──博多駅・キャナルシティ・博多座で雨を楽しむ室内プラン",
    description: "梅雨の福岡で雨に降られたとき、屋台は閉まっている。しかし福岡の室内観光スポットは、雨の日こそ本領を発揮する場所が多い。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "fukuoka",
    tags: ["雨の日", "室内スポット", "博多座", "キャナルシティ", "福岡"],
    spotIds: ["hakata-station"],
    sections: [
      { type: "heading", content: "博多座：歌舞伎・ミュージカルを見る贅沢な雨の日", level: 2 },
      { type: "text", content: "博多座は九州最大の本格劇場で、月替わりの歌舞伎・ミュージカル・演歌コンサートが上演される。当日券は開演2時間前に並べば取れることが多い。3階席で¥3,000〜と手頃な価格で、プロの舞台芸術を初めて体験するには最高の入口になる。" },
      { type: "spot-card", content: "hakata-station" },
      { type: "heading", content: "キャナルシティ博多：雨が「演出」になる水路の空間", level: 2 },
      { type: "text", content: "キャナルシティ博多は中央の運河に降る雨が、建物全体の音響を変える。雨の日の中央広場の噴水ショーは、晴れの日とは全く違う空気になる。ショッピングより「建築を体験する」感覚で歩くと、設計者・ジョン・ジャーディが意図した都市の可能性が見えてくる。" },
      { type: "heading", content: "福岡市博物館：金印を見ながら半日を過ごす", level: 2 },
      { type: "text", content: "能古島近くの百道浜にある福岡市博物館は、日本史の教科書に必ず載る「漢委奴国王」の金印を所蔵する。実物は思ったより小さく（2.3cm角）、その小ささに驚く。常設展示は無料（企画展は有料）で、雨の日の半日を充実させる最高の選択肢だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-hakata-station-guide", "fukuoka-tenjin-shopping"],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "fukuoka-yakitori-guide",
    title: "博多の焼き鳥文化──なぜ福岡は「鶏の街」なのか、正しい食べ方と地鶏の産地を知る",
    description: "博多の焼き鳥は内臓文化だ。鶏皮・ハツ・砂肝・ぼんじりを炭火で焼く文化が、なぜここまで発展したのかを探りながら名店を案内する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "fukuoka",
    tags: ["焼き鳥", "博多", "地鶏", "居酒屋文化", "福岡"],
    spotIds: ["nakasu-yatai"],
    sections: [
      { type: "heading", content: "博多の焼き鳥は「鶏皮」から始まる", level: 2 },
      { type: "text", content: "博多の焼き鳥で最初に頼むべきは鶏皮だ。じっくり炭火で炙った皮はパリっと縮み、脂が落ちてコクが凝縮する。タレと塩の二択は必ず両方頼んで比べること。これをビールと合わせる時間が博多夜の正しい始まり方だ。" },
      { type: "spot-card", content: "nakasu-yatai" },
      { type: "heading", content: "天神「とりかわ粋恭」：鶏皮を20回巻いて串にする店", level: 2 },
      { type: "text", content: "天神の「とりかわ粋恭」は鶏皮専門の焼き鳥店だ。一本の串に鶏皮を20回転以上巻きつけて焼くことで、外はカリカリ中はジューシーに仕上げる独自の技法。行列覚悟だが、それだけの価値がある。1本200円、最低5本は食べること。" },
      { type: "heading", content: "大分地鶏「豊のしゃも」を出す博多の店を探せ", level: 2 },
      { type: "text", content: "大分県産の「豊のしゃも」は歯ごたえとうま味が段違いの地鶏だ。博多でこれを出す焼き鳥店は限られており、天神の「鶏笑」と中洲の「鶏ぶ」が代表的だ。塩焼きで食べると地鶏の本質が分かる。もも肉の刺身（鶏刺し）も鮮度が命の九州ならではの体験だ。" },
    ],
    relatedArticleSlugs: ["fukuoka-motsu-nabe-guide", "fukuoka-nakasu-yatai-complete"],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "fukuoka-3days-complete",
    title: "福岡3日間完全モデルコース2025──太宰府・糸島・中洲・門司港を全部回る最適ルート",
    description: "福岡3日間で行くべきスポットを全部入れようとすると必ず失敗する。優先順位の付け方と、日程別の最適な時間配分を完全版で解説する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "fukuoka",
    tags: ["モデルコース", "3日間", "完全ガイド", "九州旅行", "福岡"],
    spotIds: ["dazaifu", "itoshima", "nakasu-yatai", "hakata-station", "mojiko-retro"],
    sections: [
      { type: "heading", content: "1日目：博多駅着→中洲屋台で博多の夜に飛び込む", level: 2 },
      { type: "text", content: "到着日の夜は中洲屋台に直行する。荷物はホテルに置き、18時台に中洲川端駅へ。屋台を3軒はしごしてラーメン1杯・おでん・焼き鳥を食べる。1,500円で博多の夜が始まる。早起きに備えて22時には宿に戻ること。" },
      { type: "spot-card", content: "dazaifu" },
      { type: "heading", content: "2日目：太宰府8時→糸島11時→二見ヶ浦17時", level: 2 },
      { type: "text", content: "2日目は朝8時に太宰府天満宮を参拝し、9時にレンタカーで糸島へ移動。昼はカフェかランチ、午後は海岸散策。17時の夕日を二見ヶ浦で見届けてから博多に戻る。夕食は天神の割烹か居酒屋で九州料理を堪能する。" },
      { type: "heading", content: "3日目：門司港10時→14時帰路or博多駅でお土産", level: 2 },
      { type: "text", content: "最終日は北九州市門司港へ。新幹線+JRで50分。焼きカレーのランチを食べ、レトロ建築を歩いて14時に博多に戻る。博多駅で明太子・梅ヶ枝餅・とおりもんを購入して新幹線に乗る。この3日間が、初めての福岡として最も充実した記憶になる。" },
    ],
    relatedArticleSlugs: ["fukuoka-dazaifu-early-morning", "fukuoka-itoshima-day-trip", "fukuoka-nakasu-yatai-complete"],
  },
];
