import { Article } from "@/types/article";

export const gifuArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "gifu-shirakawago-winter",
    title: "白川郷の冬──雪の合掌造りとライトアップが作る、非現実の夜景",
    description: "ユネスコ世界遺産の集落が雪に埋まる冬の週末。世界中から人が来る理由がここにある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "gifu",
    tags: ["白川郷", "冬", "雪景色", "世界遺産", "岐阜"],
    spotIds: ["shirakawa-go"],
    sections: [
      { type: "heading", content: "冬のライトアップは1〜2月の土日に限定", level: 2 },
      { type: "text", content: "白川郷の冬ライトアップは1月〜2月の特定の土日夜間に開催される（年5〜6回程度）。事前に観光協会公式サイトで日程を確認し、シャトルバス乗車券（往復1,000円）を予約購入するのが必須。当日売りはなく、予約なしでは入場できない。" },
      { type: "spot-card", content: "shirakawa-go" },
      { type: "heading", content: "城山展望台からの俯瞰が一番の構図", level: 2 },
      { type: "text", content: "ライトアップ当日は集落内からの見学だけでなく、対岸の城山展望台からの俯瞰が最も美しい構図になる。雪原に浮かぶ合掌屋根が点灯する瞬間を展望台から見ると、白川郷の全体像が一枚の絵になる。展望台は急な坂道を徒歩15分で登る必要がある。" },
      { type: "heading", content: "平日の白川郷は別世界の静けさ", level: 2 },
      { type: "text", content: "ライトアップのない平日の冬は、集落内の観光客が激減する。雪道を歩きながら合掌造りの軒先を見上げ、煙突から出る煙の香りを感じ、囲炉裏のある民宿で夕食を食べる体験が、本来の白川郷旅。合掌造りの民宿「勇助」「かんどや」は1泊2食10,000〜15,000円で宿泊できる。" },
    ],
    relatedArticleSlugs: ["gifu-shirakawago-model-course", "gifu-gokayama-comparison"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "gifu-takayama-morning-market",
    title: "高山の朝市──陣屋前と宮川沿い、飛騨の食文化が7時に始まる",
    description: "朝7時から開く高山の朝市は、観光地でありながら地元の食文化が呼吸している場所。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-04-08",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "gifu",
    tags: ["高山", "朝市", "グルメ", "岐阜", "飛騨"],
    spotIds: ["takayama-old-town"],
    sections: [
      { type: "heading", content: "陣屋前朝市：高山陣屋の前で毎朝開く", level: 2 },
      { type: "text", content: "高山陣屋（旧幕府代官所）の前に毎朝7時から並ぶ「陣屋前朝市」は、地元の農家が漬物・野菜・民芸品を持ち込む市。年中無休で12月〜3月は8時〜12時の短縮営業。赤かぶの漬物（500円〜）と朴葉味噌（700円〜）が定番土産として人気。" },
      { type: "spot-card", content: "takayama-old-town" },
      { type: "heading", content: "宮川朝市：川沿いの50mに露店が並ぶ", level: 2 },
      { type: "text", content: "宮川沿いの「宮川朝市」は7時〜12時開催。農産物よりも観光客向けの民芸品・飛騨のお土産が多い構成になっている。朝食用に飛騨牛の串焼き（700〜900円）や、さるぼぼのストラップ（300〜600円）が並ぶ。橋の上から市の全景を見渡すと、飛騨の朝の活気が感じられる。" },
      { type: "heading", content: "朝市の後は古い町並みを人より早く歩く", level: 2 },
      { type: "text", content: "朝市が開く7〜8時台は古い町並み（三町）もほぼ無人。黒格子の商家が連なる通りを観光客ゼロで歩けるのは朝だけ。9時になると一気に人が増えるため、朝市→古い町並み散歩→朝食の順番で組むのが高山観光の正解。" },
    ],
    relatedArticleSlugs: ["gifu-hida-beef-guide", "gifu-takayama-model-course"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "gifu-gero-onsen-guide",
    title: "下呂温泉完全ガイド──日本三名泉の泉質と温泉街の正しい楽しみ方",
    description: "草津・有馬と並ぶ日本三名泉。飛騨川沿いの温泉街を、昼から夜まで使い切る計画を立てる。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-02-25",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "gifu",
    tags: ["下呂温泉", "温泉", "三名泉", "岐阜", "旅館"],
    spotIds: ["gero-onsen"],
    sections: [
      { type: "heading", content: "下呂温泉の泉質：アルカリ性単純温泉の意味", level: 2 },
      { type: "text", content: "下呂温泉のpHは8.9前後のアルカリ性単純温泉。肌に滑りを感じる「美人の湯」と呼ばれる理由は、アルカリ成分が肌の脂分を乳化させるため。温度は55〜80℃と高く、加水なしの源泉かけ流し施設では熱い湯に少量ずつ入ることが推奨される。" },
      { type: "spot-card", content: "gero-onsen" },
      { type: "heading", content: "無料の噴泉池で外国人旅行者と並んで入る", level: 2 },
      { type: "text", content: "飛騨川の河川敷にある「噴泉池」は下呂温泉の象徴的施設で、水着着用で無料入浴できる。昼間のみ利用可能（夜間は閉鎖）。外国人旅行者がここで温泉入浴を初体験するケースが多く、国際色豊かな温泉場になっている。水着は下呂駅前のコンビニで購入可能。" },
      { type: "heading", content: "日帰り入浴は「水明館」「湯之島館」が最高品質", level: 2 },
      { type: "text", content: "下呂温泉の老舗旅館「水明館」の日帰り入浴（1,500円、11〜14時）は飛騨川を見渡す大浴場が有名。「湯之島館」（昭和の名建築）は1,500円で入浴でき、建物自体が文化財的価値を持つ。温泉まんじゅうは白木屋・香りの里・清川屋など6軒以上が競合しており、食べ比べが正解。" },
    ],
    relatedArticleSlugs: ["gifu-takayama-morning-market", "gifu-hida-beef-guide"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "gifu-hida-beef-guide",
    title: "飛騨牛の食べ方全部──高山・下呂・岐阜市で比べる飛騨牛の頂点",
    description: "A5ランクの飛騨牛を最もおいしく食べられる場所と食べ方。立ち食い串から会席まで予算別に整理。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "gifu",
    tags: ["飛騨牛", "グルメ", "高山", "岐阜", "牛肉"],
    spotIds: ["takayama-old-town", "gero-onsen"],
    sections: [
      { type: "heading", content: "立ち食い：高山の古い町並みで飛騨牛串", level: 2 },
      { type: "text", content: "高山の古い町並み（三町）沿いには飛騨牛の串焼きを販売する店が複数ある。「肉の匠・やまで屋」の飛騨牛串（700〜900円）は火入れが絶妙で、歩きながら食べる高山スタイルの筆頭。油が多いので白いシャツは注意が必要。" },
      { type: "heading", content: "ランチ：飛騨牛にぎり寿司が最高コスパ", level: 2 },
      { type: "text", content: "高山駅前の「飛騨牛まぶし・てん」では飛騨牛のにぎり寿司セット（3貫1,500円）が食べられる。ランチ限定の飛騨牛丼（1,800円）もコスパが高い。1貫から注文できる飛騨牛握りは、1人旅でも気軽に飛騨牛を体験できる形式として最適。" },
      { type: "heading", content: "本格ステーキは「飛騨牛専門店 鳩谷」で", level: 2 },
      { type: "text", content: "高山市内の「鳩谷」は1963年創業の飛騨牛専門レストラン。A5飛騨牛のステーキコース（15,000円〜）は予約制。鉄板の上で仕上げる熟練の火入れは、飛騨牛の脂の甘さを最も引き出す調理法。特別な記念日の食事として、高山旅行の1食は必ずここに使いたい。" },
    ],
    relatedArticleSlugs: ["gifu-takayama-morning-market", "gifu-takayama-model-course"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "gifu-nagaragawa-ukai",
    title: "長良川鵜飼──1300年続く夜の漁を船上から見る、岐阜市の夏の風物詩",
    description: "篝火が川面を照らし、鵜が魚を捕る瞬間を目の前で見る。現役で続く日本最古の漁法。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "gifu",
    tags: ["長良川鵜飼", "岐阜", "夏", "伝統", "川"],
    spotIds: [],
    sections: [
      { type: "heading", content: "鵜飼は5月〜10月の夜間開催", level: 2 },
      { type: "text", content: "長良川の鵜飼（岐阜市）は5月11日〜10月15日に毎夜開催（満月・雨天中止除く）。観覧船は2人乗りから大型船まで種類があり、2名乗船の小型屋形船（2人3,600円〜）が最も川面に近くて迫力がある。乗船30分前に長良川観光センターへ集合。" },
      { type: "heading", content: "篝火と鵜の動きが作る夜の漁の美学", level: 2 },
      { type: "text", content: "鵜匠が松明を持ち、篝火の明かりで魚を集め、鵜が水に潜る。鵜の喉元を縛ることで魚が飲み込めないようにし、捕った魚を鵜匠が手繰り寄せて受け取る一連の動作は、1300年変わっていない。最も見ごたえがある「総がらみ」（複数の鵜が一斉に漁をする演目）は後半30分に行われる。" },
      { type: "heading", content: "鵜飼前に岐阜城で夕方の眺望を楽しむ", level: 2 },
      { type: "text", content: "鵜飼の乗船まで時間がある場合、長良川沿いにそびえる金華山（329m）の岐阜城（200円）に立ち寄る。ロープウェイ（往復1,080円）で山頂に上がると長良川と濃尾平野の夕景が広がる。ここから鵜飼の観覧船乗り場まで徒歩15分で移動できる。" },
    ],
    relatedArticleSlugs: ["gifu-gujohachiman-summer", "gifu-shirakawago-winter"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "gifu-gujohachiman-summer",
    title: "郡上八幡の夏──徹夜踊りと清流と城下町、岐阜の夏祭りの最高峰",
    description: "8月の徹夜踊りは夜通し続く。郡上おどりが日本最長の盆踊りとして世界に認められた理由。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "gifu",
    tags: ["郡上八幡", "郡上おどり", "夏祭り", "岐阜", "城下町"],
    spotIds: [],
    sections: [
      { type: "heading", content: "郡上おどりは7月〜9月の30夜以上", level: 2 },
      { type: "text", content: "郡上おどりは毎年7月中旬〜9月初旬に30夜以上開催される日本最長期間の盆踊り。8月13〜16日の「徹夜踊り」は文字通り夜10時から翌朝5時まで踊り続ける。踊りは誰でも参加可能で、輪の中に入れば地元の人が動きを教えてくれる。" },
      { type: "heading", content: "清流吉田川に飛び込む夏の名物", level: 2 },
      { type: "text", content: "郡上八幡を流れる吉田川は透明度が高く、夏に地元の子どもたちが橋の上から川に飛び込む「橋飛び」が名物。「新橋」からの飛び込みは高さ12mで大人でも勇気がいる。見ているだけでも十分楽しいが、水着があれば自分も参加できる。" },
      { type: "heading", content: "郡上八幡城と城下町を半日で歩く", level: 2 },
      { type: "text", content: "郡上八幡城（320円）は木造再建天守の中で日本最古（1933年再建）。城山から城下町全体と吉田川の蛇行が見渡せる。城下町の水路沿いには「やな平」の鮎料理（塩焼き800円）の店が並び、鮎の香りが路地を満たす。水の街として整備された城下町歩きは1時間半で全体を回れる。" },
    ],
    relatedArticleSlugs: ["gifu-nagaragawa-ukai", "gifu-takayama-morning-market"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "gifu-takayama-model-course",
    title: "高山1泊2日モデルコース──古い町並み・朝市・飛騨牛・高山祭を全部入れる",
    description: "「飛騨の小京都」を最大限に楽しむための2日間の設計。混まない動き方と食事の予算配分。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "gifu",
    tags: ["高山", "モデルコース", "古い町並み", "岐阜", "飛騨"],
    spotIds: ["takayama-old-town"],
    sections: [
      { type: "heading", content: "1日目午前：陣屋前朝市から始める", level: 2 },
      { type: "text", content: "高山駅着は9時台推奨。まず陣屋前朝市（7〜12時）へ直行し、地元の漬物を試食しながら市場の空気を感じる。その後、高山陣屋（440円）を見学してから古い町並みへ移動。陣屋内部は江戸時代の役所の構造が保存されており、城下町理解の基礎知識が得られる。" },
      { type: "spot-card", content: "takayama-old-town" },
      { type: "heading", content: "1日目昼：古い町並みで飛騨牛食べ歩き", level: 2 },
      { type: "text", content: "一之町〜三之町の古い町並みを1時間で歩く。飛騨牛の串焼き（700〜900円）を1〜2本食べながら歩くのが高山スタイル。昼食は酒蔵「二木酒造」隣のカフェで飛騨産そばを使ったランチ（1,200円）が人気。午後は飛騨民俗村「飛騨の里」（700円）で合掌造り建築を見学。" },
      { type: "heading", content: "2日目：高山祭屋台会館と帰路", level: 2 },
      { type: "text", content: "高山祭は春（4月14〜15日）と秋（10月9〜10日）の年2回。祭り期間外は「高山祭屋台会館」（1,000円）で精巧な屋台を間近に見られる。豪華な彫刻と「からくり人形」の実演は日本の祭礼文化の粋。名古屋・大阪方面へのアクセスはJR高山本線か高速バスで、名古屋まで約2時間半。" },
    ],
    relatedArticleSlugs: ["gifu-takayama-morning-market", "gifu-hida-beef-guide"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "gifu-shirakawago-model-course",
    title: "白川郷・五箇山1泊2日コース──世界遺産2か所を効率よく巡る旅程",
    description: "白川郷と五箇山は車で30分の距離。世界遺産の合掌造り集落を2か所、比べながら歩く贅沢。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "gifu",
    tags: ["白川郷", "五箇山", "世界遺産", "合掌造り", "岐阜"],
    spotIds: ["shirakawa-go"],
    sections: [
      { type: "heading", content: "1日目：白川郷で集落に一泊する", level: 2 },
      { type: "text", content: "名古屋から高速バスで2時間半（2,600円）。昼前に白川郷着。城山展望台からの俯瞰後、集落内を散策。合掌造りの民宿「神田家」（1泊2食15,000円〜）に宿泊すると、ライトアップ終了後の夜の集落の静けさと朝靄を体験できる。翌朝の朝食は囲炉裏のある食堂で山菜料理。" },
      { type: "spot-card", content: "shirakawa-go" },
      { type: "heading", content: "2日目：五箇山で静けさと対比を感じる", level: 2 },
      { type: "text", content: "白川郷から路線バスで30分の五箇山（相倉集落）は、白川郷より規模が小さく観光客が少ない。相倉集落内を歩くと農作業をする地元の人と挨拶できる距離感で、現役の集落としての生活感がある。相倉集落入場料（500円）は集落維持のための協力金。" },
      { type: "heading", content: "移動は車があると自由度が大幅に上がる", level: 2 },
      { type: "text", content: "白川郷・五箇山間は路線バスでも移動できるが、本数が少なく時刻表を事前確認が必要。レンタカーがあると相倉・菅沼の両集落を自分のペースで回れる。白川郷ICから北陸道に乗れば金沢まで約1時間で、富山・金沢方面への旅程拡張も容易になる。" },
    ],
    relatedArticleSlugs: ["gifu-shirakawago-winter", "gifu-gokayama-comparison"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "gifu-gokayama-comparison",
    title: "白川郷と五箇山の違い──世界遺産の隣人を比べて初めてわかること",
    description: "白川郷は有名、五箇山は静か。同じ世界遺産なのに全く異なる空気が漂う理由を考察する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "gifu",
    tags: ["白川郷", "五箇山", "比較", "世界遺産", "岐阜"],
    spotIds: ["shirakawa-go"],
    sections: [
      { type: "heading", content: "白川郷：観光地化と生活の同居", level: 2 },
      { type: "text", content: "白川郷荻町集落は114棟の合掌造りが現存し、その多くが民宿・食堂・土産物屋として観光客向けに営業している。年間100万人以上が訪れるため、週末昼間は観光地の顔が強くなる。一方で地元農家が畑を耕す姿が集落内に普通に見られ、観光と農業が共存する独特の空間を作っている。" },
      { type: "heading", content: "五箇山：外界から遮断された秘境感が今も残る", level: 2 },
      { type: "text", content: "五箇山は江戸時代に火薬原料の塩硝製造を秘密裏に行っていた地区で、外界との交流が制限された歴史がある。この孤立の歴史が集落に独特の文化を育てた。現在もアクセスが不便で、バスの便数が少ないためツアー客が来づらい環境がある。この不便さが五箇山の静けさを守っている。" },
      { type: "heading", content: "どちらを選ぶか：観光目的で考える", level: 2 },
      { type: "text", content: "「写真を撮りたい」「迫力の雪景色を見たい」なら白川郷。「静かに集落を歩きたい」「地元の人と触れ合いたい」なら五箇山が向いている。理想は両方に1泊ずつすることだが、時間がなければ白川郷1泊の後に五箇山を2〜3時間かけて歩き、富山方向へ移動するルートが最も密度が高い。" },
    ],
    relatedArticleSlugs: ["gifu-shirakawago-winter", "gifu-shirakawago-model-course"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "gifu-couple-gero-stay",
    title: "カップルで下呂温泉──湯煙の夜と朝食、飛騨川沿いの旅館で過ごす2日間",
    description: "日本三名泉で一晩。飛騨川の風景と美人の湯と温泉まんじゅうで組み立てる、完璧な温泉旅。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-10-25",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "gifu",
    tags: ["下呂温泉", "カップル", "温泉旅館", "岐阜", "旅館"],
    spotIds: ["gero-onsen"],
    sections: [
      { type: "heading", content: "チェックインは15時・まずひと風呂", level: 2 },
      { type: "text", content: "下呂温泉駅から主要旅館まで徒歩10分以内。「水明館」（1泊2食30,000円〜）は日本建築の名作で知られる「飛泉閣」客室が飛騨川を見下ろす特等席。チェックイン後すぐに客室の展望風呂か大浴場へ。日が落ちる前の夕日が飛騨川を染める時間に外景が見える浴室で過ごすのが理想。" },
      { type: "spot-card", content: "gero-onsen" },
      { type: "heading", content: "夕食後は温泉街の夜散歩", level: 2 },
      { type: "text", content: "夕食後、浴衣で温泉街を散歩するのが下呂の定番。朱色にライトアップされた「湯之島橋」（幸橋）は橋の上から飛騨川と温泉街の夜景が見渡せる。川面に映るライトの揺らめきが特に美しい場所。温泉まんじゅう巡りは夜も数軒が営業しており、2人で食べ比べる理由ができる。" },
      { type: "heading", content: "翌朝の朝風呂→朝食→帰路", level: 2 },
      { type: "text", content: "下呂温泉の旅館の朝風呂は6時台に入れることが多い。朝の冷気の中、熱い湯に入って飛騨川を眺める30分が旅の最後を締めくくる。朝食後、みやげ物店が開く9時台に温泉街を歩いて帰路につく。名古屋まではJR特急「ひだ」で1時間40分（自由席4,000円前後）。" },
    ],
    relatedArticleSlugs: ["gifu-gero-onsen-guide", "gifu-takayama-model-course"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "gifu-family-takayama",
    title: "子連れ高山旅行──古い町並み・からくり人形・飛騨の里で家族の記憶を作る",
    description: "高山は子どもを連れて行きやすい観光地。江戸時代の仕掛けと自然体験が一か所に揃っている。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-07-30",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "gifu",
    tags: ["子連れ", "高山", "家族旅", "岐阜", "からくり"],
    spotIds: ["takayama-old-town"],
    sections: [
      { type: "heading", content: "高山祭屋台のからくり人形実演が子ども向けベストコンテンツ", level: 2 },
      { type: "text", content: "高山祭屋台会館（1,000円、小学生500円）のからくり人形実演は1日3回。精巧な仕掛けで動く人形が綱渡りや踊りを披露する江戸時代の機械工学。子どもが目を丸くして見る体験で、「昔の人が作った機械仕掛け」という説明をすると興味が増す。" },
      { type: "spot-card", content: "takayama-old-town" },
      { type: "heading", content: "飛騨の里で合掌造り体験", level: 2 },
      { type: "text", content: "市街地から車で10分の「飛騨の里」（700円）は移築した合掌造り建築が集まる野外博物館。建物の中に入れる施設が多く、囲炉裏・農具・昔の台所を子どもが実際に見て触れられる。売店ではさるぼぼ（飛騨の縁起物人形）の絵付け体験（500円）が子ども向けに大人気。" },
      { type: "heading", content: "子ども向け食事：みたらし団子と飛騨ラーメン", level: 2 },
      { type: "text", content: "高山のみたらし団子（醤油味・1本100円）は子どもが喜ぶ食べ歩きアイテム。砂糖を使わず醤油だけで味付けする高山独自スタイルで、甘くない串団子として珍しい。飛騨ラーメン（醤油ベース・細麺・700〜850円）は子どもでも食べやすい優しい味で、古い町並み近くに専門店が複数ある。" },
    ],
    relatedArticleSlugs: ["gifu-takayama-model-course", "gifu-takayama-morning-market"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "gifu-budget-shirakawago",
    title: "節約で行く白川郷──日帰りバスツアーと無料散策で世界遺産を体験する",
    description: "白川郷は日帰りでも十分楽しめる。高速バス・無料見学・格安食事で完結するコストゼロ旅。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-25",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "gifu",
    tags: ["節約旅", "白川郷", "日帰り", "岐阜", "バジェット"],
    spotIds: ["shirakawa-go"],
    sections: [
      { type: "heading", content: "名古屋発高速バスが最安手段", level: 2 },
      { type: "text", content: "名古屋駅から白川郷行きの高速バスは片道2,600円・約2時間半。白馬・金沢方面から来る場合も高速バスが最安で、金沢から片道1,500円・約1時間15分。行程は「白川郷BT」で降りて集落まで徒歩3分。集落内の見学は無料なので、バス代だけで来ることができる。" },
      { type: "spot-card", content: "shirakawa-go" },
      { type: "heading", content: "食費：飛騨牛コロッケとみたらし団子で節約", level: 2 },
      { type: "text", content: "集落内の食堂は1,500〜3,000円と観光地価格だが、食べ歩きで食費を抑えられる。飛騨牛コロッケ（300〜400円）・みたらし団子（2本200円）・五平餅（300〜400円）を組み合わせると、1,000円以内で飛騨の食を体験できる。持参したおにぎりを城山展望台で食べるのも正解。" },
      { type: "heading", content: "無料で楽しめるすべて", level: 2 },
      { type: "text", content: "城山展望台（無料・15分歩く）・合掌造り外観見学（無料）・宮川の河原散歩（無料）は追加費用ゼロ。有料施設に入るとしたら「和田家」（300円）か「長瀬家」（300円）の1か所のみに絞ると、交通費込みで6,000円以内で白川郷を体験できる。" },
    ],
    relatedArticleSlugs: ["gifu-shirakawago-winter", "gifu-shirakawago-model-course"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "gifu-luxury-hida-stay",
    title: "飛騨の贅沢宿──高山・下呂で選ぶべき高級旅館と特別な夕食",
    description: "飛騨牛と温泉と合掌造り。岐阜の山奥にある日本旅館の最高峰を、予算別に整理する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "gifu",
    tags: ["贅沢旅", "高山", "下呂温泉", "高級旅館", "岐阜"],
    spotIds: ["takayama-old-town", "gero-onsen"],
    sections: [
      { type: "heading", content: "高山：料亭旅館「懐石料理 坂口屋」で飛騨の粋", level: 2 },
      { type: "text", content: "高山市内の「料理旅館 坂口屋」は1泊2食35,000円〜の懐石料理専門旅館。夕食は飛騨牛を中心にした全12品の飛騨懐石で、飛騨春慶塗の器に盛られた料理は美術品としての価値もある。古い町並みから徒歩3分の立地で、夕食後の夜の散歩まで完結できる環境が整っている。" },
      { type: "heading", content: "下呂：水明館「飛泉閣」客室で飛騨川を独り占め", level: 2 },
      { type: "text", content: "「水明館」の「飛泉閣」は昭和30年代に建てられた日本建築の名作。飛騨川に面した客室から温泉につかりながら川を見下ろせる眺めは、下呂温泉で最高の体験。1泊2食45,000〜80,000円と幅があるが、川向きの客室を指定すれば35,000円台から選べる。" },
      { type: "heading", content: "白川郷：合掌造り民宿での宿泊体験", level: 2 },
      { type: "text", content: "高級とは違う「贅沢」として、白川郷の合掌造り民宿への宿泊がある。「勇助」「かんどや」「孫右エ門」などの民宿（1泊2食15,000〜20,000円）は現役の合掌造り家屋に宿泊でき、囲炉裏端での夕食と早朝の霧に包まれた集落を独占する体験は、どんな高級旅館にもない唯一性がある。" },
    ],
    relatedArticleSlugs: ["gifu-couple-gero-stay", "gifu-takayama-model-course"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "gifu-solo-takayama",
    title: "一人で行く高山──早朝の古い町並みから酒蔵まで、飛騨を独りで歩く",
    description: "高山は一人旅が最も似合う町のひとつ。人のいない朝の路地と昼の賑わいの落差を楽しむ。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-05-16",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "gifu",
    tags: ["一人旅", "高山", "古い町並み", "酒蔵", "岐阜"],
    spotIds: ["takayama-old-town"],
    sections: [
      { type: "heading", content: "早朝7時の古い町並みは一人のための空間", level: 2 },
      { type: "text", content: "7時台の三町伝統的建造物群保存地区は、観光客がほぼいない。地元の人が犬の散歩をしたり、商家の主人が軒先を掃除している姿だけがある。この時間帯に古い町並みを歩くと、高山が生きている城下町であることが実感できる。カメラを持った一人旅に最高の時間。" },
      { type: "spot-card", content: "takayama-old-town" },
      { type: "heading", content: "酒蔵は一人で入りやすい", level: 2 },
      { type: "text", content: "高山の古い町並みには「二木酒造」「舩坂酒造店」「平瀬酒造」など複数の酒蔵が酒の試飲と販売を行っている。一人で小さな酒器を手に取り、杉玉の下で試飲する体験は、グループよりも一人の方が丁寧に説明してもらいやすい。飛騨の地酒（辛口・720ml 1,500〜2,000円）は最適な土産。" },
      { type: "heading", content: "夜は居酒屋で飛騨のローカルな食を食べる", level: 2 },
      { type: "text", content: "高山の夜は駅前周辺の居酒屋で朴葉味噌焼き・飛騨牛にぎり・山菜の和え物を一人でゆっくり食べる時間がある。「有喜屋（うきや）」は地元客も多い肉割烹居酒屋で、飛騨牛のユッケ（900円）と朴葉焼き（1,200円）が一人飲みの定番。日本酒の品揃えも良く、一杯600〜900円で飛騨の銘柄を飲み比べられる。" },
    ],
    relatedArticleSlugs: ["gifu-takayama-morning-market", "gifu-takayama-model-course"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "gifu-hoba-miso-culture",
    title: "朴葉味噌の文化──飛騨の食卓を支える山の葉と発酵の話",
    description: "朴葉の上に味噌を乗せて焼く。飛騨の家庭料理が旅館料理になった背景と、正しい食べ方。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-03-30",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "gifu",
    tags: ["朴葉味噌", "飛騨", "郷土料理", "岐阜", "グルメ"],
    spotIds: ["takayama-old-town", "gero-onsen"],
    sections: [
      { type: "heading", content: "朴葉は飛騨の食文化の中心", level: 2 },
      { type: "text", content: "朴葉（ほおばのは）は飛騨地方に自生する朴の木の葉で、抗菌作用がある。冬に食料が乏しかった飛騨の農家が保存食の味噌を温めるために使ったのが朴葉味噌の起源。葉の上に飛騨味噌・ネギ・きのこ・飛騨牛を乗せ、コンロで焼きながら食べるスタイルが旅館料理として確立した。" },
      { type: "heading", content: "朴葉味噌の正しい食べ方", level: 2 },
      { type: "text", content: "朴葉を焦がさない程度の弱火でじっくり温め、味噌が泡立ち始めたら具材を混ぜながら食べるのが正解。白ご飯との相性が最高で、1枚の朴葉味噌で茶碗2杯分のご飯が進む。飛騨牛が入ったバージョン（旅館料金で3,000円前後）は味噌の甘みと牛肉の脂の組み合わせが絶品。" },
      { type: "heading", content: "土産として朴葉味噌を持ち帰る", level: 2 },
      { type: "text", content: "朴葉味噌は真空パックで販売されており、冷蔵で2週間ほど保存できる。高山の「奥飛騨食品」が作る朴葉味噌（1パック400〜700円）は自宅のガスコンロでも楽しめる。乾燥した朴葉も別売りされており、自分で味噌を乗せて家庭で朴葉焼きが再現できる。" },
    ],
    relatedArticleSlugs: ["gifu-hida-beef-guide", "gifu-solo-takayama"],
  },
];
