import { Article } from "@/types/article";

export const hiroshimaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "hiroshima-peace-memorial-guide",
    title: "原爆ドームと平和記念公園──1945年8月6日の記憶と向き合う半日",
    description: "広島を訪れるなら、観光の前に平和記念公園を歩くべきだ。その理由と、資料館の前に何を見るかを伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-06",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hiroshima",
    tags: ["原爆ドーム", "平和記念公園", "広島", "世界遺産", "歴史"],
    spotIds: ["atomic-bomb-dome"],
    sections: [
      { type: "heading", content: "元安川越しに原爆ドームを見る", level: 2 },
      { type: "text", content: "原爆ドームを最初に見るなら、平和記念公園の南側、元安川に架かる橋の上からの眺めが正しい。川の向こうに廃墟のような遺構が静かに立つ景観は、何も知らなくても言葉を失わせる。観光客の写真を撮る場所ではなく、まず黙って見る場所だ。" },
      { type: "spot-card", content: "atomic-bomb-dome" },
      { type: "heading", content: "広島平和記念資料館は「見る覚悟」を持って入る", level: 2 },
      { type: "text", content: "平和記念資料館の展示は重い。被爆者の遺品・熱線で溶けた瓦・皮膚の写真。事前に「見るための覚悟」を持って入ることをすすめる。展示は約1時間だが、急いで出てはいけない場所だ。特に子どもを連れている場合、帰り道に話し合う時間を作ってほしい。" },
      { type: "heading", content: "原爆の子の像に届く千羽鶴", level: 2 },
      { type: "text", content: "平和記念公園内の「原爆の子の像」は、白血病で亡くなった佐々木禎子さんをモデルに建てられた。現在も世界中の学校から千羽鶴が届き続け、像の周囲は常に色とりどりの折り鶴で満たされている。静かに手を合わせることが、広島旅行の本来の出発点になる。" },
    ],
    relatedArticleSlugs: ["hiroshima-okonomiyaki-guide", "hiroshima-miyajima-daytrip"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "hiroshima-miyajima-daytrip",
    title: "宮島・厳島神社──満潮と干潮で2度楽しむ大鳥居の攻略法",
    description: "厳島神社の大鳥居は満潮と干潮で全く違う顔を見せる。潮位を確認して「2つの鳥居」を一日で体験する方法。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hiroshima",
    tags: ["厳島神社", "宮島", "大鳥居", "満潮", "広島"],
    spotIds: ["itsukushima-shrine"],
    sections: [
      { type: "heading", content: "潮位表を事前に確認する習慣", level: 2 },
      { type: "text", content: "厳島神社を最大限に楽しむには「宮島潮位表」の確認が必須だ。満潮時（海に浮かぶ鳥居）と干潮時（鳥居まで歩ける）の時間帯を事前に把握し、旅程を組む。理想は午前中が満潮、午後が干潮か、その逆のパターンだ。" },
      { type: "spot-card", content: "itsukushima-shrine" },
      { type: "heading", content: "干潮時に鳥居まで歩いて触れる", level: 2 },
      { type: "text", content: "干潮になると鳥居の根本まで歩いて近づける。鳥居の柱を手で触ると、木材の表面に潮の塩分が染み込んでいることが感じられる。高さ16mの柱を下から見上げると、満潮時の「浮いている」イメージとは全く別の、圧倒的な大きさが伝わる。" },
      { type: "heading", content: "もみじ饅頭の食べ比べは外せない", level: 2 },
      { type: "text", content: "宮島の参道にはもみじ饅頭の老舗が複数ある。焼きたての揚げもみじ饅頭（天ぷら仕立て）は宮島独自の食べ方で、外はカリカリ・中はもちっとした食感が病みつきになる。こしあん・つぶあん・チーズ・チョコなど種類が多いため、1〜2個ずつ試食するのが正解だ。" },
    ],
    relatedArticleSlugs: ["hiroshima-miyajima-momiji", "hiroshima-peace-memorial-guide"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "hiroshima-miyajima-momiji",
    title: "宮島の紅葉──11月の紅葉谷公園と夜間の幻想的な灯り",
    description: "宮島の紅葉は厳島神社だけでなく、紅葉谷公園が本番だ。島全体が赤く染まる11月の宮島の楽しみ方。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hiroshima",
    tags: ["宮島", "紅葉", "紅葉谷公園", "秋", "広島"],
    spotIds: ["itsukushima-shrine"],
    sections: [
      { type: "heading", content: "紅葉谷公園は奥へ進むほど深くなる", level: 2 },
      { type: "text", content: "宮島の紅葉の中心は厳島神社の奥にある紅葉谷公園だ。公園入口から奥へ進むにつれて渓谷が深くなり、モミジとカエデの密度が増す。弥山（みせん）へのロープウェイ乗り場までの遊歩道が紅葉の核心地帯で、往復約1時間の散策コースが整備されている。" },
      { type: "heading", content: "弥山の山頂から見る秋の瀬戸内", level: 2 },
      { type: "text", content: "ロープウェイで弥山山頂（標高535m）まで上がると、紅葉に染まった宮島全体と、瀬戸内に浮かぶ島々が見渡せる。晴れた11月の澄んだ空気の中で見る山頂からの眺望は、夏や春とは全く異なる奥行きを持っている。" },
      { type: "heading", content: "紅葉期の宿泊で夜の厳島神社へ", level: 2 },
      { type: "text", content: "宮島に一泊すると夜の厳島神社にアクセスできる。宿泊者は最終フェリー後の島を独占に近い形で歩ける。夜間ライトアップされた大鳥居と社殿は昼間とは全く別の神秘的な顔を持つ。紅葉期の宿泊は6〜8ヶ月前からの予約が必要になる。" },
    ],
    relatedArticleSlugs: ["hiroshima-miyajima-daytrip", "hiroshima-onomichi-walk"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "hiroshima-okonomiyaki-guide",
    title: "広島お好み焼き入門──大阪との違いと、外せない名店の選び方",
    description: "広島風お好み焼きは「混ぜ焼き」ではなく「重ね焼き」だ。生地・キャベツ・麺の層が持つ意味と名店の選び方。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-02-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hiroshima",
    tags: ["お好み焼き", "広島グルメ", "広島風", "鉄板", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "「重ね焼き」の構造を知る", level: 2 },
      { type: "text", content: "広島風お好み焼きは薄い生地の上にキャベツを山盛りに乗せ、豚バラ・天かす・ネギを重ね、別で焼いた中華麺（または焼きそば）と合わせる「重ね焼き」スタイルだ。大阪式の「混ぜ焼き」とは工程も食感も全く異なる。鉄板の前に座って作る工程を見るのが楽しみの一部だ。" },
      { type: "heading", content: "お好み村と「鉄板ひとつ」の文化", level: 2 },
      { type: "text", content: "広島市中区には「お好み村」という約25店舗が入るビルがある。ここは高度経済成長期に屋台から始まったお好み焼き文化の集積地で、各店が独自の焼き方・具材・ソースを持つ。初めて広島風を食べるなら、ここで複数店を食べ比べるのが最も効率的だ。" },
      { type: "heading", content: "広島名物「ネギ焼き」と「カキ入り」", level: 2 },
      { type: "text", content: "通常のお好み焼きに加えて、冬季限定の「広島カキ入り」は必ず試してほしい一品。大粒の広島産カキがお好み焼きの中で蒸し焼き状態になり、牡蠣のエキスが生地全体に染み込む。シーズン（10月〜3月）限定のため、時期に合わせて訪問することをすすめる。" },
    ],
    relatedArticleSlugs: ["hiroshima-oyster-guide", "hiroshima-peace-memorial-guide"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "hiroshima-oyster-guide",
    title: "広島カキの食べ方全集──生カキ・焼きガキ・カキフライの正解",
    description: "全国生産量7割を占める広島のカキ。宮島・江田島・呉と産地別の食べ方の違いを徹底解説する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hiroshima",
    tags: ["広島カキ", "牡蠣", "宮島", "グルメ", "広島"],
    spotIds: ["itsukushima-shrine"],
    sections: [
      { type: "heading", content: "宮島の焼きガキ──炭火で焦げ目がつく瞬間", level: 2 },
      { type: "text", content: "宮島の表参道商店街では、炭火で焼いた焼きガキを立ち食いできる。1個100〜150円で提供される店が多く、殻の中に閉じ込められた塩水ごと熱される香ばしい焼きガキは、宮島グルメの中でも特別な位置にある。軍手を渡されるので手も汚れない。" },
      { type: "heading", content: "江田島の生カキ──産地直売で新鮮なまま食べる", level: 2 },
      { type: "text", content: "広島湾に浮かぶ江田島は、カキ養殖業者が直接販売する施設が充実している。11月〜3月のシーズン中、船で江田島に渡って養殖業者の直売所でカキを食べる体験は、広島市内の飲食店とは比較にならない鮮度を提供してくれる。" },
      { type: "heading", content: "カキフライは衣の厚さで店を選ぶ", level: 2 },
      { type: "text", content: "広島市内の洋食屋でカキフライを頼む際は、衣の厚さに注目してほしい。薄衣でカキの大きさをダイレクトに味わえるタイプと、厚衣でサクサク感を楽しむタイプがある。広島のカキは大粒のため、どちらのスタイルでも満足感が高い。" },
    ],
    relatedArticleSlugs: ["hiroshima-okonomiyaki-guide", "hiroshima-miyajima-daytrip"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "hiroshima-onomichi-walk",
    title: "尾道を歩く──坂と猫と寺と文学の街を解読する半日",
    description: "尾道は知っているようで知らない街だ。猫の小道・文学のこみち・千光寺展望台をつなぐ歩き方の完全版。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-18",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "hiroshima",
    tags: ["尾道", "猫", "坂道", "文学", "広島"],
    spotIds: ["onomichi"],
    sections: [
      { type: "heading", content: "ロープウェイより「猫の小道」を登る", level: 2 },
      { type: "text", content: "尾道の千光寺公園へ向かうには、ロープウェイを使う方法と「猫の小道」を歩いて登る方法がある。猫の小道は急勾配の石段と細い路地が続く道で、あちこちに猫が潜んでいる。写真を撮りながら登ると約40分かかるが、尾道の真髄はこの道にある。" },
      { type: "spot-card", content: "onomichi" },
      { type: "heading", content: "文学のこみちを文人の言葉で歩く", level: 2 },
      { type: "text", content: "千光寺公園の斜面に刻まれた「文学のこみち」は、林芙美子・志賀直哉・正岡子規ら尾道ゆかりの文人25人の詩歌・句碑が続く遊歩道だ。作品の内容を読みながら尾道の景観と重ねると、文学と場所が一体化した不思議な体験になる。" },
      { type: "heading", content: "千光寺公園展望台で瀬戸内と向島を眺める", level: 2 },
      { type: "text", content: "猫の小道・文学のこみちを登り切ると千光寺公園展望台に到着する。眼下に尾道水道と向島が広がり、しまなみ海道の島々の連なりも晴れた日は見渡せる。展望台の石畳のベンチに座って瀬戸内の風を受ける時間が、尾道旅行の記憶として最後まで残る。" },
    ],
    relatedArticleSlugs: ["hiroshima-shimanami-cycle", "hiroshima-onomichi-ramen"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "hiroshima-onomichi-ramen",
    title: "尾道ラーメン──背脂と平打ち麺の個性的な一杯の正体",
    description: "尾道ラーメンは豚骨と魚介を合わせた醤油スープに背脂が浮く。この組み合わせが生まれた理由と名店ガイド。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hiroshima",
    tags: ["尾道ラーメン", "ラーメン", "尾道グルメ", "B級グルメ", "広島"],
    spotIds: ["onomichi"],
    sections: [
      { type: "heading", content: "尾道ラーメンの構造──背脂が肝心", level: 2 },
      { type: "text", content: "尾道ラーメンは豚骨と瀬戸内の小魚（コイワシなど）を合わせた醤油ベースのスープに、豚の背脂を浮かせた独特のスタイルだ。平打ちの中太麺がスープをよく絡める。表面の背脂は見た目より重くなく、旨みのコーティングとしてスープ全体の味を引き締める役割を持つ。" },
      { type: "heading", content: "JR尾道駅前の名店は開店前から並ぶ", level: 2 },
      { type: "text", content: "尾道ラーメンの有名店はJR尾道駅の近くに集中している。「朱華園」（現在閉店）の後継文化を継ぐ店や新世代のラーメン店が複数ある。週末の昼時は行列が必至のため、平日の開店直後（11時〜11時30分）を狙うのが最も賢い選択だ。" },
      { type: "heading", content: "食べ比べるなら2〜3軒はしご", level: 2 },
      { type: "text", content: "尾道ラーメンは店によってスープの魚介感・背脂の量・麺の太さが微妙に異なる。半ラーメン（通常の半分量）を提供している店があるため、2〜3軒をはしごして自分好みの一杯を見つける楽しみ方が尾道では定着している。" },
    ],
    relatedArticleSlugs: ["hiroshima-onomichi-walk", "hiroshima-shimanami-cycle"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "hiroshima-shimanami-cycle",
    title: "しまなみ海道サイクリング──尾道から今治まで1泊2日の走り方",
    description: "世界最高峰のサイクリングロードを走る。全長約70kmを1泊2日で走り切るための計画と準備を完全解説する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "hiroshima",
    tags: ["しまなみ海道", "サイクリング", "瀬戸内", "自転車", "広島"],
    spotIds: ["shimanami-kaido", "onomichi"],
    sections: [
      { type: "heading", content: "1日目：尾道〜大三島（約40km）", level: 2 },
      { type: "text", content: "尾道駅そばのレンタサイクルターミナルで自転車を借り、向島・因島・生口島を渡る。大三島の大山祇神社で国宝の奉納武具を見学し、大三島の道の駅「多々羅しまなみ公園」に隣接したサイクリストの聖地碑で写真を撮る。1日目の宿は大三島か伯方島に確保する。" },
      { type: "spot-card", content: "shimanami-kaido" },
      { type: "heading", content: "2日目：大三島〜今治（約30km）", level: 2 },
      { type: "text", content: "2日目は伯方島・大島を渡り、来島海峡大橋を渡って今治へ。来島海峡大橋は全長4,105mで世界最長クラスの連続3橋。橋から見える来島海峡の潮の流れは迫力がある。今治でサンライズ糸山に自転車を返却し、JRで帰路につく。" },
      { type: "heading", content: "橋の上で写真を撮るための時間配分", level: 2 },
      { type: "text", content: "各橋には写真撮影の定番スポットがある。多々羅大橋の塔の上・伯方・大島大橋の真ん中・来島海峡大橋と島の重なりが見えるポイント。橋ごとに5〜10分停車する時間を見込んでスケジュールを組むと、走行と撮影を両立できる。" },
    ],
    relatedArticleSlugs: ["hiroshima-onomichi-walk", "hiroshima-shimanami-partial"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "hiroshima-shimanami-partial",
    title: "プチしまなみ──大三島だけ渡るサイクリストの正直なすすめ",
    description: "全線走破が難しくても「大三島だけ」ならしまなみ海道の本質を体験できる。半日コースの具体的な計画。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hiroshima",
    tags: ["しまなみ海道", "大三島", "プチしまなみ", "半日", "広島"],
    spotIds: ["shimanami-kaido"],
    sections: [
      { type: "heading", content: "今治からフェリーで大三島に渡る", level: 2 },
      { type: "text", content: "JR今治駅から市営バスで「今治港」へ移動し、フェリーで大三島の盛港（もりのみなと）へ約40分。ここでレンタサイクルを借りて島内を周回する。島一周は約30kmで3〜4時間の半日コースだ。全線走破よりも「大三島をじっくり味わう」選択肢として最適だ。" },
      { type: "heading", content: "大山祇神社と国宝の武具", level: 2 },
      { type: "text", content: "大三島の中心地にある大山祇神社は全国の山と海の神を祀る古社で、武将たちが奉納した国宝の甲冑・刀剣が収蔵されている。国宝・重要文化財の数は全国の刀剣・甲冑のおよそ4割が集まるとされ、博物館的な価値がある。" },
      { type: "heading", content: "多々羅大橋の下で橋の迫力を感じる", level: 2 },
      { type: "text", content: "大三島と生口島を結ぶ多々羅大橋の脚元まで自転車で走ると、橋の巨大さと構造の美しさが至近距離で体感できる。「サイクリストの聖地」碑の前は毎日多くのサイクリストが記念撮影する場所。ここで一枚撮影することが、しまなみを走った証明になる。" },
    ],
    relatedArticleSlugs: ["hiroshima-shimanami-cycle", "hiroshima-onomichi-walk"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "hiroshima-shukkeien-garden",
    title: "縮景園──広島市内で見つける江戸の静寂",
    description: "原爆で壊滅した広島の中心部に、江戸時代から続く大名庭園が再建されている。縮景園の知られざる深みを伝える。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-30",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "hiroshima",
    tags: ["縮景園", "庭園", "広島市内", "歴史", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "1620年から続く広島藩の庭園", level: 2 },
      { type: "text", content: "縮景園は1620年に広島藩浅野家の別邸として造営された回遊式庭園だ。1945年の原爆で庭園は壊滅的な被害を受けたが、戦後に復元された。現在も春の桜・夏のハス・秋の紅葉と四季折々の表情を見せ、広島市民の憩いの場になっている。" },
      { type: "heading", content: "濯纓池（たくえいち）を中心に歩く", level: 2 },
      { type: "text", content: "縮景園の中心は「濯纓池（たくえいち）」と呼ばれる池だ。池の周囲を回遊しながら茶室・橋・島を組み合わせた景観を楽しむ。池の水面に松と石灯籠が映る朝の光景は、300年の歴史を感じさせる静寂な美しさがある。" },
      { type: "heading", content: "県立美術館と合わせて回る動線", level: 2 },
      { type: "text", content: "縮景園に隣接する広島県立美術館は、国内外の美術品を収蔵する公立美術館だ。縮景園（入園料260円）と美術館を合わせて半日のコースにすると、広島市内観光に深みが加わる。平和記念公園だけでない広島の側面を知る機会になる。" },
    ],
    relatedArticleSlugs: ["hiroshima-peace-memorial-guide", "hiroshima-okonomiyaki-guide"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "hiroshima-kure-yamato",
    title: "呉の戦艦大和ミュージアム──艦船の街の歴史と海自カレー",
    description: "広島から電車30分の呉市は、戦艦大和を建造した軍港の街だ。大和ミュージアムと海上自衛隊の展示艦を訪問する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hiroshima",
    tags: ["呉", "大和ミュージアム", "戦艦大和", "海上自衛隊", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "大和ミュージアムの10分の1模型が圧巻", level: 2 },
      { type: "text", content: "「大和ミュージアム（呉市海事歴史科学館）」のメインは戦艦大和の10分の1スケール模型。全長26.3mの模型は館内の吹き抜け空間に展示され、下から見上げると実際の大きさが想像できる。戦艦の設計技術と呉の軍港としての歴史が詳細に展示されている。" },
      { type: "heading", content: "てつのくじら館では実物の潜水艦に乗れる", level: 2 },
      { type: "text", content: "大和ミュージアムの隣にある「てつのくじら館」は無料で入館できる海上自衛隊の展示施設だ。実物の潜水艦（あきしお）の内部を見学できる国内唯一の施設で、狭い艦内の居住空間と計器類を実際に見て回れる。" },
      { type: "heading", content: "海自カレーは護衛艦レシピの本物", level: 2 },
      { type: "text", content: "呉市内の複数の飲食店では海上自衛隊の各護衛艦が実際に使っているカレーレシピを再現した「海自カレー」を提供している。艦によってレシピが異なり、食べ比べの楽しみがある。金曜日の昼食に艦内でカレーを食べる海自の伝統を、陸上で体験できる。" },
    ],
    relatedArticleSlugs: ["hiroshima-peace-memorial-guide", "hiroshima-okonomiyaki-guide"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "hiroshima-hiroshima-one-day",
    title: "広島市内1日モデルコース──原爆ドームからお好み焼きまでの完全動線",
    description: "広島を1日で回るための最適ルート。路面電車と徒歩でつなぐ、移動の無駄がない動線を完全解説する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hiroshima",
    tags: ["広島市内", "1日観光", "モデルコース", "路面電車", "広島"],
    spotIds: ["atomic-bomb-dome"],
    sections: [
      { type: "heading", content: "9:00 広島駅から路面電車で平和記念公園へ", level: 2 },
      { type: "text", content: "広島駅から路面電車（広電）1号線に乗り、「原爆ドーム前」電停で降りる（約20分、160円）。午前中は平和記念公園・原爆ドーム・広島平和記念資料館を2時間かけて丁寧に見る。資料館を出た後は公園内のベンチで気持ちを整理する時間を作ること。" },
      { type: "heading", content: "11:30 お好み焼きでランチ", level: 2 },
      { type: "text", content: "平和記念公園から徒歩圏内の「お好み村」または「新天地エリア」でお好み焼きのランチ。広島風の「重ね焼き」は1枚で満足感が高い。平日なら11時30分に入れば並ばずに座れる確率が高い。" },
      { type: "heading", content: "14:00 縮景園と路面電車で帰路", level: 2 },
      { type: "text", content: "午後は路面電車で縮景園前へ移動し、江戸の庭園をゆっくり回る（約1時間）。夕方は広島駅周辺で地酒・牡蠣・もみじ饅頭を最後に購入し帰路へ。路面電車1日乗車券（700円）を活用すると移動費を節約できる。" },
    ],
    relatedArticleSlugs: ["hiroshima-peace-memorial-guide", "hiroshima-okonomiyaki-guide"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "hiroshima-miyajima-stay",
    title: "宮島に泊まる──島の夜に会う鹿と無人の厳島神社",
    description: "宮島に一泊すれば最終フェリー後の島を歩ける。鹿が徘徊する石畳と、参拝客のいない厳島神社の朝を体験する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "hiroshima",
    tags: ["宮島", "宿泊", "厳島神社", "鹿", "広島"],
    spotIds: ["itsukushima-shrine"],
    sections: [
      { type: "heading", content: "最終フェリー後の宮島は別世界", level: 2 },
      { type: "text", content: "宮島へのフェリーは24時間運行しているが、夜9時以降は日帰り観光客がいなくなる。表参道商店街は閉まり、石畳の参道に鹿だけが残る。厳島神社は夜間も開放されており、参拝客のいない社殿と大鳥居を独占に近い形で歩ける。" },
      { type: "heading", content: "宮島の旅館は満潮・干潮を見越したプランを持つ", level: 2 },
      { type: "text", content: "宮島の旅館では潮位情報を朝食時に提供してくれる宿が多い。その日の満潮・干潮の時刻と高さを教えてもらい、鳥居の見え方が最も美しい時間帯に外出する計画を立てられる。宿の仲居さんに「今日は何時が満潮ですか」と聞くことが宮島滞在の礼儀だ。" },
      { type: "heading", content: "朝食前の早朝参拝が宮島の頂点", level: 2 },
      { type: "text", content: "宮島に泊まる最大の理由は早朝6時30分に開く厳島神社への参拝だ。観光客が来る前の社殿を一人で歩く体験は、日中とは全く異なる神域の静寂を感じさせる。朝霧の中を鳥居へ向かう時間は、長く記憶に残る旅の瞬間になる。" },
    ],
    relatedArticleSlugs: ["hiroshima-miyajima-daytrip", "hiroshima-miyajima-momiji"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "hiroshima-hiroshima-lemon",
    title: "尾道レモン──瀬戸内のレモン文化と食べ方のすべて",
    description: "瀬戸内の島々は日本最大のレモン産地だ。尾道・岩城島・大崎上島のレモングルメと産地体験を完全解説する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-11-25",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hiroshima",
    tags: ["レモン", "瀬戸内", "尾道", "フルーツ", "広島"],
    spotIds: ["onomichi"],
    sections: [
      { type: "heading", content: "瀬戸内がレモン産地になった理由", level: 2 },
      { type: "text", content: "瀬戸内の島々は年間降水量が少なく温暖な気候がレモン栽培に適している。広島県は国内レモン生産量の約7割を占め、大崎上島・岩城島が主要産地だ。農薬が少なく皮まで食べられる「防腐剤不使用レモン」は全国に流通している。" },
      { type: "heading", content: "尾道のレモングルメ──レモンラーメン・レモンコーヒー", level: 2 },
      { type: "text", content: "尾道市内ではレモンを使ったグルメが急増している。塩レモンを使ったレモンラーメン・レモンを一絞りするコーヒー「レモンコーヒー」・レモンを丸ごと使ったレモネードスタンド。地元のカフェや食堂が工夫したレモン料理を探しながら街を歩くのが尾道の楽しみになっている。" },
      { type: "heading", content: "レモン農園ツアーで皮ごと食べる体験", level: 2 },
      { type: "text", content: "大崎上島や岩城島ではレモン農園見学・収穫体験ツアーが運営されている。防腐剤不使用のレモンを皮ごとかじる体験は、スーパーで売っているレモンとは全く異なる芳香と瑞々しさを教えてくれる。島へのフェリーは尾道港または竹原港から出ている。" },
    ],
    relatedArticleSlugs: ["hiroshima-onomichi-walk", "hiroshima-shimanami-cycle"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "hiroshima-hiroshima-beer",
    title: "広島地ビールと地酒──西条の酒蔵街と広島クラフトビールの案内",
    description: "広島は日本酒の名産地でもある。西条の酒蔵街と広島市内のクラフトビール事情を整理した飲み歩きガイド。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hiroshima",
    tags: ["広島酒", "西条", "クラフトビール", "酒蔵", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "西条──全国4大醸造地のひとつ", level: 2 },
      { type: "text", content: "広島県東広島市の西条は、灘（兵庫）・伏見（京都）・南部（岩手）と並ぶ全国4大醸造地のひとつだ。JR西条駅から徒歩圏内に複数の酒蔵が立ち並び、煉瓦の煙突と白壁の蔵が続く酒蔵通りは散策するだけで酒の香りに包まれる。" },
      { type: "heading", content: "酒蔵の試飲は少量を丁寧に", level: 2 },
      { type: "text", content: "西条の各酒蔵では蔵見学と試飲を実施している場所が多い（要事前確認・有料）。試飲は少量を丁寧に楽しむのが礼儀で、辛口・甘口・生酒・熟成酒の違いを一蔵で比較できる。土産に1本選ぶなら地元でしか入手できない限定品を選ぶ価値がある。" },
      { type: "heading", content: "広島市内のクラフトビールシーンが急成長中", level: 2 },
      { type: "text", content: "広島市内では近年クラフトビール専門バーとブルワリーが増加している。瀬戸内のレモンや牡蠣をつまみにしながら地元醸造のクラフトビールを飲む体験は、広島グルメの新しいスタイルだ。お好み焼きのお好み村周辺にも複数の地ビール店が点在している。" },
    ],
    relatedArticleSlugs: ["hiroshima-okonomiyaki-guide", "hiroshima-oyster-guide"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "hiroshima-hatsukaichi",
    title: "廿日市市を歩く──宮島口から見える宮島と街の日常",
    description: "観光客のほとんどが宮島へ渡るために通過する廿日市市。実は宮島口周辺にも魅力的な地元の日常が残っている。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hiroshima",
    tags: ["廿日市", "宮島口", "地元観光", "広島"],
    spotIds: ["itsukushima-shrine"],
    sections: [
      { type: "heading", content: "宮島口から見る宮島の夕景", level: 2 },
      { type: "text", content: "宮島へ渡るフェリー乗り場「宮島口」から対岸の宮島を見ると、厳島神社の大鳥居が遠望できる。夕暮れ時は宮島と対岸の海峡が橙色に染まり、渡る前・帰った後どちらの時間帯でも美しい。フェリーを待つ間に撮影するのが定番だ。" },
      { type: "heading", content: "廿日市の桟橋市場で地元の朝食", level: 2 },
      { type: "text", content: "宮島口から車で10分の廿日市市街には、地元漁師が水揚げした魚を販売する小さな市場がある。観光地価格ではなく地元価格の海産物が並ぶ朝の市場は、宮島観光の前後に立ち寄る価値がある。" },
      { type: "heading", content: "宮島街道の旧道を歩く", level: 2 },
      { type: "text", content: "廿日市市を通る旧山陽道は、参拝客が宮島へ向かうために使った歴史街道だ。廿日市の旧市街には酒蔵・神社・武家屋敷跡が残る。宮島観光だけでは見えない「宮島参拝の陸側の歴史」を辿る半日の散策は、歴史好きに特におすすめだ。" },
    ],
    relatedArticleSlugs: ["hiroshima-miyajima-daytrip", "hiroshima-miyajima-stay"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "hiroshima-budget-plan",
    title: "1泊2日・広島節約旅行──1万5千円で原爆ドーム・宮島・お好み焼きを制覇",
    description: "広島の主要観光を最安で回る1泊2日の完全プラン。交通費・宿泊費・食費の内訳を実際の数字で示す。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "hiroshima",
    tags: ["節約旅行", "広島", "バジェット", "1泊2日", "モデルコース"],
    spotIds: ["atomic-bomb-dome", "itsukushima-shrine"],
    sections: [
      { type: "heading", content: "1日目：平和記念公園と市内グルメ（7,000円）", level: 2 },
      { type: "text", content: "新大阪から高速バスで広島駅（4,000円片道）。路面電車1日券（700円）で平和記念公園・縮景園を回る。夕食はお好み村でお好み焼き1枚（800〜1,000円）。宿は広島駅近くのビジネスホテル・ゲストハウス（3,000〜4,000円）で1日合計約8,000円。" },
      { type: "heading", content: "2日目：宮島日帰り（4,000円）", level: 2 },
      { type: "text", content: "路面電車で宮島口へ移動、フェリーで宮島（往復360円）。厳島神社参拝（300円）・もみじ饅頭食べ歩き（500円）・焼きガキ2個（300円）。宮島を3時間で回り午後は広島市内に戻る。昼食は宮島の食堂で牡蠣飯（1,200円）。" },
      { type: "heading", content: "合計費用の内訳と節約のポイント", level: 2 },
      { type: "text", content: "2日間の合計費用は高速バス往復8,000円・宿4,000円・飲食4,000円・交通1,500円・入場料500円で合計約1万8,000円。新幹線を使う場合より8,000円以上節約できる。観光施設の入場料は無料・低額のものを優先し、食費は地元の食堂とテイクアウトを中心に構成するのがコツだ。" },
    ],
    relatedArticleSlugs: ["hiroshima-hiroshima-one-day", "hiroshima-okonomiyaki-guide"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "hiroshima-family-trip",
    title: "広島子連れ旅行──宮島の鹿・原爆ドームの伝え方・お好み焼き体験",
    description: "広島は子連れで訪れると「伝えること」と「楽しむこと」が両立できる稀有な観光地だ。家族旅行の完全プラン。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "hiroshima",
    tags: ["子連れ旅行", "広島", "家族", "宮島", "原爆ドーム"],
    spotIds: ["atomic-bomb-dome", "itsukushima-shrine"],
    sections: [
      { type: "heading", content: "子どもへの原爆ドームの伝え方", level: 2 },
      { type: "text", content: "小学生の子どもに原爆ドームを見せるとき、最初に「ここで何があったか」を話してから歩き始めること。平和記念資料館には年齢に合わせた展示説明があり、スタッフに「子ども向けの見方」を質問すると丁寧に教えてくれる。怖がらせることが目的ではなく「知ること」が目的だという文脈を伝えること。" },
      { type: "heading", content: "宮島の鹿と子どもの相性", level: 2 },
      { type: "text", content: "宮島には野生の鹿が約500頭生息している。参道を歩く鹿は人に慣れているため、子どもが喜んで近づく。ただし鹿は食べ物を感知すると追いかけてくるため、袋物や地図を持って歩くときは注意が必要だ。鹿に食べ物を与えることは禁止されている。" },
      { type: "heading", content: "お好み焼き体験で広島グルメを学ぶ", level: 2 },
      { type: "text", content: "広島市内のお好み焼き店の中には「鉄板の前で見学できるオープンキッチン」の店がある。子どもが鉄板越しに焼く工程を間近で見られる店を選ぶと食への興味が増す。広島風の「重ね焼き」のプロセスを見てから食べると、味の感じ方が変わる。" },
    ],
    relatedArticleSlugs: ["hiroshima-peace-memorial-guide", "hiroshima-miyajima-daytrip"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "hiroshima-tomonoura-film",
    title: "鞆の浦と映画の縁──崖の上のポニョと「潮待ち港」の物語",
    description: "広島県福山市の鞆の浦は宮崎駿が構想を練った港町。映画的な風景が今も残る路地と港の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "hiroshima",
    tags: ["鞆の浦", "崖の上のポニョ", "映画", "港町", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "宮崎駿が数ヶ月滞在した港町", level: 2 },
      { type: "text", content: "スタジオジブリの宮崎駿監督は2004年に鞆の浦に数ヶ月滞在し、「崖の上のポニョ」の構想を練った。映画の中の海沿いの街・常夜燈・古い家屋のビジュアルが鞆の浦の実景と重なることで知られており、ジブリファンが世界中から訪れる聖地になった。" },
      { type: "heading", content: "鞆の浦の「時間の止まり方」", level: 2 },
      { type: "text", content: "鞆の浦は今も江戸時代の常夜燈・雁木・波止場が現役で使われている。近代化から取り残されたとも見えるが、それが「映画的な風景」を今も維持している理由だ。路地を歩くと石畳と古い蔵が続き、現代と江戸が交差する感覚がある。" },
      { type: "heading", content: "太田家住宅と保命酒の伝統", level: 2 },
      { type: "text", content: "江戸時代に鞆の浦の問屋として栄えた太田家住宅は国の重要文化財で、内部見学が可能だ。鞆の浦の特産「保命酒（ほうめいしゅ）」は16種の生薬を漬け込んだ薬用養命酒で、江戸時代から作られ続けている。老舗の保命酒屋で試飲できる。" },
    ],
    relatedArticleSlugs: ["hiroshima-onomichi-walk", "hiroshima-shimanami-cycle"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "hiroshima-nishi-hiroshima-local",
    title: "地元民の広島──観光地から外れた路面電車の終点を歩く",
    description: "観光客が行かない広島を知りたい人へ。路面電車の終点「広電西広島」周辺の日常の店と景色。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "hiroshima",
    tags: ["広島ローカル", "路面電車", "地元グルメ", "西広島", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "広電で終点まで乗り通す", level: 2 },
      { type: "text", content: "広島の路面電車（広電）は広島駅から宮島口方面へ約1時間かけて走る。途中の「広電西広島（己斐）」は地元客の乗降が多いターミナルで、観光客はほとんど降りない。この駅周辺には昭和から続く商店街と地元密度の高い食堂が残っている。" },
      { type: "heading", content: "己斐の商店街で地元の食材を買う", level: 2 },
      { type: "text", content: "己斐本町の商店街には地元の八百屋・鮮魚店・惣菜屋が並ぶ。観光地価格ではなく、地元民が毎日使う価格で瀬戸内の魚介や広島野菜が入手できる。旅先でスーパーや市場を覗くのが好きな旅行者には、ここが広島で最もリアルな場所になる。" },
      { type: "heading", content: "夕方の電車通りを歩いて広島城方面へ", level: 2 },
      { type: "text", content: "夕方、路面電車の通りを東に向かって歩くと広島城の外堀まで20分ほどで着く。広島城（鯉城）は無料で外観を見られる。堀の前の公園は夕暮れ時に地元の人が散歩する場所で、観光地ではない広島の日常の光景に触れられる。" },
    ],
    relatedArticleSlugs: ["hiroshima-hiroshima-one-day", "hiroshima-shukkeien-garden"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "hiroshima-august-sixth",
    title: "8月6日に広島に行く──平和記念式典と慰霊の一日",
    description: "毎年8月6日は広島で平和記念式典が行われる。その日に広島を訪れることの意味と、式典への参加方法を伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-30",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hiroshima",
    tags: ["8月6日", "平和記念式典", "広島", "原爆", "慰霊"],
    spotIds: ["atomic-bomb-dome"],
    sections: [
      { type: "heading", content: "8時15分の黙祷──時計が止まる瞬間", level: 2 },
      { type: "text", content: "毎年8月6日の午前8時15分、広島では全市が黙祷する。平和記念公園での式典に参加しなくても、広島市内のどこにいてもこの時間は立ち止まって黙祷することが地元の文化だ。1945年のあの朝と同じ時間に、同じ空の下で黙祷する体験は言葉にならない重みがある。" },
      { type: "heading", content: "平和記念式典への一般参列", level: 2 },
      { type: "text", content: "8月6日の平和記念式典は一般市民も参列できる（事前登録不要）。ただし会場は早朝から混雑するため、前日から広島に滞在して6時台に会場へ向かうことを推奨する。式典は約1時間で終了し、「こどもたちの誓い」の朗読が特に心に刻まれる。" },
      { type: "heading", content: "夜の灯籠流しで一日を締める", level: 2 },
      { type: "text", content: "8月6日の夜、元安川・本川では灯籠流しが行われる。市民が折り鶴や花を入れた灯籠を川に流す光景は、1年の中でも特別な広島の夜だ。岸から見守る人・川の上の灯籠・水面の光の反射が重なる景観は、写真には収まりきらない。" },
    ],
    relatedArticleSlugs: ["hiroshima-peace-memorial-guide", "hiroshima-hiroshima-one-day"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "hiroshima-saijo-sake",
    title: "西条の酒蔵街──11月「酒まつり」で日本酒の海に溺れる",
    description: "毎年10月〜11月に開催される西条酒まつりは、全国から30万人が集まる日本最大の酒祭りだ。準備と楽しみ方を解説する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hiroshima",
    tags: ["西条", "酒まつり", "日本酒", "酒蔵", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "酒まつりは10月第2週末が本番", level: 2 },
      { type: "text", content: "西条の「酒まつり」は毎年10月の第2土日に開催される。全国の酒蔵が集まり、試飲グラス（有料）を手にして各ブースを回る形式だ。2日間で約30万人が訪れるため、JR西条駅は臨時列車が増発される。前日の金曜夜から到着して酒蔵通りを下見するのが賢い。" },
      { type: "heading", content: "酒蔵見学は酒まつり以外の時期が穴場", level: 2 },
      { type: "text", content: "酒まつり期間以外でも、西条の各酒蔵は通常期の見学・試飲を受け付けている。混雑がなく、蔵人から直接説明を聞きながらじっくり試飲できる。特に新酒ができる11月〜12月は搾りたての「しぼりたて生酒」が試飲できる最良の時期だ。" },
      { type: "heading", content: "西条の酒を土産に選ぶコツ", level: 2 },
      { type: "text", content: "西条の各蔵の代表銘柄（賀茂鶴・白牡丹・西条鶴・賀茂泉など）は広島市内のスーパーでも買えるが、蔵限定品や「鑑評会出品酒」は現地でしか手に入らない。各蔵で「限定品はありますか」と聞いてみると、普通流通していない特別な1本に出会える可能性がある。" },
    ],
    relatedArticleSlugs: ["hiroshima-hiroshima-beer", "hiroshima-okonomiyaki-guide"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "hiroshima-onomichi-cat-alley",
    title: "尾道の猫道──猫の小道の全容と「猫の細道」の行き方",
    description: "尾道には猫専用の「猫の細道」がある。千光寺への急坂に散らばる猫スポットを全て記録した完全地図付き解説。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "hiroshima",
    tags: ["尾道", "猫", "猫の細道", "坂道散策", "広島"],
    spotIds: ["onomichi"],
    sections: [
      { type: "heading", content: "「猫の細道」の入口を見つける", level: 2 },
      { type: "text", content: "尾道の「猫の細道」は千光寺山の中腹、艮神社（うしとらじんじゃ）の脇から始まる狭い石段道だ。JR尾道駅から徒歩10分で入口に到着する。案内板が小さく見逃しやすいため、Google マップで「猫の細道」を検索して近づくのが確実だ。" },
      { type: "heading", content: "「ガウディハウス」は猫アートの聖地", level: 2 },
      { type: "text", content: "猫の細道の途中にある「ガウディハウス」は、陶芸家・南耕氏が外壁に猫のモチーフをはめ込んだ建物だ。壁面全体が猫のオブジェで覆われており、どの角度から写真を撮っても絵になる。猫の細道の中で最も「映える」スポットだ。" },
      { type: "heading", content: "猫に出会うタイミングは午前中が高い", level: 2 },
      { type: "text", content: "尾道の野良猫は気温が上がる午後には日陰で寝てしまうことが多い。午前9時〜11時の時間帯は日当たりの良い石段に猫が出てきやすく、遭遇率が高い。猫は急に動かないことが最大のコツで、しゃがんで静止すると向こうから近づいてくることが多い。" },
    ],
    relatedArticleSlugs: ["hiroshima-onomichi-walk", "hiroshima-onomichi-ramen"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "hiroshima-hiroshima-castle",
    title: "広島城（鯉城）の歩き方──天守閣と二の丸の歴史を整理する",
    description: "広島城は再建天守だが内部の歴史展示は充実している。原爆で消えた城と、戦後に蘇った城の物語。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-04-22",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hiroshima",
    tags: ["広島城", "鯉城", "歴史", "広島市内", "広島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "1945年の原爆で天守まで崩壊した城", level: 2 },
      { type: "text", content: "広島城は毛利輝元が1589年に築いた平城だ。1945年の原爆投下で天守を含む全建物が崩壊・消滅し、現在の天守は1958年に再建されたコンクリート製だ。原爆で失われた城を再建した経緯が、この城を「戦後の象徴」としてより深い意味を持たせている。" },
      { type: "heading", content: "二の丸の表御門は本物の江戸建築", level: 2 },
      { type: "text", content: "天守は再建だが、二の丸の「表御門」「平櫓」「多聞櫓」は江戸時代の建物が現存・復元されている。特に表御門は時代劇に出てくる城門の様式を忠実に伝えており、国の重要文化財に指定されている。" },
      { type: "heading", content: "天守からの平和記念公園の遠望", level: 2 },
      { type: "text", content: "広島城の天守最上階からは、西の方角に平和記念公園と原爆ドームの方向を遠望できる。同じ空の下に城跡と原爆ドームが存在する事実を、この景色から実感できる。" },
    ],
    relatedArticleSlugs: ["hiroshima-peace-memorial-guide", "hiroshima-shukkeien-garden"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "hiroshima-luxury-trip",
    title: "広島贅沢旅行──宮島一泊・カキ会席・しまなみ海道の2泊3日",
    description: "広島を贅沢に味わう2泊3日の究極プラン。宮島の高級旅館・瀬戸内の食材を使った会席・しまなみ海道の絶景サイクリング。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-12-10",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "hiroshima",
    tags: ["贅沢旅行", "宮島", "カキ", "しまなみ海道", "広島"],
    spotIds: ["itsukushima-shrine", "shimanami-kaido"],
    sections: [
      { type: "heading", content: "1日目：広島市内観光と平和記念公園", level: 2 },
      { type: "text", content: "新幹線で広島入り。午前中は平和記念公園・資料館で歴史と向き合い、午後は縮景園・広島城を歩く。夕食は西条の地酒を揃える広島の和食料理店でカキ・白身魚・瀬戸内の食材を使った本格的な懐石コースを楽しむ。宿は広島市内の高級シティホテルに一泊。" },
      { type: "heading", content: "2日目：宮島に渡り高級旅館に泊まる", level: 2 },
      { type: "text", content: "午前中に宮島フェリーで宮島へ。厳島神社参拝・紅葉谷公園・弥山を満潮と干潮の時間帯を組み合わせながら歩く。夕方以降は宮島の高級旅館にチェックイン。カキ・タコ・鯛・もみじ鯛を使った宮島会席と露天風呂で瀬戸内の夜を過ごす。" },
      { type: "heading", content: "3日目：しまなみ海道の橋を自転車で渡る", level: 2 },
      { type: "text", content: "3日目は宮島を出て尾道へ移動。電動アシスト自転車をレンタルし、因島・生口島を走る。多々羅大橋で折り返し、尾道に戻る半日コース（約35km）。生口島の瀬戸田でレモンソフトクリームと地元の柑橘を楽しみ、夕方の新幹線で帰路へ。" },
    ],
    relatedArticleSlugs: ["hiroshima-miyajima-stay", "hiroshima-shimanami-cycle"],
  },
];
