import { Article } from "@/types/article";

export const hyogoArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-night-view",
    title: "神戸の夜景──摩耶山、六甲山、ポートタワーの見え方の違い",
    description: "「日本三大夜景」の一角、神戸。夜景スポットによって全く異なる表情がある。選び方を解説。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hyogo",
    tags: ["夜景", "神戸", "摩耶山", "六甲山"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "摩耶山掬星台──1000万ドルの夜景の真骨頂", level: 2 },
      { type: "text", content: "摩耶山の掬星台は海抜約700m。眼下に神戸の市街地が広がり、大阪湾の対岸まで見渡せる。空気が澄んだ冬の夜に訪れると、街の灯りが海面に映り込む様子まで確認できる。ロープウェイの最終便を確認してから計画すること。" },
      { type: "heading", content: "六甲ガーデンテラスは車でのアクセスが現実的", level: 2 },
      { type: "text", content: "六甲山山頂付近の六甲ガーデンテラスはレストランやカフェが充実しており、夜景を見ながら食事ができる。レンタカーかタクシーでのアクセスになるが、雨の日は雲で夜景が見えないため天気確認は必須。" },
      { type: "heading", content: "ポートタワーから見る港の夜景", level: 2 },
      { type: "text", content: "メリケンパーク内のポートタワーは、神戸港を間近に見下ろす低空の夜景が特徴。高さより「港の真横感」を求めるならここが最適。恋人の聖地登録もされており、カップルに人気が高い。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-couple-date", "hyogo-harbor-lunch-walk"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-beef-guide",
    title: "神戸牛を正しく食べる──値段・部位・店選びの全知識",
    description: "神戸牛は「高い」だけではない。部位と調理法を知れば、同じ予算で全く違う体験ができる。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hyogo",
    tags: ["神戸牛", "グルメ", "ステーキ", "神戸"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "神戸牛の定義──全頭検査と格付け", level: 2 },
      { type: "text", content: "神戸牛は全国でも年間5000頭以下しか認定されない超希少なブランド和牛だ。但馬牛のうち、特定の基準を満たしたものだけが「神戸牛」を名乗れる。証明書を発行している店で食べることが真贋の確認になる。" },
      { type: "heading", content: "鉄板焼きとすき焼き、どちらが正解か", level: 2 },
      { type: "text", content: "神戸牛の本場では鉄板焼き文化が根強い。目の前でシェフが焼き上げるダイナミックな調理は、食事体験としての価値が高い。一方、但馬出身の農家が家庭で食べる形はすき焼きで、こちらも肉の甘みを感じやすい。" },
      { type: "heading", content: "ランチタイムがコスパ最強", level: 2 },
      { type: "text", content: "神戸牛高級店でも、ランチコースはディナーの半額程度で提供されることが多い。ランチで神戸牛の鉄板焼きを食べ、夜は三宮の居酒屋で締めるのが賢い旅の食費配分だ。" },
    ],
    relatedArticleSlugs: ["hyogo-nada-sake-tour", "hyogo-kobe-night-view"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-chinatown",
    title: "南京町（神戸中華街）完全ガイド──食べ歩き順番と行くべき時間帯",
    description: "横浜・長崎と並ぶ日本三大中華街のひとつ、南京町。混雑を避けて楽しむための正しい歩き方。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hyogo",
    tags: ["南京町", "中華街", "食べ歩き", "神戸"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "朝10時が最も混まない時間帯", level: 2 },
      { type: "text", content: "南京町は昼前後の12時〜15時が最混雑時間帯。朝10時に開店する点心の老舗では、出来立て蒸篭の焼売や小籠包を行列なしで食べられる。胃を空けてから来るのが南京町の正しい訪れ方。" },
      { type: "heading", content: "肉まんは「老祥記」一択", level: 2 },
      { type: "text", content: "南京町の食べ歩きを象徴する老祥記の豚まんは、1日1万個以上売れる日もある名物。小ぶりで肉汁が多く、皮が薄い。2〜3個を間食として食べるのがちょうどいい。整理券が出る日もあるため開店直後が確実。" },
      { type: "heading", content: "春節は圧巻だが覚悟が必要", level: 2 },
      { type: "text", content: "旧正月の春節期間（1〜2月）の南京町は、獅子舞と爆竹が飛び交い別世界の賑わいになる。観光としては最高だが人出も最大。防寒対策を万全にして、観覧スペースには1時間前から場所取りが必要だ。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-beef-guide", "hyogo-kitano-ijinkan-walk"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "hyogo-arima-onsen-guide",
    title: "有馬温泉──金泉・銀泉の違いと旅館選びの基準",
    description: "日本三古湯のひとつ、有馬温泉。金色と銀色、二つの泉質は全く別物だ。効能と温泉宿の選び方。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-07-05",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "hyogo",
    tags: ["有馬温泉", "金泉", "銀泉", "温泉旅館"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "金泉の赤褐色──鉄分と塩分が作る奇跡の色", level: 2 },
      { type: "text", content: "有馬の金泉は塩化物泉と含鉄泉が混合した世界的にも珍しい泉質だ。赤茶色に見える湯は、空気に触れた鉄分が酸化したため。保温効果が高く、冬に入ると体の芯まで温まる。" },
      { type: "heading", content: "銀泉は二酸化炭素泉と放射能泉", level: 2 },
      { type: "text", content: "銀泉は無色透明の炭酸泉と微量放射能泉（ラジウム泉）からなる。金泉ほど知名度はないが、神経痛・疲労回復に効果があるとされる。金銀両方の湯を持つ旅館を選ぶと、1回の滞在で両方体験できる。" },
      { type: "heading", content: "日帰り入浴は「金の湯」「銀の湯」で", level: 2 },
      { type: "text", content: "有馬温泉には公共浴場の「金の湯」と「銀の湯」がある。650円・440円で本物の有馬の湯が体験できる。セット券を使えばどちらも体験できてコスパも良く、旅館に泊まらない日帰り客にも有馬の真価を伝える施設だ。" },
    ],
    relatedArticleSlugs: ["hyogo-kinosaki-onsen-walk", "hyogo-luxury-arima-ryokan"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "hyogo-kinosaki-onsen-walk",
    title: "城崎温泉の外湯巡り──7つの湯をすべて入る正しい順番",
    description: "城崎の真骨頂は外湯巡り。浴衣で下駄を鳴らして7つの温泉をはしごする1日のプランを組む。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "hyogo",
    tags: ["城崎温泉", "外湯", "浴衣", "兵庫"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "外湯の順番に意味がある", level: 2 },
      { type: "text", content: "城崎温泉の外湯7箇所（さとの湯、地蔵湯、柳湯、一の湯、御所の湯、まんだら湯、鴻の湯）はそれぞれ泉質と雰囲気が異なる。まずは離れた場所から制覇して、最後に宿に近い湯で締めるのが体力的に楽な周り方だ。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "浴衣と下駄の歩き方", level: 2 },
      { type: "text", content: "旅館が貸し出す浴衣と下駄で外湯を巡ることが城崎温泉の文化だ。下駄の音が石畳に響く大谿川沿いの道は、夜になると提灯が灯り江戸時代の温泉街の様相を見せる。この光景のために城崎に来る人も多い。" },
      { type: "heading", content: "カニは11月から3月が旬", level: 2 },
      { type: "text", content: "城崎の旅館の冬の名物は松葉ガニ（ズワイガニ）だ。11月の解禁から3月末まで、茹でガニ・焼きガニ・カニ鍋のフルコースを提供する旅館が多い。シーズン中は予約が早期に埋まるため、3ヶ月前の予約が常識。" },
    ],
    relatedArticleSlugs: ["hyogo-arima-onsen-guide", "hyogo-kinosaki-couple-trip"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "hyogo-himeji-castle-guide",
    title: "姫路城を全部見る──白鷺城の建築美と天守の謎",
    description: "「見た」と「見た気になった」は違う。姫路城を本当に理解するための必見ポイントと歩き方。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hyogo",
    tags: ["姫路城", "世界遺産", "城", "歴史"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "白漆喰の秘密──なぜ白い", level: 2 },
      { type: "text", content: "姫路城が「白鷺城」と呼ばれる理由は、外壁に塗られた白漆喰にある。防火・防水機能を持つ漆喰は、時代とともに灰色に変色したが、1956〜64年の昭和の大修理と2009〜15年の平成の修理で往時の白さが甦った。" },
      { type: "spot-card", content: "himeji" },
      { type: "heading", content: "天守の螺旋構造と戦闘の論理", level: 2 },
      { type: "text", content: "大天守の内部は6層7階構造で、急な階段が連続する。外から攻め込んだ敵は、各層の武者走りと狭間（さま）から攻撃を受け続ける仕組みだ。城全体が巨大な迷路として設計されており、実際に歩くと設計の巧みさがわかる。" },
      { type: "heading", content: "桜の時期はお堀の外から見よ", level: 2 },
      { type: "text", content: "4月上旬の姫路城は、お堀沿いの桜と白漆喰の天守が重なる絶景が生まれる。城内に入らなくても、好古園側からの眺めや菱の門前の写真ポイントは無料で楽しめる。あまり知られていないが、夜桜ライトアップも実施される。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-day-trip", "hyogo-himeji-castle-season"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "hyogo-awaji-island-drive",
    title: "淡路島1泊2日ドライブ旅──絶景と玉ねぎと鳴門海峡",
    description: "淡路島はドライブ専用の島だ。明石大橋を渡った先に待つ、本州とは別の時間の流れ。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hyogo",
    tags: ["淡路島", "ドライブ", "1泊2日", "玉ねぎ"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "明石海峡大橋を渡る瞬間", level: 2 },
      { type: "text", content: "全長3911mの明石海峡大橋は、主塔の高さが298mと世界最長の吊り橋。橋の上から見下ろす明石海峡の激しい潮流は、橋が完成するまでここが「日本最大の海峡」だったことを実感させる。" },
      { type: "heading", content: "淡路島の玉ねぎを食べ尽くす", level: 2 },
      { type: "text", content: "淡路島産玉ねぎは甘みが強く、生でも食べられると言われる。島内の道の駅や農産物直売所では、玉ねぎ使用のバーガー、スープ、スイーツが揃う。ハンバーガーショップ「淡路島バーガー」の行列は覚悟が必要。" },
      { type: "heading", content: "鳴門海峡の渦潮は時間を選べ", level: 2 },
      { type: "text", content: "淡路島南端から大鳴門橋を渡った先の渦潮は、潮の干満差が最大になる時間帯に最も大きな渦が生まれる。事前に「渦潮カレンダー」をウェブで確認し、大潮・中潮の日程に合わせることが渦潮観覧の絶対条件だ。" },
    ],
    relatedArticleSlugs: ["hyogo-akashi-bridge-view", "hyogo-awaji-resort-stay"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "hyogo-akashi-bridge-view",
    title: "明石海峡大橋の見方と明石の食──タコと魚の棚商店街",
    description: "橋を渡るだけで終わっては本物の明石体験ではない。橋を「見る」場所と明石の食文化を案内する。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hyogo",
    tags: ["明石海峡大橋", "明石", "タコ", "商店街"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "舞子公園が橋を見る最高地点", level: 2 },
      { type: "text", content: "JR舞子駅に直結する舞子公園から見る明石海峡大橋は、橋桁の迫力が肌で感じられる至近距離だ。橋の真下を通れる遊歩道「ブリッジワールド」もあり、橋の上から海峡を見下ろす体験もできる（事前予約制）。" },
      { type: "heading", content: "魚の棚商店街の朝は新鮮な明石ダコ", level: 2 },
      { type: "text", content: "明石駅前の魚の棚（うおんたな）商店街は、明石の海産物が集まる台所だ。朝8時から開いている店では、明石ダコの刺身や蛸飯定食が食べられる。タコは柔らかく、全国流通のものとは別物の食感だ。" },
      { type: "heading", content: "明石焼きは玉子焼きと言うのが地元流", level: 2 },
      { type: "text", content: "「明石焼き」は外では通じる名前だが、地元では「玉子焼き」と呼ぶ。たこ焼きより柔らかく、出汁につけて食べるスタイルが基本。三宮のたこ焼きとは全く別物だ。魚の棚周辺の玉子焼き専門店で本場の味を。" },
    ],
    relatedArticleSlugs: ["hyogo-awaji-island-drive", "hyogo-kobe-beef-guide"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "hyogo-kitano-ijinkan-walk",
    title: "神戸・北野異人館街を歩く──明治の洋館と神戸の歴史",
    description: "幕末の開港から神戸に住み着いた外国人が建てた洋館群。その建築美と神戸の国際性の起源。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hyogo",
    tags: ["北野異人館", "洋館", "神戸", "歴史"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "風見鶏の館──ドイツ人商人の威信", level: 2 },
      { type: "text", content: "1909年にドイツ人貿易商ゴッドフリート・トーマスが建てた風見鶏の館は、北野異人館の象徴的建築だ。レンガの外壁とターン時代のヴィラ様式が融合した外観は、当時の貿易商の経済力を示している。" },
      { type: "heading", content: "うろこの家は外壁が本物の魚のうろこ", level: 2 },
      { type: "text", content: "フランス人居留地の邸宅「うろこの家」は、天然スレートを魚のうろこのように外壁に張り詰めた独特の外観で知られる。内部には美術品も展示されており、カフェも併設されている。" },
      { type: "heading", content: "北野の坂道から見下ろす神戸港", level: 2 },
      { type: "text", content: "北野異人館エリアは山の手の傾斜地にあるため、少し高い場所に立つと神戸港が見渡せる。かつて外国人居留地の住民が母国を思いながら眺めたのと同じ景色だ。夕刻の光が一番美しい。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-night-view", "hyogo-harbor-lunch-walk"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "hyogo-nada-sake-tour",
    title: "灘の酒蔵を巡る──日本一の酒どころで飲む、醸造の現場",
    description: "日本の清酒生産量の約30%を占める灘五郷。酒蔵見学と試飲で、神戸のもう一つの顔に出会う。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hyogo",
    tags: ["灘の酒", "日本酒", "酒蔵見学", "神戸"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "灘五郷とは何か", level: 2 },
      { type: "text", content: "灘五郷とは神戸市灘区から西宮市にかけての酒造地帯の総称で、今津郷・西宮郷・魚崎郷・御影郷・西郷の5つの地区からなる。「宮水」と呼ばれる硬水が、辛口の男酒「灘の男酒」を生み出す。" },
      { type: "heading", content: "菊正宗・白鶴・沢の鶴──無料見学の酒蔵", level: 2 },
      { type: "text", content: "灘五郷の主要蔵元は無料の酒蔵資料館を公開している。仕込み蔵の大桶、精米機、麹室を見学できる。試飲コーナーでは代表銘柄を無料で飲み比べ可能。午前中に回ると、発酵の香りが最も強く感じられる。" },
      { type: "heading", content: "冬季限定の「しぼりたて新酒」", level: 2 },
      { type: "text", content: "12月〜1月に出回るしぼりたて生酒は、フレッシュで微発泡な味わいが特徴。灘の酒蔵では瓶詰め直後のものを直売していることもある。この時期に灘を訪れると、日本酒好きにとって最高の土産が見つかる。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-beef-guide", "hyogo-kobe-chinatown"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "hyogo-harbor-lunch-walk",
    title: "神戸ハーバーランド昼散歩──工場跡の複合施設と海沿いのランチ",
    description: "旧国鉄の操車場跡地に生まれたハーバーランドは、神戸でも特異な風景を持つ場所だ。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hyogo",
    tags: ["ハーバーランド", "神戸港", "ランチ", "散策"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "煉瓦倉庫が並ぶmosakuエリア", level: 2 },
      { type: "text", content: "かつての鉄道関連施設の煉瓦倉庫を改装した神戸煉瓦倉庫（mosaku）は、ショップとレストランが集まる複合施設。赤煉瓦と神戸港の組み合わせは、神戸を象徴するフォトスポットになっている。" },
      { type: "heading", content: "神戸ポートタワーへの道順", level: 2 },
      { type: "text", content: "ハーバーランドからメリケンパークまでは徒歩約10分。海沿いの遊歩道を歩いていくと、神戸ポートタワーが見えてくる。昼間は内部に上れ（有料）、神戸の全景を確認することができる。" },
      { type: "heading", content: "海鮮ランチは旧居留地の市場で", level: 2 },
      { type: "text", content: "ハーバーランド周辺の海鮮レストランは観光地価格になりやすい。少し歩いて旧居留地エリアまで行くと、地元のサラリーマンが通う海鮮定食屋が見つかる。1000円以下で神戸の海鮮ランチが食べられる穴場だ。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-night-view", "hyogo-kitano-ijinkan-walk"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "hyogo-family-kobe-trip",
    title: "神戸・子連れ家族旅行──子どもが飽きない1日モデルコース",
    description: "神戸は子どもを連れて行く場所がない、と思っていませんか？実は動物園・水族館・港が揃っている。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "hyogo",
    tags: ["子連れ", "家族旅行", "神戸", "水族館"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "神戸市立須磨水族園で午前を過ごす", level: 2 },
      { type: "text", content: "須磨水族園はリニューアル後、体験型展示が充実した施設になった。サメやエイが頭上を泳ぐトンネル水槽は子どもに大人気。園内の海辺のレストランで昼食を食べると、そのままビーチエリアに移動できる。" },
      { type: "heading", content: "メリケンパークで「震災の記憶」を伝える", level: 2 },
      { type: "text", content: "神戸港震災メモリアルパークは阪神淡路大震災で被災した護岸を保存している。子どもに「地震があったこと」を自然な形で伝えられる場所として、家族旅行の立ち寄りスポットとしておすすめしたい。" },
      { type: "heading", content: "夕方はハーバーランドの大観覧車へ", level: 2 },
      { type: "text", content: "ハーバーランドのモザイク大観覧車は、高さ50mから神戸港と六甲山を見渡せる。夕暮れ時の乗車が最も眺望が美しい。子どもはゴンドラの透明な床から下が見えるタイプに乗りたがる。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-castle-guide", "hyogo-awaji-island-drive"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "hyogo-solo-kobe-walk",
    title: "神戸を一人で歩く──雑貨店と洋菓子と坂道、異国情緒の1日",
    description: "一人で歩くのに最も向いている街のひとつが神戸だ。路地に店が積み重なる街の豊かさを体験する。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "hyogo",
    tags: ["一人旅", "神戸", "散策", "カフェ"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "三宮から元町、旧居留地を歩く順番", level: 2 },
      { type: "text", content: "JR三ノ宮駅から元町商店街を西へ歩き、旧居留地のビルディング群を抜けてハーバーランドへ。この直線コースで神戸の歴史の層を体感できる。所要2時間の基本ルートだ。" },
      { type: "heading", content: "神戸洋菓子の老舗を巡る", level: 2 },
      { type: "text", content: "明治の開港以来、神戸は日本の洋菓子発祥の地と言える文化を持つ。ユーハイム（バウムクーヘン）、モロゾフ（チョコレート）、ゴンチャロフ（洋菓子）はすべて神戸発祥だ。各本店を巡ると神戸の食の歴史が見える。" },
      { type: "heading", content: "北野坂から見るカフェと坂の景色", level: 2 },
      { type: "text", content: "北野坂沿いのカフェから道行く人を眺めるのが神戸の一人旅の醍醐味だ。坂道が多い地形のせいで、神戸の人は独特のリズムで歩く。一杯のコーヒーで観察する午後の時間を、神戸旅に組み込んでほしい。" },
    ],
    relatedArticleSlugs: ["hyogo-kitano-ijinkan-walk", "hyogo-harbor-lunch-walk"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-couple-date",
    title: "神戸カップルデートプラン──夜景・ランチ・散歩で作る完璧な1日",
    description: "デートで神戸を選ぶのは正解だ。街自体が洗練されていて、何もしなくても絵になる。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "hyogo",
    tags: ["カップル", "デート", "神戸", "夜景"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "ランチは旧居留地のフレンチビストロ", level: 2 },
      { type: "text", content: "明治時代の洋館が残る旧居留地には、ランチコース2000円台で食べられる本格フレンチビストロがある。外観の歴史感と内装のモダンさのギャップが神戸らしい。予約なしでも平日ランチなら入れることが多い。" },
      { type: "heading", content: "布引ハーブ園でゴンドラ散策", level: 2 },
      { type: "text", content: "新神戸駅から5分のロープウェイで上がる布引ハーブ園は、四季折々のハーブが咲く丘の上の庭園。香りと色の中を二人で歩くと、神戸の非日常感が最高潮になる。晴れた日は神戸港まで見渡せる。" },
      { type: "heading", content: "夜は摩耶山で1000万ドルの夜景", level: 2 },
      { type: "text", content: "夕食後に摩耶山ロープウェイで掬星台へ。毛布のレンタルがある展望台で、夜景を見ながら二人の時間を持つ。気温が低い日も多いため、春秋でも上着必須だ。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-night-view", "hyogo-luxury-kobe-hotel"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "hyogo-himeji-day-trip",
    title: "姫路1日観光プラン──世界遺産の城と好古園、書写山ロープウェイ",
    description: "姫路は城だけで終わらない。半日以上かけて回れるスポットを組み込んだ完全1日プラン。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hyogo",
    tags: ["姫路", "1日観光", "好古園", "書写山"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "午前9時：姫路城は開門直後が正解", level: 2 },
      { type: "text", content: "姫路城の開門は9時。修学旅行のバスが到着する10時前に天守最上階に到達するのが鉄則だ。天守最上階から見下ろす播磨平野と三方の山々は、城郭建築が防衛地形をいかに活用しているかを視覚化してくれる。" },
      { type: "heading", content: "昼前後：好古園でゆっくりする", level: 2 },
      { type: "text", content: "姫路城西側の好古園は、城の西の丸跡地に設けられた庭園群。9つの庭が連続し、全体を歩くと1時間かかる本格的な庭園だ。お茶処もあり、昼の混雑時間帯を庭でやり過ごすのが賢い姫路プランだ。" },
      { type: "heading", content: "午後：書写山圓教寺でラストムービー感", level: 2 },
      { type: "text", content: "姫路駅からバスと書写山ロープウェイで行く圓教寺は、映画のロケ地として知られる山寺。三之堂（大講堂・食堂・常行堂）が並ぶ境内は、姫路城とは異なる静寂の歴史空間だ。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-castle-guide", "hyogo-himeji-castle-season"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "hyogo-himeji-castle-season",
    title: "姫路城の四季──桜・新緑・夜景・雪景色、一番いい季節はいつか",
    description: "姫路城は季節によって全く表情が変わる。最高の姫路城を見るための季節選びガイド。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hyogo",
    tags: ["姫路城", "桜", "四季", "夜景"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "春：桜と白漆喰のコントラスト", level: 2 },
      { type: "text", content: "4月上旬の姫路城周辺は、千本桜が同時に開花する。城内の三の丸広場から見上げる天守と桜の組み合わせは、日本の城郭風景の中でも最も写真映えする景観のひとつだ。夜間のライトアップも行われる。" },
      { type: "heading", content: "冬：雪の姫路城は年数回しか見られない", level: 2 },
      { type: "text", content: "姫路は温暖な気候で雪は少ないが、数年に一度の積雪時に白漆喰の天守に雪が積もる光景は、城の白さがさらに際立つ圧巻の美しさになる。天気予報をこまめに確認して、雪が降りそうな日を狙って向かう熱心な写真家も多い。" },
      { type: "heading", content: "夜：ライトアップは週末だけ", level: 2 },
      { type: "text", content: "姫路城の夜間ライトアップは通年実施されているが、入城できるのは特定イベント日のみ。外から眺める夜の白鷺城は、昼間とは別物の美しさがある。大手門前広場が最良の鑑賞スポットだ。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-castle-guide", "hyogo-himeji-day-trip"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "hyogo-kinosaki-couple-trip",
    title: "城崎温泉カップル旅行──浴衣デートと二人の外湯体験",
    description: "城崎で浴衣を着て二人で外湯を巡る。この体験をするためだけに兵庫に来る価値がある。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "hyogo",
    tags: ["城崎温泉", "カップル", "浴衣", "温泉"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "旅館の浴衣を着て下駄で歩く非日常", level: 2 },
      { type: "text", content: "城崎では旅館チェックイン後すぐに浴衣に着替えて街に出るのが正しい手順だ。下駄の音が石畳に響く大谿川沿いを二人で歩くと、どこをどう切り取っても絵になる。温泉街の夜は提灯の光が柳に映る。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "一の湯が最もロマンチックな外湯", level: 2 },
      { type: "text", content: "城崎外湯の中で最も有名な「一の湯」は、岩盤に掘られた洞窟風呂がある。夜に二人で入る洞窟の湯は、特別なムードを生む。城崎温泉名物「縁結びの湯」として知られる所以だ。" },
      { type: "heading", content: "冬なら松葉ガニのフルコース", level: 2 },
      { type: "text", content: "11月〜3月の城崎旅館は松葉ガニをフルコースで出す。茹でガニ・焼きカニ・カニ鍋・カニしゃぶを一度の夕食で食べる豪華な食卓は、冬のカップル旅行の記念として最上の体験だ。早期予約が必須。" },
    ],
    relatedArticleSlugs: ["hyogo-kinosaki-onsen-walk", "hyogo-arima-onsen-guide"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "hyogo-budget-kobe-guide",
    title: "神戸を5000円で楽しむ──無料スポット、格安食堂、交通費節約術",
    description: "神戸は「おしゃれで高い」イメージがあるが、工夫次第で格安旅が成立する。節約神戸旅の全手順。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "hyogo",
    tags: ["節約旅行", "神戸", "バジェット", "格安"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "無料で楽しめる神戸の観光地", level: 2 },
      { type: "text", content: "メリケンパーク、ハーバーランド、北野の坂道散策、旧居留地の外観見学はすべて無料。夜景も摩耶山以外は無料スポットが充実している。神戸の良さの大部分は「歩くだけ」で体験できる。" },
      { type: "heading", content: "昼食は魚の棚で600円以下", level: 2 },
      { type: "text", content: "明石・魚の棚商店街の食堂ランチは地元価格が維持されている。玉子焼き定食600円、明石ダコの刺身定食800円など、観光地価格を大きく下回る。神戸三宮の飲食店より明石まで足を伸ばす価値がある。" },
      { type: "heading", content: "交通費は神戸1Dayループバスで節約", level: 2 },
      { type: "text", content: "神戸市内を循環する「シティループバス」の1日乗車券は700円。北野・三宮・元町・ハーバーランドを結ぶルートなので、主要観光地は1日乗り放題でカバーできる。" },
    ],
    relatedArticleSlugs: ["hyogo-solo-kobe-walk", "hyogo-harbor-lunch-walk"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "hyogo-luxury-arima-ryokan",
    title: "有馬温泉の最高級旅館体験──金泉貸切露天と会席料理の完全案内",
    description: "有馬の高級旅館に泊まることは、単なる宿泊ではなく日本の温泉文化の最高峰を体験することだ。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "hyogo",
    tags: ["有馬温泉", "高級旅館", "贅沢旅", "温泉"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "金泉貸切露天風呂の予約は先着順", level: 2 },
      { type: "text", content: "有馬の高級旅館では客室露天ではなく、別棟の貸切露天風呂が人気最高峰の設備だ。チェックイン時に好みの時間帯を予約するシステムで、人気の時間帯（21時・22時）は早いもの順。到着直後に予約カウンターへ向かうこと。" },
      { type: "heading", content: "但馬牛と有馬山椒の会席", level: 2 },
      { type: "text", content: "有馬温泉の旅館夕食は但馬産食材が基本。但馬牛の鉄板焼き、有馬山椒を使った料理、丹波篠山の黒豆豆腐など、兵庫の食材が一夕に集結する。献立は季節によって大きく変わるため、同じ宿でも季節を変えて再訪する価値がある。" },
      { type: "heading", content: "翌朝の金の湯で旅を締める", level: 2 },
      { type: "text", content: "旅館内の金泉に十分浸かった後でも、翌朝チェックアウト前に公共の「金の湯」に立ち寄ることをおすすめする。昨夜の贅沢な体験の後に、大衆浴場の素朴な良さを対比で感じると、有馬温泉の全体像が見えてくる。" },
    ],
    relatedArticleSlugs: ["hyogo-arima-onsen-guide", "hyogo-kinosaki-couple-trip"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "hyogo-luxury-kobe-hotel",
    title: "神戸の高級ホテルに泊まる──海側の部屋と朝食の価値",
    description: "神戸のシティホテルは全国でもトップクラスの洗練度を持つ。港ビューの客室から見る朝の神戸港。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "hyogo",
    tags: ["神戸", "高級ホテル", "贅沢旅", "港ビュー"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "ポートタワー側の客室を指定する", level: 2 },
      { type: "text", content: "ハーバーランド周辺のホテルは海側の客室と山側の客室で眺望が大きく異なる。予約時に「ポートタワービュー」や「シービュー」を指定すると、朝の神戸港を窓から眺める朝を体験できる。追加料金を払う価値は十分ある。" },
      { type: "heading", content: "神戸ホテルの朝食バッフェは別格", level: 2 },
      { type: "text", content: "神戸の高級ホテルの朝食は、神戸牛を使ったローストビーフ、神戸発祥の洋菓子ブランドのパン、播磨灘の鮮魚など神戸産食材が並ぶ。外食のモーニングより価値がある場合が多く、宿泊プランに組み込むことを強くすすめる。" },
      { type: "heading", content: "スパとフィットネスで街歩きの疲れを癒す", level: 2 },
      { type: "text", content: "神戸の坂道を1日歩いた後のホテルスパは効果が高い。ロウリュウサウナやジャグジーが完備した施設も多く、夜の夜景を眺めながら水風呂に入れる屋上プールがある宿もある。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-night-view", "hyogo-kobe-couple-date"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "hyogo-awaji-resort-stay",
    title: "淡路島リゾートステイ──海と山に囲まれた一泊の完全脱日常",
    description: "本州から橋を渡るだけで、完全なリゾートが始まる。淡路島の高級ホテルと食材の話。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "hyogo",
    tags: ["淡路島", "リゾート", "高級ホテル", "贅沢旅"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "淡路島の高級ホテルは絶景を売る", level: 2 },
      { type: "text", content: "淡路島の高級リゾートホテルは、大阪湾か鳴門海峡を望む絶景を最大の売りにしている。特に夕日の時間帯に大阪湾を染める夕焼けは、都市のホテルでは絶対に体験できない景色だ。" },
      { type: "heading", content: "淡路島食材の贅沢フルコース", level: 2 },
      { type: "text", content: "淡路牛、淡路玉ねぎ、鳴門海峡の天然鯛、淡路の海藻。島内の高級旅館の夕食は、すべて島産食材で完結できるほど食の宝庫だ。漁港直送の魚介は鮮度が違い、一度食べると忘れられない。" },
      { type: "heading", content: "翌朝の早起きドライブが最高のおまけ", level: 2 },
      { type: "text", content: "淡路島は早朝にレンタカーで走ると、観光客がいない絶景道路を独占できる。島の北端から南端まで約1時間の海沿いのドライブは、リゾートの締めくくりとして最高の時間になる。" },
    ],
    relatedArticleSlugs: ["hyogo-awaji-island-drive", "hyogo-akashi-bridge-view"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "hyogo-kinosaki-winter-crab",
    title: "冬の城崎温泉──松葉ガニ解禁と雪の温泉街を楽しむ",
    description: "11月の第3土曜日、松葉ガニの漁が解禁される。城崎の冬は日本の温泉旅行の頂点かもしれない。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hyogo",
    tags: ["城崎温泉", "松葉ガニ", "冬", "季節特集"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "11月解禁直後が最も感動的", level: 2 },
      { type: "text", content: "松葉ガニ解禁の週末に城崎に来ると、旅館の夕食に出てくるカニの鮮度と量が圧倒的だ。解禁直後は相場が高めだが、それに見合う体験がある。解禁週の旅館予約は9月中に行うこと。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "雪の大谿川沿いの外湯巡り", level: 2 },
      { type: "text", content: "城崎温泉は冬に雪が積もることがある。柳の木に雪が積もり、湯けむりが上がる温泉街の夜は、城崎最高のシーンのひとつだ。雪の夜の外湯巡りは、寒さが増すほど温泉のありがたさが倍増する体験になる。" },
      { type: "heading", content: "温泉玉子と城崎ジェラート", level: 2 },
      { type: "text", content: "城崎の外湯の入口近くには、温泉の熱で作る温泉玉子の販売スタンドがある。冬に温泉玉子を食べながら雪の川沿いを歩く光景は、SNS映えより先に「今ここにいる幸せ」を実感させてくれる。" },
    ],
    relatedArticleSlugs: ["hyogo-kinosaki-onsen-walk", "hyogo-kinosaki-couple-trip"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-spring-flowers",
    title: "神戸の春──須磨の桜と布引ハーブ園の花、2月〜5月のフラワーカレンダー",
    description: "神戸は花の街でもある。梅から始まり、桜、藤、ハーブへと続く春の花の連鎖を追う。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hyogo",
    tags: ["桜", "春", "神戸", "フラワーパーク"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "2月：須磨の梅林が最初の春を告げる", level: 2 },
      { type: "text", content: "須磨離宮公園の梅林は、250本以上の梅が2月中旬に開花する。白・ピンク・紅の梅が斜面に広がる光景は、まだ肌寒い季節に「もう春が来ている」という実感を与えてくれる。入場料は大人200円。" },
      { type: "heading", content: "4月上旬：須磨浦公園の桜並木", level: 2 },
      { type: "text", content: "須磨浦公園の約1000本の桜は、山陽電車の沿線に延々と続く並木道を形成する。電車の車窓から桜トンネルを通る体験は、神戸の桜シーズンの定番だ。須磨浦公園駅でロープウェイに乗ると山頂からの桜景色も楽しめる。" },
      { type: "heading", content: "5月：布引ハーブ園のローズシーズン", level: 2 },
      { type: "text", content: "布引ハーブ園の薔薇は5月中旬から6月上旬が見頃。200種2000株のバラが一度に咲く様子は、香りも含めて五感を刺激する圧倒的な体験だ。ハーブ園内のレストランで薔薇のハーブティーと合わせるのが定番の楽しみ方。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-castle-season", "hyogo-awaji-island-drive"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "hyogo-kinosaki-solo-trip",
    title: "一人で城崎温泉に行く──外湯巡りと文学碑と静かな夜",
    description: "城崎温泉は一人旅に最適な温泉地のひとつだ。志賀直哉が滞在した宿で書く日記の充実感。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "hyogo",
    tags: ["一人旅", "城崎温泉", "文学", "温泉"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "志賀直哉が書いた「城の崎にて」の舞台", level: 2 },
      { type: "text", content: "城崎温泉は志賀直哉の小説「城の崎にて」の舞台だ。療養のために訪れた作家が、大谿川で小動物の命の儚さを見ながら生死について書いた作品。文学碑を辿りながら川沿いを歩くと、作品の視点で城崎が見えてくる。" },
      { type: "heading", content: "一人だからこそゆっくり入れる外湯", level: 2 },
      { type: "text", content: "グループで外湯を回ると「次はどこ？」という会話が続くが、一人なら時間の縛りがない。一つの外湯で1時間以上のんびりすることも可能。大きな湯に一人で浸かる贅沢は、一人旅にしかできない体験だ。" },
      { type: "heading", content: "夜のならまちで読書と酒", level: 2 },
      { type: "text", content: "城崎の夜は早く静かになる。旅館に戻る前に、温泉街の小さな居酒屋で地酒と肴を一人で楽しむ時間は、旅の振り返りに最適だ。城崎の冬に一人で飲む日本酒の味は、他のどこでも再現できない。" },
    ],
    relatedArticleSlugs: ["hyogo-kinosaki-onsen-walk", "hyogo-kinosaki-winter-crab"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-access-guide",
    title: "神戸へのアクセス完全ガイド──新幹線・飛行機・高速バスの最適ルート",
    description: "新大阪から15分、大阪から30分。神戸は実は「日本で最もアクセスしやすい観光地」のひとつだ。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-02-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hyogo",
    tags: ["アクセス", "交通", "新幹線", "神戸"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "新幹線は新神戸駅が最寄り", level: 2 },
      { type: "text", content: "新幹線利用の場合、新神戸駅で下車すると地下鉄に乗り換えて三宮まで2分。新幹線の停車駅としては異例の市街地近接度だ。東京からも新大阪で乗り換えると、約4時間で三宮に到着する。" },
      { type: "heading", content: "大阪・京都からは阪急・JR・阪神を使い分ける", level: 2 },
      { type: "text", content: "大阪梅田からは阪急神戸線（三宮まで約28分）、JR神戸線（三ノ宮まで約21分）、阪神本線（三宮まで約32分）の3ルートがある。目的地によって乗り換え駅を変えると効率が良い。JRは速さが最優先の場合に選ぶ。" },
      { type: "heading", content: "神戸空港は使いやすい穴場空港", level: 2 },
      { type: "text", content: "神戸空港は市内から10分でアクセスできるコンパクトな空港だ。就航路線は限られるが、東京・札幌・那覇などの主要都市からの便がある。三宮まではポートライナーで18分。空港内は小さいが混雑しにくく使いやすい。" },
    ],
    relatedArticleSlugs: ["hyogo-budget-kobe-guide", "hyogo-kobe-night-view"],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "hyogo-himeji-gourmet",
    title: "姫路のグルメ──駅前の穴場食堂とえきそば、あなご料理",
    description: "姫路城だけが目的なら勿体ない。姫路には播磨の食文化が詰まった独自のグルメシーンがある。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-08-25",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "hyogo",
    tags: ["姫路", "グルメ", "えきそば", "あなご"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "えきそばは姫路駅ホームで食べる", level: 2 },
      { type: "text", content: "姫路駅の在来線ホームにある「まねき食堂」のえきそばは、和そばに中華麺を組み合わせた姫路独自のハイブリッドフード。大正時代からの歴史を持つ立ち食いそばで、乗り換え時間のわずかな時間に食べるのが正式な作法だ。" },
      { type: "heading", content: "穴子料理は姫路の隠れた名物", level: 2 },
      { type: "text", content: "播磨灘で獲れる穴子は脂がのっていて肉厚だ。姫路駅周辺の和食店では穴子の天ぷら、穴子の蒲焼き丼、穴子めしが郷土料理として提供されている。東京の穴子とは異なる甘みが特徴で、地元では弁当にも穴子めしが使われる。" },
      { type: "heading", content: "姫路おでんは生姜醤油で食べる", level: 2 },
      { type: "text", content: "姫路のおでんは生姜醤油をかけて食べるのが地元流だ。生姜の香りとおでんの出汁が合わさった独特の食べ方は、全国的に見ても珍しい文化だ。居酒屋で「生姜醤油ください」と頼むと通扱いされる。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-day-trip", "hyogo-himeji-castle-guide"],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-photo-spots",
    title: "神戸の写真映えスポット10選──夜景・港・洋館・路地",
    description: "神戸は歩くだけで写真が撮れる街だ。プロが選ぶ10の撮影スポットと最適な時間帯を解説。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hyogo",
    tags: ["写真映え", "神戸", "フォトスポット", "インスタ"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "北野坂の洋館と花壇", level: 2 },
      { type: "text", content: "北野坂に並ぶ洋館の外壁と手前に植えられた季節の花を組み合わせた構図は、神戸で最も撮りやすいフォトスポットだ。午前中の柔らかい光の時間帯に、標準〜広角レンズで撮影するのが定石。" },
      { type: "heading", content: "旧居留地のビルと空の対角線構図", level: 2 },
      { type: "text", content: "明治時代の石造りのビルが並ぶ旧居留地は、見上げる構図でビルの列と空の対比を切り取るのがおすすめ。薄曇りの日が影が出なくて撮りやすく、夕方の暖かい光よりも均一な光のある昼過ぎが狙い目だ。" },
      { type: "heading", content: "メリケンパークの水面反射", level: 2 },
      { type: "text", content: "メリケンパークの海面は穏やかな日に神戸ポートタワーを映し込む。夜のライトアップが水面に映る構図は、長秒露光をスマホの夜景モードで撮ると実現できる。三脚があるとなお確実だ。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-night-view", "hyogo-kitano-ijinkan-walk"],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "hyogo-family-himeji-trip",
    title: "姫路・子連れ家族旅行──城と動物園と水族館の完全1日プラン",
    description: "姫路城の隣には動物園がある。しかも無料で入れる。子連れ家族が知らなきゃ損の姫路情報。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "hyogo",
    tags: ["姫路", "子連れ", "動物園", "家族旅行"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "姫路城入場料で動物園も無料", level: 2 },
      { type: "text", content: "姫路城の敷地内にある姫路市立動物園は、城への入場券があれば追加料金なしで入場できる。キリン・ライオン・カバなど約100種の動物がいる本格的な動物園で、子どもは城より動物園に時間がかかることも。" },
      { type: "spot-card", content: "himeji" },
      { type: "heading", content: "城内見学は子ども向け解説が充実", level: 2 },
      { type: "text", content: "姫路城の内部見学は、子ども向けのクイズ形式の解説パネルが各所に設けられている。「この武器は何に使った？」「この穴の形の意味は？」という問いかけが、子どもを自然に城の歴史に引き込む。" },
      { type: "heading", content: "手柄山の水族館でクールダウン", level: 2 },
      { type: "text", content: "姫路市内の手柄山遊園地内にある水族館「姫路市立水族館」は、地元民御用達の小ぢんまりした水族館だ。大型施設ほどの迫力はないが、播磨灘の地魚が充実しており、タコやエビの展示が子どもに人気だ。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-day-trip", "hyogo-family-kobe-trip"],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "hyogo-arima-day-trip",
    title: "有馬温泉日帰りプラン──三宮から45分、温泉と炭酸せんべいの半日旅",
    description: "有馬温泉は泊まらなくても十分楽しい。日帰り入浴とお土産でも有馬の真価を体感できる。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-04-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hyogo",
    tags: ["有馬温泉", "日帰り温泉", "炭酸せんべい", "神戸近郊"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "三宮からバスで45分、有馬は近い", level: 2 },
      { type: "text", content: "神戸市営地下鉄と神戸電鉄を乗り継ぐと三宮から有馬温泉まで約45分。直通バスを使うと乗り換えなしでアクセスできる。神戸観光の午後のオプションとして有馬温泉を組み込む旅人が急増している。" },
      { type: "heading", content: "日帰り入浴は「金の湯」「銀の湯」で十分", level: 2 },
      { type: "text", content: "旅館に泊まらなくても「金の湯」「銀の湯」の公共浴場で有馬の二大泉質を体験できる。セット券を使えば両方入れて1000円以内。混雑する週末は平日より30分多く待つことも覚悟しておくこと。" },
      { type: "heading", content: "炭酸せんべいは有馬名物の本命土産", level: 2 },
      { type: "text", content: "有馬温泉の銀泉（炭酸泉）を使って作られる炭酸せんべいは、薄くてパリパリした食感が特徴の焼き菓子だ。温泉街に複数の店舗があり、目の前で焼き上げる実演販売も見もの。神戸より安く、神戸らしい土産として重宝される。" },
    ],
    relatedArticleSlugs: ["hyogo-arima-onsen-guide", "hyogo-luxury-arima-ryokan"],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "hyogo-kobe-earthquake-memory",
    title: "阪神淡路大震災の記憶を辿る旅──人と防災未来センターと震災遺構",
    description: "1995年1月17日。あの日から30年。神戸で震災の記憶と向き合う旅が、今の神戸を理解する近道だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-17",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "hyogo",
    tags: ["震災", "神戸", "防災", "歴史"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "人と防災未来センターで震災を学ぶ", level: 2 },
      { type: "text", content: "阪神淡路大震災の記録を後世に伝える「人と防災未来センター」は、映像・体験・展示を組み合わせた本格的な防災ミュージアムだ。震災当日の映像と生存者の証言は、言葉では伝えられない震災の実相を示している。" },
      { type: "heading", content: "メリケンパークの震災遺構", level: 2 },
      { type: "text", content: "神戸港震災メモリアルパークには、震災で傾いた護岸がそのままの形で保存されている。平らなコンクリートが地面ごと歪んだ姿は、地震の力の大きさを視覚的に伝える生きた証拠だ。子どもと一緒に立ち寄ることで、防災意識を自然に育てられる。" },
      { type: "heading", content: "復興した神戸の今を歩く", level: 2 },
      { type: "text", content: "震災から30年、神戸は復興を遂げ、今や日本有数の住みよい都市として評価されている。震災の傷跡を辿りながら、現在の賑わいを見ると、人間の回復力と都市の強さを実感できる。これが神戸旅行の最後に訪れるべき理由だ。" },
    ],
    relatedArticleSlugs: ["hyogo-kobe-night-view", "hyogo-harbor-lunch-walk"],
  },
];
