import { Article } from "@/types/article";

export const allArticles: Article[] = [
  {
    slug: "kyoto-morning-route",
    title: "京都・早朝巡りの黄金ルート",
    description: "人がいない京都は、こんなにも美しい。6時スタートで回る、朝だけの京都。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kyoto",
    tags: ["早朝", "京都", "モデルコース", "写真映え"],
    spotIds: ["fushimi-inari", "kiyomizu", "gion", "arashiyama"],
    sections: [
      { type: "heading", content: "朝6時、伏見稲荷からはじまる", level: 2 },
      { type: "text", content: "観光客が殺到する前の千本鳥居は別世界。朝日が鳥居を照らすと、朱が一層鮮やかに見える。稲荷駅に着いたら、まっすぐ山に向かう。四ツ辻まで登ったら、振り返って京都の街を見下ろす。この時間、ここにいるのは自分だけ。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "7時半、清水寺へ移動", level: 2 },
      { type: "text", content: "清水寺は6時開門。8時前に着けば、舞台をほぼ独占できる。三年坂を降りながら、まだ閉まっている店の格子戸を眺める。観光地が「生活の場」に見える時間帯。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "9時、祇園を歩いて終わり", level: 2 },
      { type: "text", content: "花見小路は午前中なら静か。白川沿いを歩いて、この旅の余韻を味わう。これで京都の朝は完成。午後はゆっくりカフェでもいい。" },
      { type: "spot-card", content: "gion" },
    ],
    relatedArticleSlugs: ["osaka-kuiadaore"],
  },
  {
    slug: "osaka-kuiadaore",
    title: "大阪食い倒れ1日モデルコース",
    description: "朝から晩まで、胃袋だけで大阪を制覇する。食い倒れの正しい回り方。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["グルメ", "大阪", "食べ歩き", "モデルコース"],
    spotIds: ["dotonbori", "shinsekai"],
    sections: [
      { type: "heading", content: "朝は新世界のモーニング串カツから", level: 2 },
      { type: "text", content: "ジャンジャン横丁の串カツ屋は朝から開いている。ここで軽く5本。ソースは一度漬け。この鉄の掟を守れるかどうかで、大阪との相性がわかる。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "昼は道頓堀でたこ焼きハシゴ", level: 2 },
      { type: "text", content: "道頓堀のたこ焼きは店によって全然違う。外はカリカリ、中はトロトロが好きなら「わなか」。ふわとろ系なら「くくる」。はしごしても胃は意外ともつ。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "夜は法善寺横丁で締める", level: 2 },
      { type: "text", content: "道頓堀のネオンに疲れたら、法善寺横丁に逃げ込む。石畳の路地に小さな割烹が並ぶ。水かけ不動に手を合わせて、今日食べたものへの感謝を伝える。大阪の食い倒れは、こうして締めるのが正解。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route"],
  },
  {
    slug: "kinosaki-complete",
    title: "城崎温泉 完全ガイド──外湯7湯の正しい回り方",
    description: "城崎温泉を「正解」で回る方法。7つの外湯をハシゴする、温泉街の流儀。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "hyogo",
    tags: ["温泉", "城崎", "カップル", "冬"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "城崎の流儀：宿に着いたら、まず外へ出ろ", level: 2 },
      { type: "text", content: "城崎温泉の楽しみ方は明確。チェックインしたら浴衣に着替えて、ゲタを鳴らして外湯へ向かう。宿の内湯に入るのは最後でいい。それが城崎の流儀。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "外湯7湯、どれから入る？", level: 2 },
      { type: "text", content: "一番人気は「御所の湯」。滝を見ながら入れる露天風呂がある。「一の湯」は洞窟風呂。「地蔵湯」は家族向け。全部入るなら、1日券を買って3〜4湯に絞るのが現実的。欲張ると湯あたりする。" },
      { type: "heading", content: "冬のカニ、これだけは食べろ", level: 2 },
      { type: "text", content: "11月〜3月の松葉ガニシーズンに来るなら、カニ刺し→焼きガニ→カニすき→雑炊のフルコース一択。予算は張るが、この体験は一生モノ。城崎に冬に来る理由の半分はこれ。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route"],
  },
  {
    slug: "nara-deer-guide",
    title: "奈良公園の鹿と正しく付き合う方法",
    description: "鹿せんべいを持った瞬間から始まるサバイバル。正しい鹿との距離感。",
    coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nara",
    tags: ["奈良", "家族", "のんびり", "コツ"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "鹿は野生動物である", level: 2 },
      { type: "text", content: "奈良公園の鹿は国の天然記念物で、れっきとした野生動物。可愛いけど、鹿せんべいを見せた瞬間に囲まれる。子鹿は特に積極的。落ち着いて、せんべいを高く掲げず、一枚ずつ渡すのがコツ。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "東大寺まで歩く", level: 2 },
      { type: "text", content: "奈良公園から東大寺は歩いてすぐ。大仏殿に入ると、想像の3倍デカい大仏が待っている。柱の穴くぐりは子供だけじゃなく、大人もチャレンジする。通れたら厄除けになるらしい。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route"],
  },
  {
    slug: "kumano-kodo-beginner",
    title: "熊野古道、初心者はここだけ歩けばいい",
    description: "全部歩くと3日かかる熊野古道。初めてなら3時間のこのルートで十分。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "wakayama",
    tags: ["トレッキング", "一人旅", "歴史", "和歌山"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "発心門王子からスタート", level: 2 },
      { type: "text", content: "熊野古道を全部歩く必要はない。発心門王子から熊野本宮大社までの約7kmが、初心者にちょうどいい距離。3時間でゴールできる。石畳の道、苔、木漏れ日——熊野古道の「核」はこの区間に凝縮されている。" },
      { type: "spot-card", content: "kumano-kodo" },
      { type: "heading", content: "大斎原で旅を締める", level: 2 },
      { type: "text", content: "熊野本宮大社に着いたら、そのまま大斎原まで歩く。田んぼの中に突然現れる日本一の大鳥居。朱色の門と青空のコントラスト。ここに立った瞬間、歩いてきた意味がわかる。" },
    ],
    relatedArticleSlugs: ["kinosaki-complete"],
  },
];
