import { Article } from "@/types/article";

export const allArticles: Article[] = [
  // ════════════════════════════════════════
  //  京都府（12件）
  // ════════════════════════════════════════
  {
    slug: "kyoto-morning-route",
    title: "京都・早朝巡りの黄金ルート",
    description: "人がいない京都は、こんなにも美しい。6時スタートで回る、朝だけの京都。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-03-15", author: "旅のしおり屋さん編集部",
    category: "model-course", prefectureId: "kyoto",
    tags: ["早朝", "京都", "モデルコース", "写真映え"],
    spotIds: ["fushimi-inari", "kiyomizu", "gion", "arashiyama"],
    sections: [
      { type: "heading", content: "朝6時、伏見稲荷からはじまる", level: 2 },
      { type: "text", content: "観光客が殺到する前の千本鳥居は別世界。朝日が鳥居を照らすと、朱が一層鮮やかに見える。稲荷駅に着いたら、まっすぐ山に向かう。四ツ辻まで登ったら、振り返って京都の街を見下ろす。この時間、ここにいるのは自分だけ。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "7時半、清水寺へ移動", level: 2 },
      { type: "text", content: "清水寺は6時開門。8時前に着けば、舞台をほぼ独占できる。三年坂を降りながら、まだ閉まっている店の格子戸を眺める。観光地が「生活の場」に見える時間帯。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "9時、祇園を歩いて終わり", level: 2 },
      { type: "text", content: "花見小路は午前中なら静か。白川沿いを歩いて、この旅の余韻を味わう。これで京都の朝は完成。" },
      { type: "spot-card", content: "gion" },
    ],
    relatedArticleSlugs: ["kyoto-autumn-leaves", "kyoto-cafe-5"],
  },
  {
    slug: "kyoto-autumn-leaves",
    title: "京都紅葉ガイド──見頃を外さないための5つのルール",
    description: "11月の京都は混む。でも、時間と場所を選べば、静かな紅葉がある。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-10-28", author: "旅のしおり屋さん編集部",
    category: "seasonal", prefectureId: "kyoto",
    tags: ["紅葉", "京都", "秋", "写真映え"],
    spotIds: ["kiyomizu", "arashiyama"],
    sections: [
      { type: "heading", content: "ルール1：11月中旬を狙え", level: 2 },
      { type: "text", content: "京都の紅葉ピークは11月15日〜25日あたり。早すぎると緑が残り、遅すぎると散り始める。" },
      { type: "heading", content: "ルール2：早朝か夕方以降を選べ", level: 2 },
      { type: "text", content: "昼間の清水寺は激混み。開門直後の6時か、ライトアップの17時半以降が狙い目。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "ルール3：穴場は東福寺の裏", level: 2 },
      { type: "text", content: "東福寺は紅葉の名所だが正面は混む。方丈庭園側から見ると静かに楽しめる。" },
      { type: "heading", content: "ルール4：嵐山は常寂光寺へ", level: 2 },
      { type: "text", content: "渡月橋は写真スポット。紅葉なら常寂光寺か祇王寺。苔と紅葉のコントラストは京都随一。" },
      { type: "spot-card", content: "arashiyama" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route"],
  },
  {
    slug: "kyoto-cafe-5",
    title: "京都のカフェ5選──観光の合間に寄るべき店",
    description: "抹茶ラテじゃない、本気の京都カフェ。地元民が通う5軒。",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    publishedAt: "2025-04-10", author: "旅のしおり屋さん編集部",
    category: "gourmet", prefectureId: "kyoto",
    tags: ["カフェ", "京都", "グルメ", "一人旅"],
    spotIds: ["gion"],
    sections: [
      { type: "heading", content: "1. % Arabica 京都 東山", level: 2 },
      { type: "text", content: "八坂の塔を眺めながらラテを飲む。ロケーションだけで勝っている店。" },
      { type: "heading", content: "2. Weekenders Coffee", level: 2 },
      { type: "text", content: "富小路通にある焙煎所兼カフェ。スペシャルティコーヒーを真剣に淹れている。" },
      { type: "heading", content: "3. WIFE&HUSBAND", level: 2 },
      { type: "text", content: "北山の住宅街にひっそりある。古い一軒家を改装した空間。" },
      { type: "heading", content: "4. 六曜社 地下店", level: 2 },
      { type: "text", content: "河原町の地下に50年以上ある喫茶店。ネルドリップの深い味。ドーナツが名物。" },
      { type: "heading", content: "5. 喫茶 ソワレ", level: 2 },
      { type: "text", content: "祇園四条のレトロ喫茶。ゼリーポンチは見た目で注文する。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "kyoto-gion-night"],
  },
  { slug: "kyoto-gion-night", title: "祇園の夜──18時以降の花見小路の歩き方", description: "観光客が消えた祇園は、別の顔を見せる。夕暮れ以降のルート。", coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80", publishedAt: "2025-05-20", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "kyoto", tags: ["夜", "祇園", "京都", "カップル"], spotIds: ["gion"], sections: [{ type: "heading", content: "17時半、四条大橋から始める", level: 2 }, { type: "text", content: "鴨川の夕暮れを眺めてから歩き始める。西の空が赤く染まる時間帯が一番いい。" }, { type: "heading", content: "18時、花見小路に入る", level: 2 }, { type: "text", content: "昼間の喧騒が嘘のように静か。格子戸の奥から三味線の音が聴こえることがある。" }, { type: "spot-card", content: "gion" }, { type: "heading", content: "19時、白川沿いを歩く", level: 2 }, { type: "text", content: "柳が揺れる白川沿いは、京都で最もロマンチックな散歩道。" }], relatedArticleSlugs: ["kyoto-cafe-5"] },
  { slug: "kyoto-arashiyama-half-day", title: "嵐山を半日で回るルート──竹林・渡月橋・天龍寺", description: "嵐山は広い。半日で「ここだけ」を回る最短ルート。", coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80", publishedAt: "2025-06-05", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "kyoto", tags: ["嵐山", "京都", "半日", "自然"], spotIds: ["arashiyama"], sections: [{ type: "heading", content: "9時、竹林の小径からスタート", level: 2 }, { type: "text", content: "天龍寺の北門から竹林に入る。このルートなら逆流する観光客を避けられる。" }, { type: "spot-card", content: "arashiyama" }, { type: "heading", content: "10時、天龍寺の庭園", level: 2 }, { type: "text", content: "曹源池庭園は嵐山を借景にした名庭。池の前のベンチに座って、ぼーっとする時間を作る。" }, { type: "heading", content: "11時、渡月橋で締める", level: 2 }, { type: "text", content: "渡月橋は渡るだけでいい。橋の上から嵐山を振り返る。" }], relatedArticleSlugs: ["kyoto-morning-route"] },
  { slug: "kyoto-fushimi-sake", title: "伏見の酒蔵巡り──日本酒の聖地を歩く", description: "伏見稲荷だけじゃない。伏見の本当の魅力は「水」と「酒」にある。", coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80", publishedAt: "2025-07-12", author: "旅のしおり屋さん編集部", category: "gourmet", prefectureId: "kyoto", tags: ["日本酒", "伏見", "京都", "大人旅"], spotIds: ["fushimi-inari"], sections: [{ type: "heading", content: "伏見は「水の街」", level: 2 }, { type: "text", content: "伏見の地下水は日本酒造りに最適な軟水。月桂冠、黄桜——名だたる酒蔵が集まる理由がここにある。" }, { type: "heading", content: "月桂冠大倉記念館", level: 2 }, { type: "text", content: "入場料400円で利き酒3杯つき。酒造りの歴史を学んだ後に飲む一杯は、格別にうまい。" }, { type: "heading", content: "十石舟に乗る", level: 2 }, { type: "text", content: "濠川を船で下る。柳並木と酒蔵の白壁が続く風景。春は桜のトンネルになる。" }], relatedArticleSlugs: ["kyoto-morning-route"] },
  { slug: "kyoto-winter-quiet", title: "冬の京都──観光客がいない12月の楽しみ方", description: "冬の京都は底冷えする。でも、だからこそ見える景色がある。", coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80", publishedAt: "2025-12-01", author: "旅のしおり屋さん編集部", category: "seasonal", prefectureId: "kyoto", tags: ["冬", "京都", "穴場", "一人旅"], spotIds: ["kiyomizu", "gion"], sections: [{ type: "heading", content: "12月の京都は空いている", level: 2 }, { type: "text", content: "紅葉が終わり、年末前の12月上旬〜中旬は京都のオフシーズン。普段は行列の店も、すっと入れる。" }, { type: "heading", content: "冬の清水寺は雪化粧を狙え", level: 2 }, { type: "text", content: "京都に雪が積もるのは年に数回。その日に清水寺に行けたら、人生で忘れられない景色になる。" }, { type: "spot-card", content: "kiyomizu" }, { type: "heading", content: "湯豆腐を食べろ", level: 2 }, { type: "text", content: "南禅寺の順正か奥丹。冬の京都で湯豆腐を食べないのは、来た意味の半分を失う。" }], relatedArticleSlugs: ["kyoto-cafe-5"] },
  { slug: "kyoto-couple-1day", title: "京都デート1日プラン──記憶に残る1日をつくる", description: "定番を外して、ふたりだけの京都を見つけるルート。", coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80", publishedAt: "2025-08-14", author: "旅のしおり屋さん編集部", category: "couple", prefectureId: "kyoto", tags: ["カップル", "京都", "デート", "モデルコース"], spotIds: ["arashiyama", "gion"], sections: [{ type: "heading", content: "午前：嵐山でふたりの時間", level: 2 }, { type: "text", content: "竹林の小径を並んで歩く。人力車は2人乗りがある。車夫が穴場を教えてくれる。" }, { type: "spot-card", content: "arashiyama" }, { type: "heading", content: "午後：祇園で和菓子と散策", level: 2 }, { type: "text", content: "鍵善良房のくずきりを食べる。白川沿いを手を繋いで歩く。" }, { type: "spot-card", content: "gion" }, { type: "heading", content: "夜：鴨川沿いで食事", level: 2 }, { type: "text", content: "先斗町の小さな店を選ぶ。鴨川を眺めながら京料理を食べる。" }], relatedArticleSlugs: ["kyoto-gion-night"] },
  { slug: "kyoto-uji-matcha", title: "宇治・抹茶の街を歩く──平等院だけじゃない宇治の魅力", description: "抹茶のふるさと宇治。茶畑から始まる、本物の抹茶体験。", coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80", publishedAt: "2025-09-03", author: "旅のしおり屋さん編集部", category: "gourmet", prefectureId: "kyoto", tags: ["宇治", "抹茶", "京都", "グルメ"], spotIds: [], sections: [{ type: "heading", content: "平等院は朝一で", level: 2 }, { type: "text", content: "10円玉の裏に描かれた建物。実物は10円玉の100倍美しい。" }, { type: "heading", content: "宇治橋通りで抹茶ハシゴ", level: 2 }, { type: "text", content: "中村藤吉の抹茶パフェ、伊藤久右衛門の抹茶そば、福寿園の抹茶ラテ。3軒回れば宇治の抹茶は制覇。" }, { type: "heading", content: "宇治川沿いを散歩", level: 2 }, { type: "text", content: "宇治川の流れは京都市内の鴨川より力強い。川沿いのベンチで茶団子を食べる。" }], relatedArticleSlugs: ["kyoto-cafe-5"] },
  { slug: "kyoto-budget-trip", title: "京都を3,000円で楽しむ方法", description: "金がなくても京都は楽しい。無料スポットと安い飯で回るルート。", coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80", publishedAt: "2025-04-25", author: "旅のしおり屋さん編集部", category: "budget", prefectureId: "kyoto", tags: ["節約", "京都", "学生旅", "一人旅"], spotIds: ["fushimi-inari", "gion"], sections: [{ type: "heading", content: "伏見稲荷は無料", level: 2 }, { type: "text", content: "京都最大の観光地が無料という事実。朝から夕方まで、千本鳥居をゆっくり歩ける。" }, { type: "spot-card", content: "fushimi-inari" }, { type: "heading", content: "昼は錦市場でつまみ食い", level: 2 }, { type: "text", content: "錦市場は「京都の台所」。串1本200円前後。5本も食べれば昼飯は十分。" }, { type: "heading", content: "祇園の散策は無料", level: 2 }, { type: "text", content: "花見小路も白川沿いも歩くだけなら無料。京都の風情は金をかけなくても味わえる。" }, { type: "spot-card", content: "gion" }], relatedArticleSlugs: ["kyoto-morning-route"] },
  { slug: "kyoto-rainy-day", title: "雨の京都──濡れた石畳が美しい5つの場所", description: "雨の京都はハズレじゃない。むしろ、雨の日だけの景色がある。", coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80", publishedAt: "2025-06-15", author: "旅のしおり屋さん編集部", category: "tips", prefectureId: "kyoto", tags: ["雨の日", "京都", "室内", "穴場"], spotIds: ["kiyomizu", "gion"], sections: [{ type: "heading", content: "1. 三十三間堂", level: 2 }, { type: "text", content: "1001体の千手観音が並ぶ。屋内なので雨でも問題ない。" }, { type: "heading", content: "2. 濡れた三年坂", level: 2 }, { type: "text", content: "雨に濡れた石畳は光を反射する。人が少なくなる分、写真映えする。" }, { type: "heading", content: "3. 京都国立博物館", level: 2 }, { type: "text", content: "明治古都館の建築自体が見もの。常設展だけでも2時間は潰せる。" }, { type: "heading", content: "4. 錦市場", level: 2 }, { type: "text", content: "アーケードなので雨でも大丈夫。食べ歩きしながら1時間。" }, { type: "heading", content: "5. 祇園の喫茶店", level: 2 }, { type: "text", content: "雨の日はカフェに籠もる。窓から見える雨の祇園もまた美しい。" }], relatedArticleSlugs: ["kyoto-cafe-5"] },

  // ════════════════════════════════════════
  //  大阪府（8件）
  // ════════════════════════════════════════
  { slug: "osaka-kuiadaore", title: "大阪食い倒れ1日モデルコース", description: "朝から晩まで、胃袋だけで大阪を制覇する。食い倒れの正しい回り方。", coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80", publishedAt: "2025-04-01", author: "旅のしおり屋さん編集部", category: "gourmet", prefectureId: "osaka", tags: ["グルメ", "大阪", "食べ歩き", "モデルコース"], spotIds: ["dotonbori", "shinsekai"], sections: [{ type: "heading", content: "朝は新世界のモーニング串カツから", level: 2 }, { type: "text", content: "ジャンジャン横丁の串カツ屋は朝から開いている。ここで軽く5本。ソースは一度漬け。" }, { type: "spot-card", content: "shinsekai" }, { type: "heading", content: "昼は道頓堀でたこ焼きハシゴ", level: 2 }, { type: "text", content: "道頓堀のたこ焼きは店によって全然違う。外カリ中トロなら「わなか」。ふわとろなら「くくる」。" }, { type: "spot-card", content: "dotonbori" }, { type: "heading", content: "夜は法善寺横丁で締める", level: 2 }, { type: "text", content: "道頓堀のネオンに疲れたら法善寺横丁に逃げ込む。水かけ不動に手を合わせて締めくくる。" }], relatedArticleSlugs: ["osaka-night-walk", "osaka-shinsekai-deep"] },
  { slug: "osaka-night-walk", title: "大阪ネオン散歩──夜の道頓堀から裏なんばへ", description: "道頓堀のネオンは表の顔。一本裏に入った「裏なんば」が本番。", coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80", publishedAt: "2025-05-10", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "osaka", tags: ["夜", "大阪", "ネオン", "グルメ"], spotIds: ["dotonbori"], sections: [{ type: "heading", content: "19時、戎橋からスタート", level: 2 }, { type: "text", content: "グリコの看板が一番輝く時間。写真はここで撮っておく。" }, { type: "spot-card", content: "dotonbori" }, { type: "heading", content: "20時、裏なんばへ", level: 2 }, { type: "text", content: "千日前を南に進むと、立ち飲み屋が並ぶエリアに入る。1杯500円のハイボールと串を楽しむ。" }, { type: "heading", content: "21時、法善寺で静かに終わる", level: 2 }, { type: "text", content: "酔い覚ましに法善寺横丁を歩く。大阪の夜を静かに締めてくれる。" }], relatedArticleSlugs: ["osaka-kuiadaore"] },
  { slug: "osaka-shinsekai-deep", title: "新世界ディープガイド──通天閣の足元で飲む", description: "新世界を観光で消費するな。ここは地元の人の飲み場だ。", coverImage: "https://images.unsplash.com/photo-1589452271712-64b8a66c3929?w=1200&q=80", publishedAt: "2025-06-20", author: "旅のしおり屋さん編集部", category: "gourmet", prefectureId: "osaka", tags: ["新世界", "大阪", "ディープ", "一人旅"], spotIds: ["shinsekai"], sections: [{ type: "heading", content: "朝10時、ジャンジャン横丁の串カツ", level: 2 }, { type: "text", content: "「だるま」は観光客向け。地元民は「てんぐ」か「八重勝」に行く。" }, { type: "spot-card", content: "shinsekai" }, { type: "heading", content: "昼、将棋クラブを覗く", level: 2 }, { type: "text", content: "新世界には将棋クラブがある。覗くだけでいい。これが新世界の日常。" }, { type: "heading", content: "夕方、スパワールドで風呂", level: 2 }, { type: "text", content: "世界の温泉が一箇所に集まった施設。串カツの油を落とすのに最適。" }], relatedArticleSlugs: ["osaka-kuiadaore"] },
  { slug: "osaka-family-1day", title: "大阪・家族で楽しむ1日プラン", description: "子供も大人も満足する大阪の回り方。USJなしでも十分楽しい。", coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80", publishedAt: "2025-07-15", author: "旅のしおり屋さん編集部", category: "family", prefectureId: "osaka", tags: ["家族", "大阪", "子連れ", "モデルコース"], spotIds: ["dotonbori", "shinsekai"], sections: [{ type: "heading", content: "午前：海遊館", level: 2 }, { type: "text", content: "世界最大級の水族館。ジンベエザメの巨大水槽の前で、子供が動かなくなる。" }, { type: "heading", content: "昼：道頓堀でたこ焼き", level: 2 }, { type: "text", content: "子供はたこ焼きが好き。目の前で焼いてくれる店を選ぶ。" }, { type: "spot-card", content: "dotonbori" }, { type: "heading", content: "午後：天王寺動物園", level: 2 }, { type: "text", content: "新世界のすぐ隣。入場料500円。コアラがいる。" }], relatedArticleSlugs: ["osaka-kuiadaore"] },
  { slug: "osaka-solo-gourmet", title: "大阪ひとり飯──カウンターで食べるのが正解", description: "ひとりで大阪に来たなら、カウンター席を選べ。", coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80", publishedAt: "2025-08-05", author: "旅のしおり屋さん編集部", category: "solo", prefectureId: "osaka", tags: ["一人旅", "大阪", "グルメ", "カウンター"], spotIds: ["dotonbori", "shinsekai"], sections: [{ type: "heading", content: "串カツはカウンターで食べるもの", level: 2 }, { type: "text", content: "テーブル席に1人で座るのは気が引ける。カウンターなら自然。揚げたてを1本ずつ注文する。" }, { type: "spot-card", content: "shinsekai" }, { type: "heading", content: "立ち飲み屋のハシゴ", level: 2 }, { type: "text", content: "裏なんばの立ち飲み屋は1人客が多い。3軒ハシゴしても3,000円以内。" }, { type: "heading", content: "締めのラーメン", level: 2 }, { type: "text", content: "道頓堀の川沿いで、400円のラーメンをすする。これが大阪のひとり飯。" }], relatedArticleSlugs: ["osaka-night-walk"] },
  { slug: "osaka-cheap-spots", title: "大阪を1,000円で楽しむ──無料＆激安スポット", description: "大阪は金がなくても楽しい街。1,000円あれば十分。", coverImage: "https://images.unsplash.com/photo-1589452271712-64b8a66c3929?w=1200&q=80", publishedAt: "2025-04-18", author: "旅のしおり屋さん編集部", category: "budget", prefectureId: "osaka", tags: ["節約", "大阪", "無料", "学生旅"], spotIds: ["dotonbori", "shinsekai"], sections: [{ type: "heading", content: "道頓堀を歩くのは無料", level: 2 }, { type: "text", content: "グリコ看板、かに道楽、食い倒れ太郎。見るだけなら全部タダ。" }, { type: "spot-card", content: "dotonbori" }, { type: "heading", content: "たこ焼き1舟400円", level: 2 }, { type: "text", content: "会津屋は元祖たこ焼き。ソースなしで食べる。1舟400円。" }, { type: "heading", content: "中之島公園でのんびり", level: 2 }, { type: "text", content: "レトロな中央公会堂を眺めながら、芝生に寝転ぶ。" }], relatedArticleSlugs: ["osaka-kuiadaore"] },
  { slug: "osaka-couple-night", title: "大阪デート夜プラン──ネオンから夜景へ", description: "大阪のデートは夜が本番。ネオンの街から、静かな夜景へ。", coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80", publishedAt: "2025-09-12", author: "旅のしおり屋さん編集部", category: "couple", prefectureId: "osaka", tags: ["カップル", "大阪", "夜景", "デート"], spotIds: ["dotonbori"], sections: [{ type: "heading", content: "18時、道頓堀から始める", level: 2 }, { type: "text", content: "グリコの看板の前で写真を撮る。ベタだけど、ベタがいい。" }, { type: "spot-card", content: "dotonbori" }, { type: "heading", content: "20時、梅田スカイビルの空中庭園", level: 2 }, { type: "text", content: "展望台からの夜景は大阪随一。風が強いから上着を持っていく。" }, { type: "heading", content: "21時半、北新地で食事", level: 2 }, { type: "text", content: "カウンター和食の店を予約しておく。これが大阪デートの正解。" }], relatedArticleSlugs: ["osaka-night-walk"] },
  { slug: "osaka-rainy-indoor", title: "雨の大阪──室内で1日楽しむ完全プラン", description: "大阪は雨でも楽しい。室内施設が充実しすぎている。", coverImage: "https://images.unsplash.com/photo-1589452271712-64b8a66c3929?w=1200&q=80", publishedAt: "2025-06-01", author: "旅のしおり屋さん編集部", category: "tips", prefectureId: "osaka", tags: ["雨の日", "大阪", "室内", "家族"], spotIds: ["shinsekai"], sections: [{ type: "heading", content: "午前：海遊館", level: 2 }, { type: "text", content: "雨の日の海遊館は空いている。ゆっくり回れるのはむしろラッキー。" }, { type: "heading", content: "昼：なんばグランド花月", level: 2 }, { type: "text", content: "吉本新喜劇は当日券で入れることが多い。2時間笑い続ける。" }, { type: "heading", content: "午後：スパワールド", level: 2 }, { type: "text", content: "世界各国の風呂がある。半日は潰せる。" }, { type: "spot-card", content: "shinsekai" }], relatedArticleSlugs: ["osaka-family-1day"] },

  // ════════════════════════════════════════
  //  兵庫県（6件）
  // ════════════════════════════════════════
  { slug: "kinosaki-complete", title: "城崎温泉 完全ガイド──外湯7湯の正しい回り方", description: "城崎温泉を「正解」で回る方法。外湯をハシゴする、温泉街の流儀。", coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80", publishedAt: "2025-02-20", author: "旅のしおり屋さん編集部", category: "onsen", prefectureId: "hyogo", tags: ["温泉", "城崎", "カップル", "冬"], spotIds: ["kinosaki"], sections: [{ type: "heading", content: "城崎の流儀：宿に着いたら、まず外へ出ろ", level: 2 }, { type: "text", content: "チェックインしたら浴衣に着替えて、ゲタを鳴らして外湯へ向かう。それが城崎の流儀。" }, { type: "spot-card", content: "kinosaki" }, { type: "heading", content: "外湯7湯、どれから入る？", level: 2 }, { type: "text", content: "一番人気は「御所の湯」。「一の湯」は洞窟風呂。「地蔵湯」は家族向け。全部入るなら3〜4湯に絞る。" }, { type: "heading", content: "冬のカニ、これだけは食べろ", level: 2 }, { type: "text", content: "11月〜3月の松葉ガニシーズン。カニ刺し→焼きガニ→カニすき→雑炊のフルコース一択。" }], relatedArticleSlugs: ["kinosaki-couple", "himeji-half-day"] },
  { slug: "kinosaki-couple", title: "城崎温泉カップル旅──浴衣で歩く、2人だけの夜", description: "浴衣を着て、ゲタを鳴らして、外湯をハシゴする。最高のデート。", coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80", publishedAt: "2025-11-05", author: "旅のしおり屋さん編集部", category: "couple", prefectureId: "hyogo", tags: ["カップル", "温泉", "城崎", "冬"], spotIds: ["kinosaki"], sections: [{ type: "heading", content: "15時チェックイン、すぐ浴衣に", level: 2 }, { type: "text", content: "宿に着いたら浴衣を選ぶ。色違いのペア浴衣が用意されている宿が多い。" }, { type: "spot-card", content: "kinosaki" }, { type: "heading", content: "16時、外湯めぐりスタート", level: 2 }, { type: "text", content: "2人で手をつないで温泉街を歩く。外湯の入口で一旦別れて、出口で待ち合わせる。" }, { type: "heading", content: "19時、柳並木のライトアップ", level: 2 }, { type: "text", content: "夜の城崎は柳がライトアップされる。温泉上がりの火照った体に冬の冷たい空気が気持ちいい。" }], relatedArticleSlugs: ["kinosaki-complete"] },
  { slug: "himeji-half-day", title: "姫路城と好古園──半日で回る白鷺の城", description: "姫路城は半日で十分。でも、好古園を足すと一日の価値になる。", coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80", publishedAt: "2025-03-25", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "hyogo", tags: ["城", "姫路", "歴史", "半日"], spotIds: ["himeji"], sections: [{ type: "heading", content: "9時、大手門から入る", level: 2 }, { type: "text", content: "開門直後が最も空いている。天守閣まで一気に登る。" }, { type: "spot-card", content: "himeji" }, { type: "heading", content: "11時、西の丸で写真を撮る", level: 2 }, { type: "text", content: "天守閣を最も美しく撮れるのは西の丸から。" }, { type: "heading", content: "12時、好古園で庭園散策", level: 2 }, { type: "text", content: "姫路城の隣にある日本庭園。抹茶を飲みながら庭を眺める。" }], relatedArticleSlugs: ["kinosaki-complete"] },
  { slug: "kobe-night-view", title: "神戸の夜景ガイド──1000万ドルの正しい見方", description: "六甲山からのパノラマか、メリケンパークの海沿いか。", coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80", publishedAt: "2025-10-15", author: "旅のしおり屋さん編集部", category: "couple", prefectureId: "hyogo", tags: ["夜景", "神戸", "カップル", "デート"], spotIds: [], sections: [{ type: "heading", content: "六甲山の展望台", level: 2 }, { type: "text", content: "掬星台から見る夜景は日本三大夜景のひとつ。" }, { type: "heading", content: "メリケンパーク", level: 2 }, { type: "text", content: "ポートタワーとBE KOBEモニュメント。海面に光が反射する。" }, { type: "heading", content: "ハーバーランドの観覧車", level: 2 }, { type: "text", content: "15分間、2人だけの空中散歩。デートの締めに最適。" }], relatedArticleSlugs: ["kinosaki-couple"] },
  { slug: "hyogo-arima-onsen", title: "有馬温泉──日帰りで楽しむ日本最古の湯", description: "神戸から30分。日帰りで行ける日本三古泉。", coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80", publishedAt: "2025-01-20", author: "旅のしおり屋さん編集部", category: "onsen", prefectureId: "hyogo", tags: ["温泉", "有馬", "日帰り", "神戸"], spotIds: [], sections: [{ type: "heading", content: "金泉と銀泉", level: 2 }, { type: "text", content: "金泉は鉄分を含んだ赤褐色の湯。銀泉は無色透明の炭酸泉。両方入るのが正解。" }, { type: "heading", content: "金の湯・銀の湯", level: 2 }, { type: "text", content: "公衆浴場は合計850円。タオルは持参。" }, { type: "heading", content: "温泉街を食べ歩く", level: 2 }, { type: "text", content: "炭酸せんべい、有馬サイダー、天神泉源の湯気。" }], relatedArticleSlugs: ["kinosaki-complete", "kobe-night-view"] },
  { slug: "hyogo-awaji-island", title: "淡路島1日ドライブ──海と花と淡路牛", description: "明石海峡大橋を渡れば、そこは島。1日で回る黄金ルート。", coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80", publishedAt: "2025-05-25", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "hyogo", tags: ["淡路島", "ドライブ", "グルメ", "自然"], spotIds: [], sections: [{ type: "heading", content: "10時、明石海峡大橋を渡る", level: 2 }, { type: "text", content: "橋を渡る瞬間のワクワク感。淡路SAで一度休憩。" }, { type: "heading", content: "12時、淡路牛を食べる", level: 2 }, { type: "text", content: "神戸牛の素牛が淡路牛。ステーキか、ハンバーガーか。" }, { type: "heading", content: "14時、あわじ花さじき", level: 2 }, { type: "text", content: "丘一面に花が咲く。海をバックにした花畑は圧巻。" }], relatedArticleSlugs: ["kobe-night-view"] },

  // ════════════════════════════════════════
  //  奈良県（5件）
  // ════════════════════════════════════════
  { slug: "nara-deer-guide", title: "奈良公園の鹿と正しく付き合う方法", description: "鹿せんべいを持った瞬間から始まるサバイバル。", coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80", publishedAt: "2025-01-10", author: "旅のしおり屋さん編集部", category: "tips", prefectureId: "nara", tags: ["奈良", "家族", "のんびり", "コツ"], spotIds: ["nara-park"], sections: [{ type: "heading", content: "鹿は野生動物である", level: 2 }, { type: "text", content: "奈良公園の鹿は国の天然記念物。鹿せんべいを見せた瞬間に囲まれる。落ち着いて一枚ずつ渡す。" }, { type: "spot-card", content: "nara-park" }, { type: "heading", content: "東大寺まで歩く", level: 2 }, { type: "text", content: "大仏殿に入ると、想像の3倍デカい大仏が待っている。" }], relatedArticleSlugs: ["nara-half-day", "nara-yoshino-spring"] },
  { slug: "nara-half-day", title: "奈良を半日で回る──東大寺・春日大社・ならまち", description: "奈良は半日で十分、と思ってた。実際は足りなかった。", coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80", publishedAt: "2025-03-05", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "nara", tags: ["奈良", "半日", "モデルコース", "歴史"], spotIds: ["nara-park"], sections: [{ type: "heading", content: "9時、東大寺", level: 2 }, { type: "text", content: "大仏殿→二月堂→手向山八幡宮。二月堂からの眺めが最高。" }, { type: "spot-card", content: "nara-park" }, { type: "heading", content: "11時、春日大社", level: 2 }, { type: "text", content: "石灯籠が並ぶ参道。午前中の木漏れ日が一番きれい。" }, { type: "heading", content: "12時、ならまちで昼食", level: 2 }, { type: "text", content: "柿の葉寿司かにゅうめんがいい。食後は雑貨屋を覗く。" }], relatedArticleSlugs: ["nara-deer-guide"] },
  { slug: "nara-yoshino-spring", title: "吉野山の桜──一目千本の正しい見方", description: "3万本の桜が山を染める。吉野の桜は「量」で圧倒する。", coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80", publishedAt: "2025-04-05", author: "旅のしおり屋さん編集部", category: "seasonal", prefectureId: "nara", tags: ["桜", "吉野", "春", "自然"], spotIds: ["yoshino"], sections: [{ type: "heading", content: "見頃は4月上旬〜中旬", level: 2 }, { type: "text", content: "下千本→中千本→上千本→奥千本と順に咲く。" }, { type: "spot-card", content: "yoshino" }, { type: "heading", content: "中千本からの眺めが最高", level: 2 }, { type: "text", content: "「一目千本」の名所。吉水神社の境内から見下ろす桜の海。" }, { type: "heading", content: "金峯山寺の秘仏", level: 2 }, { type: "text", content: "桜の時期だけ公開される蔵王権現。青い肌の巨大仏。" }], relatedArticleSlugs: ["nara-deer-guide"] },
  { slug: "nara-solo-temple", title: "奈良ひとり旅──静かな寺を巡る1日", description: "観光客が行かない奈良の寺。ひとりだから味わえる静けさ。", coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80", publishedAt: "2025-09-20", author: "旅のしおり屋さん編集部", category: "solo", prefectureId: "nara", tags: ["一人旅", "奈良", "寺院", "穴場"], spotIds: ["nara-park"], sections: [{ type: "heading", content: "薬師寺", level: 2 }, { type: "text", content: "東塔と西塔のバランスが美しい。早朝は人がほとんどいない。" }, { type: "heading", content: "唐招提寺", level: 2 }, { type: "text", content: "鑑真が建てた寺。金堂の列柱は奈良時代の空気をそのまま残している。" }, { type: "heading", content: "法隆寺", level: 2 }, { type: "text", content: "世界最古の木造建築。ひとりで静かに回ると、1400年前の時間が流れている気がする。" }], relatedArticleSlugs: ["nara-half-day"] },
  { slug: "nara-family-day", title: "子供と奈良──鹿と大仏で1日遊ぶ", description: "子供は鹿が好きだ。大仏も好きだ。奈良は子連れに最適。", coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80", publishedAt: "2025-07-01", author: "旅のしおり屋さん編集部", category: "family", prefectureId: "nara", tags: ["家族", "奈良", "子連れ", "鹿"], spotIds: ["nara-park"], sections: [{ type: "heading", content: "午前：鹿と遊ぶ", level: 2 }, { type: "text", content: "鹿せんべいは150円。子供に渡すと大興奮する。" }, { type: "spot-card", content: "nara-park" }, { type: "heading", content: "昼：東大寺の柱くぐり", level: 2 }, { type: "text", content: "大仏殿の柱に穴がある。子供はすいすい通れる。" }, { type: "heading", content: "午後：若草山に登る", level: 2 }, { type: "text", content: "芝生の山を登る。頂上まで30分。頂上からの眺めが最高のご褒美。" }], relatedArticleSlugs: ["nara-deer-guide"] },

  // ════════════════════════════════════════
  //  和歌山県（5件）
  // ════════════════════════════════════════
  { slug: "kumano-kodo-beginner", title: "熊野古道、初心者はここだけ歩けばいい", description: "全部歩くと3日かかる。初めてなら3時間のこのルートで十分。", coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80", publishedAt: "2025-05-01", author: "旅のしおり屋さん編集部", category: "solo", prefectureId: "wakayama", tags: ["トレッキング", "一人旅", "歴史", "和歌山"], spotIds: ["kumano-kodo"], sections: [{ type: "heading", content: "発心門王子からスタート", level: 2 }, { type: "text", content: "発心門王子から熊野本宮大社までの約7kmが初心者にちょうどいい。" }, { type: "spot-card", content: "kumano-kodo" }, { type: "heading", content: "大斎原で旅を締める", level: 2 }, { type: "text", content: "田んぼの中に突然現れる日本一の大鳥居。ここに立った瞬間、歩いてきた意味がわかる。" }], relatedArticleSlugs: ["wakayama-shirahama-summer"] },
  { slug: "wakayama-shirahama-summer", title: "白浜の夏──海・温泉・海鮮の完全プラン", description: "関西から一番近い南国。白い砂浜と露天風呂を1日で。", coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80", publishedAt: "2025-07-20", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "wakayama", tags: ["ビーチ", "白浜", "夏", "温泉"], spotIds: ["nanki-shirahama"], sections: [{ type: "heading", content: "10時、白良浜で泳ぐ", level: 2 }, { type: "text", content: "白い砂浜とエメラルドグリーンの海。関西にこんな場所があったのかと驚く。" }, { type: "spot-card", content: "nanki-shirahama" }, { type: "heading", content: "13時、とれとれ市場で海鮮丼", level: 2 }, { type: "text", content: "西日本最大級の海鮮市場。どれも新鮮で安い。" }, { type: "heading", content: "16時、崎の湯で太平洋を見ながら入浴", level: 2 }, { type: "text", content: "波しぶきが飛んでくる距離の露天風呂。これが白浜の最高の締め方。" }], relatedArticleSlugs: ["kumano-kodo-beginner"] },
  { slug: "wakayama-nachi-falls", title: "那智の滝と熊野那智大社──日本一の滝を見に行く", description: "落差133m。日本一の直瀑。滝の音だけが聞こえる場所。", coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80", publishedAt: "2025-08-10", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "wakayama", tags: ["滝", "神社", "自然", "パワースポット"], spotIds: ["kumano-kodo"], sections: [{ type: "heading", content: "那智の滝は近くで見ろ", level: 2 }, { type: "text", content: "滝壺の近くまで行ける。300円払って入る飛瀧神社の境内が最も近い。水しぶきが顔にかかる。" }, { type: "heading", content: "熊野那智大社へ登る", level: 2 }, { type: "text", content: "473段の石段を登る。三重塔と那智の滝が一緒に見える。" }, { type: "heading", content: "大門坂を歩く", level: 2 }, { type: "text", content: "杉並木と石畳の道。ここだけでも熊野古道の雰囲気を味わえる。" }], relatedArticleSlugs: ["kumano-kodo-beginner"] },
  { slug: "wakayama-adventure-park", title: "アドベンチャーワールド──パンダに会いに行く", description: "上野じゃなくて白浜。日本一パンダが多い場所は和歌山にある。", coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80", publishedAt: "2025-04-15", author: "旅のしおり屋さん編集部", category: "family", prefectureId: "wakayama", tags: ["パンダ", "家族", "白浜", "動物園"], spotIds: ["nanki-shirahama"], sections: [{ type: "heading", content: "パンダは午前中に見ろ", level: 2 }, { type: "text", content: "パンダは午前中が一番活発。笹を食べる姿を見るなら10時〜11時がベスト。" }, { type: "heading", content: "サファリワールドも回る", level: 2 }, { type: "text", content: "バスに乗ってライオンやキリンを間近に見る。" }, { type: "heading", content: "帰りに白良浜に寄る", level: 2 }, { type: "text", content: "車で10分。夕方の白良浜は人が少なくて最高。" }, { type: "spot-card", content: "nanki-shirahama" }], relatedArticleSlugs: ["wakayama-shirahama-summer"] },
  { slug: "wakayama-koyasan", title: "高野山1泊2日──宿坊に泊まる、非日常の体験", description: "山の上の聖地。宿坊に泊まって、朝のお勤めに参加する。", coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80", publishedAt: "2025-11-15", author: "旅のしおり屋さん編集部", category: "solo", prefectureId: "wakayama", tags: ["高野山", "宿坊", "一人旅", "スピリチュアル"], spotIds: [], sections: [{ type: "heading", content: "ケーブルカーで山上へ", level: 2 }, { type: "text", content: "南海高野線の終点からケーブルカーに乗る。山の上に1200年続く宗教都市がある。" }, { type: "heading", content: "奥之院を歩く", level: 2 }, { type: "text", content: "20万基の墓石が並ぶ参道。夜のナイトツアーは別格の体験。" }, { type: "heading", content: "宿坊に泊まる", level: 2 }, { type: "text", content: "精進料理を食べ、6時から朝のお勤めに参加する。読経の響きは体に染みる。" }], relatedArticleSlugs: ["kumano-kodo-beginner"] },

  // ════════════════════════════════════════
  //  滋賀県（3件）
  // ════════════════════════════════════════
  { slug: "shiga-biwako-drive", title: "琵琶湖ドライブ──湖を半周するベストルート", description: "日本一の湖を車で走る。湖東を北上して、メタセコイア並木へ。", coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80", publishedAt: "2025-05-30", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "shiga", tags: ["ドライブ", "琵琶湖", "自然", "写真映え"], spotIds: [], sections: [{ type: "heading", content: "大津からスタート", level: 2 }, { type: "text", content: "湖岸道路を北上する。左手にずっと琵琶湖が見える。窓を開けて風を感じる。" }, { type: "heading", content: "白鬚神社", level: 2 }, { type: "text", content: "琵琶湖に浮かぶ鳥居。朝日の時間帯が最も美しい。" }, { type: "heading", content: "マキノのメタセコイア並木", level: 2 }, { type: "text", content: "2.4kmの並木道。秋は紅葉、冬は雪化粧。どの季節でも絵になる。" }], relatedArticleSlugs: ["shiga-omi-hachiman"] },
  { slug: "shiga-omi-hachiman", title: "近江八幡──水郷と八幡堀を歩く", description: "時代劇のロケ地にもなった水郷の街。船に乗って、ゆったりと。", coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80", publishedAt: "2025-06-10", author: "旅のしおり屋さん編集部", category: "model-course", prefectureId: "shiga", tags: ["水郷", "歴史", "散策", "写真映え"], spotIds: [], sections: [{ type: "heading", content: "八幡堀を歩く", level: 2 }, { type: "text", content: "石垣と蔵が並ぶ堀沿いの道。朝靄がかかる時間帯が一番きれい。" }, { type: "heading", content: "水郷めぐりの船に乗る", level: 2 }, { type: "text", content: "手漕ぎ船でよしの中を進む。水の音だけが聞こえる。" }, { type: "heading", content: "クラブハリエでバームクーヘン", level: 2 }, { type: "text", content: "焼きたてバームクーヘンが食べられる。これだけのために来る人もいる。" }], relatedArticleSlugs: ["shiga-biwako-drive"] },
  { slug: "shiga-hieizan", title: "比叡山延暦寺──京都と滋賀の境目に立つ聖地", description: "日本仏教の母山。標高848mの山上に、1200年の歴史が息づく。", coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80", publishedAt: "2025-08-25", author: "旅のしおり屋さん編集部", category: "solo", prefectureId: "shiga", tags: ["寺院", "歴史", "一人旅", "山"], spotIds: [], sections: [{ type: "heading", content: "坂本ケーブルで山上へ", level: 2 }, { type: "text", content: "日本最長のケーブルカー。山を登りながら琵琶湖のパノラマが広がる。" }, { type: "heading", content: "根本中堂", level: 2 }, { type: "text", content: "1200年間消えたことがない「不滅の法灯」がある。暗い堂内に入ると空気が変わる。" }, { type: "heading", content: "横川・元三大師堂", level: 2 }, { type: "text", content: "おみくじ発祥の地。ここで引くおみくじは重みがある。" }], relatedArticleSlugs: ["shiga-biwako-drive"] },

  // ════════════════════════════════════════
  //  三重県（3件）
  // ════════════════════════════════════════
  { slug: "mie-ise-guide", title: "伊勢神宮 完全ガイド──外宮→内宮の正しい参拝順", description: "伊勢神宮は「外宮→内宮」の順で回る。2000年の正しい参拝順序。", coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80", publishedAt: "2025-01-05", author: "旅のしおり屋さん編集部", category: "tips", prefectureId: "mie", tags: ["伊勢神宮", "三重", "神社", "パワースポット"], spotIds: [], sections: [{ type: "heading", content: "まず外宮（豊受大神宮）", level: 2 }, { type: "text", content: "伊勢市駅から徒歩5分。食の神様を祀る。正宮→別宮の順で参拝する。" }, { type: "heading", content: "バスで内宮へ移動", level: 2 }, { type: "text", content: "外宮から内宮まではバスで15分。" }, { type: "heading", content: "内宮（皇大神宮）", level: 2 }, { type: "text", content: "五十鈴川の御手洗場で手を清める。正宮までの参道は玉砂利。空気が変わる瞬間がある。" }, { type: "heading", content: "おかげ横丁で食べ歩き", level: 2 }, { type: "text", content: "赤福餅、伊勢うどん、てこね寿司。赤福の本店は朝5時から営業。" }], relatedArticleSlugs: ["mie-shima-resort"] },
  { slug: "mie-shima-resort", title: "志摩リゾート──英虞湾と海の幸を楽しむ2日間", description: "伊勢志摩の海沿いをドライブして、リゾートホテルで過ごす。", coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80", publishedAt: "2025-09-08", author: "旅のしおり屋さん編集部", category: "luxury", prefectureId: "mie", tags: ["リゾート", "志摩", "三重", "カップル"], spotIds: [], sections: [{ type: "heading", content: "Day 1：パールロードをドライブ", level: 2 }, { type: "text", content: "鳥羽から志摩へ続く海沿いの道。英虞湾のリアス海岸が見える。" }, { type: "heading", content: "Day 1：横山展望台", level: 2 }, { type: "text", content: "英虞湾を一望できる展望台。入り組んだ海岸線が箱庭のように見える。" }, { type: "heading", content: "Day 2：海女小屋体験", level: 2 }, { type: "text", content: "現役の海女さんが目の前で焼いてくれるサザエやアワビ。志摩でしかできない体験。" }], relatedArticleSlugs: ["mie-ise-guide"] },
  { slug: "mie-ise-gourmet", title: "伊勢グルメ──赤福だけじゃない、伊勢の本気の食", description: "伊勢うどん、てこね寿司、伊勢海老。食でも伊勢は裏切らない。", coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80", publishedAt: "2025-02-14", author: "旅のしおり屋さん編集部", category: "gourmet", prefectureId: "mie", tags: ["グルメ", "伊勢", "三重", "食べ歩き"], spotIds: [], sections: [{ type: "heading", content: "伊勢うどん", level: 2 }, { type: "text", content: "コシがない。柔らかい。でもそれが伊勢うどん。たまり醤油の黒いタレをかけて食べる。癖になる。" }, { type: "heading", content: "てこね寿司", level: 2 }, { type: "text", content: "カツオの漬け丼。漁師飯が起源。「すし久」が定番。" }, { type: "heading", content: "赤福餅", level: 2 }, { type: "text", content: "本店で食べる赤福はひと味違う。赤福氷は夏限定。" }], relatedArticleSlugs: ["mie-ise-guide"] },
];
