import { Article } from "@/types/article";

export const allArticles: Article[] = [
  {
    slug: "kyoto-morning-route",
    title: "京都・早朝巡りの黄金ルート",
    description: "人がいない京都は、こんなにも美しい。6時スタートで回る、朝だけの京都。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kyoto",
    tags: ["早朝", "京都", "モデルコース", "写真映え"],
    spotIds: ["fushimi-inari", "kiyomizu", "gion", "arashiyama"],
    sections: [
      { type: "heading", content: "朝6時、伏見稲荷からはじまる", level: 2 },
      { type: "text", content: "観光客が殺到する前の千本鳥居は別世界。朝日が鳥居を照らすと、朱が一層鮮やかに見える。稲荷駅に着いたら、まっすぐ山に向かう。四ツ辻まで登ったら、振り返って京都の街を見下ろす。この時間、ここにいるのは自分だけ。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "7時半、清水寺へ移動", level: 2 },
      { type: "text", content: "清水寺は6時開門。8時前に着けば、舞台をほぼ独占できる。三年坂を降りながら、まだ閉まっている店の格子戸を眺める。観光地が「生活の場」に見える時間帯。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "9時、祇園を歩いて終わり", level: 2 },
      { type: "text", content: "花見小路は午前中なら静か。白川沿いを歩いて、この旅の余韻を味わう。これで京都の朝は完成。午後はゆっくりカフェでもいい。" },
      { type: "spot-card", content: "gion" },
    ],
    relatedArticleSlugs: ["osaka-kuiadaore", "kyoto-autumn-leaves", "kyoto-gion-night"],
  },
  {
    slug: "osaka-kuiadaore",
    title: "大阪食い倒れ1日モデルコース",
    description: "朝から晩まで、胃袋だけで大阪を制覇する。食い倒れの正しい回り方。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["グルメ", "大阪", "食べ歩き", "モデルコース"],
    spotIds: ["dotonbori", "shinsekai"],
    sections: [
      { type: "heading", content: "朝は新世界のモーニング串カツから", level: 2 },
      { type: "text", content: "ジャンジャン横丁の串カツ屋は朝から開いている。ここで軽く5本。ソースは一度漬け。この鉄の掟を守れるかどうかで、大阪との相性がわかる。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "昼は道頓堀でたこ焼きハシゴ", level: 2 },
      { type: "text", content: "道頓堀のたこ焼きは店によって全然違う。外はカリカリ、中はトロトロが好きなら「わなか」。ふわとろ系なら「くくる」。はしごしても胃は意外ともつ。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "夜は法善寺横丁で締める", level: 2 },
      { type: "text", content: "道頓堀のネオンに疲れたら、法善寺横丁に逃げ込む。石畳の路地に小さな割烹が並ぶ。水かけ不動に手を合わせて、今日食べたものへの感謝を伝える。大阪の食い倒れは、こうして締めるのが正解。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "osaka-budget-gourmet", "osaka-shinsekai-deep"],
  },
  {
    slug: "kinosaki-complete",
    title: "城崎温泉 完全ガイド──外湯7湯の正しい回り方",
    description: "城崎温泉を「正解」で回る方法。7つの外湯をハシゴする、温泉街の流儀。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "hyogo",
    tags: ["温泉", "城崎", "カップル", "冬"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "城崎の流儀：宿に着いたら、まず外へ出ろ", level: 2 },
      { type: "text", content: "城崎温泉の楽しみ方は明確。チェックインしたら浴衣に着替えて、ゲタを鳴らして外湯へ向かう。宿の内湯に入るのは最後でいい。それが城崎の流儀。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "外湯7湯、どれから入る？", level: 2 },
      { type: "text", content: "一番人気は「御所の湯」。滝を見ながら入れる露天風呂がある。「一の湯」は洞窟風呂。「地蔵湯」は家族向け。全部入るなら、1日券を買って3〜4湯に絞るのが現実的。欲張ると湯あたりする。" },
      { type: "heading", content: "冬のカニ、これだけは食べろ", level: 2 },
      { type: "text", content: "11月〜3月の松葉ガニシーズンに来るなら、カニ刺し→焼きガニ→カニすき→雑炊のフルコース一択。予算は張るが、この体験は一生モノ。城崎に冬に来る理由の半分はこれ。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "kinosaki-couple", "hyogo-himeji-kinosaki"],
  },
  {
    slug: "nara-deer-guide",
    title: "奈良公園の鹿と正しく付き合う方法",
    description: "鹿せんべいを持った瞬間から始まるサバイバル。正しい鹿との距離感。",
    coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nara",
    tags: ["奈良", "家族", "のんびり", "コツ"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "鹿は野生動物である", level: 2 },
      { type: "text", content: "奈良公園の鹿は国の天然記念物で、れっきとした野生動物。可愛いけど、鹿せんべいを見せた瞬間に囲まれる。子鹿は特に積極的。落ち着いて、せんべいを高く掲げず、一枚ずつ渡すのがコツ。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "東大寺まで歩く", level: 2 },
      { type: "text", content: "奈良公園から東大寺は歩いてすぐ。大仏殿に入ると、想像の3倍デカい大仏が待っている。柱の穴くぐりは子供だけじゃなく、大人もチャレンジする。通れたら厄除けになるらしい。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "nara-family-day", "nara-yoshino-spring"],
  },
  {
    slug: "kumano-kodo-beginner",
    title: "熊野古道、初心者はここだけ歩けばいい",
    description: "全部歩くと3日かかる熊野古道。初めてなら3時間のこのルートで十分。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "wakayama",
    tags: ["トレッキング", "一人旅", "歴史", "和歌山"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "発心門王子からスタート", level: 2 },
      { type: "text", content: "熊野古道を全部歩く必要はない。発心門王子から熊野本宮大社までの約7kmが、初心者にちょうどいい距離。3時間でゴールできる。石畳の道、苔、木漏れ日——熊野古道の「核」はこの区間に凝縮されている。" },
      { type: "spot-card", content: "kumano-kodo" },
      { type: "heading", content: "大斎原で旅を締める", level: 2 },
      { type: "text", content: "熊野本宮大社に着いたら、そのまま大斎原まで歩く。田んぼの中に突然現れる日本一の大鳥居。朱色の門と青空のコントラスト。ここに立った瞬間、歩いてきた意味がわかる。" },
    ],
    relatedArticleSlugs: ["kinosaki-complete", "wakayama-nature-trip", "kumano-kodo-solo-deep"],
  },
  // ── 6. 京都 秋の紅葉 ──
  {
    slug: "kyoto-autumn-leaves",
    title: "京都の紅葉、地元民が絶対に教えないスポット順",
    description: "11月の京都は戦場だ。でも、朝の30分で勝負は決まる。",
    coverImage: "https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kyoto",
    tags: ["紅葉", "秋", "京都", "写真映え"],
    spotIds: ["kiyomizu", "arashiyama", "gion"],
    sections: [
      { type: "heading", content: "清水寺の紅葉は、舞台の下から見ろ", level: 2 },
      { type: "text", content: "舞台の上から見る紅葉は確かに美しい。だが本当の絶景は、舞台を下から見上げた構図にある。紅葉の海の上に浮かぶ本堂。この角度を知っているかどうかで、京都の紅葉の満足度は変わる。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "嵐山の竹林は紅葉と組み合わせてこそ", level: 2 },
      { type: "text", content: "竹の緑と紅葉の赤。この対比を見るなら、天龍寺の庭園が最強。拝観料を払って庭園側から竹林に抜けるルートが正解。逆回りだと混雑に巻き込まれる。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "夜の祇園、紅葉ライトアップ帰りの散歩", level: 2 },
      { type: "text", content: "高台寺のライトアップを見た後、祇園まで歩いて降りる。紅葉の余韻と石畳の夜景。この組み合わせは11月の京都でしか味わえない。" },
      { type: "spot-card", content: "gion" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "nara-yoshino-spring", "kyoto-gion-night"],
  },
  // ── 7. 京都 祇園の夜 ──
  {
    slug: "kyoto-gion-night",
    title: "祇園の夜は、18時からが本番だ",
    description: "観光客が消えた花見小路。格子戸に灯りが入る瞬間を、見逃すな。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kyoto",
    tags: ["祇園", "夜", "カップル", "京都"],
    spotIds: ["gion", "kiyomizu"],
    sections: [
      { type: "heading", content: "17時、まだ早い。18時、ちょうどいい。", level: 2 },
      { type: "text", content: "祇園の花見小路は17時だとまだ観光客が残っている。18時を過ぎると、空気が変わる。格子戸に灯りが入り始め、石畳が濡れたように光る。ここからが祇園の本当の時間。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "白川沿いのバーで一杯", level: 2 },
      { type: "text", content: "花見小路を抜けたら白川沿いへ。柳が風に揺れて、川面に灯りが映る。この景色を見ながら飲む一杯は、京都でしか味わえない贅沢だ。" },
      { type: "heading", content: "帰りに清水寺方面を歩く", level: 2 },
      { type: "text", content: "二年坂・三年坂は夜になると人が消える。ライトに照らされた石段を歩くと、タイムスリップしたような感覚になる。昼とは全く別の場所。" },
      { type: "spot-card", content: "kiyomizu" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "kyoto-autumn-leaves", "kyoto-couple-weekend"],
  },
  // ── 8. 京都カップル週末 ──
  {
    slug: "kyoto-couple-weekend",
    title: "京都、2人で過ごす週末──嵐山から祇園へ",
    description: "デートプランに「京都」と書いた時点で、半分勝っている。",
    coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kyoto",
    tags: ["カップル", "週末", "京都", "デート"],
    spotIds: ["arashiyama", "gion", "kiyomizu"],
    sections: [
      { type: "heading", content: "午前：嵐山の竹林を2人で歩く", level: 2 },
      { type: "text", content: "竹林の小径は早朝が鉄則だが、カップルに早起きを強いるのは酷だ。9時でも十分美しい。渡月橋で写真を撮って、天龍寺の庭を散策する。ここまでで午前が終わる。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "午後：祇園でお茶とスイーツ", level: 2 },
      { type: "text", content: "祇園には抹茶スイーツの名店が集中している。花見小路を歩いて、白川沿いのカフェに入る。ここで急ぐ必要はない。京都の午後は、のんびり過ごすためにある。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "夕方：清水寺の夕景", level: 2 },
      { type: "text", content: "清水寺は夕方の光が一番美しい。西日が舞台を照らす時間帯。三年坂を下りながら、二人で今日の振り返りをする。それが京都デートの正しい締め方。" },
      { type: "spot-card", content: "kiyomizu" },
    ],
    relatedArticleSlugs: ["kyoto-gion-night", "kyoto-morning-route", "kinosaki-couple"],
  },
  // ── 9. 大阪 新世界ディープ ──
  {
    slug: "osaka-shinsekai-deep",
    title: "新世界の歩き方──通天閣は登らなくていい",
    description: "通天閣の足元にある、本物の大阪。観光ガイドが書かない新世界。",
    coverImage: "https://images.unsplash.com/photo-1589452271712-64b8a66c3929?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "osaka",
    tags: ["一人旅", "ディープ", "大阪", "新世界"],
    spotIds: ["shinsekai", "dotonbori"],
    sections: [
      { type: "heading", content: "ジャンジャン横丁、朝10時の空気", level: 2 },
      { type: "text", content: "新世界は朝が面白い。ジャンジャン横丁の串カツ屋が暖簾を出す頃、地元の常連がカウンターに座り始める。この空気は夜には味わえない。観光客がいない新世界が、一番新世界らしい。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "昼過ぎ、道頓堀まで歩いてみる", level: 2 },
      { type: "text", content: "新世界から道頓堀まで歩くと約30分。地下鉄に乗るのが普通だが、歩くと大阪の街の変化がわかる。ディープな下町から、ネオンの観光地へ。この対比が大阪の面白さ。" },
      { type: "spot-card", content: "dotonbori" },
    ],
    relatedArticleSlugs: ["osaka-kuiadaore", "osaka-budget-gourmet", "osaka-family-fun"],
  },
  // ── 10. 大阪 予算グルメ ──
  {
    slug: "osaka-budget-gourmet",
    title: "大阪、1,000円以下で満腹になる店だけ集めた",
    description: "大阪のグルメは高い店より安い店が旨い。財布に優しい、胃袋の味方。",
    coverImage: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "osaka",
    tags: ["節約", "グルメ", "大阪", "学生旅行"],
    spotIds: ["dotonbori", "shinsekai"],
    sections: [
      { type: "heading", content: "道頓堀のたこ焼きは500円で幸せになれる", level: 2 },
      { type: "text", content: "道頓堀のたこ焼き屋台で8個入り500円。これだけで満足度は高い。立ち食いで、川沿いのベンチで食べる。これが大阪スタイル。レストランに座る必要はない。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "新世界の串カツ、5本で500円の店がある", level: 2 },
      { type: "text", content: "ジャンジャン横丁には串カツ5本セットが500円の店がまだある。ビール1杯つけても1,000円。この価格で腹いっぱいになれる場所は、日本中探しても大阪くらいだ。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "粉モンのハシゴが最強コスパ", level: 2 },
      { type: "text", content: "たこ焼き→お好み焼き→串カツ。この3つをハシゴしても2,000円以下。大阪の粉モン文化は、学生旅行の最強の味方。" },
    ],
    relatedArticleSlugs: ["osaka-kuiadaore", "osaka-shinsekai-deep", "kinki-budget-tips"],
  },
  // ── 11. 大阪 ファミリー ──
  {
    slug: "osaka-family-fun",
    title: "子連れ大阪、退屈させない1日プラン",
    description: "子供は串カツよりたこ焼き派。大阪の家族旅は、食べて遊んで食べるだけ。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "osaka",
    tags: ["家族", "子連れ", "大阪", "体験"],
    spotIds: ["dotonbori", "shinsekai"],
    sections: [
      { type: "heading", content: "午前：道頓堀でたこ焼き作り体験", level: 2 },
      { type: "text", content: "道頓堀周辺にはたこ焼き体験ができる店がある。子供に竹串を持たせて、くるくる回す。焦げても、形が崩れても、自分で作ったたこ焼きは世界一うまい。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "午後：新世界で通天閣と串カツ", level: 2 },
      { type: "text", content: "通天閣の展望台は子供のテンションが上がる。展望台の後はジャンジャン横丁で串カツ。子供はソースの二度漬け禁止ルールを面白がる。大人は生ビール。全員が幸せになれる場所。" },
      { type: "spot-card", content: "shinsekai" },
    ],
    relatedArticleSlugs: ["osaka-kuiadaore", "nara-family-day", "kinki-family-guide"],
  },
  // ── 12. 奈良 ファミリー ──
  {
    slug: "nara-family-day",
    title: "奈良公園、子連れで行くなら知っておく5つのこと",
    description: "鹿は可愛い。でも子供のせんべいを狙ってくる。親の覚悟が試される場所。",
    coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "nara",
    tags: ["家族", "子連れ", "奈良", "鹿"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "鹿せんべいは親が持て", level: 2 },
      { type: "text", content: "子供にせんべいを持たせると、鹿が一斉に寄ってくる。囲まれた子供は泣く。これは奈良公園あるある。親がせんべいを持って、一枚ずつ子供に渡す。これが正解。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "東大寺の柱くぐりは午前中に", level: 2 },
      { type: "text", content: "東大寺大仏殿の柱の穴くぐりは子供に大人気。午後は行列ができる。午前中に行けば待ち時間ほぼゼロ。大仏の大きさに子供は黙る。その沈黙が、いい思い出になる。" },
      { type: "heading", content: "若草山は子供の遊び場になる", level: 2 },
      { type: "text", content: "若草山は芝生の斜面。子供は勝手に走り回る。鹿もいる。お弁当を広げるなら、ここが奈良のベストスポット。入山料は大人150円。安い。" },
    ],
    relatedArticleSlugs: ["nara-deer-guide", "osaka-family-fun", "kinki-family-guide"],
  },
  // ── 13. 奈良+吉野 春 ──
  {
    slug: "nara-yoshino-spring",
    title: "奈良の春、鹿と桜を1日で── 吉野山3万本の桜",
    description: "奈良公園の鹿は桜の下で昼寝する。その光景を見るだけで、春の奈良に来た価値がある。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-03-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nara",
    tags: ["春", "桜", "奈良", "吉野"],
    spotIds: ["nara-park", "yoshino"],
    sections: [
      { type: "heading", content: "午前：奈良公園で桜と鹿", level: 2 },
      { type: "text", content: "4月上旬、奈良公園の桜が満開になると、鹿がその下で昼寝を始める。桜の花びらが鹿の背中に落ちる。この光景は奈良でしか見られない。写真を撮るなら午前中の光がベスト。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "午後：吉野山の一目千本", level: 2 },
      { type: "text", content: "奈良公園から吉野まで近鉄で約1時間。吉野の桜は山を下から上へ染めていく。中千本エリアから見下ろす「一目千本」は、人生で一度は見るべき景色。金峯山寺の蔵王堂は桜の時期だけ秘仏が公開される。" },
      { type: "spot-card", content: "yoshino" },
    ],
    relatedArticleSlugs: ["nara-deer-guide", "kyoto-autumn-leaves", "nara-family-day"],
  },
  // ── 14. 兵庫 姫路城+城崎 ──
  {
    slug: "hyogo-himeji-kinosaki",
    title: "兵庫を1泊2日で──姫路城の白と城崎の湯気",
    description: "午前は白鷺城、夜は温泉街。兵庫の「正解ルート」はこれ一択。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-02-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "hyogo",
    tags: ["モデルコース", "兵庫", "城", "温泉"],
    spotIds: ["himeji", "kinosaki"],
    sections: [
      { type: "heading", content: "1日目午前：姫路城は午前の光で見ろ", level: 2 },
      { type: "text", content: "姫路城は白い。午前中の光だと白さが際立つ。西の丸から天守閣を見上げる構図が最も美しい。所要時間は約2時間。隣の好古園で庭を眺めて、昼飯を食べる。" },
      { type: "spot-card", content: "himeji" },
      { type: "heading", content: "1日目夕方〜2日目：城崎で外湯三昧", level: 2 },
      { type: "text", content: "姫路から城崎まで特急で約2時間。チェックインしたら浴衣に着替えて外湯へ。御所の湯、一の湯、地蔵湯。3つ回れば十分満足。翌朝、もう一湯入ってから帰る。" },
      { type: "spot-card", content: "kinosaki" },
    ],
    relatedArticleSlugs: ["kinosaki-complete", "kinosaki-couple", "himeji-solo-trip"],
  },
  // ── 15. 姫路城 一人旅 ──
  {
    slug: "himeji-solo-trip",
    title: "姫路城、一人で行くから見えるもの",
    description: "誰かと一緒だと見逃す。一人で行くと、城が語りかけてくる。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "hyogo",
    tags: ["一人旅", "姫路", "城", "歴史"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "天守閣まで、ゆっくり1時間かける", level: 2 },
      { type: "text", content: "グループだと足が速くなる。一人なら、各階で立ち止まれる。武者隠し、石落とし、狭間。城は戦の建築物だ。一人で黙って見ると、設計者の意図が見えてくる。" },
      { type: "spot-card", content: "himeji" },
      { type: "heading", content: "西の丸の百間廊下を歩く", level: 2 },
      { type: "text", content: "西の丸から天守閣を見る構図が一番美しい。百間廊下は千姫が暮らした場所。一人で歩くと、歴史の静けさが身にしみる。城には、一人が似合う。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-kinosaki", "kumano-kodo-beginner", "kinki-solo-guide"],
  },
  // ── 16. 城崎 カップル ──
  {
    slug: "kinosaki-couple",
    title: "城崎温泉、2人で浴衣で歩く夜",
    description: "浴衣とゲタで外湯をハシゴする。それだけで、特別な夜になる。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "hyogo",
    tags: ["カップル", "温泉", "城崎", "冬"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "チェックインしたら、浴衣で外へ", level: 2 },
      { type: "text", content: "城崎温泉はカップルのために存在するような街だ。浴衣に着替えて、ゲタを鳴らして柳並木を歩く。それだけで非日常。まず御所の湯で温まってから、街をぶらつく。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "夜の柳並木は城崎のハイライト", level: 2 },
      { type: "text", content: "大谿川沿いの柳がライトアップされる夜。川面に灯りが映る。射的やスマートボールの店に寄り道しながら、次の外湯を目指す。急がない。城崎の夜は、ゆっくりでいい。" },
      { type: "heading", content: "冬ならカニを2人でシェア", level: 2 },
      { type: "text", content: "松葉ガニのフルコースは一人前でも量が多い。2人なら、余裕でシェアできる。カニ刺しの透明な身、焼きガニの香ばしさ。これを一緒に食べる相手がいることの贅沢。" },
    ],
    relatedArticleSlugs: ["kinosaki-complete", "kyoto-couple-weekend", "hyogo-himeji-kinosaki"],
  },
  // ── 17. 和歌山 自然旅 ──
  {
    slug: "wakayama-nature-trip",
    title: "和歌山の自然は「手つかず」だ──海と山と古道",
    description: "関西で最も自然が濃い県。白浜の海と熊野の山、どちらから攻める？",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "wakayama",
    tags: ["自然", "和歌山", "海", "山"],
    spotIds: ["nanki-shirahama", "kumano-kodo"],
    sections: [
      { type: "heading", content: "1日目：白浜の海と温泉", level: 2 },
      { type: "text", content: "白良浜の白い砂とエメラルドグリーンの海。関西にこんな場所があることを知らない人が多い。崎の湯で太平洋を見ながら温泉に入る。波しぶきが飛んでくるほど海に近い露天風呂。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "2日目：熊野古道を歩く", level: 2 },
      { type: "text", content: "白浜から熊野エリアへ移動。発心門王子から本宮大社までの約3時間コース。石畳の道を歩くと、1000年前の巡礼者と同じ景色を見ていることに気づく。" },
      { type: "spot-card", content: "kumano-kodo" },
    ],
    relatedArticleSlugs: ["kumano-kodo-beginner", "nanki-shirahama-summer", "wakayama-couple-resort"],
  },
  // ── 18. 南紀白浜 夏 ──
  {
    slug: "nanki-shirahama-summer",
    title: "南紀白浜、夏の正しい過ごし方",
    description: "関西から最も近い南国。白い砂浜に寝転がる以外のことは、何もするな。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "wakayama",
    tags: ["夏", "ビーチ", "白浜", "和歌山"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "白良浜は7月がベスト", level: 2 },
      { type: "text", content: "8月は混む。7月上旬の平日が最高。白い砂浜を裸足で歩いて、エメラルドグリーンの海に飛び込む。沖縄に行かなくても、この海がある。関西人の特権。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "円月島の夕日は夏至前後が狙い目", level: 2 },
      { type: "text", content: "円月島の穴を夕日が通り抜ける瞬間。春分・秋分の頃が有名だが、夏の夕日も十分美しい。岩と海と空だけの景色。三段壁は波が荒い日に行くと迫力がある。" },
      { type: "heading", content: "崎の湯で1日を締める", level: 2 },
      { type: "text", content: "白浜で一番の贅沢は、崎の湯。太平洋に面した露天風呂で、波の音を聞きながら入浴する。日焼けした肌に温泉がしみる。これ以上の夏の締め方はない。" },
    ],
    relatedArticleSlugs: ["wakayama-nature-trip", "nanki-shirahama-family", "wakayama-couple-resort"],
  },
  // ── 19. 南紀白浜 家族 ──
  {
    slug: "nanki-shirahama-family",
    title: "白浜、子連れで行くなら海だけじゃない",
    description: "アドベンチャーワールドだけで1日潰れる。でも海も温泉も欲張れ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "wakayama",
    tags: ["家族", "白浜", "子連れ", "夏"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "白良浜は子供の天国", level: 2 },
      { type: "text", content: "白良浜は遠浅で波が穏やか。小さい子供でも安心して遊べる。砂が白くてサラサラだから、砂遊びにも最適。浮き輪を持って、1日中いられる。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "とれとれ市場で海鮮丼", level: 2 },
      { type: "text", content: "子供が海に飽きたら、とれとれ市場へ。新鮮な海鮮丼が食べられる。子供向けのメニューもある。ここの海鮮は回転寿司とは全く別物。" },
      { type: "heading", content: "夜は温泉で砂を流す", level: 2 },
      { type: "text", content: "海で遊んだ後の温泉は格別。白浜には日帰り温泉がたくさんある。子供は温泉よりプールが好きかもしれないが、崎の湯の絶景は見せておきたい。" },
    ],
    relatedArticleSlugs: ["nanki-shirahama-summer", "osaka-family-fun", "kinki-family-guide"],
  },
  // ── 20. 和歌山 カップルリゾート ──
  {
    slug: "wakayama-couple-resort",
    title: "和歌山で過ごす大人の週末──温泉リゾートと熊野の森",
    description: "日常から一番遠い場所が、実は関西にある。和歌山の奥へ。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "wakayama",
    tags: ["カップル", "リゾート", "温泉", "贅沢"],
    spotIds: ["nanki-shirahama", "kumano-kodo"],
    sections: [
      { type: "heading", content: "白浜の高級旅館で始まる週末", level: 2 },
      { type: "text", content: "白浜にはオーシャンビューの高級旅館がある。部屋から太平洋が一望できる。チェックインしたら、何もしない。ただ海を見る。それが贅沢の正解。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "翌日、熊野古道をゆっくり歩く", level: 2 },
      { type: "text", content: "贅沢な朝食の後、熊野古道へ。発心門王子から本宮まで、2人でゆっくり3時間。石畳を踏む音と、鳥のさえずりだけ。この静寂が、最高の贅沢。" },
      { type: "spot-card", content: "kumano-kodo" },
    ],
    relatedArticleSlugs: ["wakayama-nature-trip", "kinosaki-couple", "kyoto-couple-weekend"],
  },
  // ── 21. 熊野古道 一人旅ディープ ──
  {
    slug: "kumano-kodo-solo-deep",
    title: "熊野古道、1人で歩く2日間──中辺路を黙って歩け",
    description: "スマホを機内モードにして、石畳を踏む足音だけを聞く2日間。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "wakayama",
    tags: ["一人旅", "トレッキング", "熊野古道", "スピリチュアル"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "1日目：滝尻王子から近露まで", level: 2 },
      { type: "text", content: "中辺路の本気コース。滝尻王子から近露王子まで約15km。途中、誰にも会わない時間がある。杉の巨木と苔むした石段。1000年前の巡礼者と同じ道を歩いている実感が湧く。" },
      { type: "spot-card", content: "kumano-kodo" },
      { type: "heading", content: "近露の民宿で1泊", level: 2 },
      { type: "text", content: "近露には巡礼者向けの民宿がある。温泉で汗を流して、地元の食材で作られた夕食を食べる。同じ日に歩いた他のハイカーと言葉を交わす。一人旅だけど、一人じゃない。" },
      { type: "heading", content: "2日目：本宮大社へ", level: 2 },
      { type: "text", content: "2日目は本宮大社を目指す。大斎原の大鳥居が見えた瞬間、2日間歩いた疲れが一気に吹き飛ぶ。この達成感は、歩いた人にしかわからない。" },
    ],
    relatedArticleSlugs: ["kumano-kodo-beginner", "wakayama-nature-trip", "kinki-solo-guide"],
  },
  // ── 22. 京都+大阪 2日間 ──
  {
    slug: "kyoto-osaka-2days",
    title: "京都と大阪、2日で制覇する欲張りルート",
    description: "1日目は寺と竹林。2日目は串カツとたこ焼き。関西の二大巨頭を一気に。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kyoto",
    tags: ["モデルコース", "京都", "大阪", "2日間"],
    spotIds: ["fushimi-inari", "arashiyama", "gion", "dotonbori", "shinsekai"],
    sections: [
      { type: "heading", content: "1日目：京都の王道を朝から", level: 2 },
      { type: "text", content: "伏見稲荷を朝6時に出発。千本鳥居を独占してから、嵐山へ移動。竹林の小径と渡月橋を回ったら、夕方に祇園へ。花見小路で京都の1日を締める。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "spot-card", content: "arashiyama" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "2日目：大阪で食い倒れ", level: 2 },
      { type: "text", content: "京都から大阪まで電車で30分。午前中は新世界で串カツ、午後は道頓堀でたこ焼きハシゴ。胃袋の限界に挑戦する日。2日目は食べることだけに集中する。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "spot-card", content: "dotonbori" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "osaka-kuiadaore", "kinki-budget-tips"],
  },
  // ── 23. 奈良+和歌山 自然コース ──
  {
    slug: "nara-wakayama-nature",
    title: "奈良と和歌山、自然だけを追う2日間",
    description: "鹿の森から熊野の山へ。関西の自然の深さを、2日間で思い知る。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nara",
    tags: ["自然", "奈良", "和歌山", "トレッキング"],
    spotIds: ["nara-park", "yoshino", "kumano-kodo"],
    sections: [
      { type: "heading", content: "1日目：奈良公園と吉野山", level: 2 },
      { type: "text", content: "午前中は奈良公園で鹿と散歩。若草山に登って、奈良盆地を見下ろす。午後は吉野山へ移動。桜の時期なら一目千本、新緑の時期なら静かな山寺が待っている。" },
      { type: "spot-card", content: "nara-park" },
      { type: "spot-card", content: "yoshino" },
      { type: "heading", content: "2日目：熊野古道を歩く", level: 2 },
      { type: "text", content: "吉野から熊野エリアへ。発心門王子から本宮大社までの3時間コース。奈良の「穏やかな自然」と、和歌山の「深い自然」の対比が、この旅の核心。" },
      { type: "spot-card", content: "kumano-kodo" },
    ],
    relatedArticleSlugs: ["kumano-kodo-beginner", "nara-yoshino-spring", "wakayama-nature-trip"],
  },
  // ── 24. 近畿 節約旅コツ ──
  {
    slug: "kinki-budget-tips",
    title: "近畿旅行、交通費を半額にする7つの裏技",
    description: "関西の交通パスを使いこなせば、移動費は半分以下になる。知らないと損。",
    coverImage: "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=1200&q=80",
    publishedAt: "2025-01-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "osaka",
    tags: ["節約", "交通", "コツ", "初心者"],
    spotIds: ["dotonbori", "fushimi-inari", "nara-park"],
    sections: [
      { type: "heading", content: "関西周遊パスが最強", level: 2 },
      { type: "text", content: "関西周遊パスは私鉄・地下鉄が乗り放題。京都、大阪、奈良を回るならこれ一択。JR以外はほぼカバーできる。2日券で約4,400円。普通に回ると1万円超えるルートが半額以下。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "京都は市バス1日券を活用", level: 2 },
      { type: "text", content: "京都市内の移動はバスが便利。1日券700円で乗り放題。伏見稲荷→清水寺→祇園→嵐山のルートを全部バスで回ると、普通に払うより1,000円以上得する。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "奈良は近鉄がお得", level: 2 },
      { type: "text", content: "大阪から奈良は近鉄で約30分、片道570円。JRより安くて速い。奈良公園は入園無料。東大寺と春日大社の拝観料だけで1日楽しめる。コスパ最強の観光地。" },
      { type: "spot-card", content: "nara-park" },
    ],
    relatedArticleSlugs: ["osaka-budget-gourmet", "kyoto-osaka-2days", "kinki-first-timer"],
  },
  // ── 25. 近畿 初心者 ──
  {
    slug: "kinki-first-timer",
    title: "初めての関西旅行、これだけ読めば大丈夫",
    description: "京都・大阪・奈良の3都市を効率よく回る。初心者のための完全マニュアル。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-01-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "osaka",
    tags: ["初心者", "関西", "コツ", "モデルコース"],
    spotIds: ["fushimi-inari", "dotonbori", "nara-park"],
    sections: [
      { type: "heading", content: "拠点は大阪に置け", level: 2 },
      { type: "text", content: "初めての関西旅行なら、宿は大阪がベスト。京都にも奈良にも電車で30分〜1時間。大阪のホテルは京都より安い。夜は道頓堀で食い倒れて、翌朝京都へ出発する。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "京都は「朝から」が鉄則", level: 2 },
      { type: "text", content: "京都の人気スポットは午前10時を過ぎると人で溢れる。伏見稲荷は6時、清水寺も6時開門。早起きした者だけが、静かな京都を手に入れる。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "奈良は半日で十分", level: 2 },
      { type: "text", content: "奈良公園、東大寺、春日大社。この3つを回るのに半日あれば足りる。午前中に奈良を回って、午後は京都か大阪に移動。奈良を舐めてはいけないが、1日は長すぎる。" },
      { type: "spot-card", content: "nara-park" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "osaka-kuiadaore", "kinki-budget-tips"],
  },
  // ── 26. 近畿 一人旅ガイド ──
  {
    slug: "kinki-solo-guide",
    title: "関西ひとり旅──誰にも邪魔されない5つのルート",
    description: "一人だから行ける場所がある。関西の一人旅は、自由の塊だ。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-08-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kyoto",
    tags: ["一人旅", "関西", "自由", "モデルコース"],
    spotIds: ["fushimi-inari", "himeji", "kumano-kodo"],
    sections: [
      { type: "heading", content: "朝の伏見稲荷、一人で登れ", level: 2 },
      { type: "text", content: "伏見稲荷の千本鳥居は、グループで行くと写真の撮り合いになる。一人なら、黙って登るだけ。四ツ辻まで登って、京都の朝を独り占めする。この贅沢は一人旅の特権。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "姫路城を黙って歩く", level: 2 },
      { type: "text", content: "姫路城は一人で行くと、城の「戦の建築」としての本質が見えてくる。石落とし、狭間、武者隠し。ガイドブックには載っていない、城の怖さ。" },
      { type: "spot-card", content: "himeji" },
      { type: "heading", content: "熊野古道は究極の一人旅", level: 2 },
      { type: "text", content: "石畳を踏む自分の足音だけが聞こえる。スマホの電波も入らない場所がある。1000年前の巡礼者と同じ道を、同じ速度で歩く。一人旅の最高到達点。" },
      { type: "spot-card", content: "kumano-kodo" },
    ],
    relatedArticleSlugs: ["kumano-kodo-solo-deep", "himeji-solo-trip", "kumano-kodo-beginner"],
  },
  // ── 27. 近畿 家族ガイド ──
  {
    slug: "kinki-family-guide",
    title: "関西で子供が飽きない旅──年齢別おすすめプラン",
    description: "3歳は鹿、7歳は城、10歳は食い倒れ。子供の年齢で行き先が変わる。",
    coverImage: "https://images.unsplash.com/photo-1624601573012-efb68f3f150a?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "osaka",
    tags: ["家族", "子連れ", "関西", "年齢別"],
    spotIds: ["nara-park", "himeji", "dotonbori"],
    sections: [
      { type: "heading", content: "未就学児：奈良公園一択", level: 2 },
      { type: "text", content: "小さい子供には奈良公園が最強。鹿と触れ合って、芝生で走り回って、東大寺で大仏に驚く。ベビーカーでも回れる平坦な地形。疲れたら芝生で昼寝。完璧なプラン。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "小学生：姫路城で冒険", level: 2 },
      { type: "text", content: "小学生は「探検」が好き。姫路城の天守閣は、急な階段と隠し部屋の連続。石落とし、狭間、武者隠し。城攻めゲームのリアル版。子供のテンションが上がる。" },
      { type: "spot-card", content: "himeji" },
      { type: "heading", content: "小学校高学年〜：大阪で食い倒れ", level: 2 },
      { type: "text", content: "食べ盛りの子供は大阪が最適。たこ焼きを自分で焼いて、串カツの二度漬け禁止ルールを覚える。食を通じて文化を学ぶ。大阪はその教材の宝庫。" },
      { type: "spot-card", content: "dotonbori" },
    ],
    relatedArticleSlugs: ["nara-family-day", "osaka-family-fun", "nanki-shirahama-family"],
  },
  // ── 28. 嵐山 完全ガイド ──
  {
    slug: "arashiyama-complete",
    title: "嵐山、朝7時から昼まで──半日で回る完全ルート",
    description: "竹林は朝、渡月橋は昼。嵐山は時間帯で全く別の場所になる。",
    coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kyoto",
    tags: ["嵐山", "竹林", "京都", "半日"],
    spotIds: ["arashiyama"],
    sections: [
      { type: "heading", content: "7時：竹林は貸切状態", level: 2 },
      { type: "text", content: "嵐山の竹林の小径は、朝7時なら人がほぼいない。竹が風に揺れる音だけが聞こえる。この静寂を味わうために早起きする価値がある。天龍寺の裏手から入るルートが空いている。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "9時：天龍寺の庭園", level: 2 },
      { type: "text", content: "天龍寺は8時半開門。庭園の借景が見事。嵐山の山を背景にした池泉回遊式庭園。紅葉の時期は言うまでもなく美しいが、新緑の時期も負けていない。" },
      { type: "heading", content: "11時：渡月橋と嵐山グルメ", level: 2 },
      { type: "text", content: "渡月橋は昼前の光が一番きれい。橋の上から嵐山を眺めたら、周辺のカフェで抹茶パフェ。嵐山は半日あれば十分。午後は京都市内に戻って別のエリアへ。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "kyoto-couple-weekend", "kyoto-autumn-leaves"],
  },
  // ── 29. 冬の近畿 カニ+温泉 ──
  {
    slug: "kinki-winter-crab-onsen",
    title: "冬の関西、カニと温泉だけの旅",
    description: "城崎のカニを食べて、温泉に入る。冬の関西に、これ以上は要らない。",
    coverImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hyogo",
    tags: ["冬", "カニ", "温泉", "城崎"],
    spotIds: ["kinosaki"],
    sections: [
      { type: "heading", content: "11月解禁、松葉ガニのフルコース", level: 2 },
      { type: "text", content: "11月6日、松葉ガニ漁が解禁する。城崎温泉の旅館はこの日を境に「カニプラン」一色になる。カニ刺し、焼きガニ、カニすき、カニ雑炊。この4品を食べるためだけに、城崎に行く価値がある。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "食後は外湯で温まる", level: 2 },
      { type: "text", content: "カニを食べた後、浴衣で外湯へ向かう。冬の城崎は寒い。だからこそ、湯に浸かった瞬間の幸福感が倍増する。御所の湯の露天風呂で雪を見ながら入浴する。これが冬の関西の最高到達点。" },
      { type: "heading", content: "翌朝も温泉、そして帰路", level: 2 },
      { type: "text", content: "チェックアウト前にもう一湯。朝の外湯は空いている。柳並木に雪が積もっていたら、最高のフォトチャンスだ。帰りの電車で余韻に浸る。冬の城崎は、これだけで十分。" },
    ],
    relatedArticleSlugs: ["kinosaki-complete", "kinosaki-couple", "hyogo-himeji-kinosaki"],
  },
  // ── 30. 京都 贅沢旅 ──
  {
    slug: "kyoto-luxury-stay",
    title: "京都の贅沢は「何もしない」こと──高級旅館と庭の時間",
    description: "予約が取れたら行く。京都の一流旅館は、それだけの場所。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kyoto",
    tags: ["贅沢", "旅館", "京都", "大人旅"],
    spotIds: ["gion", "arashiyama"],
    sections: [
      { type: "heading", content: "祇園の料亭で始まる夜", level: 2 },
      { type: "text", content: "祇園の料亭は予約必須。カウンター8席だけの店で、板前が目の前で料理を仕上げる。京野菜、鮮魚、そして器。料理だけでなく、空間そのものが芸術。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "翌朝、嵐山の旅館で庭を眺める", level: 2 },
      { type: "text", content: "嵐山の高級旅館は、部屋から見える庭が主役。朝食後、縁側に座って庭を眺める。何もしない時間。これが京都の贅沢の本質。観光スポットを回ることだけが旅じゃない。" },
      { type: "spot-card", content: "arashiyama" },
    ],
    relatedArticleSlugs: ["kyoto-gion-night", "kyoto-couple-weekend", "wakayama-couple-resort"],
  },
  // ── 31. 吉野 一人旅 ──
  {
    slug: "yoshino-solo-spring",
    title: "吉野山、一人で登る春の朝",
    description: "3万本の桜を独り占めする方法がある。始発電車に乗れ。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nara",
    tags: ["一人旅", "桜", "吉野", "春"],
    spotIds: ["yoshino"],
    sections: [
      { type: "heading", content: "始発で吉野に着くと、桜は自分だけのもの", level: 2 },
      { type: "text", content: "吉野の桜シーズンは混む。だが始発電車で行けば、ロープウェイが動く前に歩いて登れる。朝の光に照らされた桜は、観光客が来る前の静寂の中で最も美しい。" },
      { type: "spot-card", content: "yoshino" },
      { type: "heading", content: "金峯山寺で秘仏と対峙する", level: 2 },
      { type: "text", content: "桜の時期だけ公開される蔵王権現。青い肌の巨大な仏像は、想像と全く違う。一人で向き合うと、この場所の持つ力を肌で感じる。" },
      { type: "heading", content: "奥千本まで歩く覚悟があるなら", level: 2 },
      { type: "text", content: "奥千本は吉野山の最奥部。ここまで来る人は少ない。だからこそ、一人旅にふさわしい。西行庵の前に座って、桜吹雪を浴びる。この体験は、一人だからこそ深い。" },
    ],
    relatedArticleSlugs: ["nara-yoshino-spring", "kinki-solo-guide", "kumano-kodo-solo-deep"],
  },
  // ── 32. 道頓堀 夜の歩き方 ──
  {
    slug: "dotonbori-night-guide",
    title: "道頓堀、20時からの正解──ネオンの下で食べ歩く夜",
    description: "昼の道頓堀は観光地。夜の道頓堀は、大阪そのもの。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["夜", "グルメ", "大阪", "道頓堀"],
    spotIds: ["dotonbori"],
    sections: [
      { type: "heading", content: "グリコの看板は夜が映える", level: 2 },
      { type: "text", content: "道頓堀のネオンは暗くなってからが本領発揮。グリコの看板は20時以降が一番明るく見える。橋の上から撮ると、水面にネオンが反射して二重に見える。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "食べ歩きの黄金ルート", level: 2 },
      { type: "text", content: "まずたこ焼き、次に串カツ、最後にお好み焼き。この順番を守れば、胃袋に余裕を持ちながら3つ制覇できる。逆順だと、お好み焼きで満腹になって串カツが入らない。" },
      { type: "heading", content: "法善寺横丁で夜を締める", level: 2 },
      { type: "text", content: "道頓堀のネオンに疲れたら、法善寺横丁の石畳の路地に逃げ込む。水かけ不動に手を合わせて、小さな割烹で日本酒を一杯。大阪の夜は、こうして静かに終わるのが正解。" },
    ],
    relatedArticleSlugs: ["osaka-kuiadaore", "osaka-budget-gourmet", "osaka-shinsekai-deep"],
  },
  // ── 33. 伏見稲荷 完全攻略 ──
  {
    slug: "fushimi-inari-complete",
    title: "伏見稲荷大社、頂上まで行く必要はない──正しい回り方",
    description: "千本鳥居の先に、観光客が知らない稲荷山がある。どこで引き返すかが勝負。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kyoto",
    tags: ["伏見稲荷", "攻略", "京都", "コツ"],
    spotIds: ["fushimi-inari"],
    sections: [
      { type: "heading", content: "千本鳥居は「奥社」まででいい", level: 2 },
      { type: "text", content: "千本鳥居の写真を撮るなら、本殿から奥社奉拝所までの区間。ここまでなら片道15分。鳥居が密に並んでいて、フォトジェニック。奥社で引き返す人が多いが、実はここからが面白い。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "四ツ辻が「正解」の折り返し地点", level: 2 },
      { type: "text", content: "奥社から四ツ辻まで約30分。ここに来ると京都の街が一望できる。茶屋でいなり寿司を食べて、ここで折り返すのがベスト。頂上まで行っても景色は四ツ辻と大差ない。" },
      { type: "heading", content: "朝6時に来る理由", level: 2 },
      { type: "text", content: "伏見稲荷は24時間参拝可能。朝6時に来れば、千本鳥居を独占できる。朝日が鳥居を照らす瞬間は、昼間の何倍も美しい。この30分のために早起きする価値がある。" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "kinki-first-timer", "kyoto-autumn-leaves"],
  },
  // ── 34. 近畿 持ち物リスト ──
  {
    slug: "kinki-packing-list",
    title: "関西旅行の持ち物、これだけでいい──季節別パッキング術",
    description: "荷物は少ないほど旅は自由になる。関西旅行に必要なものだけを詰めろ。",
    coverImage: "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=1200&q=80",
    publishedAt: "2025-01-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "osaka",
    tags: ["持ち物", "コツ", "初心者", "パッキング"],
    spotIds: ["fushimi-inari", "kinosaki"],
    sections: [
      { type: "heading", content: "歩きやすい靴、これが最優先", level: 2 },
      { type: "text", content: "関西旅行の最重要アイテムは靴。京都の寺巡り、奈良公園の散策、伏見稲荷の山道。全部歩く。ヒールやサンダルは論外。スニーカーか、歩きやすいブーツ。これだけで旅の快適度が3倍変わる。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "冬の城崎は防寒必須", level: 2 },
      { type: "text", content: "城崎温泉は外湯巡りが本体。浴衣で外を歩く。つまり冬は寒い。インナーダウンとカイロは必須。ただし、温泉に入った後の冷たい空気は気持ちいい。そのギャップを楽しむのが城崎。" },
      { type: "spot-card", content: "kinosaki" },
      { type: "heading", content: "ICカードは関西でも使える", level: 2 },
      { type: "text", content: "SuicaもPASMOもICOCAエリアで使える。切符を買う手間が省ける。チャージは駅の券売機で。関西周遊パスとの併用で、移動のストレスがゼロになる。" },
    ],
    relatedArticleSlugs: ["kinki-budget-tips", "kinki-first-timer", "kinki-best-season"],
  },
  // ── 35. 近畿 ベストシーズン ──
  {
    slug: "kinki-best-season",
    title: "関西旅行、いつ行くのが正解？──月別ベストガイド",
    description: "春は京都の桜、夏は白浜の海、秋は紅葉、冬はカニ。関西に「オフシーズン」はない。",
    coverImage: "https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=1200&q=80",
    publishedAt: "2025-01-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kyoto",
    tags: ["季節", "ベストシーズン", "関西", "計画"],
    spotIds: ["yoshino", "nanki-shirahama", "arashiyama", "kinosaki"],
    sections: [
      { type: "heading", content: "春（3〜5月）：桜一択", level: 2 },
      { type: "text", content: "3月末〜4月中旬は桜のシーズン。京都、奈良、吉野。どこへ行っても桜が待っている。吉野山の一目千本は4月上旬がピーク。この時期の関西は、世界中から人が集まる。" },
      { type: "spot-card", content: "yoshino" },
      { type: "heading", content: "夏（6〜8月）：海と避暑", level: 2 },
      { type: "text", content: "夏は南紀白浜のビーチが最高。白い砂浜とエメラルドグリーンの海。京都の夏は暑すぎるが、嵐山の竹林は涼しい。避暑地としての嵐山を覚えておくといい。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "秋（9〜11月）：紅葉の京都", level: 2 },
      { type: "text", content: "11月中旬〜12月上旬が紅葉のピーク。嵐山の竹林と紅葉の対比、清水寺のライトアップ。この時期の京都は混むが、行く価値がある。早朝に動けば人を避けられる。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "冬（12〜2月）：カニと温泉", level: 2 },
      { type: "text", content: "冬は城崎温泉のカニシーズン。11月〜3月の松葉ガニは一生に一度は食べるべき。外湯巡りの後のカニすき。冬の関西にはこの楽しみがある。" },
      { type: "spot-card", content: "kinosaki" },
    ],
    relatedArticleSlugs: ["kyoto-autumn-leaves", "nanki-shirahama-summer", "kinki-winter-crab-onsen"],
  },
  // ── 36. 大阪 ディープグルメ ──
  {
    slug: "osaka-deep-gourmet",
    title: "大阪のガイドブックに載らない店──地元民が通う横丁メシ",
    description: "観光客が行く店と、大阪人が行く店は違う。本物の大阪メシを食え。",
    coverImage: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["グルメ", "ディープ", "大阪", "地元民"],
    spotIds: ["shinsekai", "dotonbori"],
    sections: [
      { type: "heading", content: "新世界のホルモン焼きは昼から", level: 2 },
      { type: "text", content: "新世界の串カツは観光客向け。地元民はホルモン焼きを食べている。ジャンジャン横丁の奥にある小さな店。カウンターだけ。ビールとホルモン。これが新世界の本当の味。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "法善寺横丁の割烹は予約で行け", level: 2 },
      { type: "text", content: "道頓堀のネオンから一歩入った法善寺横丁。ここの割烹は予約必須。カウンター8席の店で、板前が目の前で仕上げる。観光地の隣にある、大阪の本気。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "朝の喫茶店モーニング文化", level: 2 },
      { type: "text", content: "大阪の純喫茶は朝が面白い。トースト、ゆで卵、コーヒーのモーニングセットが400円台。地元の常連に混ざって朝メシを食べる。これが大阪の日常に入り込む方法。" },
    ],
    relatedArticleSlugs: ["osaka-kuiadaore", "osaka-budget-gourmet", "dotonbori-night-guide"],
  },
  // ── 37. 滋賀 琵琶湖 ──
  {
    slug: "shiga-biwako-guide",
    title: "滋賀は京都の隣にある「もう一つの関西」──琵琶湖の静けさ",
    description: "京都から電車で10分。でも観光客はほぼいない。それが滋賀の魅力。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "shiga",
    tags: ["滋賀", "琵琶湖", "穴場", "のんびり"],
    spotIds: ["arashiyama", "fushimi-inari"],
    sections: [
      { type: "heading", content: "京都から10分で「別世界」に着く", level: 2 },
      { type: "text", content: "京都駅からJRで10分。大津に着くと、空気が変わる。琵琶湖の水面が広がる風景は、京都の密集した街並みとは対照的。観光客がいない分、地元の空気をそのまま味わえる。" },
      { type: "heading", content: "琵琶湖テラスからの絶景", level: 2 },
      { type: "text", content: "びわ湖テラスは標高1,100mから琵琶湖を一望できる展望カフェ。ロープウェイで山頂に上がると、日本一の湖が足元に広がる。この景色を知っている関西人は意外と少ない。" },
      { type: "heading", content: "帰りに京都に寄る、という贅沢", level: 2 },
      { type: "text", content: "滋賀の後に京都に立ち寄れるのが、この立地の強み。午前中に琵琶湖を楽しんで、午後は嵐山か伏見稲荷。1日で2つの世界を味わえる。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "spot-card", content: "fushimi-inari" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "kinki-first-timer", "kyoto-osaka-2days"],
  },
  // ── 38. 三重 伊勢志摩 ──
  {
    slug: "mie-ise-shima-guide",
    title: "三重・伊勢志摩──お伊勢参りと海の幸の正しい順番",
    description: "伊勢神宮は「外宮→内宮」の順番で回れ。逆はNG。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "mie",
    tags: ["三重", "伊勢神宮", "グルメ", "モデルコース"],
    spotIds: ["fushimi-inari", "nara-park"],
    sections: [
      { type: "heading", content: "外宮から内宮へ。これが正式参拝", level: 2 },
      { type: "text", content: "伊勢神宮の正式な参拝順は「外宮→内宮」。多くの観光客が内宮だけ行くが、外宮を飛ばすのは作法として間違い。外宮は森に囲まれた静かな空間。内宮とは全く違う空気がある。" },
      { type: "heading", content: "おかげ横丁で赤福と伊勢うどん", level: 2 },
      { type: "text", content: "内宮の参道にあるおかげ横丁。赤福餅と伊勢うどんは必食。伊勢うどんは太くてコシがない。讃岐うどんの真逆。好みが分かれるが、伊勢に来たなら食べるべき。" },
      { type: "heading", content: "翌日は志摩で海鮮三昧", level: 2 },
      { type: "text", content: "伊勢から志摩へ移動。英虞湾のリアス式海岸は絶景。海女小屋で焼きたての貝を食べる体験は三重でしかできない。京都の寺、大阪のグルメとは違う、海の関西がここにある。" },
    ],
    relatedArticleSlugs: ["kinki-first-timer", "kinki-best-season", "wakayama-nature-trip"],
  },
  // ── 39. 京都 桜シーズン攻略 ──
  {
    slug: "kyoto-sakura-strategy",
    title: "京都の桜、混雑を避ける3つの鉄則",
    description: "桜の京都は戦場。でも「朝・平日・穴場」を守れば、静かな桜に会える。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kyoto",
    tags: ["桜", "京都", "混雑回避", "春"],
    spotIds: ["arashiyama", "kiyomizu", "fushimi-inari"],
    sections: [
      { type: "heading", content: "鉄則1：朝7時に動け", level: 2 },
      { type: "text", content: "桜の京都は10時を過ぎると人で溢れる。嵐山の渡月橋は朝7時なら静か。桜と山のシルエットを独占できる。写真を撮るなら、この時間しかない。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "鉄則2：清水寺は夕方に行け", level: 2 },
      { type: "text", content: "清水寺は朝も混む。むしろ夕方の閉門間際が穴場。西日に照らされた桜と舞台の組み合わせは、朝よりも美しいことがある。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "鉄則3：定番を避けるだけで世界が変わる", level: 2 },
      { type: "text", content: "伏見稲荷の参道にも桜がある。千本鳥居の朱と桜のピンク。この組み合わせを知っている人は少ない。定番スポットの「桜の裏メニュー」を探すのが、通の楽しみ方。" },
      { type: "spot-card", content: "fushimi-inari" },
    ],
    relatedArticleSlugs: ["kyoto-morning-route", "nara-yoshino-spring", "kyoto-autumn-leaves"],
  },
  // ── 40. 姫路城 桜 ──
  {
    slug: "himeji-sakura",
    title: "姫路城と桜──白と桜色の競演",
    description: "白鷺城が最も美しくなる1週間。それが桜の時期。",
    coverImage: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=1200&q=80",
    publishedAt: "2025-03-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "hyogo",
    tags: ["桜", "姫路", "城", "春"],
    spotIds: ["himeji"],
    sections: [
      { type: "heading", content: "三の丸広場が花見の本丸", level: 2 },
      { type: "text", content: "姫路城の三の丸広場は約1,000本の桜に囲まれる。白い天守閣をバックに桜を見上げる構図は、日本中探してもここだけ。城と桜が同時に視界に入る贅沢。" },
      { type: "spot-card", content: "himeji" },
      { type: "heading", content: "西の丸から撮る「決定的構図」", level: 2 },
      { type: "text", content: "西の丸庭園から見上げる天守閣と桜。この構図がSNSで一番バズる。午前中の光が正解。逆光の午後は避けろ。好古園の枝垂桜も忘れずに。" },
      { type: "heading", content: "夜桜ライトアップは圧巻", level: 2 },
      { type: "text", content: "姫路城の夜桜ライトアップは無料。白い城と桜が闇に浮かぶ。昼間とは全く別の城になる。三の丸広場でレジャーシートを広げて、花見酒。これが姫路の春。" },
    ],
    relatedArticleSlugs: ["hyogo-himeji-kinosaki", "himeji-solo-trip", "kyoto-sakura-strategy"],
  },
];
