import { Article } from "@/types/article";

export const ishikawaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "ishikawa-kenrokuen-morning",
    title: "兼六園、早朝7時の入園──日本三名園を独占する無料時間の使い方",
    description: "観光客が押し寄せる前の兼六園は、別の場所になる。早朝の霞が池とことじ灯籠を二人占めする計画術。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "ishikawa",
    tags: ["兼六園", "日本三名園", "早朝", "金沢", "無料"],
    spotIds: ["kenroku-en"],
    sections: [
      { type: "heading", content: "3月〜10月の早朝7〜8時は無料開放", level: 2 },
      { type: "text", content: "兼六園は3月1日〜10月15日の早朝7時から8時まで無料で入園できる。通常の入園料は320円と安価だが、無料時間帯には地元の市民と早起きした旅人しかおらず、庭園が実質的に独占できる。この時間帯の霞が池は水面が鏡のように静まり返り、ことじ灯籠の水鏡が最も美しく撮れる。" },
      { type: "spot-card", content: "kenroku-en" },
      { type: "heading", content: "冬の雪吊り期間が最高潮──11月初旬から始まる", level: 2 },
      { type: "text", content: "兼六園の雪吊りは毎年11月1日頃から始まる作業で、唐崎松への雪吊りが最も有名だ。縄を放射状に張り巡らされた松の姿は、金沢の冬の象徴として全国に知られる。雪が実際に積もった日の兼六園は別世界になり、白と黒と緑の色彩だけになった庭は日本庭園の本質を見せる。" },
      { type: "heading", content: "ことじ灯籠の正しい構図──霞が池の東岸から撮る", level: 2 },
      { type: "text", content: "ことじ灯籠は霞が池の畔に立つ二本脚の石灯籠だ。池の東岸から灯籠を正面に捉え、左後方の霞が池と木々を背景に入れる構図が定番だ。早朝の逆光は灯籠のシルエットをシャープに浮かび上がらせる。観光客が多い昼は縦構図で人を外すか、人が少ない時刻を選ぶしかない。" },
    ],
    relatedArticleSlugs: ["ishikawa-higashi-chaya-walk", "ishikawa-kanazawa-oneway"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "ishikawa-higashi-chaya-walk",
    title: "ひがし茶屋街──格子戸の向こうの加賀百万石、夕方の歩き方",
    description: "昼の茶屋街は観光客で賑わう。しかし夕方になると格子窓に灯りが入り、本当の茶屋街の顔が現れる。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "ishikawa",
    tags: ["ひがし茶屋街", "金沢", "茶屋街", "夕方", "工芸"],
    spotIds: ["higashi-chaya"],
    sections: [
      { type: "heading", content: "紅殻格子の建築美──加賀茶屋の意匠を読む", level: 2 },
      { type: "text", content: "ひがし茶屋街の格子窓に塗られた赤みがかった色は「紅殻（べんがら）」という顔料で、茶屋としての格を示すために使われた。格子の細さと間隔にも格式の違いがあり、上等なお茶屋ほど細かい格子を使う。この建築言語を理解してから通りを歩くと、見える情報量が格段に増える。" },
      { type: "spot-card", content: "higashi-chaya" },
      { type: "heading", content: "金箔体験と老舗の土産──箔一とひがし茶屋街の定番", level: 2 },
      { type: "text", content: "ひがし茶屋街で必ず立ち寄るべきは「箔一本店」だ。金箔を贅沢に使ったアイスクリーム（金箔ソフト）は観光客の定番だが、店内の金箔押し体験（要予約）は職人の技を自分の手で感じられる。石川県の伝統工芸品として金箔は全国生産量の99%を占め、加賀文化の核心だ。" },
      { type: "heading", content: "夕方17時以降が本物の茶屋街──灯りが格子を照らす", level: 2 },
      { type: "text", content: "夕方17時を過ぎると観光客の数が急減し、地元の方々が格子窓を通して明かりをともし始める。この時間帯の茶屋街は、昼間とは全く異なる雰囲気を持つ。石畳に映り込む格子の光と、三味線の音が聞こえるかもしれない静けさの中を歩くのが、ひがし茶屋街の正しい楽しみ方だ。" },
    ],
    relatedArticleSlugs: ["ishikawa-kenrokuen-morning", "ishikawa-omicho-market-guide"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "ishikawa-omicho-market-guide",
    title: "近江町市場の歩き方──金沢市民の台所で食べる朝の海鮮丼",
    description: "280年の歴史を持つ近江町市場は、観光者の場所ではない。地元の食の中心を旅人として体験する方法。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "ishikawa",
    tags: ["近江町市場", "海鮮丼", "のどぐろ", "金沢", "朝食"],
    spotIds: ["omicho-market"],
    sections: [
      { type: "heading", content: "朝8時に入る──地元の料理人が仕入れる時間帯", level: 2 },
      { type: "text", content: "近江町市場は朝8時台に入ると、金沢の飲食店の料理人たちが仕入れをしている姿が見られる。観光客向けの顔と地元民の台所としての顔が同居する時間帯で、威勢のいい掛け声と魚の鮮度が最もピークを迎えている。11時以降になると観光客が増え、市場の雰囲気が変わってくる。" },
      { type: "spot-card", content: "omicho-market" },
      { type: "heading", content: "のどぐろ丼は金沢最高のコスパ体験", level: 2 },
      { type: "text", content: "市場内の食堂で食べるのどぐろ（アカムツ）の海鮮丼は、東京の高級和食店に出せる素材を比較的リーズナブルな価格で楽しめる。白身ながら脂のりが強く、ねっとりとした旨みが特徴だ。市場内の食堂は昼に行列ができるため、10時半頃の開店直後が狙い目となる。" },
      { type: "heading", content: "冬のズワイガニ──11月〜3月が旬の最高峰", level: 2 },
      { type: "text", content: "石川県の冬を代表するのがズワイガニ（加能ガニ・オス、コウバコガニ・メス）だ。11月6日の解禁日以降、近江町市場にはタグ付きの加能ガニが並ぶ。市場内の食堂でカニ料理を食べる場合、焼きガニ・ゆでガニ・カニみそ甲羅焼きをセットで注文すると石川の冬を全網羅できる。" },
    ],
    relatedArticleSlugs: ["ishikawa-higashi-chaya-walk", "ishikawa-kanazawa-oneway"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "ishikawa-shiroyone-senmaida",
    title: "白米千枚田──能登の海に向かう棚田、夕日と夜のLEDイルミネーション",
    description: "1004枚の棚田が海へ落ちる景観は、世界農業遺産の最高傑作だ。四季それぞれの見どころを完全解説。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "ishikawa",
    tags: ["白米千枚田", "棚田", "世界農業遺産", "能登", "夕日"],
    spotIds: ["shiroyone-senmaida"],
    sections: [
      { type: "heading", content: "5月の水鏡と夕日──田植え前が最高の条件", level: 2 },
      { type: "text", content: "田植え前の5月上旬〜中旬、千枚田の棚田に水が張られる時期が水鏡の最高潮だ。水を張った棚田に夕日が映り込み、空と海と田が同じ色に染まる。この構図を撮れる時間は日没前後の15〜20分間だけで、天気と潮の状態によって完成度が変わる。" },
      { type: "spot-card", content: "shiroyone-senmaida" },
      { type: "heading", content: "冬の「あぜのきらめき」──21,000個のLEDが棚田を包む", level: 2 },
      { type: "text", content: "10月下旬〜3月の期間、白米千枚田では「あぜのきらめき」と呼ばれるLEDイルミネーションが行われる。約21,000個のソーラーLEDが棚田の畦道に沿って光り、日本海の漁火と重なる夜の景色は幻想的だ。日没後1時間が最も光が際立つ時間帯で、波音と光の中で過ごす時間は特別な体験になる。" },
      { type: "heading", content: "畦道を歩いて田んぼに入る──展望台だけが全てではない", level: 2 },
      { type: "text", content: "国道249号沿いの展望台からの俯瞰も美しいが、棚田の畦道に降りて田んぼの中を歩くと、千枚田の本当のスケールが体感できる。最小0.2平方メートルという極小の棚田に、先人がいかに労力をかけて農地を維持してきたかが理解できる。入場無料で、一年中開放されている。" },
    ],
    relatedArticleSlugs: ["ishikawa-noto-peninsula-drive", "ishikawa-wajima-morning-market"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "ishikawa-21century-museum",
    title: "金沢21世紀美術館──「スイミング・プール」に沈む体験と現代アートの世界",
    description: "「無料エリアだけで十分楽しめる」は嘘だ。有料展示の密度が、金沢21世紀美術館の本当の価値だ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "ishikawa",
    tags: ["金沢21世紀美術館", "現代アート", "スイミングプール", "金沢", "美術"],
    spotIds: ["kenroku-en", "higashi-chaya"],
    sections: [
      { type: "heading", content: "レアンドロ・エルリッヒ「スイミング・プール」──水中と地上が入れ替わる錯覚", level: 2 },
      { type: "text", content: "金沢21世紀美術館で最も有名な作品は、アルゼンチン出身のレアンドロ・エルリッヒによる「スイミング・プール」だ。プールの上と下に分かれた二層構造で、上から見ると水の中にいるように見える人が実は乾いた空間にいる。水の青みと光の屈折が生み出す錯覚は、写真では伝わらない体感型の作品だ。" },
      { type: "heading", content: "無料ゾーンと有料ゾーンの違いを理解する", level: 2 },
      { type: "text", content: "21世紀美術館は屋外広場と一部の展示室が無料で入れる。しかし有料の展覧会エリアには常設作品（スイミング・プール含む）と企画展が並び、入場料360〜1200円の価値は十分にある。無料エリアだけで満足して帰ると、この美術館の本当の密度を見逃す。平日の開館時間（10時）に並ぶのが最も快適だ。" },
      { type: "heading", content: "円形の建物が作り出す光の空間", level: 2 },
      { type: "text", content: "妹島和世＋西沢立衛（SANAA）が設計した21世紀美術館の建物自体が芸術作品だ。円形の外観、ガラス張りの壁、複数の入口──どこからでも入れる建築は「街に開いた美術館」を体現している。建物の中に入り込む光の質が時間帯によって変わり、午後の斜光が最も美しい時間帯になる。" },
    ],
    relatedArticleSlugs: ["ishikawa-kenrokuen-morning", "ishikawa-higashi-chaya-walk"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "ishikawa-kaga-onsen-guide",
    title: "加賀温泉郷を巡る──山中・山代・粟津・片山津、四つの温泉の個性",
    description: "加賀温泉郷は個性の異なる四温泉地の集合体だ。どこに泊まるかで体験が全く変わる。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "ishikawa",
    tags: ["加賀温泉郷", "山中温泉", "山代温泉", "片山津温泉", "石川"],
    spotIds: ["kenroku-en"],
    sections: [
      { type: "heading", content: "山中温泉──鶴仙渓の渓谷美と芭蕉の足跡", level: 2 },
      { type: "text", content: "山中温泉は松尾芭蕉が「奥の細道」で訪れ、「山中や　菊はたおらじ　湯の匂い」と詠んだことで知られる歴史ある温泉地だ。大聖寺川沿いの渓谷「鶴仙渓」は遊歩道が整備され、秋の紅葉が渓流と重なる景観が美しい。源泉かけ流しの旅館が多く、泉質の良さは四温泉の中でも屈指だ。" },
      { type: "heading", content: "山代温泉──加賀藩御用達の格式と九谷焼文化", level: 2 },
      { type: "text", content: "山代温泉は加賀藩の御用達湯として栄えた格式ある温泉地。総湯（共同浴場）の「古総湯」は明治時代の建物を復元した施設で、石畳の浴室が時代感を漂わせる。九谷焼の産地にも近く、湯上がりに九谷焼の工房見学や購入ができる組み合わせが旅人に人気だ。" },
      { type: "heading", content: "片山津温泉──柴山潟に映る白山と水上花火", level: 2 },
      { type: "text", content: "片山津温泉は柴山潟という汽水湖の畔に立地し、湖越しに白山を望む景観が特徴的だ。夏（7〜8月）には水上花火大会が開催され、湖面に映る花火の迫力は他の花火大会と異なる水面効果がある。温泉旅館の露天風呂から柴山潟の夕日を眺める体験は片山津温泉だけのものだ。" },
    ],
    relatedArticleSlugs: ["ishikawa-luxury-kanazawa-stay", "ishikawa-kenrokuen-morning"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "ishikawa-noto-peninsula-drive",
    title: "能登半島ドライブ──千里浜・白米千枚田・輪島を走る1泊2日",
    description: "能登半島は車でないと回れない。千里浜なぎさドライブウェイから輪島まで、海岸線を走る旅の設計図。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "ishikawa",
    tags: ["能登半島", "千里浜", "ドライブ", "輪島", "白米千枚田"],
    spotIds: ["shiroyone-senmaida"],
    sections: [
      { type: "heading", content: "千里浜なぎさドライブウェイ──砂浜を走れる奇跡の8km", level: 2 },
      { type: "text", content: "能登半島ドライブの出発点は千里浜なぎさドライブウェイだ。砂粒が細かく水分を含んだ砂浜は車が沈まず、一般車が走れる日本唯一の砂浜ドライブウェイ（約8km）が存在する。波打ち際をタイヤが走る感覚と、窓を開けると潮の香りが入ってくる体験は他では体験できない。" },
      { type: "heading", content: "輪島朝市──早朝8時から始まる日本三大朝市", level: 2 },
      { type: "text", content: "輪島市中心部の「輪島朝市」は日本三大朝市のひとつとされる。朝8時から12時頃まで、地元の女性（「いちばの女将さん」と呼ばれる）が自家製の漬物・海産物・地場野菜を売る姿が続く。干物・サザエ・アワビなど能登の海の幸を直接購入でき、値切り交渉ができる数少ない観光市場だ。" },
      { type: "heading", content: "白米千枚田で夕日を待つ──能登半島最後の絶景", level: 2 },
      { type: "text", content: "輪島市から車で30分の白米千枚田は、能登ドライブの締めくくりに最適なスポットだ。夕日が日本海に落ちる時刻に合わせて展望台に立つと、棚田・海・夕日が重なる能登半島の景観の精髄を体験できる。輪島に一泊して翌朝の朝市→夕方の千枚田という動線が能登の旅の完成形だ。" },
    ],
    relatedArticleSlugs: ["ishikawa-shiroyone-senmaida", "ishikawa-wajima-morning-market"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "ishikawa-wajima-morning-market",
    title: "輪島朝市──日本三大朝市の正しい歩き方と買い方",
    description: "輪島の朝市は観光客向けではなく、本物の生活市場だ。女将さんとの駆け引きが輪島の醍醐味。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "ishikawa",
    tags: ["輪島朝市", "能登", "朝市", "海産物", "輪島"],
    spotIds: ["shiroyone-senmaida"],
    sections: [
      { type: "heading", content: "朝8時から12時──最も新鮮な時間帯は9時頃", level: 2 },
      { type: "text", content: "輪島朝市は朝8時から始まるが、全店揃うのは9時頃だ。地元の漁師の妻たちが前日の水揚げを持ち込むため、鮮度は朝が最も良い。午前中早いうちは干物・塩辛・海藻類など保存食が中心で、生魚類は早朝便が入る漁港直送の店にある。" },
      { type: "heading", content: "輪島塗と沈金体験──朝市通りを歩きながら工芸にも触れる", level: 2 },
      { type: "text", content: "朝市通り周辺には輪島塗の工房・販売店が点在する。輪島塗は124以上の工程を経る日本最高峰の漆器で、丈夫さと美しさの両立が特徴だ。工房見学（無料〜500円）では漆を塗り重ねる工程が見学でき、沈金（漆に金粉を埋め込む技法）の体験が予約制で提供されている施設もある。" },
      { type: "heading", content: "能登の朝ごはん──輪島の食堂で食べる漁師料理", level: 2 },
      { type: "text", content: "朝市の後は近くの食堂で能登の朝食を食べる。サザエの壺焼き・いしる（魚醤）を使った味噌汁・能登の地卵の卵かけご飯が揃う朝の定食は700〜1000円台。いしるは長期熟成した魚醤で、能登半島固有の発酵調味料だ。この朝食を経験すると能登の食文化の深さが実感できる。" },
    ],
    relatedArticleSlugs: ["ishikawa-noto-peninsula-drive", "ishikawa-shiroyone-senmaida"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "ishikawa-kanazawa-oneway",
    title: "金沢1日モデルコース──兼六園・ひがし茶屋街・近江町市場を最も効率よく回る",
    description: "金沢の三大観光地を半日で全部回れると思ったら甘い。一つひとつをちゃんと楽しむための時間配分術。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "ishikawa",
    tags: ["金沢", "モデルコース", "1日観光", "兼六園", "ひがし茶屋街"],
    spotIds: ["kenroku-en", "higashi-chaya", "omicho-market"],
    sections: [
      { type: "heading", content: "朝7時：兼六園（無料時間）→8時：近江町市場（朝食）", level: 2 },
      { type: "text", content: "金沢1日コースの最適解は朝7時スタートだ。まず無料開放時間の兼六園に入り（7〜8時）、早朝の庭園を独占する。8時に出て徒歩15分で近江町市場へ向かい、朝食として海鮮丼か白えびかき揚げ丼を食べる。市場内の食堂は10時半開店が多いため、早朝は市場を見て回り、開店と同時に入ると良い。" },
      { type: "heading", content: "午前：21世紀美術館→昼：ひがし茶屋街", level: 2 },
      { type: "text", content: "近江町市場の後は金沢21世紀美術館へ。開館10時と同時に入場し、スイミング・プールとその他の常設展示を1時間半で回る。12時頃ひがし茶屋街へ移動し、昼食はこのエリアの町家カフェか甘味処で。茶屋街の観光は混雑する昼間は流し見にして、夕方に再訪する計画が合理的だ。" },
      { type: "heading", content: "夕方：ひがし茶屋街（再訪）→夜：金沢の食", level: 2 },
      { type: "text", content: "午後は金沢城公園と武家屋敷跡・長町武家屋敷を歩き、夕方16時半頃に再びひがし茶屋街へ戻る。格子窓に灯りが入る夕暮れ時は昼間とは全く別の風景だ。夜は片町・香林坊エリアの居酒屋でのどぐろ・ズワイガニ・地酒（萬歳楽・天狗舞）で締める。金沢の1日はこれで完成する。" },
    ],
    relatedArticleSlugs: ["ishikawa-kenrokuen-morning", "ishikawa-higashi-chaya-walk"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "ishikawa-couple-kanazawa-stay",
    title: "金沢カップル旅行──加賀料理と茶屋街と金箔の、二人で泊まる旅",
    description: "金沢は「泊まってわかる」街だ。夜の茶屋街、加賀料理の懐石、早朝の兼六園。一泊で完成するカップル旅。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "ishikawa",
    tags: ["カップル", "金沢", "加賀料理", "旅館", "記念日"],
    spotIds: ["kenroku-en", "higashi-chaya", "omicho-market"],
    sections: [
      { type: "heading", content: "加賀料理の懐石で金沢の食文化を体感する", level: 2 },
      { type: "text", content: "金沢の夕食に選ぶべきは加賀料理の懐石コースだ。加賀野菜（打木赤皮甘栗かぼちゃ・源助大根など）と日本海の魚介、加賀の地酒で構成されたコースは、東京の和食とは素材の産地が全く異なる。特に香箱ガニ（コウバコガニ）の季節（11月〜1月）に合わせると石川の秋冬の食の頂点が体験できる。" },
      { type: "heading", content: "夜の茶屋街を二人で歩く", level: 2 },
      { type: "text", content: "夕食後にひがし茶屋街へ向かうと、格子窓の明かりが石畳を照らす夜の風景が待っている。観光客がほとんどいなくなった夜の茶屋街を二人で歩くのは、昼間とは全く異なる体験だ。まれに三味線の音が漏れ聞こえる夜もあり、加賀百万石の花街の余韻が今も生きていることを実感する。" },
      { type: "heading", content: "翌朝の兼六園無料時間で旅を締める", level: 2 },
      { type: "text", content: "チェックアウト前の朝7時に兼六園の無料開放時間を利用する。早朝の庭園は宿泊した旅人だけに許された独占時間だ。ことじ灯籠の前で二人の写真を撮り、霞が池の鏡面を眺めてから帰路につく。金沢の一泊はこのルーティンで完成する。" },
    ],
    relatedArticleSlugs: ["ishikawa-kenrokuen-morning", "ishikawa-higashi-chaya-walk"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "ishikawa-family-kanazawa",
    title: "金沢子連れ旅行──21世紀美術館・金箔体験・海鮮市場で子どもが輝く旅",
    description: "金沢は子ども連れでも十分楽しい。体験型の施設と食の豊かさで、家族旅行の満足度が高い街だ。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "ishikawa",
    tags: ["子連れ", "家族旅行", "金沢", "体験", "金箔"],
    spotIds: ["kenroku-en", "higashi-chaya", "omicho-market"],
    sections: [
      { type: "heading", content: "21世紀美術館「スイミング・プール」は子どもに大人気", level: 2 },
      { type: "text", content: "金沢21世紀美術館のスイミング・プールは、子どもが水中にいる人に手を振ったり、水面を叩く真似をしたりと体験型の楽しみ方ができる。現代アートの概念が難しくても「不思議な体験」として直感的に楽しめる作品だ。美術館の無料エリアも広く、小さな子どもでも退屈しない。" },
      { type: "heading", content: "金箔体験で世界に一つの工芸品を作る", level: 2 },
      { type: "text", content: "ひがし茶屋街周辺の金箔工房では、子どもでも参加できる金箔貼り体験（1500〜2000円）が用意されている。黒い台紙や箸・コースターに金箔を貼り付ける体験は、日本の伝統工芸に親しむ良い機会だ。完成品はそのまま土産として持ち帰れる。" },
      { type: "heading", content: "近江町市場で食育──魚の名前と食べ方を教える", level: 2 },
      { type: "text", content: "近江町市場は生きた食育の場だ。見たこともない魚が並び、市場の方が丁寧に説明してくれる。子どもが「この魚なに？」と聞くと、市場の人が答えてくれる機会が日常的にある。市場内の食堂で食べる海鮮丼の食材を、購入前に実物で確認してから食べると記憶に残る体験になる。" },
    ],
    relatedArticleSlugs: ["ishikawa-21century-museum", "ishikawa-kanazawa-oneway"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "ishikawa-budget-kanazawa",
    title: "金沢を3000円で楽しむ──無料の庭園・市場飯・加賀の酒で完全旅行",
    description: "意外と金沢は安く旅できる。無料の兼六園早朝・近江町の安い食堂・立ち飲み地酒。節約旅の金沢完全版。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-25",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "ishikawa",
    tags: ["節約旅行", "金沢", "バジェット", "格安", "無料"],
    spotIds: ["kenroku-en", "omicho-market"],
    sections: [
      { type: "heading", content: "兼六園の無料時間を最大活用する", level: 2 },
      { type: "text", content: "3月〜10月の朝7〜8時は兼六園が無料開放される。通常入場料320円が節約でき、しかも観光客がほぼいない最高のコンディションで庭を独占できる。早起きするだけで「金沢最高体験」が無料になる。金沢城公園も入場無料（玉泉院丸庭園・石川門などの一部施設は有料）だ。" },
      { type: "heading", content: "近江町市場の立ち食いで1000円以内の昼食", level: 2 },
      { type: "text", content: "近江町市場内には立ち食いスタイルの海鮮丼専門店がある。白えびかき揚げ丼850円、のどぐろ丼1200円（市場価格）と、テーブルサービスの食堂より割安で新鮮な海鮮が食べられる。早めに並んで確保すれば、金沢で最もコスパが高い食事体験が1000〜1500円で完成する。" },
      { type: "heading", content: "地酒を立ち飲みで──加賀の酒を金沢最安で飲む", level: 2 },
      { type: "text", content: "金沢市内の地酒専門酒屋では角打ち（立ち飲み）スタイルで地酒を1杯300〜500円で提供している。天狗舞・菊姫・萬歳楽・福光屋など石川を代表する銘柄を少量ずつ飲み比べると、旅の思い出に残る酒体験が1500円以下で完成する。" },
    ],
    relatedArticleSlugs: ["ishikawa-kenrokuen-morning", "ishikawa-omicho-market-guide"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "ishikawa-luxury-kanazawa-stay",
    title: "金沢の高級旅館に泊まる──加賀百万石の美意識に包まれる1泊",
    description: "金沢の最高級旅館は「宿泊する加賀文化体験」だ。工芸・料理・庭・温泉が一体になった贅沢の設計図。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "ishikawa",
    tags: ["高級旅館", "金沢", "加賀料理", "贅沢旅", "工芸"],
    spotIds: ["kenroku-en", "higashi-chaya"],
    sections: [
      { type: "heading", content: "加賀百万石の器に盛る懐石料理", level: 2 },
      { type: "text", content: "金沢の最高級旅館の夕食は、九谷焼・輪島塗・加賀友禅の布を器として使う懐石料理が多い。料理よりも器が主役といわれる加賀料理の文化は、盛り付けの美学が江戸時代から培われてきた。香箱ガニ（11〜1月）の甲羅盛りは石川の冬の最高傑作で、1尾まるごと味わうコースを選べる宿がある。" },
      { type: "heading", content: "加賀温泉郷の高級旅館と金沢市内の差", level: 2 },
      { type: "text", content: "金沢市内の旅館は観光利便性が高いが、温泉付きの本格高級旅館は加賀温泉郷（山中・山代・粟津）に多い。目的に応じて選び分けることが重要だ。金沢市内は観光後の移動なしで旅館に入れる利点があり、加賀温泉郷は源泉かけ流しと料理の本格度で上回る場合が多い。" },
      { type: "heading", content: "工芸品をコレクションする──高級旅館が最高の購入場所", level: 2 },
      { type: "text", content: "金沢の高級旅館には輪島塗・九谷焼・金箔工芸の優れた作品を展示・販売しているケースが多い。旅館で使っている器を気に入り、フロントに相談して入手するというのは金沢旅の粋な土産選びだ。量産品ではない職人の手仕事が、旅館という空間で実際に使われる形で展示されている。" },
    ],
    relatedArticleSlugs: ["ishikawa-kaga-onsen-guide", "ishikawa-couple-kanazawa-stay"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "ishikawa-noto-recovery-travel",
    title: "能登を旅する意味──復興を見守りながら食べ、歩く旅のあり方",
    description: "能登半島への旅は「消費」ではなく「応援」になる。観光客が訪れることで地域が回る仕組みを理解して旅する。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "ishikawa",
    tags: ["能登半島", "復興", "応援旅行", "観光支援", "石川"],
    spotIds: ["shiroyone-senmaida"],
    sections: [
      { type: "heading", content: "能登への旅が地域を支える直接的な経済効果", level: 2 },
      { type: "text", content: "能登半島への観光旅行は宿泊費・飲食費・土産購入という形で直接地域経済を支援する。地場産品を積極的に買うこと、地元の旅館に泊まること、能登産の食材を使う食堂で食べることが、観光客にできる最も効果的な応援だ。「消費する旅」から「応援する旅」へという意識の転換が、旅の意味を変える。" },
      { type: "heading", content: "訪問前に確認すること──開いている場所と復旧状況", level: 2 },
      { type: "text", content: "能登を訪れる前に、石川県観光連盟や各市町村の観光情報サイトで施設の営業状況を確認することが必要だ。すべての観光地が以前と同じ状態ではない可能性があるが、訪問してその現状を見ることも旅の学びになる。輪島朝市も白米千枚田も、能登の人々の営みと共に続いている。" },
      { type: "heading", content: "能登の食文化を体験することが最大の応援", level: 2 },
      { type: "text", content: "能登には「いしる（魚醤）」「能登の塩」「石川のコシヒカリ」「能登牛」など、他の地域では手に入らない食材と文化が豊富にある。これらを産地で食べ、土産として購入することが観光客ができる能登への最大の貢献だ。旅先での消費が、生産者を直接支える形になる。" },
    ],
    relatedArticleSlugs: ["ishikawa-noto-peninsula-drive", "ishikawa-wajima-morning-market"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "ishikawa-kanazawa-craft-tour",
    title: "金沢の工芸をめぐる旅──九谷焼・輪島塗・加賀友禅の産地と作り手に会う",
    description: "金沢は「工芸の都」だ。作品を見るだけでなく、作り手に会い、体験し、持ち帰る旅の組み立て方。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-08-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "ishikawa",
    tags: ["工芸", "九谷焼", "輪島塗", "加賀友禅", "金沢"],
    spotIds: ["higashi-chaya", "kenroku-en"],
    sections: [
      { type: "heading", content: "九谷焼の大胆な彩色──小松市の産地を訪ねる", level: 2 },
      { type: "text", content: "九谷焼は石川県南部の小松市・加賀市・能美市が産地で、金沢市内でも多くの工房が工芸を継承している。赤・緑・紺・黄・紫の「九谷五彩」を使った大胆な絵付けが特徴で、同じ形の器でも絵師によって全く異なる表情を持つ。体験教室では白い素地に自分で絵付けする九谷焼作り体験が1時間3000〜5000円で参加できる。" },
      { type: "heading", content: "加賀友禅──繊細な写実描写と加賀五彩", level: 2 },
      { type: "text", content: "加賀友禅は金沢の伝統的な染色工芸で、草花を写実的に描き「虫食い」の表現（葉に虫食いの模様を描く）が独自のスタイルだ。金沢市内の加賀友禅工房では染め体験（ハンカチ・スカーフへの型染め）が可能で、加賀五彩の色彩を自分で選んで染める体験は加賀文化への没入体験になる。" },
      { type: "heading", content: "ひがし茶屋街で工芸品を「使う」感覚で買う", level: 2 },
      { type: "text", content: "ひがし茶屋街周辺の工芸品店は、飾るための美術品ではなく「使う工芸品」を中心に扱う店が増えている。九谷焼のマグカップ、輪島塗の箸、金箔加工のコースター──日常で使える工芸品を旅先で選ぶことが、金沢の伝統工芸を現代に繋げる行為になる。" },
    ],
    relatedArticleSlugs: ["ishikawa-higashi-chaya-walk", "ishikawa-luxury-kanazawa-stay"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "ishikawa-kanazawa-seasonal-spring",
    title: "春の金沢──兼六園の桜と近江町の桜鯛と加賀温泉の新緑",
    description: "金沢の春は桜・食・温泉が同時に最高潮を迎える特別な季節だ。4月の金沢旅の全情報を整理する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "ishikawa",
    tags: ["春", "桜", "金沢", "桜鯛", "兼六園"],
    spotIds: ["kenroku-en", "omicho-market"],
    sections: [
      { type: "heading", content: "兼六園の桜──200本が咲き乱れる4月上旬", level: 2 },
      { type: "text", content: "兼六園の桜は4月上旬が見頃で、ことじ灯籠と霞が池を背景に咲く桜の景観は日本庭園の春の頂点を見せる。早朝の無料時間（7〜8時）に入れば、ほぼ独占状態で桜と庭園を歩ける。夜のライトアップ（期間限定）では池面に映る桜が、昼間とは全く異なる幻想的な景観を作り出す。" },
      { type: "heading", content: "桜鯛と春の近江町市場──旬の魚が一番安い時期", level: 2 },
      { type: "text", content: "3月〜4月の日本海では桜の季節に合わせてタイが産卵前の最も脂がのった状態になる「桜鯛」の時期だ。近江町市場では桜鯛の刺身・昆布〆・鯛飯が旬の味として並ぶ。白身ながら脂のりが豊かな春の鯛は、金沢の春にしか食べられない旬の味覚だ。" },
      { type: "heading", content: "加賀温泉郷の新緑と山中温泉の桜", level: 2 },
      { type: "text", content: "金沢から1時間圏内の加賀温泉郷では、4月中旬〜下旬に新緑と遅咲きの桜が重なる。山中温泉の鶴仙渓遊歩道は桜と新緑が渓谷の川沿いに連なり、温泉地の宿に泊まりながら早朝に散歩できる。金沢市内の桜が散った後でも、山間部では桜が楽しめるのが石川の春の特徴だ。" },
    ],
    relatedArticleSlugs: ["ishikawa-kenrokuen-morning", "ishikawa-kaga-onsen-guide"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "ishikawa-kanazawa-winter",
    title: "冬の金沢──雪吊りと香箱ガニと加賀料理、石川の冬を全部楽しむ",
    description: "金沢の冬は観光客が減り、食が最高峰を迎える。雪吊りの兼六園と香箱ガニが揃う11月〜2月の旅。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "ishikawa",
    tags: ["冬", "金沢", "雪吊り", "香箱ガニ", "加賀料理"],
    spotIds: ["kenroku-en", "omicho-market"],
    sections: [
      { type: "heading", content: "11月1日──雪吊り作業開始の日から金沢の冬が始まる", level: 2 },
      { type: "text", content: "兼六園の雪吊り作業は毎年11月1日に唐崎松への縄掛けから始まる。この日は金沢市民にとって「冬が来た」を告げる儀式だ。12月から1月にかけて雪が積もると、雪吊りと雪化粧の兼六園が完成する。積雪後の早朝が最も美しく、雪の重みで縄が弧を描く様子が圧巻だ。" },
      { type: "heading", content: "香箱ガニの解禁は11月6日──冬の食の最大イベント", level: 2 },
      { type: "text", content: "石川県でのメスのズワイガニ（香箱ガニ）漁の解禁は毎年11月6日だ。この日から近江町市場と金沢市内の飲食店には香箱ガニが並び始め、旬のピークは1月末まで続く。内子（卵巣）と外子（受精卵）が詰まった甲羅盛りは、石川の冬にしか食べられない稀有な料理体験だ。" },
      { type: "heading", content: "冬の加賀温泉郷──空いているオフシーズンの旅", level: 2 },
      { type: "text", content: "11月〜2月の加賀温泉郷は夏や紅葉期より観光客が少なく、旅館の予約が取りやすい。源泉かけ流しの湯につかりながら露天風呂で雪景色を眺める体験は、冬の温泉地の王道だ。山中温泉の旅館では蟹料理と温泉のセットプランが期間限定で提供され、食と湯の冬の贅沢が完成する。" },
    ],
    relatedArticleSlugs: ["ishikawa-kenrokuen-morning", "ishikawa-kaga-onsen-guide"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "ishikawa-kanazawa-food-deep",
    title: "金沢グルメ深掘り──治部煮・加賀棒茶・柴舟小出と地元の食文化の根",
    description: "海鮮だけじゃない金沢の食。郷土料理・茶文化・和菓子の奥深さを旅しながら体験する。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "ishikawa",
    tags: ["金沢グルメ", "治部煮", "加賀棒茶", "和菓子", "郷土料理"],
    spotIds: ["omicho-market", "higashi-chaya"],
    sections: [
      { type: "heading", content: "治部煮──加賀百万石の郷土料理の意味", level: 2 },
      { type: "text", content: "治部煮（じぶに）は金沢を代表する郷土料理だ。小麦粉をまぶした鴨肉（または鶏肉）を甘辛く煮た料理で、麩・野菜・わさびを加えたシンプルな煮物だ。茶道が盛んだった金沢で、茶懐石料理として発展したとされる。味わいは濃いめの甘辛だが、最後にわさびを溶かして食べると风味が引き締まる。" },
      { type: "heading", content: "加賀棒茶──炒り立ての香ばしさが金沢の茶文化", level: 2 },
      { type: "text", content: "加賀棒茶は一番摘みの茶葉の茎（棒）を焙煎した独特の香ばしいお茶だ。金沢では「棒茶」と呼ぶだけで通じるほど日常の茶として定着している。ひがし茶屋街周辺の茶専門店では試飲ができ、焙煎の強弱による風味の違いを確認してから購入できる。" },
      { type: "heading", content: "金沢の和菓子──森八・柴舟小出・諸江屋", level: 2 },
      { type: "text", content: "金沢は和菓子の生産量が全国3位（1人あたり消費量）といわれる和菓子の街だ。加賀藩の茶道文化が和菓子を育てた。森八の「長生殿」は国の重要無形文化財に指定された干菓子で、旅の土産として最も格式がある。柴舟小出の「柴舟」は生姜入りの薄焼きせんべいで、加賀棒茶との相性が抜群だ。" },
    ],
    relatedArticleSlugs: ["ishikawa-omicho-market-guide", "ishikawa-higashi-chaya-walk"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "ishikawa-noto-peninsula-deep",
    title: "能登半島の食を旅する──いしる・能登の塩・能登牛と発酵文化",
    description: "能登は「発酵の半島」だ。いしる・糠漬け・さわいかの機能性発酵食品が集積する独自の食文化を旅する。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "ishikawa",
    tags: ["能登", "いしる", "発酵食品", "能登牛", "食文化"],
    spotIds: ["shiroyone-senmaida"],
    sections: [
      { type: "heading", content: "いしる──秋田の塩魚汁・香川のいかなご醤油と並ぶ日本三大魚醤", level: 2 },
      { type: "text", content: "「いしる」（いしり）は能登半島で製造される魚醤で、イカや魚の内臓を塩漬けして発酵させたものだ。輪島市内に複数の製造元があり、製法や原料魚によって風味が大きく異なる。汁物・炒め物・刺身のたれとして使われ、能登の家庭料理には欠かせない調味料だ。土産として最も能登らしい品のひとつだ。" },
      { type: "heading", content: "能登の塩──揚浜式製塩という原始的な方法", level: 2 },
      { type: "text", content: "珠洲市に残る「揚浜式製塩」は、砂浜の砂に海水を撒いて塩分を凝縮させる古代からの製塩方法で、国の重要無形民俗文化財に指定されている。海水を直接蒸発させる方法と異なり、ミネラルが豊富でまろやかな塩が生まれる。塩田見学（夏期）では職人の作業を間近で見ることができる。" },
      { type: "heading", content: "能登牛──和牛の隠れた名ブランド", level: 2 },
      { type: "text", content: "能登牛は石川県内で育てられた和牛のブランドで、年間出荷頭数が少ないため全国的な知名度は低いが、霜降りの質と赤身の旨みのバランスが高く評価される。輪島・珠洲の旅館や飲食店では能登牛のステーキ・焼肉・すき焼きを提供しており、産地で食べる体験は特別な価値がある。" },
    ],
    relatedArticleSlugs: ["ishikawa-wajima-morning-market", "ishikawa-noto-peninsula-drive"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "ishikawa-kanazawa-access-tips",
    title: "金沢へのアクセスと市内移動──北陸新幹線・バス・自転車の最適解",
    description: "北陸新幹線延伸で金沢へのアクセスが変わった。各都市からの最速・最安ルートと市内移動のコツを解説。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "ishikawa",
    tags: ["アクセス", "北陸新幹線", "金沢", "移動", "バス"],
    spotIds: ["kenroku-en", "higashi-chaya", "omicho-market"],
    sections: [
      { type: "heading", content: "東京から金沢は北陸新幹線で約2時間30分", level: 2 },
      { type: "text", content: "2015年の北陸新幹線開業以降、東京〜金沢間は最速2時間28分（かがやき）でアクセスできる。早割・ネット割引きっぷを活用すると片道1万円台前半になることもある。金沢駅は「新幹線が停まる最大の観光地」として機能しており、駅内の商業施設で金沢の土産を一括購入できるほど充実している。" },
      { type: "heading", content: "大阪・京都からはサンダーバードが復活", level: 2 },
      { type: "text", content: "2024年の北陸新幹線敦賀延伸により、大阪・京都からは敦賀乗換で金沢へのアクセスとなった。特急サンダーバードで敦賀まで行き、そこから北陸新幹線に乗り換えて金沢まで約2時間。在来線特急の本数が削減されているため、事前に時刻表を確認することが必須だ。" },
      { type: "heading", content: "市内はバスと自転車で十分──タクシー不要の回り方", level: 2 },
      { type: "text", content: "金沢市内の観光地は金沢駅から半径3km以内に集中している。100円バス（城下まち金沢周遊バス）を使えば、兼六園・ひがし茶屋街・21世紀美術館・近江町市場を1乗車100円で移動できる。体力に自信があれば自転車が最も自由度が高く、駅レンタサイクルが500円/日程度で借りられる。" },
    ],
    relatedArticleSlugs: ["ishikawa-kanazawa-oneway", "ishikawa-kenrokuen-morning"],
  },
];
