import { Article } from "@/types/article";

export const kagawaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "kagawa-kotohira-785steps",
    title: "金刀比羅宮、785段を登る作法──何時に行けば本宮を独り占めできるか",
    description: "「こんぴらさん」の石段は量ではなく質で楽しむもの。朝イチで登った者だけが知る静寂がある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagawa",
    tags: ["金刀比羅宮", "石段", "パワースポット", "こんぴらさん", "香川"],
    spotIds: ["kotohira-gu"],
    sections: [
      { type: "heading", content: "開門直後の6時台が黄金タイム", level: 2 },
      { type: "text", content: "金刀比羅宮の開門は6時。観光バスが到着する9時前後の混雑を完全に避けるには、6〜7時台に登り始めるのが正解だ。早朝の石段には地元の参拝者と遍路姿の旅人しかおらず、785段を踏む足音と鳥の声だけが聞こえる。本宮のベンチから見渡す讃岐平野の朝靄は、登り終えた達成感を何倍にも高める景色だ。" },
      { type: "heading", content: "石段の途中で立ち止まるべき場所", level: 2 },
      { type: "text", content: "365段目の旭社は国の重要文化財で、装飾彫刻の密度が本殿に匹敵する。多くの観光客が素通りするが、30分は眺めていられる精巧さだ。500段付近の「五人百姓」は境内で唯一商売が許可された飴屋で、加美代飴を試食できる。階段の左右にある石灯籠の刻字が時代ごとに変わることも読み解きながら登ると、飽きずに785段を制覇できる。" },
      { type: "spot-card", content: "kotohira-gu" },
      { type: "heading", content: "奥社へのさらなる583段──挑む者の特権", level: 2 },
      { type: "text", content: "本宮の先にある奥社まで583段の追加が待つ。本宮訪問者の約1割しか奥社に達しないとされるが、奥社境内に入ると獰猛な守護神・厳魂彦命（いづたまひこのみこと）の場所にたどり着く。遮るものがない山頂の展望と風は、平地では得られない解放感を体全体で感じさせる。" },
    ],
    relatedArticleSlugs: ["kagawa-sanuki-udon-crawl", "kagawa-model-course-2days"],
  },

  // ── 2 ──────────────────────────────────────
  {
    slug: "kagawa-ritsurin-garden-morning",
    title: "栗林公園、開園直後の90分──ミシュラン三ツ星が朝だけ別の顔を見せる",
    description: "日の出とともに開く庭園を、観光客のいない光の中で歩く。これが栗林公園の正しい訪れ方だ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kagawa",
    tags: ["栗林公園", "庭園", "朝散歩", "ミシュラン", "香川"],
    spotIds: ["ritsurin-garden"],
    sections: [
      { type: "heading", content: "開園は日の出とともに──この設計が正しい", level: 2 },
      { type: "text", content: "栗林公園は日の出時刻に合わせて開門する。春なら5時半ごろ、夏なら5時前後。この時間帯に入ると、朝光が南湖の水面をオレンジに染め、松の影が長く伸びる最高の景観が待っている。入場料410円を払って早朝の静寂に対面すると、安さに申し訳なさすら感じる。" },
      { type: "heading", content: "偃月橋と南湖──朝の光が正解を教えてくれる", level: 2 },
      { type: "text", content: "栗林公園の代表的な撮影スポット「偃月橋」は、朝の東向き光線の時間帯に橋が順光になる。橋と水面と借景の紫雲山が画面に収まるアングルは、南側の対岸から狙うのが定石。三脚は不要で、スマートフォンのHDRモードで十分に絵になる写真が撮れる。" },
      { type: "spot-card", content: "ritsurin-garden" },
      { type: "heading", content: "掬月亭のお点前でしめる", level: 2 },
      { type: "text", content: "園内の掬月亭では抹茶と和菓子を楽しめる（820円）。南湖に面した縁側席で池を眺めながら茶をいただく体験は、日本庭園の本質に触れる時間だ。早朝は9時から対応しており、朝の散策の締めとして最適。高松空港から車で20分という好立地で、四国旅行の最初または最後に組み込むと旅のグレードが上がる。" },
    ],
    relatedArticleSlugs: ["kagawa-kotohira-785steps", "kagawa-sanuki-udon-crawl"],
  },

  // ── 3 ──────────────────────────────────────
  {
    slug: "kagawa-shodoshima-olive-island",
    title: "小豆島1泊2日──オリーブ・そうめん・寒霞渓、島の全部を詰め込む旅",
    description: "フェリーで1時間の島に、一日では消化しきれないほどの個性がある。小豆島の最良の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kagawa",
    tags: ["小豆島", "島旅", "オリーブ", "1泊2日", "香川"],
    spotIds: ["shodoshima"],
    sections: [
      { type: "heading", content: "1日目：オリーブ公園とエンジェルロード", level: 2 },
      { type: "text", content: "高松港8時発のフェリーで土庄港に到着後、レンタカーかレンタサイクルで西半分を攻める。オリーブ公園は10月のオリーブ収穫期が最も色鮮やかで、ギリシャ風車とオリーブ畑の組み合わせが絵になる。エンジェルロードは干潮時に出現する砂の道で、潮見表で干潮時刻を確認してから訪れる。昼食は土庄町内で醤油工場直営のレストランへ。" },
      { type: "spot-card", content: "shodoshima" },
      { type: "heading", content: "2日目：寒霞渓の紅葉と手延べそうめん工場", level: 2 },
      { type: "text", content: "小豆島中央部にそびえる寒霞渓は日本三大渓谷美のひとつ。ロープウェイで山頂に上がると瀬戸内海の多島美が広がる。紅葉の最盛期（11月上中旬）は混雑するため、早朝便を狙う。午後は手延べそうめんの製造工場を見学し、試食コーナーでコシのある島素麺を体験。帰りのフェリーは高松行きより姫路・神戸行きを選ぶと、瀬戸内海の夕景が船上から楽しめる。" },
      { type: "heading", content: "二十四の瞳映画村──昭和の小学校が残る岬", level: 2 },
      { type: "text", content: "島南東部の田浦地区にある「二十四の瞳映画村」は、映画のロケに使われた木造校舎がそのまま保存されている。昭和の教室・映画の衣装・地元アーティストの作品が混在する独特の空間。観光客が少ない平日午前が静かでゆっくり見られる。帰路に立ち寄る時間を30分確保しておくと、島の印象が締まる。" },
    ],
    relatedArticleSlugs: ["kagawa-naoshima-art-island", "kagawa-model-course-2days"],
  },

  // ── 4 ──────────────────────────────────────
  {
    slug: "kagawa-naoshima-art-island",
    title: "直島アート完全攻略──地中美術館・家プロジェクト・草間彌生を1日で回るルート",
    description: "直島は計画なしに行くと後悔する。チケット事情・回る順序・フェリー時刻を熟知した上で臨む。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagawa",
    tags: ["直島", "現代アート", "地中美術館", "草間彌生", "香川"],
    spotIds: ["naoshima"],
    sections: [
      { type: "heading", content: "チケットは事前予約必須──当日は買えないと思え", level: 2 },
      { type: "text", content: "地中美術館の入場チケットは公式サイトでの日時指定事前購入が推奨（実質必須）。週末・GW・紅葉期は数週間前に完売することもある。家プロジェクトのチケット（全7棟共通1,050円）は島内チケットセンターで購入できるが、人気の「南寺」は整理券配布制。島に着いたらまず南寺の整理券を入手することが最重要ミッションだ。" },
      { type: "spot-card", content: "naoshima" },
      { type: "heading", content: "推奨ルート：本村地区→地中美術館→ベネッセハウス", level: 2 },
      { type: "text", content: "宮浦港着後、まず本村地区で家プロジェクトを巡る（約2〜3時間）。昼食は本村地区内のカフェで島野菜ランチ。午後は地中美術館へ（約2時間）。モネの睡蓮3点を自然光の中で見るためだけに来る価値がある。日没前にベネッセハウス前の黄かぼちゃで写真を撮り、最終フェリーで帰る。この流れで1日フルに使う計算になる。" },
      { type: "heading", content: "泊まるならベネッセハウスで──アートの中で眠る体験", level: 2 },
      { type: "text", content: "ベネッセハウスに宿泊すると、閉館後の静寂な美術館を歩ける特権がある。島の星空の美しさも宿泊者だけが独占できる要素だ。1泊5〜8万円と高価だが、アートファンには唯一無二の体験を提供する。日帰りとは全く異なるアートの濃度が、翌朝に残る余韻を作る。" },
    ],
    relatedArticleSlugs: ["kagawa-shodoshima-olive-island", "kagawa-model-course-2days"],
  },

  // ── 5 ──────────────────────────────────────
  {
    slug: "kagawa-sanuki-udon-crawl",
    title: "讃岐うどん食べ歩き──製麺所・セルフ・一般店の三流派を制覇する半日",
    description: "讃岐うどんは一種類ではない。製麺所の立ち食いから名店の釜揚げまで、三つの流派を理解して食べる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagawa",
    tags: ["讃岐うどん", "グルメ", "食べ歩き", "うどん", "香川"],
    spotIds: [],
    sections: [
      { type: "heading", content: "製麺所型：地元民しか来ない朝7時の店", level: 2 },
      { type: "text", content: "讃岐うどんの最もプリミティブな形態が「製麺所型」。高松市内や郊外にある製麺所の一角でうどんを食べさせてくれる店で、一玉100〜200円という非常識な安さ。座席がなく立ち食いの店もある。看板がなく、知る人しか来ない場所もある。「坂出インター近くの宮武うどん」「高松市内の山越うどん」が製麺所型の聖地として有名で、朝7時の開店前に行列ができる。" },
      { type: "heading", content: "セルフ型：トッピングを自分で盛る讃岐スタイル", level: 2 },
      { type: "text", content: "讃岐うどん最大の特徴のひとつがセルフサービス。トレーにうどんを受け取り、天ぷら・おにぎり・いなり寿司を自分で選んでトッピングする。一食400〜600円が相場。「はなまるうどん」「丸亀製麺」はこのスタイルのチェーン展開版だが、地元の個人セルフ店とは麺のコシが段違い。スーパーに隣接した地元セルフ店に飛び込むのが正解だ。" },
      { type: "heading", content: "釜揚げうどん：麺の本質を最も純粋に味わう形式", level: 2 },
      { type: "text", content: "「田村うどん（善通寺）」の釜揚げは、ぐらぐら煮えた状態の麺を釜からすくってつけだしで食べる。麺がふわふわとしてコシとは逆の柔らかさを持ち、冷やうどんとは別次元の食べ物だ。釜揚げ専門店では麺の打ち方も変わるため、同じうどんとは思えない質感の差がある。1日3食うどんを食べることが「うどん県」香川では普通の感覚だ。" },
    ],
    relatedArticleSlugs: ["kagawa-honetsuki-chicken", "kagawa-model-course-2days"],
  },

  // ── 6 ──────────────────────────────────────
  {
    slug: "kagawa-honetsuki-chicken",
    title: "骨付鶏──丸亀発の讃岐グルメが東京進出しても超えられない現地の味",
    description: "骨付き鶏もも肉をスパイスで焼いた骨付鶏は、香川でしか本物には出会えない。一鶴の行列に並ぶ価値とは。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagawa",
    tags: ["骨付鶏", "グルメ", "一鶴", "丸亀", "香川"],
    spotIds: [],
    sections: [
      { type: "heading", content: "骨付鶏の発祥は丸亀の「一鶴」", level: 2 },
      { type: "text", content: "骨付鶏は鶏もも肉を骨付きのまま香辛料で焼いた料理で、丸亀市が発祥。1952年創業の「一鶴（いっかく）」が現在の形を確立した。親鳥（かみ応えのある成鶏）と若鳥（柔らかいひなどり）の二種があり、初めてなら若鳥から入るのがセオリー。食べ終わった後の肉汁をキャベツに絡めて食べるのが正しいフィニッシュだ。" },
      { type: "heading", content: "なぜ現地でしか本物の味が出ないのか", level: 2 },
      { type: "text", content: "一鶴は東京・大阪に支店があるが、丸亀・高松の本店と比べると焼き加減が違うと地元民は言う。薪窯で焼く高温と香辛料の配合は門外不出で、通信販売の冷凍品を試した人が「違う」と感じる理由がそこにある。1本1,200〜1,500円という値段も現地価格で、東京のそれより割安だ。行列は覚悟の上で、一鶴の丸亀本店を目指す。" },
      { type: "heading", content: "骨付鶏の楽しみ方──ビールとキャベツと", level: 2 },
      { type: "text", content: "骨付鶏にはビールか生レモンサワーが合う。テーブルに置かれた生キャベツは、強い塩辛さの中和と肉汁の受け皿を兼ねる。食べ方の作法は、骨を手でつかんで豪快にかじること。フォークとナイフでは本質的なおいしさの半分しか届かない。食後の口の周りのにんにく・ペッパーの残り香が、旅の記憶として翌日まで続く。" },
    ],
    relatedArticleSlugs: ["kagawa-sanuki-udon-crawl", "kagawa-model-course-2days"],
  },

  // ── 7 ──────────────────────────────────────
  {
    slug: "kagawa-model-course-2days",
    title: "香川2泊3日モデルコース──うどん・アート・島と庭園を全制覇",
    description: "「うどん県」の看板に隠れた香川の多面性を、3日間で全部体験できるルートを設計した。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kagawa",
    tags: ["モデルコース", "2泊3日", "香川", "うどん", "直島"],
    spotIds: ["ritsurin-garden", "kotohira-gu", "naoshima"],
    sections: [
      { type: "heading", content: "1日目：高松→栗林公園→琴平", level: 2 },
      { type: "text", content: "高松空港着後、まず栗林公園へ（入園1時間）。昼食は製麺所型うどんの聖地・山越うどん（高松市）。午後はJRかことでん（高松琴平電気鉄道）で琴平へ移動。金刀比羅宮の785段を登り、本宮からの夕景を鑑賞。夜は琴平温泉の旅館に宿泊し、名物の灸まんを部屋で食べる。" },
      { type: "spot-card", content: "kotohira-gu" },
      { type: "heading", content: "2日目：直島でアートに浸る", level: 2 },
      { type: "text", content: "高松港8時発のフェリーで直島へ。家プロジェクト・地中美術館を1日かけて巡る。夕方のフェリーで高松に戻り、高松港周辺の居酒屋で骨付鶏と地酒（香川の地酒「川鶴」「悦凱陣」）を楽しむ。翌日の早起きに備えて、高松市内のホテルに連泊する。" },
      { type: "spot-card", content: "naoshima" },
      { type: "heading", content: "3日目：小豆島の早朝便で帰る", level: 2 },
      { type: "text", content: "朝イチのフェリーで小豆島へ（約1時間）。オリーブ公園と寒霞渓をレンタカーで半日かけて回り、手延べそうめんの工場見学で昼食。午後のフェリーで高松に戻り、空港送迎バスで帰路へ。帰りの手荷物には讃岐うどん乾麺・小豆島そうめん・オリーブオイルを入れる。" },
    ],
    relatedArticleSlugs: ["kagawa-sanuki-udon-crawl", "kagawa-ritsurin-garden-morning"],
  },

  // ── 8 ──────────────────────────────────────
  {
    slug: "kagawa-family-tour",
    title: "子連れ香川1泊2日──うどん作り体験と直島の黄かぼちゃで大人も子どもも満足",
    description: "讃岐うどん打ち体験は小学生でも30分でできる。直島の草間彌生は子どもの記憶に刻まれる体験だ。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "kagawa",
    tags: ["子連れ", "うどん体験", "直島", "家族旅", "香川"],
    spotIds: ["naoshima"],
    sections: [
      { type: "heading", content: "うどん打ち体験は高松市内で予約できる", level: 2 },
      { type: "text", content: "讃岐うどん打ち体験は高松市内の体験施設で1人1,500〜2,500円。こねる・踏む・延ばす・切るの全工程を子どもがやり遂げられる設計になっている。自分で打ったうどんをその場で茹でて食べる体験は、食育としての価値が高い。うどんのコシの秘密を実感できるのは、食べる前に自分の手でこねた人だけだ。" },
      { type: "heading", content: "直島の黄かぼちゃは子どもが最も反応するアート", level: 2 },
      { type: "text", content: "直島の地中美術館は小学生以下入場不可だが、宮浦港の赤かぼちゃ（草間彌生）は無料で体験できる。内部に入れる穴がある赤かぼちゃに子どもは夢中になる。黄かぼちゃ（本村港）は撮影スポットとして子どもが自然にポーズをとる。島のレンタサイクルで両スポットを回る時間は約2時間で十分だ。" },
      { type: "spot-card", content: "naoshima" },
      { type: "heading", content: "帰りは丸亀城に寄り道する", level: 2 },
      { type: "text", content: "丸亀城は現存12天守のひとつで、城壁の高さが日本一。子どもが「大きい！」と驚く石垣は、積み方の美しさで見惚れる大人と、駆け上がりたい子どものニーズが一致する場所だ。天守から眺める瀬戸内海と讃岐平野の組み合わせは香川のまとめとして完璧。帰路の丸亀港から高松への船も、瀬戸内の景色で子どもが飽きない。" },
    ],
    relatedArticleSlugs: ["kagawa-sanuki-udon-crawl", "kagawa-model-course-2days"],
  },

  // ── 9 ──────────────────────────────────────
  {
    slug: "kagawa-couple-island-stay",
    title: "直島1泊2日のカップル旅──アートの島に泊まって知る、昼と夜の違い",
    description: "日帰り観光の直島とは全く別の島が、宿泊者には現れる。ベネッセハウスと星空と夜の静寂。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kagawa",
    tags: ["直島", "カップル", "ベネッセハウス", "島宿泊", "香川"],
    spotIds: ["naoshima"],
    sections: [
      { type: "heading", content: "閉館後の美術館を二人で歩く", level: 2 },
      { type: "text", content: "ベネッセハウス宿泊者は閉館後の夜間に屋外アート作品を自由に散歩できる。観光客が帰った夜の直島は別の島になる。宮浦港の黄かぼちゃを月明かりの下で見ると、昼間の賑わいとは全く異なる彫刻の重みを感じる。波の音と作品が対話するような時間は、旅の中で最も記憶に残る夜の一つになる。" },
      { type: "spot-card", content: "naoshima" },
      { type: "heading", content: "地中美術館を開館直後に独占する", level: 2 },
      { type: "text", content: "宿泊者の特権として、開館直後の10時に他の観光客が少ない時間帯を利用できる。地中美術館のモネの部屋は自然光を使った展示のため、時間によって光の色と質が変わる。朝の澄んだ光の中の睡蓮は、昼のそれとは全く異なる表情を見せる。これを二人で目撃する体験は、アートと自然の交差点でしか得られない。" },
      { type: "heading", content: "帰りは小豆島経由のルートで香川を深める", level: 2 },
      { type: "text", content: "直島から小豆島へのフェリーを組み合わせると、帰路を島巡りにできる。小豆島でオリーブソフトクリームを食べて、夕方のフェリーで高松か姫路に渡る。香川の島々を渡り歩く旅の締め方として、この帰路ルートが最も旅情を高める。" },
    ],
    relatedArticleSlugs: ["kagawa-naoshima-art-island", "kagawa-shodoshima-olive-island"],
  },

  // ── 10 ──────────────────────────────────────
  {
    slug: "kagawa-budget-udon-trip",
    title: "1万円で香川を満喫する──格安うどん旅の全計算書を公開",
    description: "交通費・宿泊費・食費込みで1万円台の香川旅行は本当に可能か。実際に計算してみたら可能だった。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-02-01",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "kagawa",
    tags: ["節約旅", "格安", "うどん", "バジェット", "香川"],
    spotIds: [],
    sections: [
      { type: "heading", content: "大阪から日帰りで達成できる最小コスト", level: 2 },
      { type: "text", content: "大阪梅田から高松まで高速バス往復約3,500円。高松市内のうどん3軒はしごで最大1,800円。栗林公園入場410円。交通と食事を合わせて5,710円という計算が成立する。宿泊なしの日帰りなら、大阪発で1万円以内の香川旅行が実現する。問題は往復5時間の移動時間をどう楽しむかだ。" },
      { type: "heading", content: "1泊2日の格安プラン：ゲストハウス＋朝うどん", level: 2 },
      { type: "text", content: "高松市内のゲストハウスはドミトリー1泊2,500〜3,500円。朝5時から営業するうどん屋での朝うどん（280円〜）と合わせると、1泊2日の宿＋食費を6,000円以内に抑えられる。ことでん1日乗り放題切符（1,000円）を使えば市内交通もカバー。金刀比羅宮は無料（奥社まで完全無料）なので、観光コストはほぼゼロに近づく。" },
      { type: "heading", content: "節約と体験を両立する直島日帰り案", level: 2 },
      { type: "text", content: "直島は宿泊すると高価だが、日帰りなら費用を絞れる。高松港からのフェリー往復1,500円程度、家プロジェクトチケット1,050円、昼食島内カフェ1,000円で合計3,550円。地中美術館チケット（2,100円）を加えても5,650円。これを格安バス移動と組み合わせると、1泊2日で1.5万円以内の香川・直島旅行が実現する計算になる。" },
    ],
    relatedArticleSlugs: ["kagawa-sanuki-udon-crawl", "kagawa-naoshima-art-island"],
  },

  // ── 11 ──────────────────────────────────────
  {
    slug: "kagawa-luxury-kotohira-stay",
    title: "琴平の贅沢な夜──金刀比羅宮参拝後に泊まる温泉旅館の選び方",
    description: "785段を登りきった後に待つ、琴平温泉の旅館。疲れた体を癒す湯と、讃岐料理のコースが旅を完成させる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-11-25",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kagawa",
    tags: ["贅沢旅", "琴平温泉", "高級旅館", "こんぴらさん", "香川"],
    spotIds: ["kotohira-gu"],
    sections: [
      { type: "heading", content: "琴平温泉は参拝後の宿泊地として完璧", level: 2 },
      { type: "text", content: "金刀比羅宮参拝後の疲れた足と体を癒すために、琴平の旅館に泊まることを強く勧める。温泉ではないが良質な軟水を使った大浴場を持つ旅館が多く、足湯や半露天で785段の疲れを抜く時間は旅の贅沢の本質だ。琴平町は旅館街として整備されており、金刀比羅宮と歩いて5分以内の立地が揃っている。" },
      { type: "spot-card", content: "kotohira-gu" },
      { type: "heading", content: "夕食は讃岐食材のコース料理で", level: 2 },
      { type: "text", content: "高級旅館の夕食は讃岐うどん・骨付鶏・オリーブ牛（香川県産の和牛）・小豆島の海鮮を組み合わせた会席料理が多い。オリーブ牛はオリーブの搾りかすを飼料にした香川ブランド牛で、サシが入りつつさっぱりした風味が特徴。1泊2食付き2〜4万円の旅館でこのコースが楽しめる。翌朝は再び境内を早朝散歩できる立地が最大の利点だ。" },
      { type: "heading", content: "琴平から高知・徳島への足として活用する", level: 2 },
      { type: "text", content: "琴平はしまなみ海道とは逆方向の四国内陸部に位置するが、高松・徳島・高知への交通の結節点でもある。四国旅行のベースキャンプとして琴平に泊まり、各方面に日帰りする旅程も成立する。琴平駅からの特急アクセスは高松40分・高知1時間30分と効率的だ。" },
    ],
    relatedArticleSlugs: ["kagawa-kotohira-785steps", "kagawa-model-course-2days"],
  },

  // ── 12 ──────────────────────────────────────
  {
    slug: "kagawa-solo-cycling",
    title: "香川一人ライド──高松〜琴平間60kmをサイクリングで走る日帰り",
    description: "平坦な讃岐平野はサイクリングに最適な地形だ。うどん屋を繋ぐルートで60kmを食べながら走る。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kagawa",
    tags: ["サイクリング", "一人旅", "讃岐平野", "うどん", "香川"],
    spotIds: ["kotohira-gu", "ritsurin-garden"],
    sections: [
      { type: "heading", content: "高松駅前レンタサイクルで出発", level: 2 },
      { type: "text", content: "高松駅前のレンタサイクルは1日1,200〜1,500円。電動アシスト付きなら向い風の日も快適だ。高松市内を南下して讃岐平野に入ると、進む先に金刀比羅宮の山が見えてくる。この一本道の景色が讃岐平野ライドの原風景で、右手に讃岐富士（飯野山）の美しい山容が付き合ってくれる。" },
      { type: "heading", content: "途中のうどん屋を繋ぐ「うどんルート」", level: 2 },
      { type: "text", content: "高松〜琴平間のサイクリングルートには有名うどん店が10軒以上点在する。一玉200〜350円のうどんを3〜4軒はしごしながら走ると、60kmの疲れを感じない。「田村うどん（善通寺）」「中村うどん（琴平）」など古参店が国道沿いに並んでいる。自転車は店の前に停めても怒られない雰囲気が讃岐にはある。" },
      { type: "spot-card", content: "kotohira-gu" },
      { type: "heading", content: "帰りはJR特急でゴール", level: 2 },
      { type: "text", content: "琴平駅からJR特急で高松まで約40分（自転車は解体・袋詰め必要）。輪行袋は持参が必要だが、体力を消耗した帰路を電車でリカバリーできるこのルートは日帰りサイクリングの完成形だ。駅前でレンタサイクルを返却して終了。走行距離60km・獲得標高最小という讃岐平野ならではの理想的なサイクリング環境だ。" },
    ],
    relatedArticleSlugs: ["kagawa-kotohira-785steps", "kagawa-sanuki-udon-crawl"],
  },

  // ── 13 ──────────────────────────────────────
  {
    slug: "kagawa-shodoshima-olive-gourmet",
    title: "小豆島のオリーブグルメ徹底解説──オリーブオイルの等級と使い方を島の生産者に聞いた",
    description: "日本のオリーブ発祥の地・小豆島。生産者が教えるオリーブオイルの正しい選び方と、島の食卓への取り入れ方。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagawa",
    tags: ["小豆島", "オリーブ", "グルメ", "オリーブオイル", "香川"],
    spotIds: ["shodoshima"],
    sections: [
      { type: "heading", content: "日本のオリーブ栽培は1908年、小豆島から始まった", level: 2 },
      { type: "text", content: "農林水産省が明治41年（1908年）に試験栽培を開始したのが、小豆島のオリーブ生産の原点。地中海性気候に近い瀬戸内の温暖な気候が栽培に適しており、現在は全国生産量の大部分を担う。島内には複数のオリーブ農場が直売所を運営しており、搾りたてのエクストラバージンオリーブオイルを試飲できる。" },
      { type: "spot-card", content: "shodoshima" },
      { type: "heading", content: "等級と味の違い──エクストラバージンの何が違うのか", level: 2 },
      { type: "text", content: "最上級の「エクストラバージンオリーブオイル」は酸度0.8%以下で、果実由来の香りと苦味・辛味が明確にある。スーパーの安価品と比べると、小豆島産のフレッシュEVOOは胡椒のような辛味と青草の香りが突出して高い。島内農場での試飲で複数の品種（マンザニロ・ルッカ・ミッション）を飲み比べると、オリーブオイルの奥深さが体感できる。" },
      { type: "heading", content: "島の食卓でのオリーブオイルの使い方", level: 2 },
      { type: "text", content: "島民はオリーブオイルを刺身に、うどんに、おにぎりのしょうゆ代わりに使う。特に「刺身×オリーブオイル×塩」の組み合わせは、見た目以上にサーモンやブリに合う。土産として500ml瓶を一本買って帰ると、料理の発想が変わる。農場直売店では収穫期（10〜11月）に最安値で購入できる。" },
    ],
    relatedArticleSlugs: ["kagawa-shodoshima-olive-island", "kagawa-sanuki-udon-crawl"],
  },

  // ── 14 ──────────────────────────────────────
  {
    slug: "kagawa-takamatsu-night",
    title: "高松の夜を深く歩く──商店街・兵庫町・片原町でつなぐ大人の夜遊び",
    description: "高松は日本最長のアーケード商店街を持つ街だ。夜になってもシャッターが閉まらない理由がある。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kagawa",
    tags: ["高松", "夜遊び", "居酒屋", "商店街", "香川"],
    spotIds: [],
    sections: [
      { type: "heading", content: "天神前〜高松築港まで2.7kmのアーケード", level: 2 },
      { type: "text", content: "高松市には日本最長クラスのアーケード商店街が続く。丸亀町・兵庫町・片原町などが連なり、夜でも多くの店が開いている。ただ歩くだけでうどん屋・居酒屋・土産物店・書店が続き、観光とローカルの境界が曖昧な空間が続く。夜の商店街は昼間と空気が違い、地元の学生や会社員が多く、旅行者の孤独を和らげてくれる賑わいがある。" },
      { type: "heading", content: "片原町の横丁で瀬戸内肴をつまむ", level: 2 },
      { type: "text", content: "片原町には小さな居酒屋横丁がある。カウンター5席程度の個人店で、ハマチ（香川ではイナダをハマチと呼ぶ）・タコ・イイダコの天ぷらが500〜700円で食べられる。地酒は「悦凱陣（よろこびがいじん）」を燗で頼むのが地元流。大将に翌日のうどん屋情報を聞くと、観光ガイドには載っていない朝一番の名店を教えてくれることがある。" },
      { type: "heading", content: "夜のライフラインは高松港の夜景", level: 2 },
      { type: "text", content: "商店街を抜けて高松港に出ると、直島・小豆島行きフェリーの待合所が夜も明るく開いている。港の防波堤から見える瀬戸内海の夜景と灯台の光が、都市の夜とは違う静けさを提供する。翌日の島旅への期待をここで膨らませてから、商店街のホテルに戻る夜の動線が高松の旅の正解だ。" },
    ],
    relatedArticleSlugs: ["kagawa-model-course-2days", "kagawa-honetsuki-chicken"],
  },

  // ── 15 ──────────────────────────────────────
  {
    slug: "kagawa-setouchi-triennale",
    title: "瀬戸内国際芸術祭の歩き方──直島・豊島・犬島を3日間で効率よく巡る",
    description: "3年に一度開催される瀬戸内国際芸術祭。島をまたぐフェリーの組み合わせと宿確保の裏技を公開する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagawa",
    tags: ["瀬戸内芸術祭", "直島", "アート", "島旅", "香川"],
    spotIds: ["naoshima", "shodoshima"],
    sections: [
      { type: "heading", content: "芸術祭は春・夏・秋の三会期で開催", level: 2 },
      { type: "text", content: "瀬戸内国際芸術祭は春（4〜5月）・夏（7〜9月）・秋（10〜11月）の三会期に分かれて開催される。会期ごとに参加島・展示アートが変わる場合があるため、公式サイトで最新情報を確認する必要がある。一般的に夏会期が最も混雑し、春・秋会期は比較的落ち着いて鑑賞できる。パスポート（全島全期間パス）を事前購入すると入場料が約20〜30%割安になる。" },
      { type: "spot-card", content: "naoshima" },
      { type: "heading", content: "フェリー時刻表は30分単位で組み立てる", level: 2 },
      { type: "text", content: "芸術祭の島々をつなぐフェリーは1日数便しか運航しない路線が多い。直島→豊島→犬島と渡り歩くには、各フェリーの出発時刻を前日夜に確認して行程表を作る。逃すと次便まで2〜3時間待ちになる。高松港発着を基点に組み立て、予備の時間を各島で30分以上確保しておく設計が安全だ。" },
      { type: "heading", content: "宿は3ヶ月前から動く", level: 2 },
      { type: "text", content: "芸術祭期間中の直島・豊島の宿は数ヶ月前に完売する。特にベネッセハウスは半年前から予約が埋まることもある。高松市内のホテルをベースにしてフェリー日帰りを繰り返す方法が現実的で、費用も抑えられる。豊島の民宿は予約さえできれば島民との距離が近い体験ができる。" },
    ],
    relatedArticleSlugs: ["kagawa-naoshima-art-island", "kagawa-shodoshima-olive-island"],
  },

  // ── 16 ──────────────────────────────────────
  {
    slug: "kagawa-udon-breakfast-culture",
    title: "香川の朝うどん文化──なぜ朝5時から行列ができるのか",
    description: "朝食にうどんを食べることが当たり前の香川。その文化の深さと、朝うどん巡りの楽しみを語る。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-01-30",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagawa",
    tags: ["朝うどん", "うどん文化", "香川", "グルメ", "讃岐"],
    spotIds: [],
    sections: [
      { type: "heading", content: "朝5時開店のうどん屋が存在する理由", level: 2 },
      { type: "text", content: "香川県民の朝食にうどんを食べる習慣は、農繁期に早朝から働く農民が手早く食事を済ませる文化から来ている。現代でも「朝うどん」は県民の日常で、近所のうどん屋で一杯食べてから仕事へ向かう人が多い。朝5時から開店する店があるのは需要があるからで、観光客が驚くこの事実が「うどん県」の真の姿だ。" },
      { type: "heading", content: "かけうどんの構造を理解する", level: 2 },
      { type: "text", content: "朝うどんの基本は「かけうどん」。透き通った出汁にうどんだけが入ったシンプルな一杯は、一玉200〜350円が相場。出汁は煮干しと昆布が基本で、東讃（高松・東側）は薄口醤油・西讃（坂出・丸亀側）はやや色が濃い傾向がある。薬味のネギとおろし生姜を自分で入れるスタイルが多く、朝の胃に優しい軽い食事として機能する。" },
      { type: "heading", content: "朝うどんの名店ルート──5時から8時の2時間", level: 2 },
      { type: "text", content: "「なかむらうどん（琴平）」は5時半開店の製麺所型。「宮武うどん（坂出）」は朝7時から地元客で埋まる。「山越うどん（高松）」は8時から整理券が必要になる人気店。この三軒を一日で巡ると、香川のうどん文化の幅と深さが立体的に見えてくる。いずれも一杯200〜400円という価格が、香川の日常食としての位置づけを物語っている。" },
    ],
    relatedArticleSlugs: ["kagawa-sanuki-udon-crawl", "kagawa-budget-udon-trip"],
  },

  // ── 17 ──────────────────────────────────────
  {
    slug: "kagawa-naoshima-teshima",
    title: "豊島（てしま）アート探訪──直島の次に行くべき瀬戸内の秘島",
    description: "豊島美術館の水のインスタレーションは、建築・アート・自然が一体になった奇跡の空間だ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kagawa",
    tags: ["豊島", "豊島美術館", "アート", "瀬戸内", "香川"],
    spotIds: ["naoshima"],
    sections: [
      { type: "heading", content: "豊島美術館は1日に一つだけ行くべき場所", level: 2 },
      { type: "text", content: "西沢立衛設計の豊島美術館は、窓のない白いシェル構造の中に内藤礼の水のインスタレーションが展開する。床面からわき出る水の玉が重力に逆らって動く空間は、美術館というより「体験装置」だ。最低でも1時間は滞在してほしい。周囲の棚田と海が窓越しに見える構図が完璧で、最良の鑑賞体験には少し雲のある日が向いている。" },
      { type: "heading", content: "高松から豊島へのフェリールート", level: 2 },
      { type: "text", content: "高松港から豊島（家浦港）まで約35分のフェリーが1日4〜5便運航している。直島経由のルートもある。島内の移動はレンタサイクル（1日1,000円）が主流で、棚田の畦道を走りながらアート作品を点在する地図で探す時間が豊島らしい楽しみ方だ。豊島横尾館は横尾忠則のグラフィック世界が古民家に展開する異空間。" },
      { type: "heading", content: "豊島の食──棚田米のおにぎりと島の食堂", level: 2 },
      { type: "text", content: "豊島は農業再生の島でもあり、棚田で作られた米は島の食堂でおにぎりになる。家浦港近くの「島キッチン」は直島ベネッセのシェフが関わった島の食材レストランで、ランチセットが1,500円前後。観光地価格ではなく島の日常価格に近いことが島旅の豊かさだ。帰りのフェリーで食べる棚田米のおにぎりを持参すると、瀬戸内海が食卓になる。" },
    ],
    relatedArticleSlugs: ["kagawa-naoshima-art-island", "kagawa-setouchi-triennale"],
  },

  // ── 18 ──────────────────────────────────────
  {
    slug: "kagawa-kotohira-deep-culture",
    title: "こんぴらさんを知って参拝する──石段の奥に眠る海の神の歴史",
    description: "金刀比羅宮は785段の石段で有名だが、船乗りの守護神としての歴史を知ると参拝の深みが変わる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagawa",
    tags: ["金刀比羅宮", "歴史", "文化", "海の神", "香川"],
    spotIds: ["kotohira-gu"],
    sections: [
      { type: "heading", content: "なぜ内陸の山に「海の神」が祀られているのか", level: 2 },
      { type: "text", content: "金刀比羅宮が祀る大物主命（おおものぬしのみこと）は農業・産業・海上の神として信仰されてきた。江戸時代の船乗りは「こんぴら参り」を航海安全の最大の信仰とし、讃岐国への参拝者が急増した背景がある。参道には今も全国の船会社・漁業組合が奉納した絵馬・模型船が多数あり、海と神の結びつきが物理的に見える。" },
      { type: "spot-card", content: "kotohira-gu" },
      { type: "heading", content: "「こんぴら狗」──犬が代参した江戸の文化", level: 2 },
      { type: "text", content: "江戸時代、足が不自由だったり遠くて参拝できない人が、犬に初穂料と旅費を袋に入れて首に提げ、道中の人々に「こんぴら代参の犬」として世話を頼んだ「こんぴら狗」という文化があった。犬は旅人に食事を与えられ、こんぴらさんまで届けてもらった。参道には現代でもこの犬の石像があり、江戸の文化の優しさが伝わる。" },
      { type: "heading", content: "参道の土産──灸まんと醤油豆の正統な選び方", level: 2 },
      { type: "text", content: "琴平参道の名物土産「灸まん」（琴平名物のお灸の形をした饅頭）は、白あんと黄あんが選べる。コシのある讃岐の醤油豆（そら豆の醤油煮）は香川の家庭の味で、お茶うけとして最適。正統な土産選びは「琴平名物＋香川全体の土産」を組み合わせること。空港では手に入らない地元製造の醤油豆は、参道の老舗で買うのが正解だ。" },
    ],
    relatedArticleSlugs: ["kagawa-kotohira-785steps", "kagawa-luxury-kotohira-stay"],
  },

  // ── 19 ──────────────────────────────────────
  {
    slug: "kagawa-access-tips",
    title: "香川へのアクセスと島間移動の全ガイド──フェリー・新幹線・飛行機の使い分け",
    description: "高松・直島・小豆島を繋ぐ移動の組み合わせは複雑に見えて、理解すれば自在に動ける。完全ガイドを作った。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagawa",
    tags: ["アクセス", "フェリー", "交通", "高松", "香川"],
    spotIds: [],
    sections: [
      { type: "heading", content: "本州から高松へ──岡山新幹線乗り継ぎが最速", level: 2 },
      { type: "text", content: "東京から高松までは、東京→岡山（新幹線約3時間20分）→高松（マリンライナー約1時間）のルートが最速（約4時間20分、約15,000〜20,000円）。飛行機は高松空港便があるが、便数が少なく早割でないと高価。大阪からは高速バス（約2時間30分、1,800〜2,500円）が圧倒的に安くて使いやすい。" },
      { type: "heading", content: "高松港からの島へのフェリー時刻表の読み方", level: 2 },
      { type: "text", content: "高松港は直島・小豆島・豊島・犬島など瀬戸内島々へのフェリーの中心地。各航路は1日3〜8便程度で、時刻は季節・曜日によって変動する。直島便は1日8往復程度で最も便利。小豆島便は2時間に1本程度。フェリー予約は「四国フェリー」公式サイトか「RYDE」アプリが使いやすい。連休は乗用車積載スペースが先に満杯になるため、徒歩乗船なら予約不要の場合が多い。" },
      { type: "heading", content: "島間直行フェリーを活用する", level: 2 },
      { type: "text", content: "高松を経由せずに島間を直行するフェリーも存在する。直島→豊島→小豆島を結ぶ便（1日1〜2便）を使うと、高松への往復を省いて移動できる。ただし便数が少ないため、乗り遅れると半日ロスになる。豊島美術館の閉館（17時）から最終フェリーまでの時間を逆算してスケジュールを組む必要がある。" },
    ],
    relatedArticleSlugs: ["kagawa-model-course-2days", "kagawa-setouchi-triennale"],
  },

  // ── 20 ──────────────────────────────────────
  {
    slug: "kagawa-new-year-kotohira",
    title: "年明けの金刀比羅宮初詣──元旦の人混みと朝3時の静寂は別物だ",
    description: "元旦に金刀比羅宮を参拝するなら、人が来る前か全員帰った後か。二つの選択肢と、その体験の違いを語る。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-12-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kagawa",
    tags: ["初詣", "金刀比羅宮", "正月", "年末年始", "香川"],
    spotIds: ["kotohira-gu"],
    sections: [
      { type: "heading", content: "元旦の石段は日本最長クラスの行列になる", level: 2 },
      { type: "text", content: "金刀比羅宮の元旦参拝者は数万人規模で、石段は人の流れが止まる。本宮到達まで通常の3倍近い時間がかかる。しかしこの人混みも「こんぴらさんの年初め」の文化の一部で、地元民は怒らずに並ぶ。屋台が出る参道の賑わいも正月の風物詩として楽しめれば、元旦の混雑は苦でなくなる。" },
      { type: "spot-card", content: "kotohira-gu" },
      { type: "heading", content: "12月31日深夜〜1月1日午前0時の参拝という選択", level: 2 },
      { type: "text", content: "地元民の一部は深夜0時の年越し参拝を選ぶ。石段に松明が灯され、参道に人影がまばらな中で785段を登る体験は非日常そのもの。気温は一桁になることが多く、暖かい服装と懐中電灯が必要。元旦昼間の混雑とは全く異なる静寂と神聖さがあり、「こんぴらさんの本当の顔」を見た気がする参拝になる。" },
      { type: "heading", content: "正月の讃岐うどんは白みそ雑煮と一緒に", level: 2 },
      { type: "text", content: "香川の正月料理は白みそ仕立てのお雑煮が定番で、丸餅・金時にんじん・大根が入る。琴平の旅館では元旦の朝食にこのお雑煮と讃岐うどんが出ることがある。白みそのまろやかな甘みと讃岐うどんのコシが、正月の朝に最も相応しい食の組み合わせだと感じる。" },
    ],
    relatedArticleSlugs: ["kagawa-kotohira-785steps", "kagawa-luxury-kotohira-stay"],
  },
];
