import { Article } from "@/types/article";

export const kagoshimaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "kagoshima-sakurajima-morning",
    title: "桜島、夜明けの噴煙──活火山と向き合う鹿児島の朝の、唯一無二の景色",
    description: "桜島は毎日噴火する。市街地のすぐ目の前で火山が生きている光景は、日本どこにもない日常だ。夜明けに港から桜島を眺める体験を語る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagoshima",
    tags: ["桜島", "活火山", "鹿児島港", "朝焼け", "鹿児島"],
    spotIds: ["sakurajima"],
    sections: [
      { type: "heading", content: "鹿児島港からのフェリーは「動く展望台」だ", level: 2 },
      { type: "text", content: "鹿児島港から桜島までのフェリー（15分・¥200）は、乗船中に桜島を正面から見ながら近づいていく。早朝6時台の便は観光客が少なく、夜明けの桜島が朝日に染まる景色を甲板で独占できる。桜島が灰を噴出している日は、黒煙が空に広がり、フェリーから見上げると圧倒的な迫力がある。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "湯之平展望所：一般開放されている最高地点", level: 2 },
      { type: "text", content: "桜島の湯之平展望所（標高373m）は観光客が入れる最高地点だ。眼下に桜島の溶岩原が広がり、遠くに鹿児島市街と錦江湾が見える。噴煙が活発な日は展望所の目の前に黒煙が流れることもある。駐車場からの徒歩5分のアクセスで、車があれば島内観光の必訪スポットだ。" },
      { type: "heading", content: "桜島大根と桜島小みかん：火山灰土壌が生む奇跡の作物", level: 2 },
      { type: "text", content: "桜島大根は直径30〜40cmにもなる世界最大級の大根で、火山灰土壌の栄養を吸収して育つ。桜島小みかんは直径3cm前後の世界最小クラスのみかんで、皮が薄く甘い。両方とも桜島フェリーターミナル近くの直売所で購入でき、鹿児島では最上の土産物のひとつだ。" },
    ],
    relatedArticleSlugs: ["kagoshima-ibusuki-sand-bath", "kagoshima-sengan-en-garden"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "kagoshima-yakushima-trekking",
    title: "屋久島トレッキング完全ガイド──縄文杉への10時間を安全に歩くための全ての準備",
    description: "縄文杉は片道5時間のトレッキングの先にある。雨の屋久島で安全に歩くための装備・ガイド選び・体力目安を全て伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagoshima",
    tags: ["屋久島", "縄文杉", "トレッキング", "世界遺産", "鹿児島"],
    spotIds: ["yakushima"],
    sections: [
      { type: "heading", content: "縄文杉コースの実態：往復22km・標高差600m・体力目安", level: 2 },
      { type: "text", content: "縄文杉への往復は約22km・所要10〜12時間だ。序盤の9kmはトロッコ道（平坦な廃線跡）、その先は登山道になる。最大の体力消費は後半の急登と帰路の長さだ。20〜40代の普通の体力であれば日帰りは可能だが、翌日全身筋肉痛になるほどの運動量を想定しておくこと。前日宿泊の屋久島入りと、翌日の回復日を旅程に組み込むのが正解。" },
      { type: "spot-card", content: "yakushima" },
      { type: "heading", content: "ガイドを雇う理由：雨と霧の屋久島での道迷い防止", level: 2 },
      { type: "text", content: "屋久島は「月に35日雨が降る」と言われる多雨地帯だ。登山道は整備されているが、霧が出ると視界が悪くなる。公認ガイド（¥10,000〜¥15,000/日）は緊急時の対応・コース変更判断・安全装備の指導が含まれており、単独行動より遥かに安全だ。ガイドは屋久島観光センターまたは各ガイド会社に事前予約する。" },
      { type: "heading", content: "白谷雲水峡：半日で「もののけ姫の森」に入る", level: 2 },
      { type: "text", content: "縄文杉が「本命」なら、白谷雲水峡は「入門コース」だ。苔むした巨岩と屋久杉の原生林が3〜4時間のルートで体験できる。アニメ「もののけ姫」の舞台モデルとして有名で、雨上がりの霧が林を漂う景色は映像の世界そのものだ。縄文杉トレッキングの前日に白谷雲水峡で体を慣らすのが理想的な順序。" },
    ],
    relatedArticleSlugs: ["kagoshima-sakurajima-morning", "kagoshima-ibusuki-sand-bath"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "kagoshima-ibusuki-sand-bath",
    title: "指宿温泉の砂むし風呂──10分間砂に埋められると何が起きるのか",
    description: "砂むし温泉は温泉ではなく「砂に埋まる体験」だ。海岸の地熱で温められた砂の中で10分間過ごした後の解放感と爽快感を語る。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-02-08",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "kagoshima",
    tags: ["指宿温泉", "砂むし風呂", "砂楽", "薩摩", "鹿児島"],
    spotIds: ["ibusuki-onsen"],
    sections: [
      { type: "heading", content: "砂むし温泉の正式手順：浴衣に着替えて海岸へ", level: 2 },
      { type: "text", content: "指宿温泉の市営砂むし会館「砂楽」（¥1,500）が最もアクセスが良い。入口で浴衣を借り、着替えて砂浜へ。仲居さんが温泉で温まった砂を全身にかけてくれる。頭部と首だけが露出した状態で10〜15分間横たわる。砂の重みと熱が全身を包み、大量発汗する。終わったら温泉で砂を洗い流す。入浴後は驚くほどぐっすり眠れる。" },
      { type: "spot-card", content: "ibusuki-onsen" },
      { type: "heading", content: "砂むし温泉の効能：サウナより深い体温上昇", level: 2 },
      { type: "text", content: "砂むし温泉は砂の重み（約50〜60kg分）が全身に圧力をかけながら加温するため、サウナより体の深部まで温まると言われる。体温が1〜1.5度上昇し、代謝が促進される。入浴後に温泉で流してから水分を補給すると、体が軽くなる感覚がある。鹿児島市内から観光バスで日帰りできる距離なので、1日ツアーに組み込みやすい。" },
      { type: "heading", content: "池田湖と開聞岳：指宿エリアの周辺観光", level: 2 },
      { type: "text", content: "指宿温泉から車で20分の池田湖は九州最大のカルデラ湖で、湖畔から見る開聞岳（「薩摩富士」・標高924m）が完璧な円錐形で美しい。日本最大のウナギが生息するという「イッシー伝説」もある。湖畔の菜の花（1〜2月）と開聞岳の組み合わせは南九州の代表的な春景色だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-sakurajima-morning", "kagoshima-sengan-en-garden"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "kagoshima-sengan-en-garden",
    title: "仙巌園の「借景」──桜島を庭の一部にした薩摩藩の大名庭園で感じる圧倒的なスケール",
    description: "仙巌園は「借景」の手法で桜島を庭に組み込んだ。365日、庭のどこに立っても桜島が見えるという設計の天才性を語る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-02-22",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagoshima",
    tags: ["仙巌園", "借景", "桜島", "薩摩藩", "鹿児島"],
    spotIds: ["sengan-en"],
    sections: [
      { type: "heading", content: "借景の桜島：庭に入った瞬間の「開ける」感覚", level: 2 },
      { type: "text", content: "仙巌園の入口を入った瞬間、錦江湾越しに桜島が正面に広がる。これが「借景」の技法で、庭の中に自然の景物を「借りる」日本庭園の最高峰の表現だ。庭の石組み・池・樹木の全てが桜島を見せるための演出として機能している。どの位置に立っても桜島が見える配置は、1658年の設計時から変わっていない。" },
      { type: "spot-card", content: "sengan-en" },
      { type: "heading", content: "世界遺産「明治日本の産業革命遺産」の構成資産", level: 2 },
      { type: "text", content: "仙巌園は「明治日本の産業革命遺産」（2015年世界遺産登録）の構成資産のひとつだ。島津斉彬が設立した集成館（日本最古の機械工場跡）が庭内にあり、明治維新の礎となった近代化の実験が行われた場所だ。反射炉跡（西洋式鉄製大砲の鋳造施設）も残り、徳川幕府に対抗するための薩摩の近代化の痕跡が読める。" },
      { type: "heading", content: "薩摩切子の体験：島津家が育てた赤と青のガラス工芸", level: 2 },
      { type: "text", content: "仙巌園内の薩摩切子ガラス館では、薩摩切子（島津家が育てた江戸切子と並ぶ日本二大カットガラス）の実演と購入ができる。赤と青の「ぼかし」が特徴の薩摩切子は、廃藩置県で一度途絶した後に復元された工芸品だ。体験工房（¥3,000〜）では自分でグラスを削る体験ができ、土産物として持ち帰れる。" },
    ],
    relatedArticleSlugs: ["kagoshima-sakurajima-morning", "kagoshima-kirishima-shrine"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "kagoshima-kirishima-shrine",
    title: "霧島神宮の杉並木と御神木──坂本龍馬が新婚旅行で来た鹿児島の古社",
    description: "霧島神宮は天孫降臨の地だ。1200年以上前から山中に鎮まる神社の、朝霧の中の杉並木と御神木の存在感を語る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagoshima",
    tags: ["霧島神宮", "天孫降臨", "杉並木", "坂本龍馬", "鹿児島"],
    spotIds: ["sakurajima"],
    sections: [
      { type: "heading", content: "霧島神宮の朝霧：雲がかかる山の神社の別格感", level: 2 },
      { type: "text", content: "霧島神宮（標高約700m）は霧島山（韓国岳）の中腹に鎮まる古社だ。名前の通り「霧島」は常に霧に包まれる山で、早朝は杉並木から白い霧が漂う。参道の大杉（樹齢800年超）が並ぶ石段を霧の中に登ると、平地の神社とは全く異なる空気の重さがある。早朝6〜7時の参拝が最も神秘的だ。" },
      { type: "heading", content: "龍馬・お龍の新婚旅行の地：日本初の新婚旅行", level: 2 },
      { type: "text", content: "坂本龍馬は1866年に妻・お龍と霧島温泉に旅した。これが「日本初の新婚旅行」とされる。寺田屋事件で傷を負った龍馬が療養を兼ねて来た旅だが、お龍と共に霧島の山を登り、地元の温泉に入ったことが記録に残る。龍馬が訪れた霧島神宮と塩浸温泉（現・龍馬とお龍の新婚湯）は、幕末の空気を感じるスポットだ。" },
      { type: "heading", content: "霧島温泉郷：硫黄泉から重曹泉まで、泉質の多様さ", level: 2 },
      { type: "text", content: "霧島温泉郷は霧島神宮から車で10〜20分圏内に「丸尾温泉」「硫黄谷温泉」「林田温泉」など複数の源泉が集まる。泉質は硫黄泉・炭酸水素塩泉・塩化物泉と多様だ。丸尾の滝（霧島の滝）は岩肌を温泉成分が染めた褐色の滝で、周囲から硫黄の香りが漂う珍しい温泉瀑布だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-sengan-en-garden", "kagoshima-sakurajima-morning"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "kagoshima-kurobuta-black-pig",
    title: "鹿児島の黒豚──六白黒豚と薩摩黒豚の違いと、最高の食べ方は「しゃぶしゃぶ」か「とんかつ」か",
    description: "鹿児島の黒豚は全国ブランドだが、種類と食べ方の違いを知ると別の食べ物になる。一番旨い黒豚の食べ方を現地の知識で語る。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagoshima",
    tags: ["鹿児島黒豚", "六白黒豚", "しゃぶしゃぶ", "とんかつ", "鹿児島"],
    spotIds: ["sakurajima"],
    sections: [
      { type: "heading", content: "六白黒豚とは何か：6か所が白い純粋なバークシャー種", level: 2 },
      { type: "text", content: "鹿児島の「六白黒豚」は黒い体に鼻先・四肢・尾の6か所が白いバークシャー種の純粋種だ。一般の黒豚（バークシャー系交雑種）と区別するために「六白」の名称が使われる。脂の甘みと赤身の旨みのバランスが最高で、薩摩芋を食べて育つため甘みが強い。産地認証（鹿児島県の認証マーク付き）を確認して購入すること。" },
      { type: "heading", content: "黒豚しゃぶしゃぶvs.とんかつ：最高の食べ方はどちらか", level: 2 },
      { type: "text", content: "黒豚は薄切りのしゃぶしゃぶで脂の甘みを味わうのが最も素材の良さが伝わる。ポン酢より昆布塩で食べると豚の甘みが際立つ。とんかつは衣のサクサク感と肉汁の対比が楽しめるが、薄切りのしゃぶしゃぶの方が黒豚の特徴を純粋に体感できる。「黒かつ亭」（鹿児島市内）は黒豚とんかつの代表的な名店で、昼は行列が必至だ。" },
      { type: "heading", content: "黒豚のコスパ最強の食べ方：スーパーで刺身用黒豚を買う", level: 2 },
      { type: "text", content: "鹿児島市内のスーパーでは「しゃぶしゃぶ用黒豚スライス（100g¥300〜¥500）」が購入できる。旅館の部屋や宿泊先で鍋一式を用意すれば、レストランの半額以下で黒豚しゃぶしゃぶが食べられる。道の駅「川辺やすらぎの里」や「鹿児島中央駅のみやげ横丁」でも産地認証の黒豚が購入できる。" },
    ],
    relatedArticleSlugs: ["kagoshima-shirokuma-kakigori", "kagoshima-shochu-guide"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "kagoshima-shirokuma-kakigori",
    title: "白熊かき氷とは何か──天文館むじゃきが生んだ、鹿児島でしか食べられない巨大かき氷",
    description: "白熊は単なるかき氷ではない。練乳の量とトッピングの密度が尋常ではない鹿児島の氷菓は、食べ終わるまで30分かかる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-12",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagoshima",
    tags: ["白熊", "かき氷", "天文館", "むじゃき", "鹿児島"],
    spotIds: ["sakurajima"],
    sections: [
      { type: "heading", content: "天文館むじゃきの「白熊」：1947年創業の元祖かき氷", level: 2 },
      { type: "text", content: "鹿児島の「白熊」は1947年創業の「天文館むじゃき」が生み出した氷菓だ。山盛りのかき氷に練乳を大量にかけ、小豆・フルーツ・白玉・寒天をトッピングする。顔のように見えるトッピング配置が「白熊の顔」に見えることから命名された。LLサイズは直径20cm以上あり、一人で食べ終えるには10〜15分かかる。" },
      { type: "heading", content: "夏以外でも食べる価値がある：鹿児島人の年中食文化", level: 2 },
      { type: "text", content: "鹿児島では白熊を夏限定として扱わない。温暖な気候のため年中食べられており、真冬でも店内で白熊を食べる地元民がいる。涼しい季節に食べると練乳の甘みが際立つという意見もある。天文館エリアには「むじゃき」以外にも複数の白熊提供店があり、食べ比べをするのが鹿児島通の楽しみ方だ。" },
      { type: "heading", content: "天文館：かき氷と共に鹿児島の繁華街を歩く", level: 2 },
      { type: "text", content: "天文館は鹿児島市の中心商店街で、白熊・黒豚料理・薩摩揚げ・薩摩焼酎が集まる鹿児島グルメの台所だ。アーケード街の路地には老舗から新店まで多様な食の選択肢がある。鹿児島市電（路面電車）で天文館電停下車後、1〜2時間かけて食べ歩きするのが鹿児島の正しい過ごし方だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-kurobuta-black-pig", "kagoshima-shochu-guide"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "kagoshima-shochu-guide",
    title: "薩摩焼酎の世界──芋焼酎の故郷で飲む「本場」の味と、蔵元巡りの正しい楽しみ方",
    description: "薩摩焼酎は全国の芋焼酎の中で唯一GI（地理的表示）認定を受けた最高峰だ。サツマイモと鹿児島の水が生む独自の香りの世界に入る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-28",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagoshima",
    tags: ["薩摩焼酎", "芋焼酎", "蔵元", "GI", "鹿児島"],
    spotIds: ["sengan-en"],
    sections: [
      { type: "heading", content: "薩摩焼酎のGI認定：鹿児島県内産サツマイモと水だけ", level: 2 },
      { type: "text", content: "「薩摩焼酎」は2005年に国税庁の地理的表示（GI）に指定された。指定要件は「鹿児島県（奄美大島を除く）産のサツマイモを原料とし、鹿児島県内で製造」すること。全国の芋焼酎がGI「薩摩焼酎」を名乗れるわけではない。代表銘柄は「薩摩宝山」「三岳」「久耀（きゅうよう）」「蔵の師匠」など。" },
      { type: "spot-card", content: "sengan-en" },
      { type: "heading", content: "芋焼酎の飲み方：お湯割りで芋の香りが開花する", level: 2 },
      { type: "text", content: "薩摩焼酎の最もポピュラーな飲み方は「お湯割り（6:4）」だ。先にお湯を入れてから焼酎を注ぐ（逆にすると対流が起きない）。芋の甘い香りがお湯の熱で開き、柔らかい味わいになる。冬の鹿児島で黒豚しゃぶしゃぶと芋焼酎お湯割りの組み合わせは、鹿児島旅行の最高の食体験だ。" },
      { type: "heading", content: "蔵元見学：薩摩宝山醸造所と三岳酒造（屋久島）", level: 2 },
      { type: "text", content: "鹿児島市近郊の「西酒造（薩摩宝山）」では事前予約で蔵内見学が可能だ。仕込み蔵の中に入ると、サツマイモが発酵する独特の甘い香りが充満している。屋久島の「三岳酒造」は屋久島の天然水と自社栽培の芋で作る限定生産の焼酎で、島外に出回りにくいため現地購入が最高の手段だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-kurobuta-black-pig", "kagoshima-shirokuma-kakigori"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "kagoshima-amami-oshima",
    title: "奄美大島の海と森──鹿児島県内で最もハードルが高く、最も報われる離島の旅",
    description: "奄美大島は鹿児島空港から飛行機60分だが、別の国に着いたような動植物と文化がある。マングローブ林・ケンムン・黒糖焼酎の世界へ。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kagoshima",
    tags: ["奄美大島", "マングローブ", "黒糖焼酎", "世界遺産", "鹿児島"],
    spotIds: ["yakushima"],
    sections: [
      { type: "heading", content: "奄美大島の世界遺産：固有種の宝庫が持つ生態系の奇跡", level: 2 },
      { type: "text", content: "奄美大島は2021年に「奄美大島、徳之島、沖縄島北部及び西表島」として世界自然遺産に登録された。アマミノクロウサギ（固有種）・ルリカケス（固有種の鳥）・オキナワトゲネズミなど絶滅危惧種が豊富に生息する。夜の林道では野生のアマミノクロウサギに出会えることがある。ガイドツアー（¥5,000〜）が最も確実な出会いの手段だ。" },
      { type: "spot-card", content: "yakushima" },
      { type: "heading", content: "住用マングローブ：日本三大マングローブのカヤック体験", level: 2 },
      { type: "text", content: "奄美市住用の「住用マングローブパーク」は日本三大マングローブのひとつだ。カヤックで河口のマングローブ林の中を漕ぐツアー（¥3,000〜）は、亜熱帯の森の中に入り込む体験だ。干潮時はマングローブの根が地面から露出して歩けるエリアが生まれる。ムツゴロウが干潟を歩く様子も見られる。" },
      { type: "heading", content: "奄美の黒糖焼酎：奄美にしか作れない焼酎の世界", level: 2 },
      { type: "text", content: "奄美大島の黒糖焼酎は奄美群島（奄美大島・喜界島・徳之島・沖永良部島・与論島）でのみ製造が許可された焼酎だ。黒糖（さとうきびの黒い砂糖）を原料とし、ラム酒に近いフルーティさと焼酎の蒸留感が同居する独自の風味を持つ。代表銘柄「龍宮」「里の曙」は奄美の食堂や居酒屋で現地価格で飲める。" },
    ],
    relatedArticleSlugs: ["kagoshima-yakushima-trekking", "kagoshima-sakurajima-morning"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "kagoshima-model-course-2days",
    title: "鹿児島2日間モデルコース──桜島・仙巌園・指宿を完全制覇する黄金ルート",
    description: "鹿児島の主要スポットは車があれば2日間で全部回れる。桜島フェリー・仙巌園・指宿砂むしを繋ぐ最適な順路と時間配分を提案する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kagoshima",
    tags: ["鹿児島モデルコース", "2日間", "桜島", "指宿", "鹿児島"],
    spotIds: ["sakurajima", "sengan-en", "ibusuki-onsen"],
    sections: [
      { type: "heading", content: "1日目：桜島と仙巌園で鹿児島の「自然と歴史」を制覇", level: 2 },
      { type: "text", content: "鹿児島空港着→市内へ（バス50分）→仙巌園（2時間・世界遺産・¥1,500）→昼食：仙巌園レストランの薩摩料理セット→桜島フェリー（¥200）→桜島島内一周（レンタサイクルか車）→湯之平展望所→桜島の足湯→夕方フェリーで戻る→天文館で夕食（黒豚・白熊）。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "2日目：指宿温泉で砂むし体験と南薩の絶景", level: 2 },
      { type: "text", content: "朝8時出発→指宿市（車で1時間）→砂むし会館「砂楽」（9時〜・¥1,500）→池田湖と開聞岳の展望（1時間）→昼食：指宿市内の鰹とビンナガまぐろの漁師定食（¥1,200）→鹿児島市へ戻り→霧島神宮（時間があれば）→空港へ。" },
      { type: "heading", content: "2日間の費用目安と移動手段", level: 2 },
      { type: "text", content: "2日間の費用目安：レンタカー（1日¥3,500〜）×2日・ガソリン¥2,000・主要入場料¥5,000・食費¥6,000・宿泊¥10,000〜（市内ビジネスホテル）。合計¥30,000〜¥40,000（飛行機代別）。公共交通でも桜島・仙巌園は路面電車とフェリーで回れるが、指宿方面は指宿枕崎線が便利だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-sakurajima-morning", "kagoshima-ibusuki-sand-bath"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "kagoshima-family-travel",
    title: "鹿児島の家族旅行プラン──子どもが喜ぶ桜島・平川動物公園・砂むし体験の2泊3日",
    description: "鹿児島は子どもへのインパクトが強い場所だ。噴火する火山・砂に埋まる体験・触れ合える動物。2泊3日の家族旅を全部組み込む計画を立てる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "kagoshima",
    tags: ["鹿児島家族旅行", "子連れ旅", "桜島", "平川動物公園", "鹿児島"],
    spotIds: ["sakurajima", "ibusuki-onsen"],
    sections: [
      { type: "heading", content: "1日目：鹿児島市内と桜島で火山を体感", level: 2 },
      { type: "text", content: "鹿児島中央駅→市電で天文館→白熊かき氷（子どもが大喜び）→桜島フェリー（子どもはフェリーに乗るだけで楽しい）→桜島の溶岩原散策→桜島ビジターセンターで噴火の仕組みを学ぶ（無料）→夕方戻り→黒豚とんかつ夕食→市内ホテル泊。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "2日目：平川動物公園でコアラに会う", level: 2 },
      { type: "text", content: "平川動物公園（¥500・子ども¥100）は日本最南端の大型動物公園でコアラを飼育している数少ない動物園のひとつだ。チンパンジーの島（池に囲まれた島にチンパンジーが自由に暮らす）は子どもに人気。午後に指宿温泉へ移動→砂むし会館で砂むし体験（子どもは砂に入ることを楽しがる）→指宿の旅館泊。" },
      { type: "heading", content: "3日目：池田湖と開聞岳で南薩の自然を満喫", level: 2 },
      { type: "text", content: "池田湖の湖畔散策（イッシー伝説を子どもに話す）→開聞岳の麓から山を見上げる→鹿児島空港へ帰路。子どもが最も印象に残るのは白熊かき氷か砂むしか桜島フェリーかは個人差があるが、どれも大人が予想する以上に子どもの記憶に強く残る体験だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-sakurajima-morning", "kagoshima-ibusuki-sand-bath"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "kagoshima-couple-travel",
    title: "鹿児島カップル旅の完全版──桜島・霧島温泉・砂むし風呂で2泊3日のロマンチック旅",
    description: "鹿児島の自然のスケールは2人旅に広がりを与える。活火山・神社・秘湯が連なる鹿児島で、思い出に残る旅を設計する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kagoshima",
    tags: ["鹿児島カップル旅", "霧島温泉", "砂むし風呂", "2泊3日", "鹿児島"],
    spotIds: ["sakurajima", "ibusuki-onsen"],
    sections: [
      { type: "heading", content: "1日目：鹿児島市内と夕焼けの桜島で旅を開幕", level: 2 },
      { type: "text", content: "鹿児島到着→仙巌園（借景の桜島を2人で眺める）→夕方にフェリーで桜島へ→桜島の足湯で夕日を見ながら休憩→フェリーで戻る（夕焼けの桜島と錦江湾を船上から見る）→天文館の黒豚しゃぶしゃぶ専門店で夕食→市内のホテル泊。" },
      { type: "spot-card", content: "ibusuki-onsen" },
      { type: "heading", content: "2日目：霧島神宮と霧島温泉で「神社とパワースポット」の旅", level: 2 },
      { type: "text", content: "霧島神宮→境内の大杉の前で写真撮影→丸尾の滝（褐色の温泉瀑布）→霧島温泉郷の旅館にチェックイン→温泉でゆっくり→夕食は旅館の会席料理（薩摩地鶏・黒豚・きびなご料理）→夜は露天風呂から霧島の夜空を眺める。" },
      { type: "heading", content: "3日目：指宿で砂に2人並んで埋まる", level: 2 },
      { type: "text", content: "霧島温泉から指宿へ（車で約1時間30分）→砂楽で2人並んで砂むし体験（横に並んで入浴できる）→池田湖の湖畔ランチ→開聞岳を眺めながらドライブ→鹿児島空港へ帰路。砂から出た後の「軽くなった感覚」を2人で確認し合うのが指宿旅の定番の会話だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-ibusuki-sand-bath", "kagoshima-kirishima-shrine"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "kagoshima-budget-travel",
    title: "鹿児島2泊3日・予算2万5,000円──薩摩の全てを節約旅で完全に楽しむ方法",
    description: "鹿児島はLCCと路面電車とスーパーの黒豚を使えば2泊3日2万5,000円で桜島・仙巌園・指宿を全部回れる。具体的な費用内訳を全て開示する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "kagoshima",
    tags: ["鹿児島節約旅", "2泊3日", "予算旅行", "バジェット", "鹿児島"],
    spotIds: ["sakurajima", "sengan-en"],
    sections: [
      { type: "heading", content: "交通費の最適化：路面電車1日乗り放題と桜島フェリー", level: 2 },
      { type: "text", content: "鹿児島市内の路面電車1日乗り放題（¥600）で仙巌園・天文館・鹿児島中央駅のエリアを全て移動できる。桜島フェリーは¥200で往復¥400。指宿への移動はJR指宿枕崎線（¥1,110）が最安値。2泊3日の公共交通費は飛行機代（LCC早割¥8,000〜）を除いて¥3,000〜¥5,000で収まる。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "宿泊費の最適化：鹿児島中央駅周辺のビジネスホテル", level: 2 },
      { type: "text", content: "鹿児島中央駅周辺のビジネスホテルは¥4,500〜¥6,000/泊で多数の選択肢がある。「ルートイン鹿児島中央駅前」「コートホテル鹿児島」が評判が安定している。2泊¥10,000〜¥12,000が節約旅の宿泊費の目安だ。" },
      { type: "heading", content: "食費の最適化：スーパーの黒豚と天文館の定食屋", level: 2 },
      { type: "text", content: "鹿児島市内の「タイヨー」「ニシムタ」などのスーパーでは産地認証黒豚の薄切り（¥400〜¥600）が購入できる。夕食は天文館の薩摩料理定食（¥900〜¥1,300）が最高コスパ。指宿の砂むしは市営「砂楽」が¥1,500で最安値。3日間の食費合計¥6,000は十分可能だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-model-course-2days", "kagoshima-sakurajima-morning"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "kagoshima-luxury-travel",
    title: "鹿児島の贅沢な旅──屋久島の高級ロッジと指宿の老舗旅館で薩摩を「深く」体験する",
    description: "鹿児島を贅沢に旅すると、屋久杉の森の高級ロッジと砂むし露天風呂付き客室という選択肢がある。贅沢旅でしか得られない鹿児島の顔を語る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kagoshima",
    tags: ["鹿児島贅沢旅", "屋久島", "高級旅館", "指宿", "鹿児島"],
    spotIds: ["yakushima", "ibusuki-onsen"],
    sections: [
      { type: "heading", content: "屋久島の高級ロッジ：縄文杉の森の中に泊まる", level: 2 },
      { type: "text", content: "屋久島の高級宿「縄文の宿 まんてん」や「山岳ホテル縄文の宿」は、屋久杉の森に囲まれた立地に建ち、敷地内に源泉温泉を持つ。1泊2食30,000円〜。夜に宿の周囲の森に入ると屋久鹿・ヤクザルに出会える可能性がある。縄文杉トレッキング前夜の宿泊として使うと、翌朝の出発が最短時間で可能だ。" },
      { type: "spot-card", content: "ibusuki-onsen" },
      { type: "heading", content: "指宿の老舗旅館「いわさきホテル指宿」：砂むし付き客室", level: 2 },
      { type: "text", content: "指宿の高級旅館「いわさきホテル指宿」は錦江湾と開聞岳を望む絶景の立地に建ち、旅館専属の砂むし温泉設備を持つ。1泊2食35,000円〜。旅館の砂むしは混雑する公共施設より予約が取りやすく、砂むし後にそのまま露天風呂に直行できる動線が完璧だ。夕食の薩摩の食材を使った会席料理は鹿児島の食文化の集大成だ。" },
      { type: "heading", content: "仙巌園のプライベートガイドツアー：世界遺産を深く読む", level: 2 },
      { type: "text", content: "仙巌園では事前予約でプライベートガイドツアー（¥5,000〜）を手配できる。通常の見学では見落とすような集成館の機械跡・薩摩切子の制作工程・島津家の歴史をガイドと2人で深掘りする体験は、グループツアーでは不可能な密度を持つ。鹿児島を「歴史の読み物」として旅するための最高の手段だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-yakushima-trekking", "kagoshima-ibusuki-sand-bath"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "kagoshima-spring-seasonal",
    title: "鹿児島の春──桜島の桜と菜の花と開聞岳、南九州の早い春を楽しむ旅",
    description: "鹿児島の春は1月から始まる。日本で最も早い桜（指宿の寒緋桜）と菜の花と開聞岳が重なる景色は、鹿児島でしか撮れない春の写真だ。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-01-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kagoshima",
    tags: ["鹿児島の春", "寒緋桜", "菜の花", "開聞岳", "鹿児島"],
    spotIds: ["ibusuki-onsen", "sakurajima"],
    sections: [
      { type: "heading", content: "指宿の「菜の花マーチ」と開聞岳：1月下旬〜2月の圧巻の景色", level: 2 },
      { type: "text", content: "指宿市の長崎鼻付近では1月下旬〜2月に菜の花が開花し、黄色い花畑と開聞岳（薩摩富士）の対比が美しい。毎年1月に行われる「指宿菜の花マーチ」のコース沿いに菜の花が咲き、ウォーキング参加者と観光客が同時に訪れる。砂むし体験とのセット旅行が最高の組み合わせだ。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "鹿児島の寒緋桜：本土より1ヶ月以上早い南国の春", level: 2 },
      { type: "text", content: "鹿児島では寒緋桜（カンヒザクラ）という濃いピンクの早咲き品種が1月〜2月に開花する。指宿市の「ふれあいパーク霧島」や鹿児島市内の各公園で見られる。ソメイヨシノより色が濃く、南国らしい鮮やかさがある。桜島を背景に寒緋桜を撮る構図は鹿児島の春の代表的な1枚だ。" },
      { type: "heading", content: "霧島神宮の春：ミヤマキリシマと神社の組み合わせ", level: 2 },
      { type: "text", content: "霧島山（えびの高原）では5月〜6月にミヤマキリシマが開花する。霧島神宮参道の周囲にも山ツツジが咲き、新緑と神社の朱色が春の色彩を作る。鹿児島の春は1月の菜の花から6月のミヤマキリシマまで長い期間楽しめる。どの季節に来ても「咲いている花がある」のが温暖な鹿児島の強みだ。" },
    ],
    relatedArticleSlugs: ["kagoshima-ibusuki-sand-bath", "kagoshima-kirishima-shrine"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "kagoshima-summer-travel",
    title: "鹿児島の夏旅行──屋久島・奄美大島・種子島で楽しむ7月8月の離島天国",
    description: "鹿児島の夏は離島が主役だ。世界遺産の屋久島、透明な海の奄美大島、ロケット打ち上げの種子島。3つの島で夏の全てが揃う。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kagoshima",
    tags: ["鹿児島の夏", "屋久島", "奄美大島", "種子島", "鹿児島"],
    spotIds: ["yakushima"],
    sections: [
      { type: "heading", content: "屋久島の夏：ウミガメの産卵と縄文杉の緑", level: 2 },
      { type: "text", content: "7〜9月は屋久島の浜辺でアカウミガメの産卵が見られる時期だ（予約必須のナイトツアー）。縄文杉トレッキングも夏がベストシーズンで、新緑の屋久杉林が最も美しい緑を見せる。雨が多いが雨上がりの森は霧に包まれて幻想的だ。夏の屋久島は梅雨明け（7月上旬）から8月が最もコンディションが良い。" },
      { type: "spot-card", content: "yakushima" },
      { type: "heading", content: "奄美大島の夏：珊瑚礁とケラマブルーに勝る透明度", level: 2 },
      { type: "text", content: "奄美大島の海は沖縄に匹敵する透明度を持つ。波布（ハブ）に注意しながらの海水浴が必要だが、シュノーケリングツアー（¥5,000〜）では熱帯魚とサンゴを間近で見られる。土盛（ともり）海岸はハートロックが有名なビーチで、エメラルドブルーの海と黒いハートロックのコントラストが奄美の代表的な景観だ。" },
      { type: "heading", content: "種子島の夏：種子島宇宙センターとサーフィン", level: 2 },
      { type: "text", content: "種子島は「宇宙の島」として知られ、JAXAの種子島宇宙センター（日本最大のロケット射場）がある。宇宙センターの無料見学（要事前予約）ではロケット発射台を間近で見られる。ロケット打ち上げ日に合わせて旅程を組むと（年数回）、宇宙に最も近い体験ができる。西之浜・島間のサーフポイントは全国から波乗りファンが集まる。" },
    ],
    relatedArticleSlugs: ["kagoshima-amami-oshima", "kagoshima-yakushima-trekking"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "kagoshima-photography-spots",
    title: "鹿児島の絶景撮影スポット──桜島の噴煙・仙巌園の借景・指宿の菜の花を撮る技術",
    description: "鹿児島は「動く被写体（噴火）」がある世界唯一の撮影地だ。写真愛好家が鹿児島で失敗しないための設定・時間帯・場所の全情報。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagoshima",
    tags: ["鹿児島撮影", "桜島噴煙", "写真スポット", "絶景", "鹿児島"],
    spotIds: ["sakurajima", "sengan-en"],
    sections: [
      { type: "heading", content: "桜島の噴煙撮影：噴火のタイミングと超望遠の組み合わせ", level: 2 },
      { type: "text", content: "桜島の噴火はほぼ毎日起きるが時間は不規則だ。鹿児島地方気象台のウェブサイトで「噴火情報」をリアルタイム確認できる。噴火直後の黒煙は3〜5分で広がるため、噴火情報が出たら即座に撮影ポジションに向かう。望遠レンズ（300mm以上）で噴煙のテクスチャを切り取るか、広角で錦江湾と市街を含めて全体構図を作るかを事前に決めておく。" },
      { type: "spot-card", content: "sengan-en" },
      { type: "heading", content: "仙巌園の撮影：桜島が正面に入る構図の作り方", level: 2 },
      { type: "text", content: "仙巌園内で最も撮影者が集まる場所は「御殿前の庭」と「海岸沿いの回廊」だ。御殿前は錦江湾と桜島を横位置でバランスよく収める構図ができる。海岸沿いの回廊からは桜島が正面に見え、廊下の奥行きを使った「フレーム内フレーム」構図が可能だ。午前中は桜島に光が当たり、午後は逆光になるため午前中の撮影が推奨だ。" },
      { type: "heading", content: "指宿・菜の花×開聞岳：日本の春の完璧な構図", level: 2 },
      { type: "text", content: "長崎鼻の菜の花畑と開聞岳の撮影は、南向きの菜の花畑（東寄り）から開聞岳を収める構図がベストだ。快晴の日は開聞岳の稜線がシャープに見える。早朝7〜8時の柔らかい光が菜の花の黄色を最も鮮やかに表現する。広角（24mm）で前景の菜の花を大きく入れ、奥に小さく開聞岳を配置するのが黄金の構図だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-sakurajima-morning", "kagoshima-ibusuki-sand-bath"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "kagoshima-solo-travel",
    title: "鹿児島一人旅の正解──薩摩焼酎を飲みながら桜島を眺める、一人でこそ深まる旅",
    description: "鹿児島は一人でいる時間が最も濃くなる場所だ。噴煙と向き合い、温泉に沈み、焼酎を飲む——誰かと一緒だと気が散る体験が鹿児島に集まっている。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kagoshima",
    tags: ["鹿児島一人旅", "薩摩焼酎", "桜島", "温泉一人旅", "鹿児島"],
    spotIds: ["sakurajima", "sengan-en", "ibusuki-onsen"],
    sections: [
      { type: "heading", content: "1日目：桜島に一人で渡り、足湯で焼酎を飲む", level: 2 },
      { type: "text", content: "鹿児島着→天文館で白熊かき氷（一人で食べきれる「小」サイズ）→桜島フェリーで島へ→湯之平展望所→桜島溶岩なぎさ公園の長い足湯（160mある無料の足湯）で薩摩焼酎の小瓶を開ける（フェリーターミナルで購入）→噴煙を眺めながら一杯→仙巌園→市内ホテル泊。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "2日目：指宿温泉で砂に一人で埋まる", level: 2 },
      { type: "text", content: "朝8時出発→指宿砂楽→砂に一人で埋まる（一人の方が砂の重さをより鮮明に感じる）→温泉で流す→池田湖→開聞岳を見ながら昼食→霧島神宮への立ち寄り（時間があれば）→鹿児島市内へ戻り→夕食はカウンター席の薩摩料理専門店で芋焼酎お湯割り→ホテル泊。" },
      { type: "heading", content: "3日目：屋久島への日帰り高速船という選択肢", level: 2 },
      { type: "text", content: "時間に余裕があれば3日目に鹿児島港から高速船（約1時間）で屋久島へ日帰りの白谷雲水峡ハイキングが可能だ。午前便で渡り、白谷雲水峡を3時間歩き、午後便で戻る。日帰りでも屋久杉の森の「別世界感」は十分伝わる。一人旅の3日目のサプライズとして最高の選択肢だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-yakushima-trekking", "kagoshima-shochu-guide"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "kagoshima-autumn-travel",
    title: "鹿児島の秋──霧島温泉の紅葉と芋焼酎の仕込み時期に重なる、秋旅の最高条件",
    description: "鹿児島の秋は霧島山の紅葉と薩摩焼酎の新酒（仕込み時期）が重なる特別な季節だ。10月〜11月の鹿児島旅行の全てのポイントを伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kagoshima",
    tags: ["鹿児島の秋", "霧島の紅葉", "薩摩焼酎新酒", "秋旅行", "鹿児島"],
    spotIds: ["sakurajima", "ibusuki-onsen"],
    sections: [
      { type: "heading", content: "霧島山の紅葉：10月中旬〜11月中旬が見頃", level: 2 },
      { type: "text", content: "霧島山（えびの高原・韓国岳周辺）の紅葉は10月中旬〜11月中旬が最盛期だ。えびの高原の池沿いを歩くと、ドウダンツツジとナナカマドの紅葉が一面に広がる。霧島神宮の参道は11月上旬に紅葉が最高潮になり、朱色の鳥居と紅葉の対比が美しい。霧島温泉郷から見る紅葉の山は、温泉の湯けむりと重なって幻想的な秋景色になる。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "芋焼酎の仕込み時期：9〜11月の蔵元が最も活気づく", level: 2 },
      { type: "text", content: "薩摩焼酎の芋の収穫は9〜11月で、この時期が仕込み（1次発酵・2次発酵）の最盛期だ。蔵元見学の申込は夏の終わりに入れ、仕込み中の蔵の甘い発酵の香りを直接体験する。「できたて新酒（しぼりたて）」を仕込み後すぐ飲める機会は蔵元直営店のみで、秋に鹿児島に来る理由のひとつになる。" },
      { type: "heading", content: "桜島の秋：大根の季節と紅葉の組み合わせ", level: 2 },
      { type: "text", content: "桜島大根の収穫は10〜12月。この時期に桜島を訪れると、畑一面に桜島大根が育っている様子が見られる。溶岩原の黒い地面から巨大な大根が生えている景色は、火山と農業の共存という別府ではない鹿児島のリアルな姿だ。直売所で桜島大根の漬物（¥500）と桜島小みかん（¥300）を買うのが秋の桜島土産の正解だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-kirishima-shrine", "kagoshima-shochu-guide"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "kagoshima-gourmet-complete",
    title: "鹿児島グルメ完全ガイド──黒豚・白熊・きびなご・薩摩揚げ・芋焼酎を1泊2日で全部食べる",
    description: "鹿児島のグルメは多様で濃い。黒豚しゃぶしゃぶから白熊かき氷まで、1泊2日で鹿児島の食を全部体験する最適なルートを組み立てる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kagoshima",
    tags: ["鹿児島グルメ", "きびなご", "薩摩揚げ", "黒豚", "鹿児島"],
    spotIds: ["sakurajima", "sengan-en"],
    sections: [
      { type: "heading", content: "きびなご：鹿児島の海が育てた銀色の宝石", level: 2 },
      { type: "text", content: "きびなごは鹿児島沿岸で捕れる小型の青魚で、刺身・南蛮漬け・干物が代表的な食べ方だ。生きたまま薄造りにするきびなごの刺身は透明感があり、酢味噌またはポン酢で食べる。きびなごの刺身は鮮度の落ちが早いため、産地の鹿児島でしか食べられない。天文館の居酒屋では必ず注文すべき一皿だ。" },
      { type: "spot-card", content: "sakurajima" },
      { type: "heading", content: "薩摩揚げ（つけ揚げ）：スーパーの惣菜が最高コスパ", level: 2 },
      { type: "text", content: "薩摩揚げは鹿児島では「つけ揚げ」と呼ばれる。魚のすり身に豆腐・野菜・砂糖を加えて揚げた鹿児島の郷土料理だ。砂糖を加えるため甘みがあるのが特徴で、全国の薩摩揚げとは全く違う。スーパーで揚げたてを¥100前後で購入できる。仙巌園近くの薩摩揚げ専門店「中万（なかまん）」の手作り品が最高峰。" },
      { type: "heading", content: "1泊2日の鹿児島グルメ全制覇プラン", level: 2 },
      { type: "text", content: "1日目：昼に天文館で白熊（¥700）→仙巌園のレストランで薩摩料理定食（¥1,800）→夕食は黒豚しゃぶしゃぶ専門店（¥4,000〜）→芋焼酎お湯割りで締める。2日目：朝に地元スーパーで薩摩揚げ購入→桜島フェリー船上で桜島大根漬物→昼は指宿でカツオのたたき定食→きびなごの刺身を天文館の居酒屋で最後の夕食。" },
    ],
    relatedArticleSlugs: ["kagoshima-kurobuta-black-pig", "kagoshima-shirokuma-kakigori"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "kagoshima-satsuma-clan-history",
    title: "薩摩藩の歴史を歩く──島津家・仙巌園・集成館が語る明治維新の「本当の起点」",
    description: "明治維新は薩摩なしには起きなかった。仙巌園と集成館が物語る、島津斉彬と薩摩の近代化の物語を歴史好きのための視点で語る。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kagoshima",
    tags: ["薩摩藩", "島津家", "明治維新", "集成館", "鹿児島"],
    spotIds: ["sengan-en"],
    sections: [
      { type: "heading", content: "島津斉彬という天才：幕末日本の最も先見的な藩主", level: 2 },
      { type: "text", content: "島津斉彬（1809〜1858）は薩摩藩第11代藩主で、西洋技術の導入に最も早く取り組んだ日本の指導者だ。反射炉（鉄製大砲の鋳造）・ガラス製造・紡績・電信・写真術を幕末の鹿児島で実験・実用化した。仙巌園の集成館（後の尚古集成館）はその実験工場の跡地で、世界遺産「明治日本の産業革命遺産」の出発点だ。" },
      { type: "spot-card", content: "sengan-en" },
      { type: "heading", content: "尚古集成館：日本最古の機械工場跡の博物館", level: 2 },
      { type: "text", content: "仙巌園内の尚古集成館（旧機械工場・1865年建造）は日本最古の機械工場建物として現存する。内部は島津家の歴史・集成館事業の記録・明治近代化の資料が展示されており、見学に1〜2時間かかる。機械工場の分厚い石壁と天井の鉄製梁が当時の工場の規模を伝える。薩摩切子・薩摩焼・甲冑なども展示されている。" },
      { type: "heading", content: "薩英戦争の記録：鹿児島が燃えた1863年", level: 2 },
      { type: "text", content: "1863年、イギリス艦隊が鹿児島湾に侵入し、薩摩と英国の間で薩英戦争が起きた。集成館の近代兵器もこの戦争で使われた。戦争後、薩摩は英国と和解し、留学生を英国に送り出した。これが後の薩長同盟・明治維新の礎になった。仙巌園と集成館を歩くと、「なぜ鹿児島が明治維新を起こせたか」という問いへの答えが見えてくる。" },
    ],
    relatedArticleSlugs: ["kagoshima-sengan-en-garden", "kagoshima-kirishima-shrine"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "kagoshima-yakushima-complete",
    title: "屋久島完全旅行ガイド──トレッキング・温泉・食・宿泊の全てを最初から整理する",
    description: "屋久島への旅は準備が多い。どの季節に行くか、縄文杉か白谷か、ガイドを雇うか否か——屋久島旅行の全ての疑問に答える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kagoshima",
    tags: ["屋久島完全ガイド", "縄文杉", "白谷雲水峡", "屋久島温泉", "鹿児島"],
    spotIds: ["yakushima"],
    sections: [
      { type: "heading", content: "屋久島へのアクセス：飛行機vs高速船の選び方", level: 2 },
      { type: "text", content: "屋久島へのアクセスは「飛行機（鹿児島空港→屋久島空港・35分・¥12,000〜）」と「高速船（鹿児島港→宮之浦港・約3時間30分・¥9,000〜）」がある。飛行機は速いが席数が少なく早期購入が必須。高速船は景色が楽しめるが台風・荒天でキャンセルが多い。飛行機往路・高速船復路の組み合わせが最も効率的だ。" },
      { type: "spot-card", content: "yakushima" },
      { type: "heading", content: "2泊3日の屋久島：縄文杉+白谷雲水峡の王道コース", level: 2 },
      { type: "text", content: "1日目：島着・島内ドライブ（ヤクザル・ヤクシカに出会う）・温泉（尾之間温泉¥300）→2日目：早朝4時出発の縄文杉トレッキング（往復10〜12時間）→3日目：白谷雲水峡ハイキング（半日）・昼食後帰路。2日間の体力消費は相当なため、宿は「縄文杉ツアー翌日は疲労回復」を前提に選ぶこと。" },
      { type: "heading", content: "屋久島の食：首折れサバと屋久島ガジュマル（飲食店）", level: 2 },
      { type: "text", content: "屋久島の名物は「首折れサバ」だ。水揚げ直後に首を折って血抜きをし、鮮度を極限まで保つサバの刺身は、産地の屋久島でしか食べられない。島内の居酒屋「ガジュマル」「百邦」では首折れサバと屋久島の地魚料理が食べられる。三岳酒造の屋久島焼酎「三岳」は東京では入手困難だが島内では普通に飲める。" },
    ],
    relatedArticleSlugs: ["kagoshima-yakushima-trekking", "kagoshima-amami-oshima"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "kagoshima-winter-travel",
    title: "鹿児島の冬旅行──砂むしで温まり、黒豚しゃぶしゃぶで締める南九州の冬の正解",
    description: "鹿児島の冬は意外と寒い。だから砂むし温泉と黒豚鍋が最高においしい。12月〜2月の鹿児島で体を温め尽くす旅の設計を伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kagoshima",
    tags: ["鹿児島の冬", "砂むし冬", "黒豚鍋", "指宿温泉", "鹿児島"],
    spotIds: ["ibusuki-onsen", "sakurajima"],
    sections: [
      { type: "heading", content: "冬の砂むし温泉：寒い日が最も気持ちいい", level: 2 },
      { type: "text", content: "砂むし温泉は外気温が低い冬に最も効果が高い。砂の熱（約50〜55度）と寒い外気の対比で体温の上昇がより顕著に感じられる。冬の指宿は観光客が減るため、砂楽でも待ち時間が少ない。砂から出た後に足湯（¥200）でゆっくりする時間は夏より格別だ。" },
      { type: "spot-card", content: "ibusuki-onsen" },
      { type: "heading", content: "菜の花と開聞岳：冬の終わり（1月下旬〜2月）が最高の景色", level: 2 },
      { type: "text", content: "1月下旬〜2月の指宿では菜の花と寒緋桜が同時に咲き始める。砂むし体験の後に長崎鼻まで車で20分走ると、菜の花×開聞岳×青い海という南国の春先の景色に出会える。この景色は冬に指宿を訪れた人だけが体験できる季節限定の報酬だ。" },
      { type: "heading", content: "黒豚しゃぶしゃぶと芋焼酎：鹿児島の冬の夜の完璧な食卓", level: 2 },
      { type: "text", content: "鹿児島市内の黒豚しゃぶしゃぶ専門店「黒豚しゃぶ和食よ志多゛」や「黒豚料理 あぢもり」では、六白黒豚の薄切り（ロース・バラ・肩ロース）を昆布だしで食べる。芋焼酎のお湯割りと合わせると、鹿児島の冬の夜の食卓の完成形になる。寒い夜に黒豚と焼酎——これが鹿児島の旅で最も記憶に残る食の体験だ。" },
    ],
    relatedArticleSlugs: ["kagoshima-ibusuki-sand-bath", "kagoshima-kurobuta-black-pig"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "kagoshima-traditional-crafts",
    title: "薩摩の伝統工芸──薩摩切子・大島紬・薩摩焼・薩摩錫器を買う場所と見る場所",
    description: "鹿児島の伝統工芸は薩摩藩の文化的遺産だ。薩摩切子・大島紬・薩摩焼の違いと、旅行者が体験・購入できる場所を一本の記事で整理する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagoshima",
    tags: ["薩摩切子", "大島紬", "薩摩焼", "伝統工芸", "鹿児島"],
    spotIds: ["sengan-en"],
    sections: [
      { type: "heading", content: "薩摩切子：赤と青の「ぼかし」が生む薩摩のガラス工芸", level: 2 },
      { type: "text", content: "薩摩切子は江戸切子と並ぶ日本二大カットガラス工芸だ。赤・青・緑・紫の色ガラスに透明ガラスを重ねた「ぼかし」の技法が独特で、光の透過で美しいグラデーションが生まれる。廃藩置県後に技法が途絶え、1985年から復元されたため本来の薩摩切子は希少品だ。仙巌園内の薩摩ガラス工芸館（¥1,200〜¥50,000）で購入できる。" },
      { type: "spot-card", content: "sengan-en" },
      { type: "heading", content: "大島紬：奄美大島が生む黒と茶の絣織物", level: 2 },
      { type: "text", content: "大島紬は奄美大島を中心に生産される国産絣（かすり）織物の最高峰だ。「本場大島紬」は正絹・手織りの証明があり、一反50万〜300万円の価格帯になることもある。独特の模様（マルキ）と泥染め（テーチ木と泥で染める）による深みのある色が特徴。鹿児島市内の「大島紬村（奄美博覧館）」で製造工程の見学と購入ができる。" },
      { type: "heading", content: "薩摩焼：12代藩主が連れてきた朝鮮陶工の末裔が守る白もんと黒もん", level: 2 },
      { type: "text", content: "薩摩焼は16世紀末の文禄・慶長の役（朝鮮出兵）の後、島津義弘が連れてきた朝鮮の陶工が始めた陶芸だ。白薩摩（白もん）は繊細な透かし彫りと絵付けの高貴な焼物、黒薩摩（黒もん）は艶のある黒い陶器で農民の日用品として使われた。日置市東市来町の「美山陶芸センター」で窯元見学と体験ができる。" },
    ],
    relatedArticleSlugs: ["kagoshima-sengan-en-garden", "kagoshima-satsuma-clan-history"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "kagoshima-tanegashima-space",
    title: "種子島宇宙センターとロケット打ち上げ観覧──日本の宇宙開発を最前線で見る旅",
    description: "種子島宇宙センターはJAXAの射場で、H-IIAロケットの打ち上げが行われる場所だ。打ち上げ観覧の申込方法と、見学の全情報を伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kagoshima",
    tags: ["種子島", "宇宙センター", "ロケット打ち上げ", "JAXA", "鹿児島"],
    spotIds: ["yakushima"],
    sections: [
      { type: "heading", content: "種子島宇宙センター：世界最南端の大型ロケット射場", level: 2 },
      { type: "text", content: "種子島宇宙センターは赤道に近い種子島の南端（北緯30.4度）に位置し、日本の主力ロケット「H-IIAロケット」「H3ロケット」の打ち上げを行う。無料見学ツアー（事前予約・1日2回）では第1射点・竹崎展望台・ロケット打ち上げシミュレーターなどを案内してもらえる。宇宙科学技術館（無料）では実物のロケットエンジンやJAXAの開発機器が展示されている。" },
      { type: "spot-card", content: "yakushima" },
      { type: "heading", content: "ロケット打ち上げ観覧：申込方法と観覧スポット", level: 2 },
      { type: "text", content: "ロケット打ち上げ日（年数回）にJAXAが公認観覧スポット（竹崎展望台・宇宙ヶ丘公園など）を設定し、無料で観覧できる。打ち上げ日は発表から2週間〜1ヶ月前が多いため、JAXAウェブサイトとSNSのフォローが必須だ。打ち上げの瞬間、数km離れた観覧スポットでも地響きと熱風が感じられる。" },
      { type: "heading", content: "種子島の観光：鉄砲伝来の歴史とサーフィンの海", level: 2 },
      { type: "text", content: "種子島は1543年にポルトガル人が漂着し、日本に初めて鉄砲（火縄銃）を伝えた島だ。「鉄砲館」では当時の鉄砲と種子島の歴史が展示されており、宇宙センターと鉄砲伝来という2つの「技術の最前線」の島という独特のキャラクターが面白い。西海岸は波が良く全国からサーファーが集まる。" },
    ],
    relatedArticleSlugs: ["kagoshima-yakushima-trekking", "kagoshima-amami-oshima"],
  },
];
