import { Article } from "@/types/article";

export const kanagawaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-daibutsu-morning",
    title: "鎌倉大仏、朝7時──逆光の中で見る800年前の青銅と空",
    description: "観光客が押し寄せる前の大仏は、空だけを背負って別の表情をしている。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-01-12",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kanagawa",
    tags: ["鎌倉大仏", "鎌倉", "早朝", "国宝", "写真映え"],
    spotIds: ["kamakura-daibutsu"],
    sections: [
      { type: "heading", content: "7時台の大仏は東から逆光になる", level: 2 },
      { type: "text", content: "高徳院は8時開門だが、周囲の住宅街から大仏の頭頂部は7時台でも見える。開門と同時に入ると、東から朝日が当たって大仏の輪郭がシルエットとして際立つ。この光は10時を過ぎると失われる。" },
      { type: "heading", content: "胎内参拝¥20は必ず体験すべき", level: 2 },
      { type: "text", content: "大仏の背中の扉から内部に入れる（¥20）。中に入ると高さ13m・重さ121トンの青銅製の内壁が間近に見える。鋳造のつなぎ目と採光窓の小さな光が、800年前の職人の仕事を物語っている。" },
      { type: "heading", content: "長谷寺の紫陽花と組み合わせるのが最善の動線", level: 2 },
      { type: "text", content: "高徳院から徒歩10分の長谷寺は、6月の紫陽花シーズン（6月上旬〜7月上旬）に40種2,500株が斜面を覆う。大仏→長谷寺の順で午前中に回ると、どちらも混雑ピーク前に済む。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-tsurugaoka-walk", "kanagawa-enoshima-sunset"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "kanagawa-enoshima-sunset",
    title: "江ノ島、夕日のシーキャンドル──富士山シルエットに太陽が沈む瞬間を狙う",
    description: "江ノ島の展望台から富士山に夕日が重なる瞬間は、湘南で最も美しい景色のひとつだ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-02-05",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kanagawa",
    tags: ["江ノ島", "夕日", "富士山", "湘南", "カップル"],
    spotIds: ["enoshima"],
    sections: [
      { type: "heading", content: "シーキャンドルは15時以降に登る", level: 2 },
      { type: "text", content: "江の島シーキャンドル（高さ59.8m）のエレベーター料金は¥500。展望フロアからは相模湾の全景と富士山が見える。夕日が富士山に沈む瞬間を狙うなら、12月〜1月の晴天日の日没40分前が最良。" },
      { type: "heading", content: "しらす丼は午前の生しらすが格別", level: 2 },
      { type: "text", content: "江ノ島のしらす丼は4月〜12月に生しらすが食べられる。鎌倉方面から橋を渡ってすぐの「とびっちょ」はしらす専門店で、釜揚げ・生・ハーフ&ハーフの3種が選べる。開店（10時）直後は30分待ちで入れる。" },
      { type: "heading", content: "岩屋洞窟は最奥まで行け", level: 2 },
      { type: "text", content: "江ノ島の南端にある岩屋洞窟（入場¥500）は全長152mで、第1岩屋の最奥に弘法大師ゆかりの石仏が安置されている。薄暗い洞窟内でろうそくを手にして歩く体験は、シーキャンドルの後に来ると対比が面白い。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-daibutsu-morning", "kanagawa-shonan-beach-summer"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-onsen-guide",
    title: "箱根温泉完全ガイド──17の温泉地と日帰り湯・宿泊の全選択肢",
    description: "東京から90分の箱根は、旅館の選び方と動線を知っているかどうかで全く別の旅になる。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-11-08",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "kanagawa",
    tags: ["箱根温泉", "温泉", "富士山", "宿泊", "カップル"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "箱根フリーパスは新宿から使い倒せる", level: 2 },
      { type: "text", content: "小田急の箱根フリーパス（2日間¥6,100）はロマンスカー往復と箱根内のバス・ロープウェイ・海賊船が全て乗り放題だ。箱根湯本→強羅→大涌谷→芦ノ湖の周回ルートをこれ1枚で回れる。" },
      { type: "heading", content: "大涌谷の黒たまごと硫黄地帯", level: 2 },
      { type: "text", content: "大涌谷は硫黄の噴煙が今も上がる活火山地帯で、その地熱で茹でた黒たまご（¥700で5個入り）は表面が黒く変色している。「1個食べると7年長生きする」という話は伝説だが、噴煙の中で食べる体験に価値がある。" },
      { type: "heading", content: "宮ノ下の富士屋ホテルで歴史的建築に泊まる", level: 2 },
      { type: "text", content: "箱根宮ノ下の富士屋ホテルは1878年開業の日本最古級リゾートホテルだ。ジョン・レノンも泊まった歴史的客室は1泊¥50,000〜だが、レストランでの昼食（¥5,000〜）だけでもこの建物の空気を吸える。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-art-museum", "kanagawa-hakone-fuji-view"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-chinatown-food",
    title: "横浜中華街の食べ歩き完全攻略──600軒から選ぶべき10店と正しい歩き順",
    description: "横浜中華街は広すぎて何を食べるか迷う。最初から動線と店を決めてから入れ。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kanagawa",
    tags: ["横浜中華街", "グルメ", "食べ歩き", "横浜", "中華料理"],
    spotIds: ["yokohama-chinatown"],
    sections: [
      { type: "heading", content: "牌楼10基を全て写真に収める動線", level: 2 },
      { type: "text", content: "横浜中華街には10基の牌楼（中華門）があり、方角ごとに守護神と色が違う。中心の朱雀門から東西南北に向かう十字の動線で歩くと全部回れる。各牌楼の前で写真を撮る「牌楼コンプリート」は中華街定番の楽しみ方。" },
      { type: "heading", content: "飲茶ランチは12時前の入店が正解", level: 2 },
      { type: "text", content: "「横浜大世界」の飲茶は週末昼に行列必至だが、11時30分の開店と同時に入れば席を確保できる。シュウマイ・腸粉・大根もちの3点セットで¥1,500〜。一方、個人経営の小さな飲茶店に入る方が体験の密度が高いのは間違いない。" },
      { type: "heading", content: "春節（旧正月）の1週間は別世界", level: 2 },
      { type: "text", content: "春節（例年1月下旬〜2月上旬）前後の中華街は龍の舞と爆竹で街全体が沸く。煙と鐘の音が満ちる通りは平時とは全く違う顔で、観光というより体験に近い。元宵節（春節から15日後）のランタン祭りも見応えがある。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-minatomirai-night", "kanagawa-yokohama-bay-walk"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-minatomirai-night",
    title: "横浜みなとみらいの夜景──ランドマークタワー273mと赤レンガ倉庫の光",
    description: "横浜ベイエリアの夜景は東京湾側から見ると全く別の顔を持つ。最良のポジションを教える。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-04-22",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kanagawa",
    tags: ["みなとみらい", "夜景", "横浜", "カップル", "展望台"],
    spotIds: ["yokohama-minatomirai"],
    sections: [
      { type: "heading", content: "スカイガーデン（69F）から横浜全景", level: 2 },
      { type: "text", content: "ランドマークタワーのスカイガーデン（高さ273m、¥1,000）からは横浜港全体と富士山が同時に見渡せる。夕方17時台に入ると日没と夜景の切り替わりの両方を1枚のチケットで体験できる。東京スカイツリーより安くて空いている。" },
      { type: "heading", content: "赤レンガ倉庫は週末マルシェが賑やか", level: 2 },
      { type: "text", content: "明治期の煉瓦倉庫を改装した赤レンガ倉庫は週末に常にマルシェやイベントが行われている。夜は外壁のライトアップが美しく、前の広場からみなとみらいのスカイラインが一望できる。入場無料。" },
      { type: "heading", content: "大桟橋から客船の入港を間近で見る", level: 2 },
      { type: "text", content: "横浜大桟橋は国際ターミナルで、大型客船が入港する日は甲板から巨大な船体と横浜の街が同フレームに収まる特別な光景が見られる。入港スケジュールは横浜港の公式サイトで確認できる。無料で入れる。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-chinatown-food", "kanagawa-yokohama-bay-walk"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-tsurugaoka-walk",
    title: "鶴岡八幡宮──段葛の桜から流鏑馬まで、鎌倉武士の精神地を歩く",
    description: "源頼朝が整備した参道を歩くと、鎌倉の800年が足の裏から伝わってくる。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kanagawa",
    tags: ["鶴岡八幡宮", "鎌倉", "桜", "歴史", "神社"],
    spotIds: ["tsurugaoka-hachimangu"],
    sections: [
      { type: "heading", content: "段葛は4月の桜トンネルが最高", level: 2 },
      { type: "text", content: "若宮大路の中央に位置する段葛（鶴岡八幡宮まで続く参道）は、4月上旬に桜のトンネルになる。両側の桜が枝を張り出して頭上を覆う光景は、鎌倉で最も美しい春の景色として知られる。早朝6時台が人が少なく最良。" },
      { type: "heading", content: "源氏池と平家池は政治史が刻まれた地形", level: 2 },
      { type: "text", content: "境内に源氏池と平家池が対になって存在する。源氏池には3つの島（産・生命の意）、平家池には4つの島（死を意味する「四」）が作られており、権力者による象徴的な地形設計が分かる。" },
      { type: "heading", content: "9月の流鏑馬は無料で見られる神事", level: 2 },
      { type: "text", content: "鶴岡八幡宮の例大祭（9月14〜16日）の流鏑馬は、馬が参道を疾走しながら射手が的を射る神事だ。一般席は無料で見られ、馬の蹄の音と矢が的に当たる瞬間の迫力は写真では伝わらない。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-daibutsu-morning", "kanagawa-kamakura-hasedera-hydrangea"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-art-museum",
    title: "箱根の美術館めぐり──彫刻の森・ポーラ美術館・岡田美術館を1泊2日で制覇",
    description: "箱根は温泉だけではない。世界水準の美術館が山中に密集する、日本で最も美術的な場所だ。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kanagawa",
    tags: ["箱根", "美術館", "アート", "彫刻の森", "ポーラ美術館"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "彫刻の森美術館は屋外展示が主役", level: 2 },
      { type: "text", content: "箱根彫刻の森美術館（¥1,600）は70,000㎡の屋外展示場にヘンリー・ムーア・ロダン・ピカソの彫刻が配置されている。ネットの塔（ステンドグラス構造物）の内部から見上げる光は唯一無二の体験だ。" },
      { type: "heading", content: "ポーラ美術館は印象派コレクションが圧倒的", level: 2 },
      { type: "text", content: "仙石原のポーラ美術館（¥1,800）はモネ・ルノワール・セザンヌ・ピカソを中心に9,500点を収蔵する。建物自体が森の斜面に埋め込まれた設計で、自然光が差し込む展示室は世界水準の空間体験だ。" },
      { type: "heading", content: "岡田美術館は日本・東洋美術の決定版", level: 2 },
      { type: "text", content: "小涌谷の岡田美術館（¥2,800）は日本の美術館で最も高額な入場料を取るが、茶碗・掛け軸・陶磁器のコレクションは国内最高水準だ。5,000㎡の建物全体が一つの展示空間になっている。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-onsen-guide", "kanagawa-hakone-fuji-view"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "kanagawa-shonan-beach-summer",
    title: "湘南ビーチの夏──七里ヶ浜・逗子・由比ヶ浜を海沿いに歩く完全ガイド",
    description: "湘南の海は海水浴場だけではない。波打ち際を歩きながら富士山を見る、それだけでいい。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kanagawa",
    tags: ["湘南", "ビーチ", "夏", "海水浴", "富士山"],
    spotIds: ["enoshima"],
    sections: [
      { type: "heading", content: "七里ヶ浜は富士山が最も美しく見えるビーチ", level: 2 },
      { type: "text", content: "江ノ電「七里ヶ浜駅」から徒歩5分の七里ヶ浜は、晴れた日に富士山・江ノ島・伊豆半島が一直線に並ぶ湘南随一の眺望を持つ。カフェ「bills」の目の前の砂浜は、リコッタパンケーキを食べながら富士山を見る非現実的な時間を作れる。" },
      { type: "heading", content: "江ノ電1日乗車券で海辺を全駅探索", level: 2 },
      { type: "text", content: "江ノ電1日乗車券「のりおりくん」（¥800）は鎌倉〜藤沢の全駅乗り降り自由だ。極楽寺・稲村ヶ崎・七里ヶ浜・江ノ島と海と山が交互に現れる車窓は、日本で最も変化に富んだローカル線体験のひとつ。" },
      { type: "heading", content: "逗子・葉山は横浜方面の穴場ビーチ", level: 2 },
      { type: "text", content: "逗子海岸と葉山の一色海岸は江ノ島・鎌倉より観光客が少なく、地元民率が高い。葉山御用邸の近くの森戸神社は海の上に立つ鳥居があり、小さな江ノ島のような風景がある。電車（逗子駅）からバスで15分。" },
    ],
    relatedArticleSlugs: ["kanagawa-enoshima-sunset", "kanagawa-kamakura-daibutsu-morning"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-fuji-view",
    title: "箱根から見る富士山──芦ノ湖・成川美術館・大観山の3つの絶景ポジション",
    description: "箱根に来て富士山が見えなかったと言う人は、立つ場所を間違えている。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-10-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kanagawa",
    tags: ["箱根", "富士山", "芦ノ湖", "絶景", "秋"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "成川美術館前の湖畔が最良のポジション", level: 2 },
      { type: "text", content: "芦ノ湖から富士山を見るベストポジションは成川美術館（¥1,200）前の湖畔テラスだ。美術館の入場料が必要だが、四季の日本画コレクションと湖越しの富士山を同時に体験できる。午前中は逆光にならず視界が澄む。" },
      { type: "heading", content: "箱根神社の鳥居と富士山の構図", level: 2 },
      { type: "text", content: "芦ノ湖に立つ箱根神社の平和の鳥居は、水に浸かった朱色の鳥居越しに富士山が見える構図で有名だ。朝の霧が晴れる9〜10時台が最良のタイミングで、湖面の静けさが鳥居の反射を作る。" },
      { type: "heading", content: "大観山は雲の上から富士山を見下ろす", level: 2 },
      { type: "text", content: "箱根ターンパイク最高地点（標高1,011m）の大観山展望台は、雲海が発生した日に富士山の中腹だけが雲の上に浮かぶ光景が見られる。秋〜冬の晴天日の朝5〜7時台が最もこの現象が出やすい。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-onsen-guide", "kanagawa-hakone-art-museum"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-autumn-foliage",
    title: "鎌倉の紅葉2025──円覚寺・明月院・瑞泉寺の見頃と穴場コース",
    description: "鎌倉の紅葉は寺ごとに見頃が1〜2週間ずれる。正しい順番で回れば長く楽しめる。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kanagawa",
    tags: ["鎌倉", "紅葉", "秋", "円覚寺", "明月院"],
    spotIds: ["tsurugaoka-hachimangu"],
    sections: [
      { type: "heading", content: "円覚寺の黄金の銀杏は11月下旬", level: 2 },
      { type: "text", content: "北鎌倉の円覚寺（¥500）は境内に巨大な銀杏の木があり、11月下旬に黄金色に染まる。仏殿前の石段に黄葉が積もる時間帯（早朝）が最も美しい。紅葉より銀杏の黄葉が先に見頃を迎えるため、11月中旬から動き始めよ。" },
      { type: "heading", content: "明月院の紅葉は「悟りの窓」と合わせて撮る", level: 2 },
      { type: "text", content: "明月院（¥500）は「アジサイ寺」として有名だが、11月下旬〜12月上旬の紅葉も見事だ。本堂の丸窓「悟りの窓」越しに紅葉した庭園を収めた写真が世界的に有名になり、この時期のみ奥の庭園が公開される。" },
      { type: "heading", content: "瑞泉寺は最も遅い12月上旬が見頃", level: 2 },
      { type: "text", content: "鎌倉宮から徒歩10分の瑞泉寺（¥200）は鎌倉で最も紅葉が遅い寺で、12月上旬でも十分色が残る。上から見下ろす岩盤庭園と紅葉の組み合わせは他に似た光景がなく、インスタ映えより本物の美しさがある。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-tsurugaoka-walk", "kanagawa-kamakura-daibutsu-morning"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-bay-walk",
    title: "横浜ベイエリア1日ウォーキングコース──山下公園・大桟橋・赤レンガ倉庫を繋ぐ",
    description: "横浜の港は歩くためにある。海沿いの遊歩道を全て繋ぐと、東京湾岸最高の散歩が完成する。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-05-02",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kanagawa",
    tags: ["横浜", "散歩", "ベイエリア", "山下公園", "みなとみらい"],
    spotIds: ["yokohama-minatomirai", "yokohama-chinatown"],
    sections: [
      { type: "heading", content: "山下公園の氷川丸から始める", level: 2 },
      { type: "text", content: "山下公園に係留された氷川丸（¥300）は1930年竣工の日本郵船の客船で、内部を見学できる。一等食堂のアール・デコ内装が保存されており、昭和初期の豪華客船旅行の雰囲気を今に伝える。" },
      { type: "heading", content: "象の鼻パークから大桟橋へ", level: 2 },
      { type: "text", content: "山下公園から西に15分歩くと象の鼻パークに着く。幕末に開港した横浜の歴史的な防波堤の跡で、横浜港の水際を感じられる場所だ。大桟橋の木製デッキから見る横浜ベイブリッジは、橋の全景が正面に広がる。" },
      { type: "heading", content: "赤レンガ倉庫でクラフトビールを飲む", level: 2 },
      { type: "text", content: "大桟橋から北へ15分歩くと赤レンガ倉庫に着く。横浜のクラフトビールブランド「横浜ビール」の醸造所が近くにあり、館内のレストランでは横浜産のビールが飲める。テラス席から見えるコスモクロック21の観覧車を眺めながら飲む1杯は格別。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-minatomirai-night", "kanagawa-yokohama-chinatown-food"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-hasedera-hydrangea",
    title: "長谷寺の紫陽花2025──40種2,500株を最も美しく見る時間と場所",
    description: "鎌倉の紫陽花シーズンは6月。長谷寺の丘から見下ろす紫陽花と海の構図は、日本で最も有名な梅雨の景色だ。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kanagawa",
    tags: ["長谷寺", "紫陽花", "鎌倉", "梅雨", "写真映え"],
    spotIds: ["kamakura-daibutsu"],
    sections: [
      { type: "heading", content: "紫陽花の見頃は6月上旬〜7月上旬", level: 2 },
      { type: "text", content: "長谷寺（¥400）の紫陽花は例年6月上旬から7月上旬に見頃を迎える。40種2,500株が斜面を埋め尽くし、青・紫・白・ピンクのグラデーションが下から登るにつれて変化する。雨の日はしっとりした色が最も鮮やか。" },
      { type: "heading", content: "展望台から海と紫陽花の構図を撮る", level: 2 },
      { type: "text", content: "長谷寺の展望台（見晴台）からは由比ヶ浜と相模湾が一望できる。手前の紫陽花と遠景の海が重なる構図は、この時期にしか撮れない鎌倉固有の風景だ。望遠レンズで圧縮すると紫陽花の密度が際立つ。" },
      { type: "heading", content: "鎌倉大仏と長谷寺のセットが最短の動線", level: 2 },
      { type: "text", content: "江ノ電長谷駅から長谷寺（徒歩3分）→鎌倉大仏（高徳院、徒歩10分）の順に回ると、午前中の2時間で2か所を回れる。紫陽花シーズンの長谷寺は整理券制になる場合があり、8時台の入園が最も確実。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-daibutsu-morning", "kanagawa-kamakura-tsurugaoka-walk"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-solo-day-trip",
    title: "箱根ひとり旅1日プラン──朝イチのロマンスカーで行く温泉と美術館と大涌谷",
    description: "箱根は2人で来る場所だと思っている人へ。一人で来た方が、深く旅できる理由がある。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kanagawa",
    tags: ["箱根", "一人旅", "日帰り", "温泉", "ロマンスカー"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "新宿7時台のロマンスカーが最良の出発", level: 2 },
      { type: "text", content: "小田急ロマンスカー（新宿→箱根湯本 約85分、¥1,270+特急料金¥1,230）の7〜8時台便に乗ると、箱根湯本に9時過ぎに着く。平日なら座席は事前予約不要で当日購入可能だ。車窓の丹沢山塊が晴れれば最高の景色になる。" },
      { type: "heading", content: "箱根湯本の早朝温泉は日帰り¥800〜", level: 2 },
      { type: "text", content: "箱根湯本駅周辺の「天成園」は日帰り温泉施設で¥1,800から入れる露天大浴場がある。早朝9時台は地元の常連が多く、観光客は少ない。温泉に1時間入ってから移動すると、1日の体力の配分が変わる。" },
      { type: "heading", content: "一人なら箱根フリーパスで気ままに乗り換え", level: 2 },
      { type: "text", content: "箱根フリーパスは乗り降り自由なので、一人旅なら時刻表をあまり気にせず動ける。大涌谷→芦ノ湖（海賊船）→元箱根→箱根湯本という帰路を使うと全ての乗り物を1日で制覇できる。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-onsen-guide", "kanagawa-hakone-fuji-view"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-yamate-bluff",
    title: "横浜・山手の洋館めぐり──明治〜昭和の外国人居留地建築を歩く半日ルート",
    description: "横浜の丘の上には150年前に外国人が建てた洋館が今も立っている。無料で全部入れる。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-03-18",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kanagawa",
    tags: ["横浜", "山手", "洋館", "歴史", "散歩"],
    spotIds: [],
    sections: [
      { type: "heading", content: "7つの洋館は全て無料開放", level: 2 },
      { type: "text", content: "山手の丘には横浜外国人居留地時代の洋館が7棟現存し、全て無料で入れる。ベーリック・ホール・山手111番館・エリスマン邸などが徒歩15分圏内に集中しており、半日で全部回れる。開館は9時〜17時（月曜休館）。" },
      { type: "heading", content: "山手聖公会教会の美しいステンドグラス", level: 2 },
      { type: "text", content: "1931年建設の山手聖公会教会は礼拝日以外も内部を見学できる。英国ゴシック様式の建築とステンドグラスは、横浜が「東洋のロンドン」と呼ばれた時代の名残だ。外から眺めるだけでも絵になる。" },
      { type: "heading", content: "外人墓地から中華街へ下る絶景ルート", level: 2 },
      { type: "text", content: "横浜外人墓地（見学寄付金制）は4,500人以上が眠る歴史的墓地で、山手の丘から港が一望できる。ここから坂を下ると中華街の朱雀門に直結する。丘の上の欧風世界から中国の香りへの急転換が横浜らしい。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-bay-walk", "kanagawa-yokohama-chinatown-food"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "kanagawa-enoshima-sea-candle-illumination",
    title: "江ノ島シーキャンドルのイルミネーション──冬の相模湾に広がる光の海",
    description: "江ノ島の冬は夏より美しい。イルミネーションと富士山のシルエットが重なる夜がある。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-12-05",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kanagawa",
    tags: ["江ノ島", "イルミネーション", "冬", "カップル", "夜景"],
    spotIds: ["enoshima"],
    sections: [
      { type: "heading", content: "江の島ウインターチューリップは12月〜2月", level: 2 },
      { type: "text", content: "江ノ島では例年12月〜2月に「江の島ウインターチューリップ」のイルミネーションが実施される。弁天橋から江島神社にかけての参道全体が光で彩られ、夕暮れから22時まで楽しめる。¥500のエスカー（エスカレーター）で上まで行くと全体が見渡せる。" },
      { type: "heading", content: "冬の日没直後は富士山が最も鮮明", level: 2 },
      { type: "text", content: "12月〜1月の日没直後（17時〜17時30分）は空が透明で富士山のシルエットが最も鮮明に見える時間帯だ。シーキャンドル展望台から見ると、富士山の冠雪とオレンジの残照が重なる瞬間が数分間だけ訪れる。" },
      { type: "heading", content: "冬の江ノ島は空いていて写真が撮りやすい", level: 2 },
      { type: "text", content: "夏の江ノ島は観光客で埋め尽くされるが、12月〜2月は格段に空いている。岩屋洞窟も参道の食べ歩きも待ち時間なしで楽しめる。しらす丼は冬でも釜揚げしらすが食べられる。" },
    ],
    relatedArticleSlugs: ["kanagawa-enoshima-sunset", "kanagawa-shonan-beach-summer"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-bamboo-grove",
    title: "報国寺の竹の庭──鎌倉で最も静かな場所で抹茶を飲む半日",
    description: "2,000本の孟宗竹が作る緑のドームの下で抹茶を飲む体験は、京都の竹林とは別の静けさがある。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-04-28",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kanagawa",
    tags: ["報国寺", "鎌倉", "竹林", "抹茶", "禅寺"],
    spotIds: [],
    sections: [
      { type: "heading", content: "報国寺の竹の庭は8時台が別世界", level: 2 },
      { type: "text", content: "鎌倉市浄明寺の報国寺（¥300+抹茶¥600）は「竹の寺」として知られ、2,000本の孟宗竹が作る竹林の庭が主役だ。開門は9時だが、開門直後の朝日が竹の間を差し込む時間帯は光と影のコントラストが際立つ。" },
      { type: "heading", content: "竹林の中で抹茶を飲む時間を作る", level: 2 },
      { type: "text", content: "庭内の休耕庵で提供される抹茶と和菓子のセット（¥600）は竹林の中に設けられたテーブルで飲める。竹の揺れる音と抹茶の苦みが重なる体験は、鎌倉で他に代えるものがない。" },
      { type: "heading", content: "近くの杉本寺と浄妙寺も組み合わせて", level: 2 },
      { type: "text", content: "報国寺の近隣には鎌倉最古の寺・杉本寺（¥200）と枯山水の庭が美しい浄妙寺（¥200）がある。3寺をセットに回ると「鎌倉のディープな禅文化」半日コースが完成する。全て鎌倉駅東口バスで10分以内。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-tsurugaoka-walk", "kanagawa-kamakura-autumn-foliage"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-ramen-museum",
    title: "新横浜ラーメン博物館──日本全国のラーメンを1か所で食べ比べる究極のガイド",
    description: "日本最大のラーメンテーマパークで、最も効率よく食べ歩くための戦略がある。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-02-22",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kanagawa",
    tags: ["ラーメン", "新横浜", "グルメ", "フード", "ラーメン博物館"],
    spotIds: [],
    sections: [
      { type: "heading", content: "入場¥380で8店のラーメンを食べ比べ", level: 2 },
      { type: "text", content: "新横浜ラーメン博物館（¥380）は1994年開業の日本最初のフードテーマパークで、全国の名店が1〜2年ごとに出店を入れ替える。半ラーメンサイズのミニ（¥700前後）で3〜4杯食べ比べるのが正しい楽しみ方。" },
      { type: "heading", content: "昭和33年の街並みが再現された地下空間", level: 2 },
      { type: "text", content: "地下1〜2階は昭和33年（1958年）の夕暮れの街並みが再現されており、ラーメン屋以外に駄菓子屋・レコード店・バーが昭和の雰囲気で並ぶ。食べ歩きが目的でなくても、この昭和世界観だけで入場料の価値がある。" },
      { type: "heading", content: "平日11時〜12時台が最も空いている", level: 2 },
      { type: "text", content: "新横浜ラーメン博物館は週末昼は全店に行列ができるが、平日11〜12時台は開店直後で空いている。人気の「支那そばや」「龍上海」は休日30分待ちが平日なら5分で入れる。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-chinatown-food", "kanagawa-yokohama-bay-walk"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-budget-daytrip",
    title: "箱根の節約旅行術──¥5,000以内で温泉・大涌谷・芦ノ湖を全部回る",
    description: "箱根は高いと思っているあなたへ。フリーパスと立ち寄り湯の組み合わせで全部体験できる。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-08-28",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "kanagawa",
    tags: ["箱根", "節約", "日帰り", "温泉", "フリーパス"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "箱根フリーパス2日券¥6,100の内訳", level: 2 },
      { type: "text", content: "小田急の箱根フリーパス2日券（¥6,100）はロマンスカー往復（¥2,460）＋箱根内交通全種（バス・ロープウェイ・海賊船など）が含まれる。交通費だけで¥4,000以上使うため、フリーパスは実質¥2,000の節約になる。" },
      { type: "heading", content: "日帰り温泉は¥500〜¥1,200で入れる", level: 2 },
      { type: "text", content: "箱根湯本の「弥次喜多の湯」は日帰り入浴¥800で硫黄泉を体験できる。箱根で最も安価に入れる立ち寄り湯のひとつだ。大涌谷でロープウェイを降りた先の蒸し玉（黒たまご）は5個¥700でシェアできる。" },
      { type: "heading", content: "芦ノ湖の海賊船と成川美術館をセットで", level: 2 },
      { type: "text", content: "フリーパスに含まれる芦ノ湖の海賊船（元箱根〜箱根町港）は約25分で、富士山が見える日は最高のクルーズになる。成川美術館（¥1,200）の前のテラスは美術館に入らなくても富士山が見えるため、入場の判断は当日の天気次第。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-solo-day-trip", "kanagawa-hakone-onsen-guide"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-cafe-modern",
    title: "鎌倉の古民家カフェ＆海カフェ──小町通りを外れた本物の店10選",
    description: "小町通りの行列店を避けると、鎌倉には本当に居心地のいいカフェが見つかる。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-05-30",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kanagawa",
    tags: ["鎌倉", "カフェ", "古民家", "海カフェ", "一人旅"],
    spotIds: [],
    sections: [
      { type: "heading", content: "由比ヶ浜の海カフェで波音を聞きながら", level: 2 },
      { type: "text", content: "由比ヶ浜駅から徒歩5分の「珊瑚礁」は1969年創業の老舗海の家カフェで、テラス席から海が見える。ドリンク¥700〜でビーチフロントに座れる。夏以外は混まず、秋〜春の空いた海カフェとして地元民に愛されている。" },
      { type: "heading", content: "御成通りの古民家カフェに人が来ない理由", level: 2 },
      { type: "text", content: "鎌倉駅西口の御成通りは観光客の多い小町通りより空いており、大正〜昭和初期の古民家を改装したカフェが点在する。「カフェ・ド・さいかい」（古民家）は日替わりランチ¥1,000で地元民が通う店だ。" },
      { type: "heading", content: "北鎌倉駅前の「喫茶かんが」は予約不要", level: 2 },
      { type: "text", content: "円覚寺の門前に位置する「喫茶かんが」は昭和の雰囲気のまま営業するコーヒー専門店で、ブレンド¥600。北鎌倉の社寺巡りの前後に立ち寄ると、歩き疲れた足と頭が整う静かな時間が作れる。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-bamboo-grove", "kanagawa-kamakura-hasedera-hydrangea"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-spring-event",
    title: "横浜春の花まつり──山下公園のチューリップと港の見える丘公園の薔薇",
    description: "横浜の春は花で始まる。4月のチューリップと5月の薔薇を組み合わせた2つの公園コース。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kanagawa",
    tags: ["横浜", "花", "春", "山下公園", "港の見える丘"],
    spotIds: ["yokohama-minatomirai"],
    sections: [
      { type: "heading", content: "山下公園の春はチューリップ30,000本", level: 2 },
      { type: "text", content: "山下公園は毎年4月に約30,000本のチューリップが咲き揃い、横浜港と客船の赤い煙突を背景に撮れる唯一の構図が生まれる。「横浜チューリップまつり」（入場無料）は4月上旬〜中旬が見頃だ。" },
      { type: "heading", content: "港の見える丘公園は5月の薔薇が見事", level: 2 },
      { type: "text", content: "山手の港の見える丘公園は5月中旬に2,000株の薔薇が開花する。この公園からはベイブリッジと横浜港が見下ろせ、薔薇と港の組み合わせは横浜観光の最高のシーンのひとつだ。入場無料。" },
      { type: "heading", content: "山手の洋館と組み合わせたフラワーコース", level: 2 },
      { type: "text", content: "港の見える丘公園→外人墓地→ベーリック・ホール→山手111番館のルートは、花と洋館と眺望を全部含む山手半日コースだ。春の晴れた日に歩くと、横浜が「東洋の港町」だった時代の面影がリアルに残っている。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-yamate-bluff", "kanagawa-yokohama-bay-walk"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-ryokan-luxury",
    title: "箱根の高級旅館に泊まる──強羅・仙石原・芦ノ湖畔、3エリアの最高の選び方",
    description: "箱根の旅館は立地と泉質と食事の3つで選ぶ。どのエリアに泊まるかで、旅の内容が全く変わる。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kanagawa",
    tags: ["箱根", "旅館", "高級宿", "温泉", "ラグジュアリー"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "強羅エリアは泉質と森の静けさが最高", level: 2 },
      { type: "text", content: "強羅（ごうら）の旅館は標高600m前後の森の中にあり、温泉の泉質がアルカリ性で肌に優しい。「強羅花壇」（1泊¥80,000〜）はCNNが選ぶ「世界のベスト旅館」に入ったことがあり、料理と庭の完成度が国内最高水準。" },
      { type: "heading", content: "仙石原のコテージ型は2人旅に最適", level: 2 },
      { type: "text", content: "仙石原エリアは草原と林の中にコテージや小規模旅館が点在する。「仙石原プリンスホテル」は1泊¥20,000〜と箱根高級宿の中では現実的な価格で、芦ノ湖が見える露天風呂を持つ。10月のすすき草原が目の前にある時期は圧倒的。" },
      { type: "heading", content: "芦ノ湖畔で富士山が見える朝を体験する", level: 2 },
      { type: "text", content: "芦ノ湖畔の旅館は早朝に富士山が見える確率が最も高い。「はなをり」は1泊¥35,000〜で芦ノ湖に面した客室から正面に富士山が見える。朝食前に湖畔を散歩すると、湖面に映る富士山と朝靄の景色が1日の始まりを決定的にする。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-onsen-guide", "kanagawa-hakone-fuji-view"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-family-plan",
    title: "子どもと行く鎌倉2日間──大仏・江ノ電・しらす丼・海水浴の最短モデルコース",
    description: "鎌倉は子どもには広すぎる。最短ルートと歩かせない工夫で、家族旅行を成功させる計画。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "kanagawa",
    tags: ["鎌倉", "家族旅行", "子ども", "江ノ電", "大仏"],
    spotIds: ["kamakura-daibutsu", "enoshima"],
    sections: [
      { type: "heading", content: "1日目：江ノ電で鎌倉→長谷→江ノ島", level: 2 },
      { type: "text", content: "鎌倉駅から江ノ電に乗り、長谷駅で降りて鎌倉大仏（¥300）を見る。子どもには「大仏の中に入れる（¥20）」を先に言うとテンションが上がる。その後、長谷から江ノ電で江ノ島駅へ。しらす丼（¥1,200〜）で昼食。" },
      { type: "heading", content: "江ノ島水族館は子どもに最適な規模", level: 2 },
      { type: "text", content: "江ノ島水族館（えのすいトリーター。¥2,500、子ども¥1,300）はクラゲ展示が世界水準で、子どもが飽きない程度のコンパクトさが利点だ。夏季限定の海水浴場（腰越・片瀬東浜）は水族館から徒歩5分。" },
      { type: "heading", content: "2日目：鶴岡八幡宮と鳩サブレーで完結", level: 2 },
      { type: "text", content: "鎌倉駅から徒歩10分の鶴岡八幡宮を参拝した後、若宮大路で「豊島屋」の鳩サブレーを買う。1枚¥100から買えて子どもが手に持って歩ける土産として最適。小町通りでソフトクリームを食べて締めると完璧な2日間。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-daibutsu-morning", "kanagawa-enoshima-sunset"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "kanagawa-miura-peninsula-maguro",
    title: "三浦半島のマグロと城ヶ島──海沿いを南下して灯台と新鮮マグロにたどり着く",
    description: "横浜から電車で90分。神奈川の最南端にある岬は、東京圏で最も漁師文化が残る場所だ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kanagawa",
    tags: ["三浦半島", "マグロ", "城ヶ島", "海鮮", "日帰り"],
    spotIds: [],
    sections: [
      { type: "heading", content: "三崎港のマグロは昼前に売り切れる", level: 2 },
      { type: "text", content: "三浦市の三崎港は日本有数のマグロ水揚げ港で、港周辺にマグロ専門の食堂が密集する。「くろば亭」のマグロ丼（¥1,600）は刺身の厚さが圧倒的で、11時の開店と同時に入れば待ち時間なし。" },
      { type: "heading", content: "城ヶ島は神奈川最南端の岬", level: 2 },
      { type: "text", content: "三崎港から橋を渡った城ヶ島は、相模湾に突き出た岩礁の島だ。「ウミウ展望台」から見る断崖と波の光景は湘南や江ノ島とは全く異なるワイルドな海岸美。城ヶ島灯台（1870年建造）は神奈川県最古の灯台。" },
      { type: "heading", content: "三浦海岸の桜×菜の花（1月〜2月）", level: 2 },
      { type: "text", content: "三浦海岸駅前の河津桜（1月下旬〜2月）は菜の花と同時に咲く早咲き桜として知られる。ピンクと黄色が海の青に映える光景は、東京周辺の春の前哨戦として毎年多くの人が訪れる。入場無料。" },
    ],
    relatedArticleSlugs: ["kanagawa-shonan-beach-summer", "kanagawa-enoshima-sunset"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-new-year",
    title: "横浜の年越し──中華街の春節ランタンと元旦の山下公園日の出",
    description: "横浜の正月は東京とは違うにぎわい方をする。中華街の年越しと港の日の出を同じ朝に体験する。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-12-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kanagawa",
    tags: ["横浜", "年越し", "中華街", "元旦", "日の出"],
    spotIds: ["yokohama-chinatown", "yokohama-minatomirai"],
    sections: [
      { type: "heading", content: "12月31日深夜の中華街は独特の雰囲気", level: 2 },
      { type: "text", content: "横浜中華街の年越しカウントダウンは爆竹と鐘の音で迎える。関帝廟（かんていびょう）では旧暦の春節前でも毎年12月31日に参拝者が訪れる。深夜0時の中華街は普段とは全く違う熱量で、観光より体験に近い。" },
      { type: "heading", content: "元旦の山下公園で東京湾の日の出", level: 2 },
      { type: "text", content: "山下公園は元旦の初日の出スポットとして地元に知られている。東京湾の水平線から昇る太陽と横浜港の朝景色は、東京の初日の出とは異なる港湾都市の朝を見せる。氷川丸の黒いシルエットと朝日の構図が撮れる。" },
      { type: "heading", content: "みなとみらいの初詣は三溪園が穴場", level: 2 },
      { type: "text", content: "横浜の初詣で意外と知られていないのが本牧の三溪園（¥700）だ。明治〜大正の日本建築17棟が集められた庭園は正月三が日も開園しており、梅の花が早咲きで始まる1月中旬には梅と古建築の組み合わせが美しい。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-chinatown-food", "kanagawa-yokohama-minatomirai-night"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-winter-onsen",
    title: "箱根の雪と温泉──冬こそ来るべき理由と雪景色の露天風呂が体験できる宿",
    description: "箱根の冬は混まない。雪が降った翌日の露天風呂は、年中の中で最高の体験になる。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-01-28",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "kanagawa",
    tags: ["箱根", "冬", "温泉", "雪", "露天風呂"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "強羅・仙石原エリアは年に数回雪が積もる", level: 2 },
      { type: "text", content: "箱根の強羅・仙石原は標高600〜700mで、1〜2月に数回積雪することがある。雪が積もった翌朝の露天風呂は、白銀の庭園と湯煙が重なる光景が見られる。雪の日の旅館は宿泊者が少なく、静かな貸し切りに近い状況になることもある。" },
      { type: "heading", content: "大涌谷は雪があると噴煙が際立つ", level: 2 },
      { type: "text", content: "雪景色の大涌谷は硫黄の噴煙がより白く際立つ。冬の澄んだ空気は富士山が最も鮮明に見える時期で、大涌谷から見る冠雪した富士山は夏より2倍美しい。防寒必須だが来る価値は十分にある。" },
      { type: "heading", content: "冬の箱根は12〜2月が最もコスパが高い", level: 2 },
      { type: "text", content: "箱根の旅館は12〜2月がオフシーズンで、紅葉シーズン（11月）や春（4〜5月）より1泊¥5,000〜¥10,000安くなる宿が多い。平日の予約はさらに安く、同じ旅館でも時期によって価格が大きく変わる。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-onsen-guide", "kanagawa-hakone-ryokan-luxury"],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "kanagawa-enoden-photo-guide",
    title: "江ノ電撮影完全ガイド──海と電車と富士山が一枚に収まる5か所の撮影ポイント",
    description: "江ノ電は走っているだけで絵になる。最も美しく撮れる場所と時間帯を全部教える。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-03-22",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kanagawa",
    tags: ["江ノ電", "写真", "鎌倉", "湘南", "撮影スポット"],
    spotIds: ["enoshima"],
    sections: [
      { type: "heading", content: "134号線との踏切は電車と海が重なる", level: 2 },
      { type: "text", content: "腰越〜江ノ島駅間の国道134号線の踏切（通称「鎌倉高校前踏切」）は電車と海が同フレームに収まる日本で最も有名な踏切のひとつだ。アニメ「スラムダンク」の聖地として世界中のファンが訪れる。早朝が混まない。" },
      { type: "heading", content: "稲村ヶ崎から電車と富士山を撮る", level: 2 },
      { type: "text", content: "稲村ヶ崎駅から西に歩いて5分の海岸（稲村ヶ崎公園）からは、江ノ電の線路と富士山が同方向に見える。夕方に西の空が染まる時間帯に来ると、電車・海・富士山・夕日の全要素が1枚に収まる可能性がある。" },
      { type: "heading", content: "極楽寺駅は映画のセットのような無人駅", level: 2 },
      { type: "text", content: "極楽寺駅は江ノ電の中で最も小さく最も静かな駅で、桜の時期（3月下旬〜4月上旬）に桜と木造駅舎が重なる光景はSNSで定期的に話題になる。電車が来る瞬間を30分待つ価値がある。" },
    ],
    relatedArticleSlugs: ["kanagawa-enoshima-sunset", "kanagawa-shonan-beach-summer"],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "kanagawa-yokohama-jazz-bar",
    title: "横浜のジャズバーと夜の山下公園──港町の夜を音楽と散歩で過ごす大人の夜",
    description: "横浜にはジャズの音楽文化がある。戦後の占領期から続くジャズの街の夜を歩く方法。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-09-28",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kanagawa",
    tags: ["横浜", "ジャズ", "夜", "バー", "大人旅"],
    spotIds: [],
    sections: [
      { type: "heading", content: "関内のジャズスポットは戦後から続く", level: 2 },
      { type: "text", content: "横浜市関内エリアは戦後の米軍占領期にジャズクラブが多数生まれた場所だ。現在も「Dolphy」（関内）はライブミュージックを毎晩行う老舗で、チャージ¥1,500〜でプロの生演奏が聴ける。20時台のステージが入りやすい。" },
      { type: "heading", content: "山下公園の夜はライトアップが静かに美しい", level: 2 },
      { type: "text", content: "ジャズの後は山下公園の夜の散歩に移動するのが横浜の大人の夜の定番動線だ。氷川丸のライトアップと横浜港の光が水面に映る光景は、観光客が帰った21時以降が最も静かで美しい。" },
      { type: "heading", content: "ホテルニューグランドのバーで締める", level: 2 },
      { type: "text", content: "山下公園前のホテルニューグランド（1927年開業）のバーはプリン・スパゲッティ・ドリア発祥の地として知られる。カクテル¥2,000〜で、歴史的ホテルのバーカウンターに座る体験は横浜の夜を完成させる。" },
    ],
    relatedArticleSlugs: ["kanagawa-yokohama-bay-walk", "kanagawa-yokohama-minatomirai-night"],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-great-hiking",
    title: "箱根のハイキングコース──明神ヶ岳・金時山・台ヶ岳で富士山を歩いて見る",
    description: "箱根の山は温泉と乗り物だけではない。歩いて登った先にしか見えない富士山がある。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-06-28",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kanagawa",
    tags: ["箱根", "ハイキング", "登山", "富士山", "金時山"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "金時山は1時間半で富士山の正面に立てる", level: 2 },
      { type: "text", content: "金時山（1,212m）は仙石原バス停から登山口まで徒歩10分、山頂まで往復3時間のコースだ。山頂に2軒の茶屋があり、「金時娘の茶屋」のあんぜんころもち（¥400）は登山者の定番。晴れた日の富士山は遮るものがない。" },
      { type: "heading", content: "明神ヶ岳は縦走コースの入口", level: 2 },
      { type: "text", content: "明神ヶ岳（1,169m）は明星ヶ岳へ続く尾根縦走コースの起点で、稜線からの富士山と箱根外輪山のパノラマが箱根ハイキングで最も広大な眺望だ。宮城野橋バス停から往復5時間、体力中級者向け。" },
      { type: "heading", content: "下山後の箱根湯本の温泉で全回復", level: 2 },
      { type: "text", content: "ハイキング後に箱根湯本の日帰り温泉施設「天成園」（¥1,800）か「箱根湯本温泉・ホテル南風荘」の立ち寄り湯（¥1,000）で入浴すると、全身の筋肉疲労が溶ける。登山×温泉の組み合わせは箱根の真骨頂だ。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-fuji-view", "kanagawa-hakone-solo-day-trip"],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "kanagawa-kamakura-zen-experience",
    title: "鎌倉の座禅体験──建長寺・円覚寺・東慶寺で本物の禅に触れる",
    description: "鎌倉は日本の禅宗発展の地だ。観光ではなく体験として、本物の僧侶と坐禅を組む朝がある。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kanagawa",
    tags: ["鎌倉", "座禅", "禅", "建長寺", "円覚寺"],
    spotIds: [],
    sections: [
      { type: "heading", content: "建長寺の日曜座禅会は予約不要", level: 2 },
      { type: "text", content: "鎌倉五山第1位の建長寺（¥500）では毎週日曜8〜10時に座禅会が行われており、予約不要・無料で参加できる（拝観料は必要）。本格的な臨済宗の道場で、外国人参加者も多い。参加するなら動きやすい服装が必要。" },
      { type: "heading", content: "円覚寺の暁天坐禅は早朝5時30分から", level: 2 },
      { type: "text", content: "北鎌倉の円覚寺では早朝5時30分から「暁天坐禅」が行われ、本格的な禅の雰囲気を体験できる。費用は¥500程度。夜明け前の境内を歩き、方丈の畳の上で30〜40分の坐禅を組む体験は旅行の意味を変える。" },
      { type: "heading", content: "東慶寺の境内は花と禅が同居する空間", level: 2 },
      { type: "text", content: "北鎌倉の東慶寺（¥200）は「縁切り寺」として知られた尼寺で、境内には梅・スイセン・イワタバコ等の花が季節ごとに咲く。坐禅会は不定期だが、静かな境内を歩くだけで禅の空気が体に入ってくる。" },
    ],
    relatedArticleSlugs: ["kanagawa-kamakura-bamboo-grove", "kanagawa-kamakura-tsurugaoka-walk"],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "kanagawa-hakone-rainy-day",
    title: "雨の箱根──温泉・美術館・カフェで雨を楽しむ完全プラン",
    description: "箱根は晴れの日より雨の日が面白い。霧に包まれた仙石原と露天風呂の雨音は、晴れ日にはない体験だ。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-06-12",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kanagawa",
    tags: ["箱根", "雨の日", "温泉", "美術館", "仙石原"],
    spotIds: ["hakone-onsen"],
    sections: [
      { type: "heading", content: "雨の仙石原は霧が出て別の景色になる", level: 2 },
      { type: "text", content: "仙石原のすすき草原は晴れていれば富士山が見えるが、雨の日は霧に包まれて別の幻想的な景色になる。10月下旬〜11月の雨の日は霧とすすきの黄金色が混ざり、誰もいない野原を独占できる。" },
      { type: "heading", content: "ポーラ美術館は雨の日に特に美しい", level: 2 },
      { type: "text", content: "ポーラ美術館は建物全体が森の斜面に埋め込まれており、雨の日は自然光の入り方が変化して展示の印象が晴れの日と違う。モネの睡蓮が雨の外の緑と内部照明のコントラストで見ると、まったく違う表情になる。" },
      { type: "heading", content: "雨の日こそ露天風呂の価値が上がる", level: 2 },
      { type: "text", content: "露天風呂は雨の日に最高の価値を発揮する。雨音と湯煙が重なる空間は、晴れた日には体験できない温泉の本質がある。宿の庭に木が多いほど雨の日の露天は美しくなる。強羅・仙石原エリアの旅館を選ぶ理由はここにある。" },
    ],
    relatedArticleSlugs: ["kanagawa-hakone-onsen-guide", "kanagawa-hakone-art-museum"],
  },
];
