import { Article } from "@/types/article";

export const kochiArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "kochi-katsurahama-sunset",
    title: "桂浜の夕暮れ──坂本龍馬像と太平洋が重なる、高知で最も感動的な時間",
    description: "龍馬像は昼間ではなく、夕日に染まる時間に見るべきだ。太平洋を背にした銅像が放つ孤独と志の気配を語る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-12",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kochi",
    tags: ["桂浜", "坂本龍馬", "夕日", "太平洋", "高知"],
    spotIds: ["katsurahama"],
    sections: [
      { type: "heading", content: "龍馬像は「夕方4時以降」に見ろ", level: 2 },
      { type: "text", content: "桂浜の坂本龍馬像は午前中に訪れる観光客が多いが、最も印象的な時間は夕方だ。西に傾く陽光が銅像を逆光で包み、太平洋を睨む龍馬の輪郭だけが浮かび上がる。海の轟音と夕焼けの中に立つと、幕末という時代の重さが肌で感じられる。" },
      { type: "spot-card", content: "katsurahama" },
      { type: "heading", content: "龍馬像の台座に登れる「龍馬に大接近」を活用する", level: 2 },
      { type: "text", content: "期間限定（年数回）で、龍馬像の台座に設置された展望台から、目の高さで龍馬と並ぶことができる。通常は地上から見上げるだけだが、この機会があれば龍馬の視線の先——太平洋の水平線——を同じ高さで見ることができる。日程は桂浜公園のウェブサイトで要確認。" },
      { type: "heading", content: "桂浜水族館は「土佐犬と握手」できる唯一の施設", level: 2 },
      { type: "text", content: "桂浜に隣接する桂浜水族館は、カツオやウミガメの展示に加え、土佐犬との握手体験が名物になっている。土佐犬は日本の国産闘犬だが、実際に触れると意外に穏やかな性格。龍馬像と水族館をセットで回るのが桂浜の正解ルートだ。" },
    ],
    relatedArticleSlugs: ["kochi-hirome-market-guide", "kochi-katsuo-tataki-perfect"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "kochi-katsuo-tataki-perfect",
    title: "カツオのたたき完全入門──わら焼きの煙と皮目の焦げが、高知でしか食べられない理由",
    description: "スーパーのたたきとは別物だ。わら焼きの炎で瞬時に焼き上げるカツオのたたきは、高知の哲学が詰まった料理だ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-02-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kochi",
    tags: ["カツオのたたき", "わら焼き", "高知グルメ", "郷土料理", "高知"],
    spotIds: ["katsurahama"],
    sections: [
      { type: "heading", content: "わら焼きと機械焼きでは別の料理になる", level: 2 },
      { type: "text", content: "高知のカツオのたたきは「わら焼き」が正統だ。稲わらを束ねて燃やし、1,000度近い炎でカツオの表面を数秒で焼く。炭火や機械焼きとは煙の質と焦げ目の香りが全く違う。皮の直下の脂が煙を吸い、独特のスモーキーさが生まれる。高知市内のほとんどの居酒屋でわら焼きのたたきが食べられる。" },
      { type: "heading", content: "「塩たたき」を選べ、ポン酢より本物に近い", level: 2 },
      { type: "text", content: "高知県民が食べるカツオのたたきはポン酢ではなく塩が基本だ。粗塩を振り、ニンニクと生姜を乗せ、青ねぎを散らす。カツオ本来の旨みと塩の鋭さが直接ぶつかる食べ方で、最初に一切れは何も付けずに食べると、わら焼きの香りが最もクリアに伝わる。" },
      { type: "heading", content: "ひろめ市場の藁焼きたたきを昼から食べる", level: 2 },
      { type: "text", content: "高知城近くの「ひろめ市場」は地元民も観光客も入り混じる屋台村形式の市場。「明神丸」のカウンターでわら焼きのたたきが実演されており、焼き上がった直後のものを食べられる。昼11時の開店直後は比較的空いている。生ビールと一緒にというのが高知流だ。" },
    ],
    relatedArticleSlugs: ["kochi-hirome-market-guide", "kochi-shimanto-river-journey"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "kochi-hirome-market-guide",
    title: "ひろめ市場の歩き方──高知の台所で地酒と郷土料理を昼から楽しむ作法",
    description: "ひろめ市場は観光地ではなく、高知の人が昼から飲む場所だ。土佐の食と酒の全てがここに圧縮されている。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kochi",
    tags: ["ひろめ市場", "高知グルメ", "土佐料理", "地酒", "高知"],
    spotIds: ["katsurahama"],
    sections: [
      { type: "heading", content: "席を先に確保してから注文に行く", level: 2 },
      { type: "text", content: "ひろめ市場の中央にはテーブルと椅子が並ぶ共用スペースがある。複数の屋台から料理を買ってきてここで食べるスタイルで、席は自由だ。週末の昼は満席になるため、荷物で席を確保してから料理を調達する。「場所取りするか確認してから動く」が鉄則。" },
      { type: "heading", content: "四万十川の青さ海苔と鮎の塩焼きも頼め", level: 2 },
      { type: "text", content: "カツオのたたき以外に食べるべきは、四万十川産の青さ海苔の天ぷらと鮎の塩焼き。青さ海苔は磯の香りが強烈で、天ぷらにすると香りが凝縮される。鮎は身が締まり、苦みのある内臓ごと食べるのが流儀。土佐の地酒「土佐鶴」と「司牡丹」は辛口で魚料理に合う。" },
      { type: "heading", content: "「べろ」文化：高知の昼飲みは文化である", level: 2 },
      { type: "text", content: "高知には「べろ」と呼ばれる昼飲みの文化が根付いている。ひろめ市場の中は平日の昼12時でも地元民がビールを飲んでいる。観光客が後ろめたさを感じる必要はない。高知という場所では、昼から飲むことは歓迎される行動だ。この文化に参加するためにひろめ市場に来ると言っても過言ではない。" },
    ],
    relatedArticleSlugs: ["kochi-katsuo-tataki-perfect", "kochi-ryoma-history-trail"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "kochi-shimanto-river-journey",
    title: "四万十川の「最後の清流」を旅する──沈下橋とカヌーと川魚が教えてくれること",
    description: "四万十川は遠い。だから来た人だけが知る静けさがある。沈下橋から青い水面を見下ろす感覚は、写真では伝わらない。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-08",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kochi",
    tags: ["四万十川", "沈下橋", "カヌー", "清流", "高知"],
    spotIds: ["shimanto-river"],
    sections: [
      { type: "heading", content: "沈下橋に欄干がない理由：洪水に流されないための知恵", level: 2 },
      { type: "text", content: "四万十川には47本の沈下橋（欄干のない橋）がある。増水時に橋が沈んでも流されないよう、あえて欄干を付けない設計だ。岩間沈下橋は撮影スポットとして有名で、朝霧が立ち込める早朝に橋の上に立つと、川の上に浮かんでいるような錯覚を覚える。" },
      { type: "spot-card", content: "shimanto-river" },
      { type: "heading", content: "カヌーで川を下ると「最後の清流」の意味が分かる", level: 2 },
      { type: "text", content: "四万十川をカヌーで下るツアーは1時間5,000円〜で複数の業者が提供している。水面から見る川岸の竹林と山の連なりは、陸上からとは全く違う世界だ。透明な水の中を鮎やウナギが泳ぐのが見える。「最後の清流」という言葉の意味はカヌーに乗って初めて実感できる。" },
      { type: "heading", content: "四万十川の川魚料理は「鮎の塩焼き」だけではない", level: 2 },
      { type: "text", content: "四万十川流域の食堂では鮎の塩焼きのほか、テナガエビの唐揚げ、川海苔の佃煮、ウナギの蒲焼きが名物だ。「四万十屋」（中村市内）は川を眺めながら川魚料理を食べられる。観光シーズンは予約必須。川魚は「新鮮さが命」なので、帰りに川魚の缶詰を土産にするのが正解。" },
    ],
    relatedArticleSlugs: ["kochi-muroto-cape-guide", "kochi-katsurahama-sunset"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "kochi-muroto-cape-guide",
    title: "室戸岬に行くべき理由──弘法大師が修行した断崖と、世界ジオパークの絶景",
    description: "室戸岬は遠くて不便だ。それが正解だ。交通の不便さが守ってきた荒々しい自然と宗教的な空気を伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kochi",
    tags: ["室戸岬", "弘法大師", "ジオパーク", "四国八十八箇所", "高知"],
    spotIds: ["muroto-cape"],
    sections: [
      { type: "heading", content: "室戸岬は「弘法大師が悟りを開いた場所」だ", level: 2 },
      { type: "text", content: "室戸岬の御厨人窟（みくろど）は、空海（弘法大師）が若年期に修行した洞窟だ。洞窟の中から見える空と海が「空海」という法名の由来になったという伝説がある。現在も立ち入ることができ、洞窟の奥から見上げると、わずかな空と太平洋の蒼が切り取られる。霊的な場所に無神論者でも何かを感じるはずだ。" },
      { type: "spot-card", content: "muroto-cape" },
      { type: "heading", content: "室戸ユネスコ世界ジオパーク：岩が語る1400万年の歴史", level: 2 },
      { type: "text", content: "室戸岬周辺は室戸ユネスコ世界ジオパークに認定されている。岬の先端には海底から隆起した巨大な奇岩が並び、波が直接打ちつける。地質学的に「付加体」と呼ばれる海洋地殻の断片が地表に出ており、1,400万年以上前の海の底を歩くことができる。岩の上に立つと足元が遠い時間と繋がる感覚がある。" },
      { type: "heading", content: "室戸岬灯台から太平洋の孤独に触れる", level: 2 },
      { type: "text", content: "室戸岬灯台（1899年初点灯）は日本の灯台の中でもレンズが大きい一等灯台だ。灯台の周囲から見る太平洋は、岬の先端という地形のため360度近く海が広がる。霧の日は灯台の霧笛が鳴り、その音が岩場に反響する。室戸岬に来た旅行者の大半が見ていない「真の孤独の景色」がここにある。" },
    ],
    relatedArticleSlugs: ["kochi-shimanto-river-journey", "kochi-katsurahama-sunset"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "kochi-ryoma-history-trail",
    title: "坂本龍馬の足跡を辿る高知1日コース──生家から桂浜まで、幕末志士の原点を歩く",
    description: "高知は龍馬が生まれた場所だ。生家跡、龍馬の生まれた町記念館、桂浜を繋ぐ半日コースで、幕末の空気を体感する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kochi",
    tags: ["坂本龍馬", "幕末", "歴史", "高知城", "高知"],
    spotIds: ["katsurahama"],
    sections: [
      { type: "heading", content: "午前：上町の龍馬生家跡と「龍馬の生まれた町記念館」", level: 2 },
      { type: "text", content: "高知市上町は龍馬が幼少期を過ごした旧・坂本家のあった地域。現在は「龍馬の生まれた町記念館」があり、幕末の高知の街並みを再現した展示で龍馬が見た世界を体感できる。近隣の才谷屋（坂本家の本家）跡の石碑も見落とさないこと。" },
      { type: "spot-card", content: "katsurahama" },
      { type: "heading", content: "昼：高知城と追手筋の日曜市でエネルギー補給", level: 2 },
      { type: "text", content: "高知城は現存12天守のひとつで、本丸御殿も現存するという全国でも珍しい城だ。天守からは高知市街が一望できる。日曜日に訪れるなら、追手筋で開催される「日曜市」（日本最長クラスの露天市）で高知の野菜や土産を物色するのが正解。" },
      { type: "heading", content: "夕方：桂浜で太平洋を背にした龍馬像に向き合う", level: 2 },
      { type: "text", content: "コースの締めは桂浜の龍馬像だ。像は台座を含めて13mあり、太平洋を真剣な眼差しで睨んでいる。龍馬は33歳で暗殺された。その短い生涯の間に、薩長同盟、大政奉還の斡旋という歴史を動かした。像の前に立って海を見ると、志と時代の話が体に入ってくる。" },
    ],
    relatedArticleSlugs: ["kochi-katsurahama-sunset", "kochi-hirome-market-guide"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "kochi-seasonal-whale-watching",
    title: "土佐湾のホエールウォッチング──日本屈指の鯨の海で、巨大生物と出会う",
    description: "土佐湾は黒潮が直接ぶつかる場所で、ニタリクジラが高確率で見られる日本屈指の鯨の海だ。4〜10月限定の体験を伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-02",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kochi",
    tags: ["ホエールウォッチング", "クジラ", "土佐湾", "黒潮", "高知"],
    spotIds: ["muroto-cape"],
    sections: [
      { type: "heading", content: "土佐湾は「ニタリクジラ遭遇率」が日本一クラス", level: 2 },
      { type: "text", content: "土佐湾でのホエールウォッチングは4月〜10月が最盛期。黒潮本流が沿岸に接近するため、ニタリクジラ・マッコウクジラ・スジイルカの群れに高確率で遭遇する。室戸市のウォッチングツアー（所要約3時間・1万円前後）の遭遇率は90%超と言われる。波が穏やかな早朝出航便が最も遭遇率が高い。" },
      { type: "spot-card", content: "muroto-cape" },
      { type: "heading", content: "船酔い対策は「船の中央前方に立つ」が鉄則", level: 2 },
      { type: "text", content: "ホエールウォッチングの船は揺れる。酔い止め薬を出発2時間前に飲むこと。船上では中央前方（ブリッジ近く）に立つと揺れが少ない。後部デッキは波をかぶることもある。クジラを見つけたら静かに待つ。船のエンジン音がクジラを驚かせるため、ガイドの指示に従うことが遭遇率を高める。" },
      { type: "heading", content: "室戸岬とセットで「黒潮の旅」を完成させる", level: 2 },
      { type: "text", content: "ホエールウォッチングツアーは室戸市発着が多い。午前中にウォッチングツアーに参加し、午後に室戸岬の御厨人窟と灯台を巡れば、黒潮が支配する海岸線の一日が完成する。室戸市内の食堂では黒潮で育った魚介の新鮮な刺身定食が1,000円台で食べられる。" },
    ],
    relatedArticleSlugs: ["kochi-muroto-cape-guide", "kochi-shimanto-river-journey"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "kochi-onsen-budono-yado",
    title: "土佐の隠れ湯と山の宿──高知の秘湯と自然の中で泊まる完全ガイド",
    description: "高知の温泉は目立たない。だから知る人だけが静かに通い続けている。四万十川流域と高知市周辺の秘湯を案内する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "kochi",
    tags: ["高知温泉", "秘湯", "四万十", "山の宿", "高知"],
    spotIds: ["shimanto-river"],
    sections: [
      { type: "heading", content: "土佐和紙の里「いの町」の温泉：高知市から最も近い癒し", level: 2 },
      { type: "text", content: "高知市内から車で30分ほどのいの町周辺には、仁淀川沿いの日帰り温泉施設が点在する。「あいの里 仁淀川」は単純弱放射能泉で、ぬるめの湯が長湯向きだ。仁淀川（日本最高クラスの清流）を見下ろす露天風呂があり、青い川面を眺めながら入る体験は他にない。" },
      { type: "spot-card", content: "shimanto-river" },
      { type: "heading", content: "四万十川沿いの宿：夜は川音だけが聞こえる", level: 2 },
      { type: "text", content: "四万十川流域の宿は民宿・ゲストハウス系が多く、1泊2食付きで8,000円前後が相場。夜は川音以外の音がない。早朝に宿から歩いて沈下橋まで行くと、朝霧の中に橋が浮かんでいる景色に出会える。これは四万十川に泊まった人だけの特権だ。" },
      { type: "heading", content: "高知龍馬空港から四万十まで：移動時間を逆手に取る", level: 2 },
      { type: "text", content: "高知空港から四万十川（中村地区）まで車で約1時間30分〜2時間かかる。この移動時間を「土佐の山道ドライブ」として楽しむのが正解だ。仁淀川沿いの国道には展望台や道の駅が点在し、途中で仁淀ブルーと呼ばれる青い川を車窓から何度も見ることができる。" },
    ],
    relatedArticleSlugs: ["kochi-shimanto-river-journey", "kochi-muroto-cape-guide"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "kochi-budget-solo-travel",
    title: "高知を1泊2日・予算2万円で旅する──安くて濃い土佐旅の全スケジュール",
    description: "高知は「食と酒と自然」さえあれば満足できる場所だ。ひろめ市場・桂浜・四万十川を2万円以内で回る現実的なプランを提示する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "kochi",
    tags: ["高知旅行", "節約旅", "一人旅", "1泊2日", "高知"],
    spotIds: ["katsurahama", "shimanto-river"],
    sections: [
      { type: "heading", content: "1日目：高知市内をひろめ市場と高知城でコンパクトに制覇", level: 2 },
      { type: "text", content: "飛行機で高知龍馬空港着（11:00前後）→バスで高知市内（30分）→高知城（¥420）→昼食はひろめ市場（¥1,500）→桂浜（バス往復¥1,400）→夜は帯屋町のスーパーで惣菜購入or地元居酒屋（¥2,000）→ゲストハウス泊（¥3,500）。合計¥8,820前後。" },
      { type: "spot-card", content: "katsurahama" },
      { type: "heading", content: "2日目：レンタサイクルで仁淀川沿いを走る", level: 2 },
      { type: "text", content: "朝食は高知駅前のコンビニ（¥500）→JRで伊野駅（¥360）→仁淀川沿いのサイクリングを3時間（無料）→昼食は地元食堂のカツオ定食（¥900）→JRで高知空港方面へ→お土産はひろめ市場周辺の地酒ミニボトル（¥1,500）→帰路。2日目合計¥3,260。" },
      { type: "heading", content: "高知の一人旅コスパ：交通費を制するが鍵", level: 2 },
      { type: "text", content: "高知の公共交通は路線バスとJRが中心で、本数が少ない。「とさでん交通1日乗り放題券（¥800）」を活用すると市内の路面電車が乗り放題になる。レンタカーは1日4,000円〜で借りられ、四万十川など郊外へ行く場合はむしろ車の方が効率的でコスパが良い。" },
    ],
    relatedArticleSlugs: ["kochi-hirome-market-guide", "kochi-katsuo-tataki-perfect"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "kochi-couple-ryoma-romance",
    title: "高知カップル旅の決定版──龍馬ゆかりの地と太平洋の夕日で演出する最高の2日間",
    description: "高知は壮大だ。広い太平洋と雄大な四万十川が、2人の旅に広がりを与える。カップルで行く高知の正解ルートを提案する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kochi",
    tags: ["カップル旅行", "高知", "四万十川", "桂浜", "夕日"],
    spotIds: ["katsurahama", "shimanto-river", "muroto-cape"],
    sections: [
      { type: "heading", content: "1日目：高知城と桂浜の夕日でドラマチックなオープニング", level: 2 },
      { type: "text", content: "午前に高知城を2人で観覧し、天守から市街を眺めてから昼食はひろめ市場でカツオのたたきと地酒を楽しむ。夕方は桂浜へ移動。龍馬像を見た後、海岸で日が沈むまで波音を聞きながら話す時間をつくる。浜辺の夕日は言葉がいらない。" },
      { type: "spot-card", content: "katsurahama" },
      { type: "heading", content: "2日目：四万十川で2人だけのカヌー体験", level: 2 },
      { type: "text", content: "朝に高知市を出発し、車で約1時間30分で四万十川の中流域（四万十市）へ。2人乗りカヌーツアーに参加すると、川面から見える山の稜線と沈下橋が記念写真に最高だ。川魚料理の昼食後、岩間沈下橋の上で夕日を待つ。橋の上から見る夕焼けの川面は、この旅の最高の瞬間になる。" },
      { type: "heading", content: "高知の宿選び：2人で泊まるなら川沿い旅館一択", level: 2 },
      { type: "text", content: "四万十川沿いの旅館は1泊2食付きで1人1万5,000円前後が相場。部屋の窓から川が見える宿を選ぶと、夜中に川音で目覚める体験ができる。朝は早起きして沈下橋まで2人で散歩し、朝霧の川を見るのが四万十川の宿泊旅の正解だ。" },
    ],
    relatedArticleSlugs: ["kochi-shimanto-river-journey", "kochi-katsurahama-sunset"],
  },
];
