import { Article } from "@/types/article";

export const kumamotoArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "kumamoto-castle-restoration",
    title: "熊本城、復興の現在──2016年地震から8年、黒い天守が語る城と市民の絆",
    description: "熊本城は崩れた。しかし諦めなかった。今も続く修復工事を「見学する」体験は、完成した城とは全く違う感動を生む。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kumamoto",
    tags: ["熊本城", "復興", "2016年地震", "城", "熊本"],
    spotIds: ["kumamoto-castle"],
    sections: [
      { type: "heading", content: "2021年に天守閣が再開：見学できる内部展示の見どころ", level: 2 },
      { type: "text", content: "2016年の熊本地震で石垣が崩壊し、大きく傾いた天守は2021年に内部公開が再開した。内部展示は6階建てで、各フロアに城の歴史と震災の記録が展示されている。震災時の崩壊した石垣の写真と、復元後の石垣を見比べると、城大工と石工の技術の高さが伝わる。" },
      { type: "spot-card", content: "kumamoto-castle" },
      { type: "heading", content: "「武者返し」の石垣：登れない理由は設計の天才性にある", level: 2 },
      { type: "text", content: "熊本城の石垣「武者返し」は下部が緩やかな勾配で、上部になるにつれて急勾配かつ反り返る設計だ。敵が登り始めると中腹で傾斜が急になり転落する。加藤清正が考案した石垣の逆曲線は、数学的な計算なしに経験と直感で完成させた技術とされる。震災でこの石垣の一部が崩れ、修復に石一つを元の位置に戻す作業が続けられている。" },
      { type: "heading", content: "二の丸広場：全体を見渡す最高の撮影ポジション", level: 2 },
      { type: "text", content: "熊本城天守の撮影は二の丸広場（入場無料エリア）からが最も構図が良い。広場の芝生から見上げると石垣・天守・青空が一枚に収まる。桜の季節（3月下旬〜4月上旬）は二の丸広場の桜並木と天守が重なり、全国の城の中でも特に人気の花見スポットになる。" },
    ],
    relatedArticleSlugs: ["kumamoto-aso-caldera-drive", "kumamoto-ramen-guide"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "kumamoto-aso-caldera-drive",
    title: "阿蘇カルデラドライブ──世界最大の火口が生む草原と噴煙の絶景ルート",
    description: "阿蘇は走らないと分からない。カルデラの縁をなぞるミルクロードと草千里ヶ浜を繋ぐドライブルートは、地球の大きさを体感させる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-25",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kumamoto",
    tags: ["阿蘇山", "ドライブ", "カルデラ", "草千里ヶ浜", "熊本"],
    spotIds: ["aso-mountain"],
    sections: [
      { type: "heading", content: "ミルクロード：カルデラの縁を走る尾根道", level: 2 },
      { type: "text", content: "ミルクロード（国道212号）はカルデラ（外輪山）の頂部を走る道路で、右手にカルデラ内の平原、左手に外輪山の急斜面が交互に見える。大観峰展望台からは阿蘇五岳（根子岳・高岳・中岳・烏帽子岳・杵島岳）が「涅槃の姿（仏が横たわる姿）」に見える角度で有名だ。" },
      { type: "spot-card", content: "aso-mountain" },
      { type: "heading", content: "草千里ヶ浜：モンゴルと見紛う草原に馬が放牧される", level: 2 },
      { type: "text", content: "草千里ヶ浜は阿蘇中岳の山腹にある直径約1kmの草原で、中央に丸い池がある。阿蘇の馬（草原馬）が自由に放牧されており、馬の背後に噴煙を上げる中岳が重なる景色はモンゴルの草原と見分けがつかないほど広大だ。晴れた日の青空と緑の草原と白い噴煙の対比が完璧だ。" },
      { type: "heading", content: "中岳火口：噴火警戒レベルを確認してから向かう", level: 2 },
      { type: "text", content: "阿蘇中岳の火口は噴火警戒レベルによって立入可能エリアが変わる。旅行前に気象庁の阿蘇山火口情報を確認すること。レベル1（平常）の時は火口ギリギリまで歩いて行けるが、レベル2以上は立入規制がある。火口に近づくとマスク着用を推奨（亜硫酸ガス対策）。エメラルドグリーンの火口湖は「条件が合えば」だけに価値がある。" },
    ],
    relatedArticleSlugs: ["kumamoto-kurokawa-onsen-guide", "kumamoto-castle-restoration"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "kumamoto-kurokawa-onsen-guide",
    title: "黒川温泉の正しい楽しみ方──入湯手形で3か所を回る湯めぐりの全手順",
    description: "黒川温泉は「入湯手形」というシステムが独特だ。3か所の露天風呂を選んで回る仕組みと、渓谷の旅館の選び方を全て伝える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-02-08",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "kumamoto",
    tags: ["黒川温泉", "入湯手形", "湯めぐり", "露天風呂", "熊本"],
    spotIds: ["kurokawa-onsen"],
    sections: [
      { type: "heading", content: "入湯手形の仕組み：¥1,600で3か所選べるシステム", level: 2 },
      { type: "text", content: "黒川温泉の入湯手形（¥1,600）は参加旅館・施設30軒以上の中から3か所を選んで入湯できる木製のお守り型チケットだ。温泉街の旅館フロントや案内所で購入できる。有効期間は6ヶ月で、3か所を一日で回っても良いし、複数日に分けても良い。温泉の泉質・湯船の形状（岩風呂・檜風呂・洞窟風呂など）が宿ごとに異なり、全く違う入浴体験ができる。" },
      { type: "spot-card", content: "kurokawa-onsen" },
      { type: "heading", content: "早朝の黒川温泉：霧と川音だけの別世界", level: 2 },
      { type: "text", content: "黒川温泉の最高の時間は早朝6〜8時だ。田の原川の渓谷に霧が立ち込め、温泉街の屋根や木々が霞の中に浮かぶ。この時間帯に浴衣で外湯に向かう宿泊者だけが体験できる景色だ。温泉街のどの道も舗装されており、下駄で歩ける。朝食前に2か所を回るのが黒川温泉の正統な楽しみ方だ。" },
      { type: "heading", content: "秋の紅葉シーズンの予約：3ヶ月前が最低ライン", level: 2 },
      { type: "text", content: "黒川温泉は10月中旬〜11月中旬の紅葉シーズンが最も人気が高く、渓谷の露天風呂と紅葉の組み合わせを目当てに全国から予約が入る。この時期は3ヶ月前でも希望の宿が埋まっていることがある。「旅荘 山の宿」「いやしの里 笑顔」など人気宿は半年前に予約する常連客もいる。" },
    ],
    relatedArticleSlugs: ["kumamoto-aso-caldera-drive", "kumamoto-amakusa-island"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "kumamoto-ramen-guide",
    title: "熊本ラーメン徹底解剖──豚骨に焦がしニンニクが加わる「熊本スタイル」の真髄",
    description: "熊本ラーメンは博多ラーメンでも鹿児島ラーメンでもない。マー油（焦がしニンニクラード）が生む独自の香りと深みを正確に語る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-02-22",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kumamoto",
    tags: ["熊本ラーメン", "マー油", "豚骨", "グルメ", "熊本"],
    spotIds: ["kumamoto-castle"],
    sections: [
      { type: "heading", content: "マー油とは何か：焦がしニンニクラードが変える豚骨の次元", level: 2 },
      { type: "text", content: "熊本ラーメンの最大の特徴は「マー油」だ。ニンニクを黒くなるまで焦がし、ラードと合わせた黒い油をスープに垂らす。これが博多豚骨との最大の違いだ。焦げニンニクの香ばしさがスープの重厚感を増幅し、麺を食べ終えた後も香りが口の中に残る。細麺と太麺の中間の「中細麺」を使う店が多い。" },
      { type: "heading", content: "熊本ラーメンの2大流派：「こむらさき」系と「味千」系", level: 2 },
      { type: "text", content: "熊本ラーメンには「こむらさき」（1954年創業・豚骨に鶏ガラを加えた濃厚系）と「味千ラーメン」（1968年創業・全国展開の標準的熊本ラーメン）の2大流派がある。観光客が食べるべきは創業店の「こむらさき下通店」で、スープの複雑さと熊本ラーメンの原型を確認できる。" },
      { type: "heading", content: "熊本ラーメンの作法：辛子高菜の量と投入タイミング", level: 2 },
      { type: "text", content: "熊本ラーメンのテーブルには辛子高菜とニンニクの薬味が必ず置かれている。最初の一口は何も入れずにスープ本来の味を確認し、2口目以降に少量の辛子高菜を溶かしながら食べる。ニンニクは生で入れると香りが強烈になるため、マー油と別の焦げニンニクが好みに合わない場合は少量から試すこと。" },
    ],
    relatedArticleSlugs: ["kumamoto-basashi-horse-meat-guide", "kumamoto-castle-restoration"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "kumamoto-basashi-horse-meat-guide",
    title: "馬刺しの真実──熊本が日本一の馬肉消費地である理由と、正しい食べ方",
    description: "馬肉は臭くない。新鮮な熊本の馬刺しは上質な牛刺しより旨い。生姜醤油で食べる作法と、スーパーで買える安い店の探し方。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kumamoto",
    tags: ["馬刺し", "馬肉", "熊本グルメ", "郷土料理", "熊本"],
    spotIds: ["suizenji-garden"],
    sections: [
      { type: "heading", content: "なぜ熊本は馬刺し文化なのか：加藤清正と戦国時代の食", level: 2 },
      { type: "text", content: "熊本に馬刺し文化が根付いた理由は、加藤清正の時代に戦場での緊急食料として馬肉を食べる習慣が広まったという説がある。九州では阿蘇の草原で馬が多く育てられており、食料としての歴史が長い。現在、熊本は日本の馬肉消費量の約40%を占める最大の生産・消費地だ。" },
      { type: "spot-card", content: "suizenji-garden" },
      { type: "heading", content: "馬刺しの部位と食べ方：赤身・中トロ・タテガミの違い", level: 2 },
      { type: "text", content: "馬刺しは部位によって全く異なる食感と味になる。赤身（ロース・モモ）は脂が少なく鉄分を感じる濃い味。中トロ（カシラ）は適度な脂でバランスが良い。タテガミ（首の脂身）は白い塊で、さっぱりした甘みがある。生姜と醤油（ニンニク醤油でも可）で食べるのが熊本流で、ワサビ醤油は熊本では使わない。" },
      { type: "heading", content: "熊本市内の馬刺し入手法：スーパーが最もコスパが高い", level: 2 },
      { type: "text", content: "熊本の地元スーパー「鮮Do！（フレッシュドー）」や「ロッキー」では、居酒屋の半額〜3分の1の価格で新鮮な馬刺しが買える。旅行者がスーパーで馬刺しを買ってホテルの部屋で食べるのは熊本流の賢い旅の仕方だ。赤身200g・¥800前後で居酒屋の一人前分の量が買える。" },
    ],
    relatedArticleSlugs: ["kumamoto-ramen-guide", "kumamoto-castle-restoration"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "kumamoto-suizenji-garden",
    title: "水前寺成趣園の湧水と庭園──阿蘇の地下水が作り出す、熊本で最も静かな時間",
    description: "水前寺成趣園の池は阿蘇の伏流水が湧き出す。底まで見える透明な池を前にすると、熊本という土地の豊かさが一点に凝縮して見える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-03-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kumamoto",
    tags: ["水前寺成趣園", "湧水", "大名庭園", "阿蘇伏流水", "熊本"],
    spotIds: ["suizenji-garden"],
    sections: [
      { type: "heading", content: "水前寺成趣園の湧水：阿蘇から30kmを旅してきた水", level: 2 },
      { type: "text", content: "水前寺成趣園の池は阿蘇の伏流水が自然に湧き出す。降った雨が阿蘇火山の地下に浸透し、数十年かけて熊本市内に到達した水だ。池の透明度は高く、底の砂に水草が揺れているのが見える。この湧水が減少した2010年代に「水が止まった」と地元で話題になるほど、水前寺の池は熊本市民のシンボルだ。" },
      { type: "spot-card", content: "suizenji-garden" },
      { type: "heading", content: "東海道五十三次を模した築山：庭の中で旅をする", level: 2 },
      { type: "text", content: "水前寺成趣園の回遊式庭園は東海道五十三次の景色を縮小して再現したものだ。富士山を模した丘、三保の松原を表す松林、宿場町を表す石組みなどが順に配置され、池の周りを歩くと江戸から京都まで旅したような体験ができる設計になっている。池の反対側から見る「富士山の丘」と鯉の群れが最も絵になる。" },
      { type: "heading", content: "隣接する出水神社：能楽と細川藩の文化的遺産", level: 2 },
      { type: "text", content: "水前寺成趣園に隣接する出水神社は細川藩主を祀る神社で、能楽の舞台がある。毎年春と秋に薪能が開催され、庭園の池を背景に幽玄の舞が演じられる。普段は静かな神社だが、この時期だけ特別な空間になる。熊本市電の水前寺公園電停から徒歩すぐという立地が、熊本城観光との組み合わせを容易にする。" },
    ],
    relatedArticleSlugs: ["kumamoto-castle-restoration", "kumamoto-basashi-horse-meat-guide"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "kumamoto-amakusa-island",
    title: "天草への旅──九州本土から橋を渡った先に広がる、潜伏キリシタンとイルカの海",
    description: "天草は橋でしか渡れない島だ。5つの橋を渡るたびに青い海が広がり、島に入るとキリシタンの歴史と野生のイルカが待っている。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-12",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kumamoto",
    tags: ["天草", "キリシタン", "イルカ", "五橋", "熊本"],
    spotIds: ["kumamoto-castle"],
    sections: [
      { type: "heading", content: "天草五橋：5つの橋を渡るドライブが旅の序章", level: 2 },
      { type: "text", content: "天草諸島へのアクセスは「天草五橋」（天草パールライン）を渡る。三角（みすみ）から大矢野島・永浦島・大池島・前島を経て天草上島まで、5本の橋が海を越えていく。全長10km弱のドライブで、橋の上から見る東シナ海の青さと島々の景色は九州でも屈指のドライブルートだ。" },
      { type: "heading", content: "天草のイルカウォッチング：遭遇率90%超の野生イルカの海", level: 2 },
      { type: "text", content: "天草下島の牛深や有明周辺の海域には常時200頭以上のバンドウイルカが生息している。ウォッチングツアーは¥3,000〜5,000で遭遇率は90%以上とされる。イルカが船の波に乗って遊ぶ「バウライディング」を間近で見られる確率が高い。4〜10月がベストシーズンで、凪の日の午前中が最も波が穏やかだ。" },
      { type: "heading", content: "崎津集落：海辺に建つゴシック式天主堂の奇跡", level: 2 },
      { type: "text", content: "天草市崎津地区は世界遺産「長崎と天草地方の潜伏キリシタン関連遺産」の構成資産だ。漁師の集落に建つ「崎津天主堂」は海のすぐ隣に立つゴシック様式の教会で、内部の畳敷きの礼拝スタイルが独特。かつて漁師たちが禁教時代に舟小屋として使っていた場所が後に教会となった歴史がある。" },
    ],
    relatedArticleSlugs: ["kumamoto-kurokawa-onsen-guide", "kumamoto-castle-restoration"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "kumamoto-family-travel",
    title: "熊本の家族旅行完全プラン──阿蘇・熊本城・天草をこどもと楽しむ2泊3日",
    description: "熊本は子どもへの刺激が多い場所だ。活火山・復興する城・イルカと島という組み合わせは、教科書には載っていない体験を与える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "kumamoto",
    tags: ["熊本家族旅行", "子連れ旅", "阿蘇", "天草", "熊本"],
    spotIds: ["aso-mountain", "kumamoto-castle"],
    sections: [
      { type: "heading", content: "1日目：熊本城で復興の話を子どもにする", level: 2 },
      { type: "text", content: "熊本城の天守内展示は震災の記録が含まれており、地震がどれだけの力を持つかを実物で教えられる。石垣の修復作業を見学できるルートでは、石一つ一つに番号が刻まれて元の位置に戻される作業を子どもと一緒に観察できる。城内の「復興城主」制度の説明は、市民が城を守ろうとする物語として子どもに伝わりやすい。" },
      { type: "spot-card", content: "aso-mountain" },
      { type: "heading", content: "2日目：阿蘇で「地球の熱さ」を体感させる", level: 2 },
      { type: "text", content: "阿蘇中岳の噴煙（レベル1の場合）、草千里ヶ浜の馬との触れ合い、ロープウェイ（運行している場合）と子どもが喜ぶ要素が揃っている。草千里の馬は柵越しに触れられることもある。阿蘇火山博物館では噴火のメカニズムを映像と展示で学べ、子どもの科学的興味を刺激する内容だ。" },
      { type: "heading", content: "3日目：天草でイルカと泳ぐ", level: 2 },
      { type: "text", content: "天草のイルカウォッチングは子どもが最も興奮する体験だ。野生のイルカが船の周りで飛び跳ねる景色は映像で見るのとは全く違うスケール感がある。ツアー後は崎津の集落を散策し、海辺の教会という非日常の景観を子どもに見せる。帰路は天草五橋を渡りながら「さっき渡ってきた橋が向こうに見える」という旅の終わりを体感する。" },
    ],
    relatedArticleSlugs: ["kumamoto-amakusa-island", "kumamoto-aso-caldera-drive"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "kumamoto-couple-aso-onsen",
    title: "熊本カップル旅──阿蘇と黒川温泉で2泊3日、九州の自然が最大に輝く旅程",
    description: "阿蘇の噴煙と黒川の渓谷温泉。熊本は「自然と静寂」でカップルの旅を包む。2人が話したくなる景色が次々と現れる2泊3日を提案する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kumamoto",
    tags: ["熊本カップル旅", "阿蘇", "黒川温泉", "2泊3日", "熊本"],
    spotIds: ["aso-mountain", "kurokawa-onsen"],
    sections: [
      { type: "heading", content: "1日目：熊本城と市内グルメで熊本に入る", level: 2 },
      { type: "text", content: "熊本空港または熊本駅着→熊本城と水前寺成趣園を午後に散策（3〜4時間）→夕食は熊本市内の居酒屋で馬刺しと熊本ラーメン（¥4,000/2人）→熊本市内のホテル泊（¥15,000〜）。熊本城の夜間ライトアップ（季節による）を見てからホテルへ戻る。" },
      { type: "spot-card", content: "aso-mountain" },
      { type: "heading", content: "2日目：阿蘇をドライブして黒川温泉に泊まる", level: 2 },
      { type: "text", content: "午前に大観峰展望台（阿蘇カルデラの絶景）→草千里ヶ浜→中岳火口（条件次第）→ミルクロードを走って昼食は阿蘇の阿蘇牛バーガーかあか牛丼（¥1,500/人）→午後に黒川温泉に入り宿泊。入湯手形で2か所の外湯を浴衣で渡り歩く夕方の時間が最も黒川温泉らしい。" },
      { type: "heading", content: "3日目：黒川温泉の朝霧と最後の一湯", level: 2 },
      { type: "text", content: "早朝6〜7時に宿を出て、霧の渓谷を2人で散歩する。入湯手形の残り1枚で朝風呂に入り、宿での朝食後に帰路へ。時間があれば天草方面へドライブを延長するか、熊本市に戻って空港前に「ひご野菜のかき氷」（熊本のさっぱりスイーツ）を食べて旅を締めくくる。" },
    ],
    relatedArticleSlugs: ["kumamoto-kurokawa-onsen-guide", "kumamoto-aso-caldera-drive"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "kumamoto-budget-travel",
    title: "熊本1泊2日・予算1万5,000円──熊本城・阿蘇・ラーメンを節約旅で完全制覇",
    description: "熊本は公共交通が充実しているわけではないが、レンタカーを活用すれば1泊2日1万5,000円で主要スポットを全部回れる現実的な方法がある。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "kumamoto",
    tags: ["熊本節約旅", "1泊2日", "予算旅行", "レンタカー", "熊本"],
    spotIds: ["kumamoto-castle", "aso-mountain"],
    sections: [
      { type: "heading", content: "交通費の最適化：熊本空港レンタカーが最安構成", level: 2 },
      { type: "text", content: "熊本空港でのレンタカー（軽自動車・1日¥3,500〜）を使えば熊本城・阿蘇・黒川温泉を1〜2日で回れる。公共バスで阿蘇に行くと往復¥3,000前後で1日かかるため、3名以上ではレンタカーが圧倒的にコスパが良い。阿蘇の山道はカーナビ必須なので、スマートフォンのマップより車載ナビを使うこと。" },
      { type: "spot-card", content: "kumamoto-castle" },
      { type: "heading", content: "食費の最適化：スーパーの馬刺しと地元食堂の活用", level: 2 },
      { type: "text", content: "熊本市内のスーパーで馬刺し（¥800/200g）、熊本ラーメンは地元食堂で¥800〜。阿蘇エリアでは道の駅「阿蘇」の赤牛丼（¥1,300）が観光地価格の中では最もコスパが高い。黒川温泉の外湯は入湯手形（¥1,600）で3か所に入れるため、単体で入るより割安。" },
      { type: "heading", content: "宿泊費の最適化：熊本市内のビジネスホテルか阿蘇の民宿", level: 2 },
      { type: "text", content: "熊本市内のビジネスホテルは¥4,000〜¥6,000で泊まれる。阿蘇内牧温泉の民宿は1泊2食¥8,000前後で温泉付きというコスパが高い選択肢だ。黒川温泉は最低でも1泊¥12,000以上かかるため、節約旅では内牧温泉の民宿を代替として使うのが賢明だ。" },
    ],
    relatedArticleSlugs: ["kumamoto-ramen-guide", "kumamoto-castle-restoration"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "kumamoto-spring-cherry-blossoms",
    title: "熊本の春と桜──熊本城の花吹雪と水前寺成趣園の湧水が作る、九州最高の花見",
    description: "熊本の桜は城と庭園と火山を背景に咲く。3月下旬から4月上旬の10日間、熊本は全てが揃う場所になる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-18",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kumamoto",
    tags: ["熊本の桜", "お花見", "熊本城", "春旅行", "熊本"],
    spotIds: ["kumamoto-castle", "suizenji-garden"],
    sections: [
      { type: "heading", content: "熊本城の桜：二の丸広場から見る花吹雪×黒天守", level: 2 },
      { type: "text", content: "熊本城の桜の見頃は3月下旬〜4月上旬。二の丸広場の桜並木は200本以上で、ピンクの花びらと黒い天守の対比が圧倒的だ。早朝7時〜8時はほぼ無人で、花吹雪の中の天守を独り占めできる。夜間ライトアップ（19時〜21時頃）は桜と城が橙色の光で包まれる。" },
      { type: "spot-card", content: "kumamoto-castle" },
      { type: "heading", content: "水前寺成趣園の春：湧水池と桜の絶妙な組み合わせ", level: 2 },
      { type: "text", content: "水前寺成趣園の桜は池の水面に映るリフレクションが美しい。阿蘇の伏流水が湧き出す透明な池に桜の花びらが散ると、水面が花で覆われる時間がある。熊本城と同じ公共交通でアクセスでき、午前に城→午後に庭園という順路が効率的だ。" },
      { type: "heading", content: "阿蘇の山桜：噴煙を背景に咲く野生の桜", level: 2 },
      { type: "text", content: "阿蘇の山肌には野生の山桜（ヤマザクラ）が点在し、4月中旬に高地で咲く。草千里ヶ浜の入口付近に桜の木があり、カルデラの噴煙を背景に咲く構図は平地では絶対に見られない景色だ。満開時期は阿蘇のweb情報で確認。" },
    ],
    relatedArticleSlugs: ["kumamoto-castle-restoration", "kumamoto-suizenji-garden"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "kumamoto-luxury-aso-kurokawa",
    title: "熊本の贅沢な旅──阿蘇の高級ヴィラと黒川温泉の名旅館で過ごす、熊本最高峰の2泊3日",
    description: "阿蘇の火口を独占する絶景ヴィラと、黒川温泉の最高級旅館。熊本は贅沢に時間をかけると全く別の顔を見せる。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kumamoto",
    tags: ["熊本贅沢旅", "高級旅館", "阿蘇", "黒川温泉", "熊本"],
    spotIds: ["aso-mountain", "kurokawa-onsen"],
    sections: [
      { type: "heading", content: "阿蘇のプレミアムヴィラ：火口を見下ろす独占空間", level: 2 },
      { type: "text", content: "阿蘇中岳を望む丘の上に建つ高級ヴィラ「あそ望の郷」や「内牧温泉の老舗高級旅館」は、デッキから中岳の噴煙が正面に見える立地だ。1泊2〜3万円から。夜明け前に噴火が起きると、窓越しに橙色の光が見えることもある。朝食は地元の阿蘇牛と阿蘇高菜を使った本格料理が出る。" },
      { type: "spot-card", content: "kurokawa-onsen" },
      { type: "heading", content: "黒川温泉の最高級旅館：渓谷を独占する露天風呂", level: 2 },
      { type: "text", content: "黒川温泉の中で最上級の宿は「山みず木」「お宿 のし湯」「旅荘 山の宿」など。1泊2食3〜5万円の価格帯で、渓谷に面した岩造りの露天風呂が売りだ。夕食は熊本の食材を活かした会席料理で、馬刺し・阿蘇牛・天草の魚介が揃う。食事の間に仲居が「次の湯をご案内します」と案内してくれる旅館は特別感がある。" },
      { type: "heading", content: "贅沢な移動：プライベートカーチャーターという選択", level: 2 },
      { type: "text", content: "熊本の観光地は点在しており、贅沢旅ではタクシー・プライベートカーのチャーターが快適だ。熊本市内の観光タクシー（1日チャーター¥25,000〜）は熊本城・阿蘇・黒川温泉を1日で回るプランを組んでくれる。ドライバーが現地の話を聞かせてくれるため、ガイドブックに載っていない知識が得られる。" },
    ],
    relatedArticleSlugs: ["kumamoto-kurokawa-onsen-guide", "kumamoto-aso-caldera-drive"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "kumamoto-photography",
    title: "熊本の絶景撮影ガイド──大観峰・草千里・黒川温泉の霧を写真に収める方法",
    description: "熊本は「光と煙と水」の組み合わせが他にない景色を生む。阿蘇の朝霧・噴煙・黒川温泉の渓谷霧の撮影条件を詳細に語る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kumamoto",
    tags: ["熊本撮影", "阿蘇大観峰", "草千里", "写真旅", "熊本"],
    spotIds: ["aso-mountain", "kurokawa-onsen"],
    sections: [
      { type: "heading", content: "大観峰の雲海：9〜10月の早朝5時が最高の条件", level: 2 },
      { type: "text", content: "阿蘇カルデラに雲海が発生するのは気温差が大きい秋（9〜11月）の早朝だ。大観峰展望台（午前4時頃〜）では、カルデラ内が雲に覆われ、その上に阿蘇五岳が浮かぶ幻想的な景色が見られる。条件が良い日は前日夜から夜景を見て車中泊して待つ写真愛好家もいる。広角レンズ（24mm以下）で全体を収め、望遠レンズで五岳を切り取る2本体制が理想。" },
      { type: "spot-card", content: "aso-mountain" },
      { type: "heading", content: "草千里ヶ浜：馬×噴煙×青空の三要素が揃う条件", level: 2 },
      { type: "text", content: "草千里の馬の撮影は午前10〜12時が最も光量が良い。馬は馬小屋エリアに集まることが多いため、草原全体に散らばっている日は珍しい。噴煙が激しく出ている日に逆光で馬と噴煙を重ねると、煙が白く輝く幻想的な1枚になる。望遠レンズ（200mm以上）で馬をアップにする構図が最もドラマチック。" },
      { type: "heading", content: "黒川温泉の朝霧：11月〜2月の早朝6〜8時のみ", level: 2 },
      { type: "text", content: "黒川温泉の渓谷霧は気温が低い秋〜冬の早朝に発生する。田の原川の水面から白い霧が立ち上り、旅館の軒先が霞の中に浮かぶ。この景色は宿泊者だけが体験できる。霧の中の路地を縦位置で撮り、手前に石畳・奥に霞んだ旅館を配置するのが定番構図だ。" },
    ],
    relatedArticleSlugs: ["kumamoto-aso-caldera-drive", "kumamoto-kurokawa-onsen-guide"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "kumamoto-solo-travel",
    title: "熊本一人旅の完全ガイド──レンタカーで阿蘇・黒川・天草を独走する3日間",
    description: "熊本の一人旅はレンタカーが最強の武器だ。誰にも縛られず阿蘇の火口から天草の海まで走り続ける、自由な3日間の設計を提案する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kumamoto",
    tags: ["熊本一人旅", "レンタカー旅", "阿蘇", "3日間", "熊本"],
    spotIds: ["aso-mountain", "kurokawa-onsen", "kumamoto-castle"],
    sections: [
      { type: "heading", content: "1日目：熊本市内と熊本城で旅の基礎をつくる", level: 2 },
      { type: "text", content: "熊本着・レンタカー借用→熊本城（2時間）→水前寺成趣園（1時間）→夕食は熊本市内の馬刺し居酒屋（一人でカウンター席が最高）→熊本市内のビジネスホテル泊。一人旅は相手に配慮が不要なため、気の向くまま散策できる。熊本城の復興展示は一人で向き合う方が深く刺さる。" },
      { type: "spot-card", content: "aso-mountain" },
      { type: "heading", content: "2日目：阿蘇を走り尽くして黒川温泉に泊まる", level: 2 },
      { type: "text", content: "早朝5時出発→大観峰で日の出と雲海を狙う（条件による）→草千里ヶ浜→中岳火口→ミルクロードを走って黒川温泉へ。黒川温泉の入湯手形を購入し、夕方から2か所の外湯を一人でゆっくり巡る。一人で露天風呂に入りながら渓谷の音を聞く時間は、一人旅でしか得られない贅沢だ。" },
      { type: "heading", content: "3日目：天草五橋を渡り、イルカに会って帰る", level: 2 },
      { type: "text", content: "黒川温泉から天草まで車で2時間弱。天草五橋ドライブ→牛深のイルカウォッチング（3時間）→崎津天主堂→熊本空港または熊本駅へ帰路。一人でイルカウォッチングの船に乗ると、ガイドとの会話や他の参加者との偶然の交流が生まれる。天草の帰路のフェリー（熊本城への眺め）という選択肢もある。" },
    ],
    relatedArticleSlugs: ["kumamoto-aso-caldera-drive", "kumamoto-kurokawa-onsen-guide"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "kumamoto-autumn-foliage",
    title: "熊本の秋──黒川温泉の紅葉と阿蘇の草紅葉が染まる10月11月の最高の旅",
    description: "熊本の秋は渓谷が主役だ。黒川温泉の露天風呂から見る紅葉と、阿蘇の高原が黄金色に変わる草紅葉は、日本の秋の最高峰に入る。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kumamoto",
    tags: ["熊本の紅葉", "秋旅行", "黒川温泉", "阿蘇の草紅葉", "熊本"],
    spotIds: ["kurokawa-onsen", "aso-mountain"],
    sections: [
      { type: "heading", content: "黒川温泉の紅葉：露天風呂から見る日本一の秋", level: 2 },
      { type: "text", content: "黒川温泉の紅葉は10月中旬〜11月上旬が最盛期。田の原川の渓谷に面した露天風呂から見上げると、モミジ・ケヤキ・ブナが橙・赤・黄に染まった斜面が視野を埋める。湯船から空を見上げると枝と紅葉だけが見える旅館もある。この景色を目的に全国から客が来るため、この時期は予約が特に難しい。" },
      { type: "spot-card", content: "kurokawa-onsen" },
      { type: "heading", content: "阿蘇の草紅葉：広大な草原が金色に変わる11月", level: 2 },
      { type: "text", content: "阿蘇の草原は11月に草紅葉（ススキの穂が金色に輝く）が起きる。草千里ヶ浜のススキが夕日を受けてオレンジ色に輝く景色は、広大なカルデラの空間と合わさって他に類を見ない雄大さがある。大観峰からカルデラ全体を見渡すと、盆地の底が金色の絨毯のように見える。" },
      { type: "heading", content: "阿蘇の野焼き：2〜3月に行われる草原再生の火", level: 2 },
      { type: "text", content: "阿蘇の草原は毎年2〜3月に「野焼き」が行われる。草原全体を焼いて翌年の新芽を促す伝統農業で、焼けた草原の中に青い新芽が吹き出す春（4月）はまた別の絶景だ。野焼き直後（2〜3月）の黒焦げた阿蘇の丘は荒涼とした月面のような景色で、秋の紅葉とは真逆の印象的な美しさがある。" },
    ],
    relatedArticleSlugs: ["kumamoto-kurokawa-onsen-guide", "kumamoto-aso-caldera-drive"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "kumamoto-daigo-jiru",
    title: "熊本の郷土料理全ガイド──だご汁・辛子蓮根・一文字ぐるぐると、熊本の食卓の全体像",
    description: "熊本の食は馬刺しとラーメンだけではない。だご汁・辛子蓮根・一文字ぐるぐるという郷土料理の存在を知ると、熊本という土地が深くなる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kumamoto",
    tags: ["熊本郷土料理", "だご汁", "辛子蓮根", "グルメ", "熊本"],
    spotIds: ["suizenji-garden", "kumamoto-castle"],
    sections: [
      { type: "heading", content: "だご汁：小麦粉の団子と根野菜が入る熊本の味噌汁", level: 2 },
      { type: "text", content: "「だご汁（だご=団子）」は小麦粉の団子（だご）、大根・ニンジン・ごぼう・里芋・こんにゃくを味噌仕立てで煮た汁物だ。農家の賄い料理が起源で、熊本の家庭料理の代表格。水前寺成趣園周辺の食堂では「だご汁定食（¥900〜）」が食べられる。ふわっとした団子の食感と野菜の旨みが合わさる素朴な温かさが特徴。" },
      { type: "spot-card", content: "suizenji-garden" },
      { type: "heading", content: "辛子蓮根：加藤清正が食べた熊本城の名物", level: 2 },
      { type: "text", content: "辛子蓮根は蓮根の穴に辛子味噌を詰め、卵黄と小麦粉の衣で揚げた熊本の土産菓子だ。加藤清正が藩主のために作らせたという伝説がある。断面が肥後熊本藩の家紋「轡（くつわ）紋」に似ているという説も。熊本駅・空港・下通商店街で購入できる。切ると断面が美しいため、土産物の見栄えが非常に良い。" },
      { type: "heading", content: "一文字ぐるぐる：春の若ネギを味噌で食べる熊本の前菜", level: 2 },
      { type: "text", content: "「一文字ぐるぐる」は春の若いわけぎ（一文字とも呼ぶ）を湯通しし、くるくると巻いて酢味噌で食べる料理だ。シンプルだが、熊本の酒の肴として古くから愛されている。居酒屋のメニューに載っている店があり、馬刺しと共に注文するのが熊本通の選び方だ。" },
    ],
    relatedArticleSlugs: ["kumamoto-basashi-horse-meat-guide", "kumamoto-ramen-guide"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "kumamoto-kuma-kumamon",
    title: "くまモンと熊本県の全体像──47都道府県最強のゆるキャラが作った経済圏の話",
    description: "くまモンは年間1,000億円規模の経済効果を生むゆるキャラだ。熊本との本質的な関係と、くまモンスクエアで「本物」に会う方法を伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kumamoto",
    tags: ["くまモン", "くまモンスクエア", "熊本観光", "ゆるキャラ", "熊本"],
    spotIds: ["kumamoto-castle"],
    sections: [
      { type: "heading", content: "くまモンスクエア：熊本市役所でくまモンのパフォーマンスを見る", level: 2 },
      { type: "text", content: "熊本市役所1階の「くまモンスクエア」では、平日定期（11時・14時）にくまモンのダンスパフォーマンスが見られる（無料）。予告なし登場の「サプライズ出没」もある。くまモンの着ぐるみは世界最大のゆるキャラ認知度を誇り、パフォーマンスの質は本物のエンターテイメントだ。子どもより大人が熱狂することも多い。" },
      { type: "spot-card", content: "kumamoto-castle" },
      { type: "heading", content: "くまモン誕生の背景：九州新幹線全線開通キャンペーンから始まった", level: 2 },
      { type: "text", content: "くまモンは2011年の九州新幹線全線開通に合わせて熊本県が作ったキャラクターだ。当初は地味なPRキャラだったが、デザイナーの水野学（グッドデザインカンパニー）がシンプルな黒い熊のデザインを提案。大阪でのゲリラ的な路上活動からSNSで拡散し、2011年にゆるキャラグランプリを獲得。今や熊本県の最大の観光資産だ。" },
      { type: "heading", content: "くまモングッズ：正規ショップと偽物を見分ける", level: 2 },
      { type: "text", content: "くまモングッズは熊本県内外で大量に販売されているが、熊本県公認マークがない商品は非公式品だ。熊本空港・熊本駅・熊本城周辺の公認ショップで購入するのが正規ルート。収益が熊本県の復興支援に活用されるため、正規品を買う意味がある。1,000円以下のキーホルダー・ぬいぐるみが最もコスパの高い土産物。" },
    ],
    relatedArticleSlugs: ["kumamoto-castle-restoration", "kumamoto-daigo-jiru"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "kumamoto-yatsushiro-uminohoshi",
    title: "八代と球磨川──熊本の「もうひとつの川」が見せる干潟と鵜飼いの原風景",
    description: "八代は熊本市から南へ40分。球磨川河口の干潟と、日本最大級のい草産地という意外な産業が集まる街の、知られざる魅力を伝える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-07-28",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kumamoto",
    tags: ["八代", "球磨川", "い草", "干潟", "熊本"],
    spotIds: ["suizenji-garden"],
    sections: [
      { type: "heading", content: "球磨川：日本三大急流の激流と水害の歴史", level: 2 },
      { type: "text", content: "球磨川は「日本三大急流」（富士川・最上川と並ぶ）のひとつで、人吉盆地から八代市まで一気に流れ下る。2020年の令和2年7月豪雨で球磨川は氾濫し、八代・人吉地域に壊滅的な被害をもたらした。復興が続く川沿いの集落では、洪水の痕跡と再建の過程が今も見られる。川と共に生きる意味を問う旅ができる場所だ。" },
      { type: "heading", content: "八代市のい草産地：畳の原料が生まれる場所を歩く", level: 2 },
      { type: "text", content: "熊本県八代市周辺は日本のい草生産の約80%を占める産地だ。5〜6月のい草の刈り取り期には、水田一面に緑のい草が広がり、収穫と乾燥作業が行われる。「ふれあいランド八代」ではい草を使った工芸体験ができる。工場見学ツアー（事前申込）では畳に加工される過程を見学できる。" },
      { type: "heading", content: "八代の「妙見祭」：国連無形文化遺産のまつりが11月に来る", level: 2 },
      { type: "text", content: "11月23日に行われる八代神社（妙見宮）の祭り「妙見祭」は「風流踊（ふりゅうおどり）」としてユネスコ無形文化遺産に登録されている。亀蛇（がめ）と呼ばれる亀の上に蛇が乗った民俗造形が神輿と共に練り歩く独特の行列は、他では見られない祭り文化だ。熊本から日帰りで参加できる距離にある。" },
    ],
    relatedArticleSlugs: ["kumamoto-amakusa-island", "kumamoto-castle-restoration"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "kumamoto-summer-travel",
    title: "熊本の夏旅行──阿蘇の高原で涼み、天草の海で泳ぐ7月8月の完全ガイド",
    description: "熊本の夏は阿蘇の高原と天草の海で2倍楽しめる。気温が30度を超える熊本市内から逃げて、夏の本当の正解ルートを伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kumamoto",
    tags: ["熊本の夏", "阿蘇高原", "天草の海", "夏旅行", "熊本"],
    spotIds: ["aso-mountain", "kumamoto-castle"],
    sections: [
      { type: "heading", content: "阿蘇高原の夏：標高1,000mは市街より7〜10度涼しい", level: 2 },
      { type: "text", content: "阿蘇の草千里ヶ浜（標高1,100m前後）は熊本市内より7〜10度気温が低い。真夏でも最高気温が25度前後で、風が通る草原はサラッとして快適だ。中岳火口への道中にある「火の山温泉どんどこ湯」は阿蘇唯一の高地温泉で、夏でも温泉に入りたくなるほど夜は涼しい。" },
      { type: "spot-card", content: "aso-mountain" },
      { type: "heading", content: "天草の海水浴：九州の透明度トップクラスのビーチ", level: 2 },
      { type: "text", content: "天草下島の「富岡海水浴場」と「壱岐ビーチ」は透明度が高く波が穏やかなため家族向け。「下田温泉海水浴場」は温泉地そばで、海水浴後に温泉という動線が完璧だ。7月中旬〜8月中旬がシーズンで、平日は比較的空いている。天草の海はサンゴが生息しており、シュノーケリングでカラフルな魚に会える可能性がある。" },
      { type: "heading", content: "熊本市内の夏まつり：おてもやん総踊りと山鹿灯籠まつり", level: 2 },
      { type: "text", content: "熊本市中心部では8月上旬に「おてもやん総踊り」が行われ、民謡「おてもやん」に合わせて市民が踊り歩く。山鹿市では毎年8月15〜16日に「山鹿灯籠まつり」が開催される。女性が頭の上に金灯籠を乗せて奉納する「千人灯籠踊り」は、光の中を人が動く幻想的な夏の風景だ。" },
    ],
    relatedArticleSlugs: ["kumamoto-amakusa-island", "kumamoto-aso-caldera-drive"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "kumamoto-sake-shochu",
    title: "熊本の酒を飲む旅──球磨焼酎と地ビール「黒ビール熊本」で巡る大人の熊本",
    description: "熊本は焼酎の聖地だ。球磨川流域で作られる米焼酎「球磨焼酎」は、日本の伝統的な蒸留酒の最高峰のひとつ。その蔵を巡る旅を提案する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kumamoto",
    tags: ["球磨焼酎", "米焼酎", "酒蔵", "熊本グルメ", "熊本"],
    spotIds: ["kumamoto-castle"],
    sections: [
      { type: "heading", content: "球磨焼酎とは何か：日本の米焼酎の最高峰", level: 2 },
      { type: "text", content: "球磨焼酎は熊本県球磨郡・人吉市で製造される米焼酎で、国税庁の地理的表示（GI）が認定された日本屈指のプレミアム焼酎だ。球磨川の清流と球磨の米（ひのひかり）、標高200〜400mの盆地の寒暖差が独自の風味を生む。蔵元は約30社あり、それぞれ味のキャラクターが全く異なる。" },
      { type: "spot-card", content: "kumamoto-castle" },
      { type: "heading", content: "人吉・球磨地域の酒蔵見学：蒸留器を間近で見る", level: 2 },
      { type: "text", content: "人吉市内には複数の球磨焼酎蔵元があり、見学を受け入れている蔵もある（事前予約推奨）。「繊月酒造」「那須酒造場」は見学対応が充実している。蒸留器（ポットスチル）から焼酎が出てくる工程と、原料の球磨米が発酵する際の甘い香りは、蔵の中でしか体験できない。見学後の試飲が楽しみだ。" },
      { type: "heading", content: "熊本市内の球磨焼酎バー：23種類以上を飲み比べる夜", level: 2 },
      { type: "text", content: "熊本市内の「炉端焼き 源次郎」「居酒屋 熊本蔵」などの専門店では、球磨焼酎の複数銘柄を飲み比べるセットが提供されている。蒸留方法（常圧蒸留・減圧蒸留）、熟成年数、麹の種類（白麹・黄麹）によって全く違う味になる球磨焼酎の多様性を、一夜で体験できる。馬刺しとの相性は格別だ。" },
    ],
    relatedArticleSlugs: ["kumamoto-basashi-horse-meat-guide", "kumamoto-daigo-jiru"],
  },
];
