import { Article } from "@/types/article";

export const kyotoArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "kyoto-nishiki-market-morning",
    title: "錦市場、8時の歩き方──観光客ゼロの仕入れ時間に紛れ込む",
    description: "「京の台所」は朝が本番。観光客向けの顔とまったく違う錦市場がある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-14",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kyoto",
    tags: ["錦市場", "朝市", "グルメ", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "8時台は業者と地元民だけ", level: 2 },
      { type: "text", content: "午前8時、錦市場に観光客はいない。魚屋が朝獲れの鱧を並べ、豆腐屋がにがりを入れる。この時間帯に市場を歩くのは、京都の食文化の核心に触れることだ。" },
      { type: "heading", content: "食べ歩きは9時半以降", level: 2 },
      { type: "text", content: "漬物屋が試食を出し始めるのは9時半ごろ。三木鶏卵の出し巻き玉子は行列必至だが、開店直後なら5分で買える。西端の麩嘉は揚げ麩が絶品。" },
      { type: "heading", content: "帰りは寺町通りへ抜ける", level: 2 },
      { type: "text", content: "東端から寺町通りに出ると、老舗の茶舗が並ぶ。一保堂茶舗で茶葉を選ぶ時間を必ず作ること。土産として最も軽く、最も喜ばれる。" },
    ],
    relatedArticleSlugs: ["kyoto-gourmet-course-hanamikoji", "kyoto-tofu-cuisine-deep"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "kyoto-cherry-blossom-route",
    title: "桜の京都──混まない穴場3ルートと見頃カレンダー",
    description: "3月末の京都は混む。でも知っている人だけが行く桜の名所がまだある。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-03-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kyoto",
    tags: ["桜", "春", "京都", "穴場", "写真映え"],
    spotIds: ["arashiyama", "kiyomizu"],
    sections: [
      { type: "heading", content: "ルート1：哲学の道を早朝に歩く", level: 2 },
      { type: "text", content: "哲学の道は朝7時台が正解。疏水沿いに桜が連なる道を、静寂の中で歩ける。南禅寺側から入り、銀閣寺まで2kmをゆっくり1時間。" },
      { type: "heading", content: "ルート2：背割堤は意外と知られていない", level: 2 },
      { type: "text", content: "八幡市にある背割堤は、宇治川と木津川に挟まれた堤防に全長1.4kmの桜並木が続く。京都市内の混雑を避けたいなら、ここが最善策。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "ルート3：嵐山の中之島公園", level: 2 },
      { type: "text", content: "渡月橋の手前、中之島公園は地元民が花見に使う場所。観光客は竹林に流れるので、ここは比較的空いている。花見弁当を持ち込んで正解。" },
    ],
    relatedArticleSlugs: ["kyoto-nishiki-market-morning", "kyoto-bamboo-grove-dawn"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "kyoto-tofu-cuisine-deep",
    title: "湯豆腐だけじゃない──京都の豆腐料理を本気で食べ歩く",
    description: "南禅寺の湯豆腐は観光客向け。本物の京豆腐文化はもっと深い場所にある。",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    publishedAt: "2025-02-08",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kyoto",
    tags: ["豆腐", "京料理", "グルメ", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "南禅寺の湯豆腐を正しく食べる", level: 2 },
      { type: "text", content: "奥丹の湯豆腐は江戸時代から変わっていない。木の椀に豆腐、昆布だし、薬味。シンプルだからこそ素材の差が出る。昼の混雑を避け、開店と同時に入るべき。" },
      { type: "heading", content: "上賀茂の豆腐屋へ足を伸ばす", level: 2 },
      { type: "text", content: "上賀茂の「とようけ茶屋」は行列必至だが、テイクアウトの揚げ出し豆腐は待ち時間10分。神馬堂のやきもちと合わせて食べると、上賀茂の朝が完成する。" },
      { type: "heading", content: "錦豆腐でしめる", level: 2 },
      { type: "text", content: "錦市場内の「服部豆腐」は創業100年超。豆乳ソフトクリームは甘さ控えめで、豆の風味がダイレクトに来る。これで京都の豆腐巡りは完結。" },
    ],
    relatedArticleSlugs: ["kyoto-nishiki-market-morning", "kyoto-solo-day-walk"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "kyoto-kurama-onsen-day",
    title: "鞍馬温泉──京都市街から1時間、山の中の硫黄泉",
    description: "京都に温泉がある事実を、多くの旅人が知らない。鞍馬は想像より遠く、想像よりいい。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-11-05",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "kyoto",
    tags: ["温泉", "鞍馬", "日帰り", "京都", "山"],
    spotIds: [],
    sections: [
      { type: "heading", content: "出町柳から叡山電鉄で30分", level: 2 },
      { type: "text", content: "叡山電鉄の終点・鞍馬駅は、京都の別の顔。杉並木が続く参道を歩くと、市街地の喧騒が嘘のように消える。鞍馬温泉まで徒歩10分か、無料送迎バスで移動。" },
      { type: "heading", content: "露天風呂からの眺めが本番", level: 2 },
      { type: "text", content: "鞍馬温泉の露天は硫黄泉で、肌がぬるっとする本格派。紅葉シーズンは11月が最高。山を眺めながら湯に浸かる30分は、京都の何百もの寺を回るより豊かな時間かもしれない。" },
      { type: "heading", content: "帰りに貴船神社を寄り道", level: 2 },
      { type: "text", content: "鞍馬から徒歩40分で貴船神社に着く。川床料理の季節（5〜9月）なら昼食もここで。水に浸すと文字が浮かぶ水占いおみくじは、ここでしかできない体験。" },
    ],
    relatedArticleSlugs: ["kyoto-cherry-blossom-route", "kyoto-solo-temple-meditation"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "kyoto-family-fushimi",
    title: "子連れ京都、伏見稲荷で半日遊ぶ──鳥居くぐりは何歳でも楽しい",
    description: "子どもが一番興奮するのは金閣寺でも清水寺でもなく、伏見稲荷だった。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "kyoto",
    tags: ["子連れ", "家族旅", "伏見稲荷", "京都"],
    spotIds: ["fushimi-inari"],
    sections: [
      { type: "heading", content: "子どもの体力で四ツ辻まで行ける", level: 2 },
      { type: "text", content: "山頂まで往復2時間かかるが、四ツ辻（中腹）なら1時間以内。小学生低学年でもクリアできる距離。鳥居をくぐる数を数えながら歩くと、子どもが自分で歩き続ける。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "お稲荷さんとキツネで気分が上がる", level: 2 },
      { type: "text", content: "子どもはキツネの石像が好き。参道沿いに「目」が入ったキツネを探す遊びで、飽きさせずに歩かせられる。御守りの種類が豊富なので、自分で選ばせると記念になる。" },
      { type: "heading", content: "帰りは伏見稲荷大社前の茶店で休憩", level: 2 },
      { type: "text", content: "参道入口近くの茶店では、稲荷寿司とみたらし団子が食べられる。稲荷寿司が伏見から広まった事実を子どもに教えると、食育にもなる。" },
    ],
    relatedArticleSlugs: ["kyoto-bamboo-grove-dawn", "kyoto-family-arashiyama"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "kyoto-couple-tea-ceremony",
    title: "カップルで体験する本格茶の湯──祇園の茶室で過ごす90分",
    description: "観光体験としての抹茶ではなく、本物の茶の湯作法を二人で習う。非日常の濃度が違う。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-22",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kyoto",
    tags: ["茶道", "カップル", "体験", "祇園", "京都"],
    spotIds: ["gion"],
    sections: [
      { type: "heading", content: "祇園の裏路地にある茶室を予約する", level: 2 },
      { type: "text", content: "花見小路から1本入った路地に、外国人旅行者向けではなく本物の稽古も行う茶室がある。予約制で少人数。英語対応可だが、所作は言葉を超えて伝わる。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "点てたお茶を相手に飲ませる", level: 2 },
      { type: "text", content: "茶道の作法で、自分が点てたお茶を相手に出すという構造がある。二人でこれをやると、妙な緊張感と親密さが同時に生まれる。旅の記憶として最も濃い体験になる。" },
      { type: "heading", content: "体験後は一力茶屋の前を歩く", level: 2 },
      { type: "text", content: "体験が終わったら花見小路を南下。祇園の夕暮れを二人で歩くのが、この体験の最良の締め方。夕食は四条通沿いの割烹を予約しておくと完璧。" },
    ],
    relatedArticleSlugs: ["kyoto-higashiyama-night-walk", "kyoto-luxury-kaiseki"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "kyoto-solo-day-walk",
    title: "一人で歩く京都──地図を持たずに迷い込む路地の楽しみ方",
    description: "計画なしで歩く京都が、実は一番おもしろい。一人旅専用の、ゆるいガイド。",
    coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80",
    publishedAt: "2025-05-03",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kyoto",
    tags: ["一人旅", "散歩", "路地", "京都", "ゆっくり"],
    spotIds: ["gion"],
    sections: [
      { type: "heading", content: "祇園から東山へ、路地を読む", level: 2 },
      { type: "text", content: "祇園の石畳を外れ、住宅地に入ると急に静かになる。表札が出た家の横に小さな地蔵があり、その奥に誰も知らない神社がある。こういう発見は、グループでは絶対にできない。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "疲れたら喫茶店に滑り込む", level: 2 },
      { type: "text", content: "京都には昭和の喫茶店が異常に多い。木屋町や寺町には、マスターが1人でやっている純喫茶が現役で存在する。一人旅でないと入りづらい空間で、コーヒーを飲みながらメモを書く。" },
      { type: "heading", content: "夕方は鴨川デルタで終わる", level: 2 },
      { type: "text", content: "出町柳の鴨川デルタは、一人で座るのに完璧な場所。石の上に腰を下ろして、水面と対岸の木々を見る。何もしない時間が、京都では最も贅沢だと気づく。" },
    ],
    relatedArticleSlugs: ["kyoto-tofu-cuisine-deep", "kyoto-nishiki-market-morning"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "kyoto-budget-temple-pass",
    title: "1日2000円以下で5つの寺を回る──京都節約参拝術",
    description: "拝観料は積み上げると高い。でも順番と優先順位を整理すれば、予算内で京都の核心に触れられる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "kyoto",
    tags: ["節約", "拝観料", "寺", "京都", "バジェット旅"],
    spotIds: ["kiyomizu", "fushimi-inari"],
    sections: [
      { type: "heading", content: "無料で入れる場所を知る", level: 2 },
      { type: "text", content: "伏見稲荷は境内への入場が無料。二条城は無料開放日が年数回ある。下鴨神社は本殿前まで無料で入れる。まずこれらを軸に日程を組む。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "拝観料が必要な寺は1日2か所まで", level: 2 },
      { type: "text", content: "清水寺（500円）と金閣寺（500円）を同日に回れば、拝観料の合計は1000円。交通費をバスではなく自転車（レンタル1日1500円）にすると、交通費が抑えられ行動自由度も上がる。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "食費は錦市場で立ち食いする", level: 2 },
      { type: "text", content: "錦市場の立ち食いで昼食を賄うと、500〜700円で十分満足できる。夕食は京都駅周辺の定食屋で1000円以内。これで食費は1800円以下に収まる。" },
    ],
    relatedArticleSlugs: ["kyoto-budget-temple-pass", "kyoto-nishiki-market-morning"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "kyoto-luxury-kaiseki",
    title: "人生に一度の懐石──京都で予約すべき3軒と予約の作法",
    description: "京都の懐石料理は、食べることが美術鑑賞と同義になる。3軒、それぞれの主張がある。",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kyoto",
    tags: ["懐石", "高級", "グルメ", "京都", "贅沢"],
    spotIds: [],
    sections: [
      { type: "heading", content: "予約は3か月前が常識", level: 2 },
      { type: "text", content: "京都の一流懐石は、3か月前から予約が埋まる。電話予約が基本で、英語対応できる店は限られる。宿泊ホテルのコンシェルジュに頼むのが最も確実な手段。" },
      { type: "heading", content: "空間ごと食べる──坐忘林の朝食懐石", level: 2 },
      { type: "text", content: "嵐山の「坐忘林」は宿泊者向けだが、朝食懐石の完成度は別格。竹林を借景にした個室で、朝7時から2時間かけて食べる。この体験のために宿泊を組む価値がある。" },
      { type: "heading", content: "ランチ懐石という入門戦略", level: 2 },
      { type: "text", content: "夜のコースが3万円以上でも、ランチなら1万円前後の店は複数ある。同じ厨房から出てくる料理で、昼のコースは内容が絞られているが素材と技術は変わらない。初心者はランチから始めるべき。" },
    ],
    relatedArticleSlugs: ["kyoto-couple-tea-ceremony", "kyoto-gourmet-course-hanamikoji"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "kyoto-photo-spot-golden-hour",
    title: "京都フォトガイド──黄金時間帯に撮るべき5つの場所",
    description: "日の出から1時間と日没前1時間。この時間帯の京都は、昼間とは別の街になる。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kyoto",
    tags: ["写真", "撮影スポット", "京都", "朝活", "インスタ映え"],
    spotIds: ["fushimi-inari", "gion", "arashiyama"],
    sections: [
      { type: "heading", content: "日の出直後：伏見稲荷の空洞", level: 2 },
      { type: "text", content: "千本鳥居は午前5時台が最高。朱色の鳥居に差し込む横光が、トンネルの奥に消えるように見える。三脚は禁止だがスマホで十分撮れる。" },
      { type: "spot-card", content: "fushimi-inari" },
      { type: "heading", content: "夕方：祇園白川の柳と提灯", level: 2 },
      { type: "text", content: "日没30分前、白川沿いの柳に橙色の光が当たる時間が1番美しい。ISO感度を少し上げてシャッタースピードを落とすと、流れる水と静止する建物のコントラストが映える。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "朝霧：嵐山竹林の静止画", level: 2 },
      { type: "text", content: "雨上がりの早朝、嵐山の竹林に霧が漂う。このタイミングは予測困難だが、梅雨明け直後の7月上旬に発生しやすい。ISO400、絞りF4で撮ると空気感が出る。" },
      { type: "spot-card", content: "arashiyama" },
    ],
    relatedArticleSlugs: ["kyoto-nishiki-market-morning", "kyoto-cherry-blossom-route"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "kyoto-gourmet-course-hanamikoji",
    title: "花見小路グルメ──一見さんでも入れる本物の京料理5軒",
    description: "「一見さんお断り」は昔話。花見小路には今、予約さえすれば入れる本気の店がある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-18",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kyoto",
    tags: ["花見小路", "グルメ", "京料理", "祇園", "京都"],
    spotIds: ["gion"],
    sections: [
      { type: "heading", content: "バー「K6」でカウンターに座る", level: 2 },
      { type: "text", content: "花見小路に隣接するK6は、京都で最も洗練されたバーのひとつ。懐石の後にここでスコッチを1杯飲む流れが完成形。カウンター8席なので必ず予約。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "昼は「おめん」の祇園店でにしんそば", level: 2 },
      { type: "text", content: "にしんそばは京都の冬の定番だが、おめんは年中提供している。特製のつけ汁が個性的で、薬味の種類が10種以上。観光地ランチの中では圧倒的なコストパフォーマンス。" },
      { type: "heading", content: "甘味は「鍵善良房」が答え", level: 2 },
      { type: "text", content: "くずきりで知られる鍵善良房は、祇園に本店を持つ。黒蜜か白蜜を選ぶシンプルな構成だが、くずの透明感が別次元。夏季限定のかき氷も行列ができる名作。" },
    ],
    relatedArticleSlugs: ["kyoto-tofu-cuisine-deep", "kyoto-couple-tea-ceremony"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "kyoto-sake-brewery-fushimi",
    title: "伏見の酒蔵巡り──月桂冠と黄桜、その先にある地酒の話",
    description: "伏見は日本屈指の酒処。観光用の試飲だけで終わらせるには、もったいなすぎる。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-12",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kyoto",
    tags: ["日本酒", "酒蔵", "伏見", "京都", "グルメ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "伏見の水が酒を作る理由", level: 2 },
      { type: "text", content: "伏見は「伏流水」が湧き出る土地。この軟水が甘口の女酒と呼ばれる伏見酒を生む。灘の硬水が辛口の男酒なら、伏見の軟水は柔らかく、後味に米の甘みが残る。" },
      { type: "heading", content: "月桂冠大倉記念館は必訪", level: 2 },
      { type: "text", content: "江戸時代の酒蔵を改装した月桂冠大倉記念館では、酒造りの歴史と工程を学べる。入館料300円で試飲3種付き。コストパフォーマンスが異常に高い。" },
      { type: "heading", content: "「招徳酒造」は予約見学がおすすめ", level: 2 },
      { type: "text", content: "観光客に知られていない招徳酒造は、事前予約で蔵見学が可能。醪（もろみ）の発酵音を聞きながら杜氏の話を聞く体験は、伏見巡りの中で最も深い時間になる。" },
    ],
    relatedArticleSlugs: ["kyoto-sake-brewery-fushimi", "kyoto-nishiki-market-morning"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "kyoto-family-arashiyama",
    title: "嵐山で子どもが本気で喜ぶ半日プラン──トロッコ列車と川遊び",
    description: "竹林より、子どもはトロッコ列車に乗りたい。それで正解。",
    coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80",
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "kyoto",
    tags: ["子連れ", "嵐山", "トロッコ列車", "京都", "家族"],
    spotIds: ["arashiyama"],
    sections: [
      { type: "heading", content: "トロッコ嵯峨駅は1か月前に予約", level: 2 },
      { type: "text", content: "嵯峨野観光鉄道のトロッコ列車は春と秋に激混みになる。ネット予約は1か月前から可能。窓なしの「ザ・リッチ号」（5号車）は指定で取ること。子どもが全員窓のない車両に座りたがる。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "亀岡からの保津川下りは別格", level: 2 },
      { type: "text", content: "トロッコで亀岡まで行き、そこから保津川下り（約2時間）で嵐山に戻るルートが最高。川の激流で船が揺れるたびに子どもが叫ぶ。ライフジャケット着用でびしょ濡れ必至。着替えは必須。" },
      { type: "heading", content: "帰りは渡月橋で屋台めし", level: 2 },
      { type: "text", content: "嵐山公園の屋台エリアでアユの塩焼きを食べる。川魚を川の近くで食べるという体験は、子どもの記憶に強く残る。" },
    ],
    relatedArticleSlugs: ["kyoto-family-fushimi", "kyoto-bamboo-grove-dawn"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "kyoto-couple-night-illumination",
    title: "ライトアップ京都──二人で歩くべき秋の夜3ルート",
    description: "昼間とは別物の美しさがある。秋夜の京都を二人で歩く、これが正解のルート。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-11-18",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kyoto",
    tags: ["ライトアップ", "夜", "秋", "カップル", "京都"],
    spotIds: ["kiyomizu", "arashiyama"],
    sections: [
      { type: "heading", content: "清水寺夜間特別拝観は17時半入場", level: 2 },
      { type: "text", content: "11月の清水寺は夜間特別拝観を開催。舞台から見下ろす京都の夜景と、紅葉のライトアップが重なる瞬間は、京都の全観光体験の中でも最高峰のひとつ。17時半の開場直後に入ると、最初の10分は比較的空いている。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "嵐山花灯路は歩いて回る", level: 2 },
      { type: "text", content: "12月の嵐山花灯路は、竹林から渡月橋にかけての光の回廊。風がなく寒い夜が最もきれいに見える。二人で並んで歩く道幅が、この時間帯にちょうどいいサイズ感になる。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "高台寺のプロジェクションマッピング", level: 2 },
      { type: "text", content: "高台寺は夜間拝観でプロジェクションマッピングを実施。方丈前の池に映るデジタルアートは毎年テーマが変わる。30分待って見る価値がある。" },
    ],
    relatedArticleSlugs: ["kyoto-higashiyama-night-walk", "kyoto-cherry-blossom-route"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "kyoto-solo-temple-meditation",
    title: "一人で座禅を体験する──妙心寺と建仁寺、作法と心構え",
    description: "初心者でも参加できる座禅体験。京都の寺で「何もしない時間」を体験する方法。",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    publishedAt: "2025-03-08",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kyoto",
    tags: ["座禅", "一人旅", "体験", "禅", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "建仁寺の座禅会は毎月第2日曜", level: 2 },
      { type: "text", content: "建仁寺（祇園）の坐禅会は毎月第2日曜の朝8時から。参加費無料、予約不要。1時間の坐禅の後に法話がある。観光客より地元の人間が多く、観光体験ではなく本物の修行に近い。" },
      { type: "heading", content: "妙心寺の早暁坐禅会", level: 2 },
      { type: "text", content: "妙心寺は毎朝6時から一般参加可能な坐禅会を開く。40分間の静寂の後、総大将格の景徳院の住職が直接指導する。警策（けいさく）で肩を打ってもらう体験を希望できる。" },
      { type: "heading", content: "座禅後の朝食が沁みる理由", level: 2 },
      { type: "text", content: "坐禅を終えた後の朝食は、何を食べても美味く感じる。近くの豆腐料理屋か普通の定食屋でいい。頭が空になった後の最初の食事に、味が全部乗ってくる。" },
    ],
    relatedArticleSlugs: ["kyoto-solo-day-walk", "kyoto-nishiki-market-morning"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "kyoto-budget-guesthouse",
    title: "京都のゲストハウスで旅を節約する──3000円泊で得られるもの",
    description: "安さだけじゃない。ゲストハウスの醍醐味は、旅人同士の偶然の会話にある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "kyoto",
    tags: ["ゲストハウス", "節約", "一人旅", "宿泊", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "京都の宿泊費中央値は上がっている", level: 2 },
      { type: "text", content: "インバウンド需要でホテル価格が跳ね上がった。週末の京都で1泊1万円以下の普通のホテルを探すのは今や困難。その中でゲストハウスは3000〜5000円で踏み止まっている。" },
      { type: "heading", content: "西陣エリアのゲストハウスが熱い", level: 2 },
      { type: "text", content: "観光地から少し離れた西陣・今出川エリアに、古民家改装型のゲストハウスが集中している。築100年超の町家に泊まれて、朝は住職が来てお経を読む宿もある。これで4000円は破格。" },
      { type: "heading", content: "ドミトリーの人脈が旅を変える", level: 2 },
      { type: "text", content: "同じドミトリーに泊まった旅行者から、誰も知らない穴場を教えてもらう体験は、旅のアルゴリズムが変わる瞬間。京都のゲストハウスには外国人旅行者も多く、英語の練習場にもなる。" },
    ],
    relatedArticleSlugs: ["kyoto-budget-temple-pass", "kyoto-solo-day-walk"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "kyoto-luxury-ryokan-eastern-hills",
    title: "東山に泊まる贅沢──高台寺周辺の宿で過ごす非日常の2日間",
    description: "京都で最も贅沢な夜は、ホテルではなく小さな旅館に泊まる夜だ。",
    coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80",
    publishedAt: "2025-04-30",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "kyoto",
    tags: ["旅館", "高級", "東山", "贅沢", "京都"],
    spotIds: ["kiyomizu", "gion"],
    sections: [
      { type: "heading", content: "高台寺周辺の旅館を選ぶ理由", level: 2 },
      { type: "text", content: "東山の旅館は立地が本物。宿から歩いて清水寺、石塀小路、高台寺に行ける。移動にタクシーも電車も不要な宿は、京都滞在の質を根本から変える。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "夕食後に夜の石塀小路を一人で歩く", level: 2 },
      { type: "text", content: "宿の夕食（懐石）が終わる21時ごろ、石塀小路は静まり返っている。観光客ゼロの石畳を、宿の浴衣で歩く。この体験のために1泊3万円を払うのは合理的な選択だと思う。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "翌朝、早朝清水寺を独占する", level: 2 },
      { type: "text", content: "旅館から徒歩10分で清水寺の開門時間（6時）に到着できる。宿泊客だけが享受できる時間割。朝食の前に清水の舞台を独り占めする感覚は、日帰り観光では絶対に得られない。" },
    ],
    relatedArticleSlugs: ["kyoto-luxury-kaiseki", "kyoto-couple-tea-ceremony"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "kyoto-rainy-day-plan",
    title: "雨の京都のすごし方──濡れることを味方にする屋内とアーケード戦略",
    description: "雨の日の京都を嘆く必要はない。苔寺は雨の日が最も美しく、純喫茶はその日だけ空いている。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-06-28",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kyoto",
    tags: ["雨の日", "屋内観光", "京都", "穴場", "コツ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "苔寺（西芳寺）は雨が正解", level: 2 },
      { type: "text", content: "西芳寺は事前申込制で入場制限がある。雨の日の苔は緑が最も鮮やかで、湿気が苔の鮮度を上げる。雨予報の日に事前申込をしておくのが賢い戦略。" },
      { type: "heading", content: "寺町通りのアーケードを南北に歩く", level: 2 },
      { type: "text", content: "寺町・新京極のアーケードは、雨の日の受け皿になる。古書店、和菓子屋、骨董屋が連なり、傘を差さずに2時間歩ける。三月書房は京都の知性が詰まった独立書店。" },
      { type: "heading", content: "美術館を雨の日のために取っておく", level: 2 },
      { type: "text", content: "京都国立博物館は晴れの日ではなく雨の日に行くべき場所。混雑が減り、展示室が静かになる。特別展よりも常設展の方が、京都という土地の深さを感じられる展示が多い。" },
    ],
    relatedArticleSlugs: ["kyoto-rainy-day-plan", "kyoto-solo-day-walk"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "kyoto-kiyomizu-deep-dive",
    title: "清水寺を本当に楽しむ──参道の歩き方から音羽の滝の作法まで",
    description: "清水寺は見るだけじゃない。音羽の滝の意味を知ってから行くと、全体が変わる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-22",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kyoto",
    tags: ["清水寺", "京都", "観光", "寺社", "解説"],
    spotIds: ["kiyomizu"],
    sections: [
      { type: "heading", content: "仁王門から入ると全景が見える", level: 2 },
      { type: "text", content: "多くの観光客は産寧坂・二年坂から上がってくるが、仁王門側から入ると清水寺の「構造」が読める。西門、三重塔、轟門と通過するたびに本堂への期待が高まる設計になっている。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "舞台の下を見ると寺の技術がわかる", level: 2 },
      { type: "text", content: "清水の舞台を支える139本の柱は「釘を一本も使わない」と言われる。見晴らし台ではなく、その下の構造体を見るために清水に来るべきだと思っている。" },
      { type: "heading", content: "音羽の滝：3本の意味を間違えない", level: 2 },
      { type: "text", content: "音羽の滝は向かって左から学業・恋愛・長寿。1種類しか飲んではいけない（欲張りは効かない）という作法がある。どれを選ぶかで旅の最後の意志が定まる。" },
    ],
    relatedArticleSlugs: ["kyoto-nishiki-market-morning", "kyoto-budget-temple-pass"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "kyoto-winter-illumination-arashiyama",
    title: "嵐山花灯路2025──12月限定、光の竹林を歩く夜",
    description: "冬の嵐山はひとの少なさが武器になる。花灯路の夜は、観光地が芸術作品に変わる。",
    coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80",
    publishedAt: "2025-12-08",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kyoto",
    tags: ["花灯路", "冬", "嵐山", "ライトアップ", "京都"],
    spotIds: ["arashiyama"],
    sections: [
      { type: "heading", content: "17時半：日が暮れる前に竹林へ", level: 2 },
      { type: "text", content: "花灯路は日没後が本番だが、薄暮の竹林を先に歩いておく価値がある。青みがかった光の中に竹の影が伸びる時間は15分しかない。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "18時以降：光のルートを逆走する", level: 2 },
      { type: "text", content: "観光客は渡月橋側から入るので、竹林から先に入って逆方向に歩くと人の流れに逆らえる。空いている光の回廊を楽しめる。" },
      { type: "heading", content: "甘酒で体を温めてから帰る", level: 2 },
      { type: "text", content: "天龍寺前の屋台で甘酒を1杯。12月の夜の嵐山は冷え込むので、薄着では体が持たない。帰りはJR嵯峨嵐山駅より、阪急嵐山駅の方が混雑が少ない。" },
    ],
    relatedArticleSlugs: ["kyoto-couple-night-illumination", "kyoto-bamboo-grove-dawn"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "kyoto-machiya-stay",
    title: "町家を一棟借りして泊まる京都──古民家ステイの見つけ方",
    description: "ホテルでも旅館でもない第3の宿泊形態。台所で朝食を作る京都の朝は、旅の概念を変える。",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "kyoto",
    tags: ["町家", "宿泊", "古民家", "カップル", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "京都の町家は今、宿になっている", level: 2 },
      { type: "text", content: "空き家問題と観光需要が重なり、西陣・丹波口・壬生エリアを中心に町家一棟貸しが急増している。最低価格は1棟1泊2万円台から。2人で割ると1人1万円以下になる。" },
      { type: "heading", content: "「しつらいの宿」的なコンセプトが多い", level: 2 },
      { type: "text", content: "多くの町家宿は、調理器具完備でスーパーで食材を買って料理できる。錦市場で買った豆腐と漬物で朝食を作る体験は、宿のサービスを超える豊かさがある。" },
      { type: "heading", content: "予約はAirbnbより専門サイトが安心", level: 2 },
      { type: "text", content: "「京の宿・町家」や「京都古民家宿」の専門予約サイトは、物件のキュレーションが厳しく管理状態が安定している。Airbnbより選択肢は少ないが、当たりハズレが少ない。" },
    ],
    relatedArticleSlugs: ["kyoto-luxury-ryokan-eastern-hills", "kyoto-couple-tea-ceremony"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "kyoto-nijo-castle-hidden",
    title: "二条城を1時間で読み解く──障壁画と「うぐいす張り」の本当の話",
    description: "二条城は見どころが多すぎる。1時間で核心だけを抜き出すルートを作った。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kyoto",
    tags: ["二条城", "歴史", "世界遺産", "京都", "観光"],
    spotIds: [],
    sections: [
      { type: "heading", content: "二の丸御殿：見るべきは虎の間", level: 2 },
      { type: "text", content: "狩野派による虎と豹の障壁画は、当時の権威の誇示そのもの。将軍に謁見する諸大名が、この絵を見て何を感じたかを想像しながら歩くと、床の間の構造がまったく別の意味を持つ。" },
      { type: "heading", content: "うぐいす張りは防犯装置だった", level: 2 },
      { type: "text", content: "廊下を歩くと床が鳴る「うぐいす張り」は、音で侵入者を察知するための機能。ガイドの説明なしでは分かりにくいが、音が出る床と出ない床があることに気づくと、設計の意図が見えてくる。" },
      { type: "heading", content: "二の丸庭園は空いている", level: 2 },
      { type: "text", content: "建物に集中した後、二の丸庭園をゆっくり歩く人は少ない。小堀遠州作の名庭を、人がいない状態で眺められる。建物と庭を合わせて1時間15分が理想の滞在時間。" },
    ],
    relatedArticleSlugs: ["kyoto-budget-temple-pass", "kyoto-kiyomizu-deep-dive"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "kyoto-higashiyama-night-walk",
    title: "東山夜歩き──産寧坂から八坂神社まで、灯籠と石畳の夜",
    description: "三年坂に夜の帳が下りると、昼間の土産物通りが消えて石畳だけが残る。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kyoto",
    tags: ["東山", "夜", "散歩", "石畳", "京都"],
    spotIds: ["kiyomizu", "gion"],
    sections: [
      { type: "heading", content: "19時、清水寺参道の静寂", level: 2 },
      { type: "text", content: "清水道のバス停を降りると、夜の茶碗坂が始まる。昼間の土産物屋は閉まり、白い壁の民家の格子から光が漏れる。この通りを1人で歩くと、時代が少しずれた感覚がある。" },
      { type: "spot-card", content: "kiyomizu" },
      { type: "heading", content: "産寧坂から二年坂へ、石畳を降りる", level: 2 },
      { type: "text", content: "三年坂（産寧坂）の石段を降りる。昔、ここで転んだら三年以内に死ぬという言い伝えがある。夜は足元が見づらいので、言い伝え通り慎重に歩くことになる。" },
      { type: "heading", content: "八坂神社で参拝して終わる", level: 2 },
      { type: "text", content: "二年坂から石塀小路を抜けると八坂神社に出る。境内の灯籠が常時点灯しており、24時間参拝可能。夜の朱塗り楼門は、昼間とまったく異なる威圧感がある。" },
      { type: "spot-card", content: "gion" },
    ],
    relatedArticleSlugs: ["kyoto-higashiyama-night-walk", "kyoto-couple-night-illumination"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "kyoto-golden-pavilion-guide",
    title: "金閣寺を後悔なく見る──時間帯・季節・撮影位置の全戦略",
    description: "金閣寺は誰でも知っている。でも「正しく見た」人は意外と少ない。",
    coverImage: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=1200&q=80",
    publishedAt: "2025-04-18",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "kyoto",
    tags: ["金閣寺", "世界遺産", "撮影", "京都", "定番"],
    spotIds: [],
    sections: [
      { type: "heading", content: "開門9時の10分前に並ぶ", level: 2 },
      { type: "text", content: "金閣寺の混雑は10時以降に爆発する。9時の開門に合わせて並ぶと、最初の15分だけは池の前に人が少ない状態で写真が撮れる。それ以降は逆に混む一方。" },
      { type: "heading", content: "撮影位置は2か所だけ決める", level: 2 },
      { type: "text", content: "「鏡湖池と金閣」の定番位置と、裏山から見下ろす「陸舟の松」の場所。この2か所で2枚撮れば金閣寺の撮影は完了。それ以外に時間をかけない。" },
      { type: "heading", content: "雪の日に予定を変更する勇気を持つ", level: 2 },
      { type: "text", content: "京都に雪が積もるのは年に数回。その朝、予定を変更して金閣寺に行くと、金と白の対比を見られる。この光景を見た人は全員「来てよかった」と言う。" },
    ],
    relatedArticleSlugs: ["kyoto-photo-spot-golden-hour", "kyoto-budget-temple-pass"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "kyoto-nishijin-textile-walk",
    title: "西陣を歩く──織物の街が生きた産業地帯である理由",
    description: "西陣は観光地ではない。今も機屋が動き、帯の音がする現役の職人街だ。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-12",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kyoto",
    tags: ["西陣", "職人", "工芸", "一人旅", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "西陣織会館から入らない方がいい理由", level: 2 },
      { type: "text", content: "西陣織会館は観光客向けの展示施設。本当の西陣はその周囲の路地にある。築60年以上の町家から「ガチャンガチャン」という機械音が聴こえたら、それが現役の機屋だ。" },
      { type: "heading", content: "café marble の建物を見よ", level: 2 },
      { type: "text", content: "西陣の「café marble」は、大正時代の西陣织物工場を改装したカフェ。梁と機械の残滓が空間を構成している。コーヒーを飲みながら、この建物が持つ産業史を想像する。" },
      { type: "heading", content: "一条通りの骨董商を冷やかす", level: 2 },
      { type: "text", content: "西陣と接する一条通りは骨董商が集まる通り。帯地を使ったポーチや、西陣織の端切れが数百円で売られている。着物より「織物の断片」を持ち帰る方が、旅の記念として重みがある。" },
    ],
    relatedArticleSlugs: ["kyoto-solo-day-walk", "kyoto-machiya-stay"],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "kyoto-summer-gion-matsuri",
    title: "祇園祭を正しく楽しむ──山鉾巡行より宵山の夜が本番",
    description: "テレビで映る山鉾巡行は観覧席が必要。でも宵山の夜は誰でも祭の中に入れる。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-07-14",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "kyoto",
    tags: ["祇園祭", "夏", "祭", "京都", "宵山"],
    spotIds: ["gion"],
    sections: [
      { type: "heading", content: "宵山は7月14〜16日の夜", level: 2 },
      { type: "text", content: "山鉾巡行（7月17日）より、その前夜の宵山が体験として上だと思う。各山鉾町が提灯で照らされ、囃子方が鉦（かね）を叩く。その音が重なった瞬間、夏の京都の核心に触れる。" },
      { type: "spot-card", content: "gion" },
      { type: "heading", content: "チマキと粽の違いを知っておく", level: 2 },
      { type: "text", content: "祇園祭で売られる「粽（ちまき）」は食べ物ではなく、魔除けの飾り物。各山鉾町によってデザインが異なる。鶏鉾の粽と長刀鉾の粽は意味が違う。家に飾ると1年間厄除けになるとされる。" },
      { type: "heading", content: "後祭は前祭より空いている", level: 2 },
      { type: "text", content: "祇園祭は前祭（7月17日）と後祭（7月24日）の2回ある。後祭は観光客が少なく、山鉾を間近で見られる。大船鉾と南観音山は後祭にしか出ない。" },
    ],
    relatedArticleSlugs: ["kyoto-higashiyama-night-walk", "kyoto-photo-spot-golden-hour"],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "kyoto-kinkakuji-to-ryoanji-walk",
    title: "金閣寺から龍安寺まで歩く──北山エリア午前半日コース",
    description: "タクシーで移動する観光客が多いが、金閣寺から龍安寺は歩いて20分。歩かないと損している。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "kyoto",
    tags: ["金閣寺", "龍安寺", "モデルコース", "北山", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "9時：金閣寺で開門を迎える", level: 2 },
      { type: "text", content: "金閣寺を9時に出ると、10時前に龍安寺に到着できる。この2時間が北山エリアの黄金時間帯。観光バスが到着するのは10時以降だから、どちらも比較的空いた状態で見られる。" },
      { type: "heading", content: "金閣寺から龍安寺の道：きぬかけの路", level: 2 },
      { type: "text", content: "両寺を結ぶ「きぬかけの路」は、西大路通りから続く緑の道。沿道に松の並木が続き、歩いているだけで気分が上がる。自転車で来ている地元の学生とすれ違う、普通の京都の朝がある。" },
      { type: "heading", content: "龍安寺の石庭：座って15分待つ", level: 2 },
      { type: "text", content: "龍安寺の石庭は「立ち止まって写真1枚」で終わらせてはいけない。縁側に座って最低15分。石の配置と砂の目を見続けると、意識が変化する瞬間が来る。これを体験した人だけが龍安寺の意味を理解できる。" },
    ],
    relatedArticleSlugs: ["kyoto-golden-pavilion-guide", "kyoto-nishiki-market-morning"],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "kyoto-sweets-wagashi-tour",
    title: "和菓子の京都──老舗3軒で食べ比べる「京菓子」の本気",
    description: "上生菓子は食べ物ではなく、季節の小宇宙だ。3軒の京菓子を食べると、京都の美意識が手に取るようにわかる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "kyoto",
    tags: ["和菓子", "上生菓子", "グルメ", "老舗", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "俵屋吉富：上生菓子の基準点", level: 2 },
      { type: "text", content: "烏丸通りの俵屋吉富は、上生菓子の教科書的な存在。季節ごとに変わる銘菓は、食べる前に名前を聞くのが作法。名前を知ってから口に入れると、味の解像度が変わる。" },
      { type: "heading", content: "鶴屋吉信：ライブで作る「つくり菓子」", level: 2 },
      { type: "text", content: "鶴屋吉信では「京菓子づくり体験」があり、目の前で職人が菓子を仕上げる実演を見られる。自分でつまんで食べる体験は、和菓子を「見る」から「作るもの」として認識し直すきっかけになる。" },
      { type: "heading", content: "出町ふたば：庶民の和菓子に帰る", level: 2 },
      { type: "text", content: "高級和菓子を2軒回った後、出町ふたばの豆大福（220円）を食べる。行列30分で買う豆大福は、お茶とセットで食べなくても十分すぎるほどの完成度。最高の食体験が必ずしも高額である必要はないと教えてくれる。" },
    ],
    relatedArticleSlugs: ["kyoto-nishiki-market-morning", "kyoto-gourmet-course-hanamikoji"],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "kyoto-bamboo-grove-dawn",
    title: "竹林の夜明け──嵐山、午前5時の静寂を独り占めする方法",
    description: "世界中の観光客が来る嵐山の竹林も、夜明け前だけは本当に誰もいない。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-09-22",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "kyoto",
    tags: ["竹林", "早朝", "嵐山", "一人旅", "写真映え"],
    spotIds: ["arashiyama"],
    sections: [
      { type: "heading", content: "5時15分：竹林に光が入り始める瞬間", level: 2 },
      { type: "text", content: "夏至前後は5時過ぎに空が明るくなる。竹の間から差し込む最初の光は、わずか10分で消える。この瞬間のためだけに早起きする価値が確実にある。" },
      { type: "spot-card", content: "arashiyama" },
      { type: "heading", content: "6時：人が来る前に天龍寺の前庭を歩く", level: 2 },
      { type: "text", content: "天龍寺の拝観は8時30分から。ただし門前の塔頭（たっちゅう）庭園の一部は早朝から自由に歩ける。手入れされた苔庭に朝露が残る時間帯は、人生でトップ5に入る「いい朝」になる。" },
      { type: "heading", content: "帰りの電車で眠る贅沢", level: 2 },
      { type: "text", content: "嵐電嵐山駅の6時台は空いている。帰りの車内でうとうとしながら戻る朝が、一人旅の完成形だと思う。京都駅でモーニングを食べて締めてもいい。" },
    ],
    relatedArticleSlugs: ["kyoto-bamboo-grove-dawn", "kyoto-photo-spot-golden-hour"],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "kyoto-family-sweets-making",
    title: "親子で体験する和菓子作り──京都で子どもが集中できる90分",
    description: "子どもが京都で一番集中するのは寺でも博物館でもない。和菓子を「作る」体験だ。",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    publishedAt: "2025-05-08",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "kyoto",
    tags: ["子連れ", "和菓子", "体験", "家族", "京都"],
    spotIds: [],
    sections: [
      { type: "heading", content: "四条烏丸の体験教室は予約が必須", level: 2 },
      { type: "text", content: "京都市内には観光客向けの和菓子体験が20か所以上ある。子ども連れには「葛菓子づくり」か「練り切り」がおすすめ。葛は火を使うので小学生以上向け。練り切りは幼稚園児でも形を作れる。" },
      { type: "heading", content: "子どもが作った菓子を持ち帰らせる", level: 2 },
      { type: "text", content: "体験後、自分が作った菓子を箱に入れて持ち帰れる教室が多い。祖父母へのお土産にすると、帰宅後の会話が生まれる。旅の記憶を家族全体で共有する仕掛けとして優秀。" },
      { type: "heading", content: "体験後は近くの公園で食べる", level: 2 },
      { type: "text", content: "二条城近くなら「京都御苑」が広い。自分が作った和菓子をお茶と一緒に食べる野点（のだて）スタイルを真似て、持参した水筒のお茶と一緒に食べると、子どもの記憶に深く刻まれる。" },
    ],
    relatedArticleSlugs: ["kyoto-family-fushimi", "kyoto-sweets-wagashi-tour"],
  },
];
