import { Article } from "@/types/article";

export const miyazakiArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "miyazaki-takachiho-gorge-morning",
    title: "高千穂峡、早朝のボート──霧の中から真名井の滝が落ちてくる",
    description: "観光客が押し寄せる前の高千穂峡は、柱状節理の壁面に霧がかかり、神話の時間そのものになる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-08",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "miyazaki",
    tags: ["高千穂峡", "ボート", "早朝", "滝", "神話"],
    spotIds: ["takachiho-gorge"],
    sections: [
      { type: "heading", content: "ボート受付は開門直後に行け", level: 2 },
      { type: "text", content: "高千穂峡のボートは1日200艘の定員制で、週末は開門前から行列ができる。8時30分の開門に合わせて駐車場に入り、受付で整理券を受け取るのが最初のミッションだ。待ち時間が1時間以上になる日も多いが、その間に遊歩道を散策して峡谷の全景を楽しめる。" },
      { type: "spot-card", content: "takachiho-gorge" },
      { type: "heading", content: "真名井の滝をボートから見上げる", level: 2 },
      { type: "text", content: "ボートが滝壺に近づくと、17mの高さから落ちる水の音が増していく。見上げると、両側の柱状節理の断崖の間から細い空が切り取られ、滝だけが光って見える。雨上がりの翌朝は水量が増し、滝しぶきがボートの上まで届く。カッパを持参すること。" },
      { type: "heading", content: "ボート返却後の遊歩道散策", level: 2 },
      { type: "text", content: "ボートを返却した後、遊歩道を上流方向に約20分歩くと「御橋」展望台に着く。ここから見下ろす峡谷全体と真名井の滝は、パンフレットに使われる定番アングルだ。午前中の光が滝に正面から当たる時間帯が最も写真映えする。" },
    ],
    relatedArticleSlugs: ["miyazaki-takachiho-mythology-night", "miyazaki-aoshima-beach-guide"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "miyazaki-takachiho-mythology-night",
    title: "高千穂神社の夜神楽──神話の踊りを毎晩20時から見る",
    description: "アマテラスが隠れた天岩戸の物語が、今夜も舞台の上で繰り広げられる。宮崎最高の夜体験。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-12",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "miyazaki",
    tags: ["高千穂神社", "夜神楽", "神話", "文化体験"],
    spotIds: ["takachiho-gorge"],
    sections: [
      { type: "heading", content: "毎晩20時、神話の舞台が始まる", level: 2 },
      { type: "text", content: "高千穂神社の神楽殿では毎晩20時から約1時間、「高千穂神楽」の公演が行われる（年中無休）。入場料800円で、4演目が披露される。「手力雄の舞」「鈿女の舞」「戸取の舞」「御神体の舞」の順で、天岩戸伝説の一連のシーンを舞で表現する。" },
      { type: "heading", content: "天岩戸神社との組み合わせで神話を深読みする", level: 2 },
      { type: "text", content: "昼間に天岩戸神社を参拝してから夜神楽を見ると、理解度が格段に上がる。天照大神が隠れた「天岩戸」とされる岩窟を御神体として祀る天岩戸神社は、高千穂町の北西に位置し、バスで20分ほど。宮司による説明を聞いてから公演に臨むと、舞の意味が体に入ってくる。" },
      { type: "heading", content: "神楽の後は高千穂の居酒屋で一杯", level: 2 },
      { type: "text", content: "夜神楽が終わる21時以降でも開いている居酒屋が高千穂町内にある。地元産の「高千穂牛」の炭火焼きと宮崎焼酎を組み合わせるのが地元流だ。焼酎は「天照大神」「神楽」など神話にちなんだ銘柄が町内の酒屋に揃っている。" },
    ],
    relatedArticleSlugs: ["miyazaki-takachiho-gorge-morning", "miyazaki-shochu-brewery-tour"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "miyazaki-aoshima-beach-guide",
    title: "青島の歩き方──鬼の洗濯板と亜熱帯植物、干潮のタイミングが全て",
    description: "青島は満潮と干潮で全く別の顔を見せる島だ。訪問前に潮位表を確認する習慣をつけること。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "miyazaki",
    tags: ["青島", "鬼の洗濯板", "干潮", "亜熱帯", "神社"],
    spotIds: ["aoshima"],
    sections: [
      { type: "heading", content: "干潮の時間を必ず調べていくこと", level: 2 },
      { type: "text", content: "青島の最大の見どころ「鬼の洗濯板」は、干潮時にしか全体が見えない。スマホの潮位アプリか宮崎地方気象台の潮汐予報で事前確認が必須だ。満潮時は岩の表面がほぼ水没し、波状岩の迫力が半減する。干潮の前後2時間が観察のベストタイム。" },
      { type: "spot-card", content: "aoshima" },
      { type: "heading", content: "ビロウ椰子の森を抜けて神社へ", level: 2 },
      { type: "text", content: "橋を渡って島に入ると、両側からビロウ椰子が覆い被さる。国指定天然記念物であるこの亜熱帯植物群落は、南国感が本物だ。島の中心に位置する青島神社は縁結びの神として有名で、絵馬の数が圧倒的。「幸せの黄色いポスト」は近年カップルの定番スポットになっている。" },
      { type: "heading", content: "帰りは青島ビーチでサーフィン観戦", level: 2 },
      { type: "text", content: "橋を渡ったすぐ左手の青島海水浴場は、宮崎サーフィン文化の発信地のひとつ。夏はサーファーが一日中波に乗る様子が見られる。近くの「道の駅フェニックス」では宮崎名物のマンゴーソフトクリーム（450円）が通年販売されている。" },
    ],
    relatedArticleSlugs: ["miyazaki-nichinan-coast-drive", "miyazaki-udo-shrine-cliffside"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "miyazaki-udo-shrine-cliffside",
    title: "鵜戸神宮──断崖の洞窟に宿る神様と、運玉投げの真剣勝負",
    description: "本殿が洞窟の中にある「下り宮」は日本でも珍しい。断崖から見渡す太平洋の迫力は圧倒的だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "miyazaki",
    tags: ["鵜戸神宮", "洞窟神社", "パワースポット", "日南海岸"],
    spotIds: ["udo-shrine"],
    sections: [
      { type: "heading", content: "石段を降りると神話の空間に入る", level: 2 },
      { type: "text", content: "鵜戸神宮は珍しい「下り宮」で、本殿に向かうほど高度が下がる。急な石段を降りると、太平洋に向かって口を開けた海蝕洞窟が現れ、朱塗りの本殿が洞窟の奥に鎮座している。午前中の光が洞窟の入口から差し込む時間帯（9〜11時頃）が最も神秘的な雰囲気になる。" },
      { type: "spot-card", content: "udo-shrine" },
      { type: "heading", content: "運玉投げは男性左手、女性右手が鉄則", level: 2 },
      { type: "text", content: "境内で販売される素焼きの「運玉」（5個100円）を亀の形をした岩の上にある升の穴に投げ入れると願いが叶うとされる。男性は左手、女性は右手で投げるのがルール。穴までの距離は約5m。成功率は10〜20%ほどで、入った瞬間の達成感は格別だ。" },
      { type: "heading", content: "崖上の展望台から見る太平洋", level: 2 },
      { type: "text", content: "参拝を終えて石段を登り返し、鳥居付近の展望エリアから日向灘を見渡すと、水平線まで遮るものがない絶景が広がる。5月から9月はウミガメが産卵に来ることがある浜辺が眼下に見え、夏の早朝は産卵後の砂の痕跡が確認できることもある。" },
    ],
    relatedArticleSlugs: ["miyazaki-nichinan-coast-drive", "miyazaki-aoshima-beach-guide"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "miyazaki-nichinan-coast-drive",
    title: "日南海岸ドライブ完全版──青島から飫肥まで、R220の絶景ルート",
    description: "宮崎を代表するシーサイドロードを、止まるべき場所と通過すべき場所に分けて完全解説。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "miyazaki",
    tags: ["日南海岸", "ドライブ", "絶景", "飫肥", "海"],
    spotIds: ["udo-shrine", "aoshima"],
    sections: [
      { type: "heading", content: "青島から南へ、フェニックスロード", level: 2 },
      { type: "text", content: "国道220号線は「フェニックスロード」の愛称を持つ日南海岸沿いの絶景ドライブルート。宮崎市の青島から日南市を経て、串間市まで約70kmが続く。道の駅「フェニックス」は宮崎市側の起点で、絶壁の展望台から日向灘と堀切峠の全景が見える。" },
      { type: "heading", content: "飫肥城下町で昼食を取る", level: 2 },
      { type: "text", content: "日南市中心部から山側に少し入った飫肥（おび）は、江戸時代の城下町の雰囲気が残る重要伝統的建造物群保存地区。「飫肥天」という厚揚げに似た郷土料理を歩きながら食べるのが定番だ。伊東家の城下町として繁栄した武家屋敷の石垣と白壁が続く路地は、映画のロケ地にもなっている。" },
      { type: "heading", content: "日南海岸を夕暮れ時に走る", level: 2 },
      { type: "text", content: "海岸線を南下する場合、西向きに沈む夕日は右手（山側）になる。だが、北上ルートで夕刻に走ると海側に夕日が落ちる絶景になる。都井岬の野生馬を見てから宮崎市へ戻るルートなら、夕日を正面に受けながらフェニックスロードを走ることができる。" },
    ],
    relatedArticleSlugs: ["miyazaki-udo-shrine-cliffside", "miyazaki-aoshima-beach-guide"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "miyazaki-miyazaki-beef-guide",
    title: "宮崎牛の食べ方完全ガイド──A5等級を宮崎市で食べる正しい店選び",
    description: "和牛オリンピック3大会連続日本一の宮崎牛。産地で食べる価格は東京の7割以下という事実。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "miyazaki",
    tags: ["宮崎牛", "A5和牛", "焼肉", "グルメ", "宮崎市"],
    spotIds: ["aoshima"],
    sections: [
      { type: "heading", content: "宮崎牛は「産地価格」が本物", level: 2 },
      { type: "text", content: "宮崎牛は全国流通する際に東京・大阪の相場で売られるが、宮崎市内の焼肉店は仕入れ価格が低いため、同じ等級でも1〜2割安い。宮崎駅周辺の「焼肉牛源」（国道沿い、¥4,000前後/人）や「万徳」（地元民御用達、¥5,000前後/人）はコスパが高いと地元民に評判だ。" },
      { type: "heading", content: "ステーキならランチが最もお得", level: 2 },
      { type: "text", content: "宮崎市のステーキ文化は全国屈指で、ランチタイムのステーキ定食は150g前後で1,500〜2,500円という価格帯がある。「おぐら本店」はチキン南蛮の発祥店として有名だが、宮崎牛ステーキも本格的でランチセットが充実している。" },
      { type: "heading", content: "宮崎牛を土産として持って帰る方法", level: 2 },
      { type: "text", content: "宮崎空港内の「宮崎ぼ〜の」や駅ビルの精肉店では、保冷バッグ付きの宮崎牛パックを販売している。冷凍真空パックなら飛行機で持ち帰れる。A5ロース100gが1,200〜1,800円ほどで、東京の百貨店の3〜4割安い。" },
    ],
    relatedArticleSlugs: ["miyazaki-chicken-nanban-origin", "miyazaki-mango-farm-visit"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "miyazaki-chicken-nanban-origin",
    title: "チキン南蛮の発祥を追う──おぐら本店と直伝のタルタルソース",
    description: "チキン南蛮は宮崎が生んだ料理だ。発祥の店と変遷の歴史を知ってから食べると味が変わる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "miyazaki",
    tags: ["チキン南蛮", "おぐら", "宮崎グルメ", "発祥"],
    spotIds: ["aoshima"],
    sections: [
      { type: "heading", content: "おぐら本店が1965年に作った元祖レシピ", level: 2 },
      { type: "text", content: "チキン南蛮は1965年頃、宮崎市の洋食店「おぐら」の調理師が作ったとされる。元祖はタルタルソースなしで、甘酢だけをまとったシンプルな料理だった。タルタルソースは後から別の店が加えた派生形で、現在はこちらが標準になっている。おぐら本店は宮崎市高千穂通りにあり、ランチ時は行列必至。" },
      { type: "heading", content: "元祖vs現代版、食べ比べる価値", level: 2 },
      { type: "text", content: "おぐらの「チキン南蛮」（¥1,100）は甘酢ベースでタルタルが後乗せ選択式。一方、市内に多数ある「直伝系」の店はタルタルがたっぷり乗る。同じ名前でも根本的にアプローチが違うため、一日に両方食べ比べると宮崎フードカルチャーの深さを実感できる。" },
      { type: "heading", content: "スーパーでも売られる宮崎のチキン南蛮文化", level: 2 },
      { type: "text", content: "宮崎では一般家庭のスーパーにもチキン南蛮専用のタルタルソースが並ぶ。地元メーカー「くにびし」のタルタルソースは地元で圧倒的なシェアを持つ。土産として持ち帰ると、家でプロに近い味が再現できる。" },
    ],
    relatedArticleSlugs: ["miyazaki-miyazaki-beef-guide", "miyazaki-mango-farm-visit"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "miyazaki-mango-farm-visit",
    title: "宮崎マンゴー農園訪問──太陽のタマゴが生まれる場所を見る",
    description: "1玉1万円を超えることもある「太陽のタマゴ」。その厳格な基準と農家の情熱を農園で体感する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "miyazaki",
    tags: ["マンゴー", "太陽のタマゴ", "農園", "宮崎フルーツ"],
    spotIds: ["aoshima"],
    sections: [
      { type: "heading", content: "「太陽のタマゴ」の規格とは何か", level: 2 },
      { type: "text", content: "「太陽のタマゴ」はJA宮崎経済連の登録商標。重量350g以上、糖度15度以上、果皮の着色基準（黄色50%以上）の全てを満たしたものだけが名乗れる。2007年には1玉30万円の競り落とし価格を記録した。通常品でも300〜500gが2,000〜5,000円。" },
      { type: "heading", content: "マンゴー農園見学は5〜7月が旬", level: 2 },
      { type: "text", content: "宮崎市郊外や都城市周辺に複数のマンゴー農園体験施設がある。「ファームあいかわ」（宮崎市高岡町）や「サンファームマンゴー農園」では、ハウス内でネットに吊るされたマンゴーを間近で見学でき、試食や産地直送購入もできる。予約制が多いので事前に電話確認を。" },
      { type: "heading", content: "宮崎のマンゴースイーツを制覇する", level: 2 },
      { type: "text", content: "JR宮崎駅の「マンゴーソフトクリーム」（500円）は宮崎の定番土産だが、宮崎市橘通の「マンゴーロール」を出す菓子店「石原製菓」のロールケーキは、地元民が贈答品に使う本格派だ。シーズン限定の生マンゴーかき氷（¥1,500〜）は宮崎市内の複数カフェで提供される。" },
    ],
    relatedArticleSlugs: ["miyazaki-miyazaki-beef-guide", "miyazaki-surfing-coast"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "miyazaki-shochu-brewery-tour",
    title: "宮崎焼酎の蔵元を巡る──霧島山麓で芋と麦の蒸留所を訪ねる",
    description: "宮崎は鹿児島と並ぶ焼酎の聖地だ。蔵元直送の試飲と蒸留工程の見学は、旅の記憶に深みを加える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "miyazaki",
    tags: ["焼酎", "蔵元", "芋焼酎", "麦焼酎", "霧島"],
    spotIds: ["takachiho-gorge"],
    sections: [
      { type: "heading", content: "宮崎焼酎の二大産地、都城と高千穂", level: 2 },
      { type: "text", content: "宮崎の焼酎産地は大きく「都城・霧島山麓エリア」と「高千穂エリア」に分かれる。都城は「霧島酒造」「雲海酒造」など大手が集積し、高千穂エリアは小規模蔵が点在する。霧島酒造（都城市）は工場見学を無料で受け付けており、芋焼酎の製造工程を70分で見学できる（要予約）。" },
      { type: "heading", content: "高千穂の地焼酎「天照」を飲む", level: 2 },
      { type: "text", content: "高千穂町内の居酒屋や土産物店では、高千穂地区の地焼酎が並ぶ。「天照」「天翔」「神楽」といった神話にちなんだ銘柄は、アルコール度数25〜35度の芋焼酎で、ロックで飲むと芋の甘みと香りが前面に出る。現地の居酒屋「だいもん」（高千穂町三田井）は地焼酎の種類が50種以上揃う。" },
      { type: "heading", content: "焼酎の土産選び、何を持って帰るか", level: 2 },
      { type: "text", content: "宮崎の焼酎で関東・関西に持ち帰って喜ばれる定番は「木挽BLUE」（雲海酒造、900ml ¥1,500）と「赤霧島」（霧島酒造、900ml ¥1,800）。どちらも全国流通品だが産地で買うと100〜200円安い。限定品では「極みの焼酎」シリーズ（蔵元直販限定）が焼酎好きへの土産として評価が高い。" },
    ],
    relatedArticleSlugs: ["miyazaki-takachiho-mythology-night", "miyazaki-takachiho-gorge-morning"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "miyazaki-surfing-coast",
    title: "宮崎サーフィン入門──木崎浜と一ッ葉海岸、日本のサーフカルチャーの発信地",
    description: "日本のサーフィン人口の多くが宮崎に集まる。波の特性とビーチの使い分けを初心者向けに解説。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "miyazaki",
    tags: ["サーフィン", "木崎浜", "一ッ葉", "ビーチ", "宮崎"],
    spotIds: ["aoshima"],
    sections: [
      { type: "heading", content: "木崎浜は日本サーフィンの聖地", level: 2 },
      { type: "text", content: "宮崎市南部の木崎浜海水浴場は、日向灘からのうねりを受ける地形でコンスタントに波が立つ。ワールドサーフリーグ（WSL）のジャパンオープンが過去に開催された実績を持つ。初心者向けのスクールは「ビーチサイドサーフスクール」（¥5,000〜/回、ボードとスーツ込み）が青島近くにある。" },
      { type: "heading", content: "一ッ葉海岸はファミリー向け", level: 2 },
      { type: "text", content: "宮崎市北部の一ッ葉海岸は、波が比較的穏やかで初心者やファミリーに向いている。フラットな砂浜が続き、シーカヤックやスタンドアップパドルボード（SUP）のレンタルスポットも充実。夕暮れ時はサンセットが海面を染める絶景が見られる。" },
      { type: "heading", content: "宮崎サーフィン文化を体験する食事処", level: 2 },
      { type: "text", content: "木崎浜周辺にはサーファー向けのカフェ・食堂が集まる「サーファーズパラダイス」的エリアがある。「カフェ・ビーチサイド」ではサーフィン後の体に嬉しいボリュームあるランチ（¥950〜）と宮崎地鶏を使った定食が人気。波待ちの様子を眺めながら食事できる席配置が気持ちいい。" },
    ],
    relatedArticleSlugs: ["miyazaki-aoshima-beach-guide", "miyazaki-mango-farm-visit"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "miyazaki-couple-sunset-plan",
    title: "宮崎カップル旅行──青島夕日と日南海岸ドライブの2日間",
    description: "宮崎の海は夕刻にいちばん美しくなる。二人で最高の夕日を見るための宮崎カップルプランを提案。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "miyazaki",
    tags: ["カップル", "夕日", "ドライブ", "青島", "宮崎"],
    spotIds: ["aoshima", "udo-shrine"],
    sections: [
      { type: "heading", content: "1日目：青島と日南海岸北部", level: 2 },
      { type: "text", content: "午前中に青島を観光し（鬼の洗濯板は干潮時間に合わせる）、昼食は青島の「亀の家」で鯛めし（¥1,200）を。午後は国道220号を南下し、堀切峠の展望台で太平洋を眺める。日没1時間前に車を停め、海岸線が夕日で染まる瞬間を二人でゆっくり見る。夕食は宮崎市内の「霧島酒造直営酒場」で焼酎と地鶏炭火焼きを。" },
      { type: "heading", content: "2日目：鵜戸神宮と飫肥城下町", level: 2 },
      { type: "text", content: "午前中に鵜戸神宮を参拝。運玉投げは二人で競うのが楽しい。昼は飫肥城下町で食べ歩き（飫肥天¥150/本）。帰路は「道の駅なんごう」に立ち寄り、亜熱帯植物ガーデンで宮崎の植物の豊かさを体感する。宮崎市内のホテルは「シェラトン・グランデ・オーシャンリゾート」がオーシャンビューで記念日に最適。" },
      { type: "heading", content: "宮崎のカップルにおすすめのグルメ", level: 2 },
      { type: "text", content: "宮崎市の「レストラン青島」は地元でも評判のシーフードレストランで、カウンター席から海を見ながら食事できる（¥3,500〜/人）。デザートはマンゴーパフェを「マンゴーハウス」（宮崎市橘通）で。2人で¥3,000以内で宮崎らしい甘味を体験できる。" },
    ],
    relatedArticleSlugs: ["miyazaki-nichinan-coast-drive", "miyazaki-aoshima-beach-guide"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "miyazaki-family-kids-plan",
    title: "子連れ宮崎旅行2泊3日──海と神話と宮崎グルメを家族で制覇",
    description: "鬼の洗濯板に神話の峡谷、そしてチキン南蛮。子どもが飽きない宮崎の家族旅行完全プランを提案。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "miyazaki",
    tags: ["子連れ", "家族旅行", "宮崎", "2泊3日"],
    spotIds: ["aoshima", "takachiho-gorge", "udo-shrine"],
    sections: [
      { type: "heading", content: "1日目：宮崎市と青島", level: 2 },
      { type: "text", content: "到着後、まず宮崎神宮（市内・無料）を参拝。広い境内で子どもが走れる。昼食は「おぐら本店」でチキン南蛮定食（¥1,100）。午後は青島で鬼の洗濯板と亜熱帯植物を見学（干潮時間を要確認）。夕食は宮崎牛炭火焼きの「焼肉五右衛門」（宮崎市）でA4和牛焼肉を。子ども用の取り皿とハサミ対応も充実。" },
      { type: "heading", content: "2日目：日南海岸と鵜戸神宮", level: 2 },
      { type: "text", content: "朝は一ッ葉海岸でSUP体験（子どもは8歳〜、¥3,500/人）。昼は飫肥城下町で飫肥天食べ歩き。午後に鵜戸神宮参拝──子どもは運玉投げに夢中になる。帰路に「道の駅フェニックス」でマンゴーソフトクリームを食べて宮崎市内のホテルへ。" },
      { type: "heading", content: "3日目：高千穂峡", level: 2 },
      { type: "text", content: "早朝出発で高千穂峡へ（片道約2時間）。ボートは子ども（2歳以上）も乗れる。真名井の滝を間近で見た感動は子どもの記憶に一生残る。高千穂神社の境内をゆっくり散策し、昼食は「食事処そば美峡」（高千穂産そば¥900）を。帰路に「高千穂牧場」に立ち寄るとソフトクリームと動物ふれあいができる。" },
    ],
    relatedArticleSlugs: ["miyazaki-takachiho-gorge-morning", "miyazaki-aoshima-beach-guide"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "miyazaki-solo-mythology-pilgrimage",
    title: "一人旅の宮崎・神話巡礼──高千穂から天岩戸まで2日間の旅",
    description: "日本神話の舞台を一人で歩く旅は、普通の観光と全く違う深さがある。神話地図を持って歩く宮崎。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "miyazaki",
    tags: ["一人旅", "神話", "高千穂", "巡礼"],
    spotIds: ["takachiho-gorge", "udo-shrine"],
    sections: [
      { type: "heading", content: "神話巡礼の拠点は高千穂町に宿泊", level: 2 },
      { type: "text", content: "高千穂エリアの見どころは車で移動するのが基本だが、宿に泊まれば「高千穂バス路線」と徒歩を組み合わせて動くことも可能。「神仙の宿旅館」「高千穂ゲストハウス神話の里」など、バス停近くに泊まれる宿がある。1泊¥5,000〜で翌日の神話巡りが楽になる。" },
      { type: "heading", content: "天岩戸神社──神話最大の事件現場", level: 2 },
      { type: "text", content: "天照大神が岩戸に隠れた伝承の地とされる天岩戸神社は、高千穂神社から車で20分。西本宮の御神体「天岩戸」を見るには神職の案内が必要で、10時・13時・15時の1日3回、無料で参加できる。当日受付でOKだが、一度参加すると高千穂峡の神話世界への理解度が大きく変わる。" },
      { type: "heading", content: "神話の舞台で一人の夜を過ごす", level: 2 },
      { type: "text", content: "高千穂での夜は20時の夜神楽を見た後、町内の「食堂みやざき」で地鶏の炭火焼き（¥1,500）と芋焼酎のお湯割りで締めくくる。山の夜は静かで、宿に戻ると星が澄んで見える。国内有数の天文条件を持つ高千穂は、天文愛好家にも密かに人気の宿泊地だ。" },
    ],
    relatedArticleSlugs: ["miyazaki-takachiho-mythology-night", "miyazaki-takachiho-gorge-morning"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "miyazaki-budget-travel-guide",
    title: "宮崎を格安で楽しむ──無料スポット多数、フェリーと路線バスで動く旅術",
    description: "宮崎は実は節約旅行に向いている。神社・海岸・神話スポットの多くが無料。賢い旅の組み立て方。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "miyazaki",
    tags: ["節約旅行", "バジェット", "格安", "宮崎"],
    spotIds: ["aoshima", "udo-shrine", "takachiho-gorge"],
    sections: [
      { type: "heading", content: "大阪からはフェリーが最安", level: 2 },
      { type: "text", content: "大阪（南港）から宮崎（宮崎カーフェリー）の航路は、雑魚寝席で¥7,000前後（繁忙期は変動）。所要約13時間。夜出発・翌朝到着で移動費を宿泊費に充てられる。春・秋の平日なら片道¥5,500で購入できる早割がある。車を積む場合も1台¥20,000〜で、レンタカー代を節約できる旅人に最適。" },
      { type: "heading", content: "無料で入れる宮崎のスポット一覧", level: 2 },
      { type: "text", content: "青島神社（島全体が無料）、鵜戸神宮（境内無料・運玉購入は任意）、高千穂神社（境内無料・夜神楽¥800）、天岩戸神社見学（無料）、宮崎神宮（無料）と、主要観光地の多くが基本無料だ。食費を1日¥2,000に抑える場合は、コンビニと道の駅の惣菜を活用する。" },
      { type: "heading", content: "宮崎市内はバスで移動できる", level: 2 },
      { type: "text", content: "宮崎市内〜青島間は路線バス（宮崎交通、¥640）で40分。1dayフリーパス（¥800）を使えば宮崎市内の路線バス全線乗り放題だ。高千穂方面は宮崎交通の高速バス（宮崎駅〜高千穂BC ¥1,900、約2時間40分）があり、レンタカーなしでも到達できる。" },
    ],
    relatedArticleSlugs: ["miyazaki-takachiho-gorge-morning", "miyazaki-aoshima-beach-guide"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "miyazaki-autumn-harvest-season",
    title: "秋の宮崎──新米・新焼酎・マンゴーシーズン後のフルーツ王国へ",
    description: "宮崎の秋は収穫の季節だ。9月の新焼酎から10月の柿・みかん・栗まで、食べ歩く秋の旅を設計する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-09-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "miyazaki",
    tags: ["秋旅行", "新焼酎", "収穫", "宮崎フルーツ", "秋"],
    spotIds: ["takachiho-gorge", "aoshima"],
    sections: [
      { type: "heading", content: "9月の「新焼酎」解禁は宮崎の祭り", level: 2 },
      { type: "text", content: "9月1日頃から出回る「新焼酎」は、その年に収穫したサツマイモで仕込んだ新鮮な芋焼酎だ。フレッシュな芋の香りが特徴で、通常品より香りが強く飲みやすい。宮崎市内の焼酎専門酒屋「高千穂酒類」（宮崎市橘通）では10種以上の新焼酎を購入・試飲できる（試飲無料）。" },
      { type: "heading", content: "高千穂峡の秋は紅葉と霧のコラボ", level: 2 },
      { type: "text", content: "高千穂峡の周囲の山は11月上旬から色づく。柱状節理の岩壁と紅葉の組み合わせは、春夏と全く異なる景色を作る。秋の早朝は霧が峡谷に溜まりやすく、霧の上から見下ろすと雲海の中に滝が落ちているような幻想的な光景になる。宿泊して早朝5時に峡谷へ向かう価値がある。" },
      { type: "heading", content: "日南海岸の秋──シーズンオフの静けさと地魚", level: 2 },
      { type: "text", content: "夏の賑わいが去った秋の日南海岸は、地元民の釣り人だけが残る穏やかな海になる。この時期のシイラ（マヒマヒ）釣りは宮崎の秋の風物詩で、釣り船のチャーターは¥10,000〜（4人割り）。釣った魚を翌日の夕食に使う漁師民宿（油津漁港周辺）もある。" },
    ],
    relatedArticleSlugs: ["miyazaki-shochu-brewery-tour", "miyazaki-takachiho-gorge-morning"],
  },
];
