import { Article } from "@/types/article";

export const miyagiArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "miyagi-matsushima-dawn-cruise",
    title: "松島、夜明けの遊覧船──日本三景を独り占めする朝6時の海",
    description: "観光客が動き出す前の松島は、朝霧と松の香りに包まれた静寂の世界だ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-12",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "miyagi",
    tags: ["松島", "日本三景", "遊覧船", "朝", "絶景"],
    spotIds: ["matsushima"],
    sections: [
      { type: "heading", content: "朝霧の中に浮かぶ260の島々", level: 2 },
      { type: "text", content: "松島湾に点在する260余りの島々は、夜明け直後の柔らかい光の中で最も美しい表情を見せる。朝6時台の遊覧船は混雑がなく、デッキを独占することも珍しくない。潮の香りと松の緑が交錯する時間は、日本三景の格を体で理解させてくれる。" },
      { type: "spot-card", content: "matsushima" },
      { type: "heading", content: "遊覧コースの選び方", level: 2 },
      { type: "text", content: "松島湾を巡る遊覧船は複数の航路があり、50分コースと25分コースが定番だ。50分の仁王島コースは外洋近くまで出るため、奇岩の迫力が増す。カモメへの餌やり（かっぱえびせん持参推奨）は子供から大人まで夢中になれる体験だ。" },
      { type: "heading", content: "松島の牡蠣──冬季限定の贅沢", level: 2 },
      { type: "text", content: "11月から3月の松島は牡蠣のシーズンだ。海岸沿いの牡蠣小屋では焼き牡蠣が500円前後から食べられる。大粒で濃厚な仙台湾産の牡蠣は、東京の半額以下で食べられる。遊覧船の後に牡蠣、というのが冬の松島の正解コースだ。" },
    ],
    relatedArticleSlugs: ["miyagi-zuiganji-deep-dive", "miyagi-matsushima-four-seasons"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "miyagi-zuiganji-deep-dive",
    title: "瑞巌寺──伊達政宗が造らせた桃山建築の最高傑作を読み解く",
    description: "国宝の本堂を彩る金碧障壁画と、洞窟参道の陰影が語る伊達家の美意識。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "miyagi",
    tags: ["瑞巌寺", "伊達政宗", "国宝", "歴史", "桃山建築"],
    spotIds: ["zuiganji"],
    sections: [
      { type: "heading", content: "洞窟群から始まる参道の仕掛け", level: 2 },
      { type: "text", content: "瑞巌寺の参道脇には江戸時代に掘られた洞窟群が並ぶ。修行僧の居室や供養のための石仏が刻まれており、本堂に着く前から歴史の重みが積み重なる構造になっている。杉並木の薄暗さと洞窟の静けさが独特の入門体験を作り出している。" },
      { type: "spot-card", content: "zuiganji" },
      { type: "heading", content: "国宝・本堂の障壁画を正面から見る", level: 2 },
      { type: "text", content: "本堂内部の障壁画は狩野派の絵師が描いたもので、豪奢な金地に孔雀や松が描かれる。政宗が江戸城普請のために招いた職人たちが、その腕を松島に残していった。拝観料700円は高くない。" },
      { type: "heading", content: "宝物館で政宗の素顔に触れる", level: 2 },
      { type: "text", content: "隣接する宝物館「青龍殿」には政宗の甲冑や書状が展示されている。等身大の木像と向き合うと、右目のない小柄な武将が、なぜあれほどの権力を築けたのかを改めて考えさせられる。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-dawn-cruise", "miyagi-sendai-castle-history"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "miyagi-sendai-castle-history",
    title: "仙台城跡、政宗騎馬像の下に立つ──伊達62万石の眺望を受け取る",
    description: "青葉山の頂に立つ政宗像は、今も仙台市街を睨み据えている。歴史と展望の両立スポット。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "miyagi",
    tags: ["仙台城", "伊達政宗", "展望", "歴史", "青葉城"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "標高132mから見る仙台平野", level: 2 },
      { type: "text", content: "仙台城跡（青葉城）からの眺めは、晴れた日に仙台平野が一望できる。政宗の騎馬像は大正3年に建てられたもので、太平洋戦争で消失した後、1964年に現在の像が復元された。戦争の痕跡と復興の意志が重なる場所だ。" },
      { type: "spot-card", content: "sendai-castle" },
      { type: "heading", content: "本丸跡の石垣を歩く", level: 2 },
      { type: "text", content: "天守閣は建てられることがなかった仙台城だが、石垣の規模は圧巻だ。野面積みの大石が整然と積み上げられ、400年以上を経ても崩れていない。石垣の上から仙台市街を眺める時間は、歴史教科書では得られない感覚を与えてくれる。" },
      { type: "heading", content: "仙台城見聞館で立体的に理解する", level: 2 },
      { type: "text", content: "城跡隣の仙台城見聞館では、CGで復元した城の姿を見られる。実物の石垣と映像の城を交互に見ることで、廃城になった今でも当時の規模が頭の中で再構築できる。入場無料なので見逃す手はない。" },
    ],
    relatedArticleSlugs: ["miyagi-zuiganji-deep-dive", "miyagi-gyu-tan-guide"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "miyagi-akiu-onsen-healing",
    title: "秋保温泉、仙台から30分の大人の逃げ場──名取川沿いの宿を選ぶ基準",
    description: "奥州三名湯のひとつ、秋保温泉は「杜の都の奥座敷」と呼ばれる理由がある。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "miyagi",
    tags: ["秋保温泉", "温泉", "仙台", "奥州三名湯", "日帰り"],
    spotIds: ["akiu-onsen"],
    sections: [
      { type: "heading", content: "名取川沿いの大型旅館と小宿の違い", level: 2 },
      { type: "text", content: "秋保温泉街には大型旅館と小規模な宿が混在する。大型旅館は露天風呂の広さと食事の豪華さが強みで、小宿はきめ細かいサービスと静けさが売りだ。一人旅なら小宿を、家族連れなら大型施設を選ぶのが賢明だ。" },
      { type: "spot-card", content: "akiu-onsen" },
      { type: "heading", content: "日帰り入浴で試してから泊まる", level: 2 },
      { type: "text", content: "秋保温泉の多くの宿が日帰り入浴（800〜1,500円）を受け入れている。複数の宿の湯を試してから、気に入った宿に宿泊予約を入れるという「湯めぐり作戦」が温泉通の定番だ。アルカリ性単純泉の柔らかい湯は肌への刺激が少なく、敏感肌の人にも向いている。" },
      { type: "heading", content: "秋保大滝と磊々峡の二択", level: 2 },
      { type: "text", content: "温泉の近くには秋保大滝（落差55m）と磊々峡（奇岩の渓谷）がある。紅葉シーズン（10月下旬〜11月上旬）は両方が色づき、温泉と自然の両方を満喫できる。宿のチェックイン前に渓谷を歩き、温泉で疲れを癒すルートが理想的だ。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-dawn-cruise", "miyagi-couple-onsen-plan"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "miyagi-gyu-tan-guide",
    title: "仙台牛タン──本場で食べるための完全ガイド、行列を避ける店選び",
    description: "厚切り塩味、麦飯、テールスープ。戦後仙台が生んだB級グルメが今や世界水準の一品に。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "miyagi",
    tags: ["牛タン", "仙台グルメ", "B級グルメ", "仙台駅", "グルメ"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "牛タンの歴史──焼き鳥屋が生んだ発明", level: 2 },
      { type: "text", content: "仙台の牛タン文化は1948年、太助の初代・佐野啓四郎が米軍払い下げの牛タンを炭火で焼いたことに始まる。フランス料理のシャルキュトリーからヒントを得たとも言われる仙台牛タンは、80年で日本の食文化に定着した。" },
      { type: "heading", content: "老舗3店の個性を知る", level: 2 },
      { type: "text", content: "「利久」は全国展開で安定感があり、「善治郎」は仙台駅構内でアクセス最良、「太助」は発祥の老舗で炭火の香りが際立つ。初めての人には利久の定食（1,800円前後）が牛タンの教科書になる。並び時間は平日午前11時〜12時が最も短い。" },
      { type: "heading", content: "麦飯とテールスープを侮らない", level: 2 },
      { type: "text", content: "牛タン定食の麦飯は食感が白米と異なり、タンの塩味との相性が絶妙だ。テールスープは8時間以上煮込んだコラーゲンたっぷりの一品で、タンを食べた後に飲むと胃が落ち着く。これをセットで食べることで「仙台牛タン」が完成する。" },
    ],
    relatedArticleSlugs: ["miyagi-sendai-castle-history", "miyagi-zunda-sweets-tour"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "miyagi-zunda-sweets-tour",
    title: "ずんだスイーツ巡り──枝豆の甘みが仙台を席巻した理由",
    description: "ずんだ餅からずんだシェイクまで。東北の甘い宝が仙台駅から広がっている。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "miyagi",
    tags: ["ずんだ", "スイーツ", "仙台土産", "餅", "グルメ"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "ずんだとは何か──枝豆を潰した先人の知恵", level: 2 },
      { type: "text", content: "ずんだは枝豆を茹でて薄皮を剥き、すりつぶして砂糖と塩で味付けしたもの。冷蔵技術のない時代に夏場の甘みとして重宝された東北の食文化だ。鮮やかな緑色と穏やかな豆の風味が、現代になって「映える和スイーツ」として再評価されている。" },
      { type: "heading", content: "ずんだ茶寮のシェイクは外せない", level: 2 },
      { type: "text", content: "仙台駅3階の「ずんだ茶寮」のずんだシェイクは常時行列ができる人気商品だ。生の枝豆を使用したシェイクは、コンビニのずんだ商品とは別物の濃さと香りを持つ。680円。テイクアウトして新幹線の中で飲む人が続出しているのも納得の旨さだ。" },
      { type: "heading", content: "手土産にするなら冷凍ずんだ餅", level: 2 },
      { type: "text", content: "宮城ふるさとプラザや駅の土産コーナーには冷凍ずんだ餅が揃う。解凍しても風味が落ちにくく、持ち帰りに最適だ。「村上屋餅店」の生ずんだ餅はもちもち感が別格だが、当日消費が必須なのでその場で食べること。" },
    ],
    relatedArticleSlugs: ["miyagi-gyu-tan-guide", "miyagi-sendai-castle-history"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "miyagi-matsushima-four-seasons",
    title: "松島、四季それぞれの見頃──春の桜から冬の牡蠣まで最適シーズン解説",
    description: "松島は1年中美しいが、シーズンごとに全く異なる顔を見せる。いつ行くかで旅は変わる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "miyagi",
    tags: ["松島", "四季", "桜", "紅葉", "牡蠣"],
    spotIds: ["matsushima"],
    sections: [
      { type: "heading", content: "春（3〜5月）桜と松島湾の共演", level: 2 },
      { type: "text", content: "4月中旬、西行戻しの松公園の桜が満開になると、ピンクと緑と海の青が一枚の絵になる。仙台よりも約3日遅い開花が多く、東北の桜を追いかける旅に組み込むと見頃を複数回体験できる。" },
      { type: "heading", content: "夏（6〜8月）緑の濃い松と七夕", level: 2 },
      { type: "text", content: "夏の松島は松の緑が最も濃く、海の青とのコントラストが鮮明だ。8月6〜8日の仙台七夕まつりと組み合わせる旅程が人気で、仙台市街の飾りつけと松島の自然を一度に楽しめる。" },
      { type: "heading", content: "冬（11〜2月）牡蠣と静寂の松島", level: 2 },
      { type: "text", content: "観光客が減る冬の松島は、島と島の間を漂う霧が幻想的な景色を作る。そして何より牡蠣の季節だ。海岸沿いの「松島さかな市場」では蒸し牡蠣が食べ放題の店もあり、グルメ目的で冬に訪れるリピーターが絶えない。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-dawn-cruise", "miyagi-zuiganji-deep-dive"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "miyagi-couple-onsen-plan",
    title: "仙台近郊カップル温泉プラン──秋保・作並を2泊3日で巡る贅沢",
    description: "東北の温泉を二人で独占する。仙台からアクセス抜群の奥座敷二湯の組み合わせ方。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "miyagi",
    tags: ["カップル", "温泉", "秋保温泉", "作並温泉", "2泊3日"],
    spotIds: ["akiu-onsen"],
    sections: [
      { type: "heading", content: "1日目：仙台市街でグルメ、夕刻に秋保入り", level: 2 },
      { type: "text", content: "仙台駅に降り立ったらまず牛タンで腹ごしらえ。午後はアーケード街「一番町」でずんだ土産を選び、17時に秋保温泉の宿へ。夕食後の貸切風呂予約は必須で、事前に宿に問い合わせておくこと。名取川の川音を聞きながらの半露天は格別だ。" },
      { type: "heading", content: "2日目：秋保大滝から作並温泉へ移動", level: 2 },
      { type: "text", content: "午前中に秋保大滝を散策（片道20分）。豪快な滝の飛沫を浴びた後、仙台市街を経由して作並温泉へ移動（車で約45分）。作並は広瀬川沿いの静かな温泉地で、秋保よりも渓谷感が強い。二湯を比較して好みを語り合うのもカップルの楽しみだ。" },
      { type: "heading", content: "3日目：松島で締める王道ルート", level: 2 },
      { type: "text", content: "最終日は作並から仙台を経由して松島へ（車で約1時間）。遊覧船50分コースで湾内を巡り、瑞巌寺を参拝して松島焼き牡蠣で締める。帰りは仙台駅でずんだシェイクとお土産を調達して完了。温泉、歴史、グルメが全部入った充実の3日間だ。" },
    ],
    relatedArticleSlugs: ["miyagi-akiu-onsen-healing", "miyagi-matsushima-dawn-cruise"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "miyagi-family-trip-plan",
    title: "仙台・松島ファミリー旅行──子連れで楽しむ2泊3日の完全プラン",
    description: "牛タン、遊覧船、カモメへの餌やり。子どもが飽きない仙台・松島の組み合わせ方。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "miyagi",
    tags: ["ファミリー", "子連れ", "松島", "仙台", "2泊3日"],
    spotIds: ["matsushima", "sendai-castle"],
    sections: [
      { type: "heading", content: "1日目：仙台到着、牛タン＆七夕ミュージアム", level: 2 },
      { type: "text", content: "仙台駅構内の牛タン通りで昼食後、仙台七夕ミュージアム（入場300円）でみちのくの祭り文化を学ぶ。夜は仙台城跡の夜間ライトアップを遠望し、駅周辺に宿泊。子ども向けの夕食は牛タンハンバーグも提供する「たんや善治郎」が安心だ。" },
      { type: "heading", content: "2日目：松島でカモメと遊覧船", level: 2 },
      { type: "text", content: "仙台から松島へは仙石線で約40分。遊覧船でカモメへのえびせん餌やりは子どもが大興奮する体験だ。五大堂の廊橋を渡り、松島水族館（または松島離宮）でイルカショーを楽しむ。昼食は松島の穴子丼（900〜1,200円）がおすすめ。" },
      { type: "heading", content: "3日目：秋保で自然体験", level: 2 },
      { type: "text", content: "最終日は秋保大滝植物園（入場200円）で自然観察。小学生以上なら磊々峡の遊歩道を歩くことができ、奇岩の渓谷に歓声が上がる。帰りに秋保温泉の日帰り入浴（子ども半額の宿が多い）で旅の疲れを癒してから仙台駅へ。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-four-seasons", "miyagi-gyu-tan-guide"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "miyagi-tanabata-festival",
    title: "仙台七夕まつり完全攻略──300万人が訪れる東北最大祭りの歩き方",
    description: "8月7日前後の仙台は日本最大の七夕飾りで彩られる。混雑を制する時間帯と路線の選択。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "miyagi",
    tags: ["七夕", "祭り", "仙台", "夏", "イベント"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "七夕飾りの7種類の意味を知る", level: 2 },
      { type: "text", content: "仙台七夕の吹き流し・短冊・折り鶴・巾着・投網・くずかご・紙衣の7種類は、それぞれ技術上達・学業向上・長寿などの願いを込めた飾りだ。アーケード商店街に吊るされた巨大飾りは、職人が数ヶ月かけて準備したものだと知ると見方が変わる。" },
      { type: "heading", content: "8月6日夜の前夜祭が狙い目", level: 2 },
      { type: "text", content: "本祭は8月7〜9日だが、6日夜の花火大会（西公園）は100万人以上が訪れる仙台最大のイベントだ。7日午前10時前に商店街へ行くと、飾りが出揃っていながら観光客が少ない黄金の時間帯がある。昼以降は人波に飲まれる。" },
      { type: "heading", content: "一番町・中央通りの飾り比べ", level: 2 },
      { type: "text", content: "一番町商店街と中央通りでは飾りの規模と趣向が異なる。「七夕コンクール」の入賞作品が掲示されるエリアを地図で確認して、ベスト作品から回るのが効率的だ。写真はアーチ状に飾りが重なる場所を選んで広角で撮ると圧巻の一枚になる。" },
    ],
    relatedArticleSlugs: ["miyagi-sendai-castle-history", "miyagi-matsushima-four-seasons"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "miyagi-matsushima-seafood-guide",
    title: "松島の海鮮を食べ尽くす──牡蠣・穴子・タコの現地価格と名店案内",
    description: "松島湾の幸は東京の半分以下の価格で食べられる。観光地価格の罠を回避する賢い食べ方。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "miyagi",
    tags: ["松島", "海鮮", "牡蠣", "穴子", "グルメ"],
    spotIds: ["matsushima"],
    sections: [
      { type: "heading", content: "松島さかな市場──地元の台所で食べる", level: 2 },
      { type: "text", content: "松島湾沿いの「松島さかな市場」は観光客向けと地元客向けが混在する市場だ。2階の食堂では海鮮丼1,200円前後で食べられ、1階の鮮魚コーナーでは旬の魚を購入して宿の調理室で食べることもできる。" },
      { type: "heading", content: "牡蠣シーズン（11〜3月）の食べ方", level: 2 },
      { type: "text", content: "牡蠣小屋では焼き牡蠣・蒸し牡蠣・生牡蠣を選べる。初めての人には蒸し牡蠣が雑菌リスクが低く、旨みが凝縮されておすすめだ。500円で5〜6個が相場で、レモンと醤油か、ポン酢で食べるのが現地流。" },
      { type: "heading", content: "穴子料理は松島の通年グルメ", level: 2 },
      { type: "text", content: "松島湾産の穴子は脂がのっており、柔らかい白身と甘いタレが合う。穴子丼（900〜1,400円）は牡蠣が終わる夏場のメイン料理として地元で親しまれている。「海風土（シーフード）」や「松島ちりん」などの食堂で年中提供されている。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-dawn-cruise", "miyagi-matsushima-four-seasons"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "miyagi-sendai-budget-trip",
    title: "仙台を1万円で楽しむ──節約しながら牛タンとずんだを制覇する方法",
    description: "交通・宿・グルメを全部含めて1万円台。仙台の魅力を低コストで最大化する旅程。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-05-28",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "miyagi",
    tags: ["節約", "仙台", "バジェット旅", "一人旅", "格安"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "高速バスで仙台入り──新幹線の半額以下", level: 2 },
      { type: "text", content: "東京〜仙台の高速バスは夜行便が3,000〜5,000円（新幹線は10,890円〜）。WILLERやJRバス東北の夜行便は4列シートで十分快適だ。朝5時頃に仙台駅に着けば、朝一番の松島遊覧船（始発8時台）に間に合う。" },
      { type: "heading", content: "仙台城跡は無料、瑞巌寺は700円", level: 2 },
      { type: "text", content: "仙台城跡への入場は無料だ。政宗像、石垣、仙台市街の展望がすべて無料で楽しめる。松島の瑞巌寺拝観料700円と遊覧船片道700円を含めても、観光費は2,000円以下に収まる。" },
      { type: "heading", content: "牛タン定食はランチで食べる", level: 2 },
      { type: "text", content: "牛タン定食はランチとディナーで価格差がほぼない（1,800〜2,200円）が、ランチのほうが並ばずに入れる店が多い。「牛タン焼き定食（並）」で十分の量があり、麦飯おかわり無料の店も多い。食後にずんだシェイク（680円）を飲めば満足度は最大になる。" },
    ],
    relatedArticleSlugs: ["miyagi-gyu-tan-guide", "miyagi-zunda-sweets-tour"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "miyagi-matsushima-luxury-inn",
    title: "松島の高級旅館に泊まる──海景色の客室と懐石料理で過ごす至福の一泊",
    description: "一泊3万円以上の価値がある松島の高級宿。海に面した客室から見る夜明けは別世界だ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "miyagi",
    tags: ["高級旅館", "松島", "海景色", "懐石", "贅沢"],
    spotIds: ["matsushima"],
    sections: [
      { type: "heading", content: "海に張り出した露天風呂付き客室の選び方", level: 2 },
      { type: "text", content: "松島湾に面した旅館の中でも、露天風呂付き客室は早めに埋まる。「松島一の坊」や「松島センチュリーホテル」の海側客室は、窓の外が松島湾のパノラマだ。朝5時に目が覚めたら湯に浸かりながら日の出を見る体験は、生涯の記憶になる。" },
      { type: "heading", content: "松島懐石の食材──海と山の競演", level: 2 },
      { type: "text", content: "松島の高級旅館の夕食は、牡蠣・ホタテ・松島産の穴子に加え、山形産の山菜や蔵王ポークが組み合わされることが多い。仙台牛の鉄板焼きを追加オプションで選べる宿もある。食材の説明を聞きながらゆっくり食べる時間が旅の核心になる。" },
      { type: "heading", content: "翌朝は早起きして遊覧船を独り占め", level: 2 },
      { type: "text", content: "旅館チェックアウト後に松島観光センターの始発遊覧船に乗れば、前日夕方から連続して松島の朝昼を体験できる。高級宿泊後の早朝遊覧というタイムラインが、松島を最も深く理解できる旅の組み方だ。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-dawn-cruise", "miyagi-matsushima-seafood-guide"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "miyagi-sendai-solo-walk",
    title: "仙台一人歩きの午後──アーケード商店街から定禅寺通りまで",
    description: "ケヤキ並木の定禅寺通りは、仙台が「杜の都」と呼ばれる理由を体で教えてくれる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-08-18",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "miyagi",
    tags: ["仙台", "一人旅", "定禅寺通り", "街歩き", "ケヤキ"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "定禅寺通りのケヤキ並木──杜の都の根拠", level: 2 },
      { type: "text", content: "仙台市中心部を走る定禅寺通りは、幅50mの道路の中央分離帯に欅の大木が2列に並ぶ。伊達政宗が城下町建設時に大量の木を植えたことが「杜の都」の起源とされる。秋の黄葉は11月上旬が見頃で、JR仙台駅から徒歩15分。" },
      { type: "heading", content: "一番町アーケードの抜け方", level: 2 },
      { type: "text", content: "仙台駅から西に歩くと国分町・一番町のアーケード商店街に入る。全長約2km、雨でも傘なしで歩けるのが東北最長クラスのアーケードの魅力だ。途中で「藤崎デパート」のずんだスイーツフロアや「勝山館」の日本酒試飲コーナーに立ち寄ると、仙台の食文化が凝縮されている。" },
      { type: "heading", content: "夕方の定禅寺通りでコーヒーと読書", level: 2 },
      { type: "text", content: "定禅寺通りのカフェに落ち着いて、ケヤキの葉陰を眺めながら過ごす午後は、一人旅の醍醐味だ。12月のSENDAI光のページェント期間中は、ケヤキ全体がLEDで輝き、コーヒー片手に眺める夜景は仙台でしか体験できない。" },
    ],
    relatedArticleSlugs: ["miyagi-sendai-castle-history", "miyagi-gyu-tan-guide"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "miyagi-akiu-day-trip",
    title: "仙台から日帰り秋保温泉──3時間で完結する近郊温泉の完璧な使い方",
    description: "仙台駅からバスで40分。午後2時に出発して夜9時に戻れる日帰り温泉の教科書。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "miyagi",
    tags: ["秋保温泉", "日帰り", "仙台", "温泉", "アクセス"],
    spotIds: ["akiu-onsen"],
    sections: [
      { type: "heading", content: "仙台駅西口バスターミナル発、直行40分", level: 2 },
      { type: "text", content: "仙台市営バス「秋保温泉」行きは仙台駅西口から毎時1〜2本運行（所要約40分、760円）。マイカーなら仙台南ICから国道457号経由で約30分。日帰り入浴受付は多くの宿で10時〜15時（入館）で、平日午後2時は最も空いている時間帯だ。" },
      { type: "heading", content: "日帰りパック（入浴＋食事）の賢い使い方", level: 2 },
      { type: "text", content: "秋保温泉の複数の宿が「日帰りパック（入浴＋昼食または夕食）5,000〜8,000円」を提供している。単純に食事代＋入浴料を別々に払うより割安で、仲居さんの案内で風呂と食事の流れがスムーズだ。公式サイトか電話で事前予約が必須。" },
      { type: "heading", content: "磊々峡の散歩を入浴前に入れる", level: 2 },
      { type: "text", content: "秋保温泉バス停から徒歩5分の磊々峡遊歩道は、奇岩が並ぶ渓谷を歩ける無料スポットだ。往復30分の軽い散歩で体を温めてから入浴すると、温泉の浸透が違う。遊歩道の橋からの眺めは紅葉期（11月上旬）が特に美しい。" },
    ],
    relatedArticleSlugs: ["miyagi-akiu-onsen-healing", "miyagi-couple-onsen-plan"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "miyagi-sendai-light-pageant",
    title: "SENDAI光のページェント──140万球のLEDが定禅寺通りを銀河に変える夜",
    description: "毎年12月、140万球のLEDがケヤキを覆う東北最大のイルミネーションの攻略法。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "miyagi",
    tags: ["光のページェント", "イルミネーション", "仙台", "冬", "夜景"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "12月初旬〜31日の開催期間と点灯時間", level: 2 },
      { type: "text", content: "光のページェントは例年12月初旬に始まり、大晦日まで開催される。点灯時間は17時30分〜23時（最終日は24時まで）。定禅寺通り0.9kmのケヤキ並木に140万球のLEDが灯り、仙台市民の年末の風物詩となっている。" },
      { type: "heading", content: "撮影ベストポジションと時間帯", level: 2 },
      { type: "text", content: "撮影は点灯直後の17時30分〜18時が空青と光の混ざる美しい時間帯だ。東一番丁交差点から西方向を撮ると、LEDのトンネルが奥へ続く圧巻の構図になる。週末と年末は人混みが激しく、平日の点灯直後がベストだ。" },
      { type: "heading", content: "周辺グルメと組み合わせる", level: 2 },
      { type: "text", content: "ページェント鑑賞後は定禅寺通り沿いのカフェや、すぐ近くの国分町で牛タンを食べる流れが仙台っ子の定番だ。12月は仙台の老舗和菓子店「白松がモナカ」の季節限定品が並ぶ時期で、土産に一箱持ち帰ると喜ばれる。" },
    ],
    relatedArticleSlugs: ["miyagi-sendai-solo-walk", "miyagi-sendai-castle-history"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "miyagi-matsushima-temple-islands",
    title: "松島の五島巡り──雄島・福浦島・仁王島を一日で歩く冒険コース",
    description: "遊覧船で眺めるだけじゃない。実際に上陸できる島で松島の時間を体と足で感じる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "miyagi",
    tags: ["松島", "島巡り", "福浦島", "雄島", "ハイキング"],
    spotIds: ["matsushima"],
    sections: [
      { type: "heading", content: "福浦橋を渡って福浦島へ（入島200円）", level: 2 },
      { type: "text", content: "朱色の福浦橋（全長252m）を渡ると、遊歩道が整備された福浦島に入れる。島内は松と自然林に覆われており、30〜40分で一周できる。高台からの松島湾眺望は遊覧船からの視点とは全く異なる。体力のある人は早朝に訪れると独占状態になる。" },
      { type: "heading", content: "雄島──霊場の静けさと苔の参道", level: 2 },
      { type: "text", content: "松島湾の中で唯一の霊場として知られる雄島は、渡月橋（無料）で上陸できる。島全体が苔に覆われ、岩壁には江戸時代の修行者が刻んだ碑文が残る。観光客が少ない穴場で、松島の商業的な賑わいとは対照的な静寂がある。" },
      { type: "heading", content: "円通院の美庭──一日の締め", level: 2 },
      { type: "text", content: "島巡りの後は円通院の庭園（拝観料300円）で締める。三慧殿に安置された伊達光宗の厨子には西洋のトランプや十字架が描かれており、17世紀の日本と西洋の交流を物語る。10月のバラ園ライトアップは別途入場料が必要だが圧巻だ。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-dawn-cruise", "miyagi-zuiganji-deep-dive"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "miyagi-shiogama-sushi-tour",
    title: "塩竈の寿司を食べる──松島湾の隣、日本有数の水産地で本物の海鮮を",
    description: "観光地の松島より、寿司なら隣の塩竈が正解。全国から職人が認める魚市場の街。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-03",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "miyagi",
    tags: ["塩竈", "寿司", "海鮮", "魚市場", "グルメ"],
    spotIds: ["matsushima"],
    sections: [
      { type: "heading", content: "塩竈が寿司の聖地である理由", level: 2 },
      { type: "text", content: "塩竈市は三陸沖と松島湾に挟まれ、全国有数の水揚げ量を誇る港町だ。マグロ・ホタテ・牡蠣・穴子のすべてが地元で揚がり、市場から寿司屋まで距離が極めて短い。鮮度の高さが仙台の寿司屋と根本的に異なる。" },
      { type: "heading", content: "塩竈水産物仲卸市場──日曜朝市の迫力", level: 2 },
      { type: "text", content: "毎週日曜日の早朝6時から始まる仲卸市場の一般開放（「日曜朝市」）は、鮮魚・干物・塩蔵品がプロ価格で並ぶ。仙台から仙石線で20分（塩釜駅下車）。早い時間に行かないと目玉商品は売り切れる。" },
      { type: "heading", content: "老舗寿司屋でのカウンター体験", level: 2 },
      { type: "text", content: "塩竈市内には江戸前の技術を持つ老舗寿司店が複数ある。お任せランチが3,000〜5,000円で、仙台市内の同価格帯と比べて魚の質が明確に上だ。予約を入れてから行くことを強く勧める。松島観光と組み合わせると、1日で松島湾の海の幸を360度体験できる。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-seafood-guide", "miyagi-matsushima-dawn-cruise"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "miyagi-sendai-morning-market",
    title: "仙台朝市の使い方──地元民が毎朝通う市場で宮城の食材を発見する",
    description: "JR仙台駅から徒歩5分。昭和の雰囲気が残る朝市で仙台の胃袋を知る。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "miyagi",
    tags: ["朝市", "仙台", "市場", "地元文化", "食材"],
    spotIds: ["sendai-castle"],
    sections: [
      { type: "heading", content: "仙台朝市──戦後の闇市が正規の市場に", level: 2 },
      { type: "text", content: "仙台駅東口近くの仙台朝市は戦後の闇市を起源とし、現在は200店以上が並ぶ公設市場になっている。早朝6時から営業しており、野菜・鮮魚・乾物・惣菜が地元の価格で並ぶ。観光客より地元のお年寄りが多く、仙台の「日常」に潜り込める場所だ。" },
      { type: "heading", content: "朝ごはんに最適な惣菜屋と食堂", level: 2 },
      { type: "text", content: "市場内の惣菜屋では玉こんにゃく（50円）や揚げたての天ぷら（150〜300円）を立ち食いできる。食堂「朝市食堂」では仙台麩の煮物定食が700円で、地元客に混じって食べる朝食は旅の満足度を格段に上げる。" },
      { type: "heading", content: "仙台味噌と牡蠣を土産に選ぶ", level: 2 },
      { type: "text", content: "朝市の乾物・加工品コーナーには宮城の特産品が揃う。仙台味噌（辛口の赤みそ）は真空パックで持ち帰れ、スーパーより品質が高いものが多い。冬季は殻付き牡蠣が格安で売られ、宅配便で自宅に送ることもできる。" },
    ],
    relatedArticleSlugs: ["miyagi-gyu-tan-guide", "miyagi-zunda-sweets-tour"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "miyagi-oshika-peninsula-retreat",
    title: "牡鹿半島の先端へ──金華山と女川で、震災と自然再生の現場に立つ",
    description: "震災から立ち直る漁師町と、神の島・金華山。観光地化されていない宮城の本質がここにある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "miyagi",
    tags: ["牡鹿半島", "金華山", "女川", "震災復興", "自然"],
    spotIds: ["matsushima"],
    sections: [
      { type: "heading", content: "女川──最もきれいな復興の町", level: 2 },
      { type: "text", content: "東日本大震災で壊滅的な被害を受けた女川町は、建築家・坂茂らの設計で美しく再生されたコンパクトシティとして世界から注目されている。シーパルピア女川の商業施設と海の眺めが融合した空間は、震災の記憶と未来への意志が同居している。" },
      { type: "heading", content: "金華山への渡船──野生の鹿と黄金山神社", level: 2 },
      { type: "text", content: "女川または鮎川から渡し船で金華山に渡れる（所要20〜30分）。島内には野生の鹿と猿が生息し、黄金山神社の朱塗りの社殿が原生林に映える。「3年連続で参拝すると金に不自由しない」という言い伝えがあり、東北の人々に信仰される島だ。" },
      { type: "heading", content: "牡鹿半島の海鮮──漁師町直売の鮮度", level: 2 },
      { type: "text", content: "半島沿いの漁村では直売所が点在し、ウニ・ホタテ・ホヤを産地価格で食べられる。特にホヤは宮城が全国生産の大半を占め、新鮮なものは磯の香りと旨みが共存するミネラルの塊だ。苦手意識がある人も産地の新鮮なものを試してほしい。" },
    ],
    relatedArticleSlugs: ["miyagi-matsushima-seafood-guide", "miyagi-shiogama-sushi-tour"],
  },
];
