import { Article } from "@/types/article";

export const nagasakiArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "nagasaki-glover-garden-morning",
    title: "グラバー園、朝9時前の特権──長崎港を独り占めする洋館散歩の作法",
    description: "グラバー園は団体客が来る前の1時間が全てだ。朝の光の中でグラバー住宅と長崎港を眺める体験は、昼間とは別の場所になる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-08",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nagasaki",
    tags: ["グラバー園", "長崎港", "洋館", "早朝", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "開園直後の8時台：団体ツアーが来る前の静寂", level: 2 },
      { type: "text", content: "グラバー園の開園は8時（季節による）。この時間に入ると観光客はほぼいない。グラバー住宅の白い壁に朝の斜光が当たり、長崎港の青い水面と合わさって絵画のような景色が広がる。昼間とは光の方向が全く違い、建物の陰影が際立つ。写真愛好家にとって朝は唯一の時間帯だ。" },
      { type: "spot-card", content: "glover-garden" },
      { type: "heading", content: "動く歩道は「降り」だけ使う：正しい歩き方", level: 2 },
      { type: "text", content: "グラバー園への動く歩道は上りのみ設置されている。帰路は石畳の坂道を歩いて降りるのだが、この下り道が実は見どころだ。大浦天主堂に向かって緩やかに下る坂沿いに、長崎らしい路地と民家が続き、斜面に張り付く街の構造が見えてくる。急ぐ必要はない。" },
      { type: "heading", content: "ハート石探しと「蝶々夫人」の伝説を重ねて歩く", level: 2 },
      { type: "text", content: "園内の石畳には3か所にハート形の石が埋め込まれている。全て見つけると「恋が叶う」という伝説がある。もうひとつの伝説はプッチーニのオペラ「蝶々夫人」だ。グラバーの息子とその妻の物語がモデルになったという説がある。石畳を歩きながら、19世紀の長崎という国際都市の片鱗を感じる時間を持てるかどうかが、グラバー園体験の深さを決める。" },
    ],
    relatedArticleSlugs: ["nagasaki-gunkan-jima-tour", "nagasaki-chanpon-ramen-guide"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "nagasaki-gunkan-jima-tour",
    title: "軍艦島上陸ツアー完全ガイド──予約から上陸まで、廃墟の島を最大限に体験する方法",
    description: "軍艦島は天候次第で上陸できない。それでも行く価値があるのはなぜか。廃墟の島に残る5,000人の生活の痕跡を読む旅。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-22",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nagasaki",
    tags: ["軍艦島", "廃墟", "世界遺産", "ツアー", "長崎"],
    spotIds: ["gunkan-jima"],
    sections: [
      { type: "heading", content: "ツアーの予約は1ヶ月前が理想：上陸率の高い業者の選び方", level: 2 },
      { type: "text", content: "軍艦島上陸ツアーは長崎港発で複数の業者が運航している。上陸率に差があるため、実績の高い「軍艦島コンシェルジュ」か「やまさ海運」を選ぶのが無難だ。波の高い日は上陸できないため、日程に1〜2日の余裕を持って長崎を旅するのが正解。料金は3,500〜4,500円が相場で、長崎市観光振興推進機構への入島料¥300が別途必要。" },
      { type: "spot-card", content: "gunkan-jima" },
      { type: "heading", content: "上陸できなかった日こそ「周回クルーズ」が価値を持つ", level: 2 },
      { type: "text", content: "上陸できなくとも、周回クルーズで島の外周を一周できる。西側の崩れかけた炭鉱施設の迫力は、上陸できるよりも広角で見える分、船上の方が全体像を把握しやすい。特に曇天の日、廃墟がグレーの海に浮かぶ景色は映画のセットのような非現実感がある。" },
      { type: "heading", content: "ガイドの話を聞かないと意味がない：5,000人の生活", level: 2 },
      { type: "text", content: "軍艦島に上陸した際、ガイドが語る内容が体験の質を決定する。最盛期（1960年代）には東京の9倍の人口密度で5,000人が暮らし、学校・病院・映画館・パチンコ店が全て島内にあった。石炭の採掘は海面下600mまで達し、炭鉱夫たちは毎日その深さまで降りて仕事をしていた。廃墟を見るだけでなく、そこに生きた人間の話を聞くことで全く別の場所になる。" },
    ],
    relatedArticleSlugs: ["nagasaki-glover-garden-morning", "nagasaki-peace-park-guide"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "nagasaki-peace-park-guide",
    title: "長崎平和公園で考える──原爆資料館と爆心地が伝える、1945年8月9日",
    description: "長崎に来たなら平和公園に行くべきだ。観光ではなく、向き合う時間を持つ場所だ。何を見て何を感じるかを事前に整理しておく。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nagasaki",
    tags: ["平和公園", "原爆", "長崎", "歴史", "8月9日"],
    spotIds: ["heiwa-koen"],
    sections: [
      { type: "heading", content: "爆心地公園と平和公園は別の場所：順序を決めて回る", level: 2 },
      { type: "text", content: "「爆心地公園」と「平和公園」は徒歩5分ほど離れた別の場所だ。爆心地（浦上地区）は原爆が炸裂した地点そのもので、黒御影石の碑が立つ。平和公園は北村西望の巨大な「平和祈念像」がある。まず爆心地で原爆の地点を確認し、それから平和公園に向かう順序が、意味の流れとして自然だ。" },
      { type: "spot-card", content: "heiwa-koen" },
      { type: "heading", content: "長崎原爆資料館：「実物」が持つ証言力", level: 2 },
      { type: "text", content: "長崎原爆資料館の展示物は実物の力が圧倒的だ。爆心地から数百m以内で溶けたガラス瓶、焼けて止まった時計（11時02分を指したまま）、被爆した聖母マリア像の頭部。これらの「物」が語る爆発の熱と衝撃は、数字や説明文より遥かに直接的に伝わる。じっくり見るなら1.5時間は必要だ。" },
      { type: "heading", content: "8月9日に訪れる：「長崎原爆の日」の式典に立ち会う", level: 2 },
      { type: "text", content: "8月9日午前11時02分、長崎全市でサイレンが鳴り黙祷が行われる。平和公園では平和祈念式典が開催され、被爆者、市民、外国からの参列者が集まる。観光シーズンの混雑とは異なる、静謐で重い時間が流れる。この日に長崎にいることを、旅の目的にする選択肢もある。" },
    ],
    relatedArticleSlugs: ["nagasaki-gunkan-jima-tour", "nagasaki-glover-garden-morning"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "nagasaki-huis-ten-bosch-illumination",
    title: "ハウステンボスの光の王国──日本最大イルミネーションを最大限に楽しむ攻略法",
    description: "ハウステンボスのイルミネーションは日本最大規模だ。1,300万球の光を効率よく全て見るための順路と時間の使い方を伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-02-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagasaki",
    tags: ["ハウステンボス", "イルミネーション", "光の王国", "長崎", "冬"],
    spotIds: ["huis-ten-bosch"],
    sections: [
      { type: "heading", content: "点灯時間の30分前に「花の王国エリア」に入れ", level: 2 },
      { type: "text", content: "イルミネーションの点灯は日没と同時（16時30分〜17時頃）。点灯直後はゲート付近が混雑する。点灯時間の30分前にパーク奥の花の王国エリアに入っておき、点灯の瞬間を暗い場所で迎えると、光が一気に溢れ出す感覚が最大化される。「光の運河」は点灯後15分で撮影者で埋まるため、先回りすること。" },
      { type: "spot-card", content: "huis-ten-bosch" },
      { type: "heading", content: "昼間のハウステンボスは「本物のオランダ建築」を見る", level: 2 },
      { type: "text", content: "ハウステンボスは夜のイルミネーションが有名だが、昼間の運河と洋館の景色も本格的だ。本物のレンガを使ったオランダ式建築が152万㎡の敷地に並んでいる。春（3〜4月）のチューリップ祭は100万球のチューリップが運河沿いに咲き、本場オランダを凌ぐという評価もある。" },
      { type: "heading", content: "1泊2日でホテルヨーロッパに宿泊するプランが最上", level: 2 },
      { type: "text", content: "ハウステンボス内のホテルヨーロッパに泊まると、ゲストは早朝6時から園内に入れる。朝のハウステンボスは宿泊者だけのもので、霧がかかった運河と洋館の景色は午前中の1時間しか見られない。夜のイルミネーションを楽しんだ後、早朝の散歩で締めくくる2日間が最も濃いハウステンボス体験だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-glover-garden-morning", "nagasaki-chanpon-ramen-guide"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "nagasaki-chanpon-ramen-guide",
    title: "長崎ちゃんぽんの真実──「リンガーハット」では食べられない本場の太麺と濃厚スープ",
    description: "長崎ちゃんぽんは全国チェーンと別の食べ物だ。豚骨・鶏ガラ・豚骨ラードが一体となったスープの深さを、長崎で食べて初めて理解する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nagasaki",
    tags: ["ちゃんぽん", "長崎グルメ", "中華街", "郷土料理", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "ちゃんぽんは「四海楼」が元祖：創業者の哲学を知る", level: 2 },
      { type: "text", content: "長崎ちゃんぽんの元祖は南山手の「四海楼」だ。明治32年、中国福建省出身の陳平順が貧しい中国人留学生のために豚骨スープにたっぷりの野菜と豚肉を入れた安くて栄養のある料理を作ったのが始まりとされる。現在も4代目が同じ場所で営業しており、本店の白濁スープは研究する価値がある。" },
      { type: "spot-card", content: "glover-garden" },
      { type: "heading", content: "「皿うどん」は太麺と細麺の2種類がある", level: 2 },
      { type: "text", content: "長崎では「皿うどん」もちゃんぽんと並ぶ定番だ。ちゃんぽんの麺をパリパリに揚げた「細麺皿うどん」と、太麺で炒め焼きにした「太麺皿うどん」があり、全く別の食べ物だ。長崎の地元民は太麺派が多い。ウスターソースをかけるか、中濃ソースをかけるかは好みによる。" },
      { type: "heading", content: "新地中華街でちゃんぽん以外も食べる：長崎中華の奥行き", level: 2 },
      { type: "text", content: "長崎市の新地中華街は横浜・神戸と並ぶ日本三大中華街のひとつ。ちゃんぽん・皿うどん以外に、角煮まんじゅう（豚の角煮を挟んだ蒸しパン）と湯煎饅頭が名物だ。角煮まんじゅうは歩きながら食べられる形式が増えており、中華街散策のおともに最適。" },
    ],
    relatedArticleSlugs: ["nagasaki-castella-bakery-guide", "nagasaki-glover-garden-morning"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "nagasaki-castella-bakery-guide",
    title: "長崎カステラの食べ比べ──福砂屋・文明堂・松翁軒、三大老舗の違いを明確に語る",
    description: "カステラは全部同じではない。卵の比率、グラニュー糖の有無、底面のザラメの量で全く違う菓子になる。長崎三大老舗の正しい比較を伝える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-03-28",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nagasaki",
    tags: ["カステラ", "長崎土産", "老舗菓子", "食べ比べ", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "三大老舗の特徴：福砂屋・文明堂・松翁軒の違い", level: 2 },
      { type: "text", content: "福砂屋（1624年創業）は卵黄の比率が高く、濃い黄色と濃厚な味が特徴。底面のザラメが多い。文明堂（1900年）はふわっとした食感で、甘さが柔らかい。松翁軒（1681年）はシックな甘さで、お茶に最も合う。3店舗全て長崎市内に本店があり、食べ比べは長崎旅行の必修科目だ。" },
      { type: "heading", content: "「切れ端」を買え：B品が最もコスパが高い", level: 2 },
      { type: "text", content: "カステラ老舗では端部分（ザラメが多く残る箇所）の「切れ端」や「B品」が正規品より2〜3割安く買えることがある。パッケージが不揃いなだけで味は全く同じ。福砂屋の本店では「わけあり品」として販売されることがある。土産にするのでなければ切れ端が最もコスパが高い。" },
      { type: "heading", content: "長崎カステラとポルトガル渡来の歴史：南蛮菓子の真実", level: 2 },
      { type: "text", content: "カステラはポルトガルの「パン・デ・ロー」が原型とされる。16世紀に長崎にキリスト教と共に伝わり、日本人の好みに合わせて改良されたのが今のカステラだ。「カステラ」という名前はスペインのカスティーリャ地方から来ているという説がある。長崎はポルトガル・オランダ・中国の食文化が混ざった唯一の場所であり、カステラはその象徴だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-chanpon-ramen-guide", "nagasaki-glover-garden-morning"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "nagasaki-night-view-inasayama",
    title: "稲佐山の夜景──世界三大夜景の一角に選ばれた長崎の夜の全貌",
    description: "稲佐山からの夜景は「すり鉢状の地形」が生む圧倒的な密度がある。香港・モナコと並ぶ世界三大夜景の見方を正しく伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "nagasaki",
    tags: ["稲佐山", "夜景", "世界三大夜景", "長崎港", "カップル"],
    spotIds: ["heiwa-koen"],
    sections: [
      { type: "heading", content: "なぜ長崎の夜景は「世界三大」なのか：地形の魔法", level: 2 },
      { type: "text", content: "長崎の夜景が特別な理由は地形にある。三方を山に囲まれたすり鉢状の地形に家々が張り付き、無数の灯りが傾斜に沿って展開する。平坦な都市では生まれない「立体感」が長崎の夜景を唯一無二にしている。稲佐山（標高333m）の展望台からは長崎港・市街・対岸の山がすべて視野に入る。" },
      { type: "heading", content: "ロープウェイは夕暮れ時が最も価値がある", level: 2 },
      { type: "text", content: "稲佐山へのアクセスはロープウェイが便利で片道¥1,250。夕暮れ時（日没30分前）に乗ると、昼の景色から徐々に夜景に変わる過程を空中から見られる。この「トワイライト」の時間帯が最も美しく、昼夜どちらの夜景よりも複雑な色が長崎港に広がる。" },
      { type: "heading", content: "グラバー園の展望台との比較：角度の違いで別の街に見える", level: 2 },
      { type: "text", content: "グラバー園の展望台（海抜約60m）と稲佐山展望台（標高333m）では夜景の角度が大きく違う。グラバー園からは長崎港を真横から見下ろす構図で、船の灯りと水面の反射が際立つ。稲佐山は街全体を俯瞰する構図で、山肌の灯りの連なりが主役になる。2か所を比較することで長崎の立体的な構造が理解できる。" },
    ],
    relatedArticleSlugs: ["nagasaki-glover-garden-morning", "nagasaki-gunkan-jima-tour"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "nagasaki-dejima-dutch-history",
    title: "出島で江戸時代のオランダを歩く──日本唯一の国際貿易港だった小さな人工島の物語",
    description: "出島は江戸時代、日本とヨーロッパを繋ぐ唯一の窓だった。復元された扇形の人工島で、鎖国の時代に何が行き来していたかを探る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nagasaki",
    tags: ["出島", "オランダ", "江戸時代", "貿易", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "出島は「鎖国の抜け穴」だった：2世紀の秘密", level: 2 },
      { type: "text", content: "江戸幕府の鎖国政策下、オランダ商館だけが出島（長崎港内の扇形の人工島）に居住を許された。商館員は長崎の外には出られず、日本人も出島には入れない。しかしその「鎖の穴」から、蘭学・医学・天文学・兵器技術が日本に流れ込んだ。シーボルトもオランダ商館付き医師として来日し、日本の植物・動物・文化を記録した。" },
      { type: "heading", content: "復元された出島：19世紀初頭の商館を歩く", level: 2 },
      { type: "text", content: "現在の出島は長崎市が復元事業を進めており、商館建物内に当時の生活様式が再現されている。蘭引（オランダ式蒸留装置）、輸入品のサンプル、商館長の居室など実物復元の展示が充実。ガイドツアー（無料）に参加すると展示物の意味が格段に理解しやすくなる。" },
      { type: "heading", content: "出島ワーフから見る現在の長崎港：変わったものと変わらないもの", level: 2 },
      { type: "text", content: "出島に隣接する「出島ワーフ」は飲食店が並ぶウォーターフロント施設だ。かつてオランダ船が停泊した水域を眺めながら食事をすると、250年前に同じ景色を見た商館員の気分が重なる。テラス席からは長崎港を行き来する船が今も見え、港町・長崎の本質は変わっていないことが分かる。" },
    ],
    relatedArticleSlugs: ["nagasaki-chanpon-ramen-guide", "nagasaki-castella-bakery-guide"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "nagasaki-urakami-cathedral",
    title: "浦上天主堂と被爆マリア──キリシタンの血と涙が染み込んだ、長崎の魂の場所",
    description: "浦上は250年間キリシタンが秘かに信仰を守り続けた場所だ。被爆したマリア像の頭部が語る歴史と信仰の話を伝える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-05-08",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nagasaki",
    tags: ["浦上天主堂", "キリシタン", "被爆マリア", "長崎", "歴史"],
    spotIds: ["heiwa-koen"],
    sections: [
      { type: "heading", content: "浦上の「隠れキリシタン」：250年の秘密の信仰", level: 2 },
      { type: "text", content: "浦上（現在の長崎市浦上地区）は江戸時代を通じてキリスト教が禁じられた時代に、農民たちが秘かに信仰を継続していた場所だ。1873年の禁教解除後、浦上天主堂の建設が始まった。1925年に完成したロマネスク様式の大聖堂は、1945年8月9日の原爆で爆心地から500mの距離にあり、一瞬で崩壊した。" },
      { type: "spot-card", content: "heiwa-koen" },
      { type: "heading", content: "被爆マリア像：首のない聖母が語ること", level: 2 },
      { type: "text", content: "浦上天主堂の旧鐘楼に安置されていた聖母マリア像は、原爆の爆風で頭部が吹き飛んだ。この「被爆マリア」の頭部は長崎原爆資料館に展示されており、顔の一部が溶けて変形している。信仰を持つ人もそうでない人も、この小さな頭部の前に立つと何かが変わる。毎年8月にはローマ法王への示現として聖母像が貸し出される。" },
      { type: "heading", content: "復元された天主堂の内部：ステンドグラスと光の静寂", level: 2 },
      { type: "text", content: "現在の浦上天主堂は1925年の姿に修復されており、内部に入ることができる（礼拝中は入場制限あり）。ステンドグラスから差し込む光が白い石造りの内壁を染める午前中が最も美しい時間帯だ。多くの観光客が外観を撮影して終わるが、内部の静寂に5分間浸ることの方が遥かに価値がある。" },
    ],
    relatedArticleSlugs: ["nagasaki-peace-park-guide", "nagasaki-glover-garden-morning"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "nagasaki-temple-nagasakizaka",
    title: "長崎の坂と寺町を歩く──石畳と異国情緒が混在する、長崎の路地旅",
    description: "長崎は坂の街だ。斜面に貼り付くように家が並ぶ路地を歩くと、どこかポルトガルか中国の街角に迷い込んだような感覚になる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nagasaki",
    tags: ["長崎の坂", "路地歩き", "寺町", "街歩き", "長崎"],
    spotIds: ["glover-garden", "heiwa-koen"],
    sections: [
      { type: "heading", content: "眼鏡橋から寺町通りへ：長崎旧市街を歩く午前のルート", level: 2 },
      { type: "text", content: "眼鏡橋（1634年建造・日本最古の石造アーチ橋）から始まり、中島川沿いを歩いて寺町通りへ進む。寺町通りは江戸時代に20以上の寺が並んでいた地区で、今も複数の寺が残る。興福寺（長崎市最古の唐寺）の赤い山門と境内の静けさは、グラバー園とは全く違う長崎の顔だ。" },
      { type: "heading", content: "斜面の「長崎路地」：地元民しか歩かない急坂の先に", level: 2 },
      { type: "text", content: "グラバー園裏手から南山手の斜面に入ると、観光マップに載っていない急な石段と狭い路地が続く。長崎の家は斜面に張り付くため、玄関が3階にある家、屋根が目の前の道路と同じ高さにある家など、平地の概念が崩れる空間になる。迷子になることを恐れず、高い方に向かって歩くと必ず展望が開ける。" },
      { type: "heading", content: "鍋冠山公園：グラバー園より少ない観光客と広い眺望", level: 2 },
      { type: "text", content: "グラバー園の裏山にある鍋冠山公園（標高約169m）は観光客が少なく、長崎港を見下ろす展望台がある。特に夕方は西日が長崎港を赤く染め、稲佐山からとは逆方向の景色が広がる。グラバー園を出た後、体力があれば20分かけて歩いて登る価値がある。" },
    ],
    relatedArticleSlugs: ["nagasaki-chanpon-ramen-guide", "nagasaki-glover-garden-morning"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "nagasaki-huis-ten-bosch-tulip",
    title: "ハウステンボスのチューリップ祭──100万球の春を歩く3月4月の完全ガイド",
    description: "春のハウステンボスはイルミネーションと別物の美しさを持つ。青空と運河とチューリップが重なる時間のために、3〜4月に来る理由を語る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagasaki",
    tags: ["ハウステンボス", "チューリップ", "春", "長崎", "花"],
    spotIds: ["huis-ten-bosch"],
    sections: [
      { type: "heading", content: "チューリップ祭の最盛期は3月下旬〜4月上旬", level: 2 },
      { type: "text", content: "ハウステンボスのチューリップ祭は100万球以上の球根を植えた日本最大規模のイベントだ。長崎の温暖な気候で例年3月下旬〜4月上旬が最盛期となる。オランダ原産の希少品種を含む約100種類のチューリップが色別に整然と並び、オランダ式建築との組み合わせが「ヨーロッパそのもの」と評される。" },
      { type: "spot-card", content: "huis-ten-bosch" },
      { type: "heading", content: "運河沿いのチューリップ：ゴンドラから眺める角度が最高", level: 2 },
      { type: "text", content: "ハウステンボスの運河沿いに植えられたチューリップはゴンドラから眺める角度が最も美しい。水面に映る花と建物が鏡のような景色をつくる。ゴンドラは追加料金（¥1,200前後）が必要だが、この角度は徒歩では絶対に得られない。春に来るならゴンドラは外せない。" },
      { type: "heading", content: "平日開園直後が最も人が少ない：写真のゴールデンタイム", level: 2 },
      { type: "text", content: "春のハウステンボスは週末に家族連れで混雑する。平日の開園直後（9時〜10時）が最も人が少なく、チューリップ畑の前で無人の写真が撮れる唯一の時間帯だ。この時間に花の王国エリアを一周し、その後に混雑しても問題ない場所（ショップ・グルメ）に移動するのが賢い順路。" },
    ],
    relatedArticleSlugs: ["nagasaki-huis-ten-bosch-illumination", "nagasaki-chanpon-ramen-guide"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "nagasaki-lantern-festival",
    title: "長崎ランタンフェスティバル──中国正月の幻想的な光の海に入り込む冬の旅",
    description: "毎年1〜2月、長崎の旧正月に1万5,000個のランタンが街を覆う。日本で最も「中国」に近い夜の祭りを案内する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-01-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagasaki",
    tags: ["ランタンフェスティバル", "中国文化", "冬祭り", "長崎", "正月"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "1万5,000個のランタン：新地中華街から湊公園へ続く光の道", level: 2 },
      { type: "text", content: "長崎ランタンフェスティバルは中国の旧正月（春節）に合わせて開催される。新地中華街・湊公園・唐人屋敷跡・中島川公園など市内複数のエリアに赤いランタンが灯り、街全体が光の中に沈む。中国獅子舞やチャイナドレスのパレードも行われ、長崎が一時的に「中国の祭り」になる。" },
      { type: "heading", content: "点灯の時間（17時30分）に湊公園にいること", level: 2 },
      { type: "text", content: "ランタンの点灯時間は日没直後の17時30分頃。この瞬間に湊公園にいると、暗がりの中で一斉にランタンが輝き出す瞬間を目撃できる。光が赤く広がる最初の30秒が最も幻想的だ。スマートフォンよりカメラを持っていく価値がある瞬間だ。" },
      { type: "heading", content: "平和公園エリアのランタン：原爆地区と中国文化の奇妙な調和", level: 2 },
      { type: "text", content: "フェスティバル期間中は平和公園周辺にもランタンが飾られる。原爆記念の場所と中国の祝祭の光が重なるこの空間は、長崎という都市の多層性を象徴している。異文化が積み重なって形成された街の本質を、ランタンの光の中を歩きながら感じることができる。" },
    ],
    relatedArticleSlugs: ["nagasaki-chanpon-ramen-guide", "nagasaki-night-view-inasayama"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "nagasaki-nagasaki-city-model-course",
    title: "長崎市内1日モデルコース──グラバー園・平和公園・稲佐山を完全制覇する黄金ルート",
    description: "長崎は路面電車1本で主要スポットが繋がる。1日で市内を賢く回る順路と時間配分を、実際に歩いたルートで提案する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nagasaki",
    tags: ["長崎市内", "モデルコース", "路面電車", "1日観光", "長崎"],
    spotIds: ["glover-garden", "heiwa-koen", "gunkan-jima"],
    sections: [
      { type: "heading", content: "午前：グラバー園→大浦天主堂→出島を3時間で制覇", level: 2 },
      { type: "text", content: "9時にグラバー園入園（1時間）→大浦天主堂（30分）→新地中華街で角煮まんじゅうを食べ歩き（30分）→路面電車で出島へ（15分）→出島見学（1時間）。午前中だけで長崎の異文化融合の歴史を体感できる。大浦天主堂は正午前後に逆光になるため、午前中に見るべきだ。" },
      { type: "spot-card", content: "glover-garden" },
      { type: "heading", content: "昼食：ちゃんぽんか皿うどんを四海楼または思案橋付近で", level: 2 },
      { type: "text", content: "昼食は四海楼（ちゃんぽんの元祖・グラバー園横）か、思案橋近くの昭和の食堂街で。四海楼は予約なしで入れるが昼のピーク時は30分待つこともある。思案橋エリアの老舗食堂は地元民も使う価格帯で、1,000円前後でちゃんぽんと皿うどんを両方食べられる「ちゃんぽんセット」がある。" },
      { type: "heading", content: "午後：平和公園→原爆資料館→稲佐山夕景", level: 2 },
      { type: "text", content: "13時に平和公園→爆心地公園（1時間）→長崎原爆資料館（1.5時間）→ロープウェイで稲佐山（夕景を見て20時下山）。稲佐山のロープウェイ最終便は21時（季節による）。夕景から夜景への変化を山頂で見届けてから長崎駅に戻る。この順路で長崎の全ての層を一日で経験できる。" },
    ],
    relatedArticleSlugs: ["nagasaki-glover-garden-morning", "nagasaki-night-view-inasayama"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "nagasaki-sasebo-burger",
    title: "佐世保バーガーの正体──米軍基地から生まれた本場アメリカの味が長崎県に残る理由",
    description: "佐世保バーガーはファストフードではない。米軍基地のある街で70年間育てられた、日本で最もアメリカに近いハンバーガーの話。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nagasaki",
    tags: ["佐世保バーガー", "佐世保", "米軍基地", "グルメ", "長崎"],
    spotIds: ["huis-ten-bosch"],
    sections: [
      { type: "heading", content: "佐世保バーガーの誕生：米軍基地が持ち込んだ食文化", level: 2 },
      { type: "text", content: "佐世保は戦後、米軍基地が置かれた街だ。基地のMPから教わったハンバーガーレシピが地元の喫茶店に伝わり、それが独自に発展した。大きさ・厚さ・手作り感が特徴で、マクドナルドとは全く別のカテゴリの食べ物だ。市内に50店以上の専門店があり、それぞれレシピが違う。" },
      { type: "spot-card", content: "huis-ten-bosch" },
      { type: "heading", content: "老舗3店：ログキット・ミサ・ブルースカイの違いを知る", level: 2 },
      { type: "text", content: "佐世保バーガー三大老舗として「ログキット」（創業1970年代）、「ミサ」（創業1968年）、「ブルースカイ」（創業1950年代後半）が挙げられる。ログキットはスモークベーコンとオリジナルソース、ミサは肉の厚さと炭火グリル、ブルースカイは全て手作りのシンプルな構成が特徴。3軒食べ比べが佐世保バーガーの正しい旅。" },
      { type: "heading", content: "ハウステンボスとのセット旅：佐世保の2つの顔", level: 2 },
      { type: "text", content: "佐世保市内にはハウステンボスがある。オランダの街並みと米軍基地文化が同じ市内に共存するという、長崎の多様性を象徴した状況だ。ハウステンボスで昼食をとってから市街でバーガーを夕食にする旅程、または逆の順序が効率的。佐世保バーガーは大きいので、昼食としては1個で十分な量がある。" },
    ],
    relatedArticleSlugs: ["nagasaki-huis-ten-bosch-illumination", "nagasaki-chanpon-ramen-guide"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "nagasaki-ikitsuki-island-hidden-christian",
    title: "生月島・平戸の隠れキリシタン遺産──禁教時代の秘密の信仰が残る場所を歩く",
    description: "平戸と生月島は日本のキリシタン史の最深部だ。禁教時代に独自の形に変化した信仰の痕跡は、世界遺産に指定された今も生きている。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nagasaki",
    tags: ["隠れキリシタン", "平戸", "生月島", "世界遺産", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "平戸：南蛮貿易の玄関口に残るキリシタンの記憶", level: 2 },
      { type: "text", content: "平戸は16世紀にポルトガル・オランダの南蛮貿易の拠点だった。フランシスコ・ザビエルが日本で最初にカトリック布教を行った地のひとつで、平戸城と教会が海を挟んで向かい合う景観は長崎県の象徴的な場所だ。世界遺産「長崎と天草地方の潜伏キリシタン関連遺産」の構成資産を歩くガイドツアーが充実している。" },
      { type: "heading", content: "生月島：日本で最後まで「かくれキリシタン」が生き残った島", level: 2 },
      { type: "text", content: "平戸島の北に浮かぶ生月島（いきつきじま）は、明治以降にカトリックに復帰した「復活キリシタン」ではなく、仏教・神道と混合した独自の信仰「かくれキリシタン」が現代まで継続している稀有な場所だ。島の郷土資料館では禁教時代の信仰用具（紙製のマリア像など）が展示されている。" },
      { type: "heading", content: "ガスパル様の岩窟：断崖の下に隠された礼拝場所", level: 2 },
      { type: "text", content: "生月島西岸の断崖には「ガスパル様」と呼ばれる岩窟がある。禁教時代、島民たちが密かに礼拝に使っていた場所で、海からしかアクセスできなかったという伝説がある。現在は遊歩道が整備され、断崖から岩窟を見下ろすことができる。人跡未踏の雰囲気の断崖に吹く風の中で、秘密の信仰の痕跡に触れる体験だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-urakami-cathedral", "nagasaki-peace-park-guide"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "nagasaki-family-travel-guide",
    title: "長崎の家族旅行完全プラン──子連れで行くハウステンボス・軍艦島・グラバー園の選び方",
    description: "子どもと一緒の長崎旅は選択肢が多い。ハウステンボスと軍艦島は子どもへの影響が真逆だ。年齢別に最適な選択肢を提案する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-05",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "nagasaki",
    tags: ["長崎家族旅行", "子連れ旅", "ハウステンボス", "軍艦島", "長崎"],
    spotIds: ["huis-ten-bosch", "gunkan-jima", "glover-garden"],
    sections: [
      { type: "heading", content: "就学前の子どもにはハウステンボス一択", level: 2 },
      { type: "text", content: "5歳以下の子どもにはハウステンボスが最適だ。アトラクション・動物・花・光と全ての要素が広い敷地に凝縮されており、飽きさせない。チューリップ祭やイルミネーションは子どもの視覚に直接刺さる体験だ。ベビーカーで全エリアを回れる設計になっており、授乳室・おむつ替えシートも充実している。" },
      { type: "spot-card", content: "huis-ten-bosch" },
      { type: "heading", content: "小学生以上なら軍艦島ツアーで「廃墟の教育」を", level: 2 },
      { type: "text", content: "軍艦島は小学生以上（特に10歳〜）に強烈な印象を与える。廃墟の建物群は「人が住んでいた痕跡」として見ると、産業・環境・エネルギーの問題が見えてくる。ガイドの説明を子どもと一緒に聞き、帰路の船上で「なぜ島が無人になったか」を話し合う時間は、教室では得られない学習体験だ。" },
      { type: "heading", content: "グラバー園のハート石探し：子どもが夢中になる宝探し", level: 2 },
      { type: "text", content: "グラバー園の石畳に3つ隠されたハート形の石は、子どもの宝探し本能を刺激する。「全部見つけたら恋が叶う」という大人向けの話は子ども向けに「宝探し成功」とアレンジすれば問題ない。広い園内を楽しんで回るための動機付けとして最高のギミックで、子どもがリードする形でグラバー園全体を自然に歩き回れる。" },
    ],
    relatedArticleSlugs: ["nagasaki-huis-ten-bosch-illumination", "nagasaki-gunkan-jima-tour"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "nagasaki-onsen-unzen",
    title: "雲仙温泉の地獄と硫黄──雲仙普賢岳が生み出す白煙の温泉地で泊まる",
    description: "雲仙温泉は硫黄の匂いと白い噴煙に包まれた温泉地だ。1990年の雲仙普賢岳噴火の記憶と共に、自然の猛威を間近に感じる旅。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "nagasaki",
    tags: ["雲仙温泉", "雲仙地獄", "普賢岳", "温泉", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "雲仙地獄：30か所以上の噴気孔が白煙を上げる温泉地帯", level: 2 },
      { type: "text", content: "雲仙温泉は30か所以上の噴気孔（地獄）が集まる活発な火山地帯だ。大叫喚地獄、お糸地獄、清七地獄など名前も個性的。摂氏95〜100度の熱湯が噴出し、硫黄の白煙が立ち込める遊歩道を歩くと足元から地面の熱気が感じられる。江戸時代にはキリシタンへの拷問に使われた歴史も持つ。" },
      { type: "heading", content: "雲仙普賢岳噴火の記憶：火砕流の跡を歩く", level: 2 },
      { type: "text", content: "1990〜1995年の雲仙普賢岳噴火では43名が犠牲になった。島原市の「道の駅みずなし本陣ふかえ」には火砕流に埋まった家屋がそのまま保存展示されている。観光ではなく「記録を見る」ための場所で、雲仙温泉への旅にセットで訪れることで、美しい温泉地の地下に何があるかを理解できる。" },
      { type: "heading", content: "雲仙温泉の宿：硫黄泉に入りながら普賢岳を望む", level: 2 },
      { type: "text", content: "雲仙温泉の旅館は1泊2食付きで15,000〜30,000円が相場。源泉かけ流しの硫黄泉（白濁した湯）が特徴で、皮膚への殺菌効果が高い。露天風呂から普賢岳を望める宿が複数あり、夜明けの山と白い噴煙を湯の中から見る体験は、日本の温泉宿の中でも唯一性が高い。" },
    ],
    relatedArticleSlugs: ["nagasaki-glover-garden-morning", "nagasaki-chanpon-ramen-guide"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "nagasaki-luxury-travel",
    title: "長崎の贅沢な旅──雲仙の高級旅館から軍艦島チャーターまで、長崎を大人の旅で楽しむ",
    description: "長崎は歴史と文化の密度が高く、贅沢に時間をかける価値がある。高級宿・プライベートツアー・老舗店でしか食べられないものを厳選する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "nagasaki",
    tags: ["長崎贅沢旅", "高級旅館", "プライベートツアー", "大人旅", "長崎"],
    spotIds: ["gunkan-jima", "glover-garden", "huis-ten-bosch"],
    sections: [
      { type: "heading", content: "軍艦島のプライベートチャーター：専用船で廃墟の島を独占する", level: 2 },
      { type: "text", content: "通常の軍艦島ツアーは20〜50人の団体で船に乗るが、プライベートチャーターを手配すると船と島を専有できる。費用は1船15万円〜（最大16名程度）で、人数が多いほどコスパが良くなる。ガイドを事前に打ち合わせして関心のある分野（建築・炭鉱史・廃墟写真など）に特化した解説を依頼できる。" },
      { type: "spot-card", content: "gunkan-jima" },
      { type: "heading", content: "ハウステンボス「ホテルデンハーグ」スイートルーム：運河を独占する部屋", level: 2 },
      { type: "text", content: "ハウステンボスの最高級宿「ホテルデンハーグ」のスイートルームは、運河に面したテラスから直接水面を眺められる造りになっている。1泊5万円〜という価格だが、早朝に宿泊者専用の時間帯でパーク内を散歩できる特権が付いてくる。夜のイルミネーションを部屋のテラスから見る贅沢は、ここでしか得られない。" },
      { type: "heading", content: "長崎市内の料亭：卓袱料理（しっぽく）で長崎の歴史を食べる", level: 2 },
      { type: "text", content: "長崎の卓袱（しっぽく）料理は日本・中国・オランダの料理文化が融合した唯一の料理形式だ。円卓に様々な料理を並べて囲む形式で、「お鰭（おひれ）」と呼ぶ吸い物に始まり、豚の角煮・魚料理・中華点心が次々と出てくる。市内の老舗料亭「富貴楼」や「坂本屋」でコースを頼むと1人10,000円〜だが、長崎の文化の全てが皿に乗っている。" },
    ],
    relatedArticleSlugs: ["nagasaki-gunkan-jima-tour", "nagasaki-night-view-inasayama"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "nagasaki-goto-islands",
    title: "五島列島への旅──長崎から渡る絶海の孤島と、世界遺産の教会群が待つ場所",
    description: "五島列島は長崎から船で渡る離島だ。潜伏キリシタンの教会が点在する絶景の島々は、長崎本島とは別の静寂がある。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nagasaki",
    tags: ["五島列島", "教会群", "世界遺産", "離島", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "五島列島のキリシタン教会群：世界遺産に選ばれた理由", level: 2 },
      { type: "text", content: "五島列島の各島に点在する教会群は「長崎と天草地方の潜伏キリシタン関連遺産」として世界遺産に登録された。頭ヶ島天主堂（上五島）、田平天主堂（平戸）など石造りの小さな教会が海岸や丘に建ち、周囲の自然との対比が美しい。今も現役の礼拝堂として使われており、静かに内部を見学できる。" },
      { type: "heading", content: "福江島：五島列島の玄関口で2泊する最低限の旅", level: 2 },
      { type: "text", content: "長崎港から高速船で約90分の福江島が五島列島の中心だ。福江城（石田城）跡、井持浦教会、大瀬崎断崖などが島内に集中しており、レンタカーで1日で主要スポットを回れる。夕日スポットの「高浜ビーチ」は白砂と透明な海で、沖縄並みの水質を持つ。宿は島内の民宿・旅館で1泊2食8,000円〜。" },
      { type: "heading", content: "五島牛と五島うどん：島の食を楽しむ", level: 2 },
      { type: "text", content: "五島列島の食の特産は「五島牛」（黒毛和牛・島の塩と干し草で育てられた）と「五島うどん」（極細の手延べ麺・椿油を使う）だ。五島うどんは島内の食堂で「地獄炊き」（熱湯に麺を入れたまま食べる）スタイルで食べるのが現地の食べ方。長崎本島では味わえない五島の食文化がある。" },
    ],
    relatedArticleSlugs: ["nagasaki-ikitsuki-island-hidden-christian", "nagasaki-glover-garden-morning"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "nagasaki-budget-travel-3days",
    title: "長崎3日間・予算3万円の旅──グラバー園・軍艦島・ハウステンボスを最安値で制覇する方法",
    description: "長崎は遠くて費用がかかると思われている。実際はJR九州パスとゲストハウスを使えば3日間3万円で主要スポットが全部回れる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "nagasaki",
    tags: ["長崎節約旅", "3日間", "予算旅行", "バジェット", "長崎"],
    spotIds: ["glover-garden", "gunkan-jima", "huis-ten-bosch"],
    sections: [
      { type: "heading", content: "交通費の最適化：JR九州パスとバスの組み合わせ", level: 2 },
      { type: "text", content: "長崎入りは東京から飛行機（LCC早割で¥6,000〜）か新幹線（JR九州パス利用で割安）が最安値。長崎市内は路面電車1日乗り放題（¥600）で全スポット移動できる。ハウステンボスへはJR大村線（¥860）が最安。3日間の交通費は空港往復含め¥12,000〜¥14,000に収まる。" },
      { type: "spot-card", content: "glover-garden" },
      { type: "heading", content: "軍艦島ツアーは最安値業者の選び方", level: 2 },
      { type: "text", content: "軍艦島ツアーの料金は業者によって¥3,500〜¥5,000まで差がある。「軍艦島コンシェルジュ」の早割インターネット予約は¥3,700（上陸料別）と最安値クラス。グループで来る場合はひとり料金が下がる「小型船チャーター」も検討に値する。平日は週末より¥500〜¥1,000安いことが多い。" },
      { type: "heading", content: "食費：長崎の地元飯を安く食べる", level: 2 },
      { type: "text", content: "ちゃんぽん・皿うどんは観光地から外れた食堂では¥700〜¥850で食べられる。国際通りや新地中華街周辺は割高なため、一本裏道に入るだけで价格が下がる。スーパー「鮮Do!（フレッシュドー）」の惣菜は地元食材が安く揃い、夕食を調達するのに使える。1日の食費¥2,000以下は十分可能だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-nagasaki-city-model-course", "nagasaki-chanpon-ramen-guide"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "nagasaki-couple-romantic",
    title: "長崎カップル旅の決定版──夜景と洋館と卓袱料理で演出する、最もロマンチックな2泊3日",
    description: "長崎は「夜が美しい街」だ。稲佐山・グラバー園・ハウステンボスと続く光の旅を、2人で歩く最高の計画を立てる。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "nagasaki",
    tags: ["長崎カップル旅", "夜景", "ロマンチック", "2泊3日", "長崎"],
    spotIds: ["glover-garden", "huis-ten-bosch"],
    sections: [
      { type: "heading", content: "1日目：グラバー園と夕景の稲佐山で長崎の夜に入る", level: 2 },
      { type: "text", content: "午後にグラバー園→大浦天主堂→出島を散策（2〜3時間）→夕食は新地中華街の卓袱料理コース（要予約・1人¥8,000〜）→稲佐山ロープウェイで夜景。稲佐山の展望台で長崎港の夜景を2人で眺める時間は、どんな場所よりもロマンチックな場面になる。" },
      { type: "spot-card", content: "glover-garden" },
      { type: "heading", content: "2日目：軍艦島の廃墟と平和公園の静けさで「深い旅」に", level: 2 },
      { type: "text", content: "午前に軍艦島ツアー（3時間）→昼食はちゃんぽん（四海楼）→午後に平和公園・長崎原爆資料館（2時間）→夕食は「思案橋横丁」の居酒屋で長崎の魚介と地酒。軍艦島と平和公園は重い内容だが、2人で向き合った後の夜の会話は格段に深くなる。長崎の旅でしか生まれない時間だ。" },
      { type: "heading", content: "3日目：ハウステンボスで光の中に浸かる", level: 2 },
      { type: "text", content: "最終日はハウステンボスで春（チューリップ）か冬（イルミネーション）の光を楽しむ。運河クルーズのゴンドラに2人で乗り、花か光の中をゆっくり進む体験で旅を締めくくる。ハウステンボス駅から直通特急で博多・福岡空港への帰路も快適だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-night-view-inasayama", "nagasaki-huis-ten-bosch-illumination"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "nagasaki-spring-sakura",
    title: "長崎の春と桜──眼鏡橋・グラバー園・大村公園で桜の長崎を歩く3月4月",
    description: "長崎の桜は坂の街の石畳と洋館に映える。平地とは違う角度で見る花吹雪の景色と、早咲き品種の多様さを伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagasaki",
    tags: ["長崎の桜", "春旅行", "眼鏡橋", "お花見", "長崎"],
    spotIds: ["glover-garden", "heiwa-koen"],
    sections: [
      { type: "heading", content: "眼鏡橋の桜：水面に映る桜と石橋のコントラスト", level: 2 },
      { type: "text", content: "眼鏡橋（中島川）沿いの桜並木は、川面に映る花びらと石橋のアーチが重なる景色が美しい。3月下旬〜4月上旬が満開期。川の水位が低い時期は川床に降りて見上げるアングルが最高だ。グラバー園周辺との距離も近く、徒歩圏内でハシゴできる。" },
      { type: "spot-card", content: "glover-garden" },
      { type: "heading", content: "大村公園の桜：日本最初の公園花見の地", level: 2 },
      { type: "text", content: "長崎県大村市の大村公園は「日本の花見発祥の地」という伝説を持つ公園だ。約2,100本の桜が咲き、池の桜のリフレクションが有名。満開時の夜桜ライトアップは平日でも見物客が多い。長崎市内から車で40分、JRで30分のアクセスで、市内観光との組み合わせがしやすい。" },
      { type: "heading", content: "グラバー園の桜：洋館と桜の記念撮影スポット", level: 2 },
      { type: "text", content: "グラバー園内にも桜の木があり、白い洋館の壁と桜のピンクが重なる景色が春限定の構図を作る。特に旧オルト住宅前の桜は見応えがあり、長崎港を背景に洋館×桜の写真が撮れる。グラバー住宅の縁側から桜を見ながら長崎港を望む角度が最も印象的だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-glover-garden-morning", "nagasaki-nagasaki-city-model-course"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "nagasaki-photography-spots",
    title: "長崎の撮影スポット完全ガイド──写真愛好家が選ぶ10の絶景アングル",
    description: "長崎は「斜面と港と歴史」が凝縮した撮影の宝庫だ。光の時間帯・季節・レンズの使い方まで、写真愛好家向けの詳細ガイドを伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nagasaki",
    tags: ["長崎撮影", "写真スポット", "稲佐山", "グラバー園", "長崎"],
    spotIds: ["glover-garden", "heiwa-koen", "gunkan-jima"],
    sections: [
      { type: "heading", content: "稲佐山：ブルーアワーの15分が人生最高の夜景写真になる", level: 2 },
      { type: "text", content: "日没後20〜30分の「ブルーアワー」は、空が深いブルーに染まりながら街の灯りが輝く時間帯だ。稲佐山展望台でこの時間を待つと、長崎港・市街・夜景が最もバランス良く収まる。三脚使用で長秒露光（ISO100・f/8・20〜30秒）が最適設定。平日でも数人の写真家がいる。" },
      { type: "spot-card", content: "glover-garden" },
      { type: "heading", content: "眼鏡橋の水面リフレクション：雨上がりの晴れ間が最高の条件", level: 2 },
      { type: "text", content: "眼鏡橋の石橋が水面に映る「連続アーチのリフレクション」は長崎屈指の定番構図だ。水面が穏やかな雨上がりの晴れ間が最も綺麗に反射する。縦位置でブリッジと水面を等分に収めるのが基本構図。朝6〜8時は無人に近い状態で撮れる。橋の上ではなく川岸から斜めのアングルが立体感を出す。" },
      { type: "heading", content: "軍艦島：曇天の廃墟写真は晴天より劇的", level: 2 },
      { type: "text", content: "軍艦島の写真は快晴より曇天の方が劇的な仕上がりになることが多い。灰色の空と廃墟のコンクリートが同じトーンになり、モノクロ的な世界観が生まれる。船上から撮る島全体のシルエットは、曇天の逆光でコントラストが際立つ。上陸後は14mmなどの超広角で建物の崩壊感を誇張して撮るのが効果的。" },
    ],
    relatedArticleSlugs: ["nagasaki-night-view-inasayama", "nagasaki-gunkan-jima-tour"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "nagasaki-october-winter-travel",
    title: "長崎秋冬旅行の全て──紅葉・雲仙地獄・ランタンフェスティバルと長崎の寒い季節",
    description: "長崎の秋冬はイルミネーションとランタンフェスティバルが待っている。10月から2月の長崎を徹底的に活用するシーズン別ガイド。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagasaki",
    tags: ["長崎秋旅", "冬の長崎", "イルミネーション", "雲仙温泉", "長崎"],
    spotIds: ["huis-ten-bosch", "glover-garden"],
    sections: [
      { type: "heading", content: "10〜11月：雲仙の紅葉と温泉で長崎の秋を満喫", level: 2 },
      { type: "text", content: "10月中旬〜11月中旬、雲仙普賢岳の麓は紅葉に染まる。雲仙温泉の旅館に1泊し、早朝に地獄の噴煙と紅葉のコントラストを見る体験は格別だ。仁田峠から普賢岳を見上げると、溶岩ドームと秋の山が重なる長崎でしか見られない景色が広がる。" },
      { type: "spot-card", content: "huis-ten-bosch" },
      { type: "heading", content: "12〜1月：ハウステンボスのイルミネーションとランタンフェスティバル", level: 2 },
      { type: "text", content: "ハウステンボスの光の王国（11月〜3月）とランタンフェスティバル（1〜2月）が重なる期間は、長崎が最も光り輝く季節だ。2つのイベントは同時に楽しめる距離ではないが、1泊2日でハウステンボス泊→長崎市内のランタンフェスティバル、という行程が最高密度の冬旅になる。" },
      { type: "heading", content: "2月：長崎ランタンフェスティバルのベストタイミング", level: 2 },
      { type: "text", content: "旧正月（春節）に合わせて開催されるランタンフェスティバルは、年によって1月下旬〜2月上旬が開催期間になる。期間は約15日間で、週末は特に混雑する。新地中華街周辺の旅館・ホテルは1〜2ヶ月前に満室になることもあるため、日程が決まったら即予約が必要だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-lantern-festival", "nagasaki-huis-ten-bosch-illumination"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "nagasaki-tsushima-island",
    title: "対馬への旅──長崎から渡る最果ての国境の島で、韓国文化と日本の歴史が交差する",
    description: "対馬は日本の中で最もアジアに近い島だ。朝鮮半島まで50kmの距離に、元寇の記憶と国境の緊張感が今も残っている。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nagasaki",
    tags: ["対馬", "国境の島", "韓国文化", "元寇", "長崎"],
    spotIds: ["glover-garden"],
    sections: [
      { type: "heading", content: "対馬の地理：朝鮮半島まで50kmの最前線の島", level: 2 },
      { type: "text", content: "対馬は長崎市から飛行機35分または高速船130分で渡れる。対馬の最北端から韓国・釜山まで直線距離50km。晴れた日には対馬から韓国の建物が見えるという。島の面積の89%が山林で、南北80kmの縦に長い地形が独特の景観を作る。人口は約3万人だが、年間の韓国人観光客が30万人を超える独特の観光地だ。" },
      { type: "heading", content: "和多都美神社：海の鳥居が対馬の神秘を象徴する", level: 2 },
      { type: "text", content: "対馬の和多都美（わたつみ）神社は、海中に建てられた鳥居が印象的な神社だ。海神（わたつみ）を祀り、入り江の先に鳥居が並ぶ構造は「海の厳島神社」と呼ばれる。干潮時には鳥居まで歩いて渡れる。早朝の霧の中に鳥居が浮かぶ景色は、対馬が持つ独特の神秘感を最も純粋に表現している。" },
      { type: "heading", content: "元寇の遺跡と国境防衛の歴史：対馬が守ってきたもの", level: 2 },
      { type: "text", content: "1274年の元寇（文永の役）で対馬は最初の上陸地点となり、島民が全滅に近い犠牲を払って鎌倉幕府に急を知らせた。島内には元寇記念碑と小茂田浜（こもだはま）神社があり、その場所は今も静かに歴史を刻んでいる。対馬は1,700年前から朝鮮半島への最前線として日本を守り続けてきた島だ。" },
    ],
    relatedArticleSlugs: ["nagasaki-goto-islands", "nagasaki-ikitsuki-island-hidden-christian"],
  },
];
