import { Article } from "@/types/article";

export const naganoArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "nagano-matsumoto-castle-guide",
    title: "松本城を100%楽しむガイド──国宝天守の正しい歩き方と最高の構図",
    description: "黒漆喰の天守と北アルプスの白。松本城の美しさを最大限に引き出す時間帯と季節。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-08",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nagano",
    tags: ["松本城", "国宝", "城", "長野", "北アルプス"],
    spotIds: ["matsumoto-castle"],
    sections: [
      { type: "heading", content: "開門8時30分と同時に入る", level: 2 },
      { type: "text", content: "松本城（入場700円）の開門は8時30分。9時台になると団体ツアーが入り、天守内の急階段が行列になる。最上階まで上がると北アルプスの連嶺が広がり、これが松本城に来る最大の理由のひとつになる。" },
      { type: "spot-card", content: "matsumoto-castle" },
      { type: "heading", content: "逆さ天守を撮る場所", level: 2 },
      { type: "text", content: "内堀の水面に映る逆さ天守は、北側の石垣沿いから撮影すると最も美しい構図になる。早朝は水面が穏やかで、黒い天守と空の青が鮮明に映り込む。4月の桜の時期は城の周囲に桜が咲き、黒・白・桃色が重なる絶景になる。" },
      { type: "heading", content: "松本の食事は中町通りで", level: 2 },
      { type: "text", content: "松本城から徒歩10分の中町通りには、信州そばの老舗と蔵造りの建物が並ぶ。「松本十割そば大盛堂」は十割そばが1,050円で食べられる本格派。城見学後の昼食に最適なコースで、観光後の疲れを信州の澄んだそば湯で癒せる。" },
    ],
    relatedArticleSlugs: ["nagano-kamikochi-trekking", "nagano-matsumoto-solo-walk"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "nagano-kamikochi-trekking",
    title: "上高地トレッキング完全ガイド──大正池から河童橋、穂高の根元を歩く",
    description: "マイカー乗り入れ禁止の山岳景勝地。バスを降りた瞬間から始まる、日本最高水準の自然歩道。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-05-12",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nagano",
    tags: ["上高地", "トレッキング", "北アルプス", "長野", "絶景"],
    spotIds: ["kamikochi"],
    sections: [
      { type: "heading", content: "アクセスは松本駅からバスで1時間半", level: 2 },
      { type: "text", content: "上高地はマイカー規制のため、沢渡（さわんど）駐車場からシャトルバス（往復2,050円）に乗り換える必要がある。松本駅から直行バスもあり片道1,900円。早朝7時台のバスが最も空いており、大正池で朝靄の景色を見るためには7時前に沢渡を出発したい。" },
      { type: "spot-card", content: "kamikochi" },
      { type: "heading", content: "大正池→田代池→河童橋の3時間コース", level: 2 },
      { type: "text", content: "大正池（バス停）から河童橋まで約3kmを約1時間半で歩ける。途中の田代池・田代湿原は湿地帯の植物相が豊富で、野生のサルが出ることもある。梓川の澄んだ流れを左手に見ながらの遊歩道は、ほぼフラットで子どもや高齢者でも問題ない。" },
      { type: "heading", content: "10月の紅葉が上高地最大のピーク", level: 2 },
      { type: "text", content: "上高地の紅葉は10月中旬〜下旬が最盛期。カラマツの黄金色と穂高の岩稜、梓川の青の組み合わせは日本の山岳風景で最も美しい部類に入る。10月の週末は駐車場・バスが混雑するため、平日か宿泊プランで混雑を避けるのが賢明。" },
    ],
    relatedArticleSlugs: ["nagano-matsumoto-castle-guide", "nagano-shiga-kogen-ski"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "nagano-zenkoji-morning-ritual",
    title: "善光寺のお朝事──朝6時の読経に参列して長野の朝を始める",
    description: "毎朝6時、住職たちの読経が本堂に響く。参道から本堂まで歩く夜明けの空気が、旅を変える。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-03-18",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "nagano",
    tags: ["善光寺", "お朝事", "長野", "寺院", "朝"],
    spotIds: ["zenkoji"],
    sections: [
      { type: "heading", content: "お朝事は毎日開催──前日に長野に泊まる", level: 2 },
      { type: "text", content: "善光寺のお朝事は年中無休で毎朝6時（夏は5時半）に行われる。参列は無料。仲見世参道の旅館や善光寺近くの宿に前泊し、早朝5時半ごろから参道を歩いて向かうのが正しい作法。暗い参道に石畳が続き、蝋燭の光が漏れる宿の軒先が趣深い。" },
      { type: "spot-card", content: "zenkoji" },
      { type: "heading", content: "お戒壇めぐりは完全な暗闇", level: 2 },
      { type: "text", content: "本堂地下の「お戒壇めぐり」（500円）は文字通り何も見えない暗闇の回廊。右手で壁を触りながら進み、中央の錠前に触れると極楽往生が約束されるとされる。10分足らずの体験だが、完全な闇を歩く非日常は長野旅の最も記憶に残る場面になる。" },
      { type: "heading", content: "参道の七味屋・そば屋が朝から開く", level: 2 },
      { type: "text", content: "善光寺仲見世通りの「根元八幡屋礒五郎」は長野の七味唐辛子の老舗。自分でブレンドできる七味体験（1,000円）が朝から楽しめる。朝食は参道沿いの「藤木庵」で信州そば（680円）がお朝事の後に食べる定番。" },
    ],
    relatedArticleSlugs: ["nagano-nagano-city-solo", "nagano-matsumoto-castle-guide"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "nagano-karuizawa-autumn",
    title: "軽井沢の秋──10月の白樺と雲場池が作る、日本で最も完成された紅葉風景",
    description: "東京から70分のリゾートが、10月だけは日本一の紅葉スポットに変わる。軽井沢の秋の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-10-08",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagano",
    tags: ["軽井沢", "紅葉", "秋", "白樺", "長野"],
    spotIds: ["karuizawa"],
    sections: [
      { type: "heading", content: "雲場池の紅葉は10月中旬が最高潮", level: 2 },
      { type: "text", content: "軽井沢随一の紅葉スポット「雲場池」は旧軽井沢銀座から徒歩15分。池の水面に映る紅葉の映り込みが完璧な構図を作り出す。10月中旬の平日朝7時〜8時台は三脚を持った写真愛好家が来る前の静かな時間。入場無料。" },
      { type: "spot-card", content: "karuizawa" },
      { type: "heading", content: "旧軽銀座は紅葉シーズンでも午前が快適", level: 2 },
      { type: "text", content: "旧軽井沢銀座通りは週末昼間に混雑するが、平日9時台はゆったりと歩ける。「つるや旅館」の前の石畳から始まるこの通りは、ジャムの沢屋・油屋・フランスベーカリーと老舗が並ぶ。フランスベーカリーのクリームパン（280円）は軽井沢で最も長い歴史を持つパン。" },
      { type: "heading", content: "聖パウロカトリック教会で紅葉の中の石造りを見る", level: 2 },
      { type: "text", content: "軽井沢のシンボル的建築、聖パウロカトリック教会（レーモンド設計）は白樺と紅葉に包まれた姿が秋に最も美しい。礼拝中は内部見学不可だが、外観と周囲の木々だけで十分な体験がある。教会前の広場から撮った写真は軽井沢を代表する秋の一枚になる。" },
    ],
    relatedArticleSlugs: ["nagano-karuizawa-couple", "nagano-zenkoji-morning-ritual"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "nagano-shiga-kogen-ski",
    title: "志賀高原スキーガイド──日本最大のスキーリゾートを滑りきる2泊3日",
    description: "18のスキー場がひとつに繋がる志賀高原。全コースを知る人間だけが使える効率的な攻略法。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-12-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagano",
    tags: ["志賀高原", "スキー", "冬", "長野", "スノーボード"],
    spotIds: [],
    sections: [
      { type: "heading", content: "志賀高原の全体像：18スキー場がひとつの山", level: 2 },
      { type: "text", content: "志賀高原は長野市から車で1時間の山岳地帯に18のスキー場が隣接している。共通リフト券（1日5,200円）で全エリアを滑れる。初心者向けの焼額山・中級者向けの一の瀬・上級者向けの寺子屋と、レベル別にエリアが分かれている。雪質は日本屈指のパウダーで1月〜2月が最良。" },
      { type: "heading", content: "宿は渋温泉・湯田中温泉が最もコスパが高い", level: 2 },
      { type: "text", content: "スキー場直結の宿は高いが、山麓の渋温泉（1泊2食15,000円前後）からシャトルバスで30分でゲレンデに着ける。渋温泉の外湯巡りは9か所の共同浴場を全て制覇できる「外湯巡り手形」（250円）があり、スキー後の疲れを癒す最高の仕組みになっている。" },
      { type: "heading", content: "地獄谷野猿公苑へのアクセスは志賀高原の帰り道", level: 2 },
      { type: "text", content: "湯田中駅から徒歩35分（シャトルバスもあり）の地獄谷野猿公苑は、スキー帰りに立ち寄れる距離。入場料800円。温泉に浸かるニホンザルは世界中のメディアに取り上げられた長野の名物。冬の白銀の中、赤ら顔のサルが温泉に浸かる光景はここでしか見られない。" },
    ],
    relatedArticleSlugs: ["nagano-jigokudani-monkeys", "nagano-kamikochi-trekking"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "nagano-jigokudani-monkeys",
    title: "地獄谷野猿公苑──世界で唯一、温泉に入るニホンザルを見に行く",
    description: "BBCや NHKが繰り返し撮影に来る冬の光景。雪の中で温泉に浸かるサルたちと過ごす1時間。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-01-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagano",
    tags: ["地獄谷野猿公苑", "温泉ザル", "長野", "冬", "野生動物"],
    spotIds: [],
    sections: [
      { type: "heading", content: "冬が最良シーズン──サルが温泉に入る理由", level: 2 },
      { type: "text", content: "地獄谷野猿公苑（入場800円）のサルが温泉に入るのは主に11月〜4月の寒い季節。サルたちは気温が下がると自発的に温泉に入り温まる習性がある。夏は水遊びはするが温泉に浸かる頻度が下がるため、冬こそがベストシーズン。" },
      { type: "heading", content: "アクセス：湯田中駅から徒歩35分", level: 2 },
      { type: "text", content: "長野電鉄湯田中駅からバス（地獄谷野猿公苑前下車・180円）またはタクシー（1,200円）で移動後、さらに雪道を徒歩2km。冬用の靴底がある防滑シューズは必須。10時〜14時台が最もサルの温泉浸かり率が高い傾向がある。" },
      { type: "heading", content: "渋温泉と組み合わせた理想の1日", level: 2 },
      { type: "text", content: "野猿公苑を午前中に見学し、徒歩で渋温泉街へ戻って昼食とお湯めぐりを楽しむのが理想のコース。渋温泉の外湯は9か所（外湯入浴料は宿泊者は無料、日帰り客は1か所500円）あり、特に「大湯」は江戸時代の石造り浴槽で格別の雰囲気がある。" },
    ],
    relatedArticleSlugs: ["nagano-shiga-kogen-ski", "nagano-onsen-guide"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "nagano-soba-deep-dive",
    title: "信州そばの深い世界──長野・松本・戸隠、そばの産地で本物を食べ比べる",
    description: "「そばは長野」と言われる理由がある。産地ごとに香りと食感が違う信州そばを系統立てて知る。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nagano",
    tags: ["信州そば", "グルメ", "戸隠", "長野", "そば打ち"],
    spotIds: ["zenkoji"],
    sections: [
      { type: "heading", content: "戸隠そばは「ぼっち盛り」で出る", level: 2 },
      { type: "text", content: "長野市街から車で40分の戸隠神社参道沿いには、数十軒のそば屋が並ぶ「戸隠そば」の聖地がある。戸隠そばの特徴は「ぼっち盛り」と呼ばれる山型の盛り付け。使用する蕎麦は地元産の戸隠在来種で、香りが強く独特のコシがある。ざるそばは950〜1,200円が相場。" },
      { type: "heading", content: "松本の「ちょっきり」そばとは何か", level: 2 },
      { type: "text", content: "松本では蕎麦を「ちょっきり」と呼ぶ文化があり、少量ずつ何枚も重ねた「ざる重ね」スタイルの店がある。松本城近くの「翁堂」は明治創業の老舗で、10割そば（1,200円）は香りが立ち蕎麦の甘さを感じる。城見学後の昼食に最適な立地。" },
      { type: "heading", content: "そば打ち体験は農家民宿で", level: 2 },
      { type: "text", content: "長野市近郊の農家民宿では、地元産そば粉を使ったそば打ち体験（2,500〜3,500円）が楽しめる。手打ちの難しさと楽しさを実感し、打ったそばをその場で食べる体験は、長野旅の記憶として最も長く残るもののひとつ。予約制が多いので事前確認を。" },
    ],
    relatedArticleSlugs: ["nagano-zenkoji-morning-ritual", "nagano-matsumoto-castle-guide"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "nagano-matsumoto-solo-walk",
    title: "一人で歩く松本──城下町の小径と縄手通り、信州の空気を独り占めする",
    description: "松本城だけが松本じゃない。路地に入ると現れる職人の街と、かえるの街・縄手通りの話。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nagano",
    tags: ["一人旅", "松本", "散歩", "城下町", "長野"],
    spotIds: ["matsumoto-castle"],
    sections: [
      { type: "heading", content: "縄手通りはカエルだらけの商店街", level: 2 },
      { type: "text", content: "松本城の東側、女鳥羽川沿いの縄手通りは「かえる大明神」を祀る江戸時代の道端が起源の商店街。今もカエルのモチーフで統一された小さな商店が並ぶ。一人で入りやすい小さなお茶屋やレトロ雑貨店が多く、1時間かけてゆっくり歩ける。" },
      { type: "spot-card", content: "matsumoto-castle" },
      { type: "heading", content: "蔵の街・中町通りで工芸品と向き合う", level: 2 },
      { type: "text", content: "中町通りには漆器・木工・陶器の工房と店舗が集まる。「あがたの森」の木工作家や、「松本民芸家具」の直営店は信州の職人文化の核心。値段は安くないが、長く使えるものを一つ買う、という旅の楽しみ方が松本では自然にできる。" },
      { type: "heading", content: "夕方は「ちきりや工芸店」前でコーヒー", level: 2 },
      { type: "text", content: "松本市内には個人経営の小さなコーヒー店が多い。中町通り沿いの「珈琲まるも」は昭和27年創業の老舗喫茶で、一人で入るのに最適な落ち着いた空間。信州りんごのケーキと深煎りコーヒー（計850円）が夕方の定番。" },
    ],
    relatedArticleSlugs: ["nagano-matsumoto-castle-guide", "nagano-soba-deep-dive"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "nagano-karuizawa-couple",
    title: "カップルで行く軽井沢──週末1泊2日の完璧な過ごし方",
    description: "旅行先ランキング常連の軽井沢。カップルに最適な宿・食事・散歩コースを整理する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "nagano",
    tags: ["軽井沢", "カップル", "週末旅", "長野", "リゾート"],
    spotIds: ["karuizawa"],
    sections: [
      { type: "heading", content: "1日目：旧軽銀座→雲場池→夕食", level: 2 },
      { type: "text", content: "新幹線で東京から70分の軽井沢駅着。タクシーで旧軽井沢銀座へ（1,000円）。食べ歩きしながら通りを往復し、15時ごろ雲場池へ移動。池の周囲1周は30分で回れる。夕食は「村民食堂」（軽井沢プリンスホテル内、3,000円〜）が軽井沢らしい食材を使ったスタイリッシュな一食。" },
      { type: "spot-card", content: "karuizawa" },
      { type: "heading", content: "2日目：朝の白樺林サイクリング", level: 2 },
      { type: "text", content: "軽井沢は自転車が最も合う観光地のひとつ。レンタサイクル（1日1,500〜2,000円）で南軽井沢の別荘地帯の白樺林を走ると、ただ歩くのとは違う開放感がある。木漏れ日の中を走る朝の30分は、二人の旅で最も豊かな瞬間になりやすい。" },
      { type: "heading", content: "お土産は「沢屋」のジャム一択", level: 2 },
      { type: "text", content: "軽井沢のお土産の定番は「沢屋」のジャム。旬の果物を使った種類は40種類以上で、イチゴ・ブルーベリー・アプリコットが人気。1瓶500〜900円の価格帯で、誰に渡しても喜ばれる。旧軽銀座の本店は試食させてくれるので、二人で選ぶ楽しみがある。" },
    ],
    relatedArticleSlugs: ["nagano-karuizawa-autumn", "nagano-luxury-resort"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "nagano-onsen-guide",
    title: "長野の温泉全ガイド──野沢・渋・白骨・別所、県内7大温泉の特徴と選び方",
    description: "温泉の数は日本屈指の長野県。泉質・景色・雰囲気が全て異なる7つの温泉地を比較する。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "nagano",
    tags: ["温泉", "長野", "野沢温泉", "白骨温泉", "渋温泉"],
    spotIds: [],
    sections: [
      { type: "heading", content: "野沢温泉：共同浴場13か所を巡る湯の里", level: 2 },
      { type: "text", content: "長野県北部の野沢温泉は、集落全体が温泉施設のような「湯の里」。13か所ある共同浴場（外湯）は地元住民の管理で運営され、旅行者は無料で入れるが賽銭箱への寄付が礼儀。「大湯」が最も有名だが、「河原湯」「麻釜湯」が隠れた名湯として地元民に好まれる。泉質はナトリウム・カルシウム硫酸塩泉。" },
      { type: "heading", content: "白骨温泉：白い湯の乳白色が山に溶け込む", level: 2 },
      { type: "text", content: "松本から車で1時間の白骨温泉は、硫黄成分で乳白色に濁った湯が特徴。「かつらの湯 丸永旅館」の日帰り入浴（800円）は源泉かけ流しで乳白色の湯が純度高く楽しめる。深い山中にある秘湯感が強く、夜は携帯が圏外になる静けさがある。" },
      { type: "heading", content: "別所温泉：信州の鎌倉と呼ばれる古刹と温泉", level: 2 },
      { type: "text", content: "上田市の別所温泉は「信州の鎌倉」とも呼ばれる古刹が集まる温泉地。北向観音・常楽寺・安楽寺（国宝八角三重塔）が温泉街の歩ける範囲にある。外湯「大師湯」（150円）は格安で本格的な温泉が楽しめる。上田駅から別所温泉行き電車（上田電鉄）で30分というアクセスの良さも魅力。" },
    ],
    relatedArticleSlugs: ["nagano-jigokudani-monkeys", "nagano-shiga-kogen-ski"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "nagano-family-tour",
    title: "子連れ長野旅行──松本城・上高地・野沢温泉で作る2泊3日の家族記憶",
    description: "長野は家族旅行に最強の県。城・自然・温泉が全部あり、子どもの記憶に残りやすい体験が揃っている。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "nagano",
    tags: ["子連れ", "家族旅", "長野", "松本城", "上高地"],
    spotIds: ["matsumoto-castle", "kamikochi"],
    sections: [
      { type: "heading", content: "1日目：松本城で子どもが城に目覚める", level: 2 },
      { type: "text", content: "松本城の急傾斜の階段は子どもが大興奮する体験になる。6層の天守内部を登り切ると北アルプスが見える最上階があり、子どもに「一番上まで登った」という達成感を与えられる。城内のクイズシートで学びながら回るプログラムもある。" },
      { type: "spot-card", content: "matsumoto-castle" },
      { type: "heading", content: "2日目：上高地で野生動物に遭遇する", level: 2 },
      { type: "text", content: "上高地の遊歩道ではニホンザル・カモシカ・野鳥が普通に姿を見せる。子どもに動物を見せたい親には、大正池〜河童橋コースが最も遭遇率が高い。遊歩道はほぼフラットなので小学生なら全行程を歩き切れる。弁当は松本駅で買って持参すること（上高地内の食事は高め）。" },
      { type: "spot-card", content: "kamikochi" },
      { type: "heading", content: "3日目：信州リンゴ狩りと帰路", level: 2 },
      { type: "text", content: "長野は日本一のリンゴ産地で、9月〜11月にリンゴ狩りができる農園が松本・長野市近郊に多い。1人食べ放題30分で900〜1,200円が相場。品種によって甘さと酸味が異なり、子どもと品種当てクイズをしながら食べると時間があっという間に過ぎる。" },
    ],
    relatedArticleSlugs: ["nagano-matsumoto-castle-guide", "nagano-kamikochi-trekking"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "nagano-budget-backpack",
    title: "長野節約旅──1日3,000円以内で善光寺・松本城・信州そばを全部やる",
    description: "電車と足だけで長野の核心を経験できる。交通費と食費を抑えながら内容を削らない旅の設計。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-08",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "nagano",
    tags: ["節約旅", "長野", "バジェット", "善光寺", "信州そば"],
    spotIds: ["zenkoji", "matsumoto-castle"],
    sections: [
      { type: "heading", content: "長野駅→善光寺：交通費ゼロで歩ける", level: 2 },
      { type: "text", content: "長野駅から善光寺まで徒歩20分。仲見世通りを歩きながら七味屋・八幡屋礒五郎の試食で朝の口を開く。戒壇めぐり（500円）の後、境内散策で午前を終える。朝食は駅前の地元向け食堂でモーニング（400円〜）が一番コスパが高い。" },
      { type: "spot-card", content: "zenkoji" },
      { type: "heading", content: "長野→松本の移動は篠ノ井線が安い", level: 2 },
      { type: "text", content: "JR篠ノ井線で長野〜松本間は约920円。1時間で移動でき、車窓から北アルプスが見える路線。松本城（700円）を見学後、縄手通りを散歩して昼食に信州そば（980円）を食べる。松本駅から徒歩30分圏内で全て完結するので交通費は最小限。" },
      { type: "heading", content: "宿はゲストハウスで長野旅人と交流", level: 2 },
      { type: "text", content: "松本・長野市内のゲストハウスは1泊2,800〜4,000円。ドミトリーでなくプライベートルームを選んでも5,000円以下の施設がある。長野を旅する人は自然・アウトドア・歴史好きが多く、フロントや共用ラウンジでの旅情報交換が旅を豊かにする。" },
    ],
    relatedArticleSlugs: ["nagano-soba-deep-dive", "nagano-zenkoji-morning-ritual"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "nagano-luxury-resort",
    title: "長野の贅沢宿──星野リゾート・界から宿で味わう信州の最上質",
    description: "長野県には星野リゾートが複数ある。各施設の特徴と、長野で贅沢を楽しむための宿泊選び。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "nagano",
    tags: ["贅沢旅", "星野リゾート", "長野", "高級旅館", "温泉"],
    spotIds: ["karuizawa"],
    sections: [
      { type: "heading", content: "星のや軽井沢：渓谷に浮かぶ水の郷", level: 2 },
      { type: "text", content: "「星のや軽井沢」は軽井沢の谷沿いに点在する客室棟と温泉が、ウォーターガーデンを中心に配置されたリゾート施設。1泊1室80,000円〜。宿泊者専用の「メインダイニング」は地元野菜と信州食材のコースが10,000〜15,000円。チェックインからチェックアウトまで敷地を出ない贅沢を体験できる。" },
      { type: "spot-card", content: "karuizawa" },
      { type: "heading", content: "界 松本：城下町に建つ文化温泉宿", level: 2 },
      { type: "text", content: "「界 松本」は松本城から徒歩10分の位置に建つ温泉旅館。信州の職人文化をテーマにした客室デザインで、信州の漆器・木工・陶器が館内各所に展示される。1泊2食35,000円〜。朝食は信州産そば・野沢菜・お焼きが揃う信州の朝の食卓。" },
      { type: "heading", content: "奥蓼科温泉「渋御殿湯」：秘湯の源泉かけ流し", level: 2 },
      { type: "text", content: "標高1,870mの奥蓼科温泉にある「渋御殿湯」は日本秘湯を守る会会員の老舗旅館（1泊2食18,000円〜）。pH2.9の強酸性硫黄泉は皮膚疾患に効くとされ、全国から療養目的の客が訪れる。湯の色は澄んだ緑がかった透明で、他の長野温泉と泉質が全く異なる珍しい存在。" },
    ],
    relatedArticleSlugs: ["nagano-karuizawa-couple", "nagano-onsen-guide"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "nagano-nagano-city-solo",
    title: "一人で行く長野市──善光寺から権堂アーケードまで、城下町の午後を独り歩く",
    description: "観光客の流れから外れた長野市の午後。善光寺を出た後に現れる、地元民の街がある。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-05-28",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nagano",
    tags: ["一人旅", "長野市", "善光寺", "散歩", "長野"],
    spotIds: ["zenkoji"],
    sections: [
      { type: "heading", content: "善光寺裏の「もんぜんぷら座」から始まる別の顔", level: 2 },
      { type: "text", content: "善光寺の仁王門をくぐった後、大勧進・大本願の塔頭寺院が並ぶ裏側の路地へ入ると、観光客がいない長野の寺院地区がある。小さな納骨堂や地蔵が並ぶ静かな道を歩くと、長野が信仰の街であることが実感できる。" },
      { type: "spot-card", content: "zenkoji" },
      { type: "heading", content: "権堂アーケードは昭和が生きている", level: 2 },
      { type: "text", content: "長野市内の権堂アーケード商店街は、昭和40年代の空気が残るレトロな商店街。シャッターが増えているが、老舗の駄菓子屋・酒屋・食堂が現役で営業している。一人でフラッと入れる焼き鳥居酒屋（串1本100〜150円）がいくつかあり、地元の人と並んで飲む夜が長野旅を完成させる。" },
      { type: "heading", content: "長野電鉄で小布施へ足を伸ばす", level: 2 },
      { type: "text", content: "長野駅から長野電鉄で30分（560円）の小布施は、北斎美術館と栗の菓子で有名な小さな町。栗羊羹・栗おこわ・モンブランが集中する町の中心部は徒歩で全部回れる。午後3時ごろ到着→美術館見学→夕方の栗菓子購入→長野へ戻る流れが一人旅の理想的な長野2日目。" },
    ],
    relatedArticleSlugs: ["nagano-zenkoji-morning-ritual", "nagano-budget-backpack"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "nagano-kamikochi-spring",
    title: "上高地の開山──5月の残雪と新緑が重なる、一年で最も美しい季節",
    description: "上高地は4月27日に開山する。残雪の穂高を前景に萌えるような新緑が広がる5月だけの風景。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagano",
    tags: ["上高地", "春", "残雪", "新緑", "長野"],
    spotIds: ["kamikochi"],
    sections: [
      { type: "heading", content: "4月27日開山──残雪と春の空気", level: 2 },
      { type: "text", content: "上高地は毎年4月27日に開山する。5月初旬はまだ雪が残る部分があり、周囲の木々が新緑に染まり始める中、白い穂高連峰が背景に立つ。この時期の梓川は雪解け水で水量が多く、透明度と流れの勢いが夏よりずっと高い。" },
      { type: "spot-card", content: "kamikochi" },
      { type: "heading", content: "5月の上高地は観光客が少なく最高", level: 2 },
      { type: "text", content: "GWを除く5月平日は上高地でも観光客が少ない。バスも混雑が少なく、遊歩道でシカやサルと静かに向き合える。大正池の朝靄は5月が最も濃く出やすく、水面に映る焼岳と残雪の山が幻想的な白い朝を作る。三脚持参のカメラマンが毎年5月に集まる理由がここにある。" },
      { type: "heading", content: "宿泊は上高地帝国ホテルで一晩の贅沢", level: 2 },
      { type: "text", content: "上高地に宿泊できる施設の中で、上高地帝国ホテル（1泊2食35,000円〜）はベストポジション。開山直後の5月は予約が取りやすく、7〜8月の繁忙期より宿泊しやすい。早朝の大正池まで散歩して宿に戻り、朝食を食べる──この流れが上高地滞在の理想的な幕開けになる。" },
    ],
    relatedArticleSlugs: ["nagano-kamikochi-trekking", "nagano-shiga-kogen-ski"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "nagano-apple-harvest",
    title: "信州りんごの秋──長野でリンゴ狩りをして旬の果実の意味を知る",
    description: "日本一のリンゴ産地で、木から直接もぐリンゴは別の食べ物だ。9月〜11月の長野果樹地帯。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagano",
    tags: ["りんご", "リンゴ狩り", "長野", "秋", "フルーツ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "長野リンゴの品種カレンダー", level: 2 },
      { type: "text", content: "長野のリンゴは9月から始まり11月まで品種が順番に変わる。9月：「つがる」（甘み強め）→10月：「秋映」（深みのある甘酸っぱさ）→11月：「ふじ」（日本のリンゴの代名詞）。旅の時期に合った品種を食べることが長野のリンゴ体験の醍醐味。" },
      { type: "heading", content: "長野市近郊の農園でリンゴ狩り", level: 2 },
      { type: "text", content: "長野市南部の篠ノ井・豊野エリアに農園が集中する。「リンゴ農園つかはら」などは事前予約なしで当日訪問可能。30分食べ放題900〜1,200円。農園の人に品種の特徴を聞きながら食べると、同じリンゴでも味の理解が深まる。" },
      { type: "heading", content: "リンゴジュース・シードルは産地価格が安い", level: 2 },
      { type: "text", content: "長野の農産物直売所や農園直売では、リンゴジュース（1L 400〜600円）や長野産シードル（500ml 900〜1,500円）が都市部より圧倒的に安い。特にアップルワイン系のシードルは長野県内の醸造所産が多く、東京ではほとんど流通しない。旅の土産として最もコンパクトで喜ばれるものの一つ。" },
    ],
    relatedArticleSlugs: ["nagano-family-tour", "nagano-budget-backpack"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "nagano-matsumoto-art-tour",
    title: "松本アートの旅──草間彌生・クラフトフェアと、信州が生んだ芸術文化",
    description: "松本は芸術の街でもある。草間彌生の故郷で、毎年開催されるクラフトフェアを中心に歩く。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nagano",
    tags: ["松本", "アート", "クラフト", "草間彌生", "長野"],
    spotIds: ["matsumoto-castle"],
    sections: [
      { type: "heading", content: "草間彌生は松本市出身", level: 2 },
      { type: "text", content: "ドット模様で世界的に知られるアーティスト草間彌生は松本市出身。松本市美術館（700円）には草間作品を常設展示する専用ギャラリーがあり、巨大なかぼちゃのオブジェが美術館前に設置されている。松本城と組み合わせた半日コースに最適。" },
      { type: "heading", content: "クラフトフェアまつもとは5月の年中行事", level: 2 },
      { type: "text", content: "毎年5月下旬に開催される「クラフトフェアまつもと」は、全国から厳選された工芸作家が松本市内の広場に集まるイベント。入場無料。陶器・木工・ガラス・革など500を超えるブースが並び、作家から直接作品を購入できる。松本の工芸文化の核心を体験できる2日間。" },
      { type: "heading", content: "松本民芸館で信州工芸の歴史を知る", level: 2 },
      { type: "text", content: "松本市中山にある「松本民芸館」（500円）は民藝運動の流れを汲む収蔵品が充実した美術館。柳宗悦・濱田庄司ゆかりの陶器・染色・木工が展示され、日本の手仕事の歴史が凝縮されている。松本城から車で15分。商店街の民芸品店を見た後に来ると、背景知識が加わって作品の見え方が変わる。" },
    ],
    relatedArticleSlugs: ["nagano-matsumoto-castle-guide", "nagano-matsumoto-solo-walk"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "nagano-zenkoji-history",
    title: "善光寺の歴史と謎──1400年の信仰を20分で理解するための予備知識",
    description: "宗派不問の不思議な寺院はなぜ生まれたか。善光寺に行く前に知っておくべきこと。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-02-14",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nagano",
    tags: ["善光寺", "歴史", "仏教", "長野", "宗教"],
    spotIds: ["zenkoji"],
    sections: [
      { type: "heading", content: "善光寺が「宗派不問」な理由", level: 2 },
      { type: "text", content: "善光寺の本尊は「一光三尊阿弥陀如来」で、日本に仏教が伝来した際に最初に来日した仏像とされる。この仏像はいかなる仏教宗派にも属さない「絶対他力」の存在とされ、そのため浄土宗・天台宗・禅宗を問わず全ての人を受け入れる宗派不問の寺院として成立した。" },
      { type: "spot-card", content: "zenkoji" },
      { type: "heading", content: "7年に一度の「御開帳」とは何か", level: 2 },
      { type: "text", content: "善光寺の本尊は「絶対秘仏」として一切公開されないが、7年に一度の御開帳では「前立本尊」（身代わり仏）が開帳される。2022年に開催された御開帳には716万人が参拝した。前立本尊に触れる「回向柱」という柱が境内に立ち、柱に触れると本尊と縁が結ばれるとされる。次回は2029年。" },
      { type: "heading", content: "境内の見方：大勧進・大本願の二立て体制", level: 2 },
      { type: "text", content: "善光寺は天台宗の「大勧進」と浄土宗の「大本願」という二つの寺院が共同で管理するという珍しい体制をとる。大勧進の住職は「貫主」、大本願の住職は「上人」とそれぞれ異なる称号を持つ。お朝事では両寺院の住職が並んで参道を歩くため、どちらが大勧進・大本願かを見分けるのもお朝事見学の楽しみ。" },
    ],
    relatedArticleSlugs: ["nagano-zenkoji-morning-ritual", "nagano-nagano-city-solo"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "nagano-karuizawa-winter",
    title: "冬の軽井沢──スキーと温泉とアウトレット、寒い季節のリゾート活用術",
    description: "夏の軽井沢しか知らないのはもったいない。スキー・温泉が加わる冬の軽井沢が実は最強。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-12-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nagano",
    tags: ["軽井沢", "冬", "スキー", "温泉", "長野"],
    spotIds: ["karuizawa"],
    sections: [
      { type: "heading", content: "軽井沢プリンスホテルスキー場は初心者に最適", level: 2 },
      { type: "text", content: "軽井沢駅から徒歩5分の「軽井沢プリンスホテルスキー場」は標高差160mのコンパクトなゲレンデで、初心者・家族に向いている。1日リフト券4,500円。夜10時まで営業するナイターは、スキーをしながら軽井沢の夜景が楽しめる。スキー場内のロッジで食べるカレーが妙においしい。" },
      { type: "spot-card", content: "karuizawa" },
      { type: "heading", content: "軽井沢アウトレットは冬が狙い目", level: 2 },
      { type: "text", content: "「軽井沢・プリンスショッピングプラザ」は国内最大級のアウトレットモール。夏は大混雑するが12月〜2月の平日は空いており、冬物コートや防寒具の掘り出し物が見つかりやすい。駅直結なので帰り際に立ち寄るのが合理的。" },
      { type: "heading", content: "中軽井沢の「星野エリア」で温泉と食事", level: 2 },
      { type: "text", content: "軽井沢駅から電車で5分の中軽井沢にある「星野エリア」は、星野リゾートが運営するリゾート複合施設。軽井沢・ハルニレテラスには個性的なレストランが集まり、日帰り温泉「トンボの湯」（大人1,400円）は単純アルカリ泉で柔らかい湯が冬に最高。" },
    ],
    relatedArticleSlugs: ["nagano-karuizawa-couple", "nagano-karuizawa-autumn"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "nagano-kamikochi-photography",
    title: "上高地フォトガイド──四季の撮影スポット・最高の光の時間帯・構図の作り方",
    description: "河童橋と穂高の「定番写真」を超えた上高地の撮り方。季節と時間が写真を決める。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-08-02",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nagano",
    tags: ["上高地", "写真", "撮影スポット", "長野", "フォトガイド"],
    spotIds: ["kamikochi"],
    sections: [
      { type: "heading", content: "大正池：早朝の朝靄が全てを変える", level: 2 },
      { type: "text", content: "上高地で最も撮影価値が高い場所は大正池の朝靄が出る早朝。立ち枯れの木と水面の靄と穂高の組み合わせは、世界的な山岳写真の被写体として有名。朝6時前に大正池バス停に着くためには前日宿泊が必須。三脚を低く設定して水面に近づくほど靄の密度が増す。" },
      { type: "spot-card", content: "kamikochi" },
      { type: "heading", content: "河童橋：午前中の光が最も順光になる", level: 2 },
      { type: "text", content: "河童橋から穂高を撮るなら午前中が順光。夕方は逆光になり穂高が暗くなる。橋の上ではなく、橋の東詰から少し下がった位置で橋と穂高を同時に画角に入れる構図が定番。桜の季節（5月初旬）に橋の周囲の桜が咲くと、前景として使える。" },
      { type: "heading", content: "10月：紅葉の上高地はカラマツが主役", level: 2 },
      { type: "text", content: "上高地の秋はカラマツ（落葉松）の黄色が支配的。10月下旬に上高地全体が黄金色に染まり、梓川の青との対比が極端に美しくなる。小梨平キャンプ場付近から梓川を渡る木橋周辺は、カラマツと川と穂高が全部入る構図が撮れる知られざる撮影ポイント。" },
    ],
    relatedArticleSlugs: ["nagano-kamikochi-trekking", "nagano-kamikochi-spring"],
  },
];
