import { Article } from "@/types/article";

export const naraArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "nara-deer-park-morning",
    title: "奈良公園、早朝7時の鹿たち──人が来る前の静寂と野生",
    description: "観光客が押し寄せる前の奈良公園は、鹿が芝を踏む音だけが聞こえる別世界だ。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nara",
    tags: ["鹿", "奈良公園", "早朝", "写真映え"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "夜明け直後、鹿は霧の中にいる", level: 2 },
      { type: "text", content: "奈良公園に朝7時に着くと、鹿はまだ眠そうにしている。早朝の低い光が若草山の斜面を照らし、鹿の背中が金色に輝く瞬間がある。この時間帯にシャッターを切れば、観光パンフレットには絶対載らない写真が撮れる。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "鹿せんべいの配り方に作法あり", level: 2 },
      { type: "text", content: "鹿せんべいは公園内の売り子から購入できる。渡す際は一枚ずつゆっくりと。一度に多く見せると囲まれる。鹿はお礼のお辞儀をすることがあるが、あれはせんべいをねだる行動だと知りながら受け取るのが奈良流だ。" },
      { type: "heading", content: "9時以降に来てはいけない理由", level: 2 },
      { type: "text", content: "9時を過ぎると修学旅行生と外国人観光客が一気に押し寄せる。午前中に公園を歩き終えて、午後は奈良町（ならまち）の路地に逃げ込むのが賢い動き方だ。" },
    ],
    relatedArticleSlugs: ["nara-todaiji-deep-dive", "nara-deer-photography-guide"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "nara-todaiji-deep-dive",
    title: "東大寺を本気で味わう──大仏殿の外側に隠れた見どころ全部",
    description: "大仏だけが東大寺ではない。南大門の仁王像、戒壇院の四天王、裏手の水路まで。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nara",
    tags: ["東大寺", "大仏", "歴史", "寺社仏閣"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "南大門の仁王像は近くで見ろ", level: 2 },
      { type: "text", content: "高さ8.4mの金剛力士像は、柵の隙間から顔を近づけると細部の彫刻に圧倒される。運慶・快慶らが69日間で仕上げたとされる傑作。遠くから眺めるだけで通り過ぎる人が多すぎる。" },
      { type: "heading", content: "大仏殿の柱の穴は何のため？", level: 2 },
      { type: "text", content: "大仏殿内部の柱に開けられた穴は、大仏の鼻の穴と同じ大きさとされる。くぐると無病息災のご利益があるとされ、子どもはもちろん大人も挑戦する。意外とくぐれる体格の人が多い。" },
      { type: "heading", content: "戒壇院の四天王で締める", level: 2 },
      { type: "text", content: "大仏殿から西に徒歩5分の戒壇院は、奈良時代の四天王像が現役で並ぶ。特に広目天の像は、巻物に何かを書き込もうとするポーズが独特で、見る角度によって表情が変わる。入場者が少ないため、静かに向き合える。" },
    ],
    relatedArticleSlugs: ["nara-deer-park-morning", "nara-horyuji-ancient-walk"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "nara-yoshino-cherry-blossom",
    title: "吉野の千本桜──日本一の花見とその正しい登り方",
    description: "吉野は「行けばわかる」ではなく、「知ってから行く」場所だ。混雑を制する計画術。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nara",
    tags: ["吉野", "桜", "花見", "春", "絶景"],
    spotIds: ["yoshino"],
    sections: [
      { type: "heading", content: "下千本・中千本・上千本・奥千本の違い", level: 2 },
      { type: "text", content: "吉野山の桜は標高差があるため、開花時期が約一週間ずれる。下千本（約200m）から奥千本（約600m）まで、開花前線が山を登っていく様子は壮観だ。見頃の時期は近鉄吉野駅の公式情報をこまめに確認すること。" },
      { type: "spot-card", content: "yoshino" },
      { type: "heading", content: "ロープウェイは使わない選択肢", level: 2 },
      { type: "text", content: "七曲り坂を歩いて登ると、桜のトンネルの中を歩く体験ができる。所要45分だが、途中の展望台から見る中千本の眺めは、ロープウェイからは得られない視点だ。帰りだけロープウェイを使うのが現実的。" },
      { type: "heading", content: "柿の葉寿司で山の中腹昼食", level: 2 },
      { type: "text", content: "吉野名物の柿の葉寿司は、塩鯖と米を柿の葉で包んだ保存食が起源。中千本エリアの茶屋で食べると、桜を眺めながらの昼食になる。温かい葛うどんと組み合わせるのが地元流。" },
    ],
    relatedArticleSlugs: ["nara-yoshino-autumn-foliage", "nara-seasonal-events-calendar"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "nara-kasuga-taisha-visit",
    title: "春日大社の歩き方──朱の回廊、神鹿、奥の院まで",
    description: "世界遺産・春日大社は表参道だけが全てではない。奥の院まで続く古道の静けさを体験する。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nara",
    tags: ["春日大社", "世界遺産", "神社", "奈良公園"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "参道の石灯籠、3000基の意味", level: 2 },
      { type: "text", content: "表参道から本殿まで続く参道に並ぶ約3000基の石灯籠は、信者からの奉納品だ。苔むした灯籠の列は、奈良の湿度と時間が作り出した独特の景観。夕刻の光が横から差し込む時間帯が最も美しい。" },
      { type: "heading", content: "万燈籠は節分と盂蘭盆会に", level: 2 },
      { type: "text", content: "年2回（2月節分と8月14〜15日）に行われる万燈籠は、3000基すべての灯籠に火を入れる神事。境内が幽玄な光に包まれる体験は、一度見ると忘れられない。チケットは事前予約が必須。" },
      { type: "heading", content: "若宮おん祭りは12月に", level: 2 },
      { type: "text", content: "12月17日の若宮おん祭りは、平安時代から900年以上続く祭礼。時代装束を纏った行列が春日大社から出発する光景は、テーマパークでは絶対に再現できない本物の歴史だ。" },
    ],
    relatedArticleSlugs: ["nara-deer-park-morning", "nara-naramachi-stroll"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "nara-horyuji-ancient-walk",
    title: "法隆寺──世界最古の木造建築に、ただ黙って立つ",
    description: "1400年前の建物が現役で立っている。これがどれほど異常なことか、奈良に来て初めてわかる。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nara",
    tags: ["法隆寺", "世界遺産", "歴史", "飛鳥時代"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "西院伽藍の時間旅行", level: 2 },
      { type: "text", content: "西院伽藍の五重塔と金堂は、推古天皇時代に建てられた世界最古の木造建築群。柱を叩くと乾いた音が返ってくる。1400年間、雨にも地震にも耐えてきた木の密度を、手のひらで感じる。" },
      { type: "heading", content: "百済観音は別格", level: 2 },
      { type: "text", content: "大宝蔵院に収められた百済観音は、7世紀の彫刻でありながら驚くほどモダンな造形をしている。細長い体躯、左右対称に近い配置、前方に差し出した手。美術史家が「古代の抽象彫刻」と呼ぶ理由が一目でわかる。" },
      { type: "heading", content: "帰りに中宮寺へ立ち寄る", level: 2 },
      { type: "text", content: "法隆寺東院の隣にある中宮寺は、菩薩半跏像で知られる尼寺。エジプトのスフィンクス、モナリザと並ぶ「世界三大微笑」に数える人もいる。法隆寺とセットで必ず訪れること。" },
    ],
    relatedArticleSlugs: ["nara-todaiji-deep-dive", "nara-yakushiji-pilgrimage"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "nara-yakushiji-pilgrimage",
    title: "薬師寺──東塔だけが残った奈良時代、その美しさの正体",
    description: "「凍れる音楽」と呼ばれた東塔は解体修理を終え、2020年代に甦った。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nara",
    tags: ["薬師寺", "奈良時代", "世界遺産", "建築"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "東塔の「凍れる音楽」を聴く", level: 2 },
      { type: "text", content: "哲学者エルンスト・クーンが「凍れる音楽」と称した薬師寺東塔。三重塔に見えて実は六重構造というリズム感が、音楽的な美しさを生む。解体修理後の姿は、奈良時代の白鳳文化の精華そのものだ。" },
      { type: "heading", content: "薬師三尊と月光菩薩の対話", level: 2 },
      { type: "text", content: "金堂に安置された薬師三尊像のうち、月光菩薩は特に表情が豊かだ。左斜め下から見上げると、視線がこちらに向いているように見える。仏師の意図した角度が、1300年後の今も生きている。" },
      { type: "heading", content: "玄奘三蔵院の壁画で締める", level: 2 },
      { type: "text", content: "東院堂の北に位置する玄奘三蔵院は、平山郁夫が30年かけて描いた「大唐西域壁画」が展示されている。現代の絵師が古代の旅を描いた作品は、薬師寺という古建築の中で特別な緊張感を持つ。" },
    ],
    relatedArticleSlugs: ["nara-horyuji-ancient-walk", "nara-todaiji-deep-dive"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "nara-naramachi-stroll",
    title: "奈良町（ならまち）散策──江戸期の町家が現役の迷宮",
    description: "奈良公園から徒歩10分、観光地図に載らない路地に本当の奈良の日常がある。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nara",
    tags: ["ならまち", "町家", "カフェ", "散策"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "猿沢池の南側から入る", level: 2 },
      { type: "text", content: "ならまちの入口は猿沢池の南側。観光客は池の前で写真を撮ってUターンするが、池の南を渡ると急に空気が変わる。江戸時代の間口が狭く奥行きが深い「うなぎの寝床」形式の町家が連続する。" },
      { type: "heading", content: "身代わり申と魔除けの意味", level: 2 },
      { type: "text", content: "ならまちの軒先に吊るされた赤い猿の人形は「身代わり申」と呼ばれる。住民の厄を引き受けてくれる守護符だ。観光化された今でも、本物の家に現役で吊るされているのがならまちの誠実さ。" },
      { type: "heading", content: "町家カフェで昼休憩", level: 2 },
      { type: "text", content: "ならまちには築100年を超える町家を改装したカフェが点在する。梁を活かした天井、坪庭に落ちる光、木の床の軋み。スペシャルティコーヒーを出す店も増え、若い旅人が長居する場所になっている。" },
    ],
    relatedArticleSlugs: ["nara-kasuga-taisha-visit", "nara-mochi-sweets-tour"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "nara-mochi-sweets-tour",
    title: "奈良の餅文化を食べ尽くす──よもぎ餅、わらび餅、三輪そうめんまで",
    description: "奈良は「餅の国」だ。草餅、わらび餅、吉野くず餅。地域ごとに形が変わる甘味文化を追う。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nara",
    tags: ["餅", "わらび餅", "グルメ", "和菓子"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "花芝餅の草餅は早い者勝ち", level: 2 },
      { type: "text", content: "奈良市内の老舗和菓子屋の草餅は、朝に仕込んだ分だけ売って終わり。午後に訪れると売り切れていることも珍しくない。当日朝に電話で在庫確認するのが奈良の常識だ。" },
      { type: "heading", content: "吉野のくず餅は別次元", level: 2 },
      { type: "text", content: "吉野本葛を使ったくず餅は、スーパーで売られる葛餅とは全く別物だ。透明で弾力があり、冷やして食べると喉越しがとろける。吉野に来たなら必ず本葛を謳う店で食べること。" },
      { type: "heading", content: "三輪そうめんで締める昼食", level: 2 },
      { type: "text", content: "奈良県桜井市の三輪は日本そうめん発祥の地とされる。三輪大社参道沿いの食堂で食べる「釜揚げそうめん」は、湯の中に直接つけて食べる形式。コシが強く、麺だけで満腹になる。" },
    ],
    relatedArticleSlugs: ["nara-sake-nara-city", "nara-naramachi-stroll"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "nara-sake-nara-city",
    title: "奈良の日本酒──菩提酛発祥の地で飲む、古代酒の系譜",
    description: "奈良は日本酒の起源の地だ。菩提酛という醸造技術が生まれた正暦寺と、現代の奈良酒蔵を巡る。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nara",
    tags: ["日本酒", "蔵元", "奈良", "グルメ"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "正暦寺と菩提酛の歴史", level: 2 },
      { type: "text", content: "奈良市郊外の正暦寺は、日本清酒の発祥地とされる。室町時代に確立された菩提酛製法は、乳酸菌を活用した安全な醸造法の原点。現在は毎年1月に「菩提酛仕込み」の見学会が行われる。" },
      { type: "heading", content: "奈良の地酒を飲み比べる", level: 2 },
      { type: "text", content: "奈良市内の地酒専門バーでは、県内10以上の蔵元の酒を飲み比べできる。奈良豆腐や飛鳥鍋との組み合わせを店主に相談すると、旅の記念になる食事体験になる。" },
      { type: "heading", content: "奈良酒の土産選び", level: 2 },
      { type: "text", content: "奈良駅周辺の酒専門店では、720mlの一升瓶から300mlの小瓶まで豊富に取り揃えている。搾りたて生酒は冷蔵管理が必要だが、クール宅配を使えば全国発送できる。現地でしか手に入らない限定品を狙うこと。" },
    ],
    relatedArticleSlugs: ["nara-mochi-sweets-tour", "nara-naramachi-stroll"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "nara-family-day-trip",
    title: "奈良・子連れデイトリップ完全プラン──鹿と大仏と若草山",
    description: "子どもが喜ぶ奈良の定番を、混雑を避けながら効率よく回る家族旅の正解プラン。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "nara",
    tags: ["家族旅行", "子連れ", "鹿", "奈良公園"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "朝イチの鹿せんべい体験", level: 2 },
      { type: "text", content: "子どもにとって、鹿から直接せんべいを食べてもらう体験は最高の思い出になる。ただし小さい子は鹿が群がって怖がることもある。親がせんべいを持ち、子どもが1枚渡す形でサポートするとうまくいく。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "若草山の芝すべりは子どもに大人気", level: 2 },
      { type: "text", content: "東大寺の東側に位置する若草山は、3月中旬〜11月末に開山。傾斜のある芝生でビニール袋を使った芝すべりは、子どもが何度でもやりたがる。頂上からの奈良市街一望は大人にも満足度が高い。" },
      { type: "heading", content: "昼は奈良公園内の食堂で", level: 2 },
      { type: "text", content: "公園内の食堂は子連れ対応が充実している。柿の葉寿司定食、鹿うどん（鹿肉うどん）、茶粥定食など奈良らしいメニューが揃う。鹿肉は臭みなく、子どもでも食べやすい味付けをしている店が多い。" },
    ],
    relatedArticleSlugs: ["nara-deer-park-morning", "nara-family-indoor-rainy"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "nara-family-indoor-rainy",
    title: "雨の奈良でも楽しめる屋内スポット5選──子連れ・雨天対応プラン",
    description: "雨でも奈良は十分楽しい。博物館、奈良町格子の家、食体験。屋根のある奈良の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "nara",
    tags: ["雨天", "室内", "子連れ", "博物館"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "奈良国立博物館の常設展示", level: 2 },
      { type: "text", content: "奈良国立博物館の「なら仏像館」は、日本最高水準の仏像コレクションを持つ。小学生以下は無料。音声ガイドを借りると、子どもでも仏像の意味を理解できる解説が付いている。" },
      { type: "heading", content: "ならまち格子の家で昔の暮らしを体験", level: 2 },
      { type: "text", content: "無料で入れる「ならまち格子の家」は、江戸時代の町家を復元した施設。竈（かまど）、土間、坪庭が再現されており、子どもが「昔の人はこんな家に住んでいたの？」と質問しやすい場所だ。" },
      { type: "heading", content: "奈良町にぎわいの家で手工芸体験", level: 2 },
      { type: "text", content: "ならまち内の体験施設では、墨絵体験、木彫り体験、奈良筆作り体験などを予約なしで楽しめる日もある。雨の日の半日をここで過ごすと、子どもに奈良の伝統工芸が自然と身に付く。" },
    ],
    relatedArticleSlugs: ["nara-family-day-trip", "nara-naramachi-stroll"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "nara-couple-date-plan",
    title: "奈良カップル旅行──鹿と夕焼けと二人だけの時間",
    description: "修学旅行生でごった返す奈良は、夕刻になると別の顔を見せる。二人で静かに歩く奈良の夜。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "nara",
    tags: ["カップル", "デート", "夕景", "奈良"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "夕刻の奈良公園、鹿が帰っていく", level: 2 },
      { type: "text", content: "観光バスが出発する16時以降、奈良公園は急に静かになる。夕日が浮見堂に落ちる瞬間を鷺池の畔で待つのは、奈良最高のデートシーンだ。敷物一枚持参すると、芝の上でゆっくりできる。" },
      { type: "heading", content: "ならまちのイタリアンで夕食", level: 2 },
      { type: "text", content: "近年、ならまちには町家を改装したレストランが増えている。奈良産食材を使ったイタリアンは、大和牛や大和野菜を活かした創作料理が魅力。ランチより夜のコースの方がゆったりした時間になる。" },
      { type: "heading", content: "猿沢池の夜景で締めくくる", level: 2 },
      { type: "text", content: "食後は猿沢池へ。興福寺五重塔が水面に映る夜景は、京都の夜景に劣らない美しさだ。池の周囲をゆっくり一周すると、二人の旅の記憶が定着する。" },
    ],
    relatedArticleSlugs: ["nara-luxury-ryokan-stay", "nara-naramachi-stroll"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "nara-luxury-ryokan-stay",
    title: "奈良の高級旅館に泊まる──古都の夜を独占する贅沢",
    description: "奈良は日帰り観光が多いが、泊まると全く別の体験が待っている。鹿と共に夜明けを迎える朝。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-08-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "nara",
    tags: ["高級旅館", "贅沢旅", "奈良泊", "温泉"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "観光客が去った後の奈良公園", level: 2 },
      { type: "text", content: "旅館に泊まると、夕食後に誰もいない奈良公園を散歩できる。鹿が芝に伏して眠り、春日大社の灯籠が静かに揺れる。この体験は日帰りでは絶対に得られない。" },
      { type: "heading", content: "奈良食材の懐石料理", level: 2 },
      { type: "text", content: "奈良の高級旅館の夕食は大和牛、吉野葛、大和まな（伝統野菜）、天川みずなすなど奈良県産食材が主役。茶粥から始まる朝食も奈良らしさがある。" },
      { type: "heading", content: "早朝の貸切感が最大の特典", level: 2 },
      { type: "text", content: "旅館に泊まる最大の価値は早朝にある。朝7時前に奈良公園や春日大社の参道を歩くと、本当に鹿と二人きりになれる瞬間がある。この感動は1泊数万円を払っても余りある体験だ。" },
    ],
    relatedArticleSlugs: ["nara-couple-date-plan", "nara-deer-park-morning"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "nara-budget-travel-guide",
    title: "奈良を5000円で楽しむ──無料スポット多数、食費を抑える旅術",
    description: "奈良は実は安い旅先だ。世界遺産の多くが低料金か無料。賢い節約法を徹底解説。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "nara",
    tags: ["節約旅行", "バジェット", "無料", "奈良"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "無料で入れる奈良公園と春日大社", level: 2 },
      { type: "text", content: "奈良公園の入場は無料。鹿との触れ合いも無料だ。春日大社の境内も基本無料で入れる（内拝は有料）。これだけで奈良の核心的体験は揃う。" },
      { type: "heading", content: "昼食は西大寺界隈の食堂で600円", level: 2 },
      { type: "text", content: "近鉄奈良駅周辺の地元食堂では、柿の葉寿司セットや茶粥定食が600〜800円で食べられる。観光客向けの店を避け、地元のおばちゃんがやっている食堂を選ぶこと。" },
      { type: "heading", content: "交通費を抑えるJRと近鉄の使い分け", level: 2 },
      { type: "text", content: "大阪・京都からは近鉄が便利だが、JRのお得きっぷも状況によっては有効。奈良市内の主要観光地は徒歩圏内に集中しているため、市内バスを使わず歩くと大幅に節約できる。" },
    ],
    relatedArticleSlugs: ["nara-family-day-trip", "nara-solo-temple-hopping"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "nara-solo-temple-hopping",
    title: "一人旅の奈良──寺をただ歩く、思索の1日",
    description: "誰かと来るのとは違う奈良がある。一人で寺と向き合う時間は、思った以上に豊かだ。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "nara",
    tags: ["一人旅", "寺巡り", "ひとり旅", "奈良"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "ひとりだから気付く建築の細部", level: 2 },
      { type: "text", content: "グループで来ると見落とす細部がある。屋根の反りの角度、組物の影、石畳の苔の生え方。一人でゆっくり歩くと、同じ場所でも全く違う情報が目に入ってくる。" },
      { type: "heading", content: "興福寺から唐招提寺まで歩くルート", level: 2 },
      { type: "text", content: "近鉄奈良駅から興福寺、東大寺、春日大社、唐招提寺、薬師寺まで歩くと約8km。所要は4〜5時間。途中のカフェで本を読む休憩を入れながら歩くと、充実した一人旅の1日が完成する。" },
      { type: "heading", content: "夕暮れの唐招提寺で一日を終える", level: 2 },
      { type: "text", content: "唐招提寺は夕方になると参拝者が激減する。金堂の廻廊に腰掛けて境内を眺めていると、鑑真が唐から渡ってきた1200年前の出来事がふと近くなる気がする。一人旅にしか味わえない静けさだ。" },
    ],
    relatedArticleSlugs: ["nara-horyuji-ancient-walk", "nara-yakushiji-pilgrimage"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "nara-deer-photography-guide",
    title: "奈良の鹿を上手に撮る──スマホで撮れる構図と光の使い方",
    description: "鹿の写真はみんな同じになりがち。プロ顔負けの1枚を撮るための具体的な方法を教える。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nara",
    tags: ["写真", "鹿", "スマホ撮影", "フォトスポット"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "逆光で撮ると鹿が輝く", level: 2 },
      { type: "text", content: "朝の低い光を逆光で使うと、鹿の輪郭が金色に光るシルエット写真が撮れる。スマホのHDRモードをオフにして、露出を手動で下げるのがコツ。" },
      { type: "heading", content: "目線を合わせる──しゃがんで撮れ", level: 2 },
      { type: "text", content: "立ったまま撮ると「見下ろす構図」になる。鹿の目の高さまでしゃがんで撮影すると、対等な視線の写真になり、動物との距離感が圧倒的に縮まる。芝が濡れていることも多いので、レインパンツが有効。" },
      { type: "heading", content: "背景を選ぶ──五重塔を入れる", level: 2 },
      { type: "text", content: "猿沢池方向から興福寺五重塔を背景に入れると、「奈良らしさ」が一枚に凝縮される。五重塔が画面の1/4程度に収まる位置に鹿を配置するのが構図の基本。" },
    ],
    relatedArticleSlugs: ["nara-deer-park-morning", "nara-kasuga-taisha-visit"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "nara-seasonal-events-calendar",
    title: "奈良の年中行事カレンダー──お水取りから正倉院展まで",
    description: "奈良の祭りは1300年続いている。季節ごとの神事と行事を知ると、旅の目的が倍になる。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-01-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nara",
    tags: ["年中行事", "お水取り", "正倉院展", "奈良のイベント"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "3月のお水取りは奈良に春を呼ぶ", level: 2 },
      { type: "text", content: "東大寺二月堂で行われる「お水取り（修二会）」は、奈良に春の訪れを告げる行事として1200年以上続く。3月1〜14日の夜、大松明の火の粉を浴びると無病息災が得られるとされる。14日のクライマックスは特に圧倒的だ。" },
      { type: "heading", content: "10〜11月の正倉院展", level: 2 },
      { type: "text", content: "奈良国立博物館の正倉院展は、天平時代の宝物が年に一度公開される催し。展示品は毎年入れ替わるため、何度通っても飽きない。入場に行列ができるため、平日朝一番の入場がおすすめ。" },
      { type: "heading", content: "12月の春日若宮おん祭り", level: 2 },
      { type: "text", content: "平安時代末期から続く春日若宮おん祭りは、12月17日に行われる時代行列が見どころ。奈良市街中心部を歩く雅楽・舞楽・流鏑馬は、日本の古典文化が生きた形で継続している証だ。" },
    ],
    relatedArticleSlugs: ["nara-yoshino-cherry-blossom", "nara-todaiji-deep-dive"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "nara-yoshino-autumn-foliage",
    title: "吉野の紅葉──桜で有名な山が秋に見せる赤の圧力",
    description: "春の桜ほど知られていないが、吉野の秋は桜の時期に劣らない絶景を作り出す。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-10-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nara",
    tags: ["紅葉", "吉野", "秋", "絶景"],
    spotIds: ["yoshino"],
    sections: [
      { type: "heading", content: "吉野の紅葉は11月初旬がピーク", level: 2 },
      { type: "text", content: "標高約600mの奥千本は10月下旬から色づき始め、11月初旬に見頃を迎える。春の桜と異なり、紅葉の時期は比較的観光客が少ない。山道の静寂の中で楽しめる。" },
      { type: "spot-card", content: "yoshino" },
      { type: "heading", content: "金峯山寺蔵王堂の秘仏特別公開", level: 2 },
      { type: "text", content: "吉野山の中心にある金峯山寺蔵王堂では、春と秋に秘仏・蔵王権現像の特別公開が行われる。高さ7mを超える青黒い巨大像は、通常見ることができない。紅葉の時期に合わせると一石二鳥だ。" },
      { type: "heading", content: "吉野葛で体を温める", level: 2 },
      { type: "text", content: "山の冷気が染みる秋の吉野では、吉野本葛を使ったくず湯が体にしみる。参道沿いの茶屋で飲むくず湯は、ショウガと黒糖が入りほんのり甘い。紅葉を見ながら飲む一杯は格別だ。" },
    ],
    relatedArticleSlugs: ["nara-yoshino-cherry-blossom", "nara-seasonal-events-calendar"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "nara-ancient-history-tour",
    title: "飛鳥・藤原を巡る──日本の夜明けを自転車で走る",
    description: "教科書の中にしかなかった「飛鳥時代」が、奈良南部では今も地面の上にある。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nara",
    tags: ["飛鳥", "古代史", "自転車", "奈良南部"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "飛鳥駅でレンタサイクルを借りる", level: 2 },
      { type: "text", content: "近鉄飛鳥駅前のレンタサイクルショップで電動自転車を借りると、エリア全体をストレスなく回れる。飛鳥寺から石舞台古墳まで約5km、高低差があるため電動がおすすめ。" },
      { type: "heading", content: "石舞台古墳──蘇我馬子の墓説", level: 2 },
      { type: "text", content: "蘇我馬子の墓とも言われる石舞台古墳は、日本最大の横穴式石室を持つ。内部に入れるため、天井を支える巨石の圧倒的な重量感を体感できる。周囲には復元された飛鳥の景観が広がる。" },
      { type: "heading", content: "明日香村の棚田と夕日", level: 2 },
      { type: "text", content: "稲渕の棚田は秋に黄金色に輝く。日本の原風景とも言える景観の中に立つと、古代から続く農耕文化の連続性を感じる。夕日が棚田を染める時間帯は、写真家たちが集まる奈良の隠れた名シーンだ。" },
    ],
    relatedArticleSlugs: ["nara-horyuji-ancient-walk", "nara-yakushiji-pilgrimage"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "nara-park-photo-spots",
    title: "奈良公園の写真映えスポット10選──プロが選ぶ構図とタイミング",
    description: "同じ場所で撮っているはずなのに、なぜかあの人の写真はきれいだ。その理由を全部解説。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nara",
    tags: ["写真映え", "インスタ", "奈良公園", "フォトスポット"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "浮見堂と鷺池──朝霧が演出する水鏡", level: 2 },
      { type: "text", content: "春日野原の南にある鷺池は、朝霧が出る日に行くと浮見堂が水面に映り込む絶景が撮れる。晴れた日よりも曇りの日に霧が出やすく、春と秋の早朝が最も条件が揃いやすい。" },
      { type: "spot-card", content: "nara-park" },
      { type: "heading", content: "登大路園地の鹿と芝、広角レンズで", level: 2 },
      { type: "text", content: "東大寺の手前、登大路園地の広い芝生に鹿が点在する光景は、広角で撮ると奥行きが出る。前景に鹿一頭を近くに置き、背景に東大寺の森を入れると奈良らしい一枚になる。" },
      { type: "heading", content: "夕刻の興福寺五重塔と猿沢池", level: 2 },
      { type: "text", content: "猿沢池から興福寺五重塔を見上げる構図は、奈良で最も有名な写真スポットのひとつ。夕暮れ時に五重塔がライトアップされると、池面への映り込みと合わさって幻想的な画になる。" },
    ],
    relatedArticleSlugs: ["nara-deer-photography-guide", "nara-deer-park-morning"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "nara-spring-green-walk",
    title: "奈良の新緑──5月の若草山と青葉の東大寺",
    description: "桜と紅葉に隠れているが、5月の奈良は一年で最も緑が美しい季節かもしれない。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nara",
    tags: ["新緑", "5月", "若草山", "春"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "若草山一帯の萌黄色", level: 2 },
      { type: "text", content: "5月の若草山は芝が萌黄色に染まる。鹿の群れが緑の丘を歩く様子は、奈良の春の代名詞的風景だ。山頂から見下ろす奈良市街も、建物よりも緑が多く見える豊かな景観が広がる。" },
      { type: "heading", content: "東大寺の境内に差し込む緑の光", level: 2 },
      { type: "text", content: "東大寺大仏殿の周囲の杉木立は、初夏に緑が最も深くなる。回廊内から空を見上げると、大木の葉が光を遮りながらも木漏れ日が降り注ぐ。この静かな光の中に大仏殿が立つ姿は、秋や冬とは全く異なる表情だ。" },
      { type: "heading", content: "正倉院の収蔵品と新緑の取り合わせ", level: 2 },
      { type: "text", content: "正倉院の外観（内部非公開）は東大寺境内の北東角にある。校倉造りの建物が新緑に囲まれた姿は、奈良時代の建築美と自然の調和を体感させてくれる。" },
    ],
    relatedArticleSlugs: ["nara-yoshino-cherry-blossom", "nara-deer-park-morning"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "nara-yoshino-overnight",
    title: "吉野に泊まる──桜守の宿と山上の夜明け",
    description: "日帰りの吉野では見えない世界がある。山の旅籠に泊まって、桜のない季節の吉野を体験する。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "nara",
    tags: ["吉野", "宿泊", "旅籠", "贅沢旅"],
    spotIds: ["yoshino"],
    sections: [
      { type: "heading", content: "観光客が消えた後の吉野山", level: 2 },
      { type: "text", content: "桜シーズンの吉野は17時を過ぎると参拝客がほぼいなくなる。宿泊者だけに許された静寂の山道を歩くと、吉野の本質が見えてくる。翌朝5時の金峯山寺の朝勤行に参加できるのも泊まりならではだ。" },
      { type: "spot-card", content: "yoshino" },
      { type: "heading", content: "吉野材の料理と吉野葛の全品コース", level: 2 },
      { type: "text", content: "吉野山の旅館の夕食は、吉野産の食材を贅沢に使った会席料理。鮎の塩焼き、葛豆腐、吉野牛のすき焼き。山の宿とは思えない本格的な料理が、地元の食文化を体感させてくれる。" },
      { type: "heading", content: "夜明けの奥千本で独り占め", level: 2 },
      { type: "text", content: "早起きして奥千本まで歩けば、完全に一人の空間で吉野山の朝を体験できる。桜の季節には数万人が訪れる場所が、早朝の冷気の中に完全な沈黙で包まれている。この対比が吉野泊の最大の価値だ。" },
    ],
    relatedArticleSlugs: ["nara-yoshino-cherry-blossom", "nara-yoshino-autumn-foliage"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "nara-winter-illumination",
    title: "冬の奈良──人が来ない季節の静寂と冬至祭",
    description: "冬の奈良は空いている。気温は低いが、霜が降りた朝の奈良公園はどの季節より美しい。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nara",
    tags: ["冬", "奈良", "イルミネーション", "オフシーズン"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "霜の奈良公園、鹿は元気", level: 2 },
      { type: "text", content: "12月〜2月の奈良公園は観光客が激減する。霜が降りた芝生に鹿がたたずむ姿は、春夏秋とは全く異なる表情だ。防寒さえすれば、最も贅沢な奈良体験ができる季節だ。" },
      { type: "heading", content: "春日大社の万燈籠（節分）", level: 2 },
      { type: "text", content: "2月3日の節分の夜、春日大社では万燈籠が行われる。3000基の灯籠が一斉に点灯する光景は、1年を通じて最も幻想的な奈良の夜だ。事前予約が必要だが、一生に一度は体験する価値がある。" },
      { type: "heading", content: "鍋と温かい奈良の冬食", level: 2 },
      { type: "text", content: "冬の奈良は飛鳥鍋（鶏肉と牛乳のミルク鍋）が旬。飛鳥時代に唐から伝わったとされるミルク鍋は、奈良の冬の郷土料理として各旅館で提供されている。甘くなく、あっさりとした和風の味付けが特徴だ。" },
    ],
    relatedArticleSlugs: ["nara-seasonal-events-calendar", "nara-kasuga-taisha-visit"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "nara-couple-overnight-ryokan",
    title: "奈良カップル一泊旅行──古都に泊まる特別な夜",
    description: "彼氏・彼女と泊まる奈良旅行。宿選び、食事、夜の散歩まで、二人旅の完全プランを提案。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "nara",
    tags: ["カップル", "一泊", "旅館", "記念日"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "宿は奈良公園エリアを選ぶ", level: 2 },
      { type: "text", content: "奈良は宿泊施設が少なく早めの予約が必要。奈良公園周辺の旅館は、翌朝の早朝散歩の利便性が高い。記念日なら風呂付き客室のある宿を選ぶと、二人の時間が充実する。" },
      { type: "heading", content: "夕食は大和牛を食べる", level: 2 },
      { type: "text", content: "奈良市内には大和牛（やまとうし）専門の焼肉店やステーキレストランが複数ある。霜降りの大和牛は関西の中でも屈指のブランド和牛。旅の記念日に選ぶ価値がある。" },
      { type: "heading", content: "夜の奈良公園を二人で歩く", level: 2 },
      { type: "text", content: "夕食後、ライトアップされた東大寺や興福寺周辺を歩くのが奈良泊の醍醐味だ。日中の喧噪が嘘のように静かになった公園で、鹿と出会うことも珍しくない。二人だけの奈良が始まる。" },
    ],
    relatedArticleSlugs: ["nara-couple-date-plan", "nara-luxury-ryokan-stay"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "nara-naramachi-cafe-guide",
    title: "ならまちのカフェ完全ガイド──町家で飲む一杯のコーヒー",
    description: "古い建物の中で飲むコーヒーは、なぜこんなに美味しいのか。ならまちのカフェ文化を総まとめ。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nara",
    tags: ["カフェ", "ならまち", "コーヒー", "町家"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "築100年の町家で飲むスペシャルティコーヒー", level: 2 },
      { type: "text", content: "ならまちには近年、古民家を改装したスペシャルティコーヒー専門店が増えている。梁と土壁が残るインテリアの中で飲む一杯は、どんなおしゃれなカフェとも違う時間の質がある。" },
      { type: "heading", content: "日本茶専門店も外せない", level: 2 },
      { type: "text", content: "コーヒーだけでなく、日本茶専門店もならまちの重要なカフェ文化を担う。大和茶を使ったかき氷（夏季限定）や抹茶パフェは、奈良らしさとスイーツの融合として人気が高い。" },
      { type: "heading", content: "テイクアウトで公園へ", level: 2 },
      { type: "text", content: "ならまちのカフェでテイクアウトして、徒歩5分の浮見堂周辺の芝生で飲むのも贅沢な過ごし方だ。コーヒーと奈良公園の鹿という組み合わせは、他のどこでも体験できない。" },
    ],
    relatedArticleSlugs: ["nara-naramachi-stroll", "nara-mochi-sweets-tour"],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "nara-summer-firefly-night",
    title: "奈良の蛍──初夏の宇陀川と月ヶ瀬で見る乱舞",
    description: "奈良南部の清流には、まだ蛍が飛んでいる。6月の奈良で蛍を見る旅を計画する。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "nara",
    tags: ["蛍", "初夏", "宇陀", "自然"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "宇陀川の蛍は6月初旬がピーク", level: 2 },
      { type: "text", content: "奈良県宇陀市を流れる宇陀川は、ゲンジボタルの生息地として知られる。6月1〜10日頃が見頃で、薄暮から20時頃までの1時間が最も多く飛ぶ。車での移動が基本で、懐中電灯は蛍を脅かすため使わないこと。" },
      { type: "heading", content: "月ヶ瀬の梅と蛍の二役", level: 2 },
      { type: "text", content: "月ヶ瀬は梅の名所として有名だが、初夏には蛍スポットとしても地元民に親しまれている。月ヶ瀬湖畔を歩きながら蛍を眺め、近くの民宿に泊まると奈良の山里の暮らしが体感できる。" },
      { type: "heading", content: "蛍の後は星空観察", level: 2 },
      { type: "text", content: "奈良南部は光害が少なく、蛍鑑賞が終わった後に仰向けで星空を見上げると、天の川が肉眼で見えることがある。蛍と星空という二つの光の饗宴は、夏の奈良旅の特権だ。" },
    ],
    relatedArticleSlugs: ["nara-spring-green-walk", "nara-ancient-history-tour"],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "nara-todaiji-with-kids",
    title: "子どもと東大寺──大仏の大きさを体で理解させる方法",
    description: "「大きい」では伝わらない。子どもが東大寺大仏の規模を実感できる、親のための案内術。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "nara",
    tags: ["東大寺", "子連れ", "大仏", "教育"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "大仏の手のひらに乗れる？", level: 2 },
      { type: "text", content: "盧舎那仏の手のひらの大きさは約2.5m。成人が5〜6人乗れる計算になる。子どもにこの数字を伝えてから入堂すると、見え方が変わる。事前に「自分の手と比べてみよう」と伝えておくのが効果的だ。" },
      { type: "heading", content: "柱の穴くぐりで盛り上がる", level: 2 },
      { type: "text", content: "大仏殿内の柱に開いた穴は、子どもにとって最高のアトラクションだ。くぐった後に「大仏の鼻の穴と同じ大きさ」と教えると驚く。大仏の顔を見上げながら「あの穴か！」と気づく瞬間が楽しい。" },
      { type: "heading", content: "ミュージアムショップの大仏グッズ", level: 2 },
      { type: "text", content: "大仏殿を出たところの売店には、大仏をモチーフにしたお菓子やグッズが充実している。大仏ラムネ、大仏サブレなど、子どもが喜ぶ土産が揃う。価格帯も300〜600円程度で家族旅の予算に優しい。" },
    ],
    relatedArticleSlugs: ["nara-family-day-trip", "nara-deer-park-morning"],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "nara-yoshino-spring-plan",
    title: "吉野桜1泊2日プラン──旅行者が知らない穴場と正しい時期の選び方",
    description: "「吉野に行ったけど桜が終わっていた」を防ぐ。開花情報の読み方と移動計画を完全解説。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "nara",
    tags: ["吉野", "桜", "1泊2日", "プランニング"],
    spotIds: ["yoshino"],
    sections: [
      { type: "heading", content: "開花情報は「下千本」「奥千本」を別々に確認", level: 2 },
      { type: "text", content: "吉野山観光協会の公式サイトでは、下・中・上・奥千本の開花状況を別々に更新している。標高差約400mがあるため、下千本が満開でも奥千本はつぼみということが珍しくない。狙う場所の標高を確認してから日程を決めること。" },
      { type: "heading", content: "1日目：下千本・中千本、2日目：奥千本の計画", level: 2 },
      { type: "text", content: "1日目は午前中に混雑するロープウェイ沿いの下千本・中千本を歩き、午後は宿でゆっくりする。2日目の早朝に奥千本まで歩くと、観光客がいない静寂の桜回廊が体験できる。" },
      { type: "spot-card", content: "yoshino" },
      { type: "heading", content: "帰りは桜の終わった後の景色も美しい", level: 2 },
      { type: "text", content: "桜が散った後の吉野山は、花びらが積もった「花筏」が見られる。満開よりも人が少なく、落花の静けさの中で歩く参道は、また別の感動がある。「外れた」と思わないこと。" },
    ],
    relatedArticleSlugs: ["nara-yoshino-cherry-blossom", "nara-yoshino-overnight"],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "nara-food-local-guide",
    title: "奈良のローカルフード完全攻略──柿の葉寿司から吉野鍋まで",
    description: "奈良の食は地味だと思っていた。でも一つひとつにちゃんと深い理由がある郷土料理だった。",
    coverImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "nara",
    tags: ["郷土料理", "柿の葉寿司", "茶粥", "奈良グルメ"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "柿の葉寿司──防腐の知恵と発酵の旨み", level: 2 },
      { type: "text", content: "柿の葉に含まれるタンニンと抗菌成分が魚の保存を助ける。1日以上経ったものが最も旨いとされ、発酵による酸味が増す。吉野・五條エリアの名店と奈良市内のチェーン店では味が全く異なるため、本場で食べることを推奨する。" },
      { type: "heading", content: "奈良の茶粥──シンプルが最高のご馳走", level: 2 },
      { type: "text", content: "番茶で炊いたさらさらの茶粥は、奈良の家庭料理の根幹だ。旅館の朝食でしか体験できないと思っている人が多いが、ならまちの食堂でも日常食として出している店がある。漬物だけで食べるのが奈良流。" },
      { type: "heading", content: "飛鳥鍋と大和の冬の食卓", level: 2 },
      { type: "text", content: "奈良の冬の鍋料理「飛鳥鍋」は、鶏肉と牛乳を出汁にして野菜を煮込む独特の料理。乳製品を使う鍋は日本でも珍しく、唐から伝来した料理文化の痕跡だという説もある。奈良の居酒屋では冬季限定で提供される。" },
    ],
    relatedArticleSlugs: ["nara-mochi-sweets-tour", "nara-sake-nara-city"],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "nara-best-access-guide",
    title: "奈良へのアクセス完全ガイド──大阪・京都・名古屋からの最安・最速ルート",
    description: "近鉄とJRどっちが得か。新幹線で来る場合は？奈良アクセスの疑問を全部解決する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-02-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "nara",
    tags: ["アクセス", "交通", "近鉄", "奈良駅"],
    spotIds: ["nara-park"],
    sections: [
      { type: "heading", content: "大阪からは近鉄が最強", level: 2 },
      { type: "text", content: "大阪難波から近鉄奈良線の急行で約42分。阪急・JRと組み合わせても時間差はわずかで、近鉄奈良駅が観光エリアへの最近接駅であるため近鉄一択。1dayフリーきっぷも活用可能。" },
      { type: "heading", content: "京都からはJRと近鉄で迷う", level: 2 },
      { type: "text", content: "京都からはJR奈良線（約45分）か近鉄京都線（約35分）。近鉄の方が速く、近鉄奈良駅は観光中心部に近い。ただしJR奈良駅は世界遺産の唐招提寺・薬師寺エリアへの移動が便利な面もある。" },
      { type: "heading", content: "名古屋からは近鉄特急が便利", level: 2 },
      { type: "text", content: "名古屋から近鉄大阪線・近鉄奈良線を経由する特急（約1時間50分）が直通で便利。ひのとり・アーバンライナーとは異なるが、特急料金を払えば快適に移動できる。奈良まで新幹線を使う必要はない。" },
    ],
    relatedArticleSlugs: ["nara-budget-travel-guide", "nara-deer-park-morning"],
  },
];
