import { Article } from "@/types/article";

export const niigataArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "niigata-yahiko-shrine-morning",
    title: "弥彦神社、早朝の参道──越後一宮の空気を独占する時間",
    description: "杉並木が朝霧を纏う時間帯、弥彦神社は別世界になる。越後平野の夜明けと神域の静寂。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-08",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "niigata",
    tags: ["弥彦神社", "越後一宮", "早朝", "参道", "新潟"],
    spotIds: ["yahiko-shrine"],
    sections: [
      { type: "heading", content: "朝7時、杉並木は霧の中にある", level: 2 },
      { type: "text", content: "弥彦神社の大鳥居をくぐる時刻を朝7時に設定すると、杉並木の参道に薄い霧が漂っていることが多い。この時間帯は参拝客がほとんどおらず、修祓を受ける地元の人が数人、神職が掃き清めている姿があるだけだ。轟くような静寂の中で踏みしめる玉砂利の音が、余計に聞こえる。" },
      { type: "spot-card", content: "yahiko-shrine" },
      { type: "heading", content: "弥彦山ロープウェイで越後平野を一望する", level: 2 },
      { type: "text", content: "境内参拝の後、弥彦山山麓駅からロープウェイで山頂展望台へ向かう。9時の始発に乗れば山頂もまだ空いている。晴れた日の展望台からは、日本海と越後平野が180度に広がり、佐渡島の輪郭まで確認できる。この景色を見ると、古代の人がこの山を神域と定めた理由が腑に落ちる。" },
      { type: "heading", content: "参拝後は彌彦公園で紅葉を楽しむ（10〜11月）", level: 2 },
      { type: "text", content: "神社に隣接する彌彦公園は、10月下旬から11月初旬にかけて紅葉が見頃を迎える。もみじ谷と呼ばれるエリアには数十本のカエデが集まり、境内の杉の深緑と紅葉の赤が混ざり合う独特の色彩が生まれる。11月の菊まつり期間と合わせて訪れると、色彩の密度が最高潮になる。" },
    ],
    relatedArticleSlugs: ["niigata-kiyotsu-gorge-art", "niigata-tokamachi-art-field"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "niigata-kiyotsu-gorge-art",
    title: "清津峡「Tunnel of Light」──世界が認めた水鏡の行き方と撮り方",
    description: "日本三大峡谷の終端に現代アートがある。水面に映る峡谷を最高の条件で撮るための全知識。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-05-02",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "niigata",
    tags: ["清津峡", "Tunnel of Light", "大地の芸術祭", "水鏡", "写真映え"],
    spotIds: ["kiyotsu-gorge"],
    sections: [
      { type: "heading", content: "午前10時前が最良の光条件", level: 2 },
      { type: "text", content: "清津峡トンネルの最奥部「Tunnel of Light」は、薄い水盤に峡谷と空が映り込む構造になっている。光の条件が最も整うのは午前中。午後になると日が峡谷の奥まで差し込まず、水鏡の解像感が落ちる。開館直後の9時に入場し、終端に向けて歩くのが推奨プランだ。" },
      { type: "spot-card", content: "kiyotsu-gorge" },
      { type: "heading", content: "3つのパノラマステーションの見どころ", level: 2 },
      { type: "text", content: "トンネル内には終端の手前に3か所のパノラマステーションがある。第1・第2ステーションからは柱状節理の岩壁を近距離で観察でき、第3ステーションからは対岸の岩壁が最も大きく見える。各ステーションで立ち止まり、峡谷の異なる表情を記録してから終端へ進むのが正しい順路だ。" },
      { type: "heading", content: "秋の紅葉期は混雑を覚悟して来る", level: 2 },
      { type: "text", content: "10月下旬〜11月初旬の紅葉期は入場制限がかかるほどの混雑になる。事前にWEBチケットを購入し、開館と同時に入場すること。紅葉と水鏡の組み合わせは唯一無二の美しさだが、平日でも終端では列ができる。水盤の中に足を踏み入れて撮影するスペースを確保するため、前の人が退くのを待つ余裕が必要だ。" },
    ],
    relatedArticleSlugs: ["niigata-yahiko-shrine-morning", "niigata-tokamachi-art-field"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "niigata-nagaoka-fireworks-guide",
    title: "長岡花火──日本最大の三尺玉とフェニックスを見るための完全計画",
    description: "鎮魂と復興の花火は、単なる祭りを超えている。8月2・3日に長岡へ行くための全準備。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "niigata",
    tags: ["長岡花火", "三尺玉", "フェニックス", "夏祭り", "長岡"],
    spotIds: ["nagaoka-fireworks"],
    sections: [
      { type: "heading", content: "フェニックス花火の意味を知ってから見る", level: 2 },
      { type: "text", content: "長岡まつり大花火大会は戦災と水害からの復興を祈念して始まった。「フェニックス」と呼ばれる超大型スターマインは信濃川全長2kmを使い、火の鳥が飛翔する演出で観客を包む。この花火が「感動する」のではなく「胸が痛む」と評されるのは、先に歴史を知っているからだ。観覧前に長岡市内の戦災資料館に立ち寄ることを強く勧める。" },
      { type: "spot-card", content: "nagaoka-fireworks" },
      { type: "heading", content: "有料観覧席は半年前から動く", level: 2 },
      { type: "text", content: "長岡花火の有料席（テーブル席・マス席）は毎年2〜3月頃から申込受付が始まり、人気席は即日完売する。公式サイトとLINE公式アカウントをフォローして、発売日を事前に把握することが必須だ。無料エリアも存在するが、川沿いの好位置は当日の早朝から場所取りが始まる。" },
      { type: "heading", content: "宿は柏崎・新潟まで範囲を広げる", level: 2 },
      { type: "text", content: "長岡市内の宿は本番数ヶ月前には完売する。長岡から電車で20〜40分圏内の柏崎・燕三条・新潟市内まで宿の範囲を広げると選択肢が増える。当日は花火終了後に特別臨時列車が運行されるため、帰りの交通手段を事前に確認すること。" },
    ],
    relatedArticleSlugs: ["niigata-sake-tasting-tour", "niigata-murakamigyu-beef"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "niigata-sado-island-guide",
    title: "佐渡島1泊2日──朱鷺と金山と太鼓の島の歩き方",
    description: "フェリーで渡る離島だから、日常が完全にリセットされる。佐渡の本質に触れる旅の設計図。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "niigata",
    tags: ["佐渡島", "朱鷺", "金山", "太鼓", "離島"],
    spotIds: ["yahiko-shrine"],
    sections: [
      { type: "heading", content: "新潟港から高速船2時間──海を渡ると別の時間が流れる", level: 2 },
      { type: "text", content: "佐渡島へは新潟港からカーフェリー（2時間30分）か高速船ジェットフォイル（65分）でアクセスできる。島に降り立つと、本州の時間感覚が少し遅くなる感じがある。レンタカーを島内で借りると、海岸線を自分のペースで走れる。" },
      { type: "heading", content: "佐渡金山──江戸幕府を支えた金脈の地下へ", level: 2 },
      { type: "text", content: "史跡佐渡金山は江戸時代に世界最大の産金量を誇った金山の坑道跡。実物大の人形が当時の採掘の様子を再現する。坑道内は夏でも15度前後と涼しく、薄い上着があると良い。金塊に手を入れるコーナーでは、約12.5kgの金塊の重さを体感できる。" },
      { type: "heading", content: "たらい舟と朱鷺の森公園", level: 2 },
      { type: "text", content: "小木港周辺では伝統のたらい舟体験が観光客向けに開放されている。浅い磯でバランスをとりながら漕ぐたらい舟は5〜10分の体験だが、島の漁業文化の一端を感じられる。北部の「トキの森公園」では保護されたトキを間近で観察でき、繁殖に成功した個体の野生復帰も行われている。" },
    ],
    relatedArticleSlugs: ["niigata-hegisoba-guide", "niigata-kiyotsu-gorge-art"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "niigata-hegisoba-guide",
    title: "へぎそばを新潟で食べる──布海苔と手繰りの正統を知る",
    description: "スーパーで売っているそばとは別物だ。新潟・小千谷発祥のへぎそばの本当の味とは何か。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "niigata",
    tags: ["へぎそば", "布海苔", "小千谷", "新潟グルメ", "そば"],
    spotIds: ["kiyotsu-gorge"],
    sections: [
      { type: "heading", content: "布海苔がつなぎ──独特のコシと磯の香り", level: 2 },
      { type: "text", content: "へぎそばの最大の特徴は、小麦粉ではなく布海苔（ふのり）をつなぎに使う点だ。もともと織物産業が盛んな小千谷・十日町では、機織りに使う布海苔が身近にあった。これを蕎麦粉のつなぎにしたことで、独特のコシと磯の風味が生まれた。水にさらして盛り付ける「手繰り」の技術も、職人によって見た目が大きく変わる。" },
      { type: "heading", content: "「へぎ」とは何か──器の名前が料理名になった", level: 2 },
      { type: "text", content: "「へぎ」とは薄い板を剥いで作った木製の器のことだ。この器に一口大のそばを手繰りで盛り付けたことから「へぎそば」と呼ばれるようになった。一枚のへぎには3〜4人前が盛られ、テーブルをシェアして食べるのが正式なスタイル。新潟市内の専門店から、小千谷・十日町の老舗まで、食べ比べる価値がある。" },
      { type: "heading", content: "辛み大根おろしとの組み合わせが正解", level: 2 },
      { type: "text", content: "へぎそばのつゆには、山わさびか辛み大根おろしを合わせるのが新潟流だ。布海苔の磯の香りが、辛みのある薬味と相性が良い。食べ終わったら蕎麦湯をもらうこと。へぎそばのそば湯は布海苔の旨みが溶け出し、単体でも飲む価値がある。" },
    ],
    relatedArticleSlugs: ["niigata-sake-tasting-tour", "niigata-murakamigyu-beef"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "niigata-sake-tasting-tour",
    title: "新潟の日本酒を飲み尽くす──越後の地酒蔵巡りと飲み比べの流儀",
    description: "新潟は「淡麗辛口」の代名詞。県内90蔵以上が競い合う日本一の酒の国を旅する。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "niigata",
    tags: ["日本酒", "新潟酒", "蔵元", "淡麗辛口", "飲み比べ"],
    spotIds: ["yahiko-shrine"],
    sections: [
      { type: "heading", content: "新潟清酒が「淡麗辛口」になった理由", level: 2 },
      { type: "text", content: "新潟の軟水と長い低温発酵が、スッキリと切れのある辛口を生む。越後杜氏（とじ）と呼ばれる職人集団が全国の酒蔵に技術を広めた歴史もあり、新潟の醸造文化の厚みが日本酒の水準を押し上げてきた。久保田・八海山・越乃寒梅などの全国ブランドが揃うのも新潟だ。" },
      { type: "heading", content: "新潟市内の角打ちで地酒を飲む", level: 2 },
      { type: "text", content: "新潟市内には地酒を専門に扱う酒屋や角打ちが点在する。古町界隈の日本酒バーでは県内20以上の蔵元の酒を飲み比べできる。同じ辛口でもフルーティーなものからシャープなものまで差があり、飲み比べることで初めて新潟酒の多様性がわかる。" },
      { type: "heading", content: "越後湯沢駅の「ぽんしゅ館」は入門に最適", level: 2 },
      { type: "text", content: "新幹線停車駅・越後湯沢の「ぽんしゅ館」は、新潟全蔵元のお酒を試飲できる施設だ。500円分のコインでランダムに飲める試飲マシーンは旅のスタート地点として機能する。気に入った銘柄があれば即購入でき、新潟酒のガイドとして旅の入口にするのに最適だ。" },
    ],
    relatedArticleSlugs: ["niigata-hegisoba-guide", "niigata-murakamigyu-beef"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "niigata-murakamigyu-beef",
    title: "村上牛と村上の鮭文化──日本最北の城下町に根付いた食の歴史",
    description: "村上には牛と鮭という二つの食文化が共存している。城下町を歩きながら食を深掘りする旅。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "niigata",
    tags: ["村上牛", "鮭", "村上市", "城下町", "新潟グルメ"],
    spotIds: ["yahiko-shrine"],
    sections: [
      { type: "heading", content: "村上牛──知る人ぞ知る超希少ブランド牛", level: 2 },
      { type: "text", content: "村上牛は年間数百頭しか出荷されない超希少な和牛だ。新潟県北部の豊かな自然の中でゆっくりと育てられ、脂のりと赤身のバランスが際立つ。村上市内の専門レストランか高級旅館でしか食べられず、東京の百貨店でも入手困難なブランドだ。旅先で本物を食べる価値がある。" },
      { type: "heading", content: "鮭のまち村上──100種類の鮭料理が伝わる", level: 2 },
      { type: "text", content: "村上は「鮭のまち」として知られ、江戸時代から「鮭の一百家事（ひゃくかじ）」と呼ばれる100種類以上の鮭料理が伝えられてきた。軒先に鮭を吊るして干す「塩引き鮭」は冬の村上の風物詩。城下町の商家通り「黒塀通り」では、鮭料理専門店が軒を連ねる。" },
      { type: "heading", content: "村上城址からの日本海展望", level: 2 },
      { type: "text", content: "城下町を食べ歩いた後は、臥牛山（がぎゅうさん）にある村上城址へ徒歩で登る。石垣だけが残る山頂からは、三面川の河口と日本海が見渡せる。鮭が三面川を遡上する秋（10〜11月）は、橋の上から遡上する鮭を肉眼で確認できる。" },
    ],
    relatedArticleSlugs: ["niigata-hegisoba-guide", "niigata-sake-tasting-tour"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "niigata-ski-resort-guide",
    title: "新潟のスキーリゾート徹底比較──苗場・湯沢・妙高の選び方",
    description: "雪国・新潟のスキー場は首都圏から最も近い大規模ゲレンデが集まる。自分に合う場所の見つけ方。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "niigata",
    tags: ["スキー", "苗場", "湯沢", "妙高", "新潟冬"],
    spotIds: ["kiyotsu-gorge"],
    sections: [
      { type: "heading", content: "新幹線スキーの王道──越後湯沢エリア", level: 2 },
      { type: "text", content: "越後湯沢は上越新幹線で東京から約80分という圧倒的なアクセスの良さを誇る。石打丸山・湯沢高原など複数のスキー場がリフト券の共通化を進めており、初心者から上級者まで対応した幅広いゲレンデが揃う。スキー後は温泉街で地酒というルーティンが確立している。" },
      { type: "heading", content: "苗場スキー場──バブルの記憶と今の実力", level: 2 },
      { type: "text", content: "苗場スキー場はバブル期の象徴として語られるが、現在もプリンスホテルが運営するゲレンデは国内最大規模のひとつだ。ドラゴンドラで谷川連峰の絶景を楽しめる点は他のスキー場にない。雪質は妙高には及ばないが、施設の充実度と立地のアクセスのバランスが良い。" },
      { type: "heading", content: "妙高エリア──上越市の粉雪と温泉の組み合わせ", level: 2 },
      { type: "text", content: "妙高高原は長野との県境近くに位置し、日本海から運ばれる水分の多い雪が降る。関温泉・燕温泉など秘湯系の温泉が周囲に点在し、スキー後の入浴体験が他エリアと一線を画す。赤倉温泉スキー場はヨーロッパ調のリゾートタウンが整備され、宿泊滞在型の旅に向いている。" },
    ],
    relatedArticleSlugs: ["niigata-sake-tasting-tour", "niigata-winter-seafood"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "niigata-couple-date-plan",
    title: "新潟カップル旅行──日本海と棚田と夕日、二人で見る風景",
    description: "新潟は地味だと思っていた。海と山が近く、食が豊かで、人が少ない。カップル旅の最適解かもしれない。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "niigata",
    tags: ["カップル", "新潟", "日本海", "夕日", "デート"],
    spotIds: ["yahiko-shrine", "kiyotsu-gorge"],
    sections: [
      { type: "heading", content: "弥彦神社から始まる古都デート", level: 2 },
      { type: "text", content: "新潟のカップル旅は弥彦から始めるのが王道だ。越後一宮の厳粛な空気の中で参拝し、弥彦山ロープウェイで眼下に広がる越後平野を二人で眺める。山頂展望台のベンチで佐渡島を遠望しながら過ごす時間は、スマホを置きたくなる特別な静けさがある。" },
      { type: "heading", content: "清津峡の水鏡──二人で立つ「Tunnel of Light」", level: 2 },
      { type: "text", content: "清津峡トンネルの終端「Tunnel of Light」は、カップルの写真撮影スポットとして全国的に知られている。水盤に二人のシルエットが映り込む構図は、インスタグラムの投稿でも見覚えのある方が多いだろう。平日の午前中ならば比較的空いており、ゆっくりと向き合える時間が持てる。" },
      { type: "heading", content: "夕食は新潟港近くの海鮮で締める", level: 2 },
      { type: "text", content: "新潟市の古町・本町エリアは海鮮居酒屋が豊富だ。のどぐろ・ズワイガニ・佐渡海老といった日本海の幸が揃い、地酒と合わせた夕食は旅の締めくくりにふさわしい。予約が取れれば日本酒バーで地酒の飲み比べも加えると、旅の記憶として残りやすい。" },
    ],
    relatedArticleSlugs: ["niigata-sake-tasting-tour", "niigata-hegisoba-guide"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "niigata-solo-countryside-walk",
    title: "新潟ひとり旅──越後の田園を一人で歩く、贅沢な何もなさ",
    description: "混んでいないから一人旅に向いている。棚田、峡谷、神社、日本酒。新潟の「静かな豊かさ」を一人で受け取る。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "niigata",
    tags: ["ひとり旅", "新潟", "田園", "棚田", "一人旅"],
    spotIds: ["yahiko-shrine", "kiyotsu-gorge", "nagaoka-fireworks"],
    sections: [
      { type: "heading", content: "一人旅に最適な理由──観光客が少なく、食が安い", level: 2 },
      { type: "text", content: "新潟は東京・大阪のような有名観光地に比べると外国人観光客が少なく、人気スポットでも一人でゆっくり過ごせる。飲食店の物価も首都圏より低く、同じ予算でより豊かな食体験ができる。一人で角打ちに入り、蔵元の方と話しながら地酒を飲む──そんな旅が成立する県だ。" },
      { type: "heading", content: "越後湯沢から十日町──大地の芸術祭エリアを歩く", level: 2 },
      { type: "text", content: "越後湯沢を拠点に、清津峡トンネルと大地の芸術祭のアート作品が点在する十日町・津南エリアを歩く1泊2日コースは一人旅に最適だ。レンタカーかタクシーを使えば、棚田と峡谷とアートを一日で回れる。" },
      { type: "heading", content: "弥彦神社の早朝参拝で旅を締める", level: 2 },
      { type: "text", content: "最終日の朝、弥彦神社に早朝参拝して帰路につく。人のいない杉並木の参道を一人で歩くと、旅全体の総括のような気分になる。そのまま新幹線燕三条駅から帰れば、東京まで1時間半。週末の1泊2日が完成する。" },
    ],
    relatedArticleSlugs: ["niigata-kiyotsu-gorge-art", "niigata-yahiko-shrine-morning"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "niigata-family-day-trip",
    title: "新潟子連れ旅行──鉄道博物館・水族館・花火と子どもが喜ぶ完全プラン",
    description: "新潟は子ども向けの施設が充実している。週末のファミリー旅行で外れない新潟の楽しみ方。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "niigata",
    tags: ["子連れ", "家族旅行", "新潟", "水族館", "アクティビティ"],
    spotIds: ["nagaoka-fireworks"],
    sections: [
      { type: "heading", content: "マリンピア日本海──日本海の生き物を間近で見る", level: 2 },
      { type: "text", content: "新潟市西区にある水族館「マリンピア日本海」は、日本海の生き物を中心に展示する県内最大の水族館だ。マイワシの大群が舞うトンネル水槽、カワウソの生態展示、バンドウイルカのショーなど、子どもが半日以上楽しめるコンテンツが揃う。" },
      { type: "heading", content: "長岡市に子ども向けサイエンス施設", level: 2 },
      { type: "text", content: "長岡市には「科学博物館」と「立体映像館・サイエンス・コア」があり、理科系の体験学習施設が充実している。長岡花火の時期（8月）に合わせて訪れると、花火の歴史と科学も同時に学べる。子どもが花火大会前に花火の仕組みを学んでから夜の本番を見ると、感動が倍増する。" },
      { type: "heading", content: "佐渡金山で子どもに江戸時代を伝える", level: 2 },
      { type: "text", content: "佐渡金山の坑道見学は小学生以上の子どもに特に人気だ。当時の採掘の様子を再現した実物大の人形と、実際の坑道を歩く体験は、教科書の江戸時代が立体的に理解できる生きた歴史教室になる。「400年前の人がここで働いていたんだ」という驚きを子どもと共有できる。" },
    ],
    relatedArticleSlugs: ["niigata-nagaoka-fireworks-guide", "niigata-sado-island-guide"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "niigata-budget-travel",
    title: "新潟を安く旅する──1泊2日1万5000円で日本酒も海鮮も楽しむ節約術",
    description: "物価が低く、無料スポットが多い新潟はバジェット旅行の優等生だ。具体的な予算配分を解説。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "niigata",
    tags: ["節約旅行", "バジェット", "新潟", "格安", "コスパ"],
    spotIds: ["yahiko-shrine", "kiyotsu-gorge"],
    sections: [
      { type: "heading", content: "新幹線よりも高速バスで交通費を半額以下に", level: 2 },
      { type: "text", content: "東京〜新潟間の高速夜行バスを使うと、往復1万円以下で移動できる。新幹線（自由席往復約2万円）の半額以下だ。夜に乗って朝着く夜行バスにすれば宿泊費も1泊分節約できる。体力に余裕があれば、これだけで旅の予算が大幅に改善される。" },
      { type: "heading", content: "弥彦神社と清津峡は入場無料", level: 2 },
      { type: "text", content: "弥彦神社の参拝は無料。清津峡トンネルは入場料800円がかかるが、日本三大峡谷とアートを同時体験できる価格としては割安だ。新潟市内の信濃川沿いの「みなとぴあ」（新潟市歴史博物館）は常設展示500円で新潟の歴史が理解できる。" },
      { type: "heading", content: "地元スーパーで昼食を買う──新潟の惣菜は本物だ", level: 2 },
      { type: "text", content: "新潟市内の地元系スーパー（ウオロク・原信など）の鮮魚コーナーと惣菜コーナーは、地元の魚介を使った惣菜が揃う。昼食をスーパーの惣菜で済ませると600〜800円で新潟らしい食事ができる。夕食だけ専門店に行くとメリハリのある予算配分になる。" },
    ],
    relatedArticleSlugs: ["niigata-hegisoba-guide", "niigata-sake-tasting-tour"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "niigata-luxury-onsen-stay",
    title: "新潟の高級温泉宿──月岡・岩室・松之山に泊まる越後の贅沢",
    description: "新潟には隠れた名湯が複数ある。日本酒と地の食材と温泉が揃う、越後の贅沢な宿泊体験。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "niigata",
    tags: ["高級旅館", "温泉", "月岡温泉", "岩室温泉", "贅沢旅"],
    spotIds: ["yahiko-shrine"],
    sections: [
      { type: "heading", content: "月岡温泉──美人の湯と青緑の硫黄泉", level: 2 },
      { type: "text", content: "新発田市の月岡温泉は、硫黄成分が豊富な青みがかった湯色が特徴の温泉地だ。「美人の湯」として知られ、肌がすべすべになる泉質は入浴後も実感できる。温泉街の外湯「美人の湯・しらさぎ荘」は日帰りでも入浴でき、周囲には洒落たカフェや甘味処も整備されている。" },
      { type: "heading", content: "岩室温泉──弥彦神社に最も近い宿場の湯", level: 2 },
      { type: "text", content: "弥彦神社の門前温泉として栄えた岩室温泉は、小規模ながら品のある旅館が揃う。越後の食材を贅沢に使った懐石料理は、どの宿でも地物の鮮魚と地酒を軸に構成されている。弥彦神社の早朝参拝を翌朝に設定して前泊すると、旅の密度が上がる。" },
      { type: "heading", content: "松之山温泉──秘湯指定の濃厚な塩化物泉", level: 2 },
      { type: "text", content: "十日町市の松之山温泉は「日本三大薬湯」に数えられ、塩化物濃度が極めて高い濃厚な湯が特徴だ。清津峡と合わせて1泊2日のルートに組み込みやすく、清津峡訪問後に松之山温泉に宿泊する動線が自然だ。周囲は棚田と山里が続き、夜の静けさが本物の秘湯感を演出する。" },
    ],
    relatedArticleSlugs: ["niigata-sake-tasting-tour", "niigata-couple-date-plan"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "niigata-tokamachi-art-field",
    title: "大地の芸術祭──十日町・津南の棚田とアートを歩く旅",
    description: "3年に一度、越後の里山に現代アートが出現する。アーティゾンだけじゃない「場所そのものが作品」の体験。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "niigata",
    tags: ["大地の芸術祭", "十日町", "現代アート", "棚田", "里山"],
    spotIds: ["kiyotsu-gorge"],
    sections: [
      { type: "heading", content: "里山アートの始まり──農業と芸術の接点", level: 2 },
      { type: "text", content: "大地の芸術祭（越後妻有アートトリエンナーレ）は2000年から3年ごとに開催される国際芸術祭だ。廃校・空き家・棚田・山道がアーティストの作品舞台となり、鑑賞者は「作品を見に行く」というより「里山を歩きながら作品と出会う」感覚で旅をする。" },
      { type: "heading", content: "「Tunnel of Light」以外の必見作品", level: 2 },
      { type: "text", content: "清津峡の「Tunnel of Light」は最も有名だが、他にも見逃せない作品がある。廃校を改築した「まつだい農舞台」のコレクション、田んぼの中に立つ「棚田」をテーマにした複数のインスタレーション、深い森の中にひっそりと置かれた彫刻群など、車で回らないと見つけられない作品も多い。" },
      { type: "heading", content: "レンタカーが必須──1日で効率よく回るルート", level: 2 },
      { type: "text", content: "大地の芸術祭の作品は広大なエリアに散在しているため、レンタカーが必須だ。越後湯沢駅か十日町駅でレンタカーを借り、清津峡→農舞台→津南エリアの順に回ると1日で主要作品を網羅できる。作品数が多いため、事前にパスポートチケット（全作品共通券）を購入しておくこと。" },
    ],
    relatedArticleSlugs: ["niigata-kiyotsu-gorge-art", "niigata-solo-countryside-walk"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "niigata-winter-seafood",
    title: "新潟の冬の食──寒ブリ・カニ・牡蠣、日本海の冬の幸を食べ尽くす",
    description: "冬の日本海は荒れる。しかし海が荒れるほど魚は旨くなる。新潟の冬にしか食べられないものがある。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "niigata",
    tags: ["冬グルメ", "寒ブリ", "カニ", "牡蠣", "新潟冬"],
    spotIds: ["yahiko-shrine"],
    sections: [
      { type: "heading", content: "寒ブリ──12月〜2月が最も脂がのる", level: 2 },
      { type: "text", content: "新潟の冬の主役はブリだ。日本海を回遊する天然ブリは12月を過ぎると脂肪を蓄え、刺身にするとトロのような甘みが出る。糸魚川・出雲崎の漁港近くの食堂では、朝獲れのブリが昼に刺身として出てくる。鮮度が違うという言葉の意味が、一口目でわかる。" },
      { type: "heading", content: "越後の岩牡蠣は夏が旬──冬は真牡蠣が主役", level: 2 },
      { type: "text", content: "新潟沿岸で養殖される真牡蠣は11月〜3月が旬だ。粒が大きく、ミルキーな甘みが特徴。牡蠣小屋型の施設が各漁港に出現し、炭火焼きで食べると磯の香りと旨みが一体になる。日本酒との相性が抜群で、地酒と牡蠣のセットは新潟の冬旅の定番だ。" },
      { type: "heading", content: "越後湯沢でスキーと海の幸を同時に楽しむ", level: 2 },
      { type: "text", content: "越後湯沢では雪山スキーと日本海の魚介を同じ週末に楽しめる。宿泊する旅館で地元の鮮魚を使った懐石料理を頼むと、一日中スキーで疲れた体に日本酒と海の幸が染みる。雪国の冬が「寒いだけ」ではなく「食が豊かな季節」だと実感できる旅だ。" },
    ],
    relatedArticleSlugs: ["niigata-ski-resort-guide", "niigata-sake-tasting-tour"],
  },
];
