import { Article } from "@/types/article";

export const okayamaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "okayama-kurashiki-bikan-morning",
    title: "倉敷美観地区、朝8時の歩き方──白壁に人影がない時間",
    description: "倉敷美観地区は夕方が美しいと言われるが、朝8時前後はさらに人が少ない。白壁と柳と静寂が重なる早朝の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-08",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okayama",
    tags: ["倉敷美観地区", "早朝", "白壁", "倉敷", "岡山"],
    spotIds: ["kurashiki-bikan"],
    sections: [
      { type: "heading", content: "8時前後は川舟も動かず人もいない", level: 2 },
      { type: "text", content: "倉敷川の川舟流しが動き始めるのは午前9時。その前の1時間は、白壁と柳が静水面に映る美観地区本来の顔を独占できる時間だ。JR倉敷駅から徒歩15分でアクセスできるため、宿泊せず早朝の新幹線で来た場合でも十分に間に合う。" },
      { type: "spot-card", content: "kurashiki-bikan" },
      { type: "heading", content: "大原美術館の前で光の変化を待つ", level: 2 },
      { type: "text", content: "大原美術館の正面玄関前の広場は、朝の光が斜めに差し込む時間帯に柱の陰影が美しくなる。美術館の開館は9時だが、外観の撮影なら早朝から可能だ。エル・グレコやモネの名画に会う前に、建物そのものを鑑賞する時間を持つとよい。" },
      { type: "heading", content: "川舟流しは平日開館直後がベスト", level: 2 },
      { type: "text", content: "川舟流しは定員制で混雑すると待ち時間が生じる。平日の9時台は最も空いており、船頭さんのガイドを独占に近い状態で聞ける。白壁を水面から見上げる視点は、地上から歩いて見るのとは全く異なる美観地区の側面を教えてくれる。" },
    ],
    relatedArticleSlugs: ["okayama-kurashiki-ivy-square", "okayama-korakuen-garden"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "okayama-kurashiki-ivy-square",
    title: "倉敷アイビースクエア──紡績工場の煉瓦と蔦が作る空間",
    description: "明治時代の紡績工場を再活用した倉敷アイビースクエアは、美観地区の中でも特別な空気感を持つ場所だ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "okayama",
    tags: ["アイビースクエア", "倉敷", "煉瓦", "産業遺産", "岡山"],
    spotIds: ["kurashiki-bikan"],
    sections: [
      { type: "heading", content: "煉瓦の壁を覆うツタが秋に赤く染まる", level: 2 },
      { type: "text", content: "倉敷アイビースクエアは1888年創業の倉敷紡績発祥の工場を、1974年にホテル・商業施設へ転換した複合施設だ。赤煉瓦の建物を覆うツタ（アイビー）は秋に真紅に染まり、その景観が施設名の由来になっている。" },
      { type: "heading", content: "倉紡記念館で産業の歴史を学ぶ", level: 2 },
      { type: "text", content: "施設内の「倉紡記念館」では倉敷紡績の歴史と明治〜昭和の繊維産業を展示している。職工の生活・労働条件・工場設備などが詳細に記録されており、美観地区の経済的背景を理解するために役立つ内容だ。" },
      { type: "heading", content: "中庭でコーヒーを飲む時間", level: 2 },
      { type: "text", content: "アイビースクエアの中庭には複数のカフェが出店しており、煉瓦と緑に囲まれた空間でコーヒーを飲める。美観地区の混雑した商店街から離れて、ここで休憩する時間は旅の密度を上げてくれる。" },
    ],
    relatedArticleSlugs: ["okayama-kurashiki-bikan-morning", "okayama-jeans-street"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "okayama-korakuen-garden",
    title: "後楽園の四季──日本三名園の正しい楽しみ方",
    description: "後楽園は季節ごとに全く違う庭園になる。梅・桜・紅葉・雪景色と、それぞれのベストシーズンを整理した。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okayama",
    tags: ["後楽園", "日本三名園", "庭園", "桜", "岡山"],
    spotIds: ["korakuen"],
    sections: [
      { type: "heading", content: "春は梅と桜を1ヶ月で楽しめる", level: 2 },
      { type: "text", content: "後楽園の春は2月下旬の梅から始まり、4月上旬の桜まで続く。梅林・八重桜・芝桜と段階的に花が変わるため、1ヶ月の間に何度来ても違う顔が見られる。岡山城との組み合わせで撮影できる桜の景色は岡山を代表する春の光景だ。" },
      { type: "spot-card", content: "korakuen" },
      { type: "heading", content: "放し飼いの鶴は朝が行動的", level: 2 },
      { type: "text", content: "後楽園では国特別天然記念物のタンチョウが放し飼いにされている。午前中は芝生の上を歩き回ることが多く、至近距離で見られるチャンスがある。鶴と岡山城の天守が同一画角に収まる写真は後楽園でしか撮れない特別な1枚だ。" },
      { type: "heading", content: "秋のライトアップは幻想的", level: 2 },
      { type: "text", content: "紅葉シーズン（11月）の週末に行われる後楽園のライトアップは、岡山の秋の風物詩。昼間とは全く異なる照明に照らされた庭園は幻想的で、入園料は昼間と同額。閉園まで粘って見る価値がある。" },
    ],
    relatedArticleSlugs: ["okayama-castle-walk", "okayama-kurashiki-bikan-morning"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "okayama-castle-walk",
    title: "岡山城（烏城）の歩き方──黒い天守と後楽園を結ぶ旭川の視点",
    description: "「烏城」の異名を持つ黒い岡山城。後楽園との橋渡しルートと、最上階から見る後楽園の絶景を解説する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okayama",
    tags: ["岡山城", "烏城", "後楽園", "岡山", "歴史"],
    spotIds: ["okayama-castle", "korakuen"],
    sections: [
      { type: "heading", content: "旭川越しの岡山城──黒と緑のコントラスト", level: 2 },
      { type: "text", content: "後楽園を出て旭川に架かる橋を渡ると岡山城に着く。橋の上から川越しに見上げる黒い天守は、後楽園の緑と対比されて絵になる。朝の光が川面に反射する時間帯が最も美しく、写真撮影のゴールデンタイムは開園直後だ。" },
      { type: "heading", content: "天守最上階からの後楽園俯瞰", level: 2 },
      { type: "text", content: "岡山城天守の最上階に上ると、眼下に後楽園の全体が見渡せる。日本三名園の庭園を上から見る体験は、後楽園の内部を歩くのとは異なる理解を与えてくれる。特に芝生の緑と延養亭の屋根の組み合わせが俯瞰で美しい。" },
      { type: "heading", content: "2022年リニューアル後の展示は体験型", level: 2 },
      { type: "text", content: "岡山城は2022年のリニューアルで展示が体験型に刷新された。甲冑の着用体験・VRによる江戸時代の城下の再現など、従来の歴史資料展示とは別の楽しみ方が追加されている。子連れやデジタルコンテンツに興味がある旅行者にも対応している。" },
    ],
    relatedArticleSlugs: ["okayama-korakuen-garden", "okayama-kibidango"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "okayama-seto-ohashi-view",
    title: "瀬戸大橋を鷲羽山から見る──夕景と夜景のベストポジション",
    description: "瀬戸大橋の最高の眺め場所は鷲羽山展望台だ。夕日から夜景への変化を追う1時間の撮影ガイド。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "okayama",
    tags: ["瀬戸大橋", "鷲羽山", "夕景", "夜景", "岡山"],
    spotIds: ["seto-ohashi"],
    sections: [
      { type: "heading", content: "鷲羽山展望台へのアクセス", level: 2 },
      { type: "text", content: "JR児島駅からバスで「鷲羽山展望台」バス停まで約20分。バス停から展望台まで急坂を5分ほど歩く。車の場合は鷲羽山スカイラインを使うと展望台直近まで上れる。夕日の鑑賞を目的とするなら日没60分前には展望台に着くこと。" },
      { type: "spot-card", content: "seto-ohashi" },
      { type: "heading", content: "日没後20分が最も橋が美しく見える", level: 2 },
      { type: "text", content: "瀬戸大橋のライトアップは日没後に点灯する。日没の瞬間よりも、空が紺色に変わり始めた日没後20〜30分の「ブルーアワー」に橋のライトアップが最も映える。三脚を持参して長時間露光撮影すると、橋と水面の光の軌跡が美しく写る。" },
      { type: "heading", content: "冬の夜景は空気が澄んで遠くまで見える", level: 2 },
      { type: "text", content: "12〜2月の乾燥した空気の日は視界が特に澄んでいる。橋を渡った先の四国・坂出市の街明かりまで鮮明に見え、瀬戸内の多島美と都市の灯りが混在する景観が現れる。寒さ対策を十分にして来ること。" },
    ],
    relatedArticleSlugs: ["okayama-jeans-street", "okayama-kurashiki-bikan-morning"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "okayama-jeans-street",
    title: "児島ジーンズ街──日本のデニム発祥地で本物の1本を選ぶ",
    description: "岡山県倉敷市児島は日本のジーンズ発祥の地。ジーンズストリートで自分に合うデニムを探す旅の楽しさ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okayama",
    tags: ["児島ジーンズ", "デニム", "児島", "ショッピング", "岡山"],
    spotIds: ["seto-ohashi"],
    sections: [
      { type: "heading", content: "日本製デニムが児島から生まれた理由", level: 2 },
      { type: "text", content: "児島は戦後の繊維産業で学生服・足袋の生産拠点として発展し、その技術基盤を活かして1960年代に日本初のジーンズ生産を始めた。現在もBIG JOHN・BOB SON・JAPAN BLUEなどの国内ブランドが児島で生産を続けており、メイドインジャパンのデニムの聖地だ。" },
      { type: "heading", content: "ジーンズストリートの歩き方", level: 2 },
      { type: "text", content: "JR児島駅から徒歩約10分の「ジーンズストリート」は、約10店舗のデニムショップが並ぶ通りだ。各店でシルエット・生地・洗い加工の違いを試着しながら比較できる。ファクトリーブランドの直販店では工場から直接仕入れた価格で購入できるため、品質に比して割安感がある。" },
      { type: "heading", content: "オーダーメイドデニムという選択肢", level: 2 },
      { type: "text", content: "児島の一部のショップでは股下・ウエスト・シルエットを指定したオーダーメイドに対応している。納期は通常3〜4週間かかるが、旅行の記念として世界に1本だけの日本製デニムを作る体験は、児島でしかできない。" },
    ],
    relatedArticleSlugs: ["okayama-seto-ohashi-view", "okayama-kurashiki-bikan-morning"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "okayama-kibidango",
    title: "きびだんごと岡山グルメ──桃太郎の土産だけじゃない食の奥深さ",
    description: "きびだんごは岡山の顔だが、岡山の食文化はもっと幅広い。バラ寿司・えびめし・デミカツとグルメの全体像。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okayama",
    tags: ["きびだんご", "岡山グルメ", "バラ寿司", "えびめし", "岡山"],
    spotIds: [],
    sections: [
      { type: "heading", content: "きびだんごの正しい選び方", level: 2 },
      { type: "text", content: "岡山の「きびだんご」は本来きびを練り込んだ餅菓子だが、現在は白玉系のやわらかい餅に変化したものが主流だ。土産として選ぶなら廣榮堂の「元祖きびだんご」が最も歴史があり、きびの香りが強い。JR岡山駅構内でも購入できる。" },
      { type: "heading", content: "バラ寿司──祭り寿司の豪快さ", level: 2 },
      { type: "text", content: "岡山のバラ寿司（祭り寿司）は、酢飯の上に焼き穴子・エビ・錦糸卵・蓮根・山菜などを豪快に盛り込んだ押し寿司スタイルだ。江戸時代に倹約令への反発として「華美でなく見えるが中は豪華」という逆転の発想で生まれたという逸話がある。" },
      { type: "heading", content: "えびめしとデミカツ──岡山のソウルフード", level: 2 },
      { type: "text", content: "「えびめし」は黒いデミグラスソースで炒めた焼き飯で、岡山市内の老舗洋食店の名物。「デミカツ」はカツにデミグラスソースをかけた岡山式カツ料理。どちらも岡山市内の食堂・洋食屋で食べられる個性的なローカルフードだ。" },
    ],
    relatedArticleSlugs: ["okayama-castle-walk", "okayama-korakuen-garden"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "okayama-kurashiki-oohara-museum",
    title: "大原美術館の歩き方──地方美術館の概念を超える倉敷の宝庫",
    description: "大原美術館はモネ・マネ・エル・グレコを所蔵する地方美術館を超えた存在だ。3つの棟の見方と絵の選び方を解説する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "okayama",
    tags: ["大原美術館", "西洋絵画", "倉敷", "美術", "岡山"],
    spotIds: ["kurashiki-bikan"],
    sections: [
      { type: "heading", content: "本館のエル・グレコから始める", level: 2 },
      { type: "text", content: "大原美術館の本館入口を入ると最初に迎えるのがエル・グレコの「受胎告知」だ。16世紀スペインの巨匠による縦2mを超える大作が地方美術館に所蔵されている事実は、初めて訪れる人を驚かせる。モネの「睡蓮」はその奥に控えており、本館だけで2時間は必要だ。" },
      { type: "heading", content: "工芸・東洋館まで歩く覚悟を持つ", level: 2 },
      { type: "text", content: "大原美術館は本館・分館・工芸・東洋館の4棟から構成される。体力的に全部回ると3〜4時間かかる。工芸館では濱田庄司・河井寬次郎ら民芸運動の巨匠の作品が充実しており、西洋絵画とは異なる深みがある。" },
      { type: "heading", content: "開館時間と混雑パターン", level: 2 },
      { type: "text", content: "大原美術館は9時開館で月曜休館。週末の11時以降は団体客が増えるため、平日の開館直後が最もゆっくり鑑賞できる。入館料（1,500円）は倉敷観光としての価値から見れば圧倒的にコストパフォーマンスが高い。" },
    ],
    relatedArticleSlugs: ["okayama-kurashiki-bikan-morning", "okayama-kurashiki-ivy-square"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "okayama-washi-mountain",
    title: "鷲羽山の自然と瀬戸内海──橋を渡らず山から眺める多島美",
    description: "鷲羽山は展望台だけではない。山全体のハイキングコースから見る瀬戸内海の多島美は、橋の景色を超える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "okayama",
    tags: ["鷲羽山", "瀬戸内海", "多島美", "ハイキング", "岡山"],
    spotIds: ["seto-ohashi"],
    sections: [
      { type: "heading", content: "鷲羽山ハイキングコースは約90分", level: 2 },
      { type: "text", content: "鷲羽山には頂上（標高133m）を経由するハイキングコースが整備されている。JR児島駅から登山口まで徒歩15分、頂上まで約40分。稜線から見える瀬戸内の島々の重なりは、展望台からとは異なるアングルで迫る。" },
      { type: "heading", content: "頂上から見る橋と島の重なり方", level: 2 },
      { type: "text", content: "鷲羽山の頂上は展望台より高い位置にあり、瀬戸大橋の全体と奥の四国の山並みが見渡せる。橋と島と海の三つが重なる構図は、この頂上からしか見えないアングルだ。風が穏やかな春と秋が最も視界が澄んでいる。" },
      { type: "heading", content: "下山後は児島の塩業の歴史を訪ねる", level: 2 },
      { type: "text", content: "鷲羽山の麓に広がる児島湾干拓地は、近代の塩田干拓の歴史を持つ。野崎家旧宅（野崎武左衛門別邸）は塩業で財を成した豪商の邸宅で、国の重要文化財に指定されている。鷲羽山とセットで訪問すると児島の歴史が立体的に見えてくる。" },
    ],
    relatedArticleSlugs: ["okayama-seto-ohashi-view", "okayama-jeans-street"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "okayama-city-tram",
    title: "路面電車で岡山市内を半日巡る──後楽園・岡山城・表町商店街",
    description: "岡山市内の観光は路面電車が便利だ。後楽園・岡山城・表町商店街を半日でつなぐ路面電車活用術。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-28",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "okayama",
    tags: ["路面電車", "岡山市内", "後楽園", "岡山城", "岡山"],
    spotIds: ["korakuen", "okayama-castle"],
    sections: [
      { type: "heading", content: "路面電車の1日乗車券は400円", level: 2 },
      { type: "text", content: "岡山電気軌道の1日フリー乗車券は400円（大人）。後楽園・岡山城・表町商店街を往復するだけで元が取れる計算になる。乗り換えなしでJR岡山駅から後楽園前まで約12分と、意外と速い移動手段だ。" },
      { type: "heading", content: "表町商店街──岡山最大のアーケード", level: 2 },
      { type: "text", content: "後楽園・岡山城の観光後、路面電車で「城下」電停に戻ると目の前に表町商店街のアーケードが始まる。岡山最大の商店街で、地元の老舗・カフェ・飲食店が混在している。観光地の土産物屋よりも地元密度が高く、岡山の日常を覗ける場所だ。" },
      { type: "heading", content: "夕方は岡山駅周辺のグルメで締める", level: 2 },
      { type: "text", content: "岡山駅周辺にはえびめし・デミカツ・バラ寿司の専門店・地産品を扱う料理屋が集まっている。路面電車の最終電車はJR岡山駅まで深夜近くまで走るため、夕食後も焦らず帰れる。" },
    ],
    relatedArticleSlugs: ["okayama-korakuen-garden", "okayama-castle-walk"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "okayama-kibi-cycling",
    title: "吉備路サイクリング──古代吉備王国の遺跡を自転車でたどる",
    description: "岡山市郊外の吉備路は、古代吉備王国の遺跡が田園の中に点在する国内屈指の自転車ルートだ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okayama",
    tags: ["吉備路", "サイクリング", "古墳", "備中国分寺", "岡山"],
    spotIds: [],
    sections: [
      { type: "heading", content: "備中国分寺の五重塔から始める", level: 2 },
      { type: "text", content: "吉備路サイクリングの起点はJR総社駅または吉備津駅。田んぼの中に突如現れる備中国分寺の五重塔は、菜の花や彼岸花と組み合わさった景観が有名だ。自転車を借りてここからルートを組むのが最もスムーズだ。" },
      { type: "heading", content: "造山古墳──全国4位の巨大前方後円墳", level: 2 },
      { type: "text", content: "吉備路ルートの途中にある造山古墳は墳丘長350mで全国第4位の規模を誇る。しかもほとんど整備されておらず、立ち入りが自由という稀有な古墳だ。丘に登ると吉備平野が360度見渡せ、古代の権力者がなぜここを選んだか理解できる。" },
      { type: "heading", content: "吉備津神社で旅の安全を祈る", level: 2 },
      { type: "text", content: "吉備路の終点に近い吉備津神社は、桃太郎伝説の鬼・温羅を退治した吉備津彦命を祀る大社だ。全長360mの廻廊（回廊）は国の重要文化財で、その連なりを歩く体験だけでも吉備路を訪れる価値がある。" },
    ],
    relatedArticleSlugs: ["okayama-castle-walk", "okayama-korakuen-garden"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "okayama-ohashi-day-trip",
    title: "瀬戸大橋を渡る旅──岡山側から四国を日帰りする",
    description: "瀬戸大橋を渡って四国・坂出へ。岡山からの日帰りで丸亀城・金比羅さんを組み合わせる最短ルート。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okayama",
    tags: ["瀬戸大橋", "日帰り", "四国", "丸亀城", "岡山"],
    spotIds: ["seto-ohashi"],
    sections: [
      { type: "heading", content: "マリンライナーで40分、橋の上を走る", level: 2 },
      { type: "text", content: "JR岡山駅から快速マリンライナーに乗ると、瀬戸大橋の上を走りながら四国・坂出駅まで約40分で到着する。2階建て車両の最前席を事前予約すると、橋から見える瀬戸内の島々を真正面に眺めながら渡れる。" },
      { type: "heading", content: "丸亀城と丸亀うちわ", level: 2 },
      { type: "text", content: "坂出から乗り換えて丸亀駅へ。日本に12しかない現存天守のひとつ・丸亀城の石垣は「扇の勾配」と呼ばれる反り上がりが特徴的で、城郭マニアに特に人気が高い。丸亀市は全国シェア9割を誇る丸亀うちわの産地でもあり、工房見学も可能だ。" },
      { type: "heading", content: "琴平の金比羅さんで785段の石段を上る", level: 2 },
      { type: "text", content: "丸亀から琴平へ移動し、金刀比羅宮の石段を上る。本宮まで785段、奥社まで1,368段の石段は、脚力のある人には奥社まで行ってほしい。讃岐平野を見渡す景色と達成感が待っている。帰りは琴電・JR経由で岡山へ戻る。" },
    ],
    relatedArticleSlugs: ["okayama-seto-ohashi-view", "okayama-jeans-street"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "okayama-muscat-grape",
    title: "マスカット・オブ・アレキサンドリア──岡山の白ぶどうを農園で食べる",
    description: "岡山はマスカット・オブ・アレキサンドリアの産地。農園直売と観光農業で出会う特別なぶどう体験。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okayama",
    tags: ["マスカット", "ぶどう", "農園", "フルーツ", "岡山"],
    spotIds: [],
    sections: [
      { type: "heading", content: "マスカット・オブ・アレキサンドリアとは", level: 2 },
      { type: "text", content: "岡山を代表するぶどう「マスカット・オブ・アレキサンドリア」は、大粒で緑色の薄皮から透ける果肉が特徴。甘みと酸味のバランスが繊細で、一般的なぶどうと全く異なる高貴な香りを持つ。8月〜9月が収穫の最盛期だ。" },
      { type: "heading", content: "岡山市北区の農園地帯を訪れる", level: 2 },
      { type: "text", content: "岡山市北区の高松・御津エリアには農園が集中しており、直売所での販売や農園見学ができる場所がある。一般の観光客が立ち寄れる農園は事前に問い合わせが必要な場合が多いが、道の駅での直売は手軽に利用できる。" },
      { type: "heading", content: "桃・ピオーネとの食べ比べセット", level: 2 },
      { type: "text", content: "岡山は桃（白桃）・マスカット・ピオーネ（黒ぶどう）の三種が名産で、夏〜秋はこれらを組み合わせた食べ比べセットを道の駅や農産物直売所で購入できる。1箱に3種類が入ったギフトセットは岡山みやげとしての完成度が高い。" },
    ],
    relatedArticleSlugs: ["okayama-kibidango", "okayama-korakuen-garden"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "okayama-kurashiki-night",
    title: "倉敷美観地区の夜──ライトアップで白壁が黄金色に変わる時間",
    description: "倉敷美観地区の夜は昼間と全く別の顔を見せる。川面に映る灯りと白壁のシルエットは、日本の夜景の中でも特別な美しさを持つ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "okayama",
    tags: ["倉敷美観地区", "夜景", "ライトアップ", "倉敷川", "岡山"],
    spotIds: ["kurashiki-bikan"],
    sections: [
      { type: "heading", content: "ライトアップは日没後に自動点灯", level: 2 },
      { type: "text", content: "倉敷美観地区のライトアップは季節によって点灯時間が変わるが、日没後から23時頃まで自動点灯している。冬は17時台から点灯するため、夕方の観光と夜景を同日に楽しみやすい。" },
      { type: "heading", content: "倉敷川沿いの橋から撮影する", level: 2 },
      { type: "text", content: "ライトアップされた白壁と柳の木が川面に映る景観は、倉敷川に架かる各橋の上から見るのが最も美しい。カメラを三脚に固定して長時間露光撮影すると、流れる水の表情と橋の灯りが合わさった絵が撮れる。" },
      { type: "heading", content: "夜の大原美術館外観を鑑賞する", level: 2 },
      { type: "text", content: "大原美術館は夜間開館していないが、外観はライトアップされている。昼間とは異なるスポットライトが当たった正面ファサードの表情を、夜に改めて見ると建物の立体感が増す。倉敷川の夜景散歩の最後に立ち寄ってほしい場所だ。" },
    ],
    relatedArticleSlugs: ["okayama-kurashiki-bikan-morning", "okayama-kurashiki-oohara-museum"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "okayama-family-model-course",
    title: "岡山子連れ旅──後楽園・岡山城・きびだんご体験の2日間",
    description: "小学生の子どもと行く岡山旅行のモデルコース。鶴を見て城を体験して、桃太郎伝説を学ぶ2日間の完全プラン。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-20",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "okayama",
    tags: ["岡山", "子連れ旅行", "後楽園", "岡山城", "家族"],
    spotIds: ["korakuen", "okayama-castle"],
    sections: [
      { type: "heading", content: "1日目：後楽園で鶴を見て岡山城へ", level: 2 },
      { type: "text", content: "午前中は後楽園でタンチョウを探す。子どもは鶴を目指して園内を走り回るため、自然に庭園全体を歩き回ることになる。昼食は後楽園内の茶店で鯉料理や地元弁当。午後は旭川を渡って岡山城へ。体験型展示で甲冑を着る体験が子どもに人気だ。" },
      { type: "heading", content: "1日目夜：表町商店街で岡山グルメ", level: 2 },
      { type: "text", content: "路面電車で表町商店街へ移動し、夕食はデミカツ丼またはえびめし。子ども向けのメニューがある洋食屋で岡山のソウルフードを体験する。アーケード内の商店街を歩きながら、きびだんごの老舗で夜の甘味を買う。" },
      { type: "heading", content: "2日目：吉備路自転車と倉敷美観地区", level: 2 },
      { type: "text", content: "2日目午前は吉備路でレンタサイクル（子ども用も貸し出しあり）。備中国分寺の五重塔と古墳を巡る。午後は倉敷へ移動して美観地区。大原美術館は小学生以下無料のため、子ども連れには特にコストパフォーマンスが高い施設だ。" },
    ],
    relatedArticleSlugs: ["okayama-korakuen-garden", "okayama-castle-walk"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "okayama-luxury-stay",
    title: "岡山・倉敷の贅沢な一泊──美術館と美観地区に隣接した宿を選ぶ",
    description: "倉敷の旅を最大化するには美観地区内または隣接エリアへの宿泊が最善だ。朝夕の人のいない美観地区を独占できる。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-11-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "okayama",
    tags: ["倉敷", "高級宿", "美観地区", "贅沢旅行", "岡山"],
    spotIds: ["kurashiki-bikan"],
    sections: [
      { type: "heading", content: "美観地区内に泊まれる旅館とは", level: 2 },
      { type: "text", content: "倉敷美観地区内には老舗旅館「旅館くらしき」がある。江戸時代の米倉を改装した客室は、白壁と倉敷川が見えるロケーション。朝食前に誰もいない美観地区を歩く体験は、この宿に泊まった人だけが手に入れられる記憶だ。" },
      { type: "heading", content: "大原美術館チケット付きプランを活用", level: 2 },
      { type: "text", content: "倉敷周辺の一部旅館では大原美術館のチケット付き宿泊プランを提供している。閉館後の美術館への特別入館が付いているプランもあり、通常の営業時間では感じられない静寂の中で名画と向き合える特別な体験になる。" },
      { type: "heading", content: "チェックアウト後の早朝美観地区が真の贅沢", level: 2 },
      { type: "text", content: "美観地区内または隣接旅館に泊まると、朝6時台に散歩できる。川舟も観光客もなく、白壁と朝霧だけが広がる時間帯は倉敷観光の本質だ。この時間のために一泊する価値がある。" },
    ],
    relatedArticleSlugs: ["okayama-kurashiki-bikan-morning", "okayama-kurashiki-oohara-museum"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "okayama-momotaro-legend",
    title: "桃太郎伝説の舞台をたどる──鬼ノ城と吉備津神社の鬼退治ルート",
    description: "岡山は桃太郎のモデルとなった伝説が残る場所だ。鬼が立て籠もったとされる「鬼ノ城」から物語の地を歩く。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okayama",
    tags: ["桃太郎", "鬼ノ城", "吉備津神社", "伝説", "岡山"],
    spotIds: [],
    sections: [
      { type: "heading", content: "鬼ノ城──古代山城の遺構が残る鬼の拠点", level: 2 },
      { type: "text", content: "総社市の山中にある「鬼ノ城（きのじょう）」は、7世紀に築かれた古代山城の遺構だ。鬼が住んでいたという伝説の地で、城壁・水門・展望台の復元が進む。総社市街からシャトルバスでアクセス可能。山城の石積みと吉備平野の眺めが心に刻まれる。" },
      { type: "heading", content: "吉備津神社の廻廊と鳴釜神事", level: 2 },
      { type: "text", content: "桃太郎のモデルとされる吉備津彦命を祀る吉備津神社は、全長360mの廻廊が有名だ。釜の音で吉凶を占う「鳴釜神事（なりかましんじ）」は現在も行われており、事前に申し込めば見学できる。吉備路サイクリングと組み合わせて訪問するのが効率的だ。" },
      { type: "heading", content: "桃太郎ミュージアムで伝説の全体像を把握", level: 2 },
      { type: "text", content: "岡山市北区にある「岡山桃太郎ミュージアム」では桃太郎伝説と吉備の歴史を分かりやすく展示している。子ども向けの展示だが、大人が見ても岡山の地域史に新しい視点が加わる内容だ。吉備路観光の入門として活用できる。" },
    ],
    relatedArticleSlugs: ["okayama-kibi-cycling", "okayama-kibidango"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "okayama-korakuen-night",
    title: "後楽園ライトアップ──秋の幻想的な夜間開園に立ち入る",
    description: "後楽園の紅葉期ライトアップは年に数週間しか開催されない。岡山の秋の夜を最高密度で過ごす方法。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-11-08",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okayama",
    tags: ["後楽園", "ライトアップ", "紅葉", "夜間開園", "岡山"],
    spotIds: ["korakuen"],
    sections: [
      { type: "heading", content: "ライトアップ期間は11月上旬〜下旬の約3週間", level: 2 },
      { type: "text", content: "後楽園の秋の夜間ライトアップは通常11月上旬から下旬にかけての限定期間に開催される。入園料は通常の昼間と同額（410円）で、夕方から夜間の特別な庭園を歩ける。開催日程は公式サイトで確認が必要だ。" },
      { type: "heading", content: "ライトアップで浮かび上がる紅葉の色", level: 2 },
      { type: "text", content: "夜間照明に照らされた後楽園の紅葉は、昼間とは全く異なる鮮烈な赤と橙に変化する。池の水面に映る紅葉のリフレクションは、夜間ならではの景観だ。三脚を持参して長時間露光撮影をすると、作品として成立する1枚が撮れる。" },
      { type: "heading", content: "岡山城のライトアップと組み合わせる", level: 2 },
      { type: "text", content: "後楽園ライトアップの帰りに旭川を渡って岡山城のライトアップも合わせて見ると、岡山の夜の観光が完結する。二つのライトアップを1時間で回れる距離感が岡山の好ポイントだ。夕食は後楽園近くの居酒屋で岡山の地酒と地鶏を楽しむ。" },
    ],
    relatedArticleSlugs: ["okayama-korakuen-garden", "okayama-castle-walk"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "okayama-kurashiki-craft",
    title: "倉敷の工芸品を選ぶ──倉敷帆布・い草・デニムの手仕事",
    description: "倉敷は土産物が充実している。倉敷帆布・い草・デニムと地場産業が生み出した本物の工芸品の選び方。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okayama",
    tags: ["倉敷帆布", "工芸品", "土産", "い草", "岡山"],
    spotIds: ["kurashiki-bikan"],
    sections: [
      { type: "heading", content: "倉敷帆布──綿100%のタフな日用品", level: 2 },
      { type: "text", content: "倉敷帆布は岡山県南部の綿花栽培と繊維産業を背景に発展した厚地の綿布。一反一反手作業で仕上げたトートバッグ・ポーチ・財布は使い込むほどに味が出る。美観地区内の「帆布の店」では職人が生地を選ぶところから一緒に考えてくれる。" },
      { type: "heading", content: "倉敷緞通──畳の上に敷く伝統手織りカーペット", level: 2 },
      { type: "text", content: "「倉敷緞通（くらしきだんつう）」は明治時代から続く手織りの敷物で、岡山特産のい草を使った織物産業の延長上にある。現在は職人の数が少なく希少品だが、美観地区周辺の工芸店で現物を見られる場合がある。" },
      { type: "heading", content: "児島デニムのアクセサリー", level: 2 },
      { type: "text", content: "児島ジーンズストリートでは端切れデニムを使ったアクセサリーも販売されている。デニム生地のキーホルダー・コースター・ブローチは手軽に買える土産で、倉敷帆布と組み合わせると岡山の繊維産業全体をギフトとして渡せる。" },
    ],
    relatedArticleSlugs: ["okayama-jeans-street", "okayama-kurashiki-bikan-morning"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "okayama-tomo-no-ura",
    title: "鞆の浦を岡山から日帰りする──瀬戸内の港町とジブリの聖地",
    description: "広島県福山市の鞆の浦は岡山から1時間。宮崎駿が「崖の上のポニョ」の着想を得た港町の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-09-30",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okayama",
    tags: ["鞆の浦", "瀬戸内", "日帰り", "港町", "岡山"],
    spotIds: [],
    sections: [
      { type: "heading", content: "岡山〜福山〜鞆の浦の移動は1時間半", level: 2 },
      { type: "text", content: "岡山駅から新幹線で福山駅（約20分）、福山駅からバスで鞆の浦まで約30分。合計1時間半でアクセスできる。日帰りでは少し駆け足になるが、午前中に出れば昼食と散策を組み合わせた充実した半日が作れる。" },
      { type: "heading", content: "常夜燈と雁木の港を歩く", level: 2 },
      { type: "text", content: "鞆の浦の港には江戸時代の「常夜燈」が現存しており、波止場の雁木（石段状の船着き場）も当時のまま使われている。ここが「崖の上のポニョ」のモデルになった港町で、古い漁師町の雰囲気は観光地化されながらもリアルな生活感が残っている。" },
      { type: "heading", content: "仙酔島への渡し船で島時間を過ごす", level: 2 },
      { type: "text", content: "鞆の浦の港から渡し船で5分の仙酔島は、江戸時代から「五色岩」と景色の美しさで知られる無人島だ。島内を30分ほど歩くと断崖の岩場や入り江が現れ、対岸の鞆の浦の町並みを海から眺められる。岡山からの日帰りにプラスαの価値がある。" },
    ],
    relatedArticleSlugs: ["okayama-seto-ohashi-view", "okayama-ohashi-day-trip"],
  },
];
