import { Article } from "@/types/article";

const img1 = "https://images.unsplash.com/photo-1590253230532-a67f6bc61b9e?w=1200&q=80";
const img2 = "https://images.unsplash.com/photo-1570789210967-2cac24afeb00?w=1200&q=80";
const img3 = "https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1200&q=80";

export const okinawaArticles: Article[] = [
  {
    slug: "okinawa-shurijo-castle-guide",
    title: "首里城完全ガイド｜琉球王国の栄華を体感する歴史散策",
    description: "世界遺産・首里城で琉球王国の壮大な歴史と鮮やかな朱色の建築美を堪能しましょう。",
    coverImage: img1,
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okinawa",
    tags: ["首里城", "世界遺産", "琉球王国", "那覇", "歴史"],
    spotIds: ["shurijo"],
    sections: [
      { type: "heading", content: "琉球王国の象徴・首里城", level: 2 },
      { type: "text", content: "首里城は沖縄を代表する世界遺産で、14〜19世紀に栄えた琉球王国の王城です。鮮やかな朱色と独特の建築様式は、中国と日本の文化が融合した琉球独自の美を体現しています。2019年の火災後、現在も復元工事が進む首里城は、再びその全貌を取り戻しつつあります。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "見どころと回り方", level: 2 },
      { type: "text", content: "守礼門から始まり、歓会門・瑞泉門と続く門めぐりが見どころ。正殿前の御庭では琉球舞踊の公演も行われます。所要時間は約1〜2時間。那覇市内からゆいレール「首里駅」から徒歩15分とアクセスも良好です。" },
    ],
    relatedArticleSlugs: ["okinawa-kokusai-dori-guide", "okinawa-sefa-utaki-power-spot"],
  },
  {
    slug: "okinawa-churaumi-aquarium-complete",
    title: "美ら海水族館完全攻略｜ジンベエザメと泳ぐ夢の海中世界",
    description: "世界最大級の水槽「黒潮の海」でジンベエザメが優雅に泳ぐ、沖縄随一の観光スポットを徹底解説。",
    coverImage: img2,
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "okinawa",
    tags: ["美ら海水族館", "ジンベエザメ", "本部町", "家族旅行", "水族館"],
    spotIds: ["churaumi-aquarium"],
    sections: [
      { type: "heading", content: "世界最大級の水槽が圧倒的", level: 2 },
      { type: "text", content: "沖縄美ら海水族館の「黒潮の海」水槽は、幅35m・高さ8.2mの巨大アクリルパネルで仕切られた世界最大級の水槽のひとつ。ジンベエザメやナンヨウマンタが悠々と泳ぐ光景は、まさに圧巻です。" },
      { type: "spot-card", content: "churaumi-aquarium" },
      { type: "heading", content: "周辺エリアも充実", level: 2 },
      { type: "text", content: "水族館を含む「海洋博公園」には、熱帯ドリームセンターやマナティー館、ウミガメ館なども併設。1日かけてじっくり楽しめます。那覇から車で約2時間、那覇空港からバスも運行しています。" },
    ],
    relatedArticleSlugs: ["okinawa-nakijin-castle-ruins", "okinawa-family-travel-guide"],
  },
  {
    slug: "okinawa-kokusai-dori-guide",
    title: "国際通り完全ガイド｜那覇の台所で食べ歩き&お土産探し",
    description: "沖縄最大の繁華街・国際通りで沖縄そば、ちんすこう、シーサーみやげを堪能する究極の散策ガイド。",
    coverImage: img3,
    publishedAt: "2025-02-14",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["国際通り", "那覇", "お土産", "食べ歩き", "ショッピング"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "奇跡の1マイル・国際通りを歩く", level: 2 },
      { type: "text", content: "戦後の焼け野原から急速に発展した国際通りは、約1.6kmにわたって飲食店・土産物店・ブランドショップが立ち並びます。沖縄を訪れたなら必ず足を運ぶべき那覇の中心地です。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "食べ歩きグルメと買い物スポット", level: 2 },
      { type: "text", content: "さっぱりとした沖縄そばや、揚げたてのサーターアンダーギー、塩ちんすこうは必食。牧志公設市場では沖縄独自の食材を見学・購入できます。シーサーややちむんなどの工芸品みやげも充実しています。" },
    ],
    relatedArticleSlugs: ["okinawa-soba-guide", "okinawa-shurijo-castle-guide"],
  },
  {
    slug: "okinawa-kouri-island-romantic",
    title: "古宇利島ロマンティックドライブ｜コバルトブルーの海を渡る橋",
    description: "古宇利大橋を渡る絶景ドライブと、沖縄版アダムとイブ伝説が息づく恋の島を満喫するカップル旅。",
    coverImage: img1,
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "okinawa",
    tags: ["古宇利島", "古宇利大橋", "ドライブ", "カップル", "絶景"],
    spotIds: ["kouri-island"],
    sections: [
      { type: "heading", content: "恋の島・古宇利島へ", level: 2 },
      { type: "text", content: "古宇利島は沖縄本島北部、今帰仁村に属する小さな離島。全長1960mの古宇利大橋からは、エメラルドグリーンの海が360度に広がる絶景が楽しめます。「沖縄版アダムとイブ」の伝説が残り、恋愛成就のパワースポットとしても人気です。" },
      { type: "spot-card", content: "kouri-island" },
      { type: "heading", content: "ハートロックと夕日鑑賞", level: 2 },
      { type: "text", content: "島の北岸にあるティーヌ浜には、ハート型の岩「ハートロック」があり、カップルに大人気。夕暮れ時には橋の上から沈む夕日を眺める絶景ドライブが格別。近くにはオシャレなカフェも点在しています。" },
    ],
    relatedArticleSlugs: ["okinawa-nakijin-castle-ruins", "okinawa-sunset-spot-guide"],
  },
  {
    slug: "okinawa-taketomi-island-cultural",
    title: "竹富島で過ごす1日｜水牛車と白砂の道に癒される石垣の島",
    description: "水牛車でゆったり巡る赤瓦屋根の集落と、コンドイビーチの透明な海に心洗われる竹富島の旅。",
    coverImage: img2,
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "okinawa",
    tags: ["竹富島", "水牛車", "石垣島", "離島", "伝統文化"],
    spotIds: ["taketomi-island"],
    sections: [
      { type: "heading", content: "時間が止まったような集落", level: 2 },
      { type: "text", content: "竹富島は石垣島から高速船で約10分の小さな離島。国の重要伝統的建造物群保存地区に選定された集落には、赤瓦屋根のサンゴ石垣が続き、沖縄の原風景が今も息づいています。" },
      { type: "spot-card", content: "taketomi-island" },
      { type: "heading", content: "水牛車と星空観察", level: 2 },
      { type: "text", content: "三線の音色に乗って集落を巡る水牛車観光は竹富島の定番体験。コンドイビーチの透明な浅瀬や、夜の満天の星空も見逃せません。日帰りもできますが、宿に泊まってゆったり過ごすのがおすすめです。" },
    ],
    relatedArticleSlugs: ["okinawa-ishigaki-island-guide", "okinawa-miyako-island-guide"],
  },
  {
    slug: "okinawa-manza-mo-cliff-walk",
    title: "万座毛の断崖絶壁｜象の鼻岩と紺碧の海が生む絶景散歩道",
    description: "沖縄本島随一の景勝地・万座毛で、象の形をした奇岩と広大なサンゴ礁の海を一望する爽快ウォーク。",
    coverImage: img3,
    publishedAt: "2025-07-08",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["万座毛", "絶景", "恩納村", "象の鼻岩", "ドライブ"],
    spotIds: ["manza-mo"],
    sections: [
      { type: "heading", content: "琉球石灰岩の絶景・万座毛", level: 2 },
      { type: "text", content: "万座毛は恩納村にある琉球石灰岩の断崖で、「万人が座れる毛（野原）」の意。象の鼻に似た奇岩が海に突き出し、眼下には真っ青なサンゴ礁が広がる沖縄有数の絶景スポットです。" },
      { type: "spot-card", content: "manza-mo" },
      { type: "heading", content: "整備された遊歩道で安全散策", level: 2 },
      { type: "text", content: "2021年にリニューアルされた万座毛では、整備された遊歩道を歩きながら断崖の絶景を楽しめます。周辺には物産センターも完備。夕日が海を染める夕暮れ時は特に美しく、フォトスポットとして人気です。" },
    ],
    relatedArticleSlugs: ["okinawa-sunset-spot-guide", "okinawa-kouri-island-romantic"],
  },
  {
    slug: "okinawa-zamami-island-diving",
    title: "座間味島ダイビング天国｜ケラマブルーの海で出会うウミガメ",
    description: "世界有数の透明度を誇るケラマ諸島・座間味島で、ウミガメと泳ぐ至福のダイビング体験を完全ガイド。",
    coverImage: img1,
    publishedAt: "2025-04-22",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["座間味島", "ダイビング", "ケラマ諸島", "ウミガメ", "離島"],
    spotIds: ["zamami-island"],
    sections: [
      { type: "heading", content: "ケラマブルーの海へ", level: 2 },
      { type: "text", content: "座間味島は那覇・泊港から高速船で約50分のケラマ諸島の島。「ケラマブルー」と呼ばれる透明度の高い海は、世界でもトップクラスのダイビングスポット。ウミガメに高確率で出会えることでも有名です。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "シュノーケルから本格ダイビングまで", level: 2 },
      { type: "text", content: "初心者向けの体験ダイビングから本格的なファンダイビングまで対応したショップが充実。2月〜4月にはザトウクジラの目撃情報も多く、ホエールウォッチングも楽しめます。島内には宿泊施設も複数あります。" },
    ],
    relatedArticleSlugs: ["okinawa-diving-guide", "okinawa-miyako-island-guide"],
  },
  {
    slug: "okinawa-sefa-utaki-power-spot",
    title: "斎場御嶽で感じる琉球の精神｜世界遺産の聖地を歩く",
    description: "琉球王国最高の聖地・斎場御嶽で、太古から続く信仰と神秘的な岩組の空間に心を洗われる旅。",
    coverImage: img2,
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["斎場御嶽", "世界遺産", "パワースポット", "南城市", "琉球信仰"],
    spotIds: ["sefa-utaki"],
    sections: [
      { type: "heading", content: "琉球最高の聖地へ", level: 2 },
      { type: "text", content: "斎場御嶽（せーふぁうたき）は沖縄本島南部・南城市に位置する琉球王国最高の聖地。2000年に世界遺産に登録されたこの場所では、三庫理（さんぐーい）と呼ばれる2つの巨大な岩が交差する神秘的な空間が訪れる人を圧倒します。" },
      { type: "spot-card", content: "sefa-utaki" },
      { type: "heading", content: "参拝マナーと見どころ", level: 2 },
      { type: "text", content: "御嶽は今も現役の聖域。静かに参拝し、岩には触れないよう注意が必要です。入場は御嶽南口管理センターからのみ。那覇から車で約40分。近くには知念岬公園もあり、合わせて訪れるのがおすすめです。" },
    ],
    relatedArticleSlugs: ["okinawa-shurijo-castle-guide", "okinawa-nakijin-castle-ruins"],
  },
  {
    slug: "okinawa-nakijin-castle-ruins",
    title: "今帰仁城跡の桜と夕景｜世界遺産の城壁を染める絶景",
    description: "日本最南端の桜の名所・今帰仁城跡で、世界遺産の石積み城壁とカンヒザクラの絶景を楽しむ旅案内。",
    coverImage: img3,
    publishedAt: "2025-01-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["今帰仁城跡", "世界遺産", "桜", "今帰仁村", "絶景"],
    spotIds: ["nakijin-castle"],
    sections: [
      { type: "heading", content: "日本最南端の桜名所", level: 2 },
      { type: "text", content: "今帰仁城跡は沖縄本島北部・今帰仁村にある世界遺産の城跡。1〜2月にはカンヒザクラ（緋寒桜）が咲き誇り、日本一早い桜まつりが開催されます。城壁から見る東シナ海の絶景も格別です。" },
      { type: "spot-card", content: "nakijin-castle" },
      { type: "heading", content: "夕景と歴史散策", level: 2 },
      { type: "text", content: "曲線を描く石積みの城壁は、グスク（城）特有の美しさ。夕暮れ時には城壁が橙色に染まり幻想的な雰囲気に。隣接する今帰仁村歴史文化センターで歴史を学んでから城跡を歩くと理解がより深まります。" },
    ],
    relatedArticleSlugs: ["okinawa-churaumi-aquarium-complete", "okinawa-kouri-island-romantic"],
  },
  {
    slug: "okinawa-soba-guide",
    title: "沖縄そば食べ比べ完全版｜那覇から北部まで名店巡り",
    description: "小麦麺とソーキ軟骨の旨みが絶妙な沖縄そば。地元民が通う名店から観光客向けの絶品店まで徹底紹介。",
    coverImage: img1,
    publishedAt: "2025-08-12",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["沖縄そば", "グルメ", "那覇", "ソーキそば", "食べ歩き"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "沖縄そばの魅力", level: 2 },
      { type: "text", content: "沖縄そばは小麦粉で作った麺に豚骨・カツオだしのスープ、ソーキ（豚スペアリブ）や三枚肉をのせた沖縄の国民食。本土のそばとは別物で、コシのある麺とあっさりした塩味スープが特徴です。" },
      { type: "heading", content: "地域別おすすめ名店", level: 2 },
      { type: "text", content: "那覇エリアでは「首里そば」や「なかむら屋」が人気。北谷や恩納村では海を眺めながら食べるカフェスタイルのそばも増えています。八重山地方の「八重山そば」は麺が細く別の美味しさ。ぜひ食べ比べてみてください。" },
      { type: "spot-card", content: "kokusai-dori" },
    ],
    relatedArticleSlugs: ["okinawa-goya-champuru-guide", "okinawa-kokusai-dori-guide"],
  },
  {
    slug: "okinawa-goya-champuru-guide",
    title: "ゴーヤチャンプルーの聖地巡礼｜沖縄家庭料理の真髄を味わう",
    description: "苦みと旨みの絶妙なハーモニー、ゴーヤチャンプルーを沖縄の食堂と家庭料理で堪能する美食ガイド。",
    coverImage: img2,
    publishedAt: "2025-09-03",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["ゴーヤチャンプルー", "沖縄料理", "食堂", "家庭料理", "グルメ"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "チャンプルー文化の魅力", level: 2 },
      { type: "text", content: "「チャンプルー」とは沖縄方言で「ごちゃまぜ」の意。ゴーヤ・豆腐・卵・ポーク缶（スパム）を炒め合わせたゴーヤチャンプルーは、沖縄の食卓に欠かせない一品です。苦みの中に隠れた旨みがクセになります。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "おすすめ食堂と家庭の味", level: 2 },
      { type: "text", content: "那覇市内の大衆食堂「三笠食堂」や「かなぐすく食堂」などで本場の味が楽しめます。牧志公設市場周辺の食堂街も穴場。ゴーヤはビタミンCが豊富で夏バテ防止にも効果的な沖縄の健康食です。" },
    ],
    relatedArticleSlugs: ["okinawa-taco-rice-guide", "okinawa-soba-guide"],
  },
  {
    slug: "okinawa-taco-rice-guide",
    title: "タコライス発祥の地・沖縄で食べる本場の味｜金武町と那覇の名店",
    description: "アメリカ文化と沖縄が融合して生まれたタコライス。発祥の金武町から那覇まで名店を巡る食べ歩きガイド。",
    coverImage: img3,
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["タコライス", "金武町", "B級グルメ", "アメリカン", "那覇"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "タコライス誕生の物語", level: 2 },
      { type: "text", content: "タコライスは1984年、沖縄県金武町でメキシコ料理のタコスをご飯にのせたアレンジ料理として誕生。米軍基地が多い沖縄ならではのアメリカ×沖縄文化の融合グルメです。タコスミートとチーズ、レタス、サルサソースの組み合わせが絶品。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "金武町・那覇の人気店", level: 2 },
      { type: "text", content: "発祥の店「キングタコス」金武本店は行列必至の名店。那覇・国際通り周辺にも多くのタコライス店があります。チーズたっぷりのチーズタコライスや、ドリア風にしたアレンジもお試しください。" },
    ],
    relatedArticleSlugs: ["okinawa-goya-champuru-guide", "okinawa-blue-seal-ice-cream"],
  },
  {
    slug: "okinawa-blue-seal-ice-cream",
    title: "ブルーシールアイスクリームの全フレーバー制覇｜沖縄スイーツの王様",
    description: "戦後アメリカ生まれの沖縄ソウルスイーツ、ブルーシール。紅芋・塩ちんすこう・シークヮーサー全制覇ガイド。",
    coverImage: img1,
    publishedAt: "2025-06-28",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["ブルーシール", "アイスクリーム", "スイーツ", "紅芋", "沖縄グルメ"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "沖縄生まれのアイスクリーム", level: 2 },
      { type: "text", content: "ブルーシールは1948年に米軍基地内で誕生したアイスクリームブランド。沖縄食材を使ったユニークなフレーバーが魅力で、紅芋・塩ちんすこう・シークヮーサーなど沖縄ならではの味が揃います。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "おすすめフレーバーと店舗情報", level: 2 },
      { type: "text", content: "人気No.1は定番の紅芋。塩味が甘みを引き立てる「塩ちんすこう」も必食。国際通り店や那覇空港店など沖縄県内に50以上の店舗があり、旅のフィナーレにぴったりのお土産用パイントも充実しています。" },
    ],
    relatedArticleSlugs: ["okinawa-taco-rice-guide", "okinawa-awamori-guide"],
  },
  {
    slug: "okinawa-diving-guide",
    title: "沖縄ダイビング完全ガイド｜初心者から上級者まで最高の海を選ぶ",
    description: "ケラマ諸島・石垣島・宮古島など沖縄各エリアのダイビングスポットを透明度・難易度別に徹底比較解説。",
    coverImage: img2,
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["ダイビング", "シュノーケル", "ケラマ", "石垣島", "宮古島"],
    spotIds: ["zamami-island", "taketomi-island"],
    sections: [
      { type: "heading", content: "沖縄のダイビングシーン", level: 2 },
      { type: "text", content: "沖縄は日本最高峰のダイビングスポットが集まるエリア。本島周辺から離島まで、透明度抜群のサンゴ礁やウミガメ、マンタとの遭遇が期待できます。初心者向けの体験ダイビングも充実しています。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "エリア別おすすめスポット", level: 2 },
      { type: "text", content: "ケラマ諸島（座間味・渡嘉敷）はウミガメとの遭遇率が高く初心者にも最適。石垣島・宮古島は上級者向けの豪快なドリフトダイビングが体験できます。4月〜11月がベストシーズンです。" },
    ],
    relatedArticleSlugs: ["okinawa-zamami-island-diving", "okinawa-miyako-island-guide"],
  },
  {
    slug: "okinawa-american-village-guide",
    title: "美浜アメリカンビレッジ完全ガイド｜沖縄×アメリカンカルチャーの聖地",
    description: "北谷町の異国情緒あふれる複合リゾート・美浜アメリカンビレッジで食べて買って楽しむ丸1日ガイド。",
    coverImage: img3,
    publishedAt: "2025-10-18",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okinawa",
    tags: ["アメリカンビレッジ", "北谷", "ショッピング", "グルメ", "観覧車"],
    spotIds: ["manza-mo"],
    sections: [
      { type: "heading", content: "アメリカンビレッジとは", level: 2 },
      { type: "text", content: "北谷町の美浜アメリカンビレッジは、米軍基地返還地に開発されたショッピング＆エンタメ複合施設。カラフルなビルが立ち並ぶアメリカンな雰囲気の中、飲食店・雑貨店・アウトレットが軒を連ねます。" },
      { type: "spot-card", content: "manza-mo" },
      { type: "heading", content: "夕日と観覧車の絶景", level: 2 },
      { type: "text", content: "夕暮れ時には観覧車の向こうに沈む夕日が絶景。サンセットを眺めながらオープンエアのカフェでくつろぐ時間は格別です。那覇からバスや車で約30分のアクセス。夜まで賑わっています。" },
    ],
    relatedArticleSlugs: ["okinawa-sunset-spot-guide", "okinawa-cafe-guide"],
  },
  {
    slug: "okinawa-zanpa-cape-lighthouse",
    title: "残波岬灯台と白波の絶景｜読谷村の断崖を歩く爽快散策",
    description: "沖縄本島最西端・残波岬の白亜の灯台と荒波打ち寄せる断崖から望む東シナ海の絶景をご紹介。",
    coverImage: img1,
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["残波岬", "読谷村", "灯台", "断崖絶壁", "夕日"],
    spotIds: ["manza-mo"],
    sections: [
      { type: "heading", content: "沖縄本島西端の絶景岬", level: 2 },
      { type: "text", content: "残波岬は読谷村の東シナ海に突き出した約2kmの断崖が続く岬。高さ約30mの白亜の灯台からは360度の大パノラマが広がり、沖縄本島の夕日スポットとしても有名です。" },
      { type: "spot-card", content: "manza-mo" },
      { type: "heading", content: "読谷やちむんと合わせて訪問", level: 2 },
      { type: "text", content: "残波岬の近くには「やちむんの里」があり、沖縄の伝統陶器・やちむんの工房が集まります。岬散策後に工房を訪れて器選びを楽しむのが読谷村観光の王道コース。那覇から車で約45分です。" },
    ],
    relatedArticleSlugs: ["okinawa-yachimun-pottery-guide", "okinawa-manza-mo-cliff-walk"],
  },
  {
    slug: "okinawa-ishigaki-island-guide",
    title: "石垣島完全ガイド｜川平湾の絶景とマンタと泳ぐ南国天国",
    description: "日本最南西の島・石垣島で、ミシュラン三つ星の川平湾と世界最高峰のダイビングを満喫する旅案内。",
    coverImage: img2,
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okinawa",
    tags: ["石垣島", "川平湾", "八重山諸島", "ダイビング", "マンタ"],
    spotIds: ["taketomi-island"],
    sections: [
      { type: "heading", content: "八重山の中心・石垣島", level: 2 },
      { type: "text", content: "石垣島は那覇から飛行機で約1時間の八重山諸島最大の島。世界有数の透明度を誇る川平湾やマンタが乱舞するマンタスクランブル、石垣牛など独自の魅力が満載です。" },
      { type: "spot-card", content: "taketomi-island" },
      { type: "heading", content: "川平湾とグラスボート", level: 2 },
      { type: "text", content: "ミシュランの星を獲得した川平湾はエメラルドグリーンの海が神秘的な美しさ。グラスボートでサンゴ礁の上を漂う体験は格別。石垣牛の焼肉や八重山そばなどグルメも充実しています。" },
    ],
    relatedArticleSlugs: ["okinawa-taketomi-island-cultural", "okinawa-miyako-island-guide"],
  },
  {
    slug: "okinawa-miyako-island-guide",
    title: "宮古島マリンリゾート完全版｜与那覇前浜と宮古ブルーの楽園",
    description: "東洋一の白砂ビーチ・与那覇前浜と「宮古ブルー」の海が輝く離島リゾート、宮古島の全魅力を網羅。",
    coverImage: img3,
    publishedAt: "2025-08-30",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "okinawa",
    tags: ["宮古島", "与那覇前浜", "宮古ブルー", "リゾート", "海水浴"],
    spotIds: ["zamami-island"],
    sections: [
      { type: "heading", content: "宮古ブルーの海に魅せられる", level: 2 },
      { type: "text", content: "宮古島は那覇から飛行機で約45分。「宮古ブルー」と称される透き通った青い海と、東洋一と称される与那覇前浜ビーチは、国内外から多くの旅行者を引きつけます。伊良部大橋など絶景の橋めぐりも人気です。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "アクティビティとグルメ", level: 2 },
      { type: "text", content: "宮古島の海ではシュノーケルやダイビング、カヤック、シーウォーカーなど多彩なアクティビティを体験できます。島の食堂では「宮古そば」や「海ぶどう丼」が人気。リゾートホテルも充実しています。" },
    ],
    relatedArticleSlugs: ["okinawa-ishigaki-island-guide", "okinawa-diving-guide"],
  },
  {
    slug: "okinawa-ie-island-lily",
    title: "伊江島てっぽうゆり祭り｜白い花咲く春の離島ショートトリップ",
    description: "4月の伊江島を白く埋め尽くすてっぽうゆりの絶景と、城山（タッチュー）からの360度パノラマ展望。",
    coverImage: img1,
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["伊江島", "てっぽうゆり", "春", "城山", "日帰り島旅"],
    spotIds: ["nakijin-castle"],
    sections: [
      { type: "heading", content: "白百合の楽園・伊江島", level: 2 },
      { type: "text", content: "伊江島は本部港からフェリーで約30分の小さな離島。毎年4月にはてっぽうゆり祭りが開催され、島全体が白い花に覆われます。シンボルの城山（タッチュー）は標高172mながら絶景の展望台です。" },
      { type: "spot-card", content: "nakijin-castle" },
      { type: "heading", content: "日帰りショートトリップの楽しみ方", level: 2 },
      { type: "text", content: "フェリーで往復して半日から1日楽しめる伊江島。レンタサイクルで島内を一周し、ゆり畑の中でのんびりするのが定番の楽しみ方。伊江ビーチでの海水浴も人気です。" },
    ],
    relatedArticleSlugs: ["okinawa-nakijin-castle-ruins", "okinawa-churaumi-aquarium-complete"],
  },
  {
    slug: "okinawa-yachimun-pottery-guide",
    title: "読谷やちむんの里めぐり｜沖縄の魂が宿る器を選ぶ旅",
    description: "沖縄の伝統陶器・やちむんの工房が集う読谷やちむんの里で、職人の手仕事に触れ、一生の宝物を選ぶ。",
    coverImage: img2,
    publishedAt: "2025-11-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["やちむん", "読谷村", "陶器", "工芸品", "ショッピング"],
    spotIds: ["shurijo"],
    sections: [
      { type: "heading", content: "やちむんとは", level: 2 },
      { type: "text", content: "「やちむん」とは沖縄方言で陶器のこと。力強い絵付けと温かみのある形が特徴で、読谷村のやちむんの里には20以上の工房が集まり、それぞれ独自のデザインを制作・販売しています。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "工房めぐりのコツ", level: 2 },
      { type: "text", content: "各工房には個性豊かな作品が並び、陶器市やワークショップも開催されています。手作りの一点物を求めるなら、10〜11月の「やちむん陶器市」がおすすめ。シーサーや湯呑み、器など旅の思い出になる逸品が見つかります。" },
    ],
    relatedArticleSlugs: ["okinawa-zanpa-cape-lighthouse", "okinawa-siisa-craft-guide"],
  },
  {
    slug: "okinawa-beach-ranking-guide",
    title: "沖縄ビーチランキング2025｜本島・離島含む最高の海TOP10",
    description: "透明度・設備・アクセスで徹底比較！エメラルドグリーンの海が輝く沖縄絶景ビーチBEST10を一挙公開。",
    coverImage: img3,
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["ビーチ", "海水浴", "透明度", "本島", "離島"],
    spotIds: ["manza-mo", "zamami-island"],
    sections: [
      { type: "heading", content: "沖縄ビーチ選びのポイント", level: 2 },
      { type: "text", content: "沖縄には数百のビーチが点在します。透明度・白砂の質・アクセスのしやすさ・設備の充実度で選ぶのがポイント。本島は交通の便が良く、離島はより透明度の高い海が楽しめます。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "おすすめビーチTOP5", level: 2 },
      { type: "text", content: "1位：阿嘉島（ケラマ諸島）2位：与那覇前浜（宮古島）3位：川平湾（石垣島）4位：コンドイビーチ（竹富島）5位：古座間味ビーチ（座間味島）。いずれも透明度が高く、ウミガメやサンゴ礁が見られる絶景スポットです。" },
    ],
    relatedArticleSlugs: ["okinawa-diving-guide", "okinawa-zamami-island-diving"],
  },
  {
    slug: "okinawa-sunset-spot-guide",
    title: "沖縄絶景サンセットスポット7選｜黄金色に染まる夕暮れを追いかける",
    description: "残波岬・古宇利大橋・万座毛など沖縄で夕日が最も美しく見えるスポットを厳選してご紹介。",
    coverImage: img1,
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "okinawa",
    tags: ["サンセット", "夕日", "絶景", "万座毛", "古宇利島"],
    spotIds: ["manza-mo", "kouri-island"],
    sections: [
      { type: "heading", content: "沖縄サンセットの魅力", level: 2 },
      { type: "text", content: "東シナ海に面した沖縄は、日本有数のサンセット天国。夕暮れ時には空と海が橙や紫に染まり、旅の記憶に深く刻まれる絶景が広がります。" },
      { type: "spot-card", content: "manza-mo" },
      { type: "heading", content: "おすすめサンセットスポット", level: 2 },
      { type: "text", content: "残波岬、万座毛、古宇利大橋、美浜アメリカンビレッジ（北谷）、伊江島・タッチューはどれも夕日の名所。石垣島の御神崎灯台や宮古島の砂山ビーチも離島ならではの美しい夕日が楽しめます。" },
    ],
    relatedArticleSlugs: ["okinawa-kouri-island-romantic", "okinawa-manza-mo-cliff-walk"],
  },
  {
    slug: "okinawa-cafe-guide",
    title: "沖縄のおしゃれカフェ巡り｜海ビューからリノベカフェまで全島制覇",
    description: "ブルーの海を眺めながらフルーツシェイクを飲む至福。沖縄本島・離島の個性派カフェを厳選してご紹介。",
    coverImage: img2,
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "okinawa",
    tags: ["カフェ", "海カフェ", "恩納村", "北谷", "おしゃれ"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "沖縄カフェシーンの今", level: 2 },
      { type: "text", content: "沖縄では海を見渡す高台のカフェや、古民家をリノベーションしたカフェが急増中。南国フルーツを使ったスムージーや、沖縄食材を取り入れたスイーツが旅行者に大人気です。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "エリア別おすすめカフェ", level: 2 },
      { type: "text", content: "恩納村の「浜辺の茶屋」は波打ち際のテーブルが名物。北谷「海辺カフェ」は夕日鑑賞スポット。読谷村の古民家カフェは静かな時間が流れます。離島では石垣島「離島のんびりカフェ」が人気です。" },
    ],
    relatedArticleSlugs: ["okinawa-american-village-guide", "okinawa-sunset-spot-guide"],
  },
  {
    slug: "okinawa-awamori-guide",
    title: "泡盛の世界を深掘り｜沖縄の蒸留酒文化と蔵元めぐり",
    description: "600年の歴史を持つ沖縄の蒸留酒・泡盛の製法と味わいの違いを蔵元訪問で学ぶ大人の旅ガイド。",
    coverImage: img3,
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["泡盛", "蔵元", "沖縄文化", "お酒", "試飲"],
    spotIds: ["shurijo"],
    sections: [
      { type: "heading", content: "泡盛600年の歴史", level: 2 },
      { type: "text", content: "泡盛は14〜15世紀にタイから伝わった蒸留酒で、日本最古の蒸留酒とも言われます。黒麹菌と米を使って造られるその独特の香りとコクは、沖縄の食文化に深く根付いています。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "古酒（クース）と蔵元見学", level: 2 },
      { type: "text", content: "3年以上熟成された古酒（クース）は特に香り豊か。沖縄本島には「瑞泉酒造」「菊之露酒造」など見学できる蔵元が複数あります。試飲コーナーでお気に入りの一本を選んで、お土産にするのがおすすめです。" },
    ],
    relatedArticleSlugs: ["okinawa-orion-beer-guide", "okinawa-blue-seal-ice-cream"],
  },
  {
    slug: "okinawa-siisa-craft-guide",
    title: "シーサーの魅力と手作り体験｜沖縄の守り神を自分の手で作る",
    description: "沖縄の守り神・シーサーの歴史から手作り体験工房まで、沖縄伝統工芸の奥深い世界をご紹介します。",
    coverImage: img1,
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["シーサー", "工芸", "手作り体験", "伝統文化", "お土産"],
    spotIds: ["shurijo"],
    sections: [
      { type: "heading", content: "シーサーとは何か", level: 2 },
      { type: "text", content: "シーサーは沖縄の家々の屋根や門に置かれる守り神。獅子（ライオン）をモチーフにした陶製の像で、魔除けと家内安全を祈願します。口を開いたオスと閉じたメスを一対で置くのが一般的です。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "手作りシーサー体験", level: 2 },
      { type: "text", content: "那覇の「壺屋やちむん通り」周辺や読谷やちむんの里には、シーサー絵付け・制作体験工房が数多くあります。自分だけの表情のシーサーを作る体験は子どもから大人まで人気。完成品は後日自宅に届けてもらえます。" },
    ],
    relatedArticleSlugs: ["okinawa-yachimun-pottery-guide", "okinawa-kokusai-dori-guide"],
  },
  {
    slug: "okinawa-orion-beer-guide",
    title: "オリオンビールの聖地巡礼｜沖縄の青空の下で飲む黄金の一杯",
    description: "沖縄生まれのオリオンビール醸造所見学から、ビアガーデン・地元バーまでオリオンビールを楽しむ完全ガイド。",
    coverImage: img2,
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["オリオンビール", "ビール", "名護市", "工場見学", "グルメ"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "沖縄ソウルドリンク・オリオンビール", level: 2 },
      { type: "text", content: "1957年創業のオリオンビールは沖縄を代表するビールブランド。スッキリとした飲み口と南国の空気が相まって、格別のおいしさです。名護市にある「オリオンハッピーパーク」では工場見学と無料試飲が楽しめます。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "工場見学と試飲のすすめ", level: 2 },
      { type: "text", content: "オリオンハッピーパークでは製造工程の見学（無料）後に試飲コーナーへ。製造直後の新鮮なビールを2杯まで無料で飲めます。那覇からバスで約1.5時間。事前予約がおすすめです。" },
    ],
    relatedArticleSlugs: ["okinawa-awamori-guide", "okinawa-goya-champuru-guide"],
  },
  {
    slug: "okinawa-family-travel-guide",
    title: "沖縄家族旅行完全ガイド｜子どもが大喜びの3泊4日モデルプラン",
    description: "美ら海水族館・ビーチ・工作体験まで、子連れ沖縄旅行を成功させるための実践的プランニングガイド。",
    coverImage: img3,
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "okinawa",
    tags: ["家族旅行", "子連れ", "美ら海水族館", "ビーチ", "モデルコース"],
    spotIds: ["churaumi-aquarium", "nakijin-castle"],
    sections: [
      { type: "heading", content: "子連れ沖縄旅行のポイント", level: 2 },
      { type: "text", content: "沖縄は家族旅行に最適なデスティネーション。美ら海水族館やビーチ遊び、シーサー絵付けなど子どもが楽しめるアクティビティが豊富です。那覇空港から主要観光地へのアクセスも良好です。" },
      { type: "spot-card", content: "churaumi-aquarium" },
      { type: "heading", content: "3泊4日おすすめモデルコース", level: 2 },
      { type: "text", content: "1日目：那覇・国際通り散策→首里城。2日目：美ら海水族館→今帰仁城跡→古宇利島。3日目：ビーチ＆マリンアクティビティ。4日目：やちむん体験→那覇空港。各スポット間は車移動が便利です。" },
    ],
    relatedArticleSlugs: ["okinawa-churaumi-aquarium-complete", "okinawa-nakijin-castle-ruins"],
  },
  {
    slug: "okinawa-budget-travel-guide",
    title: "沖縄格安旅行術2025｜3万円以内で楽しむ4日間の完全プラン",
    description: "LCC活用・格安宿・無料スポット駆使で沖縄を3万円以下で満喫する、賢い節約旅行の完全ガイド。",
    coverImage: img1,
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "okinawa",
    tags: ["格安旅行", "節約", "LCC", "バックパッカー", "那覇"],
    spotIds: ["shurijo", "sefa-utaki"],
    sections: [
      { type: "heading", content: "沖縄を安く旅するコツ", level: 2 },
      { type: "text", content: "沖縄旅行の費用を抑えるには、LCC（ジェットスター・ピーチ）の早期予約が鍵。那覇空港発着の格安便を使えば往復1万円以下も可能です。宿はゲストハウスや民宿を利用し、食事は地元食堂で定食を食べましょう。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "無料・格安の絶景スポット", level: 2 },
      { type: "text", content: "首里城公園（外郭無料）、斎場御嶽（300円）、万座毛（無料）、残波岬（無料）など絶景スポットは格安で楽しめます。ゆいレール1日乗車券（800円）で那覇市内を効率よく回りましょう。" },
    ],
    relatedArticleSlugs: ["okinawa-solo-travel-guide", "okinawa-soba-guide"],
  },
  {
    slug: "okinawa-luxury-resort-guide",
    title: "沖縄ラグジュアリーリゾート完全版｜憧れの高級ホテルでの過ごし方",
    description: "ザ・リッツカールトン・ハレクラニ沖縄など、沖縄の5つ星リゾートで夢のような滞在を叶えるガイド。",
    coverImage: img2,
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "okinawa",
    tags: ["ラグジュアリー", "高級ホテル", "リゾート", "恩納村", "スパ"],
    spotIds: ["manza-mo", "kouri-island"],
    sections: [
      { type: "heading", content: "沖縄の高級リゾートシーン", level: 2 },
      { type: "text", content: "沖縄本島の恩納村・北谷エリアには世界トップクラスのラグジュアリーリゾートが集積。ザ・リッツカールトン沖縄、ハレクラニ沖縄、ヒルトン沖縄北谷リゾートなど、プールと海が一体化したインフィニティプールが自慢です。" },
      { type: "spot-card", content: "manza-mo" },
      { type: "heading", content: "極上の時間の過ごし方", level: 2 },
      { type: "text", content: "朝はビーチヨガ、昼はプールで読書、夜は新鮮な海の幸を使ったコースディナー。スパでのトリートメントや、プライベートビーチでの夕日鑑賞が至福の時間。特別な旅の思い出になること間違いなしです。" },
    ],
    relatedArticleSlugs: ["okinawa-sunset-spot-guide", "okinawa-couple-romantic-guide"],
  },
  {
    slug: "okinawa-solo-travel-guide",
    title: "沖縄ひとり旅の魅力｜自分だけの時間に浸る7日間プラン",
    description: "ひとりだからこそ深く味わえる沖縄。地元食堂めぐり・スキューバ体験・伝統芸能観賞を組み合わせた充実プラン。",
    coverImage: img3,
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "okinawa",
    tags: ["ひとり旅", "ソロトラベル", "那覇", "食堂めぐり", "ダイビング"],
    spotIds: ["sefa-utaki", "zamami-island"],
    sections: [
      { type: "heading", content: "ひとり旅で沖縄をより深く", level: 2 },
      { type: "text", content: "ひとり旅なら地元の人と自然に会話が生まれ、観光ガイドには載らない隠れスポットを教えてもらえることも。朝の市場、昼の食堂、夕方のビーチ、夜の居酒屋と、沖縄の1日を自分のペースで堪能できます。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "ソロにおすすめのアクティビティ", level: 2 },
      { type: "text", content: "体験ダイビング（ひとりでも参加しやすい）、三線体験教室、琉球舞踊鑑賞、やちむん陶芸体験はひとり旅に最適。自由な時間に斎場御嶽や識名園など世界遺産を静かに巡るのも贅沢な過ごし方です。" },
    ],
    relatedArticleSlugs: ["okinawa-budget-travel-guide", "okinawa-cafe-guide"],
  },
  {
    slug: "okinawa-couple-romantic-guide",
    title: "沖縄カップル旅行完全版｜2人だから楽しめる夢のロマンチックプラン",
    description: "古宇利島ドライブ・ビーチサンセット・リゾートスパと、2人の記念日を彩る沖縄ロマンティック旅行ガイド。",
    coverImage: img1,
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "okinawa",
    tags: ["カップル旅行", "ロマンティック", "記念日", "古宇利島", "サンセット"],
    spotIds: ["kouri-island", "taketomi-island"],
    sections: [
      { type: "heading", content: "2人だから楽しい沖縄旅", level: 2 },
      { type: "text", content: "沖縄はカップルに最高のデスティネーション。コバルトブルーの海と白砂のビーチ、夕日の絶景ドライブ、リゾートのプールサイドと、ロマンチックな瞬間が次々と訪れます。" },
      { type: "spot-card", content: "kouri-island" },
      { type: "heading", content: "記念日をさらに特別に", level: 2 },
      { type: "text", content: "古宇利島のハートロックで写真撮影、竹富島での水牛車デート、恩納村の高級リゾートでのスパ体験、夕暮れ時の万座毛での散歩など、2人だけの特別な思い出を作りましょう。" },
    ],
    relatedArticleSlugs: ["okinawa-kouri-island-romantic", "okinawa-sunset-spot-guide"],
  },
  {
    slug: "okinawa-spring-cherry-sakura",
    title: "沖縄の春旅行｜日本で一番早い桜と花咲く離島をめぐる",
    description: "1月〜2月に咲くカンヒザクラで日本最南端の花見を楽しむ、沖縄春旅行の完全ガイドをお届けします。",
    coverImage: img2,
    publishedAt: "2025-01-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["桜", "春旅行", "今帰仁城", "カンヒザクラ", "伊江島"],
    spotIds: ["nakijin-castle"],
    sections: [
      { type: "heading", content: "1月から咲く沖縄の桜", level: 2 },
      { type: "text", content: "沖縄のカンヒザクラ（緋寒桜）は本土より2〜3ヶ月早く1月下旬〜2月に開花。今帰仁城跡や名護城址公園、伊江島が有名な花見スポットです。ピンクと朱色の鮮やかな色合いは本土の桜とは趣が異なります。" },
      { type: "spot-card", content: "nakijin-castle" },
      { type: "heading", content: "春の沖縄のおすすめ行動", level: 2 },
      { type: "text", content: "1〜2月は観光客が少なく宿泊費も安め。海はやや肌寒いですが、ハイキングや花見には最適。今帰仁城跡の桜まつり（毎年1〜2月）では地元グルメの出店も並びます。" },
    ],
    relatedArticleSlugs: ["okinawa-nakijin-castle-ruins", "okinawa-ie-island-lily"],
  },
  {
    slug: "okinawa-summer-sea-guide",
    title: "沖縄夏旅行2025｜7月〜9月の海と祭りを120%楽しむ完全版",
    description: "エイサー祭り・花火大会・ビーチ・ダイビングと、沖縄の夏を全力で楽しむためのアクティビティ全網羅。",
    coverImage: img3,
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["夏旅行", "エイサー", "海水浴", "花火", "夏祭り"],
    spotIds: ["zamami-island", "manza-mo"],
    sections: [
      { type: "heading", content: "沖縄の夏はマリンアクティビティの季節", level: 2 },
      { type: "text", content: "7〜9月は沖縄旅行のベストシーズン。海は透明度抜群でダイビング・シュノーケル・サーフィン・カヤックなど全てのマリンアクティビティが最高の状態で楽しめます。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "夏の祭りと文化体験", level: 2 },
      { type: "text", content: "8月の旧盆にはエイサー（沖縄の盆踊り）が各地で開催。那覇の「一万人のエイサー踊り隊」は圧巻の迫力。7月下旬の「うみんちゅワーフ」での花火大会も見逃せない夏の風物詩です。" },
    ],
    relatedArticleSlugs: ["okinawa-beach-ranking-guide", "okinawa-diving-guide"],
  },
  {
    slug: "okinawa-autumn-travel-guide",
    title: "沖縄秋旅行のススメ｜10月〜11月は海も陸も観光ベストシーズン",
    description: "台風シーズン終わりの10〜11月は人も少なく天気も安定。秋の沖縄を旅するベストな理由と過ごし方。",
    coverImage: img1,
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["秋旅行", "穴場", "10月", "11月", "観光"],
    spotIds: ["sefa-utaki", "shurijo"],
    sections: [
      { type: "heading", content: "秋の沖縄が穴場な理由", level: 2 },
      { type: "text", content: "10〜11月の沖縄は台風が終わり、気温も25〜28度と過ごしやすい季節。夏の混雑が落ち着き、宿泊料金も下がるため、ゆったり旅したい人に最適のシーズンです。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "秋ならではのおすすめ体験", level: 2 },
      { type: "text", content: "11月上旬にはやちむん陶器市が開催され、希少な一点物の器と出会えます。読谷村のハロウィンイベント、糸満市の「ハーリー」民俗行事なども秋ならでは。海は10月まで泳げる温度が続きます。" },
    ],
    relatedArticleSlugs: ["okinawa-yachimun-pottery-guide", "okinawa-zanpa-cape-lighthouse"],
  },
  {
    slug: "okinawa-winter-whale-watching",
    title: "沖縄冬の絶景体験｜ザトウクジラのホエールウォッチングガイド",
    description: "12月〜3月にケラマ諸島周辺に現れるザトウクジラ。ブリーチングが見られる冬の沖縄旅行の全魅力。",
    coverImage: img2,
    publishedAt: "2025-12-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "okinawa",
    tags: ["ホエールウォッチング", "ザトウクジラ", "冬旅行", "ケラマ", "座間味"],
    spotIds: ["zamami-island"],
    sections: [
      { type: "heading", content: "冬の沖縄はクジラの楽園", level: 2 },
      { type: "text", content: "12月〜3月にかけてザトウクジラが沖縄周辺海域に繁殖・子育てのために現れます。ケラマ諸島周辺はブリーチングやテールスラップが間近で見られる世界有数のホエールウォッチングスポットです。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "ツアー参加のポイント", level: 2 },
      { type: "text", content: "那覇・泊港から出発するホエールウォッチングツアーは所要3〜4時間。遭遇率は80〜90%と非常に高く、シーズン中は連日出港しています。防寒着を忘れずに。2月がピークで最も遭遇率が高い時期です。" },
    ],
    relatedArticleSlugs: ["okinawa-zamami-island-diving", "okinawa-autumn-travel-guide"],
  },
  {
    slug: "okinawa-photography-spots",
    title: "沖縄フォトジェニックスポット25選｜インスタ映えする絶景撮影地",
    description: "古宇利大橋から竹富島の集落まで、沖縄で最も美しい写真が撮れる絶景スポット25か所を徹底紹介。",
    coverImage: img3,
    publishedAt: "2025-05-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["フォトジェニック", "インスタ映え", "絶景", "写真", "撮影スポット"],
    spotIds: ["kouri-island", "taketomi-island", "manza-mo"],
    sections: [
      { type: "heading", content: "沖縄は日本最高の撮影地", level: 2 },
      { type: "text", content: "コバルトブルーの海、白砂のビーチ、朱色の首里城、ガジュマルの古木、赤瓦の集落と、沖縄は被写体の宝庫。スマホカメラでもプロのような写真が撮れるスポットが満載です。" },
      { type: "spot-card", content: "kouri-island" },
      { type: "heading", content: "撮影ベストタイムとコツ", level: 2 },
      { type: "text", content: "朝日・夕日の時間帯（ゴールデンアワー）は光が柔らかく最高の写真が撮れます。古宇利大橋は午前中、万座毛の断崖は夕方前後が絶景。竹富島の集落は朝早くに訪れると人が少なく撮影しやすいです。" },
    ],
    relatedArticleSlugs: ["okinawa-sunset-spot-guide", "okinawa-taketomi-island-cultural"],
  },
  {
    slug: "okinawa-ryukyu-history-trail",
    title: "琉球王国歴史散策｜世界遺産9か所をつなぐ3日間の歴史旅",
    description: "首里城・斎場御嶽・今帰仁城跡など琉球王国の世界遺産9か所を巡る、知的好奇心を満たす歴史旅ガイド。",
    coverImage: img1,
    publishedAt: "2025-03-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okinawa",
    tags: ["琉球王国", "世界遺産", "歴史", "首里城", "グスク"],
    spotIds: ["shurijo", "sefa-utaki", "nakijin-castle"],
    sections: [
      { type: "heading", content: "琉球の世界遺産を巡る旅", level: 2 },
      { type: "text", content: "2000年に登録された「琉球王国のグスク及び関連遺産群」は9か所の資産で構成。首里城跡・中城城跡・座喜味城跡・斎場御嶽・今帰仁城跡などが沖縄各地に分布しています。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "3日間モデルコース", level: 2 },
      { type: "text", content: "1日目：那覇・首里城周辺（首里城・識名園・玉陵）。2日目：南部（斎場御嶽・浜比嘉島）→中部（中城城・座喜味城）。3日目：北部（今帰仁城・勝連城）。レンタカーが必須です。" },
    ],
    relatedArticleSlugs: ["okinawa-shurijo-castle-guide", "okinawa-sefa-utaki-power-spot"],
  },
  {
    slug: "okinawa-tropical-fruits-guide",
    title: "沖縄トロピカルフルーツ完全ガイド｜マンゴー・ドラゴンフルーツを食べ尽くす",
    description: "南国沖縄でしか味わえないアップルマンゴー・パッションフルーツ・スターフルーツを農園訪問で食べ尽くす。",
    coverImage: img2,
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["マンゴー", "トロピカルフルーツ", "農園", "スイーツ", "グルメ"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "南国フルーツの宝庫・沖縄", level: 2 },
      { type: "text", content: "沖縄は国内唯一の熱帯・亜熱帯性気候で、マンゴー・ドラゴンフルーツ・パッションフルーツ・ピタヤなどの南国フルーツが栽培されています。農園直売や観光農園では採れたての新鮮フルーツが味わえます。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "マンゴーシーズンと食べ方", level: 2 },
      { type: "text", content: "沖縄マンゴーの旬は6〜8月。濃厚な甘みとコクは「果物の王様」の名に恥じません。丸ごと食べるほか、マンゴーソフトクリーム・かき氷・パフェでも楽しめます。お土産の人気No.1です。" },
    ],
    relatedArticleSlugs: ["okinawa-blue-seal-ice-cream", "okinawa-cafe-guide"],
  },
  {
    slug: "okinawa-ryukyu-dance-music",
    title: "琉球舞踊と三線の世界｜沖縄伝統芸能を体験・鑑賞する旅",
    description: "国立劇場おきなわでの本格鑑賞から、三線体験教室・エイサー見学まで沖縄の伝統芸能を深掘りする旅。",
    coverImage: img3,
    publishedAt: "2025-04-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["琉球舞踊", "三線", "エイサー", "伝統芸能", "文化体験"],
    spotIds: ["shurijo"],
    sections: [
      { type: "heading", content: "沖縄音楽・芸能の魅力", level: 2 },
      { type: "text", content: "三線（さんしん）の音色と沖縄民謡、華やかな琉球舞踊は、他の日本文化と一線を画す独自の美しさがあります。首里城での舞踊公演や、国際通り周辺の民謡ライブで生の演奏を楽しめます。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "体験できる伝統芸能", level: 2 },
      { type: "text", content: "三線体験教室では1時間程度で「涙そうそう」など沖縄の名曲を演奏できるようになります。エイサー体験も観光施設で実施中。本格的な琉球舞踊鑑賞は国立劇場おきなわで。" },
    ],
    relatedArticleSlugs: ["okinawa-shurijo-castle-guide", "okinawa-siisa-craft-guide"],
  },
  {
    slug: "okinawa-sea-kayak-mangrove",
    title: "沖縄マングローブカヤック体験｜西表島・本島で生命溢れる秘境へ",
    description: "マングローブ林の川を漕ぐカヤックツアーで、沖縄独自の亜熱帯自然と多様な生態系を間近に体験する。",
    coverImage: img1,
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "okinawa",
    tags: ["カヤック", "マングローブ", "西表島", "エコツーリズム", "自然"],
    spotIds: ["taketomi-island"],
    sections: [
      { type: "heading", content: "マングローブの秘境をカヤックで探検", level: 2 },
      { type: "text", content: "沖縄のマングローブ林は独特の亜熱帯植物が生息する貴重なエリア。西表島の仲間川、本島の慶佐次湾などでカヤックツアーが開催されています。カニ・魚・野鳥など多様な生き物と出会えます。" },
      { type: "spot-card", content: "taketomi-island" },
      { type: "heading", content: "西表島・ジャングル体験", level: 2 },
      { type: "text", content: "西表島は島面積の90%以上が亜熱帯の森。カヤック後にトレッキングでピナイサーラの滝を目指すコースが人気。イリオモテヤマネコの生息地として世界自然遺産にも登録されています。" },
    ],
    relatedArticleSlugs: ["okinawa-taketomi-island-cultural", "okinawa-ishigaki-island-guide"],
  },
  {
    slug: "okinawa-model-course-5days",
    title: "沖縄本島5日間モデルコース｜那覇〜北部をレンタカーで完全制覇",
    description: "首里城から美ら海水族館・やんばるまで、沖縄本島を南から北へレンタカーで縦断する5日間の完全プラン。",
    coverImage: img2,
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okinawa",
    tags: ["モデルコース", "5日間", "レンタカー", "那覇", "やんばる"],
    spotIds: ["shurijo", "churaumi-aquarium", "nakijin-castle"],
    sections: [
      { type: "heading", content: "5日間の旅程概要", level: 2 },
      { type: "text", content: "1日目：那覇市内（首里城・国際通り・牧志公設市場）。2日目：南部（斎場御嶽・平和祈念公園）→中部（読谷やちむんの里）。3日目：恩納村（万座毛・シュノーケル）。4日目：北部（美ら海水族館・今帰仁城・古宇利島）。5日目：やんばる国立公園→那覇。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "レンタカー旅のコツ", level: 2 },
      { type: "text", content: "那覇空港周辺にレンタカー会社が集中。国際通りから車で各スポットへは1時間以内がほとんど。渋滞は国道58号線が要注意。カーナビ必須で、ETC利用で沖縄自動車道の料金を節約できます。" },
    ],
    relatedArticleSlugs: ["okinawa-shurijo-castle-guide", "okinawa-churaumi-aquarium-complete"],
  },
  {
    slug: "okinawa-healthy-food-guide",
    title: "沖縄長寿食の秘密｜健康食材と郷土料理が生む百年の活力",
    description: "世界的に有名な沖縄の長寿食文化。ゴーヤ・豆腐・昆布・豚肉フル活用の沖縄郷土料理と健康の関係を探る。",
    coverImage: img3,
    publishedAt: "2025-02-08",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "okinawa",
    tags: ["長寿食", "健康料理", "ゴーヤ", "豆腐よう", "沖縄料理"],
    spotIds: ["kokusai-dori"],
    sections: [
      { type: "heading", content: "長寿の島・沖縄の食文化", level: 2 },
      { type: "text", content: "沖縄はかつて世界最長寿地域として知られていました。その秘密は地元食材にあります。ゴーヤのビタミンC、豆腐・島豆腐のイソフラボン、昆布の食物繊維、豚肉のコラーゲンが組み合わさった食事が健康を支えます。" },
      { type: "spot-card", content: "kokusai-dori" },
      { type: "heading", content: "食堂で食べる長寿の味", level: 2 },
      { type: "text", content: "「豆腐よう」は島豆腐を泡盛と紅麹で発酵させた珍味。「クーブイリチー」は昆布の炒め煮。「中身汁」は豚のモツスープ。これらは地元食堂や那覇の居酒屋で手軽に味わえます。" },
    ],
    relatedArticleSlugs: ["okinawa-goya-champuru-guide", "okinawa-soba-guide"],
  },
  {
    slug: "okinawa-snorkeling-guide",
    title: "沖縄シュノーケリング完全ガイド｜道具不要・初心者でも楽しめる海",
    description: "シュノーケリングで沖縄の海を楽しむための場所・道具・注意点を初心者目線で完全解説します。",
    coverImage: img1,
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["シュノーケリング", "初心者", "ビーチ", "ウミガメ", "サンゴ礁"],
    spotIds: ["zamami-island", "kouri-island"],
    sections: [
      { type: "heading", content: "シュノーケリングの基本", level: 2 },
      { type: "text", content: "シュノーケリングは泳げない人でも浮き輪を使えば楽しめる、手軽な水中観察スポーツ。沖縄のビーチは遠浅で透明度が高く、ゴーグルとシュノーケルだけでカラフルな熱帯魚やサンゴ礁を観察できます。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "初心者向けのおすすめビーチ", level: 2 },
      { type: "text", content: "座間味島の古座間味ビーチ、石垣島の米原ビーチ、竹富島のコンドイビーチは初心者にも安全で透明度が高いビーチ。スノーケリングツアーでガイドと一緒に参加すれば安心です。" },
    ],
    relatedArticleSlugs: ["okinawa-diving-guide", "okinawa-zamami-island-diving"],
  },
  {
    slug: "okinawa-resort-hotel-ranking",
    title: "沖縄リゾートホテルランキング2025｜最高の朝食と眺望で選ぶTOP15",
    description: "朝食・プール・ビューで徹底比較した沖縄リゾートホテルBEST15を予算別にご紹介します。",
    coverImage: img2,
    publishedAt: "2025-01-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "okinawa",
    tags: ["リゾートホテル", "ランキング", "朝食", "プール", "宿泊"],
    spotIds: ["manza-mo"],
    sections: [
      { type: "heading", content: "沖縄ホテル選びの基準", level: 2 },
      { type: "text", content: "沖縄リゾートホテル選びでは、ビーチへのアクセス・プールの質・朝食の内容・景色が重要なポイント。恩納村・北谷・那覇・読谷村など、エリアによって雰囲気も大きく異なります。" },
      { type: "spot-card", content: "manza-mo" },
      { type: "heading", content: "カテゴリー別おすすめホテル", level: 2 },
      { type: "text", content: "高級：ザ・リッツカールトン沖縄、ハレクラニ沖縄。中級：ANAインターコンチネンタル万座ビーチリゾート、ヒルトン沖縄北谷リゾート。格安：OMO5沖縄那覇by星野リゾート。それぞれに異なる魅力があります。" },
    ],
    relatedArticleSlugs: ["okinawa-luxury-resort-guide", "okinawa-model-course-5days"],
  },
  {
    slug: "okinawa-naha-walking-guide",
    title: "那覇市内歩き旅｜首里から壺屋やちむん通りを歩く半日散策",
    description: "ゆいレールで繋がる那覇の見どころを徒歩で繋いだ、地元目線のディープな半日散策プランをご紹介。",
    coverImage: img3,
    publishedAt: "2025-03-30",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "okinawa",
    tags: ["那覇", "散策", "壺屋", "ゆいレール", "街歩き"],
    spotIds: ["shurijo", "kokusai-dori"],
    sections: [
      { type: "heading", content: "那覇の街を深く知る散策", level: 2 },
      { type: "text", content: "那覇市内はゆいレールとバス・徒歩でほとんどの観光地を回れます。首里城から壺屋やちむん通り→国際通り→牧志公設市場と歩くと、那覇の歴史と現在の両方が体感できます。" },
      { type: "spot-card", content: "shurijo" },
      { type: "heading", content: "壺屋やちむん通りの魅力", level: 2 },
      { type: "text", content: "石畳の壺屋やちむん通りには陶器工房・ギャラリー・雑貨店が軒を連ねます。古くから続く窯元を覗きながら歩くと、沖縄の工芸文化が伝わってきます。カフェや泡盛バーも点在しています。" },
    ],
    relatedArticleSlugs: ["okinawa-kokusai-dori-guide", "okinawa-yachimun-pottery-guide"],
  },
  {
    slug: "okinawa-yaeyama-island-hop",
    title: "八重山島めぐり4日間｜石垣・竹富・西表・波照間の完全ルート",
    description: "八重山諸島の島々をフェリーで繋いだ、日本最南端の旅。竹富・西表・波照間まで足を伸ばす完全ガイド。",
    coverImage: img1,
    publishedAt: "2025-10-28",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "okinawa",
    tags: ["八重山", "石垣島", "竹富島", "西表島", "波照間島"],
    spotIds: ["taketomi-island"],
    sections: [
      { type: "heading", content: "八重山諸島の魅力", level: 2 },
      { type: "text", content: "石垣島を拠点に複数の離島をフェリーで巡る八重山島めぐりは、本島とは全く違う南国の世界を体験できます。竹富島の伝統集落、西表島のジャングル、波照間島の星空は絶品です。" },
      { type: "spot-card", content: "taketomi-island" },
      { type: "heading", content: "4日間の推奨ルート", level: 2 },
      { type: "text", content: "1日目：石垣島着・川平湾・市街地。2日目：竹富島（水牛車・コンドイビーチ）。3日目：西表島（カヤック・仲間川マングローブ）。4日目：波照間島（星空・ニシ浜）→石垣島から帰路。" },
    ],
    relatedArticleSlugs: ["okinawa-taketomi-island-cultural", "okinawa-ishigaki-island-guide"],
  },
  {
    slug: "okinawa-okinawa-war-history-memorial",
    title: "沖縄戦の歴史と平和への祈り｜ひめゆりの塔と平和記念公園を巡る",
    description: "沖縄戦の記憶と平和の誓いを後世に伝えるひめゆりの塔・平和祈念公園・対馬丸記念館の旅案内。",
    coverImage: img2,
    publishedAt: "2025-06-23",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["平和学習", "沖縄戦", "ひめゆり", "平和記念公園", "歴史"],
    spotIds: ["sefa-utaki"],
    sections: [
      { type: "heading", content: "沖縄戦の記憶を受け継ぐ", level: 2 },
      { type: "text", content: "1945年の沖縄戦は民間人を含む多くの命が失われた太平洋戦争最後の激戦地。ひめゆりの塔・平和祈念公園・旧海軍司令部壕などで当時の記録と向き合うことが大切な旅の一部です。" },
      { type: "spot-card", content: "sefa-utaki" },
      { type: "heading", content: "平和記念公園での祈り", level: 2 },
      { type: "text", content: "沖縄本島南端の摩文仁の丘にある平和祈念公園では、「平和の礎（いしじ）」に24万人超の犠牲者の名前が刻まれています。毎年6月23日の「慰霊の日」には厳かな式典が執り行われます。" },
    ],
    relatedArticleSlugs: ["okinawa-ryukyu-history-trail", "okinawa-sefa-utaki-power-spot"],
  },
  {
    slug: "okinawa-kabira-bay-glass-boat",
    title: "川平湾グラスボート体験｜石垣島が誇る世界屈指の美しい入り江",
    description: "ミシュラン三つ星の絶景スポット・川平湾でグラスボートに乗り、エメラルドの海底に広がるサンゴ礁を覗く。",
    coverImage: img1,
    publishedAt: "2025-08-18",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["川平湾", "石垣島", "グラスボート", "ミシュラン", "絶景"],
    spotIds: ["taketomi-island"],
    sections: [
      { type: "heading", content: "ミシュランが認めた絶景", level: 2 },
      { type: "text", content: "石垣島北部に位置する川平湾はミシュランの星を獲得した沖縄最高峰の景観地。遠浅の湾に点在する小島と、太陽の角度で色が変化するエメラルドグリーンの海面が息をのむほどの美しさです。" },
      { type: "spot-card", content: "taketomi-island" },
      { type: "heading", content: "グラスボートでサンゴ礁観察", level: 2 },
      { type: "text", content: "ガラス張りの底から海底のサンゴ礁や熱帯魚を観察できるグラスボートが人気。遊泳禁止ですがグラスボートで海中の世界を楽しめます。所要約30分、料金は大人1200円ほど。石垣空港から車で約40分です。" },
    ],
    relatedArticleSlugs: ["okinawa-ishigaki-island-guide", "okinawa-photography-spots"],
  },
  {
    slug: "okinawa-uminchu-fishing-experience",
    title: "沖縄の海人（うみんちゅ）文化体験｜素潜りと漁師飯に出会う旅",
    description: "沖縄の漁師文化「海人」に触れ、素潜りや地引き網体験と新鮮な漁師飯をいただく特別な体験旅行。",
    coverImage: img3,
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "okinawa",
    tags: ["海人", "漁師体験", "素潜り", "地引き網", "海の幸"],
    spotIds: ["zamami-island", "kokusai-dori"],
    sections: [
      { type: "heading", content: "海人文化と海の幸", level: 2 },
      { type: "text", content: "沖縄の漁師「海人（うみんちゅ）」は古くから豊かな海の恵みを支える存在。地引き網体験や素潜り見学ができる漁業体験ツアーが本島各地で開催されています。" },
      { type: "spot-card", content: "zamami-island" },
      { type: "heading", content: "新鮮な漁師料理を堪能", level: 2 },
      { type: "text", content: "体験後はその日水揚げされた魚介の刺身や汁物をいただける民宿・食堂も。グルクン（国魚）の唐揚げや、イセエビのお刺身など沖縄ならではの海の幸を楽しめます。" },
    ],
    relatedArticleSlugs: ["okinawa-zamami-island-diving", "okinawa-soba-guide"],
  },
  {
    slug: "okinawa-shisa-village-ryukyu-mura",
    title: "琉球村で体感する沖縄の原風景｜古民家・伝統芸能・黒糖作りを1日満喫",
    description: "恩納村の琉球村で古民家移築・エイサー・三線・黒糖作り体験と沖縄の生きた文化に全身で触れる旅。",
    coverImage: img3,
    publishedAt: "2025-04-08",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "okinawa",
    tags: ["琉球村", "体験", "エイサー", "黒糖", "伝統文化"],
    spotIds: ["shurijo", "manza-mo"],
    sections: [
      { type: "heading", content: "琉球村で過ごす昔の沖縄", level: 2 },
      { type: "text", content: "恩納村の琉球村は、県内各地から移築した江戸〜明治期の古民家を展示する体験型テーマパーク。黒糖作り・藍染め・機織り・ハブ酒工場見学など、沖縄の伝統文化を直接体験できます。" },
      { type: "spot-card", content: "manza-mo" },
      { type: "heading", content: "エイサーショーと三線体験", level: 2 },
      { type: "text", content: "毎日複数回開催されるエイサーショーは迫力満点。三線や琉球舞踊の体験教室も好評です。家族連れから大人まで楽しめる施設で、沖縄の文化的理解が格段に深まります。那覇から車で約50分。" },
    ],
    relatedArticleSlugs: ["okinawa-ryukyu-dance-music", "okinawa-manza-mo-cliff-walk"],
  },
];
