import { Article } from "@/types/article";

export const osakaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "osaka-dotonbori-night-walk",
    title: "道頓堀、夜22時からが本番──グリコ看板より先の路地を歩く",
    description: "観光客が引き上げた後、道頓堀は別の顔を見せる。地元民が行く屋台と、深夜限定の串カツ屋がある。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-01-18",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "osaka",
    tags: ["道頓堀", "夜遊び", "ナイトライフ", "大阪"],
    spotIds: ["dotonbori"],
    sections: [
      { type: "heading", content: "グリコ看板の先に本当の道頓堀がある", level: 2 },
      { type: "text", content: "午後10時を過ぎると、道頓堀の人口密度は半分になる。その代わり残るのは地元の飲み客と、本気の食い倒れ族だ。戎橋を渡って西へ進み、法善寺横丁に入ると空気が変わる。石畳が濡れていると特に美しい。" },
      { type: "heading", content: "「たこ焼き道楽わなか」は深夜2時まで", level: 2 },
      { type: "text", content: "観光地のたこ焼き屋の多くは22時で閉まるが、わなかは例外。外はカリカリ、中は半熟のトロトロ。出汁の利いたソースと青のりで完成する一皿600円は、深夜の道頓堀で食べると倍旨い。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "締めは「金龍ラーメン」で豚骨一択", level: 2 },
      { type: "text", content: "24時間営業の金龍ラーメンは、道頓堀の〆文化を象徴する店。豚骨スープは濃く、麺は細め。キムチと白ネギは食べ放題。深夜帯でも行列ができるが、回転は早い。大阪の夜を完走するにはここで終わるべきだ。" },
    ],
    relatedArticleSlugs: ["osaka-shinsekai-retro-walk", "osaka-street-food-tour"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "osaka-shinsekai-retro-walk",
    title: "新世界は昭和の標本箱──通天閣を無視して路地に入れ",
    description: "通天閣の行列に並ぶ必要はない。新世界の真価はジャンジャン横丁の焼き鳥屋台と、昭和のまま止まったゲームセンターにある。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-02-12",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "osaka",
    tags: ["新世界", "レトロ", "串カツ", "大阪", "昭和"],
    spotIds: ["shinsekai"],
    sections: [
      { type: "heading", content: "ジャンジャン横丁は11時から開く", level: 2 },
      { type: "text", content: "新世界の南側、ジャンジャン横丁は午前11時になると串カツ屋が一斉に暖簾を出す。幅2メートルの路地に串カツの煙が充満し、どこに入っても大差ない——と思いきや、「づぼらや」跡地の向かいにある無名の立ち飲み店は常連だけが知る逸品を出す。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "串カツの二度漬け禁止は本当に守られている", level: 2 },
      { type: "text", content: "「だるま」の元祖串カツは衣がサクサクで薄い。ソースの二度漬けは本当に怒られる——これは観光演出ではなく、衛生上の本気のルール。キャベツでソースをかけ、一口で食べ切るのが正しい作法。" },
      { type: "heading", content: "昭和のゲームセンターで時間を溶かす", level: 2 },
      { type: "text", content: "通天閣の足元に残るゲームセンターは、メダルゲームと麻雀卓が混在する。観光客より地元の年配者が多く、午後の陽光の中でコインを入れ続ける彼らの横顔が、新世界の本質を語っている。" },
    ],
    relatedArticleSlugs: ["osaka-dotonbori-night-walk", "osaka-budget-eats-guide"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "osaka-street-food-tour",
    title: "大阪ストリートフード完全ガイド──たこ焼き・串カツ・かすうどんの正解店",
    description: "大阪の食い倒れ文化は路上にある。有名店より、地元民が毎週通う店を選ぶ基準を教える。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["たこ焼き", "串カツ", "グルメ", "大阪", "街歩き"],
    spotIds: ["dotonbori"],
    sections: [
      { type: "heading", content: "たこ焼きは西成の「明石焼き屋」で食べ直せ", level: 2 },
      { type: "text", content: "道頓堀のたこ焼きはソース派が多いが、大阪人が本当に好きなのは出汁に浸けて食べる明石焼きスタイル。西成区の「あっちゃん」は地元民でいつも満席。卵たっぷりのふわふわ生地を、薄い昆布だしに沈めて食べる体験は、道頓堀では味わえない。" },
      { type: "heading", content: "かすうどんは泉大津まで足を延ばす価値がある", level: 2 },
      { type: "text", content: "牛の小腸を油で揚げた「油かす」を乗せるかすうどんは、大阪南部のソウルフード。泉大津の「かすうどん正」は、油かすをその場で揚げる。コシのある麺にコクのあるスープ、サクサクの油かすが合わさった一杯は、大阪グルメの新定番として広まりつつある。" },
      { type: "heading", content: "天満市場の朝ごはんで始める一日", level: 2 },
      { type: "text", content: "大阪天満宮の北側に広がる天満市場は、午前6時から開く。鮮魚、野菜、惣菜が並ぶ中を歩いて、路地の定食屋で650円の朝定食を食べる。玉子焼き・焼き魚・白飯・味噌汁。シンプルだが、これが大阪の朝だ。" },
    ],
    relatedArticleSlugs: ["osaka-dotonbori-night-walk", "osaka-morning-market"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "osaka-spring-sakura-spots",
    title: "大阪の桜穴場5選──造幣局「桜の通り抜け」だけじゃない春の歩き方",
    description: "造幣局の行列は毎年2時間超え。同じ週に、もっと静かで美しい桜を見る方法がある。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-03-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "osaka",
    tags: ["桜", "春", "穴場", "大阪", "花見"],
    spotIds: [],
    sections: [
      { type: "heading", content: "毛馬桜之宮公園は早朝に限る", level: 2 },
      { type: "text", content: "大川沿いに4.2kmつづく毛馬桜之宮公園は、大阪最長の桜並木。午前7時台は犬の散歩をする地元民しかいない。屋台が並び始める昼前とは別世界で、ベンチに座って川面を眺めるだけで1時間が溶ける。" },
      { type: "heading", content: "長居植物園の八重桜は4月中旬まで楽しめる", level: 2 },
      { type: "text", content: "染井吉野が散った後、長居植物園の八重桜が見頃を迎える。ボタン桜・関山・一葉など品種が多く、色の濃淡も様々。入園料280円で、混雑ゼロのゆっくりした花見ができる。" },
      { type: "heading", content: "大阪城公園の西の丸庭園は夜桜が格別", level: 2 },
      { type: "text", content: "大阪城の東側は常に混雑しているが、西の丸庭園（入場300円）は比較的空いている。ライトアップ期間中の夜桜は、城をバックにした写真が撮れる数少ない場所。17時以降に入り、暗くなるまで待つのが正解。" },
    ],
    relatedArticleSlugs: ["osaka-photo-spots-guide", "osaka-seasonal-summer-fireworks"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "osaka-seasonal-summer-fireworks",
    title: "大阪の夏祭りと花火──PL花火・なにわ淀川・天神祭の賢い見方",
    description: "花火大会は場所取りが命。3大花火の穴場スポットと、混雑を回避するタイムラインを公開する。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "osaka",
    tags: ["花火", "夏祭り", "天神祭", "大阪", "夏"],
    spotIds: [],
    sections: [
      { type: "heading", content: "天神祭の船渡御は橋の上から見るな", level: 2 },
      { type: "text", content: "7月25日の天神祭奉納花火は、天満橋の上は激混み。代わりに、OMMビル屋上の有料観覧席（事前予約制）か、川沿いのマンション住民向けに開放される岸辺スペースを狙う。大川に映る花火の逆さ富士が見どころ。" },
      { type: "heading", content: "PL花火は富田林駅から20分歩く覚悟で", level: 2 },
      { type: "text", content: "PL花火芸術は打ち上げ数より音と規模が圧倒的。近鉄富田林駅から会場まで徒歩20分、帰りは1時間以上並ぶのがデフォルト。スニーカーと折りたたみ椅子と水2リットルは必需品。終了後すぐに動かず、20分待って人波が引いてから動くのが正解。" },
      { type: "heading", content: "なにわ淀川花火は梅田スカイビルから俯瞰する", level: 2 },
      { type: "text", content: "淀川沿いの公式会場は有料エリアが拡大しているが、梅田スカイビルの空中庭園（展望台入場料1500円）から見下ろす花火も絶景。遠景ではあるが風もなく、飲食しながら花火を見られる快適さは有料会場にはない。" },
    ],
    relatedArticleSlugs: ["osaka-spring-sakura-spots", "osaka-couple-osaka-night"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "osaka-morning-market",
    title: "大阪の朝市3選──天満・鶴橋・木津で地元民と肩を並べて食べる朝",
    description: "大阪人は朝から食べることに本気だ。市場の朝は、観光ガイドには載らない大阪の食文化の核にある。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["朝市", "天満市場", "鶴橋", "グルメ", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "天満市場は大阪最古の公設市場", level: 2 },
      { type: "text", content: "天神橋筋商店街の東側に隣接する天満市場は、江戸時代から続く青空市場の系譜。午前6時から業者の仕入れが始まり、7時ごろから一般客も入れる。鮮魚店「東大水産」の浜焼きは、炭火の香りが路地まで漂ってくる。" },
      { type: "heading", content: "鶴橋市場のコリアンタウンで朝キムチを買う", level: 2 },
      { type: "text", content: "鶴橋駅を出ると、焼き肉の煙と発酵食品の香りが混ざった独特の空気が漂う。市場の路地を奥に進むと、早朝から白菜キムチを漬け込む店がある。1kg800円〜の樽売りキムチは、大阪土産として持ち帰り可能なサイズに小分けしてもらえる。" },
      { type: "heading", content: "木津卸売市場の「市場食堂」で朝定食", level: 2 },
      { type: "text", content: "難波から南へ徒歩15分の木津卸売市場は、一般客も入れる穴場スポット。市場内の食堂は午前5時半から営業。海鮮丼950円、焼き魚定食700円。仲買人と並んで食べる朝食は、観光の文脈を離れた本物の大阪体験だ。" },
    ],
    relatedArticleSlugs: ["osaka-street-food-tour", "osaka-budget-eats-guide"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "osaka-budget-eats-guide",
    title: "大阪1日1,500円食費で生き延びる──節約グルメの完全ルート",
    description: "食い倒れの街で財布を守る。うまい・安い・多いの三拍子が揃う店だけを厳選した。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "osaka",
    tags: ["節約", "格安グルメ", "大阪", "バジェット旅", "一人旅"],
    spotIds: ["shinsekai"],
    sections: [
      { type: "heading", content: "朝：鶴橋の立ち食い寿司で400円", level: 2 },
      { type: "text", content: "鶴橋市場の立ち食い寿司「市場寿司」は、1皿2貫100円から。朝8時に開く。地元の市場関係者と並んで食べる鮮度抜群の寿司は、銀座の高級店より鮮烈な体験を与えてくれる。4皿食べて400円。" },
      { type: "heading", content: "昼：天神橋筋商店街の立ち食いうどん300円", level: 2 },
      { type: "text", content: "日本一長い商店街、天神橋筋6丁目には立ち食いうどん店が10軒以上ある。「麺ふく」のかすうどんは350円。油かすのコクがスープに溶け出し、安いのに圧倒的な満足感がある。昼のピーク時でも5分待てば座れる。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "夜：新世界の串カツ2本でビール1杯", level: 2 },
      { type: "text", content: "新世界で最も安いのはジャンジャン横丁の無名立ち飲み店。串カツ1本80円、生ビール中300円。予算700円でしっかり飲んで食べられる。〆に「八重勝」の串カツ5本盛り500円で締めれば、夜の食費は1,200円以内に収まる。" },
    ],
    relatedArticleSlugs: ["osaka-shinsekai-retro-walk", "osaka-solo-backpacker"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "osaka-luxury-dining",
    title: "大阪の贅沢食い倒れ──ミシュラン星付きより「なんば」の高級割烹が正解な理由",
    description: "東京と同じ値段を出すなら、大阪では別次元の料理が食べられる。なんば・北浜・本町の贅沢ルートを案内する。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "osaka",
    tags: ["高級グルメ", "割烹", "贅沢旅", "大阪", "ミシュラン"],
    spotIds: [],
    sections: [
      { type: "heading", content: "北浜「たに川」のランチは1万円以下の奇跡", level: 2 },
      { type: "text", content: "北浜の土佐堀川沿いに建つ「たに川」は、大阪懐石の正統。昼の松花堂弁当コース8,800円は、東京で同等の料理を食べると倍の値段になる。季節の食材を使った椀物は、この店の真骨頂。予約は1週間前から電話のみ。" },
      { type: "heading", content: "本町「山田屋」の天ぷらカウンターで揚げたてを食べる", level: 2 },
      { type: "text", content: "本町のオフィス街に紛れるように存在する「山田屋」の天ぷらカウンターは、全7席。大将が一人で揚げ、順に出す。穴子・車海老・ハモのコース12,000円は、素材の違いが如実に出る。カウンター越しに大将と会話しながら食べるのが作法。" },
      { type: "heading", content: "〆は法善寺横丁「めおと善哉」で", level: 2 },
      { type: "text", content: "贅沢な食事の後、法善寺横丁の「めおと善哉」で小豆ぜんざいを食べる。文楽の世界から続く老舗で、夫婦セット（2椀）1,200円。コースの重厚さを洗い流す甘さと、苔むした提灯の光の中の静けさが、大阪の夜を完成させる。" },
    ],
    relatedArticleSlugs: ["osaka-couple-osaka-night", "osaka-dotonbori-night-walk"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "osaka-family-kids-spots",
    title: "子連れ大阪3日間モデルコース──USJを使わずに子どもを喜ばせる方法",
    description: "USJのチケットは高い。大阪には子どもが本当に興奮する場所が、入場無料でいくつもある。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-08-05",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "osaka",
    tags: ["子連れ旅", "ファミリー", "無料スポット", "大阪", "子ども"],
    spotIds: [],
    sections: [
      { type: "heading", content: "大阪市立科学館：プラネタリウムは幼児も寝ない", level: 2 },
      { type: "text", content: "肥後橋にある大阪市立科学館のプラネタリウムは、日本最大級の投影径20m。大阪の空の解説から始まり、宇宙の果てまで連れて行かれる50分間。4歳から楽しめると言われるが、2歳でも画面を指さして声を上げる子どもを何人も見た。入場料400円。" },
      { type: "heading", content: "海遊館のジンベエザメは子どもの語彙を増やす", level: 2 },
      { type: "text", content: "大阪港の海遊館は入場料2,400円と高めだが、太平洋水槽のジンベエザメ展示は日本最大級。8mのジンベエザメが目の前を通過するとき、子どもは必ず何か叫ぶ。水族館は体験型の図鑑だ。平日午前9時の開館と同時に入ると混雑なしで見られる。" },
      { type: "heading", content: "長居公園の自然史博物館で化石を掘る体験", level: 2 },
      { type: "text", content: "大阪市立自然史博物館（入場300円）のナウマンゾウ全身骨格は、子どもより大人が興奮する展示。土日に開催される「化石発掘体験」ワークショップ（別途500円）は、実際に石を砕いて化石を見つける作業が体験できる。事前予約が必要。" },
    ],
    relatedArticleSlugs: ["osaka-family-aquarium-port", "osaka-rainy-day-osaka"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "osaka-family-aquarium-port",
    title: "大阪港エリア半日コース──海遊館→天保山→サンタマリアで海と遊ぶ",
    description: "大阪は海の街でもある。港エリアを半日かけて回ると、子どもも大人も全員満足する。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "osaka",
    tags: ["大阪港", "海遊館", "ファミリー", "子連れ旅", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "天保山の観覧車は世界最大級の高さ112m", level: 2 },
      { type: "text", content: "海遊館の隣にある天保山大観覧車は、夜間ライトアップも美しいが、昼間は大阪湾と六甲山が両方見える。1周15分600円。ゴンドラが透明なシースルーキャビンもあり、恐怖を楽しみたい子どもに人気がある。" },
      { type: "heading", content: "帆船サンタマリアで大阪湾クルーズ45分", level: 2 },
      { type: "text", content: "天保山ハーバービレッジから出発するサンタマリア号は、コロンブスの旗艦を模した帆船型観光船。大人1,800円、子ども900円で45分のクルーズ。船上から見る大阪のスカイラインは陸上とは別物で、海風の中で飲む缶コーヒーの味まで変わる。" },
      { type: "heading", content: "MEGA WEBマーケットプレイスで昼食を", level: 2 },
      { type: "text", content: "天保山マーケットプレイス内のフードコートは、選択肢が多く子連れに優しい。たこ焼き・回転寿司・ラーメンが一か所に集まり、家族バラバラの要望を一度に満たせる。窓から大阪港を眺めながら食べられる席を確保したい。" },
    ],
    relatedArticleSlugs: ["osaka-family-kids-spots", "osaka-couple-osaka-night"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "osaka-couple-osaka-night",
    title: "カップルで泊まる大阪──北浜のリバービューホテルと夜景ディナーの完全プラン",
    description: "大阪をデートで使い倒す方法を知っている人は少ない。北浜・中之島の水辺は、夜になると東京より美しくなる。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "osaka",
    tags: ["カップル旅", "夜景", "北浜", "中之島", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "北浜「コンラッド大阪」の川側客室を必ずリクエスト", level: 2 },
      { type: "text", content: "コンラッド大阪は33〜57階のスーパーハイフロアホテル。土佐堀川と淀川が見える東側客室は、夜になるとネオンの反射が水面に広がり、映画のワンシーンのような光景になる。宿泊予約時に「リバービュー希望」と備考を入れるとほぼ通る。" },
      { type: "heading", content: "中之島バラ園の夕暮れ散歩は無料", level: 2 },
      { type: "text", content: "大阪市中央公会堂の裏手、中之島公園のバラ園は5月と10月が見頃。入場無料で、250種4,000株のバラが咲き乱れる。夕方17時以降はカップルが多く、ライトアップはないが沈む夕日がバラを赤く染める。" },
      { type: "heading", content: "リバービューディナーは「HAJIME」か「カハラ」で", level: 2 },
      { type: "text", content: "中之島の「HAJIME」は世界のベストレストラン50入りの実績がある大阪が誇るフレンチ。完全予約制でコース18,000円〜。予算を抑えるなら同じく川沿いの「カハラ大阪」の月替わりイタリアンコース8,800円が、対コスパで大阪ナンバーワンと言っていい。" },
    ],
    relatedArticleSlugs: ["osaka-luxury-dining", "osaka-photo-spots-guide"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "osaka-couple-retro-date",
    title: "昭和レトロデート──新世界・飛田新地周辺・阿倍野のノスタルジックを歩く",
    description: "大阪には昭和の気配が色濃く残る街がある。カップルで歩くと、不思議と距離が縮まる街の話。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-11-08",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "osaka",
    tags: ["レトロ", "カップル旅", "昭和", "阿倍野", "大阪"],
    spotIds: ["shinsekai"],
    sections: [
      { type: "heading", content: "あべのハルカスと高さ300mの現実から離れる", level: 2 },
      { type: "text", content: "日本一の高さを誇るあべのハルカスから下りて、南側の旧市街を歩くと30分で昭和初期の景観が残る路地に出る。昭和薬科大学脇の商店街は今でもシャッターが少なく、八百屋・豆腐屋・金物屋が現役で営業している。" },
      { type: "spot-card", content: "shinsekai" },
      { type: "heading", content: "新世界のカフェ「喫茶アメリカン」で昭和の珈琲を飲む", level: 2 },
      { type: "text", content: "通天閣の真下にある「喫茶アメリカン」は1950年代の内装をほぼそのまま維持している。コーヒー480円、モーニングセット680円。木製の回転椅子と焦げた珈琲の匂いが混ざった空間で、しばらく何も喋らなくても気まずくない。" },
      { type: "heading", content: "阿倍野筋の商店街で縁日みたいな夜を過ごす", level: 2 },
      { type: "text", content: "阿倍野橋を渡って北上すると阿倍野筋1〜4丁目に昔ながらの商店街が連続する。秋の夕方は縁日の匂いがして、たこ焼き屋の煙と金木犀の香りが混ざる。大阪らしい雑多さと人の密度は、カップルの距離をいつの間にか縮める。" },
    ],
    relatedArticleSlugs: ["osaka-shinsekai-retro-walk", "osaka-spring-sakura-spots"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "osaka-solo-backpacker",
    title: "一人で大阪を歩き倒す──ゲストハウス・立ち飲み・深夜映画の孤独な贅沢",
    description: "一人旅で大阪に来た人間が享受できる自由は、グループ旅行では絶対に手に入らない。深夜の立ち飲みと朝の銭湯を軸にした一人旅のかたち。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-02-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "osaka",
    tags: ["一人旅", "バックパッカー", "立ち飲み", "ゲストハウス", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "ゲストハウスはなんばと西成を比較検討せよ", level: 2 },
      { type: "text", content: "なんばのゲストハウスは便利だが、1泊2,500〜3,500円。西成エリア（萩之茶屋）のゲストハウスは1,800〜2,500円で、地元民との距離が近い。清潔で設備が整った宿も増えており、「Guesthouse HIVE」は外国人一人旅客にも定評がある。" },
      { type: "heading", content: "立ち飲みは天満の「松葉」で始まる", level: 2 },
      { type: "text", content: "天満駅の高架下に続く立ち飲み横丁は、一人でも入りやすい空間。「松葉」はホルモン焼きが絶品で、おばちゃんが仕切るカウンターは見知らぬ客同士が10分で会話し始める。ビール中瓶400円、ホルモン塩一人前500円。予算1,500円で2時間過ごせる。" },
      { type: "heading", content: "深夜0時の「シネ・リーブル梅田」でアート映画を", level: 2 },
      { type: "text", content: "梅田ブルク7の隣にあるシネ・リーブル梅田は、深夜上映が充実している。一人旅の夜、見知らぬ街で見るアート映画は記憶の定着が違う。ミニシアター特有の静けさと、上映後に外の夜風に当たる瞬間が、一人旅の醍醐味だ。" },
    ],
    relatedArticleSlugs: ["osaka-budget-eats-guide", "osaka-solo-sento-morning"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "osaka-solo-sento-morning",
    title: "大阪の銭湯一人旅──朝6時開店の老舗銭湯で始める旅の朝",
    description: "大阪には今も100円台で入れる銭湯が残っている。朝の銭湯は、一人旅の日課にするべき習慣だ。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "osaka",
    tags: ["銭湯", "一人旅", "朝活", "大阪", "レトロ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "大阪の銭湯料金は490円（2025年現在）", level: 2 },
      { type: "text", content: "東京の520円より安い大阪の銭湯は、今でも旅人の味方だ。西成・今里・鶴橋エリアに集中する昭和建築の銭湯は、外観からして価値がある。特に今里の「弁天温泉」は大正時代の宮造り建築が残り、写真家にも人気の場所だ。" },
      { type: "heading", content: "「千代の湯」（西成）は朝6時から人が集まる", level: 2 },
      { type: "text", content: "西成の「千代の湯」は午前6時開店。常連のお爺さんたちが7時にはもう帰っていく。熱湯・ぬる湯・薬草湯の3種類があり、地元民の会話に混じって湯に浸かる30分は、観光では絶対に得られない大阪体験だ。石鹸・シャンプーは持参が前提。" },
      { type: "heading", content: "銭湯後の朝食は近くの喫茶店のモーニングで", level: 2 },
      { type: "text", content: "大阪の喫茶店のモーニングは、コーヒー代（350〜400円）だけでトースト・ゆで卵・サラダがつくのが相場。銭湯から徒歩5分以内に必ず一軒はある。汗を流した後のブレンドコーヒーとトーストは、旅の朝として完璧な組み合わせだ。" },
    ],
    relatedArticleSlugs: ["osaka-solo-backpacker", "osaka-retro-photography"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "osaka-craft-beer-guide",
    title: "大阪クラフトビール完全ガイド──醸造所直営タップルームから角打ちまで",
    description: "大阪のビールシーンは5年で急変した。今や大阪だけで30以上のブルワリーが稼働している事実を、ビール好きは知っておくべきだ。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-04-25",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["クラフトビール", "ブルワリー", "グルメ", "大阪", "地ビール"],
    spotIds: [],
    sections: [
      { type: "heading", content: "「MINOH BEER Pub W」は箕面ブルワリーの直営店", level: 2 },
      { type: "text", content: "箕面ビールは大阪クラフトビールの先駆者。梅田から阪急で30分の箕面にある直営タップルームは、常時10種類以上のクラフトビールをサーブ。エクストラペールエール（ABV5.5%）は年間通じての定番で、柑橘系の香りと軽い苦みが食事と合わせやすい。" },
      { type: "heading", content: "北浜「BEER BELLY北浜」は平日のビジネスマンが集まる店", level: 2 },
      { type: "text", content: "北浜のオフィス街に溶け込む「BEER BELLY」は、18時からサラリーマンで埋まる。バレルエイジドやサワーエールなど実験的なビールが多く、スタッフの知識も深い。グラス700〜900円で飲み比べができる「テイスター3種セット」が初訪問にベスト。" },
      { type: "heading", content: "西区「蔵前通り」のクラフトビール角打ちで地元民と飲む", level: 2 },
      { type: "text", content: "西区にある酒屋「かど酒店」は、クラフトビール冷蔵庫を持つ角打ち営業が評判。店内で購入した缶ビールをその場で開けて飲めるシステムで、350ml450〜600円。夕方5時から地元の工務店の兄ちゃんと隣に並んで飲むのが大阪流の贅沢だ。" },
    ],
    relatedArticleSlugs: ["osaka-solo-backpacker", "osaka-dotonbori-night-walk"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "osaka-rainy-day-osaka",
    title: "雨の大阪で一日過ごす──屋根がある場所だけを繋いだ雨天完全コース",
    description: "大阪は雨の日に最強の街だ。地下街・商店街・アーケードが網の目のように繋がり、傘を差さずに何時間でも過ごせる。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "osaka",
    tags: ["雨天対策", "室内スポット", "地下街", "大阪", "梅雨"],
    spotIds: [],
    sections: [
      { type: "heading", content: "梅田地下街「ホワイティうめだ」は迷路で正解", level: 2 },
      { type: "text", content: "梅田の地下街は世界的に見ても最大規模に属する。特にホワイティうめだとディアモールを繋ぐルートは、総延長4km以上の屋内歩行空間になる。雨の日は地下だけで梅田→なんば間を移動できる——実はJRとメトロを乗り継がなくても、御堂筋線の地下と繋がっている。" },
      { type: "heading", content: "天神橋筋商店街は全長2.6kmのアーケード", level: 2 },
      { type: "text", content: "日本最長のアーケード商店街は雨の日に真価を発揮する。古本屋、駄菓子屋、喫茶店、八百屋が混在する2.6kmを歩くだけで半日かかる。途中の「千成屋珈琲」でアイスコーヒーを飲んで休憩し、また歩く。傘要らずで完全に一日を過ごせる。" },
      { type: "heading", content: "なんばCITY地下から海遊館まで傘なしで行けるルート", level: 2 },
      { type: "text", content: "なんばCITY地下→なんばウォーク→御堂筋線（大国町乗換）→大阪港→シャトルバス→海遊館、という経路は雨天でも濡れずに移動できる。知っている人だけが使う大阪の雨天攻略。帰りは海遊館内のカフェで時間を潰せるため、タクシー不要。" },
    ],
    relatedArticleSlugs: ["osaka-family-kids-spots", "osaka-tips-osaka-transport"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "osaka-tips-osaka-transport",
    title: "大阪交通完全攻略──ICOCAとOsaka Metroパスで移動費を半分にする",
    description: "大阪の交通網は複雑に見えて、正しいパスを買えば観光コストが大幅に下がる。知らないと損する乗り放題チケットを整理した。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-01-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "osaka",
    tags: ["交通", "節約", "旅のコツ", "大阪", "ICOCAパス"],
    spotIds: [],
    sections: [
      { type: "heading", content: "「大阪周遊パス」は1日2,800円で地下鉄乗り放題＋施設入場無料", level: 2 },
      { type: "text", content: "Osaka Metro全線乗り放題に加え、大阪城天守閣・海遊館割引・通天閣など30施設以上の入場料が含まれる大阪周遊パスは、観光客向けに設計されたコスパ最強のチケット。1日版2,800円、2日版3,600円。入場施設を3つ回れば元が取れる計算。" },
      { type: "heading", content: "阪急・阪神・近鉄は別会社、ICOCAで統一が正解", level: 2 },
      { type: "text", content: "大阪は地下鉄（Osaka Metro）・阪急・阪神・近鉄・南海・JRが入り乱れる。それぞれ別会社のため、チケットを買い直す手間が生じる。ICOCAをひとつ持てば全路線でタッチアンドゴーが使える。チャージは駅の機械より、7-11のATMが手数料不要で効率的。" },
      { type: "heading", content: "梅田〜なんばは徒歩22分、実は歩ける距離", level: 2 },
      { type: "text", content: "梅田（大阪駅）となんばは地下鉄で3分だが、御堂筋を南に歩くと22分。御堂筋のイチョウ並木（秋は黄葉）を眺めながら歩く道は、大阪の都市景観を理解する最適な経路だ。雨以外の日は乗り放題パスを温存するために歩くことを勧める。" },
    ],
    relatedArticleSlugs: ["osaka-rainy-day-osaka", "osaka-budget-eats-guide"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "osaka-photo-spots-guide",
    title: "大阪フォトスポット完全ガイド──SNSに頼らない自分だけの撮影場所を見つける方法",
    description: "グリコ看板の前で撮影するだけが大阪写真ではない。知られていない絶景ポイントと、光の読み方を解説する。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "osaka",
    tags: ["写真", "フォトスポット", "撮影", "大阪", "インスタ映え"],
    spotIds: ["dotonbori"],
    sections: [
      { type: "heading", content: "道頓堀を「下から」撮る──川面の反射が主役", level: 2 },
      { type: "text", content: "グリコ看板の正面ではなく、戎橋を渡りきった後に川沿いの遊歩道「とんぼりリバーウォーク」に下りる。水面に映るネオンと、看板の上部が切り取れる角度は、橋の上からは絶対に撮れないアングルだ。三脚不要、ISO800で手持ち撮影できる光量がある。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "中之島リーガロイヤルホテル前の橋は朝靄が出る", level: 2 },
      { type: "text", content: "秋冬の朝6時〜7時、中之島の肥後橋周辺で川面に靄が立ち込める日がある。リーガロイヤルホテルのクラシックなファサードと、靄の中に浮かぶ橋灯が重なる構図は大阪写真の隠れた名シーン。気温差が10度以上ある日の翌朝に期待値が上がる。" },
      { type: "heading", content: "通天閣の「足元」を撮る新世界の路地", level: 2 },
      { type: "text", content: "通天閣を「見上げる」写真より、周辺の路地から「額縁」として通天閣を収める構図が面白い。恵美須町から北に伸びる縦路地は、昭和の建物と現代の塔が重なるレイヤード感がある。夕方4〜5時の斜光が路地に差し込む時間帯が最も立体感が出る。" },
    ],
    relatedArticleSlugs: ["osaka-retro-photography", "osaka-couple-osaka-night"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "osaka-retro-photography",
    title: "レトロ大阪を撮る──フィルムカメラで歩く西成・鶴橋・天満の路地裏",
    description: "デジタルで撮っても伝わらない大阪の古層は、フィルムカメラを持って路地裏を歩くと見えてくる。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-07-30",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "osaka",
    tags: ["フィルム写真", "路地裏", "西成", "鶴橋", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "西成・動物園前の「凪」の空気感", level: 2 },
      { type: "text", content: "動物園前交差点から北西に伸びる商店街は、昼過ぎに独特の静けさが漂う。月曜定休の店が多く、看板が傾いたまま残り、昭和の広告が色褪せて壁に残っている。フィルムで撮ると粒状感がこの街の空気にフィットする。Kodak Ultramax 400が推奨。" },
      { type: "heading", content: "鶴橋のスナップは午前10時〜正午がゴールデンタイム", level: 2 },
      { type: "text", content: "鶴橋市場の横断歩道橋の上から見下ろす迷路状の市場路地は、午前中が最も活気がある。魚を担ぐ人、段ボールを積む台車、ハングル文字の看板が混在する場所で、50mm標準レンズが一番正直に街を写す。シャッター速度は1/250以上で止めること。" },
      { type: "heading", content: "天満の高架下にフィルム写真の被写体が集まっている", level: 2 },
      { type: "text", content: "JR天満駅高架下は飲み屋街と路地の集合体。夕方5時以降に増える居酒屋の赤提灯と、高架の鉄骨が作る影の交差が絵になる。FujiFilm PRO400Hのオーバー気味の現像が、この場所の湿度と熱を最もよく表現してくれる。" },
    ],
    relatedArticleSlugs: ["osaka-solo-sento-morning", "osaka-photo-spots-guide"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "osaka-onsen-day-trip",
    title: "大阪から日帰り温泉3選──有馬・犬鳴山・天然温泉スパワールド",
    description: "大阪市内から1時間以内で本格温泉に入れる。街の喧騒をリセットしたい日の選択肢を揃えた。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "osaka",
    tags: ["温泉", "日帰り温泉", "有馬温泉", "大阪", "リラックス"],
    spotIds: [],
    sections: [
      { type: "heading", content: "有馬温泉は神戸経由で梅田から75分", level: 2 },
      { type: "text", content: "日本最古の温泉地のひとつ、有馬温泉へはJR大阪から新神戸乗換で特急グリーンで75分。金泉（鉄分が多い褐色のお湯）と銀泉（炭酸水素塩泉）の2種類が楽しめる「金の湯」「銀の湯」は日帰り入浴可能。金の湯650円、銀の湯550円。炭酸せんべいは土産に最適。" },
      { type: "heading", content: "犬鳴山温泉は大阪府内の秘湯", level: 2 },
      { type: "text", content: "南海電鉄の泉佐野駅からバスで25分、大阪府泉佐野市の山中に犬鳴山温泉がある。渓谷沿いに温泉宿が7軒並び、最も歴史ある「山乃湯」は日帰り入浴600円。弱アルカリ性単純温泉で、肌がすべすべになる。周辺の滝の遊歩道も整備されており、温泉前の散歩に最適。" },
      { type: "heading", content: "スパワールドは難波から徒歩10分の異空間", level: 2 },
      { type: "text", content: "新世界の南端にあるスパワールドは、世界12か国の風呂文化を再現した巨大温浴施設。1,200円で深夜まで滞在できる。ヨーロッパゾーンとアジアゾーンが月替わりで男女入れ替えになり、常に新鮮。岩盤浴・プール・レストランが全て入っているため、雨の日の半日籠り先としても最適。" },
    ],
    relatedArticleSlugs: ["osaka-solo-sento-morning", "osaka-rainy-day-osaka"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "osaka-autumn-colors",
    title: "大阪の紅葉穴場──万博記念公園・箕面滝・勝尾寺の11月を歩く",
    description: "大阪で紅葉を見るなら万博記念公園か箕面が二択。しかし行き方と時間帯を間違えると、混雑だけが残る。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-11-18",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "osaka",
    tags: ["紅葉", "秋", "箕面", "万博記念公園", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "万博記念公園の紅葉は11月中旬が見頃", level: 2 },
      { type: "text", content: "モノレールで万博記念公園駅下車すぐの公園は、260haの広大な敷地に紅葉樹が点在する。太陽の塔との組み合わせで撮る紅葉写真は、日本では大阪にしかない構図だ。入場料260円。平日の午前中は家族連れが少なく、ゆっくり回れる。" },
      { type: "heading", content: "箕面の滝道は片道4kmの紅葉トンネル", level: 2 },
      { type: "text", content: "阪急箕面駅から箕面大滝まで片道4km、標高差60mの緩やかな遊歩道が続く。カエデとモミジが道の両側を覆い、11月第2〜3週は完全に紅葉のトンネルになる。往復2時間。週末の昼は混雑するので、平日か土曜の午前9時前に箕面駅をスタートすること。" },
      { type: "heading", content: "勝尾寺のダルマと紅葉の組み合わせは唯一無二", level: 2 },
      { type: "text", content: "箕面の山の中に建つ勝尾寺は、境内いたる所に小さなダルマが奉納されている。紅葉の赤とダルマの赤が重なる11月の境内は、日本の秋の象徴的な景観のひとつ。入山料400円。箕面駅からバスで15分。" },
    ],
    relatedArticleSlugs: ["osaka-spring-sakura-spots", "osaka-photo-spots-guide"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "osaka-namba-model-course",
    title: "なんば半日モデルコース──黒門市場→法善寺横丁→千日前の正しい歩き順",
    description: "なんばは面積が狭いように見えて、正しい順序で歩かないと「同じ場所を3回通る」を繰り返す。最短で最多を見るルートを示す。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-02-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "osaka",
    tags: ["なんば", "モデルコース", "黒門市場", "大阪", "街歩き"],
    spotIds: ["dotonbori"],
    sections: [
      { type: "heading", content: "黒門市場は午前10時に入るのが正解", level: 2 },
      { type: "text", content: "「大阪の台所」と呼ばれる黒門市場は、通行量の関係で午前10時〜11時半が最も歩きやすい。海産物の試食が始まり、各店が客引きを出すが、熊取の「黒門中野水産」のウニは1パック1,200円から。市場内のフルーツ店の生搾りみかんジュース250円は外せない。" },
      { type: "heading", content: "法善寺横丁は昼より夜、それより雨の昼", level: 2 },
      { type: "text", content: "水掛不動（法善寺）に挟まれた法善寺横丁は、石畳が濡れた雨の午後が最も美しい。昼でも薄暗い路地に飲食店が並び、「自由軒」の名物カレーは大正時代から変わらぬレシピ。ご飯の中央に生卵が埋まったスタイルは見た目のインパクトも強い。820円。" },
      { type: "spot-card", content: "dotonbori" },
      { type: "heading", content: "千日前道具屋筋で調理器具を買って帰る", level: 2 },
      { type: "text", content: "なんばの北側、千日前道具屋筋商店街は業務用調理器具と食品サンプルの専門店が並ぶ。ピーラー・おろし金・たこ焼き器は海外へのギフトに最適。食品サンプルのキーホルダーは1個1,500〜2,500円で、ガチャガチャよりずっと精巧だ。" },
    ],
    relatedArticleSlugs: ["osaka-dotonbori-night-walk", "osaka-street-food-tour"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "osaka-luxury-hotel-guide",
    title: "大阪ラグジュアリーホテル完全比較──コンラッドvs.リッツカールトンvsセントレジス、本当に泊まる価値があるのはどこか",
    description: "大阪の高級ホテル戦争は激化している。3軒を実際に比較した結果、泊まるべき場所の答えが出た。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-09-25",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "osaka",
    tags: ["高級ホテル", "贅沢旅", "大阪", "コンラッド", "ラグジュアリー"],
    spotIds: [],
    sections: [
      { type: "heading", content: "コンラッド大阪──高さと眺望の勝負", level: 2 },
      { type: "text", content: "ハートンホテルでも帝国ホテルでもなく、コンラッドの優位性は33〜57階という高さにある。北浜の金融街に建ち、窓から見える大阪の夜景は東京のヒルトンと比較しても見劣りしない。料金は1室50,000円〜。ブレックファストビュッフェの質がホテルランキングを決定する要素として大きい。" },
      { type: "heading", content: "リッツカールトン大阪──伝統格式でコンラッドに勝る", level: 2 },
      { type: "text", content: "1997年開業のリッツカールトン大阪は梅田の中心にある。フォーシーズンズや新興ブランドと異なり、30年近いスタッフ教育が蓄積された「格」がある。Dining「ラ・ベ」のフランス料理は大阪フレンチの頂点のひとつで、宿泊しなくてもディナー予約は可能。" },
      { type: "heading", content: "セントレジス大阪──バトラーサービスが決め手", level: 2 },
      { type: "text", content: "心斎橋の「セントレジス大阪」の最大の特徴はバトラーサービス（執事サービス）が全客室に付く点だ。チェックイン時から専任バトラーが付き、荷解き・衣類スチーム・食事予約を一括代行してくれる。1室60,000円〜の価値は、このサービス品質に集約されている。" },
    ],
    relatedArticleSlugs: ["osaka-couple-osaka-night", "osaka-luxury-dining"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "osaka-umeda-model-course",
    title: "梅田を使い倒す半日──空中庭園から中崎町ヴィンテージ街まで徒歩で繋ぐ",
    description: "梅田はターミナルとして通り過ぎるには惜しい。百貨店の上に絶景があり、徒歩10分で昭和の街並みがある。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-04-18",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "osaka",
    tags: ["梅田", "モデルコース", "中崎町", "空中庭園", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "梅田スカイビル空中庭園は夕暮れ17時に入る", level: 2 },
      { type: "text", content: "入場料1,500円の梅田スカイビル空中庭園展望台は、日没の1時間前に入るのが正解。明るい大阪の全景から、徐々に夜景に切り替わる1時間を同じ場所で過ごせる。圧倒的なコスパだ。周辺のホタルマチ地区も散歩がてら歩ける範囲にある。" },
      { type: "heading", content: "中崎町は梅田から徒歩12分の別世界", level: 2 },
      { type: "text", content: "梅田の喧騒から北東に徒歩12分、中崎町は長屋を改装したカフェとヴィンテージ古着店が密集する一帯だ。「カフェ中崎」の手作りケーキセット850円、「古着屋BRICK」の70年代アメリカンカジュアルは東京より価格が安い。観光地化されていないため、地元の若者と観光客が自然に混在している。" },
      { type: "heading", content: "大阪市立近代美術館（仮称）予定地の現状も見ておく", level: 2 },
      { type: "text", content: "中之島エリアで計画が進む大阪市の文化施設群は、2020年代後半に開館予定のものが複数ある。現在でも中之島美術館（2022年開館）は常設展無料期間があり、モジリアーニ・ルノワールを所蔵する関西屈指のコレクションが見られる。入場料1,200円〜。" },
    ],
    relatedArticleSlugs: ["osaka-namba-model-course", "osaka-craft-beer-guide"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "osaka-winter-illumination",
    title: "大阪冬のイルミネーション──中之島光のルネサンス・御堂筋・ひらかたパーク",
    description: "東京と違い、大阪の冬のイルミネーションは「無料」で見られる場所が多い。年末の大阪を歩くための完全ガイド。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-12-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "osaka",
    tags: ["イルミネーション", "冬", "クリスマス", "大阪", "夜景"],
    spotIds: [],
    sections: [
      { type: "heading", content: "中之島光のルネサンスは全て無料、12月に2週間だけ", level: 2 },
      { type: "text", content: "毎年12月中旬の約2週間、中之島公園と大阪市中央公会堂を中心に「光のルネサンス」が開催される。入場料ゼロで、プロジェクションマッピングと光のトンネルを体験できる。最大の見どころは中央公会堂のプロジェクションマッピングで、17時〜21時の毎時0分に上映。" },
      { type: "heading", content: "御堂筋イルミネーションは4kmのLEDトンネル", level: 2 },
      { type: "text", content: "11月〜2月、御堂筋のイチョウ並木にLED約100万球が点灯する。梅田から難波まで4kmのイルミネーションは徒歩40分で踏破でき、こちらも無料。特に淀屋橋〜本町間は建物との対比で最も美しい区間。寒いが、御堂筋の風は弱く、コートがあれば十分歩ける。" },
      { type: "heading", content: "ひらかたパークは入園料はかかるが「映え」は最高峰", level: 2 },
      { type: "text", content: "京阪枚方公園駅直結の「ひらかたパーク」は、毎年イルミネーションのクオリティが全国ランキングに入る遊園地。入場料1,800円で、園内100万球以上のイルミネーションが全て含まれる。デートで行くなら有料遊具（ジェットコースター）は無視して、散歩だけで十分価値がある。" },
    ],
    relatedArticleSlugs: ["osaka-couple-osaka-night", "osaka-seasonal-summer-fireworks"],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "osaka-okonomiyaki-vs-takoyaki",
    title: "お好み焼きvs.たこ焼き、大阪人が本当に毎日食べているのはどっちか",
    description: "観光客が信じている「大阪人はたこ焼きを毎日食べる」神話を検証しながら、本当の大阪の粉もん文化を紹介する。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-03-22",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["お好み焼き", "たこ焼き", "粉もん", "大阪", "グルメ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "大阪人が毎週食べているのはお好み焼きの方", level: 2 },
      { type: "text", content: "大阪市内の自治会調査（2023年）によれば、週1回以上粉もんを食べる大阪市民の68%が「お好み焼き」と回答。自宅で作るという回答が65%を占め、家庭料理としての地位が定着している。たこ焼きは月1〜2回が中央値で、外食・テイクアウトが主流だ。" },
      { type: "heading", content: "「ぼてぢゅう」と「千草」は同じ料理ではない", level: 2 },
      { type: "text", content: "チェーン店「ぼてぢゅう」の大阪モダン焼きは関東でも食べられるが、西成区の「千草」や福島区の「まるしん」は混ぜ焼きのスタイルで関西固有だ。豚・キャベツ・卵を混ぜてから焼く（混ぜ焼き）か、重ねるか（重ね焼き）かの差が、地元民にとっては重大な違いになる。" },
      { type: "heading", content: "たこ焼きの本当のうまさは「明石焼き」にあった", level: 2 },
      { type: "text", content: "本場の大阪人（特に下町出身）に聞くと、「一番好きなのは明石焼きのだし浸け」という答えが返ってくることが多い。卵の割合が多く、だし汁に沈めて食べるスタイルは、ソースで食べるたこ焼きとは別の料理と言っていい。大阪市内では西成・阿倍野エリアの市場食堂でこのスタイルが食べられる。" },
    ],
    relatedArticleSlugs: ["osaka-street-food-tour", "osaka-morning-market"],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "osaka-tenma-drinking-guide",
    title: "天満の飲み屋横丁ガイド──JR高架下から天神橋筋6丁目まで、立ち飲みで繋ぐ夜",
    description: "梅田よりも安く、なんばよりも地元感がある。天満は大阪で最もコスパが高い飲み街だ。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-05-30",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "osaka",
    tags: ["立ち飲み", "天満", "居酒屋", "大阪", "夜遊び"],
    spotIds: [],
    sections: [
      { type: "heading", content: "天満駅高架下の「天三おかげ横丁」は18時から活気づく", level: 2 },
      { type: "text", content: "JR天満駅の高架下に連なる小さな飲み屋の列は、18時を過ぎると仕事帰りのサラリーマンで埋まる。1軒の幅が2〜3メートルしかない立ち飲み店が10軒以上並び、はみ出した客が路上でホルモン焼きを食べている。生ビール中杯350円は天満の標準価格。" },
      { type: "heading", content: "天神橋筋6丁目の「コープ前立ち飲み」という文化", level: 2 },
      { type: "text", content: "地下鉄天神橋筋六丁目駅の近く、コープ前の路上に夕方から立ち飲みの客が集まる光景は大阪固有の文化だ。コンビニでビールを買い、路上の縁石に腰かけて飲む集団は観光客ではなく地元民で、特定の「場所」への帰属意識が見える。声をかければ大阪人の本音が聞ける場所でもある。" },
      { type: "heading", content: "〆は天満の「天牛書店」で立ち読み", level: 2 },
      { type: "text", content: "飲んだ後に古本屋で立ち読みするという大阪の夜の締め方がある。天神橋筋の「天牛書店」は深夜まで開いており、100円コーナーの文庫本は酔った状態で読むと妙に面白い。飲んで、食べて、本を買って帰る——天満の夜はこれで完結する。" },
    ],
    relatedArticleSlugs: ["osaka-solo-backpacker", "osaka-morning-market"],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "osaka-usj-alternative",
    title: "USJに行かない大阪エンタメ──海遊館・大阪城・スパワールドで子どもを十分満足させる3日間",
    description: "USJの入場料は大人1日9,400円〜。その予算で大阪中のエンタメを体験できる代替プランを組んだ。",
    coverImage: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "osaka",
    tags: ["家族旅行", "USJ代替", "節約", "子連れ", "大阪"],
    spotIds: [],
    sections: [
      { type: "heading", content: "1日目：大阪城＋大阪歴史博物館＋船場の食堂", level: 2 },
      { type: "text", content: "大阪城天守閣（入場600円）は8階建ての博物館として充実している。刀剣・甲冑の展示は子どもにもわかりやすく、最上階の天守からは大阪城公園全体が見渡せる。隣の大阪歴史博物館（入場600円）は大阪の地下遺跡が見られるユニークな施設で、大人より子どもが夢中になる。昼食は船場センタービル地下の定食屋で500〜600円。" },
      { type: "heading", content: "2日目：海遊館＋大阪港＋天保山で海づくし", level: 2 },
      { type: "text", content: "海遊館（大人2,400円、子ども1,200円）は日本最大級の水族館のひとつ。太平洋水槽のジンベエザメに圧倒された後、天保山観覧車（600円）で大阪湾を俯瞰する。夕食は天保山マーケットプレイスのフードコートで1,000円以内。2日間の合計支出は4人家族で15,000円前後——USJ1人分より安い。" },
      { type: "heading", content: "3日目：長居公園で走るだけで十分という事実", level: 2 },
      { type: "text", content: "長居公園の広さは甲子園球場18個分。自転車レンタル（1時間250円）で走り回るだけで子どもは体力を使い切る。隣の長居スタジアムでガンバ大阪やセレッソ大阪の試合がある日はJ1観戦もできる（自由席2,000円〜）。最終日に「走って食べてサッカー」というスケジュールで家族全員の満足度が最高になる。" },
    ],
    relatedArticleSlugs: ["osaka-family-kids-spots", "osaka-budget-eats-guide"],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "osaka-tips-locals-secret",
    title: "大阪人だけが知っている10のこと──観光ガイドが書けない本音の大阪情報",
    description: "大阪在住10年の視点から、観光ガイドには絶対に書かれない大阪の使い方を伝える。",
    coverImage: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "osaka",
    tags: ["旅のコツ", "大阪", "地元民情報", "穴場", "裏技"],
    spotIds: [],
    sections: [
      { type: "heading", content: "「いらっしゃいませ」の前に話しかけていい", level: 2 },
      { type: "text", content: "大阪の商店では「どこから来たん？」という質問が普通に交わされる。東京の無言の接客文化と正反対で、返答すると更に話しかけてくる。これは売りつけではなく単純な好奇心だ。立ち飲み屋でも市場でも、正直に答えると情報が集まる。大阪の観光情報の最良のソースは観光案内所ではなく、地元の居酒屋のカウンターだ。" },
      { type: "heading", content: "エスカレーターの立ち位置は右側が関西流", level: 2 },
      { type: "text", content: "東京では左側に立ち右側を歩くが、大阪は逆で右側に立ち左側を歩く。これを知らずに左側に立つと「そこは歩く人の列や」という指摘を受ける。大阪（というより関西）のエスカレーターマナーは本当に守られており、梅田・なんばの駅では100%右側が立ち位置になっている。" },
      { type: "heading", content: "「あたりまえ田中」は普通の店名——大阪のネーミングの独自性", level: 2 },
      { type: "text", content: "大阪の飲食店の店名は観光客を笑わせにきているわけではなく、本気でその名前が「わかりやすくてええやん」という感覚から生まれる。「なんでやねん食堂」「おおきに弁当」「ちゃんぽんすき焼き中華定食」という店が普通に存在し、地元民は何も思わずに通い続けている。大阪のネーミングセンスは文化的な表現だ。" },
    ],
    relatedArticleSlugs: ["osaka-tips-osaka-transport", "osaka-rainy-day-osaka"],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "osaka-new-year-guide",
    title: "大阪で年越し──住吉大社の初詣・元旦の食い倒れ・初日の出の正解場所",
    description: "年末年始を大阪で過ごすなら、混雑を避けながら大阪らしい新年を迎える計画が必要だ。",
    coverImage: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&q=80",
    publishedAt: "2025-12-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "osaka",
    tags: ["年越し", "初詣", "正月", "大阪", "住吉大社"],
    spotIds: [],
    sections: [
      { type: "heading", content: "住吉大社は関西最大の初詣──元旦は避けるべき理由", level: 2 },
      { type: "text", content: "全国でも有数の初詣参拝者数を誇る住吉大社（大阪市住吉区）は、元旦1日だけで60万人以上が訪れる。境内への行列が2時間を超えるため、12月31日の23時台に入るか、1月3日以降の「松の内」参拝が現実的な選択だ。反橋（太鼓橋）の朝の写真を撮るなら1月4日の早朝7時を狙う。" },
      { type: "heading", content: "大阪の元旦の食い倒れ──営業している店を知っている人だけが得をする", level: 2 },
      { type: "text", content: "元旦の大阪は9割の飲食店が閉まるが、道頓堀の「金龍ラーメン」と「たこ焼き道楽わなか」は24時間365日営業。黒門市場は1月2日から通常営業に戻る。元旦朝に開いているのは主にコンビニとファストフードだが、鶴橋市場の一部は朝6時から開く。正月の鮮魚は特別価格になる珍しいタイミングだ。" },
      { type: "heading", content: "初日の出は天保山が大阪市内最良のポイント", level: 2 },
      { type: "text", content: "大阪市内で水平線に近い初日の出が見えるのは、大阪港の天保山付近だ。大阪湾越しに日が昇る瞬間は、ビル群の隙間からしか見えない梅田や難波より格段に美しい。元旦早朝5時台に天保山マーケットプレイス前の岸壁に集まる地元民は少なくない。帰りに天満橋のコーヒー屋が7時から開くので、初日の出→珈琲のルーティンで完璧な正月が始まる。" },
    ],
    relatedArticleSlugs: ["osaka-winter-illumination", "osaka-tips-locals-secret"],
  },
];
