import { Article } from "@/types/article";

export const sagaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "saga-yoshinogari-complete-guide",
    title: "吉野ヶ里遺跡を半日で制覇する──弥生時代の都市をどう歩くか、最短ルートと見どころ全解説",
    description: "国内最大の弥生集落跡は広すぎて、適当に歩くと疲れて終わる。コンパクトに最大値を取るルートと、見逃してはいけない展示の解説。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "saga",
    tags: ["吉野ヶ里遺跡", "弥生時代", "歴史", "佐賀", "国営公園"],
    spotIds: ["yoshinogari"],
    sections: [
      { type: "heading", content: "入口から北内郭まで：最重要エリアに直行する", level: 2 },
      { type: "text", content: "吉野ヶ里歴史公園の入口は東口と西口がある。東口から入ると弥生時代の集落中心部「北内郭」まで徒歩15分でアクセスできる。ここが遺跡の核心で、首長の館と祭殿が復元されている。祭殿の内部に入ると、弥生人の宗教儀礼の空間がリアルに再現されている。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "甕棺墓列：日本最大の弥生人の埋葬地", level: 2 },
      { type: "text", content: "甕棺墓列は発掘された弥生時代の墓地跡で、2,000基以上の甕棺（壺に遺体を納める埋葬法）が並ぶ。発掘当初の状態を保存しながら公開しており、ガラス越しに実際の遺骨の痕跡が残る甕棺を見ることができる。これを見ると弥生時代が「教科書の話」ではなくなる。" },
      { type: "heading", content: "自転車レンタルが正解：広大な敷地を効率的に回る", level: 2 },
      { type: "text", content: "吉野ヶ里歴史公園は東西約1km、南北約700mの広大な敷地だ。全部歩くと4時間以上かかるが、入口で自転車を借りると2時間で主要スポットを全て回れる。レンタル料¥200/時間。春は公園全体に桜が咲き、自転車で走りながら花見するのが最も贅沢な楽しみ方だ。" },
    ],
    relatedArticleSlugs: ["saga-arita-pottery-tour", "saga-karatsu-day-trip"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "saga-arita-pottery-tour",
    title: "有田焼を買いに行く旅──窯元めぐりの作法と、陶器市以外でも楽しめる有田の365日",
    description: "有田陶器市だけが有田ではない。年間を通じて窯元は動いており、GW以外の方が作家と話しながら一枚を選ぶ体験ができる。その方法を教える。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "saga",
    tags: ["有田焼", "陶芸", "窯元", "佐賀", "伝統工芸"],
    spotIds: ["arita-pottery"],
    sections: [
      { type: "heading", content: "窯元に入る前に知っておくべき3つのこと", level: 2 },
      { type: "text", content: "有田の窯元は「見学歓迎」「要予約」「ショップのみ」の3種類に分かれる。事前確認なしで飛び込みで入れる窯元は全体の半数程度だ。有田観光協会のウェブサイトで当日訪問可能な窯元リストを確認してから出発すること。作家が在籍する時間帯は午前10時〜午後3時が目安。" },
      { type: "spot-card", content: "arita-pottery" },
      { type: "heading", content: "陶山神社：磁器でできた鳥居の前に立つ意味", level: 2 },
      { type: "text", content: "有田の陶山神社は鳥居・狛犬・灯籠が全て磁器で作られている。世界的にも珍しいこの神社は、有田焼が単なる工芸品ではなく、町民の信仰の対象でもあったことを示している。境内から見える有田の街並みと電車の線路のコントラストが独特の写真になる。" },
      { type: "heading", content: "GW陶器市は「6号線」より「内山エリア」を歩け", level: 2 },
      { type: "text", content: "毎年GWに開催される有田陶器市は、国道35号線沿いを中心に500軒以上が軒を連ねる。観光客が集中する6号線より、内山地区の歴史的な街並みに点在する窯元の方が掘り出し物が多く、値段の交渉も可能だ。内山の泉山磁石場近くの小道が地元陶芸家のファンに知られている。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-ureshino-onsen-guide"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "saga-ureshino-onsen-guide",
    title: "嬉野温泉完全ガイド──美肌の湯と温泉湯豆腐の正しい楽しみ方、日帰りvs宿泊の分岐点",
    description: "嬉野温泉はpH9.4の強アルカリ性重曹泉だ。肌に何が起きるのかを理解してから入浴すると、体験が全く変わる。湯豆腐の食べ方と合わせて解説する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "saga",
    tags: ["嬉野温泉", "美肌", "温泉湯豆腐", "佐賀", "日帰り温泉"],
    spotIds: ["ureshino-onsen"],
    sections: [
      { type: "heading", content: "なぜ嬉野の湯は肌がすべすべになるのか", level: 2 },
      { type: "text", content: "嬉野温泉の泉質はナトリウム炭酸水素塩泉（重曹泉）でpH9.4。この高アルカリ性が肌の余分な角質層を溶かし、触るとぬるっとした感触になる。入浴後30分〜1時間で肌の変化を感じ始める人が多い。日本三大美肌の湯の中でも最も即効性を実感できる泉質だ。" },
      { type: "spot-card", content: "ureshino-onsen" },
      { type: "heading", content: "温泉湯豆腐：なぜ温泉水で煮ると豆腐が溶けるのか", level: 2 },
      { type: "text", content: "嬉野の名物「温泉湯豆腐」は、重曹を含む温泉水で豆腐を煮ることでタンパク質が変性し、表面がとろとろに溶ける独特の料理だ。市内の専門店「宗庵よこ長」は江戸時代から続く老舗で、土鍋で供される湯豆腐は食べ始めてから15分で別物の食感になる。" },
      { type: "heading", content: "日帰り入浴の最良の選択：シーボルトの湯", level: 2 },
      { type: "text", content: "嬉野市の公共浴場「シーボルトの湯」は大正時代の洋館を模した建物で、日帰り入浴¥400。源泉かけ流しの本物の嬉野温泉が500円以下で体験できる施設は全国でも珍しい。宿泊せずに嬉野の湯を体験したいなら、ここが最高のコストパフォーマンスだ。" },
    ],
    relatedArticleSlugs: ["saga-arita-pottery-tour", "saga-saga-city-guide"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "saga-karatsu-day-trip",
    title: "唐津1日モデルコース──唐津城・虹ノ松原・呼子のイカを1日で全部回る完全プラン",
    description: "唐津は小さな町だが、日本三大松原・天守閣・日本一のイカが全部入っている。コンパクトだから1日で全部回れる。その完璧な時間割を公開する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "saga",
    tags: ["唐津", "唐津城", "呼子", "イカ", "モデルコース"],
    spotIds: ["yoshinogari"],
    sections: [
      { type: "heading", content: "9時：唐津城天守閣で玄界灘を一望する", level: 2 },
      { type: "text", content: "唐津城は松浦川河口の小高い丘に建ち、天守閣からは玄界灘の海と虹ノ松原が一望できる。混雑は少なく、開館直後の9時に登ると城内を独占できる。虹ノ松原（全長約4.5km）が海岸線に帯状に続く景色は、唐津の地形の美しさを教えてくれる。" },
      { type: "heading", content: "11時：呼子のイカ生け造りで昼食", level: 2 },
      { type: "text", content: "唐津から北へ車で30分の呼子は「日本一のイカの街」だ。朝に水揚げされたケンサキイカの生け造りは、透明な身が口の中でとろける。「河太郎」「萬坊」が有名だが、行列は萬坊の方が短い。ゲソの天ぷらまで含めて完食するのがイカ定食の正しい食べ方。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "14時：虹ノ松原の松林を歩いてリセットする", level: 2 },
      { type: "text", content: "食後は虹ノ松原の遊歩道を歩く。国の特別名勝で全長4.5kmの松林は、江戸時代に防風林として植えられたもの。松の隙間から見える海と砂浜、松林の中の静けさは、呼子のイカの興奮を静めるのに最適だ。往復1時間のハイキングで唐津の一日が完結する。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-ika-guide"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "saga-ika-guide",
    title: "佐賀・呼子のイカを知り尽くす──なぜ呼子のイカは全国一なのか、旬と食べ方の完全版",
    description: "呼子のイカが「日本一」と言われる理由は鮮度だけではない。玄界灘の海流・水温・漁の方法が重なって生まれる特別な食材の正体を解説する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "saga",
    tags: ["イカ", "呼子", "グルメ", "玄界灘", "佐賀"],
    spotIds: ["yoshinogari"],
    sections: [
      { type: "heading", content: "なぜ呼子のイカは透き通っているのか", level: 2 },
      { type: "text", content: "呼子で水揚げされるケンサキイカは、朝獲れを当日の昼に生け造りで提供する。死後わずか数時間の新鮮さがあるため、身が半透明のまま供される。東京の市場に流通する頃には色が変わっているため、呼子の生け造りは現地でしか食べられない体験だ。" },
      { type: "heading", content: "旬は6月〜8月：夏が最も甘みが強い", level: 2 },
      { type: "text", content: "ケンサキイカの旬は夏、特に6〜8月だ。産卵期前の個体は身が最も肉厚になり、甘みが増す。冬もイカは獲れるが、夏と比べると甘さが劣る。呼子のイカを目的に旅するなら、梅雨が明けた7月以降が最高の時期だ。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "ゲソの天ぷら：捨てる部分が最も旨い", level: 2 },
      { type: "text", content: "生け造りを食べた後、ゲソ（足と内臓）を天ぷらに調理してもらうのが呼子の正しい流儀だ。新鮮なゲソを揚げると、甘みと磯の香りが凝縮された最高の天ぷらになる。身の透明感とゲソの力強い旨みで、イカ一匹を全部食べ切ることができる。" },
    ],
    relatedArticleSlugs: ["saga-karatsu-day-trip", "saga-yoshinogari-complete-guide"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "saga-saga-city-guide",
    title: "佐賀市内観光1日ガイド──佐賀城跡・葉隠の里・七ツ釜まで佐賀城下を歩く",
    description: "佐賀市は「通過する街」だと思っている人が多い。実は城下町の骨格が残る歴史の深い街で、1日かけて歩く価値がある。その全貌を公開する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "saga",
    tags: ["佐賀市", "佐賀城", "歴史", "城下町", "佐賀"],
    spotIds: ["yoshinogari", "arita-pottery"],
    sections: [
      { type: "heading", content: "佐賀城本丸歴史館：幕末佐賀藩の近代化の記録", level: 2 },
      { type: "text", content: "佐賀城の本丸を復元した「佐賀城本丸歴史館」は入館無料。佐賀藩が江戸末期に実現した均田制・藩校弘道館・アームストロング砲の製造まで、近代日本を先取りした革新的な藩政の記録が詳細に展示されている。明治維新で活躍した佐賀出身者の多さが数字で理解できる。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "葉隠の里：「武士道とは死ぬことと見つけたり」の本物の文脈", level: 2 },
      { type: "text", content: "『葉隠』は佐賀藩士・山本常朝の言行録で、「武士道とは死ぬことと見つけたり」の言葉で知られる。佐賀市の「徴古館」では葉隠の原本写本と佐賀藩の武具が展示されている。武士道が抽象的な概念ではなく、具体的な佐賀の歴史の産物だったことが分かる場所だ。" },
      { type: "heading", content: "佐賀のバルーンフェスタ：毎年11月の世界的大会", level: 2 },
      { type: "text", content: "佐賀インターナショナルバルーンフェスタは毎年11月初旬、嘉瀬川河川敷で開催される熱気球の国際大会だ。早朝の一斉離陸で100機以上の気球が空に浮かぶ光景は、日本では佐賀でしか見られない。JR佐賀駅から無料シャトルバスが出る。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-ureshino-onsen-guide"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "saga-couple-onsen-arita",
    title: "佐賀カップル旅2日間──嬉野温泉1泊と有田焼の窯元めぐりで完成する大人の休日",
    description: "佐賀のカップル旅は「美肌の湯と工芸品の旅」として設計できる。嬉野温泉に1泊して、翌日は有田で一生使える器を選ぶ。この2日間のルートを完全公開。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "saga",
    tags: ["カップル旅", "嬉野温泉", "有田焼", "佐賀", "温泉旅行"],
    spotIds: ["ureshino-onsen", "arita-pottery"],
    sections: [
      { type: "heading", content: "1日目：嬉野温泉の宿で美肌の湯を独占する", level: 2 },
      { type: "text", content: "嬉野温泉の旅館は中規模が多く、露天風呂付き客室が比較的リーズナブルに取れる。15時チェックインで夕食前に2回入浴するのが嬉野の正しい楽しみ方だ。夕食の温泉湯豆腐フルコース（¥8,000〜）は事前予約が必須で、嬉野茶を使ったスイーツで締めくくる。" },
      { type: "spot-card", content: "ureshino-onsen" },
      { type: "heading", content: "翌朝：早朝の嬉野川沿い散歩", level: 2 },
      { type: "text", content: "嬉野温泉の朝は川沿いを歩くことから始まる。嬉野川沿いの遊歩道は朝7時台に散策する旅館の宿泊客で静かに賑わっている。川の畔に足湯が設置されており、朝の澄んだ空気の中で入浴後の体を再び温める体験は嬉野の宿泊者にしか与えられない特権だ。" },
      { type: "heading", content: "2日目：有田で一生使う器を二人で選ぶ", level: 2 },
      { type: "text", content: "嬉野から有田へは車で30分。二人で一緒に気に入った器を選ぶ時間が旅のハイライトになる。「使う食器を旅先で選ぶ」という行為は、旅の記憶を日常の食卓に持ち込む最も贅沢な方法だ。予算¥5,000〜¥10,000で、作家が丁寧に作った飯碗や皿が手に入る。" },
    ],
    relatedArticleSlugs: ["saga-ureshino-onsen-guide", "saga-arita-pottery-tour"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "saga-budget-trip",
    title: "佐賀1泊2日格安旅行──吉野ヶ里・唐津・嬉野を最安値で全部回る方法",
    description: "佐賀旅行は交通費が高い。でも組み合わせ方次第で、主要スポットを全部回って1泊2日の総費用が15,000円以下に収まる。その方程式を公開する。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-07-05",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "saga",
    tags: ["節約旅", "格安旅行", "佐賀", "バジェット", "一人旅"],
    spotIds: ["yoshinogari", "ureshino-onsen"],
    sections: [
      { type: "heading", content: "JR九州フリーきっぷで交通費を半分にする", level: 2 },
      { type: "text", content: "「JR九州ワイドパス（3日間）」は¥18,800だが、佐賀・長崎・熊本を横断するなら元が取れる。佐賀だけなら「博多〜佐賀の往復+嬉野バス込み」の特定区間フリーきっぷが¥3,800で使える日がある。JR九州の季節限定フリーきっぷは公式アプリで事前確認すること。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "吉野ヶ里の割引入場券：JAFカードで¥100引き", level: 2 },
      { type: "text", content: "吉野ヶ里歴史公園の入場料は¥460だが、JAFカードを持参すると¥100引きになる。また「佐賀県立博物館・美術館」との共通券は¥710で両方入れる。イオンのWAONポイントデーにも割引があるため、訪問日を選ぶと更に節約できる。" },
      { type: "heading", content: "嬉野温泉の日帰り最安値：シーボルトの湯¥400", level: 2 },
      { type: "text", content: "嬉野温泉は旅館での宿泊が理想だが、日帰りなら市営「シーボルトの湯」が¥400で本物の源泉かけ流しに入れる。宿泊施設と泉質は同じだ。嬉野温泉湯豆腐は「茶心の宿 和楽園」の外来ランチコース（¥2,200）が最もコストパフォーマンスが高い。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-ureshino-onsen-guide"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "saga-autumn-harvest-season",
    title: "佐賀の秋──佐賀牛・新米・嬉野茶の収穫シーズンに食べるべきもの全部",
    description: "佐賀の10月〜11月は食材の宝庫だ。佐賀牛の脂が乗り、新米が出回り、嬉野の秋茶が仕上がる。この季節に来た人だけが食べられるものを全部挙げる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "saga",
    tags: ["秋", "佐賀牛", "新米", "嬉野茶", "佐賀"],
    spotIds: ["ureshino-onsen", "yoshinogari"],
    sections: [
      { type: "heading", content: "佐賀牛の霜降りは11月が最高になる理由", level: 2 },
      { type: "text", content: "佐賀牛は黒毛和牛の中でも霜降り等級が全国トップレベルで、A5等級の比率が全国最高だ。秋口から気温が下がると牛の脂の質が変わり、融点が下がって口溶けが良くなる。佐賀市内の「松扇」と唐津の「炭火焼肉 一牛」が最も脂の質にこだわる店として知られる。" },
      { type: "spot-card", content: "ureshino-onsen" },
      { type: "heading", content: "嬉野の秋茶：玉緑茶の「さえみどり」が10月に出回る", level: 2 },
      { type: "text", content: "嬉野茶は主に玉緑茶（ぐり茶）で知られる。春の一番茶が最高品質だが、10月の秋茶は渋みが少なくまろやかな味わいになる。嬉野温泉街の茶屋「嬉野茶市場」で産地直送の秋茶を買うと、同等品が東京の2〜3割安く手に入る。茶の香りとぬる湯の組み合わせが、嬉野の秋の完成形だ。" },
      { type: "heading", content: "バルーンフェスタ：11月第1週の朝に一斉離陸を見よ", level: 2 },
      { type: "text", content: "佐賀インターナショナルバルーンフェスタは毎年11月第1週に開催される。早朝7時の競技一斉離陸で、100機以上の気球が霧の中から浮かび上がる光景は別世界の美しさだ。競技観覧は無料。嘉瀬川河川敷に前夜から場所を取っている人もいるほどの人気イベントだ。" },
    ],
    relatedArticleSlugs: ["saga-ureshino-onsen-guide", "saga-karatsu-day-trip"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "saga-solo-history-trip",
    title: "一人旅で佐賀の歴史を掘る──吉野ヶ里から葉隠まで、弥生〜幕末を一日で縦断する",
    description: "佐賀は歴史密度が異常に高い県だ。弥生時代の国内最大集落跡から、明治維新を動かした幕末藩士の記録まで。一人旅で時間を贅沢に使えば1日で縦断できる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "saga",
    tags: ["一人旅", "歴史旅", "弥生時代", "幕末", "佐賀"],
    spotIds: ["yoshinogari", "arita-pottery"],
    sections: [
      { type: "heading", content: "9時：吉野ヶ里で弥生時代の都市に立つ", level: 2 },
      { type: "text", content: "JR吉野ヶ里公園駅から徒歩15分で、2,000年前の日本最大の弥生集落跡に立つ。一人旅なら自分のペースで甕棺墓列の前に1時間でも座っていられる。他の観光客が通り過ぎていく中で、弥生人の埋葬を一人で見つめる時間は、グループ旅行では絶対に味わえない体験だ。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "13時：有田で江戸時代の磁器産業を体感", level: 2 },
      { type: "text", content: "吉野ヶ里から電車で有田へ。有田の泉山磁石場は、江戸時代から採掘が続く採石場で「有田焼の聖地」だ。山肌が白く削られた独特の景観は一見の価値がある。有田のランチは「有田ポーセリンパーク」のレストランで有田牛を使ったランチが1,500円〜。" },
      { type: "heading", content: "16時：佐賀城本丸歴史館で幕末佐賀藩の革命を知る", level: 2 },
      { type: "text", content: "有田から佐賀市へ戻り、佐賀城本丸歴史館（無料）で佐賀藩の幕末改革の記録を見る。均田制・蒸気機関の開発・反射炉の建設。江戸時代末期に独自の近代化を成し遂げた佐賀藩の先進性が、資料と展示から生々しく伝わってくる。一人旅でゆっくり読み込む価値がある。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-saga-city-guide"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "saga-family-arita-yoshinogari",
    title: "子連れ佐賀旅行──吉野ヶ里の発掘体験と有田の絵付け体験、子どもが主役の1泊2日",
    description: "佐賀は子ども向けの体験型観光が充実している。弥生時代の発掘模擬体験と有田焼の絵付け体験を組み合わせると、子どもが「作った」と「発見した」の二つの感動を持ち帰れる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "saga",
    tags: ["子連れ旅", "吉野ヶ里", "有田焼絵付け", "体験型観光", "佐賀"],
    spotIds: ["yoshinogari", "arita-pottery"],
    sections: [
      { type: "heading", content: "吉野ヶ里の勾玉づくり体験：弥生時代のアクセサリーを作る", level: 2 },
      { type: "text", content: "吉野ヶ里歴史公園では、弥生時代の装飾品「勾玉」を実際に作るワークショップが定期開催されている（¥600〜）。滑石を削って形を整え、紐を通してペンダントにする。小学生から参加可能で、作った勾玉はそのまま持ち帰れる。旅の記憶が形として残る最高の体験だ。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "有田焼絵付け体験：オリジナルの器を焼いてもらう", level: 2 },
      { type: "text", content: "有田の「源右衛門窯」「柿右衛門窯」などでは磁器への絵付け体験ができる（¥1,500〜）。白磁の素地に専用の呉須（青い顔料）で絵を描くと、本焼き後に本物の有田焼になる。仕上がりは2〜3週間後に郵送してもらえるため、旅から帰った後も届くまでの楽しみが続く。" },
      { type: "heading", content: "子連れで嬉野温泉：足湯と温泉湯豆腐が子どもにも人気", level: 2 },
      { type: "text", content: "嬉野温泉の足湯は無料で利用できるものが複数ある。子どもが足を入れて「ぬるぬるする！」と驚く体験は、温泉の泉質を体で覚える最初の入口になる。温泉湯豆腐は子どもが「豆腐が溶けていく！」と面白がる料理で、食育的な体験にもなる。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-arita-pottery-tour"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "saga-luxury-yamagata-beef",
    title: "佐賀牛を極める旅──A5等級の最高峰を食べるための宿と店の選び方",
    description: "佐賀牛はA5等級の比率が全国最高だ。松坂・近江・飛騨と比較されることは少ないが、食べれば分かる。牛肉の旅として佐賀を選ぶ理由を語る。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "saga",
    tags: ["佐賀牛", "高級グルメ", "A5等級", "贅沢旅", "佐賀"],
    spotIds: ["ureshino-onsen"],
    sections: [
      { type: "heading", content: "佐賀牛とは何か：全国最高のA5等級比率の秘密", level: 2 },
      { type: "text", content: "佐賀牛は佐賀県産の黒毛和牛の中でも、最高等級BMS（牛脂肪交雑基準）No.7以上のものだけを指す。霜降りの密度と均一性が全国トップクラスで、火を入れた瞬間に脂が溶け出し、肉の甘みが口に広がる。松坂牛と同等以上と評する料理人も多い。" },
      { type: "spot-card", content: "ureshino-onsen" },
      { type: "heading", content: "嬉野温泉の宿で佐賀牛コースを食べる贅沢", level: 2 },
      { type: "text", content: "嬉野温泉の高級旅館「椎葉山荘」「和多屋別荘」では、夕食のコースに佐賀牛が組み込まれている。温泉でリセットした体で食べる最高品質の牛肉は、都市の高級レストランとは全く別の体験になる。1泊2食付きで¥30,000〜が相場で、それだけの価値が確実にある。" },
      { type: "heading", content: "佐賀市「松扇」：佐賀牛の本場で最も信頼できる焼肉店", level: 2 },
      { type: "text", content: "佐賀市中心部の焼肉店「松扇」は産地直送の佐賀牛を扱う老舗だ。ロース¥3,800〜、カルビ¥2,800〜。東京の同品質の焼肉と比べると30%以上安い。予約は必須で、週末は2週間先まで満席が続く。佐賀牛のカルビを炭火で自分で焼く体験は、食べる行為そのものが楽しい。" },
    ],
    relatedArticleSlugs: ["saga-ureshino-onsen-guide", "saga-autumn-harvest-season"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "saga-spring-cherry-balloon",
    title: "佐賀の春──吉野ヶ里の桜と熱気球が重なる4月の特別な週末",
    description: "4月の佐賀は二つの絶景が重なる。吉野ヶ里遺跡の桜と、嘉瀬川の熱気球。この組み合わせを知っている旅行者はほとんどいない。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "saga",
    tags: ["春", "桜", "熱気球", "吉野ヶ里", "佐賀"],
    spotIds: ["yoshinogari"],
    sections: [
      { type: "heading", content: "4月第1週：吉野ヶ里の桜と弥生の復元集落", level: 2 },
      { type: "text", content: "吉野ヶ里歴史公園では毎年4月第1週に「弥生の花まつり」が開催される。復元された竪穴住居の周囲に桜が咲き、弥生時代の衣装をつけたガイドが歩き回る特別な週末だ。桜の下で勾玉づくり体験ができる出展もあり、子どもも大人も一緒に楽しめる春の佐賀の名物イベント。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "嘉瀬川の春バルーン：GW前の練習飛行が穴場", level: 2 },
      { type: "text", content: "バルーンフェスタは11月開催だが、4〜5月にかけて競技者の練習飛行が嘉瀬川河川敷で行われる。正式な大会ではないため観覧は無料で、距離も近い。早朝5〜7時の離陸風景は誰にも邪魔されず見られる。佐賀のガスバーナーの轟音と朝霧の中で浮かぶ気球の組み合わせは春の佐賀限定の体験だ。" },
      { type: "heading", content: "4月の嬉野：茶畑の新芽と温泉の最高の組み合わせ", level: 2 },
      { type: "text", content: "嬉野の一番茶の摘み取りは4月下旬〜5月上旬に始まる。この時期に嬉野を訪れると、茶畑の鮮やかな黄緑色と温泉街の静けさを同時に体験できる。一部の茶農家では摘み取り体験を受け付けており、自分で摘んだ茶葉を使った一煎を飲む体験は、旅行の中でも特別な記憶になる。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-ureshino-onsen-guide"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "saga-arita-pottery-buy-guide",
    title: "有田焼の賢い買い方──アウトレット・直販・陶器市、三つのルートで最高の一枚を見つける",
    description: "有田焼を買うルートは三つある。アウトレットで格安に探す方法、窯元直販で作家物を選ぶ方法、GWの陶器市で掘り出し物を見つける方法。それぞれの正解を教える。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "saga",
    tags: ["有田焼", "買い物", "アウトレット", "陶器市", "佐賀"],
    spotIds: ["arita-pottery"],
    sections: [
      { type: "heading", content: "アリタセラ：アウトレット専門施設で定価の30〜50%引き", level: 2 },
      { type: "text", content: "有田駅から徒歩10分の「アリタセラ」は、有田焼の窯元が共同で運営するアウトレット施設だ。B品（わずかな傷や色むらがある製品）が定価の30〜50%引きで販売されている。美術館的な展示も充実しており、有田焼の歴史を学びながら買い物ができる施設として外国人旅行者にも人気が高い。" },
      { type: "spot-card", content: "arita-pottery" },
      { type: "heading", content: "窯元直販のコツ：値段交渉よりも「話を聞く」方が得", level: 2 },
      { type: "text", content: "窯元直販は値段の交渉をしても断られることが多い。むしろ作家に「どうやって作ったか」「この模様の意味は何か」と話を聞くと、会話の流れで「これ、おまけしますよ」と言われることがある。買い手として「ちゃんと理解して買いたい」という姿勢が、窯元との関係を良くする最大の戦略だ。" },
      { type: "heading", content: "陶器市の必勝法：朝6時に内山地区に入れ", level: 2 },
      { type: "text", content: "有田陶器市（GW開催）の掘り出し物は朝6時台に出ている。多くの窯元は値段交渉が最も通りやすい初日の午前中に在庫を並べ替え、昼以降は値段が固定される。開始前から内山エリアの路地に入って、まだシートがかかっている商品を並べ直す窯元と話すのが正解だ。" },
    ],
    relatedArticleSlugs: ["saga-arita-pottery-tour", "saga-couple-onsen-arita"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "saga-complete-3day-route",
    title: "佐賀県完全制覇3日間ルート──吉野ヶ里・有田・唐津・嬉野を全部制する最適な動き方",
    description: "佐賀の主要4エリアは一筆書きで回れる。北から南に向かう順番と、各エリアの最低滞在時間を設定した3日間の完全プランを公開する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "saga",
    tags: ["モデルコース", "3日間", "佐賀", "完全制覇", "旅行プラン"],
    spotIds: ["yoshinogari", "arita-pottery", "ureshino-onsen"],
    sections: [
      { type: "heading", content: "1日目：博多発→吉野ヶ里→佐賀市内泊", level: 2 },
      { type: "text", content: "博多から在来線で吉野ヶ里公園駅まで50分（¥820）。午前中に遺跡を2時間見学し、午後に佐賀市内に移動して城本丸歴史館へ。夕食は佐賀市内で佐賀牛焼肉。佐賀市内のビジネスホテルは¥6,000〜と格安で質が高い。" },
      { type: "spot-card", content: "yoshinogari" },
      { type: "heading", content: "2日目：有田→唐津→呼子のイカ昼食", level: 2 },
      { type: "text", content: "2日目は佐賀市内からレンタカーで有田へ（約45分）。午前中に窯元めぐりと器の購入。昼前に唐津城に登り、呼子まで移動してイカ定食の昼食。午後は虹ノ松原を散策して嬉野温泉へ移動。嬉野での1泊が旅全体のリセットになる。" },
      { type: "heading", content: "3日目：嬉野温泉朝湯→佐賀空港or博多帰着", level: 2 },
      { type: "text", content: "最終日は朝6時に起床して温泉に入り、嬉野茶のお土産を購入してから出発。嬉野温泉から佐賀空港まで車で45分。博多に戻る場合はJR武雄温泉駅から西九州新幹線で29分。3日間で佐賀の全てのエッセンスを持ち帰ることができる完璧なルートだ。" },
    ],
    relatedArticleSlugs: ["saga-yoshinogari-complete-guide", "saga-karatsu-day-trip", "saga-ureshino-onsen-guide"],
  },
];
