import { Article } from "@/types/article";

export const saitamaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "saitama-kawagoe-model-course",
    title: "川越半日モデルコース──蔵造りの街を9時から15時で制覇する",
    description: "「小江戸」川越を効率よく回る。一番街・時の鐘・菓子屋横丁の最適順路。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "saitama",
    tags: ["川越", "小江戸", "蔵造り", "埼玉", "モデルコース"],
    spotIds: ["kawagoe"],
    sections: [
      { type: "heading", content: "9時台の一番街は観光客が少ない", level: 2 },
      { type: "text", content: "川越駅から一番街まで徒歩15分。9時に到着すると観光客の数が少なく、江戸時代の蔵造り商家が並ぶ街並みをゆっくり歩ける。黒壁の蔵造りは江戸大火後に防火建築として発展した様式で、現在も現役の店舗として使われている物件が20棟以上残る。" },
      { type: "heading", content: "時の鐘は12時の鐘音を現地で聞く", level: 2 },
      { type: "text", content: "時の鐘は1日4回（6・12・15・18時）鳴る。正午の鐘は最も人が集まるタイミングで、鐘の真下に立って聞くと地響きのような低音が身体に届く。鐘楼の高さは16mで、江戸時代から続く川越の時を知らせる存在。鐘楼横の「時の鐘通り」は写真映えする構図が多い。" },
      { type: "heading", content: "菓子屋横丁で昭和の駄菓子を買う", level: 2 },
      { type: "text", content: "一番街から北へ徒歩5分の菓子屋横丁は、全長約100mの路地に昭和創業の駄菓子屋が密集する。芋けんぴ¥200〜・麦こうじ¥150〜・金平糖¥300〜が基本的な土産ラインナップ。子どもより大人が懐かしさで盛り上がる場所で、平日午前中は地元の高齢者もよく見かける。" },
      { type: "heading", content: "川越いもスイーツで締める", level: 2 },
      { type: "text", content: "川越はサツマイモの産地として有名で「川越いも」ブランドが確立している。一番街周辺の店で芋アイス（¥400〜）・芋モンブラン（¥600〜）・芋ようかん（¥300〜）が揃う。帰りに川越市駅近くの「菓匠右門」で芋恋（大学いも）を土産に買って帰るのが定番ルート。" },
    ],
    relatedArticleSlugs: ["saitama-kawagoe-couple", "saitama-kawagoe-gourmet"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "saitama-kawagoe-gourmet",
    title: "川越グルメ完全版──芋料理と鰻とわらじかつの全部を1日で食べ歩く",
    description: "小江戸川越は食べ物が面白い。地元メディアも取り上げない穴場グルメまで全部収録。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-05-18",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "saitama",
    tags: ["川越", "グルメ", "芋", "食べ歩き", "埼玉"],
    spotIds: ["kawagoe"],
    sections: [
      { type: "heading", content: "川越芋料理の正しい食べ方", level: 2 },
      { type: "text", content: "川越産のサツマイモ（紅あずま・紅はるか）を使った料理は、焼き芋専門店「小江戸いも」が基点だ。石焼き芋1本¥300〜¥500で、切り口から蜜が滴るねっとり系と、ほくほく系を選べる。芋ソフトクリーム（¥450）は一番街のすずのや菓子舗が安定した品質。" },
      { type: "heading", content: "川越の鰻は成田より安くて旨い", level: 2 },
      { type: "text", content: "川越に鰻のイメージはないが、川越最古の鰻屋「小川菊」（創業1807年）は全国の鰻ファンに知られた存在だ。うな重（上）¥4,200で、蒸しを丁寧にかけるふわふわの江戸前スタイル。11時開店直後に並ばないと昼過ぎには売り切れる。予約不可の当日勝負。" },
      { type: "heading", content: "わらじかつ丼は秩父の文化だが川越でも食べられる", level: 2 },
      { type: "text", content: "「三久」（本丸御殿前）ではわらじかつ丼（¥1,200）を提供している。秩父発祥のメニューだが、川越でも食べられる店が増えた。タレがやや甘めで埼玉スタイル。カツ1枚が丼からはみ出す大きさが視覚的インパクトを作る。昼前後は行列必至。" },
    ],
    relatedArticleSlugs: ["saitama-kawagoe-model-course", "saitama-chichibu-day-trip"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "saitama-kawagoe-couple",
    title: "川越カップル旅──昼の蔵造り街と夜の提灯通りを2人で歩く",
    description: "川越は夜もいい。提灯が灯る一番街の夕方以降のムードと2人向けプランを解説。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "saitama",
    tags: ["川越", "カップル", "夜景", "提灯", "埼玉"],
    spotIds: ["kawagoe"],
    sections: [
      { type: "heading", content: "昼は蔵造りの街を2人でゆっくり歩く", level: 2 },
      { type: "text", content: "一番街の蔵造り商家の多くは内部が見学できる。市立博物館（無料）では川越の歴史を30分で把握できる。仙波東照宮（無料）は日本三大東照宮のひとつで、行列がなく静かに参拝できる穴場。昼食は芋スイーツと川越の地ビールを出すカフェ「紋蔵庵」が一番街から徒歩3分。" },
      { type: "heading", content: "夕方から提灯が灯る一番街に変わる", level: 2 },
      { type: "text", content: "17時を過ぎると一番街の軒先に提灯が灯り始め、蔵造りの黒壁にオレンジの光が映える。観光客が引いていく時間帯で、写真的にも昼より美しい瞬間が多い。時の鐘の18時の鐘音を2人で聞くのが川越カップル旅の定番のシーン。" },
      { type: "heading", content: "蔵の街でちょっと贅沢な夕食を選ぶ", level: 2 },
      { type: "text", content: "川越の和食店「蔵の街料亭 福呂屋」は江戸時代の蔵を改装した空間で、川越野菜と地鶏を使ったコース（¥6,000〜）が揃う。予約は1週間前が目安。川越の蔵の中で2人きりで食べる懐石は、東京のレストランにはない質感を持つ体験だ。" },
    ],
    relatedArticleSlugs: ["saitama-kawagoe-model-course", "saitama-nagatoro-couple"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "saitama-chichibu-day-trip",
    title: "秩父日帰り旅行の全ルート──芝桜・霊場・夜祭の季節別完全ガイド",
    description: "東京から90分の秩父は何度来ても違う顔を見せる。季節別の最適ルートを3パターン解説。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-04-28",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "saitama",
    tags: ["秩父", "芝桜", "霊場", "埼玉", "日帰り"],
    spotIds: ["chichibu"],
    sections: [
      { type: "heading", content: "春ルート：羊山公園の芝桜40万株", level: 2 },
      { type: "text", content: "4月下旬〜5月上旬の羊山公園は40万株の芝桜が斜面を埋め尽くす。西武秩父駅から徒歩20分、または有料シャトルバス¥200。ピーク週末は駐車場が朝8時に満車になるため電車利用が必須。芝桜の丘入園料¥300。武甲山を背景に広がるピンクのグラデーションは正午より午前中の光の方が美しい。" },
      { type: "heading", content: "通年ルート：秩父三十四か所巡礼の一部だけ歩く", level: 2 },
      { type: "text", content: "秩父三十四か所霊場の全行程は約100kmだが、1番の四萬部寺から5番の語歌堂まで約10kmを歩くだけでも霊場の空気を感じられる。無人の古い堂宇が山中に点在しており、観光化された霊場とは別次元の静寂がある。スタンプ帳（¥500）を手に入れると「御朱印めぐり」として整理できる。" },
      { type: "heading", content: "秩父名物・わらじかつ丼で昼食を取る", level: 2 },
      { type: "text", content: "西武秩父駅前の「野さか」はわらじかつ丼の元祖とされる店だ（¥1,350〜）。開店11時の30分前から並ぶ人が出るほどの人気で、14時には売り切れることがある。タレは醤油ベースの甘辛で、衣が薄くカツの肉質が直接感じられるスタイル。" },
      { type: "heading", content: "冬ルート：12月3日の秩父夜祭に照準を合わせる", level: 2 },
      { type: "text", content: "秩父夜祭（毎年12月3日）は日本三大曳山祭のひとつで、6台の屋台・笠鉾が夜の秩父市内を練り歩く。夜10時頃の花火は山に反響して音量が異常で、秩父ならではの迫力だ。当日は西武秩父駅から祭り会場まで徒歩圏内。宿泊は1か月前から予約しないと近隣に空きがなくなる。" },
    ],
    relatedArticleSlugs: ["saitama-nagatoro-rafting", "saitama-kawagoe-gourmet"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "saitama-nagatoro-rafting",
    title: "長瀞ライン下り完全ガイド──コース選びと岩畳の歩き方",
    description: "長瀞の3コースを全部乗った。急流のスリルと岩畳の静寂を両立するルートを教える。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-07-04",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "saitama",
    tags: ["長瀞", "ライン下り", "夏", "埼玉", "アウトドア"],
    spotIds: ["nagatoro"],
    sections: [
      { type: "heading", content: "3コースの違いを整理する", level: 2 },
      { type: "text", content: "長瀞ライン下りは「上長瀞〜長瀞」（急流あり・約20分・¥1,500）、「長瀞〜親鼻」（穏やか・約20分・¥1,500）、全行程「上長瀞〜親鼻」（約40分・¥2,500）の3コースがある。初めてなら全行程コースが両方の景色を体験できて最もコスパがいい。4月〜10月の土日は予約制になるため前日までに電話予約を推奨。" },
      { type: "heading", content: "岩畳は時間帯を選んで歩く", level: 2 },
      { type: "text", content: "長さ500m・幅30mの岩畳は荒川の国の名勝・天然記念物だ。ライン下り後は岩畳を歩いて地質を観察する時間を作ること。朝8時台は観光客がほぼいないため、川面と岩の音だけが聞こえる特別な時間を過ごせる。サンダルよりスニーカーの方が岩の凹凸で歩きやすい。" },
      { type: "heading", content: "宝登山神社の蝋梅と紅葉も組み合わせる", level: 2 },
      { type: "text", content: "長瀞駅から宝登山神社まで徒歩15分。蝋梅（1〜2月）は関東屈指の名所で、山全体が黄色の花と甘い香りに包まれる。秋（11月）の紅葉は岩畳と荒川の組み合わせで最高の景色になる。神社は秩父のパワースポットとして有名で参拝者が多い。" },
    ],
    relatedArticleSlugs: ["saitama-chichibu-day-trip", "saitama-nagatoro-couple"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "saitama-nagatoro-couple",
    title: "長瀞カップル旅──川と岩畳と星空温泉の2人旅設計",
    description: "長瀞は日帰りでも1泊でも成立するカップル旅の名地。完璧な2日間のプランを設計した。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-10-12",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "saitama",
    tags: ["長瀞", "カップル", "秩父", "埼玉", "温泉"],
    spotIds: ["nagatoro"],
    sections: [
      { type: "heading", content: "1日目午後：ライン下りで秩父の川を体験", level: 2 },
      { type: "text", content: "東京から西武池袋線・秩父鉄道乗り継ぎで長瀞駅へ（約1時間50分）。13時着でライン下り全行程コース（¥2,500）に乗り、川面から岩畳と紅葉を眺める。降船後は岩畳を2人で歩いて夕方の光の変化を楽しむ。17時台の夕日が荒川に反射する時間が長瀞で最も美しい瞬間の一つ。" },
      { type: "heading", content: "宿泊は渓谷を見下ろす旅館一択", level: 2 },
      { type: "text", content: "「長瀞山麓温泉 月の石もみじ公園」エリアの旅館は荒川渓谷を見下ろす露天風呂を持つ宿が多い（1泊2食¥20,000〜¥30,000）。秩父錦（地酒）と秩父ウイスキーを部屋で楽しみながら渓谷の夜を過ごすのが最も贅沢な時間の使い方だ。" },
      { type: "heading", content: "2日目朝：蝋梅か桜を早朝に見る", level: 2 },
      { type: "text", content: "宝登山の蝋梅（1〜2月）は朝8時台が無人で黄金の光に包まれる最高のタイミング。4月の桜シーズンは岩畳と荒川越しに桜並木が見える場所が長瀞駅前の公園にある。帰路は秩父に寄ってわらじかつ丼を食べて締める2日間の完成形。" },
    ],
    relatedArticleSlugs: ["saitama-nagatoro-rafting", "saitama-chichibu-day-trip"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "saitama-tetsudo-museum",
    title: "鉄道博物館の攻略法──子連れで半日を最大化する全手順",
    description: "大宮の鉄道博物館は大人も本気で楽しめる。混雑回避から体験系展示の抑え方まで解説。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "saitama",
    tags: ["鉄道博物館", "大宮", "家族旅行", "子ども", "埼玉"],
    spotIds: [],
    sections: [
      { type: "heading", content: "開館前15分に並ぶ理由", level: 2 },
      { type: "text", content: "鉄道博物館（さいたま市大宮区）は10時開館だが、9時45分には入口に列ができる。人気のD51シミュレーター（¥500）は1日10回のみで、開館直後に並ばないと整理券が取れない。ミニ運転列車体験（¥200）も朝イチに整理券を確保すること。入場料¥1,330（大人）・¥620（小学生）。" },
      { type: "heading", content: "1階の実物車両展示から圧倒される", level: 2 },
      { type: "text", content: "センターステーションには実物の新幹線・蒸気機関車・特急列車が36両展示されている。0系新幹線の先頭部分の断面カットは、車内構造が外から見えて子どもが感動する展示。車内に実際に乗り込める展示車両もあり、昭和の特急列車の座席に座る体験は大人にとっても懐かしい。" },
      { type: "heading", content: "昼食はランチトレインで食べる", level: 2 },
      { type: "text", content: "館内の「ランチトレイン」は実物の食堂車を使ったレストランで、走行中の車窓映像を見ながら食事できる。月替わりの駅弁セット（¥1,200〜）が揃い、昼のピーク（11時半〜13時）は30分待ちが発生することがある。11時前か13時半以降が空いている。" },
    ],
    relatedArticleSlugs: ["saitama-omiya-hikawa-shrine", "saitama-kawagoe-model-course"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "saitama-omiya-hikawa-shrine",
    title: "氷川神社の参道2kmを全部歩く──大宮の聖域で感じる2,000年の歴史",
    description: "関東最大の神社の参道は日本最長クラスだ。その全体を歩いた先に見えるものを語る。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-01-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "saitama",
    tags: ["氷川神社", "大宮", "神社", "初詣", "埼玉"],
    spotIds: [],
    sections: [
      { type: "heading", content: "一の鳥居から歩き始める", level: 2 },
      { type: "text", content: "氷川神社の参道は大宮公園内の一の鳥居から本殿まで約2kmの直線だ。三の鳥居まで松並木が続き、関東平野の中に切り取られたような参道の静寂がある。正月三が日は参拝者200万人以上が訪れる埼玉最大の初詣スポットで、1月4日以降が静かで参拝しやすい。" },
      { type: "heading", content: "境内の楼門と舞殿の格式を見る", level: 2 },
      { type: "text", content: "氷川神社の楼門は明神造りの格式ある建築で、朱塗りの柱が緑の森に映える。舞殿では年間を通じて神楽・雅楽の奉納が行われる。七五三（11月）は境内が晴れ着の家族で賑わい、神社の境内が最も「生活に近い」表情を見せる。" },
      { type: "heading", content: "大宮公園で桜と池を追加する", level: 2 },
      { type: "text", content: "氷川神社に隣接する大宮公園は4月の桜名所として知られる。約1,000本の桜が咲き、花見の宴会が禁止されているため家族連れが多い。不忍の池（小さな弁天堂付き）は紅葉シーズンもいい。氷川神社参拝と大宮公園散策をセットにした半日が大宮の正しい使い方。" },
    ],
    relatedArticleSlugs: ["saitama-tetsudo-museum", "saitama-kawagoe-model-course"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "saitama-chichibu-solo",
    title: "秩父一人旅──霊場と酒蔵と星空を独り占めする2日間",
    description: "人込みを避けて秩父の深い部分に入り込む。霊場巡りと地酒と満天の星を独り占めする旅。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "saitama",
    tags: ["秩父", "一人旅", "霊場", "酒蔵", "埼玉"],
    spotIds: ["chichibu"],
    sections: [
      { type: "heading", content: "霊場巡りは朝6時から始める", level: 2 },
      { type: "text", content: "秩父三十四か所の1番四萬部寺は朝6時から開いている。早朝の霊場は参拝者がほぼおらず、鐘の音と鳥の声だけが聞こえる静寂の空間だ。1〜5番を歩くと約10km・3時間で、歩き遍路の入口を体験できる。軽登山靴と御朱印帳（¥500）を準備していくこと。" },
      { type: "heading", content: "秩父の地酒「秩父錦」と「武甲正宗」を飲み比べる", level: 2 },
      { type: "text", content: "秩父には「矢尾本店（秩父錦）」と「武甲酒造（武甲正宗）」の2つの代表的な蔵元がある。矢尾本店は西武秩父駅から徒歩10分で試飲ができる（要予約）。純米吟醸¥1,800〜が土産として最適。武甲正宗は秩父神社裏で、並んで飲み比べると山の水の差がわかる。" },
      { type: "heading", content: "宿泊は秩父の星空を見るために", level: 2 },
      { type: "text", content: "秩父市内から車で20〜30分の山間部は関東でも数少ない光害の少ないエリアだ。「満天の星が見える宿・秩父山の宿」などの山間の民宿（¥10,000〜）に1泊すると、夜9時以降に肉眼で天の川が見える。これが一人旅で秩父に泊まる唯一の理由になり得る体験。" },
    ],
    relatedArticleSlugs: ["saitama-chichibu-day-trip", "saitama-nagatoro-rafting"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "saitama-chichibu-spring-flowers",
    title: "秩父の春花──芝桜・羊山公園・長瀞の桜を3日間で制覇",
    description: "4〜5月の秩父は花が連続する。最も効率的に春の全部を見るための旅程設計。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "saitama",
    tags: ["秩父", "芝桜", "桜", "春", "埼玉"],
    spotIds: ["chichibu", "nagatoro"],
    sections: [
      { type: "heading", content: "長瀞の桜（4月上旬）から春を始める", level: 2 },
      { type: "text", content: "4月第1週の長瀞駅周辺は荒川沿いに桜並木が咲く。岩畳の上から見る桜と川の景色は関東の桜スポットの中でも珍しい地形的な美しさを持つ。平日なら混雑が少なく、岩畳の上でゆっくり花見ができる。長瀞駅のSL（春季・秋季運行）に乗ると花見と乗り鉄を同時に体験できる。" },
      { type: "heading", content: "羊山公園の芝桜（4月下旬〜5月上旬）でピークを迎える", level: 2 },
      { type: "text", content: "芝桜の丘（¥300）の見頃は例年4月25日〜5月5日前後。平日の朝8時台に来ると入場直後で人が少なく、武甲山をバックにした芝桜の丘全体を撮れる。土日は9時で既に混雑するため前泊推奨。近隣の宿は2週間前には埋まる人気期間。" },
      { type: "heading", content: "荒川流域の菜の花と藤で5月を締める", level: 2 },
      { type: "text", content: "5月初旬〜中旬は荒川沿いの菜の花畑が開花する。秩父市内・長瀞町の荒川堤防沿いを車や自転車で流すと黄色の絨毯が続く。レンタサイクル（長瀞駅前・¥800/3時間）で荒川沿いを走るのが春の秩父を最も体感できる動き方だ。" },
    ],
    relatedArticleSlugs: ["saitama-chichibu-day-trip", "saitama-nagatoro-rafting"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "saitama-nagatoro-budget",
    title: "長瀞を¥3,000以下で楽しむ──ライン下りと岩畳と蝋梅を最安で全部やる",
    description: "長瀞観光の費用は工夫次第で3,000円台に収まる。節約しながらも体験を削らない方法。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "saitama",
    tags: ["長瀞", "節約", "秩父", "埼玉", "ハイキング"],
    spotIds: ["nagatoro"],
    sections: [
      { type: "heading", content: "電車は「秩父フリーきっぷ」で最安化", level: 2 },
      { type: "text", content: "西武鉄道の「秩父フリーきっぷ」（¥2,670〜）は池袋〜長瀞・西武秩父間を往復できる。単純往復より800円以上安い。フリーエリア内の電車は乗り放題で、長瀞と秩父を1日で両方周れる。土日祝限定で券売機で当日購入できる。" },
      { type: "heading", content: "ライン下りは「上長瀞〜長瀞」コースで十分", level: 2 },
      { type: "text", content: "急流を含む「上長瀞〜長瀞」コース（¥1,500・約20分）は最もコスパが高い。全行程コース（¥2,500）との差額¥1,000で急流の迫力は同じ体験ができる。ライン下り後の岩畳は無料で歩けるため、両者の差はほぼ静水区間の追加だけ。" },
      { type: "heading", content: "昼食は駅前の地元向け食堂を狙う", level: 2 },
      { type: "text", content: "長瀞駅前の「阿左美冷蔵」は天然氷のかき氷（¥900〜）で有名だが、隣の食堂「玉屋」は味噌カツ定食¥900・そば定食¥800とリーズナブル。観光客向けの店と地元民向けの店の価格差は1.5倍程度あるので見極めが必要。" },
    ],
    relatedArticleSlugs: ["saitama-nagatoro-rafting", "saitama-chichibu-solo"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "saitama-kawagoe-family",
    title: "川越ファミリー旅行──子どもが飽きない蔵造りと菓子屋横丁と芋体験",
    description: "小江戸川越は子どもにも楽しい体験が多い。家族で一日過ごす最適ルートを解説。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "saitama",
    tags: ["川越", "家族旅行", "子ども", "埼玉", "食べ歩き"],
    spotIds: ["kawagoe"],
    sections: [
      { type: "heading", content: "菓子屋横丁が子どもの最優先スポット", level: 2 },
      { type: "text", content: "菓子屋横丁の駄菓子屋は¥100以下の商品が多く、子どもが自分の予算で自由に選べる。麦こうじ・金平糖・ソースせんべいは昭和の味で大人も懐かしがる。路地全体が昭和の市場感覚で、子どもが初めて経験する「昔の買い物体験」になる。" },
      { type: "heading", content: "川越まつり会館は無料に近い価格で充実", level: 2 },
      { type: "text", content: "川越まつり会館（¥300）は江戸の祭礼文化を映像と実物で展示する。山車2台が常設展示されており、実物の大きさに子どもが圧倒される。12月3日の川越まつり期間は無料開放日がある。館内は20分で一周できるコンパクトな施設。" },
      { type: "heading", content: "川越いも芋掘り体験で農業を教える", level: 2 },
      { type: "text", content: "川越市近郊の農園では9月〜11月にサツマイモ掘り体験ができる（¥1,500〜¥2,000・食べ放題付き）。「農業体験農場あぐれっしゅ川越」は事前予約が必要だが、子どもが土から掘り出す達成感は他で代替できない体験だ。" },
    ],
    relatedArticleSlugs: ["saitama-kawagoe-model-course", "saitama-tetsudo-museum"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "saitama-nagatoro-luxury",
    title: "長瀞・秩父の贅沢旅──渓谷温泉宿と地酒ペアリングの上質な1泊2日",
    description: "長瀞の旅館は非常に品質が高い。知る人ぞ知る上質宿と秩父の地酒・地食材の組み合わせ。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "saitama",
    tags: ["長瀞", "温泉", "贅沢旅", "秩父", "埼玉"],
    spotIds: ["nagatoro", "chichibu"],
    sections: [
      { type: "heading", content: "長瀞の旅館で最高峰は「四萬部庵」", level: 2 },
      { type: "text", content: "荒川渓谷を望む客室と源泉掛け流し温泉を持つ「四萬部庵」（1泊2食¥28,000〜）は予約が取りにくい人気旅館だ。秩父の食材を中心にした懐石料理は猪・地鶏・秩父野菜が主役で、秩父錦の純米酒とのペアリングが提案されている。渓谷の露天風呂は夜11時まで開放。" },
      { type: "heading", content: "秩父ウイスキー「イチローズモルト」を現地で飲む", level: 2 },
      { type: "text", content: "秩父市の「ベンチャーウイスキー」が製造するイチローズモルトは世界的に評価の高い国産クラフトウイスキーだ。蒸留所見学（要予約）の後に直売所で購入すると定価で手に入る（¥4,000〜¥8,000）。東京の酒販店では入手困難なボトルも蒸留所直売には揃う。" },
      { type: "heading", content: "朝の渓谷を霧の時間に歩く贅沢", level: 2 },
      { type: "text", content: "秋冬の早朝（7〜9時）の長瀞渓谷は荒川から霧が立ち上る幻想的な景色を見せる。宿泊者のみが体験できる時間帯で、日帰り観光者が来る前の岩畳を独占できる。霧の中に浮かぶ岩畳の景色は撮影者にとって1年で最も価値の高い時間帯。" },
    ],
    relatedArticleSlugs: ["saitama-nagatoro-couple", "saitama-chichibu-solo"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "saitama-chichibu-winter",
    title: "冬の秩父──芝桜のない季節にこそ見えてくる本物の秩父",
    description: "観光客が減る冬の秩父は別の顔を持っている。霜と温泉と夜祭の三重奏。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-12-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "saitama",
    tags: ["秩父", "冬", "温泉", "夜祭", "埼玉"],
    spotIds: ["chichibu"],
    sections: [
      { type: "heading", content: "秩父夜祭（12月3日）は日本三大曳山祭", level: 2 },
      { type: "text", content: "12月3日の秩父夜祭は日本三大曳山祭（秩父・飛騨高山・京都祇園）の一つだ。笠鉾・屋台の山車6台が夜の秩父市内を練り歩き、深夜に御旅所へ向かう。打ち上げ花火は秩父の山々に反響して地鳴りのような音量になる。最寄りの西武秩父駅は当日は大混雑で、東武秩父駅側から入ると少し空いている。" },
      { type: "heading", content: "冬の秩父温泉で身体を温め直す", level: 2 },
      { type: "text", content: "秩父市内の「武甲温泉」（日帰り¥700）は地元民が使う温泉施設だ。アルカリ単純泉で肌に優しく、露天風呂から武甲山が見える。夜祭翌日に使うと疲れを取りながら秩父の山を眺めるリセットの時間が作れる。土日は¥800。" },
      { type: "heading", content: "蔵元の仕込み時期に酒造見学を入れる", level: 2 },
      { type: "text", content: "冬（12月〜2月）は日本酒の仕込み最盛期で、秩父の蔵元は見学可能な期間が増える。武甲酒造（予約制・無料）では仕込み蔵の内部と麹の発酵過程を見学できる。試飲は搾りたての「しぼりたて生原酒」（¥300〜）が飲めるため、冬の秩父訪問に必ず組み込む価値がある。" },
    ],
    relatedArticleSlugs: ["saitama-chichibu-day-trip", "saitama-chichibu-solo"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "saitama-omiya-day-walk",
    title: "大宮半日散歩──氷川神社・鉄道博物館・大宮公園を午前中で回る",
    description: "大宮は半日で十分に濃い。徒歩とバスで回れる3つの目的地の最短ルートを解説。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-06-08",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "saitama",
    tags: ["大宮", "散歩", "氷川神社", "鉄道博物館", "埼玉"],
    spotIds: [],
    sections: [
      { type: "heading", content: "8時スタートで氷川神社の静寂を味わう", level: 2 },
      { type: "text", content: "大宮駅東口から徒歩15分で氷川神社参道に入る。参道の一の鳥居から2km歩いて本殿へ向かうルートが基本。8時台は参拝者がほとんどおらず、朝の光の中で杉並木を歩く体験ができる。参拝後に境内の休憩所で無料のお茶と御神水が飲める。" },
      { type: "heading", content: "大宮公園で桜か紅葉を確認する", level: 2 },
      { type: "text", content: "氷川神社に隣接する大宮公園は花見（4月）と紅葉（11月）のシーズンが特に美しい。ハナミズキ並木は5月初旬に白とピンクの花が咲き、穴場の花見スポットになる。公園内の動物園（無料）は小動物と鳥類がメインで、子ども連れにも最適。" },
      { type: "heading", content: "鉄道博物館で正午まで過ごす", level: 2 },
      { type: "text", content: "大宮公園から「ニューシャトル（¥170）」で鉄道博物館前駅へ1駅。10時開館に合わせて入場すると午前中で主要展示を回れる。昼食はランチトレイン（¥1,200〜）か、大宮駅に戻って北海道・東北・上越の各駅弁が買えるエキュート大宮（常時30種以上）を活用する。" },
    ],
    relatedArticleSlugs: ["saitama-omiya-hikawa-shrine", "saitama-tetsudo-museum"],
  },
];
