import { Article } from "@/types/article";

export const shimaneArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "shimane-izumo-taisha-guide",
    title: "出雲大社、正しい参拝の作法──二礼四拍手一礼の理由を知る",
    description: "全国で二礼二拍手一礼が標準の神社参拝。出雲大社だけが四拍手である理由と、その作法が持つ意味を解説する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "shimane",
    tags: ["出雲大社", "参拝作法", "縁結び", "島根", "パワースポット"],
    spotIds: ["izumo-taisha"],
    sections: [
      { type: "heading", content: "四拍手の由来──偶数は「陰」の数", level: 2 },
      { type: "text", content: "出雲大社が四拍手を採用するのは、大国主命（おおくにぬしのみこと）が地上の守り神として特別な敬意を示す習慣が続いているためとされる。偶数の拍手が「陰」の世界、すなわち縁や運命に関わる神様への作法として定着したという説が有力だ。" },
      { type: "spot-card", content: "izumo-taisha" },
      { type: "heading", content: "参拝ルートは勢溜の大鳥居から始める", level: 2 },
      { type: "text", content: "出雲大社の正式な参拝は「勢溜の大鳥居」から始まる。一の鳥居から順に四つの鳥居をくぐって本殿に向かう。拝殿の大しめ縄は写真で見るより遥かに大きく、実物の迫力に圧倒される。" },
      { type: "heading", content: "神在月（旧暦10月）に訪れる価値", level: 2 },
      { type: "text", content: "旧暦10月は全国の神様が出雲に集まるとされる「神在月」。出雲以外の地域では「神無月」と呼ばれる逆説が面白い。神迎神事（11月頃）は稲佐の浜で執り行われ、神様を迎える行列が大社へ向かう様子を一般参観できる。" },
    ],
    relatedArticleSlugs: ["shimane-izumo-enmusubi", "shimane-matsue-castle-guide"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "shimane-izumo-enmusubi",
    title: "縁結びの聖地・出雲──恋愛だけじゃない「縁」のすべて",
    description: "出雲の「縁結び」は恋愛に限らない。人と人、人と仕事、人と土地のあらゆる縁を結ぶ神様の話。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "shimane",
    tags: ["出雲大社", "縁結び", "カップル", "恋愛", "島根"],
    spotIds: ["izumo-taisha"],
    sections: [
      { type: "heading", content: "大国主命が「縁結び」の神になった理由", level: 2 },
      { type: "text", content: "大国主命は国造りの神であり、あらゆる人の縁・運命を結ぶ存在とされる。恋愛に限らず、友情・仕事・土地との縁もこの神の担当だ。出雲大社へ参拝するカップルが多いのは正しい選択だが、「縁のすべて」を願う場として参拝するとより深みが増す。" },
      { type: "heading", content: "出雲大社周辺の縁結びスポット", level: 2 },
      { type: "text", content: "大社から徒歩圏内にある「命主社（いのちぬしのやしろ）」は、縁結びの補完神が祀られる小さな社。大きな本殿より静かに参拝できる。稲佐の浜は神様が上陸する海岸で、夕暮れ時の雰囲気は格別だ。" },
      { type: "heading", content: "出雲そばで参拝の疲れを取る", level: 2 },
      { type: "text", content: "出雲大社の参拝後は、大社門前の老舗そば屋で出雲そばを食べるのが習慣だ。割子そばは3段の丸い漆器に盛られ、つゆをかけて食べる独特の様式。そばの色が濃く、香りと風味が強い。出雲そばを食べてこそ、出雲参拝は完結する。" },
    ],
    relatedArticleSlugs: ["shimane-izumo-taisha-guide", "shimane-tamatsukuri-onsen"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "shimane-matsue-castle-guide",
    title: "国宝松江城の歩き方──堀川遊覧船と黒い天守の一日",
    description: "現存12天守かつ国宝。松江城はただ上るだけでなく、お堀の遊覧船と組み合わせると一日分の見応えになる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "shimane",
    tags: ["松江城", "国宝", "堀川遊覧船", "松江", "島根"],
    spotIds: ["matsue-castle"],
    sections: [
      { type: "heading", content: "開門直後に天守へ登る", level: 2 },
      { type: "text", content: "松江城天守は朝8時30分に開門する。開門直後は観光客が少なく、最上階からの宍道湖と市街の眺望を独占できる。黒い板張りの外壁と現存する木造の内部は、再建天守とは全く異なる空気感がある。" },
      { type: "spot-card", content: "matsue-castle" },
      { type: "heading", content: "堀川遊覧船は橋の下をくぐる瞬間が名場面", level: 2 },
      { type: "text", content: "堀川遊覧船は約50分でお堀を一周する。コースの途中、低い橋を通過するときに船の屋根が下がる仕掛けがある。船頭さんが「頭を下げてください」と案内する瞬間は、全乗客が笑顔になる名場面だ。" },
      { type: "heading", content: "小泉八雲の家と記念館を歩く", level: 2 },
      { type: "text", content: "堀川沿いには小泉八雲（ラフカディオ・ハーン）が暮らした旧居と記念館がある。松江を愛し、日本に帰化したアイルランド出身の作家の視点を通じて、松江がいかに魅力的な都市であるかが伝わる展示になっている。" },
    ],
    relatedArticleSlugs: ["shimane-matsue-sunset", "shimane-izumo-taisha-guide"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "shimane-matsue-sunset",
    title: "宍道湖の夕日──松江が選ばれ続ける夕景の理由",
    description: "宍道湖に沈む夕日は「日本の夕日百選」に選ばれている。ベストポジションと撮影のタイミングを伝える。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-25",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "shimane",
    tags: ["宍道湖", "夕日", "松江", "絶景", "島根"],
    spotIds: ["matsue-castle"],
    sections: [
      { type: "heading", content: "夕日スポットは「嫁ヶ島」のある宍道湖北岸", level: 2 },
      { type: "text", content: "宍道湖の北岸沿いを走る国道9号沿い、特に松江市街から西に延びる袖師町あたりが夕日の名所だ。湖の中央に浮かぶ小島「嫁ヶ島」のシルエットと夕日の組み合わせは、松江を象徴する景観として写真集でも頻繁に登場する。" },
      { type: "heading", content: "松江城天守最上階から見る夕景", level: 2 },
      { type: "text", content: "松江城の天守最上階からも宍道湖の夕景が見える。天守の閉門は通常17時30分（夏季18時30分）のため、タイミングが合えば城の中から夕日を眺められる。宍道湖の湖面が橙色に染まる瞬間は、この場所でしか見られない。" },
      { type: "heading", content: "夕日と宍道湖七珍のシジミ汁で締める", level: 2 },
      { type: "text", content: "夕日鑑賞の後は宍道湖のシジミ汁を食べてほしい。宍道湖はヤマトシジミの産地として全国有数で、松江市内の居酒屋や食堂で必ず提供されている。シジミの旨みが凝縮した汁は、旅の一日を締めくくるにふさわしい。" },
    ],
    relatedArticleSlugs: ["shimane-matsue-castle-guide", "shimane-tamatsukuri-onsen"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "shimane-iwami-ginzan-world-heritage",
    title: "石見銀山を歩く──世界遺産の坑道と江戸の町並みを半日で体験",
    description: "石見銀山は広大な世界遺産エリアだ。龍源寺間歩・大森の町並み・自転車ルートを地図なしで回れる完全ガイド。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "shimane",
    tags: ["石見銀山", "世界遺産", "銀山", "大森", "島根"],
    spotIds: ["iwami-ginzan"],
    sections: [
      { type: "heading", content: "入口は「石見銀山世界遺産センター」から", level: 2 },
      { type: "text", content: "石見銀山の観光はJR大田市駅からバスで約40分の「石見銀山世界遺産センター」が起点だ。無料の展示室で銀山の歴史を把握してから、自転車を借りて移動すると効率がいい。一般公開されている坑道「龍源寺間歩」まではセンターから約2km。" },
      { type: "spot-card", content: "iwami-ginzan" },
      { type: "heading", content: "龍源寺間歩──坑道の涼しさと暗闇", level: 2 },
      { type: "text", content: "龍源寺間歩は全長273mの坑道のうち157mが公開されている。年間を通じて洞内温度は10℃前後で、夏は外との温度差に身震いする。狭い坑道を進むと当時の採掘の様子を示す鑿の痕が至る所に残り、労働の過酷さが伝わってくる。" },
      { type: "heading", content: "大森地区の江戸〜明治の建物を歩く", level: 2 },
      { type: "text", content: "龍源寺間歩から自転車を戻し、大森地区の町並みを歩く。古民家を使ったカフェ・雑貨店・工芸品店が点在し、観光地化されていながらも生活感が残る不思議な街だ。石畳の路地を抜けながら、銀山で栄えた時代の建築様式を観察できる。" },
    ],
    relatedArticleSlugs: ["shimane-izumo-taisha-guide", "shimane-tsuwano-walk"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "shimane-tamatsukuri-onsen",
    title: "玉造温泉──神話の国の美肌の湯に泊まる一泊",
    description: "「神々の湯」と称される玉造温泉は日本最古の温泉のひとつ。美肌効果で知られるアルカリ性単純泉の正体とは。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-10-30",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "shimane",
    tags: ["玉造温泉", "温泉", "美肌", "島根", "宿泊"],
    spotIds: [],
    sections: [
      { type: "heading", content: "「美人の湯」と呼ばれる科学的理由", level: 2 },
      { type: "text", content: "玉造温泉のお湯はpH9.4以上のアルカリ性単純泉。アルカリ性の泉質は皮膚表面の古い角質を溶かす作用があり、入浴後に肌がなめらかに感じる理由だ。メタケイ酸の含有量が高く、肌のハリを保つとされる成分も豊富に含まれている。" },
      { type: "heading", content: "温泉街を流れる玉湯川沿いの散策", level: 2 },
      { type: "text", content: "玉造温泉は玉湯川沿いに旅館が並ぶ温泉街で、川沿いの遊歩道を浴衣で歩く夕暮れの散歩が定番だ。足湯が複数設置されているため、外出時に立ち寄れる。出雲大社から1時間程度でアクセスできるため、出雲参拝の翌日に泊まる旅程が人気だ。" },
      { type: "heading", content: "姫神山の「勘助の湯」で共同浴場を体験", level: 2 },
      { type: "text", content: "玉造温泉の中心部に無料の共同浴場「姫神山の湯（勘助の湯）」がある。小さいが地元の人も使う本物の共同浴場で、旅館の温泉とはまた違う湯使いが体験できる。宿泊者はここを外湯として使うことで、より豊かな温泉体験になる。" },
    ],
    relatedArticleSlugs: ["shimane-matsue-sunset", "shimane-izumo-enmusubi"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "shimane-tsuwano-walk",
    title: "津和野──山陰の小京都を歩く鯉と石畳の散策記",
    description: "島根県西端の小さな城下町・津和野。掘割を泳ぐ鯉と白壁の街並みは、観光地化されながらも本物の静けさが残る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "shimane",
    tags: ["津和野", "城下町", "山陰の小京都", "鯉", "島根"],
    spotIds: [],
    sections: [
      { type: "heading", content: "鯉が泳ぐ掘割は商店街の下を流れる", level: 2 },
      { type: "text", content: "津和野の殿町通りには古い商家の前に掘割が走り、大きな鯉が泳いでいる。この鯉は江戸時代に武士が飢饉の備えとして放したのが起源とされ、現在は観光資源として大切に守られている。透明な水の中を悠々と泳ぐ色とりどりの鯉は、静かな街並みに映える。" },
      { type: "heading", content: "太鼓谷稲成神社から城下を見下ろす", level: 2 },
      { type: "text", content: "山の中腹に朱色の鳥居が連なる太鼓谷稲成神社は、日本五大稲荷のひとつに数えられる。約1,000基の鳥居のトンネルを抜けて登ると、津和野の城下町全体を見渡せる展望スポットに到着する。" },
      { type: "heading", content: "津和野の名菓「源氏巻」を試す", level: 2 },
      { type: "text", content: "津和野の土産の定番は「源氏巻（げんじまき）」。薄いどら焼き生地に餡を巻いた棒状の和菓子で、江戸時代から藩主への献上品として作られてきた。各店舗で微妙に餡の甘さや生地の厚みが違うため、食べ比べが楽しい。" },
    ],
    relatedArticleSlugs: ["shimane-iwami-ginzan-world-heritage", "shimane-izumo-taisha-guide"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "shimane-izumo-soba",
    title: "出雲そば──割子三段の食べ方と名店ガイド",
    description: "出雲そばは「割子」か「釜揚げ」かで食べ方が違う。出雲大社参拝後に食べるべき一杯の選び方。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "shimane",
    tags: ["出雲そば", "割子そば", "グルメ", "出雲", "島根"],
    spotIds: ["izumo-taisha"],
    sections: [
      { type: "heading", content: "割子そばの食べ方──つゆを重ねていく", level: 2 },
      { type: "text", content: "割子そばは丸い漆器（割子）に一口量のそばが盛られ、3〜5段重ねで出される。食べ方は最初の段につゆをかけて食べ、残ったつゆを次の段に移してかける。薬味のネギ・もみじおろし・のりを各段に足しながら風味を変えていくのが正解だ。" },
      { type: "heading", content: "釜揚げそばは冬に食べる", level: 2 },
      { type: "text", content: "出雲そばのもう一つの食べ方は「釜揚げ」。茹で汁ごとそばを器に移し、濃いつゆをかけて食べる。そば湯と一体で食べるため、体が温まる冬向きのスタイル。割子より素朴でそば本来の香りを楽しめる。" },
      { type: "heading", content: "大社門前の老舗は開店前に並ぶ", level: 2 },
      { type: "text", content: "出雲大社の神門通り沿いにある有名なそば屋は、週末は開店前から行列ができる。事前に混雑状況を調べておき、参拝は早朝に済ませ、そばは11時の開店直後に入るのが最も賢い。" },
    ],
    relatedArticleSlugs: ["shimane-izumo-taisha-guide", "shimane-izumo-enmusubi"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "shimane-iwami-ginzan-cycle",
    title: "石見銀山レンタサイクル完全ガイド──2時間でまわる遺産エリア",
    description: "広大な石見銀山エリアを最も効率的に回る手段は自転車だ。電動アシスト付きを選ぶべき理由と、走るべきルートを解説する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "shimane",
    tags: ["石見銀山", "レンタサイクル", "サイクリング", "島根", "観光"],
    spotIds: ["iwami-ginzan"],
    sections: [
      { type: "heading", content: "電動アシスト付きを選ぶべき理由", level: 2 },
      { type: "text", content: "石見銀山エリアは起伏が多く、龍源寺間歩への往復は緩やかな上り坂が続く。電動アシスト付き自転車なら体力を消耗せず、帰りの大森地区散策に余力を残せる。レンタル料は電動で約1,500円（2時間）と少し高いが選ぶ価値がある。" },
      { type: "heading", content: "推奨ルート：センター→龍源寺間歩→大森→センター", level: 2 },
      { type: "text", content: "世界遺産センターを出発して銀山街道を北上し、龍源寺間歩を見学（30分）。そこから自転車を大森地区の駐輪場に置いて散策（40分）。センターに戻るまでのルートは下り基調で走りやすい。全行程2時間で充実した銀山体験ができる。" },
      { type: "heading", content: "散策後の昼食は大森の古民家カフェで", level: 2 },
      { type: "text", content: "大森地区にはいくつかの古民家カフェがある。江戸時代の建物を改修した空間で食べるカレーや定食は、雰囲気も含めて満足度が高い。ただし席数が少ないため、到着時間が遅れると満席になることも。11時台に入るのが正解だ。" },
    ],
    relatedArticleSlugs: ["shimane-iwami-ginzan-world-heritage", "shimane-tsuwano-walk"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "shimane-matsue-onsen-ryokan",
    title: "松江の温泉旅館──宍道湖畔で玉造の湯と地元料理を楽しむ",
    description: "松江の観光を終えた後、宍道湖畔の温泉旅館に泊まる一泊。湖の幸を使った夕食と、部屋からの夕景が旅を完成させる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-11-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "shimane",
    tags: ["松江", "旅館", "宍道湖", "温泉", "島根"],
    spotIds: ["matsue-castle"],
    sections: [
      { type: "heading", content: "宍道湖畔の旅館に泊まる意味", level: 2 },
      { type: "text", content: "松江市内の宍道湖畔に建つ旅館では、客室から湖の夕日を眺められる部屋が人気だ。日没前30分〜後30分の1時間は、橙から深紫へと変化する湖面の色を眺めながら過ごす特別な時間になる。" },
      { type: "heading", content: "宍道湖七珍の夕食──シジミ・モロゲエビ・白魚", level: 2 },
      { type: "text", content: "宍道湖には「七珍」と呼ばれる7種の食材がある。スズキ・モロゲエビ・ウナギ・アマサギ・シジミ・コイ・シラウオ。地元の旅館の夕食にはこれらが組み込まれており、特にシジミの味噌汁と白魚の天ぷらは他では食べられない味だ。" },
      { type: "heading", content: "朝食前に城山・城跡を朝散歩する", level: 2 },
      { type: "text", content: "松江の旅館に泊まると早朝の松江城が歩いて行ける距離にある。朝7時台の城山は観光客がおらず、石垣と堀川の静けさの中に城が佇む。朝食前の30分散歩が、松江滞在の記憶の中で最も鮮明に残ることが多い。" },
    ],
    relatedArticleSlugs: ["shimane-matsue-sunset", "shimane-tamatsukuri-onsen"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "shimane-izumo-kamiari",
    title: "神在月の出雲──日本中の神様が集まる旧暦10月の特別な旅",
    description: "旧暦10月（新暦11月頃）だけ出雲は「神有月」になる。神迎祭・神在祭の期間に合わせて出雲を訪れる意味を伝える。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-11-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "shimane",
    tags: ["出雲大社", "神在月", "神在祭", "縁結び", "島根"],
    spotIds: ["izumo-taisha"],
    sections: [
      { type: "heading", content: "神迎神事は稲佐の浜で執り行われる", level: 2 },
      { type: "text", content: "神在月の始まりは、出雲大社から西2kmほどにある稲佐の浜での「神迎神事」だ。日没後、大きな松明の光の中で神職が神様を迎える儀式が行われる。一般見学が可能で、厳粛な空気の中で旧暦の日本の信仰文化に触れられる。" },
      { type: "heading", content: "神在祭中は「忌み言葉」に気をつける", level: 2 },
      { type: "text", content: "神在祭の期間、出雲では大声を上げたり騒がしくしたりすることが戒められてきた。現代でもその習慣は地元で引き継がれており、静かに参拝する姿勢が求められる。縁結び会議が行われているという信仰が、自然に場の雰囲気を変えている。" },
      { type: "heading", content: "神在祭の宿泊は早めに確保する", level: 2 },
      { type: "text", content: "神在祭期間は出雲周辺の旅館・ホテルが満室になりやすい。特に週末と神迎神事の前後は需要が集中するため、2〜3ヶ月前からの予約が必要だ。松江や玉造温泉に宿を取り、出雲まで日帰りで往復するルートも現実的な選択肢になる。" },
    ],
    relatedArticleSlugs: ["shimane-izumo-taisha-guide", "shimane-izumo-enmusubi"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "shimane-matsue-samurai",
    title: "松江城下の武家屋敷──小泉八雲が愛した「水の都」の原風景",
    description: "松江の魅力は松江城だけではない。城下に残る武家屋敷・堀川・水路の風景が、外国人にも愛された理由がある。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "shimane",
    tags: ["松江", "武家屋敷", "小泉八雲", "城下町", "島根"],
    spotIds: ["matsue-castle"],
    sections: [
      { type: "heading", content: "塩見縄手通り──最も松江らしい通り", level: 2 },
      { type: "text", content: "松江城の北側を走る塩見縄手は、江戸時代の武家屋敷が残る松江の代表的な景観スポットだ。土塀と松の木が続く約500mの通りは、両側に武家屋敷の遺構や復元建物が並ぶ。朝の光が土塀に斜めに差し込む時間帯が最も美しい。" },
      { type: "heading", content: "小泉八雲旧居──松江を愛した外国人の視点", level: 2 },
      { type: "text", content: "アイルランド系アメリカ人作家ラフカディオ・ハーンは1890年に松江に着任し、ここで日本女性と結婚して帰化した。彼が暮らした旧居は現存しており、当時の生活様式を見学できる。ハーンの著書「怪談」の執筆背景を知るとこの旧居がより深く見える。" },
      { type: "heading", content: "堀川と水路が作る「水の都」の景観", level: 2 },
      { type: "text", content: "松江には宍道湖から城を囲む堀川・中海へとつながる水路が張り巡らされている。小泉八雲が「水の都」と呼んだその景観は、今も堀川遊覧船の上から体感できる。水面の高さから見る城と武家屋敷の景色は、陸からでは気づかない松江の美しさを教えてくれる。" },
    ],
    relatedArticleSlugs: ["shimane-matsue-castle-guide", "shimane-matsue-sunset"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "shimane-iwami-ginzan-town",
    title: "大森の町を深掘りする──石見銀山の遺産は坑道だけじゃない",
    description: "石見銀山で最も見逃されているのが大森の町並みだ。江戸から昭和の建物が混在する生きた町の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "shimane",
    tags: ["石見銀山", "大森", "町並み", "古民家", "島根"],
    spotIds: ["iwami-ginzan"],
    sections: [
      { type: "heading", content: "大森代官所跡から歩き始める", level: 2 },
      { type: "text", content: "石見銀山の統治を担った代官所の跡地は、現在は広場になっている。この場所から銀山街道沿いに歩いていくと、江戸・明治・昭和の建物が混在する不思議な時間軸の街が続く。建物の年代を調べながら歩くと、街の「地層」が見えてくる。" },
      { type: "heading", content: "古民家を使ったショップで地元の工芸品を買う", level: 2 },
      { type: "text", content: "大森には古民家をリノベーションしたクラフトショップが点在する。石見焼の器・草木染めの布・銀細工のアクセサリーなど、地元作家の手仕事が並ぶ。どの店も小さいが、作り手と直接話せることが多く、物を買う以上の体験になる。" },
      { type: "heading", content: "大森の鉱山神社で銀山労働者を悼む", level: 2 },
      { type: "text", content: "大森地区の山側には、銀山で亡くなった坑夫や労働者の霊を慰める小さな祠が各所にある。世界遺産の「光」の部分だけでなく、過酷な労働の「影」の部分を感じる時間を持つと、石見銀山の重みが増す。" },
    ],
    relatedArticleSlugs: ["shimane-iwami-ginzan-world-heritage", "shimane-iwami-ginzan-cycle"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "shimane-shimane-peninsula",
    title: "島根半島ドライブ──出雲から松江をつなぐ海岸線の絶景",
    description: "出雲大社から松江城まで、島根半島の北岸を海沿いに走るドライブルートは景観の連続だ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-25",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "shimane",
    tags: ["島根半島", "ドライブ", "海岸線", "絶景", "島根"],
    spotIds: ["izumo-taisha", "matsue-castle"],
    sections: [
      { type: "heading", content: "稲佐の浜から半島北岸へ", level: 2 },
      { type: "text", content: "出雲大社を参拝した後、稲佐の浜を経由して島根半島の北岸道路に入る。国道431号線沿いに日本海の荒波と岩礁の景観が続く。晴れた日は水平線が驚くほど遠く、鉛色の曇り空の日は日本海の厳しさが伝わる。" },
      { type: "heading", content: "日御碕灯台──断崖に立つ白亜の灯台", level: 2 },
      { type: "text", content: "出雲大社から西に約10km、日御碕に立つ日御碕灯台は日本一高い灯台のひとつで、高さ43.65m。断崖の上に立つ白い灯台と青い海のコントラストは、島根半島ドライブの最初のハイライトだ。灯台内部の登頂体験もできる。" },
      { type: "heading", content: "美保関で松江側のゴールを迎える", level: 2 },
      { type: "text", content: "島根半島の東端「美保関」は、松江から約25kmの岬だ。美保神社（えびす様の総本社）と連絡船で松江へのルートがあり、半島ドライブのゴールとして最適な場所。美保関のカキ料理を食べてから松江市街に向かうと、一日のドライブが完結する。" },
    ],
    relatedArticleSlugs: ["shimane-izumo-taisha-guide", "shimane-matsue-sunset"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "shimane-budget-trip",
    title: "2泊3日で島根を回る──出雲・松江・石見銀山の節約旅行術",
    description: "島根は見どころが分散している。交通費を抑えながら出雲・松江・石見銀山を2泊3日で効率よく回る完全プラン。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "shimane",
    tags: ["島根", "節約旅行", "モデルコース", "2泊3日", "出雲"],
    spotIds: ["izumo-taisha", "matsue-castle", "iwami-ginzan"],
    sections: [
      { type: "heading", content: "1日目：出雲大社参拝と出雲そば", level: 2 },
      { type: "text", content: "大阪・岡山から特急やくもで松江へ、一畑電車で出雲大社前へ移動。午前中に出雲大社を参拝し、門前で出雲そばを食べる。午後は稲佐の浜と日御碕灯台を訪問。一畑電車・バスの1日フリー乗車券（約1,500円）が移動コストを抑える鍵だ。" },
      { type: "heading", content: "2日目：松江城・堀川遊覧船・宍道湖夕景", level: 2 },
      { type: "text", content: "出雲泊から松江に移動。午前中に松江城と堀川遊覧船。午後は小泉八雲旧居・武家屋敷の塩見縄手を散策。夕方は宍道湖畔で日没を鑑賞。宿は松江駅周辺のビジネスホテルで6,000〜8,000円を確保できる。" },
      { type: "heading", content: "3日目：石見銀山を2時間で回って帰路", level: 2 },
      { type: "text", content: "早朝に松江を出発し、JR大田市駅から石見銀山へ。龍源寺間歩・大森地区を電動自転車で2時間で回る。昼食後に大田市駅へ戻り、特急で広島・岡山経由で帰宅。3日間の交通費は2万円以内に収まる。" },
    ],
    relatedArticleSlugs: ["shimane-iwami-ginzan-world-heritage", "shimane-izumo-taisha-guide"],
  },
];
