import { Article } from "@/types/article";

export const tochigiArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-toshogu-model-course",
    title: "日光東照宮の全体を理解する半日コース──陽明門から奥宮まで見落としゼロ",
    description: "508体の彫刻と眠り猫。観光客の9割が見ていない場所を含む完全見学ルート。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tochigi",
    tags: ["日光東照宮", "日光", "世界遺産", "栃木", "モデルコース"],
    spotIds: ["nikko-toshogu"],
    sections: [
      { type: "heading", content: "9時開門直後に表門をくぐる", level: 2 },
      { type: "text", content: "日光東照宮は9時開門。混雑は11時以降に急増するため、9時〜10時半を核として動くことが鉄則だ。表参道から石段を上がり、表門をくぐると三神庫（上神庫・中神庫・下神庫）が左右に現れる。上神庫の「想像の象」は実物を見ずに絵師が描いた象の絵彫刻で、象に見えない象として有名。" },
      { type: "heading", content: "神厩舎の三猿は8枚の物語の2枚目", level: 2 },
      { type: "text", content: "三猿は神厩舎（馬小屋）の8枚の彫刻パネルの2枚目に位置する。人生の成長を描いた物語のうち「幼年期に悪を見聞きしない」場面が三猿だ。8枚を順に読んでいくと、日光東照宮が伝えたかったメッセージが見えてくる。見学時間は30分を確保すること。" },
      { type: "heading", content: "陽明門は上を見ながら1時間かけて回る", level: 2 },
      { type: "text", content: "陽明門は高さ11m・幅7mの門の表面全体に508体の彫刻が埋め尽くされている。白と金の配色が日光の杉の緑と対比する。一日中見ていられるという意味で「日暮の門」と呼ばれた。門の裏面を見る観光客は少ないが、裏面にも細密な彫刻が続いており表面と異なるパターンがある。" },
      { type: "heading", content: "眠り猫と奥宮の207段石段が最終目的地", level: 2 },
      { type: "text", content: "眠り猫は左甚五郎作とされる木彫りの猫で、廊下の天井近くに設置されている。その裏面には2羽の雀が彫られており「猫が眠っていても雀が平和に遊べる＝平和な世」を表す。奥宮まで207段の石段を登ると家康の墓所・宝塔がある。石段の脇の杉の古木が醸す静寂は、陽明門の絢爛とは全く別の空気だ。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-kegon-falls", "tochigi-nikko-autumn-foliage"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-kegon-falls",
    title: "華厳の滝の全て──地下観瀑台と紅葉の最適シーズンと周辺3滝ルート",
    description: "日本三大瀑布を地下100mから見上げる。中禅寺湖エリアの全滝を1日で制覇する方法。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-10-18",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tochigi",
    tags: ["華厳の滝", "日光", "紅葉", "栃木", "滝"],
    spotIds: ["kegon-falls"],
    sections: [
      { type: "heading", content: "地下観瀑台は¥570で別次元の体験", level: 2 },
      { type: "text", content: "有料エレベーター（¥570往復）で地下100mまで降りると、落差97mの滝を真横から見上げる位置に出る。水しぶきが顔にかかる距離感で、上から見る無料展望台とは全くの別物だ。エレベーターは8時から動いており、開館直後なら待ち5分以内。紅葉シーズンは20分待ちになる。" },
      { type: "heading", content: "中禅寺湖展望台から華厳の滝と湖を同時に見る", level: 2 },
      { type: "text", content: "華厳の滝の上部展望台から歩いて5分の中禅寺湖展望台は、湖面と滝の両方が同じ視野に入る。10月下旬の紅葉ピーク時は周囲の山肌が赤・黄・橙に染まり、湖の青と滝の白が重なる景色は「日本の秋の頂点」と言い切れる。" },
      { type: "heading", content: "竜頭の滝と湯滝で「奥日光三名瀑」を完成させる", level: 2 },
      { type: "text", content: "華厳の滝・竜頭の滝・湯滝の3つが奥日光三名瀑と呼ばれる。竜頭の滝は中禅寺湖北岸でバス移動（約15分）。湯滝は湯ノ湖から流れ落ちる形式で、滝壺から見上げると岩壁を白い水が落ちる迫力がある。3つ全部を1日で回るには東武バスの1日乗車券（¥2,000）が必須。" },
      { type: "heading", content: "紅葉の見頃は10月20日〜11月5日前後", level: 2 },
      { type: "text", content: "奥日光の紅葉は例年10月中旬から始まり10月下旬にピークを迎える。中禅寺湖周辺から日光市街へ向かうにつれて標高が下がるため、下りの方向に色が広がっていく。日光東照宮周辺の紅葉は11月5日前後まで楽しめ、東照宮と紅葉を同時に楽しめる最大のチャンス。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-kinugawa-onsen-stay"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "tochigi-kinugawa-onsen-stay",
    title: "鬼怒川温泉で1泊──渓谷を見下ろす露天風呂と正しい宿の選び方",
    description: "東京から2時間の温泉渓谷。コスパの高い旅館の選び方とライン下りのベストシーズン。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-11-05",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "tochigi",
    tags: ["鬼怒川温泉", "温泉", "栃木", "日光", "宿泊"],
    spotIds: ["kinugawa-onsen"],
    sections: [
      { type: "heading", content: "鬼怒川の旅館は「渓谷露天あり」が絶対条件", level: 2 },
      { type: "text", content: "鬼怒川温泉の旅館の差は「渓谷を見下ろす露天風呂があるか否か」に尽きる。「あさや」「鬼怒川パークホテルズ」「藤屋御本陳」などが渓谷露天で評価が高い。泉質はアルカリ単純泉でほぼ共通だが、露天からの視野が旅の記憶を決定する。秋の紅葉シーズン（10月下旬）は3か月前予約が必要。" },
      { type: "heading", content: "ライン下りは春（雪解け）か秋（紅葉）が最高", level: 2 },
      { type: "text", content: "鬼怒川ライン下りは4km・約30分のコース（¥1,700〜¥2,000）で春〜秋に運行する。3月下旬〜4月の雪解け時期は水量が最大で急流の迫力が増す。10月下旬は渓谷の両岸が紅葉に染まる「紅葉のライン下り」が体験できる。事前予約は土日祝には不可欠。" },
      { type: "heading", content: "廃墟旅館の景観という独特の体験", level: 2 },
      { type: "text", content: "鬼怒川には1990年代のバブル崩壊後に廃業した大型旅館の廃墟が今も残る。廃墟自体は立入禁止だが、川沿いから見える廃墟と自然の混在する光景は「終わった観光地の静寂」として独特の存在感を持つ。廃墟と温泉の新旧が混在する川沿いの遊歩道散歩は鬼怒川でしかできない体験。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-nikko-kegon-falls"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "tochigi-ashikaga-flower-park",
    title: "足利フラワーパークの藤──樹齢150年の大藤と夜間ライトアップの完全攻略",
    description: "CNNが選んだ「世界の夢の旅行先」。藤のトンネルと大藤の正しい見方を教える。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-04-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tochigi",
    tags: ["足利フラワーパーク", "藤", "夜景", "栃木", "写真映え"],
    spotIds: ["ashikaga-flower-park"],
    sections: [
      { type: "heading", content: "大藤4本の見頃は4月下旬〜5月上旬", level: 2 },
      { type: "text", content: "樹齢150年の大藤4本が見頃を迎えるのは例年4月25日〜5月5日前後だ。1本の大藤が1,000平方mを覆う花の天蓋は、昼間でも暗くなるほどの密度がある。白藤のトンネルは全長80mで潜り歩く体験ができ、藤の香りが強い。入場料は繁忙期¥1,700（時期によって変動）。" },
      { type: "heading", content: "夜間ライトアップは昼の藤とは別物", level: 2 },
      { type: "text", content: "日没後のライトアップは大藤の房が下方向から照らされ、昼間の可憐さとは全く異なる妖艶な光景が広がる。藤の紫色が夜の暗さでより深く見えるため、写真映えは昼より夜の方が圧倒的に高い。ライトアップは日没から21時まで（繁忙期）で、20時台が最も人が少なくゆっくり鑑賞できる。" },
      { type: "heading", content: "チケット購入は事前オンラインが必須", level: 2 },
      { type: "text", content: "藤の最盛期（4月最終週〜5月GW）は入場制限が実施される。当日窓口では入場できない日が発生するため、公式サイトでの事前購入を必須とする。平日の朝10時〜正午は比較的空いており、週末午後と比較して待ち時間が80%減少する。" },
      { type: "heading", content: "冬のイルミネーション（11〜2月）も別の絶景", level: 2 },
      { type: "text", content: "藤の季節が終わった11月からは大規模なイルミネーションに切り替わる。光のトンネルや光の滝など冬限定の展示が登場し、足利フラワーパークは年間2シーズン楽しめる場所になっている。冬の入場料は藤シーズンより安く¥1,100〜。平日なら待ちゼロで入れる。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-utsunomiya-gyoza"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "tochigi-utsunomiya-gyoza",
    title: "宇都宮餃子の全部を食べ歩く──6店舗の価格・皮・タネ比較",
    description: "日本一の餃子消費都市・宇都宮。何が違うのか、なぜ旨いのか。6軒食べ歩いてわかった真実。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "tochigi",
    tags: ["宇都宮", "餃子", "グルメ", "栃木", "食べ歩き"],
    spotIds: [],
    sections: [
      { type: "heading", content: "宇都宮餃子の特徴──薄皮・野菜多め・安い", level: 2 },
      { type: "text", content: "宇都宮餃子の特徴は皮が薄く野菜の割合が高いことだ。キャベツ・ニラ・ニンニクを主役にして、豚肉は控えめに使う店が多い。価格は1皿（6個）¥250〜¥400が標準で、東京の餃子より3〜4割安い。焼き・水・揚げの3種が選べる店も多く、食べ比べを楽しむのが宇都宮流。" },
      { type: "heading", content: "来らっせ（地下）で全店舗を一気に制覇", level: 2 },
      { type: "text", content: "JR宇都宮駅前のオリオン通り地下にある「来らっせ」は宇都宮の主要餃子店が集まる施設だ。常設5店舗のほか日替わりで出店する店もあり、1か所で10種以上の餃子を食べ比べできる。1皿1〜2個から注文できる試食スタイルで、¥1,500〜¥2,000で十分に満足できる。" },
      { type: "heading", content: "行列の価値がある老舗3軒", level: 2 },
      { type: "text", content: "「正嗣（まさし）宮島本店」は焼き・水の2種のみで余計なものが何もない餃子の原型を出す（1皿¥230）。「みんみん」は宇都宮餃子文化の発信源の一つで、焼き・揚げ・水の3種が揃う（各¥290）。「宇都宮みんみん本店」は開店前から行列ができるが、回転が早く最大待ち30分で入れる。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-ashikaga-flower-park"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-couple",
    title: "日光カップル旅──世界遺産と温泉と中禅寺湖の完璧な2日間",
    description: "1泊2日で日光の全部を回る。東照宮・華厳の滝・鬼怒川温泉を最高の動線で繋ぐ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "tochigi",
    tags: ["日光", "カップル", "温泉", "栃木", "1泊2日"],
    spotIds: ["nikko-toshogu", "kegon-falls", "kinugawa-onsen"],
    sections: [
      { type: "heading", content: "1日目午前：日光東照宮を朝から攻略", level: 2 },
      { type: "text", content: "東京駅8時発の日光・きぬがわ号（特急）で東武日光駅へ（約1時間50分）。9時開門の東照宮を陽明門・眠り猫・奥宮の順に巡る。2人で歩く石段の静寂は、混雑時間より早い朝の特権。拝観料¥1,300×2名。昼前に中禅寺湖方面へバスで移動。" },
      { type: "heading", content: "1日目午後：中禅寺湖と華厳の滝", level: 2 },
      { type: "text", content: "昼食は中禅寺湖畔の「日光レークサイドホテル」レストランで虹鱒の一皿（¥2,200〜）がおすすめ。食後に華厳の滝の地下観瀑台へ（¥570）。17時台の中禅寺湖は夕日が水面に反射して朝とは別の表情を見せる。夕方バスで鬼怒川温泉へ移動（約40分）して宿泊。" },
      { type: "heading", content: "2日目：渓谷温泉と日光市街の散策", level: 2 },
      { type: "text", content: "2日目朝は宿の露天風呂で渓谷を見下ろす時間を作る。午前中に日光市街に戻り、二荒山神社・輪王寺を追加参拝。日光は東照宮だけでなく「二社一寺」が世界遺産構成の全体像。日光ゆば料理（昼食¥1,500〜）を食べて帰路へ。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-kinugawa-onsen-stay"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-family",
    title: "日光ファミリー旅行──子どもが飽きない世界遺産と滝と温泉の2泊3日",
    description: "子連れで日光を回る最大の課題は「飽き」だ。全行程を子ども視点で設計した完全プラン。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-07-18",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "tochigi",
    tags: ["日光", "家族旅行", "子ども", "栃木", "世界遺産"],
    spotIds: ["nikko-toshogu", "kegon-falls", "kinugawa-onsen"],
    sections: [
      { type: "heading", content: "1日目：東照宮は「三猿クイズ」で子どもを巻き込む", level: 2 },
      { type: "text", content: "子どもと東照宮を回るなら、神厩舎の8枚の彫刻パネルを順番に見せながら「これは何をしているシーンか」とクイズ形式で歩くと飽きない。三猿の「見ざる・言わざる・聞かざる」は子どもが自分で見つけると記憶に残る。奥宮の石段207段を親子で数えながら登るのも子どもが乗り越えやすい。" },
      { type: "heading", content: "2日目：華厳の滝のエレベーターに子どもが興奮", level: 2 },
      { type: "text", content: "地下100mへ降りるエレベーターは子どもにとって最高のアトラクション。地下観瀑台に着くと水しぶきが飛んでくる距離感は小学生以下に強い記憶を残す。龍頭の滝は遊歩道沿いに歩きやすく、小学生なら全行程1時間を歩き切れる体力で到達できる。" },
      { type: "heading", content: "3日目：鬼怒川でライン下りと温泉", level: 2 },
      { type: "text", content: "鬼怒川ライン下りは小学生から乗船可能（要ライフジャケット・無料貸出）。急流の前後に船頭のガイドがあり、子どもが怖くないよう声かけをしてくれる。宿の大浴場で温泉に初めて入る子どもには、ぬる湯から徐々に慣らすこと。鬼怒川温泉は家族向け旅館が多く、離れ型より大浴場付きの方が使い勝手がいい。" },
    ],
    relatedArticleSlugs: ["tochigi-kinugawa-onsen-stay", "tochigi-nikko-kegon-falls"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-autumn-foliage",
    title: "日光の紅葉完全ガイド──中禅寺湖から東照宮まで色付き日程を読む",
    description: "日本屈指の紅葉名所・日光。標高差を利用した「3週間楽しめる」紅葉観光の全手順。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-10-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tochigi",
    tags: ["日光", "紅葉", "秋", "栃木", "中禅寺湖"],
    spotIds: ["nikko-toshogu", "kegon-falls"],
    sections: [
      { type: "heading", content: "標高別の色付き順序を理解する", level: 2 },
      { type: "text", content: "日光の紅葉は標高の高い奥日光（1,400m）から始まり、中禅寺湖（1,270m）を経て、東照宮周辺（600m）へと2〜3週間かけて下りてくる。10月中旬：奥日光の木道、10月下旬：中禅寺湖・華厳の滝、11月上旬：東照宮・神橋の順で見頃を迎える。1回の訪問でどこを見るか事前に狙いを絞ることが重要。" },
      { type: "heading", content: "中禅寺湖展望台が日光紅葉の最高点", level: 2 },
      { type: "text", content: "中禅寺湖周辺の紅葉は10月20〜30日が例年のピーク。中禅寺湖展望台からは湖面に映る紅葉と奥に連なる山の色が同時に見える。戦場ヶ原のカラマツ黄葉（10月下旬〜11月上旬）は草原全体が黄金色に変わる光景で、木道を歩きながら見るのが正しいスタイル。" },
      { type: "heading", content: "紅葉×東照宮の最短2時間ルート", level: 2 },
      { type: "text", content: "東照宮周辺の紅葉見頃は11月5〜10日前後。陽明門の金箔と周囲の赤・黄が混在する景色は、この時期だけの特権だ。神橋（赤い橋・撮影有料¥300）越しに紅葉の山を撮る構図は日光を代表する秋の1枚になる。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-kegon-falls", "tochigi-kinugawa-onsen-stay"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-budget",
    title: "日光を1泊¥10,000以下で回る──節約旅行者のための費用最小化ガイド",
    description: "東照宮も華厳の滝も温泉も全部入れる。日光観光の費用を徹底的に削る方法。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-05-22",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "tochigi",
    tags: ["日光", "節約", "栃木", "1泊2日", "格安旅行"],
    spotIds: ["nikko-toshogu", "kegon-falls"],
    sections: [
      { type: "heading", content: "東武フリーパスで交通費を最小化", level: 2 },
      { type: "text", content: "東武浅草駅から「日光・鬼怒川エリアパス」（¥4,780）を使うと東武線往復＋日光・鬼怒川内バス乗り放題になる。通常の個別運賃（往復¥5,800+バス代）と比べると1,500円以上節約できる。特急ではなく急行を使えばさらに¥880の特急料金を削れる。" },
      { type: "heading", content: "日光二社一寺共通拝観券で割引", level: 2 },
      { type: "text", content: "東照宮・二荒山神社・輪王寺の共通拝観券（¥1,000）は個別購入（¥1,300+¥500+¥500＝¥2,300）より¥1,300安い。地下観瀑台（¥570）は別払いだが、それ以外は共通券で全て対応できる。" },
      { type: "heading", content: "宿泊は日光のゲストハウスか民宿", level: 2 },
      { type: "text", content: "日光市街の「日光ゲストハウス澤屋」はドミトリー¥3,500〜・個室¥7,000〜で提供。東照宮から徒歩15分の立地で、チェックアウト後も荷物を預けられる。朝食付きプランで¥4,500〜の民宿も複数ある。東京発の日帰り新幹線+観光よりも1泊の方が総コストが安くなるケースが多い。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-utsunomiya-gyoza"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "tochigi-kinugawa-luxury",
    title: "鬼怒川温泉の贅沢宿──露天風呂付き客室と栃木の食材尽くし懐石",
    description: "鬼怒川の高級旅館に泊まる価値。渓谷から聞こえる川音と、夜明けの露天風呂。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-09-28",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "tochigi",
    tags: ["鬼怒川温泉", "高級旅館", "贅沢旅", "栃木", "温泉"],
    spotIds: ["kinugawa-onsen"],
    sections: [
      { type: "heading", content: "「藤屋御本陳」は鬼怒川最高峰の旅館", level: 2 },
      { type: "text", content: "藤屋御本陳は客室数が少なく（全19室）、鬼怒川渓谷を専有する造りだ。1泊2食¥50,000〜と高額だが、各部屋に露天風呂があり渓谷の音と温泉を同時に体験できる唯一性がある。夕食の懐石は栃木の地野菜・日光ゆば・那須和牛が主役で8〜10品構成。宇都宮の純米酒「鳳凰美田」との相性が抜群。" },
      { type: "heading", content: "コスパが高い準高級旅館の選択肢", level: 2 },
      { type: "text", content: "「あさや」（1泊2食¥25,000〜）は大浴場が複数あり、渓谷を臨む大露天風呂の規模が圧倒的だ。「ホテルニュー岡部」（1泊2食¥18,000〜）は家族露天付きの部屋タイプがあり、プライバシー重視の旅行者に向く。どちらも紅葉シーズン（10月）は3か月前の予約が必要。" },
      { type: "heading", content: "翌朝の渓谷散歩で旅を完成させる", level: 2 },
      { type: "text", content: "朝7時の鬼怒川渓谷は霧が立ち込める日が多い（特に秋〜冬）。渓谷沿いの遊歩道を1時間歩くと、昼間とは全く異なる鬼怒川の静寂に包まれる。宿の朝食後に歩いてから帰路に就く順序が、鬼怒川温泉旅行を最大限に使いきる正しい終わり方だ。" },
    ],
    relatedArticleSlugs: ["tochigi-kinugawa-onsen-stay", "tochigi-nikko-couple"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "tochigi-utsunomiya-solo",
    title: "宇都宮一人旅──餃子6軒とカクテル文化と大谷資料館の1日",
    description: "宇都宮は餃子だけじゃない。大谷石の地下空間と日本屈指のカクテルバー文化がある。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-08-14",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tochigi",
    tags: ["宇都宮", "一人旅", "大谷資料館", "カクテル", "栃木"],
    spotIds: [],
    sections: [
      { type: "heading", content: "大谷資料館の地下空間は異次元", level: 2 },
      { type: "text", content: "宇都宮市郊外の大谷資料館は、大谷石の採石場跡を活用した地下空間の博物館だ。地下約30m、広さ2万平方mの空間は年中8℃に保たれており、夏は天然の涼しさが感じられる。柱状節理の岩壁が空洞を作る光景は映画のセットのようで、ライトアップは一種の現代アートになっている。入場¥800。" },
      { type: "heading", content: "宇都宮はカクテルの街でもある", level: 2 },
      { type: "text", content: "宇都宮はカクテルのバーテンダーの輩出地として知られており、市内に50軒以上のカクテルバーがある。「ミューズバー」「ルヴァン」などは創業30〜40年の老舗で、1杯¥1,200〜¥1,800で日本トップレベルのカクテルが飲める。餃子の後にカクテルバーへ行くのが宇都宮通の夜の正解。" },
      { type: "heading", content: "餃子6軒食べ歩きの正しい体重管理", level: 2 },
      { type: "text", content: "1皿6個の餃子を6店舗で1皿ずつ注文すると合計36個になる。1日かけて食べ歩くなら、昼前から18時頃まで2〜3時間おきに1軒ずつ入ると胃への負担が少ない。来らっせの試食スタイル（1〜2個単位）から始めて、気に入った店を再訪するルートが正しい攻め方だ。" },
    ],
    relatedArticleSlugs: ["tochigi-utsunomiya-gyoza", "tochigi-ashikaga-flower-park"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-tips",
    title: "日光観光の失敗しないコツ──混雑回避・駐車場・ランチ問題を全部解決",
    description: "週末の日光は渋滞と行列が酷い。現地を100回以上訪れた経験から失敗パターンを全て解説。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tochigi",
    tags: ["日光", "混雑回避", "旅のコツ", "栃木", "駐車場"],
    spotIds: ["nikko-toshogu"],
    sections: [
      { type: "heading", content: "週末の日光は電車で来るべき理由", level: 2 },
      { type: "text", content: "GWと紅葉シーズン（10月下旬〜11月上旬）の週末は、日光宇都宮道路の日光IC〜清滝IC間が30〜50km渋滞することがある。東武特急（浅草〜東武日光・約1時間50分）で来れば渋滞ゼロ。駐車場は東武日光駅前の有料（¥600/日）1か所だけで十分な量がある。" },
      { type: "heading", content: "ランチは11時前か14時以降で解決", level: 2 },
      { type: "text", content: "東照宮周辺の飲食店は12時〜13時に全て満席になる。日光ゆば料理は「日光金谷ホテル」（¥2,500〜）か「松本家」（¥1,800〜）が品質安定だが、どちらも11時前か14時以降に入らないと1時間待ちになる。コンビニ弁当を持参して神橋近くの公園で食べるのも実は最高の選択。" },
      { type: "heading", content: "拝観料の「二社一寺共通券」を絶対に使う", level: 2 },
      { type: "text", content: "東照宮・二荒山神社・輪王寺の個別拝観料の合計は¥2,300以上になる。共通拝観券（¥1,000）を東照宮入口で購入すると¥1,300以上節約できる。さらに輪王寺の「輪王寺宝物殿」（別料金¥200）は常に空いていて国宝の仏像を近距離で見られる穴場だ。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-nikko-budget"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "tochigi-ashikaga-winter-illumination",
    title: "足利フラワーパーク冬のイルミネーション──光の滝と光のトンネルの攻略法",
    description: "冬の足利フラワーパークは藤と並ぶ圧倒的な光の体験だ。混雑を避ける全手順。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-11-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tochigi",
    tags: ["足利フラワーパーク", "イルミネーション", "冬", "栃木", "夜景"],
    spotIds: ["ashikaga-flower-park"],
    sections: [
      { type: "heading", content: "11月下旬〜2月の冬イルミネーションの全容", level: 2 },
      { type: "text", content: "冬の足利フラワーパークは11月下旬〜2月にイルミネーション期間に入る。「光の滝」「光の藤」「光のトンネル」の3エリアが中心で、藤の木骨格にLEDを巻き付けた「光の藤」は藤シーズンを思わせる形状をそのまま光で表現している。入場料¥1,100で日没から21時まで開放。" },
      { type: "heading", content: "平日17時入場が最高のタイミング", level: 2 },
      { type: "text", content: "冬のイルミネーション鑑賞の理想は平日17時〜19時。日没直後の薄暮の空と光の対比が最も美しく、来場者密度が最低になる時間帯が重なる。土日の18時〜20時は入場待ちが発生することがある。電車で来る場合はJR両毛線富田駅から徒歩10分が最もスムーズ。" },
      { type: "heading", content: "宇都宮餃子とセットにした日帰り旅程", level: 2 },
      { type: "text", content: "宇都宮から両毛線で足利へ（約50分）移動し、足利フラワーパークのイルミネーション鑑賞後に宇都宮へ戻る動線が1日で完成する。帰りに宇都宮の餃子屋で夕食を取れば、餃子とイルミネーションという栃木の2大名物を1日で制覇できる。" },
    ],
    relatedArticleSlugs: ["tochigi-ashikaga-flower-park", "tochigi-utsunomiya-gyoza"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-solo",
    title: "日光一人旅──山岳霊場と深夜の温泉と夜明け前の石段",
    description: "一人だから深く入れる日光がある。人が来る前の東照宮と、深夜の鬼怒川を経験する旅。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-09-08",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tochigi",
    tags: ["日光", "一人旅", "栃木", "東照宮", "温泉"],
    spotIds: ["nikko-toshogu", "kinugawa-onsen"],
    sections: [
      { type: "heading", content: "前日入りして夜の日光を歩く", level: 2 },
      { type: "text", content: "日光市街に前泊して夜9時以降に街を散歩すると、昼間とは全く違う空気がある。東照宮の参道は夜間開放されておらず門が閉まっているが、石段の手前まで来て杉並木の奥の暗闇を感じる時間は一人旅の特権だ。参道沿いの旅館で地酒「日光誉」（栃木地酒）を飲んで早朝に備える。" },
      { type: "heading", content: "朝6時に神橋周辺から東照宮へ歩く", level: 2 },
      { type: "text", content: "東照宮は9時開門だが、参道・神橋周辺は朝6時から歩ける。朝霧が立ち込める杉並木を独り占めできる時間がある。神橋（¥300）は早朝でも渡れ、朝の霧の中の朱塗りの橋は日光で最も静寂な写真が撮れる場所だ。9時の開門に合わせて東照宮へ向かう流れが一人旅の理想的な朝動線。" },
      { type: "heading", content: "鬼怒川温泉の深夜の露天風呂", level: 2 },
      { type: "text", content: "鬼怒川の旅館の多くは深夜2時頃まで露天風呂を開放している。深夜の渓谷は無音に近く、川音だけが聞こえる中で湯に浸かる体験は、一人旅でないとできない質の集中がある。翌朝の早立ちのために5時に起きて再び露天に入ると、夜明けの渓谷が霧の中から姿を現す瞬間に立ち会える。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-kinugawa-luxury"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "tochigi-nasu-highland",
    title: "那須高原の全部──温泉・牧場・茶臼岳を1泊2日で制覇する",
    description: "栃木北部の那須高原は日光と並ぶ関東屈指のリゾート。その全体像を整理する。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-08-28",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tochigi",
    tags: ["那須高原", "温泉", "牧場", "栃木", "夏"],
    spotIds: [],
    sections: [
      { type: "heading", content: "那須温泉の多様な泉質を日帰りで回る", level: 2 },
      { type: "text", content: "那須温泉は「那須七湯」と呼ばれる7つの温泉地の総称だ。鹿の湯（硫黄泉・¥400）は那須最古の源泉で、草津温泉と同じ強酸性泉。大丸温泉（アルカリ泉）とのハシゴで全く異なる泉質を1日で体験できる。那須湯本温泉の共同浴場「鹿の湯」は6段階の温度設定（41〜48℃）があり、48℃に入れるかが那須の挑戦。" },
      { type: "heading", content: "那須高原の牧場で乳製品三昧", level: 2 },
      { type: "text", content: "「那須どうぶつ王国」と「東武ワールドスクウェア」は知名度が高いが、コスパの高い体験は「那須高原自然の家」周辺の小規模農場だ。地元の牧場直売のソフトクリーム（¥400〜）はチェーン店とは別物の濃さがある。チーズ工房「パストラル」（¥600）の見学は予約制で、製造過程を間近で見られる。" },
      { type: "heading", content: "茶臼岳（1,915m）にロープウェイで登る", level: 2 },
      { type: "text", content: "那須ロープウェイ（¥1,400往復）で茶臼岳山頂直下まで一気に上がれる。山頂まで徒歩20分で、噴煙を上げる那須岳の火山地形が間近に見える。晴れた日は関東平野が一望でき、東京スカイツリーが見えることもある。7月〜8月は花が咲き、10月は紅葉が始まる。強風の日は運休するため天気予報の確認が必須。" },
    ],
    relatedArticleSlugs: ["tochigi-kinugawa-onsen-stay", "tochigi-nikko-toshogu-model-course"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "tochigi-kinugawa-family",
    title: "鬼怒川温泉ファミリー旅──子どもが喜ぶアトラクションと家族風呂完備の宿",
    description: "鬼怒川は子連れ旅行に向いている。ライン下り・廃墟・温泉の三重奏を家族で体験。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-07-30",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "tochigi",
    tags: ["鬼怒川温泉", "家族旅行", "子ども", "栃木", "アトラクション"],
    spotIds: ["kinugawa-onsen"],
    sections: [
      { type: "heading", content: "東武ワールドスクウェアで1日潰す", level: 2 },
      { type: "text", content: "鬼怒川温泉駅から徒歩15分の「東武ワールドスクウェア」は世界の建造物を1/25サイズで再現したテーマパークだ（¥2,800・子ども¥1,400）。ピラミッド・エッフェル塔・東京スカイツリーなど102の建造物が1か所に集まっており、子どもが世界地図への興味を持つきっかけになる。所要時間は3〜4時間。" },
      { type: "heading", content: "ライン下りは小学生の好奇心を刺激する", level: 2 },
      { type: "text", content: "鬼怒川ライン下りは「急流・大波・水しぶき」が子どもの記憶に強く残る。小学生なら「怖い」と「楽しい」が混在する状態が最も価値の高い体験で、親と共有する感情の記憶になる。4月〜10月運行、料金¥1,700（子ども半額）、所要約30分。" },
      { type: "heading", content: "家族風呂がある宿の選び方", level: 2 },
      { type: "text", content: "幼児連れの場合は大浴場より「家族風呂（貸切露天）」がある宿が使いやすい。「ホテルニュー岡部」「鬼怒川グランドホテル夢の季」は家族風呂を複数持ち、1回45分¥2,000〜で利用できる。小学生低学年以下は大浴場で他の利用者に気を遣う必要がなくなるため、家族風呂一択が正解。" },
    ],
    relatedArticleSlugs: ["tochigi-kinugawa-onsen-stay", "tochigi-nikko-family"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "tochigi-ashikaga-solo",
    title: "足利一人旅──大藤・鑁阿寺・足利学校で古都の静寂を歩く",
    description: "足利は藤だけじゃない。日本最古の学校と関東最古の武家屋敷跡で歴史の層を感じる旅。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-05-08",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tochigi",
    tags: ["足利", "一人旅", "藤", "鑁阿寺", "栃木"],
    spotIds: ["ashikaga-flower-park"],
    sections: [
      { type: "heading", content: "足利学校で日本最古の学問の場を体感", level: 2 },
      { type: "text", content: "足利学校（¥420）は室町時代に創立した日本最古の学校とされる。学びの場を復元した建物が現役の文化財として公開されており、書物の複製や当時の教育カリキュラムを展示している。平日の朝は見学者が少なく、当時の学生が勉強した部屋を独り占めできる時間がある。" },
      { type: "heading", content: "鑁阿寺（ばんなじ）は足利氏の菩提寺", level: 2 },
      { type: "text", content: "鑁阿寺は足利氏の館跡を寺に転用した国宝・重要文化財の集積地だ。周囲を堀で囲まれた境内は「城」の原型を持ち、本堂（国宝）は鎌倉時代の木造建築が現役で立っている。入場無料。大銀杏（11月紅葉）は樹齢650年以上で、黄色に染まった秋の境内は足利で最も美しい光景の一つ。" },
      { type: "heading", content: "夕方の大藤ライトアップで1日を締める", level: 2 },
      { type: "text", content: "足利フラワーパーク（JR富田駅から徒歩10分）の日没後ライトアップは、混雑が日中より少なく藤の紫色が光に映える。一人でゆっくり大藤の下に立って見上げる時間は、団体客がいる昼間では体験できない静寂の藤鑑賞だ。20時以降に来ると人がさらに少なくなる。" },
    ],
    relatedArticleSlugs: ["tochigi-ashikaga-flower-park", "tochigi-utsunomiya-solo"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "tochigi-utsunomiya-tips",
    title: "宇都宮を1日で最大に楽しむコツ──餃子・大谷石・二荒山神社の動線設計",
    description: "宇都宮の観光地は点在している。最短動線で全部回るための移動術と優先順位。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-04-02",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tochigi",
    tags: ["宇都宮", "旅のコツ", "大谷石", "餃子", "栃木"],
    spotIds: [],
    sections: [
      { type: "heading", content: "朝は大谷資料館から逆方向へ回る", level: 2 },
      { type: "text", content: "宇都宮観光の定番は「まず餃子→大谷資料館」だが、大谷資料館（宇都宮駅西口からバス30分）を朝イチ（9時開館）で訪れる方が空いている。10時半に出て駅方面に戻りながら二荒山神社（11時）、昼に来らっせで餃子（12時）という逆算動線が渋滞と行列を最小化する。" },
      { type: "heading", content: "宇都宮の二荒山神社は見逃されている", level: 2 },
      { type: "text", content: "宇都宮城跡公園に隣接する二荒山神社は宇都宮の総鎮守で、市内最大の神社だ。桜の名所（4月上旬）として地元民には知られているが、観光客が少なく参拝者の列もない。境内からの宇都宮市街の眺望と、緑に囲まれた本殿は地方都市の神社の持つ落ち着きがある。参拝後に近くの宮カフェで宇都宮産のいちご（¥800〜）を食べる動線が完成形。" },
      { type: "heading", content: "帰りの新幹線で宇都宮の日帰り限界に挑む", level: 2 },
      { type: "text", content: "宇都宮は東京上野から新幹線で50分だ。朝8時に東京を出て夜20時に戻る日帰りでも、大谷資料館・二荒山神社・餃子6軒・カクテルバー1軒を全部こなせる。新幹線を使うと時間的コスパが大幅に上がるため、高速バス（安い）より新幹線（速い）を選ぶべき都市の典型例。" },
    ],
    relatedArticleSlugs: ["tochigi-utsunomiya-gyoza", "tochigi-utsunomiya-solo"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-luxury",
    title: "日光の贅沢旅──金谷ホテルで1泊、明治から続く老舗の格式を体験する",
    description: "明治6年開業の日光金谷ホテルに泊まる意味。日光でしか体験できない贅沢とは何か。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "tochigi",
    tags: ["日光", "金谷ホテル", "贅沢旅", "明治", "栃木"],
    spotIds: ["nikko-toshogu"],
    sections: [
      { type: "heading", content: "日光金谷ホテルは日本最古のクラシックホテル", level: 2 },
      { type: "text", content: "1873年（明治6年）開業の日光金谷ホテルは、日本に現存する最古のクラシックホテルのひとつだ。歴代のアメリカ大統領・英国王族・著名作家が宿泊してきた歴史を持つ。1泊¥40,000〜でメインダイニングの洋食コース（日光ゆばを使った創作西洋料理）が夕食の核。神橋から徒歩5分の立地で、朝の東照宮参道を人気のない時間に歩ける。" },
      { type: "heading", content: "メインダイニングの「日光ゆばと洋食」の組み合わせ", level: 2 },
      { type: "text", content: "金谷ホテルのメインダイニングでは日光名物のゆばを洋食のコースに取り込んだオリジナル料理が出る。ゆばと地魚のムニエル・那須牛のロースト・栃木野菜のグラタンというコース（¥8,000〜）は、和の食材と明治以来の洋食技術が融合した日光固有の料理体験だ。" },
      { type: "heading", content: "宿泊翌朝の東照宮を誰もいない時間に歩く", level: 2 },
      { type: "text", content: "金谷ホテルに泊まれば東照宮まで徒歩8分で9時開門に合わせて動ける。平日に宿泊すれば9時〜10時の東照宮は観光バスが来る前の静寂な時間帯で、陽明門を1人で独占できる瞬間が生まれる。この体験ができるかどうかが、日光観光に前泊する最大の価値だ。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-toshogu-model-course", "tochigi-nikko-couple"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "tochigi-nikko-chuzenji-lake",
    title: "中禅寺湖の1日──ボートと奥日光の湿原と湯元温泉で完成する",
    description: "日光の奥に広がる中禅寺湖エリア。東照宮より少ない観光客で本物の奥日光を体験する。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-07-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tochigi",
    tags: ["中禅寺湖", "日光", "奥日光", "栃木", "ハイキング"],
    spotIds: ["kegon-falls"],
    sections: [
      { type: "heading", content: "中禅寺湖でボートに乗る", level: 2 },
      { type: "text", content: "中禅寺湖の湖畔では手漕ぎボート（¥1,000/時間）とモーターボート（¥2,000/30分）が借りられる。湖面から見る男体山の正面構図は陸から見るのと別物の迫力がある。6〜7月はワカサギ釣りのボートが出回る時期で、湖の静けさに同調しながら釣りを楽しめる（竿レンタル¥500〜）。" },
      { type: "heading", content: "戦場ヶ原ハイキングで高層湿原を歩く", level: 2 },
      { type: "text", content: "中禅寺湖から光徳牧場方面へバスで20分の戦場ヶ原は標高1,400mの湿原だ。木道約5kmが整備されており、7月のホザキシモツケ（赤紫の花）・10月のカラマツ黄葉が主なハイライトになる。湿原の向こうに男体山と日光白根山が見える360度の眺望は「本物の奥日光」を感じさせる。" },
      { type: "heading", content: "湯元温泉で硫黄泉に浸かって完結", level: 2 },
      { type: "text", content: "戦場ヶ原から湯元温泉へバスで15分。湯元温泉の源泉は湯ノ湖湖畔に湧いており、硫黄泉の白濁した湯が特徴だ。温泉寺（日帰り¥500）は境内に源泉を引いた浴槽があり、お寺の本堂を見ながら入れる。湯元の日帰り施設「日光湯元ビジターセンター」の無料展示で奥日光の自然を学んでから帰路へ。" },
    ],
    relatedArticleSlugs: ["tochigi-nikko-kegon-falls", "tochigi-nikko-toshogu-model-course"],
  },
];
