import { Article } from "@/types/article";

export const tokushimaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "tokushima-iya-valley-autumn",
    title: "祖谷渓、秋霧の朝──かずら橋を渡る前に知っておきたいこと",
    description: "平家の落人が隠れ住んだ秘境・祖谷渓。紅葉と霧が重なる朝は、日本の原風景がここにある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokushima",
    tags: ["祖谷渓", "かずら橋", "秘境", "紅葉", "徳島"],
    spotIds: ["iya-valley"],
    sections: [
      { type: "heading", content: "霧が晴れる前に着いておく", level: 2 },
      { type: "text", content: "祖谷渓の朝霧は10月中旬から11月上旬にかけて、早朝5時から9時ごろに発生することが多い。前夜から近くの宿に泊まり、夜明け前に峠の展望台へ向かうと、谷間に霧が溜まる幻想的な景観に出会える。太陽が昇るにつれて霧が動き、紅葉した山肌が現れる瞬間は息をのむ美しさだ。" },
      { type: "heading", content: "かずら橋は潮時を選ぶ", level: 2 },
      { type: "text", content: "かずら橋の開橋は7時から。観光バスが到着する10時前後は混雑する。7時台か17時前後が空いており、橋を独占する気分で渡れる。シラクチカズラで編まれた橋は3年ごとに架け替えられるが、揺れと隙間はいつも本物のスリルだ。橋下に流れる祖谷川の青みがかった水が美しい。" },
      { type: "spot-card", content: "iya-valley" },
      { type: "heading", content: "奥祖谷二重かずら橋は知る人ぞ知る", level: 2 },
      { type: "text", content: "本家かずら橋から車で40分、奥祖谷には二重かずら橋がある。観光客が少なく、野猿（手漕ぎの川渡し）体験もできる。ここまで来ると、本当に平家落人の隠れ里に踏み込んだ気持ちになる。道は細いが舗装されており、レンタカーがあれば問題ない。" },
    ],
    relatedArticleSlugs: ["tokushima-oboke-rafting", "tokushima-model-course-2days"],
  },

  // ── 2 ──────────────────────────────────────
  {
    slug: "tokushima-naruto-whirlpools-guide",
    title: "鳴門の渦潮、大潮の日に行く──潮見表の読み方と観潮船の選び方",
    description: "渦潮は毎日同じではない。大潮・小潮で迫力は何倍も変わる。正しい日に行けば本物の轟音が体に響く。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokushima",
    tags: ["鳴門", "渦潮", "大潮", "観潮船", "徳島"],
    spotIds: ["naruto-whirlpools"],
    sections: [
      { type: "heading", content: "大潮の日を狙う──潮見表の見方", level: 2 },
      { type: "text", content: "渦潮は新月・満月の前後3日間、いわゆる「大潮」の時期が最大になる。鳴門海峡の潮流が最速になるのは干潮・満潮の前後約1時間。公式サイトや潮見表アプリで「鳴門」の潮汐を確認し、最大潮流時刻に合わせてスケジュールを組む。この日程にするだけで渦潮の直径が倍以上変わる。" },
      { type: "heading", content: "渦の道 vs 観潮船──どちらを選ぶか", level: 2 },
      { type: "text", content: "大鳴門橋の橋桁内を歩く「渦の道」はガラス床越しに俯瞰できる。高さ約45mから見下ろす渦潮は圧倒的だが、音がしない。観潮船は渦のすぐそばを航行するため、海水が渦巻く音と振動が体に直接来る。どちらか一方を選ぶなら、感動の質が違う観潮船を推薦する。両方行く時間があるなら、先に観潮船、帰りに渦の道が効率的だ。" },
      { type: "spot-card", content: "naruto-whirlpools" },
      { type: "heading", content: "鳴門公園で渦潮以外を楽しむ", level: 2 },
      { type: "text", content: "渦潮観光の前後に鳴門公園を散策する。千畳敷展望台からは大鳴門橋全体が見渡せ、橋と海峡の絶景が広がる。鳴門市ドイツ館は第一次世界大戦時の捕虜収容所の歴史を伝える意外な見どころ。鳴門の特産である鳴門金時（さつまいも）を使ったスイーツも商店街に充実している。" },
    ],
    relatedArticleSlugs: ["tokushima-iya-valley-autumn", "tokushima-gourmet-sudachi"],
  },

  // ── 3 ──────────────────────────────────────
  {
    slug: "tokushima-oboke-rafting",
    title: "大歩危でラフティング──吉野川の激流に飛び込む半日体験記",
    description: "日本屈指のラフティングポイント・大歩危。初心者でも体験できるコースと、押さえておきたい安全のコツ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tokushima",
    tags: ["大歩危", "ラフティング", "アクティビティ", "吉野川", "徳島"],
    spotIds: ["oboke-koboke"],
    sections: [
      { type: "heading", content: "大歩危ラフティングは初心者向けコースから", level: 2 },
      { type: "text", content: "大歩危・小歩危の吉野川はラフティングの国内有数の激流として知られる。初心者向けの半日コース（約3〜4時間）は、小歩危の穏やかな瀬から入り、徐々に大きな波に挑む構成。ガイドの指示に従えば水泳ができなくても参加できる。装備はすべてレンタルできるので、水着と濡れても良いシューズだけ持参すれば十分だ。" },
      { type: "heading", content: "遊覧船で渓谷美を俯瞰する", level: 2 },
      { type: "text", content: "体力に自信がない人や子連れには遊覧船がある。約30分で大歩危峡の核心部を川面から見上げる。2億年かけて形成された結晶片岩の岩壁が迫り、その壮大さは地上から見るより何倍も大きく感じる。春は岸辺の桜、秋は燃えるような紅葉が渓谷を彩る。" },
      { type: "spot-card", content: "oboke-koboke" },
      { type: "heading", content: "ラフティング後は祖谷温泉でゆっくり", level: 2 },
      { type: "text", content: "大歩危から車で30分、祖谷温泉はケーブルカーで下った渓谷底に湧く日本三大秘湯のひとつ。アルカリ性単純泉は肌に優しく、激流で使い果たした体を芯から回復させる。宿泊もできるが、日帰り入浴も受け付けている。露天風呂から眺める祖谷川の流れが最高の景色だ。" },
    ],
    relatedArticleSlugs: ["tokushima-iya-valley-autumn", "tokushima-model-course-2days"],
  },

  // ── 4 ──────────────────────────────────────
  {
    slug: "tokushima-awa-odori-guide",
    title: "阿波踊り完全ガイド──見るだけではもったいない、踊る阿呆の作法",
    description: "「踊る阿呆に見る阿呆、同じ阿呆なら踊らにゃ損損」。徳島の夏はこの哲学で成立している。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokushima",
    tags: ["阿波踊り", "祭り", "夏", "体験", "徳島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "8月11〜15日、徳島市が踊りで沸く", level: 2 },
      { type: "text", content: "阿波踊りは毎年8月11日から15日の4日間、徳島市で開催される日本最大規模の盆踊り。参加者は100万人を超え、桟敷席・演舞場・街角のあちこちで踊りが繰り広げられる。徳島市内の主要4カ所に有料演舞場が設けられ、有名連（れん）の演技を座って鑑賞できる。桟敷席は早い時期に完売するため、公式サイトでの事前予約が必須だ。" },
      { type: "heading", content: "踊る側に回る──「にわか連」の門を叩く", level: 2 },
      { type: "text", content: "観光客でも参加できる「にわか連」が毎日開催される。浴衣と菅笠を借りて、インストラクターに基本の踊りを習い、演舞場前の街を練り歩く。「エライヤッチャ」の掛け声と三味線・鉦・太鼓のリズムに体が自然と動き出す。30分で基本が覚えられ、終わった後には観客に混じれた達成感が残る。" },
      { type: "heading", content: "阿波おどり会館で年中体験できる", level: 2 },
      { type: "text", content: "8月以外に訪れる人のために、阿波おどり会館（眉山ふもと）では毎日プロの踊り子による実演ショーが行われる。館内の体験コーナーでは踊りのレクチャーを受けることも可能。屋上からのロープウェイで眉山山頂に上がると、徳島市街と吉野川の眺望が広がる。" },
    ],
    relatedArticleSlugs: ["tokushima-gourmet-ramen", "tokushima-model-course-2days"],
  },

  // ── 5 ──────────────────────────────────────
  {
    slug: "tokushima-gourmet-ramen",
    title: "徳島ラーメンを制覇する──豚骨醤油の濃厚スープが生卵で化ける瞬間",
    description: "徳島ラーメンは豚骨醤油に生卵が入る全国でも稀なスタイル。地元民が愛する三流派を食べ歩く。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-02-14",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "tokushima",
    tags: ["徳島ラーメン", "グルメ", "豚骨醤油", "ラーメン", "徳島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "徳島ラーメンの三系統を知る", level: 2 },
      { type: "text", content: "徳島ラーメンは大きく三つの系統に分かれる。茶系（濃厚な豚骨醤油）・白系（鶏ガラ系の薄口）・黄系（中華そば風）だ。最もポピュラーな茶系は豚の旨みが凝縮されたスープに豚バラ肉、そして生卵を溶き入れて食べるスタイル。卵黄がスープにとけ込み、濃厚さと丸みが一体になる瞬間が徳島ラーメンの本質だ。" },
      { type: "heading", content: "老舗「いのたに」vs 人気店「麺王」", level: 2 },
      { type: "text", content: "創業50年超の「いのたに」は茶系の原点。煮込んだ豚バラチャーシューがとろけ、スープの余韻が長い。若い世代に人気の「麺王」はやや甘みを強調した現代的な解釈。どちらも一杯800円前後と安く、はしごが現実的だ。鳴門市には独自の「鳴門ラーメン」文化もあり、あっさりした醤油スープが特徴。" },
      { type: "heading", content: "ライス必須、そして二杯が礼儀", level: 2 },
      { type: "text", content: "徳島ラーメンのテーブルには最初からライスが置かれる店が多い。スープとご飯を交互に食べる地元流が正しい食べ方。濃いスープにライスが合いすぎて、気づくと二杯食べてしまう。店を出るときには完食の達成感と、明日もまた来たいという引力が残る。" },
    ],
    relatedArticleSlugs: ["tokushima-gourmet-sudachi", "tokushima-model-course-2days"],
  },

  // ── 6 ──────────────────────────────────────
  {
    slug: "tokushima-gourmet-sudachi",
    title: "すだちが変える食卓──徳島の香酸柑橘を使った料理と土産の選び方",
    description: "徳島はすだちの全国シェア98%を誇る。その使い方は刺身だけではない、奥深いすだち文化を探る。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "tokushima",
    tags: ["すだち", "グルメ", "柑橘", "土産", "徳島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "すだちは9月が旬、このタイミングを逃さない", level: 2 },
      { type: "text", content: "すだちの最盛期は9月上旬から10月上旬。この時期に徳島を訪れると、市場・スーパー・道の駅に山積みのすだちが並ぶ。搾りたての香りは爽烈で、ほんの少し絞るだけで料理の世界が変わる。徳島の人はサンマに、焼き魚に、うどんに、当たり前のようにすだちを絞る。他県では見ない量の消費が文化の深さを証明している。" },
      { type: "heading", content: "すだちを使った郷土料理──そば米汁とすだちそば", level: 2 },
      { type: "text", content: "「そば米汁」は蕎麦の実を米のように炊いたものを野菜と煮た郷土汁で、仕上げにすだちを一絞りする。すっきりとした酸味がコクを引き締める。「すだちそば」は冷たい出汁にすだちを薄切りにして浮かべた清涼感あふれる麺料理で、夏の終わりの一杯として最適。徳島市内の蕎麦店や道の駅で提供している。" },
      { type: "heading", content: "土産はすだち果汁・すだち果皮粉末・すだちぽん酢", level: 2 },
      { type: "text", content: "土産として鮮度が落ちにくいのは絞り汁ボトル・果皮粉末・ぽん酢の三種。絞り汁は冷蔵保存で数ヶ月使える。果皮粉末は塩と合わせると万能調味料になる。地元では当たり前に使うすだちぽん酢は、東京では高級品として扱われるギャップがある。徳島阿波おどり空港の売店よりも、地元スーパーのほうが品揃えが豊かで価格も安い。" },
    ],
    relatedArticleSlugs: ["tokushima-gourmet-ramen", "tokushima-awa-odori-guide"],
  },

  // ── 7 ──────────────────────────────────────
  {
    slug: "tokushima-model-course-2days",
    title: "徳島2泊3日モデルコース──秘境・渦潮・祭り文化を全部回る",
    description: "徳島の魅力は一ヶ所に集中していない。山・海・文化を効率よく巡る3日間のルートを組んだ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-15",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tokushima",
    tags: ["モデルコース", "2泊3日", "徳島", "秘境", "観光"],
    spotIds: ["naruto-whirlpools", "iya-valley", "oboke-koboke"],
    sections: [
      { type: "heading", content: "1日目：鳴門から阿波踊り会館へ", level: 2 },
      { type: "text", content: "徳島阿波おどり空港着後、まず鳴門へ。潮見表を確認して最大潮流の時間に合わせて渦の道・観潮船を体験。午後は徳島市に戻り、阿波おどり会館でプロの演舞を鑑賞。夜は眉山ロープウェイで夜景を楽しんだ後、徳島ラーメンで締める。" },
      { type: "spot-card", content: "naruto-whirlpools" },
      { type: "heading", content: "2日目：大歩危から祖谷渓の秘境へ", level: 2 },
      { type: "text", content: "レンタカーで出発、JR大歩危駅周辺でラフティングまたは遊覧船を体験。昼食は大歩危峡まんなかで地鶏料理。午後から祖谷渓に入り、かずら橋を渡る。夕方は祖谷温泉で疲れを癒す。温泉宿に宿泊し、囲炉裏料理で山の食文化を体験する。" },
      { type: "spot-card", content: "oboke-koboke" },
      { type: "heading", content: "3日目：奥祖谷と帰路", level: 2 },
      { type: "text", content: "朝、奥祖谷二重かずら橋に立ち寄り、観光客のいない静寂の秘境を体感。野猿体験後、ドライブで吉野川沿いを下りながら徳島市へ。帰りの空港でそば米汁とすだちぽん酢を土産に。全工程レンタカー推奨、公共交通だと2日目以降が大幅に制限される。" },
    ],
    relatedArticleSlugs: ["tokushima-iya-valley-autumn", "tokushima-naruto-whirlpools-guide"],
  },

  // ── 8 ──────────────────────────────────────
  {
    slug: "tokushima-solo-henro",
    title: "四国遍路はじめての一歩──徳島県内の1番〜23番札所を歩く",
    description: "「お遍路」は宗教の垣根を越えた旅のスタイル。徳島の発心の道場で、最初の一歩を踏み出す準備。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-03-21",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tokushima",
    tags: ["四国遍路", "お遍路", "一人旅", "歩き", "徳島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "徳島は「発心の道場」──なぜここから始まるか", level: 2 },
      { type: "text", content: "四国八十八箇所の第一番札所・霊山寺（りょうぜんじ）は徳島県鳴門市にある。弘法大師・空海が開いた修行の旅の出発点として、1200年の歴史を持つ。ここで白衣・金剛杖・菅笠を揃えるのが正式な装束。全部で1,200kmを超える遍路道のうち、徳島は第23番まで「発心の道場」として最初の章をなす。" },
      { type: "heading", content: "歩き遍路 vs バス遍路──最初の選択", level: 2 },
      { type: "text", content: "全行程を歩くと約40〜60日かかる。徳島内だけなら7〜10日程度。バス・タクシーによるツアー遍路は10〜14日で四国全体を回れる。初めての人は徳島内の数カ所だけを歩き遍路し、遍路の雰囲気を体感してから全体計画を立てるのが現実的だ。「お接待」と呼ばれる地元民の無償の支援が旅の随所に現れ、遍路の精神的な豊かさを実感できる。" },
      { type: "heading", content: "徳島で遍路に必要な装備を揃える", level: 2 },
      { type: "text", content: "霊山寺の門前には遍路用品を揃えた店が複数ある。白衣（白装束）・菅笠・金剛杖のフルセットで約1万円。スニーカーでも歩けるが、足首を固定できるトレッキングシューズが望ましい。納経帳（御朱印帳）は各寺で朱印を押してもらうもので、一冊2,000円前後。すべて現地で揃えられる。" },
    ],
    relatedArticleSlugs: ["tokushima-model-course-2days", "tokushima-iya-valley-autumn"],
  },

  // ── 9 ──────────────────────────────────────
  {
    slug: "tokushima-couple-iya-stay",
    title: "祖谷の山里に泊まる──かずら橋から徒歩圏の古民家宿で過ごす2日間",
    description: "電波が届かない山奥に、囲炉裏と露天風呂がある。スマホを置いて、二人だけの時間を取り戻す旅。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "tokushima",
    tags: ["カップル", "古民家", "祖谷", "秘境宿", "徳島"],
    spotIds: ["iya-valley"],
    sections: [
      { type: "heading", content: "祖谷の古民家宿を選ぶ理由", level: 2 },
      { type: "text", content: "祖谷渓周辺には江戸・明治時代の古民家を改装した宿が点在する。現代的なホテルとは対極にある静寂と素材感が魅力で、囲炉裏を囲んで地鶏・山菜・川魚を食べる夕食は、旅の記憶の核心になる。宿によっては露天風呂が渓谷に張り出しており、木立の向こうに星空が広がる体験が待っている。" },
      { type: "spot-card", content: "iya-valley" },
      { type: "heading", content: "2日目の朝、かずら橋を誰もいない時間に渡る", level: 2 },
      { type: "text", content: "宿泊者の特権として、観光客が来ない朝7時台に動けることがある。宿から徒歩圏のかずら橋を朝霧の中で渡ると、日中とは全く異なる静寂と神秘感がある。橋の下を流れる祖谷川が朝光を反射する時間は、写真ではなく記憶に刻む時間だ。" },
      { type: "heading", content: "帰りは大歩危の温泉付き食事処で昼食", level: 2 },
      { type: "text", content: "下山途中の大歩危周辺には、渓谷を見下ろしながら昼食をとれる食事処がある。阿波地鶏の焼き鳥定食と祖谷そばが定番。帰りの時間に余裕があれば、大歩危駅前の資料館で吉野川の地質と歴史を30分学ぶと、渓谷の見え方が変わる。" },
    ],
    relatedArticleSlugs: ["tokushima-iya-valley-autumn", "tokushima-oboke-rafting"],
  },

  // ── 10 ──────────────────────────────────────
  {
    slug: "tokushima-family-naruto",
    title: "鳴門で子どもが夢中になる半日──渦潮・大塚国際美術館のW体験",
    description: "鳴門の渦潮と世界の名画が原寸大で並ぶ大塚国際美術館。大人も子どもも満足する鳴門の1日。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-30",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "tokushima",
    tags: ["子連れ", "鳴門", "大塚国際美術館", "家族旅", "徳島"],
    spotIds: ["naruto-whirlpools"],
    sections: [
      { type: "heading", content: "午前は渦潮、午後は大塚国際美術館", level: 2 },
      { type: "text", content: "鳴門の2大観光スポットは徒歩圏内にある。大潮の日は午前に観潮船で渦潮を体感し、昼食後に大塚国際美術館へ向かうスケジュールが理想的。大塚国際美術館は世界の名画を陶板で原寸大再現した施設で、1,000点以上が展示される。滞在時間は最低でも3時間必要で、1日では回りきれない規模だ。" },
      { type: "spot-card", content: "naruto-whirlpools" },
      { type: "heading", content: "子どもが食いつくコーナーが充実", level: 2 },
      { type: "text", content: "大塚国際美術館には原画と見比べる体験コーナーや、名画の中で写真を撮れるフォトスポットが豊富。ダ・ヴィンチの「最後の晩餐」は修復前後の比較が見られる。子ども向けのスタンプラリーもあり、館内探検ゲーム感覚で絵画に触れられる。カフェはシスティーナ礼拝堂の天井画の下でランチができる非日常空間。" },
      { type: "heading", content: "鳴門金時ソフトクリームで締める", level: 2 },
      { type: "text", content: "鳴門の定番スイーツは鳴門金時を使ったソフトクリーム。美術館出口近くの売店や鳴門公園内の売店で購入できる。甘みとほくほく感が子どもに大人気で、大人は鳴門金時の焼き芋スイーツと食べ比べするのが楽しい。帰りのフェリーで淡路島経由を選ぶと、さらに玉ねぎスープの特典が待っている。" },
    ],
    relatedArticleSlugs: ["tokushima-naruto-whirlpools-guide", "tokushima-model-course-2days"],
  },

  // ── 11 ──────────────────────────────────────
  {
    slug: "tokushima-budget-backpack",
    title: "徳島を安く旅する──ヒッチハイク禁止！でも1日3,000円で回れる交通術",
    description: "徳島は移動費がかさむと思われがちだが、組み合わせ次第で格安旅が成立する。節約プランを公開。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "tokushima",
    tags: ["節約旅", "バジェット", "交通", "徳島", "一人旅"],
    spotIds: [],
    sections: [
      { type: "heading", content: "高速バス＋自転車が最強の組み合わせ", level: 2 },
      { type: "text", content: "東京・大阪からの高速バスは夜行を使えば宿泊費を節約できる。徳島市内はレンタサイクル（1日1,000円前後）で十分回れる。鳴門へは徳島駅から高速バス（片道520円）が頻発しており、渦潮まで追加のタクシーは不要。阿波踊り会館周辺の無料・格安駐車場も整備されているので、レンタカーを使う日とバスの日を分けるのが賢い選択だ。" },
      { type: "heading", content: "道の駅と公共施設を活用する", level: 2 },
      { type: "text", content: "吉野川沿いの道の駅「にしいや」では地元野菜・川魚の弁当が500円以下で揃う。祖谷渓周辺の道の駅も地鶏の惣菜が格安。観光施設の入場料は、阿波おどり会館の常設展示（無料）・渦の道（510円）・かずら橋（550円）と、全部回っても2,000円以下に収まる。お遍路割引を使えば一部施設が安くなるため、遍路用品を買っておくと結果的に元がとれることもある。" },
      { type: "heading", content: "夜は屋台横丁「新町橋」で500円グルメ", level: 2 },
      { type: "text", content: "徳島市の新町橋周辺には夜に屋台が並び、徳島ラーメン・焼き鳥・天ぷらが500〜700円で食べられる。テーブルを他の旅行者と共有する雰囲気が一人旅の孤独を消してくれる。地元民が多く、地元情報を交換できる場所でもある。翌朝のモーニングは駅前の喫茶店で380円のトースト＋コーヒーが定番。" },
    ],
    relatedArticleSlugs: ["tokushima-model-course-2days", "tokushima-solo-henro"],
  },

  // ── 12 ──────────────────────────────────────
  {
    slug: "tokushima-luxury-iya-ryokan",
    title: "祖谷渓の贅沢宿──渓谷に張り出した露天風呂と囲炉裏料理の一夜",
    description: "日本の秘境に、世界水準の宿がある。祖谷渓で体験できる、非日常の最上級を探した。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "tokushima",
    tags: ["贅沢旅", "高級旅館", "祖谷渓", "露天風呂", "徳島"],
    spotIds: ["iya-valley"],
    sections: [
      { type: "heading", content: "渓谷に浮かぶ宿を選ぶ基準", level: 2 },
      { type: "text", content: "祖谷渓の高級宿の選択肢は少ないが密度が高い。渓谷に張り出した露天風呂付き客室と、囲炉裏を囲んで地元食材だけで構成された懐石夕食が評価の基準になる。客室数が少ない宿ほど対応が丁寧で、予約競争が激しい。3〜6ヶ月前の予約が安全だ。週末は1部屋4〜6万円が相場だが、一生に一度の体験として正当化できる価格だと感じる旅人が多い。" },
      { type: "spot-card", content: "iya-valley" },
      { type: "heading", content: "夕食：阿波牛・阿波地鶏・山菜の囲炉裏料理", level: 2 },
      { type: "text", content: "囲炉裏料理のコースは阿波牛の炭火焼き・阿波地鶏の炙り・祖谷豆腐・山菜の天ぷらが中心。阿波牛は黒毛和牛のブランド牛で、神戸牛・松阪牛と並ぶ品質を誇る。囲炉裏の煙が食材に移る香ばしさは、都市のレストランでは再現できない。食後は宿の湯治場で山の温泉につかり、静寂の中で眠りにつく。" },
      { type: "heading", content: "翌朝の朝食と出発", level: 2 },
      { type: "text", content: "朝食は地元の豆腐・味噌・漬物・鮎の干物で構成された和朝食。食後は宿のチェックアウト前に、宿から送迎してもらえるかずら橋を独占する早朝体験ができる宿もある。帰路は吉野川沿いをドライブしながら、日常との境界をゆっくり越えていく。" },
    ],
    relatedArticleSlugs: ["tokushima-couple-iya-stay", "tokushima-iya-valley-autumn"],
  },

  // ── 13 ──────────────────────────────────────
  {
    slug: "tokushima-oboke-viewpoint",
    title: "大歩危峡の絶景展望スポット5選──撮影クルーが選ぶベストアングル",
    description: "渓谷美は角度で変わる。撮影ロケで大歩危を何度も歩いたカメラマンが教える、本当に美しい5つのポイント。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokushima",
    tags: ["大歩危", "絶景", "撮影", "写真映え", "徳島"],
    spotIds: ["oboke-koboke"],
    sections: [
      { type: "heading", content: "国道32号沿いの駐車帯──水面と岩壁が重なる基本構図", level: 2 },
      { type: "text", content: "大歩危駅から国道32号を南下すると、吉野川が眼下に現れる駐車帯がいくつかある。早朝は川霧が谷間を埋め、日が当たり始めると色が動く。標準ズームで水面・岩壁・空の3層を収める構図が安定して美しい。車を停めて5分立っているだけで絵になる写真が撮れる場所だ。" },
      { type: "spot-card", content: "oboke-koboke" },
      { type: "heading", content: "遊覧船の船上から見上げる「岩の圧壁」", level: 2 },
      { type: "text", content: "遊覧船は渓谷を水面から体験できる唯一の手段。船上から見上げる結晶片岩の岩壁は高さ100m超で、陸上から見るより圧倒的に大きく感じる。光の方向は朝が逆光ぎみになるため、午前10時〜14時が岩壁に光が当たる順光タイム。船の揺れに対応できる広角レンズが有利。" },
      { type: "heading", content: "秋の紅葉期は別の渓谷になる", level: 2 },
      { type: "text", content: "11月上中旬の大歩危は紅葉が青い川面を縁取り、まるで色鉛筆で描いたような景色になる。特に曇りの日は色彩のコントラストが高く、写真映えする。観光客のピークは週末のため、平日に来ると渓谷をほぼ独占できる贅沢さがある。" },
    ],
    relatedArticleSlugs: ["tokushima-oboke-rafting", "tokushima-iya-valley-autumn"],
  },

  // ── 14 ──────────────────────────────────────
  {
    slug: "tokushima-awa-dance-history",
    title: "阿波踊り400年の歴史──なぜこの踊りだけが生き続けるのか",
    description: "江戸時代から続く阿波踊りは、単なる観光イベントではない。この踊りに宿る文化の強度を読み解く。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-08-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokushima",
    tags: ["阿波踊り", "歴史", "文化", "郷土芸能", "徳島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "起源は1587年、藩主の城祝いから", level: 2 },
      { type: "text", content: "阿波踊りの起源は諸説あるが、1587年に蜂須賀家政が徳島城を築いた際、民衆が踊り狂ったのが始まりとする説が有力だ。盆踊りの形式をとりながら、他の地方の盆踊りとは全く異なる洗練度と体系化がある。「連（れん）」と呼ばれる踊りの集団は年間を通じて練習し、大会形式で技術を競う文化が400年にわたって踊りの質を高め続けてきた。" },
      { type: "heading", content: "「阿呆」の哲学──踊ることの正当性", level: 2 },
      { type: "text", content: "「踊る阿呆に見る阿呆、同じ阿呆なら踊らにゃ損損」という囃子は、参加の哲学を一言で言い切っている。見ているだけでは人生の半分しか生きていないという意味が込められており、この価値観が400年間、祭りへの参加者を生み出し続けてきた。現代においても、初めて踊りに参加した旅行者が翌年も徳島を訪れる理由として最も多く挙げるのが「あの解放感をもう一度」だ。" },
      { type: "heading", content: "有名連を知ることで踊りの深みが増す", level: 2 },
      { type: "text", content: "阿波踊りには「娯茶平（ごちゃぺい）」「葉月連（はづきれん）」など有名連が多数存在し、それぞれ独自のスタイルと歴史を持つ。演舞場では「どの連が出るか」を確認してから席を選ぶのがマニアの流儀。有名連のチケットが早期完売する理由は、プロスポーツと同じレベルの技術と緊張感がそこにあるからだ。" },
    ],
    relatedArticleSlugs: ["tokushima-awa-odori-guide", "tokushima-model-course-2days"],
  },

  // ── 15 ──────────────────────────────────────
  {
    slug: "tokushima-access-guide",
    title: "徳島へのアクセス完全ガイド──飛行機・バス・電車、最安ルートを比較する",
    description: "徳島は意外とアクセスの選択肢が多い。大阪・東京からの各交通手段を時間・費用・快適さで比較した。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokushima",
    tags: ["アクセス", "交通", "飛行機", "高速バス", "徳島"],
    spotIds: [],
    sections: [
      { type: "heading", content: "大阪からは高速バスが最強", level: 2 },
      { type: "text", content: "大阪（梅田・なんば）から徳島までの高速バスは1日30便以上あり、所要約2時間30分・片道1,800〜2,500円。明石海峡大橋・淡路島を経由するルートで、車窓から橋の景観が楽しめる。マイカーでは神戸淡路鳴門自動車道経由で約2時間（高速料金片道約4,000円）。新幹線は使えず、在来線特急は岡山経由で3時間30分超かかるため、バスが圧倒的に優位だ。" },
      { type: "heading", content: "東京からは飛行機一択", level: 2 },
      { type: "text", content: "東京（羽田）から徳島阿波おどり空港まで約1時間10分。ANAが1日3〜4便運航しており、早割を使えば8,000〜15,000円で購入できる。空港から徳島市街中心部までリムジンバスで25分。新幹線は岡山乗り換えで約4時間かかるため、時間コストを考えると飛行機の圧勝。夜行バスは東京から10時間以上かかるが、節約派には選択肢になる。" },
      { type: "heading", content: "四国内の移動はレンタカーが現実的", level: 2 },
      { type: "text", content: "徳島市内は電車・バスで動けるが、祖谷渓・大歩危小歩危・室戸岬などの主要観光地は公共交通が極めて不便。レンタカーは徳島阿波おどり空港で各社揃っており、24時間6,000〜9,000円程度。JAF会員・各種クレジットカード優待を組み合わせると10〜20%割引になる。徳島市内の宿は駐車場付きが多く、駐車コストの心配が少ない。" },
    ],
    relatedArticleSlugs: ["tokushima-model-course-2days", "tokushima-budget-backpack"],
  },
];
