import { Article } from "@/types/article";

export const tokyoArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "tokyo-asakusa-morning-walk",
    title: "浅草寺、早朝6時の歩き方──仲見世が開く前の江戸時間に入る",
    description: "観光客が来る前の浅草には、東京で最も古い朝の空気が残っている。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tokyo",
    tags: ["浅草", "早朝", "寺院", "食べ歩き", "定番"],
    spotIds: ["senso-ji"],
    sections: [
      { type: "heading", content: "6時の雷門はほぼ無人", level: 2 },
      { type: "text", content: "浅草寺は朝6時に開門する。この時間、雷門をくぐっても仲見世の屋台はまだシャッターを下ろしており、提灯の赤だけが薄明かりに浮かぶ。参拝を静かに済ませるなら、今の東京でこれ以上の場所はない。" },
      { type: "heading", content: "二天門から入る隠しルート", level: 2 },
      { type: "text", content: "雷門が混んでいる時間帯は、東側の二天門から境内に入るルートが正解だ。仁王像を横目に本堂まで直行でき、香炉の煙を浴びてから御朱印所に向かうと、待ち時間なしで受け取れる。" },
      { type: "heading", content: "8時以降の食べ歩きへ", level: 2 },
      { type: "text", content: "仲見世が開き始める8時以降は人形焼きと揚げまんじゅうが揚げたてになる。「木村家本店」の人形焼きは小豆の甘さが控えめで、朝の口に合う。ここまでで半日分の密度がある。" },
    ],
    relatedArticleSlugs: ["tokyo-ueno-museum-rainy-day", "tokyo-tsukiji-breakfast"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "tokyo-meiji-jingu-forest-walk",
    title: "明治神宮の森──原宿駅から徒歩1分で東京の騒音が消える",
    description: "70万平方メートルの人工林が作り出す静寂は、東京のどのカフェよりも深い。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-02-14",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tokyo",
    tags: ["明治神宮", "神社", "森", "早朝", "パワースポット"],
    spotIds: ["meiji-jingu"],
    sections: [
      { type: "heading", content: "参道の砂利音だけが聞こえる朝", level: 2 },
      { type: "text", content: "原宿駅の改札を出て5分歩くと、都市の音が消える。365種10万本の木が植えられた参道は、人工林とは思えないほど深い。早朝7時前に来ると、ほぼ地元の参拝者だけで静かに歩ける。" },
      { type: "heading", content: "奉納の酒樽とワイン樽を見逃すな", level: 2 },
      { type: "text", content: "参道の両側に並ぶ酒樽とワイン樽は、明治天皇が洋文化を取り入れた象徴として奉納されたものだ。和と洋が並立する光景は明治の精神を視覚化している。" },
      { type: "heading", content: "参拝後は代々木公園を経由して渋谷へ", level: 2 },
      { type: "text", content: "本殿を参拝した後、南参道から出ると代々木公園に直結する。週末の代々木公園はフリーマーケットや路上演奏が賑やかで、明治神宮との対比が東京らしい。渋谷駅まで徒歩15分。" },
    ],
    relatedArticleSlugs: ["tokyo-shinjuku-gyoen-seasons", "tokyo-harajuku-takeshita-street"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "tokyo-tower-night-view",
    title: "東京タワー夜景完全ガイド──増上寺構図と夜のメインデッキ",
    description: "333mの赤い鉄塔を最も美しく見る方法は、上から見下ろすことではなく、下から見上げることだ。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "tokyo",
    tags: ["東京タワー", "夜景", "カップル", "写真映え", "港区"],
    spotIds: ["tokyo-tower"],
    sections: [
      { type: "heading", content: "増上寺正門からの定番構図", level: 2 },
      { type: "text", content: "増上寺の正門前に立つと、朱色の三解脱門と東京タワーが同じフレームに収まる。日没後30分のマジックアワーに来ると、空の紺とタワーのオレンジが混ざった特別な色彩になる。三脚は必要ない明るさ。" },
      { type: "heading", content: "メインデッキ（150m）は夜が正解", level: 2 },
      { type: "text", content: "昼間のメインデッキから見える風景は平坦だが、夜は光の点が無数に広がり東京の密度を体感できる。西側窓からは富士山のシルエットが見えることがある。チケット¥1,200は混雑を避けて平日夜に。" },
      { type: "heading", content: "タワーの真下から見上げる", level: 2 },
      { type: "text", content: "意外と知られていないのが、タワーの真下から見上げた時の鉄骨の迫力だ。4本の脚が交差する地点に立つと、3万3千トンの鉄骨構造が頭上に広がる。入場不要、無料でアクセスできる。" },
    ],
    relatedArticleSlugs: ["tokyo-roppongi-art-night", "tokyo-shibuya-scramble-guide"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "tokyo-shibuya-scramble-guide",
    title: "渋谷スクランブル交差点──渡る側より「見る側」に回った方が面白い",
    description: "1回の青信号で3,000人が交差する光景を、本当に体験するには2階から見下ろすべきだ。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-04-18",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokyo",
    tags: ["渋谷", "スクランブル交差点", "定番", "夜", "観光"],
    spotIds: ["shibuya-scramble"],
    sections: [
      { type: "heading", content: "スターバックス2階が最良の観察地点", level: 2 },
      { type: "text", content: "QFRONT内のスターバックス渋谷スクランブル交差点店の2階窓際席は、交差点全体を俯瞰できる東京随一のビューポイントだ。金曜夜19〜21時は最も密度が高く、コーヒー1杯で世界最多の横断歩道を堪能できる。" },
      { type: "heading", content: "夜のビジョンと光の洪水", level: 2 },
      { type: "text", content: "日没後の交差点は、QFRONTの大型LEDビジョンと周囲のネオンが光の競演を作る。雨の日は路面に光が反射してさらに美しい。傘を持って雨の渋谷を歩く価値は十分ある。" },
      { type: "heading", content: "渋谷ストリームで新旧対比", level: 2 },
      { type: "text", content: "交差点から渋谷川沿いを西に5分歩くと渋谷ストリームがある。かつてのドブ川が都市型リバーサイドに変わった光景は、東京の再開発の象徴だ。夜はライトアップされた水面が綺麗。" },
    ],
    relatedArticleSlugs: ["tokyo-tower-night-view", "tokyo-harajuku-takeshita-street"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "tokyo-tsukiji-breakfast",
    title: "築地場外市場、朝6時の食べ歩き全ガイド──マグロ・玉子焼き・海鮮丼の順番",
    description: "プロの料理人が仕入れる時間帯に築地に来ると、観光地とは別の顔が見える。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-05-07",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "tokyo",
    tags: ["築地", "市場", "朝活", "海鮮", "グルメ"],
    spotIds: ["tsukiji-outer-market"],
    sections: [
      { type: "heading", content: "6時〜7時はプロの仕入れ時間", level: 2 },
      { type: "text", content: "築地場外市場は朝5時台から開く鮮魚店があり、6〜7時は飲食店のシェフや料理人が仕入れに来るピーク時間だ。この時間帯に来ると、100gあたりの値段交渉が飛び交う活気に紛れ込める。" },
      { type: "heading", content: "松露の玉子焼きは8時に揚がる", level: 2 },
      { type: "text", content: "玉子焼き専門店「松露」の焼き立て出汁巻き玉子は、通常の卵焼きとは別物の食感だ。8時台に焼き上がるタイミングを狙うと、熱々をその場で食べられる。1本¥350で惜しくない値段。" },
      { type: "heading", content: "海鮮丼は月・水を外して選ぶ", level: 2 },
      { type: "text", content: "月曜と水曜は定休店が多い。「大和寿司」や「鮨大」は行列必至だが、9時前に並べば1時間以内で入れる。マグロの赤身とウニのハーフ丼は¥2,800前後が相場。" },
    ],
    relatedArticleSlugs: ["tokyo-asakusa-morning-walk", "tokyo-ueno-museum-rainy-day"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "tokyo-ueno-museum-rainy-day",
    title: "雨の日の上野──東京国立博物館と不忍池のハスで半日過ごす方法",
    description: "雨が降ったら上野に行け。東京随一の文化密集地は、天気が悪い日ほど価値が出る。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokyo",
    tags: ["上野", "美術館", "雨の日", "博物館", "家族"],
    spotIds: ["ueno-park"],
    sections: [
      { type: "heading", content: "東京国立博物館の常設展で半日", level: 2 },
      { type: "text", content: "東京国立博物館の常設展は所蔵品12万点のうち約3,000点が常時展示されている。入館料¥1,000で縄文時代から江戸時代まで通史で見られる美術史の教科書だ。企画展より常設展を先に制覇するべき。" },
      { type: "heading", content: "上野動物園のパンダは予約制に注意", level: 2 },
      { type: "text", content: "上野動物園のジャイアントパンダ観覧は2024年以降も日時指定の事前予約が必要な場合がある。公式サイトで確認の上、朝イチの枠を取ると待機列なしで間近に見られる。入園料¥600。" },
      { type: "heading", content: "不忍池のハスは7〜8月の早朝が別格", level: 2 },
      { type: "text", content: "7〜8月の早朝、不忍池は水面全体をハスの葉と花が覆い尽くす。朝6時台に来ると光が低く入り込み、ハスの葉に溜まった水玉が光を反射する瞬間が見られる。写真を撮るなら必ずこの時間帯。" },
    ],
    relatedArticleSlugs: ["tokyo-asakusa-morning-walk", "tokyo-akihabara-subculture"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "tokyo-shinjuku-gyoen-seasons",
    title: "新宿御苑の四季──桜1,100本・菊花壇・温室、一度で3つの庭園を歩く",
    description: "新宿駅から歩いて10分、58ヘクタールの中に日本・フランス・イギリスの庭が同居している。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-03-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokyo",
    tags: ["新宿御苑", "庭園", "桜", "秋", "散歩"],
    spotIds: ["shinjuku-gyoen"],
    sections: [
      { type: "heading", content: "桜シーズンは上野より空いている", level: 2 },
      { type: "text", content: "新宿御苑の桜は1,100本以上で、開花時期が異なる品種が植えられているため3月下旬から4月中旬まで長く楽しめる。上野公園ほど混まず、芝生でゆっくり花見ができる。入園料¥500。" },
      { type: "heading", content: "11月の菊花壇展は無料で観覧", level: 2 },
      { type: "text", content: "11月下旬〜12月上旬に行われる菊花壇展は日本最高水準の品評会で、精巧に仕立てられた懸崖菊や大菊が庭園に並ぶ。入園料だけで観覧でき、東京の秋を締める行事として価値が高い。" },
      { type: "heading", content: "温室は雨の日のリカバリーに最適", level: 2 },
      { type: "text", content: "新宿御苑の温室には熱帯・亜熱帯植物が集められており、外が雨でも完全に楽しめる。高さ20m超のフタバガキとバナナの群落は、都心にいることを忘れさせる。" },
    ],
    relatedArticleSlugs: ["tokyo-meiji-jingu-forest-walk", "tokyo-imperial-palace-run"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "tokyo-roppongi-art-night",
    title: "六本木アート・ナイト──森美術館と東京シティビューで夜の現代アートを体験",
    description: "52階の森美術館と夜景を同一チケットで楽しめる六本木は、東京の夜に最も密度がある場所だ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "tokyo",
    tags: ["六本木", "アート", "夜景", "ラグジュアリー", "現代美術"],
    spotIds: ["roppongi-hills"],
    sections: [
      { type: "heading", content: "森美術館は企画展のレベルが世界水準", level: 2 },
      { type: "text", content: "森美術館（52F）はテート・モダンやMoMAと同等のラインナップで企画展を開催する。入場¥2,000は東京の美術館で最高クラスだが、展示替えのたびに新しい体験ができる。火曜休館に注意。" },
      { type: "heading", content: "東京シティビューでタワーを同時に見る", level: 2 },
      { type: "text", content: "52階の東京シティビューは森美術館のチケットで入れる。ここから東京タワーとスカイツリーが同フレームで収まる写真が撮れる。夕方17時頃から入ると、夕景と夜景の両方を1回の入場で見られる。" },
      { type: "heading", content: "毛利庭園のリフレクション", level: 2 },
      { type: "text", content: "ヒルズのアリーナ横にある毛利庭園の池には、森タワーが逆さに映る。夜のライトアップ時間帯に来ると水面の反射が完璧な対称を作る。入場無料で、最も写真映えするポイントのひとつだ。" },
    ],
    relatedArticleSlugs: ["tokyo-tower-night-view", "tokyo-ginza-luxury-guide"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "tokyo-akihabara-subculture",
    title: "秋葉原サブカル完全案内──電気街・アニメ・メイドカフェを全部回る半日ルート",
    description: "世界で最も密度の高いオタク文化の街を初めて歩く人のための地図。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tokyo",
    tags: ["秋葉原", "アニメ", "サブカル", "買い物", "電気街"],
    spotIds: ["akihabara"],
    sections: [
      { type: "heading", content: "ラジオ会館は8フロアで半日消える", level: 2 },
      { type: "text", content: "秋葉原ラジオ会館は1〜8階がフィギュア・トレカ・コスプレ・同人誌の専門店で構成されている。フロアごとにジャンルが違い、マニア密度が高い。エレベーターで最上階から降りながら見るのが効率的。" },
      { type: "heading", content: "中古ゲーム・ソフトは掘り出し物が出る", level: 2 },
      { type: "text", content: "スーパーポテトやレトロゲーム専門店が中央通り沿いに集中している。ファミコンカセットから初代プレステまで、現役で動く中古ソフトが¥100〜¥1,000で並ぶ。宝探し感覚で棚をあさる楽しさ。" },
      { type: "heading", content: "メイドカフェ体験は最初の1時間が全て", level: 2 },
      { type: "text", content: "メイドカフェは「@ほぉ〜むcafe」が老舗で初心者向け。ドリンクと「おかえりなさいませ♡」の接客で¥1,500〜¥2,000が相場。延長すると料金が加算されるので最初から時間を決めて入るのが正解。" },
    ],
    relatedArticleSlugs: ["tokyo-ueno-museum-rainy-day", "tokyo-budget-eats-kanda"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "tokyo-imperial-palace-run",
    title: "皇居外周ラン──2.14kmのコースと東御苑の江戸城跡を同じ朝に歩く",
    description: "東京の中心に立ち入れない場所がある。その外側と内側の両方を、一度の朝で体験する方法。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-09-22",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tokyo",
    tags: ["皇居", "ランニング", "歴史", "無料", "散歩"],
    spotIds: ["imperial-palace"],
    sections: [
      { type: "heading", content: "外周2.14kmは世界で最も有名な皇居ラン", level: 2 },
      { type: "text", content: "皇居外周のランニングコースは週末早朝に何百人もの市民が走る東京名物だ。大手門から時計回りに1周2.14km。「ランステ」（ランニングステーション）が近隣に複数あり、手ぶらで来ても着替えとロッカーが使える。" },
      { type: "heading", content: "東御苑で江戸城天守台を見る", level: 2 },
      { type: "text", content: "東御苑は火・木・金・土・日の9時〜16時30分に無料開放されている。本丸跡の広大な芝生に江戸城天守台の石積みが残り、かつての天守閣の大きさを想像させる。東京で最も静かな庭園空間。" },
      { type: "heading", content: "桜田門内側から皇居を見る", level: 2 },
      { type: "text", content: "桜田門は江戸時代に大老・井伊直弼が暗殺された場所だ。内側から皇居の白い石垣と松の緑を見ると、権力の継続性を感じる。外国人旅行者に最も人気のある撮影スポットでもある。" },
    ],
    relatedArticleSlugs: ["tokyo-shinjuku-gyoen-seasons", "tokyo-meiji-jingu-forest-walk"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "tokyo-cherry-blossom-ueno",
    title: "上野の桜800本──花見の名所を早朝から夜まで使い倒す完全ガイド",
    description: "日本一の花見スポットで、本当に桜を堪能するには何時に来てどこに陣取るかがすべてだ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-03-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokyo",
    tags: ["上野", "桜", "花見", "春", "定番"],
    spotIds: ["ueno-park"],
    sections: [
      { type: "heading", content: "早朝7時前はブルーシートが並ぶ前", level: 2 },
      { type: "text", content: "上野の花見シーズンは朝7時以前が別世界だ。ブルーシートを張る前の桜並木を静かに歩ける唯一の時間帯。屋台も準備中で、公園が本来の公園として機能している。" },
      { type: "heading", content: "不忍池越しの桜は写真的に最強", level: 2 },
      { type: "text", content: "不忍池の東岸から池越しに見る桜並木は、水面に反射した花の色が広がって上野随一の絶景になる。弁天堂の朱と桜のピンクが重なるアングルは、午前中の順光で撮ると色が鮮やかに出る。" },
      { type: "heading", content: "夜桜は18〜19時のライトアップが最良", level: 2 },
      { type: "text", content: "日没後のライトアップは18時から始まる。屋台のオレンジ色の灯りと桜の白が混ざる18〜19時が最も柔らかい光の時間帯。21時以降は急激に人が減り、夜桜を独占できる。" },
    ],
    relatedArticleSlugs: ["tokyo-shinjuku-gyoen-seasons", "tokyo-asakusa-morning-walk"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "tokyo-ginza-luxury-guide",
    title: "銀座ラグジュアリーガイド──寿司・鉄板焼き・バーを1日で堪能する最高の使い方",
    description: "銀座は高い。でも正しいお金の使い方を知ると、東京で最も密度の高い1日になる。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "tokyo",
    tags: ["銀座", "高級", "寿司", "グルメ", "夜"],
    spotIds: [],
    sections: [
      { type: "heading", content: "ランチ寿司が夜の3分の1の価格", level: 2 },
      { type: "text", content: "銀座の高級寿司店はランチコースを¥8,000〜¥15,000で提供している。同じカウンターで夜は¥30,000を超える店でも、ランチなら現実的な価格で職人の技を体験できる。久兵衛・鮨さいとうのランチは予約が取りやすい枠がある。" },
      { type: "heading", content: "銀座シックス最上階のテラスは無料", level: 2 },
      { type: "text", content: "GINZA SIXの6階テラスガーデンと屋上は無料で開放されている。周囲の銀座の街並みが見渡せる場所で、ショッピングの前後に立ち寄るだけで気分が変わる。夕方は西日が建物に当たって美しい。" },
      { type: "heading", content: "バー巡りは資生堂パーラーとポールスターで", level: 2 },
      { type: "text", content: "夜の銀座はバーの密度が日本最高だ。資生堂パーラーの銀座バーは1902年創業、カクテル¥1,800〜。その後、並木通りのスタンディングバーを梯子すると銀座の夜の深さが分かってくる。" },
    ],
    relatedArticleSlugs: ["tokyo-roppongi-art-night", "tokyo-tsukiji-breakfast"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "tokyo-family-summerland",
    title: "東京の家族旅行完全プラン──上野動物園・浅草・お台場を2日で回る最短ルート",
    description: "子どもと来る東京は効率が命。移動を最小限にして、子どもの体力をコンテンツに使い切る計画。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-07-31",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "tokyo",
    tags: ["家族", "子ども", "上野動物園", "浅草", "お台場"],
    spotIds: ["ueno-park", "senso-ji"],
    sections: [
      { type: "heading", content: "1日目：上野→浅草の北東ルート", level: 2 },
      { type: "text", content: "上野駅着9時。動物園でパンダを見た後、徒歩で下谷神社を経由して浅草へ向かう。昼は浅草の牛かつ専門店「牛かつもと村」でサクッと食べ、午後は仲見世でお土産を買う。子どもは人形焼きを自分で選ぶのを楽しむ。" },
      { type: "heading", content: "2日目：お台場でデジタルと海を体験", level: 2 },
      { type: "text", content: "チームラボボーダレス（有明）は事前オンライン予約必須。¥3,200（子ども¥1,000）で2〜3時間没入できるデジタルアート施設だ。その後、お台場海浜公園の砂浜で自由時間を設けると子どもの電池が切れる。" },
      { type: "heading", content: "宿は上野・浅草エリアが最もコスパ高い", level: 2 },
      { type: "text", content: "ファミリー向け宿泊なら浅草ビューホテルが連泊でリーズナブル。浅草寺まで徒歩5分の立地で大人¥15,000/泊前後。朝食ブッフェ付きプランにすると子どものコンディション管理がしやすい。" },
    ],
    relatedArticleSlugs: ["tokyo-asakusa-morning-walk", "tokyo-ueno-museum-rainy-day"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "tokyo-budget-eats-kanda",
    title: "神田・御茶ノ水の格安グルメ──ランチ¥800以下で食べる本物のカレーとそば",
    description: "東京で安くて美味しいものを食べたいなら、観光地を外れて神田に来るべきだ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "tokyo",
    tags: ["神田", "格安", "カレー", "そば", "ランチ"],
    spotIds: [],
    sections: [
      { type: "heading", content: "神田カレー街は100店舗超が集中", level: 2 },
      { type: "text", content: "神田駅周辺はカレー店の密集度が日本最高で、1kmの徒歩圏内に100店以上がある。欧風カレーの老舗「ボンディ」のランチセット¥1,300、インドカレーなら「エリックサウス」のラッサム¥1,200が食べておくべき2店。" },
      { type: "heading", content: "御茶ノ水のそば屋で¥600ランチ", level: 2 },
      { type: "text", content: "御茶ノ水駅周辺の立ち食いそば「小諸そば」はかき揚げそば¥520で、東京最安級のランチが食べられる。ただし「神田まつや」（創業1884年）の手打ちもり¥850は格安ではないが、それだけの価値がある。" },
      { type: "heading", content: "秋葉原の中華ランチも500円台", level: 2 },
      { type: "text", content: "秋葉原の裏路地にある中華食堂はランチタイムに日替わり定食¥500〜¥700を提供している。ガパオライスやチャーハン定食が量・質ともに観光地価格より圧倒的に良い。サラリーマンが行く店を選べばまず外れない。" },
    ],
    relatedArticleSlugs: ["tokyo-akihabara-subculture", "tokyo-shibuya-scramble-guide"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "tokyo-harajuku-takeshita-street",
    title: "原宿・竹下通りの正しい歩き方──クレープとコスプレショップで若者文化を体験",
    description: "竹下通りはカオスだ。でもそのカオスを楽しむには順番がある。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokyo",
    tags: ["原宿", "竹下通り", "クレープ", "ファッション", "若者文化"],
    spotIds: [],
    sections: [
      { type: "heading", content: "開店直後の10時台が唯一空いている", level: 2 },
      { type: "text", content: "竹下通りは全長350mだが、週末の昼以降は肩が触れ合う密度になる。唯一空いているのは店が開き始める10〜11時台。クレープ店が暖機運転中でも並ばずに買えるのはこの時間帯だけだ。" },
      { type: "heading", content: "マリオンクレープのクリームチーズはやはり正解", level: 2 },
      { type: "text", content: "竹下通りのクレープは「マリオンクレープ」と「カフェクレープ」の2強だ。マリオンのクリームチーズ&ストロベリー（¥750）は1980年代から変わっていないレシピで、原宿の歴史を食べる体験。" },
      { type: "heading", content: "表参道へ抜けると価格帯が急変する", level: 2 },
      { type: "text", content: "竹下通りを抜けて表参道に出ると、同じ原宿エリアとは思えないほど客層と価格帯が変わる。アニエスベー・コムデギャルソン・バレンシアガが並ぶ表参道ヒルズで1時間過ごすと、東京のファッション格差がリアルに見える。" },
    ],
    relatedArticleSlugs: ["tokyo-meiji-jingu-forest-walk", "tokyo-shibuya-scramble-guide"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "tokyo-autumn-foliage-shinjuku",
    title: "東京の紅葉2025──新宿御苑・昭和記念公園・六義園の見頃と混雑を徹底比較",
    description: "東京の紅葉は11月下旬から12月上旬。どこに行くかより、何時に行くかが全てを決める。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokyo",
    tags: ["紅葉", "秋", "新宿御苑", "昭和記念公園", "六義園"],
    spotIds: ["shinjuku-gyoen"],
    sections: [
      { type: "heading", content: "新宿御苑のメタセコイアは11月下旬", level: 2 },
      { type: "text", content: "新宿御苑では11月下旬のメタセコイアの紅葉が最も美しい。高さ20mを超えるオレンジ色の巨木が並ぶ列は、フランス式庭園の広場と組み合わさって異国的な光景を作る。開園直後の9時に入ると光が低く横から入る。" },
      { type: "heading", content: "昭和記念公園のいちょうは東京最大規模", level: 2 },
      { type: "text", content: "立川市の昭和記念公園は「かたらいのイチョウ並木」の黄葉が11月中旬〜下旬に見頃を迎える。全長300mのイチョウ並木のトンネルは、東京都内で最も長い黄葉ルートだ。入園料¥450。" },
      { type: "heading", content: "六義園のライトアップは予約なしで入れる", level: 2 },
      { type: "text", content: "文京区の六義園（りくぎえん）は江戸時代の大名庭園で、11月下旬〜12月上旬の夜間ライトアップが美しい。入園料¥300で17〜21時まで楽しめる。池に映る紅葉の色が独特で、他にはない光景。" },
    ],
    relatedArticleSlugs: ["tokyo-shinjuku-gyoen-seasons", "tokyo-cherry-blossom-ueno"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "tokyo-cafe-tour-shimokitazawa",
    title: "下北沢コーヒーショップ巡り──一人旅で通いたい東京の本物の喫茶文化",
    description: "東京にはスターバックスより深い喫茶文化がある。下北沢の路地裏がその中心地だ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-05-22",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tokyo",
    tags: ["下北沢", "カフェ", "喫茶店", "一人旅", "コーヒー"],
    spotIds: [],
    sections: [
      { type: "heading", content: "下北沢の路地裏に本物の珈琲がある", level: 2 },
      { type: "text", content: "下北沢（小田急線・井の頭線）は古着屋と劇場の街だが、路地裏に自家焙煎のスペシャルティコーヒー店が密集している。「気流舎」は昭和の雰囲気で文庫本が並ぶ読書カフェで、コーヒー¥600でオーナーと会話できる。" },
      { type: "heading", content: "中目黒のエスプレッソバーで都市型コーヒーを", level: 2 },
      { type: "text", content: "目黒川沿いの中目黒は「猿田彦珈琲」発祥の地だ。本店のハンドドリップ（¥700）はスタンディングで立って飲む東京スタイル。川沿いのカフェはテラス席が多く、春は桜の下でエスプレッソを飲める。" },
      { type: "heading", content: "清澄白河のサードウェーブコーヒーの聖地", level: 2 },
      { type: "text", content: "清澄白河は「Blue Bottle Coffee日本1号店」があるサードウェーブコーヒーの発祥地として知られる。周辺にARiSE Coffee RoastersやKIYOSUMI COFFEEが集まり、半日をかけて飲み歩く価値がある。" },
    ],
    relatedArticleSlugs: ["tokyo-budget-eats-kanda", "tokyo-imperial-palace-run"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "tokyo-odaiba-bay-sunset",
    title: "お台場ベイエリア夕景ガイド──レインボーブリッジと自由の女神像の構図を制覇",
    description: "東京湾の夕日は毎日違う色をしている。お台場から富士山シルエットと橋が重なる瞬間を捉えよ。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-08-25",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "tokyo",
    tags: ["お台場", "夕景", "夜景", "レインボーブリッジ", "カップル"],
    spotIds: [],
    sections: [
      { type: "heading", content: "自由の女神像からレインボーブリッジを見る", level: 2 },
      { type: "text", content: "お台場の自由の女神像（フランスから贈られたレプリカ）を前景に、レインボーブリッジと東京スカイラインが広がる構図は東京湾で最も有名な風景のひとつだ。日没30分前から橋のライトが点灯し始める。" },
      { type: "heading", content: "夕日の富士山シルエットは1月〜2月が最良", level: 2 },
      { type: "text", content: "冬の晴れた日の夕方、お台場から西の方角に富士山のシルエットが浮かぶことがある。1月〜2月は太陽の沈む位置と富士山が重なりやすく、ダイヤモンド富士に近い光景が見られる年もある。" },
      { type: "heading", content: "夜のデジタルアートで締める", level: 2 },
      { type: "text", content: "夕景の後は有明の「チームラボプラネッツ TOKYO」へ移動するのが最良の動線だ。素足で水の中を歩くインスタレーションは18時台から人が減るため、19時以降の予約が快適。ペア¥6,400。" },
    ],
    relatedArticleSlugs: ["tokyo-tower-night-view", "tokyo-roppongi-art-night"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "tokyo-halloween-shibuya",
    title: "渋谷ハロウィン2025──混雑を避けて楽しむ大人の参加術とベストポジション",
    description: "渋谷ハロウィンは世界最大の仮装パーティだ。参加するなら正しい場所と時間帯を知るべきだ。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokyo",
    tags: ["ハロウィン", "渋谷", "イベント", "仮装", "秋"],
    spotIds: ["shibuya-scramble"],
    sections: [
      { type: "heading", content: "10月31日より前の週末が穴場", level: 2 },
      { type: "text", content: "渋谷ハロウィンのピークは10月31日前後の週末だが、10月最初の週末も十分な仮装密度がある。本番直前の土曜は人出の8割程度で、撮影もしやすい。コスプレのクオリティも時間帯によって大きく差がある。" },
      { type: "heading", content: "観るなら109前か道玄坂上", level: 2 },
      { type: "text", content: "スクランブル交差点は混みすぎて動けなくなるため、SHIBUYA109の前か道玄坂の上の方が仮装を撮影しやすい。スターバックスの2階から見下ろす俯瞰は、ハロウィンの人密度を映えた写真で残せる。" },
      { type: "heading", content: "21時以降は渋谷から離れる", level: 2 },
      { type: "text", content: "渋谷ハロウィンは21時を過ぎると酔客が増え安全度が下がる。19〜21時の2時間で撮影と観察を終えて、代官山か恵比寿のバーに移動するのが賢い動き方。" },
    ],
    relatedArticleSlugs: ["tokyo-shibuya-scramble-guide", "tokyo-autumn-foliage-shinjuku"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "tokyo-new-year-hatsumode",
    title: "東京の初詣2026──明治神宮300万人と浅草寺の正しい参拝計画",
    description: "元旦の東京には特別な空気がある。正月の神社を賢く回るための時間と順番の話。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-12-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokyo",
    tags: ["初詣", "正月", "明治神宮", "浅草寺", "元旦"],
    spotIds: ["meiji-jingu", "senso-ji"],
    sections: [
      { type: "heading", content: "明治神宮は元旦0時直後か4日以降", level: 2 },
      { type: "text", content: "明治神宮は三が日に300万人以上が訪れる日本最多の初詣スポットだ。最も空いているのは0時の年越し直後か、1月4日以降。2日・3日の日中は最も混み、参拝まで2時間以上かかることがある。" },
      { type: "heading", content: "浅草寺は6時台の夜明けが別格", level: 2 },
      { type: "text", content: "元旦の浅草寺は0時から夜通し参拝者が続く。混雑のピークを外すなら夜明け前の5〜6時台だ。街が白みかける時間に雷門をくぐる体験は、年に一度の東京の顔を見ることになる。" },
      { type: "heading", content: "1月4日の増上寺が最も空いている", level: 2 },
      { type: "text", content: "港区の増上寺は徳川将軍家の菩提寺で、格式は最高クラスだが知名度は明治神宮・浅草寺より低い。元旦以降は比較的空いており、東京タワーと同じフレームで初詣写真が撮れる都心の穴場だ。" },
    ],
    relatedArticleSlugs: ["tokyo-meiji-jingu-forest-walk", "tokyo-asakusa-morning-walk"],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "tokyo-skytree-asakusa-combo",
    title: "東京スカイツリー＋浅草1日モデルコース──下町の縦軸を歩き倒す",
    description: "スカイツリーから浅草まで歩いて15分。この距離に東京の新旧が凝縮されている。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-04-12",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tokyo",
    tags: ["スカイツリー", "浅草", "下町", "モデルコース", "東京観光"],
    spotIds: ["senso-ji"],
    sections: [
      { type: "heading", content: "スカイツリーは朝イチの展望デッキが正解", level: 2 },
      { type: "text", content: "東京スカイツリーの第1展望台（350m）は朝9時台が最も空いている。チケットは¥2,100（当日窓口）で、オンライン事前購入なら¥100割引。第2展望台（450m）まで行くと追加¥1,000かかるが、1度は上がる価値がある。" },
      { type: "heading", content: "浅草へは隅田川沿いを歩く", level: 2 },
      { type: "text", content: "スカイツリータウンから隅田川沿いを北へ歩くと20分で浅草に着く。川沿いの遊歩道から見るスカイツリーは、川に映った逆さの高架が美しい。東京水辺ラインの屋形船がすれ違う時間帯は格別。" },
      { type: "heading", content: "昼は浅草の老舗で江戸前うなぎ", level: 2 },
      { type: "text", content: "浅草の「色川」（創業1861年）のうな重は上重¥5,500で、都内最高水準の江戸前うなぎが食べられる。11時の開店直後に入ると待ち時間なし。鰻の柔らかさと甘辛のたれは東京の定番を教えてくれる。" },
    ],
    relatedArticleSlugs: ["tokyo-asakusa-morning-walk", "tokyo-tsukiji-breakfast"],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "tokyo-summer-fireworks",
    title: "東京の夏祭り・花火2025──隅田川・神宮外苑・江戸川の3大花火を完全ガイド",
    description: "東京の夏は花火で始まり花火で終わる。混雑を避けて最良の場所から見る方法がある。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tokyo",
    tags: ["花火", "夏", "隅田川", "花火大会", "夏祭り"],
    spotIds: [],
    sections: [
      { type: "heading", content: "隅田川花火は観覧エリア抽選が最善策", level: 2 },
      { type: "text", content: "隅田川花火大会は例年7月最終土曜日開催で、観覧エリアへの入場は事前抽選（無料）か有料席チケットの購入が必要。一般の無料スペースは浅草橋・蔵前橋の間が比較的空いていて視界が開ける。" },
      { type: "heading", content: "神宮外苑花火は外周の無料スポットで十分", level: 2 },
      { type: "text", content: "神宮外苑花火大会（8月中旬）は会場チケット不要でも外苑周辺から十分見える。四谷3丁目駅から歩いて10分の荒木町付近の坂道が最も視界が開いている穴場。持ち込み飲料が事実上フリー。" },
      { type: "heading", content: "江戸川区花火は東京最大の規模", level: 2 },
      { type: "text", content: "江戸川区花火大会は1万4千発で東京最大規模だ。江戸川河川敷に無料で入れる場所が多く、有料席なしで楽しめる。瑞江駅から徒歩20分で河川敷に出られ、草の上でシートを広げる本格的な花火体験になる。" },
    ],
    relatedArticleSlugs: ["tokyo-cherry-blossom-ueno", "tokyo-halloween-shibuya"],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "tokyo-rainy-day-indoor",
    title: "雨の東京で行くべき場所8選──博物館・水族館・映画館の正しい選び方",
    description: "東京の雨は旅程の敵ではない。雨の日のために存在する場所が、東京には驚くほど多い。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-06-02",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokyo",
    tags: ["雨の日", "室内", "博物館", "水族館", "東京観光"],
    spotIds: ["ueno-park", "roppongi-hills"],
    sections: [
      { type: "heading", content: "上野は雨の日に最強の密度を発揮する", level: 2 },
      { type: "text", content: "雨の日は上野に行けというのが東京旅行の鉄則だ。東京国立博物館・国立科学博物館・東京都美術館が徒歩5分圏内に揃っており、1日で3館を梯子できる。常設展の入館料は¥600〜¥1,000と安い。" },
      { type: "heading", content: "六本木の森美術館と汐留のパナソニック汐留美術館", level: 2 },
      { type: "text", content: "六本木の森美術館は世界水準の企画展が常に行われており、雨の日に訪れると空いている傾向がある。汐留のパナソニック汐留美術館は小規模だが企画が精鋭で、空いていてゆっくり見られる。" },
      { type: "heading", content: "品川アクアパーク水族館は夜も面白い", level: 2 },
      { type: "text", content: "品川の「マクセルアクアパーク品川」はイルカショーとデジタルアートが融合した水族館で、夜間もオープンしている。入館¥2,300。雨の日よりむしろ夜に来た方が、プロジェクションマッピングが映える。" },
    ],
    relatedArticleSlugs: ["tokyo-ueno-museum-rainy-day", "tokyo-roppongi-art-night"],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "tokyo-night-walk-shimbashi",
    title: "新橋・汐留の夜──サラリーマンの街で飲む東京の本物の居酒屋文化",
    description: "新橋は東京で最もリアルな夜の街だ。観光地化されていない居酒屋が残る最後のエリア。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "tokyo",
    tags: ["新橋", "居酒屋", "グルメ", "夜", "ローカル"],
    spotIds: [],
    sections: [
      { type: "heading", content: "新橋駅前のSL広場から路地に入れ", level: 2 },
      { type: "text", content: "新橋駅東口のSL広場を越えて路地に入ると、立ち飲み屋・焼き鳥屋・もつ焼き屋が密集する。値段は生ビール¥400〜、串焼き1本¥100〜120が相場。17時台から満員になるため、18時前に陣取るのが正解。" },
      { type: "heading", content: "鳥森神社の横の飲み屋街は昭和が生きている", level: 2 },
      { type: "text", content: "新橋駅北口の鳥森神社（とりもりじんじゃ）横の飲み屋横丁は、30〜50年前から変わっていない雰囲気のガード下飲み屋街だ。店主の顔が見える小さな店に入ると、東京のサラリーマン文化の核に触れる。" },
      { type: "heading", content: "汐留の寿司バーでコースを締める", level: 2 },
      { type: "text", content: "新橋から汐留方向に歩いて10分のCaretta汐留B1Fには銀座・新橋の寿司職人が出る小さな寿司バーが並ぶ。コース¥5,000〜¥8,000で、立ち飲みの後に席でゆっくり寿司を食べるギャップが東京らしい。" },
    ],
    relatedArticleSlugs: ["tokyo-tsukiji-breakfast", "tokyo-ginza-luxury-guide"],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "tokyo-sumo-ryogoku",
    title: "両国・相撲観戦ガイド──国技館のますチケットと朝の相撲部屋見学の組み合わせ",
    description: "相撲観戦は日本で最も費用対効果の高いスポーツ体験のひとつだ。両国の1日を使い倒す方法。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-01-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokyo",
    tags: ["両国", "相撲", "国技館", "スポーツ", "伝統"],
    spotIds: [],
    sections: [
      { type: "heading", content: "本場所は1月・5月・9月に東京開催", level: 2 },
      { type: "text", content: "大相撲本場所の東京開催は1月（初場所）・5月（夏場所）・9月（秋場所）の年3回。すべて両国国技館で15日間行われる。升席チケットは¥8,000〜¥13,000で公式サイトから購入できる。" },
      { type: "heading", content: "朝9時からの取組が穴場の本物体験", level: 2 },
      { type: "text", content: "本場所の取組は朝9時から始まり、序の口・序二段・三段目と番付が上がっていく。この時間帯の国技館はほぼ空席で、間近で見られる。幕内の土俵入りは15時頃。1日通しの入場券で長さを自分で決められる。" },
      { type: "heading", content: "朝5時の相撲部屋稽古見学", level: 2 },
      { type: "text", content: "両国周辺には20以上の相撲部屋が集中している。一部の部屋は朝稽古の見学を受け入れており、申し込み不要で土俵の端に座って見学できる場合がある。朝5〜7時の稽古は力士が最も激しく動く時間帯。" },
    ],
    relatedArticleSlugs: ["tokyo-asakusa-morning-walk", "tokyo-budget-eats-kanda"],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "tokyo-art-galleries-kiyosumishirakawa",
    title: "清澄白河のギャラリー＆コーヒー──東京現代アートの最前線を歩く半日ルート",
    description: "清澄白河は10年前の下北沢に似ている。次に東京の文化の重心が来る場所がここだ。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-02-28",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tokyo",
    tags: ["清澄白河", "アート", "ギャラリー", "コーヒー", "現代美術"],
    spotIds: [],
    sections: [
      { type: "heading", content: "東京都現代美術館は常設展だけで3時間", level: 2 },
      { type: "text", content: "清澄白河の東京都現代美術館（MOT）は国内最大の現代美術コレクションを持つ。常設展¥500で草間彌生・荒川修作・パウル・クレーの作品を見られる。企画展と同時に来ると1日使える密度がある。" },
      { type: "heading", content: "ARiSE Coffee RoastersとBlue Bottleを梯子", level: 2 },
      { type: "text", content: "清澄白河はBlue Bottle Coffee日本1号店のオープン（2015年）以来、サードウェーブコーヒーの聖地になった。ARiSE Coffee Roasters（創業2010年）は地元民率が高く、ブレンド¥600の安定感が抜群。" },
      { type: "heading", content: "週末の路地を歩くと隠れたギャラリーが出る", level: 2 },
      { type: "text", content: "清澄白河の倉庫街には小規模な現代アートギャラリーが点在している。「MUJIN-TO Production」「Taka Ishii Gallery」などは予約不要で入れる。無料で世界レベルのアートを見られる東京の隠れ財産。" },
    ],
    relatedArticleSlugs: ["tokyo-cafe-tour-shimokitazawa", "tokyo-roppongi-art-night"],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "tokyo-shinjuku-kabukicho-nightlife",
    title: "新宿・歌舞伎町の夜──安全に楽しむための完全マニュアルと周辺の本物の店",
    description: "歌舞伎町は東京最大の歓楽街だ。観光で来るなら入るべき店と避けるべき場所がある。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-11-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tokyo",
    tags: ["新宿", "歌舞伎町", "夜", "グルメ", "安全"],
    spotIds: [],
    sections: [
      { type: "heading", content: "ゴールデン街は路地裏の本物の文化", level: 2 },
      { type: "text", content: "歌舞伎町の隣にある新宿ゴールデン街は、6坪程度のバーが200軒以上密集する日本唯一の飲み屋街だ。1杯¥500〜¥800のチャージで文学者・映画人・芸術家が通う店が残る。1〜2軒梯子するのが正しい使い方。" },
      { type: "heading", content: "思い出横丁の焼き鳥は昭和のまま", level: 2 },
      { type: "text", content: "新宿駅西口の思い出横丁（通称「ションベン横丁」）はガード下の狭い路地に30軒以上の飲み屋が密集する。焼き鳥1本¥150〜、もつ焼き¥180〜。1960年代の新宿がここだけ凍結したように残っている。" },
      { type: "heading", content: "東宝建設のゴジラヘッドは深夜でも見られる", level: 2 },
      { type: "text", content: "歌舞伎町の東宝シネマズ新宿ビルの屋上に設置されたゴジラヘッドは、夜間もライトアップされる。Hotel Gracery Shinjukuの8階テラスから間近で見られるので、宿泊せずにロビーから8階に上がることも可能。" },
    ],
    relatedArticleSlugs: ["tokyo-budget-eats-kanda", "tokyo-night-walk-shimbashi"],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "tokyo-ikebukuro-art-otaku",
    title: "池袋のアートとオタクカルチャー──東池袋と西口を渡り歩く丸1日ルート",
    description: "池袋は渋谷・新宿の影に隠れているが、独自の文化密度を持つ東京第3の繁華街だ。",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    publishedAt: "2025-08-18",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tokyo",
    tags: ["池袋", "サンシャイン60", "アニメ", "モデルコース", "展望台"],
    spotIds: [],
    sections: [
      { type: "heading", content: "サンシャイン60展望台は¥700で東京東部全景", level: 2 },
      { type: "text", content: "池袋のサンシャイン60は高さ240mの展望台（¥700）から、スカイツリーと上野の森が同時に見える。スカイツリーの展望台より安く空いているため、穴場的価値が高い。60階のカフェでモーニングは至高。" },
      { type: "heading", content: "乙女ロードは女性向けサブカルの聖地", level: 2 },
      { type: "text", content: "東池袋の「乙女ロード」は女性向けBL・コスプレ・同人誌の専門店が集中する通り。秋葉原と並ぶ日本のオタク文化の2大聖地で、ジャンルが全く異なる。週末は国際色豊かな客が訪れる。" },
      { type: "heading", content: "西口の喫茶店「大都会」でモーニング", level: 2 },
      { type: "text", content: "池袋西口の昭和レトロ喫茶「大都会」は創業50年超で、モーニングセット（トースト・ゆで卵・コーヒー）¥600が今も健在だ。年季の入ったマスターが一人でこなす職人気質の喫茶店は、東京に残り少ない。" },
    ],
    relatedArticleSlugs: ["tokyo-akihabara-subculture", "tokyo-cafe-tour-shimokitazawa"],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "tokyo-day-trip-nikko",
    title: "東京発・日帰り日光──東照宮・華厳の滝・いろは坂を6時間で回る最速プラン",
    description: "東京から新幹線なしで行ける最高の日帰り旅行先は日光だ。午前6時に出れば全部回れる。",
    coverImage: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
    publishedAt: "2025-10-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tokyo",
    tags: ["日帰り旅行", "日光", "東照宮", "紅葉", "モデルコース"],
    spotIds: [],
    sections: [
      { type: "heading", content: "浅草6:20発の東武特急スペーシアXで行く", level: 2 },
      { type: "text", content: "浅草駅から東武スペーシアX（特急）に乗ると東武日光駅まで約110分・¥2,920。6:20発の始発に乗れば8時10分には日光に着く。日光東照宮は8時開門で、着いた直後が最も空いている時間帯。" },
      { type: "heading", content: "東照宮→華厳の滝→いろは坂の動線", level: 2 },
      { type: "text", content: "9〜11時は東照宮の陽明門・三猿・眠り猫をじっくり見る。11時にバスで中禅寺湖へ移動（約45分）。華厳の滝の地下観瀑台（¥570）は12時頃が最も空いている。いろは坂の紅葉は帰路のバスから見下ろすのが絶景。" },
      { type: "heading", content: "東武日光17時発で浅草19時着", level: 2 },
      { type: "text", content: "日光駅17時前後の特急に乗ると浅草に19時前後に到着する。帰路は浅草で夕食を取ると、日光の文化と東京の下町が1日に入る濃密な体験になる。特急の帰路は車内で駅弁を食べるのが正しい流れ。" },
    ],
    relatedArticleSlugs: ["tokyo-asakusa-morning-walk", "tokyo-skytree-asakusa-combo"],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "tokyo-winter-illumination",
    title: "東京冬のイルミネーション2025──六本木・表参道・丸の内の3大スポットを夜に巡る",
    description: "東京の冬は光で飾られる。11月下旬から始まる3大イルミネーションを最も美しく見る順番がある。",
    coverImage: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "tokyo",
    tags: ["イルミネーション", "冬", "クリスマス", "夜景", "カップル"],
    spotIds: ["roppongi-hills"],
    sections: [
      { type: "heading", content: "表参道ケヤキ並木は11月下旬から6週間", level: 2 },
      { type: "text", content: "表参道のケヤキ並木イルミネーションは例年11月下旬〜1月上旬に実施される。700mにわたるケヤキの枝全体に電球が灯り、青白い光のトンネルになる。最も美しいのは19〜20時の消灯前1時間。" },
      { type: "heading", content: "丸の内イルミネーションは赤レンガ×シャンパンゴールド", level: 2 },
      { type: "text", content: "丸の内仲通りのイルミネーションはシャンパンゴールドの暖色が特徴で、明治期の赤レンガ建築と合わさって欧州の冬都市に見える。1.2kmの通りを端まで歩いて戻るだけで、東京で最もエレガントな夜歩きになる。" },
      { type: "heading", content: "六本木ヒルズの毛利庭園×クリスマス", level: 2 },
      { type: "text", content: "六本木ヒルズの毛利庭園には冬のイルミネーション期間中、池の周囲に光の装飾が施される。森タワーのライトアップと合わさった光のリフレクションは、東京で最も都会的な冬の光景を作り出す。入場無料。" },
    ],
    relatedArticleSlugs: ["tokyo-roppongi-art-night", "tokyo-tower-night-view"],
  },
];
