import { Article } from "@/types/article";

export const tottoriArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "tottori-sand-dunes-dawn",
    title: "鳥取砂丘、夜明け前に立つ──砂紋が消える前の1時間",
    description: "観光客が来る前の砂丘には、風だけが描いたキャンバスがある。誰も踏んでいない砂の上を歩く朝。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tottori",
    tags: ["鳥取砂丘", "早朝", "砂紋", "絶景", "鳥取"],
    spotIds: ["tottori-sand-dunes"],
    sections: [
      { type: "heading", content: "日の出30分前に砂丘センターへ", level: 2 },
      { type: "text", content: "鳥取砂丘の砂紋は朝が命だ。観光客の足跡がつく前、前夜の風が彫り上げた細い縦横の模様は、日の出後1時間で消え始める。鳥取駅から最初のバスに乗り、まだ薄暗い砂丘センター前で降りれば、砂の美術館の先に誰もいない丘が広がっている。" },
      { type: "heading", content: "馬の背を越えた先の日本海", level: 2 },
      { type: "text", content: "砂丘の最高点「馬の背」を登るとき、足が砂に沈む感覚はどこにもない体験だ。斜面を越えた瞬間、眼前に日本海が現れる。冬は灰色、夏は青い。季節によって全く違う海の色が待っている。" },
      { type: "spot-card", content: "tottori-sand-dunes" },
      { type: "heading", content: "帰りは「砂の美術館」で砂像の世界へ", level: 2 },
      { type: "text", content: "砂丘の隣に建つ砂の美術館は、世界各地をテーマにした砂像が展示される屋内施設。雨の日でも楽しめる。テーマが毎年変わるため、リピーターも多い。入館は午前9時からだが、砂丘で朝を過ごした後に立ち寄るルートが正解だ。" },
    ],
    relatedArticleSlugs: ["tottori-sand-dunes-camel", "tottori-urashima-coast"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "tottori-sand-dunes-camel",
    title: "ラクダに乗って砂丘を歩く──砂漠体験の意外なリアル",
    description: "鳥取砂丘でラクダ乗り体験ができることを知らずに来る人が多い。目線が上がると砂丘が変わる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "tottori",
    tags: ["鳥取砂丘", "ラクダ", "体験", "家族", "鳥取"],
    spotIds: ["tottori-sand-dunes"],
    sections: [
      { type: "heading", content: "ラクダ乗り場は砂丘入口の東側", level: 2 },
      { type: "text", content: "鳥取砂丘のラクダ乗り体験は、砂丘センターから砂丘に入ってすぐ右手にある。1頭のラクダに1〜2名が乗り、引き手に連れられて砂丘を歩く体験コースだ。料金は1回約1,000円。所要時間は10分ほどだが、高い目線から見る砂丘は地上とは別物の迫力がある。" },
      { type: "heading", content: "子どもより大人が喜ぶ理由", level: 2 },
      { type: "text", content: "ラクダに乗ると最初に気づくのは、揺れる幅の大きさだ。立ち上がる瞬間と座る瞬間の傾きに備えないといけない。子どもよりも大人の方が声を上げることが多い。砂丘という非日常の中で、さらに非日常の移動手段を使う感覚は忘れにくい。" },
      { type: "heading", content: "砂丘全体を歩くなら午前中が正解", level: 2 },
      { type: "text", content: "夏の砂丘は午後になると砂の表面温度が60度を超えることがある。裸足で歩きたいなら午前10時までに行動すること。スニーカーを脱いで砂の感触を確かめるなら、朝の砂が一番気持ちいい。" },
    ],
    relatedArticleSlugs: ["tottori-sand-dunes-dawn", "tottori-nashi-gourmet"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "tottori-mizuki-road-yokai",
    title: "水木しげるロード完全攻略──177体の妖怪を全部見つけろ",
    description: "境港の妖怪商店街は、スタンプラリーを持って歩くと全く違う楽しみ方になる。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-03",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tottori",
    tags: ["水木しげるロード", "妖怪", "境港", "スタンプラリー", "鳥取"],
    spotIds: ["mizuki-road"],
    sections: [
      { type: "heading", content: "まずスタンプラリーの台紙を入手する", level: 2 },
      { type: "text", content: "JR境港駅を降りたらすぐに駅舎内の観光案内所でスタンプラリーの台紙を受け取ること。177体のブロンズ像にはそれぞれ名前がついており、台紙を持って歩くと「あの妖怪の名前が鬼太郎の父の目玉親父だ」と発見が重なる。子連れはスタンプラリー、大人は妖怪の由来を調べながら歩くのが正解。" },
      { type: "spot-card", content: "mizuki-road" },
      { type: "heading", content: "水木しげる記念館は昼前に入る", level: 2 },
      { type: "text", content: "水木しげる記念館は商店街の中ほどにある。原画・草稿・妖怪の立体展示が充実しており、漫画ファン以外でも2時間は軽く過ごせる。入館は午前中が空いており、午後は団体客が入ってくることが多い。" },
      { type: "heading", content: "妖怪グルメは食べ歩きで楽しむ", level: 2 },
      { type: "text", content: "目玉おやじをかたどった肉まん、鬼太郎ラーメン、ネコ娘のケーキ。食べ歩きグルメは軒並み妖怪モチーフ。ただし量が多いので最初から全部買わず、気になるものを1〜2品ずつ試しながら歩くのが賢い。" },
    ],
    relatedArticleSlugs: ["tottori-daisen-hike", "tottori-sand-dunes-dawn"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "tottori-daisen-hike",
    title: "大山登山入門──伯耆富士の夏山道を日帰りで歩く",
    description: "中国地方最高峰・大山は、整備された夏山登山道があれば初心者でも日帰りが可能だ。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-08-15",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "tottori",
    tags: ["大山", "登山", "夏山", "日帰り", "鳥取"],
    spotIds: ["daisen"],
    sections: [
      { type: "heading", content: "夏山登山道は6合目まで樹林帯", level: 2 },
      { type: "text", content: "大山の標準ルートは南光河原駐車場を出発する夏山登山道。登山口から6合目まではブナ林の中を歩くため、夏でも涼しい。6合目小屋で水分を補給し、稜線への急斜面に備えること。" },
      { type: "spot-card", content: "daisen" },
      { type: "heading", content: "山頂稜線は木道を慎重に歩く", level: 2 },
      { type: "text", content: "大山の山頂付近はナイフリッジと呼ばれる細い稜線が続く。木道が整備されているが、視界が悪い日は特に慎重な歩行が求められる。晴れた日の山頂からは米子平野と日本海が一望できる。" },
      { type: "heading", content: "下山後は大山牧場でソフトクリーム", level: 2 },
      { type: "text", content: "下山後の楽しみは大山牧場の大山放牧牛乳ソフトクリーム。濃厚な乳脂肪分と山の空気が合わさって、格別においしく感じる。大山寺周辺の温泉施設で汗を流してから帰るルートが完璧だ。" },
    ],
    relatedArticleSlugs: ["tottori-daisen-autumn", "tottori-sand-dunes-dawn"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "tottori-daisen-autumn",
    title: "大山の紅葉──10月中旬、ブナ林が黄金色に染まる1週間",
    description: "大山寺周辺のブナ林の紅葉は、関西以西で最も美しい山岳紅葉のひとつ。時期を狙って行く価値がある。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tottori",
    tags: ["大山", "紅葉", "秋", "ブナ林", "鳥取"],
    spotIds: ["daisen"],
    sections: [
      { type: "heading", content: "見頃は10月中旬〜下旬", level: 2 },
      { type: "text", content: "大山のブナ林の紅葉は例年10月中旬から始まり、下旬に向けてピークを迎える。標高が高い山頂付近から始まり、大山寺の境内、南光河原へと順に下りてくる。見頃の週末は駐車場が埋まるため、公共交通機関の利用が推奨される。" },
      { type: "heading", content: "大山寺参道の黄金のトンネル", level: 2 },
      { type: "text", content: "大山寺に続く石畳の参道は、両側のブナが黄金色のアーチを形成する。朝の光が差し込む午前9時前後が最も美しい。参道の石畳に落ちた黄葉を踏みながら歩く感触は、言葉では伝わらない。" },
      { type: "heading", content: "大山环状道路からのパノラマ", level: 2 },
      { type: "text", content: "車があれば大山環状道路を一周すると、山の各面から異なる紅葉の表情が見られる。鍵掛峠からの大山南壁と紅葉の組み合わせは、写真家が毎年集まる名撮影ポイントだ。" },
    ],
    relatedArticleSlugs: ["tottori-daisen-hike", "tottori-urashima-coast"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "tottori-nashi-gourmet",
    title: "鳥取梨──二十世紀梨発祥の地で食べる梨の本気",
    description: "鳥取の梨は「二十世紀」だけではない。新品種の食べ比べから梨スイーツまで、秋の鳥取グルメを深掘りする。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-05",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "tottori",
    tags: ["梨", "二十世紀梨", "グルメ", "果物狩り", "鳥取"],
    spotIds: [],
    sections: [
      { type: "heading", content: "二十世紀梨と「なつひめ」の違い", level: 2 },
      { type: "text", content: "鳥取県が全国生産量トップを誇る二十世紀梨は、淡い黄緑色の薄皮と透明感のある甘みが特徴。一方、近年普及した「なつひめ」は黄白色でより濃い甘さ。鳥取市内の直売所では両方を1個から買えるため、食べ比べてみることをすすめる。" },
      { type: "heading", content: "梨狩りは8月末〜10月が旬", level: 2 },
      { type: "text", content: "鳥取市東部から八頭郡にかけては梨農園が多く、直接摘み取り体験ができる農園も複数ある。予約が必要な農園がほとんどだが、現地で受け付けている場合もあるため、訪問前に電話確認を。" },
      { type: "heading", content: "梨スイーツは道の駅でまとめて試食", level: 2 },
      { type: "text", content: "「道の駅 なしっこ館」（鳥取市）は梨に特化した道の駅で、梨ジュース・梨ジャム・梨のスイーツが充実している。農家直売品も並ぶため、産地ならではの価格で箱買いすることも可能。梨の産地としての鳥取を一か所で体験できる。" },
    ],
    relatedArticleSlugs: ["tottori-matsuba-crab", "tottori-sand-dunes-camel"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "tottori-matsuba-crab",
    title: "松葉ガニを食べに行く旅──11月解禁日から始まる冬の鳥取",
    description: "「松葉ガニ」とはズワイガニの山陰ブランド名。解禁直後の11月、港町に漂う潮の香りと一緒に食べる蟹は格別だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "tottori",
    tags: ["松葉ガニ", "カニ", "冬グルメ", "鳥取", "境港"],
    spotIds: [],
    sections: [
      { type: "heading", content: "11月6日解禁──漁港に活気が戻る朝", level: 2 },
      { type: "text", content: "松葉ガニ漁は毎年11月6日に解禁される。境港・賀露港（鳥取市）などの漁港では早朝から競りが行われ、その日の昼には市場の食堂に出回る。解禁直後の1週間は最も値が張るが、鮮度と感動の両方が最高峰だ。" },
      { type: "heading", content: "茹でガニと焼きガニ、どちらが正解か", level: 2 },
      { type: "text", content: "松葉ガニは茹でて食べるのが基本だが、漁師町では炭火で焼いて食べる「焼きガニ」も人気だ。茹では甘みと繊細な旨みを楽しめ、焼きは香ばしさと凝縮した風味が増す。どちらも正解で、量に余裕があれば両方食べてほしい。" },
      { type: "heading", content: "境港の市場で仲買価格を体験", level: 2 },
      { type: "text", content: "境港水産物直売センターでは漁協直営の販売が行われており、一般の観光客でも比較的リーズナブルにカニを購入できる。その場で蒸してもらうサービスもある。市場の活気の中でカニを選ぶ時間そのものが旅の醍醐味になる。" },
    ],
    relatedArticleSlugs: ["tottori-nashi-gourmet", "tottori-urashima-coast"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "tottori-urashima-coast",
    title: "浦富海岸──山陰の「リアス海岸」で見るエメラルドの入り江",
    description: "鳥取市の東、岩美町に広がる浦富海岸は山陰を代表する海岸美。透明度の高い水と奇岩の連続が圧巻だ。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "tottori",
    tags: ["浦富海岸", "海", "リアス海岸", "絶景", "鳥取"],
    spotIds: [],
    sections: [
      { type: "heading", content: "遊覧船で入り江を巡る", level: 2 },
      { type: "text", content: "浦富海岸の最大の魅力は、陸から見えない入り江の数々だ。岩美町岩井の遊覧船乗り場から出る「浦富海岸島めぐり遊覧船」に乗ると、洞窟や奇岩の近くまで船が近づく。透明度の高い海を底まで覗きながら進む40分の航路は、晴れた日に体験してほしい。" },
      { type: "heading", content: "シーカヤックで海岸線を漕ぐ", level: 2 },
      { type: "text", content: "夏季は地元のアウトドア業者によるシーカヤックツアーが運営されている。遊覧船が入れない浅い洞窟の入口まで漕ぎ込める体験は、参加者に強い印象を残す。初心者向けのツアーもあるため、事前予約で申し込める。" },
      { type: "heading", content: "砂浜は「菜種五島海水浴場」が穴場", level: 2 },
      { type: "text", content: "浦富海岸に連なる菜種五島海水浴場は、県内でも水質評価が高い海水浴場のひとつ。人が少なく、岩場と砂浜が混在する地形が変化に富んでいる。沖に向かって泳がず岩場周辺でシュノーケリングするだけで、驚くほど多くの魚が見られる。" },
    ],
    relatedArticleSlugs: ["tottori-sand-dunes-dawn", "tottori-matsuba-crab"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "tottori-sand-dunes-winter",
    title: "冬の砂丘──雪が積もった砂丘は、日本でここだけの光景",
    description: "砂と雪のコントラストは、年に数回しか見られない。SNSで一瞬で広がる冬の砂丘の正体を伝える。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "tottori",
    tags: ["鳥取砂丘", "冬", "雪", "絶景", "鳥取"],
    spotIds: ["tottori-sand-dunes"],
    sections: [
      { type: "heading", content: "砂丘に雪が積もる日は年10日前後", level: 2 },
      { type: "text", content: "鳥取砂丘に積雪が見られる日数は年間10日前後。海に近いため、雪が降っても翌日には融けていることが多い。鳥取市の降雪情報をXやウェブで確認し、積雪が予報されたら次の朝に動ける準備を事前にしておくことが唯一の方法だ。" },
      { type: "heading", content: "雪砂丘の撮影ポイントは馬の背の下", level: 2 },
      { type: "text", content: "白い雪と茶色い砂が混じり合う砂丘の斜面は、馬の背の直下で最も美しいコントラストを見せる。風紋に雪が入り込んだ細部のテクスチャーは、マクロ撮影でも絵になる。三脚を持参して早朝に入ることを推奨する。" },
      { type: "heading", content: "冬の砂丘は防寒と防風が最重要", level: 2 },
      { type: "text", content: "冬の鳥取砂丘は日本海から強風が吹き込む。フリースだけでは足りず、ウィンドブレーカーと手袋が必須だ。砂が目に入りやすいため、ゴーグルやサングラスがあるとより快適に過ごせる。足元はスニーカーではなく、保温素材のブーツが正解だ。" },
    ],
    relatedArticleSlugs: ["tottori-sand-dunes-dawn", "tottori-matsuba-crab"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "tottori-mizuki-museum",
    title: "水木しげる記念館の歩き方──妖怪ワールドの核心に迫る",
    description: "水木しげる記念館は単なる「マンガの資料館」ではない。水木が生涯かけて集めた妖怪の哲学がここにある。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "tottori",
    tags: ["水木しげる", "記念館", "妖怪", "境港", "鳥取"],
    spotIds: ["mizuki-road"],
    sections: [
      { type: "heading", content: "2024年リニューアル後の注目展示", level: 2 },
      { type: "text", content: "水木しげる記念館は2024年にリニューアルオープンし、展示がより没入型になった。妖怪の世界観を体感できる大型ジオラマ、戦争体験をベースにした水木の生涯の展示は、漫画を知らない世代にも深く刺さる内容だ。" },
      { type: "spot-card", content: "mizuki-road" },
      { type: "heading", content: "原画展示エリアを丁寧に見る", level: 2 },
      { type: "text", content: "ゲゲゲの鬼太郎の原画が収められたエリアは、印刷物では見えない線の密度と筆圧が伝わる展示だ。水木しげるが描く妖怪の線は細部まで丁寧で、デジタル作画とは全く異質の迫力がある。" },
      { type: "heading", content: "館内のショップで限定グッズを買う", level: 2 },
      { type: "text", content: "記念館内のミュージアムショップは記念館限定品が多い。ロードの商店街でも買えるグッズと、記念館だけで手に入るグッズは明確に違う。特に水木しげるの直筆サインが入ったポストカードシリーズは入手困難なため、見かけたら買っておくことをすすめる。" },
    ],
    relatedArticleSlugs: ["tottori-mizuki-road-yokai", "tottori-matsuba-crab"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "tottori-daisen-ski",
    title: "大山スキーリゾート入門──初心者が楽しむ中国地方の雪山",
    description: "中国地方最大規模のスキーエリアを持つ大山。雪質が安定している1月下旬〜2月が狙い目だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-01-15",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "tottori",
    tags: ["大山", "スキー", "ウィンタースポーツ", "鳥取", "冬"],
    spotIds: ["daisen"],
    sections: [
      { type: "heading", content: "大山のスキー場は3エリアに分かれる", level: 2 },
      { type: "text", content: "大山のスキーエリアは大山ホワイトリゾート（南壁）、大山国際スキー場（西部）、奥大山スキー場（奥大山）の3か所が代表的。初心者には緩やかなゲレンデが揃う大山国際スキー場が適している。レンタルは現地で揃えられる。" },
      { type: "heading", content: "スキーよりスノーシューで行く大山", level: 2 },
      { type: "text", content: "スキーが得意でない人には、スノーシューで大山のブナ林を歩くエコツアーがある。雪の重みで枝が垂れたブナ林の中を歩く静寂な体験は、スキーとは全く異なる大山の魅力を伝えてくれる。ガイド同行のツアーで参加できる。" },
      { type: "heading", content: "ゲレンデ食堂の大山牛乳コーヒーが絶品", level: 2 },
      { type: "text", content: "大山のスキー場のゲレンデ食堂では大山牧場の牛乳を使ったコーヒー牛乳が定番メニュー。寒さの中で飲む濃厚なミルクコーヒーは、スキーの疲れを回復させる。カレーやラーメンより、このミルクコーヒーを目当てに来る地元客もいる。" },
    ],
    relatedArticleSlugs: ["tottori-daisen-hike", "tottori-daisen-autumn"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "tottori-tottori-city-walk",
    title: "鳥取市街を歩く──城下町の痕跡と砂丘以外の見どころ",
    description: "鳥取市は砂丘だけの町ではない。鳥取城跡・仁風閣・久松公園と、城下町の地層を読む歩き方がある。",
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    publishedAt: "2025-04-25",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "tottori",
    tags: ["鳥取市", "城下町", "鳥取城", "仁風閣", "街歩き"],
    spotIds: [],
    sections: [
      { type: "heading", content: "久松公園と鳥取城跡", level: 2 },
      { type: "text", content: "鳥取市中心部の久松公園は、鳥取城の堀と石垣が残る公園だ。桜の季節は地元の花見スポットとして賑わい、天守台跡からは市街が一望できる。戦国・江戸時代に鳥取藩32万石の城として機能した遺構が、草の中に静かに残っている。" },
      { type: "heading", content: "仁風閣は明治の迎賓館", level: 2 },
      { type: "text", content: "久松公園内にある仁風閣は1907年建造の白い洋館で、皇太子（後の大正天皇）の行啓に合わせて建てられた迎賓館。フレンチルネサンス様式の優美な建物内部は見学できる。鳥取城跡の石垣と仁風閣の白壁の対比が美しい。" },
      { type: "heading", content: "鳥取砂丘のついでに立ち寄る動線", level: 2 },
      { type: "text", content: "鳥取市内観光は午前中に砂丘、午後に仁風閣・鳥取城跡を回るルートが効率的だ。砂丘から市街までバスで約30分。夕方には鳥取駅近くの「かろいち」（鳥取市民市場）で松葉ガニや地元鮮魚のショッピングができる。" },
    ],
    relatedArticleSlugs: ["tottori-nashi-gourmet", "tottori-matsuba-crab"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "tottori-onsen-guide",
    title: "鳥取の温泉ガイド──三朝温泉・皆生温泉・関金温泉を比較する",
    description: "世界有数のラジウム泉を持つ三朝温泉、米子の海沿い皆生温泉、山の中の関金温泉。3つの温泉地の個性を整理した。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-02-20",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "tottori",
    tags: ["温泉", "三朝温泉", "皆生温泉", "ラジウム泉", "鳥取"],
    spotIds: [],
    sections: [
      { type: "heading", content: "三朝温泉──世界屈指のラジウム泉", level: 2 },
      { type: "text", content: "鳥取県中部・三朝町にある三朝温泉は、世界でも有数のラドン含有量を誇るラジウム泉で知られる。放射能泉ながら「飲む温泉」として古くから親しまれ、川沿いに旅館が立ち並ぶ風情ある温泉街は散策だけでも楽しめる。" },
      { type: "heading", content: "皆生温泉──日本海を見渡す砂浜の宿", level: 2 },
      { type: "text", content: "米子市の弓ヶ浜半島沿いに広がる皆生温泉は、日本海の夕日を眺めながら入れる露天風呂が魅力。大型旅館が多く、海鮮を食べながら宿泊する「海の温泉旅館」として人気が高い。大山との組み合わせで米子を拠点にする旅行者に選ばれやすい。" },
      { type: "heading", content: "関金温泉──大山登山後に泊まる山の湯", level: 2 },
      { type: "text", content: "大山の南西麓にある関金温泉は登山者に支持される山の温泉地。小さな温泉街だが、地元の人も通う日帰り入浴施設「せきがね湯命館」は料金が安く湯質が良い。大山登山と組み合わせる旅程なら、関金温泉が最も動線が合う。" },
    ],
    relatedArticleSlugs: ["tottori-daisen-hike", "tottori-matsuba-crab"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "tottori-sakaiminato-daytrip",
    title: "境港日帰り旅──カニと妖怪と漁港の1日モデルコース",
    description: "米子から電車1本の境港は、水木しげるロードと漁港グルメを半日で回れる日帰りの名所だ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-11-25",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "tottori",
    tags: ["境港", "日帰り", "モデルコース", "水木しげる", "カニ"],
    spotIds: ["mizuki-road"],
    sections: [
      { type: "heading", content: "9:00 JR境港駅に到着・妖怪スタンプラリー開始", level: 2 },
      { type: "text", content: "米子駅から境線に乗り約45分で境港駅に到着。すぐに観光案内所でスタンプラリーの台紙をもらい、水木しげるロードの妖怪ブロンズ像を探しながら商店街を歩き始める。午前中は観光客が少なく、写真撮影しやすい。" },
      { type: "heading", content: "11:00 境港水産物直売センターで海鮮ランチ", level: 2 },
      { type: "text", content: "漁港そばにある水産物直売センターでは、カニをはじめとした新鮮な魚介類が市場価格で販売されている。センター内の食堂で海鮮丼やカニ汁を食べてから、午後の妖怪観光に戻る。カニシーズンは11月〜3月がベスト。" },
      { type: "heading", content: "13:00 水木しげる記念館で締める", level: 2 },
      { type: "text", content: "午後は水木しげる記念館で2時間をかけてじっくり回る。展示量が多いため、入館前にトイレを済ませておくこと。帰りのJRは米子行きの境線が1時間に1〜2本。日没前に米子に戻るなら15:30頃の電車が目安だ。" },
    ],
    relatedArticleSlugs: ["tottori-mizuki-road-yokai", "tottori-matsuba-crab"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "tottori-budget-trip",
    title: "1泊2日2万円で行く鳥取──砂丘・カニ・温泉の最安ルート",
    description: "鳥取は交通費が課題だが、工夫すれば1泊2日の充実した旅が2万円台で収まる。節約ルートを完全解説する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-15",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "tottori",
    tags: ["節約", "バジェット旅", "1泊2日", "鳥取", "モデルコース"],
    spotIds: ["tottori-sand-dunes", "mizuki-road"],
    sections: [
      { type: "heading", content: "交通は高速バスで大阪〜鳥取を4,000円", level: 2 },
      { type: "text", content: "大阪・神戸から鳥取への高速バスは日本交通・全但バスが運行しており、早割で片道3,500〜4,000円。新幹線からの特急スーパーまつかぜ乗り継ぎより安く、本数も多い。到着後はバスやレンタサイクルを使うと交通費をさらに抑えられる。" },
      { type: "heading", content: "宿は砂丘周辺のゲストハウスで4,000円", level: 2 },
      { type: "text", content: "鳥取砂丘の近くには複数のゲストハウスがあり、ドミトリーなら1泊3,500〜4,500円。温泉付き宿を選ぶなら福部温泉・鳥取温泉エリアの民宿が狙い目。素泊まりで予約し、食事は地元の定食屋でとると出費を抑えられる。" },
      { type: "heading", content: "グルメの取捨選択が節約の核心", level: 2 },
      { type: "text", content: "松葉ガニをフルコースで食べるとどうしても1人1万円超えになる。節約するなら、かろいちや市場で甲羅焼きの単品を注文するのが正解。梨・岩牡蠣・とうふちくわは安価でコストパフォーマンスが高いため、こちらをメインの食事にすると満足度が高い。" },
    ],
    relatedArticleSlugs: ["tottori-sand-dunes-dawn", "tottori-matsuba-crab"],
  },
];
