import { Article } from "@/types/article";

export const toyamaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "toyama-kurobe-dam-guide",
    title: "黒部ダム完全ガイド──観光放水・黒部湖・立山アルペンルートの歩き方",
    description: "220mの堤高が作り出す放水の轟音と飛沫。立山黒部アルペンルートの核心地点を余すことなく楽しむ計画術。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "toyama",
    tags: ["黒部ダム", "立山", "アルペンルート", "絶景", "富山"],
    spotIds: ["kurobe-dam"],
    sections: [
      { type: "heading", content: "観光放水は6月〜10月のみ──時間を逃すな", level: 2 },
      { type: "text", content: "黒部ダムの観光放水は毎年6月26日〜10月15日の期間に行われる。毎秒10〜15トンの水が放流される光景は、堤体上から正面に見ると音と飛沫が全身を包む。晴れた日は霧の中に虹が出現し、「これが日本最大のダムか」という実感が一気に押し寄せる。" },
      { type: "spot-card", content: "kurobe-dam" },
      { type: "heading", content: "黒部湖遊覧船「ガルベ」で湖上から展望", level: 2 },
      { type: "text", content: "黒部ダム上流に広がる黒部湖では、遊覧船「ガルベ」（6〜10月運航）に乗ることができる。標高1470mの人造湖を船から眺めると、周囲の峰々と空が水面に映り込む。船上からダムを振り返ると、アーチの美しさと北アルプスの稜線が一枚の絵として収まる。" },
      { type: "heading", content: "アルペンルートを通過する1泊2日の計画", level: 2 },
      { type: "text", content: "黒部ダムを含む立山黒部アルペンルートは全長37.3km、7つの乗り物を乗り継ぐ山岳観光ルートだ。富山側（立山駅）から入り、室堂で1泊して翌日に長野側（信濃大町駅）へ抜けるルートが王道。室堂の雪の大谷（4〜6月）と黒部ダムの放水（6〜10月）を一つの旅で見られる時期は6月が最高潮だ。" },
    ],
    relatedArticleSlugs: ["toyama-tateyama-murodo-snow", "toyama-alpine-route-seasons"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "toyama-amaharashi-coast-photo",
    title: "雨晴海岸──立山連峰と海が重なる朝の10分間を逃さない",
    description: "日本で最も贅沢な海の風景は、条件が揃った朝にしか現れない。雨晴海岸の攻略法を完全解説。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-03-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "toyama",
    tags: ["雨晴海岸", "立山連峰", "朝日", "写真映え", "富山湾"],
    spotIds: ["amaharashi-coast"],
    sections: [
      { type: "heading", content: "冬晴れの早朝が最高の条件──3000m超の白峰が海の向こうに立つ", level: 2 },
      { type: "text", content: "雨晴海岸で立山連峰が最も鮮明に見えるのは、冬から春にかけての晴天の朝だ。空気が澄んだ1〜4月、海面の向こうに劔岳・立山・薬師岳の3000m超の稜線が白く浮かぶ瞬間は、現実とは思えない構図になる。日の出の時間帯、朝日がオレンジ色に空を染める中に山の白が浮かぶ10分間が最高潮だ。" },
      { type: "spot-card", content: "amaharashi-coast" },
      { type: "heading", content: "義経岩と海岸の構図──岩を前景に入れる撮影術", level: 2 },
      { type: "text", content: "海岸には「義経岩」と呼ばれる岩があり、源義経が奥州に落ちる際に雨宿りしたという伝説がある。この岩を前景に入れ、背景に立山連峰を配置する構図は雨晴海岸の定番写真だ。岩の左側に立つと山が右奥に見える位置関係になる。三脚を立てて日の出時刻から20分前に構えているのが正しいタイミングだ。" },
      { type: "heading", content: "道の駅雨晴で海鮮朝食を食べる", level: 2 },
      { type: "text", content: "海岸に隣接する道の駅雨晴では、富山湾で水揚げされた新鮮な魚介を使った朝食が食べられる。ガラス張りの施設から海と山を眺めながら食べる海鮮定食は、早朝撮影の疲れを癒してくれる。白えびかき揚げ丼は地元定番のメニューで、朝9時から提供される。" },
    ],
    relatedArticleSlugs: ["toyama-kurobe-dam-guide", "toyama-takaoka-old-town"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "toyama-gokayama-winter",
    title: "五箇山合掌造り──冬の雪原と世界遺産の孤高を体験する旅",
    description: "白川郷より静かで、より深い。雪に埋まった合掌造り集落に一泊して本物の山村の冬を感じる。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "toyama",
    tags: ["五箇山", "合掌造り", "世界遺産", "冬景色", "雪"],
    spotIds: ["gokayama-gassho"],
    sections: [
      { type: "heading", content: "相倉集落と菅沼集落──二つの顔", level: 2 },
      { type: "text", content: "五箇山には「相倉」と「菅沼」の二つの合掌造り集落がある。相倉は規模が大きく23棟が現存し、宿泊可能な民家も多い。菅沼は規模は小さいが集落全体の一体感が強く、周囲の山と田んぼの景観が相倉より開けている。両方を同じ日に訪れると、集落の個性の違いが際立つ。" },
      { type: "spot-card", content: "gokayama-gassho" },
      { type: "heading", content: "冬のライトアップは予約が必要", level: 2 },
      { type: "text", content: "1〜2月の土日に行われる冬のライトアップは、相倉・菅沼それぞれで実施される。雪原に浮かぶ合掌屋根がライトに照らされる光景は世界中から観光客が集まるが、当日の車の乗り入れは規制されシャトルバスでのアクセスになる。宿泊者は夜通し集落を歩けるため、宿泊と合わせた計画が推奨される。" },
      { type: "heading", content: "囲炉裏端の夜──合掌造りに泊まる体験", level: 2 },
      { type: "text", content: "相倉集落の合掌造り民宿に宿泊すると、囲炉裏を囲んだ夕食が体験できる。岩魚の塩焼き、山菜の煮物、地元の豆腐鍋──山村の食卓は素朴だが、囲炉裏の火に照らされる空間がそれを特別なものにする。翌朝の雪原の静けさと、朝の光が合掌屋根を照らす瞬間は宿泊者だけの特権だ。" },
    ],
    relatedArticleSlugs: ["toyama-takaoka-old-town", "toyama-couple-gokayama-stay"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "toyama-hotaruika-spring",
    title: "ホタルイカの身投げ──3月〜5月、富山湾の奇跡を夜明け前に見る",
    description: "世界でここにしかない自然現象。ホタルイカが発光しながら浜に打ち上げられる春の夜明けを体験する。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "toyama",
    tags: ["ホタルイカ", "身投げ", "富山湾", "春", "夜明け"],
    spotIds: ["amaharashi-coast"],
    sections: [
      { type: "heading", content: "3月上旬〜5月中旬、夜明け前が唯一の時間帯", level: 2 },
      { type: "text", content: "ホタルイカの「身投げ」は、産卵のために深海から浮上したホタルイカが浜に打ち上げられる現象だ。滑川市から魚津市の砂浜で夜明け前（午前3〜5時）に出現することが多く、発光するホタルイカが打ち寄せる波の中で瞬くように光る様子は幻想的だ。自然現象のため必ず見られる保証はなく、現地の漁協や観光協会の情報を前日に確認すること。" },
      { type: "heading", content: "ほたるいかミュージアム──確実に発光観察をするなら", level: 2 },
      { type: "text", content: "滑川市の「ほたるいかミュージアム」では、春季（3〜6月）限定でホタルイカの発光観察体験ができる。館内のプールで生きたホタルイカの発光を暗闇で観察するプログラムは予約制。自然の身投げが見られない日の代替として、あるいは子ども連れの確実な体験として利用価値が高い。" },
      { type: "heading", content: "沖漬けと刺身──春の富山の食として楽しむ", level: 2 },
      { type: "text", content: "観察の後は、ホタルイカを食べる旅に転換する。早朝に水揚げされたホタルイカは、刺身（生食用処理済み）か沖漬け（醤油漬け）として富山市内の魚市場や飲食店で提供される。沖漬けは日本酒との相性が極めて高く、春の富山の最高の組み合わせだ。" },
    ],
    relatedArticleSlugs: ["toyama-himiburi-winter", "toyama-amaharashi-coast-photo"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "toyama-himiburi-winter",
    title: "氷見ブリ──12月〜2月、天然寒ブリの聖地で食べる旅",
    description: "「氷見のブリ」は日本で最も有名なブリのブランドだ。産地で食べるブリは別の食べ物だった。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "toyama",
    tags: ["氷見ブリ", "天然ブリ", "氷見市", "冬グルメ", "富山"],
    spotIds: ["amaharashi-coast"],
    sections: [
      { type: "heading", content: "氷見漁港の「ひみ番屋街」──朝獲れを昼に食べる", level: 2 },
      { type: "text", content: "氷見漁港に隣接する「ひみ番屋街」は、地元漁師の文化を体感できる食と物産の施設だ。朝5時頃に水揚げされた魚が同日の11時には食堂に並ぶ。冬（12〜2月）に「大寒ブリ入荷」の看板が出ていれば、刺身と照り焼きを迷わず注文すること。脂のりが別格の天然ブリは、産地でしか体験できない。" },
      { type: "heading", content: "「ブリしゃぶ」は氷見の冬の文化", level: 2 },
      { type: "text", content: "氷見市内の旅館・料亭では「ブリしゃぶ」を冬季メニューとして提供する。薄く切ったブリをだし昆布の鍋でしゃぶしゃぶし、ポン酢で食べるスタイルは、ブリ特有の脂の甘みが湯に溶け出すシンプルな料理だ。大根おろしと組み合わせると脂肪分が中和され、何枚でも食べ続けられる。" },
      { type: "heading", content: "立山連峰を背景に食べる──雨晴から氷見への動線", level: 2 },
      { type: "text", content: "雨晴海岸での早朝撮影を終えた後、氷見市内に移動してブリを食べる動線は富山冬旅の完成形だ。雨晴から氷見まで車で約30分。途中、立山連峰を右手に見ながら走る富山湾沿いの道は、富山の景観を最も贅沢に感じられるドライブルートになる。" },
    ],
    relatedArticleSlugs: ["toyama-hotaruika-spring", "toyama-amaharashi-coast-photo"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "toyama-tateyama-murodo-snow",
    title: "立山室堂・雪の大谷──20mの雪壁を歩く春のアルペン体験",
    description: "4月〜6月、立山室堂では雪に挟まれた道路を歩く「雪の大谷ウォーク」が楽しめる。日本の春の絶景体験。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "toyama",
    tags: ["室堂", "雪の大谷", "立山", "春", "アルペンルート"],
    spotIds: ["kurobe-dam"],
    sections: [
      { type: "heading", content: "4月中旬〜6月の雪壁──例年13〜17mの積雪量", level: 2 },
      { type: "text", content: "室堂平（標高2450m）の雪の大谷ウォークは、毎年4月中旬から6月下旬まで開催される。国道除雪で作られた雪の壁の高さは年によって異なるが、例年13〜17m。見上げると垂直の白い壁が両側にそびえ立つ。真っ青な空との対比が極めて強烈だ。" },
      { type: "heading", content: "みくりが池と地獄谷──室堂の歩き回り方", level: 2 },
      { type: "text", content: "室堂バスターミナルの周辺には、みくりが池・みどりが池・地獄谷と歩ける場所が点在する。雄山登山（往復約4時間）は体力が必要だが、バスターミナル周辺だけでも十分な景観が楽しめる。地獄谷の硫黄の噴気孔と白い雪の対比は、別の惑星のような異世界感がある。" },
      { type: "heading", content: "富山側からと長野側から──どちらから入るか", level: 2 },
      { type: "text", content: "立山黒部アルペンルートは富山側（立山駅）と長野側（信濃大町駅）の両方から入れる。日帰りで雪の大谷だけ楽しむなら富山側から入り、同じルートを引き返すのが時間効率が良い。前後泊を含めた場合は富山→長野（または逆）の縦断ルートが推奨される。" },
    ],
    relatedArticleSlugs: ["toyama-kurobe-dam-guide", "toyama-alpine-route-seasons"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "toyama-takaoka-old-town",
    title: "高岡の古い町並と国宝・瑞龍寺──加賀藩ゆかりの城下町を歩く",
    description: "富山第二の都市・高岡は、前田家ゆかりの歴史と鋳物文化を今も持つ。奥深い城下町の歩き方。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "toyama",
    tags: ["高岡", "瑞龍寺", "鋳物", "城下町", "国宝"],
    spotIds: ["amaharashi-coast"],
    sections: [
      { type: "heading", content: "国宝・瑞龍寺──前田家が建てた禅宗建築の最高峰", level: 2 },
      { type: "text", content: "高岡市の瑞龍寺は加賀藩2代藩主・前田利長の菩提寺で、山門・法堂・仏殿が国宝に指定されている。17世紀に建立された伽藍は江戸時代の禅宗建築を代表する建物群で、特に整然と並ぶ回廊と法堂の屋根の曲線美は見る角度によって表情が変わる。拝観料500円で1時間は過ごせる。" },
      { type: "heading", content: "山町筋──土蔵造りの商家町", level: 2 },
      { type: "text", content: "高岡市中心部の山町筋は、明治時代の大火後に防火を考慮して建てられた土蔵造りの商家が連続する重要伝統的建造物群保存地区だ。漆喰壁と黒い帯のコントラストが美しく、現在も店舗として機能している建物が多い。高岡の老舗和菓子屋「大野屋」はこのエリアにあり、和菓子と抹茶で休憩できる。" },
      { type: "heading", content: "高岡銅器──400年の鋳物文化の核心", level: 2 },
      { type: "text", content: "高岡は日本最大の銅器産地で、全国の銅器シェアの約95%を占める。高岡大仏（日本三大仏のひとつ）は高岡銅器の最も有名な作品だ。市内の鋳物体験工房では、実際に溶かした金属を型に流し込むミニチュア銅器作りが体験でき、職人技の一端に触れられる。" },
    ],
    relatedArticleSlugs: ["toyama-amaharashi-coast-photo", "toyama-gokayama-winter"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "toyama-couple-gokayama-stay",
    title: "五箇山・合掌造りに泊まるカップル旅行──囲炉裏と雪と夜の静寂",
    description: "世界遺産の集落に宿泊する体験は、記念日旅行として最高の選択肢のひとつだ。二人で過ごす山里の夜。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-01-20",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "toyama",
    tags: ["カップル", "五箇山", "合掌造り宿泊", "記念日", "世界遺産"],
    spotIds: ["gokayama-gassho"],
    sections: [
      { type: "heading", content: "宿の選び方──相倉集落の現役民宿を選ぶ", level: 2 },
      { type: "text", content: "五箇山での宿泊は相倉集落の合掌造り民宿が候補になる。現役で使われている合掌造りに泊まれる施設は数軒しかなく、週末の予約は2〜3ヶ月前には埋まる。囲炉裏部屋付きの部屋を選ぶと、夜に二人で火を囲む特別な時間が持てる。" },
      { type: "heading", content: "夕食後の集落散歩──消灯後の世界遺産", level: 2 },
      { type: "text", content: "夕食後の集落は街灯が少なく、晴れた夜は満天の星空が広がる。冬は雪で反射した月明かりが合掌屋根を照らし、昼間とは全く異なる幻想的な景色が現れる。この夜の集落を二人で歩ける体験は、宿泊者にしか許されていない特権だ。" },
      { type: "heading", content: "早朝の朝食と出発前の景色", level: 2 },
      { type: "text", content: "合掌造り民宿の朝食は朴葉味噌・山菜・川魚の素朴な膳が多い。朝食後に再び集落を歩くと、夜明けの光が雪原と合掌屋根を照らす最も美しい瞬間が待っている。チェックアウト時刻を少し遅らせて、この光を二人で見届けてから帰路につくのが正解だ。" },
    ],
    relatedArticleSlugs: ["toyama-gokayama-winter", "toyama-luxury-alpine-stay"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "toyama-family-day-trip",
    title: "富山子連れ旅行──黒部ダムと水族館と魚市場、1泊2日の完全プラン",
    description: "子どもが驚く体験が揃う富山。黒部ダムの放水音、富山湾の魚、立山の雪。圧倒的な自然を家族で体験する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "toyama",
    tags: ["子連れ", "家族旅行", "富山", "黒部ダム", "水族館"],
    spotIds: ["kurobe-dam", "amaharashi-coast"],
    sections: [
      { type: "heading", content: "黒部ダムの放水音──子どもの「でかい！」を体感させる", level: 2 },
      { type: "text", content: "黒部ダムの放水シーズン（6〜10月）に合わせると、子どもは放水の音と飛沫と迫力に圧倒される。ダム堤上から見下ろす黒部湖の水色と、真下に落ちる放水を同時に見上げると、体感スケールが理解できる。長いトンネルを電気バスで走る道中も子どもには十分な体験になる。" },
      { type: "heading", content: "魚津水族館──日本最古の水族館で富山湾の生き物を見る", level: 2 },
      { type: "text", content: "魚津市の魚津水族館は1913年開館の日本最古の水族館のひとつ。富山湾の深海魚を中心に展示しており、ホタルイカ・ゲンゲ・ダイオウグソクムシなど他ではなかなか見られない生き物が揃う。歴史的な建物の雰囲気と最新の展示が混在する個性的な水族館だ。" },
      { type: "heading", content: "富山市内で白えびバーガーとますのすし", level: 2 },
      { type: "text", content: "富山市の地元グルメ「ますのすし」はサーモン系の押し寿司で、子どもでも食べやすい味付けだ。富山駅内の「源」は全国区のブランドで、駅弁として新幹線の中で食べる形式でも人気がある。白えびのから揚げは子どもが大好きな味で、富山の食を家族で楽しむ入門になる。" },
    ],
    relatedArticleSlugs: ["toyama-kurobe-dam-guide", "toyama-tateyama-murodo-snow"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "toyama-budget-travel",
    title: "富山を安く旅する──アルペンルート以外の魅力を1万円台で回る",
    description: "富山はアルペンルートだけじゃない。無料の絶景・安い海鮮・地酒の角打ち。バジェット旅行の新定番。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "toyama",
    tags: ["節約旅行", "富山", "バジェット", "格安", "コスパ"],
    spotIds: ["amaharashi-coast", "gokayama-gassho"],
    sections: [
      { type: "heading", content: "雨晴海岸は入場無料──日本最高の海景色がタダ", level: 2 },
      { type: "text", content: "雨晴海岸は無料で入れる。あいの風とやま鉄道の雨晴駅から徒歩5分というアクセスも素晴らしく、電車旅でも気軽に寄れる。日本で最も贅沢な海の景色が無料で見られるのは、旅の予算配分において極めて優秀なスポットだ。" },
      { type: "heading", content: "富山市中心部の「総曲輪（そうがわ）」で安く食べる", level: 2 },
      { type: "text", content: "富山市の繁華街・総曲輪エリアには地元民向けの海鮮居酒屋が多い。白えびのかき揚げ・のどぐろの塩焼き・富山湾の刺身盛り合わせが2000〜3000円の予算で楽しめる。立山の地酒（新川大吟醸・満寿泉・立山）も1杯400〜600円で楽しめる。" },
      { type: "heading", content: "五箇山の集落見学は無料──宿泊せずとも価値あり", level: 2 },
      { type: "text", content: "五箇山の合掌造り集落（相倉・菅沼）は集落への入場は無料だ。有料施設（合掌の里など）もあるが、外から眺めるだけでも十分な感動がある。白川郷より混雑が少ないため、静かに写真を撮れる時間が長く、コストパフォーマンスの高い世界遺産観光が成立する。" },
    ],
    relatedArticleSlugs: ["toyama-amaharashi-coast-photo", "toyama-gokayama-winter"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "toyama-luxury-alpine-stay",
    title: "立山・室堂に泊まる贅沢──標高2450mの天空ホテルと星空体験",
    description: "夜の室堂は別世界だ。雲の上の宿に泊まり、星空と日の出を独占する富山の最高峰体験。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-07-25",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "toyama",
    tags: ["室堂", "立山", "山岳ホテル", "星空", "贅沢旅"],
    spotIds: ["kurobe-dam"],
    sections: [
      { type: "heading", content: "みくりが池温泉──日本最高所の天然温泉", level: 2 },
      { type: "text", content: "室堂バスターミナルから徒歩10分の「みくりが池温泉」は標高2430mに位置し、日本最高所の天然温泉として知られる。硫黄の香りが漂う露天風呂（酸性硫黄泉）から眺める立山連峰の稜線は、日本のどの温泉でも体験できない絶景だ。宿泊者は夜間の星空鑑賞と翌朝のご来光を独占できる。" },
      { type: "heading", content: "ご来光と朝のみくりが池の水鏡", level: 2 },
      { type: "text", content: "室堂での宿泊最大の価値はご来光だ。日の出時刻（夏は4時半前後）に合わせてみくりが池まで歩くと、池の水面に立山三山が映り込む水鏡を独占できる。日中は何百人もの観光客が集まる場所が、朝4時台には数人しかいない静寂に包まれる。" },
      { type: "heading", content: "黒部ダムとセットにする1泊2日ルート", level: 2 },
      { type: "text", content: "1日目：富山側から立山駅→室堂（みくりが池温泉泊）。2日目：室堂で朝の星空観察→黒部ダム見学→信濃大町へ下山するルートが贅沢な2日間だ。観光放水の時期（6〜10月）に合わせれば、室堂の大自然と黒部ダムの人工美を同時に体験できる。" },
    ],
    relatedArticleSlugs: ["toyama-kurobe-dam-guide", "toyama-tateyama-murodo-snow"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "toyama-masuzushi-food-guide",
    title: "ますのすしと富山の食文化──駅弁から郷土料理まで完全攻略",
    description: "富山の食は「地味だが深い」。鱒寿司・白えび・昆布〆・ブラックラーメン。食で語る富山旅の真髄。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "toyama",
    tags: ["ますのすし", "白えび", "昆布〆", "富山ブラック", "富山グルメ"],
    spotIds: ["amaharashi-coast"],
    sections: [
      { type: "heading", content: "ますのすし──1000年の歴史を持つ押し寿司の傑作", level: 2 },
      { type: "text", content: "鱒寿司（ますのすし）は富山湾でとれたサクラマスを塩漬けにして笹と酢飯と合わせた押し寿司だ。源が1900年代初頭に駅弁として広めて全国的なブランドになった。富山駅構内の売店では複数の蔵元が並ぶ「ますのすし食べ比べセット」が販売されており、製法の差を楽しめる。" },
      { type: "heading", content: "白えびとは何か──富山湾だけの宝石", level: 2 },
      { type: "text", content: "白えびは富山湾の水深300〜800mに生息するエビで、ほぼ富山湾でしか漁獲されない固有の種に近い存在だ。鮮度落ちが早いため産地でしか刺身では食べられない。かき揚げ丼・白えびバーガー・白えびせんべいなど加工品は全国で流通しているが、生の白えびを産地で食べる体験とは全く別物だ。" },
      { type: "heading", content: "富山ブラックラーメン──醤油と塩気の暴力的なパワー", level: 2 },
      { type: "text", content: "富山ブラックは醤油が黒く濃く煮詰まったスープが特徴のご当地ラーメンだ。戦後、工場労働者のおかずとして（飯のおかずとして食べるため塩辛くする）生まれたとされる。富山市内の「大喜（たいき）」「西町大喜」が元祖系で、実際に食べると塩辛さに驚くが、これが富山の食の真髄の一面だ。" },
    ],
    relatedArticleSlugs: ["toyama-himiburi-winter", "toyama-hotaruika-spring"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "toyama-solo-cycling",
    title: "富山をサイクリングで旅する──日本海沿岸と黒部川扇状地のルート設計",
    description: "富山は実は自転車旅に最適な地形だ。平野が広く、道が整備され、景色が変化に富む。一人旅の新定番。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "toyama",
    tags: ["サイクリング", "ひとり旅", "富山", "日本海", "自転車"],
    spotIds: ["amaharashi-coast", "kurobe-dam"],
    sections: [
      { type: "heading", content: "富山が自転車旅に向いている理由", level: 2 },
      { type: "text", content: "富山県は富山湾沿岸から立山連峰まで標高差のある地形だが、海沿いの平野部は平坦で自転車旅に最適だ。雨晴海岸〜氷見〜高岡を結ぶ海岸線ルートは約40kmで、1日で走り切れる距離に絶景スポットが連続する。観光案内所でのレンタサイクルも各主要駅で整備されている。" },
      { type: "heading", content: "雨晴→氷見の海岸線ルート──立山を右手に走る", level: 2 },
      { type: "text", content: "雨晴海岸から氷見市街まで約15km、海沿いの道路は車が少なく富山湾と立山連峰を常に視界に捉えながら走れる。途中の道の駅で休憩しながら、魚介の惣菜を食べ歩くのが正しい走り方だ。氷見市街でブリを食べて折り返すか、さらに和倉温泉まで走るかを状況で選択する。" },
      { type: "heading", content: "黒部川扇状地の直線道路を走る", level: 2 },
      { type: "text", content: "黒部市の中心部から海側に向かって広がる黒部川扇状地は、整然とした格子状の道路が続く農村地帯だ。果樹園と水田が広がる平地の向こうに立山連峰が見え、秋（9〜10月）は柿と稲穂の黄金色が道路の両側を染める。人が少なく、走っているだけで豊かな気持ちになるルートだ。" },
    ],
    relatedArticleSlugs: ["toyama-amaharashi-coast-photo", "toyama-takaoka-old-town"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "toyama-alpine-route-seasons",
    title: "立山黒部アルペンルート四季ガイド──最良の季節の選び方",
    description: "春夏秋それぞれに全く異なる顔を見せるアルペンルート。自分の目的に合った訪問時期の決め方。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-02-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "toyama",
    tags: ["アルペンルート", "四季", "立山", "観光計画", "旅のコツ"],
    spotIds: ["kurobe-dam"],
    sections: [
      { type: "heading", content: "春（4〜6月）──雪の大谷と残雪の室堂", level: 2 },
      { type: "text", content: "4月中旬の開山から6月末にかけては、雪の大谷ウォークが楽しめる時期だ。室堂平には大量の積雪が残り、青空と白の世界が広がる。黒部ダムの観光放水は6月26日から開始される。春は最も人気が集中する時期で、週末は混雑が激しい。" },
      { type: "heading", content: "夏（7〜8月）──高山植物と稜線歩きのベストシーズン", level: 2 },
      { type: "text", content: "7月〜8月は雪がほとんど解け、室堂平に高山植物（チングルマ・ミヤマキンバイ・ハクサンイチゲなど）が咲き乱れる。雄山（3003m）への登山が本格的に楽しめるのもこの時期だ。ただし本格的な高山登山の装備が必要で、午後の雷雨には注意が必要。" },
      { type: "heading", content: "秋（9〜10月）──紅葉と黒部湖の碧の競演", level: 2 },
      { type: "text", content: "9月下旬〜10月中旬は立山・黒部の紅葉シーズンだ。黒部湖の周囲の山々が赤・黄・緑に染まる中、碧い湖面との対比が極めて美しい。10月中旬にアルペンルートは閉鎖されるため、ぎりぎりの秋は時間との勝負になる。ケーブルカーからの紅葉眺望が特に見ごたえがある。" },
    ],
    relatedArticleSlugs: ["toyama-kurobe-dam-guide", "toyama-tateyama-murodo-snow"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "toyama-onsen-guide",
    title: "富山の温泉を知る──宇奈月・庄川峡・新湯のひそかな名湯",
    description: "富山のメインは山と海だが、実は渓谷沿いに良質な温泉が点在する。知る人ぞ知る名湯を巡る旅。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "toyama",
    tags: ["温泉", "宇奈月温泉", "庄川峡", "富山", "渓谷温泉"],
    spotIds: ["kurobe-dam", "gokayama-gassho"],
    sections: [
      { type: "heading", content: "宇奈月温泉──黒部峡谷トロッコ列車の玄関口", level: 2 },
      { type: "text", content: "宇奈月温泉は黒部峡谷の入口に位置する温泉地で、黒部川の渓流沿いに旅館が立ち並ぶ。泉質は無色透明のアルカリ性単純泉で、肌当たりが優しい。温泉地の最大の魅力はトロッコ列車（黒部峡谷鉄道）だ。春〜秋の運行期間に乗ると、黒部渓谷の奥深い自然を車窓から堪能できる。" },
      { type: "heading", content: "庄川峡温泉──五箇山の帰り道に寄れる渓谷の湯", level: 2 },
      { type: "text", content: "砺波市の庄川峡は庄川が刻む渓谷沿いに複数の温泉施設が点在するエリアだ。五箇山合掌造り集落から帰る道中に位置しており、観光後の日帰り入浴立ち寄りに最適だ。秋の紅葉期（10〜11月）は渓谷の紅葉と湯の組み合わせが特に美しい。" },
      { type: "heading", content: "立山温泉エリア──アルペンルート前泊の選択肢", level: 2 },
      { type: "text", content: "立山黒部アルペンルートの富山側入口・立山駅周辺には宿泊施設と温泉が整備されている。アルペンルートを翌日に控えた前泊として利用すると、早朝の始発ケーブルカーに楽にアクセスできる。富山市内から立山駅までは富山地方鉄道で約1時間。" },
    ],
    relatedArticleSlugs: ["toyama-luxury-alpine-stay", "toyama-couple-gokayama-stay"],
  },
];
