import { Article } from "@/types/article";

export const wakayamaArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "wakayama-kumano-kodo-nakahechi",
    title: "熊野古道・中辺路を歩く──世界遺産の石畳と山の空気",
    description: "1000年以上前から人々が歩き続けた参詣道。苔むした石畳と木漏れ日の中で、自分のペースで歩く一日。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "wakayama",
    tags: ["熊野古道", "中辺路", "世界遺産", "ハイキング", "巡礼"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "滝尻王子から熊野本宮大社へ", level: 2 },
      { type: "text", content: "中辺路の出発点・滝尻王子から歩き始めると、すぐに深い杉林の中に吸い込まれる。石畳の道は整備されているが、急坂もあるため軽登山靴は必須だ。道中には休憩所と水場が点在し、地元のおばちゃんが無人販売で梅干しを売っていることもある。" },
      { type: "spot-card", content: "kumano-kodo" },
      { type: "heading", content: "継桜王子の大クスノキに圧倒される", level: 2 },
      { type: "text", content: "野中の継桜王子に立つ大クスノキは樹齢800年超。幹を両手で抱えようとしても届かないほどの巨木が、道の脇に静かに立っている。古道を歩く人々を見守ってきた存在感に、思わず足が止まる。" },
      { type: "heading", content: "熊野本宮大社の大斎原で旅を締める", level: 2 },
      { type: "text", content: "かつての本宮の場所・大斎原に立つ日本最大の鳥居は、田んぼの中に突然現れる。訪れる人が少ない夕方、鳥居の向こうに夕日が沈む瞬間は、言葉を失う美しさだ。" },
    ],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "wakayama-shirahama-beach-summer",
    title: "白浜ビーチで過ごす夏──青い海と白い砂、関西屈指のリゾート",
    description: "関西随一の透明度を誇る白浜。砂浜の質、アクセスの良さ、周辺施設の充実度すべてが高水準。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "wakayama",
    tags: ["白浜", "海水浴", "ビーチ", "夏", "リゾート"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "白良浜の白砂はハワイ産？", level: 2 },
      { type: "text", content: "白浜のシンボル・白良浜の砂は純白で、実はハワイのワイキキビーチと姉妹浜の関係を持つ。砂の補充はオーストラリア産の珪砂を使っているという話もあるが、どちらにせよ関西では別格の美しさだ。夏の週末は混雑するため、早朝到着か平日訪問が快適。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "崎の湯──海を見ながら入る露天の元祖", level: 2 },
      { type: "text", content: "日本最古の温泉地のひとつとされる白浜で、最も海に近い露天風呂が崎の湯だ。波しぶきがかかるほどの距離に岩があり、太平洋に向かって湯につかる体験は、国内どこにもない。入浴料500円という良心的な価格もうれしい。" },
      { type: "heading", content: "円月島の夕日は全員に見せたい", level: 2 },
      { type: "text", content: "白浜の名勝・円月島は海食によって真ん中に穴が開いた小島だ。秋分・春分の前後、穴の中心に夕日が沈む「だるま夕日」が見られることがある。ただし毎年ズレるため、観光協会のウェブサイトで最新情報を確認してから行くこと。" },
    ],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "wakayama-koyasan-shukubo-stay",
    title: "高野山・宿坊体験──精進料理と朝のお勤めで整う一泊",
    description: "標高900mの霊場に一泊して、弘法大師空海の世界に浸る。宿坊の選び方から作法まで全解説。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "wakayama",
    tags: ["高野山", "宿坊", "精進料理", "仏教", "修行体験"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "宿坊の選び方──価格帯と雰囲気の違い", level: 2 },
      { type: "text", content: "高野山には117もの宿坊がある。一泊二食付きで1万5000円前後の標準的なものから、庭園が美しい高級宿坊まで幅広い。初めてなら恵光院や一乗院など、外国人客も多く英語対応しているところが入りやすい。予約は高野山宿坊協会の公式サイトから。" },
      { type: "heading", content: "朝6時のお勤めに参加する", level: 2 },
      { type: "text", content: "宿坊に泊まれば早朝のお勤めに参加できる。読経の振動が体の芯まで届く体験は、録音では絶対に再現できない。正座が苦手な人はあぐらでも問題ない。終了後に出される朝食の精進料理がまた格別だ。" },
      { type: "heading", content: "奥の院の夜──提灯の灯りと静寂", level: 2 },
      { type: "text", content: "宿坊に泊まることのもうひとつの特権が、夜の奥の院参拝だ。20万基を超える墓石と杉の大木が並ぶ参道は、夕方以降は提灯だけで照らされる。一人で歩くと怖いが、この静寂と古さは唯一無二の体験だ。" },
    ],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "wakayama-nachi-falls-pilgrimage",
    title: "那智の滝と飛瀧神社──日本一の落差133mを仰ぎ見る",
    description: "熊野三山のひとつ・那智大社と、御神体である那智の滝。濡れても近づく価値がある迫力の聖地。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-06-05",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "wakayama",
    tags: ["那智の滝", "熊野那智大社", "世界遺産", "滝", "パワースポット"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "飛瀧神社の延命の水を飲む", level: 2 },
      { type: "text", content: "那智の滝の真下に立つ飛瀧神社では、滝の落ち口近くから引いた「延命の水」が飲める。冷たくて清澄な水は、急坂を下りてきた体に染み渡る。お守り代わりに小さなボトルを持参して汲んで帰る人も多い。" },
      { type: "spot-card", content: "kumano-kodo" },
      { type: "heading", content: "熊野那智大社と青岸渡寺の重なり", level: 2 },
      { type: "text", content: "神社の隣に寺が並立する熊野那智大社と青岸渡寺は、神仏習合の歴史を現在も体現している。青岸渡寺の三重塔越しに那智の滝を撮る写真は、SNS上で最も認知度の高い和歌山の絶景のひとつだ。" },
      { type: "heading", content: "那智黒飴と熊野牛王神符をお土産に", level: 2 },
      { type: "text", content: "参道沿いの土産屋では那智黒飴（炭酸カルシウムを含む黒飴）と、からすの足跡模様が並ぶ熊野牛王神符が売られている。牛王神符は厄除けと火伏せの御符で、神社によって烏の数が違う。三社分集めるツウな買い方もある。" },
    ],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "wakayama-adventure-world-pandas",
    title: "アドベンチャーワールドのパンダ全頭制覇──世界一のパンダ王国",
    description: "世界で最多のジャイアントパンダを飼育する施設は、白浜にある。全エリアを効率よく回る作戦。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-01",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "wakayama",
    tags: ["アドベンチャーワールド", "パンダ", "白浜", "動物園", "家族旅行"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "開園直後がパンダ活動のゴールデンタイム", level: 2 },
      { type: "text", content: "パンダが最も活発に動くのは午前中。開園と同時に「パンダラブ」へ直行すると、竹をぐいぐい食べる姿や転げ回る姿が見られる確率が高い。午後は昼寝していることが多いため、午前中に押さえておくのが鉄則だ。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "サファリエリアは徒歩で回れる", level: 2 },
      { type: "text", content: "アドベンチャーワールドの広大なサファリは、バスツアーだけでなく徒歩エリアも充実している。ライオン、チーター、キリンなどが間近に見られる柵越し体験ゾーンは、子どもの反応が最も激しい場所だ。" },
      { type: "heading", content: "海獣館と水族館エリアも見逃さない", level: 2 },
      { type: "text", content: "同施設内の「マリンワールド」では、イルカショーと大型水槽の展示が楽しめる。アザラシの赤ちゃんが展示される春は特に混雑するため、事前にウェブサイトで誕生情報を確認しておくといい。" },
    ],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "wakayama-onsen-ryokan-luxury",
    title: "南紀白浜・川湯温泉の贅沢一泊──露天風呂と和会席で体を解く",
    description: "和歌山の温泉は白浜だけではない。川底から湯が湧く川湯温泉は、全国でもここだけの体験だ。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-11-10",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "wakayama",
    tags: ["温泉", "川湯温泉", "白浜温泉", "旅館", "贅沢旅"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "川の中に自分で掘る露天風呂「仙人風呂」", level: 2 },
      { type: "text", content: "川湯温泉では冬季限定（12月〜2月）で、大塔川の河原に巨大な露天風呂「仙人風呂」が作られる。川底を掘ると自然に湯が湧くため、宿泊客は自分でスペースを掘って入浴できる。開放感と原始的な体験が同時に得られる日本唯一の温泉。" },
      { type: "heading", content: "白浜温泉の高台旅館からの太平洋ビュー", level: 2 },
      { type: "text", content: "白浜の高台に建つ旅館の中には、全室オーシャンビューで客室に露天風呂付きのものがある。夕食の和会席では、地元で獲れた伊勢海老や紀伊の鮎が並ぶ。価格は一人3万円台からが相場だが、眼前の太平洋を独り占めする価値がある。" },
      { type: "heading", content: "紀州梅のコースで始まる朝食", level: 2 },
      { type: "text", content: "和歌山の旅館朝食で欠かせないのが南高梅だ。はちみつ漬け、しそ漬け、白干しと三種類が並ぶ朝食は、塩分補給と食欲増進に抜群の効果がある。食後に梅酒のデザートが出る旅館もあり、朝から幸せな気分になれる。" },
    ],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "wakayama-seafood-katsuura",
    title: "勝浦漁港の朝市で食べる生マグロ──本場の味はこれほど違う",
    description: "那智勝浦はマグロの水揚げ量全国トップクラスの港町。朝4時から始まる市場と朝食丼の世界。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "wakayama",
    tags: ["マグロ", "勝浦", "朝市", "海鮮", "グルメ"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "朝4時の那智勝浦魚市場", level: 2 },
      { type: "text", content: "那智勝浦の魚市場は早朝4時から活況を呈する。水揚げされたばかりの本マグロが並ぶセリは一般見学不可だが、市場周辺の食堂は5時頃から開店する。地元漁師が食べる「まぐろ漬け丼」は、東京のどのマグロ丼より赤くて脂がのっている。" },
      { type: "heading", content: "朝市通りで買い食いの作法", level: 2 },
      { type: "text", content: "駅前から漁港にかけての「朝市通り」では、早朝から干物、みかん、梅干しなどが並ぶ。試食が多く、おばあさんの押し付けには素直に従った方が楽しい。袋いっぱい買っても2000円以下というコストパフォーマンスは驚異的だ。" },
      { type: "heading", content: "熊野灘の伊勢海老も外せない", level: 2 },
      { type: "text", content: "那智勝浦周辺の熊野灘は伊勢海老の産地でもある。秋から冬にかけては活け造りが食べられる旅館や食堂が増え、一人前5000〜8000円程度で本物の伊勢海老が楽しめる。東京で食べる値段の半分以下だ。" },
    ],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "wakayama-surfing-susami",
    title: "すさみサーフィン入門──波質と初心者スクールの全情報",
    description: "和歌山の太平洋沿岸はサーフィンの名所が点在する。中でもすさみは波が安定しており初心者向きだ。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "wakayama",
    tags: ["サーフィン", "すさみ", "マリンスポーツ", "初心者", "海"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "すさみのポイントは季節で使い分ける", level: 2 },
      { type: "text", content: "すさみ町には複数のサーフポイントがあり、夏は南うねりで腰〜胸サイズの波が続く。JR周参見駅から歩いてアクセスできるポイントもあり、車なしでも挑戦できる。初心者スクールは町内の複数ショップが通年開催している。" },
      { type: "heading", content: "午前中の波は午後より安定する", level: 2 },
      { type: "text", content: "南紀の海は午後になると南東の海風が入り、波面が乱れやすい。サーフィン体験は午前中の早い時間帯を選ぶのが基本。前泊して朝一番から入水するのが最も良いコンディションを得られる方法だ。" },
      { type: "heading", content: "サーフィン後はすさみ温泉で塩を流す", level: 2 },
      { type: "text", content: "すさみ温泉「ホテルベルヴェデーレ」の日帰り入浴は、海から徒歩圏内で利用できる。ナトリウム塩化物泉は肌に優しく、塩分と日焼けで疲れた体を癒してくれる。夕方の窓から見える熊野灘の夕日が旅の締めとして最高だ。" },
    ],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "wakayama-spiritual-journey-solo",
    title: "一人で歩く熊野詣──現代人が古道に求めるものとは",
    description: "SNS疲れ、仕事のストレス。現代の「病」を抱えて熊野古道を歩く人が増えている理由を探る。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-01",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "wakayama",
    tags: ["一人旅", "熊野古道", "精神的旅", "自己探求", "巡礼"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "熊野に来る人は「何かを抱えている」", level: 2 },
      { type: "text", content: "熊野の宿の女将が言っていた言葉が忘れられない。「うちに来るお客さんは、何かを抱えて来る人が多い」と。転職前の人、離婚直後の人、病気が治った人。古道には人生の節目に歩く磁力がある。" },
      { type: "heading", content: "歩くことがメディテーションになる", level: 2 },
      { type: "text", content: "石畳を一歩一歩踏みしめる単調な動作は、半日も続けると一種の瞑想状態に近くなる。スマホを気にする暇がなくなるのは、適度な疲労と美しい景色が集中を引き出すためだ。参加者の9割が「また来たい」と答えるリピート率の高さがそれを証明している。" },
      { type: "heading", content: "一人旅に向いたコースとタイミング", level: 2 },
      { type: "text", content: "一人で歩くなら、宿が途中にある中辺路の「滝尻〜熊野本宮」3日間コースがおすすめだ。各宿の女将に次の宿を紹介してもらえる口コミネットワークがあり、一人で飛び込んでも安心して歩き続けられる。春と秋は特に混雑が少なく、道を独り占めできる時間が長い。" },
    ],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "wakayama-family-beach-vacation",
    title: "白浜で子連れ家族旅行──海・パンダ・温泉を1泊2日で制覇",
    description: "「子どもが喜ぶ」「親も楽しめる」「移動が楽」の三条件を満たす白浜2日間モデルプラン。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-07-15",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "wakayama",
    tags: ["白浜", "家族旅行", "子連れ", "1泊2日", "パンダ"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "1日目：アドベンチャーワールドでパンダ三昧", level: 2 },
      { type: "text", content: "開園直後（9時）から入場してパンダラブへ。午前中はパンダエリアとサファリを歩き、昼食はパーク内のレストランで。午後はイルカショーを見てから16時頃チェックアウト。白浜の宿へ向かい夕食前に温泉で1日の疲れを取る。" },
      { type: "spot-card", content: "nanki-shirahama" },
      { type: "heading", content: "2日目：白良浜で朝イチ水遊び", level: 2 },
      { type: "text", content: "早起きして白良浜へ。8時前なら人が少なく、子どもが安心して砂遊びできる。海の家は9時頃から開くため、シャワー・更衣室込みで利用するのが便利。昼食は千畳敷近くの食堂で海鮮丼を食べてから帰路へ。" },
      { type: "heading", content: "大阪・名古屋からのアクセスは特急が最速", level: 2 },
      { type: "text", content: "大阪（新大阪）からはJR特急「くろしお」で約2時間10分。名古屋からは特急「南紀」で約3時間。新幹線経由より特急直通の方が乗り換えなしで子連れには断然楽だ。週末は指定席が埋まりやすいため2週間前の予約を推奨する。" },
    ],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "wakayama-koyasan-couple-retreat",
    title: "高野山カップル旅──霊場の宿坊で過ごす非日常の一泊",
    description: "「神聖な場所に二人で行くのはどうなの？」その疑問に答えながら、カップルで楽しむ高野山を提案する。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "wakayama",
    tags: ["高野山", "カップル", "宿坊", "紅葉", "デート"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "秋の高野山は紅葉と霧が美しい", level: 2 },
      { type: "text", content: "10月下旬から11月上旬の高野山は、標高900mの気温差が紅葉を鮮やかに染める。早朝の霧の中を二人で歩く奥の院参道は、現実から切り離されたような空間だ。紅葉と苔と杉の組み合わせは、どのカメラで撮っても絵になる。" },
      { type: "heading", content: "宿坊の精進料理を二人で語りながら食べる", level: 2 },
      { type: "text", content: "宿坊の夕食は精進料理。肉・魚は一切使わず、豆腐・胡麻豆腐・野菜の天ぷらなどが静かに並ぶ。外食とは異なるこの静けさの中で食べる夕食は、普段とは違う話ができる場になる、とカップルの宿泊者に聞いた。" },
      { type: "heading", content: "壇上伽藍の夕暮れは二人占め", level: 2 },
      { type: "text", content: "日没前の壇上伽藍エリアは観光客が引けて静かになる。根本大塔の朱色と空の青のコントラストは、昼間とは全く異なる表情を見せる。夕食前に少し歩いてこの景色を二人で見るだけで、翌朝の目覚めが変わる。" },
    ],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "wakayama-plum-blossom-minabe",
    title: "みなべ梅林の梅まつり──日本一の梅の里を歩く",
    description: "和歌山県みなべ町は南高梅の産地として有名だが、2〜3月の梅まつりの時期は別格の美しさになる。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "wakayama",
    tags: ["梅", "みなべ", "南高梅", "梅まつり", "春の花"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "晴耕雨読の丘から一面の梅を俯瞰", level: 2 },
      { type: "text", content: "みなべ町の南部梅林は約10万本の梅が一斉に咲く。「晴耕雨読の丘」と呼ばれる展望台からは、山の斜面を白とピンクで埋め尽くす光景が広がる。2月上旬〜3月上旬が見頃で、梅まつり期間中はシャトルバスが運行される。" },
      { type: "heading", content: "梅干し工場の見学ツアー", level: 2 },
      { type: "text", content: "梅林散策と合わせて、地元の梅干し工場見学ができる農家が複数ある。実際に天日干しの工程を見て、試食できる機会もある。南高梅の完熟果実を使ったはちみつ梅は、箱買いしても後悔しない品質だ。" },
      { type: "heading", content: "梅まつりの屋台グルメ", level: 2 },
      { type: "text", content: "会場内の屋台では梅酒ソフトクリーム、梅干しおにぎり、梅ジュースが売られる。「梅そば」という珍しいメニューを出す屋台もあり、梅の酸味がそばつゆに溶け込んだ独特の味わいが癖になる。" },
    ],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "wakayama-budget-backpacking-kumano",
    title: "熊野古道バックパッカー旅──3泊4日を3万円以内で完歩",
    description: "交通費・宿泊費・食費の節約術を全公開。一人で歩く熊野古道、お金をかけずに最大限楽しむ方法。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-25",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "wakayama",
    tags: ["節約旅", "バックパック", "熊野古道", "格安旅行", "一人旅"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "交通費を半額にする「熊野古道きっぷ」", level: 2 },
      { type: "text", content: "南海電鉄が販売する「南海・熊野古道きっぷ」は、大阪〜紀伊田辺往復と熊野交通バス乗り放題がセットで通常の約6割の価格で買える。さらに年齢によっては学割・シニア割が適用される。購入は南海なんば駅の窓口が確実。" },
      { type: "heading", content: "1泊4000円以下の宿が沿道にある", level: 2 },
      { type: "text", content: "熊野古道沿線の民宿や農家民泊は、素泊まりで3500〜4500円の宿が残っている。古道ガイド協会のウェブサイトに掲載されている「やどかりシステム」を使えば、当日電話でも宿を紹介してもらえる。地元の夕飯に誘ってもらえることもある。" },
      { type: "heading", content: "食費は道の駅とコンビニを活用する", level: 2 },
      { type: "text", content: "道の駅「熊野古道中辺路」や「ほんぐう」では、地元産の弁当が500〜600円で売られている。コンビニは田辺市内と本宮周辺にしかないため、事前に補給しておくのが重要。山道の途中に茶屋がある場合もあるが営業日は不定期だ。" },
    ],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "wakayama-nachi-fire-festival",
    title: "那智の火祭り──日本三大火祭りのひとつを全身で体感",
    description: "毎年7月14日に行われる熊野那智大社の例大祭「那智の火祭り」。扇神輿と大松明の圧巻を前列で見る方法。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-07-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "wakayama",
    tags: ["那智の火祭り", "祭り", "那智大社", "夏祭り", "世界遺産"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "12基の扇神輿と12本の大松明が並ぶ", level: 2 },
      { type: "text", content: "那智の火祭りのクライマックスは、扇状に描かれた那智の滝の絵が描かれた12基の扇神輿が参道を降り、12本の大松明（直径1.3m、重さ50kg）と出会う場面だ。松明から降り注ぐ火の粉の中を神輿が進む様子は、写真や映像では伝わらない熱量がある。" },
      { type: "heading", content: "前列確保は2時間前から", level: 2 },
      { type: "text", content: "神事が始まる13時頃には、境内への参道が人で埋まる。前列で見たければ11時前には社殿前のスペースに陣取る必要がある。夏の直射日光対策として帽子・日焼け止め・水分は必携。熱中症対策を万全にして臨もう。" },
      { type: "heading", content: "祭り前後は宿が埋まるため1ヶ月前予約を", level: 2 },
      { type: "text", content: "7月14日前後の那智勝浦周辺の宿は、1〜2ヶ月前から埋まり始める。宿が取れない場合は新宮市や田辺市から当日移動するか、日帰り特急で対応するしかない。那智大社の公式サイトで当日のシャトルバス情報を事前に確認しておくこと。" },
    ],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "wakayama-high-end-ryokan-shirahama",
    title: "白浜の高級旅館に泊まる──選ぶべき宿と避けるべき宿の基準",
    description: "一人3万円以上を出すなら、どの旅館を選ぶべきか。実際の宿泊体験をもとに、選定基準を明かす。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-11-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "wakayama",
    tags: ["高級旅館", "白浜", "贅沢旅", "温泉", "和食"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "「オーシャンビュー露天付き客室」の確認方法", level: 2 },
      { type: "text", content: "旅館サイトの写真では全室オーシャンビューに見えても、実際には一部の部屋しか海が見えないケースが多い。予約前に電話で「円月島が見えるか」「露天は客室専用か共用か」を必ず確認すること。これを怠ると価格に見合わない部屋に案内されることがある。" },
      { type: "heading", content: "夕食の内容で旅館の本気度がわかる", level: 2 },
      { type: "text", content: "高級旅館の夕食は、地元食材の使い方で格が決まる。本物の南紀白浜の旅館なら、伊勢海老・クエ・南高梅を使った料理が揃うはずだ。「地元産」を謳いながら仕入れを外部に頼っている旅館は、料理の説明が曖昧になる。" },
      { type: "heading", content: "チェックイン15時・アウト12時の余裕が価値", level: 2 },
      { type: "text", content: "一流旅館は遅いチェックアウトと早いチェックインで滞在時間を最大化してくれる。翌日の観光を急がずに、朝風呂→朝食→昼前の海散歩→チェックアウトという流れが、高額宿泊の元を取る正しい使い方だ。" },
    ],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "wakayama-kumano-hongu-taisha",
    title: "熊野本宮大社の参拝作法と歴史──神々の宿る森の中心へ",
    description: "熊野三山の中心・熊野本宮大社は、深い森の中に静かに立つ。その歴史と正しい参拝の順序を解説。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "wakayama",
    tags: ["熊野本宮大社", "熊野三山", "参拝", "パワースポット", "世界遺産"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "158段の石段を登る前に息を整える", level: 2 },
      { type: "text", content: "本殿への石段は158段。急ではないが、傾斜は一定で長い。石段を登る前に手水舎で手を清め、ゆっくりと一段一段を踏みしめることが作法だとされている。石段の両側を飾る古木が作る影が、夏でも涼しい空間を作ってくれる。" },
      { type: "heading", content: "第四殿から参拝する理由", level: 2 },
      { type: "text", content: "熊野本宮大社の本殿は4社が並んでいるが、参拝の順序は「第四殿→第三殿→第二殿→第一殿」が正式とされている。この順序の理由は諸説あるが、第一殿の主祭神・家都美御子大神がすべての根源にあたるため、最後に敬うという解釈が有力だ。" },
      { type: "heading", content: "八咫烏のお守りは本宮限定品", level: 2 },
      { type: "text", content: "三本足のカラス・八咫烏（やたがらす）は日本サッカー協会のシンボルでもあり、熊野本宮大社の神使だ。ここでしか手に入らない八咫烏のお守りや絵馬は、サッカーファンにも巡礼者にも人気の品。試合前に買いに来る選手もいると聞く。" },
    ],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "wakayama-tanabe-hida-walk",
    title: "田辺市内の熊野古道スタート地点──歩き出しの一歩を現地で踏み出す",
    description: "多くの人が見落としている田辺市内の古道スタート地点。出発前に立ち寄るべき場所と準備の全て。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-01",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "wakayama",
    tags: ["田辺", "熊野古道", "準備", "スタート地点", "巡礼"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "闘鶏神社で旅の安全祈願を", level: 2 },
      { type: "text", content: "田辺の市街地にある闘鶏神社は、熊野古道の起点に立つ古社だ。かつて武蔵坊弁慶の父・熊野別当湛増が鶏を使って平家・源氏への協力を決めたという伝説の地でもある。参拝後に社務所で「熊野古道出立の証」を押してもらえる。" },
      { type: "heading", content: "世界遺産熊野本宮館でルートを把握", level: 2 },
      { type: "text", content: "田辺市内の「世界遺産熊野本宮館」は、古道全体の地図と現在の道路状況を無料で配布している。スタッフに歩行レベルと日数を伝えると最適ルートを提案してくれる。レンタルの杖（1日100円）も借りられる。" },
      { type: "heading", content: "足慣らしに市内の王子社を巡る", level: 2 },
      { type: "text", content: "田辺市内には平安時代の貴族が参拝した「王子社」が複数残っている。2〜3時間で市内の王子社を徒歩で巡るルートは、本格的な古道歩きの前日の足慣らしとして最適だ。市内なので迷っても大丈夫という安心感がある。" },
    ],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "wakayama-kimino-mandarin-picking",
    title: "紀美野町みかん狩り──和歌山の柑橘農家で過ごす秋の半日",
    description: "和歌山はみかんの生産量全国1位。本場で食べるみかんは、スーパーで買うものと別物だ。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-11-05",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "wakayama",
    tags: ["みかん", "みかん狩り", "農業体験", "紀美野町", "秋"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "11月は早生みかんの最盛期", level: 2 },
      { type: "text", content: "和歌山の早生温州みかんは10月下旬〜11月に収穫期を迎える。紀美野町内のみかん農家の多くが観光農園として体験を受け入れており、1時間食べ放題1500〜2000円程度で参加できる。持ち帰り用の購入も農家直売価格で可能。" },
      { type: "heading", content: "農家のおじちゃんに「糖度の高い見分け方」を習う", level: 2 },
      { type: "text", content: "農家の人に聞くと、糖度の高いみかんの見分け方を惜しみなく教えてくれる。「皮が薄くて色にムラがあるものが甘い」「形が少し扁平なものを選べ」など、スーパーでは絶対に教えてもらえない知識が聞ける。" },
      { type: "heading", content: "帰りに道の駅でみかん加工品を買い占める", level: 2 },
      { type: "text", content: "道の駅「しみず」や「くちくまの」では、みかんジュース、みかんゼリー、みかん酢、みかん味噌など独創的な加工品が並ぶ。特にストレートみかんジュースは東京のデパートでは1本1000円以上するレベルの品が400〜600円で買える。" },
    ],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "wakayama-shirahama-onsen-day-trip",
    title: "白浜温泉日帰り入浴ガイド──海に浮かぶ湯と絶景露天8選",
    description: "宿泊しなくても白浜温泉は楽しめる。日帰りで入れる個性豊かな8つの温泉施設を徹底比較。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-09-01",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "wakayama",
    tags: ["白浜温泉", "日帰り温泉", "露天風呂", "海の見える温泉", "日帰り旅"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "崎の湯──岩に囲まれた海際の露天", level: 2 },
      { type: "text", content: "入浴料500円で入れる崎の湯は、千畳敷の岩場に直接掘られた露天風呂だ。波が高い日は飛沫が飛んでくることもある。塩類泉の湯は肌がぬるっとした感触になり、上がった後もポカポカが長続きする。" },
      { type: "heading", content: "牟婁の湯──地元民が通う公衆温泉", level: 2 },
      { type: "text", content: "地元の人が日常的に使う牟婁の湯は、入浴料わずか460円。シャンプー・石鹸の持参が必要だが、観光客向けに整えすぎていない素朴な雰囲気が逆に好ましい。早朝6時から開いているため、旅館の朝風呂が物足りない人にもおすすめ。" },
      { type: "heading", content: "白浜温泉の泉質を知る", level: 2 },
      { type: "text", content: "白浜温泉の源泉は主に塩化物泉と炭酸水素塩泉の2種類がある。塩化物泉は保温効果が高く冬向き、炭酸水素塩泉は「美人の湯」とも呼ばれ肌を柔らかくする効果がある。施設によって源泉の種類が異なるため、入り比べるのも旅の楽しみになる。" },
    ],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "wakayama-pilgrimage-guide-first-time",
    title: "初めての熊野詣完全ガイド──三山参拝と御朱印の取り方",
    description: "熊野本宮・熊野速玉・熊野那智の三社を制覇する。初心者が迷わないルートと御朱印収集の作法。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-05-05",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "wakayama",
    tags: ["熊野三山", "御朱印", "参拝", "初心者", "巡礼"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "三山を一日で回るには車が必須", level: 2 },
      { type: "text", content: "熊野本宮大社・熊野速玉大社・熊野那智大社の三山は車で1日で回れる距離にある。公共交通でも可能だが、バスの本数が少なく効率が悪い。レンタカーは白浜か新宮で借りて、那智大社→速玉大社→本宮大社の順に南から北上するルートが最もスムーズ。" },
      { type: "heading", content: "御朱印帳は三山専用を用意する", level: 2 },
      { type: "text", content: "熊野三山それぞれの御朱印は様式が異なり、三社揃えると熊野詣の証明になる。熊野本宮大社では通常の御朱印に加えて「八咫烏御朱印」が人気で、社務所の開始時間（8時）前から並ぶ人もいる。専用の御朱印帳は各社で購入可能。" },
      { type: "heading", content: "熊野速玉大社の神宝館で宝物を見る", level: 2 },
      { type: "text", content: "三山の中で最も見落とされやすい熊野速玉大社だが、境内の神宝館には国宝を含む多数の宝物が収蔵されている。平安時代の神具の精巧さと保存状態の良さは博物館級。三山を回る際は速玉大社に時間の余裕を作っておくこと。" },
    ],
  },
  // ── 21 ──────────────────────────────────────
  {
    slug: "wakayama-south-cape-landscape",
    title: "串本・潮岬──本州最南端の岬で海を独り占めする",
    description: "本州最南端の潮岬は、三方を海に囲まれた絶景の岬。観光地化されすぎていない素朴な雰囲気が魅力だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "wakayama",
    tags: ["潮岬", "串本", "本州最南端", "絶景", "岬"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "潮岬灯台からの360度ビュー", level: 2 },
      { type: "text", content: "1870年に初点灯した潮岬灯台は、白い円筒形の姿が青空に映える。灯台に登ると（入場料200円）太平洋を360度見渡せる。晴れた日の午前中は視界が澄んでいて、水平線がはっきりと見える。" },
      { type: "heading", content: "芝生広場でのんびり過ごす", level: 2 },
      { type: "text", content: "灯台周辺の広大な芝生公園は、夏でも海風が涼しく気持ちいい。シートを広げて寝転がると、空と海と風だけの時間が流れる。売店も少なく人も少ないため、「何もしない」贅沢を楽しみたい人に最適な場所だ。" },
      { type: "heading", content: "橋杭岩の奇岩群は夜明けに訪れる", level: 2 },
      { type: "text", content: "串本の奇景・橋杭岩は、海中から一列に並ぶ岩柱群だ。弘法大師が一夜で建てたという伝説を持つ。日の出の時間に訪れると、朝日に照らされた岩と海のシルエットが幻想的で、写真家に人気のスポットだ。" },
    ],
  },
  // ── 22 ──────────────────────────────────────
  {
    slug: "wakayama-ume-harvest-experience",
    title: "南高梅収穫体験──6月の梅農家に一日入り込む",
    description: "梅干しの原料・南高梅の収穫シーズンは6月。農家の手伝いをして、本物の梅の値段を体で学ぶ。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "wakayama",
    tags: ["南高梅", "梅収穫", "農業体験", "みなべ", "食農体験"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "朝6時から始まる梅拾いの現実", level: 2 },
      { type: "text", content: "南高梅の収穫は、熟した梅が自然に落ちるのを待って拾う方式が基本だ。早朝6時から始まる収穫作業は、太陽が上がる前の涼しい時間帯に集中する。地面に腰を屈めて拾い続ける作業は想像以上に腰にくる。農家の人が「若い人は楽そうに見えて実は大変」と笑う。" },
      { type: "heading", content: "一粒一粒の傷を確認する選果作業", level: 2 },
      { type: "text", content: "収穫した梅は傷の有無と大きさで選別される。傷のある梅は梅酢や梅酒用に格下げされ、無傷の完熟梅が高級梅干し用になる。農家の目はAIより精度が高く、0.5mm以下の傷も見逃さない。この作業を見ていると梅干し一粒の値段の根拠がわかる。" },
      { type: "heading", content: "農家直売で持ち帰る量を計算する", level: 2 },
      { type: "text", content: "体験後に農家から直接買える完熟南高梅は、スーパーより20〜30%安いことが多い。梅干しを漬けるには梅1kgに塩150g程度が目安。1日仕込みに使う5〜10kgを持ち帰るのが一般的だ。農家によっては梅干し作りのレシピも教えてくれる。" },
    ],
  },
  // ── 23 ──────────────────────────────────────
  {
    slug: "wakayama-tanabe-food-scene",
    title: "田辺の食を探る──古道の玄関口に残る郷土料理と居酒屋文化",
    description: "熊野古道の起点・田辺市には独自の食文化がある。地元民が通う居酒屋と郷土料理を徹底取材。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "wakayama",
    tags: ["田辺", "グルメ", "郷土料理", "居酒屋", "食文化"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "めはり寿司──高菜で包んだ紀州の握り飯", level: 2 },
      { type: "text", content: "紀州南部の郷土食・めはり寿司は、漬け高菜で大きなおにぎりを包んだシンプルな食事だ。名前の由来は「目を見張るほど大きい」から来ているという。田辺市内の老舗食堂では、1個150〜200円で一つ一つ丁寧に作られためはり寿司が食べられる。" },
      { type: "heading", content: "クエ鍋は冬の田辺で食べる", level: 2 },
      { type: "text", content: "「クエの鍋は高い」という印象があるが、田辺市内の漁師料理の店では一人前3000〜4000円から食べられる。クエは熊野灘の深海に生息する大型魚で、鍋にすると出汁が絶品だ。予約必須で10月〜3月が主な提供期間。" },
      { type: "heading", content: "地元民に愛される駅前居酒屋の文化", level: 2 },
      { type: "text", content: "JR紀伊田辺駅前の居酒屋通りは、古道を歩き終えた旅人と地元の常連客が混在するユニークな空間だ。「今日どこから歩いて来たの？」という会話が自然に生まれる。生地元産の梅酒と紀伊半島の地酒が1杯400〜500円から飲める。" },
    ],
  },
  // ── 24 ──────────────────────────────────────
  {
    slug: "wakayama-rainy-day-indoor-spots",
    title: "和歌山の雨の日プラン──濡れずに楽しめる屋内スポット7選",
    description: "雨が降っても和歌山旅行は中止しなくていい。温泉・水族館・博物館・ショッピングモールで雨を楽しむ。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-06-15",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "wakayama",
    tags: ["雨の日", "屋内スポット", "和歌山", "旅行プラン", "水族館"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "アドベンチャーワールドは雨でも楽しめる", level: 2 },
      { type: "text", content: "アドベンチャーワールドの屋内施設は充実していて、雨でも1日過ごせる。マリンワールド（水族館）とパンダラブは全天候対応。雨の日はむしろ屋外サファリの動物が柵近くに寄ってくるため、観察に好都合だという逆転現象もある。" },
      { type: "heading", content: "串本海中公園の水中観覧室", level: 2 },
      { type: "text", content: "串本のサンゴ礁を水中から見られる串本海中公園の水中観覧室は、雨の日でも視界が変わらない。半潜水型の観覧船と水中観察窓から見るサンゴと熱帯魚は、水族館の水槽とは違うリアルな自然の美しさだ。" },
      { type: "heading", content: "和歌山市内の「和歌山城天守閣」と城下町散策", level: 2 },
      { type: "text", content: "和歌山市街の和歌山城は、天守閣内部の展示が充実している。天守から見る市街地の眺めは晴れ晴れしいが、雨の日は霧が城を幻想的に包んで写真映えする一面もある。城下町のカフェでゆっくり過ごすプランとの相性も良い。" },
    ],
  },
  // ── 25 ──────────────────────────────────────
  {
    slug: "wakayama-wakayama-castle-history",
    title: "和歌山城と紀州藩の歴史──徳川御三家の城下町を歩く",
    description: "紀州徳川家が居を構えた和歌山城は、天守閣と石垣の美しさで有名だ。城の歴史と周辺散策ルートを解説。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-20",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "wakayama",
    tags: ["和歌山城", "紀州藩", "歴史", "城下町", "徳川"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "豊臣秀吉の弟・秀長が最初に築いた城", level: 2 },
      { type: "text", content: "和歌山城は1585年に豊臣秀吉の命で弟の秀長が築城した。その後紀州徳川家の居城となり、8代将軍吉宗を輩出した。現在の天守閣は1958年の復元だが、石垣や堀は創建当時のものが残っている。" },
      { type: "heading", content: "西の丸庭園「紅葉渓庭園」の美しさ", level: 2 },
      { type: "text", content: "城内の西の丸にある紅葉渓庭園は、秋は紅葉・春は桜と四季折々の美しさがある。日本庭園の中心にある茶室では抹茶と和菓子を楽しめる（有料）。城の天守閣入場と合わせて2時間ほどで散策できる。" },
      { type: "heading", content: "城下町に残る旧加納家長屋門", level: 2 },
      { type: "text", content: "城周辺の和歌山市街には、藩政時代の武家屋敷の痕跡がわずかに残っている。旧加納家長屋門は国の登録有形文化財で、無料で見学できる。城郭だけでなく城下町の痕跡を探す歩き方が、歴史好きには深く刺さる。" },
    ],
  },
  // ── 26 ──────────────────────────────────────
  {
    slug: "wakayama-kii-peninsula-cycling",
    title: "紀伊半島自転車旅──海沿い国道42号を走る2泊3日",
    description: "熊野灘沿いの国道42号は、右手に太平洋を見ながら走る自転車旅の絶好コースだ。ルートと補給地点を全解説。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "wakayama",
    tags: ["自転車旅", "サイクリング", "紀伊半島", "熊野灘", "アクティビティ"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "白浜〜串本間は向かい風に注意", level: 2 },
      { type: "text", content: "国道42号の南紀区間は、午後になると南東からの海風が向かい風になりやすい。1日目は午前中に多めに距離を稼ぐ計画を立てること。白浜から串本まで約55kmは脚力によって3〜5時間で走れる。" },
      { type: "heading", content: "補給地点は道の駅を軸にする", level: 2 },
      { type: "text", content: "道の駅「すさみ」「串本」「くしもと橋杭岩」はトイレ・自動販売機・食事が揃う。コンビニは白浜・串本・那智勝浦の市街部に集中しており、その間は20〜30kmスパンで何もない区間がある。補給サイクルを事前に確認しておくこと。" },
      { type: "heading", content: "那智勝浦でゴール後の温泉と海鮮", level: 2 },
      { type: "text", content: "2泊3日のゴール地点を那智勝浦に設定すると、マグロの本場でのゴール飯が楽しめる。ホテルや民宿の駐輪スペースを予約時に確認しておくこと。温泉でじっくりと脚の疲れを取ってから、生マグロの宴で旅を締めくくる。" },
    ],
  },
  // ── 27 ──────────────────────────────────────
  {
    slug: "wakayama-new-year-kumano",
    title: "正月の熊野詣──新年に熊野三山を参る旅の計画",
    description: "「年が明けたら熊野に行く」という誓いを実行する人が増えている。混雑を回避した正月参拝の段取り。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2024-12-25",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "wakayama",
    tags: ["正月", "初詣", "熊野三山", "新年旅行", "巡礼"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "三が日は宿が取りにくい現実", level: 2 },
      { type: "text", content: "熊野本宮大社周辺の宿は、年末から年始にかけて半年前から埋まり始める人気ぶりだ。三が日を外して1月4日〜6日に訪れると、混雑が一段落して落ち着いて参拝できる。年始特有の張り詰めた空気は4日以降も残っているため、雰囲気は十分に楽しめる。" },
      { type: "heading", content: "雪の高野山に元旦参拝する選択肢", level: 2 },
      { type: "text", content: "高野山は冬は積雪があり、元旦の奥の院参道は雪に覆われた幻想的な景色になる。除夜の鐘が各伽藍で鳴り響く中で年を越す宿坊泊は、一生に一度体験する価値がある。ただし防寒対策は東北旅行レベルを想定すること。" },
      { type: "heading", content: "初詣御朱印は特別バージョンが出る", level: 2 },
      { type: "text", content: "熊野三山の多くの社で、正月期間限定の御朱印が頒布される。通常版と異なる金や朱の特別バージョンは、毎年デザインが変わるため毎年通う常連もいる。頒布数に制限がある社もあるため、開門前の並びが必要になることもある。" },
    ],
  },
  // ── 28 ──────────────────────────────────────
  {
    slug: "wakayama-shirahama-watersports",
    title: "白浜マリンスポーツ全ガイド──SUP・シュノーケル・カヤック",
    description: "白浜の海は泳ぐだけでは勿体ない。SUP、シュノーケリング、カヤックの体験情報を一本にまとめた。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "wakayama",
    tags: ["マリンスポーツ", "SUP", "シュノーケル", "カヤック", "白浜"],
    spotIds: ["nanki-shirahama"],
    sections: [
      { type: "heading", content: "SUPは白浜の湾内で安全に楽しめる", level: 2 },
      { type: "text", content: "白浜の湾内は波が穏やかで、SUP（スタンドアップパドル）の入門に最適な環境だ。白良浜周辺のマリンショップが体験プログラムを開催しており、1時間3000〜4000円程度で道具レンタル込みで楽しめる。立てるようになるまで30分もかからない。" },
      { type: "heading", content: "田辺・白浜のシュノーケルスポット", level: 2 },
      { type: "text", content: "白浜から南の磯エリアではシュノーケリングで熱帯魚や岩魚が見られる。ただし波の状況によって視界が変わるため、事前に当日の海況確認が必要だ。現地ショップが提供するガイドツアーに参加すれば、非公開の良ポイントに案内してもらえる。" },
      { type: "heading", content: "カヤックで洞窟探検ができる", level: 2 },
      { type: "text", content: "白浜近郊の海岸線には海食洞が点在しており、カヤックで中に入る体験ツアーがある。波の状況が良い日に限られる冒険的なアクティビティだが、洞窟内の反響音と光の入り方が幻想的で参加者の評価が高い。小学生以上から参加可能。" },
    ],
  },
  // ── 29 ──────────────────────────────────────
  {
    slug: "wakayama-koya-pilgrimage-guide",
    title: "高野山から熊野へ──「小辺路」を歩く4日間の旅程",
    description: "高野山から熊野本宮大社を結ぶ小辺路は、四つの峠越えを含む全72kmの難路だ。準備から宿まで全情報。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-04-15",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "wakayama",
    tags: ["小辺路", "高野山", "熊野古道", "ハイキング", "4日間"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "1日目：高野山から伯母子岳越えまで", level: 2 },
      { type: "text", content: "小辺路の第一日は高野山の山上集落を出発し、伯母子岳（1136m）への登りが続く。標高差は約400mで、登山経験のない人には体力面でのハードルがある。初日の宿は野迫川村の民宿か大股集落の民宿が選択肢になる。" },
      { type: "heading", content: "2〜3日目：十津川温泉で中間休息", level: 2 },
      { type: "text", content: "小辺路の中間点・十津川温泉は日本一大きな村（面積）にある温泉地だ。体の疲れを温泉で取り、旅の後半に備える。十津川温泉の宿は素泊まりから食事付きまで多様で、予算に合わせて選べる。" },
      { type: "heading", content: "4日目：熊野本宮大社に到着する達成感", level: 2 },
      { type: "text", content: "最終日は七色高原から本宮大社へ下る。4日間・72kmを歩いた後に辿り着く本宮大社の石段を登る時の達成感は、他のどんな旅行でも味わえないものだ。社殿に手を合わせた後は大斎原の鳥居前に座って川の音を聞くだけでいい。" },
    ],
  },
  // ── 30 ──────────────────────────────────────
  {
    slug: "wakayama-whale-watching-taiji",
    title: "太地町のクジラ文化──捕鯨の歴史と博物館、そして海",
    description: "太地町は世界で最も長い捕鯨の歴史を持つ町だ。文化として捕鯨を理解し、海を感じる一日の旅。",
    coverImage: "https://images.unsplash.com/photo-1440186347098-386b7459ad6b?w=1200&q=80",
    publishedAt: "2025-09-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "wakayama",
    tags: ["太地町", "捕鯨", "クジラ", "文化", "博物館"],
    spotIds: ["kumano-kodo"],
    sections: [
      { type: "heading", content: "くじらの博物館で400年の歴史を学ぶ", level: 2 },
      { type: "text", content: "太地町立くじらの博物館は、江戸時代から続く組織的捕鯨の歴史を実物資料で紹介している。クジラの骨格標本や捕鯨道具の展示は博物館としての質が高く、賛否が分かれるテーマを丁寧に伝えようとする姿勢が伝わってくる。" },
      { type: "heading", content: "クジラ料理を食べることの意味", level: 2 },
      { type: "text", content: "太地町内の食堂ではクジラ料理が食べられる。鯨のベーコン、鯨のたれ（干し肉）、鯨のコロ（皮の揚げ物）など、独自の食文化が残っている。食べることが文化の継承を支えているという主張は、地元の人から直接聞いてこそ重みがある。" },
      { type: "heading", content: "イルカウォッチングと太地の海", level: 2 },
      { type: "text", content: "議論のある捕鯨問題とは別に、太地沖の海はイルカの回遊が多く、春〜秋にかけてイルカウォッチングのボートツアーが出ている。海の豊かさを感じながら、文化の複雑さを静かに考えることができる場所として、太地町は訪れる価値がある。" },
    ],
  },
];
