import { Article } from "@/types/article";

export const yamanashiArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "yamanashi-fujigoko-model-course",
    title: "富士五湖1泊2日モデルコース──本栖湖の逆さ富士から河口湖の夕暮れまで",
    description: "千円札と同じ景色を朝5時に見る。富士五湖を効率よく巡る、定番にして最高の旅程。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-10",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "yamanashi",
    tags: ["富士五湖", "富士山", "逆さ富士", "モデルコース", "山梨"],
    spotIds: ["fuji-goko"],
    sections: [
      { type: "heading", content: "1日目朝：本栖湖で逆さ富士を狙う", level: 2 },
      { type: "text", content: "本栖湖北岸の撮影ポイントに夜明け前に着く。無風の早朝だけ湖面が鏡になり、千円札とまったく同じ逆さ富士が現れる。駐車場から徒歩5分。三脚があると安心だが、スマートフォンでも十分な条件が揃う。" },
      { type: "spot-card", content: "fuji-goko" },
      { type: "heading", content: "1日目昼：ほうとう不動で昼食", level: 2 },
      { type: "text", content: "河口湖周辺に数軒ある「ほうとう不動」は、山梨のほうとうを代表する店。南店が行列が短め。かぼちゃと太い平打ち麺が入った味噌汁仕立てのほうとうは1,450円。体が温まり、午後の観光に備えられる。" },
      { type: "heading", content: "2日目：山中湖の白鳥と富士山展望", level: 2 },
      { type: "text", content: "山中湖は富士山の眺めが五湖の中で最も開けている。白鳥の浮かぶ湖畔を歩きながら富士山を正面から見る時間が、旅の最後を締めくくる。道の駅富士吉田でお土産を選んでから帰路につく。" },
    ],
    relatedArticleSlugs: ["yamanashi-hottarakashi-onsen-dawn", "yamanashi-fruit-picking-guide"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "yamanashi-hottarakashi-onsen-dawn",
    title: "ほったらかし温泉、日の出前入湯記──甲府盆地の夜景と朝焼け富士",
    description: "日の出1時間前から開く露天風呂。暗闇の中に湯に入り、空が白む瞬間を全身で感じる体験。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-03-05",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "yamanashi",
    tags: ["温泉", "日の出", "露天風呂", "富士山", "ほったらかし温泉"],
    spotIds: ["hottarakashi-onsen"],
    sections: [
      { type: "heading", content: "開門は日の出1時間前──4時台に出発する", level: 2 },
      { type: "text", content: "ほったらかし温泉の「あっちの湯」は日の出の1時間前から開く。季節によって開館時刻が変わるので事前確認必須。山梨市駅からタクシーで約15分・1,600円が最も確実なアクセス手段。入浴料は900円。" },
      { type: "spot-card", content: "hottarakashi-onsen" },
      { type: "heading", content: "暗闇の湯から空が変わる30分", level: 2 },
      { type: "text", content: "真っ暗な湯に入ると、甲府盆地の夜景が広がる。次第に空が濃紺から藍色、オレンジへと変わる。富士山のシルエットが浮かび上がり、山頂に朝日が当たった瞬間が最高潮。この変化を湯の中で体感するために、日本中から人が来る。" },
      { type: "heading", content: "湯上がりは桃ソフトクリームで決まり", level: 2 },
      { type: "text", content: "隣接する売店は朝5時から開いており、山梨産桃を使ったソフトクリーム（400円）が名物。温泉上がりの体に冷たいソフトクリームは、ここでしか成立しない組み合わせ。帰りに笛吹市のフルーツロードを車で走ると、朝の果樹園が美しい。" },
    ],
    relatedArticleSlugs: ["yamanashi-fujigoko-model-course", "yamanashi-shosenkyo-autumn"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "yamanashi-shosenkyo-autumn",
    title: "昇仙峡の紅葉──覚円峰と仙娥滝、11月の峡谷美",
    description: "花崗岩の奇岩と紅葉が重なる11月の昇仙峡は、日本一の渓谷美という言葉が誇張でない。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-11-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "yamanashi",
    tags: ["昇仙峡", "紅葉", "秋", "渓谷", "山梨"],
    spotIds: ["shosenkyo"],
    sections: [
      { type: "heading", content: "昇仙峡の紅葉カレンダー", level: 2 },
      { type: "text", content: "昇仙峡の紅葉は標高によって時期がずれる。ロープウェイ上部エリアは10月下旬から色づき始め、渓谷沿いの遊歩道は11月上旬〜中旬が見頃。混雑ピークは11月の土日祝で、駐車場が満杯になる9時前に到着したい。" },
      { type: "spot-card", content: "shosenkyo" },
      { type: "heading", content: "覚円峰の真下で見上げる", level: 2 },
      { type: "text", content: "高さ180mの柱状岩壁・覚円峰は、遊歩道から真下で見上げると首が痛くなる迫力がある。秋は周囲の木々が赤く染まり、灰色の岩壁との色のコントラストが写真で再現できないほど鮮烈。遊歩道は滑りやすいので底がラバーソールの靴推奨。" },
      { type: "heading", content: "仙娥滝で旅のクライマックス", level: 2 },
      { type: "text", content: "遊歩道の終点にある仙娥滝（落差30m）は、秋の紅葉が滝を額縁のように囲む。飛沫を浴びながら近づける岩場があり、全身で水音を受ける体験ができる。滝の上のロープウェイ乗り場（1,000円）でさらに上のエリアへ。水晶・宝石の露店が並ぶ独特の山頂エリアも見どころ。" },
    ],
    relatedArticleSlugs: ["yamanashi-hottarakashi-onsen-dawn", "yamanashi-takeda-shrine-history"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "yamanashi-hoto-gourmet",
    title: "ほうとうの本当においしい食べ方──山梨の郷土食を地元流で味わう",
    description: "観光地の行列店だけがほうとうじゃない。地元の人が通う店と、自宅での作り方まで。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-02-18",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "yamanashi",
    tags: ["ほうとう", "山梨", "郷土料理", "グルメ", "冬"],
    spotIds: [],
    sections: [
      { type: "heading", content: "ほうとうは「うどんの親戚」ではない", level: 2 },
      { type: "text", content: "ほうとうは小麦粉を練った生地を不規則に切った太い平打ち麺。塩を入れないため麺がやわらかく、味噌仕立ての汁に直接入れて煮込む。かぼちゃが必ず入るのが山梨のほうとうの定義。食べ始めるより終わりのほうが汁が濃くなる、煮込み料理の特性を楽しむ。" },
      { type: "heading", content: "名店「ほうとう不動」と「小作」の違い", level: 2 },
      { type: "text", content: "「ほうとう不動」（河口湖南店・1,450円）は麺の太さとかぼちゃの存在感が際立つ濃厚系。「小作」（甲府・河口湖に複数店）は麺が細めでスープが澄みやすい。甲府市内の「奥藤本店」は昭和の定食屋の雰囲気でかつ丼と並ぶ看板メニュー。好みで選ぶ楽しさがある。" },
      { type: "heading", content: "冬の山梨旅でほうとうを一番おいしく食べる方法", level: 2 },
      { type: "text", content: "ほうとうが最もおいしいのは寒い日の昼食。外を歩いて体が冷えた状態で熱々の土鍋を受け取る時、ほうとうの本質がわかる。河口湖か昇仙峡の観光を午前中にこなし、正午前に入店するのが行列を避けるコツ。量が多いので1人1鍋で十分。" },
    ],
    relatedArticleSlugs: ["yamanashi-fujigoko-model-course", "yamanashi-fruit-picking-guide"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "yamanashi-fruit-picking-guide",
    title: "山梨フルーツ狩り完全ガイド──桃・ぶどう・さくらんぼ、季節別の楽しみ方",
    description: "日本一の果物県・山梨。何を、どこで、いつ食べるかで体験の質が大きく変わる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-07-01",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "yamanashi",
    tags: ["フルーツ狩り", "桃", "ぶどう", "山梨", "家族旅"],
    spotIds: [],
    sections: [
      { type: "heading", content: "6月：さくらんぼ狩りは短期決戦", level: 2 },
      { type: "text", content: "山梨のさくらんぼ狩りは6月上旬〜中旬のわずか2週間。甲州市・笛吹市周辺に農園が集中する。60分食べ放題で1,800〜2,500円が相場。予約なしで当日訪問できる農園も多いが、週末は9時で満員になることも。" },
      { type: "heading", content: "7〜8月：桃は山梨でしか食べられない密度がある", level: 2 },
      { type: "text", content: "笛吹市・甲州市・山梨市の桃は、日本全体の生産量の約3割を占める。農園での食べ放題は45分1,700円前後。熟した桃は輸送に耐えられないため、産地でしか食べられない。夕方に農園直売所で買う完熟桃（1箱2,000〜3,000円）を宿に持ち込むのも正解。" },
      { type: "heading", content: "9〜10月：ぶどうは品種を食べ比べる", level: 2 },
      { type: "text", content: "山梨のぶどうは甲州・シャインマスカット・ピオーネなど品種が豊富。甲州市勝沼の農園では品種別に食べ比べができる施設もある。ワインの原料となる甲州ぶどうは皮ごと食べられ、独特のさっぱりした甘さがある。近隣のワイナリー見学と組み合わせると山梨のぶどう文化の全体像がわかる。" },
    ],
    relatedArticleSlugs: ["yamanashi-hoto-gourmet", "yamanashi-fujigoko-model-course"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "yamanashi-takeda-shrine-history",
    title: "武田神社と甲府城──戦国武田氏の足跡を歩く半日コース",
    description: "風林火山の旗の下に戦った武田信玄。その居城跡と守護神社を巡る、歴史好きのための甲府。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-04-14",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "yamanashi",
    tags: ["武田神社", "甲府城", "歴史", "武田信玄", "山梨"],
    spotIds: [],
    sections: [
      { type: "heading", content: "武田神社は「躑躅ヶ崎館」跡に建つ", level: 2 },
      { type: "text", content: "武田神社は武田信玄が居館を構えた躑躅ヶ崎館跡に明治時代に創建された神社。甲府駅から徒歩20分または北口からバスで10分。境内には武田24将の彫刻や武田氏の家紋「武田菱」があしらわれた燈籠が並ぶ。宝物殿（300円）には信玄ゆかりの品々が展示される。" },
      { type: "heading", content: "甲府城（舞鶴城）で石垣の美学を見る", level: 2 },
      { type: "text", content: "甲府城は豊臣秀吉が甲斐支配のために築いた城で、江戸時代は徳川の重要拠点となった。甲府駅からすぐ、無料で入れる石垣と天守台が残り、最上部からは甲府盆地と富士山が見渡せる。隣接する甲府市歴史公園の無料展示室では甲斐国の歴史がわかりやすく解説されている。" },
      { type: "heading", content: "昼食はB級グルメの鳥もつ煮で締める", level: 2 },
      { type: "text", content: "甲府のB級グルメ「鳥もつ煮」は、鶏のモツをタレで炒め煮にした甘辛の一品。小料理屋「奥藤本店」の鳥もつ煮（450円）が元祖とされる。B-1グランプリ優勝経験もある郷土料理で、観光客よりも地元の人が日常的に食べている庶民の味。" },
    ],
    relatedArticleSlugs: ["yamanashi-shosenkyo-autumn", "yamanashi-hoto-gourmet"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "yamanashi-solo-fujigoko",
    title: "一人で行く富士五湖──早起きだけが知っている、静かな湖畔の朝",
    description: "団体バスが来る前の富士五湖は別世界。一人旅こそ早朝の湖畔に立つべき理由。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "yamanashi",
    tags: ["一人旅", "富士五湖", "早朝", "富士山", "山梨"],
    spotIds: ["fuji-goko"],
    sections: [
      { type: "heading", content: "観光バスが来る前の1時間が勝負", level: 2 },
      { type: "text", content: "河口湖の観光バスが到着するのは9時台以降。逆算すると7時〜8時台は湖畔がほぼ無人になる。この1時間、富士山を独り占めできる確率が高い。河口湖インターチェンジから車で10分の湖北ビューラインがプライベート感の高い撮影スポット。" },
      { type: "spot-card", content: "fuji-goko" },
      { type: "heading", content: "西湖・精進湖は観光客が少ない", level: 2 },
      { type: "text", content: "五湖の中で西湖と精進湖は観光開発が少なく静か。精進湖は最も小さい湖で、北岸から富士山と湖面が構図よく入る。西湖の「いやしの里根場」（350円）は茅葺き集落が復元されており、富士山を背景に江戸時代の農村景観が体験できる。" },
      { type: "heading", content: "宿は河口湖駅周辺のゲストハウスで十分", level: 2 },
      { type: "text", content: "一人旅なら河口湖駅から徒歩圏のゲストハウス（2,500〜4,000円）が最もコスパが高い。チェックインが遅い時間でも対応してくれる宿が多く、翌朝の早起きに向けて荷物を最小化できる環境が整っている。観光名所は自転車レンタル（1日1,500円）で十分に回れる範囲にある。" },
    ],
    relatedArticleSlugs: ["yamanashi-hottarakashi-onsen-dawn", "yamanashi-fujigoko-model-course"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "yamanashi-budget-onedaytour",
    title: "山梨日帰り節約旅──3,000円で富士山と温泉とほうとうを全部やる",
    description: "新宿から特急で約90分。費用を抑えながら山梨の核心を全部経験する、1日の設計図。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-12",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "yamanashi",
    tags: ["節約旅", "日帰り", "山梨", "バジェット", "富士山"],
    spotIds: ["fuji-goko", "hottarakashi-onsen"],
    sections: [
      { type: "heading", content: "交通費を抑える：高速バスが最安手段", level: 2 },
      { type: "text", content: "新宿から河口湖行きの高速バスは片道1,750円。往復3,500円で、JRより大幅に安い。早朝7時発のバスなら9時前に河口湖に着ける。バス車内から富士山が見えることもある。" },
      { type: "heading", content: "昼食は道の駅で800円以内", level: 2 },
      { type: "text", content: "道の駅なるさわ（富士五湖周辺）のフードコートでほうとうが1,000円以下で食べられる。農産物直売コーナーでは山梨の桃・ぶどうが市価より安く、旬の季節ならフルーツを買って湖畔で食べるのが最高のランチ。" },
      { type: "heading", content: "温泉は銭湯価格の「富士眺望の湯ゆらり」", level: 2 },
      { type: "text", content: "本栖湖周辺の「富士眺望の湯ゆらり」は日帰り入浴1,500円。高台の露天風呂から富士山が正面に見える。夕方割引（17時以降）で1,000円になる。ほったらかし温泉（900円）と比べてアクセスしやすく、バス停から近い点が節約旅向き。" },
    ],
    relatedArticleSlugs: ["yamanashi-hoto-gourmet", "yamanashi-fujigoko-model-course"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "yamanashi-couple-wine-tour",
    title: "カップルで行く甲州ワイナリー巡り──勝沼の丘で飲む一杯の価値",
    description: "ぶどう畑の中でグラスを傾ける。日本ワインの産地・山梨で、二人だけの時間を作る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-05",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "yamanashi",
    tags: ["ワイン", "カップル", "勝沼", "ぶどう", "山梨"],
    spotIds: [],
    sections: [
      { type: "heading", content: "勝沼ぶどう郷駅が出発点", level: 2 },
      { type: "text", content: "JR中央本線の勝沼ぶどう郷駅を降りると、目の前にぶどう畑が広がる。ここから徒歩圏内に10軒以上のワイナリーが点在する。ぶどうの収穫期（9〜10月）は見学ツアーの予約が取りにくいが、その分畑の景色が最も豊か。" },
      { type: "heading", content: "シャトー勝沼で午前の試飲から始める", level: 2 },
      { type: "text", content: "シャトー勝沼は国内最大規模のワイナリーで、無料の工場見学と有料試飲（500円〜）が楽しめる。甲州種（白）は軽い渋みとミネラル感が特徴で、日本食との相性が抜群。試飲後に気に入ったワインを購入できる。" },
      { type: "heading", content: "夕食はワイナリーレストランで完結", level: 2 },
      { type: "text", content: "いくつかのワイナリーはレストランを併設しており、ぶどう畑を眺めながら地元野菜と山梨産ワインのコースが楽しめる。「ドメーヌQ」のランチコース（3,500円〜）は眺望が良く、ウェディングに使われるほど雰囲気が良い。二人でシェアして4,000〜5,000円で収まる。" },
    ],
    relatedArticleSlugs: ["yamanashi-fruit-picking-guide", "yamanashi-solo-fujigoko"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "yamanashi-shosenkyo-crystal",
    title: "昇仙峡の宝石──水晶の産地で本物の石を選ぶ",
    description: "昇仙峡の山頂エリアは水晶・宝石の店が立ち並ぶ独自の世界。旅の土産の選び方を変える。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-06-22",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "yamanashi",
    tags: ["昇仙峡", "水晶", "宝石", "土産", "山梨"],
    spotIds: ["shosenkyo"],
    sections: [
      { type: "heading", content: "山梨は日本一の宝石加工産地", level: 2 },
      { type: "text", content: "山梨県は日本最大の宝飾品加工産地で、特に甲府市は「宝石のまち」として全国の宝石卸の中心を担う。昇仙峡は古くから水晶の産地で、ロープウェイを降りた山頂エリアには原石から加工品まで扱う専門店が集まる。" },
      { type: "spot-card", content: "shosenkyo" },
      { type: "heading", content: "本物の水晶の見分け方", level: 2 },
      { type: "text", content: "天然水晶は人工ガラスより重く冷たい。同じサイズで比較すると重量の違いがわかる。昇仙峡山頂の老舗「山の工芸堂」では産地証明付きの山梨産水晶を扱う。3,000円前後から質の高い原石が購入できる。" },
      { type: "heading", content: "甲府市内の宝石博物館も立ち寄る価値がある", level: 2 },
      { type: "text", content: "甲府市内の「山梨宝石博物館」（入館無料）は世界中の鉱物・宝石を展示する。市内には宝石加工の工場見学ができる施設もあり、半日かけると山梨の宝石文化が丸ごとわかる。昇仙峡と合わせた1泊2日プランに最適。" },
    ],
    relatedArticleSlugs: ["yamanashi-shosenkyo-autumn", "yamanashi-budget-onedaytour"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "yamanashi-fujisan-west-side",
    title: "富士山の静岡・山梨側の違い──北麓から眺める富士山の特別な理由",
    description: "富士山は見る方向で別の山になる。山梨側（北麓）が「富士山の顔」とされる、地形的な理由。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-04-30",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "yamanashi",
    tags: ["富士山", "山梨", "写真", "絶景", "ガイド"],
    spotIds: ["fuji-goko"],
    sections: [
      { type: "heading", content: "北麓（山梨側）が「正面」とされる理由", level: 2 },
      { type: "text", content: "千円札・1,000円硬貨・富士山の絵画の多くは北麓からの構図を使っている。富士五湖を前景にした山梨側の眺めが「富士山の顔」として定着した理由は、南北方向から見たときに宝永火口が正面に来ないことと、湖との距離感が絵になる点にある。" },
      { type: "spot-card", content: "fuji-goko" },
      { type: "heading", content: "逆さ富士が成立する条件", level: 2 },
      { type: "text", content: "本栖湖・河口湖で逆さ富士が撮れる条件は、風のない早朝と、視線の高さを湖面に近づけること。三脚で地面スレスレまでカメラを下げると、湖面の映り込みと富士山が一枚に入る。風速2m以上で水面が波立つため、無風の朝5時〜6時台がゴールデンタイム。" },
      { type: "heading", content: "富士吉田の溶岩樹型（天然記念物）も訪ねる", level: 2 },
      { type: "text", content: "富士吉田市にある「吉田口溶岩樹型」は溶岩が木を包んで固まった穴が残る天然記念物。富士山噴火の生々しい痕跡で、観光客がほとんど来ない穴場。入場無料で24時間アクセス可能。富士五湖観光と組み合わせると、富士山を立体的に理解できる。" },
    ],
    relatedArticleSlugs: ["yamanashi-fujigoko-model-course", "yamanashi-solo-fujigoko"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "yamanashi-winter-illumination",
    title: "山梨の冬イルミネーション──富士五湖周辺で光る夜を歩く",
    description: "冬の富士五湖には夜がある。光の中に富士山のシルエットが浮かぶ、12月の夜旅。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "yamanashi",
    tags: ["冬", "イルミネーション", "富士五湖", "夜景", "山梨"],
    spotIds: ["fuji-goko"],
    sections: [
      { type: "heading", content: "河口湖ハーブフェスティバルの冬バージョン", level: 2 },
      { type: "text", content: "河口湖ミューズ館周辺では冬のイルミネーションイベント「光の花の庭」が11月〜3月に開催される。入場料500円。富士山をバックに光の花が広がる構図は、山梨でしか撮れない冬のポートレート。" },
      { type: "spot-card", content: "fuji-goko" },
      { type: "heading", content: "山中湖のイルミネーション「キラリン湖」", level: 2 },
      { type: "text", content: "山中湖畔では毎年11月〜3月にイルミネーションイベントが開催される。湖面に映る光と富士山のシルエットが重なる場所は、撮影ポイントとして有名。気温は零下になるので、防寒装備は必須。カイロを貼って2時間でも全身が冷える冬の湖畔。" },
      { type: "heading", content: "忍野八海の雪景色と組み合わせる", level: 2 },
      { type: "text", content: "忍野八海（山中湖近く）は富士山の雪解け水が湧き出す泉が8か所点在する。入場無料。冬は周囲が雪景色になり、澄んだ青い水と白い雪のコントラストが美しい。夕方の光が弱くなる時間帯が最も幻想的で、日中の観光客が帰った後の静けさも魅力。" },
    ],
    relatedArticleSlugs: ["yamanashi-fujigoko-model-course", "yamanashi-hottarakashi-onsen-dawn"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "yamanashi-luxury-villa-stay",
    title: "山梨で泊まる贅沢──富士山を独り占めする高原ヴィラの選び方",
    description: "富士山を眺めながら過ごす一夜。山梨の高級旅館・ヴィラで経験できる、特別な静寂。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-08-15",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "yamanashi",
    tags: ["贅沢旅", "高級旅館", "富士山", "山梨", "ヴィラ"],
    spotIds: ["fuji-goko", "hottarakashi-onsen"],
    sections: [
      { type: "heading", content: "「界 富士」：星野リゾートの富士山温泉旅館", level: 2 },
      { type: "text", content: "山中湖近くの「界 富士」は富士山を望む露天風呂付き客室が売り。1泊2食付き1人45,000円〜。夕食の甲州牛と富士山が一枚の絵に収まる食事処は、記念旅行に使われることが多い。11月は紅葉と富士山の組み合わせで予約が最も困難。" },
      { type: "heading", content: "河口湖畔の隠れ宿「湖月」", level: 2 },
      { type: "text", content: "河口湖の湖畔に建つ全室湖側客室の旅館「湖月」は1泊2食25,000円前後。客室の窓から富士山と河口湖が同時に見える立地で、部屋に露天風呂が付いた客室は特に人気が高い。夕食は地元食材を使った会席料理で、ほうとうが小鍋で一品出る。" },
      { type: "heading", content: "ほったらかし温泉付近のグランピング", level: 2 },
      { type: "text", content: "山梨市周辺にはほったらかし温泉と組み合わせられるグランピング施設が増えている。テント内にベッドと暖房が完備された施設は1泊2食35,000〜45,000円。夜の甲府盆地の夜景と朝の富士山を一続きで体験できる、ほったらかし温泉の日の出入浴とセットにするプランが最もコスパが高い。" },
    ],
    relatedArticleSlugs: ["yamanashi-hottarakashi-onsen-dawn", "yamanashi-couple-wine-tour"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "yamanashi-kids-adventure",
    title: "子連れ山梨──富士急ハイランドだけじゃない、子どもが喜ぶ山梨全部入り",
    description: "富士急はもちろん。フルーツ狩り・忍野八海・水族館、子どもが飽きない山梨の使い方。",
    coverImage: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1200&q=80",
    publishedAt: "2025-07-22",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "yamanashi",
    tags: ["子連れ", "家族旅", "富士急", "山梨", "フルーツ"],
    spotIds: ["fuji-goko"],
    sections: [
      { type: "heading", content: "富士急ハイランドは1日で十分", level: 2 },
      { type: "text", content: "富士急ハイランドは入場無料・乗り物課金制（各800〜2,200円）か1日フリーパス（大人7,400円）を選べる。小学生以下の子どもはアトラクションより「トーマスランド」エリアが人気。9時開園と同時に入ると午前中でほぼ全て回れる。" },
      { type: "spot-card", content: "fuji-goko" },
      { type: "heading", content: "忍野八海で水の不思議を体験", level: 2 },
      { type: "text", content: "忍野八海は透明度の高い湧き水の池が8か所。巨大なニジマスが泳ぐ池は子どもに人気で、餌やり体験（100円）もできる。入場無料で手ぶらで行けるので、富士急の翌日に立ち寄るサブスポットに最適。" },
      { type: "heading", content: "フルーツ狩りは体験型の農業教育にもなる", level: 2 },
      { type: "text", content: "笛吹市の「石和温泉フルーツ公園」や甲州市の農園では、子どもが自分でもいで食べるフルーツ狩りが体験できる。ぶどう・桃・さくらんぼと季節によって異なるため、繰り返し訪れる動機になる。農家の人との会話が、食べ物の産地を実感するきっかけになる。" },
    ],
    relatedArticleSlugs: ["yamanashi-fruit-picking-guide", "yamanashi-fujigoko-model-course"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "yamanashi-shosenkyo-rope-way",
    title: "昇仙峡ロープウェイ完全攻略──山頂展望台からの360度パノラマと水晶市場",
    description: "渓谷の遊歩道だけでは昇仙峡の半分しか見ていない。ロープウェイで上がる山頂エリアの全部。",
    coverImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200&q=80",
    publishedAt: "2025-05-10",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "yamanashi",
    tags: ["昇仙峡", "ロープウェイ", "展望台", "水晶", "山梨"],
    spotIds: ["shosenkyo"],
    sections: [
      { type: "heading", content: "ロープウェイは仙娥滝の上にある", level: 2 },
      { type: "text", content: "昇仙峡ロープウェイ（往復1,000円）の乗り場は仙娥滝の上流側にある。下から歩いて遊歩道を進んだ後、滝を見てそのままロープウェイ乗り場へ上がるのが自然な動線。所要4分で標高差300mを移動する。" },
      { type: "spot-card", content: "shosenkyo" },
      { type: "heading", content: "山頂・羅漢寺山展望台からの眺め", level: 2 },
      { type: "text", content: "ロープウェイを降りると羅漢寺山（標高1058m）山頂の展望台がある。晴れた日は富士山・八ヶ岳・南アルプスが同時に見渡せる360度パノラマ。昇仙峡の渓谷を真上から見下ろせる方向もあり、遊歩道から見た景色とまったく違う表情がある。" },
      { type: "heading", content: "山頂エリアの水晶・宝石店を楽しむ", level: 2 },
      { type: "text", content: "山頂エリアには水晶・宝石を扱う店が10軒以上並ぶ。観光地価格のものもあるが、目利きすれば良質な山梨産水晶を適正価格で購入できる。「山梨県産」の表示があるものを選ぶのが基本。数百円の小さな原石から数万円の加工品まで予算に応じて選べる。" },
    ],
    relatedArticleSlugs: ["yamanashi-shosenkyo-autumn", "yamanashi-shosenkyo-crystal"],
  },
];
