import { Article } from "@/types/article";

export const yamagataArticles: Article[] = [
  // ── 1 ──────────────────────────────────────
  {
    slug: "yamagata-zao-onsen-winter",
    title: "蔵王温泉のスキーとスノーモンスター──山形の冬が作る氷の巨人を見に行く",
    description: "モンスターと呼ばれる樹氷は1月〜2月に蔵王山頂付近に出現する。温泉と雪山の完璧な組み合わせ。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-01-15",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "yamagata",
    tags: ["蔵王温泉", "樹氷", "スノーモンスター", "スキー", "冬"],
    spotIds: ["zao-onsen"],
    sections: [
      { type: "heading", content: "樹氷はなぜ「モンスター」と呼ばれるか", level: 2 },
      { type: "text", content: "蔵王の樹氷はアオモリトドマツに水滴が凍りつき、風で造形されることで生まれる。高さ2〜3mに達する氷の塊は人間の顔や動物に見えることがあり、「スノーモンスター」の愛称で知られる。この現象は気温・湿度・風向きの条件が整う蔵王でしか見られない。" },
      { type: "spot-card", content: "zao-onsen" },
      { type: "heading", content: "樹氷ロープウェイで山頂へ", level: 2 },
      { type: "text", content: "蔵王温泉スキー場の樹氷ロープウェイは山麓から山頂駅（標高1,661m）まで3段で上る。往復2,800円。山頂付近は風が強くマイナス15度になることもあるため、防寒対策は完全武装が必須だ。晴天の午前中が樹氷の輝きが最も美しい時間帯で、空の青さと白のコントラストが圧倒的だ。" },
      { type: "heading", content: "蔵王温泉の硫黄泉で温まる", level: 2 },
      { type: "text", content: "蔵王温泉は強酸性の硫黄泉で、スキー後の筋肉疲労回復に極めて効果的だ。温泉街の共同浴場（上湯・川原湯・下湯）は入浴料200円前後と格安で、地元の方も利用する昔ながらの雰囲気がある。硫黄の香りが衣服につくほど濃い泉質は、蔵王温泉の個性だ。" },
    ],
    relatedArticleSlugs: ["yamagata-zao-summer-crater", "yamagata-ginzan-onsen-snow"],
  },
  // ── 2 ──────────────────────────────────────
  {
    slug: "yamagata-ginzan-onsen-snow",
    title: "銀山温泉の雪景色──大正ロマン建築と灯籠が照らす東北の奇跡の夜",
    description: "大正時代の多層建築が雪に覆われ、灯籠に照らされる銀山温泉は日本で最も美しい温泉街だ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-02-10",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "yamagata",
    tags: ["銀山温泉", "大正ロマン", "雪景色", "夜景", "温泉街"],
    spotIds: ["ginzan-onsen"],
    sections: [
      { type: "heading", content: "銀山温泉の誕生──鉱山跡地に湧いた湯", level: 2 },
      { type: "text", content: "江戸時代初期に銀鉱山として栄えた延沢銀山が廃坑になった後、鉱山跡地から温泉が湧き出した。昭和初期に建てられた大正ロマン様式の旅館が銀山川沿いに並ぶ現在の景観は、NHKドラマのロケ地にもなり、海外からの観光客も多く訪れる。" },
      { type: "spot-card", content: "ginzan-onsen" },
      { type: "heading", content: "日帰り入浴の制限──宿泊してこそ価値が高まる", level: 2 },
      { type: "text", content: "銀山温泉は狭い温泉街の保護のため、一部の宿では日帰り入浴を制限している。できれば1泊してガス燈が灯る夕刻から翌朝の人のいない朝まで、時間帯による表情の変化を体験してほしい。宿泊予約は繁忙期（冬・秋）は3〜6ヶ月前が必要だ。" },
      { type: "heading", content: "朝の温泉街散策──人が来る前の静寂", level: 2 },
      { type: "text", content: "早朝6時頃の銀山温泉は日帰り観光客がまだ来ておらず、宿泊者だけの静寂がある。雪があれば新雪に宿泊者の足跡だけが残り、川の音と温泉の湯気だけが包む空間になる。この時間の撮影が最高の一枚を生む。" },
    ],
    relatedArticleSlugs: ["yamagata-zao-onsen-winter", "yamagata-ginzan-onsen-summer"],
  },
  // ── 3 ──────────────────────────────────────
  {
    slug: "yamagata-yamadera-pilgrim",
    title: "山寺（立石寺）──1,015段の石段を登る先に待つ、芭蕉が詠んだ絶景",
    description: "「閑さや 岩にしみ入る 蝉の声」。松尾芭蕉が残した句が今も現実として体験できる場所。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-05-25",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "yamagata",
    tags: ["山寺", "立石寺", "松尾芭蕉", "石段", "歴史"],
    spotIds: ["yamadera"],
    sections: [
      { type: "heading", content: "1,015段の石段──登るべき理由と覚悟", level: 2 },
      { type: "text", content: "山寺の石段は根本中堂から奥の院まで1,015段。急勾配の箇所もあるが、健脚でなくても1時間程度で登れる。石段の脇に歴代の高僧の墓碑が並び、1,000年の歴史の重みが足元から伝わってくる。登り始めは「きつい」、頂上で「来てよかった」と全員が感じる。" },
      { type: "spot-card", content: "yamadera" },
      { type: "heading", content: "開山堂と五大堂──頂上の絶景", level: 2 },
      { type: "text", content: "石段の最上部に立つ開山堂は岩壁に張り付くように建つ赤い建物で、山形盆地と最上川が一望できる。五大堂の展望台からの眺めは、芭蕉が詠んだ「静けさ」が今も現実に存在することを証明している。眼下の緑の山々と白い雲のコントラストは、山形の夏を象徴する風景だ。" },
      { type: "heading", content: "山寺駅の立地──電車でのアクセスが理想的", level: 2 },
      { type: "text", content: "JR仙山線の山寺駅は立石寺の参道入口から徒歩5分と理想的な立地だ。仙台から1時間、山形から30分でアクセスできる。駅前の茶屋では山形名物の「力こんにゃく」（100円）や「芋煮汁」が食べられ、登山前の腹ごしらえに最適だ。" },
    ],
    relatedArticleSlugs: ["yamagata-dewa-sanzan-pilgrim", "yamagata-summer-cherry"],
  },
  // ── 4 ──────────────────────────────────────
  {
    slug: "yamagata-dewa-sanzan-pilgrim",
    title: "出羽三山巡礼──羽黒山・月山・湯殿山を歩く山伏の修行路",
    description: "生まれ変わりの旅。山形が誇る1,400年の修験道の聖地を、現代人が歩く意味とは。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-06-20",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "yamagata",
    tags: ["出羽三山", "修験道", "羽黒山", "月山", "巡礼"],
    spotIds: ["dewa-sanzan"],
    sections: [
      { type: "heading", content: "出羽三山の意味──過去・現在・未来の山", level: 2 },
      { type: "text", content: "羽黒山（現世利益）・月山（死後の世界）・湯殿山（生まれ変わり）の三山は、修験道において「死と再生」の旅を体験する場だ。江戸時代には庶民の「一生に一度の旅」として年間数十万人が訪れた記録がある。現代でも山伏の修行（研修会）が年間を通じて行われている。" },
      { type: "spot-card", content: "dewa-sanzan" },
      { type: "heading", content: "羽黒山五重塔──森の中に佇む国宝", level: 2 },
      { type: "text", content: "羽黒山への参道にある五重塔（国宝）は14世紀の建立で、東北最古の塔建築だ。杉の巨木に囲まれた薄暗い参道の中に突然現れる朱塗りの塔は、宗教建築の力を全身で感じさせる。参道の2,446段の石段も有名で、全部歩くと1時間半かかる。" },
      { type: "heading", content: "月山の夏山登山──残雪と高山植物", level: 2 },
      { type: "text", content: "月山（1,984m）は7〜8月でも残雪が残り、雪解け後に高山植物が一斉に咲く「花の山」だ。八合目からの登山（往復約5時間）は体力が必要だが、山頂の月山神社と360度の眺望は登山の報酬として充分すぎる。山開きは例年7月1日。" },
    ],
    relatedArticleSlugs: ["yamagata-yamadera-pilgrim", "yamagata-zao-onsen-winter"],
  },
  // ── 5 ──────────────────────────────────────
  {
    slug: "yamagata-summer-cherry",
    title: "山形のさくらんぼ狩り──日本一の産地で食べ放題、品種と旬の完全解説",
    description: "佐藤錦・紅秀峰・山形美人。山形のさくらんぼは品種ごとに全く味が異なる。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-06-01",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "yamagata",
    tags: ["さくらんぼ", "山形名物", "果物狩り", "食べ放題", "夏"],
    spotIds: ["yamadera"],
    sections: [
      { type: "heading", content: "山形がさくらんぼ王国になった理由", level: 2 },
      { type: "text", content: "山形県は全国のさくらんぼ生産量の約75%を占める。内陸盆地の昼夜の寒暖差と、梅雨時期に比較的雨が少ない山形の気候がさくらんぼ栽培に最適だ。明治初期にアメリカから導入された品種を地元農家が改良を重ね、「佐藤錦」などの山形独自品種が生まれた。" },
      { type: "heading", content: "佐藤錦・紅秀峰・山形美人の違い", level: 2 },
      { type: "text", content: "佐藤錦（6月中旬〜下旬）は甘みと酸味のバランスが取れた王道品種。紅秀峰（7月上旬）は糖度が高く濃厚な味わいで高値がつく。山形美人（6月下旬〜7月上旬）は大粒でジューシーな後発品種だ。農園によって取り扱い品種が異なるので予約時に確認する。" },
      { type: "heading", content: "観光農園の選び方と予約のコツ", level: 2 },
      { type: "text", content: "東根市・天童市・寒河江市エリアに観光農園が集中する。食べ放題30分（1,500〜2,500円）が標準的だ。雨除けのビニールハウス付き農園を選ぶと、天候に関わらず確実に体験できる。週末は1ヶ月前から予約が埋まるため、行き先が決まったらすぐに問い合わせること。" },
    ],
    relatedArticleSlugs: ["yamagata-yonezawa-beef-guide", "yamagata-yamadera-pilgrim"],
  },
  // ── 6 ──────────────────────────────────────
  {
    slug: "yamagata-yonezawa-beef-guide",
    title: "米沢牛を米沢で食べる──三大和牛のひとつを産地で食べる価格と店選び",
    description: "松阪牛・神戸牛と並ぶ米沢牛は、山形の山間の城下町・米沢でこそ本当の価値がわかる。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-10",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "yamagata",
    tags: ["米沢牛", "三大和牛", "グルメ", "米沢", "ステーキ"],
    spotIds: ["yamadera"],
    sections: [
      { type: "heading", content: "米沢牛の定義──厳格な血統と育成条件", level: 2 },
      { type: "text", content: "米沢牛は米沢市を中心とした山形県南部で生まれ育った黒毛和牛の中でも、定められた格付け基準（A4〜A5等級）を満たしたものだけが名乗れる。生産農家が少なく希少性が高いため、産地外での入手は高価かつ品質がばらつくことがある。" },
      { type: "heading", content: "米沢駅周辺の専門店で食べる", level: 2 },
      { type: "text", content: "米沢駅前には「牛鍋よし亭」「登起波牛肉店」など老舗の米沢牛専門店が並ぶ。しゃぶしゃぶコース（1人5,000〜8,000円）は薄切り肉の赤みと脂のバランスが際立ち、産地ならではの鮮度を体感できる。ステーキは100gで3,000〜6,000円が相場だ。" },
      { type: "heading", content: "米沢の城下町文化と合わせる", level: 2 },
      { type: "text", content: "米沢は上杉鷹山で知られる上杉藩の城下町だ。上杉神社（米沢城跡）や稽照殿（武具・甲冑の宝物館）を午前中に訪れ、昼食に米沢牛を食べるという流れが充実度の高い米沢旅だ。新幹線つばさで東京から約2時間20分でアクセスできる。" },
    ],
    relatedArticleSlugs: ["yamagata-summer-cherry", "yamagata-yamadera-pilgrim"],
  },
  // ── 7 ──────────────────────────────────────
  {
    slug: "yamagata-ginzan-onsen-summer",
    title: "銀山温泉の夏──新緑と大正建築の涼しい渓谷、人が減る狙い目シーズン",
    description: "冬の雪景色で有名な銀山温泉だが、夏は緑が映え、混雑が少ない穴場の時期だ。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-07-20",
    author: "旅のしおり屋さん編集部",
    category: "onsen",
    prefectureId: "yamagata",
    tags: ["銀山温泉", "夏", "新緑", "温泉", "大正ロマン"],
    spotIds: ["ginzan-onsen"],
    sections: [
      { type: "heading", content: "夏の銀山──観光客が減る穴場シーズン", level: 2 },
      { type: "text", content: "銀山温泉は冬（12〜3月）と秋（10〜11月）が最も混む時期だ。7〜8月は猛暑の都市から逃れる避暑客が訪れるが、冬と比べると宿の予約が取りやすい。渓谷の涼しさと銀山川の清流音、新緑に包まれた大正建築の佇まいは、夏ならではの美しさがある。" },
      { type: "heading", content: "銀山川の清流と延沢銀山跡", level: 2 },
      { type: "text", content: "温泉街の奥に延沢銀山の採掘坑跡が残っている。涼しいトンネル状の坑道入口まで徒歩で行けるミニハイキングコースがあり、夏の運動不足解消にちょうどよい。銀山川では7月下旬〜8月にホタルが飛び、宿からの鑑賞ツアーを企画する旅館もある。" },
      { type: "heading", content: "大銀杏と紅花──山形の花を見る", level: 2 },
      { type: "text", content: "銀山温泉周辺の尾花沢市は江戸時代に紅花の産地として繁栄した地域だ。7月上旬〜中旬には紅花畑が黄色い花を咲かせ、銀山温泉とセットで訪れる価値がある。紅花染めの体験施設も複数あり、手ぬぐいや風呂敷を自分で染める体験ができる。" },
    ],
    relatedArticleSlugs: ["yamagata-ginzan-onsen-snow", "yamagata-zao-onsen-winter"],
  },
  // ── 8 ──────────────────────────────────────
  {
    slug: "yamagata-zao-summer-crater",
    title: "蔵王お釜──神秘のエメラルドグリーンのカルデラ湖、夏の蔵王を歩く",
    description: "五色沼とも呼ばれる蔵王のお釜は、天候と時間帯で色が変わる自然の謎だ。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-08-10",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "yamagata",
    tags: ["蔵王", "お釜", "カルデラ湖", "夏", "絶景"],
    spotIds: ["zao-onsen"],
    sections: [
      { type: "heading", content: "お釜の色が変わる科学的理由", level: 2 },
      { type: "text", content: "蔵王お釜は活火山のカルデラ湖で、強酸性の湖水（pH3.5前後）の成分が空の色と太陽光の角度によって見る色が変化する。晴天の正午は鮮やかなエメラルドグリーン、曇りの日は深い灰緑色に見える。霧に包まれた日でも湖面が見える瞬間は幻想的だ。" },
      { type: "spot-card", content: "zao-onsen" },
      { type: "heading", content: "蔵王エコーライン──ドライブと眺望", level: 2 },
      { type: "text", content: "お釜へのアクセスは蔵王エコーライン（有料道路）を走り、刈田駐車場（標高1,730m）から徒歩5分でお釜展望台に到達できる。6月中旬に開通し10月下旬に閉鎖される。レンタカーが最も自由度が高いが、山形・宮城両側からバスツアーも運行されている。" },
      { type: "heading", content: "蔵王温泉での宿泊と蔵王の二面性", level: 2 },
      { type: "text", content: "夏のお釜観光と冬の樹氷・スキーを両方体験するには、蔵王温泉に宿泊するのが効率的だ。同じ蔵王山が夏と冬で全く異なる景観を見せることに、山形の気候の振れ幅が凝縮されている。温泉街の宿は夏・冬ともに混むため、いずれにせよ早めの予約が必須だ。" },
    ],
    relatedArticleSlugs: ["yamagata-zao-onsen-winter", "yamagata-dewa-sanzan-pilgrim"],
  },
  // ── 9 ──────────────────────────────────────
  {
    slug: "yamagata-couple-trip",
    title: "山形カップル旅行──銀山温泉×蔵王×山寺の2泊3日究極プラン",
    description: "大正ロマンの温泉、芭蕉の俳句の地、神秘の火口湖。山形の三大名所を二人で巡る。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-10-01",
    author: "旅のしおり屋さん編集部",
    category: "couple",
    prefectureId: "yamagata",
    tags: ["カップル", "山形", "2泊3日", "銀山温泉", "蔵王"],
    spotIds: ["ginzan-onsen", "zao-onsen", "yamadera"],
    sections: [
      { type: "heading", content: "1日目：山形駅着→山寺登山→山形市泊", level: 2 },
      { type: "text", content: "新幹線つばさで山形駅到着後、仙山線で山寺へ移動（30分）。1,015段を二人で登り、芭蕉の句碑で写真を撮る。帰りに山形市内の老舗「香味庵まるごと山形館」でだし文化を味わいながら夕食。山形市内に宿泊し翌日の移動に備える。" },
      { type: "heading", content: "2日目：蔵王お釜から銀山温泉へ", level: 2 },
      { type: "text", content: "レンタカーで蔵王エコーラインを走り、お釜の展望台へ（約1時間）。お釜を眺めた後、山形側の蔵王温泉で昼食（温泉ラーメンが名物）。午後に銀山温泉へ移動（約2時間）し、チェックイン後は温泉街の夕暮れ〜ガス燈点灯の時間をゆっくり二人で歩く。" },
      { type: "heading", content: "3日目：銀山温泉の朝散策から帰路", level: 2 },
      { type: "text", content: "早朝6時の銀山温泉は日帰り客がおらず、宿泊者の特権タイムだ。川沿いを二人で散策し、朝食後に出発。新庄駅から新幹線で帰路につく（山形新幹線つばさは銀山温泉最寄りの大石田駅から乗車可能）。帰りの車内で購入するさくらんぼジュースが旅の余韻を延ばしてくれる。" },
    ],
    relatedArticleSlugs: ["yamagata-ginzan-onsen-snow", "yamagata-yamadera-pilgrim"],
  },
  // ── 10 ──────────────────────────────────────
  {
    slug: "yamagata-family-trip-plan",
    title: "山形ファミリー旅行──さくらんぼ狩り・山寺・温泉の子連れ完全プラン",
    description: "子どもが主役の山形旅。さくらんぼを食べ放題して、芭蕉の山に挑戦する2泊3日。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-06-25",
    author: "旅のしおり屋さん編集部",
    category: "family",
    prefectureId: "yamagata",
    tags: ["ファミリー", "子連れ", "さくらんぼ", "山形", "2泊3日"],
    spotIds: ["yamadera", "zao-onsen"],
    sections: [
      { type: "heading", content: "1日目：さくらんぼ狩りで始まる山形旅", level: 2 },
      { type: "text", content: "東根市・天童市の観光農園でさくらんぼ食べ放題体験（6月中旬〜7月）。子どもは1,500円前後で食べ放題30分。農園によっては収穫作業の体験もできる。昼食に山形名物の冷やしラーメン（山形市発祥）を食べてから天童市内の宿へ。" },
      { type: "heading", content: "2日目：山寺に子どもと挑戦", level: 2 },
      { type: "text", content: "山寺の石段は小学生でも登れるが、下り優先の登り方を守ることと、行動食（さくらんぼゼリーなど）を持参することを推奨する。登り切った五大堂の展望台で達成感を共有した後、麓の茶屋でかき氷を食べる流れが子どもの記憶に残る。往復約2時間。" },
      { type: "heading", content: "3日目：蔵王温泉のプールと温泉", level: 2 },
      { type: "text", content: "蔵王温泉のスキー場エリアには夏季にジップラインやアスレチック施設が開設される。温泉硫黄成分は子どもの皮膚に刺激がある場合があるため、薄めた浴槽がある共同浴場を選ぶと安心だ。帰りの新幹線で購入する板そば（山形名物）の持ち帰り土産を子どもに選ばせると旅の最後が盛り上がる。" },
    ],
    relatedArticleSlugs: ["yamagata-summer-cherry", "yamagata-zao-onsen-winter"],
  },
  // ── 11 ──────────────────────────────────────
  {
    slug: "yamagata-imonikai-guide",
    title: "山形の芋煮──最上川河原で行われる日本最大の鍋パーティーを体験する",
    description: "毎年9月、山形市の最上川河原に3万人が集まり芋煮を食べる。里芋と牛肉の醤油鍋文化。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-08-20",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "yamagata",
    tags: ["芋煮", "芋煮会", "山形名物", "鍋", "最上川"],
    spotIds: ["yamadera"],
    sections: [
      { type: "heading", content: "芋煮会とは何か──山形の秋の風物詩", level: 2 },
      { type: "text", content: "芋煮会は秋（9〜10月）に最上川などの河原でグループが集まり、里芋・牛肉・こんにゃく・ネギを醤油ベースで煮る野外鍋パーティーだ。山形では芋煮会が秋の行事として日常化しており、友人・職場・学校のグループが週末に河原でガス台と大鍋を持ち込む光景が当たり前だ。" },
      { type: "heading", content: "9月第1日曜の「日本一の芋煮会」", level: 2 },
      { type: "text", content: "山形市の「日本一の芋煮会フェスティバル」では6mの巨大鍋（重機で掻き回す）で3万食の芋煮を作り、来場者に提供する。参加費は1杯500円程度で、山形市内からシャトルバスが運行される。全国・海外からも観光客が訪れる秋の最大イベントだ。" },
      { type: "heading", content: "山形の芋煮と宮城の芋煮──地域差", level: 2 },
      { type: "text", content: "山形の芋煮は牛肉×醤油が基本（内陸文化）だが、宮城の芋煮は豚肉×味噌が主流だ。同じ「芋煮」でも県をまたぐと全く別の料理になる。山形旅行中に両方食べ比べる「芋煮格差体験」は食文化理解の近道だ。" },
    ],
    relatedArticleSlugs: ["yamagata-yonezawa-beef-guide", "yamagata-summer-cherry"],
  },
  // ── 12 ──────────────────────────────────────
  {
    slug: "yamagata-sake-and-soba",
    title: "山形の板そばと地酒──真っ白なそばと出羽桜・十四代の深い関係",
    description: "そば王国・山形は一人あたりそば消費量全国一位。板そばの食べ方と最高の地酒の選び方。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-10-15",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "yamagata",
    tags: ["板そば", "山形そば", "地酒", "十四代", "グルメ"],
    spotIds: ["yamadera"],
    sections: [
      { type: "heading", content: "山形の板そば──木箱に盛られた郷土の麺", level: 2 },
      { type: "text", content: "山形の「板そば」は木製の箱（板）にそばを盛る食べ方で、山間部の農山村文化に由来する。二八そばが多く、コシが強くて香りが高い。複数人でシェアしながら食べるスタイルが本来の形で、1枚（2〜3人前）を注文してひとつの板から分けて食べる。" },
      { type: "heading", content: "十四代──入手困難な日本酒界の頂点", level: 2 },
      { type: "text", content: "村山市の高木酒造が醸す「十四代」は全国の日本酒ランキングで常に上位を占め、定価で入手することはほぼ不可能だ。山形市内の一部居酒屋や日本酒専門店では、グラス（1,500〜3,000円）で提供していることがある。山形に来たら一度は試みる価値がある。" },
      { type: "heading", content: "出羽桜酒造の見学と試飲", level: 2 },
      { type: "text", content: "天童市の出羽桜酒造は見学（事前予約）を受け入れており、仕込み蔵の見学と試飲ができる。「出羽桜 桜花吟醸」は山形観光の定番土産で、全国の百貨店でも入手できるが蔵元での購入は特別感がある。板そばと出羽桜の組み合わせは山形の食文化の正解だ。" },
    ],
    relatedArticleSlugs: ["yamagata-yonezawa-beef-guide", "yamagata-imonikai-guide"],
  },
  // ── 13 ──────────────────────────────────────
  {
    slug: "yamagata-mogami-river-cruise",
    title: "最上川舟下り──芭蕉「五月雨を集めて早し最上川」を船上で追体験する",
    description: "奥の細道に登場する最上川を実際に下る舟旅。松尾芭蕉が見た川の速さは今も変わらない。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    publishedAt: "2025-05-12",
    author: "旅のしおり屋さん編集部",
    category: "model-course",
    prefectureId: "yamagata",
    tags: ["最上川", "舟下り", "松尾芭蕉", "奥の細道", "川旅"],
    spotIds: ["dewa-sanzan"],
    sections: [
      { type: "heading", content: "最上川舟下り──険しい峡谷を12kmで下る", level: 2 },
      { type: "text", content: "最上峡を下る舟下りは戸沢〜清川間（約12km、約1時間）で、川幅が狭まる峡谷区間が迫力満点だ。芭蕉が1689年に乗船した場所に近いルートで、船頭さんの民謡唄を聞きながら川の速さを体感できる。料金は大人2,500円前後。" },
      { type: "heading", content: "春（5月）と秋（10月）が最もおすすめ", level: 2 },
      { type: "text", content: "最上川舟下りは4月下旬〜11月が運航期間だ。5月は新緑が峡谷を覆い、川面に反射する緑が美しい。10月中旬〜下旬の紅葉期は特に人気が高く、週末の便は予約が必要になることもある。夏（7〜8月）は日差しが強いため帽子と日焼け止めが必須だ。" },
      { type: "heading", content: "庄内・鶴岡と組み合わせる旅程", level: 2 },
      { type: "text", content: "最上川の下流域にある庄内地方（鶴岡・酒田）は出羽三山の玄関口で、芭蕉も訪れた歴史がある。舟下り後に最上川を下って庄内平野へ抜け、鶴岡の加茂水族館（クラゲ展示世界一）を見てから酒田で海鮮を食べる1泊2日が、山形の多様性を体験できる旅程だ。" },
    ],
    relatedArticleSlugs: ["yamagata-yamadera-pilgrim", "yamagata-dewa-sanzan-pilgrim"],
  },
  // ── 14 ──────────────────────────────────────
  {
    slug: "yamagata-budget-trip",
    title: "山形を低コストで旅する──新幹線不要、高速バスと乗り合いで山形を制覇",
    description: "東京〜山形の高速バスは4,000円から。節約しながら銀山温泉まで到達する完全ガイド。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-04-05",
    author: "旅のしおり屋さん編集部",
    category: "budget",
    prefectureId: "yamagata",
    tags: ["節約", "山形", "格安旅行", "高速バス", "一人旅"],
    spotIds: ["yamadera", "ginzan-onsen"],
    sections: [
      { type: "heading", content: "東京〜山形 高速バスで4,000〜6,000円", level: 2 },
      { type: "text", content: "山交バスや国際興業バスが東京〜山形間に高速バスを運行（所要5時間程度）。新幹線（約2時間20分、12,000〜18,000円）の約3分の1の費用だ。夜行バスなら宿泊費も節約できる。山形バスターミナル着後、仙山線で山寺まで30分（440円）でアクセスできる。" },
      { type: "heading", content: "山寺は入山料300円のみ", level: 2 },
      { type: "text", content: "山寺の登山入山料は300円（2024年から値上がり）。往復の電車賃880円と昼食代1,000円を合わせても2,200円以下で山寺を完全体験できる。山形市内の「冷やしラーメン」発祥の店「栄屋本店」の冷やしラーメン（1,000円）は、節約旅でも外せないグルメだ。" },
      { type: "heading", content: "銀山温泉は素泊まり旅館を狙う", level: 2 },
      { type: "text", content: "銀山温泉の宿は2食付きが基本の高価格帯が多いが、素泊まりプランを提供する宿も存在する（1人8,000〜12,000円）。食事は温泉街の外れにある食堂や、バスで30分の尾花沢市内で取れば予算を大幅に圧縮できる。大石田駅からのバス往復1,000円も節約ポイントだ。" },
    ],
    relatedArticleSlugs: ["yamagata-yamadera-pilgrim", "yamagata-ginzan-onsen-summer"],
  },
  // ── 15 ──────────────────────────────────────
  {
    slug: "yamagata-winter-foods",
    title: "山形の冬食──芋煮・玉こんにゃく・どんがら汁で東北の冬を食で体感する",
    description: "山形の冬は食べ物が際立つ季節だ。雪の中で作られる発酵食品と鍋文化の全容。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-12-01",
    author: "旅のしおり屋さん編集部",
    category: "gourmet",
    prefectureId: "yamagata",
    tags: ["山形グルメ", "冬料理", "どんがら汁", "玉こんにゃく", "発酵食"],
    spotIds: ["ginzan-onsen"],
    sections: [
      { type: "heading", content: "どんがら汁──タラの骨ごと煮る庄内の冬味", level: 2 },
      { type: "text", content: "「どんがら汁」は冬に最上川から日本海に下るタラ（寒ダラ）の頭・内臓・白子・身を豆腐と豆乳で煮た庄内地方の郷土鍋だ。ぷるぷるの白子と濃厚な魚のスープが一体になった味は、他の地域では絶対に食べられない。1月〜2月の庄内の食堂で提供される。" },
      { type: "heading", content: "玉こんにゃく──山形の屋台の主役", level: 2 },
      { type: "text", content: "山形では球形のこんにゃくを醤油で煮た「玉こんにゃく」が屋台や道の駅の定番食だ。1串に3〜4個刺さって100〜150円という安さと、ピリ辛の醤油だしの染みた食感が老若男女に愛される。山寺の参道でも販売しており、石段前のエネルギー補給に最適だ。" },
      { type: "heading", content: "雪の下の野菜──冬を越した甘みの秘密", level: 2 },
      { type: "text", content: "山形の冬野菜は雪の断熱効果でゆっくりと成長し、デンプンが糖に変換されて甘みが増す。「雪の下にんじん」「雪中キャベツ」は東京の高級食材店でも扱うブランド野菜だが、産地の直売所では通常価格で手に入る。冬の山形旅では農産物直売所に必ず立ち寄ってほしい。" },
    ],
    relatedArticleSlugs: ["yamagata-ginzan-onsen-snow", "yamagata-imonikai-guide"],
  },
  // ── 16 ──────────────────────────────────────
  {
    slug: "yamagata-luxury-yamagata-stay",
    title: "山形最上の宿泊体験──銀山温泉の能登屋旅館と蔵王の高級宿を比較する",
    description: "山形を代表する二つの宿。重要文化財の木造建築と蔵王の展望風呂、どちらを選ぶか。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-11-20",
    author: "旅のしおり屋さん編集部",
    category: "luxury",
    prefectureId: "yamagata",
    tags: ["高級旅館", "山形", "銀山温泉", "蔵王", "贅沢"],
    spotIds: ["ginzan-onsen", "zao-onsen"],
    sections: [
      { type: "heading", content: "銀山温泉・能登屋旅館──登録有形文化財の4階建て木造旅館", level: 2 },
      { type: "text", content: "1921年創業の能登屋旅館は銀山川沿いに立つ4階建ての木造建築で、国の登録有形文化財だ。窓から見える温泉街の風景は日本の原風景を体現しており、廊下の軋む音と障子の質感が「本物の古旅館」を体感させてくれる。1人2食付きで30,000〜50,000円程度が相場だ。" },
      { type: "heading", content: "蔵王の高級旅館──山岳温泉と料理の贅沢", level: 2 },
      { type: "text", content: "蔵王温泉の高級旅館は、山岳眺望の露天風呂と山形の食材を活かした創作料理が売りだ。米沢牛のしゃぶしゃぶ、出羽三山の山菜、庄内の鮮魚──山形の全地域の食材が一晩の夕食に集まる贅沢は、山形の地理的多様性を食で理解する体験になる。" },
      { type: "heading", content: "どちらを選ぶか──スタイルの違い", level: 2 },
      { type: "text", content: "歴史的建築と大正ロマンを求めるなら銀山の能登屋旅館、スキー・樹氷と温泉の組み合わせなら蔵王の宿が最適だ。秋田の乳頭温泉との組み合わせで東北の高級宿を2泊巡る旅も、時間と予算に余裕があれば最高のプランになる。" },
    ],
    relatedArticleSlugs: ["yamagata-ginzan-onsen-snow", "yamagata-zao-onsen-winter"],
  },
  // ── 17 ──────────────────────────────────────
  {
    slug: "yamagata-tsuruoka-culture",
    title: "鶴岡の食文化都市──ユネスコ食文化創造都市、日本初の称号の意味",
    description: "精進料理・伝統野菜・出羽三山の食。鶴岡が世界に認められた「食」の多様性を体験する。",
    coverImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0え?w=1200&q=80",
    publishedAt: "2025-09-25",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "yamagata",
    tags: ["鶴岡", "食文化", "ユネスコ", "精進料理", "伝統野菜"],
    spotIds: ["dewa-sanzan"],
    sections: [
      { type: "heading", content: "なぜ鶴岡がユネスコ食文化創造都市か", level: 2 },
      { type: "text", content: "鶴岡市は2014年に日本初のユネスコ食文化創造都市に認定された。その根拠は、在来作物（50種類以上）・出羽三山の精進料理・庄内平野の農業文化・漁村の食文化が集積した稀有な食の多様性だ。「孟宗竹のタケノコ」「民田なす」「温海かぶ」など、鶴岡だけの伝統食材が今も生産されている。" },
      { type: "heading", content: "食文化拠点「鶴岡食文化市場FOODEVER」", level: 2 },
      { type: "text", content: "鶴岡駅前の「鶴岡食文化市場FOODEVER」は在来作物を使った料理を提供するレストランや、食材を販売するマルシェが集まる複合施設だ。「アル・ケッチャーノ」の奥田政行シェフ（鶴岡の食文化発信者として著名）の料理が食べられる系列店も入居している。" },
      { type: "heading", content: "出羽三山の精進料理に泊まりがけで挑む", level: 2 },
      { type: "text", content: "羽黒山山上の宿坊（斎館など）では、山の幸だけを使った精進料理に宿泊できる。山菜・豆腐・こんにゃくを丁寧に調理した一汁五菜は、肉食文化とは別の「食の哲学」を体で理解させてくれる。1泊2食付きで8,000〜15,000円程度から。" },
    ],
    relatedArticleSlugs: ["yamagata-dewa-sanzan-pilgrim", "yamagata-sake-and-soba"],
  },
  // ── 18 ──────────────────────────────────────
  {
    slug: "yamagata-autumn-foliage-tour",
    title: "山形の紅葉を追う──蔵王・山寺・銀山の紅葉前線を10月に追いかける",
    description: "山形は標高差があるため、10月だけで3つの紅葉名所の見頃が重なる稀な県だ。",
    coverImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    publishedAt: "2025-09-28",
    author: "旅のしおり屋さん編集部",
    category: "seasonal",
    prefectureId: "yamagata",
    tags: ["紅葉", "山形", "蔵王", "山寺", "銀山温泉"],
    spotIds: ["zao-onsen", "yamadera", "ginzan-onsen"],
    sections: [
      { type: "heading", content: "10月上旬：蔵王の高所から紅葉が始まる", level: 2 },
      { type: "text", content: "蔵王（標高1,500m以上）の紅葉は10月上旬に始まる。お釜周辺のナナカマドが真赤に色づき、残雪が微量に残る年は白・赤・青の三色が重なる贅沢な風景になる。蔵王エコーラインの走行中に左右が紅葉のトンネルになる区間が特に人気だ。" },
      { type: "heading", content: "10月中旬：山寺の杉林と紅葉の共演", level: 2 },
      { type: "text", content: "山寺（立石寺）の石段沿いの紅葉は10月中旬〜下旬が見頃だ。常緑の杉と紅葉する落葉樹が混在する参道の色彩は独特で、1,015段の石段が紅葉のトンネルに変わる。五大堂からの眺めは春と秋で全く異なる表情を持つ。" },
      { type: "heading", content: "10月下旬：銀山温泉の黄葉と大正建築", level: 2 },
      { type: "text", content: "銀山温泉の渓谷の紅葉は10月下旬が最盛期で、川沿いのイチョウと楓が黄橙色に染まる中に大正建築が佇む風景は山形の秋の極致だ。週末の宿泊予約は2〜3ヶ月前から埋まる。紅葉期は日帰り観光のバスツアーも多く、平日訪問のメリットが大きい。" },
    ],
    relatedArticleSlugs: ["yamagata-zao-summer-crater", "yamagata-ginzan-onsen-snow"],
  },
  // ── 19 ──────────────────────────────────────
  {
    slug: "yamagata-solo-onsen-retreat",
    title: "山形の温泉に一人で籠もる──蔵王・銀山・肘折で3日間の完全リセット",
    description: "スマートフォンを置いて山形の温泉に3日間だけ入り続ける。都市疲れへの処方箋。",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    publishedAt: "2025-03-20",
    author: "旅のしおり屋さん編集部",
    category: "solo",
    prefectureId: "yamagata",
    tags: ["一人旅", "温泉", "山形", "湯治", "リトリート"],
    spotIds: ["zao-onsen", "ginzan-onsen"],
    sections: [
      { type: "heading", content: "1日目：蔵王温泉で体を作り直す", level: 2 },
      { type: "text", content: "蔵王温泉の強酸性硫黄泉は殺菌・美肌効果が高く、1日3〜4回入浴すると肌が変わる実感がある。大露天風呂（入場600円）は混浴（タオル可）で開放的な空間だ。温泉街の共同浴場巡り（上湯・川原湯・下湯、各200円）で3種類の浴槽を試す。" },
      { type: "heading", content: "2日目：銀山温泉に移動してゆっくり過ごす", level: 2 },
      { type: "text", content: "蔵王から銀山温泉へは山形市経由で約2時間（バス＋電車＋バス）。銀山温泉では温泉以外に何もしないことを許容すること。本を持参して宿の縁側で読む午後は、都市では作れない時間の流れを体験できる。夜のガス燈点灯（17時〜）は何度見ても飽きない。" },
      { type: "heading", content: "3日目：肘折温泉──最深の秘湯で締める", level: 2 },
      { type: "text", content: "最上郡大蔵村の肘折温泉は山形の最奥の温泉郷だ。毎朝6時から始まる「肘折朝市」では地元農家の野菜・山菜・手作り惣菜が並び、湯治文化が今も生きている。黄土色のナトリウム泉は胃腸への効能で古くから知られ、長期湯治の旅館が今も現役で稼働している。" },
    ],
    relatedArticleSlugs: ["yamagata-ginzan-onsen-snow", "yamagata-zao-onsen-winter"],
  },
  // ── 20 ──────────────────────────────────────
  {
    slug: "yamagata-crafts-and-arts",
    title: "山形の工芸を買う──天童将棋駒・山形鋳物・樺細工の産地を巡る旅",
    description: "将棋駒のシェア90%を占める天童市と、鋳鉄文化が息づく山形市。工芸品の背景を知って買う。",
    coverImage: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=1200&q=80",
    publishedAt: "2025-04-28",
    author: "旅のしおり屋さん編集部",
    category: "tips",
    prefectureId: "yamagata",
    tags: ["天童将棋駒", "山形鋳物", "工芸", "産地巡り", "土産"],
    spotIds: ["yamadera"],
    sections: [
      { type: "heading", content: "天童市──全国将棋駒の90%が生まれる地", level: 2 },
      { type: "text", content: "天童市は国内将棋駒生産量の90%以上を占める産地だ。江戸時代に藩の財政難打開策として将棋駒製造を奨励したのが始まりで、今も職人が手彫りで駒を作る。「天童将棋駒工人展示館」では駒の製造工程が見学でき、1,000〜3,000円から職人手作りの駒が購入できる。" },
      { type: "heading", content: "山形鋳物──東北の鉄が生む美しい器", level: 2 },
      { type: "text", content: "山形市は平安時代から続く鋳物産地で、岩手の南部鉄器と並ぶ東北の鉄工芸文化を持つ。山形鋳物は薄肉軽量が特徴で、急須・風鈴・ぐい飲みなどが産地の工房や道の駅で販売されている。使うほど味が出る鉄の器は一生物の土産になる。" },
      { type: "heading", content: "山形の工芸巡りを旅程に組み込む方法", level: 2 },
      { type: "text", content: "天童市（将棋駒）→山形市（鋳物・紅花染め）→角館（樺細工、秋田）という東北工芸ルートは、1泊2日から組めるユニークな旅程だ。工芸品は重くなるため最終日に購入し、宅配便で自宅へ送ることを前提にすれば荷物の心配がなくなる。" },
    ],
    relatedArticleSlugs: ["yamagata-sake-and-soba", "yamagata-yamadera-pilgrim"],
  },
];
